- WordPress/Classes/Stores/StatsPeriodStore.swift
- WordPress/Classes/ViewRelated/Stats/Charts/Charts+Support.swift
- WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
- WordPress/Classes/ViewRelated/Stats/Charts/PostChart.swift
- WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Ref #11876
Fixes #11888 
This change displays light grey bars when a chart view is empty. 
This also fixes an issue where chart Likes was not being updated after the Likes query finished.
To test:
---
Latest Post Summary chart:
- The empty view on this one is a bit hard to trigger.
- A site with views, but no views in the past 2 weeks.
- A site with no views, but has Likes or Comments.
- Verify light grey bars appear on the chart.
---
Period Overview chart:
- On a site with no Views, Visitors, Likes, and/or Comments for _all the periods_ on the chart.
- Verify light grey bars appear on the chart.
---
Post Stats chart:
- Access Post Stats for a site with no stats in the past 2 weeks.
- Verify light grey bars appear on the chart.
---
Chart Likes:
- On a site with Likes.
- Verify Likes …
> [Stats Refresh] Show grey bars when chart is empty

- WordPress/Classes/Services/PostService.m
Fixes #11897 
This issue was introduced with [this fix ](https://github.com/wordpress-mobile/WordPress-iOS/pull/11736)
Now we're only going to merge the revision back to the base post if its status is draft. Seems like a work around but I'm expecting this to be solved more elegantly with the implementation of the uplaod manager. 
To test:
1. Be offline
2.Edit a published post
3. Choose update
See a snack bar with "error occurred while saving" and the post content remains as is.
> Fixing an issue with post content disappearing on visible editor

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.h
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
- WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
- WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.h
- WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController+FeaturedImageUpload.swift
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Fixes #11433.
Before, trying to set a Featured image on a post while offline/on a slow connection, would throw up this ugly modal pop-up.
Now, it lets you pick an image and tries to upload it anyway — displaying a notice if it fails.
|before|after|
|---|---|
|![Simulator Screen Shot - iPhone Xs Max - 2019-06-12 at 05 40 33](https://user-images.githubusercontent.com/1594081/59322002-a32b7380-8cd4-11e9-966d-a09509cbe75a.png)|![Simulator Screen Shot - iPhone Xs Max - 2019-06-12 at 05 33 20](https://user-images.githubusercontent.com/1594081/59321854-f7822380-8cd3-11e9-9ec4-d010904fc07b.png)|
To test:
1. Put your device/sim offline.
2. Go to Posts
3. Open editor for any given Post
4. Go to Post Settings
5. Try to set a featured image
6. Verify that the app lets you try to do that, even when …
> Don't show blocking alert on set feature image

- WordPress/Classes/ViewRelated/Post/PostEditor.swift
PostEditorUtil is not present anymore. Instead we converted to PostEditor extensions
> Remove outdated comments in code.

- .circleci/config.yml
- Podfile
- Podfile.lock
- WordPress/WordPress.xcodeproj/project.pbxproj
This adds the necessary CircleCI config to run the full UI test suite every night.
It depends on the following open PRs:
- ~https://github.com/wordpress-mobile/circleci-orbs/pull/28~ Now merged.
- ~https://github.com/wordpress-mobile/WordPressMocks/pull/4~ Now merged.
To test:
There is not much you can do to test this apart from seeing that the UI tests pass on CircleCI: https://circleci.com/gh/wordpress-mobile/WordPress-iOS/8374.
> Run WordPressUITests nightly on CircleCI

- Podfile
- Podfile.lock
- Rakefile
This has two quick improvements to the mocks:
- Include @JavonDavis's changes for sign up (https://github.com/wordpress-mobile/WordPressMocks/pull/5).
- Make `rake mocks` work if you are using a local copy of `WordPressMocks` to make development easier.
To test:
- Run `rake mocks`.
- Run the UI tests to confirm they still pass.
> Update WordPressMocks to include sign up and make development easier

- WordPress/Classes/Services/PostService.m
Reverts #11736 (fac83ab447507b7fb9afb6f0e41e03ed8276bcf8) as it caused the Editor to discard the contents when pressing the _Update_ button while offline. This was found while finding the solution for #11905. 
The #11736 changes will have to be reverted for `develop` too. After that, we will find a way to fix it without causing the regression. 
1. While online, create a draft. Make sure the draft is uploaded to the server. 
2. Stay on the Post List and go offline. 
3. Edit the draft. Make some changes.
4. Click on the _Update_ button. The contents should not disappear.
Please also test other statuses like published or when online. 
There's another unrelated issue here. After exiting and retrying the upload, the Post List will not show the updated contents. However, after …
> Revert fix for Discard losing changes

- WordPress/Classes/Stores/StatsInsightsStore.swift
- WordPress/Classes/Stores/StatsPeriodStore.swift
- WordPress/Classes/ViewRelated/Stats/Helpers/SiteStatsInformation.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
- WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
- WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Fixes #n/a
This mainly just removes importing `WordPressComStatsiOS` in various new Stats files. It's not been used since `StatsServiceRemoteV2` was fully implemented.
I also made a minor change to the way `StatsServiceRemoteV2` is created for Insights. 
To test:
- Sanity check Insights, make sure the stats appear as expected.
> [Stats Refresh] remove references to old stats service

- WordPress/Classes/Services/PostService.m
Completely reverts the fixes for #11435. 
This reverts the PRs #11898 and #11736. They caused the Editor to discard the contents when pressing the Update button while offline, both for drafts and published posts. This was found while finding the solution for #11905.
The #11736 was already reverted for `release/12.6` in https://github.com/wordpress-mobile/WordPress-iOS/pull/11920.
As I commented in https://github.com/wordpress-mobile/WordPress-iOS/issues/11435#issuecomment-501859629, we still need to fix the #11435 issue but we should wait until the discussion in wordpress-mobile/WordPress-Android#9561 is finished so the iOS and Android solutions will match. 
1. While online, create a draft. Make sure the draft is uploaded to the server. 
2. Stay on the Post List and go offline. 
3. Edit …
> Revert fix for Discard losing changes in develop

- WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
Fixes #11922 
This fix the crash when the Stats section is selected and the device rotates.
This bug should affect all the devices where you have a single screen in portrait and a split view in landscape.
• Run the branch on and iPhone XR, X, 8 Plus, iPad
• Open Stats from a selected blog
• Rotate the device. It shouldn't crash.
• Change also period and rotate
> [Refresh Stats] Fix crash on rotation

- Podfile
- Podfile.lock
This version of WPMediaPicker brings the following features:
- User albums are sorted alphabetically 
- Fix a bug were the selection frame got the wrong size after rotating a device
- Make sure that asset previews are centered correctly
To test:
- Check if the features/fixes above are correct on the uses of the library.
- Smoke test other places where the library is used:
- Site icon picker
- User avatar picker
- Media Library insertion of media
- Editor insertion of media.
> Update version of WPMediaPicker to version 1.4.2

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
- WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Fixes #11904  
This updates Insights _Today_ to use the two-column stat card.
To test:
- On a site with no Today data, go to Insights _Today_.
- Verify `No data yet` is shown.
- On a site with Today data, go to Insights _Today_.
- Verify the data is shown in two columns.
> [Stats Refresh] Insights Today: update to new design

- RELEASE-NOTES.txt
- WordPress/Classes/Stores/StatsInsightsStore.swift
- WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
- WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.xib
- WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
- WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Ref #11908 
This is step one of adding a `View more` option to Insights _This Year_. The detail view shows the current year's data. 
Not done yet: showing a date bar, and displaying data for the selected year.
Also, there is a bug that's causing extra space above the first row. That's not new (it happens on Period _Published_ as well). I'll fix that separately.
To test:
- On a site with data for this year, go to Insights _This Year_.
- Verify the yearly data is shown.
> [Stats Refresh] Insights This Year: add `View more` details

- WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Fixes #n/a
Fixes a missing parameter when creating `TwoColumnStatsRow`. (caused by #11936 merge)
To test:
- Does the app build? 
> Fix missing argument

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Charts/Charts+LargeValueFormatter.swift
Fixes #11954.
The large value formatter for stats charts was failing in locales that format large numbers differently. This PR fixes the locale of the large value formatter's number formatter to `en-US`, so that this won't happen.
**To test:**
* In your Xcode scheme settings, set the app region to Sweden.
* Before this change, the stats charts will have y axis labels like `15x10^00`. After this, they should be formatted correctly (the example just given would be `15`).
> [Stats Refresh] Fix locale of large value formatter

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Charts/Charts+LargeValueFormatter.swift
Same as #11957, but targeting `release/12.7`.
> [Stats Refresh] Fix locale of large value formatter (12.7)

- WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.xib
Refs. #11852
This PR fixes the Countries map cell separator line. If the map is visible, the bottom separator line should have the same height of the default separator line.
• Select a site that contains data to display and select a stats period
• Scroll until the countries section is displayed and check the separator line between the map and the countries list. The separator height should be the same.
• Do the same test selecting a site with no data.
> [Stats Refresh] Countries section - fix map separator height

- WordPress/Launch Screen.storyboard
Fixes #11679 
This PR should fix the blue logo in the Launch Screen. I was bale to reproduce it sometimes running the app with the iPhone XR (XCode 10) and every time with XCode 11 (beta 1 & 2) and iPhone XR.
I followed the suggestion wrote by @jaclync and I set the tint colour to white.
- Run the branch on different devices like iPhone XR, 5, 5S with iOS 12
- Run the branch on different devices with iOS 13 
> [Fix] Launch Screen Blue Icon

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
- WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
This is a follow up to https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/103
Closes #11893 by adding the required documentation.
Since we're only adding comments, we only need to check the code still compiles.
1. Reinstall the pods.
2. Make sure the project builds correctly.
> Documents some critical stats we're tracking.

- WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
Fixes #11949 
This crash happened on iOS 11 only. Calling the `performBatch` while scrolling the tableview caused a crash in Stats periods and insights. `performBatch` should be called only when the row is touched.
- Run the branch on iOS 11
- Open Stats Insights and Period and scroll the overview.
- Expand and close the cells.
- Make the same test using a device with iOS 12 to make sure everything is working as expected.
> [Fix] Fix NSRangeException in Stats running on iOS 11

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
- WordPress/Classes/ViewRelated/Stats/Charts/PostChart.swift
- WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
Ref #11876
For empty charts, the grey bars are now the height of the chart.
To test:
---
Latest Post Summary chart:
- The empty view on this one is a bit hard to trigger.
- A site with views, but no views in the past 2 weeks.
- A site with no views, but has Likes or Comments.
- Verify grey bars extend the height of the chart.
---
Period Overview chart:
- On a site with no Views, Visitors, Likes, and/or Comments for _all the periods_ on the chart.
- Verify grey bars extend the height of the chart.
---
Post Stats chart:
- Access Post Stats for a site with no stats in the past 2 weeks.
- Verify grey bars extend the height of the chart.
> [Stats Refresh] Set empty chart bar height to chart height

- WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
This PR makes a few small improvements to VoiceOver support for StatsTotalRow and its container TopTotalsCell.
* StatsTotalRow should now read the name of the cell followed by the value, and if tappable state that it's a button and to tap for more detail.
* TopTotalsCell should read that it's a table, followed by the names of the columns.
For example:
* Tapping / selecting this entire table will read "Table showing Link and Clicks".
* Tapping the row shown on the screenshot will read "WordPress.com, 53. Button. Tap for more detail."
**To test:**
* Build and run and enable VoiceOver
* Navigate through a stats period screen and check that the rows are read correctly. 
There are user facing changes but as we're going to have a large dump of VoiceOver changes, let's just …
> [Stats Refresh] Some VoiceOver improvements for StatsTotalRow

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Related WordPressKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/163
Fixes #11952 
When we upload a post on a request to preview we call the uploadPost method in PostService. 
That call creates a remotePost in https://github.com/wordpress-mobile/WordPress-iOS/blob/e26bb0f8ba71e7650a4149b145748aca68e66d59/WordPress/Classes/Services/PostService.m#L720
When the site is self hosted updatePost in PostServiceRemoteXMLRPC is called and it returns a boolean. We then invoke a callback with the captured remote post (that has no URL).
In this PR
Pointing to WordPressKit release 4.2.0-beta.2. With this change, we are fetching the post after it's update like we do in createPost so the returned post should contain a url (permalink)
To test:
1. Select a self-hosted site in the app.
2. …
> Fetching a post after update

- RELEASE-NOTES.txt
- WordPress/Classes/Stores/StatsInsightsStore.swift
- WordPress/Classes/Stores/StatsPeriodStore.swift
Fixes #11983 
To test:
- Go to Stats Insights.
- Pull to refresh.
- Verify the stats are not cleared, and the table continues to show data. (See #11983 for example of what it should _not_ do.)
> [Stats Refresh] Save Insights overview to Core Data when refreshed.

- WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
Fixes #11979
To test:
- Go to all stats views (Insights, Period, Post Stats, details).
- Verify the card subtitles are now normal case.
Examples:
> [Stats Refresh] Change stat card subtitles to be normal case.

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Helpers/StatsPeriodHelper.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
(Same as #11980 but targeting 12.7)
Fixes #11976. This PR updates the color of the difference value in stats to grey to de-emphasize how positive / negative the change is.
**To test:**
* Build and run, check the appearance of the difference label
> [Stats Refresh] Change stats difference value to grey colour (12.7)

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
Fixes #11775
Ref #11908
This adds analytics tracks for:
- Insights _This Year_ `View more`.
- Date Bar: tapping backward and forward. Includes the selected period in the event properties.
- Period Overview chart: selecting filter bar tabs _Views_, _Visitors_, _Likes_, and _Comments_. Includes the selected period event properties.
NOTE: Accompanying Shared PR: https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/210
To test:
- Go to Insights _This Year_ `View more`. Verify the action is tracked.
```
🔵 Tracked: stats_this_year_view_more_tapped, properties: {
"blog_id" = <id>;
}
```
- Go to any period and change the date via the Date Bar. Verify the actions are tracked.
```
🔵 Tracked: stats_date_tapped_backward, properties: {
"blog_id" = <id>;
period = day;
}
```
```
🔵 Tracked: …
```
> [Stats Refresh] add new analytics tracks

- RELEASE-NOTES.txt
https://github.com/wordpress-mobile/WordPress-iOS/pull/11985 updated release notes for 12.7
> Remove release note from 12.8 as it was fixed in 12.7

- WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/StatsNoDataRow.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/ViewMoreRow.swift
Refs. #11995 
This PR is a first part of the accessibility improvements:
- View More rows
- No data rows
- Reflect expanded / collapsed state of expandable rows
- If the table header is empty the element is not accessible
- Enable Accessibility -> VoiceOver
- Select a site and open Stats
- Try to tap on the grey spacer row below date bar (is not inspectable anymore)
- Tap on a View More row
- Tap on a collapsed/expanded row
> [Stats Refresh] Improve accessibility

- WordPress/WordPressUITests/Flows/LoginFlow.swift
- WordPress/WordPressUITests/Screens/BaseScreen.swift
- WordPress/WordPressUITests/Screens/Editor/AztecEditorScreen.swift
- WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
- WordPress/WordPressUITests/Tests/EditorAztecTests.swift
- WordPress/WordPressUITests/Tests/EditorGutenbergTests.swift
- WordPress/WordPressUITests/Tests/LoginTests.swift
- WordPress/WordPressUITests/Tests/MainNavigationTests.swift
- WordPress/WordPressUITests/Tests/SignupTests.swift
- WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
This PR improves some of the UI test output, to help us better understand some flaky test failures we have seen in recent test runs:
* When a UI test fails, we'll take a screenshot after the failure. That way we can see the state of the app when it fails.
* It [groups some test steps](https://developer.apple.com/documentation/xctest/activities_and_attachments/grouping_tests_into_substeps_with_activities) into named activities, to clarify in the logs what step we're at in the test and why certain actions are being taken.
To test:
* Start the mocking server with `rake mocks`.
* Open the simulator.
* Run the UI tests in the `WordPressUITests` target. In the test logs, confirm you see the new named activities as expected.
* Force a test to fail (e.g. remove one of the test steps and re-run …
> Improve UI test output (logs and screenshots)

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
Fixes #11966 
To test:
- On iOS 11, go to Stats > any period.
- On the Overview chart, verify the _Visitors_ legend is on top of the y-axis.
- Verify iOS 12 still works as expected.
> [Stats Refresh] Fix chart legend location

- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
This PR removes an extra track of the event `editor_session_end` on save/update posts.
As showed [in this comment](https://github.com/wordpress-mobile/WordPress-Android/issues/10098#issuecomment-505755839), this event was being double tracked on save/update events.
This event is already properly tracked for all interactions here:
https://github.com/wordpress-mobile/WordPress-iOS/blob/c504303b0962001b8f77fbb3cf071e633e908b26/WordPress/Classes/ViewRelated/Post/PostEditor%2BPublish.swift#L92
To test:
Even though this should only affect save/update actions, to be sure let's check that in all possible editor closing actions, `editor_session_end` is tracked only once.
**Tip:** To clear the console: 
- Activate the `OS_ACTIVITY_MODE: disable` environment variable in the Run scheme editor.
- On …
> Remove extra editor_session_end tracks event

- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
Refs. #11955 
This PR adds the accessibility labels in the Period Bar
• Switch on the VoiceOver
• Open Stats from a selected site
• Inspect the period bar tapping the current date and the back/forward arrows
> [Stats Refresh] Accessibility labels in Period Bar

- .circleci/config.yml
This adds failure notifications to the A8C Slack when the UI tests fail on CircleCI. They go to the `#ios-osx-dev` channel. We can move them somewhere else if needed. Here is what it looks like:
Related: https://github.com/wordpress-mobile/WordPress-Android/pull/10116
> Add Slack notifications to CircleCI UI tests

- WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.swift
Fixes #n/a
With #11964, the details table no longer updated as it was calling a delegate method that changed. The result was rows didn't expand and child rows were not shown.
This restores the table update by calling the new delegate method.
To note, this also restores all chevrons updating when a row is expanded, but hey at least they expand.
To test:
- Go to any details view that has expandable rows. 
- Expand a row.
- Verify child rows appear.
> [Stats Refresh] Stats details: fix expanding rows

- WordPress/Classes/Extensions/WPStyleGuide+ApplicationStyles.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Refs #11683
Changes the icons on the Me tab to be `neutral` from the Muriel palette. Also changes the site details screen to match.
To test:
- look at Me tab and My Sites > details.
- observe that the icons have a better color
> Muriel colors: fix the dang blue icons on Me tab

- WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.swift
Fixes #12019.
This fixes an issue with cell reuse in Custom Domains, when some cells would incorrectly get their `UITextField`s disabled.
1. Go to PluginViewModel.swift, and on line 178 add:
```
self.presentDomainRegistration(for: directoryEntry)
return
```
1. Go to Plugin section in app on site that has them enabled (AT/Biz plan site)
1. Go to any plugin that isn't yet installed on the site
1. Try to install it — the Custom Domain flow should pop up instead
1. Go to second page of Custom Domain flow, where you're asked to provide your data
1. Verify that you can select and input text into any text fields
> Fix issue where some cells in Custom Domains would become untappable

- Podfile
- Podfile.lock
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/12009.
To test:
Create a jurassic.ninja *non-JP* site
Log in to it in the app
Compose a new post
Set it to "private" in Post Settings
Verify that it Publishes correctly
(given last-minute status of it, I decided to omit a `RELEASE-NOTES.txt` mention)
> Fix for publishing private posts on XML-RPC sites

- WordPress/Classes/Extensions/UIColor+MurielColors.swift
- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
- WordPress/Classes/ViewRelated/Views/NoResults.storyboard
Refs #11683
This updates the FancyButtons to match the muriel colors.
| Flag Off/Old Colors | Flag On/Muriel |
| ---- | ---- |
| ![Simulator Screen Shot - iPhone Xʀ - 2019-06-27 at 15 29 18](https://user-images.githubusercontent.com/517257/60306629-c3267e00-98f5-11e9-88b4-429a633faba0.png) | ![Simulator Screen Shot - iPhone Xʀ - 2019-06-27 at 15 23 37](https://user-images.githubusercontent.com/517257/60306640-cb7eb900-98f5-11e9-8315-7f1328cc390a.png) |
**Note:** The secondary colors were so similar between the two, I didn't have to add new semantic colors for them. But since the primary is blue vs. pink, I did for those.
To test:
- Check out the login epilogue screen
- And a `no results view`
- Also a FancyAlert, like when you login for the first time on a fresh install
- Ensure the …
> Muriel Colors: update FancyButtons

- WordPress/Launch Screen.storyboard
This PR updates the launch screen to use a Blue-500 background. It seemed like it would be difficult to feature flag this, and I figured it wasn't necessary as the feature flag is already open to everyone and it's an easy revert.
**To test:**
* Build and run, and check the launch screen uses a darker blue (Blue-500)
> Change launch screen background to Blue-500

- WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
Fixes #12035 
This PR fixes the color used by the Period Chart legend.
(Pictures on the left: without Muriel colors)
• Open stats form a selected site
• Select a DWMY period
• The Period Chart legend should use the `primaryDark` color
> [Stats Refresh] Use primary dark as legend color

- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Instead of relying on the default description of the properties dictionary, use a custom transformation so it all fits in one line.
While reviewing #12005, there were some instructions to try to tame all the noise in the console when debugging tracks events. A better approach could be to use the search function in the Xcode console and filter lines with `🔵` or `Tracked:`. However, since we print event properties across several lines, they would get lost in the filter.
So instead of this...
```
🔵 Tracked: editor_session_end, properties: {
"blog_type" = jetpack;
"content_type" = new;
editor = gutenberg;
"has_unsupported_blocks" = 0;
outcome = cancel;
"post_type" = post;
"session_id" = "B8CF1CB8-31B5-4716-879C-DD5A559ED7F3";
}
```
...we are logging like this...
```
🔵 Tracked: …
```
> Improve logging of tracks events

- WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartConfiguration.swift
- WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
Fixes #12037 
This is an _hotfix_ and it fixes a problem when a user is trying to change a period selecting the chart bar.
I saw the delegate injected in the Chart View was nil. I think this is caused by the element passed trough the configuration object. This is owned by the function scope, which means it will be released when the function returns. Injecting the delegate reference in the view init fixes the problem.
• Open Stats and select one of the period DWMY
• Tap the bars to change the date
• It should reload the data
> [Stats Refresh] Tapping Chart bars doesn't work

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
- WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
- WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
- WordPress/Classes/ViewRelated/Menus/MenusViewController.m
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
When displaying  NoResultsView due to no connection from post lists
we want to display a specific copy and a create post button.
Fixes #11997 
Before:
After:
To test:
1. Be offline
2. Go to Published or Drafts tab 
3. See the "no results view" with the right copy
4. See the "Create Post" button
5. Tap create post button
6. See that when exiting the editor or from the menu you have save as draft option
7. Tap save as draft
8. See the post was created as draft but fails to upload.
> Added Create Post button to empty results view displayed on no connectivity from post list

- WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyContentView.swift
Fixes #12046 
In the last step of the Site Creation flow, the preview is no longer being laid out behind the "Done" button.
Please test in both iPhone and iPad.
1. Go to the list of sites.
2. Create a new WP.com site.
3. Fill out all of the required information, and reach the last step (site preview).
4. Make sure you can scroll all the way down to the bottom of the site and that the site doesn't finish behind the "Done" button.
> Fixes an issue that was causing new site previews to show behind the "Done" button.

- Scripts/BuildPhases/AddVersionToIcons.sh
- WordPress/WordPress-Internal-Info.plist
- WordPress/Wordpress-Alpha-Info.plist
This PR fixes a couple of issues with the app icon for internal (and alpha) builds:
* Updated the icon versioning script to use the new `MurielImages.xcasset` asset catalog. Otherwise I was seeing an error on build.
* Adds the new alternate icons to the Internal and Alpha info plists. Otherwise they don't show up in the app.
**To test:**
* Do an internal build in Xcode, check there are no errors.
* Run the internal build (you can disable login if it's quicker by adding a `return` to the start of `showWelcomeScreenIfNeeded`). Go Me > App Settings > App Icon and check you can see the alternate icons and switch to one.
> Fix internal app icon issues

- WordPress/Classes/Stores/StatsPeriodStore.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Fixes #12048 
This PR fixes the delay caused when the chart bar is selected (only for cached data).
Also it introduces an improvement when the cache data is loaded at the beginning and a fix to avoid displaying an empty table if the overview is fetching and a new request is triggered.
- Select a site and open Stats
- Select one of the period DWMY
- Select different dates using the chart bars
- If the data is cached it should update the view immediately
> [Stats Refresh] Avoid delay when a chart bar is selected

- WordPress/Classes/ViewRelated/Blog/BlogDetailHeaderView.m
- WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
- WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
Fixes #11687 
This PR also fixes two issues that could cause the spotlight effect to never go away:
1. If we run the "Upload an Icon" tutorial multiple times in a row without ever tapping the icon.
2. If we run the "Upload an Icon" tutorial and then a different one without ever tapping on the icon.
1. Create a WP.com site.
2. When offered to, request assistance to set the site up.
3. Make sure the spotlight dot effect is visible when the "Upload an Icon" tutorial is running.
4. Try multiple combinations of running "Upload an Icon" tutorial multiple times in a row with and without tapping on the icon.  Make sure it behaves well.
5. Try multiple combinations of running "Upload an Icon" tutorial and other tutorials multiple times in a row with and without tapping on the icon.  Make sure it …
> Fixes an issue with the tour guide not initializing some values in time.

- .gitignore
- Scripts/BuildPhases/AddVersionToIcons.sh
- WordPress/WordPress.xcodeproj/project.pbxproj
Adds support for versioned alternate icons for internal builds.
**To Test:**
1) Check out this branch and run `bundle exec pod install`
2) In Xcode, select the "WordPress Internal" target, then the "Generic iOS Device"
3) Choose Product > Archive
4) Once the build is complete, choose Window > Organizer > WordPress Internal. Right-click on the latest archive, and choose "Show in Finder". Right click on the `xcarchive`, and choose "Show Package Contents". Navigate to Products > Applications > WordPress. Right click on the app and choose "Show Package Contents".
5) Verify that all of the `.png` icon files have the right version number. 
6) Back in Xcode, select the "WordPress" target, then the "Generic iOS Device"
7) Choose Product > Archive
8) Once the build is complete, choose Window > …
> Add support for versioned alternate icons

- WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
Refs. #11852
This PR removes the possibility to deselect a selected chart bar. Unfortunately there's no property to enable/disable this feature and there's no public method to override the behaviour.
For this reason I replaced the default tap gesture implementing a new one owned by the `StatsBarChartView` itself.
- Open a DWMY period and select a date from the chart
- Try to tap on the same bar verifying the bar is not deselected
> [Stats Refresh] Avoid deselect action when a chart bar is selected

- WordPress/Classes/Services/KeyValueDatabase.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+InformativeDialog.swift
- WordPress/WordPressTest/GutenbergInformativeDialogTests.swift
- WordPress/WordPressTest/NullMockUserDefaults.swift
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1186
This PR flips the "default for new posts" switch to true the first time the block editor is launched, if the switch is off.
The alert text was changed to match https://github.com/wordpress-mobile/gutenberg-mobile/issues/1186#issuecomment-508231868
The logic is:
- The alert will be shown if:
- The Gutenberg default switch is off
- The post has gutenberg blocks
- Is first time opening a gutenberg post
When the alert is shown, we automatically flip the switch located in App Settings.
This will trigger the tracks event `AppSettingsGutenbergEnabled` but I'd say that it is still desirable, unless we want a new tracks event for this particular case?
I'm unsure if we should add this to the release notes.
**To test:**
- Set …
> Default to Gutenberg upon opening a block based post

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Closes part of #11846. 
When a media upload fails and the upload is retried, the error label “Failed to insert media” never disappears even if the retry succeeded. This covers this scenario by clearing the error label when an upload is started or restarted.
| ![old](https://user-images.githubusercontent.com/198826/60619996-4123d280-9d97-11e9-9168-0ea9b9a0044b.gif)       |   ![new](https://user-images.githubusercontent.com/198826/60620003-441ec300-9d97-11e9-96d5-8cd0fceae401.gif)    |
1. Go offline.
2. Create a post and add an image. Do not leave the editor. 
3. Go online. The image upload should be restarted. 
Confirm that the error label is no longer shown.
> Aztec Media: Clear existing errors when restarting

- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressUITests/README.md
This adds a README to the repo (under `WordPress/WordPressUITests/`) with documentation for running the UI tests, adding a test, and adding/updating the network mocks.
**To review:**
* You can view the README here: https://github.com/wordpress-mobile/WordPress-iOS/tree/add/ui-tests-readme/WordPress/WordPressUITests
* In addition to proofreading, please let me know if there's anything you think we should add, clarify, or remove here.
> Add README with UI test documentation

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
Fixes #12072 
This fixes an issue where on rotation the Period details views would revert to showing only 10 rows.
The issue was caused by Period being refreshed via `viewWillTransition` in `SiteStatsDashboardViewController`, resulting in the data to be overwritten in `StatsPeriodStore`.
This changes Period to only refresh data if the view is visible. 
To note, the original issue specifically states Posts and Pages, but it actually affected _all_ Period details.
To test:
- On a site with a lot of data (so you get more than 10 detail data rows), go to Period, and select `View more` for any stat.
- Verify all the data is shown (i.e. is not limited to 10 rows).
> [Stats Refresh] Period details: Show all data on rotation

- WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
Fixes #11978 
This changes the Latest Post Summary chart height to be the same as the Overview charts, which is 150.
To test:
- Go to Insights > Latest Post Summary.
- Verify the height of the chart area is 150.
> [Stats Refresh] Change Latest Post Summary chart height

- WordPress/Classes/ViewRelated/Stats/Helpers/StatsPeriodHelper.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
Ref #11962, #12043
This fixes the date bar on Insights Annual details view that was broken when 12.7 was merged to `develop`. An attempt was made to fix it on #12043 but it wasn't quite right.
To test:
- Follow the steps noted on #11962 .
- Specifically what was broken - `mostRecentDate` is used to prevent the date bar from going past the site's most recent year. For example, on a site with no date for 2019, we don't want to use `Date()` for the current date as that will result in a broken view. So, on a site with no data for 2019:
- Go to Insights > This Year > View more.
- Verify the date bar only goes up to the year the site has data for.
> [Stats Refresh] Fix Insights Annual details date bar

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
- WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
- WordPress/Classes/ViewRelated/Views/LoadingStatusView.swift
- WordPress/Classes/ViewRelated/Views/LocadingStatusView.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #11812 
As described in the issue when saving a draft or autosaving a post before preview we used to show a blocking spinner which would block the user from performing any actions till preview is generated. 
This issue is prominent in low connectivity.
This PR aims to improve the experience by showing the saving/generating status in the navigation bar the same way we do when uploading media. 
**This improvement brings up the need to also remove the blocking spinner when loading the preview (web view loading). It will be tackled in a separate [PR](https://github.com/wordpress-mobile/WordPress-iOS/issues/12032)**
To test:
1. Go to device settings -> Developer and turn on Network Link Conditioner with "Very Bad Network"
POSTS:
2. Open the app and go to published posts
3. Update a post …
> remove blocking spinner on upload and autosave before preview 

- WordPress/Classes/Extensions/UIColor+MurielColors.swift
- WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityDay.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityLegend.swift
Refs. #11852 
This PR updates the colors used in _Insights -> Posting Activity_
**Left Image:** _Old colors_    |    **Right Image:** _New colors_
- Select a site with some Posting activity
- Open Stats -> Insights and scroll until Posting activity is displayed
> [Stats Refresh] Update Insights Posting activity colors

- WordPress/Classes/Extensions/AbstractPost+PostInformation.swift
- WordPress/Classes/Models/AbstractPost.h
- WordPress/Classes/Models/AbstractPost.m
- WordPress/Classes/Services/PostService.m
- WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
Fixes #12100 
Changes:
- Renames `isDraft()` to `originalIsDraft()` since it better represents what that method was doing.
- Introduces a new `isDraft()` method, which is used to fix part of the preview issues.
- Moves some code into the service layer, to make it part of the autosaving logic.
- The new logic prefers autosaving (over uploading) whenever possible.  Even for drafts.  This is much safer as it means it's much less likely that something will be saved by mistake during previews.
2. Type a title and some content
3. Don't save yet!  Tap "..." and then "Preview".
In a WP.com blog: Make sure the preview shows as expected.  The post should be saved as a draft.
In a self-hosted blog: Make sure the preview shows as expected.  The post should be saved as a draft.
1. …
> Fixes a bug that was causing previews to publish some posts.

- WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
- WordPress/Classes/ViewRelated/Post/PostCardCell.swift
- WordPress/Classes/ViewRelated/Post/PostCardCell.xib
- WordPress/Classes/ViewRelated/Post/PostCompactCell.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.swift
- WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.swift
This PR updates the new post list to use the new Muriel colors.
**To test:**
* Navigate to the post list and ensure nothing looks out of place – compare to standard screens like BlogDetailsViewController and MeViewController
* Try expanding and deleting cells
* Try deleting a post and checking the style of the 'restore' row
@mattmiklic here are some screenshots for you. I used `primary` for the upload progress bar instead of `accent`, as I figured it's not tappable. Let me know what you think.
> Post List: Update to Muriel color scheme

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+DomainCredit.swift
- WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
- WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
This PR tweaks a few color items before we cut our release. Most important is the update to unread notification backgrounds, which were very difficult to differentiate.
* Unread notification row background is now blue-0 instead of neutral-0
* Domain credit icon is now yellow-20 to make it lighter
* Reader separators are lighter as they were quite heavy previously and didn't match other areas of the app
**To test:**
* Build and run (or check the screenshots)
* Ensure the colors look okay and match the description above.
* To get the domain credit row to show, you can modify `configureTableViewData` in `BlogDetailsViewController`.
> Color tweaks: notifications unread color, domains credit icon, reader separators

- WordPress/Classes/System/WordPressAppDelegate+openURL.swift
- WordPress/Classes/Utility/Logging/LoggingURLRedactor.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/Logging/LoggingURLRedactorTests.swift
Fixes #12081
**To test:**
1) Checkout this branch, and run the app on a simulator.
2) Switch to Safari in the simulator.
3) In the address bar, type `wpdebug://magic-login?token=abc123`. Allow Safari to open WordPress.
4) In the Xcode log, search for "launched with", and note that the token is redacted.
5) Observe that the tests for this functionality pass.
**For Discussion**
I manually placed all of the URL schemes in the code. This could be adjusted to read the URL scheme out of `Info.plist`, but given that this code is on the critical path for launch, I wanted to avoid the additional IO. Happy to hear your thoughts.
> Add magic login token redaction

- WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
As part of the update done here: https://github.com/wordpress-mobile/WordPress-iOS/pull/12023
singularSubtitle is no longer used. 
This PR Removes the declaration of this variable
> Remove unused variable - singularSubtitle

- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/Aztec/AztecPostViewControllerAttachmentTests.swift
Closes #11846.  
This adds simple tests for the code that was added in #12058. 
Running the new test class, `AztecPostViewControllerAttachmentTests`, should be enough.
> Add tests for media upload restart handling

- WordPress/Launch Screen.storyboard
We noticed that the released version of 12.8 wasn't showing a launch screen for fresh installs of the app (users would just see black until the app loads). This PR fixes that by updating the background color of the launch image storyboard. It was still referencing an old asset color that no longer exists:
I've updated it to use `WordPress-50`. cc @nheagy 
**To test:**
* Build and run a fresh install (simulator is fine).
* Check you see the launch image when the app launches
> [Hotfix] Fix launch image background color

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Fixes #n/a
The WPKit PR (https://github.com/wordpress-mobile/WordPressKit-iOS/pull/169) fixes issues where parsing Insights json would fail if any piece of data was missing. 
I noticed the issue for these stats:
- This Year
- Most Popular
- Posting Activity
I didn't actually see these stats fail, but I did apply the same fix here as well:
- All Time
- Today
To test:
- On a site with very little data (but not _no_ data), go to Insights.
- For the stats listed above, verify they appear if they have data (can be verified in Calypso).
> [Stats Refresh] Insights: fix missing stats

- WordPress/Classes/ViewRelated/Post/Revisions/Browser/Preview/RevisionPreviewViewController.swift
- WordPress/Classes/ViewRelated/Post/Revisions/Browser/Revisions.storyboard
Fixes #11999 
This PR fixes the layout used by the Revision diffs view, using a readable width when the device is an iPad. It also fixes the bottom navigation button alignment.
• Open a _post/page_ with multiple revisions
• Tap on `•••` to open menu
• Tap on History to open _History/Revisions_ viewer
• In History/Revisions viewer, tap `•••`, to switch between _HTML/Visual_ modes
> Use readable content in Revision diffs

- Gemfile.lock
- Scripts/fastlane/Pluginfile
This PR updates `Pluginfile` to handle the changes in https://github.com/wordpress-mobile/release-toolkit/pull/60. 
`RMagick` is not a default dependency for `release-toolkit`, so this PR adds it as an optional one to be installed when the promo screenshot feature is required. 
1. Run `bundle install --without screenshots` and verify that RMagick is not installed. 
2. Run `bundle install` and verify that RMagick is not installed. 
3. Run `bundle install --with screenshots` and verify that RMagick is installed. 
> Update release-toolkit and its dependency scheme

- WordPress/Classes/Extensions/UIColor+MurielColors.swift
- WordPress/Classes/Extensions/WPStyleGuide+ApplicationStyles.swift
- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Blog.swift
- WordPress/Classes/ViewRelated/Media/CircularProgressView.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Reply.swift
- WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.swift
- WordPress/Classes/ViewRelated/Reader/ReaderBlockedSiteCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderGapMarkerCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderListStreamHeader.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSearchSuggestionsViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
- WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.swift
- WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
- WordPress/Classes/ViewRelated/Themes/WPStyleGuide+Themes.swift
- WordPress/WordPressDraftActionExtension/MainDraftActionViewController.swift
- WordPress/WordPressShareExtension/MainShareViewController.swift
- WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
This PR just adds a new `tableBackground` semantic color to the Muriel palette, as we were referencing gray-0 all over the place. This should make it simpler if ever we need to update it in future.
**To test:**
* Check the code
* Build and run and check backgrounds look okay!
> Muriel: Add a `tableBackground` semantic color

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
- WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift
- WordPress/WordPressTest/Analytics/EditorAnalytics/PostEditorAnalyticsSessionTests.swift
WPiOS side of https://github.com/wordpress-mobile/gutenberg-mobile/issues/1174
Analog of Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10237
**UPDATE:**
The new property has been added just to EDITOR_SESSION_START event.
**Old description:**
A new property unsupported_blocks is added to the EDITOR_SESSION_* events, and it does hold the list of unsupported blocks found in the post.
**Note:**
Since the unsupported blocks list is stored at the beginning of the editor session, subsequent editions to the post won't affect this property.
If the user remove all blocks, then save and close the post, tracks will still track the original list of unsupported blocks. and also track: `has_gutenberg_blocks: 0` creating an inconsistency.
Talking with @daniloercoli , on Android …
> [Gutenberg] - Send unsupported blocks list to Tracks

- WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
Fixes #12158
This PR adds the jetpack error name and the site URL as properties when the Jetpack Install fails.
If we want more info from the error we get from the API response we need to update WP Kit as well.
- Try to install Jetpack on a website that might fail (Use a slow connection profile to generate a timeout)
> [Jetpack Remote Install] Add more info in analytics failure event 

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.m
- WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Refs #11683.
This PR makes some changes to the Reader to handle the new color palette. The largest change is improving consistency between all the different places action buttons appear (comment, like, save for later, etc).
---
**To test**
Updated Reader comments view header to match comments in the [master issue](#11683). Navigate to a post in the Reader, and then click the comments button:
* The border below this header should be neutral-5.
* The “Comment on…” text should be neutral-50.
* The “Weekly hangout” text can be the default text color.
---
Reader action buttons should now be consistent. Resolves these issues from the [master issue](#11683):
* Number of likes button text in Reader comments is still orange
* Likes star color in Reader comments view should match reader post list …
> Color schemes: Improve Reader colors to match new palette

- WordPress/Classes/Stores/StatsInsightsStore.swift
- WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
- WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Refs. #12146
This is a light PR that improves the Insights Store and the Insights View Model.
The biggest changes are:
- Hide the store removing all the other references to it and leave the ViewModel to bind the view
- Remove the PeriodStore reference and fetch the last posts directly in the Insights Store. 
The PR also fixes a small problem I saw when the pull to refresh is triggered.
@ScoutHarris I would merge this after #12159 
- Open Stats -> Insights and check everything works as before
> [Stats Refresh] Improve Insights Store

- MIGRATIONS.md
- Podfile
- Podfile.lock
- WordPress/Classes/Models/Blog+Editor.swift
- WordPress/Classes/Models/Blog.h
- WordPress/Classes/Models/Blog.m
- WordPress/Classes/Services/BlogService.m
- WordPress/Classes/Services/EditorSettingsService.swift
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/Utility/Editor/EditorFactory.swift
- WordPress/Classes/Utility/Editor/GutenbergSettings.swift
- WordPress/Classes/Utility/ZendeskUtils.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
- WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 88.xcdatamodel/contents
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/GutenbergSettingsTests.swift
This PR is a work-in-progress, targeting a feature branch to implement https://github.com/wordpress-mobile/gutenberg-mobile/issues/1233
This PR adds `mobileEditor` and `webEditor` to the Blog model, and are synchronized with the server.
Related `WordPressKit` PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/166 
The editor selection setting is now per site, but the switch is still App-wide, so (just for now), changing the `Use Block Editor` switch will iterate through all the user's blogs and set the appropriate value. This will change when we merge https://github.com/wordpress-mobile/WordPress-iOS/pull/12166, that move the switch UI to the Site Settings section.
**Note:** As mentioned on https://github.com/wordpress-mobile/gutenberg-mobile/issues/1233:
> Check the values of …
> [Gutenberg] Sync editor setting per site

- WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.swift
Fixes #11602 
This PR fixes the margins then the table is extended on either side. The table view cell background view extends fully to the edges but the content view is inset to stay within the safe area. To fix it then I set the white background only for the cell contentView, setting the cell background view color equal to the table view background color.
- Open Stats for a site with data
- Open Post Stats table view
- Check the tableview margins in landscape
> [Stats Refresh] Post Stats cells background view

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
Fixes #12157 
To test:
- Access Post Stats for a post with little data the past two weeks.
- Verify the back button on the date bar no longer goes prior to the earliest date available.
> Stats: Post Stats: restrict date bar back button to data available.

- WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.xib
- WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
Fixes #12152 
The stat separator lines are now scaled according to the device (as we do other lines).
To test:
- Run the app on devices of different [scale](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/image-size-and-resolution/).
- Verify the top and bottom lines on stat cards scale accordingly. Ex:
- iPhone XS: lines are .33pt.
- iPhone XR: lines are .5pt.
> Stats: fix card border heights

- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.xib
Fixes #12080 
To test:
- Go to a view with a date bar.
- Verify the back and forward buttons are bigger, making them easier to tap.
Before:
After:
> Stats date bar: increase back and forward button sizes

- Podfile
- Podfile.lock
- WordPress/Classes/Models/Notifications/Actions/ApproveComment.swift
- WordPress/Classes/Models/Notifications/Actions/EditComment.swift
- WordPress/Classes/Models/Notifications/Actions/Follow.swift
- WordPress/Classes/Models/Notifications/Actions/LikeComment.swift
- WordPress/Classes/Models/Notifications/Actions/LikePost.swift
- WordPress/Classes/Models/Notifications/Actions/MarkAsSpam.swift
- WordPress/Classes/Models/Notifications/Actions/NotificationAction.swift
- WordPress/Classes/Models/Notifications/Actions/ReplyToComment.swift
- WordPress/Classes/Models/Notifications/Actions/TrashComment.swift
- WordPress/Classes/Utility/FormattableContent/Actions/FormattableContentActionCommand.swift
- WordPress/Classes/Utility/WPTableViewHandler.h
- WordPress/Classes/Utility/WPTableViewHandler.m
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift
- WordPress/WordPressTest/ApproveCommentActionTests.swift
- WordPress/WordPressTest/EditCommentActionTests.swift
- WordPress/WordPressTest/LikeCommentActionTests.swift
- WordPress/WordPressTest/MarkAsSpamActionTests.swift
- WordPress/WordPressTest/ReplyToCommentActionTests.swift
- WordPress/WordPressTest/TrashCommentActionTests.swift
Now that we've bumped our base SDK up to iOS 11, we can drop MGSwipeTableCell and use native UISwipeActions instead. This PR does just that. Apologies that it's a little long, but the majority of the changes are just cookie cutter across the different types of notifications and their tests.
A few notes:
* I was kind of confused by our existing setup for these actions. From what I can tell, every notification action type (such as Like Comment, Like Post, Reply, Spam) implemented a method returning a button, but it seems as though we were only using Approve and Trash (and mark as read, but that's separate). I've implemented contextual actions for all of them for consistency, but I'm not sure they're all needed right now. When testing, please ensure the actions still show up in places like …
> Implement UISwipeActions / Remove MGSwipeTableCell

- WordPress/Classes/Utility/PushNotificationsManager.swift
Fixes #12193 
It looks like the event `wpios_push_notification_received` stopped firing with v11.4. For more context, see p77Llu-cng-p2
This PR forces the PushNotificationsManager to fire the `wpios_push_notification_received` event, to partially undo the changes in PR #10551
To test:
- Trigger a push notification
- Check that the event `wpios_push_notification_received` is received in Tracks
> Submit Tracks event when receiving a push notification

- WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
Fixes #11824 
To test:
- Go to Period > Authors > View more.
- Expand an Author.
- Verify the child row height is approximately 44pt high (the rows are dynamic, but it should be close).
> Stats: fix Period Authors details expanded row height

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Jetpack/Install/Error/JetpackInstallError+Blocking.swift
- WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
- WordPress/Classes/ViewRelated/Jetpack/Install/View/State/JetpackRemoteInstallState.swift
Refs. #12138 
This PR adds more log info about the JRI error received.
New log example:
```
Jetpack Remote Install error for site SITE_URL – The request timed out. (-1001: unknown)
```
I will update the Podfile as soon [#171](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/171) is merged.
• Try to install Jetpack on a website that might fail (Use a slow connection profile to generate a timeout)
> [Jetpack] Jetpack Remote Install Error log

- WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
Refs #11919 
Just a small PR to fix two of the stats audit issues.
1. The latest post summary header was being prepared for voiceover after styles were applied. This meant the accessibility label was set to "LATEST POST SUMMARY" (uppercased), which was read as "Latest P O S T summary". I've changed to prepare the accessibility label before the uppercasing happens.
2. The "most popular time" entry in Insights was displaying a localised hour number, but this wasn't necessarily clear even for users without accessibility issues. And with Voiceover, hearing "Best hour 17" was perhaps even less clear. Even living in a country that typically uses the 24 hour clock, I wouldn't usually expect to see the hour number on its own. I changed this to use a format of "12-hour hour AM/PM" – this matches …
> Stats Voiceover Audit: Fixes most popular hour and latest post summary header

- WordPress/Classes/ViewRelated/Blog/BlogDetailHeaderView.m
Closes #12179, and closes #12180. 
This applies accessibility labels to the Site Page's icon, title, and domain. The title and domain are now considered as one and will be triggered if hovering over them and the icon. 
| Main | Site Icon |
| <img src="https://user-images.githubusercontent.com/198826/61750362-700fe180-ad62-11e9-9296-0df696e4b168.PNG" width="320"> |   <img src="https://user-images.githubusercontent.com/198826/61750296-3e971600-ad62-11e9-8bf2-84b4d69bde3c.PNG" width="320">   |
1. Navigate to a Site Page.
2. Turn on VoiceOver. 
3. Hover over the title, domain, and icon. The icon should be dictated as a button. 
This is my first time adding VoiceOver support so I'd be happy to hear your comments. 🙂 
> Make the Site header accessible

- WordPress/Classes/Utility/ZendeskUtils.swift
- WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Closes #12177.
This improves the accessibility of the Me → Help & Support page. 
| Where | What |
| <img src="https://user-images.githubusercontent.com/198826/61835270-3dd0b380-ae38-11e9-851e-f91219505c7f.PNG" width="240">       | 64af8f8  d752e17   The buttons _WordPress Help Center_, _Contact Us_, _My Tickets_, and _Contact Email_ are now dictated as "buttons". |
| <img src="https://user-images.githubusercontent.com/198826/61835289-4d4ffc80-ae38-11e9-8690-6b17e5eb02a9.PNG" width="240"> | eacb586 The message of the alert shown when pressing the _Contact Email_ is now dictated first. |
| <img src="https://user-images.githubusercontent.com/198826/61835288-4d4ffc80-ae38-11e9-9380-54e44f47fef2.PNG" width="240"> | b3aa0b5 Added labels to the text fields so the user can …
> Improve VoiceOver in Me → Help & Support page

- WordPress/Classes/Extensions/UIView+Borders.swift
- WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.swift
- WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.swift
- WordPress/Classes/ViewRelated/Reader/NewsCard.swift
- WordPress/Classes/ViewRelated/Reader/ReaderBlockedSiteCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesStreamHeader.swift
- WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesStreamHeader.xib
- WordPress/Classes/ViewRelated/Reader/ReaderListStreamHeader.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSavedPostUndoCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
- WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.swift
- WordPress/Classes/ViewRelated/System/Notices/NoticeView.swift
Fixes #12153, by reducing the width of the border on Reader cards.
**To test:**
* Build and run, and view a stream in the Reader
* Ensure that the cards have single pixel borders on both 2x and 3x screen types (e.g. iPhone XS and iPhone XS Max).
@etoledom, would you mind reviewing?
cc @mattmiklic 
(I didn't update release notes and I think it's so minor it can just be included in "Improved color scheme consistency" that I've added in another branch)
> Reader: Fix card borders to account for display scale

- WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
Fixes #12172 
This modifies the logic used to determine `relativeStringInPast` (used by Latest Post Summary and Followers).
- When a time falls into the `AndaHalf` categories, the time is now rounded accordingly.
- Ex: previously 1.75 days would display as "1 days". Now it displays as "2 days".
- 1 day and 1 hour are now displayed as "a day" and "an hour". 
- Previously, they would display as "1 days" and "1 hours".
- Updated month breakpoints to be more inline with Calypso.
To test:
- On sites with varying periods since the Latest Post Summary was published, go to Insights LPS.
- Verify the periods are as expected.
> Stats: adjust 'relativeStringInPast' logic

- WordPress/Classes/Services/PostCoordinator.swift
In this PR we're limiting auto-uploading of posts temporarily to new drafts or existing drafts that haven't changed status.
Make sure you comment these lines out, so that we can have a post in CoreData that failed to publish without its status being changed to draft.
https://github.com/wordpress-mobile/WordPress-iOS/blob/c8403092a99194637e7917c0f24ca16d27ba650b/WordPress/Classes/Services/PostService.m#L263-L266
Make sure you test this using a device, as the simulator seems to have some issues with reachability.
1. Go offline
2. Create a new post
3. Publish the post
4. Create a new draft
5. Save the draft
6. Make sure both are marked as failed.
7. Reconnect the device and make sure that the published post isn't uploaded, but the draft is.
> Limits auto-uploading temporarily.

- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.xib
Ref #12018, https://github.com/wordpress-mobile/WordPress-iOS/pull/12159#issuecomment-514607655
This changes the timezone font to `callout`, and adjusts the top/bottom margins accordingly so the date bar is 60pt high when the timezone is displayed.
To test:
- On a site where your local and the site timezones differ, go to a view with a date bar.
- Verify the height is 60pt.
- On a site where your local and the site timezones match, go to a view with a date bar.
- Verify the height is still 44pt.
> Stats date bar: update timezone font

- WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.xib
Fixes #11637 
To test:
- Access Post Stats for a post with a single line title.
- Verify the cell height is about 70pt.
- Verify there is less space around the title label.
- Access Post Stats for a post with a multi-line title.
- Verify it's still spaced properly.
> Post Stats header: fixed cell and label heights

- WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
Fixes #11743 
Since the whole detail view is refreshed when a row is expanded/collapsed, we need to know which row was selected. This adds a `detailRowDisclosureNeedsUpdating` property to `StatsDataHelper` to track that. 
When detail rows are recreated, only the disclosure icon for the row matching `detailRowDisclosureNeedsUpdating` is animated.
To test:
- Go to any detail view with expandable rows.
- Expand and collapse rows.
- Verify only the icon for the row selected is animated.
> Stats details expandable rows: only rotate disclosure icon on selected row 

- WordPress/Classes/ViewRelated/Stats/Helpers/StatsPeriodHelper.swift
Ref #12159 
Issues I noticed for sites with a timezone ahead of my local:
- When going back by one day I couldn't go forward again.
- The oldest day was one day older than it should have been.
This corrects the date used in the date comparison for the date bar.
To test:
On the Day period, verify:
- When going back a day (either via the bar or chart), you can go forward again to the most recent day.
- When going back to the oldest day (either via the bar or chart), the date bar disables going back further.
Please also test this with site timezones:
- Ahead of your local.
- Behind your local.
- Equal to your local.
> Stats date bar: correct date used to determine back/forward availability

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
This PR updates the gutenberg-mobile reference to point to the latest release, v1.10.0.
The reference is currently pointing to the release/1.10.0 branch of https://github.com/wordpress-mobile/gutenberg-mobile.
Gutenberg side PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1246
To test:
> Update Gutenberg to v1.10.0

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #11486.
At first, I thought that this can be fixed by simply adding a `setBarsHidden(false)` if the `contentOffset.y` is `0`. It worked. However, I found out that VoiceOver cannot properly dictate the total number of pages if the `scrollView`'s height is dynamic. The dictation looks like this:
| Action | Dictation |
| The user is halfway and scrolls down. | "Page 3 of 4" |
| The user scrolls to the bottom. | "Page 4 of 4" |
| The bars are automatically shown. | "Page 5 of 5" ¯\\\_(ツ)\_/¯ |
The change in the total pages can be confusing to the user.
With this in mind, I opted to disallow hiding of the bars when VoiceOver is turned on. This keeps the dictated total pages static.
1. Navigate to Reader.
2. Select a post to view.
3. Turn on VoiceOver.
4. Scroll down …
> Reader: Do not hide bars if VoiceOver is turned on

- WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleHeader.swift
- WordPress/Classes/ViewRelated/Site Creation/SiteInfo/SiteInformationWizardContent.swift
- WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsWizardContent.swift
- WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift
- WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
Fixes part of #12127. 
This focuses on improving the accessibility of the headers for Site Creation. 
1.  1eddad0 The title and subtitle are now dictated together. 
2. 1698f2e When a new screen is shown, VoiceOver will select and dictate the first element on the screen. Unfortunately for us, this is usually the _Cancel_ or the _Back_ button. Following [Apple's guidelines](https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/SupportingAccessibility.html#//apple_ref/doc/uid/TP40007457-CH12-SW1), the headers are now dictated first. 
1. Turn on VoiceOver.
2. Navigate to My Sites and press the plus button to create a new site.
3. Go over the Site Creation flow. 
Please test:
- That the headers are read together
- The headers are read first when the screens …
> SiteCreation: Dictate the headers first

- WordPress/Classes/ViewRelated/Pages/Pages.storyboard
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/Classes/ViewRelated/Post/Posts.storyboard
Fixes #12219. This PR reintroduces the + button to the Posts list. I also switched both Pages and Posts to use a gridicon icon for consistency, and just use the system spacing instead of doing our own thing.
**To test:**
I haven't updated the release notes yet. If we can get this into 12.9 too then a release note won't be necessary as nobody will ever notice the button was gone.
> Add + icon back to Posts list

- WordPress/Classes/Models/Blog+Editor.swift
- WordPress/Classes/Models/Blog.h
- WordPress/Classes/Models/Blog.m
- WordPress/Classes/Services/BlogService.m
- WordPress/Classes/Services/EditorSettingsService.swift
- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/Classes/Utility/Editor/EditorFactory.swift
- WordPress/Classes/Utility/Editor/GutenbergSettings.swift
- WordPress/Classes/Utility/Migrations/87-88/BlogToBlogMigration87to88.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+InformativeDialog.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/CoreDataMigrationTests.m
- WordPress/WordPressTest/EditorSettingsServiceTests.swift
- WordPress/WordPressTest/GutenbergSettingsTests.swift
Third step to implement https://github.com/wordpress-mobile/gutenberg-mobile/issues/1233
Based on https://github.com/wordpress-mobile/WordPress-iOS/pull/12166
This PR implements the editor default logic and the migration of the local setting to remote, when the remote setting is empty.
To test:
- Open the test user's report card
- Check that nothing is set on `SELECTED EDITORS` for mobile platform.
- You can press `reset` to remove the setting if there's any.
**Sync and Migration from local to remote:**
- Login with a test user.
- Check that the locally defined default editor was set on the report card.
- Toggle the switch 
- Check that the new value was set on the report card.
**Sync from remote to local**
- Set a blog on Aztec and a blog on Gutenberg
- Uninstall the app, install and …
> [Gutenberg] - PR 02 - Editor default and migration

- WordPress/Classes/Stores/StatsPeriodStore.swift
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Ref #11963 
This adds _File Downloads_ to the period views. 
Since the endpoint isn't returning data yet:
- There is a `statsFileDownloads` FeatureFlag, just in case.
- There is a temporary method (`stubFileDownloads`) that can be used to simulate displaying data.
To test:
---
- Go to any period.
- Verify _File Downloads_ appears at the bottom, with the `No data` message.
---
- Disable the `statsFileDownloads` FeatureFlag.
- Verify _File Downloads_ does not appear.
---
To test with stub data:
- In `StatsPeriodStore:getTopFileDownloads`, enable `return stubFileDownloads()`.
- Verify _File Downloads_ appears.
- NOTE: `View more` does not work just yet. That will be in a future PR.
---
> Stats: Add File Downloads to Period view

- WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
- WordPress/Classes/ViewRelated/Stats/Charts/PostChart.swift
Fixes #12223
This PR updates the colors used in Stats.
- Open Stats from a selected site
- Select _insights_, _DWMY_ to display the chart bars to check the new colors are correct
> [Stats Refresh] Update Stats Chart bars colors

- WordPress/Classes/Extensions/WPStyleGuide+ApplicationStyles.swift
- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Refs #12211. This PR fixes some issues from 12211:
- Changes the window color to black to improve the appearance of the new style modal windows.
- Navigation bars in splitview detail controllers should now have correct styling. After these fixes I was seeing an issue on the iPad simulator where the status bar is incorrectly being colored `.darkContent`, but the iPhone simulators and my iPhone device are fine. If you could test on an iPad that'd be great.
- Fixes a crash when the notifications alert on first launch was dismissed.
- Fixes a crash when accessing the Notifications screen.
**To test:**
- Build and run (fresh install) with Xcode 11, iOS 13 SDK
- Log in
> Some iOS 13 fixes!

- WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/ViewMoreRow.swift
Ref #11963 
This adds _File Downloads_ detail view.
Since the endpoint isn't returning data yet, use the temporary method `stubFileDownloads` to simulate displaying data.
To test:
- In `StatsPeriodStore:getTopFileDownloads`, enable `return stubFileDownloads()`.
- Go to Period > _File Downloads_ and select `View more`.
- Verify `🔵 Tracked: stats_file_downloads_view_more_tapped <blog_id: xxxxxx>` appears in the logs.
- Verify the 10 rows created with `stubFileDownloads` are displayed.
> Stats: Add File Download details

- WordPress/News.strings
Fixes #n/a
This updates the News card to show info about Stats.
To test:
- Go to the Reader.
- Verify the News card now references Stats.
- Verify `Read more` opens the Stats en.blog post. 
> Update News card for Stats

- WordPress/Classes/Utility/Media/MediaFileManager.swift
Refs #12218.
@etoledom, I wasn't sure who to ask to review this – ideally I'd ask @SergioEstevao, but he's still AFK for a while. I know you've worked on some media code in the past, but let me know if you'd rather I pass it to somebody else.
The issue referenced mentions reports of user device storage being used up and never cleared when we clear the media cache. I noticed two issues that I think contribute to this:
We have code to clear the media uploads folder (in Documents) on app launch, but in my testing this is never actually happening. The predicate to find media that should be excluded from the deletion was:
`purgeMediaFiles(exceptMedia: NSPredicate(format: "blog != NULL || remoteURL == NULL")`
along with the comment:
```
/// Clear the local Media directory of any files that are …
```
> Allow clearing of unused media uploads

- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
Refs #11221
This fixes a crash after approving push notifications on iOS 13.
To test:
- Install a fresh install of WPiOS
- Login
- Re-launch (why isn't the request happening the first time? 🤔)
- Approve push notifications
- Ensure nothing crashes
> Fix notification request crash on iOS 13

- WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
- WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib
Refs #11863
> Yellow "private" text should be gray, preceded by a •
Before | After
----- | -----
| <img width="378" alt="image" src="https://user-images.githubusercontent.com/517257/62313318-55fe8f00-b445-11e9-8b96-ed91b2611854.png"> | <img width="422" alt="image" src="https://user-images.githubusercontent.com/517257/62313331-6151ba80-b445-11e9-8d1e-b560ecdd7cfa.png"> |
To test:
- Open the pages list, find or create a private page
- Ensure that the new appearance matches the description
> Change page list labels (private, etc) to be gray

- WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityDay.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityLegend.swift
This quick PR updates the colors names used for the PostingActivityColors struct. It uses semantic names based on the what @ScoutHarris suggested [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/12070/files#r301276239)
• Select a site with some Posting activity
• Open Stats -> Insights and scroll until Posting activity is displayed
> [Stats Refresh] Update Activity Posting colors name

- WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
- WordPress/Classes/ViewRelated/Views/LoadingStatusView.swift
This replaces the UI blocking HUD. Prominent in low connectivity. 
Fixes #12032 
To test:
1. Enable Network Link Conditioner for bad network
2. Update a post or a draft
3. Choose preview
4. See the loading status in the navigation bar instead of a blocking HUD
5. Make sure you can navigate back while the spinner is loading 
> Now showing loading status in navigation bar when preview is loading 

- WordPress/Classes/Extensions/WPStyleGuide+ApplicationStyles.swift
- WordPress/Classes/ViewRelated/Activity/Activity.storyboard
- WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPress/Classes/ViewRelated/Menus/MenuHeaderViewController.m
- WordPress/Classes/ViewRelated/Menus/MenusViewController.m
Refs #11683
This fixes the background colors for: Activity, Menu, Themes, and Media screens. It also includes some text color fixes for activity details view.
To test:
- Check out the screens mentioned above
- Verify that they all have the same background color, which is the same as the blog details view (and hopefully, by now, most of the rest of the app)
> Update several screen's background colors

- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
Fixes #12242 
**Reason of the crash:**
With the site settings controller loaded, after the user logs out, the blog's account becomes nil.
This makes the `tableSections` return to change, while the table still expected the old values.
For some reason the system will refresh the sections (or possibly, all visible cells) when the app goes to background, and given the state previously described, the crash will happen. 💥 
**Fix proposal:**
This PR forces to reload the table when there default account changes (i.e. user logout), updating the table's data source.
Maybe another option could be to manually remove the controller when a logout happens.
To test:
- Follow the instructions from #12242 
- Check that the app doesn't crash.
- Run UI tests locally on iPad
- Check that all UI tests pass …
> Fix crash after logout

- WordPress/Classes/Services/MediaCoordinator.swift
Fixes #12213.
Okay, so fixing this one was a doozy. What helped me get on the right path was a log submitted by a user in 2204495-zen. 
A relevant excerpt is:
```
019-07-25 10:22:10:808 🔵 Tracked: media_service_upload_failed <error_code: 2, error_description: Error Domain=Alamofire.AFError Code=2 "The system returned an error while checking the provided URL for reachability. 
URL: file:///var/mobile/Containers/Data/Application/8E539821-37D0-47C1-A310-791005ADD3D2/Documents/Media/IMG_5144.JPG 
Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “IMG_5144.JPG” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///var/mobile/Containers/Data/Application/8E539821-37D0-47C1-A310-791005ADD3D2/Documents/Media/IMG_5144.JPG, …
```
> Don't repeatedly show failed upload notices after auto retry

- WordPress/Classes/Services/BlogService.m
- WordPress/Classes/Services/PlanService.swift
- WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift
In line with recent changes made to the Plans endpoint, this PR updates our plans list code to use the API for the current user account instead of an anonymous API. This allows us to show the correct plans for the current user.
**To test:**
* Log into an account with a blogger plan. Ensure you see the blogger plan in the list.
* Log into an account without a blogger plan. Ensure you don't see the blogger plan in the list.
> Plans: Use api for current account instead of anonymous

- WordPress/Classes/Utility/Editor/EditorFactory.swift
- WordPress/Classes/Utility/Editor/GutenbergSettings.swift
- WordPress/Classes/Utility/Migrations/87-88/BlogToBlogMigration87to88.swift
- WordPress/WordPressTest/GutenbergSettingsTests.swift
Fixes https://github.com/wordpress-mobile/WordPress-iOS/pull/12221#issuecomment-516079036
I tried to avoid adding the change on the migration to not need to modify the key used for per-site gutenberg enabled once. But the migration alternative feels a bit more "correct" (?).
I also added a set of tests to cover our backs regarding the autoenable logic and requirements.
If you notice there are some cases not covered by the tests please let me know.
To test:
- Migrate from v12.9 with GB ON, start new post → should be Gutenberg in all sites
- Should not show the autoenable dialog on new gutenberg post.
> [Gutenberg] Fix showing autoenable dialog after migration

- WordPress/Classes/Utility/Editor/EditorFactory.swift
- WordPress/Classes/Utility/Editor/GutenbergSettings.swift
- WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
- WordPress/WordPressTest/GutenbergSettingsTests.swift
This PR is the WPiOS side of: https://github.com/wordpress-mobile/WordPress-Android/pull/10300
Add additional properties to gutenberg_enabled , and gutenberg_disabled analytics events:
The property source can now have the following values:
- via-site-settings
- on-block-post-open
- on-site-creation
**Disclosure:**
With this changes, are **not** tracking the switch event in cases where:
- We are setting Gutenberg/Aztec as part of a migration
- We are setting Gutenberg/Aztec as part of sync with remote
- We are setting Aztec as the default value
Is this the proper behavior? cc @daniloercoli @hypest 
**To test:**
Test 1:
- Flip the block editor setting in Site settings and make sure the property is added correctly
Test 2:
- Create a new site, and make sure the property is added with the …
> [Gutenberg] Adding Tracks properties to gutenberg enable/disable event

- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/Services/PostService.m
- WordPress/Classes/ViewRelated/Post/PostListFilter.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/PostListFilterTests.swift
- WordPress/WordPressTest/Services/PostCoordinatorFailedPostsFetcherTests.swift
Part of #12240. This is targeting the master branch `issue/12240-master-branch`. 
Local drafts that the user set to `published` will now be automatically uploaded and **published** when the device is online. Previously, local `published` posts were changed to `DRAFT` and were automatically uploaded as `draft`.
This change was based on @diegoreymendez's work in #12178. 
This deliberately targets `published` only. Scheduled, private, and other statuses' behaviors are left unchanged. I believe this lowers the risk of regression. After everything is done, we can also test the whole publishing flow before fully committing with all statuses.
Please see #12240 for the current plan. 
This change also completes the _"Post stays in draft"_ requirement. This is a missing portion of #12178, as …
> Auto-upload local published posts

- MIGRATIONS.md
- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
- WordPress/Classes/Models/FileDownloadsStatsRecordValue+CoreDataClass.swift
- WordPress/Classes/Models/FileDownloadsStatsRecordValue+CoreDataProperties.swift
- WordPress/Classes/Models/StatsRecord+CoreDataClass.swift
- WordPress/Classes/Stores/StatsPeriodStore.swift
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 89.xcdatamodel/contents
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/FileDownloadsStatsRecordValueTests.swift
Fixes #11963 
WPKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/175
To test:
- Go to Stats period.
- Verify File Downloads now has data. (This verifies the WPKit change.)
- FD is not live in Calypso yet. Data can be verified via the console with the `file-downloads` endpoint. Ex: `/sites/<site_id>/stats/file-downloads?period=day&date=2019-08-05&num=1`
- The filenames are displayed as-is. I've inquired on the FD P2 exactly how filenames are going to be displayed/formatted in Calypso, and will make any adjustments with a future change if necessary.
- Disable your network.
- Return to stats.
- Verify File Downloads has data.
> Stats: add File Downloads to Core Data

- WordPress/Classes/ViewRelated/Plugins/PluginDetailViewHeaderCell.swift
- WordPress/Classes/ViewRelated/Plugins/PluginDetailViewHeaderCell.xib
- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryAccessoryItem.swift
- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryCollectionViewCell.swift
- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryCollectionViewCell.xib
- WordPress/Classes/ViewRelated/Plugins/PluginListCell.swift
Refs #11683
This updates colors on the plugin screens:
Directory | List | Detail
--- | --- | ---
To test:
- On a Jetpack site, tap Plugins 
- Ensure the colors in this section have been updated
> Update colors on plugin screens

- Podfile
- Podfile.lock
- WordPress/Classes/Services/EditorSettingsService.swift
- WordPress/Classes/Utility/Migrations/87-88/BlogToBlogMigration87to88.swift
- WordPress/WordPressTest/EditorSettingsServiceTests.swift
This PR implements the new request from https://github.com/wordpress-mobile/WordPressKit-iOS/pull/176
To test:
- Run the migration from 12.9 to 13.0
- Check that the settings on server corresponds with the expectation:
- All blogs without mobile editor set, should be set to the new value given
- All blogs with a mobile editor set, should remain unchanged
- The local settings for all blogs should map the final state of mobile editor settings on server
> [Gutenberg] Implement new single request to bulk update user's mobile editor preference

- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTodayWidget/MainInterface.storyboard
This PR fixes the button color in the _Stats Today_ widget.
Also some improvements have been added:
• More space between the button and text
• The button is not wide as the container
• Build the branch and add the widget
• If you are logged in you can even sign out to make sure you see the widget right screen
> [Stats] Update Today Widget button

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/ViewRelated/Me/Change Username/ChangeUsernameViewController.swift
Fixes #9705 
This PR adds 3 new analytics events:
- _account_settings_change_username_succeeded_
- _account_settings_change_username_failed_
- _account_settings_change_username_suggestions_failed_
WP Shared updated [here](https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/214). I'll create a tag version and update here the pod file as soon this PR will be approved.
* Select the Tab Me -> Account Settings
* Tap on the username to open the new screen and change the username
> [Account Settings] Change Username analytics

- WordPress/Classes/ViewRelated/Post/PostCardCell.xib
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostCompactCell.swift
- WordPress/Classes/ViewRelated/Post/PostCompactCell.xib
- WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
- WordPress/Classes/ViewRelated/System/Notices/NoticeView.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/PostCardCellTests.swift
- WordPress/WordPressTest/PostCompactCellTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
Part of #12240. 
In #12252, we added auto-uploads for locally published posts. This PR updates the Notice and Post List messages to reflect the design described in #12240. 
Most of the commits were cherry-picked from @diegoreymendez's work in #12178.  
|What| Before | After |
--------|-------|----
Notice | <img src="https://user-images.githubusercontent.com/198826/62576719-a406fe80-b85a-11e9-9bf8-fb1f736e123c.PNG" width="320"> | <img src="https://user-images.githubusercontent.com/198826/62576723-a49f9500-b85a-11e9-841d-ee79ba48e715.PNG" width="320">
Post List | <img src="https://user-images.githubusercontent.com/198826/62576718-a406fe80-b85a-11e9-843c-6e7b5b5ed270.PNG" width="320"> | <img src="https://user-images.githubusercontent.com/198826/62576722-a49f9500-b85a-11e9-9552-c43c2a97cc0b.PN …
> [Auto-upload Published] Update Notice and Post List messages for failed local published posts

- WordPress/Classes/Utility/InteractiveNotificationsManager.swift
- WordPress/Classes/Utility/Universal Links/Routes+Me.swift
I just discovered a Notifications API that I figured we should probably implement. It allows us to hook into system notifications settings UI, providing a way for users to jump into Notification Settings in our app. There are two places it surfaces:
1. In system **Settings > WordPress > Notifications**, there's now a **WordPress Notification Settings** item:
2. When you receive a notification, if you either expand it and tap the `...` button or swipe it and tap Manage, you're shown a system menu for Deliver Quietly, Turn Off... or Settings. Now, if you tap Turn Off... you'll be presented with a new option to jump into the app to manage your settings:
**To test:**
* Navigate to system settings and check that item 1 above exists and works.
* Receive a notification, and bring …
> Notifications: Add support for `providesAppNotificationSettings`

- WordPress/Classes/Utility/ZendeskUtils.swift
Fixes #11397. I think this PR should fix the crash we're seeing in #11397. It switches Zendesk to use a modal presentation style instead of pushing onto the existing navigation stack. We're using `formSheet`, which will show full screen on iPhone, and in a smaller modal on iPad.
**To test:**
* Ensure that Zendesk views still work as expected
* Create a new ticket, and tap the attachment icon. Scroll the image picker to the left and choose Media Library or Camera and ensure the app doesn't crash.
cc @jkmassel @SylvesterWilmott 
> Issue/11397 Fix Zendesk presentation crash

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
This PR implements the Gutenberg Bridge changes from: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1271
his PR fixes an issue that crashes the app when trying to start a photo post from the 3D Touch shortcuts.
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1190
To test:
- Build and run on a iOS **device with 3D touch** (iPhone 6S family or later)
- When the app is running, send it to background
- Find the WordPress app icon, and "force touch" it to display the shortcut options.
- Select "New Photo Post"
- Choose an image (or a few)
- Press on "Insert" at the bottom right corner
- Check that the images are added to the post and there is no crash
> [Gutenberg] Fix crash when creating New Photo Post on gutenberg from 3D Touch shortcut

- .circleci/config.yml
The UI tests have now been running nightly for several weeks and have proved to be reliable. This enables running them on every PR. It means that PRs will take a little longer to go green, but should only be a few minutes longer than now.
There is potential to improve run time by parallelizing the unit tests and UI tests building but that can be an improvement for later.
To test:
- UI tests for iPhone XS and iPad 6th gen are green on this PR.
> CircleCI: Run UI tests on every PR

- WordPress/Classes/Services/MediaCoordinator.swift
Fixes (hopefully for realsies this time?????) #12213.
After staring at the code for 6h today, I had a eureka moment — I realized my fix from #12214 worked for images uploaded added straight to media library, but could (potentially) fail for images added directly to the posts.
I _thought_ my fix would cover both of those cases (and in my local testing it seemed to have done so), but I now realize there was a subtle (I THINK) race condition involved.
My (pretty educated, but also, desperate) guess at what was happening is as follows:
1. There's a race between `resume()` methods of `MediaCoordinator` and `PostCoordinator` (or, more specifically, between `-[PostService getFailedPosts:]` and the `MediaService` counterpart.
2. I think that in cases where MediaCoordinator/Service won that race, …
> Fix the issue with persistent failure upload notices, hopefully for realsies this time.

- WordPress/Classes/ViewRelated/Post/PostEditor+BlogPicker.swift
Fixes #12300 
The issue here is that when switching a site while in the editor, we are calling recreatePostRevision to create the post in the selected site.
When we are setting the new post createDate by doing:
`newPost.dateCreated = post.dateCreated`
The setCreatedDate method in AbstractPost is getting called. There we check if the date created is nil or equal to the modified date and if so we update the status to publish:
``` 
if ([self dateCreatedIsNilOrEqualToDateModified]) {
// A nil date means publish immediately.
self.status = PostStatusPublish;
} 
```
This PR sets the status of the new post, after setting it's createdDate so the original post status will remain and will be set back to draft.
To test:
1. Open the editor in the app.
2. Tap the site name at the top of the editor. In …
> Updating new post status *after* setting its created date

- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Fixes #12284 
To test:
1. Be on drafts / scheduled tab
2. Create a post / page
3. publish the post / page
4. The editor is removed from view
* Notice that the post lists / pages list remains on the same tab you started in.
> Existing the editor to posts list / pages list will remain in the same tab.

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR adds a few missing editor events to tracks:
- List button tapped
- Undo button tapped
- Redo button tapped
WordPress-Shared PR: https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/217
This is homologue to the WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10389
Aztec iOS doesn't have paragraph alignment options, and I did not find the options for `EDITOR_TAPPED_NEXT_PAGE` and `EDITOR_TAPPED_PREFORMAT`. @daniloercoli maybe you could clarify that?
- All other `editor button tapped` events tracked on android are being tracked already on iOS.
- I did not find any event on iOS that is not being tracked on Android ✅ 
- Also checked the names and they are consistent
cc @hypest 
To test:
- run `rake dependencies`
- Run the app (preferably on an iPad …
> Add missing editor (Aztec) tracks events

- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Fixes #12049 
To test:
1. Be offline 
2. Go to Pages 
3. See the no results view with "Create Page" button
4. tap create page
5. Enter title / Content
6. Exit the editor with "Save Draft"
7. See that draft page was created and a notice that it wasn't uploaded
> Added "Create Page" button to no results view when offline

- WordPress/Classes/Utility/ContextManager.m
Refs #12028 
One thing making #12028 hard to diagnose is that very little information is being reported. This change gives a unique error name for each specific core data error, and will also add multiple errors to the `reason` argument, if multiple are present.
**Note:** I couldn't find a great way to test this :( 
To test:
- kind of look over the code to suss out if it might work
- i tried really hard to find a good way to make CD save fail, but couldn't
> Add specific reasons for ContextManager save: errors

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #n/a
WPAuth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/113
This enables the new `enableSignInWithApple`  flag added in the above WPAuth, allowing the 'Continue with Apple' button to appear in the Log In button view.
To test:
- Run the app in XCode 11.
- Run on iOS 13. Verify the Apple button appears.
- Tapping the button doesn't do anything yet, but does log a `Login Prologue: Apple tapped.` message.
- Run in a lower iOS version. Verify the Apple button does not appear.
- Run the app in XCode 10. 
- Verify the Apple button never appears.
- Disable `FeatureFlag:signInWithApple`.
- Verify the Apple button never appears.
> [SIWA] Log In: add 'Continue with Apple' button to login options

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.xib
Fixes #12339 
This PR fixes a bug with the Post stats title.
@loremattei this needs to be merged in _13.1_
• Go to _My Site > Stats > DWMY_ and find a time period with views.
• Scroll down to _Posts and Pages_, and tap one of the _Posts or Pages_ that has views.
• Try tapping the site title under _Showing stats for_
> [Stats Refresh] Fix title link from post stats

- WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
Fixes #10677 
The issue seems to be that our `UIWebView` delegate methods call `stopLoading`.  This would be fine if the delegate methods were called once for the web view, but they can be called multiple times for any resources (like embeds) that the page loads.
@shiki hasn't been able to reproduce this reliably, while I've managed to reproduce it every single time.  When testing this I suggest to use the network link conditioner and try to make sure it's set to have a very slow connection.
The reason for this is that the bug relies on the second request being started BEFORE the first one completes.  On a very fast connection, the first request could complete really fast, and make it look like everything's fine.
@rachelmcr - Can I ask you to test this fix on several different site types …
> Fixes an issue that causing our previews to cancel loading.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- Added a mediaFor(uploadID: String) which searches for the media by upload id within the post object since the mediaCoordinator keeps returning nil for the media that failed to upload
- updated overlay reset method to reset only if the media doesn't have an error. 
- updated the reset overlay method name to communicate that it will only be reset if there is no error
Fixes #11937 
To test:
1. Open the editor on an existing post or start a new post in the classic editor
2. Be offline
3.  Add media to the post
4. See the failure overlay 
5. Tap on overlay
6. Choose discard or tap on title (or other content in the post)
7. See that the overlay is still there
8. Become online
9. Wait till the media is auto uploaded
10. See that the overlay disappears 
> Fix for media overlay disappears on action sheet dismissal in Classic editor

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPTextAttachment.swift
Refs #12211 
This is a first pass at resolving some artifacting be hind images in the Reader on iOS 13.  It looks like NSTextAttachments that are initialized without default data, file reference, or image will show a placeholder graphic.  Adding a 1px x 1px white image as starting data seems to hide the placeholder. 
This is the first thing I thought of, and there might be a more elegant solution. Other ideas welcome. 
To test:
Confirm the artifacting by viewing the reader post detail with an iOS 13 development build. Look for any post with an attachment--image or media.
Switch to this branch and confirm that the artifacting no longer appear.
> Reader: Initialize attachments with default image data.

- WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
- WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/Utility/ImmuTable+WordPress.swift
- WordPress/Classes/Utility/WPTableViewHandler.m
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Blog/DiscussionSettingsViewController.swift
- WordPress/Classes/ViewRelated/Blog/RelatedPostsSettingsViewController.m
- WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift
- WordPress/Classes/ViewRelated/Blog/SharingConnectionsViewController.m
- WordPress/Classes/ViewRelated/Blog/SharingDetailViewController.m
- WordPress/Classes/ViewRelated/Blog/SharingViewController.m
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
- WordPress/Classes/ViewRelated/Domains/DomainsListViewController.swift
- WordPress/Classes/ViewRelated/Me/ActivityLogViewController.m
- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSiteSubscriptionViewController.swift
- WordPress/Classes/ViewRelated/Pages/ParentPageSettingsViewController.swift
- WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
- WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
- WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressTableViewProvider.swift
- WordPress/WordPressShareExtension/ShareCategoriesPickerViewController.swift
- WordPress/WordPressShareExtension/ShareModularViewController.swift
Refs #11683
This removes the `murielColors` feature flag. If I did everything right, you won't even notice it's gone.
To test:
- launch the app
- look at every single screen in the app
- ensure that nothing has changed since before this PR
> New colors: turn off feature flag

- MIGRATIONS.md
- WordPress/Classes/Models/AbstractPost+HashHelpers.h
- WordPress/Classes/Models/AbstractPost+HashHelpers.m
- WordPress/Classes/Models/AbstractPost.h
- WordPress/Classes/Models/AbstractPost.m
- WordPress/Classes/Models/Page.swift
- WordPress/Classes/Models/Post.swift
- WordPress/Classes/Services/PostAutoUploadInteractor.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/System/WordPress-Bridging-Header.h
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
- WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 90.xcdatamodel/contents
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/PostTests.swift
- WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
Fixes #12136.
(NOTE: this PR is against the `issue/12240-merge-develop` branch. When #12346 is merged, I'll change the head of this one.)
This adds a mechanism for the app to make sure that the post user clicked "Publish" on, is the same post we'll try to auto-upload in the future.
Originally this PR also contained a check to make sure that the `dateModified` is also not greater than 48h, before realizing that the `dateModified` on `AbstractPost` does not contain the values I thought it did.
The implementation should be fairly straightforward to read — it took me _ages_ to get the correct incantation of SHA_* methods (and not accidentally cause collisions in the calculations!), but in the end the code ended up fairly simple. 
Because the hashing APIs in iOS aren't (yet! iOS13 changes …
> Add content hashes for Posts to prevent accidentaly uploading changed posts.

- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/InteractivePostViewDelegate.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/WordPressTest/PostActionSheetTests.swift
I found this while doing additional scoping for #12240. It does not look like we use this at all.
I believe compiling and the tests passing should be enough. 😬
> Remove unused InteractivePostViewDelegate.schedule

- WordPress/Classes/Services/PostCoordinator.swift
Fixes #12325 
To test:
1. Be offline 
2. Create new post 
3. Publish post
4. See the option to cancel
5. Tap cancel
6. See the notice 
> Show notice on cancel auto upload

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
- WordPress/Classes/ViewRelated/Stats/Helpers/StatsPeriodHelper.swift
- WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
Fixes #12348
This PR fixes the problem with the formatted date when the Site timezone is different from the device timezone.
CC. @rachelmcr @elibud @jkmassel 
- Set your site timezone to a timezone other than UTC. Choose a timezone that, if you add your device timezone to it, the date will be different.
- Check your stats in the app. Note that it now shows the right date for your site timezone setting.
> [Stats Refresh] Fix formatted date when timezone is different

- RELEASE-NOTES.txt
- WordPress/Classes/Models/Blog.h
- WordPress/Classes/Services/BlogService+Deduplicate.swift
- WordPress/Classes/Services/BlogService.m
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/BlogServiceDeduplicationTests.swift
This doesn't prevent the site duplication from happening, but if it has happened it will clean it up in the next blog sync
To help with #7886
To test:
To set up the scene, check out `release/13.1` and run the app, but before set up a breakpoint in `-[BlogService updateBlogWithRemoteBlog:account:]` so it always creates a duplicate when syncing:
Then go to the sites list and pull to refresh until you start seeing duplicates.
Add some local drafts in different blogs by creating new posts and relaunching the app before they get saved on the server.
Now checkout `fix/deduplicate-blogs` and run the app. Go to the sites list and wait for a bit, it should sync automatically. If not, pull to refresh. The duplicates should be gone. If you go to the posts list, every local draft should be there. …
> De-duplicate blogs after syncing

- WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/Map/CountriesMapView.swift
Fixes a build error on `develop` where the stats map view references old color names.
**To test**
* Check the app builds with no errors
> Fix incorrect color references for map view

- MIGRATIONS.md
- WordPress/Classes/Models/AbstractPost+HashHelpers.h
- WordPress/Classes/Models/AbstractPost+HashHelpers.m
- WordPress/Classes/Models/AbstractPost.h
- WordPress/Classes/Models/AbstractPost.m
- WordPress/Classes/Services/PostAutoUploadInteractor.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 90.xcdatamodel/contents
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/PostTests.swift
- WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
This is a second part of #12136 — adding support for expiring the scheduled autouploads after 48hs from confirmation.
Note that since this is using the same Core Data model number as #12347, it might crash on launch if you ran the #12347 branch in your simulator before. You'll need to delete and reinstall the app from the sim/device.
This is expected — I don't want this to create multiple migrations that will have to happen at runtime for our users, and all the migrations in the master branch should be coalesced into one before merging into `develop`.
To test:
Scenario 1 — making sure "young posts" are correctly autouploaded:
1. Go offline
2. Change the date on your Mac/device to yesterday 
3. Compose a post, try to post it
4. Change the date on your Mac/device back to the correct one
5. …
> Offline Posting: Expire AutoUploads after 48h

- Podfile
- Podfile.lock
Fixes #n/a
WPAuth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/119
This uses the changes in the above WPAuth PR.
Run the app in Xcode 11.
- Log out if necessary.
- Select Log In > Continue with Apple.
- Walk through the process, selecting an Apple email that already has a WP account.
- After entering your Apple password, the WP password entry view should be displayed.
**NOTE**: There is a hack noted in the WPAuth PR if account creation doesn't work yet.
Run the app in Xcode 10. Verify the app runs and does not show the 'Continue with Apple' login button.
To test:
> [SIWA] Show redirect to WP password entry of using associated email

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
PR for Gutenberg DarkMode
Known Issues: 
- ToolBar button colors are not changed. Will need some extra work.
- The SafeArea border colors on Landscape can get some more ❤️
- Dynamically changing between Dark and Light mode with the editor open, some parts of the editor won't change accordingly (bottom-sheet and a few elements in the toolbar)
All these will be worked on, on future PRs.
To test:
- `rake dependencies`
- Build and run using Xcode 11 (beta)
- Set the device to Dark Appearance
- Open gutenberg editor
- Check that is dark 🌑 
Test for a solved crash:
- Open gutenberg editor
- Close gutenberg editor
- Go to iOS settings and change the appearance mode.
- Go back to WordPress app
- Check that it does not crash (there was a crash at this point before)
> Gutenberg DarkMode

- WordPress/Classes/ViewRelated/Reader/NewsCard.swift
- WordPress/Classes/ViewRelated/Reader/NewsCard.xib
- WordPress/Classes/ViewRelated/Reader/Reader.storyboard
- WordPress/Classes/ViewRelated/Reader/ReaderCardDiscoverAttributionView.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/WordPressTest/NewsCardTests.swift
- WordPress/WordPressTest/SiteCreation/SiteSegmentsCellTests.swift
- WordPress/WordPressTest/SiteCreation/TitleSubtitleHeaderTests.swift
Refs #12320. This PR implements dark mode improvements for the Reader.
I think there are still probably a few loose ends, but on the whole it's better than what was there before!
**To test:**
* Build and run on iOS 13 light and dark mode and iOS 12
* Check nothing looks unexpected
> Dark mode: Reader

- WordPress/Classes/Utility/WebKitViewController.swift
- WordPress/Classes/Utility/WebProgressView.swift
Refs #12320. Quick PR to improve the appearance of WebKitViewController in dark mode.
**To test:**
* You know the drill. Build and run on iOS 13 light and dark mode and iOS 12.
* Check it looks 😎
> Dark Mode: Webkit view controller

- WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift
Just a quick one for the iOS 13 release – setting the Jetpack install flow to explicitly use fullscreen modal presentation. Without this change, on iOS 13 it was displaying a dismissable modal sheet, which would allow the user to swipe out of the flow partway through.
**To test:**
* Build and run, and add a self-hosted non-Jetpack site.
* Go to Stats and tap Install Jetpack, and insure the Jetpack flow is presented as a fullscreen modal.
> Fix Jetpack install presentation for iOS 13

- WordPress/Classes/ViewRelated/Views/WPAnimatedBox.m
This is a quick / hacky fix to prevent an issue where the WPAnimatedBox loading animation was using 100% CPU when not on screen. I _think_ this is only affecting iOS 13.
From my testing it only seemed to occur for StatsInsightsViewController – I think one is created on app launch and hangs around in the background. We need to fix the underlying issue, but this PR should prevent the animation from looping and using CPU.
**To test**
* Build and run on iOS 13
* In the Debug navigator, you should see CPU at ~100%
* Pause the app in the debugger and you should see a stack trace containing WPAnimatedBox. If not, try resuming and pausing again.
> [iOS 13] Fix for WPAnimatedBox 100% CPU usage

- WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostCardCell.swift
- WordPress/Classes/ViewRelated/Post/PostCardCell.xib
Refs #12320
Makes the ghosts in the posts list look much better in dark mode. 
To test:
- Pay attention to the placeholder cells/ghosts while the posts list is loading
- Check for both big and small cards
> Dark Mode: Fix colors on the ghosts in posts list

- WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
Fixes #12348
This PR fixes the delta generated when the site TimeZone is applied to the current date.
The delta represents a Time Interval generated by the difference between the Site and the Local TimeZones. 
**An example:** (The site is 8hrs ahead)
**Device**: UTC-8 (6:30am): current date printed is _2019-08-29 14:18:12 +0000_ (GMT)
**Site**: UTC+0
**Results**: _2019-08-29 22:18:17 +0000_ (GMT)
- Run the app and open Stats -> DWMY (Day is fine and quick to load)
- Play with the Site TimeZone and your device TimeZone (I found the bug testing with Site and Device UTC+2)
> [Fix] Stats TimeZone delta

- WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Fixes #12212 
It looks like there are swipe actions in the code but the swipe option wasn't working correctly (tested against iOS 12.4 and 11.4).
> Update comments swipe actions to UISwipeActions

- WordPress/Classes/ViewRelated/Post/AuthorFilterViewController.swift
Fixes #12330 
This PR wants to fix the popover tableview inset while the app is running on iOS 13.
Investigating the problem I found here ([1](https://forums.developer.apple.com/thread/121729) | [2](https://twitter.com/steipete/status/1157666057424912384)) that 
popovers in iOS 13 use safe area. This implies I had to fix the top inset and avoid the bottom safe area over the last row.
- Run the App on iOS 13
- Open the Post list and tap on the Author filter
- Make the same test with iOS 12
> [Fix] Author filter issues

- WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Refs #7886 
This PR introduces some new state flags to track when the blog list is syncing, ~and the last time it was synced~.  This addresses Bugs 5 and 7 in #7886 where multiple syncs (and multiple derived contexts) could occur simultaneously, leading to duplicated blogs. 
It would be nice if only a single derived context could exist but I'm not too keen on keeping a reference to a context while syncing (and beyond).  Our pattern thus far is that contexts, like services, would be ephemeral. Open to other ideas tho.
Test Prep: 
- Use Network Link Conditioner to slow requests. 
- Optionally, edit [BlogListViewController viewWillAppear:] to call `autoSyncBlogs` multiple times. 
- ~Optionally adjust the time interval for auto syncs to avoid waiting a full 5 minutes between auto syncs.~
- …
> Blogs: Do not sync while syncing.

- WordPress/Classes/ViewRelated/Post/PostCardCell.xib
Refs #12320 
Fixes a white line in dark mode:
To test:
- View the blog post list in dark mode
- Ensure the white line is gone
> Dark mode: white line in blog post list

- WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.xib
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityDay.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityViewController.swift
- WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
- WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.xib
- WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.xib
Refs. #12320 
This PR fixes some white background in Stats, mostly in Insights Overview and some detail.
- Run the App with Xcode 11 and iOS 13 with Dark Mode enabled
- Select a site with data like `en.blog` site
- Open Stats -> Insights and scroll the whole overview to check if there are still white backgrounds
- Click on View More from the Insights Posting Activities section and check the detail
- From the LPS (or select a post in the Post and Pages section in DWMY) select view more and check the detail.
> [Dark Mode]Fix/stats insights white space

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
Fixes #12320. This PR can also be used to verify the changes in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/124
This PR updates the sign up epilogue to remove white backgrounds:
**To test:**
* See the WPAuthenticator PR for full testing instructions.
> Dark mode: Fix NUX sign up epilogue colors

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextImage.swift
Refs #11398 
This PR is an attempt to address the crash in #11398. 
Rather than call `WPRichTextImage.clean` during `WPRichContentView.deinit`, let's call `CachedAnimatedImageView.clean` from `WPRichTextImage.deinit`.  This will avoid the call to `CachedAnimatedImageView.prepareForReuse`, which doesn't make sense during `deinit` and still cancel any inflight session tasks. 
You can see from the comments in the issue that its not clear how the deinit call could be related to the crash, but we might at least be able to rule out a suspect.
To test:
Launch the app and view the Reader. 
Find posts or comments with animated images. 
Confirm there are no regressions and that WPRichTextImage.deinit is called.
@jleandroperez Would you be game for a quick review of this one?
> RichContent: Tweaks deinit logic.

- WordPress/Classes/ViewRelated/Activity/Activity.storyboard
- WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
- WordPress/Classes/ViewRelated/Activity/ActivityListSectionHeaderView.swift
- WordPress/Classes/ViewRelated/Activity/ActivityListSectionHeaderView.xib
- WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
- WordPress/Classes/ViewRelated/Activity/WPStyleGuide+Activity.swift
- WordPress/Classes/ViewRelated/Me/ActivityLogDetailViewController.m
- WordPress/Classes/ViewRelated/Plans/FeatureItemCell.swift
- WordPress/Classes/ViewRelated/Plans/FeatureItemRow.swift
- WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift
- WordPress/Classes/ViewRelated/Plans/PlanListRow.swift
- WordPress/Classes/ViewRelated/Plans/Plans.storyboard
- WordPress/Classes/ViewRelated/System/PagedViewController.swift
- WordPress/Classes/ViewRelated/System/PagedViewController.xib
Refs #12320. This PR adds fixes for a number of areas:
**My Site > Activity**
Cells and headers now support dark mode
**Help and Support > Activity Logs**
These are now readable.
**Plans**
Plans list and detail now support dark mode
**To test:**
* Build and run on iOS 13 light and dark mode, and iOS 12
* Check the styles of each section listed above.
> Dark mode: Activity, support activity log, plans

- WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift
- WordPress/Classes/ViewRelated/Comments/WPStyleGuide+Comments.swift
Refs #12320
This improves the look of pending comments in both light and dark modes:
To test:
- View some pending comments
- Ensure the colors match the image above
> Dark Mode: Fix colors for pending comments

- WordPress/WordPressTodayWidget/TodayViewController.swift
Refs #12320. This PR updates the text label colors in the today widget for dark mode.
**To test:**
* Build and run in iOS 13 light and dark mode, and iOS 12
* Check the labels in the today widget are readable
> Dark mode: today widget

- WordPress/Classes/Models/AbstractPost.h
- WordPress/Classes/Models/AbstractPost.m
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/PostCardCellTests.swift
- WordPress/WordPressTest/PostTests.swift
Fixes #12328
Part of #12240.
We don't to show a "Upload failed" message for those posts, for which users have manually cancelled the auto-retries. This does that!
To test:
1. Go offline
2. Try to publish a post
3. Tap on "Cancel" in the post list
4. Verify it no longer says "Upload failed" in red, but "Local changes" 
> Hide the "upload failed" message if the user has manually cancelled

- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Refs #11389 
This PR is an attempt at resolving #11389 by adjusting a guard statement to check for a nil date--a possible cause of the crash based on the stack trace.
To test:
- Go to the Reader. 
- Scroll to load more. 
- Ensure more posts load (assuming there were more), and there are no regressions in this feature.
@ctarda could I trouble you for a quick review?
> Reader: Adjust guard statement to check for nil date.

- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/Utility/ContextManager.m
While trying to resolve #12416, I realized that media being uploaded wasn't properly marked as having `remoteStatus == .pushing`.  Upon debugging this issue I realized the problem was that we are setting this status asyncrhonously here:
https://github.com/wordpress-mobile/WordPress-iOS/blob/534556756a7d11efb3e10000aad6860493bc7d6b/WordPress/Classes/Services/MediaService.m#L245-L252
In this PR I change that block to be executed synchronously, as well as the save operation at the end of the block.
Place breakpoint A [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/534556756a7d11efb3e10000aad6860493bc7d6b/WordPress/Classes/Services/MediaService.m#L248).
Place breakpoint B [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/534556756a7d11efb3e10000aad6860493bc7d6b/WordPr …
> Makes the remoteStatus change synchronous for media uploads.

- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/Utility/ContextManager.m
Reverts wordpress-mobile/WordPress-iOS#12450 for the time being due to a deadlock found by @leandroalonso.
I'll investigate this further in the original branch.
> Revert "Makes the remoteStatus change synchronous for media uploads."

- WordPress/Classes/Utility/ContextManager+ErrorHandling.swift
- WordPress/Classes/Utility/ContextManager.m
- WordPress/WordPress.xcodeproj/project.pbxproj
See #12338
In #12208 we added some extra information to the errors generated when saving Core Data failed. This improved things a bit but it hasn't been enough to debug the recent surge in Core Data crashes.
First, the first PR was missing some important error codes, wrongly assuming that we weren't using much of Core Data validation. Perhaps we aren't doing a good job at it, but we have plenty of [properties that are non-optional](https://gist.github.com/koke/3622bd216354030e93b5fc6abfb492f3).
Second, the new error handling was only added to the save method for the main context. Saving derived context would still generate errors without any extra detail. More than two thirds of the latest 1,000 crashes happened on a derived context.
The new error handling added information about the …
> Improved logging of core data save errors

- Podfile
- Podfile.lock
Fixes #12398 
This PR implements the changes added in [WordPressAuthenticator-iOS PR](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/125).
The _Continue with Apple_ button is now available in the Sign Up .
I will update the _Podfile_ as soon the WordPressAuthenticator PR will be approved.
• Run the App on iOS 13 with Xcode 11
• Logout if you are signed in
• Tap _Sign up for WordPress.com_
• You should see the _Continue with Apple_ button
• Complete the flow testing everything works fine
> [SIWA] - Add Continue with Apple to Sign Up

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Refs. #12320 
This PR set the color to the HTML textView in the Aztec editor.
I'll update the Podfile as soon [Aztec #1209](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1209) will be merged
Adding also @mattmiklic to set the right colors used for the comments and the tags.
• Run the branch with Xcode 11 and iOS 13
• Edit a post and switch between _visual_ and _HTML_ mode
• Check the html text color is not black in Dark Mode
• Run it on iOS 12 to check everything works fine
> [Dark Mode] Fix text color in Aztec - HTML text view

- WordPress/WordPressShareExtension/MainShareViewController.swift
- WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
- WordPress/WordPressShareExtension/ShareModularViewController.swift
- WordPress/WordPressShareExtension/ShareTagsPickerViewController.swift
- WordPress/WordPressShareExtension/WPStyleGuide+Share.swift
Refs. #12320 
This PR fixes the colors in the Share Extension. 
• Run the branch with Xcode 11 and iOS 13
• Open a Post preview and try to share it selecting WordPress as option
• Check the colors in Light/Dark mode
• Run it on iOS 12 to check everything works fine
> [Dark Mode] Fix colors in Share Extension

- WordPress/Classes/Utility/WebKitViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Refs. #12320
Fixes #12457
Fixes #12456 
This PR fixes some wrong colors and behaviour in Dark Mode. The visible Gradient has been fixed along with the Quote border. This PR also contains a fix with the tab bar in the WebKit view controller.
**Note**:
This doesn't fix #12441 . Switching the interface mode while the app is running doesn't update the RichView background color.
• Run the branch with Xcode 11 and iOS 13
• To test the reader, open a post with a quote in the Reader to check the gradient and the quote border
• To test the WebKit view select _View Site_ from the Site dashboard.
> [Dark Mode] Fix Reader Detail and WebKit colors

- WordPress/Classes/Services/AccountService+MergeDuplicates.swift
- WordPress/Classes/Services/AccountService.h
- WordPress/Classes/Services/AccountService.m
- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/AccountServiceTests.swift
This is a copy of #12451 that ports the fix into our forthcoming 13.2.xx release.
This PR cannot be merged until #12484 has been.
This PR consists of commits that were artisanally plucked from the other branch and brought into this one. The code moving over should be identical.
> Merge Duplicate Sites Fix into 13.2.xx Part 2

- WordPress/Classes/Models/DiffAbstractValue+Attributes.swift
- WordPress/Classes/ViewRelated/Pages/PageListSectionHeaderView.swift
- WordPress/Classes/ViewRelated/Post/Revisions/Browser/Diffs/RevisionDiffViewController.swift
- WordPress/Classes/ViewRelated/Post/Revisions/Browser/Preview/RevisionPreviewViewController.swift
- WordPress/Classes/ViewRelated/Post/Revisions/Browser/RevisionDiffsBrowserViewController.swift
- WordPress/Classes/ViewRelated/Post/Revisions/Browser/Revisions.storyboard
- WordPress/Classes/ViewRelated/Post/Revisions/RevisionsTableViewController.swift
- WordPress/Classes/ViewRelated/Post/Revisions/Views/Cell/RevisionsTableViewCell.swift
- WordPress/Classes/ViewRelated/Post/Revisions/Views/Footer/RevisionsTableViewFooter.swift
- WordPress/Classes/ViewRelated/Post/Revisions/Views/Operation/RevisionOperationViewController.swift
Refs. #12320 
This PR fixes the colors in _History/Revisions_.
- Run the branch with Xcode 11 and iOS 13
- Select a Post with a History
- Open its History and switch between dark and light mode
- Check everything is ok with the 3 screens: _List_, _Diffs_ and _Preview_
- Test everything is ok on iOS 12
> [Dark Mode] Fix History/Revisions colors

- WordPress/Classes/ViewRelated/Cells/ExpandableCell.swift
- WordPress/Classes/ViewRelated/Cells/TextWithAccessoryButtonCell.swift
- WordPress/Classes/ViewRelated/Plugins/PluginDetailViewHeaderCell.swift
- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryCollectionViewCell.swift
- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryCollectionViewCell.xib
- WordPress/Classes/ViewRelated/Plugins/PluginListCell.xib
- WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift
Refs #12320 
This PR fixes some white background and colors in the Plugins section.
- Run this branch with Xcode 11 and iOS 13
- Use a site where you can install plugins
- Open the Plugins list and check the colors
- Open on Plugins category and check the colors
- Open a Plugin detail (specially one not installed) and check the colors
- Test everything works on iOS 12
> [Dark Mode] Fix Plugins colors

- WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsSectionHeaderView.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsSectionHeaderView.xib
- WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.swift
- WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.swift
- WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.xib
- WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
- WordPress/Classes/ViewRelated/Blog/QuickStartCongratulationsCell.xib
- WordPress/Classes/ViewRelated/Blog/QuickStartListTitleCell.xib
- WordPress/Classes/ViewRelated/Blog/SiteManagement/DeleteSite.storyboard
- WordPress/Classes/ViewRelated/Blog/SiteManagement/DeleteSiteViewController.swift
- WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
- WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift
- WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyContentView.swift
- WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleHeader.swift
- WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift
- WordPress/Classes/ViewRelated/Site Creation/SiteInfo/SiteInformationWizardContent.swift
- WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsCell.swift
- WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsWizardContent.swift
- WordPress/Classes/ViewRelated/Site Creation/Verticals/NewVerticalCell.swift
- WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsCell.swift
- WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift
- WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.swift
- WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
- WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
Refs. #12320 
This PR fixes:
- Muriel placeholder color: [bd29ac8](https://github.com/wordpress-mobile/WordPress-iOS/commit/bd29ac834e1ace71c5838c02ee47bc71df49ec24)
- Page List cell labels colors & Delete Button in Site Settings
- Site creation flow
- Fix Quick Start
• Run this branch with Xcode 11 and iOS 13
• Create a new WordPress.com site and check everything works fine in dark and light mode
• Then activate QuickStart and check the site dashboard header has the right color.
• Check the 2 QuickStart checklist have the right colors
• Go to the site settings and try to cancel it. Check the cancel button has the right color.
• Do the same thing building for iOS 12
> [Dark Mode] Multiple Fixes

- .circleci/config.yml
This shaves >1 minute off every CircleCI job by speeding up git checkout time using https://github.com/wordpress-mobile/circleci-orbs/pull/32
To test:
- CircleCI is green, and quick!
> CircleCI: Shallow clone repo to speed up builds

- WordPress/WordPressTest/SiteCreation/SiteSegmentsCellTests.swift
This PR removes a failing site segment test, where we've now updated background colors to use system colors.
> Remove broken site segment cell test

- WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
- WordPress/Classes/ViewRelated/Blog/DomainCredit/DomainCreditRedemptionSuccessViewController.swift
- WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController+HeaderFooter.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/Views/RegisterDomainDetailsFooterView.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainSuggestions/RegisterDomainSuggestionsViewController.swift
- WordPress/Classes/ViewRelated/Domains/Views/RegisterDomainSectionHeaderView.swift
- WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
- WordPress/Classes/ViewRelated/Views/NoResultsViewController.swift
Refs. #12320 
This PR fixes some colors and white background in the Domain Redemption flow.
- Run this branch with Xcode 11 and an iOS 13 device
- Buy a plan in order to obtain the possibility to register a domain
- Register the domain using the app. Follow the flow form the site dashboard and check the colors.
- Run it with iOS 11/12 to check everything works fine.
> [Dark Mode] Fix colors in Domain redemption flow

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/ZendeskUtils.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Re-enables ZenDesk and updates the ZenDesk pod to the iOS 13 version.
**To test:**
1) Ensure the PR is green
2) Run on-device, and ensure that tickets can be sent.
Known issue: 
- If you change the email address for the user in ZenDesk, sending tickets may fail
- Sending tickets from a WordPress.com admin account may fail.
> Enable zendesk in 13.2.1

- Podfile
- Podfile.lock
Updates the WPAuth pod to support Xcode 11 and SIWA reordering
**To test:**
- Ensure tests pass
- Ensure SIWA button is at the bottom when logging in (iPhone only – not on iPad)
**Update release notes:**
> Update WPAuth to 1.9.0-beta.1

- WordPress/Classes/Utility/PushNotificationsManager.swift
Fixes #11779. Kudos to @jtreanor for the suggested fix!
**To test:**
You can replicate the issue by following the steps in #11779.
To test that this fixes the issue, follow the same steps:
- Sign in
- Ensure Push Notifications are working (take some action to cause one to be sent – posting a comment as another user is a good candidate)
- Turn on Airplane Mode
- Log Out
- Turn Airplane Mode off
- Take some action that causes a push notification to be sent – it shouldn't appear on-device. Ideally, you could test this with a signed-in device next to your testing device – that'll help ensure the push notification was actually sent.
**Update release notes:**
> Fix logout not stopping notifications

- WordPress/Classes/Services/PostAutoUploadInteractor.swift
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/PostCardCellTests.swift
- WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
- WordPress/WordPressTest/Services/PostCoordinatorFailedPostsFetcherTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Views/PostCardStatusViewModelTests.swift
Closes #12324. 
This adds auto-uploading support for published and draft posts that were previously uploaded to the server. The main change is the removal of [`!post.hasRemote()` in `PostAutoUploadInteractor`](https://github.com/wordpress-mobile/WordPress-iOS/commit/873bd85000c3970bc20d4c5fafe61fdbd0ceb10f#diff-ebdb8497b6444c39da3f2b426dc2a78cL29-L30). 
This also incorporates the related changes as described in the pending tasks in Android:
- https://github.com/wordpress-mobile/WordPress-Android/issues/10465 - Show “Cancel” after editing existing drafts. 
- https://github.com/wordpress-mobile/WordPress-Android/issues/10461#issuecomment-526843789 - Show “Draft will be uploaded next time your device is online” for drafts.
- https://github.com/wordpress-mobile/WordPress-Android/issues/10463 …
> Automatically upload published and draft posts

- WordPress/Classes/Extensions/UINavigationController+Helpers.swift
- WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
Fixes an issue that @rachelmcr discovered with the split view on iPads in dark mode. I don't think this entirely fixes the underlying issue, but it does resolve it for now. Really, we need to re-do the splitview implementation at some point.
I also resolved an issue where the status bar text color was dark instead of light.
**To test:**
* Build and run on iPad, iOS 13
* Launch the app to a view like Me
* Enter iPad multitasking (on the simulator, hold Cmd+shift and double-tap H)
* Select another app
* Enter multitasking again
* Select WordPress
* Before this patch, the detail pane would switch into dark mode.
> [Dark mode] Fix iPad split view appearance

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
To test:
1. Check out branch and execute `rake dependencies`.
2. Test logging in and signing up with SIWA on a device or in the simulator.
3. Verify that only one `signed_in` and `logged_in` event is fired and it has the `apple` source parameter listed.
> Updated Authenticator pod to test SIWA login tracks fixes

- Podfile
- Podfile.lock
Update pods to release versions for 13.3
> Update pods to release versions for 13.3

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Fixes #n/a
To test:
- Go to Stats > any Period.
- Verify File Downloads card still appears at the bottom of the table.
> [Stats] Remove file downloads feature flag.

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Fixes #12495 
in iOS 13, traitCollectionDidChange gets called when the view is created as oppose to previous versions where it was called when added to the view hierarchy. The different timing of the call created this issue.
Apple suggestion is to perform any work involving traits in one of the layout methods
and then rely on traitCollectionDidChange for any future size class changes.
> Trait environments, such as views and view controllers, now have their traitCollection property populated with traits during initialization. These initial traits represent a prediction of the ultimate traits that the trait environment will receive when it gets added to the hierarchy. Because the traits that are populated during initialization are just a prediction, they might differ from the traits that …
> Fix issue with gap in NotificationsController

- WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
Fixes #12362 
To test:
1. Be online
2. Create a post with title
3. Exit editor
4. Save as draft
5. Put a break point here: https://github.com/wordpress-mobile/WordPress-iOS/blob/fb953e49825704046034ee1aba673e7c682fc83b/WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift#L30
6. Go offline
7. Continue run 
8. See notice "Post was uploaded" and tap publish in notice
9. Go online
10. See that the post is auto uploaded.
> Marks an uploaded draft to be auto uploaded.

- Scripts/localize.py
- WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
Localisation failed for the 13.3 code freeze for two reasons:
- There were some new strings that were not literals.
- Something changed in the behaviour of the command line tools for Xcode 11, causing `find` to have a trailing newline and therefore `genstrings` was looking for a file called `""`, and failing.
I have fixed both of these issues so we can proceed with the code freeze.
To test:
- Run `./Scripts/localize.py` from the root of the repo. If should succeed.
> Fix localize.py for Xcode 11 and string issues

- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/WordPressTest/PostCoordinatorTests.swift
This one has been failing here and there for a while.
Thanks @aerych for the ping to look at it.  IMHO calling `postCoordinator.save` ought to either:
- Have persisted its changes by the time it returns _or_
- Provide a callback that lets the caller know exactly when the save operation is complete.
Personally, I'd prefer the first approach, but right now it seems like the timing in this save behaviour is non-deterministic, which makes me wonder if it's part of / related to some of the Core Data instability we've seen recently.
Assuming this should be synchronous, I think we should refactor the tests not to use `toEventually(equal()) ` and instead should just use `to(equal())`.
**To test:** (not ready yet)
- Ensure tests are green in GitHub
- Erase Content + Settings in the Simulator then …
> Towards fixing a flaky test

- WordPress/Classes/Models/WPAccount.m
It seems iOS 13 introduces a new check to ensure we don't try to present a controller from a background thread, or the app will crash. This would happen when syncing blogs (in a derived context), if the token for the account was missing it would present the sign in flow.
Fixes #12520 
To test:
I haven't been able to reproduce the issue, but if you can make the account token go away, then pull to refresh in the blogs list it should happen?
> Fix threading crash on iOS 13

- WordPress/Classes/Services/CommentService.m
- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/Services/MediaThumbnailService.swift
- WordPress/Classes/Services/ReaderPostService.m
- WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme
In https://github.com/wordpress-mobile/WordPress-iOS/issues/11384#issuecomment-526758270, @aerych suggests the root cause for the crash #11384 is some implementation error when using derived contexts and multiple threads.
To mitigate this, I've enabled [Core Data's concurrency debug mode](https://oleb.net/blog/2014/06/core-data-concurrency-debugging/) (`-com.apple.CoreData.ConcurrencyDebug 1`). I've left that enabled in this PR, like we have the Main Thread Checker, so other developers can catch more threading issues I might have missed.
To find issues, I looked at every usage of `newDerivedContext` and tried to use the app hitting those code paths. When Xcode crashed on bad threading, I made sure we were using the right context for each managed object.
To test:
Code paths I have tested …
> Core Data Threading fixes

- RELEASE-NOTES.txt
- WordPress/WordPressNotificationContentExtension/Sources/NotificationViewController.swift
- WordPress/WordPressNotificationContentExtension/Sources/Views/NotificationContentView.swift
Refs. #12320 
This PR fixes the colors used in the rich notifications title and body.
**Title** -> `.text`
**Body** -> `. textSubtle`
- Run this branch with iOS 13
- Generate a push notification from another account
- Expand the notification to see its content
- Switch between light/dark style to verify the colors are ok
- Run it with iOS 12 and verify everything works as always
> [Dark Mode] Fix colors in rich notifications

- WordPress/Classes/Services/AccountService.m
Refs #12537
While testing #12537 I noticed that auth tokens were not updating as expected.  This PR restores the expected behavior. 
To test:
- Apply the patch
- Start logged into the app
- You want to clear your existing auth token.  One way to do this is set a break point in the `[BlogListViewController setEditing:]`, go to the My Sites tab and view the blog list.  Tap the Edit button. Then run `po [WordPressAuthenticationManager showSigninForWPComFixingAuthToken];`. 
- If you use the above method, you can pull to refresh to invoke the authenticator to fix the auth toekn.  Otherwise you can close and relaunch the app. 
- Enter your password to login when prompted by the auth flow. 
- Confirm you are properly logged in and an NSAssert is not tripped due to the account not having an auth …
> Accounts: Ensure authtoken is updated for existing account.

- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
- WordPress/WordPressTest/Aztec/AztecPostViewControllerAttachmentTests.swift
Fixes #12498
While offline:
- Create a new post (using Aztec)
- Add some images
- Tap publish
- Check that the message "post will be published next time..." is appearing
We had an issue with Aztec (the same doesn't happen with Gutenberg) that was not updating `post.content` after an image was added. This explains why sometimes we ended up with `<img src="placeholder://">` in the post. This fix also prevents this issue from happening again.
> Auto-upload published posts with failed media

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
While online:
- Create a post
- Add 2 images
- Publish the post
- Go Offline
- Tap Edit
- Add another image and wait until it fails
- Go back Online
- Tap Update
- You should see a message and the upload should start
- After the upload is done, tap "Update" again
* The best solution is to change the "Update" action to use `PostCoordinator.save`. However, this is not a small change and we've decided to address it later
* We tried to add a unit test but due to coupling issues, we had to give up. It was taking too long.
> Upload failed medias before updating a post

- WordPress/Classes/Utility/ContextManager.m
This would at least allow us to capture the message and context of the error
For #12338
I'm wondering if we should ship this in a 13.2 hot fix instead, since 13.3 is still a week away (cc @jtreanor)
> Turn error initializing Core Data into proper exception

- WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.swift
Fixes #11555 
- added a workaround for the text fiel to be able to show the spaces (spaces need to be replaced by unicode space)
To test:
1. Start creating a new site
2. When entering the title, enter some name with spaces, spaces are now normally visible during typing
> Issue/11555 Site Creation: Space in the title/tagline doesn't appear

- WordPress/Classes/Models/AbstractPost.m
We are preforming refreshStatus in PostService+RefreshStatus that does the exact thing so no need  for the logic in awakeFromFetch.
This solves the issue of the status not being updated to failed as expected and as a result the post was not being picked up by the auto uploader
Please see comment: https://github.com/wordpress-mobile/WordPress-iOS/issues/12420#issuecomment-535319004
Fixes #12420 
To test:
1. Be offline
2. Create a post
3. Publish post
4. See the message: "Post will be published..."
5. Quit the app
6. return to the app turn online
7. See that the post is being auto uploaded
> Remove awakeFromFetch from AbstractPost

- .circleci/config.yml
This PR updates CircleCI orbs to include the changes in https://github.com/wordpress-mobile/circleci-orbs/pull/36 that fixes "shallow checkout" from forked PRs.
To test:
Make sure CI tests are green.
> Update CircleCI orbs to fix checkout from forked PRs

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
Fixes #12388.
Some of our universal links rules for WordPress.com capture URLs that we currently don't handle in the app. For example:
`/post/*` is used to open the editor for new posts for URLs like `wordpress.com/post/mycoolsite.wordpress.com`
Unfortunately, this also captures URLs we don't handle in the app, such as editing a specific post:
`wordpress.com/post/mycoolsite.wordpress.com/123`
We didn't implement handling for these URLs because we felt we couldn't be confident that the post exists in the app and that we have the latest version (the user could've already done some editing in Safari, potentially). However, our `/post/*` route matches this URL, so the app launches but we just silently do nothing.
This PR is a small tweak so if we launch due to a URL but it doesn't match any …
> Universal links: If we don't match a URL, pop back to Safari

- WordPress/Classes/Services/PostService+MarkAsFailedAndDraftIfNeeded.swift
- WordPress/Classes/Services/PostService.m
- WordPress/WordPressTest/PostService+MarkAsFailedAndDraftIfNeededTests.swift
Fixes a regression in #12324 
For tests instructions, please take a look in #12466 
> Automatically upload published and draft posts with existing remote

- WordPress/Classes/Models/Post.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/PostCardCellTests.swift
- WordPress/WordPressTest/PostCoordinatorTests.swift
- WordPress/WordPressTest/PostTests.swift
- WordPress/WordPressTest/Services/PostCoordinatorFailedPostsFetcherTests.swift
Fixes #12322
While offline:
- Create a post
- Tap publish
- Tap cancel
- Go back online and check that a revision was created (aka the post was autosaved)
Issue #12322 mentioned that an editor crash was another way to trigger an `.autoSave` state. Currently, this *does not happen* since no post upload attempt is made.
Anyway, in the case of a crash, the content will be locally saved.
> Remote auto-save unconfirmed published posts

- WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Fixes #12554 
This PR fix the problem introduced fixing [#12540](https://github.com/wordpress-mobile/WordPress-iOS/pull/12540) where the app wasn't able to keep the screenshot in background. Using @koke suggestion and the new _UIColor_ API `resolvedColor(with:)` I'm able to generate an attributed string for the dark and light user interface and assign it.
• Run this branch on iOS 13 and go to the Reader
• Open a post and check everything works normally
• Switch user interface style (light to dark or vice versa)
• Put the app in background and check it doesn't crash
• On the App switch screen, change user interface style (light to dark or vice versa) and see if the app screenshot change
• Test on iOS 12 to check everything works fine
> [Dark Mode] Re-enable screenshots when app is in background

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
This reverts changes done by #10556 since we are in a code freeze on gutenberg mobile and this wasn't supposed to get merged during it.
I used `git diff bbad25cf34e3130eb4bbc733d6d217710119aaca fa459afd34cd652817ea0224030666eb25d4d121` to compare this branch with the previous commit in develop to make sure this is reverting everything.
This reverts commit a2a5e527d26acf343c82648c228b84ceb8dbc616.
Fixes #
To test:
> Revert "support multiple prop in gutenberg editor"

- MIGRATIONS.md
- WordPress/Classes/Models/AbstractPost.h
- WordPress/Classes/Services/PostAutoUploadInteractor.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Post/AutoUploadMessages.swift
- WordPress/Classes/ViewRelated/Post/PostAutoUploadMessages.swift
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 91.xcdatamodel/contents
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/I18n.swift
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/PostCardCellTests.swift
- WordPress/WordPressTest/PostCompactCellTests.swift
- WordPress/WordPressTest/PostCoordinatorTests.swift
- WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Views/PostCardStatusViewModelTests.swift
Fixes #12369
While offline:
1. Create and publish a post
2. Check that both the toast and the post card says: "Post will be published next time..."
3. Restart the app
4. Check that both the toast and the post card says: "Post couldn't be published. We'll try again later"
5. Restart the app and check the same behavior as above
6. Restart again and check that the post failed and that the message "Couldn't perform operation. Post not published" is shown
While offline:
1. Create and publish a post
2. Check that both the toast and the post card says: "Draft will be uploaded next time..."
3. Restart the app
4. Check that both the toast and the post card says: "Post couldn't be drafted. We'll try again later"
5. Restart the app and check the same behavior as above
6. Restart again and check that …
> Do not automatically retry upload after 3 failures

- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Closes #12584 
The remaining auto-switching that were removed in this PR are:
- When pressing _Move to Draft_
- When pressing _Publish Now_
- Exiting the editor after publishing an existing draft
I didn't remove `updateFilterWithPostStatus` because it is being used in `PageListViewController` for Quick Start. 
Verify that the Post List tabs are no longer automatically selected when the scenarios described above happen. 
> Remove auto-switching of Post List tabs

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Fixes #12568 
Since iOS 13, the delegate method ```textView(_ textView: UITextView, shouldInteractWith URL: URL, in characterRange: NSRange, interaction: UITextItemInteraction)```
gets called not only when tapping on a link but also when scrolling.
As a result of this and the way we handle things inside that delegate method, links would open on scroll which feels especially buggy in link heavy posts like the ones in this blog: https://5blogs.wordpress.com
This PR adds a gesture recognizer to `WPRichContentView` where we now handle taps on links and attachments.
It also introduces a new WPRichContentViewDelegate method `interactWith(URL: URL)` to preform customization of the link presentation in the controller if needed. 
[Reported issues on …
> Handle link tap inside WPRichContentView instead of in shouldInteractWith URL

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #12603.
This PR updates the background color of the Like star animation in Reader detail to fix an issue where it was appearing as black.
Before:
After:
To test:
* Build and run on iOS 13 and turn on dark mode
* Navigate to a post in the reader
* Tap the Like button and check the animation looks good
* Double check it still looks okay in light mode
> [Dark Mode] Fix Reader Detail Like star animation background color

- WordPress/Classes/Models/AbstractPost.m
To test:
1. Build the project
2. Make sure no warnings are shown in `AbstractPost`
> Remove warning in AbstractPost

- WordPress/Classes/Services/PostAutoUploadInteractor.swift
- WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
Fixes #12586 
To test:
1. Be offline
2. Publish a page
3. Make sure you get notice "Page upload failed" and not "Post will be published"
3. Come back online 
4. Make sure page is not auto-uploaded 
This PR and its test will be reversed in a following Pages Improvement project.
> *Temporarily* not allowing auto upload for pages

- WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
Fixes #12596 
This PR fixes a white background in the Post settings Tag picker. Also it fixes some other colors.
- Run this branch on iOS 13
- Go to the Post list and edit one
- Open the post settings and tap on Tag
- Check the colors are correctly set. Switch also between light/dark mode.
- Test everything works correctly on iOS 12
> [Dark Mode] Update Tag picker colors

- WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift
- WordPress/Classes/ViewRelated/Tools/TimeZoneSelectorViewController.swift
Fixes #12599 
This PR removes the white background from the Site Settings->Tags and TimeZone
• Run this branch on iOS 13
• Go to the Site Settings
• Click on TimeZone and pull down the tableView. The white background shouldn't be there anymore. Switch also between light/dark mode.
• Click on Tags and pull down to refresh the tableView. The white background shouldn't be there anymore. Switch also between light/dark mode.
• Test everything works correctly on iOS 12
> [Dark Mode] Remove white background from Site Settings Tags and TimeZone

- WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesStreamHeader.swift
Fixes #12602 
This PR removes the white background in `ReaderFollowedSitesStreamHeader`.
• Run this branch on iOS 13
• Go to the _Reader_ and tap the _Manage_ button.
• Navigate back and check if the button still has the white background. Switch also between light/dark mode.
• Test everything works correctly on iOS 12
> [Dark Mode] Removed white background in Reader Manage button

- WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.swift
- WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.swift
Fixes #12598 
This PR fixes the white background (and divider color) in the Post Undo cell
• Run this branch on iOS 13
• Go to the Post list and delete one so the Undo cell will appear
• Check the colors are correctly set. Switch also between light/dark mode.
* Test everything works correctly on iOS 12
> [Dark Mode] Fix Post Undo cell background and divider

- WordPress/Classes/ViewRelated/Post/PostAutoUploadMessages.swift
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
- WordPress/WordPressTest/PostCardCellTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
This PR updates the strings related to the Offline Support accordingly to the [Android Editorial Review](https://github.com/wordpress-mobile/WordPress-Android/pull/10542). It also:
* Removes the message that was shown when a post with remote was edited;
* Adds media-related fail messages
To test:
Review thoroughly the strings changed.
And:
1. While offline, create a new post, add an image and tap publish
2. Restart the app 3 times
3. Check the message that says "We couldn't upload this media, and didn't publish the post."
1. While offline, create a new post, add an image and save as draft
2. Restart the app 3 times
3. Check the message that says "We couldn't upload this media."
1. While offline, create a new scheduled post, add an image and tap publish
2. Restart the app 3 times
3. Check …
> Update strings for Offline Support

- Gemfile
- Gemfile.lock
- Scripts/fastlane/Pluginfile
This PR updates `release-toolkit` to import some fixes in the release notes handling for iOS.
It also updates `fastlane` to get rid of the security warning about rubyzip.
To test:
> Update fastlane and release-toolkit

- WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressUITests.xcscheme
We have been seeing a lot of erroneous/flaky failures for the UI tests that use a magic link (magic link login and signup), due to the issue described in https://github.com/wordpress-mobile/WordPress-iOS/issues/12608. This PR disables those tests until we can make them reliable.
FYI @designsimply we'll want to make sure signup and magic link login are fully tested in beta while these tests are disabled.
To test:
* Confirm all tests pass on CircleCI and the tests `testEmailMagicLinkLogin` and `testEmailSignup` are skipped.
cc @frosty
> Disable UI tests that use a magic link

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Ref #12405 
To test:
- On a slow network, go to Stats > Insights.
- Verify the Ghost Animations appear on the Insights card until the stats are loaded.
> [Stats] Enable internal testing for Insights async loading.

- WordPress/Classes/Services/PostService.m
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/Services/PostServiceSelfHostedTests.swift
- WordPress/WordPressTest/Services/PostServiceTests.swift
- WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Fixes #12630 
Whenever a **new published post** is auto-saved, it gets stuck at “Uploading post...”. The cause was `PostCoordinator.autoSave` thinks that the post should be auto-saved instead of created in the server. 
https://github.com/wordpress-mobile/WordPress-iOS/blob/db3444be48d52294f83fc0024badeb0b19a7a114/WordPress/Classes/Services/PostService.m#L340
And because the post is _new_, the call to `[restRemote autoSave]` will fail and the `failureBlock` is called:
https://github.com/wordpress-mobile/WordPress-iOS/blob/db3444be48d52294f83fc0024badeb0b19a7a114/WordPress/Classes/Services/PostService.m#L336-L338
But the `failureBlock` never resets the `Post.remoteStatus` to `.failed`, so the post gets stuck at `.pushing`. Hence, the cause of the infinite “Uploading post...” message. 
I …
> Make PostCoordinator.autoSave create non-draft posts if necessary and handle failures

- .configure
- .gitignore
- README.md
- Scripts/fastlane/Matchfile
- WordPress/WordPress.xcodeproj/project.pbxproj
@loremattei raised a very good point in https://github.com/wordpress-mobile/WordPress-iOS/pull/12653#discussion_r333399836 that we need to be careful about copying sensitive files to the project, even if they are ignored by git.
We discussed this and agreed that a good compromise to mitigate this is to store all files under one directory, and add it to `.gitignore`. This means when new files are added, there is no need for a new entry in `.gitignore` and the risk of committing the files should not be there.
To test:
Since the files are moved, we should test they are still working:
1. Run `rake dependencies`, it should succeed and the new files under `.gitignore` should be ignored.
- Run fastlane match to see it still succeeds: `bundle exec fastlane match enterprise --app_identifier …
> Store all credentials under .configure-files to prevent accidental commits

- WordPress/Classes/ViewRelated/Cells/PickerTableViewCell.swift
Fixes #12600 
This PR fixes the Picker background used in these screens:
**Post per Page**
**Close commenting, Paging, Links in comments**
• Run this branch on iOS 13
• Go to the _Site Settings_
• Under _Writing_ open **Posts per Page** and check if the background color is correctly set. Switch also between light/dark mode.
• Go to _Discussion_
• Under _Comments_ open **Close Commenting, Paging, Links in comments** and check if the background color is correctly set. Switch also between light/dark mode.
• Test everything works correctly on iOS 12
> [Dark Mode] Fix Picker background color

- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Fixes #12662
To test:
1. Edit an existing pending for review post. 
2. Make some changes. 
3. Tap X → Update Post. Notice that after doing this, no dialog asking to _Publish_ the post appears.
4. The post still "Pending Review"
You can repeat the same process while offline and then ensure that the message "We'll submit your post for review when your device is back online." appears.
1. Edit an existing scheduled post. 
2. Make some changes. 
3. Tap X → Update Post. Notice that after doing this, no dialog asking to _Publish_ the post appears.
4. The post still Scheduled
You can repeat the same process while offline and then ensure that the message "We'll schedule your post for review when your device is back online." appears.
> Editing a pending/scheduled post keeps it status

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes #12601 
This PR fixes the background color when a Reader comment cell is selected
The background is using the `listForegroundUnread` as color. This color has `.primary(.shade0)` for **old iOS versions** and `tertiarySystemGroupedBackground` for **iOS 13**
- Build this PR on **iOS 13**
- Go to _Reader -> Discover_ and tap the comment icon on the top post
- Tap the _Reply_ button underneath one of the comments and check the cell background color
- Test everything works with **iOS 12**
> [Dark Mode] Fix Reader comment background color

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Fixes #12661
The `GutenbergViewController` was not being updated accordingly with the changes in a post.
1. Start the creation of a new post
2. Post Settings -> Choose a future date to be scheduled
3. Go back, check that the upper-right button label is "Schedule"
1. Start the creation of a new post
2. Post Settings -> Set the status to "Pending review"
3. Go back, check that the upper-right button label is "Save"
4. Tap it, check that the post is "Pending review"
Ps.: Initially this was meant to target the Offline Support master branch, but talking with @etoledom we've decided that it worths to be fixed in `develop`.
> Changes Gutenberg VC accordingly with changes in the post

- .circleci/config.yml
- Podfile.lock
@jkmassel found and fixes a CocoaPods issue in https://github.com/wordpress-mobile/circleci-orbs/pull/41 which could lead to `pod install` timing out on CircleCI. This just updates the Orb to use that.
To test:
- There is a `Podfile.lock` change on the PR, see that `pod install` runs successfully on CI.
> CircleCI: Update Orb to fix pod install timeouts

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
- WordPress/WordPressTest/PostCoordinatorTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
Fixes #12589
1. Create and publish a post
2. While offline, edit the post
3. Tap "Update"
4. Tap X: note that no dialog should *not* appear if you already confirmed the changes
5. A snackbar message should appear
6. Check that the post will be updated when back online
Please, try different combinations:
* Add images
* Edit different type of posts: scheduled, drafts, pending
* Use Aztec and Gutenberg
Note that the original issue had 2 more tasks:
* A key difference is the button should not close the editor
* The blocking progress dialog should be removed
I decided to leave those to another task since it's not directly related to the Offline Support (and these behaviors are currently in `develop`).
> Update button works while offline

- .circleci/config.yml
- .configure
- .configure-files/project.env.enc
- Scripts/fastlane/Fastfile
- WordPress/WordPress.xcodeproj/project.pbxproj
This adds installable builds for WPiOS. When triggered, a build with the current changes will be made and a comment with a HockeyApp link will be posted on the PR.
The changes can be broken down as follows:
- Fastlane Match support for the "WordPress Alpha" scheme. This mirrors what is already done for the AppStore and Internal schemes.
- Added a new lane, `build_and_upload_installable_build` which builds and uploads the "WordPress Alpha" scheme to HockeyApp.
- New CircleCI job, `Installable Build` which requires [manual approval](https://circleci.com/blog/manual-job-approval-and-scheduled-workflow-runs/) to run. It does not run automatically as it would use ~15 minutes of CI resources on every push. See the test instructions for how to trigger it.
It builds on these PRs:
- …
> Optionally provide installable build on Pull Requests

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/Services/MediaService.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/BlogBuilder.swift
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/PostCoordinatorTests.swift
- WordPress/WordPressTest/Services/MediaCoordinatorTests.swift
As we've discovered in #12690 and fixed in 3e37abf1527dc0aa0426f704990026e111ef0a77, we had a bad merge when we recently merged `develop` into `issue/12240-master-branch` during #12664. 
This adds a simple test for `MediaCoordinator.uploadMedia` to avoid this from happening in upcoming merges. 
1. Revert `MediaCoordinator.uploadMedia` to the previous buggy version as shown in 3e37abf1527dc0aa0426f704990026e111ef0a77. 
2. Run `MediaCoordinatorTests`. The test `testUploadMediaReturnsTrueIfAllPendingMediaAreQueuedForUpload` should fail. 
3. Clean all changes and run the test again. The test `testUploadMediaReturnsTrueIfAllPendingMediaAreQueuedForUpload` should pass. 
- Only 1 reviewer is needed but anyone can review. 
- Please merge it if you approve of the change and are not requesting any …
> Add simple tests for MediaCoordinator.uploadMedia

- WordPress/Classes/Models/AbstractPost.m
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/Services/PostService+MarkAsFailedAndDraftIfNeeded.swift
- WordPress/Classes/Services/PostService+RefreshStatus.swift
- WordPress/Classes/Services/PostService.m
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/PostCoordinatorTests.swift
- WordPress/WordPressTest/PostService+MarkAsFailedAndDraftIfNeededTests.swift
- WordPress/WordPressTest/TestUtilities/PageBuilder.swift
Closes #12713
This definitely happened when I suggested to remove `markAsFailedAndDraftIfNeeded` in #12613. Because of that, we forgot to update that part to revert Pages to `.draft.`
This reverts the `markAsFailedAndDraftIfNeeded` removal and adds additional logic which reverts the `status` to `.draft` if the post is a `Page. 
1. Go offline.
2. Create a page and publish it.
3. Go online.
4. Tap on More → Retry
The page should be uploaded as a draft. 
- Only 1 reviewer is needed but anyone can review. 
- Please merge it if you approve of the change and are not requesting any changes.
> [Offline Posting] Fix Page List → Retry regression

- Rakefile
@ScoutHarris pointed out that running `rake dependencies` when there are changes to any of the credentials files will lead to prompts like this:
```
Would you like to make a backup of .configure-files/project.env? (y/n)
```
This is not useful since we always should use the latest version. Using `force:true` with configure_apply ensures the latest is always used.
To Test:
- Run `rake dependencies`
- Add some whitespace to the bottom of `.configure-files/project.env`.
- Run `rake dependencies` again. It should run successfully without prompting about overwriting.
> Rakefile: Always use latest credentials when running 'rake dependencies'

- WordPress/Classes/Models/Media.m
- WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/Views/RegisterDomainDetailsErrorSectionFooter.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryAccessoryItem.swift
- WordPress/WordPressShareExtension/ShareExtractor.swift
In Xcode 11 we had 12 build warnings. This PR fixes 9 of them, just leaving us with Swift 5 conversion and project settings updates.
I've tagged a couple of you for review, as these warnings were in sections of code that you edited last – please could you take a quick peek and check my changes look okay?
**To test:**
* Build and run, check there are only 3 warnings
* If you want to step through part of the app that a change affects then go ahead – I did try as many things as I could (media upload, browsing plugin directory, triggering register domain errors) and I think everything should be fine.
> Fix build warnings in Xcode 11

- WordPress/Classes/Models/Media.swift
- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/WordPressTest/MediaTests.swift
Fixes #12678
Please, use Gutenberg and Aztek for testing.
1. While offline, create a post and add an image
2. Tap Publish (or Save, or Schedule)
3. Check that the snack bar message says the post will be published later
> Show snackbar with "We'll publish the post" on failure to upload post with media

- Podfile
- Podfile.lock
Fixes #12724 
Updating pod after adding the attribute - https://github.com/wordpress-mobile/WordPressKit-iOS/pull/190
> Add signup_flow param by updating WordPressKit pod

- WordPress/Classes/Models/AbstractPost.swift
- WordPress/Classes/Models/BasePost.m
- WordPress/WordPressTest/AbstractPostTest.swift
Fixes #12750
To test:
1. Create a new post in the app and save it as a draft.
2. Open the same post in the web editor.
3. Upload a featured image to the post and save it.
4. In the app, make sure the remote changes are synced (e.g. pull to refresh the post list) and then open the post again.
5. Open the post settings. The image should be loaded.
> Opening post settings after uploading a featured image from another client displays the image

- Podfile
- Podfile.lock
Updates gutenberg-mobile dependency to v1.15.1
> Update to Gutenberg-Mobile v1.15.1

- Podfile
- Podfile.lock
GiphyCoreSDK has been deprecated (and deleted 😱), so we need to implement the new `Giphy` pod instead.
Sadly this pod also installs the Giphy UI library that we don't use.
This error started to appear in some [CI checks](https://circleci.com/gh/wordpress-mobile/WordPress-iOS/15175?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) already.
It should be able to reproduce the error by deleting the local `Pods/` folder and running `rake dependencies`.
To test:
- `rm -rf Pods/`
- `rake dependency`
- Build and Run.
- Check that you can download/add gifs to the Media Library or (Aztec) posts.
> Replace GiphyCoreSDK with Giphy pod

- .gitignore
Derived data path for Fastlane driven builds have been changed in [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/12654). This PR updates `.gitignore` to ignore that folder.  
To test:
1. Run a fastlane build lane (for example: `bundle exec fastlane build_and_upload_itc`) and verify that git status is clean after the build.
> Ignore derived-data folder

- WordPress/Classes/Services/PostService.m
- WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Fixes #12763
To test:
1. Publish a post
2. While offline, edit the post and tap "Update"
3. Tap "Cancel" in the post list
4. Go back online, wait for the post to be autosaved
5. Tap More -> "Move to Trash"
6. Refresh the list, the post will appear only under "Trashed"
> Deleted post with local changes appears only under Trashed tab

- WordPress/Classes/Stores/StatsPeriodStore.swift
- WordPress/Classes/Stores/StatsStore+Cache.swift
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Stats/Operation/AsyncOperation.swift
- WordPress/Classes/ViewRelated/Stats/Operation/StatsPeriodAsyncOperation.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.xib
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/AsyncOperationTests.swift
- WordPress/WordPressTest/StatsPeriodAsyncOperationTests.swift
Refs. #12147 
Refs. #11852
This is the first step to allow DWMY to load the blocks independently adding a new feature flag `statsAsyncLoadingDWMY` and the `AsyncOperation` class.
1. Open Stats -> DWMY from a Site you never opened before (or from a fresh install)
2. Yous shouldn't see the NRV
3. You should be able to load the chart and Top Posts card
4. Disable the feature flag and make sure everything works as before
> [Stats Refresh] DWMY Async loading operations and feature flag

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+InformativeDialog.swift
- WordPress/WordPressTest/GutenbergInformativeDialogTests.swift
Simple PR to update the text displayed when the user opens the block editor for the first time.
Old text:
> You're currently using the block editor to create new posts. Want to use the classic editor by default? Head to Site Settings.
New text:
> You’re now using the block editor for new posts — great! If you’d like to change to the classic editor, go to ‘My Site’ > ‘Site Settings’.
cc @hypest
> [Gutenberg] Update new editor popup message.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #12626
To test:
- Check the scenario referred in the ticket to see if the bug still happens
> Do full link selection fix only on 13.0

- WordPress/Classes/Models/AbstractPost.swift
- WordPress/Classes/Models/Media.swift
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/WordPressTest/PostCardCellTests.swift
Fixes #12802
To test:
1. Use a self-hosted site (or WPCom, the output is the same for both)
2. Go offline
3. Edit an existing draft
4. Add an image to it
5. Tap X → Update Draft
6. Tap "Cancel"
7. Go online and immediately go back offline as soon as you see the media being uploaded
8. Do the above step 3 times
9. Check the "Retry" button is appearing with a _We couldn't upload this media._ message
> Show media error if a post has permanent failed media

- WordPress/Classes/Extensions/AbstractPost+PostInformation.swift
- WordPress/Classes/Services/PostAutoUploadInteractor.swift
- WordPress/WordPressTest/BlogBuilder.swift
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/PostCoordinatorTests.swift
- WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
- WordPress/WordPressTest/Services/PostCoordinatorFailedPostsFetcherTests.swift
Fixes #12801 
To test:
1. While offline, edit an existing draft post.
2. Tap on X → Update Draft
3. In the Post List, tap Cancel.
4. Go online.
5. See that the post is *not* auto-uploaded  
> posts of self-hosted sites are not auto- uploaded if canceled

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
Ref #11852 
To test:
- Go to Stats > Insights.
- Verify ghost views appear when loading.
- On an Insight card, select 'View more'.
- Verify ghost views appear when loading.
> Stats: Remove statsAsyncLoading feature flag

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
- WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
- WordPress/WordPressNotificationServiceExtension/Sources/Tracks/Tracks+ServiceExtension.swift
Ref https://github.com/wordpress-mobile/WordPress-iOS/issues/12669#issuecomment-545375106
This adds some logging to help identify crashes with malformed push notifications.
- `NotificationsViewController.selectRow` now logs more information before calling `tableView.selectRow`. 
- The `request.content` is now added to the `wpios_notification_service_extension_malformed_payload` track properties.
To test:
- Go to Notifications and select a row. Note something like this in the logs:
`<WordPress.NotificationsViewController: 0x1088f9a00> selectRow(for:animated:scrollPosition:) Selecting row at [1, 8] for Notification: <note_id> (<notif_type>) - <notif_title>`
> Add push notification logging

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/12730
Following up from https://github.com/wordpress-mobile/WordPress-iOS/pull/12772.
I agree with @koke on https://github.com/wordpress-mobile/WordPress-iOS/pull/12772#issuecomment-547299425.
Since iOS 13.0 is so low on adoption, I believe is better to keep the simpler fix, regardless of the UX issue on 13.0, avoiding possible crashes.
I will do the gutenberg side changes next, but will probably go live on WPiOS 13.6.
To test:
> Aztec: `shouldInteractWithURL` will return always false to avoid crashes

- Podfile
- Podfile.lock
- WordPress/WordPress.xcodeproj/project.pbxproj
This PR updates ZenDesk to 3.0.2. Release notes for it can be found here: https://github.com/zendesk/zendesk_sdk_ios/releases/tag/3.0.2.
To test:
It's just a bug fix release, but we should thoroughly test any ZD functionality as part of this to ensure regressions haven't happened.
> Update ZenDesk to 3.0.2

- WordPress/Classes/ViewRelated/Post/Scheduling/CalendarCollectionView.swift
- WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController.swift
Addressing the remaining review comments on PR https://github.com/wordpress-mobile/WordPress-iOS/pull/12820
- Change DateCoordinator from value to reference type
- Access Control Level adjustments
- Removal of old code
> [12686 - Post Scheduling] Address PR Comments

- Podfile
- Podfile.lock
Ref #10975
WPKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/196
To test:
- Clean and build the project. Verify there are no errors.
- Verify stats work as expected.
> [Stats] Remove old WPKit stats code

- Podfile
- Podfile.lock
Fixes #
To test:
- Using an iOS 13.2 device
- Create a new GB post
- Add one of the following blocks to it: List, Quote or Image captions
- Try to write multiple lines
- See if the block size updates correctly when typing or deleting Enters
> Update Gutenberg to version 1.15.3

- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/GhostViews/StatsGhostTableViewRows.swift
This PR fixes a bug in the colors used by the Ghost animations layer in the DWMY header.
It also fixes the header background color.
- Open Stats from a selected blog (like en.blog)
- Select one Period and check the header colors in light and dark mode
> [Dark Mode] Fix Ghost animations colors in DWMY header

- WordPress/Classes/Extensions/AbstractPost+PostInformation.swift
- WordPress/Classes/Services/PostAutoUploadInteractor.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/Services/PostService.h
- WordPress/Classes/Services/PostService.m
- WordPress/WordPressTest/BlogBuilder.swift
- WordPress/WordPressTest/PostBuilder.swift
- WordPress/WordPressTest/PostCoordinatorTests.swift
- WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
- WordPress/WordPressTest/Services/PostServiceSelfHostedTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
Fixes #12861. 
After the changes in #12812, we no longer call `PostService.autoSave()` for self-hosted site posts. That seems to be the correct fix. It does cause the effect of not having unconfirmed published posts uploaded as drafts. This is one of the features of Offline Posting — avoiding data loss and always uploading the changes to the server. 
This was a bit tricky, which is why I'm targeting `develop` instead of the frozen `release/13.6` branch. I thought of adding another logic in `PostService.autoSave()` to support this. However, that method is also used in post previews. Adding that logic in `autoSave` would cause previews to be confusing for users. Consider this scenario:
1. Create a post. Set its status as Published in Post Settings.
2. Preview — the post will be …
> [Offline Posting] Self-hosted: Upload unconfirmed published posts as drafts

- WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
Need to manually set the post status after setting the data. Functionality was copied from `PostSettingsViewController` implementation.
> Resolve scheduled post status

- WordPress/Classes/ViewRelated/Reader/WPImageViewController.m
Fixes #12867
When `WPImageViewController` is presented by itself, not inside a `UINavigationController`, the VoiceOver escape gesture does not automatically handle the dismissal. 
This adds 2 things:
- 93bbc6d Make the image accessible so the VoiceOver user can interact with it.
- 85458c3 React to the escape gesture and dismiss self
1. Navigate to Reader and to a post with an image.
2. Turn on VoiceOver
3. Tap on the image. The `WPImageViewController` should be shown. 
Confirm that you can:
- Double-tap on the image to dismiss the view. 
- Use the escape gesture to dismiss the view (move two fingers back and forth three times quickly, making a “z”).
> [VoiceOver] Make WPImageViewController dismissible 

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Related #https://github.com/wordpress-mobile/gutenberg-mobile/issues/1373
Fix the tap in links bug in Aztec editor.
To test:
- Open a post using Aztec
- Try to tap in a link and see that you can interact correctly with and no Safari browser is open.
> Fix tap link bug in Aztec editor.

- WordPress/WordPressTest/DomainsServiceTests.swift
Every so often, I get unit test failures in CircleCI because of `DomainServiceTests`. I looked at [one of the successful builds](https://circleci.com/gh/wordpress-mobile/WordPress-iOS/16348) and found that one of the tests is pretty close to 1 sec.
```
DomainsServiceTests
✓ testDomainServiceHandlesTwoNewDomains (0.868 seconds)
✓ testDomainServiceParsesAllDomainTypes (0.048 seconds)
✓ testDomainServiceParsesPrimaryDomain (0.044 seconds)
✓ testDomainServiceRemovesOldDomains (0.051 seconds)
✓ testDomainServiceUpdatesExistingDomains (0.044 seconds)
```
Locally, it takes about 0.2 seconds. Something might have changed somewhere that resulted in this test to be not as fast as we thought it was.
This just increases the timeout to 2 seconds. This is not the most ideal solution but it's probably …
> Increase the timeout of DomainServiceTests

- WordPress/Classes/ViewRelated/System/Notices/NoticeView.swift
- WordPress/WordPressUITests/Screens/Editor/EditorNoticeComponent.swift
Fixes the failing UI tests caused by #12873. 
In #12873, I changed the accessibility of `NoticeView` so that both the title and message are dictated as a single unit (d04b6f12abe9154a7bea0e7e64d817133d605cfb). This broke the editor UI tests. 
This PR changes `EditorNoticeComponent` so that:
- 881a6c2 It will wait for the container of the Notice's title and message 
- ac4a04f It will validate based on the expected title and message
I'd love to have your opinion on the changes as I wasn't sure of how the UI test architecture connects all the classes together. 
I believe testing that `EditorAztecTests` and `EditorGutenbergTests` pass should be good enough.
> Update NoticeComponent to accommodate VoiceOver changes

- WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift
- WordPress/Classes/ViewRelated/System/Notices/NoticeView.swift
- WordPress/WordPressUITests/Screens/Editor/EditorNoticeComponent.swift
Fixes part of #11496.
This adds 2 things: 
- d34c7af Announcement of Notices when they are shown
- d04b6f1 Grouping the title and message together so they are dictated once by VoiceOver
Run through Quick Start and validate that whenever a Notice is shown, VoiceOver will announce the title and message. 
I noticed that VoiceOver will sometimes not dictate the Notice when you go navigate back to the Site page from a different page (e.g. Themes). VoiceOver will either: 
- Select the previously selected element
- Select the announced Notice
Not sure if it's worth it to chase the fix for that. It seems to be out of our control. 🤷‍♂ 
1. Replace [`showNoInternetConnectionNotice`](https://github.com/wordpress-mobile/WordPress-iOS/blob/b96410ddc5700b50fcba763ddad6da17bcb78b00/WordPress/Classes/Utili …
> [VoiceOver] Announce Notices when they are shown

- WordPress/Classes/ViewRelated/Reader/Reader.storyboard
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Refs #12866.  
This is just a minor improvement on the Reader Detail's header.
I removed the site URL from the accessible elements. It was too small as a touch target and the site name (plus URL) being dictated together should be good enough. 
Removed | Improved
1. Turn VoiceOver on.
2. Navigate to a Reader post 
3. Validate that you can no longer navigate to the site URL using VoiceOver. 
> Reader: Merge site name and URL for VoiceOver

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextImage.swift
Refs #12866. 
This hides the dictated “Attachment. PNG. File“ message.
The dictation was caused by the `ReaderPlaceholderAttachment`. The message gets dictated even for images. 
For the life of me, I could not hide it from VoiceOver using `isAccessibilityElement`. I ended up using an empty `accessibilityLabel` instead. 
In addition, I also made the `CachedAnimatedImageView` used in `WPRichTextImage` accessible so when a user hovers over it, VoiceOver would announce that it's an image rather than be silent. 
1. Turn VoiceOver on.
1. In Reader, navigate to a post with an image.
2. Hover over the first paragraph. Confirm that VoiceOver doesn't say ”Attachment. PNG. File” anymore and just proceeds to dictate the paragraph's content. 
4. Hover over an image. Confirm that VoiceOver will …
> [VoiceOver] Reader Detail: Hide “Attachment. PNG. File” dictation

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController+Cells.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController.swift
- WordPress/Classes/ViewRelated/Site Creation/SiteInfo/SiteInformationWizardContent.swift
Fixes #12796. A previous PR, #12564, introduced some changes to the way spaces were handled in the domain registration form. Unfortunately, this wasn't entirely successful and has resulted in form validation failures due to fields containing unicode non-breaking spaces instead of actual space characters.
This PR fixes that by ensuring text field values are sanitised before being passed back to the delegate. See the first commit for this change.
I also took the liberty to improve the UX of the domain registration form while I was in there. The second two commits enable auto capitalization on fields in the form and allows the Next button to tab to the next available editable field.
**To test:**
* Access domain registration for one of your sites. I did this by commenting out code at the …
> Issue/12796 Fix domain registration failure due to spaces

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/12909
Related WordPressKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/197
To test:
1. Log in to a self-hosted site (without Jetpack).
2. Open the My Sites tab.
3. Open the Comments section.
4. Select a pending comment.
5. Tap "Approve" and confirm the comment is approved (doesn't revert to pending state).
6. Tap "Unapprove" and confirm the comment is unapproved (doesn't revert to approved state).
> Fix comment moderation on self-hosted sites

- WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
Fixes #12921
This works around the issue reported in https://github.com/wordpress-mobile/gutenberg-mobile/issues/1567 to ensure the `testTabBarNavigation()` doesn't fail due to the editor not being fully loaded. It will also prevent other flaky test failures due to slow editor loading in editor tests.
To test:
* Check the UI test runs on CircleCI to confirm that all tests pass, especially `testTabBarNavigation()`.
> Testing: Wait for block editor to be fully loaded before closing it

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
Enables the preformatted block in iOS for release 1.17.0
To test:
- Start a post using Gutenberg
- Add a preformatted block to the post
- See if it works correctly and interacts correctly with other blocks.
> Enable Preformatted block in Gutenberg.

- WordPress/ColorPalette.xcassets/Gray0.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray10.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray100.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray20.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray30.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray40.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray5.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray50.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray60.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray70.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray80.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray90.colorset/Contents.json
Based on spreadsheet:
To test:
Compare colors in spreadsheet to represented in ColorsPalette.xcassets
> Update Gray colors dark mode colors

- WordPress/ColorPalette.xcassets/Gray0.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray10.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray100.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray20.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray30.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray40.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray5.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray50.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray60.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray70.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray80.colorset/Contents.json
- WordPress/ColorPalette.xcassets/Gray90.colorset/Contents.json
The addition of dark appearance for gray colors (#12915) caused weird appearance issues in navigation bar that was displayed white bright in dark mode and table separators that appeared brighter. 
In this PR the colors are still updated to the right values according to https://github.com/Automattic/color-studio/blob/2.2.0/dist/color-properties-rgb.css
But their dark counterparts are no longer defined in ColorPalette.
> Removing dark appearance for gray colors

- Gemfile.lock
- Scripts/fastlane/Fastfile
- Scripts/fastlane/Pluginfile
- Scripts/fastlane/env/user.env-example
This PR updates the Fastlane configuration to switch binary upload from HockeyApp to MSAppCenter because of HockeyApp sunsetting.
1. Create a new [API Token in AppCenter](https://appcenter.ms/settings/apitokens).
2. Add a APPCENTER_API_TOKEN entry to your ~/.wopios-env.default with the token above.
3. Bump the internal version of the app.
4. `bundle install`.
5. Run `bundle exec fastlane build_and_upload_internal` and verify that the app is built and uploaded to App Center.
> Update Fastlane to work with AppCenter

- .circleci/config.yml
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme
- WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressUITests.xcscheme
- WordPress/WordPressTest/WordPressUnitTests.xctestplan
- WordPress/WordPressUITests/WordPressUITests.xctestplan
This PR converts our existing unit and UI tests to use the new test plans in Xcode 11. This doesn't change what tests are run or when, but it does remove the need for two build-for-testing steps on CircleCI. Both unit and UI test plans are linked to the WordPress scheme now (with unit tests as the default).
To test:
* Confirm all of the unit tests are run and passing on CircleCI.
* Confirm all of the UI tests are run on both iPhone and iPad and passing on CircleCI.
* In Xcode, confirm that when working with the WordPress scheme, unit tests are run by default and UI tests can be run by selecting the WordPressUITests test plan in the Test Navigator or under Product > Test Plan:
> Testing: Convert unit & UI tests to test plans

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergFilesAppMediaSource.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1265
This PR adds the option to select media items from the iOS Files App via "Other Apps" option.
This works for all media related blocks, and the user should be allowed to pick just the corresponding media types for the blocks.
For this to work, the `filters` property was needed from JS, but it wasn't given via `requestOtherMediaPick` methods. The `gutenberg` side changes are meant to allow this property to be passed on any `requestMediaPick` for any source.
`gutenberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1547
`gutenberg` PR: https://github.com/WordPress/gutenberg/pull/18303
**Note:**
- As shown in the GIF, there seems to be a bug on iOS 13 where the bar buttons on the Documents Picker are …
> [Gutenberg] Implement "Other Apps" media source option

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.xib
- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.xib
Refs #12906 
This enhances VoiceOver support for the Notifications page. 
The cells now have the `.button` trait so that it's more obvious that they can be tapped. I also added hints (66a9c26) for the notification kinds that I know of. I couldn't find information on how to _create sample notifications_ the following:
- `.post`
- `.user`
I increased the accessible width of the table headers and added `.heading` traits on them. This makes them navigatable via Headings using [the rotor](https://support.apple.com/en-ca/guide/iphone/iph3e2e3a6d/ios) and also just simply give out more useful information than a normal label. 
1. Turn VoiceOver on
2. Navigate to Notifications
3. Verify the changes have been implemented as described above. 
Only 1 reviewer is …
> [VoiceOver] Enhancements for main Notifications page

- WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
- WordPress/Classes/ViewRelated/Views/NoResults.storyboard
- WordPress/Classes/ViewRelated/Views/NoResultsViewController.swift
Refs #11487 and #12906. 
This changes the `NoResultsViewController` so that the full view is accessible instead of just the title and subtitle as suggested in #11487. This makes the “no results” message easily discoverable by VoiceOver users. They do not need to have their finger travel far to _find_ the message.
The title and subtitle are now also dictated together. 
Some attempts at announcing the “no results” message were done to no great results. More information about that starting at https://github.com/wordpress-mobile/WordPress-iOS/issues/11487#issuecomment-551319114 if you're interested. 🙂 
To make this work, I had to modify `NoResults.storyboard`:
- Made `noResultsView` cover the whole Safe Area
- Moved the `noResultsView` alignment and margins to …
> [VoiceOver] NoResultsView enhancements

- WordPress/WordPressUITests/Screens/BaseScreen.swift
- WordPress/WordPressUITests/Screens/FancyAlertComponent.swift
- WordPress/WordPressUITests/Screens/Media/MediaPickerAlbumListScreen.swift
- WordPress/WordPressUITests/Screens/Media/MediaPickerAlbumScreen.swift
This is similar to the fix in https://github.com/wordpress-mobile/WordPress-iOS/pull/12928, in that it ensures screens are fully loaded before continuing a test. This includes a fix for the flakiness that I believe @jkmassel saw in https://github.com/wordpress-mobile/WordPress-iOS/pull/12930#pullrequestreview-316542476.
To test:
* Ensure tests pass on both iPhone and iPad on CircleCI.
* Run tests locally (be sure to run `rake mocks` first to start the mocks server) and confirm you don't see any flaky test failures.
> Testing: Ensure screens are loaded before continuing

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Ref #12686 
This enables the Post Scheduling enhancement for internal testing.
To test:
- On a post, go to Post Settings > Publish.
- Verify the new 'Publish' page appears, and tapping the 'Date and Time' row displays the date and time selectors.
> [Post Scheduling] Enable scheduling enhancements for internal

- Podfile
- Podfile.lock
Update internal deps to released versions
To test:
- Make sure CI is green
> Update internal deps to released versions

- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergBlockProcessor.swift
- WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergImgUploadProcessor.swift
- WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergVideoUploadProcessor.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/Gutenberg/GutenbergImgUploadProcessorTests.swift
- WordPress/WordPressTest/GutenbergVideoUploadProcessorTests.swift
- WordPress/WordPressTest/MediaAssetExporterTests.swift
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1512
This PR improves the media processors used in Gutenberg media upload to check for blocks and don't relay on the id of media to be the first attributed.
To test:
- Create a video or img block
- Choose a video or img from the device
- Publish the post while the upload is still going
- Wait for the upload to finish while seeing the list
- When all the uploads are finished
- Open the post again
- Check that content is correct and pointing to remote videos
- Repeat using the media-text blocks.
> Improve media processors for gutenberg

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1525
This PR make sure that after the content of a post is set, the status of the media objects is refreshed to show the more recent state
To test:
- Start a new post using Gutenberg
- Add some image blocks to the post
- Save the post while media is still uploading
- Exit the editor
- Renter the editor
- Check that the media progress is refresh for all the media objects in the post as soon as the post is opened.
> Update media status when opening post in Gutenberg.

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/Services/MediaService.h
- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Blog/SiteIconPickerPresenter.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
- WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergStockPhotos.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController+FeaturedImageUpload.swift
- WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift
Fixes #https://github.com/wordpress-mobile/WordPress-iOS/issues/12629
While doing tests on others part of the media stack I run through this exception. After some investigation I found that media creation sometimes could fail if the blog or post (for me it only make sense post) objects provided to `createMediaWith` method in `MediaService` to be a temporary ID that then is update to a permanent ID and then not found on search later on.
I changed the code to actually pass the Blog or Post objects to make it harder for this to happen. I also change the media signature method to be ready signal that the Media returned can be nil and adopted the code that uses it to this scenario.
To test:
- Test the following media flows:
- Add media to posts (Aztec, Gutenberg)
- Add media using the media …
> Fix media crash

- WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergFilesAppMediaSource.swift
This PR fixes a build error on `develop` branch that happened by a PR that made mediaInserter return an optional media object, in parallel to the PR that implemented Files App media source on Gutenberg.
cc @SergioEstevao 
To test:
- Make sure that the project Builds and run.
> [Gutenberg] Handling mediaInserter now returning optional media object

- Scripts/localize.py
This PR fixes two warnings issued by `Scritps/localize.py`:
1. https://github.com/wordpress-mobile/WordPress-iOS/pull/12794 removed `WordPressComStatsiOS`, so this PR removes it from the list of the source frameworks.
2. https://github.com/wordpress-mobile/WordPress-iOS/pull/12580 added this helper file https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/WordPressTest/I18n.swift that triggers an error in `genstrings` because it passes a not literal string as the argument. Since this is only used as a helper for some tests, this PR makes sure it's not analyzed by `genstrings`.
_Note_: this is an ugly fix for an ugly script that's overdue for an update to new technologies. Since we'll have to throw this one away in order to be able to make use of some of the new …
> Fix warnings in localize.py

- WordPress/Classes/Services/SuggestionService.m
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
While testing another PR I noticed that the suggestions service (used in CommentViewController in Notifications) has a broken endpoint path, which results in a lot of 404 requests when you type a comment:
```
2019-11-19 19:25:13:862 WordPress[31045:3833400] [Rest API] ! The specified path was not found. Please visit https://developer.wordpress.com/docs/ for valid paths.
2019-11-19 19:25:14:106 WordPress[31045:3833400] [Rest API] ! The specified path was not found. Please visit https://developer.wordpress.com/docs/ for valid paths.
2019-11-19 19:25:14:545 WordPress[31045:3833400] [Rest API] ! The specified path was not found. Please visit https://developer.wordpress.com/docs/ for valid paths.
```
Ideally, we should write a remote for this service which uses the remote methods for …
> Fixes suggestions service endpoint path

- .github/PULL_REQUEST_TEMPLATE.md
With https://github.com/wordpress-mobile/WordPress-Android/pull/10554 we added a new item to the PR submitter checklist that reminds about adding unit tests where possible.
This PR makes the same change on WPiOS. 
> Add a step about unit tests to the PR submission checklist

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityDay.swift
Ref https://github.com/wordpress-mobile/WordPress-iOS/issues/7163#issuecomment-555523582
WPShared PR: https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/226
To test:
- Go to Stats > Insights > Posting Activity.
- Select 'View more'.
- Verify `🔵 Tracked: stats_posting_activity_view_more_tapped` appears in the console.
- Select a specific day.
- Verify `🔵 Tracked: stats_posting_activity_day_tapped` appears in the console.
> [Stats] Tracking Posting Activity 'View more' and day selection.

- RELEASE-NOTES.txt
- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/Classes/Utility/ZendeskUtils.swift
Fixes #12297 
As noted on #12297 , the problem was:
When _any_ request is created, we automatically take the `Current` activity log and populate the `System Status Report` field with it. If the log is big enough, it will exceed the field limit. This will cause _any_ request to fail (even if you're not attaching anything). 
The limit on that field type isn't specified, and I got no response from Zendesk support. So I did some testing, and found that it'll handle about 50k characters. So that's the limit.
If the log text exceeds that limit, the text is truncated from the beginning so we get the last 50k characters (i.e. most recent).
To test:
On an account with a large `Current` activity log:
- Go to Me > Help & Support > Contact us.
- Attempt to send a message.
- Verify it sends.
- Bonus: …
> Support: Truncate the log text so it fits in the ticket field.

- Podfile
- Podfile.lock
Fixes #12688 
Updates Aztec version to bring fixes for copy/paste in dark mode.
After the fix is confirmed I will need to release a new version of Aztec and update the reference here.
To test:
- Set your device to dark mode
- Using the Aztec editor, copy text from other apps that don't support dark mode and/or have black text on white background
- Check that text is show correctly
- Double check the same thing on the Gutenberg editor
> Fix copy/paste in dark mode for Aztec.

- WordPress/WordPressTodayWidget/TodayViewController.swift
Fixes #12990
To test:
- Go to Stats, and select a site to use for the Today widget.
- Go to the widget.
- Verify the Visitors value matches Visitors from the Insights > Today stat. 
> Today Widget: Correct value used for Visitors

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Ref #12992
This disables internal testing for Post Scheduling date/time pickers due to the above issue.
To test:
This feature is still present in dev, so you'll still see it. So verify the Feature Flag setting is correct.
> Post Scheduling: Disable internal testing

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Me/MeViewController.swift
Fixes #13000.
The Me screen currently shows empty until a network request to refresh the current account details is complete. This PR moves the call to load the view model so that it's displayed instantly.
**To test:**
* Log in and check you can view the Me screen without seeing it blank at all
* Quit the app and relaunch, and check the Me screen isn't blank
* Quit the app, turn on airplane mode, relaunch the app and check the Me screen isn't blank
> Fix empty Me screen due to network conditions

- WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergImageLoader.swift
Fixes n1 from https://github.com/wordpress-mobile/gutenberg-mobile/issues/1593
In this PR, we avoid using the PhotonAPI helper, which was aggressively stripping the image size properties from the URL.
The `downloadImage` method of `RCTImageURLLoader` is used by the JS function `Image.getSize()` to retrieve the original image and calculate its size.
I also took this opportunity to add a simple in-memory image cache to avoid fetching the same image multiple times.
To test:
- On a WPCom site:
- Add an image block.
- Add an image from any source.
- Change the image size to thumbnail.
- Check that the size of the image visually changes.
> [Gutenberg] Image size improvements

- WordPress/Classes/System/WordPressAppDelegate.swift
After testing the SIWA, and subsequently removing the Apple 2fa from my test account, I notice I was being logged out of the app after every launch (sometimes with a crash).  I traced the cause back to `WPAppleIDKeychainUsernameKey` being used as a service name rather than `WPAppleIDKeychainServiceName`. This was interfering with the delete call to the keychain so the apple ID was always checked at launch and assumed revoked. 
To test:
For a full test, create an Apple id to use for testing, setup 2fa then create a wpcom account via SIWA.   Then find the email from apple that will let you roll back 2fa and disable SIWA from Apple's side.  You can confirm the glitch from a `develop` branch by logging in to the app with a normal WPCom flow.  Finally, switch to this branch and log in to the …
> Use the correct const for the service name.

- WordPress/Classes/Utility/ContextManager.m
- WordPress/Classes/Utility/Logging/SentryStartupEvent.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Refs #12338
In https://github.com/wordpress-mobile/WordPress-iOS/pull/12569 we changed the Core Data startup error to a proper exception. However, we still unable to have more details about this issue. Mainly because:
1. Xcode reports don't give much information. They just state that an objc exception was thrown but no details;
2. No data is being sent to Sentry
This aims to fix number 2.
Add those lines in `ContextManager.m` right before `return _persistentStoreCoordinator;` inside `(NSPersistentStoreCoordinator *)persistentStoreCoordinator`:
```swift
NSError *errMsg = nil;
errMsg = [NSError errorWithDomain:@"aaa" code:1001 userInfo:@{ NSLocalizedDescriptionKey:@"aaa" }];
[errors addObject:errMsg];
errMsg = [NSError errorWithDomain:@"bbb" code:1001 userInfo:@{ …
```
> Track Core Data startup errors to Sentry

- WordPress/Classes/ViewRelated/Me/MeViewController.swift
This PR removes the "Notification settings can now be found in the Notifications tab" hint that was present in the Me screen, now that the settings have been moved for a couple of releases.
Android equivalent PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10840
**To test**
* Access the Me tab
* Check you don't see the above text underneath the App Settings row in the table
> Me: Remove Notification Settings hint text

- Scripts/fastlane/Fastfile
This PR updates Fastlane to the new organization name used in AppCenter.
- Run `bundle exec fastlane build_and_upload_internal` and verify that the build is successfully uploaded to AppCenter.
- Delete the build from AppCenter.
- Run the installable build and verify it finishes without errors. 
- Verify that the download link is correct. 
> Update Fastlane to new org name in AppCenter

- WordPress/Classes/ViewRelated/Post/PostCardCell.xib
- WordPress/Classes/ViewRelated/Post/PostCompactCell.swift
- WordPress/Classes/ViewRelated/Post/PostCompactCell.xib
- WordPress/WordPressTest/NotificationUtility.swift
- WordPress/WordPressTest/PostCompactCellGhostableTests.swift
- WordPress/WordPressTest/PostCompactCellTests.swift
Fixes #12675 
Following wordpress-mobile/WordPress-Android#10559's model.
|---|:---|
| ![alt before](https://user-images.githubusercontent.com/198826/66603404-5d3ec900-eb69-11e9-83cb-83a6a89ad261.png)| ![alt after](https://i.imgur.com/PENsVNT.png) |
> Fix Compact Post List to show date

- WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+Search.swift
Fixes #13037
| Light mode | Dark mode |
| <img src="https://user-images.githubusercontent.com/7040243/70258699-6c0dba80-176b-11ea-969b-91fa95d965c9.png" width="300" >  | <img src="https://user-images.githubusercontent.com/7040243/70258705-70d26e80-176b-11ea-948d-b1ee33fcef73.png" width="300">  |
Use the app in both light and dark mode and check the search bar appearance.
It seems that, for some reason, Apple changed the default color for the `searchTextField`. This PR updates it with neutral with zero shade. This changes slightly the colors of the component, that's why I'm requesting a designer review.
> Fix search bar color

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Refs #12953
This accessible element is the title placeholder (`UILabel`) and can be confused with the title text field. 
Disabled if nothing is selected | Enabled when a media is selected
Making it visible could make it more discoverable and makes it easier to understand how to use the UI. If VoiceOver is turned off, the app will use the original behavior of hiding or showing the button. 
I also changed the `accessibilityLabel` of the button to `“Insert selected”` to make it more obvious **when** it will be enabled. 
1. Turn VoiceOver on.
2. Create a new post (Aztec)
3. Navigate by swiping right or left. Confirm that there is only one accessible “Title“ element and it can be activated
1. Turn VoiceOver on.
2. Create a new post (Aztec)
3. Navigate to the content text field …
> [VoiceOver] Enhancements for Aztec editor

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergImageLoader.swift
This PR fixes an issue with gallery blocks, where the image downloaded is of a noticeable lower quality than the expected:
**Expected:**
**Actual result:**
To test:
- Test the gallery block, adding 3 images.
- Check that the 3rd image has good quality.
- Add an image block with an image in a WPCom site.
- Set the image size to Thumb
- Check that the image size changes and looks smaller.
> [Gutenberg] Fix guten-gallery image size.

- WordPress/Classes/Stores/StatsInsightsStore.swift
- WordPress/Classes/ViewRelated/Stats/StatsViewController.m
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/AllTimeWidgetStats.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/TodayWidgetStats.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
- WordPress/WordPressAllTimeWidget/MainInterface.storyboard
- WordPress/WordPressTodayWidget/TodayViewController.swift
Ref #13030 
This implements data handling for the 'All Time' widget.
- When Insights are accessed in the WP app, 'All Time' data is stored in `AllTimeData.plist`.
- The widget loads and saves data from/to the plist.
- The widget loads site information from `UserDefaults`, and uses it to fetch stat data.
The data is displayed in plain labels in the widget to facilitate testing this. The real UI will be implemented in a future PR.
To test:
---
- Go to Stats > Insights.
- Select `Widgets` in the nav bar, and then `Use this site`.
- Add the `WordPress All-Time` widget to your Today view.
- Verify the data displayed matches Insights > All-Time in the app.
---
- In the app, switch sites and `Use this site` again to change the site used for widgets.
- Verify the All Time widget updates …
> [All Time Widget] Add data handling

- WordPress/Classes/ViewRelated/Post/PostPostViewController.swift
Fixes #13040. The methods for changing the appearance of a `UINavigationBar` changed in iOS 13. This PR updates `PostPostViewController` to use the new way of creating a transparent nav bar.
**To test:**
* Publish a new post
* Tap "View" when the published notice appears at the bottom of the screen
* Check the navigation bar isn't visible in the post-post screen
> Update PostPost navigation bar to use iOS 13 appearance methods

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
In order to get started with the Post Reblogging feature, I added a `postReblogging` feature flag in the `FeatureFlag` enum. At the moment, it will only enable the feature for local development.
> Feature flag for Post Reblogging

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/AztecAttachmentDelegate.swift
- WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
- WordPress/Classes/ViewRelated/Post/Revisions/Browser/Preview/RevisionPreviewTextViewManager.swift
This way the placeholder images will adapt to the current interface
mode on the device.
Fixes #https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1236
**Note**: At this PR I'm not fixing the placeholders when the user switches from dark mode to light mode, while the editor is open. This will need a fix in the Aztec lib to force a refresh of the media attachments.
To test:
- Start the app using dark mode
Scenario 1:
- Open a new post
- Insert a new media from device
- Check that the placeholder image show properly while the final image is not ready
Scenario 2
- Open a post with several images
- Check that the placeholder images show properly while the final images are loading.
Run the same tests with image/video/files
Run the same tests with light mode to make sure all is ok
PR …
> Make placeholder images tinted with text color.

- WordPress/Classes/Extensions/NotificationCenter+ObserveMultiple.swift
- WordPress/Classes/ViewRelated/Post/Scheduling/ChosenValueRow.swift
- WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Refs #12959.  
This fixes only a few things in #12959 but it felt like a good stopping point. 🙂 
Currently, you cannot dismiss the picker by using the global escape (Z). The Close button is also hidden when in portrait mode. With VoiceOver turned on, you basically have to continue and pick a date and time to dismiss the picker. 
- The Close button is now always shown in iPhone portrait mode if VoiceOver (or Switch Control) is turned on
- You can dismiss the picker using VoiceOver by using the global escape (making a Z with 2 fingers)
Heading | Close Button
I made the “Choose a date” a heading to (possibly) better clarify what the user is currently interacting with. The Close button was also missing an accessibility label. 
1. Turn VoiceOver on
1. Navigate to Post Settings …
> [VoiceOver] Published Date Picker enhancements

- WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
Fixes #12795. This PR ensures all icons in the Reader menu use the same tint color.
To test:
* Build and run and navigate to the Reader menu. You'll best be able to see this change if you have the Automattic item in your Reader.
* Ensure the colors of the list icons are all the same.
> Standardize Reader menu list icon colors

- WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
Fixes #12283. This PR just slightly adjusts the alpha component of the stats chart highlight background to make the bar itself stand out more.
**To test:**
* Build and run, select a bar in stats and check it looks like the above
> Stats: Lighten selected highlight color on bar charts

- Scripts/fastlane/Fastfile
- WordPress/WordPress.xcodeproj/project.pbxproj
https://github.com/wordpress-mobile/WordPress-iOS/pull/13053 added a new All Time Widget, but it didn't include the configuration of the profiles for all the schemes. 
This PR just adds the new profiles and the related configuration. 
- Check that CI is green. 
- Check that an Installable build has been successfully generated. 
- Check that a local build on your machine is successful. 
@cameronvoell you'll need to rebase your branch after this is merged into `develop` in order to fix Installable Builds. 
> Add All Time Widget signing configuration

- Podfile
- Podfile.lock
Fixes #13062. Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/11488. 
Details for testing are in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/166. That must be reviewed first.
> [VoiceOver] Update WordPressAuth to 1.10.5-beta.3

- WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.swift
- WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
Refs #12127. 
This doesn't completely _fix_ #12127. I feel like there is still more we can do with the Domains step. But I'm not quite sure what those are. This PR hopefully makes the UI a bit easier to understand by VoiceOver users. 
To help guide what needs to be done after entering something in the search field, I added a “Suggestions updated” announcement for VoiceOver. This idea was taken from [Android's implementation](https://github.com/wordpress-mobile/WordPress-Android/commit/990f0de44ea1702f87bc28c81e8bf1ac810f0fcd) which does the same thing.
By default, the _Create Site_ button is only shown when the user has selected a domain. My theory related to this is UI elements that are hidden and shown after an action is not ideal for VoiceOver users. There is usually no indication that …
> [VoiceOver] Site Creation → Domains enhancements

- WordPress/Classes/ViewRelated/Post/Scheduling/CalendarCollectionView.swift
Fixes #13113
Demo Video: https://www.dropbox.com/s/489k5s2tpy00omi/iPhone%208%20-%2013.3%20-%20Calendar%20Paging%20-%20Fix.mov?dl=0
**To test:**
2. Tap the + button to create a post
3. Tap the `...` tab bar item to show more controls
4. Tap Post Settings
5. Tap the Publish row
6. Tap Date & Time
7. Swipe the calendar to change months
7.a While swiping move your finger/cursor up and down
**PR submission checklist:**
> Enables direction lock on the post scheduling calendar view

- Podfile
- Podfile.lock
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/13086. Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/12188.
Please see https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/170 for testing and reviewing. 🙂
> [VoiceOver] Self-hosted Login Flow enhancements

- WordPress/Classes/ViewRelated/Comments/EditCommentViewController.m
Fixes #13121
| Device | iOS Version | Video |
| --- | --- | --- |
| iPhone 5s | 11.4 | https://www.dropbox.com/s/37xv4le0k6hzwbd/iPhone%205s%20-%2011.4.mov?dl=0 |
| iPhone 8 | 12.4 | https://www.dropbox.com/s/go1481pxp4o0inu/iPhone%208%20-%2012.4.mov?dl=0 | 
| iPhone 11 Pro Max | 13.3 | https://www.dropbox.com/s/volcro0h2yjxvx7/iPhone%2011%20Pro%20Max%20-%2013.3.mov?dl=0 | 
| iPad Air 3rd Gen | 13.3 | https://www.dropbox.com/s/eavcgnnfx8xl43z/iPad%20Air%203rd%20Gen%20-%2013.3.mov?dl=0 |
**To test:**
1. Locate a comment to edit
2. Tap the Edit button
3. Tap the cancel button to close the overlay
**PR submission checklist:**
> Removes the Done button from the EditCommentViewController

- WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift
- WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Reply.swift
Fixes #12918 subtask: Update the UI for the existing `ReplyTextView`
**To test:**
1. Enter any comment flow (reader, notification, comments)
**Screenshots**
| Device | Mode | Placeholder | Text |
|---|---|---|---|
| iPad Air 12.4 | Light | <img src="https://user-images.githubusercontent.com/793774/70844948-b6430b80-1dfd-11ea-9421-06621635d38a.png" width="50%"/> | <img src="https://user-images.githubusercontent.com/793774/70844949-b6430b80-1dfd-11ea-960d-2def4dca464e.png" width="50%"/> |
| iPhone 11 Pro Max 13.3 | Light | <img src="https://user-images.githubusercontent.com/793774/70844950-b6430b80-1dfd-11ea-8d6a-1934ba50f0a5.png" width="50%"/> | <img src="https://user-images.githubusercontent.com/793774/70844953-b6430b80-1dfd-11ea-83b3-b460ce775b30.png" width="50%"/> |
| iPhone 11 Pro Max …
> Commenting: Refreshes the ReplyTextView UI colors and font

- WordPress/Classes/Models/Blog.m
When replying to a comment in Notifications, if you type the @ symbol you'll be presented with a list of users you can @-mention. This functionality had a check on it for if the current user `isAdmin`, however the suggestions service that powers it also seems to work if you're not an admin. I've removed this check so it should work in more situations.
**To test:**
* Find a notification for a reply or comment or mention for a site that you have admin access for.
* Start typing a reply and type the @ symbol. Check the autocomplete menu appears.
* Change your access to the site to something other than admin (or remove yourself entirely) – if you're unsure how, ask me! :)
* Log out and back into the app to force it to refresh the site details so it knows you're no longer an …
> Removes check for `isAdmin` for mention suggestions

- WordPress/Classes/Services/PeopleService.swift
- WordPress/Classes/ViewRelated/Blog/SiteIconPickerPresenter.swift
- WordPress/Classes/ViewRelated/Media/Giphy/GiphyMedia.swift
- WordPress/Classes/ViewRelated/Ratings/AppFeedbackPromptView.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Tools/PromptViewController.swift
Autocorrecting with `swiftlint` was leading to these changes. I figure we might as well change them since the Source Editor doesn't properly display these with more than two forward slashes.
All comments so there's no functionality change.
> Fix MARK formatting across several files

- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityMonth.swift
Refs #12971, #11995.
This improves the accessibility of the [`PostingActivityMonth`](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Stats/Insights/Posting%20Activity/PostingActivityMonth.swift) component. 
Currently, VoiceOver users are able to access all the days within the component. This is a bit problematic if the user tries to navigate the page by swiping right. They would have to go through one hundred tiny UI elements before they can reach the bottom of the page. 
This is an attempt to make this better. 
[before video (15s)](https://drive.google.com/file/d/12hC_VO-1BvJQikFvS4C3bXbZDBppuPF5/view?usp=sharing)       |       [after video (23s)](https://drive.google.com/file/d/12mFSze8u0pvlwhpkSsGw0Kc8WXFBMx-V …
> [VoiceOver] Improvements for Stats Posting Activity 

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Enables #12686, the Post Scheduling flow with Calendar picker.
Refer to the [Post Scheduling Enhancements label](https://github.com/wordpress-mobile/WordPress-iOS/labels/Post%20Scheduling%20Enhancements) to see related work.
To test:
- Create a post
- Enter Post Settings
- Change the Publish date to another value
> Post Settings: Added a new Calendar picker to select a Post's publish date
> Enable Feature Flag for Post Scheduling Calendar Picker

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
adds WPAnalyticsStatReaderArticleDetailReblogged for Post Reblogging tracks
Ref: #12960
WPShared PR: wordpress-mobile/WordPress-iOS-Shared/pull/236
It will be possible to test once the feature is merged
> Adds tracks for post reblogging

- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
- WordPress/Classes/ViewRelated/Reader/ReaderReblogAction.swift
- WordPress/WordPressTest/ReaderReblogActionTests.swift
Ref #12960
- Build and run the app
- Go to the reader
- Tap on the `reblog` button in the post list
- check that the console contains the following log:
- `🔵 Tracked: reader_article_reblogged <blog_id: [some_id], post_id: [some_id]>`
- Go back to the post list
- Tap on a post to enter the post detail
- Tap on the `reblog` button
- Check that the console contains the following log:
- `🔵 Tracked: reader_article_detail_reblogged <blog_id: [some_id], post_id: [some_id]>`
- added an `OriginType` enum in `ReaderReblogAction` to distinguish between detail and list
- added an extension to `ReaderReblogAction` containing a `trackReblog(_ :, _ : )` method that will execute the track
- `changed the `execute( )` method to take `OriginType` as an additional parameter
there was a missing `break` in the …
> Analytics tracks for Post Reblogging

- RELEASE-NOTES.txt
- WordPress/Classes/Stores/StatsPeriodStore.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Fixes #13138 
This change forces the period queries to be cancelled and restarted when period data is refreshed. 
I referred to the PR that fixed this problem initially (https://github.com/wordpress-mobile/WordPress-iOS/pull/11495), and it appears somewhere along the way the `forceRefresh` flags got swapped. I simply swapped them back.
To test:
- Got to Stats > Periods.
- Quickly switch between period tabs.
- Verify the tab you end up on displays the correct data.
> Stats: force refresh when Period changes

- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Fixes #12282
1. While offline, run the app
2. Create a new post and an image
3. Tap "..." > "Save as Draft"
4. Add another image
5. Go back online, everything should work :)
(If you follow these steps in `develop` the app will crash)
As @etoledom [mentioned](https://github.com/wordpress-mobile/WordPress-iOS/issues/12282#issuecomment-566471145) the problem is not only related to Media. What was happening is that `PostCoordinator` was deleting a revision being used by the Editor. This caused a lot of trouble.
The idea of this PR is to remove this deletion from `PostCoordinator` so this problem will not happen anymore. This logic is now in the Editors.
However, you can see the content in the editor blinking when the content is updated. I wonder if this is a bad experience, if it is, I'd …
> Do not delete revision outside from the editors

- RELEASE-NOTES.txt
- WordPress/Classes/System/WordPressAppDelegate.swift
Fixes #11250 
Fixes #11377
- Moves the appearance proxy up earlier during the launch cycle
- Removes preloading of the noto regular font. This code was a workaround from 4 years ago and I was unable to notice a difference in the places which used the font.
<div style="float: left">
</div>
- Log in to the app
- Go to https://wordpress.com/me/security/connected-applications and disconnect WordPress for iOS
- Navigate somewhere in the app, any network request should trigger the login screen
- Navigate to the Notifications view and view a Comment notification cell
> Load appearance proxy earlier in launch

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Fixes crash when the App is launched by certain notifications after being inactive.
Fixes #12669 
You'll need to enable push notifications for our development environment.  This can be done by logging into your WordPress Sandbox, and running these commands:
```bash
cd /home/wpcom/public_html/bin/mobile-push-notification
svn up
php push-notifications-server.php -type=push -qi=10 -app_id=5
```
Just run the testing steps below in our `develop` branch and you should see an exception being raised.
1. Make sure push notifications are running for our dev environment (see "Before Testing").
2. Run the App.
3. Immediately send it to brackground.
4. Comment with another user in one of your test blogs so that a notification is sent to your device.
5. Tap on the notification.
The notification should …
> Fixes crash when the App is launched by certain notifications after being inactive.

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
This PR brings [this fix sent to develop](https://github.com/wordpress-mobile/WordPress-iOS/pull/13155) to the `release/13.9` branch.
Fixes crash when the App is launched by certain notifications after being inactive.
Fixes #12669 
You'll need to enable push notifications for our development environment.  This can be done by logging into your WordPress Sandbox, and running these commands:
```bash
cd /home/wpcom/public_html/bin/mobile-push-notification
svn up
php push-notifications-server.php -type=push -qi=10 -app_id=5
```
Just run the testing steps below in our `develop` branch and you should see an exception being raised.
1. Make sure push notifications are running for our dev environment (see "Before Testing").
2. Run the App.
3. Immediately send it to brackground.
4. Comment with …
> Crash when tapping on certain notifications

- WordPress/WordPressShareExtension/TextBundleWrapper.m
While testing a high-impact Sentry issue (https://sentry.io/organizations/a8c/issues/1340948093/?project=1438083) I came across several warnings from the static analyzer.  One of them was a memory leak that's fixed by this PR.
The reason for the memory leak is that `UTTypeCopyPreferredTagWithClass()` returns a new `CFStringRef` which needs to be manually released after we're done working with it (using `CFRelease(stringRef)`).
By replacing the `__bridge` cast with a `__bridge_transfer` cast, we're just letting the compiler know that it's fine for ARC to take that string reference over, and release it when we're done.
Just run the static analyzer in `develop` and notice it points to a memory leak in the line that's modified by this PR.
Then run the static analyzer in this branch and notice …
> Fixes a memory leak.

- WordPress/WordPressShareExtension/TextBundleWrapper.h
While testing a high-impact Sentry issue (https://sentry.io/organizations/a8c/issues/1340948093/?project=1438083) I came across several warnings from the static analyzer.  This PR fixes a nullability issue we have.
The static analyzer is rightfully complaining about this method returning `nil`:
https://github.com/wordpress-mobile/WordPress-iOS/blob/726379543f13492d52841532846a60ed2e5a1931/WordPress/WordPressShareExtension/TextBundleWrapper.m#L81-L85
While it's declared as not being able to return `nil` (due to `NS_ASSUME_NONNULL_BEGIN` on top):
https://github.com/wordpress-mobile/WordPress-iOS/blob/726379543f13492d52841532846a60ed2e5a1931/WordPress/WordPressShareExtension/TextBundleWrapper.h#L10-L33
While this may look like a minor fix at first, this bug is (theoretically) quite capable …
> Improves the nullability info in TextBundleWrapper.h (potential Crasher).

- WordPress/WordPressShareExtension/TextBundleWrapper.m
While testing a high-impact Sentry issue (https://sentry.io/organizations/a8c/issues/1340948093/?project=1438083) I came across several warnings from the static analyzer.  This PR just silences some of those warnings.
The warnings silenced in this PR are fairly harmless, but I took the opportunity to clean them up, in order to reduce the noise we get from the static analyzer.
Just run the static analyzer in `develop` and notice the warnings for the modified lines.
Then run the static analyzer in this branch and notice the alerts are gone.
> Silences several static analyzer warnings.

- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #n/a
The `Resources` folder was inadvertently moved into the `Credentials` folder with https://github.com/wordpress-mobile/WordPress-iOS/pull/13034.
This moves the Resources back to the main directory.
To test:
- Run the app. Verify resourcy things appear. Like icons, the launch screen, or the Reader News card.
> Move Resources folder out of Credentials.

- Podfile
- Podfile.lock
WPKitiOS Ref: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/206
To test:
- Run the app and scroll through the Reader section
- Check the Memory Graph Debugger for reported leaks
> Reference WordPressKit fix for dataRequest leak

- WordPress/Classes/ViewRelated/System/FancyAlertViewController+SavedPosts.swift
Fixes #13149 
Removed "(Yet! We're working on it)" from the alert that comes up when you save a reader post for later reading.
1. Launch the App and go to the reader.
2. Tap on a post.
3. Tap "Save" in the bottom left corner.
Make sure the part of the message that read "(Yet! We're working on it)" is no longer in the alert, as requested in #13149
> Updates some text for the reader's save-for-later feature.

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/MediaEditor/Enums/MediaEditorStyle.swift
- WordPress/MediaEditor/MediaEditor.swift
- WordPress/MediaEditor/MediaEditorHub.storyboard
- WordPress/MediaEditor/MediaEditorHub.swift
- WordPress/MediaEditor/MediaEditorImageCell.swift
- WordPress/MediaEditor/MediaEditorThumbCell.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/MediaEditor/MediaEditorHubTests.swift
- WordPress/WordPressTest/MediaEditor/MediaEditorTests.swift
Ref #13102
This PR adds the capability to show multiple images and to navigate between them on the Media Editor. Editing a selected image and tapping Done will be addressed in a future PR.
First, in `GutenbergViewController.swift` replace the function `gutenbergDidRequestFullscreenImage` by this one:
```swift
func gutenbergDidRequestFullscreenImage(with mediaUrl: URL) {
gutenbergDidRequestMediaEditor(with: mediaUrl, callback: { _ in })
}
```
And inside `gutenbergDidRequestMediaEditor` give the `image` multiple times to the MediaEditor, like this (line 447):
```swift
let mediaEditor = WPMediaEditor([image, image, image, image, image, image, image, image, image, image])
```
You can test the same thing in Aztec, just pass the same image multiple times.
You can swipe between the images, the …
> Show multiple images

- WordPress/Classes/Extensions/UIView+ExistingConstraints.swift
- WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/Extensions/UIView+ExistingConstraints.swift
This PR silences some auto-layout warnings.
This is NOT high priority - but it's something I found a quick solution for while researching other issues.
1. Run the App in `develop`.
2. Place a breakpoint here:
https://github.com/wordpress-mobile/WordPress-iOS/blob/5e9aa81f67082e17b4f6b15d608f79f7898c074b/WordPress/Classes/ViewRelated/Post/WPStyleGuide%2BPosts.swift#L64
3. Run the app and open the posts list for one of your sites.
Check that when that breakpoint hits, stepping over it will show up a warning.
Repeat the reproduction steps in this branch and notice the warning is gone.
> This PR silences some auto-layout warnings.

- WordPress/Classes/ViewRelated/Stats/Charts/Charts+AxisFormatters.swift
- WordPress/Classes/ViewRelated/Stats/Charts/Charts+Support.swift
- WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
- WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
- WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
- WordPress/Classes/ViewRelated/System/FilterTabBar.swift
Fixes #12971. Refs #11995.
This prioritizes fixing the user-reported issue #12971. But I also included some little things along the way. 
The user reported that it is not easy to identify Visitors from Views. This adds labels to the bar chart items. 
The label only applies in stacked bar charts. This is the default behavior from the Charts library. See `BarChartRenderer.createAccessibleElement` for that. 
VoiceOver reads these buttons without pause. Which is quite odd when you hear it. This PR improves that by making use of [`accessibilityLabel` and `accessibilityValue`](https://github.com/wordpress-mobile/WordPress-iOS/blob/4d966872a41140e9a3d483b6ebe369dfbe50f399/WordPress/Classes/ViewRelated/System/FilterTabBar.swift#L11-L13) for pausing. I also added …
> [VoiceOver] Stats Overview Improvements

- WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
Fixes #13191. Refs #11995. 
I tried a few things to figure out the reason for this. 
Nope
I tried posting `.layoutChanged` and `.screenChanged` notifications and that didn't work. 
Nope. The tab press event is on the main thread. 
I experimented by not recreating the `ChartView` after it's been created once. I just removed it from the view hierarchy. It looks like even though the `ChartView` is no longer in the view hierarchy, VoiceOver would still consider it as accessible. ¯\\\_(ツ)\_/¯
By luck, I found that forcing `chartContainerView` to declare its `accessibilityElements` fixes this. 
https://github.com/wordpress-mobile/WordPress-iOS/blob/5e04dff5ff0c56b6e00fa72bebec3630213463dd/WordPress/Classes/ViewRelated/Stats/Period%20Stats/Overview/OverviewCell.swift#L213
I'm still not sure why …
> [VoiceOver] Fix VoiceOver reading the previous bar chart

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/Media/MediaImageExporter.swift
- WordPress/WordPressTest/MediaURLExporterTests.swift
Fixes #13018
With this PR we will use the last path component to name the exported file. This will then be used to name the media asset when importing the url
to the media library.
To test:
1. Choose an image from your iPhoto library and save to files. Select either iCloud Drive or On My iPad).**Note**: Make sure the file is a JPEG or PNG, by default the new iPhone devices save images on HEIC format that are not accepted directly in WordPress sites. To go around this you can go to Camera settings and select to save the photos in a "Compatible format"
2. Rename the image and save.
3. Open the WordPress app and go to Media > + to add a new image.
4. Select 'Other Apps' to open files library (whether you select from On My iPad or iCloud Drive the same behaviour happens)
5. Select the renamed …
> Use filename of files exported from other apps to name media objects.

- WordPress/MediaEditor/Capabilities/Crop/MediaEditorCropZoomRotate.swift
- WordPress/MediaEditor/Capabilities/MediaEditorCapability.swift
- WordPress/MediaEditor/MediaEditor.swift
- WordPress/MediaEditor/MediaEditorCapabilityCell.swift
- WordPress/MediaEditor/MediaEditorHub.storyboard
- WordPress/MediaEditor/MediaEditorHub.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/MediaEditor/MediaEditorHubTests.swift
- WordPress/WordPressTest/MediaEditor/MediaEditorTests.swift
Fixes #13104
Depends on https://github.com/wordpress-mobile/WordPress-iOS/pull/13171
This PR shows all the available capabilities (so far, only crop/zoom/rotate) and the user can manipulate the image.
First, in `GutenbergViewController.swift` replace the function `gutenbergDidRequestFullscreenImage` by this one:
```swift
func gutenbergDidRequestFullscreenImage(with mediaUrl: URL) {
gutenbergDidRequestMediaEditor(with: mediaUrl, callback: { _ in })
}
```
And inside `gutenbergDidRequestMediaEditor` give the `image` multiple times to the MediaEditor, like this (line 447):
```swift
let mediaEditor = WPMediaEditor([image, image, image, image, image, image, image, image, image, image])
```
You can test the same thing in Aztec, just pass the same image multiple times.
1. Tap the crop button
2. …
> Crop media when showing multiple images

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/MediaEditor/Extensions/PHAsset+AsyncImage.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #13175
Depends on https://github.com/wordpress-mobile/WordPress-iOS/pull/13174
This PR adds support to use `PHAsset`s in the Media Editor.
I've also added a Feature Flag to allow it to be tested in Aztec (Gutenberg is our main target but it doesn't support multiple images yet).
1. Add a single image and insert it
2. The Media Editor should appear and show the crop/zoom/rotate capability right away
1. Add multiple images and tap "Insert X"
2. The Media Editor should appear showing all the selected images
> Adds support to PHAsset

- Podfile
- Podfile.lock
Updates WordPressAuthenticator to `1.10.6-beta.2` https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/174
> Update WordPressAuthenticator to 1.10.6-beta.2

- RELEASE-NOTES.txt
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
- WordPress/WordPressTodayWidget/TodayViewController.swift
Ref #12702 
This abbreviates the `Today` and `All-Time` widget values to match the app. That is, any number larger than 10,000 will get abbreviated.
To test:
- On a site with high traffic, go to Stats > Widgets > `Use this site`.
- Tip: en.blog is a good one.
- If necessary, add the `Today` and `All-Time` stats to the Insights view. Make note of the values.
- Add the `Today` and `All-Time` widgets to the Today view.
- Verify the widget numbers are abbreviated as they are in the app.
- Hack: `Today` is a bit difficult to verify. You can manually set the values in `TodayViewController:updateStatsLabels` to see the abbreviation. Of course this won't match the app, but it uses the same abbreviation logic.
**Insights All-Time:**
**Widget All-Time:**
> Stats Widgets: Abbreviate large values

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/MediaEditor/AsyncImage.swift
- WordPress/MediaEditor/Enums/MediaEditorStyle.swift
- WordPress/MediaEditor/Extensions/UIImage+AsyncImage.swift
- WordPress/MediaEditor/MediaEditor.swift
- WordPress/MediaEditor/MediaEditorHub.storyboard
- WordPress/MediaEditor/MediaEditorHub.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/MediaEditor/MediaEditorHubTests.swift
- WordPress/WordPressTest/MediaEditor/MediaEditorTests.swift
- WordPress/WordPressUITests/Screens/Editor/AztecEditorScreen.swift
Ref #13188
Depends on https://github.com/wordpress-mobile/WordPress-iOS/pull/13176
This PR implements the feature to return all images after tapping "Done" in Media Editor. It will returned all the images — including the ones that were edited.
It also updates the integration with Aztec and Gutenberg.
*Note: We're using Aztec to test this PR to take advantage of the multiple images since Gutenberg doesn't have support for it yet. Our main goal's still Gutenberg.*
1. Using Aztec, selecting multiple images
2. Edit any image
3. Tap "Done"
4. The images should be uploaded — including the ones that were cropped/zoomed/rotated
> Return all images

- RELEASE-NOTES.txt
- WordPress/Classes/System/WordPressAppDelegate+openURL.swift
Fixes #13194 
The problem was that the site ID used for stats was being overwritten by the site ID from the widget. To resolve this, the selected site ID is restored when the widget's Stats modal is dismissed. The Stats view is then refreshed for the correct site ID.
To test:
- Add the `Today` and/or the `All-Time` widget to the Today view.
- In the app:
- Select a site. Go to Stats > Widgets > `Use this site`.
- Select a different site, and go to Stats.
- Close the app.
- Return to the Today view and tap a widget.
- The app is launched, and a modal is displayed with the Stats for the widget site.
- Tap `Done` to close the modal.
- Verify the Stats view then displays the Stats for the selected site (not the widget site).
> Stats: restore selected site ID when widget Stats modal is dismissed

- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
Closes https://github.com/wordpress-mobile/WordPress-iOS/issues/13199
This method addresses some old code for the purpose of migrating from `UIWebView` to `WKWebView`.
https://github.com/wordpress-mobile/WordPress-iOS/blob/428de4c95de908768333206e9de9d87167467de6/WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift#L214-L228
`WebViewControllerFactory` [instantiates `WebKitViewController`](https://github.com/wordpress-mobile/WordPress-iOS/blob/428de4c95de908768333206e9de9d87167467de6/WordPress/Classes/Utility/WebViewControllerFactory.swift#L9), which [is implemented using `WKWebView`](https://github.com/wordpress-mobile/WordPress-iOS/blob/428de4c95de908768333206e9de9d87167467de6/WordPress/Classes/Utility/WebKitViewController.swift#L7).
The lines of code in the method above …
> Removes obsolete lines of code.

- RELEASE-NOTES.txt
I moved the release notes line to 14.0 per a discussion with @pinarol on Slack stating the fullscreen comment functionality will be included in 14.0 and not 13.9.
> Moves the fullscreen commenting release note line from 13.9 to 14.0

- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetFooterView.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetFooterView.xib
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetTwoColumnCell.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetUnconfiguredCell.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetUnconfiguredCell.xib
- WordPress/Classes/ViewRelated/Stats/Today Widgets/WidgetStyles.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Ref #12702 , https://github.com/wordpress-mobile/WordPress-iOS/pull/13148#issuecomment-567896870
This updates the widget separator lines to be more in line with the system widget style.
- The separator in the unconfigured view.
- The footer separator in the configured view.
To test:
---
**Unconfigured View:**
- Start with a fresh install, or be logged out of the app.
- Add the `Today` and `All-Time` widgets to your Today view.
- Verify the separator line looks more like that on system widgets (in this example, Shortcuts).
Light:
Dark:
---
**Configured View:**
- Log into the app.
- Go to Stats > Widgets > Use this site.
- On the WP widgets, verify the separator line looks more like that on system widgets (in this example, Shortcuts).
Light:
Dark:
---
PR …
> Stats Widgets: update separator line color

- WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.xib
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.xib
- WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.xib
- WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/Map/CountriesMapCell.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
Refs #11995.
This is a collection of unrelated improvements for Stats. I just made a pass and improved as much as I can. 🙂 
23ad69c20a406196666234a8ea3bef1fc0c8ccb1 Changed the order so that when swiping right, the date and the timezone are accessed first. 
b23542d5c88080ed648a96cae8f616aa36dc9c2c Headers are now read with “Heading” by VoiceOver. 
4f61ee112b754ef8cc0fc6f0851905485c4bcf00 Fixed the swiping order of the section header so that the title is accessed first before the Manage Insights button. 
Fixed the labels of some of the View More buttons. They were previously read as just “Button”. 
- f0c179f63c7e659d9117188a9f24b007696ef30d
- d37c7d68e11dc72e721b38fd7f0374bc4df887f8
- …
> [VoiceOver] Various improvements for Stats

- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/ViewMoreRow.swift
Refs #11995. This is a continuation of https://github.com/wordpress-mobile/WordPress-iOS/pull/13202. 
The Previous and Next period buttons are not read with “dimmed” by VoiceOver if they are disabled. This usually happens automatically. Fixed in 7646774. 
⚠️ Note: All the UI elements in `SiteStatsTableHeaderView` automatically get a `.header` trait. As a result, the buttons will be read as “Button title, dimmed, Button, **Heading**, ...”. It seems that iOS automatically adds `.header` to the elements of a `UITableView` header. I spent an hour or so on this the other day but couldn't figure out a way to stop it from happening. 
As agreed in https://github.com/wordpress-mobile/WordPress-iOS/pull/13202#issuecomment-572649766, we will just remove the hints for …
> [VoiceOver] Improvements for Stats Header Buttons and View More

- WordPress/Classes/Services/EditorSettingsService.swift
- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/Classes/Utility/Editor/GutenbergRollout.swift
- WordPress/Classes/Utility/Editor/GutenbergSettings.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+InformativeDialog.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/GutenbergSettingsTests.swift
iOS side of https://github.com/wordpress-mobile/WordPress-Android/pull/11029
This PR implements the phase 2 of the Gutenberg rollout plan, targeting users that still have aztec as their default editor in any of there sites, and switching it to Gutenberg. With that we show a message explaining the change:
To test:
- Before checking out this branch: Set a site to use Aztec and another one using Gutenberg.
- Set `phase2Percentage` on `GutenbergRollout` to 100 and build.
- Check that the site using Aztec has now the switch set to Gutenberg.
- Open the editor and check that the message shows.
- Close and open the editor again, check that the message doesn't show anymore.
- Open the site that was previously set to Gutenberg.
- Check that it opens Gutenberg without any message.
PR submission …
> [Gutenberg] Rollout phase 2

- WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift
- WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/StatsTwoColumnRow.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetTwoColumnCell.swift
Ref: #12702, #11995
This change adds an accessibility label to abbreviated stats so that the unit name is read instead of the abbreviated letter. For example, “54.8M” is now read as “54 point 8 million” instead of "54 point 8 m".
The accessibility label is not yet utilized _everywhere_ an abbreviated value is displayed, but does hit most. Specifically:
- `StatsTotalRow` - used by all non-specialized stat cards.
- `StatsTwoColumnRow` - used by Insights two-column stat cards. (`Today`, `All-Time`, `Follower Totals`, `This Year`)
- `WidgetTwoColumnCell` - used by the `Today` and `All-Time` widgets.
Also, as an added bonus, the abbreviated strings are now translated.
To test:
Prereqs:
- Run the app & enable VoiceOver.
- Select a high volume site and go to Stats. Hogwarts or en.blog are …
> Stats: add accessibility label for abbreviated stats

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
- WordPress/MediaEditor/MediaEditor.swift
- WordPress/MediaEditor/MediaEditorHub.swift
- WordPress/WordPressTest/MediaEditor/MediaEditorTests.swift
- WordPress/WordPressUITests/Screens/Editor/AztecEditorScreen.swift
Fixes #13218
As for now, Gutenberg doesn't support multiple images. However, the flow is already implemented and you can test. In order to do so, in the method `gutenbergDidRequestMediaFromDevicePicker` change `allowMultipleSelection` to `true`.
1. Create a new post using Gutenberg
2. Insert a block image
3. Tap "Add image" > "Choose from device"
4. Select images (only the first selected will be uploaded)
5. Tap "Preview X"
6. Edit the first image
7. Tap Done
8. Check that the image was uploaded correctly
1. Create a new post using Aztec
2. Tap "+"
3. Tap <img src="https://user-images.githubusercontent.com/7040243/72288781-8f5c3d00-3628-11ea-8257-7f128c7015f1.png" height="28px">
4. Select as many images as you want
5. Tap "Preview X"
6. Edit the images and tap Done
7. All the images …
> Add Media Editor to Gutenberg and Aztec flows

- WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
- WordPress/WordPressTodayWidget/TodayViewController.swift
Ref: #12702
This fixes an issue where the widgets would show the initial loading view when re-shown. The issue was I'd failed to reload the table when saved stats were loaded. Now the table is reloaded whenever `statsValues` is updated.
Known Issue: when the widgets are expanded, the footer sometimes "bounces" a bit. This exists on `develop` and isn't a result of this change. I'll look at that separately.
To test:
- In the app, select a site. Go to Stats > Widgets > `Use this site`.
- Add the `Today` and the `All-Time` widgets to the Today view.
- Scroll away from the Today view, wait a few seconds, then scroll back.
- Verify the dashes are not displayed before the data is refreshed.
Before | After
> Stats Widgets: reload table when stats are updated.

- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetDifferenceCell.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressThisWeekWidget/ThisWeekViewController.swift
Ref #13044 
This addresses two issues with the _This Week_ widget:
- The first two rows showing the initial loading view when re-loaded.
- Abbreviates values over 10,000.
Known Issue: when expanding the widget, the footer still jumps from the top to the bottom. I'll address this in a future PR.
To test:
---
Reloading:
- In the app, select a site. Go to Stats > Widgets > `Use this site`.
- Add the `This Week` widget to the Today view.
- Scroll away from the Today view, wait a few seconds, then scroll back.
- Verify the dashes are not displayed before the data is refreshed.
Before | After
---
Abbreviated Values:
- On a high volume site, view the `This Week` widget.
- Verify `Views` higher than 10,000 are abbreviated.
- Hack tip: This can be a bit hard to verify. You can …
> This Week widget: fix reloading view, abbreviate values

- Podfile
- Podfile.lock
Fixes broken CI in several PRs
To test:
All UI tests should pass.
> Update WordPressMocks to fix broken CI

- Scripts/fastlane/Fastfile
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressThisWeekWidget/Info.plist
Ref #13044 
This updates the _This Week_ widget profiles to use the `match...` profiles, similar to what was done for _All Time_ on https://github.com/wordpress-mobile/WordPress-iOS/pull/13076.
To test:
- Check that an Installable build has been successfully generated.
- Check that a local build on your machine is successful.
> This Week widget: update code signing profiles

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/WebKitViewController.swift
- WordPress/Classes/ViewRelated/Post/Preview/PreviewDeviceLabel.swift
- WordPress/Classes/ViewRelated/Post/Preview/PreviewDeviceSelectionViewController.swift
- WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/ViewRelated/Post/Controllers/PreviewWebKitViewControllerTests.swift
Part of #13197
This adds UI and basic functionality to switch between Desktop and Mobile previews:
To test:
- View a blog or site page preview
- Try switching between device previews
A few things still to come:
- Need to use the new device preview icon shown in #13197. I believe a new icon needs to be added to gridicons.
- I think we may want to use the [`contentMode` API](https://developer.apple.com/documentation/webkit/wkwebpagepreferences/contentmode) or other User Agent modification to increase the chance of showing the true Desktop styling.
> Desktop Preview Feature UI

- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressAllTimeWidget/Info.plist
- WordPress/WordPressAllTimeWidget/InfoPlist.strings
- WordPress/WordPressThisWeekWidget/Info.plist
- WordPress/WordPressThisWeekWidget/InfoPlist.strings
- WordPress/WordPressTodayWidget/Info.plist
- WordPress/WordPressTodayWidget/InfoPlist.strings
Ref #12702 
This localizes the Stats Widgets display names.
To test:
Since there aren't localizations yet (obviously), you can verify the widgets are using localized strings by altering the `CFBundleDisplayName` in their respective `InfoPlist.strings` file.
The `CFBundleDisplayName` is displayed:
- In the widget list.
- In the widget title.
Example with altered `CFBundleDisplayName`:
> Stats Widgets: localize display names

- WordPress/Classes/Utility/Spotlight/SearchManager.swift
- WordPress/Classes/Utility/WebKitViewController.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
This changes the navigation bar style from the default to a light navigation bar style but keeps the default modal presentation (the new covering style instead of fullscreen) for iOS 13.
Below are screenshots displaying the change in style:
<details>
<summary>All Screenshots</summary>
</details>
To test:
- Open a preview of a post or site page
- Check navigation bar styling
> Change to light navigation bar for web previews

- WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostCardCell.swift
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostCompactCell.swift
Closes #13205. 
Added accessibility labels to the Post and Page List's More buttons.
Allowed dismissal of the search using VoiceOver escape gesture. 
Previously, when selecting a post with VoiceOver, VoiceOver would read the information like this:
```
{title}, {very long excerpt}, {6 days ago}, {author name}, {error/status}, middle dot
```
I changed it using these goals: 
- Easier to get to the important information first. 
- More clarity on what the text being read is. 
It's now read like this: 
```
{title}, {6 days ago}. By {author name}. {Sticky}. {error/status}. Excerpt. {very long excerpt}
```
I added the `“Excerpt”` static string in there as I believe it'll be a good indicator for the user that a possibly very long text will be read. They can then …
> [VoiceOver] Improvements for Post List 

- WordPress/Classes/Utility/LinkBehavior.swift
Fixes an issue where external resource loads open a new window in Safari.
| Before        | After           |
|:-------------:|:-------------:|
| <img src="https://user-images.githubusercontent.com/3250/72836768-7f58e480-3c4a-11ea-9df2-6e507d2609a9.gif" width="300">      | <img src="https://user-images.githubusercontent.com/3250/72836772-8253d500-3c4a-11ea-8402-e2e1673493d2.gif" width="300"> | <img src="https://user-images.githubusercontent.com/3250/72836772-8253d500-3c4a-11ea-8402-e2e1673493d2.gif" width="300"> |
To test:
- Open a site preview page on a custom domain loads resources from an external domain (I used a comment form for this)
- Notice that a request to an external domain opens in Safari
> Fixes navigation issue when external resources load

- Podfile
- Podfile.lock
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1792
This PR updates the `gutenberg-mobile` reference to point to `v1.20.1`, a hotfix release.
Note: First it the Podfile will reference a commit hash to run CI tests, then after all PRs are green, the Podfile will be updated to reference a tag (after the hotfix is merged to gutenberg-mobile master, and tagged there).
`gutenberg`: https://github.com/WordPress/gutenberg/pull/19774
`gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1794
`WordPress-Android`: https://github.com/wordpress-mobile/WordPress-Android/pull/11120
This PR disables the gallery image size options on mobile. We can re-enable them after we've verified / implemented the desired behavior for mobile.
**To test:**
Steps:
* Create a …
> Disable gallery size options

- WordPress/Classes/Services/TodayExtensionService.m
- WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/AllTimeWidgetStats.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/ThisWeekWidgetStats.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/TodayWidgetStats.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetDifferenceCell.swift
- WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
- WordPress/WordPressThisWeekWidget/ThisWeekViewController.swift
- WordPress/WordPressTodayWidget/TodayViewController.swift
Ref #12702 
When changing the site used for widgets, the stored data for the old site is now purged.
To test:
The easiest way to test this is to prevent the widgets from fetching data for the new site.
- In the app, go to Stats > Widgets > `Use this site`.
- Add the 3 WordPress widgets to the Today view.
- Return to the app and change the site used for widgets.
- Disable your internet connection.
- Verify all the widgets show dashes (because no data was loaded from the plists and new data cannot be fetched).
**Note:** I'm currently working on a "no connection" view, so showing dashes in this state is temporary. This is just the easiest way to verify the data is purged.
> Stats Widgets: clear stored data when site is changed

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/WPWebViewController.m
This PR fixes the color of the title, subtitle and header buttons in WPWebViewController.
The color change was discussed with @mbshakti .
|--------|------|
1. Go to "My Sites"
2. Select a site from your list of sites.
3. Tap on "Sharing"
4. Tap on "Facebook" or any of the other services.
5. Tap "Connect"
Make sure the title, subtitle and close button looks like the "after" image above.
> Changes some colors from WPWebViewController.

- WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
- WordPress/WordPressUITests/Screens/Editor/AztecEditorScreen.swift
- WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
This PR changes the accessibility label for the more button on the Post View Controller and also adds an accessibility identifier to make the UI tests more robust.
To test:
- Run the UI tests
- Check that they all pass.
> Fix UI unit tests

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
- WordPress/Classes/Extensions/AbstractPost+Dates.swift
- WordPress/Classes/ViewRelated/Post/PostCardCell.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #13258 where the Post list displayed a time string which did not take into account the site time zone, unlike Post Settings.
- Uses [new version](https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/240) of WordPressShared which includes overrides for time zones.
- Adds a new `displayDate()` helper which duplicates the logic from `dateStringForDisplay()` with new time zones passed in.
Follow instructions in #13258 or:
- Set a site time zone two hours away from your own.
- Schedule a post for a time of your choosing.
- Note that the Post List will show a time different than the time in Post Settings.
Note that Scheduling always exhibits this behavior, Drafts and Published will exhibit this behavior only if the elapsed time is greater than 7 days because the relative time …
> Fix #13258: Post time string uses site time zone

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/FormattableContent/FormattableContentRange.swift
- WordPress/WordPressTest/FormattableContentFormatterTests.swift
Fixes a crash that can happen when given invalid ranges – if the range extended past the end of the string, the app would crash. That doesn't happen anymore.
Fixes #
**To test:**
- Comment out the bounds check, run the new test, see that the app crashes
- Un-comment out the bounds check, run the tests again, see that they pass.
> Add bounds checking to notification styles

- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/TodayWidgetStats.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetTwoColumnCell.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetUnconfiguredCell.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetUnconfiguredCell.xib
- WordPress/WordPressTodayWidget/MainInterface.storyboard
- WordPress/WordPressTodayWidget/TodayViewController.swift
Ref #12702
For the _Today_ widget, a `No network available` message is displayed if:
- There is no network connection.
- There is no saved data.
If there is saved data, it will be displayed.
To test:
Side note: In the simulator, the widget was never notified when the network connection was re-established. I suggest testing on a real device as the reachability notifications work as expected. 
Since `No network available` will only be displayed if there is no saved data, the data needs to be purged, and then the network disabled.
---
- In the app, go to Stats > Widgets > `Use this site`.
- Add the _Today_ widget to the Today view.
- Return to the app and change the site used for widgets (so the saved data is purged).
- Verify the no …
> Today Widget: show no connection view

- Scripts/fastlane/Fastfile
This PR adds a simple public lane that can be used by developers to generate new Match handled profiles for new components.
To test:
1. Run `bundle exec fastlane update_certs_and_profiles` and verify that the provisioning profiles for alpha, internal and production builds are installed. 
> Add a lane to update certificates and profiles

- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/AllTimeWidgetStats.swift
- WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
- WordPress/WordPressAllTimeWidget/MainInterface.storyboard
- WordPress/WordPressTodayWidget/TodayViewController.swift
Ref #13271
For the _All-Time_ widget, a `No network available` message is displayed if:
- There is no network connection.
- There is no saved data.
If there is saved data, it will be displayed.
To test:
Side note: In the simulator, the widget was never notified when the network connection was re-established. I suggest testing on a real device as the reachability notifications work as expected. 
Since `No network available` will only be displayed if there is no saved data, the data needs to be purged, and then the network disabled.
---
- In the app, go to Stats > Widgets > `Use this site`.
- Add the _All-Time_ widget to the Today view.
- Return to the app and change the site used for widgets (so the saved data is purged).
- Verify …
> All-Time Widget: show no connection view

- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/ThisWeekWidgetStats.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetDifferenceCell.swift
- WordPress/WordPressThisWeekWidget/MainInterface.storyboard
- WordPress/WordPressThisWeekWidget/ThisWeekViewController.swift
Ref #13271
For the _This Week_ widget, a `No network available` message is displayed if:
- There is no network connection.
- There is no saved data.
If there is saved data, it will be displayed.
To test:
Side note: In the simulator, the widget was never notified when the network connection was re-established. I suggest testing on a real device as the reachability notifications work as expected. 
Since `No network available` will only be displayed if there is no saved data, the data needs to be purged, and then the network disabled.
---
- In the app, go to Stats > Widgets > `Use this site`.
- Add the _This Week_ widget to the Today view.
- Return to the app and change the site used for widgets (so the saved data is purged).
- …
> This Week Widget: show no connection view

- WordPress/Classes/Services/MediaCoordinator.swift
This PR makes the media upload notifications to show again.
I think that the behaviour of `allSatisfy` may have changed between
Swift versions because it looks this was working correctly before.
To test:
- Open the app and go to a media library of a site
- Press on the + button and multiple media
- Wait for the uploads to finish
- See if the notification/toast is showed correctly
> Make sure we are not checking for failed media on an empty array.

- WordPress/WordPress.xcodeproj/project.pbxproj
@SergioEstevao reported that with `killall Simulator` local UI test runs were failing to run with this error:
> The test runner encountered an error (Failed to prepare device ‘iPhone X’ for impending launch. (Underlying error: Timed out waiting for Simulator.app to become ready.))
At his suggestion, I'm replacing that command with `xcrun simctl shutdown all`, which closes any open simulators instead of closing the Simulator app entirely before running the UI tests. (Closing the simulator is required to make sure the hardware keyboard is disabled in test runs, but it turns out that closing the Simulator app was overkill.)
@SergioEstevao can you check whether this resolves the problem you were seeing?
To test:
* Run `rake mocks` to start the mock server.
* In Xcode, select the `WordPress` …
> Testing: Shut down simulators instead of closing Simulator app before UI test runs

- WordPress/WordPressUITests/README.md
This updates the UI testing instructions per the changes in https://github.com/wordpress-mobile/WordPress-iOS/pull/12930.
To test: Go through the instructions for running the UI tests locally and confirm they run.
> Update UI test instructions to use test plans

- WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
Site creation flow was designed to be displayed in full screen.
Since iOS 13 the default presentation mode for modal is page sheet style that can be interactively dismissed with a downward swipe. This means that users can dismiss the modal anytime they want with a swipe down gesture, which is not the behavior we want in such a fundamental flow.
To test:
A. Site creation following signup
1. Signup 
2. Tap "Add New Site"
3. tap "Create WordPress.com site"
4. See the site creation flow in full screen
B. Site creation on adding new site
1. Tap "switch site" 
2. Tap + button in top right
3. Tap "create WordPress.com site"
4. See the site creation flow in full screen
Before             |  After
:-------------------------:|:-------------------------:
> Present Site creation flow in full screen mode

- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressAllTimeWidget/Info.plist
- WordPress/WordPressAllTimeWidget/InfoPlist.strings
- WordPress/WordPressThisWeekWidget/Info.plist
- WordPress/WordPressThisWeekWidget/InfoPlist.strings
- WordPress/WordPressTodayWidget/Info.plist
- WordPress/WordPressTodayWidget/InfoPlist.strings
Fixes #13296 
This reverts the changes made with https://github.com/wordpress-mobile/WordPress-iOS/pull/13247. That was an attempt to translate the widget display names. However, having an explicit `CFBundleDisplayName` apparently overrides _all_ the `Info*.plist`s, despite `LSHasLocalizedDisplayName` only being set in the release plist. That resulted in the "(Internal)" being dropped from the display names.
So we'll go back to hard-coded display names, defined in each plist, and I'll try translations another day.
To test:
There isn't really a way to test Internal display names, but each are hard-coded in their respective `Info*.plist`, so just verify the display names are as expected in dev. To note, the display names are used in both the widget list and on the widget itself.
PR …
> Stats Widgets: fix display names

- WordPress/Classes/Utility/AccountHelper.swift
- WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
- WordPress/WordPressThisWeekWidget/ThisWeekViewController.swift
- WordPress/WordPressTodayWidget/TodayViewController.swift
Fixes #13293 
This fixes two issues:
1. Tapping the widgets was not opening the app. Cause: The `handleTapGesture` methods were checking the wrong state.
2. The 'no network available' view was not being displayed after logging out of the app. Cause: The widgets' stored data was not being cleared on logout.
To test:
Note: In the simulator, the widgets don't receive the notification when the network connection is re-established (you have to scroll away from the Today view and back to update the widgets). You might want to test on a real device as the reachability notifications work as expected.
---
- Log out of the app.
- Add the 3 Stats widgets to the Today view.
- The unconfigured view should be displayed.
- Verify tapping the widgets opens the app.
---
- Disconnect your network.
- The …
> Stats Widgets: fix opening app when widgets are tapped

- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetDifferenceCell.swift
- WordPress/WordPressThisWeekWidget/ThisWeekViewController.swift
Fixes #13312 
I couldn't exactly repro the issues in #13312, but from the video and screenshot it appears the expanded widget height is incorrect when going from connection > no connection > connection on some devices.
The issue is the height is calculated before the rows are rendered, so when going from no connection > connection, the `WidgetDifferenceCell.defaultHeight` was always used.
In order to have a more accurate expanded height, I've made these changes:
1. Changed the `WidgetDifferenceCell.defaultHeight` to be more inline with the actual height on most devices.
2. When the actual row height is calculated, it is now saved. It is then used when re-showing data rows when the connection is re-established.
To test:
The 'No network available' view is only displayed when:
- There is no …
> This Week widget: fix expanded height calculation

- Podfile
- Podfile.lock
- WordPress/Classes/Services/TodayExtensionService.m
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
- WordPress/WordPressAllTimeWidget/Tracks+AllTimeWidget.swift
- WordPress/WordPressThisWeekWidget/ThisWeekViewController.swift
- WordPress/WordPressThisWeekWidget/Tracks+ThisWeekWidget.swift
- WordPress/WordPressTodayWidget/TodayViewController.swift
- WordPress/WordPressTodayWidget/Tracks+TodayWidget.swift
Fixes #13272 
Shared PR: https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/245
The `stats_launched` and `configure_launched` Tracks defined in #13272 were already implemented. So only these changes were needed:
- Added Track for when the widget site changes.
- Removed the `extension_accessed` Track from all 3 widgets.
To test:
- Go to Stats > Widgets > Use this site.
- Verify this in the console:
`🔵 Tracked: widget_active_site_changed`
> Stats Widgets: update Tracks

- WordPress/Classes/ViewRelated/Stats/SiteStatsDashboard.storyboard
- WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
Fixes #13301 
To test:
Note: This appears to have been an issue only on devices without a home button. Like iPhone X* and iPhone 11*.
- Run the app.
- Go to Stats > Widgets > Use this site.
- Add any Stat widget to the Today view.
- Tap on the widget. The app will launch, displaying the Stats in a modal.
- Verify the bottom of the view is extended.
Before | After
> Stats: fix background color when viewed in a modal

- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/AllTimeWidgetStats.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/ThisWeekWidgetStats.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/TodayWidgetStats.swift
- WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
- WordPress/WordPressThisWeekWidget/ThisWeekViewController.swift
- WordPress/WordPressTodayWidget/TodayViewController.swift
Ref #12702
As noted here https://github.com/wordpress-mobile/WordPress-iOS/pull/13233#pullrequestreview-343277093, the widgets shouldn't update if the data has not changed. Accordingly:
- Each widget now compares the new data with the old.
- If the data has changed, the widget will update.
- If the data has not changed, the widget will not update.
To test:
There really isn't a way to test widgets aren't updated, but you can test that they are.
- In the app, go to Stats > Widgets > Use this site.
- Note: en.blog might be a good one since it updates fairly frequently.
- Add the 3 Stats widgets to the Today view.
- Scroll away from the Today view, and back. Verify the stats update (assuming there is new data to show).
> Stats Widgets: Update only if data has changed.

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
#13197 
Enables the `postPreview` feature flag for internal builds.
To test:
- Preview a Blog Post or Site Page
- Check that the new Post Preview UI (with Desktop preview) is available
> Enable Post Preview feature for internal testing

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
#13197 
Enables the `postPreview` flag for all users.
To test:
* Preview a Blog Post or Site Page
* Check that the new Post Preview UI (with Desktop preview) is available
> Enable Post Preview for all users

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
This PR fixes the loading of the Noto font when opening Gutenberg.
To test:
- Immediately press the Write new Post button on the interface on a blog that has GB active
- Check that the font loaded correctly ( check the lowercase `g` as in the screenshot above)
> Fix noto font loading on Gutenberg

- WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetUnconfiguredCell.swift
- WordPress/Classes/ViewRelated/Stats/Today Widgets/WidgetStyles.swift
- WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
- WordPress/WordPressThisWeekWidget/ThisWeekViewController.swift
- WordPress/WordPressTodayWidget/TodayViewController.swift
Ref #12702 
For all the Stats widgets, if fetching data fails, a `Couldn't load data` view is displayed.
To test:
A bit of hackery is needed to force data fetching to fail. In the `retrieveSiteConfiguration` method in all three VCs, you can replace this line:
```
siteID = sharedDefaults.object(forKey: WPStatsTodayWidgetUserDefaultsSiteIdKey) as? NSNumber
```
With this magic:
```
if loadingFailed {
siteID = sharedDefaults.object(forKey: WPStatsTodayWidgetUserDefaultsSiteIdKey) as? NSNumber
} else {
siteID = 9999999999999999
}
```
That will cause the first attempt to fail by setting an invalid `siteID`, and the second attempt to succeed by setting the correct `siteID`.
Now, to actually test:
- In the app, go to Stats > Widgets > Use this site.
- Add the Stats widgets to the device's Today …
> Stats Widgets: show failed loading view

- WordPress/News.strings
Fixes #10525 
To test:
1. Open the Reader 
2. See the new card with updated content and link to offline support blog post on en.blog
> Updated News Card to announce Offline Support

- RELEASE-NOTES.txt
- WordPress/Classes/Models/Comment.m
- WordPress/Classes/ViewRelated/Comments/CommentViewController.m
Fixes #10015
**Description**
After some deliberation with @leandroalonso we decided to strip the HTML from the comments for now. 
This PR strips the HTML from the comment view, and the edit comments view.
**To test:**
1. Tap the My Sites section
2. Select a site
3. Tap the Comments item
4. Locate a comment with HTML content
5. Tap to view more of the comment
5.a. Tap the Edit option to edit the plain text of the comment
**Video Demos**
| Device | Version | Link |
|---|---|---|
| iPhone 8 | 11.4 | https://d.pr/i/6Pscbz |
| iPhone 8 | 12.4 | https://d.pr/i/QAMK0A |
| iPhone 8 | 13.3 | https://d.pr/i/dFbSjS |
|---|---|---|
| iPhone 11 Pro Max | 13.3 | https://d.pr/i/xONIan |
|---|---|---|
| iPad Air | 11.4 | https://d.pr/i/eExl9L |
| iPad Air (3rd Gen) | 12.4 | https://d.pr/i/uS5KG4 |
| iPad …
> Strips HTML from the comment view/edit on the site detail views

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Supersedes: https://github.com/wordpress-mobile/WordPress-iOS/pull/13358
Removes an unused feature flag.
No testing needed since the feature flag wasn't really used.  Just build and run the unit tests and make sure all is fine.
> Cleanup: remove exampleFeature flag.

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Removes the domain credit feature flag, since it was set `true` nearly 9 months ago now.
1. Make sure you have a WP.com testing blog that has credit, and doesn't have a registered domain.
2. Run the app, go to the blog mentioned in step 1.
3. Make sure you see a "Register Domain" row on top of the site details screen (as shown below).
> Removed the domain credit feature flag.

- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Fixes #13326 
This fixes an issue where the ghost cells in the Blog Posts list would appear white instead of showing the ghost animation.
Note: there is a [separate issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/13364) with the Search bar border color.
To test:
- Set the device to dark mode.
- On a slow network, go to Blog Posts.
- Switch between tabs.
- Verify the ghost cells animate.
Before | After
> [Dark Mode] Posts list: Re-set ghost style when switching filter tabs.

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/WPWebViewController.h
- WordPress/Classes/Utility/WPWebViewController.m
- WordPress/Classes/Utility/WPWebViewController.xib
- WordPress/Classes/Utility/WebViewAuthenticator.swift
- WordPress/Classes/ViewRelated/Blog/SharingAuthorizationWebViewController.m
Fixes #13356 
This PR implements sharing using `WKWebView` instead of `UIWebView`.  Unfortunately this is the easiest way to resolve the connection issues we were facing with Facebook.
All services were tested.
Just test sharing with all the available services.
> Fix sharing with Facebook.

- WordPress/Classes/Utility/WPWebViewController.m
- WordPress/WordPressTest/WPUserAgentTests.m
Fixes #13185
This PR also removes a protocol that is no longer implemented by `WPWebView`.
Simply run the unit tests.
> Removes some code from unit tests that's no longer needed.

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
`gutenberg`: https://github.com/WordPress/gutenberg/pull/20045
`gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1856
`WordPress-Android`: https://github.com/wordpress-mobile/WordPress-Android/pull/11236
This brings the fix from https://github.com/WordPress/gutenberg/pull/19800 to the release branch for `1.22.0` and updates the release notes to reflect the new feature.
Tested via steps here: https://github.com/WordPress/gutenberg/pull/19800#issue-365661691
> Fix gallery size labels - 1.22.0

- RELEASE-NOTES.txt
- WordPress/Classes/Services/BlogService.h
- WordPress/Classes/Services/BlogService.m
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+BlogPicker.swift
- WordPress/Classes/ViewRelated/Post/PostEditor.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderReblogFormatter.swift
- WordPress/Classes/ViewRelated/Reader/ReaderReblogPresenter.swift
- WordPress/WordPressTest/ReaderPostCardCellTests.swift
- WordPress/WordPressTest/ReaderReblogActionTests.swift
Ref #12960
To test:
wp:image markup
- Make sure you have a test blog with Block Editor enabled
- Navigate to the reader and choose a post with a featured image
- Either from post list or post detail, tap on `reblog`, and choose the site with block editor enabled
- verify that the image is displayed after the title and before the summary
Reblog button visibility
- log in with a self hosted site (Login -> Login with WordPress -> Login by entering your site address)
- Navigate to the reader, and verify that the reblog button is not visible on any post
Self hosted sites not visible in the blog selector
- Login with a user that has at least one self hosted site
- Navigate to the reader, tap the reblog button and verify that:
- If the user has no WordPress.com sites (regardless self hosted …
> Post Reblogging - Add wp:image markup to posts reblogged with Block Editor

- docs/README.md
- docs/localization.md
This adds a short guide for how to localize strings. Most of the information was taken from @mindgraffiti and @loremattei's work. 
1. View the file [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/ee60ffa8f2ba0ada3abf9b98ff44ad59e520f3fd/docs/localization.md).
2. Please feel free to scrutinize. 😄 
3. Please check that the examples are correct.
> Add localization doc

- Podfile
- Podfile.lock
Fixes # 
Ref to gb-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1616
Ref to gutenberg: https://github.com/WordPress/gutenberg/pull/18823
This PR introduces 1st iteration of mobile `Button` block component.
To achieve gradient background color on mobile `react-native-linear-gradient` comes in handy.
The first iteration includes:
* Rendering `Button` with:
* gradient background color ✅ 
* custom background color chosen from picker ✅ 
* custom text color chosen from picker ✅ 
* Options to change border radius, add link, open url in new tab ✅ 
* Expanding and shrinking `RichText` ✅ 
* Notification for missing color settings functionality ✅ 
To test:
**-> Gradient**
* open draft post on web
* add Button
* choose the gradient background color
* save post
* open draft post …
> Add react-native-linear-gradient lib

- RELEASE-NOTES.txt
- WordPress/Classes/Services/CommentService.m
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #13259 
**Description**
You can read more about the source of this issue here: https://github.com/wordpress-mobile/WordPress-iOS/issues/13259#issuecomment-582589196
Since when adding a new comment there is a chance the post it's added to is the wrong post until a network sync, this PR will reassign the Comment's post property to the originating Post object. 
This allows it to appear after being added. 
**To test:**
1. Tap the Reader Tab
2. Tap Followed Sites
3. Locate a Post and tap the name of the site
4. Tap the post to open the post detail
5. Tap the comment icon 
6. Leave a Comment
**Video Demos**
| Device | Version | Link |
|---|---|---|
| iPhone 8 | 11.4 | https://d.pr/i/0tu82q |
| iPhone 8 | 12.4 | https://d.pr/i/Yj6yxw |
| iPhone 8 | 13.3 | https://d.pr/i/w8AMXT | …
> Fixes an issue where comments made in the Reader may not appear after adding successfully

- WordPress/Classes/Utility/Editor/GutenbergRollout.swift
- WordPress/WordPressUITests/Screens/BaseScreen.swift
- WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
- WordPress/WordPressUITests/Screens/FancyAlertComponent.swift
- WordPress/WordPressUITests/Screens/MySiteScreen.swift
- WordPress/WordPressUITests/Screens/PostsScreen.swift
- WordPress/WordPressUITests/Tests/EditorGutenbergTests.swift
WPiOS side of https://github.com/wordpress-mobile/WordPress-Android/pull/11240
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/12888
This PR bumps the gutenberg rollout to 100% of users.
**Note:** this targets 14.1, we were waiting for 14.0 feedback before making that changes.
> [Gutenberg] Bump phase 2 rollout to 100%

- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
- WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Views/PostCardStatusViewModelTests.swift
Fixes #13280
You can test this in two different ways:
1. By having a self-hosted website that is disabled added in your app;
2. Or by intercepting the result (like using Charles proxy) and returning an error;
2. Publish it
3. Check that the message states that your post will be published later when you're online
1. Crate a new post
2. Publish it (the publish action should fail in the server)
3. Check that the app shows a "Failed to upload" message
> Displays offline messages only when the user is offline

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.h
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
Fixes #11426 
To test:
- Select a site where you opened the site Media Library before
- Start a new post ( test with GB and Aztec)
- Go offline
- Tap on add media 
- Select the option to pick from the site MEdia Library
- Check if you are able to pick a cached media object and insert on the post
- Select a site where you **never** open the site Media Library on the device
- Start a new post ( test with GB and Aztec)
- Go offline
- Tap on add media 
- Select the option to pick from the site MEdia Library
- Check that you see an alert that says that you are unable to sync with the server
> Fix media library pick while offline

- Gemfile
- Gemfile.lock
- Scripts/fastlane/Fastfile
- Scripts/fastlane/Pluginfile
This PR updates Fastlane and the AppCenter plugin to the latest version. 
There are no big changes in Fastlane, while the AppCenter plugin update contains a fix for an issue with the params that we were experiencing. 
To test:
1. Verify that CI is green and that the installable build job has been able to upload the artifact to AppCenter.
2. Run `bundle install` on your local environment and verify that it succeeds. 
3. Run `bundle exec fastlane build_and_upload_internal` and verify that the binary is uploaded to the WPInternal channel of AppCenter. 
4. Delete the WPInternal binary from AppCenter.
N.B.: I'm sending this against `release/14.1` because I created it out of that branch in order to be able to test it during the beta release. The changes don't affect the app in any way.
PR …
> Update Fastlane and the AppCenter plugin 

- WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergStockPhotos.swift
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1863
1. Add a Gallary Block.
2. Open the Free Photo Library.
3. Choose one (or many) images.
4. Select add
**_Expect:_** All images should be added to the Gallery Block in the selected order
1. Add an Image block.
2. Open the Free Photo Library.
3. Choose one (or many) images.
4. Select add
**_Expect:_** All images should be added as separate Image Blocks
1. Add a Media & Text Block.
2. Open the Free Photo Library.
3. Choose one (or many) images.
4. Select add
**_Expect:_** The first image should be added to the Media block and the rest of the images should be added as separate Image Blocks
> [Gutenberg] Support Multiple uploads in Gallery

- WordPress/Classes/ViewRelated/Blog/Detail Header/NewBlogDetailHeaderView.swift
- WordPress/Classes/ViewRelated/Blog/Detail Header/SiteIconView.swift
#13318 
This adds support for the drag and drop API to the new Blog Detail Header view with quick actions. This mirrors the current version in the existing Blog Detail Header.
To test:
- Drag and drop an image onto the Site Icon view
- Make sure site icon is updated
> Quick Actions: Add Drop Target API for iPad

- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Navigation Title should be filled out the same way it was when navigating from My Sites. Instead, resuming the app does not fill out the navigation title.
|--|--|
| <a href="https://user-images.githubusercontent.com/3250/74261899-2d3f3800-4cb9-11ea-96ef-b8951fc9cee7.png"><img src="https://user-images.githubusercontent.com/3250/74261899-2d3f3800-4cb9-11ea-96ef-b8951fc9cee7.png" width="300"></a> | <a href="https://user-images.githubusercontent.com/3250/74262149-94f58300-4cb9-11ea-99a0-e24c80e9401e.png"><img src="https://user-images.githubusercontent.com/3250/74262149-94f58300-4cb9-11ea-99a0-e24c80e9401e.png" width="300"></a> |
To test:
1. Open Site from My Sites section
2. Background and then kill the app
3. Reopen the app (should return to the Site Details screen)
4. …
> Fixes missing navigation title for a blog on resume

- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Blog/Detail Header/NewBlogDetailHeaderView.swift
- WordPress/Classes/ViewRelated/Blog/Detail Header/SiteIconView.swift
https://github.com/wordpress-mobile/WordPress-iOS/issues/13318
This adds the Spotlight view to the new blog detail header's site icon during the Quick Start tour.
To test:
- Create a new site
- Check that the Quick Start tour animation is displayed for the site icon on the blog detail page
> Quick Actions: Add spotlight for Quick Start tour

- .github/workflows/danger-pr-labels.yml
- .github/workflows/danger-prs.yml
This is the first step to implement https://github.com/wordpress-mobile/WordPress-iOS/issues/13366.
This adds a GitHub workflows that run the [shared Peril settings](https://github.com/Automattic/peril-settings) to:
-  [validate the PR's labels](https://github.com/Automattic/peril-settings/blob/f8b40cef2adae13967ddd55c3fd917c3b0f200b6/org/pr/labels.ts)
- [preform consistency checks on the iOS code](https://github.com/Automattic/peril-settings/blob/f8b40cef2adae13967ddd55c3fd917c3b0f200b6/org/pr/ios-macos.ts)
This setup uses the [Danger GitHub Action](https://github.com/marketplace/actions/danger-js-action). I like it because we don't have to add anything to our repo in order to run Danger, but it comes with a time overhead on CI because the action needs to be fetched and built. 
Using the …
> Set up GitHub workflows to run basic checks and validate PR labels via Danger

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
Fixes #13418 
To test:
- run the app
- make sure you have one or more private site(s) in the list of `Followed Sites` in the `Reader`
- Go to the `Reader -> Followed Sites -> Manage` and select any of the private sites
- Verify that the `reblog` button does not appear
- Enter any post detail from the post list
- Verify that the `reblog` button does not appear
> Fix reblog for private sites

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/WPMediaEditor.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Fixes #13425 
1. Edit an already published image
2. Check that the label says "Done" instead of "Insert 1"
1. Edit an already published image
2. Check that the label says "Done" instead of "Insert 1"
Scenario 2:
1. Add multiple images and tap "Preview X"
2. Check that the label says "Insert X"
> Display "Done" label when editing already published images

- WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift
Fixes #13436 by dismissing the editor after publishing and adding a confirmation dialog.
Fixes #13438 by taking the user straight to the post list so that post settings are not as easy to change while publishing.
It seems like there are a couple of options to fix the issue:
1. Dismiss both the preview and the editor and go back to the Post List. (Equivalent to using Publish Now)
2. Go back to the Editor with the post fully published and everything updated.
3. Go back to the Editor with the status changed to Published so that if you “Cancel” instead of hitting the additional Publish button in the navigation bar, the Publish would be cancelled. (equivalent of changing the Post's Status to Published in Post Settings)
The first option has the benefit of being a small code change and …
> Fix 13436: Preview Publish dismiss Editor w/ Confirm

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Header.swift
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/ActionRow.swift
- WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
- WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/SiteIconView.swift
Finishes the remaining items from #13318 (before enabling the feature flag).
- Adjusts accessibility elements for Quick Action buttons and Site Icon button
- Adds a `tap_source` property to the existing Tracks events for the quick actions:
- From the table: `row`
- From quick actions: `button`
- from another source (deep link or other action): `link`
To test:
- View the Blog Details Header using Accessibility to check that the Quick Actions and Site Icon buttons are accessible.
- Check that events fired when tapping on the Quick Actions buttons contain `tap_source: row`
> Quick Actions Accessibility + Tracks

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Closes #13318 
To test:
- Open Blog Details page
- Use Quick Actions buttons to access parts of a blog
<a href="https://user-images.githubusercontent.com/3250/74666326-85b18200-515e-11ea-89f7-c08d12462c6c.png"><img src="https://user-images.githubusercontent.com/3250/74666326-85b18200-515e-11ea-89f7-c08d12462c6c.png" width="300"></a>   <a href="https://user-images.githubusercontent.com/3250/74666439-b691b700-515e-11ea-8dbb-171fe225f9c0.png"><img src="https://user-images.githubusercontent.com/3250/74666439-b691b700-515e-11ea-8dbb-171fe225f9c0.png" width="300"></a>
> Enable Quick Actions feature flag

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/System/Floating Create Button/FloatingActionButton.swift
- WordPress/Classes/ViewRelated/System/Floating Create Button/WPTabBarController+CreateButton.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressUITests/Screens/TabNavComponent.swift
#13320
Adds the new Floating Action Button to create a post. This is mostly to check the visual design of the button with other functionality coming in follow up PRs.
- Button is shown on all screens. To simplify review, a separate PR will properly hide the button depending on which screen is shown.
- There is no list sliding up from the bottom to select a Site Page or Blog Post. This will be added in a separate PR.
- Open Application to any tab
- Notice Create Button in bottom right
> Add feature flag + Create Button

- RELEASE-NOTES.txt
Removes gallery image size release note from 14.3 because that was added (and included in the release notes) in 14.2.
> Remove duplicate gallery image size release note

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #13451
1. Open the Reader
2. Open any post on Reader (tap on post's card)
3. Tap "Me" on the tab bar
4. Log Out
5. The app should not crash
> Fix crash on logout after using Reader

- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/Services/PostService+MarkAsFailedAndDraftIfNeeded.swift
- WordPress/Classes/Services/PostService+RefreshStatus.swift
- WordPress/Classes/Services/PostService.m
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/WordPressTest/PostCoordinatorTests.swift
- WordPress/WordPressTest/PostService+MarkAsFailedAndDraftIfNeededTests.swift
Closes https://github.com/wordpress-mobile/WordPress-iOS/issues/13378
Closes https://github.com/wordpress-mobile/WordPress-iOS/issues/13402
Closes https://github.com/wordpress-mobile/WordPress-iOS/issues/13379
Closes https://github.com/wordpress-mobile/WordPress-iOS/issues/13492
This PR targets a feature branch.  While this doesn't mean proper testing is not important, the feature being implemented isn't complete.
Some things that still need to be addressed:
- The messaging in the cells in the main pages list needs to be updated.
- Tracking needs to be implemented.
Please, test these steps while offline.
The test steps below should be completed once for saving a draft, once for publishing a page, once for submitting for review, and once for scheduling a page.
1. Create a new page.
2. Try …
> Show new messaging when saving / publishing / scheduling / submitting pages.

- WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
- WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Fixes #13458
This PR changes how the PSI display logic that was introduced in https://github.com/wordpress-mobile/WordPress-iOS/pull/13459 is called. It's been moved from the `BlogListViewController` to the `WordPressAuthenticationManager`. 
The reason for this is:
- Ease of disabling the login epilogue view
- Ease of intercepting the signup epilogue view continue button
- Preventing a potential bug that would cause the PSI to display if you remove all your sites
**Part 1:**
1. If you're logged in, log out
1. Tap Continue with WordPress.com
1. Login to an account that has no sites
Note: You should **not** be shown the login epilogue view (https://d.pr/i/8vJSs6)
You should be displayed the interstitial view
**Part 2:** 
1. Relaunch the app, you should not be displayed the …
> Changes how the Post Signup Interstitial is displayed

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Post/Scheduling/CalendarMonthView.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/Collection+RotateTests.swift
Uses the `firstWeekday` offset to adjust the weekday symbols displayed in the Post Scheduling calendar.
Fixes #13491 
<a href="https://user-images.githubusercontent.com/3250/74783971-1aea6e80-5264-11ea-8731-46c07a07add9.png"><img src="https://user-images.githubusercontent.com/3250/74783971-1aea6e80-5264-11ea-8731-46c07a07add9.png" width="300"></a>
To test (see steps in #13491):
- Change Region settings to a locale which uses a different starting weekday (Lithuania, for example)
- Enter Post Settings from a blog post
- Change the Published On / Scheduled date and view the weekday header.
> Fixes weekday symbols regional offsets

- WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes an issue where the incorrect tab bar icon was used for the Notifications section.
Thanks for pointing this out @Gio2018!
Notice the Notifications icon in the _Before_ image
|--|--|
| ![Before-TabFix](https://user-images.githubusercontent.com/3250/74787139-a4516f00-526b-11ea-8d0c-c9465bb3f96b.gif) | ![After-TabFix](https://user-images.githubusercontent.com/3250/74787143-a87d8c80-526b-11ea-8c8a-45bacacaf7f6.gif) |
To test:
- Tap on any tab in the tab bar
- Notice that the Notifications icon changes to the Me tab's icon
> Adjusts the tab index when updating Me Icon

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
Fixes #12880 
Shared PR: https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/249
**To test:**
1. If you're logged in, log out
1. Tap Continue with WordPress.com
1. Login to an account that has no sites
1. When the PSI is displayed, verify this in the console:
`🔵 Tracked: welcome_no_sites_interstitial_shown`
1. Tap the create site button, and verify this in the console:
`🔵 Tracked: welcome_no_sites_interstitial_button_tapped <button: create_new_site>`
1. Tap the add self-hosted site button, and verify this in the console:
`🔵 Tracked: welcome_no_sites_interstitial_button_tapped <button: add_self_hosted_site>`
1. Tap the Not Right Now option, and verify this in the console:
`🔵 Tracked: welcome_no_sites_interstitial_dismissed`
Note: In order to test each button …
> Adds analytics for the Post Signup Interstitial

- WordPress/Classes/ViewRelated/Comments/CommentViewController.m
Reference: #10015 
**Description**
We decided to allow HTML markup to be displayed in the comment editor again after a discussion on what would be a better experience for the user. 
**To test:**
1. Launch the app and login if needed
2. Tap the My Sites tab
3. Select a site from the list
4. Tap the Comments item
5. Locate a comment with that contains HTML
6. Tap on it 
**Expectation:** You will be brought to the comment detail view, you should *not* see the HTML markup here: https://d.pr/i/2it2uF
7. Tap the Edit button
**Expectation:** You should see the  HTML markup: https://d.pr/i/ocUSgL
**Demo**
> Disable stripping of HTML when editing a comment from the CommentViewController

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Post/PostActionSheet.swift
- WordPress/WordPressTest/PostActionSheetTests.swift
Fixes #13514
I wasn't able to reproduce the case where the "Retry" action appears in the Action Sheet (normally is the 2nd option in the Post Card).
However, I'm sure that his change will fix the crash and the option will appear.
Also, I made the `switch` exhaustive instead of using a `default`.
> Fix crash in Post List Action Sheet

- WordPress/Classes/Utility/WebKitViewController.swift
- WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift
Adjusts the web view's actual width to provide Mobile Preview on tablets.
This is different than the Android version (which was already just keeping the same Default + Desktop previews). I originally added the Mobile preview on tablet because iOS 13 is intended to use a more "desktop like" web experience. This is less obvious because the theme designs are responsive and the preview is presented in a popover, taking up a smaller portion of the screen.
The preview in the Calypso editor on the web appears to adjust the iframe width. I think it makes sense to copy that behavior on the mobile clients so it is consistent.
| Default | Mobile |
|--|--|
| <a href="https://user-images.githubusercontent.com/3250/74798414-efc74580-528a-11ea-9902-6f4b1bfd25d2.png"><img …
> #13440: Adjusts mobile preview on tablets

- Scripts/fastlane/Fastfile
This PR adds some steps to the `release_finalize` Fastlane action: 
- removing the branch protection.
- removing the frozen tag.
- closing the milestone.
- creating a new milestone. 
Testing is a bit tricky as it requires to change the state of the release. 
The easiest way is probably to mock up a release and to test only the new steps in the lane. The following steps use `14.4` as test version because it doesn't affect the current release (`14.2`) and the milestone currently used in develop (`14.3`).
*Set up*
1. Checkout a `release/14.4` branch out of this branch.
2. Change the version in `Version.public.xcconfig` to 14.4.
3. Comment the `ios_update_metadata(options)`, `ios_bump_version_beta()` and `ios_final_tag(options)` steps in the lane as they will fail. 
4. Commit and push the …
> Add automation for release wrap up steps

- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/Services/PostService.h
- WordPress/Classes/Services/PostService.m
- WordPress/Classes/Services/PostServiceQueueList.swift
- WordPress/Classes/Services/PostServiceUploadingList.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/PostCoordinatorTests.swift
- WordPress/WordPressTest/PostServiceUploadingListTests.swift
Fixes #13430
Fixes #13429 
Follow the steps described by @rachelmcr:
2. Enter some post content and save the post as a draft.
3. Add more post content and select "Preview" from the ellipsis menu.
4. Immediately (while the status bar still shows "Generating preview") tap "Update" to save the post
The app should not crash.
> Handle concurrent calls to upload the same post

- Podfile
- Podfile.lock
Ref #13427
There's no feature added.
Just run the app and perform some network requests: publish posts, upload media, etc.
- `WordPressKit`: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/212
- `WordPressAuthenticator`: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/184
> Update Alamofire to 4.8

- WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Blog.swift
- WordPress/Classes/ViewRelated/NUX/EpilogueSectionHeaderFooter.xib
- WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
Ref #13413 
This updates the 'My Sites' section of the Login Epilogue to the new design. Specifically:
- 'LOGGED IN AS' section header removed (above the User Info block).
- Site labels' font and color updated.
- Added separator lines between site rows.
- Table and row background colors updated.
Not yet updated:
- User Info block (including the top and bottom separator lines).
- Bottom buttons.
- iPad specific layout.
- Accessibility.
To test:
- Log into the app.
- Verify the 'My Sites' list looks like the Zeplin design, or that on #13413 .
Light | Dark
> Login Epilogue: updated My Sites list

- RELEASE-NOTES.txt
Fixes #
Adding the release note for "Group block". That line was overlooked during the release of gutenberg-mobile 1.23 release.
WP-Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/11368
To test:
> Add the missing release note for the Block editor

- WordPress/WordPressShareExtension/MainShareViewController.swift
Fixes a bug that was causing the share extension to misbehave in internal releases.
More info: p5T066-1au=p2#comment-4322
1. Run WPiOS with the internal build configuration.
2. Open a page in Safari, share.
3. Scroll to the bottom and pick the "Share Draft (internal)" action.
In the share window sure the site picker is shown - the editor should not be shown.
> Fixes a bug that was causing the share flow to be broken in internal.

- RELEASE-NOTES.txt
- WordPress/Classes/Models/AbstractPost.m
- WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
- WordPress/WordPressTest/ViewRelated/Post/Controllers/PublishSettingsControllerTests.swift
Fixes #13506 by adjusting the logic to determine whether a post should be immediately published.
To test:
* Create a post and save as Draft.
* Edit the draft, and view Post Settings.
* Notice the 'Publish Immediately' message.
* Tap 'Published Immediately'. Notice the 'Date and Time: Immediately' message.
> Wrong publish string in post settings

- Gemfile.lock
- Scripts/fastlane/Fastfile
- Scripts/fastlane/Pluginfile
This PR adds a new `build_release` lane, based on the `build_and_upload_itc` one, that, after the build, creates the GitHub release and upload the xarchive.
1. Tag a commit with a version that we don't use (for example `10.10`) and push the tag.
2. Update `Version.public.xcconfig` to use the same version.
The easy way:
3.a. Comment out the `ios_build_prechecks`, `ios_build_preflight`, `testflight` and `sentry_upload_dsym` from the `build_and_upload_itc` lane.
The complex way:
3.b Checkout a new `release/10.10` (or what you used) branch out of this one and push it.
4. Run `bundle exec fastlane build_release`.
5. Verify that after the build, a new 10.10 release has been drafted in GitHub and the XArchive and the release notes have been uploaded.
*Clean Up*
6. Delete the release from GitHub. …
> Add GitHub release creation to the release tooling

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/System/Floating Create Button/FloatingActionButton.swift
- WordPress/Classes/ViewRelated/System/Floating Create Button/HideShowCoordinator+HideShowCreate.swift
- WordPress/Classes/ViewRelated/System/Floating Create Button/WPTabBarController+CreateButton.swift
- WordPress/Classes/ViewRelated/System/Floating Create Button/WPTabBarController+HideShowCreate.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.h
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressUITests/Screens/TabNavComponent.swift
- WordPress/WordPressUITests/Tests/MainNavigationTests.swift
#13320 
This adds the hide/show functionality to the Create Floating Action Button and repositions the button to sit over the primary view controller in the split view controller.
We've decided to only show the Create button on the Blog Detail screen. Because of that, the implementation has changed to simply show/hide the button when that screen is appearing or disappearing. This simplifies some of the previously complex (and fragile) logic in #13544.
<a href="https://user-images.githubusercontent.com/3250/75308936-e69b2300-580c-11ea-86b6-fcdf1da65505.gif"><img src="https://user-images.githubusercontent.com/3250/75308936-e69b2300-580c-11ea-86b6-fcdf1da65505.gif" width="300"></a>
To test:
- View Blog Details page to see the create button
- All other views should hide the button
PR …
> Add hide/show animation to floating action button

- WordPress/Classes/ViewRelated/System/Floating Create Button/FloatingActionButton.swift
- WordPress/Classes/ViewRelated/System/Floating Create Button/WPTabBarController+CreateButton.swift
Many thanks to @emilylaguna for reporting this issue!
When the My Sites tab is not in the view hierarchy at the time the floating Create button is added to the tab bar, constraint exceptions can result.
This _shouldn't_ be possible with the move of the Me button to the Blog Details screen (upon logout, you're always back at the My Sites tab), but this commit should ensure that the exception doesn't occur and activates the FAB trailing constraint in a single location.
To test:
* Disable the `meMove` feature flag
* Log out of an account from the Me tab
* Log back in to that account
* Should crash the app with an autolayout exception.
> Wait to activate trailing constraint until update

- WordPress/Classes/ViewRelated/Blog/Blog + Me/UIBarButtonItem+MeBarButton.swift
- WordPress/Classes/ViewRelated/Me/App Settings/About/AboutViewController.swift
- WordPress/Classes/ViewRelated/Views/CircularImageView.swift
- WordPress/WordPressTest/BlogDetailsViewController+MeButtonTests.swift
- Add a larger transparent view behind the gravatar `Me` button to enlarge the tappable area. To keep the same position of the gravatar, this is vertically centered in the transparent view, and aligned to the right (trailing margin set to 0). The size of the transparent view is 44 x 44
- Add a white border to the gravatar
- Present modally the web views from `AboutViewController()
Ref #13319
To test:
- go to `My Site`
- Check that the `Me` gravatar button: 
- works as expected
- has a comfortable tap area
- Go to App Settings -> About
- check that the web views (e.g. Acknowledgement) are presented modally and no bottom bar persists in the `Me` screen after they are dismissed. 
> Enlarge tappable area behind the `Me` gravatar button

- Podfile
- Podfile.lock
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/13583
This PR improves the error handling so that we don't ignore some error responses.
Try signing up with a valid email account.  It should send you the magic link.
Try signing up with an invalid email provider.  For example "tester@mailinator.com".
You should see an error prompting you to use a different email provider.
Try singing up with a used email address (you can try with the email of your existing account).
You should see an error letting you know the email address is not available.
> Integrates new versions of WPKit and WPAuth to fix a signup issue.

- WordPress/Classes/Services/AccountSettingsService.swift
- WordPress/Classes/Services/WordPressComSyncService.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
In this PR we're adding new API to **AccountSettingsService**, that deals with Display Name changes, and wiring it in the Signup Epilogue. Why:
- Former mechanism involved using `AccountSettingsChange`, meant to keep Core Data in consistent state, in the scenario of a REST call failure
- The Signup Epilogue **isn't tied up** (AKA does not populate) its fields from Core Data
- The **AccountSettings** are not synchronized in the Epilogue
- And furthermore, the Epilogue **does not need** the **AccountSettings**
For the reasons above, it makes 1000% sense to mimic the same mechanisms used in the Epilogue to (A) Change Passwords or (B) Change Username, without going thru `AccountSettingsChange` (which is not really needed here).
Fixes #13594
cc @diegoreymendez WDYT? (Thanks in advance!!
1. …
> WordPressComSyncService: Synchronizing Settings

- Podfile
- Podfile.lock
Same as https://github.com/wordpress-mobile/WordPress-iOS/pull/13585 but for 14.3.
Use the same testing steps.
> Integrates WPKit and WPAuth into 14.3.

- WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift
- WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
Fixes #13592 
To test (in dark and light mode):
1. Add a new site
2. Get to the domain search screen
3. Search for a domain
4. see loading indicator when results are loading 
5. See loading indicator removed when done loading results 
Not loading|Loading
-|-
> Show loading indicator when searching domains

- WordPress/Classes/Utility/Editor/GutenbergSettings.swift
- WordPress/WordPressTest/EditorSettingsServiceTests.swift
- WordPress/WordPressTest/GutenbergSettingsTests.swift
Remove the Gutenberg dialog that was showning after creating a new site by setting gutenberg as default.
Since Aztec was set as default, the logic run the migration to gutenberg and set the dialog to be shown.
Just setting gutenberg as default should have been enough, but there was an issue where the URL string on the site creation flow appends a trailing `/`. This URL is used as the key for gutenberg `enabledOnce` setting. After refreshing the URL from remote, the trailing `/` was removed, creating a different key, so `enabledOnce` was returning false (and showing the dialog when it shouldn't).
This PR solves that issue ensuring that there are no trailing `/`s when saving the `enabledOnce` setting.
**To test:**
Test 1:
- Create a new site.
- Create a new post, make sure the block editor …
> Remove the Gutenberg dialog on new sites

- WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
Fixes (Issue not yet opened)
To test:
- Disable the feature flag for `Me`
- Build/run
- Go to the `Me` tab
- check that the sub levels of the navigation display correctly on iPad (portrait and landscape) or iPhone 11 Pro Max landscape, as well as any iPhone in portrait
- Repeat the tests with the feature flag enabled.
> Fixes the split view for the existing Me Tab

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/StatsViewController.m
Fixes #12951 by switching to use the grouped table view's background color. This is a grayer color than the original but I think it fits here.
To test:
|--|--|
| <a href="https://user-images.githubusercontent.com/3250/76365420-e4e15d00-62ec-11ea-83fd-e143f1d03efc.png"><img src="https://user-images.githubusercontent.com/3250/76365420-e4e15d00-62ec-11ea-83fd-e143f1d03efc.png" width="500"></a> | <a href="https://user-images.githubusercontent.com/3250/76365019-ececcd00-62eb-11ea-8041-64c65c9c7dab.png"><img src="https://user-images.githubusercontent.com/3250/76365019-ececcd00-62eb-11ea-8041-64c65c9c7dab.png" width="500"></a> |
| <a href="https://user-images.githubusercontent.com/3250/76365443-f4f93c80-62ec-11ea-8e5b-ab8f2a401331.png"><img …
> Stats background color in landscape

- RELEASE-NOTES.txt
- WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+Search.swift
Fixes #13364 
This fixes the border color of the Search bar when light/dark mode toggled. 
To test:
- Go to any view with a Search bar. (ex: Site Pages, Blog Posts, Themes)
- Switch between light and dark modes.
- Verify the Search bar border color is updated accordingly.
> Search bar: update border color when dark/light mode toggled.

- WordPress/Classes/Extensions/Notifications/NotificationName+Names.swift
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+PushPrimer.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #13593 
As of iOS 8, the application must register for user notifications using -[UIApplication registerUserNotificationSettings:] before being able to set the icon badge which we are relying on when setting the notification tab bar item's to it's unread state. 
Since we don't prompt the user to allow notification (registerUserNotificationSettings) right after signup, we need to show the "unread notification" icon in a different way.
This PR, adds a user defaults key named "welcomeNotificationSeen" and sets it to false right after signup (when the user taps continue on the signup epilogue. 
`updateNotificationBadgeVisibility` in WPTabController, in addition to checking the `applicationIconBadgeNumber` is now also looking for the value of the new UserDefaults key to determine if to …
> Add missing welcome notification indicator 

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
- WordPress/Classes/System/WordPressAppDelegate.swift
Fixes #12759 
Media Picker PR: https://github.com/wordpress-mobile/MediaPicker-iOS/pull/346
This sets the Media Picker's `WPActionBar` appearance to use dynamic colors.
To test:
- Go to a view that allows media multiple selection (ex: Media Library > add, edit post > media gallery > add media).
| ![media_library](https://user-images.githubusercontent.com/1816888/76461508-a65ba900-63a5-11ea-810c-37137559ac9b.png) | ![post_gallery](https://user-images.githubusercontent.com/1816888/76461520-ad82b700-63a5-11ea-9985-a75bb908d9ea.png) |
- Select multiple items so that the action bar at the bottom appears.
- Switch between light and dark modes. 
- Verify the action bar updates accordingly.
| ![light](https://user-images.githubusercontent.com/1816888/76461604-d1de9380-63a5-11ea- …
> Media Picker action bar: customize appearance

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Ref #12441 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/199
This uses the Auth changes that updates the Login & Signup `NUXButton`s when light/dark mode toggled.
NOTE: These buttons are _not_ `NUXButton`s, and therefore are not fixed:
- Sign in with Apple. This will be updated on https://github.com/wordpress-mobile/WordPress-iOS/issues/13620.
- 'Connect another site' button on the login epilogue. This button will be removed with the new epilogue https://github.com/wordpress-mobile/WordPress-iOS/issues/13413, and thus won't be an issue soon.
To test:
- Log out of the app.
- On the initial view, toggle light/dark mode. 
- Verify the buttons update accordingly.
| ![initial_light](https://user-images.githubusercontent.com/1816888/76470599-2a1d9180-63b6-11ea-9d2 …
> Login/Signup buttons: update colors when appearance changes

- Podfile
- Podfile.lock
- WordPress/Classes/Services/MediaService.m
Fixes #11644
This PR changes the MediaService sync code to allow updates of the local CoreData database for each media page loaded from the server. This should allow the user to interact with media libraries quicker and get updates quickly. 
The only downside of this approach is that we are only able to show deletions after all the media library is in sync. This was already was a limitation before, and can only be addressed with changes on the server endpoint.
Related changes on WordPressKit: 
To test:
- Between each test scenario, you need to change the site being used or logout the user
- Scenario 1
- Load the app
- Open a blog/site that has a large media collection
- Open the media library
- See if it shows the initial library contents quickly
- Check that all loads in the end
- …
> Allow media updates while media pages are loading.

- Scripts/fastlane/Fastfile
This PR fixes the hotfix branch creation tooling. 
The current implementation tags the branch as soon as it's created, which means that the tag has to be manually deleted and re-added after the changes are merged. 
This PR removes the tagging step from the creation lane and adds a short lane only for tagging. 
> Update hotfix tooling

- WordPress/Classes/ViewRelated/Views/NoResultsViewController.swift
This PR updates the default title for `NoResultsViewController` when the user is offline,  so it's more generic and appropriate for all cases.
VCs that want to have a more specific message can do so through the `NoResultsViewController` class interface.
Fixes #13604 
> Updated the default offline title for NoResultsViewController.

- WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
- WordPress/Classes/ViewRelated/Me/App Settings/DebugMenuViewController.swift
Fixes #13619. This PR updates the Quick Start snack bar highlight text to use a regular font weight instead of semibold.
**To test:**
* To make this easier to test, I added a new tool to the Debug menu (available via Me > App Settings > Debug). Tap "Enable Quick Start for Site" and choose a site to add Quick Start to. 
* Close the modal that appears, and navigate to the site in My Sites.
* Follow the instructions to set a site icon, by tapping the site's icon.
* The next notice that's displayed should contain a highlighted section, and should appear in regular text not semibold.
cc @elibud
> Tweak Quick Start Highlight Font

- WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Blog.swift
Fixes #n/a
Ref #13413 
This updates the border on the site icons to update when toggling light/dark mode.
To test:
- Log into the app with an account that has sites.
- On the epilogue, switch between light/dark mode.
- Verify the site icon image border updates accordingly.
| ![before](https://user-images.githubusercontent.com/1816888/76558123-5c84c880-6462-11ea-8583-4f86dec978e1.png) |  ![after](https://user-images.githubusercontent.com/1816888/76557875-f304ba00-6461-11ea-9345-b6092dbbcc19.png) |
> Login Epilogue: Update site icon border color when appearance mode changes.

- Podfile
- Podfile.lock
Integrates the fix for this issue: https://github.com/wordpress-mobile/WordPressKit-iOS/issues/228
Go to the list of plans for a site and check that the console doesn't report any message like this one:
```2020-03-04 15:56:59:708 Error parsing plans response for site dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "rawPrice", intValue: nil)], debugDescription: "Parsed JSON number <9.5> does not fit in Int.", underlyingError: nil))```
> Integrates WPKit 4.6.0-beta.5

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes #13638 
This allows the Reader Comments view to update when light/dark mode toggled.
To test:
- Go to the Reader.
- On a post with comments, select Comments.
- Switch light/dark mode.
- Verify the view updates accordingly, specifically:
- The header bottom border (i.e. the "Comments on" block).
- Comment text color.
- Action bar icons (i.e. Reply, Likes).
> Reader Comments: update content when appearance changes.

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Reader/Reader.storyboard
Fixes #12470
To test:
- Open a post in Reader
- Check bottom toolbar
> Stretch Reader toolbar to edges of view

- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Fixes # n/a
To test:
- `rake dependencies`
- build & run
These warnings should disappear:
> Remove duplicate param in method

- Podfile
- Podfile.lock
To test:
- install dependencies
- verify that build/run are successful
> Update NSURL+IDN version to 0.4

- Scripts/fastlane/Fastfile
Cleans up a periodic alert in Sentry, and lets us get crash data for anything that happens in one.
**To test:**
Note the following section of the build log in CI:
```
[23:55:07]: --------------------------------
[23:55:07]: --- Step: sentry_upload_dsym ---
[23:55:07]: --------------------------------
[23:55:07]: sentry-cli 1.51.1 installed!
[23:55:07]: Starting sentry-cli...
[23:55:10]: > Found 11 debug information files
[23:55:11]: > Prepared debug information files for upload
[23:55:18]: > Uploaded 11 missing debug information files
[23:55:18]: > File upload complete:
[23:55:18]: 
[23:55:18]: PENDING fa53b492-4e3d-3dba-a76a-a5351184397b (WordPressNotificationContentExtension.appex.dSYM/Contents/Resources/DWARF/WordPressNotificationContentExtension; arm64 debug companion)
[23:55:18]: …
```
> Add symbol upload for installable builds

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallStateView.swift
- WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift
Fixes #13441 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/202
This updates the Jetpack install flow to use the correct color scheme.
To test:
- Follow the steps on #13441 .
- Verify the background and text colors are correct.
| ![init](https://user-images.githubusercontent.com/1816888/76669964-a1d4f300-6553-11ea-92be-91dd3f15f125.png) | ![install](https://user-images.githubusercontent.com/1816888/76669967-a9949780-6553-11ea-9ff6-d6db36433a90.png) |
Hack:
- You can force show the `Don't have an account?` button if you don't want to actually install Jetpack. In `LoginEmailViewController:configureForWPComOnlyIfNeeded`, set `wpcomSignupButton?.isHidden = false`. The signup button will then always show on the email entry view. 
PR submission …
> Update Jetpack install flow to use most recent colors.

- WordPress/Classes/Services/NotificationSyncMediator.swift
- WordPress/Classes/ViewRelated/Comments/CommentViewController.m
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTableViewCell.swift
In this PR we're working around an Autolayout-Engine-Y (alledged) bug, which results in text getting cut off.
**PLUS** since I was in the neighborhood, I'm patching up the Comment Notification Actions spacing, since current layout yields cutoff text in smaller devices.
@diegoreymendez May I bug you with a hopefully quick one?
After literally... hours of debugging, i've managed to pinpoint exactly what's going on.
0. **NoteBlockCommentTableViewCell** is the exact component that's getting cutoff
1. During cell initialization (before there's a superview) we set all of its properties
2. Whenever **NoteBlockCommentTableViewCell.isApproved** runs, we were executing the method **refreshSeparators**
3. The above lead, in a specific flow, into the execution of …
> Notification Layout Issues

- Podfile
- Podfile.lock
Fixes # n/a
This PR updates WPiOS to use the latest Authenticator changes (update the Lottie pod).
Ref. https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/204
**To test:**
1. `rake dependencies`
2. build and run
3. If already logged in, log out
4. Swipe through the carousel. All animations should run as expected.
**Do not merge until:**
1. Lottie pod changes in Authenticator have been merged https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/204 ✔️
2. Authenticator 1.11.0-beta.9 has been published to CocoaPods trunk ✔️
3. This branch is pointing to the published pod version 1.11.0-beta.9 ✔️
> Point podfile to Lottie update branch. Update podfile.lock

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Fixes #13664 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/206
This uses the Auth changes to display updated Magic Link instruction text.
To test:
- Login or Signup.
- Select `Send Link`.
- Verify the displayed text matches that on #13664 .
| Signup | Login |
| ![signup](https://user-images.githubusercontent.com/1816888/76797366-f0240500-6792-11ea-8ca7-0d63083da2c5.jpeg) | ![login](https://user-images.githubusercontent.com/1816888/76797378-f5814f80-6792-11ea-907a-985374a86089.jpeg) |
> Update Magic Link instructions

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift
Adds startup time to the `editor_session_start` event.
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1988
Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/11411
To test:
Look at the tracks logs in the console and ensure the `startup_time_ms` gets added to `editor_session_start` and it reflects the actual startup time of the editor.
> Add editor startup time

- Podfile
- Podfile.lock
Fixes a signup regression.  Existing accounts should be redirected to login, instead of displaying an error.
WPAuth: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/208
WPKit: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/235
These tests are the same we did on the WPKit and WPAuth PRs.  Since the code hasn't changed since that PR was tested, there may not be a need to re-check all 3 cases here.
1. Check out the WPiOS branch.
2. Install the pods.
3. Run the app from scratch.
4. Try to sign up with an existing account.
Verify that you're redirected to login and that you an complete the login process.
Same test steps as in Test 1, but try to sign up with a mailinator account instead (any random account will do, like `testing@mailinator.com`).
Verify that …
> Fixes a SignUp regression.

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Ref #13620 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/209
This uses the Auth changes to display the updated Google buttons.
To test:
- If logged in, log out.
- Select `Log In` and `Sign up`.
- Verify the Google button displays the logo and `Continue with Google` text.
| Login | Signup |
| ![login](https://user-images.githubusercontent.com/1816888/76899428-1ca45380-685d-11ea-987f-465a8e56a79d.png) | ![signup](https://user-images.githubusercontent.com/1816888/76899439-2332cb00-685d-11ea-88e2-10d0801987c8.png) |
> Show updated Google login/signup button

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Post/Scheduling/CalendarCollectionView.swift
- WordPress/Classes/ViewRelated/Post/Scheduling/CalendarMonthView.swift
- WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/ViewRelated/Post/Controllers/SchedulingCalendarViewControllerTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Views/CalendarHeaderViewTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Views/WeekdaysHeaderViewTests.swift
Fixes #13651:
When the time zone of your site is after your device's time zone, the prior date is shown when selecting from the calendar.
To test:
- Set your time zone to one that is after that on your device (site: PST if device is in EST)
> Wrong calendar date when timezone differs

- WordPress/WordPress-Internal-Info.plist
- WordPress/Wordpress-Alpha-Info.plist
To test:
- download the installable build on iPad
- Alternatively, from Xcode, build and run with Release-Alpha configuration
- verify that the alternate app icons are available in App Settings -> App Icon
> Add CFBundleIcons~ipad dictionary to WordPress-Internal-Info.plist and Wordpress-Alpha-Info.plist

- WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
- WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/Bottom Sheet/BottomSheetViewControllerTests.swift
Fixes #13659
This PR creates the Bottom Sheet to be used for Prepublishing Nudges.
Most of the code is basically a copy-and-paste of the work @bjtitus has been doing with a few changes:
* The `BottomSheetViewController` needs another `UIViewController`
* The `view` of this `UIViewController` is what will be displayed in the Bottom Sheet
2. Tap "Publish"
3. Check that the Bottom Sheet appears
If you're using iPad, the sheet should behave as a popover and appear from the "Publish" button.
> Create Bottom Sheet

- WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.h
Fixes #NA
To test:
- build/run
- verify that when tapping the `Notification` tab bar icon, analytics do not track `me_tab_accessed`
> Fix wrong analytics tracks when accessing notifications tab

- WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fix #13633
Related to #13320 
This moves the Create Button to the Blog List's navigation controller. The animations will still occur when switching between screens in that navigation stack, but will not occur when switching tabs. The requirement to position the button next to the edge of the primary split view controller instead of the right hand side of the screen had made some of the constraints less than reliable. This change should resolve that since the view and its constraints are part of the same hierarchy.
This also removes animations when Reduced Motion is enabled.
To test:
> Move FAB to Blog List Navigation Controller

- WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
Ref #13413 
This addresses two issues from @mattmiklic 's PR reviews.
- My Sites list - If the user has no sites drop the "My Sites" header (https://github.com/wordpress-mobile/WordPress-iOS/pull/13561#pullrequestreview-371341140)
- User Info - adjust is the amount of extra space between the Gravatar and the display name (https://github.com/wordpress-mobile/WordPress-iOS/pull/13543#issuecomment-596603280)
To test:
---
**My Sites header:**
- Log in with an account that has no sites.
- Verify the `My Site` header no longer appears above `Connect a site`.
| iPhone | iPad |
| ![no_sites_iphone](https://user-images.githubusercontent.com/1816888/77211614-1ff04700-6aca-11ea-8bc5-5f2eff6842de.png) | ![no_sites_ipad](https://user-images.githubusercontent.com/1816888/77211622-254d …
> Login Epilogue: misc changes

- WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
- WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.h
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
Pat of #13320 
- Sets "tap_source" to "create_button" when accessed from the button
- Code adjustments to be able to change "tap_source" when showing the page (for deep linking)
- Adds "create_sheet_shown" event
- General renaming
To test:
- Tap the Create Button and notice the new "create_sheet_shown" event
- Tap either option in the action sheet and notice that "tap_source" = "create_button"
> Create Button Tracks Additions

- WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteCreationRotatingMessageView.swift
This PR fixes a localisation warning in `SiteCreationRotatingMessageView` due to a variable being passed to `NSLocalizedString`.
As far I understand, `SiteCreationRotatingMessageView`  is instanced only in `SiteAssemblyContentView` and the strings in the _statusMessages_ array are already localised [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/6599f3ecd6787270fbac0bebda3401788d066daa/WordPress/Classes/ViewRelated/Site%20Creation/FinalAssembly/SiteAssemblyContentView.swift#L175), so I think that we can simply remove  the call to `NSLocalizedString`. 
> Fix localization warning

- WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
Fixes #13721 
**To test:**
1. Create a new blog post
2. Tap the publish button
3. Tap the drag handler and slide down to begin dismissing
3.a. Flick down to dismiss quickly
3.b Slowly drag down to dismiss interactively 
Expected Result:
- While dragging you are able to slide the view up/down
- When flicking the view dismisses
**Demo**
> Change how the interactionControllerForDismissal gets the interactionController

- WordPress/Classes/System/WordPressAppDelegate+openURL.swift
- WordPress/Classes/Utility/Universal Links/Route+Page.swift
- WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Adds the following Deep Link routes:
`wordpress://newpage` following the same URL query parameters as the `newpost` URL but without`tags`:
* `content` at minimum
* `title`
`https://apps.wordpress.com/get#/page`
`https:/apps.wordpress.com/get#/page/<domain>`
Part of #13320
- Open `https://apps.wordpress.com/get#/page` as a link (I used Messages to send myself the link and open the app. All other copies of the app must be uninstalled since I believe it is random which copy of the app is chosen to open the URL)
- Open `wpdebug://newpage?content=test` as a link (also used Messages for this one after configuring the app to register for the wordpress scheme)
> Add deep link for Page editor

- WordPress/Classes/Models/Notifications/Actions/ApproveComment.swift
- WordPress/Classes/Models/Notifications/Actions/EditComment.swift
- WordPress/Classes/Models/Notifications/Actions/Follow.swift
- WordPress/Classes/Models/Notifications/Actions/LikeComment.swift
- WordPress/Classes/Models/Notifications/Actions/LikePost.swift
- WordPress/Classes/Models/Notifications/Actions/MarkAsSpam.swift
- WordPress/Classes/Models/Notifications/Actions/ReplyToComment.swift
- WordPress/Classes/Models/Notifications/Actions/TrashComment.swift
This PR fixes the build problems when using Xcode 11.4 to build the project
To test:
- Check the notification area of the app
- Try to mark notification with the multiple actions available: like, spams, reply, etc..
> Refactor Comment action method signature to be compatible with Xcode 11.4

- WordPress/Classes/Utility/ZendeskUtils.swift
Fixes #13473
To test:
- Go to Me > Help & Support.
- Tap `Contact Email`.
- Tap in the text field to bring up the keyboard.
- Enter a valid email address. Verify tapping `return` dismisses the alert.
- You can tell it's valid because the `OK` button will be enabled.
- Enter an invalid email address. Verify tapping `return` does nothing.
- You can tell it's invalid because the `OK` button will be disabled.
> Support Contact Email: Validate email when Return keyboard button pressed.

- Podfile
- Podfile.lock
First reviewer wins 🏆 
Fixes # n/a
Ref. https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/223
1. Check out this branch
2. `rake dependencies`
3. Build and run
4. Select the Log in button
5. Verify the "Continue with Google" and "Continue with Apple" buttons have a logo and the spacing is correct.
6. Select the carousel to dismiss the Log in button view
7. Select "Sign up for WordPress.com" and verify the Google and Apple buttons are correctly spaced.
8. Select "Sign up with Email" and verify the NUX button has the correct insets (the hotfix was accidentally reverted).
1. The Authenticator PR has been merged: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/223
2. The Authenticator changes have been released
3. The release has been published to …
> Correct the whitespace for a translation string

- WordPress/Classes/System/WordPressAppDelegate+openURL.swift
- WordPress/Classes/Utility/Universal Links/Route+Page.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
Fixes bad merge. `showPageTab` changed to `showPageEditor`.
To test:
- Compile
> Change showPageTab to showPageEditor

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- Scripts/fastlane/Fastfile
- Scripts/fastlane/Pluginfile
This PR introduces release builds on CI. 
The builds are triggered by pushing a release tag.
Tags that don't have a `version`-like format are not considered.
On beta tags (`x.y.z.a`) the system runs the internal and the app store builds. 
On final tags  (`x.z.<z>`) the system runs only the app store builds. 
The artifacts are uploaded to AppCenter and AppStore. 
[This branch](https://github.com/wordpress-mobile/WordPress-iOS/tree/release/14.3.1) has been checked out from the source of this PR and it has been adjusted with a fake version and tags in order to test this PR. 
The build log for the build triggered by the tag is here: https://circleci.com/gh/wordpress-mobile/WordPress-iOS/24967.
Note:
As soon as this is approved and before merging it, we have to:
- delete the artifact from …
> Add beta builds on CI

- WordPress/Classes/Utility/ZendeskUtils.swift
- WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Fixes #12277 
The cause of #12277 was that `ZendeskUtils` was trying to get user information for display purposes and also for the Zendesk identity. These two goals conflicted.
While researching the problem, I realized there was really no need to show `Not Set` for the email initially because we know the email (if the user is logged in). So now the email is auto-populated initially (and consistently). Behind the scenes, the user information is now obtained when Support is first displayed, instead of when a user attempts to access Zendesk.
**To test:**
The only visible change is auto-populating the email address. The other items to test are verifying existing functionality (i.e. ensuring I didn't break anything).
---
**Prerequisite**: Start with a fresh install (to clear User Defaults). …
> Support: get user information when view initially displayed

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes #13577 
The issue was caused by the no results view being added to the top of the view stack, causing it to cover the suggestions table, blocking selection. This change inserts the NRV below the suggestions table.
To test:
- Go to the Reader.
- Find a post with no comments.
- Tap the comments icon.
- The no results view will display `Be the first to leave a comment.`
- Tap in the reply text view.
- Type `@` to display @ suggestions.
- Verify:
- The no results message appears behind the suggestion list.
- You can select a suggestion.
> Comment mentions: move NRV behind suggestions table

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift
This PR reverts https://github.com/wordpress-mobile/WordPress-iOS/pull/13510 to fix a crash on WPiOS 14.4 when inserting a button block.
This PR was merged to develop and released directly to WPiOS 14.4 without a proper gutenberg release, so we have skipped the regular tests before releases.
https://github.com/wordpress-mobile/WordPress-iOS/pull/13756/commits/f092a137090cf34e5d619c6849c6c56fd5d12a5c was needed to fix a failing unit test, that test for analytic events mapping. We couldn't revert WP-Shared version since it brings also other new events needed for other features.
This reverts commit aa0fa2f3a59276ad83ae76260029eac8a773e6e4, reversing
changes made to e42a658a9f188b1a28b4fae8961b3e9080f09560.
To test:
- Open the block editor.
- Insert a button block.
- Check that it doesn't …
> [Gutenberg] [Hotfix] Set Gutenberg version to v1.23

- WordPress/Classes/ViewRelated/Notifications/FormattableContent/Styles/SubjectContentStyles.swift
- WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
Fixes #13340 
To test:
- Go to Notifications.
- Verify the bold text is now semibold.
| ![before](https://user-images.githubusercontent.com/1816888/77695582-9e893080-6f71-11ea-9fe4-567590d9178d.png) | ![after](https://user-images.githubusercontent.com/1816888/77695600-a47f1180-6f71-11ea-9e80-26a7307b54c5.png) |
> Notifications: change subject font to semibold

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
🙏 @Gio2018 for pointing this out and noticing the layout loop.
- Use a UIStackView for the Notifications header so the view can just be hidden for collapse instead of manipulating a constraint.
- Remove the unnecessary layout calls
- Tweaks to the animations for hiding the prompt and showing the prompt
Fixes #13744 
|--|--|
| <a href="https://user-images.githubusercontent.com/3250/77853965-8f3df900-71a4-11ea-9367-09d0d53fb6c1.gif"><img src="https://user-images.githubusercontent.com/3250/77853965-8f3df900-71a4-11ea-9367-09d0d53fb6c1.gif" width="300"></a> | <a href="https://user-images.githubusercontent.com/3250/77853972-995ff780-71a4-11ea-9255-6102911c2645.gif"><img src="https://user-images.githubusercontent.com/3250/77853972-995ff780-71a4-11ea-9255-6102911c2645.gif" …
> Change to a Stack View for Notifications Header

- WordPress/Classes/Utility/WPMediaEditor.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fix the `source` when adding an image in Aztec through Media Editor and add a new property to check how many images are being shown in the Media Editor.
1. Create a new post in Aztec
2. Add an image
3. Edit the image using the Media Editor
4. Check that the property `wpios_editor_photo_added` has the property `via: media_editor`
1. Add a Gallery block in Gutenberg
2. Tap "Add media" and then select "Choose from device"
3. Select multiple images from the device
4. Tap "Preview X" (at the left bottom corner)
5. Check that `media_editor_shown` is triggered with the correct `number_of_images`
> Fix Media Editor track in Aztec

- Scripts/fastlane/Fastfile
This PR adds a step to the `code_freeze` lane that checks that mobile Gutenberg is referenced by version number and not by commit hash. 
If a reference by commit hash is found, the script fails on CI and ask the user if they want to continue or stop on local environments.
1. Verify that Gutenberg is referenced by version in the `Podfile`.
2. Run `bundle exec fastlane code_freeze` and verify that the script shows a prompt with its proposal for the next version number. **Abort** the execution.
3. Edit the `Podfile` so that Gutenberg is referenced by commit hash.
4. Run `bundle exec fastlane code_freeze` and verify that the script shows a prompt about the Gutenberg reference and asks what to do. Agree to continue and verify that the script shows a prompt with its proposal for the next …
> Add Gutenberg specific checks to Code Freeze

- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
- WordPress/Classes/ViewRelated/Post/PostVisibilitySelectorViewController.swift
- WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
This is a refactor to allow the Post Visibility selection View Controller to be used in other parts (Nudges View, I'm looking at you).
2. Go to Settings
3. Change the visibility
The post should be published with the visibility you specified.
> Extract post visibility selection

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Enabling internal flag for #13320
Enabling internal flag for #13319
To test:
- Open app and notice removal of New Post and Me button from the tab bar
- Create FAB button should be visible in the bottom right when on the Blog Details screen
- Me button should be visible in the Navigation Bar when on the Blog Details screen
> Enable Me and Floating Create button for internal builds

- RELEASE-NOTES.txt
- WordPress/Classes/Models/Blog.m
Fixes #13742
To test:
- Ensure that the display URL is shown in the list of Blogs and Blog Details screens.
> Ensure non-null Blog url before search

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/GhostViews/StatsGhostCells.swift
Fixes #13781 
This updates the stats period chart, date bar, and stats ghost cells to re-animate when the appearance changes so the ghost colors are updated.
To test:
- On a slow network, go to Stats > any period (Days, Weeks, Months, Years).
- While the ghost animation is displayed, toggle light/dark modes.
- Verify these ghost colors update accordingly.
- Date bar. 
- Chart.
- Stats rows.
| ![broken](https://user-images.githubusercontent.com/1816888/78191344-08528000-7433-11ea-9aaa-78e8581b5e58.gif) | ![fixed](https://user-images.githubusercontent.com/1816888/78191305-f7a20a00-7432-11ea-80f0-e6154272b8f0.gif) |
> Stats Period: light/dark mode ghost colors 

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Post/InteractivePostViewDelegate.swift
- WordPress/Classes/ViewRelated/Post/PostActionSheet.swift
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/WordPressTest/PostActionSheetTests.swift
- WordPress/WordPressTest/ViewRelated/Post/Views/PostCardStatusViewModelTests.swift
This PR implements the feature as described in #12314 
To test:
1. Go to Posts -> Published tab
2. Tap *more* button, then select Share
3. The Share activity dialog should show and allow user to share the published Post.
iPhone:
iPad:
> Add Share action into post "more" button in the Posts list

- .circleci/config.yml
This change sets up a CircleCI workflow to optionally run UI tests on PRs. This is the iOS equivalent of these Android changes:
* https://github.com/wordpress-mobile/WordPress-Android/pull/11495
* https://github.com/wordpress-mobile/WordPress-Android/pull/11535
* https://github.com/wordpress-mobile/WordPress-Android/pull/11575
Here's an overview of the changes:
* UI tests continue to run automatically on the `develop` and `release/*` branches. When a test fails on one of these branches, a Slack notification will be posted in `#ios-osx-dev` similar to this:
* On PRs, UI tests will only run on PRs when the `Optional Tests` job is manually approved on CircleCI. (Peril will be set up to force the `Optional Tests` check to have a `success` status on the PR, so you can ignore it if you don't …
> Testing: Make UI tests optional on PRs

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #13763 
To test:
- Go to Reader.
- Select a post.
- Switch between light & dark modes.
- Verify the area around the image (or title if there is no image) is updated accordingly.
| ![broken](https://user-images.githubusercontent.com/1816888/78305795-0d7d0100-74ff-11ea-8459-627adbbdc3f4.png) | ![fixed](https://user-images.githubusercontent.com/1816888/78305867-39988200-74ff-11ea-8ff8-ee6cf7e08ac6.png) |
> Reader detail: fix background colors when switching appearance

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/Spotlight/SearchManager.swift
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
- WordPress/Classes/ViewRelated/Post/PostNoticeNavigationCoordinator.swift
Sets the Post Preview to the `.fullScreen` modal presentation style. iOS 13 changes the default modal presentation style for iPads so that the view does not take up the entire screen. We want the full size of the preview to be shown on iPad.
|--|--|
| <a href="https://user-images.githubusercontent.com/3250/78207730-c25fe100-745f-11ea-9ff5-18667ccf477b.png"><img src="https://user-images.githubusercontent.com/3250/78207730-c25fe100-745f-11ea-9ff5-18667ccf477b.png" width="350"></a> | <a href="https://user-images.githubusercontent.com/3250/78207753-cc81df80-745f-11ea-8b6d-dcbea1e5bfb2.png"><img src="https://user-images.githubusercontent.com/3250/78207753-cc81df80-745f-11ea-8b6d-dcbea1e5bfb2.png" width="350"></a> |
To test:
- Open a Post Preview from the Post List, the Post …
> Change iPad Post Preview presentation to fullscreen

- WordPress/WordPressUITests/WordPressUITests.xctestplan
We have started seeing the `testTabBarNavigation()` fail inconsistently in `develop` UI test runs, on the Reader step (opening Reader search with the keyboard up, instead of the Followed Sites screen).
This PR disables that test until we have time to thoroughly investigate and fix that failure.
To test:
* Confirm `testTabBarNavigation()` is disabled (isn't run with the UI tests).
* Confirm all other UI tests pass.
> Testing: Disable tab bar navigation test due to unexpected failures

- WordPress/Classes/Networking/MediaRequestAuthenticator.swift
Fixes #13811 
The old proxy endpoint was:
`/sites/${ siteIdOrSlug }/atomic-auth-proxy/file${ mediaPath }`
The new one is:
`/sites/${ siteIdOrSlug }/atomic-auth-proxy/file?path=${ mediaPath }`
1. Create an Atomic Private Site following the instructions from p58i-8xH-p2
2. Remember to make sure the site is indeed, well, private 😄 
3. Publish a post with an image through the web, or set the site's icon.
4. Before running WPiOS place a breakpoint here: https://github.com/wordpress-mobile/WordPress-iOS/blob/665162286a4bd8a518934d8a90d511f37fe7b1d4/WordPress/Classes/Networking/MediaRequestAuthenticator.swift#L229
5. Run the App and make sure that breakpoint is hit for your image.  Check that the URL matches the new endpoint path described above.
6. Make sure the image is shown.
PR submission …
> Changes the auth-proxy path.

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes an issue reported in Mobile Requests (p4a5px-2xL-p2) with navigating to the root of Notifications by tapping the tab bar icon.
To test:
- Enter the Notifications tab
- Tap on one of the Notifications
- Tap again on the Notifications tab
- You should be popped to the root of the Notifications navigation stack (prior to this PR, this was not working)
> Fix new tab selection logic in WPTabBar

- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
- WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.swift
- WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.xib
- WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/PrepublishingHeaderViewTests.swift
Fixes #13849
This PR:
- Makes sure the Voice Over focus move to Prepublishing Nudges when it appears
- That all the options are accessible and the user can return to the main screen
- That the bottom sheet is dismissable
You will need a real device.
1. Enable Voice Over
2. Create a new post
3. Tap Publish
4. Navigate through the Prepublishing Nudges and try to find a dead-end
> Prepublishing Nudges Accessibility Improvements

- WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
- WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
- WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Depends on #13853
Fixes #13876
This PR reduces the space below the grip button and disable gestures to increase the Nudges view height.
1. Tap "Publish..."
2. Tap "Tags"
3. Check that the space between the navigation bar and the grip is zero
> Changes grip button margin

- WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
Fixes #13879
The method `configureScrollViewInsets` was crashing due to a `nil` property only on devices.
We just check if `presentingViewController.view` exists before moving on.
Using a DEVICE (the crash doesn't happen on Simulator):
* Tap "Publish..." to show the Nudges view
* Tap "Publish" option to schedule
* Dismiss the calendar
* Dismiss the Nudges view
* Tap "Publish..." to show the Nudges view again
* Tap "Tags"
* Tags show be displayed
> Fix crash on Bottom Sheet

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
We'd like to test making the Sign Up button on the login prologue the primary action. This PR pulls in the relevant WPAuthenticator pod update to make this change.
**To test:**
* Log out if already logged in
* Ensure the log in and sign up buttons match the appearance above, with the Sign Up button being the most prominent
> WPAuthenticator: Make Sign Up primary prologue button

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Fixes # n/a
This PR removes the segue `.showURLUsernamePassword`, which sends the user to the `LoginSelfHostedViewController`. Now the user is navigated programmatically.
Ref. https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/240
The object of the game is to reach the "username / password" screen 👇 from two different scenarios.
Go through these flows:
**Devs:** not sure how to make an email address flagged as suspicious on purpose, so we'll do it manually.
**Testers:** you might have to skip testing this flow since I don't know how to manually make an email address get flagged as suspicious. 
1. Check out this branch AND check out the Authenticator branch. 
2. In the Authenticator code, go to the `LoginEmailViewController`. Remove the success code starting at L367. …
> Remove the .showURLUsernamePassword segue and replace with navController

- WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
Sets the Quick Actions maximum width to 500 points based on feedback to reduce spacing from @osullivanchris and to avoid running into the FAB.
- Visit the Blog Details Page
- Check the Quick Actions Buttons in Portrait and Landscape
<details>
<summary><strong>iPhone 11 Pro</strong></summary>
</details>
<details>
<summary><strong>iPhone 11 Pro Max</strong></summary>
</details>
<details>
<summary><strong>iPad Pro 11"</strong></summary>
</details>
> Constraint Quick Actions Max Width

- .circleci/config.yml
- Gemfile.lock
- Scripts/fastlane/Fastfile
- Scripts/fastlane/Pluginfile
This PR switches CircleCI test runs to use Fastlane with the [test_center plugin](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center), which supports various testing improvements including retries on failure. This change will retry failed tests (total of 3 test runs) before reporting failures, reducing CI failures due to flaky test results.
**This PR relies on:**
To test:
* Ensure unit and UI tests run as expected on CI, tests pass, and test output is saved.
* You can run the tests locally:
* Build the app for testing. On the command line, you can run `xcodebuild build-for-testing -workspace 'WordPress.xcworkspace' -scheme 'WordPress' -configuration 'Debug' -sdk iphonesimulator -derivedDataPath DerivedData`.
* Before running the UI tests, run `rake mocks` to start the mocks …
> Testing: Use Fastlane for CI test runs with retries

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2153
WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/11647
To test:
**Bug fix**
**New feature & Improvement**
> Gutenberg: update to v1.26.0

- WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
- WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
- WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
Fixes #13902
Check if `editor_post_publish_tapped` is fired.
Check if `editor_post_scheduled` is fired with `via: prepublishing_nudges` property.
Check if `editor_post_scheduled` is fired with `via: settings` property.
Check if `editor_post_visibility_changed` is fired `via: prepublishing_nudges` property.
Check if `editor_post_visibility_changed` is fired `via: settings` property.
Check if `editor_post_tags_added` is fired `via: prepublishing_nudges` property.
Check if `editor_post_tags_added` is fired `via: settings` property.
Check if `editor_post_publish_now_tapped` is fired.
> Prepublishing Nudges Tracks

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSaveForLater+Analytics.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterAction.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSavedPostCellActions.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
Ref #13580
To test:
- go to the Reader
- Save/unsave posts from any stream other than saved
- verify that the 'Saved' tab shows posts accordingly
- Verify that tapping one 'view all' on the toasts switches to the 'Saved' tab
- In the 'Saved' tab, tap on the 'save' icon, and verify that the undo cell appears and behaves as expected
- tap on the 'search' button in the top right corner and verify that the search works same as the old reader.
> Add Saved Posts to the new Reader

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Fixes # n/a
This PR removes the segue `.showSelfHostedLogin`, which sends the user to the `LoginSelfHostedViewController`. Now the user is navigated using a navController.
Ref. https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/242
1. Check out this branch
2. `rake dependencies`
3. Build and run WPiOS.
Navigate to this Self-Hosted Login (Site Address) screen:
By going through these flows:
1. Log In > tap the "entering your site address" link text
2. **Expected:** you are navigated to the self-hosted screen that asks for the site address.
1. Log out if you're logged in.
2. Log in > Continue with WordPress.com > tap the "entering your site address" link text
3. **Expected:** you are navigated to the self-hosted screen that asks for the site address. 
1. After logging in, …
> UL&S: Remove .showSelfHostedLogin segue and replace with navController

- WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueConnectSiteCell.swift
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
Ref #13413 
This adds VoiceOver support to various Login Epilogue components.
To test:
- Login and enable VoiceOver. 
- Select the User Info block at the top.
- VO should say `Account Information. <full name> <username>`.
- The components inside the User Info block should not be accessible.
- Select the `My Sites` header.
- VO should say `My Sites. Heading. A list of sites on this account.`.
- Select a site row.
- VO should say `<site name> <site url>`. (To note, this has not changed, but just for verification.)
- Select the `Connect another site` button.
- VO should say `Connect another site. Button`.
> Login Epilogue: accessibility

- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
We are also disabling the default error message displayed by the
WPMediaPicker and not showing any message and use the no view screen
when media is empty.
Fixes #11320 
Fixes #10941 
To test:
- Navigate to a post where you never synced the media library before
- Turn off the Internet Connection for the device
- Open the Media Library
- Check if the custom empty view shows a no extra alert is presented
- Exit the Media Library
- Turn on the internet connection
- Renter the media library
- Check that media assets shows
- Turn off the connection again
- Pull to refresh
- See if a notice shows up with an easy to understand message.
> Show standard notice for network errors on the Media Library

- .circleci/config.yml
Followup to https://github.com/wordpress-mobile/WordPress-iOS/pull/13810
This updates our CI test runs to match changes to the iOS Orb, where the test output directory is set as a parameter on the `ios/save-xcodebuild-artifacts` step. In this case, `build/results` is the test output directory specified in our Fastlane setup.
Relies on this PR:
To test:
* Confirm unit and UI tests pass and test output is zipped and saved as a CircleCI artifact.
> Testing: Save test output with updated CircleCI Orb

- WordPress/Classes/ViewRelated/Plugins/PluginListViewController.swift
Fixes #13891 
Attempt to fix the crash by adding a check for number of sections in tableViewModel > 0 before accessing a section
> Check sections count before accessing section 0

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
This PR is a small tweak the title of the Blog Detail screen to always read "My Site" instead of duplicating the site name, which is shown in the screen header anyway.
I've chosen not to update all the code references to "My Sites" at this stage, as we may do a further refactoring to the actual hierarchy of the sites list -> site detail screens.
To test:
* Build and run, and check the leftmost tab bar item is titled "My Site"
* Select a site and ensure the header title is "My Site"
* Select a different site and ensure the header title stays as "My Site"
> Update My Sites tab title to My Site

- WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
- WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
- WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PasswordAlertController.swift
- WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.swift
- WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Fixes #13915
* Schedule the post for a future date and check that the cell label changes to "Scheduled for"
* Tap on "Tags" and check that there is a label informing why the user might want to add tags and a "Done" button at the right-top corner
* The blog image has 4pt radius
* The password placeholder has the text "Enter password"
* When using Voice Over, if you do an escape gesture (Z with two fingers) the bottom sheet is dismissed
I've testes other languages and RTL languages, it all work goods. Apparently the calendar doesn't support RTL languages, but I'd say this is out of our scope. I'll open an issue.
> Design improvements

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Fixes #11771 
WPKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/241. This includes the actual fix.
WPAuth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/243. This just updates the WPKit pod version so WPiOS will build.
This includes the WPKit change that now returns a response when Gravatar doesn't find a matching user.
The effect is when logging in with a self-hosted site that does not have a Gravatar associated with the email address, the spinner in the User Info block will now stop and the User Info will be shown.
To test:
- Log in with a self-hosted site that does not have a Gravatar associated with the email address.
- Verify the spinner in the User Info block is removed and the account names are displayed.
> Login Epilogue: stop loading User Info when Gravatar can't be downloaded

- WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
- WordPress/Classes/ViewRelated/Reader/Filter/FilterSheetView.swift
- WordPress/Classes/ViewRelated/Reader/Filter/FilterSheetViewController.swift
- WordPress/Classes/ViewRelated/Reader/Filter/FilterTableData.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
- WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
#13581 This adds the Filter Sheet control for filtering the Reader stream.
- Open to the Reader screen and select the "Filter" button
* No Empty Sites or Tags views. I'll add these in a follow up PR.
* No Unit tests. I will also add these in a follow up PR (maybe the same with the empty views)
@osullivanchris I have a few questions about some things I noticed that we might want to add/change:
- I think we may want to update the designs to show the site's icon to match what the current app is doing. I can do this in a follow up PR.
- Should we show a checkmark next to the currently selected site / tag in the filter table?
- On Landscape iPhone, the bottom sheet starts out "collapsed" (half way down the screen) this doesn't leave much room for scrolling (see the first iPhone landscape …
> 13581: Reader Filter Sheet

- WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
- WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
Fixes #12156
To test:
Go to Period > Posts and Pages > select a post.
Go to Insights > Latest Post Summary > View more.
Note that the differenceLabel color is now grey
- [x ] I have considered adding unit tests where possible.
> Make Post Stats chart difference value grey for current day

- WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorReponseParser.swift
- WordPress/WordPressTest/MediaPicker/Tenor/TenorAPIResponseTests.swift
This PR fixed the issue where the date value of Tenor picker mage's accessibility label was incorrect. This a part of #13803. 
**Test**
You will need the Accessibility Inspector tool running to inspect accessibility label: Right click on the Xcode icon at the macOS Dock, choose Open Developer Tool then select Accessibility Inspector.
- Go to Site -> Media Library
- Tap + button at the top right to access the media options menu
- Tap **Free GIF Library** to bring up the Tenor Picker
- Search for some images
- Tap the Locate button on the Accessibility Tool
- Tap any image in the Tenor Picker, and notice the Label value in the Accessibility Tool shows a correct date
> Tenor: correctly parse GIF date

- WordPress/Classes/Utility/Media/GIFPlaybackStrategy.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextImage.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPTextAttachmentManager.swift
Fixes #13895 (well kind of, read on).
The issue in #13895 is that the GIFs were really large, so we kept loading frames at all times.  This PR changes the amount of frames in the buffer to 300, which means there will be no more jumps when scrolling the reader **AFTER THE GIF IS DONE LOADING**.
There will still be some jumps before the GIFs finish loading, and fixing this IMHO is not great in terms of efforts vs benefit.
Additionally, an issue in the reader was causing attachments to be loaded twice, so these GIFs were animating twice.  This was caused by a strong reference to the images held by a the `mediaArray` we're removing.
1. Load in the reader the post shown in p4a5px-2xT-p2.
2. Make sure that after the GIFs are done loading for good, scrolling is smooth in that post.
> Fixes some issues with GIF images in the reader.

- WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergStockPhotos.swift
This PR fixes an issue where the analytics source of stock photo images being sent as Giphy within Gutenberg Editor. The issue's found when I were working on #13803.
**To test**
1. Go to Site -> Posts, open a Post to edit with **Block Editor** (you may need to switch if your default editor is the classic one)
2. Add an image block, tap **ADD IMAGE** then choose **Free Photo Library**
3. Search and select an image, then tap **Add** button at the bottom right.
4. Notice the message `🔵 Tracked: editor_photo_added <blog_id: 174512392, bytes: 815818752, ext: jpeg, media_origin: not_identified, megapixels: 1, mime: image/jpeg, via: stock_photos>` where the `via` is correctly pointed to `stock_photos` source.
> Wrong analytics image source for Stock Photo in Gutenberg Editor

- WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes #13950
This PR fixes the crash when loading the list of comments.
1. Navigate to the Notifications tab
2. Tap a notification (for example, a notification about a new post)
3. Tap the "comments" icon at the bottom right
4. The app navigates to the list of comments, and should not crash
From my tests, all `comment`'s entities had a `nil` `blog` property. What I did was to change the way the comments and cell is configured. Given a post or siteID/blogID I try to load the `Blog` associated with these params.
Then, this value is given to the cell, who uses it to configure the `MediaHost`. This fixes both the crash while maintains the logic to load images from a private Atomic site.
> Fix crash when rendering comments

- WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes #13950
After talking to @aerych we can simplify the fix for the comments section crash while keeping Reader unaware of `BlogService`.
1. Navigate to the Notifications tab
2. Tap a notification (for example, a notification about a new post)
3. Tap the "comments" icon at the bottom right
4. The app navigates to the list of comments, and should not crash
> Refactor the fix for comments crash

- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Fixes #13959
Posts:
1. Create a new post and add some content
2. Tap Publish
3. Tap "Publish Now"
4. The post should be published
Pages:
1. Create a new *page*
2. Add some content
3. Tap Publish
4. Tap Publish again
5. The page should be published
> Fix crash when publishing a Page

- WordPress/Classes/Utility/Media/GIFPlaybackStrategy.swift
- WordPress/Classes/ViewRelated/Media/Tenor/TenorMedia.swift
- WordPress/Classes/ViewRelated/Media/Tenor/TenorPicker.swift
This PR adds support for animating GIF in the Tenor Picker as an enhancement for #13803. It is a follow up after my post [here](https://wp.me/pbMoDN-hD).
**To test:**
Tenor GIF picker can be found in Media Library, Aztec Editor & Block Editor. However, they use the same Tenor Picker instance, so you can verify in any where which is convenient, of course it's best to verify all of those places.
Steps to verify animated GIF support in Tenor Picker trigged from Media Library
1. Go to Site -> Media Library, tap the + button at the top right corner
2. Select Free GIF Library
3. Search for any GIF, verify they are being animated in the picker ;-)
> Animating GIFs in Tenor Picker

- WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
Fixes #13966
2. Tap Publish
3. Schedule the post
4. Check if the top-right button is not truncated and displays the whole word
> Fix editor button from being truncated

- WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
- WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
- WordPress/Classes/ViewRelated/NUX/SignupEpilogue.storyboard
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Ref #13939 
This updates the Signup Epilogue's User Info section to the new design. Specifically:
- 'New Account' section header removed.
- Blue 'add' gridicon is now used for the add gravatar button.
- Top and bottom separator lines removed.
- Background color updated (light and dark modes).
Please note the table itself hasn't been updated, so the table colors are still off (i.e. the area around the User Info section). This change only applies to the User Info section itself. I'll request Design review once the table is updated and it looks more final.
---
To test:
- Signup.
- If you don't want to actually sign up, see below for WPAuth hack tip.
- On the Signup Epilogue, verify the User Info section looks like that on #13939 or the designs in Zeplin. …
> Signup Epilogue: update User Info section

- WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Ref #13939 
This removes the table section just for the Password field, and adds the Password field to the same section as the other account fields.
To note, this is still a WIP, so table colors are still off. This change is just to move the Password field. 
---
To test:
- Sign up with Email. (If you don't want to actually sign up, see below for WPAuth hack tip.)
- On the epilogue, verify:
- The password field is displayed below the Username field, in the same section.
- The `You can always...` text is displayed below the Password field (in the section footer).
| ![wp_before](https://user-images.githubusercontent.com/1816888/79923645-33f1d600-83f3-11ea-8575-82bda28aa1d8.png) | ![wp_after](https://user-images.githubusercontent.com/1816888/79923663-394f2 …
> Signup Epilogue: remove Password table section

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
This PR changes the bottom-left button's label in Media Picker. Instead of showing "Preview X" (where X is the number of images) we now say "Edit X".
This was discussed with @mbshakti and @malinajirka.
My intention was to point this PR to the release branch. But since this adds a new string (and the translation for the release branch has already started) I'm targeting `develop`. 
1. Add a "Gallery Block"
2. Tap "Add Media"
3. Tap "Choose from Device"
4. Select one or more images and check that the label of the left button says "Edit X" (where X is the number of images you selected)
1. Add a "+" at the action bar
2. Tap the image icon (right next to the WP logo)
3. Select one or more images and check that the label of the left button says "Edit X" (where X is the number of images you …
> Change Media Picker label from "Preview %@" to "Edit %@"

- WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Fixes #13929 
To test (Classic and block editors - *Please test on device*):
1. Go to My Site -> Posts then select a Post to edit.
2. Add an Image / gallery block or classic
3. While the image being uploaded, Tap the ... menu at the top-right corner, select Preview
4. See the alert if image still uploading 
5. When Image done uploading, tap preview again
6. See preview with the image 
> Show an alert when trying to preview while uploading media 

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/FormattableContent/Styles/HeaderDetailsContentStyles.swift
- WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #13856 
Rendering notification details label (includes stripping new-line) instead of plain text. 
To test:
1. Go to notifications 
2. Tap on notification where someone replied or liked your comment 
3. see the comment details line 
(more information and screenshots in the issue)
> Fix issue with notification header details comment preview not showing

- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
- WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
Fixes #13983 and #13985
1. Go to My Site > Blog Posts > +.
1. Add a title and some content.
1. Tap More > Save as Draft. 
1. Tap More > Publish. 
1. Change the date to something in the future.
1. Tap the "Schedule Now" button.
1. The post should be scheduled
For this one, I fixed two issues: we do not display a date in the past. If it's in the past, we show "Immediately". Also, if you schedule a draft and then remove the scheduling, the draft will behave as a draft (instead of "Publish" as it was before, you'll see "Update").
1. Go to the My site tab > Blog posts > Drafts.
2. Select a draft to open it in the editor.
3. Optional: make some changes to the post content.
4. Open the ellipsis menu and tap "Publish"
5. Notice that the publish date is set to "Immediately". Tap Publish > select …
> Fix scheduling issues

- WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
Ref: #13939, #13413
On the Signup and Login Epilogues, the gravatar's top margin is now 32pts.
To test:
- Login or Signup (they share the User Info view, so either will suffice).
- Verify the gravatar is now 32pts from the top of the view.
| ![login_before](https://user-images.githubusercontent.com/1816888/80157707-fa040980-8583-11ea-8a83-b36bafbf5c4e.png) | ![login_after](https://user-images.githubusercontent.com/1816888/80157712-fd979080-8583-11ea-8719-c8e774ea7b13.png) |
| ![signup_before](https://user-images.githubusercontent.com/1816888/80157479-819d4880-8583-11ea-8bb2-1247042fd544.png) | ![signup_after](https://user-images.githubusercontent.com/1816888/80157483-85c96600-8583-11ea-9e93-34c3ab0e778d.png) |
> Signup & Login Epilogues: adjust gravatar top margin

- Podfile
- Podfile.lock
Forgot to change the referenced WordPressUI version from the branch to the released version.
You can verify this works if the pods install and the Filter Sheet Popover on iPad does not collapse.
> Update WordPressUI to 1.5.4-beta.3

- WordPress/Classes/Extensions/UIView+Borders.swift
- WordPress/Classes/ViewRelated/NUX/EpilogueSectionHeaderFooter.swift
- WordPress/Classes/ViewRelated/NUX/EpilogueSectionHeaderFooter.xib
- WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
- WordPress/Classes/ViewRelated/NUX/SignupEpilogue.storyboard
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.xib
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Ref #13939 
This updates the Signup Epilogue content margins to be 20pts leading and trailing. The margins have been added to the cells and removed from the table.
This allowed these issues to be resolved: (as discussed on https://github.com/wordpress-mobile/WordPress-iOS/pull/13973)
- The `Password (optional)` label now lines up with the other fields on the left.
- The `Username` disclosure icon now lines up with the other fields on the right.
**Note:** this change breaks the _Login_ epilogue alignment. I'll fix that in a follow up PR.
---
To test:
- Signup. (See below if you don't want to actually signup)
- On the epilogue, verify:
- All the content has 20 pt leading and trailing margins.
- The separator lines have 20 pt leading and 0 pt trailing margins. …
> Signup Epilogue: update content margins

- WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueConnectSiteCell.xib
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
Ref #13413 
This updates the Login Epilogue content margins to be 20pts leading and trailing. The margins have been added to the cells and removed from the table.
---
To test:
- Login.
- On the epilogue, verify:
- All the content has 20 pt leading and trailing margins.
- The separator lines have 20 pt leading and 0 pt trailing margins.
- On iPhone, the Done button as 20 pt leading and trailing margins.
- On iPad, the Done button has 0 leading and trailing margins (i.e. is the same width as the table).
| iPhone | iPad |
| ![iphone](https://user-images.githubusercontent.com/1816888/80542609-8c345500-896a-11ea-9eb3-0172bca31da5.png) | ![ipad](https://user-images.githubusercontent.com/1816888/80542622-922a3600-896a-11ea-8905-b6e9c4896b2b.png) |
---
> Login Epilogue: update content margins

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2186
WordPress-Android: https://github.com/wordpress-mobile/WordPress-Android/pull/11756
To test:
**Bug fix**
**New feature & Improvement**
**Note:** including this to ensure we don't see the block in production yet:
> Gutenberg: update to v1.27.0

- WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Ref #13939 
This adds VoiceOver support to various Signup Epilogue components.
---
To test:
- Signup and enable VoiceOver. 
- User Info:
- Select the User Info block. VO should say `Account Information. <full name> <username>`.
- Select the gravatar icon. VO should say `Add account image. Button. Add image, or avatar, to represent this new account.`
- Fullname and username should not be accessible.
- Account Details:
- Select the `Account Details` header. VO should say `Account details. Heading.`.
- Select the Display Name row. VO should say `Display Name. <display name>.`.
- Select the Display Name field. VO should say `<display name>. Text field. Double tap to edit`.
- Select the Username row. VO should say `Username <username>. Button.`.
- Select the Password row. VO should say …
> Signup Epilogue: accessibility

- WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
Ref #13413 
This fixes two issues that @mattmiklic  discovered while testing the [Signup PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/14018):
- The Done button leading/trailing margins now match the table content margins.
- 50/50 split view on larger iPads should display properly now.
To test:
---
- Login.
- Verify the Done button margins are the same as the table content margins.
| ![ipad_portrait](https://user-images.githubusercontent.com/1816888/80657220-3fbb4900-8a40-11ea-99ec-494539775a6c.jpeg) | ![ipad_landscape](https://user-images.githubusercontent.com/1816888/80657228-45b12a00-8a40-11ea-8fa9-ab280e7236c6.jpeg) |
---
- Multitask on an iPad and change the view size. 
- Especially 50/50 split view in landscape on a 12.9" iPad. 
- Verify the table …
> Login Epilogue: fix iPad layout issues

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
Fixes an issue where WPSplitViewController delays in updating its sizing.
I noticed these two issues with the split view controller:
- Frame settings of other views is delayed until the rotation animation is complete. (i.e. the frame of views in the primary view controller were wrong during transition because of the animation delay)
- Visual jitter occurs during rotation because the initial view sizing is based on the original property values before the animation
Notice the primary view controller's frame jump in the before gif:
|--|--|
| ![Before 2020-04-29 16_44_44](https://user-images.githubusercontent.com/3250/80654111-d1bf5380-8a38-11ea-9999-54938a3a94b6.gif) | ![AfterChange 2020-04-29 16_42_56](https://user-images.githubusercontent.com/3250/80654122-d71c9e00-8a38-1 …
> Fix bug w/ WPSplitView Rotation Logic

- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
- WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
- WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Fixes #14020, #14021, #13986 (phew!)
1. Create a post
2. Tap Publish
3. Check that the order in the Nudges view is: Visibility, Publish Date and Tags
1. Create a post
2. Tap Publish
3. Check that the option that schedules a post now reads "Publish Date"
1. Create a post
2. Tap Publish
3. Tap "Publish Date"
4. Dismiss the calendar
5. Scroll the Nudges view and check that there's no additional empty scroll area
> Change options order and fix label and scroll issue

- WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Fixes #14036
2. Go to post settings
3. Change each setting and check the console output for the events triggered
After talking with @malinajirka we decided to change how the property `via: media_editor` should be fired for `photo_added`. Now, this only happens if the user edits an already uploaded image, otherwise, the original source will be kept.
> Track Settings Options usage + fix Media Editor tracking

- WordPress/Classes/Services/PostService+MarkAsFailedAndDraftIfNeeded.swift
Fixes #12776
To test: Fixes a bug where the post author was not displayed for drafted posts made while offline, since the author info was obtained via networking. When the post is drafted while offline, the display name for the account associated with the blog is assigned as the author, so the user sees their name assigned to the post (rather than blank, as previously).
> Fixed post author not showing on drafted offline posts

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/NUX/SignupEpilogue.storyboard
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
Ref #https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/257
WPAuth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/268
---
To test:
- Sign up. (see below to avoid actually signing up)
- On the epilogue, select `Username`.
- Verify the `Change Username` view is displayed.
| ![epilogue](https://user-images.githubusercontent.com/1816888/81007061-c6d83a80-8e0d-11ea-86cc-ddf411614eca.png) | ![username](https://user-images.githubusercontent.com/1816888/81007072-cb9cee80-8e0d-11ea-929f-f3853027b0b8.png) |
---
To show the Signup Epilogue without actually signing up:
- Check out the accompanying `WordPressAuthenticator` branch locally.
- In WPiOS `Podfile`, point `WordPressAuthenticator` to your local Auth.
- In `LoginViewController`, …
> Signup Epilogue: Remove showUsernames segue name

- WordPress/Classes/Utility/Analytics/WPAppAnalytics+Media.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
- WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
- WordPress/Classes/ViewRelated/Media/Tenor/NoResultsTenorConfiguration.swift
- WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorClient.swift
This PR addresses comments from @frosty for #13949. 
What included?
1. Removed refs to P2 from the codebase
2. Added `contentFilter` param to Tenor API Client to allow us control the GIF safety filer level on Tenor
3. Converted some literal strings into Constants
4. Making sure a new Tenor picker instance being created each time and correctly release it when closing in Media Library and Aztec Editor
*Test*
1. Open a Post with Aztec Editor
2. Select Add media menu and choose Free GIF Library
3. Search with any term, close the picker
4. Select Add media menu again, and choose Free GIF Library
5. You will notice the Picker present a new instance without no previous search left
> Improvements for Tenor picker to address comments in #13949

- Podfile
- Podfile.lock
Ref #13939 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/269
This uses the Auth branch that updates the secure text image color on the Signup Epilogue password field.
---
To test:
- Sign up. (see below to work around signing up)
- On the epilogue, verify the password field icon matches the color in Zeplin or the images in #13939.
| <img width="432" alt="light" src="https://user-images.githubusercontent.com/1816888/81022685-766fd580-8e2b-11ea-8e94-2e92b8778b4d.png"> | <img width="432" alt="dark" src="https://user-images.githubusercontent.com/1816888/81022687-796ac600-8e2b-11ea-8915-f60142201774.png"> |
---
To show the Signup Epilogue without actually signing up:
- Check out the accompanying `WordPressAuthenticator` branch locally.
- In …
> Signup Epilogue: update secure text image color

- WordPress/Classes/Models/Blog.m
Fixes #14052 
This PR is removing a custom setter implemented back in https://github.com/wordpress-mobile/WordPress-iOS/pull/3806 as it is no longer needed -- we're not building blavatars for sites anymore. As written the code returns the site URL's host rather than an icon. This leads to errors attempting to load the non-nil icon. 
All props to @oguzkocer for the investigation into the cause of the errors.
To test:
Confirm the app builds.
Confirm unit tests pass.
Load the site list. Confirm there are no sentry errors logged and that any site with a site icon continues to display its site icon. 
> Blog: Deletes the old, obsolete, custom icon setter.

- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainSuggestions/RegisterDomainSuggestionsViewController.swift
- WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
Fixes #n/a
Ref https://github.com/orgs/wordpress-mobile/projects/60
This removes the usage of NUX view controllers in the Domain Registration views. It only affected the `RegisterDomainSuggestionsViewController`. The nav buttons are now added in that VC, instead of by `NUXViewController`.
---
To test:
- See below to manually enable domain registration.
- On site details, select `Register Domain`.
- Verify:
- `Cancel` dismisses the view.
- `Help` opens the `Support` view.
| ![reg](https://user-images.githubusercontent.com/1816888/81121419-f2c9ed80-8eeb-11ea-9b0a-5e144e3c284e.png) | ![support](https://user-images.githubusercontent.com/1816888/81121390-dcbc2d00-8eeb-11ea-8b62-bf96214ecf7f.png) |
---
To enable the Domain Registration option:
- In …
> Domain Registration: Remove usage of NUX view controllers

- WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupUsernameViewController.swift
Ref #13413, #13939
This is just some code cleanup in the Signup and Login epilogues. Primarily:
- Remove usage of NUX view controllers.
- Cleanup private methods and properties.
- Remove some unnecessary code.
There should be no functional or visual changes.
---
To test:
- Login.
- Verify the view appears as it should.
- Verify the `Done` button dismisses the view.
- Verify the `Connect another site` displays the site address view.
- Signup.
- Verify the view appears as it should.
- Verify the view does not rotate in iPhone landscape.
- Select `Username`. Verify the `Help` nav bar button opens the `Support` view.
- Go back to the epilogue. Verify the blue nav bar does not appear.
---
To show the Signup Epilogue without actually signing up:
- In WPiOS `Podfile`, point …
> Epilogues: code cleanup

- WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
Ref https://github.com/wordpress-mobile/WordPress-iOS/issues/13413
In https://github.com/wordpress-mobile/WordPress-iOS/pull/14061 I moved `setNavigationBarHidden` to `viewDidLoad`. Turns out, that doesn't work for Google and Apple logins. This moves `setNavigationBarHidden` back to `viewWillAppear` so the nav bar is hidden when logging in with Google/Apple.
To test:
- Log in with Google and/or Apple.
- On the epilogue, verify the big blue nav bar is hidden.
| ![broken](https://user-images.githubusercontent.com/1816888/81319455-eb6e2580-904c-11ea-8d00-5e57bbbe9e7f.png) | ![fixed](https://user-images.githubusercontent.com/1816888/81319565-18223d00-904d-11ea-9226-6b28e2eabba9.png) |
> Login Epilogue: hide nav bar for social logins

- WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
Fixes #14067 
This fixes password validation on the Signup Epilogue. Specifically, if the password is blank, it will no longer attempt to update it.
---
To test:
- Sign up. (see below for a workaround)
- On the epilogue, enter a password.
- Delete the password.
- Tap Done.
- Verify:
- You do not get the error noted on #14067 .
- You do not see the `Changing password` HUD.
---
To show the Signup Epilogue without actually signing up:
- In WPiOS `Podfile`, point `WordPressAuthenticator` to your local Auth.
- In `LoginViewController`, change `showLoginEpilogue` to show the signup epilogue:
```
func showLoginEpilogue(for credentials: AuthenticatorCredentials) {
guard let navigationController = navigationController else {
fatalError()
}
showSignupEpilogue(for: credentials)
// …
```
> Signup Epilogue: don't update empty password

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
`Gutenberg Mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2223
`WordPress-Android`: https://github.com/wordpress-mobile/WordPress-Android/pull/11827
To test:
**Bug fix**
> Gutenberg: update to v1.27.1

- WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
This PR fixes an issue where the Reader comment reply button wasn't being tinted. I'm not sure why the original regression happened, but this fix ensures that the button image is tintable.
This image shows the issue:
And this is with the fix applied:
**To test:**
* From either a Reader post or a comment notification, access the comments of a post
* Ensure that the Reply button image is tinted the same as its title and the Like button
> Reader Comments: Fix Reply button color by ensuring image is tinted

- WordPress/Classes/Utility/Media/MediaFileManager.swift
This PR aims to fix the `*** Terminating app due to uncaught exception 'Unresolved Core Data save error (Derived Context)', reason: 'Merge policy failed - unable to complete merging on null.null' crashes.
Please, keep in mind that this PR doesn't solve all of our Core Data errors, only this specific one.
This code reverted here was originally submitted to fix #12142. The removal of this part will probably cause a regression on the fix of this bug, but the impact it's nothing compared to the number of crashes we've seen.
1. Create a draft post and add one or more images
2. Close the post and save as draft
3. Re-open the post
4. Background the app
5. Kill/relaunch: the app would re-open to that same post
6. Close the post: no crash should occur
1. Upload gallery on an existing draft
1. quit …
> Remove media deletion to prevent Core Data null.null errors

- WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
- WordPress/Classes/ViewRelated/System/Notices/NoticeStyle.swift
- WordPress/Classes/ViewRelated/System/Notices/NoticeView.swift
* Persists tooltip state & display count via User Defaults
* Sets a maximum of 5 of times that tooltip will appear
- Open the Blog Details screen
- Click on the Create button and ensure that the tooltip is no longer shown
Reset using these command in LLDB:
```
e -l swift -- import WordPress; UserDefaults.standard.createButtonTooltipWasDisplayed = false
e -l swift -- import WordPress; UserDefaults.standard.createButtonTooltipDisplayCount = 0
```
- Check that the tooltip is shown again
- Try switching to other screens (non-Blog Detail) and ensure that the tooltip is hidden after 5 times navigating away and back.
> Hide Create FAB Tooltip after usage or # times

- WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergStockPhotos.swift
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/953#issuecomment-627709554
In this PR I removed the hardcoded value of `allowMultipleSelection` in StockPhotosPicker and used flag passed from JS side instead.
To test:
- Run app
- Open Gutenberg editor
- Add the cover block and choose "Free photo library"
- You should be able to select only one media
> [FIX] Gutenberg - use allowMultipleSelection flag from JS in the GutenbergStockPhotosPicker

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
The "Blog Details Table" accessibility identifier was no longer on a table view so the query for a table with that identifier failed. This happened after a refactoring to make the table view a subview instead of the root view of this view controller.
* Run UI tests
* Verify that tests succeed
> Fix the UI test failure on the Blog Details screen

- WordPress/Classes/Extensions/UIImageView+SiteIcon.swift
Fixes #14051
To test:
- Set a breakpoint on UIImageView+SiteIcon lines 93 and 101.
- Search for a site using the Reader search page .
- When rapidly switching between searches (quick enough so that some site icons do not finish loading), you should NOT see the error handler (line 101) called when the `AFIError.requestCancelled` error occurs.
Throttling the network connection with Charles or Link Conditioner should help make it easier to switch between searches.
> Don't log sentry error for cancelled Site Icon downloads

- WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
- WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
Fixes #14113 
To test:
1.
1.1 Create a post
1.2. hit publish 
1.3. schedule the post (to past date or future date - test both)
1.4. go to post settings
1.5. see that the date and all labels are correct  
2.
2.1 Create a post
2.2. go to post settings  
2.3. schedule the post (to past date or future date - test both)
2.4. back to editor
2.5 hit schedule 
2.5. see that the date and all labels are correct 
** Please test Switching between scheduling and publish Immediately to see all labels and dates are updated correctly on both post settings and bottom sheet**
> Fix to update labels correctly when scheduling or publishing immediately 

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Fixes #14115
To test:
2. See that the publish button is disabled
3. Enter post content
4. Notice the publish button is enabled 
> Fix publish button is active immediately after creating new (empty) post

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FancyAlerts.swift
This PR simply updates the blog post URL used in the IA announcement model to what we expect the published post URL to be.
**To test**
As the post isn't live yet, you can't really test this one functionally. Just check the URL looks okay!
> [IA] Updates blog post URL used in IA announcement alert

- WordPress/Classes/Models/NewsItem.swift
- WordPress/Classes/ViewRelated/Reader/NewsCard.swift
- WordPress/News.strings
- WordPress/WordPressTest/DefaultNewsManagerTests.swift
- WordPress/WordPressTest/LocalNewsServiceTests.swift
- WordPress/WordPressTest/NewsCardTests.swift
- WordPress/WordPressTest/NewsItemTests.swift
- WordPress/WordPressTest/Test Data/News.strings
Closes #13789
- Change the version number to 14.9
- Visit the Reader tab with the Following filter tab selected
- Notice the header (news card) showing the simplified navigation
- The Learn More button should push the post preview (note that this URL doesn't work yet so you should get an error for that page).
> Adds Simplified Navigation News Card

- .github/workflows/danger.yml
Builds have been starting to fail with a 404, but nothing has changed on our end. Something might have changed on the GitHub end.
While we sort this out, it's better to disable the integration so we don't disturb the devs' workflow.
See:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/14124
- https://github.com/wordpress-mobile/WordPress-iOS/pull/14110
**To test**: If the GitHub action passes and no Danger step runs, then this works
---
> Disable broken Danger to avoid noise for the dev team

- RELEASE-NOTES.txt
- WordPress/Classes/Networking/MediaRequestAuthenticator.swift
- WordPress/Classes/Utility/Media/ImageLoader.swift
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Fixes #14098 
To test:
- Add some content
- Access the Post Settings
- Set a Featured image ( use an image from the local device)
- Wait for the upload to finish
- Check if the featured image shows correctly
- Exit Post Settings
- Enter Post SEttings again
- Check if the featured image shows
- Tap on the feature image.
- Tap Remove
- Check if the Post Settings reload and the image is not show any longer.
> Hotfix for featured image bugs

- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
On pages the featured image while has the same tag is
not on the same position so reloading the section make
the code to crash.
Fixes #14098 
To test:
- Create a **page** 
- Open page settings and add a featured image to it.
- Tap on the featured image
- Tap on remove
- Check that it doesn't crash.
- Repeat the steps above but now using a **post** and see if all is ok there too.
> Reload all data instead of section only.

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2106
When uploading media from the block editor without **internet connection**, the placeholder will hang instead of showing the retry message. This affects any block that handles media upload, `Image`, `Video`, `Media & Text`, and `Cover`.
This PR adds an internet connection check in the `thumbnailReady` state to avoid showing the progress bar when it is not uploading anything and display the retry message instead.
For a bit more insight, when uploading media from the media library outside the editor it won't let the user upload anything without an internet connection. In this case, we do want to start the upload process but let the user know if it failed by having no connection.
- Open the app.
- Open the editor.
- Add …
> Gutenberg - Media Inserter - Check for internet connection

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
Fixes #14150 
This fixes an issue where state restoration would fail on Blog Details View Controller (and view controllers below it in the navigation stack) because the restoration properties were not set.
There are two additional preventative changes.
- Calls the proper initializer in `BlogDetailsViewController` so that `restorationClass` and restorationIdentifier` are set.
- Defaults to hiding the create button instead of leaving it shown.
- Also adds a check for the CreateButton feature flag to prevent a possible crash if that feature flag is disabled.
- Navigate to the Blog Details or Stats Screens inside the My Sites Screen
- Send the app to the background
- Kill the app in Xcode to trigger state restoration
- Notice that the Stats Screen is restored (this _does not_ happen in …
> Fix State Restoration issue + feature flag check

- Podfile
- Podfile.lock
Updates WordPressUI version to version with pan+scroll
Original PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14121
To test:
* Navigate to the Reader screen and tap the Filter button
* Filter modal begins compact but expands upon scrolling the content up
* Filter modal switches to compact on scrolling down
* Filter modal dismisses on scrolling further down
* Filter modal will expand or dismiss on "flinging" while scrolling up or down
> 14.9 - Adds Pan on Scroll to Bottom Sheet

- WordPress/WordPressUITests/Screens/MySiteScreen.swift
- WordPress/WordPressUITests/Screens/ReaderScreen.swift
- WordPress/WordPressUITests/Tests/MainNavigationTests.swift
- WordPress/WordPressUITests/WordPressUITests.xctestplan
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/13825
This test case was [disabled](https://github.com/wordpress-mobile/WordPress-iOS/pull/13824) because it was failing inconsistently. This PR enables it again and also addresses suggestions to improve it from the issue:
> We should ensure the test checks that the correct Reader screen is opened (not just any Reader screen).
Now it will check the Reader screen has loaded.
> We should update the test to only navigate through the tabs in the bottom nav bar. (The test still opens the block editor, but that's no longer part of the bottom nav bar. The editor is exercised as part of the editor tests, so it shouldn't be required here.)
It removes opening the block editor and just navigates throughout the navigation bar.
To test: …
> Testing: Fix and enable MainNavigationTests - TestTabBarNavigation

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Fixes #9685 
The new version of WPMediaPicker library will fix the bug seen on the ticket above.
To test:
- Go to the Me Screen
- Tap on the user icon
- Take a new photo
- Press Use
- Check that on the crop screen the Use button is visible on the top right
- Do the same as above for the Site Icon selection
> Update MediaPicker to version 1.7.0-beta.2

- Podfile
- Podfile.lock
Fixes #14146 
Ref. https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/280
Ref. https://github.com/wordpress-mobile/WordPressKit-iOS/pull/245
Prerequisite: need an Apple device, an existing SIWA account, and 2fa enabled for the WP.com account. 
1. Check out this branch
2. `rake dependencies`
3. Build and run
4. If logged in, clear your Activity Logs (Me > Help & Support > Activity Logs > "Clear Old Activity Logs")
5. Log in > Continue with Apple > 2fa code
6. After logging in, navigate to Me > Help & Support > Activity Logs > Current.
7. Copy and paste or share the report to a trusted source. Search the text for `bearer_token` and `token_links`. 
**Expected:** the values for those fields say `*** REDACTED ***`
If this isn't showing up properly in the Activity Logs, try …
> Redact tokens

- Podfile
- Podfile.lock
Updates Gutenberg version to 1.28.1
To test:
- Start the app.
- Smoke test the Gutenberg editor.
> Update gutenberg version to 1.28.1

- WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
- WordPress/WordPressNotificationServiceExtension/Sources/Tracks/Tracks+ServiceExtension.swift
In this PR we're fixing a crash in the NotificationServiceExtension, caused by JSON Encoding of an entity that's not encodeable.
Ref. #13412
cc @leandroalonso sir, may I bug you with this one? Thanks in advance!!
Please DM me for instructions on how to send a Push Authentication Notification!
> Fix: UNNotificationContent Crash

- docs/README.md
- docs/issue-triage.md
This PR adds documentation for what issue triage is, why we do it, and how it's done (labels and prioritization).
@designsimply Anything you'd add/change/remove here? Do you think it's clear?
> Docs: Add Issue Triage doc

- WordPress/Classes/ViewRelated/Post/PostVisibilitySelectorViewController.swift
Fixes #13996
This PR makes sure that published posts' original date isn't changed when changing its status to private.
cc @jd-alexander 
Change a published post to private and make sure that the original date is not changed.
> Do not change the date of published posts when changing it to private

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Ref #https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/282
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/287
This uses the Auth branch to utilize the Google signup refactor.  To note, there should be _no_ functional or visible changes. Testing is to verify nothing is broken.
To test:
---
**Error Handling:**
Different settings on an existing WP account result in different errors. I _think_ these scenarios cover them. But the gist here is that if Signup fails when selecting an existing account, a popup is displayed with an API error message. i.e. the _handling_ of these errors is no different, just the messages may differ.
Pro tip: To check if your WP account is connected to Google, go to wordpress.com > Account > Security > Social Login. …
> Update Auth to use Google signup refactor.

- WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.xib
- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
- WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Fixes #14206
Updates the cross post cell design to match the new reader UI updates (https://github.com/wordpress-mobile/WordPress-iOS/pull/14185)
|---|---|
| <img width="376" alt="Screen Shot 2020-05-27 at 5 22 20 PM" src="https://user-images.githubusercontent.com/793774/83084814-efcfa200-a03e-11ea-9607-4053498c7f9d.png"> | <img width="375" alt="Screen Shot 2020-05-27 at 5 25 45 PM" src="https://user-images.githubusercontent.com/793774/83084884-20afd700-a03f-11ea-98cb-b76fe978d66f.png"> |
|---|---|
|<img width="371" alt="Screen Shot 2020-05-27 at 5 22 47 PM" src="https://user-images.githubusercontent.com/793774/83084830-f5c58300-a03e-11ea-89a1-9eabf18c1ed7.png"> | <img width="374" alt="Screen Shot 2020-05-27 at 5 25 40 PM" …
> Update the cross post table cell design to match the new reader card

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FancyAlerts.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Ref #14202
To test:
- Build and run as fresh install
- Navigate to 'Notifications'
- Verify that the notifications permissions alert shows up
- verify that the buttons are actionable
- verify (on a real device) that tapping on 'allow notifications' presents the system screen to allow notifications
**Notes**
- The in-line prompt logic is yet to be updated. At this time, if users tap on 'not now', the in-line prompt will show up after navigating away and returning to the 'Notifications' tab
- To show the permission alert without deleting the app, pause the execution using the debugger and run the following command
```
e -l swift -- import WordPress; UserDefaults.standard.notificationPrimerAlertWasDisplayed = false
```
This will only work if the notifications permissions have not been set …
> Move push notifications permission alert to Notifications tab

- .github/workflows/danger.yml
- package.json
- yarn.lock
Hat tip to @loremattei for thinking of this option. Now instead of having new steps in the GitHub Actions workflow for each check we want to run with Danger, we simply execute a [dedicated remote Dangerfile](https://github.com/Automattic/danger-settings/blob/a2c8edff32be081595509d34bf25bc18a6c1bd1e/wordpress/ios.ts).
The checks run by this file are currently:
- [labels](https://github.com/Automattic/danger-settings/blob/a2c8edff32be081595509d34bf25bc18a6c1bd1e/org/label.ts)
- [iOS specific safety checks](https://github.com/Automattic/danger-settings/blob/a2c8edff32be081595509d34bf25bc18a6c1bd1e/org/pr/ios.ts)
I had to make a new repo, `danger-settings` because in order to get this setup to work I had to make a few changes to the code originally in …
> Re-enable Danger with new centralized setup

- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/WordPress-Alpha.entitlements
- WordPress/WordPress-Internal.entitlements
- WordPress/WordPress.entitlements
This PR adds preliminary support for Iterable deep links. The server side of things isn't set up yet, so we can't actually verify that the deep links work. But we can verify that existing links still work okay.
I've deviated a little from the [Iterable example code](https://support.iterable.com/hc/en-us/articles/115003909366-Handling-iOS-Deep-Links-Without-the-SDK-), as I can't see how thier way of detecting an Iterable deep link would work – they use a regex, which to me looks like it'll basically just match any URL? (`/a/[a-zA-Z0-9]+`) so instead, I'm checking for our Iterable domain.
**To test:**
* Build and run in the simulator
* Background the app
* In the Terminal, run: `xcrun simctl openurl booted https://wordpress.com/notifications` and verify that the app launches to the …
> Add support for Iterable deep links

- WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift
- WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
Fixes (same issue on android) https://github.com/wordpress-mobile/WordPress-Android/issues/12084
To test:
1. Create a site 
2. Choose segment
3. See that the keyboard is up immediately when domain search screen is visible 
4. Go back and forth, enter different values, remove tex.. check that everything works as expected
As part of this PR, I remove workaround code done to fix an issue with the textfield not resigning first responder. Since then we have shortened site creation steps so the only screen that has text input is domain search. 
> Site creation domain search textField becomes first responder

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
- WordPress/Classes/ViewRelated/System/FancyAlertViewController+NotificationPrimer.swift
Ref #14202 14202
To test:
- perform a fresh install and login or signup
- go to 'Notifications' tab
- When the alert shows, tab 'Not Now'
- Go to another tab and back to 'Notifications' four more times
- Verify that the in-line prompt shows up
> Push Notifications Permissions - In-line Prompt After 5 Visits

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/182
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/297
This change:
1. Updates the unified `viewControllerBackgroundColor` to work in light and dark modes (i.e white and black).
2. Uses the Auth changes to set background color via `WordPressAuthenticatorUnifiedStyle`.
To test:
- Enable the `unifiedSiteAddress` feature flag.
- Run the app.
- Log out if necessary.
- Verify the background is white.
- Enable dark mode.
- Verify the background is black.
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-03 at 18 23 22](https://user-images.githubusercontent.com/1816888/83703140-de047680-a5cb-11ea-92a2-ecb42f3fe67d.png) | ![Simulator Screen Shot - iPhone 11 …
> ULS: set unified views background color

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/282
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/298
This uses the Auth changes to show the Google login to signup redirect.
To test:
- Enable the `unifiedGoogle` feature flag.
- Run the app.
- Log out if necessary.
- Select either Login or Signup > Continue with Google.
- Select a Google account that has not been used on a WP account.
- Verify the signup confirmation view is displayed.
- As noted on the Auth PR, `Next` doesn't do anything yet.
> ULS: show Google login to signup redirect.

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Previously moved the method `showNotificationsPrimerAlert` from `BlogDetailsViewController+FancyAlerts` to `NotificationsViewController` in order to move the alert to the 'Notifications' tab, then noticed that there was another `showNotificationsPrimerAlert` in `BlogDetailsViewController` that is not called from anywhere.
Ref #14202
To test:
- verify that the app builds and runs
- optionally, fresh install, login, go to 'Notifications' and verify that the notification primer alert shows up.
> Remove unused showNotificationsPrimerAlert from BlogDetailsViewController

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
- WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Fixes #13995 
Related PR: https://github.com/wordpress-mobile/WordPressUI-iOS/pull/69
To test:
1. start a new post.
2. Add a title and/or post content.
3. Tap publish
4. Tap on "Visibility."
5. Select "Private."
6. Dismiss the bottom sheet.
7. Tap "X" to close the editor.
8. Notice the "You have unsaved changes" prompt appears with an option to save draft
> Revert post status setting when Prepublishing bottom sheet dismissed

- WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift
- WordPress/Classes/ViewRelated/Me/App Settings/PrivacySettingsViewController.swift
Fixes #10344 
To test:
- Launch the app and verify that the privacy section looks like expected.
- Turn the crash reporting setting on and off and verify that crash reporting reacts accordingly.
| ![Simulator Screen Shot - iPhone X - 2020-06-04 at 13 27 43](https://user-images.githubusercontent.com/5558824/83802416-19ad4800-a681-11ea-9cc2-f880cbfb0bf7.png)  | ![Simulator Screen Shot - iPhone X - 2020-06-04 at 15 47 40](https://user-images.githubusercontent.com/5558824/83802425-1ca83880-a681-11ea-8d49-40911e97122b.png)  |
> Privacy settings: add a crash reporting option

- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
- WordPress/Classes/Utility/AppAppearance.swift
- WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Implements #13122. This PR adds an in-app setting to change the current app theme independently of the current system dark mode setting.
**To test:**
* Navigate to Me (top right of My Site) > App Settings, and scroll to Appearance near the bottom
* Ensure that the default displayed value is 'system default'.
* Try changing the value to light and then dark and ensure that the UI appearance updates
* Quit the app and restart, and ensure that your preference is remembered – if you chose dark, the app should still be dark. Also check that the Settings menu still reflects your choice.
* As this feature involves overriding the style of the app's main window, do a smoke test of other areas of the app and ensure everything looks right. Most notably, Notices use their own window, …
> Adds in-app appearance setting

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/282
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/300
This uses the Auth changes to create a Google account. Also, the `unifiedGoogle` Feature Flag is now enabled for dev.
To test:
Prerequisites:
- Sorry - you're going to need 3 unused Google accounts for this, one for each test case.
- You'll need another instance of WP (not using these changes) for the existing account tests.
---
New Google account:
- Select either Log in or Sign up > Continue with Google.
- Walk through the Google auth process, selecting an unused Google account.
- Press `Next` on the signup confirmation view.
- While the account is being created, the `Processing Account` HUD is displayed.
- When the account is …
> ULS: Use Google signup flow

- WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Fixes #14250
1. Create a new post.
2. Enter a title and/or content.
3. Tap `Publish`.
4. Change the publish date to a past or future date.
5. Change the visibility to `Private`.
Result: The publish date is set to `Immediately` and the button says "Publish Now".
> Fix publish label in Prepublishing Nudges

- WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
Fixes #12129 
This PR changes the "tap" instruction text in the Quick Start tour notification to be more inclusive to our accessibility users and says "select" instead. Just like [we shouldn't say "click here"](https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/) for links, we should not say "tap". 
Once the user chooses the "Themes" item, it speaks the correct accessibility trait ("Themes. Button.")
<a href="https://user-images.githubusercontent.com/1062444/84049993-c124c600-a972-11ea-9e60-c4c275764626.PNG"><img src="https://user-images.githubusercontent.com/1062444/84049993-c124c600-a972-11ea-9e60-c4c275764626.PNG" width="350" /></a>
<a href="https://user-images.githubusercontent.com/1062444/84050018-cc77f180-a972-11ea-9d1a-a6950eedcc21.PNG"><img …
> Improve VoiceOver accessibility in Quick Start v2

- WordPress/Classes/ViewRelated/Reader/ReaderCardDiscoverAttributionView.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.xib
- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
- WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Fixes #14253
Applies the following feedback:
|---|---|
|![01 - discover - light - before](https://user-images.githubusercontent.com/793774/83925393-e4196500-a73b-11ea-8f62-7c8934afdd0e.png)|![01 - discover - light - after](https://user-images.githubusercontent.com/793774/83925381-e085de00-a73b-11ea-8876-8367335841cd.png)|
|---|---|
|![02 - discover - dark - before](https://user-images.githubusercontent.com/793774/83925428-fc897f80-a73b-11ea-8bd1-6c2a557447e1.png)|![02 - discover - dark - after](https://user-images.githubusercontent.com/793774/83925417-f85d6200-a73b-11ea-84e7-480cb1c4511b.png)|
|---|---|
|<img width="406" alt="03 - 01 - crosspost - light - before" src="https://user-images.githubusercontent.com/793774/83925581-5c802600 …
> Applies new reader card UI design feedback

- WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
- WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
Fixes #13282 
To test:
- Check that the notifications section header, read and unread status look like the original specification on iOS < 13.
- Check that the notifications section header, read and unread status look like the original specification on iOS > 13, light and dark mode.
> Update notifications table colors

- WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
Fixes #11394 
This PR uses the recommended `.clearWithTag` behavior instead of `.dismiss` on the Quick Start tour guide.
Walk through the "Customize Your Site" tour and "Grow Your Audience" tour. Ensure there are no regressions to the toasts and how they behave.
**Known issues:** the iA work has changed where our navigation is located, so now some steps are marked incorrectly in the Quick Start guide. See issues #14267 and #14268.
> Quick Start: Dismiss Notices using clearWithTag

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Fixes #13911 
To test:
1. Add an Image block
1. Add an image to it using `Free Photo Library` (or `Free GIF Library` or `Other Apps`)
1. Preview the post
1. Close preview
1. Add another Image Block
1. Add an image to it using the same source as before
1. App shouldn't crash and image should be successfully added
> Fix crash in block editor when adding a second image

- WordPress/Classes/ViewRelated/Media/Tenor/TenorPageable.swift
Ref https://github.com/wordpress-mobile/WordPress-iOS/issues/13803#issuecomment-626715437
This fixes the issue noted in the referenced comment: 
> Issue in the block editor where I saw search results appear briefly and then vanish. For some reason it happens for me every time with the search term 'blathers'.
The problem was `TenorService` was loading an additional page when it didn't need to because `TenorPageable` was telling it there was a next page. So, after correctly displaying the search results, the last fetch would return nothing, resulting in the no results message.
This change determines if the last page was partial or not. If it was, stop loading.
To test:
- Add media via Free GIF Library. (media library or page/post editors)
- Enter a search term that has few results. …
> GIF search: correctly display partial page results.

- WordPress/Classes/ViewRelated/Reader/ReaderRelativeTimeFormatter.swift
- WordPress/WordPressTest/ReaderRelativeTimeFormatterTests.swift
Fixes #14315
The test was failing because of a different in the date formats between the test and code. I updated the formats to match the code base. 
I also noticed the dateFormatter property was mistakenly setting the `timeZone` property and not the `timeStyle` property. I updated that as well.
1. Run the unit tests for the ReaderRelativeTimeFormatterTests class
> Fixes the failing test

- Podfile
- Podfile.lock
- WordPress/Classes/System/WordPress-Bridging-Header.h
Running `bundle exec pod outdated` tells us that the `FormatterKit` pod is unused in the project.
Deleting it compiles and passes all tests, so I'd imagine it's safe to remove.
#14320 must be merged before opening this for review.
> Remove formatterkit

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Fixes #NA
To test:
- Make sure the app builds and runs
- Additionally, try to draft/publish some posts, access the Reader, add saved posts, etc
> Revert swift core data feature flag to local developer only

- WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Fixes #13437 
This fixes an issue where the web preview logic to upload a post could occur multiple times while the post is being uploaded to the server. It checks whether the post is currently being pushed before trying again and showing the web preview.
- Make a few changes to the content
- Throttle connection using Network Link Conditioner (or other tool). These were the settings I used:
- Go to "Web Preview"
- While the Preview is being generated, tap "Web Preview" again and do this 2-3 times.
- Before the PR this should produce a Preview Unavailable message. Afterward, this should produce an alert about the post being uploaded.
> Fixes Web Preview bug

- MIGRATIONS.md
- WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 97.xcdatamodel/contents
- WordPress/WordPress.xcodeproj/project.pbxproj
Refs #12028
While digging into #12028 I found a number of events where the cause was `TopCommentedPostStatsRecordValue.postURLString` being `nil` when Core Data was saved.  The data model did not define the `postURLString` field for this entity as optional, even tho the code across the app did. (The API code is written such that a URL should always be returned so an optional here is a little odd, but I digress.) 
Looking at other stats model entities I found inconsistent property definitions where numerical fields might have default values or not, and where string, date, and numerical fields might be optional or not.  
It's important to resolve the core data crash, and since the code seems to be pretty consistent in how it handles these different fields the best thing seems to be to …
> Core Data: Normalizes model config for stats entities.

- WordPress/Classes/Utility/Migrator/CoreDataIterativeMigrator.swift
A quick PR to add some extra information to errors that can be thrown during a core data migration to help better understand what went wrong.  Changes include:
- Including the to and from version involved when something goes 💥 
- Including information from an original error (if one exists) as part of our thrown error description.
- A slight refactor in a couple of places where a thrown error could be out right ignored.
Xcode was complaining in a few places about the newly added `error(with:description)` method so there is a bit of a mix-match with its usage. I prefer not having to include the class as part of the usage so I've only done that where necessary. Not sure why this is happening tho.
To test:
Run the branch and make sure it builds. 
Try migrating from a previous version and make …
> Core Data: Tweaks thrown errors to include more context about what went wrong

- WordPress/Classes/Utility/Networking/GutenbergRequestAuthenticator.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergWeb/GutenbergWebViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes parts of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2358
This PR overrides `RequestAuthenticator` for the specific Gutenberg web view use case, where we want to use the `regular` auth type also for Atomic sites.
To test:
- Setup an atomic site and test as public and private.
- Create a post with a block not yet supported on mobile.
- Test on a real device.
- Will need Metro server running (on gutenberg-mobile develop branch is enough)
- Log out from your wp account in the app to clean cookies.
- Uninstall the app from your device.
- Install building the app from this PR.
- Login and go directly to the Atomic site.
- Open the created post with unsupported block.
- Open the unsupported block on the web view.
- Check that gutenberg opens on the web view without asking …
> [Gutenberg] Fix gutenberg web-view auth issues with Atomic sites

- MIGRATIONS.md
- WordPress/Classes/Services/PostCategoryService.m
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 97.xcdatamodel/contents
Refs #12028 
This PR attempts to address some core data save errors where `Category.parentID` is `nil`, or where `Category.blog` is `nil`.  The exact circumstance that leads to the error remains unknown so the changes here are a best guess about what could contribute to the error. 
Changes:
- I've removed where Category.blog was explicitly set to `nil` when deleting a Category. The Category entity is already configured to nullify the `blog` relation when deleted so this should have been unnecessary and it's not clear why it [was added](https://github.com/wordpress-mobile/WordPress-iOS/pull/6451/files).
- The data model is updated so numeric fields are scalar and non optional. This should result in there always being a default value as opposed to nil when saving.
- I've modified code in …
> Categories: Makes fields scalar non optional. Adjusts order of execution

- Podfile
- Podfile.lock
Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/182
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/307
This uses the Auth branch to display Large Titles in the navigation bar. 
As noted in the Auth PR, displaying the large titles in the email login flow is for testing purposes only, and will be removed before the PRs are merged.
To test:
---
- Run the app. Log out if necessary.
- `Log In` > `Continue with WordPress.com`.
- Verify:
- The back button label is 'Back'.
- `Log In` is displayed in the nav bar.
---
- Enter an email address and `Next`.
- Verify:
- The back button label is 'Back'.
- `Log In` is displayed in the nav bar.
---
- Select `Enter your password instead.`
- Verify:
- The back button label is 'Back'.
- There is no …
> ULS: Display navigation bar large titles

- WordPress/Classes/ViewRelated/Reader/DetailWebView/OfflineReaderWebView.swift
- WordPress/Classes/ViewRelated/Reader/DetailWebView/ReaderDetailToolbar.swift
- WordPress/Classes/ViewRelated/Reader/DetailWebView/ReaderWebView.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailWebviewViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterAction.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #14337
Review only after #14328 is merged
This PR adds basic support to offline when saving a post for later in the Reader.
Why *basic* support? What we do is:
1. We open a hidden webview to preload the post, so when offline must of the resources (mainly images) will be there
2. Why not all of them? Because the WebView respects the cache from the server. If an image comes from a server that disables caching its resources, this will not work (but it will work with WP.com)
**Make sure that you have overridden the new reader Feature Flag and it's not using the older Reader (Me -> App Settings -> Debug -> "Reader content displayed in a webview" should be ON)**
1. Open the Reader
2. Save a few posts for later
3. Close the app
4. Go offline
5. Open the app
6. Open the saved posts, most of …
> Save for later: basic offline support

- .github/workflows/danger.yml
This is just a little refinement that makes sure that if the only change someone makes to a PR is adding or removing the milestone, our workflow will run and Danger will leave a comment, if appropriate.
Unfortunately, in order to test this, the code needs to be on the default branch already, see [the docs](https://help.github.com/en/actions/reference/events-that-trigger-workflows#issues-event-issues).
(_The fact that the workflow needs to be on the default branch explains the behavior @jkmassel experienced with milestones [in this earlier PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/13556#discussion_r384676495)_)
You can play around with adding milestones to PRs and issues (to verify Danger doesn't run) on [this repo](https://github.com/mokagio/danger-github-actions-examples) …
> Update GitHub Actions workflow running Danger to support milestone events

- WordPress/Classes/ViewRelated/Reader/DetailWebView/ReaderCSS.swift
- WordPress/Classes/ViewRelated/Reader/DetailWebView/ReaderWebView.swift
- WordPress/Classes/ViewRelated/Reader/DetailWebView/reader.css
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.storyboard
- WordPress/WordPress.xcodeproj/project.pbxproj
Review only after #14339 is merged.
This PR:
- Center images in small devices so they don't appear in the left if they're small
- Adds the color for the captions
- Adds a structure to refresh the CSS every two days if the user is online (won't affect offline)
- Only display images after they have been fully loaded, to simulate a native feel
- Do not display images broken, again, to have a native feel
To test
* Check this post, the image should be center-aligned: https://made4testing0318.blog/2020/04/17/another-image-block/
* In the same post, you can check the caption color
* Open a post full of images and check that they appear as a whole instead of slowly appearing
* Open a post with a broken image and check that the image doesn't appear, space it's there, but no broken images icons are …
> New Reader Detail: CSS fixes 

- RELEASE-NOTES.txt
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Fixes #13862
Fixes #9525
Fixes #13863
Fixes #13936
Fixes #13937
Fixes #14014
Fixes #14023
Fixes #2199
This PR just enables the new Reader.
To test
1. Open a post in the Reader
2. Make sure it's opening with the new `ReaderDetailWebviewViewController`
> Enable new Reader Detail

- WordPress/Classes/Utility/InteractiveNotificationsManager.swift
- WordPress/Classes/Utility/PushNotificationsManager.swift
- WordPress/WordPressTest/PushNotificationsManagerTests.m
In this PR we're introducing a workaround, expected to fix scenarios in which the Push Authentication alert would not be presented.
cc @leandroalonso sir, may I bug you with this one?
cc @yaelirub @bummytime Ladies and gentlmene, **quick and easy workaround**
Fixes #13412
Before time was invented, the way to determine if the user interacted (pressed) a Push Notification alert was to check the `applicationState`. Anything but `.background` signaled that the Alert was presented, and the user pressed on it.
Since iOS 10, `UNUserNotificationCenter` has become the preferred way to determine User Interaction over Pushes.
Proper solution involves a cleaner refactor of `PushAuthenticationManager` / `InteractiveNotificationsManager`. In the aims of fixing this bug ASAP, we're introducing a low …
> Fixing Push Authentication

- WordPress/Classes/Utility/Networking/RequestAuthenticator.swift
Refs #13953 
This fixes an issue where the app would attempt to fetch auth cookies for atomic sites that were not private.  The endpoint in question assumes that it will only be used with a private atomic site and returns a 500 error in other cases. 
To test:
Use a private atomic site, set to coming soon or not, and confirm you can successfully get auth cookies, view the site's media, and preview a draft post
Repeat the test with a public atomic site and confirm auth cookies are not fetched and not needed to preview posts or view media.
@etoledom Could I trouble you with this one?
> Auth: Use atomic cookie auth only if atomic and private.

- WordPress/Classes/Services/AuthenticationService.swift
- WordPress/Classes/Utility/CookieJar.swift
- WordPress/Classes/ViewRelated/Reader/ReaderRelativeTimeFormatter.swift
- WordPress/WordPressTest/ReaderRelativeTimeFormatterTests.swift
This PR fixes an auth issue on Previews due to changes in the backend.
We are not setting the WordPress User Agent to the auth cookies request to avoid being blocked.
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2411
To test:
- Clean install the WordPress app.
- Login to a WPCom account.
- Create a new post on a blog that's not private Atomic.
- Write something and choose to preview (without publishing).
- Check that the preview works.
**Note:** This PR was initially intended to fix an auth issue on Gutenberg Web-View for the unsupported block fallback project. So this also fixes parts of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2358
cc @marecar3 @aerych
> Fix WebViews Auth on WPCom after login in.

- WordPress/Classes/ViewRelated/System/WPTabBarController+QuickStart.swift
Fixes #14286
To test:
1. Create a new site
2. Yes, Help Me when prompted
3. Close the "Customize Your Site" modal view
4. Open "Grow Your Audience"
5. Choose "Follow other sites"
6. Rotate the device or sim and verify that the spotlight stays close to the reader icon tab
> Fix spotlight on the reader tab icon when rotating devices

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Reader/ReaderDetailCoordinator.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderMenuAction.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
**Fixes** #14190
When a user taps the more menu the event looks for a `ReaderSiteTopic` for the `ReaderPost`'s site, and if the site topic doesn't exist for some reason the the event would be ignored and nothing will happen. 
```
let service = ReaderTopicService(managedObjectContext: context)
--> if let topic = service.findSiteTopic(withSiteID: post.siteID) { <-- if this is nil, nothing happens
showMenuForPost(post, context: context, topic: topic, readerTopic: readerTopic, fromView: anchor, vc: vc)
return
}
```
Prior to 14.7 the `ReaderMenuViewController` called the [`syncTopics`](https://github.com/wordpress-mobile/WordPress-iOS/blob/14.6/WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift#L253) method which sync'd both the reader more menu and the followed sites.
The …
> Fixes reader more menu not appearing

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Fixes #14371 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/309
To test:
Have an account that:
- Has been used to login via SIWA.
- Does not have a WP password set.
- Has 2FA enabled on the WP account.
Login via `Continue with Apple`. 
- After entering the Apple ID credentials, verify the 2FA code entry view is displayed.
- Enter code and verify the account is logged in.
> Update Auth to fix SIWA passwordless 2FA logins.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
- WordPress/Classes/ViewRelated/Post/PostEditor.swift
Fixes #13618 
Added a new method to the PostEditor protocol to allow the editor
send the information about content metrics.
This allows them to use a more optimized way to calculate metrics
and match with the way they display content information in the editor.
@koke I think you may enjoy reviewing this one :)
I also have a question for you I notice that on `word_diff_count` prop for analytics we are sending the original number of words in the post, is this correct or should we send the actual difference of numbers words between the original post and new post content?
**Update (22-06-2020)**: After some discussion offline we decided to remove the `word_diff_count` property altogether.
The rationale is that we are not using it for any stats, and we also don't implement it in Android and …
> Fix word count to ignore HTML tags/comments when doing analytics.

- WordPress/Classes/Services/ReaderPostService.m
- WordPress/Classes/System/WordPressAppDelegate.swift
- WordPress/Classes/ViewRelated/Reader/DetailWebView/ReaderCSS.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailWebviewViewController.swift
This PR fixes the navigation bar title behavior when scrolling down/up in the Reader Detail.
It also makes sure that the Reader content doesn't have any `script` tag, preventing possible JavaScript injections.
1. Open a post in the Reader
2. Scroll down/up
3. Check that the navbar fades in or out depending on how much you scroll
Make sure the nav bar has the same font size / weight.
> Fix navigation bar title when scrolling

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
CircleCI follows build paths for `.localDeveloper`. Since I left `.unifiedSiteAddress` enabled for dev builds, it created a cascading effect and made all the tests fail.
To test: n/a 
This PR disables the .unifiedSiteAddress feature flag.
> Disable .unifiedSiteAddress feature flag

- WordPress/Classes/ViewRelated/Reader/DetailWebView/ReaderDetailHeaderView.swift
This PR fixes an issue where the gradient views at the edges of the Reader detail view header's byline didn't adapt to user interface style changes:
When viewing the app in dark mode, for instance, the gradients remained using a light background color. This issue only affects the new webview-based Reader detail view.
**To test:**
* Build and run the app – ensure that the new Reader webview-based detail view is enabled.
* In Me > App Settings > Appearance, set the app to dark mode
* In Reader, visit the detail page for a post
* Ensure the gradients aren't visible at the sides of the byline
* You can also test this with the Appearance set to System default, and toggle dark mode on and off at the system level.
> ReaderDetailHeaderView: Reload gradients if interface style changes

- WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsCollectionViewFlowLayout.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Creates a `UICollectionViewFlowLayout` class to be used on the Reader Phase 2 Select Interests view.
The flow layout supports:
| Left to Right | Right to Left | Centered LTR | Centered RTL |
|---|---|---|---|
| ![00 - LTR](https://user-images.githubusercontent.com/793774/85890189-ba36e980-b7a1-11ea-852f-2cd3ddada390.png) | ![01 - RTL](https://user-images.githubusercontent.com/793774/85890192-bacf8000-b7a1-11ea-933c-77575d28cad4.png) | ![02 - Centered LTR](https://user-images.githubusercontent.com/793774/85890194-bacf8000-b7a1-11ea-83cc-b90a1e00385f.png) | ![03 - Centered RTL](https://user-images.githubusercontent.com/793774/85890196-bb681680-b7a1-11ea-8bd1-acfd6d124ab8.png)|
There are no user facing changes to test right now.
> Reader Phase 2: Select Interests: Creates a custom UICollectionViewFlowLayout subclass

- Podfile
- Podfile.lock
- WordPress/WordPress.xcodeproj/project.pbxproj
Updates the Media Editor to 1.2.0.
The green build should be enough. There wasn't any change on Media Editor API and the changes were tested in there.
> Update Media Editor

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergWeb/GutenbergWebNavigationViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergWeb/GutenbergWebViewController.swift
This PR replaces https://github.com/wordpress-mobile/WordPress-iOS/pull/14353
Fixes parts of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2358
Implements changes from: https://github.com/WordPress/gutenberg/pull/23450
`gutenberg-mobile` ref: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2449
We are adding:
- `gutenberg_unsupported_block_webview_shown`
- params: `"block": "{block_internal_name}"`
- `gutenberg_unsupported_block_webview_closed` 
- params: `"action": "save" / "dismiss"` accordingly.
cc @marecar3 
To test:
- Run Metro server on https://github.com/wordpress-mobile/gutenberg-mobile/pull/2449  to activate the webview option on unsupported blocks ensuring that the required JS code is running.
- Open the unsupported block web view
- Check that …
> [Gutenberg] Unsupported fallback tracks

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Related https://github.com/wordpress-mobile/gutenberg-mobile/pull/2457
To test: See https://github.com/WordPress/gutenberg/pull/23592
> Enable editing of unsupported blocks

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Main Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/14395
1. Tap the My Sites tab
2. Tap your profile icon in the top corner
3. Tap the debug settings item
4. Verify there is a 'Reader Improvements Phase 2' item
5. And it's off
> Add feature flag for reader improvements phase 2

- Podfile
- Podfile.lock
- Fixes a couple of crashes
- Has better Swift 5 support
To test:
- If the tests pass, it means the logging configuration is working and this PR is ok.
This PR is probably destined to have `Podfile.lock` conflicts forever. I think I'll have to fix that immediately before merging.
> Update CocoaLumberjack to 3.6.1

- Podfile
- Podfile.lock
Fixes #14404 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/314
This uses the Auth changes to correctly set the navigation bar's title text color.
To test:
- Run the app on a device with iOS 13.5.1. (Per the comment on the [bug](https://github.com/wordpress-mobile/WordPress-iOS/issues/14404): "I'm only seeing this on iOS 13.5.1. On iOS simulators with iOS 13.5 I don't see the issue.")
- Log in.
- NOTE: The only way I could reproduce the bug was to log in with a social account that didn't require any WP information, i.e. a Google or Apple account that does not prompt for WP password or 2FA code, and goes directly to the login epilogue.
- Verify the nav title text color is white.
> Update Auth to fix the nav bar's normal title color.

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/316
This updates the large title font weight in the Login and Signup Epilogues. It also uses the Auth changes to show the updated nav bar in the Site Address view.
To test:
- Enable the `unifiedSiteAddress` Feature Flag.
- Verify the nav bar title is in NY font.
<kbd><img width="472" alt="auth" src="https://user-images.githubusercontent.com/1816888/86839790-1d0c6880-c05f-11ea-86f9-ad98daceaa8d.png"></kbd>
- Log in.
- Login and Signup Epilogues use the same user info UI, so testing one will verify both.
- On the epilogue, verify the user name is in NY font.
<kbd><img width="468" alt="epilogue" …
> ULS: Update large title font

- WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
Fixes #14411
To test:
1. With an existing account, create a new site and when prompted "Want a little help getting started" tap on "Yes, help me". 
2. Select "Set your site title" and verify that the notice says "Select Site Title to set a new title"
3. Set a custom title
3. From "My Site", tap on the "Customize my site" in the "Next Steps Section", and from the "Completed" section, select "~~Set your Site Title~~"
4. Verify that the notice now reports the custom title that you previously set
1. Log out.
1. Log in with a new account and create a new site. Follow the same steps as 1
1. Select "Yes, Help Me" when prompted.
1. Go to Quick Start > Site Title.
1. Checkthe notice says "Select Site Title to set a new title" and does not contain names from the previously logged accounts
PR …
> Fixes wrong site title showing in quick start tour

- Podfile
- Podfile.lock
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/317
This uses the Auth changes that removes the app icon from the unified Auth navigation bar.
To test:
- Enable the `unifiedSiteAddress` Feature Flag.
- Verify the WP icon does not display in the nav bar.
- Note: the icon is white, so you may want to switch to dark mode so you can see it's actually gone.
- Go to any other auth view.
- Verify the WP icon is displayed in the nav bar.
> ULS: update Auth to show updated nav bar.

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Fixes #14287
To test:
- create a new site
- accept the quick start guide
- go to step 6/6 'view your site' 
- Tap on 'View site'
- Modal view opens with your site
- Close the modal
- Verify that the notice bar has been dismissed and the FAB is in the expected position
> Fix wrong FAB position after Quick Start -> Visit Site

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
The Unsupported Block Editor feature was disabled on sites connected via Jetpack because of an issue requesting cookies from those sites without having login credentials other than WP.com credentials.
This inadvertently blocked Atomic sites as well, which are also connected via Jetpack. Atomic sites, being WP.com sites, don't have the cookie issue so this PR enables this feature on those sites.
Addresses https://github.com/wordpress-mobile/gutenberg-mobile/issues/2470
To test, perform [the Unsupported Block test cases 1 to 4](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/unsupported-block-editing.md).
> Allow the Unsupported Block Editor on Atomic sites

- Podfile
- Podfile.lock
Fixes #n/a
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/325
This update Auth to include the fix for https://github.com/wordpress-mobile/WordPress-iOS/issues/14404.
To test:
Follow the testing steps on https://github.com/wordpress-mobile/WordPress-iOS/pull/14418.
> Updating Auth branch.

- WordPress/Classes/ViewRelated/Reader/DetailWebView/ReaderCSS.swift
- WordPress/Classes/ViewRelated/Reader/DetailWebView/ReaderWebView.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/ReaderCSSTests.swift
This PR fixes the basic offline suport in the new Reader detail.
1. Open the Reader
2. Save a few posts 
3. Go offline
4. Open the saved posts, they should show the cached images
> Fix basic offline support in Reader

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/326
This uses the Auth changes to show the new unified auth nav bar. That is, no large titles.
To test:
- Enable the `unifiedSiteAddress` Feature Flag.
- Verify the standard navigation title is displayed.
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-09 at 14 22 24](https://user-images.githubusercontent.com/1816888/87087661-bf0f8a80-c1f0-11ea-97ff-d77721a38abf.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-09 at 14 22 41](https://user-images.githubusercontent.com/1816888/87087681-c6cf2f00-c1f0-11ea-8591-526d5e47695f.png) |
> ULS: Show unified Auth nav bar without large titles. 

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FancyAlerts.swift
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/BlogDetailHeaderView.swift
- WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
Fixes #14441
To test:
* Enter the "Customize Your Site" screen from your new site
* Tap the "Upload a site icon" or "Set your site title"
* Tap on any cell in the table view
* Go back to the My Site and verify that the spotlight does not show anymore
> Remove spotlight from site title and site icon after navigating away of My Site

- WordPress/Classes/ViewRelated/Reader/ReaderDetailCoordinator.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailWebviewViewController.swift
- WordPress/WordPressTest/ReaderDetailCoordinatorTests.swift
Fixes #9140 
1. Use this post: https://wordpress.com/read/blogs/93917131/posts/2091
2. Tap on a link and check that the page scrolls
> Reader: enable scroll for #hash links

- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
Ref #14412 (improves the performance but does not totally fixes the issue)
Loads followed sites asynchronously to avoid blocking the Reader UI when it first loads.
To test:
1. Do a fresh install of the app or log out and back in to a different account.
2. Go to Reader.
3. Verify that the reader UI loads quickly and there is no noticeable blank screen before it loads
4. verify that issue #14370 does not occur
> Fixes reader UI too slow to load at first load

- WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsStyleGuide.swift
- WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.swift
- WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.xib
Main Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/14396
1. If it's not already enabled, enable the Feature Flag for Reader Improvements Phase 2
3. Tap the Reader tab
4. The view will be presented
5. Verify the button is now disabled and says "Select a few to continue"
6. Tap an interest to select it
7. Verify the button is now enabled and says "done"
8. Deselect the interest
9. Verify the button is now disabled and says "Select a few to continue"
1. Follow the steps above
2. When the button is enabled
3. Tap it
4. Verify the view is dismissed
> Reader Improvements Phase 2: Select Interests: Add next button enable/disable selection toggle

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Header.swift
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Tools/SettingsTextViewController.h
- WordPress/Classes/ViewRelated/Tools/SettingsTextViewController.m
Fixes #NA
To test:
- Create a new WordPress.com site
- When prompted, select "Yes, Help Me"
- Tap on "Set Site Title"
- Verify that once you are done (by either cancelling or setting a new title) the "Set Site Icon" suggestion appears
- Set your site icon (or cancel the action once started)
- Verify that the "Set theme" suggestion appears
> Add quick start next step suggestion for site title and site icon

- Scripts/fastlane/Fastfile
This PR fixes the description of the `finalize_hotfix_release`.
Thank you @oguzkocer for spotting this!
> Fix finalize_hotfix_release lane description

- WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderWelcomeBanner.swift
- WordPress/Classes/ViewRelated/Reader/ReaderWelcomeBanner.xib
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/ReaderWelcomeBannerTests.swift
Part of #14399
This PRs adds the welcome banner the first time the user sees the Discover section.
| Light  | Dark |
| ![Simulator Screen Shot - iPhone 11 - 2020-07-14 at 09 49 04](https://user-images.githubusercontent.com/7040243/87429451-2d21cc00-c5ba-11ea-81cf-936ea30d927e.png) | ![Simulator Screen Shot - iPhone 11 - 2020-07-14 at 09 48 54](https://user-images.githubusercontent.com/7040243/87429498-3f9c0580-c5ba-11ea-9437-7933017d146c.png) |
| Light  | Dark |
| ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-07-14 at 09 53 01](https://user-images.githubusercontent.com/7040243/87429556-57738980-c5ba-11ea-9aab-3bd7f94b466d.png) | ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-07-14 at 09 51 …
> New Discover Welcome Banner

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Fixes #13702
To test:
1. Create a new site in the app.
2. When prompted, accept more help getting started to get the Quick Start tours.
3. Select the "Publish a post" tour from the 'Grow Your Audience' groups in 'Next Steps'
4. Follow the prompt to open the post editor on the FAB
5. Publish a post.
6. Publish or dismiss a post
7. Verify that quick start next step notice appears when the post editor is dismissed
> Launch quick start next step after dismissing post editor

- WordPress/Classes/Utility/WebKitViewController.swift
- WordPress/Classes/Utility/WebViewControllerConfiguration.swift
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FancyAlerts.swift
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Fixes #13070
See note: https://github.com/wordpress-mobile/WordPress-iOS/issues/13070#issuecomment-658271671
To test:
1. Create a new site in the app.
2. When prompted, accept more help getting started to get the Quick Start tours.
3. Select the "Choose a theme" tour.
4. Open the Themes section.
5. Select and activate a new theme.
6. Tap 'OK' and then close the theme preview
7. Verify that the next quick start prompt is shown
> Present quick start next step after the theme preview has been dismissed

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Fixes an issue where the Block Editor Loading View wouldn't adjust to changes when the device changes orientation.
To test:
- Open a post/page with gutenberg.
- While the editor is loading, rotate the device.
- Check that the Loading View responds accordingly to the orientation change.
> [Gutenberg] Fix Editor loading view on device orientation changes

- WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController+Cells.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewModel/RegisterDomainDetailsViewModel+RowDefinitions.swift
- WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewModel/RegisterDomainDetailsViewModel+RowList.swift
- WordPress/WordPressTest/RegisterDomainDetailsViewModelTests.swift
In domain registration form text field on edit end now transforms non-ASCII-range Latin letters to an approximate ASCII-range equivalent letters
Fixes #10536
To test:
There is a "Register Domain" button appearing for premium accounts who have free premium domain or other accounts with domain credits.
1. Open domain registration suggestions
1. Search a random domain name
1. Select it
1. In the form type [Latin-1 Supplement](https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block)#Character_table) or [Latin Extended-A](https://en.wikipedia.org/wiki/Latin_Extended-A) letters in various fields
1. If you go to another field those letters should be transformed to ASCII-range letters
> Domain Registration: Sanitize form fields

- WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
Fixes #14409
Configures the Reader Following search bar using the method from `WPStyleGuide`.
|--|--|
| <a href="https://user-images.githubusercontent.com/3250/87353821-c9949180-c51a-11ea-8060-e42483126b42.png"><img src="https://user-images.githubusercontent.com/3250/87353821-c9949180-c51a-11ea-8060-e42483126b42.png" width="300"></a> | <a href="https://user-images.githubusercontent.com/3250/87353843-d1543600-c51a-11ea-844d-609057b50d6f.png"><img src="https://user-images.githubusercontent.com/3250/87353843-d1543600-c51a-11ea-844d-609057b50d6f.png" width="300"></a> |
1. Go to Reader > Manage (cog icon).
2. Check the color of the search bar.
> Fixes Reader Following search bar color + style

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+MoreActions.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Exact same changes as #14461, but targetting 15.3 – it would be nicer to get this fix out sooner than 15.4 as the menu is currently pretty unusable for anyone on the iOS 14 betas on iPad.
**To test:**
- You'll need to build using Xcode 11.5 to an iPad running iOS 14.2. To do this, you'll also need the latest Xcode 12 beta installed, and to symlink to the device support folder as detailed here: https://gist.github.com/steipete/d9b44d8e9f341e81414e86d7ff8fb62d#file-gistfile1-txt
- Build and run on an iPad running iOS 14b2
- Open Aztec and open the More menu multiple times. Ensure you can see the contents.
- Open the block editor and open the More menu multiple times. Ensure you can see the contents.
> iOS 14 More Popover Fix (targetting 15.3)

- WordPress/Classes/Services/ReaderCardService.swift
- WordPress/WordPressTest/ReaderCardServiceTests.swift
- WordPress/WordPressTest/Test Data/reader-cards-success.json
Part of #14399
This PR calls the API giving the list of followed interests/topics.
There are no visual changes to be tested.
Please, rely on the code and unit tests when reviewing. :)
> Call Reader Card API with the list of followed interests

- Podfile
- Podfile.lock
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/330
This uses the Auth changes to show the updated status bar. That is:
- In the new Site Address flow, the status bar is `default` (i.e. black and white).
- In the existing flows, the status bar is still white.
To test:
- Enable the `unifiedSiteAddress` feature flag.
- In both views in this flow (site address and credentials), verify the status bar is:
- Black in light mode.
- White in dark mode.
| <img width="498" alt="light" src="https://user-images.githubusercontent.com/1816888/88002054-d38c3680-cabe-11ea-9ae1-bee45bfc1aec.png"> | <img width="499" alt="dark" …
> ULS: Use updated status bar for unified flows

- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
This fixes an issue where the Support nav bar style was (incorrectly) inheriting the unified Auth nav style. Now, when Support is displayed from Auth, the nav bar style is set to the app's nav style.
To test:
- Enable the `unifiedSiteAddress` feature flag.
- Tap `Help` on the nav bar.
- Verify the `Support` nav bar is now back to the original style, i.e. blue background with white text.
| <img width="499" alt="Screen Shot 2020-07-21 at 1 17 18 PM" src="https://user-images.githubusercontent.com/1816888/88096851-8b1f5800-cb54-11ea-9fd7-2e372ed79920.png"> | <img width="497" alt="Screen Shot 2020-07-21 at 1 15 47 PM" …
> ULS: Support view: use the app's nav bar style when presented from Auth

- Podfile
- Podfile.lock
Possibly fixes #13427
WordPressKit change: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/263
The memory graph debugger shows a leak of `SessionDelegate` objects due to a retain cycle caused by delegate properties set in `WordPressOrgXMLRPCApi`:
I'm theorizing that this leak _could_ be the culprit of #13427 because that crash occurs inside of the generated `__ivar_destroyer` of `SessionDelegate`. Additionally, when I checked the address of those crashes using [Hopper](https://www.hopperapp.com) I landed on a line which appears to be releasing the 
`sessionDidReceiveChallengeWithCompletion` property in `SessionDelegate`:
To test:
1. Create a site on jurassic.ninja if you do not already have one
2. Log in to the self-hosted site
3. Open the Memory Graph Debugger or Leaks …
> SessionDelegate Leak Fix

- Scripts/update-translations.rb
This PR updates the build for translators to use the .com GlotPress instance. Currently, the .com instance is sync'ed only for some languages, so the script will download only those. 
To test:
1. Run `bundle exec fastlane build_for_translation_review` and verify that the build succeeds and that the translations for the languages in the  `REVIEW_LANGS` array have been downloaded. 
2. Clean up any local change. 
3. Run `.Scripts/update-translations.rb` from the project root folder and verify that it succeeds and that all the translations have been downloaded.  
> Update translators review builds

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
This PR adds the feature to show the post content when using the arrows to navigate between notifications.
Previous, we just showed the post title with an image or an excerpt, now the full post is shown.
| Before  | After |
| ![2020-07-22 14 17 08](https://user-images.githubusercontent.com/7040243/88207387-1ae10700-cc26-11ea-890b-057b5b8865ea.gif) | ![2020-07-22 14 15 07](https://user-images.githubusercontent.com/7040243/88207407-22081500-cc26-11ea-8b8b-d8cdb2a12958.gif) |
1. Go in the Notifications tab
2. Make sure you have at least one notification of a new post published in any site
3. Tap the closest notification (below or above) that one
4. Use the arrow to navigate to the post notification
5. Make sure the content is rendered
PR submission …
> Show post content when navigating between notifications

- WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
- WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
After these views are dismissed, the nav bar style is reset to the app style. This fixes the issue noted on [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/14386#issuecomment-650316300) where the nav bar was incorrect after accessing a unified Auth flow.
- `LoginEpilogueViewController`
- `SignupEpilogueViewController`
- `PostSignUpInterstitialViewController`
**To test:**
The bug is triggered by _first_ accessing the Site Address view, which changes the nav bar style, _then_ logging in with an Apple that requires no WP information. That is:
- Does not have a WP password.
- Does not have 2FA enabled.
In short, you need an Apple account that immediately logs in after entering the Apple …
> ULS: Reset nav bar style when initial views are dismissed.

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FancyAlerts.swift
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Fixes #12740
To test:
1. Create a new WordPress.com site in the app.
2. Follow the prompts until you reach the screen saying "Want a little help getting started?".
3. Tap "Yes, Help Me".
4. Go through each of the tour items in order, stopping when you get to the "View your site" prompt with "Now now" and "Yes, show me" options.
5. With that prompt still on the screen, open the Blog Posts section.
6. Tap "View" to preview a post.
7. Verify that you are redirected to 'My Site' and the 'View Site' action is suggested by the notice and the spotlight
> Go back to My Site when the 'View Site' quick action suggestion is displayed in a child ViewController

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
- WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
Fixes #13803 
This removes the `tenor` feature flag and associated checks.
To test:
Detailed testing steps can be found on https://github.com/wordpress-mobile/WordPress-iOS/pull/13949. In short, verify you can add GIFs from:
- Media Library
- Block Editor
- Classic Editor 
> Remove Tenor feature flag.

- Podfile
- Podfile.lock
Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/283
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/334
To test:
- Enable the `unifiedSiteAddress` feature flag.
- On both the Site Address and Site Credentials views, verify the table and button widths are sized properly:
- On iPad portrait.
- On iPad landscape.
- On iPhone portrait (views don't rotate to landscape on iPhone), or multi-tasking on iPad.
As noted on the Auth PR:
- For the Regular x Regular size class:
- In portrait, the table is 66% of the view width.
- In landscape, the table is 50% of the view width.
- For all other size classes, the table is 100% of the view width.
- The Continue button width resizes with the table.
---
**Regular x …
> ULS: Update Auth to use iPad table widths

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
This PR removes Plans from 15.3.
**To test**
- In the app, view a WordPress.com site. Ensure that Plans doesn't appear as the last item in the first section of blog details:
- Using the debug menu (blog details > me avatar > App Settings > Debug), enable Quick Start for a site. Ensure that the Plans item doesn't show in the Grow Your Audience quickstart list:
> Removes Plans from 15.3

- WordPress/Classes/Models/Post.swift
- WordPress/Classes/Services/PostService+MarkAsFailedAndDraftIfNeeded.swift
- WordPress/WordPressTest/BlogBuilder.swift
- WordPress/WordPressTest/PostService+MarkAsFailedAndDraftIfNeededTests.swift
Fixes #14493
This PR fixes offline support regression caused by a single and small line change. 🙃
A unit test was added to make sure the regression will not happen again. 
1. Go offline
2. Create a new post and publish it
3. Check that the message says "We'll publish your post..."
4. Go back online and make sure the post is **published**
1. Go offline
2. Create a new post and publish it
3. In the post list, make sure to select _Everyone_ to see posts from all users
4. Check that your post has your username
> Fix offline support for posts

- WordPress/Classes/Models/ReaderPost.m
Fixes #14531
This PR removes all the inline `style` in a Reader post's content.
We do this to prevent weird styles from showing in the Reader, like this:
1. Create a post in a blog you follow
2. Add the timeline block
3. Fill with some content
4. Go to the Reader
5. Open your post
6. Make sure that no grey background appears (test in both light and dark mode)
You can also add any other `style` tag you want and test (custom colors, size, etc). The style should not appear.
> Remove inline styles from Reader post's content

- RELEASE-NOTES.txt
- WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib
- WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.swift
- WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
After updating the topic page header in #14525 , we are now giving the site header a fresh new look as well.
To test:
1. Go to reader 
2. Tap on a site name in a post card 
3. See the new site header
Before             |  After
:-------------------------:|:-------------------------:
> Update site header UI 

- Podfile
- Podfile.lock
- WordPress/Classes/Services/ReaderCardService.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
- WordPress/WordPressTest/ReaderCardServiceTests.swift
- WordPress/WordPressTest/ReaderCardTests.swift
- WordPress/WordPressTest/Test Data/reader-cards-success.json
Part of #14399
WPKit related PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/266
This PR connects the new Discover session to the real cards API.
First, make sure you have the flag Reader Improvements Phase 2 **enabled**.
1. Go to discover
2. You should see post cards based on the interests you follow
1. Go to discover
2. Tap any post
3. Make sure the content appears correctly
1. Go to Discover
2. Scroll down
3. Checks that more posts are loaded
1. Go to discover
2. Scroll down
3. Checks that more posts are loaded and the UI is never blocked as it was before
1. Change your device/simulator language
2. Go to Discover
3. Check that the posts match your language
> Integration with Cards API

- WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderInterestsCoordinator.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
- WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.swift
- WordPress/WordPressTest/ReaderSelectInterestsCoordinatorTests.swift
Part of #14399
Review only after #14532 is merged.
This PR doesn't add any new features. Instead, it refactors logics related to the topics selecting screen.
What was done:
1. Code moved from `ReaderStreamViewController` to `ReaderCardsViewController`
2. Decoupling between the Interests Coordinator and Reader screen
3. Removed the logic to track if the user has seen the selects interests screen or not (this isn't relevant anymore, we always show this screen if the user is not following any topic)
4. Removed a few view animations to simplify code understanding
1. Login using a WP.com account
3. Delete all of your followed tags if you have any
4. Tap on the Reader tab
5. Tap on the 'Discover' tab
**Expectation:** You are presented with the Select Interests View
1. …
> Select topics refactoring

- WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderInterestsCoordinator.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
This PR fixes an issue pointed by @yaelirub in #14539:
> Discover content doesn't get updated when Im removing and adding tags so I have to pull to refresh to see the new content:
> 
> <img src="https://user-images.githubusercontent.com/1335657/89010671-e9220d00-d2c3-11ea-9cc6-856cc2fed028.GIF" width="300">
First, remove all your followed tags (Following -> Cog -> remove all followed tags).
1. Go to Discover
2. Select one interest
3. Tap Done and check that posts related to your selected interest are appearing
4. Go back to following
5. Remove all followed tags (Following -> Cog -> remove all followed tags)
6. Tap Discover again
7. Select an interest different from the previous one you selected
8. Tap Done
9. Make sure the new content is related to your new selected interest
PR submission …
> Update Discover section when new interests are selected

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/Services/MediaService.h
This is an attempt to fix what looks like a silent failure here: https://github.com/wordpress-mobile/WordPress-iOS/issues/14561
Unfortunately I wasn't able to reproduce the issue, but there's a chance this change could at least raise the error so that both our users and the App detect it.
> Removes a silent failure.

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
To test:
- Create A new page either from the FAB button or Page List
- Expect to see the new page editor
- Toggle Modal layout picker on 
<details>
<summary>To disable or enable the development version of Modal Layout Picker</summary>
- Open the app from the build that allows FeatureFlags such as a PR build or a local development build
- By default, the modal layout picker will be enabled.
- From the site page:
- Click on your Gravatar.
- Click on App Settings.
- Click on Debug.
- Toggle "Gutenberg Modal Layout Picker" to enable or disable the picker
<details>
<summary>To toggle:</summary>
</details>
</details>
- Create A new page either from the FAB button or Page List
- Expect to see the layout picker
> Default Modal layout picker to off

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
- WordPress/Classes/ViewRelated/Gutenberg/Views/GutenGhostView.xib
Fixes the ghost/loading view for Gutenberg being a few pixels too low
To test:
1. Create a new blog post with Gutenberg
1. Check that the loading view shows similar to the gif attached
Before | After
--- | ---
Fixed version gif | 
---|
> [Gutenberg] Fix ghost/loading view position

- WordPress/Classes/Models/ReaderTagTopic.swift
- WordPress/Classes/Services/ReaderTopicService+FollowedInterests.swift
- WordPress/Classes/Services/ReaderTopicService.m
- WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.swift
This PR allows logged out users to follow topics.
1. Do a fresh install and login with a self-hosted site
2. Go to Reader
3. Tap Discover
4. Follow Art
5. Once the cards appear, scroll down until you see the topics you might like
6. Choose one and follow it
7. Close the app
8. Open again, open the topic view you just followed and make sure you're following it (you can also tap the cog under Following and make sure the topic is there)
Scenario: removing followed topics while logged out
1. Login with an account
2. Go to Reader -> Following
3. Tap the cog
4. Only the topic you were following before with this account will be presented
Scenario: following topics while logged in
1. While still logged in follow any new topic
2. Go to https://wordpress.com/read
3. Make sure the topic is there …
> Follow topics while logged out

- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMentionsViewController.swift
- WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h
- WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
Addresses https://github.com/WordPress/gutenberg/issues/24425
The PR adds a hit area with a minimum height of 50 points to the suggestion UI list, which allows the UI to be dismissed no matter what the screen size. Currently, on smaller phones such as the iPhone 7, the suggestions UI takes up all available screen space and there is no room to tap outside it to dismiss.
**Note: the gap in the second screenshot shows the hit area this PR adds to facilitate dismissing the list.**
| -- | -- |
| <img src="https://user-images.githubusercontent.com/1898325/89603690-a7e7ab00-d837-11ea-8553-a1b4a5c7bea2.PNG"> | <img src="https://user-images.githubusercontent.com/1898325/89603696-ac13c880-d837-11ea-997d-0d90d858216e.PNG"> |
_You'll need to test with a smaller device such as an …
> Add hit area to suggestions UI to allow dismissing on smaller devices

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Gutenberg/GutenbergMentionsViewController.swift
- WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h
- WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
This PR incorporates the 1.33.1 release of gutenberg-mobile. For details about the changes included in this PR and testing instructions please see the related gutenberg-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2538
To test:
> Integrate gutenberg release 1.33.1

- WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
- WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.swift
- WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.xib
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
- WordPress/WordPressTest/ReaderTabItemsStoreTests.swift
- WordPress/WordPressTest/ReaderTabViewModelTests.swift
This PR has two different (but inter-connected) changes:
* It displays the Select Interests fullscreen
* It doesn't wait for a request to finish to show the Reader and preload the topics when the user login
1. Open the app
2. Tap Reader
3. Check that it appears right away, without waiting for a request with the server to finish
1. Do a fresh install of the app
2. Login with a self-hosted site
3. Tap the Reader, check that the Interests screen pops up
4. Select at least one topic
5. Tap Done and check that the Discover session is shown
1. You can either do a fresh install or login into an account
2. Tap Reader
3. Make sure to remove any topic you're already following
4. Tap "My Site" and then Reader again
3. Check that the Interests screen pops up
4. Select at least one topic
5. Tap Done …
> Present Select Interests fullscreen

- WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
- WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Following design feedback in: #14612 
In this PR:
- Added 2 colors, buttonIcon and primaryButtonBorder to UIColor+MurielColors.
- updated button font from headline to callout
- updated following font from semibold to regular
- updated button's border color to opaqueSeparator
- updated following background color to clear instead of black
- update following text and icon color to .systemGray2
Follow             |  Following 
:-------------------------:|:-------------------------:
Follow             |  Following 
:-------------------------:|:-------------------------:
To test:
1. Go to reader
2. Tap on a site name in a post card
3. See the follow / following button looks good and applies designs updates 
> Update Follow button UI

- WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
- WordPress/Classes/ViewRelated/What's New/WhatIsNewViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Ref #14594
Adds the "What's New" Entry in app settings and presents a modal that will become the Feature Announcement screen (see the flow in #14594).
**Note: this PR only sets the basis. Things that will be addressed in future PRs:**
- Content of the "What's New" screen: at the moment, only the "continue" button is there (and actionable)
- Size of the modal on iPad: at the moment it uses the standard size and does not reflect the designs
- Accessibility
- Unit tests
To test:
- go to 'Me' -> 'App Settings'
- scroll to the bottom and verify that there is a "What's New in WordPress" row
- tap on it and verify that a modal with a 'Continue' button is presented (see below)
- tap 'Continue' and verify that the modal is dismissed
<p align=center>
</p>
> Add What's New entry in App Settings

- WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
To clarify to app users that the Contact button is to contact WordPress.com support and not a place to leave contact details for _their_ site visitors to contact their the site, we clarified the button title to "Contact Support".
Note: The Zendesk chat screen title should also be changed, but it requires manually adding a string to the localized string files, which is incompatible with our approach of auto-generating string files from NSLocalizedString usage in the codebase.
There might be a way of doing using [extract-framework-translations.swift](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/Scripts/extract-framework-translations.swift), but it was deemed low priority.
For the record, `"ios.ZDKRequests.createRequest.title" = "Contact Support";` is what would need to be …
> Rename Contact Us to Contact Support

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
Fixes #14620 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/372
This uses the Auth changes to _not_ update the username on the Password view when logging in via a social account. To note, this fixes the issue in the current flow, not the unified. I'll fix that in a later PR.
**Prereqs:**
- You'll need to use an actual device to get the password manager button on the keyboard. 
- Two gmail accounts that:
- Have been used to create WP accounts.
- Are _not_ connected to Google*.
- Have WP passwords set.
* You can check Google connection at https://wordpress.com/me/security/social-login:
**To test:**
Google Login:
- Go to Log In > Continue with Google.
- Select account A.
- On the password entry view, tap the password manager button on the keyboard, and select …
> Social account logins: Don't update username when using a password manager.

- Podfile
- Podfile.lock
Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/352
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/375
This uses the Auth changes to use the updated unified Password view with password manager support. As noted on the Auth PR, iOS12 1Password support is not fully functional yet. So we'll just test iOS13+ here.
**Prereqs:**
- You'll need to use an actual device to get the password manager button on the keyboard. 
- A gmail account that:
- Has a WP password set.
- Is not connected to Google.
You can check Google connection at https://wordpress.com/me/security/social-login:
**To test:**
Google Login:
- Go to Log In > Continue with Google > select an account.
- On the password entry view, tap the password manager button on the keyboard, …
> ULS: use Password view with password manager support

- WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
- WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
- WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
This PR fixes the Quick Start flow for "Follow other sites" after the addition of the "Select Interests" screen.
| Before  | After |
| ![2020-08-13 11 26 49](https://user-images.githubusercontent.com/7040243/90147041-22dd2400-dd58-11ea-9ff0-ab756f58bb97.gif) | ![2020-08-13 11 20 48](https://user-images.githubusercontent.com/7040243/90147098-312b4000-dd58-11ea-903f-ef92c1aed4e6.gif) |
1. Remove all topics you're following
1. Create a new site
1. When the apps ask you if you want a little help getting started, tap Yes
1. Dismiss the "Customize Your Site" screen
1. Tap "Grow Your Audience"
1. Tap "Follow other sites" to start the tour
1. A notice appears aking you to tab the Reader tab, tap it
1. The notice disappears and the interests screen appears
1. …
> New Reader: fix Quick Start

- WordPress/Classes/Models/PostContentProvider.h
- WordPress/Classes/Models/ReaderPost.m
- WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCellConfiguration.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
- WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsCollectionViewFlowLayout.swift
- WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsStyleGuide.swift
- WordPress/Classes/ViewRelated/Reader/Tags View/DynamicHeightCollectionView.swift
- WordPress/Classes/ViewRelated/Reader/Tags View/ReaderTopicCollectionViewCoordinator.swift
- WordPress/Classes/ViewRelated/Reader/Tags View/TopicsCollectionView.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Main Issue #14570
| Collapsed | Expanded |
| :---: | :---: |
|<img src="https://user-images.githubusercontent.com/793774/90162908-31bcda00-dd4a-11ea-874c-8fcd4ba0448c.png" width="50%"/>| <img src="https://user-images.githubusercontent.com/793774/90162907-31244380-dd4a-11ea-9407-1a4952fb8111.png" width="50%"/> |
| Collapsed | Expanded |
| :---: | :---: |
|<img src="https://user-images.githubusercontent.com/793774/90163101-81030a80-dd4a-11ea-947a-b5a08680f091.png" width=""/>| <img src="https://user-images.githubusercontent.com/793774/90163119-86f8eb80-dd4a-11ea-9ff7-8406f70190ef.png" width=""/> |
1. Tap on the Reader tab
2. Tap on the Discover tab
1. Follow the steps from 01
2. Locate a post that has an expansion cell indicated by the 'X+' where X is the number of chips left to be displayed …
> Reader Improvements Phase 2: Adds a tags chips group to the top of the reader card cell

- Podfile
- Podfile.lock
Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/352
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/376
This updates Auth to show the updated Password and 2FA views in the SIWA path.
**Prerequisites:**
- Enable `unifiedApple` feature flag.
- A SIWA (Apple ID) account that:
- Has a WP password set.
- Has WP 2FA set.
- The WP account does not have SIWA connected. (https://wordpress.com/me/security/social-login)
<kbd><img width="500" alt="social_connections" src="https://user-images.githubusercontent.com/1816888/90189169-f1755000-dd79-11ea-85be-42a538db4937.png"></kbd>
**To test:**
- Select `Continue with Apple` from either Login or Signup.
- Finish Apple ID authentication.
- Verify the new Password view is displayed.
- Enter the WP …
> ULS: update Auth to show new Password and 2FA views in SIWA path

- WordPress/Classes/Services/ReaderTopicService.h
- WordPress/Classes/Services/ReaderTopicService.m
- WordPress/WordPressTest/ReaderTopicServiceTest.swift
Fixes #14387
- If a site is unfollowed from the browser, remove it from the app's followed site list
- Keep track of sites fetched from remote
- Compare them against sites fetched from CoreData
- If a site fetched from CoreData isn't in the the list of sites fetched from remote, mark that site as being unfollowed
1. Log into WordPress.com in a browser and go to your reader followed site list.
2. Select a site to unfollow.
3. Go to the reader in the app and click the gear icon to switch to "Followed Sites".
4. Pull down to refresh the list.
5. Check that the site unfollowed from the browser is removed from the app followed site list ✅
> Reader: fix unfollowed sites not being removed from list of followed sites

- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
- WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.h
- WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.m
- WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Fixes #14623
To test:
1. Navigate to the “Reader” tab
2. Tap on the comments button on a post
3. Check that a follow conversation button is displayed ✅ 
8. Check that the follow button matches [design specs](https://wpmobilep2.wordpress.com/2020/08/06/follow-conversations-design/) ✅ 
2. Check that by setting the `isSubscribedToPost` flag in code, the button is updated accordingly ✅ 
Follow conversation | Following conversation
--- | ---
> [Reader P2 follow conversations] add button in comments view

- WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
- WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
Fixes #14660
1. Run the app with the Reader Improvements Phase 2 flag enabled
2. Tap on the Reader tab
3. Tap on the Discover tab
3. Scroll down a few posts
4. Tap on a topic at the top of a post
5. Wait for it to load
6. Tap back
**Expectation:** The app displays the posts that were there before
> Reader Improvements: Fix Discover indefinite ghost mode

- Podfile
- Podfile.lock
- WordPress/Classes/Services/ReaderCardService.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
Fixes #14666
Related WordPressKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/271
1. Enable the Reader Improvements Phase 2 feature flag
2. Tap on the Reader tab
3. Tap on the Discover tab
4. Wait for the posts to load
5. Pull to refresh
6. You should see a new set of posts
7. Pull to refresh again
8. You'll see a new data set
> Reader Improvements Phase 2: Add random posts on pull to refresh support

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
- WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
Fixes #14592 
WPAuth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/383
Implements all remaining tracking for Google Sign In.
Since we're ditching `GoogleSignupConfirmationViewController.swift` soon, some of the tracking that's currently in there will be moved, but that's beyond the scope of this PR.
- Enabled the `unifiedGoogle` feature flag.
1. Either login or signup with Google.
2. When the dialog that requests permission to use google.com for signup comes up, tap "Cancel"
There will be more events, but these two are the important ones to check out near the end of your log:
🔵 Tracked: unified_login_failure <failure: The user canceled the sign-in flow., flow: google_login, source: default, step: start>
2020-08-17 18:11:18.168107-0300 WordPress[16173:5944979] …
> Completes Google tracking for UL&S

- Podfile
- Podfile.lock
- RELEASE-NOTES.txt
This PR incorporates the 1.33.2 release of gutenberg-mobile. The overview of the change can be seen from https://github.com/WordPress/gutenberg/pull/24569 which is a fix for this issue WordPress/gutenberg#24563 for Unsupported block editor not working on the Classic Block
Diff of gutenberg updates: https://github.com/WordPress/gutenberg/compare/rnmobile/1.33.1...rnmobile/1.33.2
Diff of gb-mobile updates: https://github.com/wordpress-mobile/gutenberg-mobile/compare/v1.33.1...release/1.33.2
> Integrate gutenberg release 1.33.2

- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
- WordPress/Classes/ViewRelated/Reader/Tags View/ReaderTopicCollectionViewCoordinator.swift
- WordPress/Classes/ViewRelated/Reader/Tags View/TopicsCollectionView.swift
Fixes #14681
To test:
1. Enable the Reader Improvements Phase 2 feature flag
2. Tap on the Reader tab
3. Tap on Discover
4. Reload until you see a post that has a lot of tags
5. Expand them
6. Pull top refresh the view
7. The cell should be collapsed and no longer show the 'hide' view
> Reset the isExpanded flag on reuse

- WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
when follow/ unfollow from post menu action
Fixes #13315 
To test:
1.Navigate to the “Reader” tab.
2.Tap “Followed Sites”.
3. Tap on site title
4. See site page
5. Follow / Unfollow the Site through the header and one of the posts repeatedly.
6. Wait a couple of seconds
7. See that the Follow / Following header button is updated 
8. See post actions are synced with following / unfollowing state 
> Fix site header is not updated when follow / unfollow from post actions

- WordPress/Classes/WordPress.xcdatamodeld/WordPress 97.xcdatamodel/contents
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 98.xcdatamodel/contents
This PR updates the minimum "Tools Version" used by our current Core Data model **WordPress 97.xcdatamodel** from Xcode 7.3 to 9.0.
This was the minimum change necessary to enable the (newish) Core Data attribute type, URI, which allows URLs to be modeled directly as `URL` instead of as `String`. Without this change, using URI produced an error:
Updating the version changes the underlying XML data model automatically as seen in the diff. These are the changes I see:
- `minimumToolsVersion="Xcode 7.3"` becomes `minimumToolsVersion="Xcode 9.0"`
- Changes related to indexing:
- Removal of `indexed="YES"` from model attributes
- addition of `<fetchIndex>`, [which is related to a new indexing API](https://stackoverflow.com/a/47852563/1305067)
This change doesn't involve a new Core Data model …
> Update Core Data model minimum tools version

- WordPress/Classes/Services/MediaService.m
Fixes #14680
(I'll cherry-pick the fix to `release/15.5` after this is merged)
**Make sure to test using a real device**
1. Go to My Sites and select an Atomic site
2. Go to Blog Posts to create a new post or edit an existing one and use the image block or gallery block.
3. Select Choose from my device. 
4. Choose a 'live photo' (HEIC) from your albums and add it
5. The image should upload
> Fix upload for HEIC files (live photos)

- Podfile
- Podfile.lock
- WordPress/WordPressUITests/Screens/Login/LoginSiteAddressScreen.swift
- WordPress/WordPressUITests/Screens/Login/LoginUsernamePasswordScreen.swift
Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/283
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/393
This updates the strings the UI tests use to validate Site Address views.
To test:
- Follow the "[Running tests](https://github.com/wordpress-mobile/WordPress-iOS/tree/develop/WordPress/WordPressUITests#running-tests)" steps. 
- Run the `LoginTests`. Verify they pass.
To note, local UI tests can be...persnickity. If the UI tests pass on this PR it should be good.
> ULS Site Address: fixing UI tests

- WordPress/Classes/ViewRelated/What's New/Dependency container/WPTabBarController+WhatIsNew.swift
- WordPress/Classes/ViewRelated/What's New/Views/WhatIsNewView.swift
Fixes #14718
To test:
- go to Me/App Settings/What's New in WordPress
- scroll the announcements and verify that the header and version scroll with them.
- Try different device sizes and orientations and make sure that view elements look right.
here are a couple of example screenshots
iPhone | iPad compact
--- | ---
**Note: I added a few more fake announcements to emphasize the scrolling. These will all go away once the real data come in.**
> What's New: header and version scroll with content
