WordPress/WordPressTest/ContextManagerTests.swift
=> Fix compiler error on tests: missing optional indicator.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
Closes #2665 (again).
/cc @sendhil (thanks!)
=> Prevents nuking replyTextView contents on dismiss

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m, WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
Fixes #2986
/cc @aerych (Thanks in advance!)
=> Resetting Badge on Logout

WordPress/Classes/Models/AbstractPost.h, WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/Models/BasePost.h, WordPress/Classes/Models/BasePost.m, WordPress/Classes/Models/Post.m, WordPress/Classes/Networking/PostServiceRemoteREST.m, WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/441).
/cc @bummytime
=> The post can't be saved now unless it has a title and content.

WordPress/Classes/ViewRelated/Post/PostsViewController.m
=> Changing 'Delete' text to 'Trash' for posts view.

WordPress/Classes/ViewRelated/Pages/WPLegacyEditPageViewController.m
Fix wordpress-mobile/WordPress-iOS-Editor#459
/cc @bummytime @sendhil
=> Use CreateDraftPage... instead of CreateDraftPost for pages.

WordPress/Classes/Models/Comment.m, WordPress/Classes/Models/WPCommentContentViewProvider.h, WordPress/Classes/ViewRelated/Reader/CommentContentView.m
=> Flag whether comment content is for a private site

Podfile, Podfile.lock, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/WordPressApi/WordPressComApiCredentials.h, WordPress/WordPressApi/WordPressComApiCredentials.m, WordPress/WordPressApi/gencredentials.rb
Was previously adding it in by hand as I wasn't sure if we'd keep it but that was a bit hacky and would result in difficulty  hunting down certain line #'s when looking at debug logs. We can remove it easily after the fact if we need to.
=> Adding New Relic to Internal Beta

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Fixes #2476
/cc @astralbodies (Thanks in advance Aaron!)
=> Prevents Manage button shift

WordPress/Classes/ViewRelated/Comments/CommentTableViewCell.xib, WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard, WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift
Closes #2791
The new "Unapproved" view looks like this:
/cc @roundhill  (Thanks in advance Dan!)
=> Notifications: Updates comment separators

WordPress/Classes/ViewRelated/Reader/CommentContentView.m, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes an issue where a cell would not reflect a liked state change if the cell included images.
Fixes #3013
=> Always configureCell.

Podfile, Podfile.lock
Closes #2999
(WOW this is effectively issue number 3k!!)
/cc @sendhil
=> Updates Simperium Podspec

WordPress/Classes/Models/WPAccount.m
=> Prevents nuking the dotcom account token

WordPress/Classes/Services/ReaderTopicService.m, WordPress/Classes/ViewRelated/Reader/ReaderPostsViewController.m, WordPress/Classes/ViewRelated/Reader/RecommendedTopicsViewController.m, WordPress/Classes/ViewRelated/Reader/SubscribedTopicsViewController.m, WordPress/WordPressTest/ContextManagerTests.swift, WordPress/WordPressTest/ReaderTopicServiceTest.m
=> Improves tag capitalization.

WordPress/Classes/Networking/ReaderTopicServiceRemote.m
=> Update tag sanitization to match core

WordPress/Classes/ViewRelated/Reader/ReaderPostsViewController.m
=> Reset previous featured image when loading new image.

WordPress/Classes/Models/Notifications/Notification.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
Closes #3053
/cc @aerych   (Thanks in advance!)
=> Notifications: Updates Assert Messages

WordPress/Classes/Services/BlogService.m
This is the same as #3031, but targeting the new branch.
Closes #3016
=> Work around for issues with basic http auth.

WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Closes #3056 
/cc @aerych (Thank you sir!)
=> Fixes autolayout error

WordPress/Classes/System/WordPressAppDelegate.m
=> Disabling new relic crash reporting

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/NotificationsManager.h, WordPress/Classes/Utility/NotificationsManager.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/ContextManagerTests.swift, WordPress/WordPressTest/NotificationsManager+TestHelper.h, WordPress/WordPressTest/NotificationsManager+TestHelper.m, WordPress/WordPressTest/SettingsViewControllerTest.m
Properly fixing #2476 
/cc @astralbodies (Thanks Aaron!)
=> Push Notifications: Properly refreshing the UI when needed

Podfile, Podfile.lock
=> Bumping Lookback.io version

WordPress/Classes/Utility/WPTableImageSource.h, WordPress/Classes/Utility/WPTableImageSource.m, WordPress/Classes/ViewRelated/Reader/ReaderPostDetailViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderPostsViewController.m, WordPress/Classes/ViewRelated/Views/WPRichTextView.m
=> Adds support for photon quality. Reader uses medium quality.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Closes #1433
/cc @aerych (Sir, you're a genius!)
=> Preserving Notifications TableView offset

WordPress/WordPress.xcodeproj/project.pbxproj
=> Updates provisioning profiles

Podfile.lock, WordPress/Classes/ViewRelated/Reader/ReaderPostContentView.h, WordPress/Classes/ViewRelated/Reader/ReaderPostContentView.m, WordPress/Classes/ViewRelated/Reader/ReaderPostDetailViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderPostsViewController.m, WordPress/Classes/ViewRelated/Views/WPContentActionView.h, WordPress/Classes/ViewRelated/Views/WPContentActionView.m
=> Hide action buttons if not logged in.

Scripts/run-oclint.sh
=> Allow to run OClint on a single file

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Ratings/AppRatingUtility.m
=> Removing unnecessary logging with regard to the app review throttle

WordPress/Classes/ViewRelated/System/WPTabBarController.m
Also, a minor code style change
Closes #3071
=> Returns the name of the me tab if its selected.

WordPress/UITests/CommentsTests.m, WordPress/UITests/LoginTests.m, WordPress/UITests/MeTabTests.m, WordPress/UITests/PagesTests.m, WordPress/UITests/PostsTests.m, WordPress/UITests/ReaderTests.m, WordPress/UITests/StatsTests.m, WordPress/UITests/WPUITestCase.m
Update UITests to make them run using the new navigation bar.
cc @bummytime , please review.
=> Upgrade tests for the new app navigation structure.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Closes #3090
@aerych may i bother you with a quick review?. Thanks!
=> NotificationsViewController: Renames dead method

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Closes #3092
Note: Please, merge #3091 first, since this pull request also includes that change, to prevent a merge conflict.
/cc @aerych
=> Reverts Sticky Scroll Position

Podfile, Podfile.lock
Closes #3125
/cc @diegoreymendez  (Thanks in advance!)
=> Updates Simperium and SocketRocket

WordPress/Resources/HTML/defaultPostTemplate.html
Fix for this issue https://github.com/wordpress-mobile/WordPress-iOS/issues/3123
/cc @bummytime can you review this?
=> Hide progress bars in review mode.

Scripts/run-oclint.sh
Fix oclint step in Travis when multiple files changed.
Improves logging message on log and GitHub integration.
cc @sendhil
=> OCLint improvements

.travis.yml, Scripts/build.sh
Same as https://github.com/wordpress-mobile/WordPress-iOS/pull/3151 but pointing to develop.
/cc @sendhil
=> Failing unit tests on travis

WordPress/Classes/ViewRelated/Reader/RecommendedTopicsViewController.m
=> Fix label for logged out reader

Podfile, Podfile.lock, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/WordPressApi/WordPressComApiCredentials.h, WordPress/WordPressApi/WordPressComApiCredentials.m, WordPress/WordPressApi/gencredentials.rb
Decided to drop New Relic from the build as we aren't going to use it and will stick with Crashlytics/Hockeyapp
cc @jleandroperez
=> Removing New Relic

WordPress/Classes/ViewRelated/Reader/ReaderPostsViewController.m
=> Do not save if we're still syncing.

WordPress/Classes/System/WordPressAppDelegate.m
=> Skipping Mixpanel init if no token present

WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Fix #3124 and https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/528
Pointing to 4.8
/cc @bummytime, can you please review.
=> Press stop on featured image uploading shows error

WordPress/Classes/ViewRelated/Pages/PageSettingsViewController.m
Fix this #3181
cc @bummytime, please review
=> Make page setting update featured image when removed from post.

Podfile, Podfile.lock
/cc @diegoreymendez may i bother you with a quick review?. 
Thanks!
=> Updates Simperium to Mark 0.7.8

WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #3220
@oguzkocer may i bother you with a violent review?.
Thank you sir!
=> Fixes WPTabBarController helpers

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fix for a regression on the upload progress status when a media failed.
cc @diegoreymendez or @bummytime please review.
=> Check for failed media on list on ongoing media progress.

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fix for https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/538
cc @bummytime or @diegoreymendez please review.
=> Editor 538 fix progress bar position

WordPress/Classes/ViewRelated/Me/MeHeaderView.m
This is a temporary fix to #3169. We'll be working on a better solution in #3216.
@jleandroperez May I bother you with a quick review? 
/cc @aerych
=> Don't add @ prefix before email in me page

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanelInstructionsForStat.h, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanelInstructionsForStat.m
cc @diegoreymendez , @meremagee
=> Tracking app version where user created account

WordPress/Classes/ViewRelated/Post/EditImageDetailsViewController.m
=> Assign default value to size.

WordPress/Classes/Services/BlogService.m
=> Fix bool pointer reference

WordPress/Classes/ViewRelated/Cells/WPProgressTableViewCell.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Fix this #3104 and this #3105
cc @aerych can you review?
=> Improve featured image progress cell

WordPress/Classes/ViewRelated/Comments/EditReplyViewController.m
Fixes #3102
@aerych may i bother you with a quick review?.
Thanks!
=> Updates Reply Title on iPad

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m
=> Adding tracking for login failures

WordPress/Classes/Networking/BlogServiceRemoteREST.m, WordPress/Classes/Services/BlogService.m, WordPress/WordPressTest/BlogServiceTest.m
Following suit for #3267 - cherry picked to release/4.8.
cc: @sendhil
=> Fix timezone in 4.8

WordPress/Resources/HTML/defaultPostTemplate.html
Fix for #3275. Set explicit word-wrap CSS property.
=> Issue/3275 Simple Preview Word Break

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
=> Remove unused media code in WPPostViewController

WordPress/Classes/ViewRelated/Views/WPRichTextEmbed.swift
=> Resets viewport after document is ready.

WordPress/Resources/WhatsNew/WPWhatsNewView.xib
=> Adding accessibility identifier to help with the screenshot tool

WordPress/WordPressTest/ReaderTopicServiceTest.m
=> Fix topic tests. Renames method. Sets missing attrs.

WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fix #3230 
cc @diegoreymendez, please review.
=> Clean up loops wp post view controller

WordPress/Classes/Models/Notifications/Notification.m
Closes #3294
@diegoreymendez may i bother you with a violent review?
(Thanks in advance!)
=> Updates Notification Range logic

WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPMediaProgressTableViewController.m
cc @aerych, can you please review?
=> Fix presentation for media progress indicator in legacy editor.

Podfile, Podfile.lock
=> Locked in Stats at 0.2.0 instead of a commit hash

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
@aerych may i bother with a super quick review?.
Thanks!
=> NotificationsViewController: Nukes redundant UINib property

WordPress/Classes/Networking/ReaderPostServiceRemote.m
Fixes #3325
/cc @aerych (Thank you sir!)
=> ReaderPostServiceRemote: Updates parsing logic

WordPress/Classes/ViewRelated/Post/EditImageDetailsViewController.m
=> Fix an issue with image size set to zero. Respects aspect ratio.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m, WordPress/Classes/ViewRelated/Reader/WPTableViewHandler.m
Fixes #3342
@aerych may i bother you (yet again) with a review?.
Thank you!!
=> Fixes Selected Row Glitch

WordPress/Classes/Categories/NSMutableDictionary+Helpers.m, WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/WPAccount.m, WordPress/Classes/Networking/PostServiceRemoteXMLRPC.m
Takes care of some of the oclint messages reported in [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/3340).
=> Cleaned up some code to reduce oclint warnings.

WordPress/Classes/ViewRelated/NUX/LoginViewController.m
=> Adjusting login errors to display Helpshift if available on first error instead of the second

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
=> Notifications: Implements SVProgressHUD

WordPress/Classes/ViewRelated/Reader/ReaderViewController.h, WordPress/Classes/ViewRelated/Reader/ReaderViewController.m, WordPress/Classes/ViewRelated/System/WPScrollableViewController.h, WordPress/Classes/ViewRelated/System/WPTabBarController.m, WordPress/WordPress.xcodeproj/project.pbxproj
=> Restores reader scoll to top when tapping tab.

WordPress/Classes/Services/AccountService.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.h, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
Original version https://github.com/wordpress-mobile/WordPress-iOS/pull/3314
Fixes #2984 
cc @oguzkocer, @astralbodies
=> Refactoring WPAnalyticsTrackerMixpanel's email update

WordPress/Classes/ViewRelated/Reader/ReaderPostsViewController.m
=> Fixes issue blocking multiple sites.

WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
Closes #3241 
/cc @aerych (Thank you!!)
=> Notifications: Updates Timestamp's Compression Resistance

Scripts/coverage.py
Just removed a debug line which was committed previously by mistake.
/cc @jleandroperez, @sendhil
=> Removed a debug line.

WordPress/Classes/Services/AccountService.m, WordPress/Classes/System/Constants.h, WordPress/Classes/System/Constants.m, WordPress/Classes/Utility/Migrations/10-11/BlogToAccount.m
=> Nukes Legacy UserDefaults

WordPress/Classes/Services/BlogService.h, WordPress/Classes/Services/BlogService.m
Strictly formatting changes. 
I purposefully left `Blog` related strings in there. Only created constants for inner-class-relevant strings. Also, didn't touch predicates.
=> Blog service formatting

WordPress/Classes/ViewRelated/Settings/NotificationSettingsViewController.m
This PR adds an extra TableView Footer into the `NotificationSettingsViewController` helper.
2. Log into a WordPress.com account
3. Tap over the Notifications TabBar button
4. Tap over `Manage` (Top right button)
5. Scroll all the way down
The user should see a label with the following format:
```
Network Last Seen: xxx [Status]
```
Closes #3212
@bummytime may i bother you with a quick review?. Thank you sir!
=> Notification Settings: Adds extra Debug Footer

.travis.yml, WordPress/WordPressTest/AppRatingUtilityTests.m
=> Make sure we install CocoaPods 0.35 and run pod install with it.

WordPress/Classes/Networking/MediaServiceRemoteXMLRPC.m
Fix for this: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/594
cc @bummytime, can you please review.
=> Add basic auth credentials to streaming requests when uploading images.

WordPress/Classes/System/WordPressAppDelegate.m
=> Fixes an assignment to a readonly property.

WordPress/Classes/ViewRelated/Cells/WPProgressTableViewCell.m
Fix for this https://github.com/wordpress-mobile/WordPress-iOS/issues/3305
cc @aerych can you please review.
=> Explicit report when progress is completed.

Podfile, Podfile.lock
cc @bummytime can you please review?
=> Integrate Editor-599 fix

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
cc @bummytime can you please review.
=> Extract common code in first insert and upload of media and retry media upload

WordPress/WordPressTest/WPAppAnalyticsTests.m
Small fix to my unit tests after what seems to be a bad merge.
=> Fixed two unit tests.

WordPress/Classes/ViewRelated/Post/PostsViewController.m, WordPress/Classes/ViewRelated/System/WPTableViewControllerSubclass.h
=> Don't autosync if uploading a post.

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
=> Updates Push Notification Event Name

WordPress/Classes/Services/AccountService.h, WordPress/Classes/Services/AccountService.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/ContextManager.h, WordPress/Classes/Utility/ContextManager.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/WordPressTest/AccountServiceTests.swift
Fixes #3401
/cc @astralbodies (Thanks in advance!)
=> Prevents Multiple Dotcom Accounts on Reauth

WordPress/Classes/ViewRelated/NUX/LoginViewController.m
Closes #3440
/cc @diegoreymendez  (Thanks in advance!)
=> Dismissing keyboard on 1P Login Lookup

WordPress/Classes/ViewRelated/Reader/CommentContentView.m
=> Fixes broken constraints on iOS 7

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Files/WPAppFilesManager.h, WordPress/Classes/Utility/Files/WPAppFilesManager.m, WordPress/WordPress.xcodeproj/project.pbxproj
Only moves some code from the app delegate into `WPAppFilesManager` class.
The logic should not be changed at all.
/cc @bummytime, @jleandroperez
=> Modularized the app delegate a bit more.

Podfile.lock, WordPress/Classes/ViewRelated/Settings/NotificationSettingsViewController.m
1. Fresh install WPiOS (on the device!)
2. Sign up for a new account
3. Open the Notifications tab
4. Hit the *Manage* button
As a result, the newly created blog should show up in the *Sites* section.
Fixes #3121
@aerych may i bother you with a quick review?.
Thank you sir!
=> Notification Settings: Fixes Empty Sites Section

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
@diegoreymendez mind taking a super quick look?. 
Thanks!
=> NotificationDetails: Adds a comment

Podfile.lock, WordPress/Classes/Models/Notifications/Notification.h, WordPress/Classes/Models/Notifications/Notification.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
@astralbodies may i bother you with a violent review?
=> Handling Follow Notification Range

WordPress/Classes/System/WordPressAppDelegate.m
Fixes a retain cycle in the app delegate and cleans up the code a bit.
=> Fixes a retain cycle. Cleans up the code a bit.

Podfile, Podfile.lock
Updating the editor pod to the official release version (0.6). 
/cc @sendhil
=> Updated to 0.6 editor pod

README.md
Added version information for Xcode and Cocoapods, and a link to the handbook.
Not trying to harp on the Swift 1.2 issue :wink:, really just trying to help out future developers with the problems I had getting the project built.
I'm not sure how to split the information between the Readme and the Handbook, but as I'm unable to contribute to the Handbook I put it here :)
=> Updating README.md #3532

WordPress/Classes/ViewRelated/Me/MeViewController.m
Current text: https://cloudup.com/c-LVuOenEg6
New text: https://cloudup.com/c2ADCVZvNbJ
=> Updates signout pop-up label to be more descriptive

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fix #3543 
cc @bummytime can you please review
=> Cache button items and only change nav bar if they are different.

Podfile, Podfile.lock
Email Checker's Master branch was deleted. This PR remaps the pod to develop. 
/cc @bummytime (Thanks for spotting this one!)
=> Fixes email checker dependency

Podfile, Podfile.lock, WordPress/Classes/Services/AccountServiceFacade.h, WordPress/Classes/Services/AccountServiceFacade.m, WordPress/Classes/Services/BlogSyncFacade.h, WordPress/Classes/Services/BlogSyncFacade.m, WordPress/Classes/Services/HelpshiftEnabledFacade.h, WordPress/Classes/Services/HelpshiftEnabledFacade.m, WordPress/Classes/Services/LoginFacade.h, WordPress/Classes/Services/LoginFacade.m, WordPress/Classes/Services/OnePasswordFacade.h, WordPress/Classes/Services/OnePasswordFacade.m, WordPress/Classes/Services/WordPressComOAuthClientFacade.h, WordPress/Classes/Services/WordPressComOAuthClientFacade.m, WordPress/Classes/Services/WordPressXMLRPCAPIFacade.h, WordPress/Classes/Services/WordPressXMLRPCAPIFacade.m, WordPress/Classes/Utility/ReachabilityFacade.h, WordPress/Classes/Utility/ReachabilityFacade.m, WordPress/Classes/ViewRelated/NUX/LoginFields.h, WordPress/Classes/ViewRelated/NUX/LoginFields.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.h, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewModel.h, WordPress/Classes/ViewRelated/NUX/LoginViewModel.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/LoginFacadeTests.m, WordPress/WordPressTest/LoginViewModelTests.m
https://github.com/wordpress-mobile/WordPress-iOS/pull/3512/files was getting messier and messier with merges and given almost all of the PR is via new files I thought it cleanest to re-create the PR.
=> Clean up the LoginViewController and make it more testable (re-do of https://github.com/wordpress-mobile/WordPress-iOS/pull/3512/files)

Podfile, Podfile.lock
=> Updating to AFNetworking 2.5.3

WordPress/Classes/Extensions/NSIndexPath+Swift.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift, WordPress/Classes/ViewRelated/Views/WPRichTextEmbed.swift
Fixes #3562
@sendhil may i bother you with a quick review?
=> Removes redundant NSString to String conversions

Podfile, Podfile.lock
Close #3588 
cc @bummytime can you please do a quick review?
=> Update Media Picker version.

WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m
Closes https://github.com/wordpress-mobile/WordPress-iOS/issues/3119
cc @aerych can you please review?
=> Configure fields to present Next and Done instead of Return.

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Fixes #3535 
Fixes a few more event names - merge #3570 first.
=> Fixes a few more event names for Tracks

WordPress/Classes/Extensions/UITableViewCell+Helpers.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift
/cc @aerych (thanks in advance!!)
=> Moves non-generic helpers to specific UITableViewCell subclass'ess

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Closes #3620 
Updated to latest Tracks library which fixes a crash when an event isn't found for whatever reason.
cc: @sendhil
=> Update to latest Tracks library

WordPress/Classes/System/WordPressAppDelegate.h, WordPress/Classes/Utility/Logging/WPLogger.h, WordPress/Classes/ViewRelated/Settings/ActivityLogViewController.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/3629).
How to test:
1. Run the app.
2. Go to Me / Help and check the logs are showing up.
=> Fixed an issue introduced in a previous PR.

WordPress/Classes/ViewRelated/Reader/CommentContentView.m
=> Fixes cropped descenders.

WordPress/Classes/ViewRelated/Comments/CommentViewController.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
=> Changes 'Give Up' text to 'Cancel'

WordPress/Classes/Models/Blog+Jetpack.m
Fixes #3141 
@aerych do you mind testing this one?
=> Only sync blogs for the default account

WordPress/Classes/ViewRelated/WhatsNew/WPWhatsNewView.m
=> Localize the accept button text.

WordPress/Classes/System/Constants.m, WordPress/Classes/Utility/Ratings/AppRatingUtility.m, WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewModel.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m, WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m, WordPress/Classes/ViewRelated/System/AboutViewController.m
I updated all the URLs to use HTTPS, except gravatars.
Fixes #3651
=> Update URLs to use HTTPS

WordPress/Classes/ViewRelated/Settings/SupportViewController.m
=> Improves explaination of extra debug feature.

Scripts/localize.py
Title has it.
cc @sendhil can you please review
=> Add mediapicker to localize script

WordPress/Classes/ViewRelated/NUX/WPNUXSecondaryButton.m
- https://github.com/wordpress-mobile/WordPress-iOS/issues/3665
=>  Fixes issue: "Add self hosted" gets truncated in Portuguese #3665

WordPress/Classes/ViewRelated/NUX/LoginViewController.m
Fixes #3664
@koke may i bother you with a super quick review?. 
Thanks sir!
=> LoginViewController: Increases SMS Label Maximum Number of Lines

WordPress/WordPress.xcodeproj/project.pbxproj
Translation files were there since #3377 but they were never added to
the Xcode project
Replaces #3666 
=> Added missing arabic translation

WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m
In #3635 we switched to a unique list for all the sites in the app.
Update the blog selector to match that
=> One list for the blog selector

WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
=> Fixes the default value specified when editing post status.

WordPress/Classes/ViewRelated/Blog/EditSiteViewController.m
=> Show settings instead of edit site.

WordPress/Classes/ViewRelated/Reader/WPImageViewController.m
Closes #3108 
How to test:
* Open post with feature image set.
* Edit post
* Open post settings
* Click on Featured Image
* See if a activity indicator shows up while the featured image is loading.
=> Show activity indicator while loading image.

WordPress/Classes/ViewRelated/Stats/StatsWebViewController.m
=> Fixes grammer, adds localization comments.

WordPress/Classes/ViewRelated/Blog/EditSiteViewController.m
using BlogDetailsViewController as a guide, created enums for section and row identifiers, created consts for section and row counts, for #3450
=> const cleanup for EditSiteViewController

WordPress/Classes/Extensions/Notifications/NotificationBlock+Interface.swift, WordPress/Classes/Models/Notifications/Notification.h, WordPress/Classes/Models/Notifications/Notification.m, WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
2. Log into your WordPress.com
3. Receive a Comment Notification, that includes an Automattcher (@yourhandle!)
4. Tap over the Notifications icon
5. Open the new Notification
As a result, the Handle should be highlighted in blue.
/cc @aerych  (Thank you!)
Closes #3447
=> Notifications: Automattcher Range Support

WordPress/Classes/WordPress.xcdatamodeld/WordPress 30.xcdatamodel/contents
=> Restores the slug property added in 29 but missing in 30

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewControllerSubclass.h, WordPress/Classes/ViewRelated/Post/PostListFooterView.xib, WordPress/Classes/ViewRelated/Post/PostListViewController.m
Adjusts height of footer for better alignment on post list.
Fixes color of divider.
Closes #3751 
=> Updates list footer appearance.

Podfile, Podfile.lock
This mainly includes internal updates as well as fixes to blockquote.
/cc @diegoreymendez
=> Update editor pod to latest

WordPress/Classes/Models/Notifications/Notification.h, WordPress/Classes/Models/Notifications/Notification.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
1. Receive +10 Like / +10 Followers Notifications
3. Open the Notifications tab
As a result, the notification should display a footer cell, with the legend `See all of your Followers` / `See all of your Likers`, as follows.
/cc @diegoreymendez (**sorry** about the duck typing :disappointed: )
Fixes #2593
=> Notifications: Styling Footer Cells

WordPress/WordPressApi/WordPressComApi.h, WordPress/WordPressApi/WordPressComApi.m
@aerych would it be okay if we nuke this code from WordPressComApi?.
Easiest PR ever!. Thanks in advance!
=> WordPressComApi: Nukes dead code

WordPress/Classes/ViewRelated/Pages/PageListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewControllerSubclass.h, WordPress/Classes/ViewRelated/Post/PostListViewController.m
Fixes #3819 
To test:
Use a blog that has *lots* of pages, enough so that you should need to load more a few times. 
Scroll to the bottom of the list and confirm that new pages are loading correctly. 
=> Restore syncing pages.

README.md
=> Update CocoaPods version requirement

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
=> Adds the new post list stats to the tracker. (oopsie)

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Just a quick follow up to tweak the stat names. 
=> Updates stat names to conform to naming conventions.

Scripts/build.sh
=> Use a 64bits simulator on Travis

WordPress/Classes/ViewRelated/Pages/PageListViewController.m
Closes #3889 
Steps to reproduce are included in the issue description.
=> Fixes the structure of the page lists fetch predicate.

WordPress/Classes/ViewRelated/Post/PostListViewController.m
Closes #3892 
To test:
Open the post list
Trash a post and let the undo cell appear. 
Change orientation.  The undo cell height should remain the same.
@kwonye would you mind having a look at this one?
Needs Review: @kwonye
=> Return restore cell height from correct method.

WordPress/Classes/ViewRelated/Post/PostListViewController.m
Closes #3899 
To test:
Open the post list and tap a post. 
The editor should be in preview mode. 
Return to the list and tap the Edit button in one of the post cards.
The editor should open in edit mode. 
=> Tapping post shows editor in preview mode.

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Resources/MainWindow.xib
=> Removes setFrame from AppDelegate and replaces old MainWindow.xib

WordPress/Classes/ViewRelated/Settings/SupportViewController.m
=> Remove disclosure indicators from Helpshift items

Podfile, Podfile.lock
Closes #3951
This updated version solves the bug referenced above.
=> Update media picker to latest version.

WordPress/Classes/Services/BlogService.m
I've been unable to directly trigger this crash. Nevertheless, let's try to prevent any Core Data threading issues (*OR* issues related to invalidated objects).
@astralbodies mind taking a look?
=> Implements NSObjectInaccessible Failsafe

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m, WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m
@aerych  can you have a quick look on this? it's just a redo of #4005. 
I wrongly merged develop on that PR so I needed to redo it.
=> 4003 app crashes on media add take 2

WordPress/Classes/Services/BlogService.m
I've just got an NSInvalidArgumentException. Screenshot below.
Reference: #4026 and #4017
=> Prevents NSInvalidArgumentException Crash

WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.m
We were using the Main Context in background threads. I've added a check, so that, when we're in BG, we simply use a Derived Context.
Fixes #4042
Needs Review: @aerych  (Thanks Eric!)
=> PrivateSiteURLProtocol: Fixes CoreData Threading Glitch

WordPress/WordPressTest/WPAvatarSourceTest.m
=> Increase timeout to avoid test failures on Travis.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
=> NotificationsViewController: Updates tracking behavior

WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/PhotonImageURLHelperTest.m
This fix a couple of tests that where broken because of a refactor that was made on the photon helper classes.
=> Refactor and fix test to use new photon helper class.

WordPress/Classes/Services/LoginFacade.m, WordPress/Classes/Services/ReaderTopicService.m, WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m, WordPress/Classes/ViewRelated/Comments/CommentViewController.m, WordPress/Classes/ViewRelated/Me/MeHeaderView.m, WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m, WordPress/Classes/ViewRelated/Reader/FollowedSitesViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderPostDetailViewController.m, WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m, WordPress/Classes/ViewRelated/WhatsNew/WPWhatsNewView.xib, WordPress/WordPressTest/LoginViewModelTests.m
With reference to ticket #1345, cleanup the unnecessary semicolons.
=> removes unnecessary semicolons.

WordPress/Classes/ViewRelated/Reader/OriginalAttributionView.m, WordPress/Classes/ViewRelated/Views/RichTextView/RichTextView.swift
Fixes #4166 
To Test:
Open a reader list
Scroll down a bit
Tap the status bar and confirm the view scrolls to the top. 
Needs review: @oguzkocer Would you mind a quick review?
=> Switch off scrollsToTop in nested UITextViews

WordPress/Classes/Networking/BlogServiceRemoteREST.m
Just re-submitting https://github.com/wordpress-mobile/WordPress-iOS/pull/4169 against `release/5.5`.
cc @aerych
=> Adds check before assigning nil value (Re-done)

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
How to test:
- Add a blog to the user account where it doesn't have admin rights ( only editor or writer rights)
- Open the blog details screen and check if configuration section is not visible.
- On a blog where the user has admin right check if the configuration section and the settings row is available.
=> Only shows the configuration section if the user has admin right on the blog

WordPress/Classes/Utility/WPError.m
=> Improves wording of the 'incompatible site' error message.

WordPress/WordPressApi/WordPressComApi.h, WordPress/WordPressApi/WordPressComApi.m
In sight of wrapping up a larger [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/4123), I made some atomic changes separately here.
No need to test, other than make sure the code builds and the unit tests don't fail.
=> Removed unused services.

WordPress/Classes/Networking/ReaderTopicServiceRemote.m, WordPress/Classes/Services/ReaderTopicService.m
2. Tap over the Reader tab
3. Trigger the Browse Site view
As a result, the site should be onscreen
Thanks for helping me out Eric!
=> Fixes ReaderTopicService URL's

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
1. Receive a New Follower notification
2. Tap over any of the Rows (or over the header)
As a result, the native Site Browser should be pushed.
Closes #4181
Needs Review: @aerych (Thanks Eric!!)
=> Notifications: Wiring Site Browser

WordPress/Classes/Services/NotificationsService.swift
2. Tap over the `Me` tab
3. Pick any of your sites
4. Tap over `Push Notifications`
5. Edit any of the settings
6. Hit back two times, so that the main `Me` tab is onscreen
7. Open again the Push Notifications Settings for the site you've picked in (3).
As a result, the settings you've updated should be onscreen.
=> NotificationsService: Updates remote data structure

WordPress/Classes/Networking/PushAuthenticationServiceRemote.swift, WordPress/Classes/Services/PushAuthenticationService.swift
Removes an unnecessary initializer.
=> Removed an unnecessary initializer.

WordPress/Classes/Categories/NSString+Helpers.h, WordPress/Classes/Categories/NSString+Helpers.m, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/WordPressTest/NSStringHelpersTest.m
=> Refactor word count algorithm to string helper category.

WordPress/Classes/Models/Blog.h, WordPress/Classes/Services/BlogService.m, WordPress/Classes/Services/BlogSyncFacade.m, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
How to test:
* Add a self-hosted site where you have admin rights
* Check the Blog->Blog Details->Settings is available
* Add a self-hosted site where you don't admin rights, just editor rights for example
* Check if the Blog->Blog Details->Settings is not available
=> Set the admin setting when options are available.

WordPress/WordPressTest/PostServiceRemoteRESTTests.m
=> Fix Create and Update Post tests by stubbing metadata.

Podfile, Podfile.lock
Fixes #4243 
Fixes the segmented control in the Insights sections for comments and followers.
=> Update to stats pod 0.4.7

WordPress/Classes/Models/Blog.m, WordPress/Classes/Networking/ReaderPostServiceRemote.m, WordPress/Classes/Utility/WPTableViewHandler.m, WordPress/Classes/Utility/WPVideoOptimizer.m, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m
Fix some warning detect by the new static analyser on Xcode 7.
How to test: Run the static analyser and see if all warning are gone. 
=> Fix static analyser warnings

.travis.yml, Scripts/build.sh, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/AccountServiceTests.swift, WordPress/WordPressTest/ContextManagerTests.swift, WordPress/WordPressTest/MockWordPressComApi.swift, WordPress/WordPressTest/NotificationsServiceTests.swift, WordPress/WordPressTest/PushAuthenticationServiceRemoteTests.swift, WordPress/WordPressTest/ReaderStreamViewControllerTests.swift, WordPress/WordPressTest/ReaderTopicServiceTest.swift, WordPress/WordPressTest/TestUtilities/JSONLoader.swift
=> Update travis configuration for xcode 7 and ios9

.gitignore
=> Ignore new xcode 7 auto generated file type.

WordPress/Classes/ViewRelated/Reader/ReaderPostDetailViewController.m
Closes #4292 
Fixes an issue with like icon not updating with changes on post detail. 
A second take on #4294 
Needs review : @jleandroperez
=> Updates like button when liked/unliked.

Podfile.lock, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.xib, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift, WordPress/Info.plist, WordPress/Launch Screen.storyboard, WordPress/WordPress-Internal-Info.plist, WordPress/WordPress.xcodeproj/project.pbxproj
1. Since (the whole app) isn't fully supporting Multitasking, please, set `UIRequiresFullScreen` to false in `Info.plist`
2. Launch the app on an iPad Air 2 (Simulator)
3. Open the Notifications tab, and open a Comment notification
4. Try rotating the device
5. Switch to Safari
6. Try "Slide Over". Attempt to rotate the device
7. Resize WPiOS's screen, so that it covers 50% of the screen
8. Try rotating again
Closes #4219
Needs Review: @aerych (Thanks Eric!)
=> Notifications: Adaptive Comments

Podfile.lock, WordPress/WordPress.xcodeproj/project.pbxproj
=> Updates Certificates

Podfile.lock, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Closes #4403. 
To test, 
- Follow the steps outlined in the issue and confirm that likes made in the detail are reflected in the list. 
- While on the list, pull to refresh and confirm the refresh happens normally, no jank, or glitching. 
Needs Review: @alexcurylo
=> Reader: Ensures changes saved in the detail show in the list.

Podfile.lock, WordPress/Classes/ViewRelated/Reader/ReaderSubscriptionViewController.m
Closes #4408 
I don't have steps to reproduce the crash but this should fix it. 
Needs Review: @kwonye
=> Reader: No need to set delegate to nil in dealloc.

Podfile, Podfile.lock, WordPress/Classes/Utility/Migrations/AccountToAccount22to23.swift, WordPress/Classes/Utility/PushAuthenticationManager.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingStreamsViewController.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift, WordPress/Classes/ViewRelated/Settings/AboutViewController.swift
Also fixing `WPAnalyticsStat` enum calls in Swift
=> Update Analytics pod to 0.39

Podfile, WordPress/Classes/Utility/NotificationsManager.m, WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift, WordPress/WordPress-Alpha.entitlements, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Alpha.xcscheme, WordPress/WordPressTodayWidget/Info-Alpha.plist, WordPress/WordPressTodayWidget/WordPressTodayWidget-Alpha.entitlements, WordPress/Wordpress-Alpha-Info.plist
This will be a build that'll contain nightly versions of `develop`
=> Add alpha build

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Title has it. Version 1.0 of the editor brings in the multitasking and format bar updates.
@sendhil would you mind reviewing?
=> Updated editor pod to v1.0

Podfile, Podfile.lock, WordPress/Classes/Extensions/UIImageView+Networking.swift, WordPress/Classes/Networking/NotificationsServiceRemote.swift, WordPress/Classes/Networking/PushAuthenticationServiceRemote.swift
=> Updates AFNetworking to Mark 2.6.3

WordPress/WordPress-Internal-Info.plist
=> Turns on multitasking for 5.8 internal build

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
=> Adding missing Analytics enums so we can build the internal beta

Podfile, Podfile.lock
Needs Review: @diegoreymendez (Thanks Diego!)
=> Updates Simperium to Mark 0.8.9

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Refs #4419 
Second attempt at patching this crash. 
=> Reader: Fix for #4419 take deux.

WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyBezierView.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockImageTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift
- Updated the way optional closures are called. (I'm not even sure why we used the `if let` pattern!)
- Added typealiases, when appropriate
- Minor style fixes
Needs Review: @aerych (Thanks in advance Eric!)
=> Notifications: Minor Swift Updates

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Log the errors that happen on media uploads.
=> Log errors on media uploads failures.

README.md
Adds GPLv2 license information to the README.
Resolves #2241.
=> Add license info to README

WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
=> Use SwitchTableViewCell for geotagging

WordPress/Classes/Models/BlogSettings+Discussion.swift, WordPress/Classes/Models/BlogSettings.swift, WordPress/Classes/Networking/Remote Objects/RemoteBlogSettings.swift, WordPress/Classes/Services/BlogService.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/BlogSettingsDiscussionTests.swift
In this PR we implement an Extension for the `BlogSettings` entity. It's goal is to provide a high level API, to be consumed by #4397.
This can be considered as an *Adapter*, Swift style.
Thank you Diego!
=> BlogSettings: Implements Discussion Extension

Podfile, Podfile.lock, WordPress/Classes/Extensions/Math.swift, WordPress/Classes/ViewRelated/Cells/MediaSizeSliderCell.swift, WordPress/Classes/ViewRelated/Cells/MediaSizeSliderCell.xib, WordPress/Classes/ViewRelated/Settings/SettingsViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/Extensions/MathTest.swift, WordPress/WordPressTest/ViewRelated/Cells/MediaSizeSliderCellTest.swift
I replaced all the custom cell wrangling with a new `MediaSizeSliderCell` and the existing `SwitchTableViewCell`.
I'm also hoping to extract ImmuTable from #4510 into a separate PR, so I needed to get all the custom cells ready.
Refs #4530 
~~Needs Review: @aerych~~
=> Refactor SettingsViewController using custom cells

WordPress/Classes/ViewRelated/Themes/ThemeBrowser.storyboard, WordPress/Classes/ViewRelated/Themes/ThemeBrowserCell.swift, WordPress/Classes/ViewRelated/Themes/ThemeBrowserHeaderView.swift
Closes #4574 
To test:
1) Attempt to trigger action button in multiple cells as demoed here(https://cloudup.com/cTNXcL3BcaQ) and ensure only touch in selected cell fires.
2) Attempt to trigger multiple buttons from the current+search bars in the browser header as well and trigger only the initially touched.
Needs Review: @kurzee
=> Fix multiple theme action triggering

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Changes Appearance to Personalize, Configuration to Configure, to match the labels used on the web. Fixes #4586.
=> Update subheadings in My Sites menu

WordPress/Classes/Utility/ImmuTable.swift
I forgot to actually handle the stored section header/footer text
=> Adds missing section header/footer text to ImmuTable

WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Just a small bit of clean up. 
Needs Review : @kurzee
=> Removes some obsolete TODOs.

Podfile, Podfile.lock
=> Updating Helpshift to 4.15.0.

WordPress/WordPress.xcodeproj/project.pbxproj
Aaron, may i bother you with a quick review?. Dev profile is broken (again!)
Thank you!
=> Updates Development Provisioning Profiles

WordPress/Classes/Networking/SharingServiceRemote.swift, WordPress/Classes/Services/SharingService.swift
Title has it. 
No real code changes, but for paranoia test by building / running the branch and confirm there are no errors. 
Needs review: @alexcurylo
=> Minor code style tweaks. Mostly whitespace.

WordPress/Classes/Utility/FeatureFlag.swift, WordPress/Classes/ViewRelated/MeViewController.swift, WordPress/WordPressTest/FeatureFlagTest.swift
=> Enable My Profile on App Store builds

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Closes #4802 
The crash occurs when the controller had a nil `readerTopic` and a user tries to refresh the list. The problem is when a topic is nil, the fetchRequest is also nil, resulting in the WPTableViewHandler's NSFetchResultsController also being nil and thus the crash is due to an unexpected nil when accessing an unwrapped optional.  
I need to make a stability pass over the reader looking for this sort of thing, but in the mean time we can avoid crashes of this type by ensuring the results controller is never nil by always returning a NSFetchRequest, and updating the predicate to avoid returning ReaderPosts that do not belong to a topic. 
To test:
- Open the reader's post list and choose a tag from the menu.
- Put your device in airplane mode. 
- Tap the header of a post card to …
=> Reader: Improves handling of nil topics.

WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m
Closes #4596 
Needs Review: @aerych do you mind review this? thanks in advance.
=> Update remove feature image button style and location.

WordPress/WordPress.xcodeproj/project.pbxproj
We had previously disabled this because at the time Helpshift didn't support it. Their current versions do so we should re-enable this.
=> Re-enabling Bitcode

WordPress/Classes/Extensions/CLPlacemark+Formatting.swift, WordPress/Classes/Utility/LocationService.h, WordPress/Classes/Utility/LocationService.m, WordPress/Classes/ViewRelated/Cells/PostGeolocationCell.m, WordPress/Classes/ViewRelated/Pages/PageSettingsViewController.m, WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationView.h, WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationView.m, WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController_Internal.h, WordPress/WordPress.xcodeproj/project.pbxproj
Closes #4808 
Adds the possibility for user to set a location by searching by name instead of using only the current location.
=> Allow users to search for location

WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
Fixes #4833 
To test:
Tag a post with a very long tag. 
Like the post
Open the reader to your likes feed and confirm that the buttons are not truncated, (but the tag can be).
=> Reader: Adjusts content compression and hugging for buttons.

WordPress/WordPress.xcodeproj/project.pbxproj
Closes #2723
Removed the distribution build configuration.
cc: @sendhil 
=> Removes the unused distribution configuration

WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #4913 
To test:
Repeat the steps outlined in the issue and confirm the UI is always responsive. 
=> Reader: Stay responsive while animating bars.

WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift
Fixes bad merge
Possibly a badly resolved conflict from #4905 and #4902
Cc: @diegoreymendez 
=> Pass active plan to controller helper

Podfile, Podfile.lock
Fixes #4864 
Fixes #4924
To test 1:
- Insert a media to upload
- Rotate the device while media is uploading
- Check if the media is not removed and upload finishes and the media progress bar is removed
To test 2:
- Insert a media to upload
- Click on the close button of the editor. When the editor warns about pending changes cancel the close
- Check if the media is not removed and upload finishes and the media progress bar is removed
=> Update editor to version 1.1.4

WordPress/Classes/Services/BlogService.h, WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift, WordPress/Classes/ViewRelated/Blog/DiscussionSettingsViewController.swift, WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift
=> Adds nullability annotations to BlogService

WordPress/Classes/Extensions/NSMutableData+Helpers.swift, WordPress/Classes/Networking/GravatarServiceRemote.swift, WordPress/Classes/Services/GravatarService.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/GravatarServiceTests.swift
In this PR we're implementing the service layer, for the upcoming `Update Gravatars™` iOS feature.
Although there is no direct way to test this one, we have a few Unit Tests that should cover (the very, very, very, very basics, mostly to make sure everything builds correctly).
Reference: #3492
Eric, may i bother you with a review?
=> Gravatar service layer

Podfile, Podfile.lock, WordPress/Classes/Services/BlogService.m, WordPress/Classes/Services/BlogSyncFacade.m, WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/Reader/CommentContentView.m, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift, WordPress/WordPress-Internal-Info.plist, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/System/3DTouch/WP3DTouchShortcutCreatorTests.swift
=> Merge 6.1 branch to develop

WordPress/Classes/Extensions/PHAsset+Exporters.swift, WordPress/Classes/Extensions/UIImage+Exporters.swift, WordPress/Classes/Models/Blog.m, WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift
=> Merge 6.1 to develop

WordPress/Classes/Utility/WPWebViewController.m
WordPress CDN (`.files.wordpress.com`) doesn't deal with authentication. In this (small) PR we're patching (hacking) the Auth URL.
**Note:** (Just for the record) I've got a working branch to switch over to `WKWebView`, which would have *vastly* improved the code quality in WPWebViewController. However... `WKWebView` appears to ignore the `NSURLRequest` **HTTPBody**. Isn't that so great?
1. I've hacked [this spot](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Stats/StatsViewController.m#L159), and added the following snippet, for the sake of ease of testing.
```
url = [NSURL URLWithString:@"https://astralbodiesnet.files.wordpress.com/2014/02/2014-02-10_12-44-50.png"];
```
2. Launch WPiOS and log into your account
3. Open any blog's Stats, and …
=> WPWebViewController: Fixing WordPress CDN auth

WordPress/Classes/ViewRelated/Post/PostCardActionBar.h, WordPress/Classes/ViewRelated/Post/PostCardActionBar.m, WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
Fixes #4999 
To test: Repeat the steps outlined in the issue and confirm the action buttons are properly reset.
Needs review: @SergioEstevao would you do the honors?
=> Post List: Reset action buttons when cell is configured.

WordPress/Classes/Models/Post.m, WordPress/Classes/Services/PostService.h, WordPress/Classes/Services/PostService.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m, WordPress/Classes/ViewRelated/Post/PostListViewController.m, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Follow up to another PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/4952
Please review the discussion there.  This new PR is aimed at `release/6.1`.
=> Issue/4904 offline changes lost 6.1

WordPress/WordPress.xcodeproj/project.pbxproj
=> Fixes code signing & deployment target on share extension

WordPress/Classes/ViewRelated/Blog/SharingAuthorizationWebViewController.m
Fixes #5024 
To test: 
Connect to any of the available services. 
Try to connect a second time to the same service. 
Confirm that you have to enter credentials for the service and are not already signed in. 
Needs review: @jleandroperez would you do the honors sir?
=> Sharing: Removes cookies set by third-party service.

WordPress/Info-Alpha.plist, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressShareExtension/Info-Internal.plist
Fixes #5045 
To test:
Build and Archive the internal beta.
=> Creates a separate bundle ID and Info.plist for share extension configs

WordPress/Classes/Models/BasePost.m
Removes an unused method.
To test: just build the app and make sure there aren't any errors.
=> Removes an unused post.

Podfile, Podfile.lock
Just keeping the lib updated to the latest.(!)
=> Updates Simperium to Mark 0.8.15

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Removes two unnecessary optionals and cleans the code up a bit.
To test:
- Using the device (the simulator has limited functionality on sharing), share a post from the reader.
- Make sure it works.
=> Removes two unnecessary optionals.

WordPress/Classes/Services/PostService.h, WordPress/WordPress.xcodeproj/project.pbxproj
Removes a compilation warning (also fixes the provisioning profiles).
To test:
- Just build and make sure it succeeds.
=> Removes a compilation warning (also fixes the prov. profiles).

Podfile, Podfile.lock
Fixes #5072 
To test:
Build, run, make sure stats works properly. Functionality was tested in the pod repo.
Note: After this is merged, lets do a TestFlight build to be sure it validates properly with Apple.
=> Update to stats pod 0.6.5

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #5043
To test:
- Find a device with low disk space available
- Try to export a large video to make the disk limit to be hit
- Check if an error message is displayed properly and no crash happens
Needs review: @astralbodies @rachelmcr
=> Show message upon upload when device is low on disk space

Podfile
=> Integrates WPiOS Editor v1.4.

WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #5164 
To test:
1. Create an internal build.
2. Use the share extension.
=> Updates share extension build to provide WPCOM_PREFIX

Scripts/build.sh, circle.yml
=> Remove CircleCI support

WordPress/Classes/ViewRelated/Tools/PromptViewController.swift
Sendhil, may i trouble you with a quick review?
Thank you!
=> PromptViewController: Renames Methods

WordPress/Classes/Services/ReaderSiteService.m
Tracks hates uppercase characters.
Fixes a few issues properly tracking follows/unfollows and blocking sites in the reader.
=> Reader: Fixes property casing for tracks analytics.

MIGRATIONS.md, WordPress/Classes/Models/Blog+Capabilities.swift, WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/BlogSettings+Discussion.swift, WordPress/Classes/Networking/AccountServiceRemoteREST.m, WordPress/Classes/Networking/Remote Objects/RemoteBlog.h, WordPress/Classes/Services/BlogService.m, WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion, WordPress/Classes/WordPress.xcdatamodeld/WordPress 49.xcdatamodel/contents, WordPress/WordPress.xcodeproj/project.pbxproj
This is required by #5175. We need to track a Blog's Capabilities, in order to Enable / Disable the UI accordingly.
We're simply adding a `Capabilities` field to the Blog Entity (Transformable).
cc @bummytime
=> Adding Blog capabilities

WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift
Fixes #5234
I'm afraid we don't really have repro steps for this crash. Nevertheless, let's add `guard`'s so that nothing too obvious goes wrong.
Needs review: @sendhil 
Thanks sir!
=> ReplyTextView: So long, IUO!

WordPress/Classes/Extensions/NSFetchedResultsController+Helpers.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+RowActions.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #5255
No specific repro steps on this one. Please, open the Notifications tab, swipe over random notifications, and make sure the Actions still show up.
Needs review: @sendhil 
=> Out of Bounds Failsafe

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Cells/WPBlogTableViewCell.h, WordPress/Classes/ViewRelated/Cells/WPBlogTableViewCell.m
Pulling #5196 over to `release/6.2`.
Needs Review: @jleandroperez 
Thanks Jorge!
=> Issue/5195 – visibility fix targeting release/6.2

WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.m
Refs #5245
To test:
- Access sites that are marked private on WP.com
- Check the Post List, Pages, List, and Editor view and check if images are loaded correctly.
- Check on the reader if images are loaded for private sites.
Needs review: @aerych, do you mind have a look on this?
=> Replace NSURLConnection from NSURLSession on the PrivateSiteURLProtocol

WordPress/Classes/ViewRelated/Pages/PageListViewController.swift, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- Renames `postListViewController` to `tableViewController` since that's what it truly is.
- Turns a few properties into computed properties since they don't really need to be stored locally.
To test:
1. Launch the app.
2. Go to the list of posts / pages for a blog
3. Make sure the table view works right.
4. Make sure pull-down-to-refresh works right.
=> Improves the UITableViewController-related code in AbstractPostListVC.

Podfile, Podfile.lock
=> Updates the Shared pod to v0.5.7

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/KeychainTools.swift, WordPress/WordPress.xcodeproj/project.pbxproj
We don't know why items disappear from the keychain, but with this PR we can at least simulate it so we handle that state properly.
To test: Edit the scheme and add a WipeKeychainItem argument
=> Adds launch argument to remove keychain items

.travis.yml, Gemfile
Let's see if this works
https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone
If the travis build is green and the [caches](https://travis-ci.org/wordpress-mobile/WordPress-iOS/caches) are properly generated, this should be enough.
=> Adds caching of pods and gems for Travis

WordPress/Classes/Utility/FeatureFlag.swift
Closes #5290 
To test:
1. Build & run. Archive if you feel like being super complete.
2. Verify My Profile, Account Settings and App Settings all function.
=> Enables the /me features like My Profile, Account Settings.

WordPress/Classes/Models/ManagedAccountSettings+CoreDataProperties.swift, WordPress/Classes/Models/ManagedAccountSettings.swift, WordPress/Classes/Models/ManagedPerson+CoreDataProperties.swift, WordPress/Classes/Models/ManagedPerson.swift, WordPress/Classes/Models/Person.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Closes #5307
To test:
Please, build the app, and make sure nothing breaks. This PR only shuffles code around.
=> Splitting Person and ManagedPerson

WordPress/Classes/Extensions/Notifications/Notification+Interface.swift, WordPress/Classes/Networking/PeopleRemote.swift, WordPress/Classes/Services/PeopleService.swift, WordPress/Classes/ViewRelated/People/PeopleCell.swift, WordPress/Classes/ViewRelated/People/PeopleCellViewModel.swift, WordPress/Classes/ViewRelated/People/PeopleViewController.swift, WordPress/Classes/ViewRelated/People/PersonViewController.swift, WordPress/Classes/ViewRelated/People/RoleViewController.swift
**My bad**: After merging few pending PR's, and setting up Swift Lint, i've realized i've introduced ~110 new lint warnings.
This PR fixes them all, sorry about that!
=> Fixing Swift Lint Warnings

WordPress/Classes/ViewRelated/Me/MyProfileViewController.swift, WordPress/Classes/ViewRelated/Me/SettingsCommon.swift
Fixes #4860 
To test: 
- Go the Me -> My Profile
- Select the About Me row,
- Check if the field is multi row, and if changes are properly saved. 
=> Use a multiline field for the about me section.

WordPress/Classes/ViewRelated/NUX/SigninLinkRequestViewController.swift
=> Fixed a small typo in SigninLinkRequestViewController

WordPress/Classes/Services/BlogService.h, WordPress/Classes/Services/BlogService.m, WordPress/WordPressTest/BlogJetpackTest.m, WordPress/WordPressTest/Extensions/StringExtensionsTests.swift
To test:
Run the test suite, make sure there are no warnings
=> Fix test warnings

Podfile, Podfile.lock
To test:
- Build and Run tests for a real device
=> Update libraries in order to allow tests to be build for device.

WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
Just a quick clean up of the ReaderHelper class's documentation style. 
Needs review: @jleandroperez could I trouble you for a review?
=> Reader: Updates documentation style.

WordPress/Classes/Networking/ThemeServiceRemote.h, WordPress/Classes/Networking/ThemeServiceRemote.m, WordPress/Classes/Services/ThemeService.m, WordPress/WordPressTest/ThemeServiceRemoteTests.m, WordPress/WordPressTest/ThemeServiceTests.m
Refs #5245 
To test:
- Login in the app using a wp.com account
- Go to the theme section, and test the following:
- List the themes
- Activate a theme
- Search theme
Check if all is working has before.
=> Convert the theme service to use WordPressComRestAPI.

WordPress/Classes/Networking/JetpackServiceRemote.m
Refs #5245 
To test:
- Login in the app with a self-hosted blog
- Access the stats and try to connect using jetpack
- Enter credentials.
- Check if everything went correct.
=> Refactor JetpackService to use AFHTTPSessionManager.

WordPress/Classes/ViewRelated/Menus/Menu+ViewDesign.h, WordPress/Classes/ViewRelated/Menus/MenuItem+ViewDesign.h, WordPress/Classes/ViewRelated/Menus/MenuItemAbstractPostsViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemCategoriesViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemCheckButtonView.h, WordPress/Classes/ViewRelated/Menus/MenuItemEditingFooterView.h, WordPress/Classes/ViewRelated/Menus/MenuItemEditingHeaderView.h, WordPress/Classes/ViewRelated/Menus/MenuItemEditingViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemLinkViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemPagesViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemPostsViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemSourceCell.h, WordPress/Classes/ViewRelated/Menus/MenuItemSourceFooterView.h, WordPress/Classes/ViewRelated/Menus/MenuItemSourceHeaderView.h, WordPress/Classes/ViewRelated/Menus/MenuItemSourceResultsViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemSourceResultsViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceTextBar.h, WordPress/Classes/ViewRelated/Menus/MenuItemSourceViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemTagsViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemTypeSelectionView.h, WordPress/Classes/ViewRelated/Menus/MenuItemTypeViewController.h, WordPress/Classes/ViewRelated/Menus/MenusSelectionDetailView.h, WordPress/Classes/ViewRelated/Menus/MenusSelectionItem.h, WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.h, WordPress/Classes/ViewRelated/Menus/MenusSelectionView.h
Adding nullability specification to already merged Menus headers. Best to go ahead and do this now as I'm the original author and am almost wrapped up with merging.
To test:
- Build the branch, ensure no warnings or build errors show up due to nullability.
Needs review: @diegoreymendez can you take a quick look? 🕵
=> Menus: Nullability Specification.

WordPress/Classes/Networking/BlogServiceRemoteREST.h, WordPress/Classes/Networking/BlogServiceRemoteREST.m, WordPress/Classes/Services/BlogService.m, WordPress/WordPressTest/BlogServiceRemoteRESTTests.m
Refs #5245 
To test:
- Login in the app using a WP.com account.
- Test if blog setting are showing up correctly and are able to edit them
=> Migrate BlogService to use WordPressComRestApi class.

WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Simplified and unified some code in `PageListViewController`.
This unifies the code in synch with [this upcoming PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/5400).
The idea is to simplify and streamline the code in both VCs in order to try and find code that can be modularized into components that both VCs can use.
1. Run the app
2. Go to the list of pages for a blog
3. Perform these actions on pages: create, edit, view, view stats, trash, restore.
4. Pull down to refresh too.
=> Simplified and unified some code in PageListViewController.

WordPress/Classes/Networking/PostServiceRemoteREST.h, WordPress/Classes/Networking/PostServiceRemoteREST.m, WordPress/Classes/Services/PostService.m, WordPress/WordPressTest/PostServiceRemoteRESTTests.m
Refs #5245 
To test:
- Login in the app using a WP.com account
- Go to Blog -> Posts and Blog-Pages and do all the actions:
- List 
- Select
- Delete
- Restore
- Create a new post/page
=> Migrate post service to nsurlsession.

WordPress/Classes/ViewRelated/Menus/MenuHeaderViewController.h, WordPress/Classes/ViewRelated/Menus/MenuHeaderViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceTextBar.m, WordPress/Classes/ViewRelated/Menus/MenusSelectionDetailView.m, WordPress/Classes/ViewRelated/Menus/MenusSelectionView.m, WordPress/WordPress.xcodeproj/project.pbxproj
This PR adds a few cleanup changes made to Menus over the last few PRs. Merging these now to keep the final PR a bit cleaner for review.
Needs review: @diegoreymendez, can you take a quick look for me? Tagging you as you actually reviewed these classes originally.
=> Menus: Cleanup before completing Menus merge

WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Fixes #5399.
To test:
1. Compile the code and make sure it works fine.
2. Run the app, go to the list of posts and play around with it.
3. Create posts, edit posts, view posts, view stats for posts, trash posts, restore posts.
4. Make sure to try searching and selecting different filters.
=> Remove some redundancy in PostListViewController

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
Adds the analytics values for Menus.
To Test: Build without warnings/errors.
Needs review: @jleandroperez can you take a quick peak for me? 🔪
=> Menus: Analytics Additions

Scripts/build.sh
Hotfix for release/6.3, this script is going away in develop
=> Use bundled xcpretty-travis-formatter

WordPress/Classes/Networking/AccountServiceRemoteREST.m, WordPress/Classes/Networking/BlogServiceRemoteREST.m, WordPress/Classes/Networking/MediaServiceRemoteREST.m, WordPress/Classes/Networking/ReaderTopicServiceRemote.m, WordPress/Classes/Networking/TaxonomyServiceRemoteREST.m
=> Use correct enums for api version

Rakefile
Fixes #5443 
To test: rake should work without having bundler installed
=> Install bundler locally if not present in system

WordPress/WordPressTest/PostTests.swift
Title has it
To test: just run the unit tests and evaluate the code.
=> Adds more test for Post.

WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m
Fixes #5478 
To test:
- Set your device on Airplane Mode or without an internet connection
- Go to Me > Account Settings
- All fields should be empty
- Tap on Primary Blog
- Blog selector should appear without crashing
=> Fix crash on blog selector with no selected blog

WordPress/Classes/Networking/PeopleRemote.swift, WordPress/Classes/Services/PeopleService.swift, WordPress/Classes/ViewRelated/People/PeopleViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/PeopleRemoteTests.swift, WordPress/WordPressTest/Test Data/people-send-invitation-failure.json, WordPress/WordPressTest/Test Data/people-send-invitation-success.json, WordPress/WordPressTest/Test Data/people-validate-invitation-failure.json, WordPress/WordPressTest/Test Data/people-validate-invitation-success.json
This PR implements the Service Layer required to send invitations to a blog. To test, please, run the unit tests.
Ref. #5381
Thanks in advance Diego!
=> People Management: Invitations Service Layer

WordPress/Classes/Categories/UIApplication+Helpers.h, WordPress/Classes/Categories/UIApplication+Helpers.m, WordPress/Classes/Utility/InteractiveNotificationsHandler.swift, WordPress/Classes/Utility/PushNotificationsManager.swift
=> Replace isAlphaBuild with existing build helper

WordPress/Classes/Networking/AccountSettingsRemote.swift, WordPress/Classes/Services/AccountSettingsService.swift, WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift, WordPress/Classes/ViewRelated/Me/MyProfileViewController.swift, WordPress/WordPressApi/WordPressComRestApi.swift
Refs #5245 
To test: 
- Login with a WP.com account
- Go to Me->Account Settings
- Change some of the values and see if they update correctly.
=> Migrate account settings to WordPressComRestAPI

WordPress/WordPressApi/WordPressComRestApi.swift
Fixes two retain cycles caused by circular strong references.
=> Fixes two retain cycles.

WordPress/Classes/Services/ThemeService.h
Retargetting [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/5513) to `release/6.3`, as requested by @SergioEstevao.
=> Fixed some return values.

WordPress/WordPressTest/ReaderPostServiceRemoteTests.m, WordPress/WordPressTest/ReaderPostServiceTest.m
To test:
- Run unit tests and see if ReaderPostServiceRemoteTests.m all pass.
=> Compare objects not pointers.

WordPress/WordPressTest/MenusServiceTests.m
To test:
- Run unit tests,
- See if they pass ok.
=> Fix Menu Service Tests

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
We hope this will aid in fixing #5561, but these are good assertions to have even if they prove unrelated to it.
To test:
- Just compile the code and make sure it works.
- Also run the app and create a new post, make sure the assertion doesn't fail.
- Discard changes and make sure the assertion doesn't fail.
=> Adds 2 assertions to avoid unwanted scenarios.

WordPress/Classes/Utility/OptimizelyHelper.swift
If the user is already signed in start Optimizely asynchronously.
To test:
Add break points in the new conditional.
Launch the app while signed in and confirm Optimizely is loaded async. 
Launch the app while signed out and confirm Optimizely is loaded sync. 
=> Optimizely: Start async if the user is already signed in.

WordPress/Classes/Networking/ReaderSiteServiceRemote.m
Refs #5245 
To test:
- Check Reader Sites functionality.
=> Fix block signature.

Podfile, Podfile.lock
Refs #5245 
To test:
- Test if the stats section ares working properly
- Test if the today widget is working properly.
=> Update stats repo to latest version.

WordPress/Classes/Utility/Ratings/AppRatingUtility.m
Refs #5245 
To test:
- Launch the app in a mode that forces an AppRatingUtilityCheck
- Check if all code works properly.
=> Migrate AppRatingUtility from AFHTTPRequestOperation to NSURLSession.

WordPress/Classes/Networking/ReaderSiteServiceRemote.m, WordPress/WordPress-Internal-Info.plist
=> Merge 6.3 on develop

WordPress/WordPressApi/WordPressComRestApi.swift
Remove unnecessary log message.
=> Remove unnecessary log message.

Podfile, Podfile.lock
Updates the editor pod to version 1.7.1
To test:
- Check if keyboard shortcuts are showing correctly in the app
- Check if the editor is working correctly
=> Updates the editor pod to version 1.7.1

Gemfile.lock, Podfile, Podfile.lock, WordPress/Classes/Services/ShareExtensionService.swift, WordPress/Classes/System/Constants.h, WordPress/Classes/System/Constants.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift, WordPress/WordPressShareExtension/MediaView.swift, WordPress/WordPressShareExtension/ShareViewController.swift, WordPress/WordPressShareExtension/UIImage+Extensions.swift
Fixes #5653
To test:
1. Attempt posting pictures from Photos.app / PIgment.app
2. Verify that posting from Safari didn't break.
Thanks in advance Aaron!!
=> Share Extension: Session Invalidation

WordPress/Classes/Utility/FeatureFlag.swift
=> Beta + Internal: Enables People Management Feature

WordPress/Classes/ViewRelated/Reader/ManageCellAccessoryView.xib, WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
Fixes #5659
To test: Repeat the steps described in the issue and confirm that the Follow Sites cell is correctly rendered.
=> Reader: Fixes a breaking constraint and layout issue when multitasking.

WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderMenuViewModel.swift
Refs #4094 
Refs [design feedback here](https://github.com/wordpress-mobile/WordPress-iOS/pull/5600#issuecomment-230940836).
To test:
Confirm that the add tags button shows the correct "plus" icon.
Confirm that swipe to delete shows a "Remove" button.
Confirm that a newly added tag is scrolled to be visible.
=> Reader: Implements feedback from design review.

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
So #5714 accidentally removed the Add Site button from BlogListViewController. This VC restores it.
It also restores functionality to hide search if there are only a couple of sites in the list.
=> Restores Add Site button to BlogListViewController

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Extensions.swift, WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyBezierView.swift, WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift, WordPress/Classes/ViewRelated/Notifications/Tools/NotificationMediaDownloader.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockImageTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTextTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockUserTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteUndoOverlayView.swift
In this PR i'm addressing a little bit of a technical debt, within the Notifications code. No new functionality has been added:
- Normalized spacing here and there
- Implemented `guard else` when needed
- Removed a TODO from february 2015 (yay!)
Sir, may i bother you with a swifty review?
Thanks! yay!!
=> Notifications: Swift Improvements

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
This PR updates the analytics related to the reader search feature.
To test:
Set break points where the analytics are bumped. Confirm that the calls are correctly made and there are no warnings/crashes.
Needs review: @sendhil would you mind taking this one?
=> Reader: Updates search analytics.

Podfile, Podfile.lock
Fixes https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/839.
To test:
- Replicate the steps in [this video]() and make sure the weird behavior is gone.
Needs review: @sendhil, @SergioEstevao
=> Updates the editor pod to v1.8

WordPress/WordPressTest/NotificationTests.m
Please, just run the unit tests, and verify nothing breaks now.
Nate, may i bother you with a quick review?. Thanks for spotting this!!
=> Notifictions: Fixing broken Unit Test

Podfile, Podfile.lock
=> Bumping Helpshift to 5.6.2.

WordPress/Classes/Utility/FeatureFlag.swift, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/Me/MeViewController.swift
Fixes #5317 
To test:
1. Compile the app?
I also put a placeholder feature in for an example for us in the future when we need to use this again.
=> Removes all feature flags no longer in use.

WordPress/Classes/ViewRelated/Plans/PlanDetailViewModel.swift, WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift
Fixes #5758 
To test:
Turn on Airplane mode and verify it shows the new error message
@frosty I am fully aware this may not be the best way to fix this issue. If so, please let me know what the better way is 👍
=> Fix offline text

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Fixes trailing whitespace violation 👮 
Needs review: @aerych 👀
=> Reader: Trim whitespace, lol.

WordPress/Classes/ViewRelated/Menus/MenuDetailsViewController.m, WordPress/Classes/ViewRelated/Menus/MenuHeaderViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItem+ViewDesign.m, WordPress/Classes/ViewRelated/Menus/MenuItemAbstractPostsViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemAbstractView.h, WordPress/Classes/ViewRelated/Menus/MenuItemAbstractView.m, WordPress/Classes/ViewRelated/Menus/MenuItemCategoriesViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemCheckButtonView.m, WordPress/Classes/ViewRelated/Menus/MenuItemEditingFooterView.m, WordPress/Classes/ViewRelated/Menus/MenuItemEditingHeaderView.m, WordPress/Classes/ViewRelated/Menus/MenuItemEditingViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemInsertionView.m, WordPress/Classes/ViewRelated/Menus/MenuItemLinkViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceCell.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceFooterView.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceHeaderView.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceResultsViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceTextBar.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemTagsViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemTypeSelectionView.m, WordPress/Classes/ViewRelated/Menus/MenuItemTypeViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemView.m, WordPress/Classes/ViewRelated/Menus/MenuItemsViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemsVisualOrderingView.m, WordPress/Classes/ViewRelated/Menus/MenusSelectionDetailView.h, WordPress/Classes/ViewRelated/Menus/MenusSelectionDetailView.m, WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.m, WordPress/Classes/ViewRelated/Menus/MenusSelectionView.m, WordPress/Classes/ViewRelated/Menus/MenusViewController.m
While developing Menus a while back, I did not have Xcode enabled for trimming whitespace.... Sooo now I've trimmed the whitespace. 😅 
Also, not entirely sure why our linter didn't catch this on its own....
To test:
- Just needs a build to ensure no compile issues.
Needs review: @aerych can I bother you for a cleanup PR? 🙏
=> Menus: Clean up white space formatting.

WordPress/Classes/Networking/ReaderPostServiceRemote.m
Closes #5878 
This is more of a band-aid for #5878.  The regex in `stringByReplacingHTMLEmoticonsWithEmoji` is *very* taxing on the CPU for posts with lots and lots of images (the referenced post had ~100).  Some more performant parsing would be grand but the work should probably be done in the background regardless... hence this patch. 
To test:
Try loading the post referenced in the issue via the reader's liked feed.  Ensure that the UI does *not* block.  Note that it may take some time before you see the new content appear. 
Needs review: @kurzee, how about one more?
=> Reader: Moves results parsing/formatting onto a background thread.

Podfile, Podfile.lock
Please, just perform a fresh install, and verify that your dotcom account gets all of the latest notifications.
Needs Review: @sendhil 
=> Updating Simperium to Mark 0.8.17

Podfile, Podfile.lock
To test:
- Add an image to a post
- While the upload is going turn of the network
- Check if the an error overlay shows on top of the image with icon and error message. 
=> Update editor version to 1.8.1

WordPress/Classes/Extensions/PHAsset+Exporters.swift, WordPress/Classes/Extensions/UIImage+Exporters.swift, WordPress/Classes/Services/MediaService.m
Refs #2752
To test:
- Add an animate GIF to your cameral roll
- Start a new post 
- Tap on the add media button
- Select the animated GIF from the camera roll
- Check if after the upload is done the animated GIF is working properly.
- Post the post.
=> If image are GIFs export the original data of the GIF 

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
This PR converts (part of the) Notifications Filtering snippets into a swift friendly style. To test simply build the app, and verify that the filters behave as expected.
Ref. #5613
Needs Review: @frosty 
Mind taking a peek?
Thanks!!
=> Notifications: Swiftifying Filters

WordPress/Classes/System/3DTouch/WP3DTouchShortcutHandler.swift, WordPress/Classes/System/WordPressAppDelegate.m
Fixes #5948 
To test:
Verify all 3D touch shortcuts still work
cc @astralbodies can you verify the guard statement looks fine? The only thing funky I could see was the indentation which is fixed.
=> 3D touch cleanup

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Fixes #5957
To test: See #5957 for steps to reproduce.
=> Fix filter change not syncing

WordPress/WordPress-Internal-Info.plist
No conflicts, and only my commits from #5959 are included. 🎉
=> Merge latest from release/6.5 into develop

WordPress/Classes/Networking/ReaderPostServiceRemote.m, WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Merging updates back to develop.
=> Merge/release 6.5

WordPress/WordPressTest/ReaderPostTest.m
Closes #5987 
To test: Run the test and make sure it passes.
Needs review: @sendhil, since you know what this one is about.
=> Reader: Adds test for dateForDisplay

WordPress/Classes/Models/AbstractPost.h, WordPress/Classes/Networking/ReaderPostServiceRemote.m, WordPress/Classes/Networking/ThemeServiceRemote.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/Utility/DisplayableImageHelper.m, WordPress/Classes/Utility/PhotonImageURLHelper.m, WordPress/Classes/Utility/Ratings/AppRatingUtility.m, WordPress/Classes/Utility/WPLookbackPresenter.m, WordPress/Classes/Utility/WPTableViewHandler.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceTextBar.m, WordPress/Classes/ViewRelated/Menus/MenusViewController.m, WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift, WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/Reader/CommentContentView.m, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m, WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/OCLint.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Alpha.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Internal.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressScreenshotGeneration.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressShareExtension.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressTodayWidget.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressUITests.xcscheme
Applied recommended settings for Xcode 8, and fixed all new warnings. There were a bunch of options that didn't match the right type and weren't really needed.
=> Recommended settings

WordPress/WordPress.xcodeproj/project.pbxproj
Needs review: @sendhil 
Sir, can i bug you with a quick PR?
Thanks!!
=> Updates debug profiles

WordPress/Classes/Extensions/CGAffineTransform+Helpers.swift, WordPress/Classes/Extensions/UIView+Animations.swift, WordPress/Classes/Utility/Gravatar.swift, WordPress/Classes/ViewRelated/Me/MeHeaderView.m, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockImageTableViewCell.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Ref. #5613
2. Open a Comment Notification
3. Try the following actions: Like / Unlike / Approve / Unapprove
Verify that the action button's image gets a nice animation.
2. Open the `Me` tab
3. Press over the gravatar
Verify that the image gets a Spring animation.
2. Open a badge notification
Verify that the image gets a Spring animation.
Will, may i bug you with a review?
=> Notifications: Action Animations

WordPress/Classes/ViewRelated/Comments/CommentViewController.m
I've noticed that the new Autosizing i've implemented in Notifications broke CommentViewController.
This PR just fixes that. Yay!
1. Launch wpios
2. Open `My Sites` > `Your Supercool Site`
3. Open the `Comments` section
4. Tap over any of the comments
Make sure that the text doesn't cut off after the first line. Everything should get it's size automatically.
Mind taking a peek at this one sir?
Thaaaanks!!!
=> CommentViewController: Let there be Autosizing Cells

WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift
Fixes #4725
Verify that NotificationsList and CommentsList don't display labels with clear backgrounds anymore.
=> Opaque Views

WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
Fixes #5971
To test:
2. Open any Comment-Y Notification
3. Begin typing a reply
4. Try adding a `@ mention`, and quickly complete a random handle, before previous request completes.
As a result, gravatars shouldn't mix anymore.
=> SuggestionsTableView: Fixing Gravatar Race Condition

Podfile, Podfile.lock
To test: Run `pod install` and build the project, ensure no warnings or errors occur 🙏 
Needs review: @nheagy can you take a look?
=> Updates WordPress-iOS-Shared pod to 0.6.2

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Improves #5537 in response to @koke's suggestions [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/5537#issuecomment-249917822). 
Basically, adds a cache timer to stop from frequent server requests.
This implementation works because `AbstractPostListViewController` already had code looking at `lastPostsSync/lastPagesSync`. So that's a freebie.
1. View the detail screen for a blog
1. The network activity icon shouldn't appear in the status bar
1. View the detail screen for a blog
1. The network activity icon should appear in the status bar, however this isn't concrete evidence because this screen performs other preloading
1. Ensure new post(s) appear immediately when viewing the Blog Posts screen, not after a new network request from this screen
1. Further, this screen …
=> Improve pages and posts preloading

WordPress/Classes/ViewRelated/Reader/ReaderMenuViewModel.swift
Fixes #6019 
To test: Follow the steps outlined in the issue.  Ensure that there are no missing sections in the reader after signing into wpcom. 
@frosty would you be game to review this one? 
=> Reader: updates sections if necessary.

WordPress/Classes/ViewRelated/Settings/SupportViewController.m
Fixes #2544 
Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/4629
=> Enable better ticket deflection for Helpshift

WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/WPAccount.h, WordPress/Classes/Utility/HelpshiftUtils.h, WordPress/Classes/Utility/HelpshiftUtils.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m
Cherry-picking #6061 #6075 for 6.6. 
=> Helpshift improvements for 6.6

WordPress/Classes/Utility/LocationService.h, WordPress/Classes/Utility/LocationService.m, WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationView.h, WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationView.m, WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m
Fixes #6088 
To test:
- Create or Edit a post
- Tap on Options
- Tap on Set Location
- Search for places around your current location
- see if results are better than before
- Check if selection of result works ok.
=> Use MKLocalSearch instead of geocoder to get better search results.

WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTextTableViewCell.swift, WordPress/Classes/ViewRelated/Views/RichTextView/RichTextView.swift
Implements a (temporary) workaround, to be removed once we enable Readability.
Please, DM me regarding details on how to test!
Fixes #6085
Brent, may i bug you with a super fun review?
cc @kwonye
=> Notifications: Autosizing Nightmare

WordPress/Classes/Services/PostService.h, WordPress/Classes/Services/PostService.m, WordPress/Classes/ViewRelated/Pages/EditPageViewController.m, WordPress/Classes/ViewRelated/Pages/PageListViewController.swift, WordPress/Classes/ViewRelated/Pages/WPLegacyEditPageViewController.m, WordPress/Classes/ViewRelated/Post/PostListViewController.swift, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes: #5962
**To test:**
1. Build and run? 😄
2. Create a post or page and make sure everything works as expected.
Unit tests pass but then no unit tests were ever written for these methods I removed 🙄. I will be doing further refactoring for #5963 so ignore any ugly code duplication you're seeing across multiple VCs.
Needs review: @nheagy, @frosty
=> Remove PostService main context-specific methods

WordPress/Classes/System/WordPressAppDelegate.m
Fixes #6138 
To test:
- Make sure the app builds normally.
- Make sure the unit tests run normally.
=> Removes newpost support for URLs.

WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Fixes #6109 
To test:
- On a multi-author site test if the author selection filters the post list correctly.
=> Refresh Post list after author filter is changed.

WordPress/Info.plist, WordPress/WordPressShareExtension/Info.plist, WordPress/WordPressTodayWidget/Info.plist
Merging latest from release/6.7.
=> Merge release/6.7 in to develop

WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/ReaderSiteServiceRemoteTests.swift, WordPress/WordPressTest/WordPressTest-Bridging-Header.h
=> Adds tests for ReaderSiteServiceRemote class

WordPress/Classes/Networking/MediaServiceRemoteREST.h, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/MediaServiceRemoteRESTTests.swift, WordPress/WordPressTest/MockWordPressComRestApi.swift, WordPress/WordPressTest/WordPressTest-Bridging-Header.h
=> Adds tests for MediaServiceRemoteREST class

WordPress/Classes/Services/CommentService.m
There is an issue where the reader comments endpoint will return the (previously fetched) last page of comments instead of an empty array when the last page + 1 is requested.  The app expects zero results.  The unexpected result set causes the app to behave as if there were more comments available to load, creating a loading loop.  The trigger is for the comments endpoint to return a full batch of comments for the last page, rather than a partial batch.
Since its possible some existing clients rely on this endpoint behavior we can't just patch the current version of the endpoint. This PR patches the app and we can look at updating the endpoint behavior in a future update to the REST API.
To test:
View comments in the reader.  Ensure that comments load as expected when:
- there are less …
=> Reader Comments: Resolves an issue where load more could get stuck in a loop

WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist, WordPress/Wordpress-Alpha-Info.plist
Fixes #5084
Adding the Encryption Flag to all of the plist for consistency, and to prevent TF from bugging us as well.
=> Adding ITSAppUsesNonExemptEncryption flag

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift, WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
Fixes #5781
1. Launch the app in a 4s device
2. Open a Badge notification
3. Rotate the device into Landscape mode
4. Verify that vertical scrolling is enabled (if there's actual overflow!)
Please: also verify that regular notifications (non badge ones!) always have vertical scrolling enabled.
Brent, you game for a hopefully fun review?
Thanks a lot in advance!!
=> Notifications: Badge Scrolling

WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #6269 
To test:
Repeat the steps outlined in the issue and confirm there is no crash.  You might want to add a `print` within the new `if` block to log when its executed to the console. 
=> Reader Detail: Fixes a potential crash when rotating 180 degrees.

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #6300
To test:
2. Open My Sites > Posts
3. With the post list onscreen, create a new post.
4. Save it as a draft
5. Publish the post
Make sure nothing breaks!
Needs review: @nheagy / @frosty
=> Fixing Violent KVO Crash

WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Fixes #6303 
To test:
Go to the Theme Browser and click customize. Then Header Image and try to upload a photo from the device. You should be able to upload the image just fine now.
=> Theme Customizer upload photo capability

WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m
To test:
- Build without warning. 😄 
=> Removes unused var and warning.

README.md
=> Updates README Swift and Xcode versions.

WordPress/Classes/Networking/ReaderTopicServiceRemote.m
Fixes #6362 
To test:
Repeat the steps outlined in the issue to confirm the bug.
Switch to this branch and repeat the steps to confirm the fix.
(Optional) Browse all those glorious coffee related posts.
Needs review: @jleandroperez game for a quick review?
=> Reader: Create a slug from a tag name before following.

WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Please, just verify that WPiOS builds successfully. Minor cleanup // Swift 3 style.
=> AztecPostViewController: Minor code cleanup!

WordPress/Classes/Extensions/WPStyleGuide+Fonts.swift, WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift, WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift, WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift, WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Adds dynamic type support to the reader. 
To test:
Adjust the system setting for larger font size.  Relaunch the app and observe the change in the reader list, reader detail, and reader comments.
=> First pass at dynamic type support for the reader.

WordPress/Classes/Utility/HelpshiftUtils.h, WordPress/Classes/Utility/HelpshiftUtils.m, WordPress/Classes/Utility/WPError.h, WordPress/Classes/Utility/WPError.m, WordPress/Classes/ViewRelated/NUX/NUXAbstractViewController.swift, WordPress/Classes/ViewRelated/NUX/Signin2FAViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninEmailViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninErrorViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninLinkMailViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninLinkRequestViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninSelfHostedViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninWPComViewController.swift, WordPress/Classes/ViewRelated/NUX/SignupViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift, WordPress/Classes/ViewRelated/Settings/SupportViewController.h, WordPress/Classes/ViewRelated/Settings/SupportViewController.m, WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m, WordPress/Classes/ViewRelated/Tools/HelpshiftPresenter.swift
A simple PR to get #6469 into 6.9
or whoever is around ;)
=> Merge Helpshift tags into 6.9

WordPress/Classes/ViewRelated/NUX/NUXAbstractViewController.swift, WordPress/Classes/ViewRelated/NUX/Signin2FAViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninEmailViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninErrorViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninLinkRequestViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninSelfHostedViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninWPComSyncHandler.swift, WordPress/Classes/ViewRelated/NUX/SigninWPComViewController.swift, WordPress/Classes/ViewRelated/NUX/SignupViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
=> Merge release/6.9 into develop

WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/Services/PostService.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController_Internal.h, WordPress/WordPressTest/PostTests.swift
Fixes #491 
To test: 
1. Select a post
2. Go to options and scroll down to excerpt (last option)
3. Tap and edit the excerpt
4. Update the post
Needs review: @jleandroperez @kurzee @koke 
CC: @sendhil
=> Adds ability to edit excerpt

WordPress/Classes/ViewRelated/Stats/StatsViewController.m
If we load the stats view while offline, we currently bail and don't even allow pull to refresh.
This keeps track of that case, and will automatically try to load stats when the app is back online
Fixes part of #6482
To test:
- Switch to airplane mode
- Launch the app and visit stats for a site
- Switch off airplane mode
- Stats should load automatically as soon as there is a connection
=> Retry loading stats when reachable if offline

WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
=> Fix "optional" X-Post titles

Podfile, Podfile.lock
Give Aztec a smoke test, please, and verify nothing breaks.
=> Updates Aztec Dependency

WordPress/Classes/Models/AbstractPost.m
To test:
- Run the app
- Check that log messages like: Copying Relationship, Skipping Relationship.. and Skipping... ; no longer show up in the console and logs.
=> Remove unnecessary log.

WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
Fixes #6500 
When I added fullscreen support to the reader, I implemented a custom navigation controller transition. Unfortunately, it turns out that once you implement `navigationController(_:animationControllerFor operation:from:to:)` the navigation controller disables its `interactivePopGestureRecognizer`. 
Folks on Stack Overflow recommend setting the `interactivePopGestureRecognizer`'s delegate to nil, but whilst this does re-enable the gesture it creates some other issues – namely, you can trigger the gesture when there's only one view controller in the stack which then breaks forward navigation temporarily.
As such, it seems that the main way to fix this was to just implement our own delegate for the recogniser. I'm allowing the gesture to take place as long as we're not about to …
=> Issue/6500 Restores interactive pop gesture

Podfile, Podfile.lock
=> Switch to Aztec 0.5a2 for 7.0 cut.

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #6655
To test:
- Ensure the app has no problem when publishing, scheduling, or saving a post 
=> Remove dead HUD code

Podfile, Podfile.lock
Updates to Aztec v0.5a3 release 2
=> Updates to Aztec v0.5a3 release 2

WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Fixes #6715 
To test:
- Start a new post using Aztec
- Switch to html mode
- Make some changes in html mode
- Press Publish or Save without switching back to visual mode
- See if you changes where save correctly on the post.
=> Save on html text changes also.

Podfile, Podfile.lock
Integrates the latest from develop.
=> Integrates the latest from Aztec.

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/InteractiveNotificationsManager.swift
This PR fixes the Push Authentication glitch that's affecting 7.0 release.
Fixes #6730
1. Make sure the Development Push Notifications Server is running
2. Install this branch and leave the app running in **Foreground**
3. Attempt to log into WordPress.com in a browser
4. Verify that the Push Authentication alert shows up
5. Wait for ~5 minutes!
6. Retry steps 1-4, but with the app in **Background** or **Killed** instead
7. Verify if the world is a happy place again
This patch is a temporary fix for two reasons:
- Small footprint!
- Develop already has +10.0 as the deployment target
- A proper and cute refactor is due. Filing an issue right away
cc @koke
=> Fixing Push Authentication

WordPress/Classes/Networking/MediaServiceRemoteREST.m, WordPress/Classes/Utility/InteractiveNotificationsManager.swift, WordPress/Classes/Utility/WPError.m, WordPress/Classes/ViewRelated/Blog/BlogListViewController.h, WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/System/WPTabBarController.h, WordPress/Classes/ViewRelated/System/WPTabBarController.m, WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressShareExtension/Info-Internal.plist, WordPress/WordPressShareExtension/Info.plist, WordPress/WordPressTest/MediaServiceRemoteRESTTests.swift, WordPress/WordPressTodayWidget/Info-Internal.plist, WordPress/WordPressTodayWidget/Info.plist
@jleandroperez Can you verify I merged the notifications fixes properly? Most notably the app I removed the app delegate changes with the old iOS 9 methods.
=> Merge 7.0 into develop

Scripts/fastlane/Deliverfile, Scripts/fastlane/Snapfile, Scripts/fastlane/wordpress_translation_retrieval.rb, WordPress/Classes/ViewRelated/NUX/SigninEmailViewController.swift, WordPress/Classes/ViewRelated/NUX/SigninWPComViewController.swift, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/System/WPTabBarController.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressScreenshotGeneration.xcscheme, WordPress/WordPressScreenshotGeneration/SnapshotHelper.swift, WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
Had to fix a minor merge conflict in the project file.
=> Merge 7.0 to develop

Podfile, Podfile.lock
=> Integrates Aztec 0.5a5

WordPress/Classes/Utility/ContextManager.h, WordPress/Classes/Utility/ContextManager.m, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Pulling in fixes from #6768 for our last iOS 9 build.
Needs review: @kurzee @astralbodies
=> 7.0.2: Cherry-picked context manager fixes

WordPress/Classes/Services/PostService.m
Fixes #6764
1. Enable Aztec
2. Create a new page
3. Open the Options panel
4. Set an excerpt
5. Publish the Page
6. Exit back to the Pages List
7. Reopen the Post > Options
Verify that the Excerpt is visible, and that it looks as expected.
Sir, may i bug you with a quick review?
Thanks!!!
=> Pages: Patching Page Excerpt Serialization

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/HockeyManager.m, WordPress/Classes/Utility/Logging/WPLogger.m
Fixes #6814 
To test:
Well... just make sure my stuff compiles and the next internal build we'll use the crash handler created in #2245 to test it for sure.
=> Turn off HockeyApp crash reporting & switch to Crashlytics for internal

Podfile, Podfile.lock
Updates Aztec to 0.5a6
Needs some quick testing to make sure nothing big is sneaking in.
=> Updates Aztec to 0.5a6.

Podfile.lock
=> Podfile lock aztec bump.

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift, WordPress/Classes/ViewRelated/Post/OptionsTableView.swift, WordPress/WordPress.xcodeproj/project.pbxproj
- New Header Style Picker
- Wired the new Format Bar
**Notes:**
- *OptionsTableView* is a direct port from what we've got in Aztec. Definitely happy to implement a custom / tailored solution, but for Mark I, let's bring in what we currently have in the Aztec Example!
- Mapped the Podfile to the latest commit. I'll update that to a stable release, when possible!
Needs review: @diegoreymendez @astralbodies @SergioEstevao 
Thanks in advance gentlemen!
=> Integrating Latest Aztec

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift, WordPress/Classes/ViewRelated/Post/OptionsTableView.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Sames as #6884 but now targeting the release 7.2
=> Integrate aztec on 7.2

WordPress/Classes/System/WordPress-Bridging-Header.h
=> Disable warnings about deprecated UILocalNotification in Helpshift

WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Fixes #6827
1. Open Aztec in "Rich Text Mode"
2. Add a couple images
3. Switch to another site
4. Verify that the images have been removed
5. Repeat in "HTML Mode"
=> AztecPostViewController: Stripping Media on site switch

WordPress/Classes/ViewRelated/Blog/SharingAuthorizationHelper.m
=> Improve publicize error messages

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Post/Aztec/CommentAttachmentRenderer.swift, WordPress/Classes/ViewRelated/Post/Aztec/MoreAttachmentRenderer.swift, WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj
- Integrates latest Aztec's release
- Updated Gridicons
- Wired new **More Comment** functionality
1. Try inserting a `` in html mode, and verify it gets rendered properly
2. Insert a `` comment, and verify it gets properly displayed
3. Try pressing the `More` format bar action (righter-most button)
Needs review: @SergioEstevao / @astralbodies 
=> Integrates Aztec Mark 0.5a7.1

Scripts/runUITests.sh, WordPress/WordPressUITests/MainNavigationTests.swift, WordPress/WordPressUITests/XCTest+Extensions.swift
This is a simple update for the current XCUI test examples based on @hoverduck 's work as in #6747
All tests should pass now, except for the `create account` test, which I'll leave it for now before #6790 is landed. 
Appreciate any review in advance.
=> Update XCUI tests and run UI test script

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Refs #6819
The previous attempt at a patch in #6855 did not resolve the issue completely as we're still seeing it spammed by the 7.2 release.   Since the underlying issue remains illusive, this PR removes the stat until we can get it sorted.
=> Post List: Removes the 'load more' stat.

WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Fixes #6680 and Fixes #6824 
To test:
- Create or edit a post on the app
- Write a title with multiple lines
- Write some content with multiple lines
- Check that the title and text scroll correctly
- Check that placeholders of both title and text are placed correctly
- Switch to HTML mode and check the same things has above
Needs review: @jleandroperez, this is very similar to the Aztec repo tickets that you checked recently.
=> Make title adapt to title content size and scrollable with the content.

WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
Fixes #6917.
To test:
- Open the app
- Login
Needs review
=> Remove conversion of the url to lowercase in login

WordPress/Classes/ViewRelated/NUX/Signin2FAViewController.swift
When you are looking at the 2FA screen and switch to your authenticator app,
this will automatically paste what's on the pasteboard if:
- The text field is empty
- The contents are different from what was there before becoming inactive
- The contents are a string with 6 digits
=> Auto-fill 2FA code from Pasteboard

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Post/Aztec/HTMLAttachmentRenderer.swift, WordPress/Classes/ViewRelated/Post/Aztec/MoreAttachmentRenderer.swift, WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Integrates the latest release of Aztec into WPiOS for release in 7.4.
/cc @koke, @astralbodies since this needs to be included in 7.4.
=> Integrates the latest version of Aztec.

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Post/AztecAttachmentViewController.swift, WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Integrates Aztec v1.0b1 into WPiOS 7.5.
=> Integrate Aztec v1.0b1

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
=> Attempt to fix crash by explicitly unwrapping

WordPress/Classes/ViewRelated/Me/MeViewController.swift
**Fixes** #7125 
**To test:**
Me->Log Out
Check that the message and button text is correct.
=> Update log out alert copy

WordPress/Classes/Services/PostService.m, WordPress/Classes/Utility/DisplayableImageHelper.m
Fixes #7152 #7154 
To test:
1. Checkout develop
2. Go to one of your blogs
3. Create a post with just one image
4. Follow that blog and check that on Reader and on the Post list the image is not displayed
5. Check out this branch
6. Check that on Reader and on the Post list the image is correctly displayed.
| Develop        | This branch           |
| ------------- |-------------|
| ![simulator screen shot may 16 2017 14 04 40](https://cloud.githubusercontent.com/assets/5558824/26118946/f553de28-3a41-11e7-9b76-fdf4b6fded94.png)|![simulator screen shot may 16 2017 13 45 19](https://cloud.githubusercontent.com/assets/5558824/26118954/ff51a400-3a41-11e7-9e34-d004957fbeb8.png)|
| ![simulator screen shot may 16 2017 14 04 52](https://cloud.githubusercontent.com/assets/5558824/26118967/0bf71636- …
=> Issue/7152 7154 inconsistencies on post images: Reader and Post List

WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
**Fixes** #6663 
**To test:**
Add a contributor to one of your sites.
Log in as the contributor and check that the you can't publish a post, but only get the option to "Submit for Review"
Log back as yourself and happily publish the post.
=> Same decision as WPEditorViewController to determine if a user can Publish

.swiftlint.yml, WordPress/Classes/Extensions/NSURL+Exporters.swift, WordPress/Classes/Models/ManagedAccountSettings.swift, WordPress/Classes/Models/Notifications/NotificationSettings.swift, WordPress/Classes/Networking/AccountSettingsRemote.swift, WordPress/Classes/Networking/NotificationSyncServiceRemote.swift, WordPress/Classes/Networking/PeopleServiceRemote.swift, WordPress/Classes/Services/NotificationSyncMediator.swift, WordPress/Classes/Services/PeopleService.swift, WordPress/Classes/ViewRelated/Me/AboutViewController.swift, WordPress/Classes/ViewRelated/NUX/EpilogueSegue.swift, WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift, WordPress/Classes/ViewRelated/Notifications/Tools/NotificationMediaDownloader.swift, WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanDetailViewModel.swift, WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderSearchSuggestionsViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift, WordPress/Classes/ViewRelated/Views/BadgeLabel.swift, WordPress/WordPressApi/WordPressComRestApi.swift, WordPress/WordPressApi/WordPressOrgXMLRPCApi.swift, WordPress/WordPressApi/WordPressRSDParser.swift, WordPress/WordPressShareExtension/ShareViewController.swift
and apply fixes to conform to those rules. These are violations that will be introduced once 0.19.0 ships (currently in [RC1](https://github.com/realm/SwiftLint/releases/tag/0.19.0-rc.1)).
=> Add empty_enum_arguments, empty_parameters & mark to .swiftlint.yml

WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Make the author name font size match the rest of the line
Addresses feedback from #7227 and retargeted to 7.7
To test:
Find a X-Post and make sure it looks good
=> Tweak styles for x-post subtitles

WordPress/Classes/Services/NotificationSyncMediator.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
This handles several issues with the previous implementation:
1. NotificationDetailsViewController was listening for changes on its notification, and marking it as read, even if it wasn't visible (app in the background, split view keeping a reference to a detail even after dismissing it). Now it listens to background/foreground notifications and only updates if
the view is visible.
2. NotificationDetailsViewController was marking notes as read from the NSManagedObjectContextObjectsDidChange notification, causing a core data save within another core data save, and crashing. Now it uses an async dispatch to break out of the current save.
3. If the markAsRead request failed, it'll revert the note to unread, and NotificationDetailsViewController would attempt to mark it as read again. This …
=> Improve marking notifications read logic

WordPress/Classes/Networking/MediaServiceRemoteXMLRPC.m
As identified in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/424, the response dictionary from uploading media via XMLRPC contains many more fields than it used to. I've consolidated our two parsing methods to handle media responses, so we should now parse out more data (if it's available) for uploads. I've also kept in a few fallbacks in case the newer field is nil.
To test:
* Check the code, attempt some uploads over XMLRPC – check that all fields are parsed correctly.
=> MediaServiceRemoteXMLRPC: Update XMLRPC response parsing for all fields

WordPress/Info.plist, WordPress/Resources/AppStoreStrings.po, WordPress/WordPress-Internal-Info.plist, WordPress/WordPressShareExtension/Info-Internal.plist, WordPress/WordPressShareExtension/Info.plist, WordPress/WordPressTodayWidget/Info-Internal.plist, WordPress/WordPressTodayWidget/Info.plist
=> Bringing develop current with release 7.7

Scripts/fastlane/download_metadata.swift, WordPress/Resources/AppStoreStrings.po
Updated app store what's new description
=> Bringing develop current with release 7.8 (strings update only)

Scripts/fastlane/Deliverfile, Scripts/fastlane/download_metadata.swift, WordPress/Resources/AppStoreStrings.po, WordPress/WordPressScreenshotGeneration/SnapshotHelper.swift
This PR adds the new subtitle field to the list of strings to be translated and makes the necessary updates so it is picked up. 
Needs review: @astralbodies Can you take a quick look at this one? Particularly, is there anything else I should to other than the updates on `AppStoreStrings.po` so the subtitle is picked up for translation?
Thanks
=> Adds support for new AppStore field subtitle

WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
Fixes #7392 
To test:
- Follow the step on the issue #7392 
- It shouldn't crash anymore
=> Allow the adding of asset when only the blog is defined.

WordPress/Classes/ViewRelated/NUX/Login.storyboard, WordPress/Classes/ViewRelated/NUX/LoginPrologueViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj
I derped and forgot to double check that the buttons were localized before we shipped https://github.com/wordpress-mobile/WordPress-iOS/pull/7397 .... so here's a quick PR to take care of that. :)
=> Login: Localize buttons on the prologue screen.

Podfile, Podfile.lock
Add version requirement to lottie in the Podfile
To test:
- ensure project still builds correctly
Thanks!
=> Add version to lottie in Podfile

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Post/WPEditorStatMap.swift, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
We use delegate methods to track stats now instead of the analytics pod
=> Update editor analytics usage

Podfile, Podfile.lock
Title has it.  Run the unit tests and do some manual testing before merging in.
=> Integrates Aztec v1.0.0-beta.6.

WordPress/Classes/Services/EditorSettings.swift, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/FeatureFlag.swift, WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift, WordPress/WordPressTest/EditorSettingsTests.swift
Fixes #7498
To test:
1. Build, run.
2. Make sure "beta" editor is an available option.
=> Remove all the feature flag items for Aztec; should be always visible

WordPress/WordPressTest/WPAppAnalyticsTests.m
To test:
1. Build.
2. Run unit tests.
3. Look for green Buddybuild status.
cc: @koke
=> Fixes logical issues with analytics unit tests

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #7528 
To test: Check the issue above to see how to reproduce.
=> Check for failed media when switching to html mode.

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Minor PR aimed at refreshing the Post Title Height upon rotation!
Fixes #7515
1. Launch Aztec in portrait mode
2. Enter a title that _just_ triggers a second line of text. (The bare minimum please!)
3. Toggle the device into landscape mode
4. Verify that the title got shrinked
=> AztecPostViewController: Updating title height upon view transformation

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift, WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist, WordPress/WordPressShareExtension/Info-Internal.plist, WordPress/WordPressShareExtension/Info.plist, WordPress/WordPressTodayWidget/Info-Internal.plist, WordPress/WordPressTodayWidget/Info.plist
Reverts wordpress-mobile/WordPress-iOS#7542
=> Revert "Brings develop current with 8.0.0.2"

WordPress/Classes/ViewRelated/NUX/Login.storyboard, WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift, WordPress/Classes/ViewRelated/NUX/LoginSiteAddressViewController.swift
Refs #7272 
To test:
On the epilogue screen, 
- confirm clicking the continue button dismisses the screen. 
- confirm clicking the "add another" button shows the site address view controller
- confirm the site address view controller has a cancel button
- confirm that the correct button title is shown when there are zero blogs, and when there is one or more blogs.
=> Login: Wires up 'connect another' button on epilogue screen.

WordPress/Classes/Models/Media.h, WordPress/Classes/Models/Media.m, WordPress/Classes/Services/MediaService.m
Fixes #7555 
To test: Check the issue above for steps to reproduce.
=> Improve parsing of mime types.

circle.yml
This is just the minimum configuration required so CircleCI can build the app. We can tweak more later.
=> CircleCI Integration

WordPressKit/WordPressKit/WordPressOrgXMLRPCValidator.swift
Most HTTP redirects will turn a POST request into a GET request, which makes
the XML-RPC probe fail. This means that a site with enforced SSL would require
multiple attempts before succeeding.
Now if we detect a redirect we'll retry a request. I've limited this to
redirects with the same host name.
Fixes #7621 
To test:
- Try adding a site that redirects to https
- The validator should succeed in the first validator step (i.e., you should not see "Try the original given url as an XML-RPC endpoint" in the console)
=> Improve handling of redirects when adding sites

WordPress/Classes/Extensions/WPStyleGuide+Aztec.swift, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
=> Fix warning in AztecPostViewController

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift, WordPress/Classes/ViewRelated/NUX/LoginProloguePromoViewController.swift
Updates the Specta and Especta pods version
Also removes incorrect whitespaces in two files.
To test:
`pod install`
Run all tests and make sure they pass
=> Update Specta and Especta pods

Scripts/fastlane/Deliverfile, Scripts/fastlane/download_metadata.swift, WordPress/Resources/AppStoreStrings.po
=> Bring develop current with release/8.2

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Somehow we missed these a while back 😬. Also tracking blog for Plans.
=> Add missing stats for people

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
In this PR we're integrating Aztec's Bleeding Edge (Beta Mark 10).
Fixes #7648 (yay!)
=> Aztec Beta Mark 10

WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist, WordPress/WordPressShareExtension/Info-Internal.plist, WordPress/WordPressShareExtension/Info.plist, WordPress/WordPressTodayWidget/Info-Internal.plist, WordPress/WordPressTodayWidget/Info.plist
Forgot to update develop with the latest version number update on August 15th.
=> Bring develop current with release/8.3

WordPress/Classes/Extensions/UIDevice+Helpers.swift, WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #7766 
To test:
Verify the new post icon looks correctly on iPhone/iPad with iOS 10/11
=> Correct tab bar alignment in iOS 11

WordPress/Classes/Services/WordPressXMLRPCAPIFacade.h, WordPress/Classes/Services/WordPressXMLRPCAPIFacade.m, WordPress/Classes/ViewRelated/Tools/HelpshiftPresenter.swift, WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist, WordPress/WordPressShareExtension/Info-Internal.plist, WordPress/WordPressShareExtension/Info.plist, WordPress/WordPressTodayWidget/Info-Internal.plist, WordPress/WordPressTodayWidget/Info.plist
=> Bring develop current with release/8.4

WordPress/Classes/ViewRelated/Aztec/Renderers/CommentAttachmentRenderer.swift
Fixes #7807 
To test:
1. Edit a Gutenberg-create post.
2. Make sure you can't see Gutenberg block comments in visual mode.
3. Make sure other HTML comments are still rendered.
We still have an empty character to represent the comment, because any logic to try and hide the fact that there's content would be extremely complicated, and as such, dangerous to have.
=> Hides Gutenberg comments from visual mode.

WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m
Fixes #7800
To test:
- Check the ticket steps to how to reproduce, and see if crash no longer happens.
=> Add check for class type before accessing path component.

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift, WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Fixes #7757 
Updates media to 0.21 and address the issues above
To test:
Check the tickets details for steps to test.
=> Integrate wpmediapicker 0.22

WordPress/Classes/Utility/PushNotificationsManager.swift
In this PR we're:
- Moving constants to nested types
- Removing a few calculated properties that... were not really needed, to begin with!
- Grouping related methods in categories
Ref. #6755
**No logic** was changed in this PR. In order to test this, please, verify that the Unit Tests don't break.
Mind taking a quick peek at this one sir?
=> PushNotificationsManager: Swift cleanup

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Refs #7821 
To test:
- Launch the app on iPhoneX
- Using the Aztec editor open or create a new post
- Check that title and content view are keep inside the safe areas for the iPhoneX
- Check if things still work on the older devices.
=> Fix Aztec text editor insets

Podfile, Podfile.lock, WordPress/Classes/Networking/Pinghub.swift, WordPress/WordPressTest/PinghubTests.swift
**Fixes** #7926 
**To test:**
Build and ran the app, send yourself a notification from the web, test that everything works as expected.
Run the tests locally, check that all is all green.
=> Update Nimble and Starscream to latest version

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #7935 
To test:
- Check the ticket steps above for how to reproduce it.
=> Don’t nil the picker when canceling.

WordPress/Classes/ViewRelated/Aztec/Helpers/AztecVerificationPromptHelper.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Supplementary PR to #7899, fixing issues kindly pointed out by @jleandroperez :)
=> AztecVerificationPromptHelper: Fix incorrect (de-)registration from notifications.

README.md
is needed as a minimum version
Fixes #
To test:
Needs review: @
=> Update README to say Xcode 9.0

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Fixes #7975 
This PR makes the + button on post list and pages list visible again.
To test:
- Check ticket description to see how to reproduce the issue.
=> Make sure the bar button item has the correct dimension.

WordPress/Classes/System/WordPressAppDelegate.m
**Fixes** #8004 
**To test:**
Run the app and check that it looks like the screenshot on the original item.
=> Updated main navigation tab title color to grey

WordPress/Classes/Extensions/WPStyleGuide+Aztec.swift, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #7957
2. Verify that everything looks as expected!
=> AztecPostViewController: Replacing Feedback Text with Gridicon

WordPress/WordPressTest/Posts/PostAttachmentTests.swift
Run the unit tests, and verify that (now) everything is happy.
=> Fixing Unit Tests Build Error

WordPress/Classes/Models/Comment.m, WordPress/Classes/ViewRelated/Views/RichTextView/NSAttributedString+RichTextView.swift, WordPress/Classes/ViewRelated/Views/WPRichText/WPTextAttachmentManager.swift
@jleandroperez and @aerych I don't think we no longer this, after we removed DTCoreText from the project right?
=> Remove uncessary hack and references to DTCoreText

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #8060 
To test:
See ticket above for steps on how to reproduce.
=> Disable smart quotes in aztec.

Podfile, Podfile.lock
Fixes #7988 
To test:
- See ticket above for description on how to reproduce.
=> Update WPMediaPicker to version 0.24.

WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
Fixes #8073
To test:
- ensure the back button works as described in #8073
=> Login: fix back button during Google login

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift, WordPress/Classes/ViewRelated/NUX/Login.storyboard, WordPress/Classes/ViewRelated/NUX/LoginPrologueViewController.swift
Fixes #8150
To test:
To ensure the flag works, try tapping the "Create a WordPress site" during login. With the flag on, a new gray screen should appear. And when off, the old signup screen should appear.
Needs Review: @ScoutHarris
=> Social signup: add feature flag

WordPress/Classes/Services/MediaService+Swift.swift, WordPressKit/WordPressKit/RemoteMedia.h, WordPressKit/WordPressKitTests/MediaServiceRemoteRESTTests.swift
This PR implements better checking of nil values while merging media.
To test:
- Open the demo app
- Open a site media library
- Check that sync happens correctly
=> Make sure we have better failsafe for nil fields.

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecAttachmentViewController.swift, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Merging 8.9 into develop.
Created this PR, since there were merge conflicts I resolved manually.
/cc @SergioEstevao can you verify the merges look fine?
=> Merge 8.9 into develop

WordPress/WordPress.xcodeproj/project.pbxproj
We missed a step when building the Flux library to the device.
To test:
- Select a real device for the build target of the app
- Build and run the app on the device.
=> Make sure flux library is signed when copied to the device.

.gitignore, WordPress/Classes/ViewRelated/NUX/Login.storyboard, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressUITests/LoginTests.swift, WordPress/WordPressUITests/MainNavigationTests.swift, WordPress/WordPressUITests/Screens/BaseScreen.swift, WordPress/WordPressUITests/Screens/LinkOrPasswordScreen.swift, WordPress/WordPressUITests/Screens/LoginEmailScreen.swift, WordPress/WordPressUITests/Screens/LoginEpilogueScreen.swift, WordPress/WordPressUITests/Screens/LoginPasswordScreen.swift, WordPress/WordPressUITests/Screens/MeTabScreen.swift, WordPress/WordPressUITests/Screens/MySitesScreen.swift, WordPress/WordPressUITests/Screens/SignupScreen.swift, WordPress/WordPressUITests/Screens/TabNavComponent.swift, WordPress/WordPressUITests/Screens/WelcomeScreen.swift, WordPress/WordPressUITests/Utils/Logger.swift, WordPress/WordPressUITests/XCTest+Extensions.swift, WordPress/WordPressUITests/gencredentials.rb
Rewritten login tests in Page Object manner.
=> Rewrite Login tests w/ Page Objects

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Let's enable this to make sure we don't forget before the code freeze 😁 
See #8318
=> Enable plugin management in app store builds

WordPress/Classes/Stores/PluginStore.swift, WordPress/Classes/ViewRelated/Plugins/PluginListViewController.swift, WordPress/Classes/ViewRelated/Plugins/PluginListViewModel.swift
Adds a UIRefreshControl to the plugins list, and makes it work with Flux.
See #8318
=> Add pull-to-refresh to plugins list

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecAttachmentViewController.swift, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift, WordPress/WordPressTest/Posts/PostAttachmentTests.swift
This PR integrates Aztec 1.0.0 Beta 16 into WPiOS.
There are some problems with the integration due to [this change](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/846/files#diff-d8a133f794ed76fc0e76e3f633a1cf51L11) in Beta 16.
Ideally, this should be merged before the 9.1 code freeze on Monday.
Can you let me know when the fix is up @SergioEstevao.  Thanks!
/ccing @elibud since she'll be freezing 9.1.
=> Updates Aztec to beta 16. Integration needs fixing.

Scripts/fastlane/download_metadata.swift, WordPress/Resources/AppStoreStrings.po
=> Bring develop current with release/9.1

Scripts/fastlane/Deliverfile, WordPress/Classes/Services/MediaCoordinator.swift, WordPress/Classes/Services/MediaService.h, WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Merges WPiOS 9.0 into WPiOS 9.1.
Manually fixes some small conflicts.
=> Merges WPiOS 9.0 into 9.1

RELEASE-CYCLE.md
Added a new file that contains a brief description of how our release cycle works. 
@astralbodies @diegoreymendez can you take a look? If you find anything you would like to change feel free to edit directly. Thanks.
=> Release cycle doc

.gitignore, WordPress/WordPressUITests/LoginTests.swift, WordPress/WordPressUITests/MainNavigationTests.swift, WordPress/WordPressUITests/Screens/BaseScreen.swift, WordPress/WordPressUITests/Screens/LinkOrPasswordScreen.swift, WordPress/WordPressUITests/Screens/LoginEmailScreen.swift, WordPress/WordPressUITests/Screens/LoginEpilogueScreen.swift, WordPress/WordPressUITests/Screens/LoginPasswordScreen.swift, WordPress/WordPressUITests/Screens/MeTabScreen.swift, WordPress/WordPressUITests/Screens/MySitesScreen.swift, WordPress/WordPressUITests/Screens/SignupScreen.swift, WordPress/WordPressUITests/Screens/TabNavComponent.swift, WordPress/WordPressUITests/XCTest+Extensions.swift
Make sure tests are passing now. Also, fixed some warnings and done minor clean-up.
Fixes #8341 
To test:
Check buddybuild run
=> Fix failing UI tests

WordPress/Classes/Stores/PluginStore.swift
Fixes #8423 
To test:
- Put your phone in Airplane mode
- Toggle active/autoupdates for a plugin
- The app should display a notice with an error
=> Show errors when plugin modifications fail

WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift, WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.xib, WordPress/Classes/ViewRelated/Activity/WPStyleGuide+Activity.swift
Another step on #7832 
**To test:**
Go to the Activity Log and check that is pretty :)
=> Activity Log: Update ActivityTableViewCell to v1 design

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR updates the code to check for failed attachment on the local Aztec editor error structure instead of the media coordinator. The main reason for this is that after all uploads are finished(errored or not) all of them are cleaned out of the coordinator.
To test:
- Start a post
- Go to offline
- Try to insert some images from the local device.
- See them fail
- Try to Save or Publish
- Check that you see an alert message about this media
=> Fix remove all failed media

WordPress/Classes/Services/MediaService.m
Fixes #8517 
To test:
- Check ticket above for details on how to reproduce.
=> Make sure we have a thumbnail callback before invoking it.

WordPress/Classes/Utility/ImmuTable.swift, WordPress/Classes/ViewRelated/Activity/ActivityListSectionHeaderView.swift, WordPress/Classes/ViewRelated/Activity/ActivityListSectionHeaderView.xib, WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift, WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.xib, WordPress/WordPress.xcodeproj/project.pbxproj
Another step on #7832 
**To test:**
1. Go to a site with ActivityLog enabled (ping me if you need access).
2. Scroll and check that the headers stick to the stop of the table while doing so.
3. Check that the header style looks close enough to our latest design.
=> Activity Log: Update TableView headers

Podfile, Podfile.lock, Scripts/fastlane/Deliverfile, WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist, WordPress/WordPressShareExtension/Info-Alpha.plist, WordPress/WordPressShareExtension/Info-Internal.plist, WordPress/WordPressShareExtension/Info.plist, WordPress/WordPressTodayWidget/Info-Alpha.plist, WordPress/WordPressTodayWidget/Info-Internal.plist, WordPress/WordPressTodayWidget/Info.plist, WordPress/Wordpress-Alpha-Info.plist
Includes all the changes from release 9.2.1
=> Release 9.2.1

WordPress/Classes/ViewRelated/Jetpack/JetpackConnectionWebViewController.swift
This is to better identify flows coming from the apps
=> Add from parameter to connection flow URL

WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist, WordPress/WordPressShareExtension/Info-Alpha.plist, WordPress/WordPressShareExtension/Info-Internal.plist, WordPress/WordPressShareExtension/Info.plist, WordPress/WordPressTodayWidget/Info-Alpha.plist, WordPress/WordPressTodayWidget/Info-Internal.plist, WordPress/WordPressTodayWidget/Info.plist, WordPress/Wordpress-Alpha-Info.plist
Updates version numbers for a new 9.3 release.
=> Updates version numbers for a new 9.3 release.

WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.swift, WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.xib
The "more information" link was showing a FAQ entry that wasn't very helpful.
=> Remove more information link from Jetpack prompt

WordPress/Classes/ViewRelated/NUX/FancyAlertViewController+LoginError.swift, WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
Reverts wordpress-mobile/WordPress-iOS#8608
=> Revert "Decoupling Authentication Flow: Mark III"

WordPress/Classes/Services/MediaCoordinator.swift
Fixes #8664 
To test:
- Check issue above to see steps on how to replicate original issue, and make sure it doesn't happen
- Test with regular WP.com and self-hosted sites also.
=> Make sure changes done in the main context are merged in derived context

WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Fixes #8721
New accounts will now get an auto generated display name
To test:
- Create a new account using the new site creation process
- Check that the auto generated name looks decent
=> Social signup: Auto generate display name

WordPress/Classes/ViewRelated/Activity/WPStyleGuide+Activity.swift, WordPressKit/WordPressKit/Activity.swift, WordPressKit/WordPressKitTests/Mock Data/activity-log-success-1.json, WordPressKit/WordPressKitTests/Mock Data/activity-log-success-2.json, WordPressKit/WordPressKitTests/Mock Data/activity-log-success-3.json, WordPressShared/WordPressShared/NSDate+Helpers.swift
**Fixes** #8728 
**To test:**
1. Test that the activity log doesn't load in develop.
2. Check out this branch and check that it does.
3. Check that the code makes sense.
cc: @dmsnell
=> Update published format to include milliseconds

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Ref #8109 
To test:
- Go to create an account.
- Verify it shows the new signup flow.
cc: @elibud
=> Permanently enable new signup.

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+JetpackPrompt.swift, WordPress/Classes/ViewRelated/Stats/StatsViewController.m, WordPressShared/WordPressShared/Core/Analytics/WPAnalytics.h
**Fixes** #8754 
**To test:**
Trigger the flow and check that the correct stats are reported.
=> Fix Jetpack installation stats

WordPressKit/WordPressKit/Activity.swift, WordPressKit/WordPressKitTests/ActivityServiceRemoteTests.swift, WordPressKit/WordPressKitTests/Mock Data/activity-rewind-status-restore-failure.json, WordPressKit/WordPressKitTests/Mock Data/activity-rewind-status-restore-finished.json, WordPressKit/WordPressKitTests/Mock Data/activity-rewind-status-restore-in-progress.json, WordPressKit/WordPressKitTests/Mock Data/activity-rewind-status-restore-queued.json, WordPressKit/WordPressKitTests/Mock Data/activity-rewind-status-success.json
**Another step for** #7832 
**To test:**
This info is still not integrated in the UI so just check that all the test pass and that the code looks solid.
=> Add lastUpdated field to RewindStatus

WordPress/Classes/ViewRelated/NUX/SiteCreationDomainsTableViewController.swift
**Fixes** #8764 
**To test:**
First check that you can replicate the reported issue with the branch `release/9.5`.
Then check that you claim the domain that matches your username (.wordpress.com) in this branch.
=> Address suggestion endpoint call needs to be authenticated

WordPress/Classes/ViewRelated/Stats/StatsViewController.m
Fixes #8803 
To test:
There are no known reproduction steps
=> Don't crash stats when opening bad URLs

WordPress/Classes/Services/SiteCreationService.swift
**Fixes** #8842
**To test:**
Follow the steps on the ticket and make sure you can claim the url associated with your username.
@ScoutHarris I think this fix is the more straight forward one for this issue, but let me know if you think we should take a different approach.
=> Authenticate blog address validation call

WordPress/Classes/ViewRelated/NUX/SiteCreationCreateSiteViewController.swift
=> Fix Typo in error message

WordPress/Classes/Stores/PluginStore.swift
Ref #8831 
To test: Verify 'Successfully' is correctly spelled.
=> Fix ‘Successfully’ misspelling.

WordPress/Classes/ViewRelated/Menus/MenuHeaderViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemAbstractView.m, WordPress/Classes/ViewRelated/Menus/MenuItemView.m, WordPress/Classes/ViewRelated/Menus/MenusSelectionDetailView.m, WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.m, WordPressShared/WordPressShared/Core/Views/WPStyleGuide+DynamicType.swift
This unbreaks `develop`. Why my branch was not breaking is beyond my comprehension
=> Update usage of WPStyleGuide, passing a maximum font size from Obj-C

WordPress/WordPressShareExtension/AppExtensionsService.swift
Fixes #8919 
This PR fixes an issue in the share and draft extensions: if a user's primary site is hidden in WPiOS, it is also hidden in the app extension's site picker (it shouldn't be). In addition, the categories for the primary load even though no site is selected. 
**FWIW ->** a higher-order issue here is that the primary site shouldn't be able to be hidden in the first place (which would match Calypso).
First on `develop`, ensure you are able to repro the issue described in [the bug](https://github.com/wordpress-mobile/WordPress-iOS/issues/8919).
Then on this PR's branch:
1. Load WPiOS and hide the primary site.
2. Share something and verify: the primary site still displays in the site picker, the correct categories are loaded, and the primary site is pre-selected when the modules …
=> App Extensions: Primary site can no longer be hidden in site picker

WordPress/Classes/Models/AbstractPost.h, WordPress/Classes/Services/PostCoordinator.swift, WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift, WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
This PR adds functionality to the PostCoordinator to allow the retry of media uploading.
=> Retry upload of post

WordPressComStatsiOS/WordPressComStatsiOS/UI/StatsTableViewController.m
=> Merge cherry pick stats fix into release/9.7

WordPress/Classes/ViewRelated/NUX/Signup.storyboard
Fixes #8982 
To test:
- Follow repro steps on #8982 .
- Verify "Waiting for Google to complete…" label wraps.
=> Constraining Signup > Google View > title label

Podfile, Podfile.lock, WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #9026 
To test:
- pod install.
- Verify ZendeskSDK (1.11.0.1) is installed.
- Verify project builds & app runs.
=> Adding ZendeskSDK pod.

WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
Fixes #8282 
To test:
- Go to Post Settings
- Tap on Tag Setting
=> Post Settings: Removed Drop shadow on tags input field

WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosDataSource.swift
Implements part of #8954 
This PR throttles searches, so that we don't trigger a network request with every single keystroke.
Turns out there was already a facility in the codebase for this specific use case. It's good that I found it only after a couple of hours of banging my head against the problem 😛 
I set a 1 second interval, which might be a bit too long. 
To test:
1. Navigate to the Stock Photos interface
2. Press several keys in sequence. Notice how a new search is not actually triggered until one second after the last keystroke
=> Stock photos: Throttle search requests

WordPress/Classes/Extensions/URL+Helpers.swift, WordPress/Classes/Models/Blog+Quota.swift, WordPress/Classes/Utility/Media/MediaExporter.swift, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift, WordPress/Classes/ViewRelated/Post/PostEditorState.swift
This PR merges 9.7 back into develop resolving all conflicts.
=> Merges 9.7 back into develop.

WordPress/Classes/ViewRelated/System/Notices/NoticeView.swift
This PR adds a drop shadow to `NoticeView`, to improve their visibility – particularly against lighter coloured backgrounds where they tended to blend in.
I had to swap the view hierarchy around a little, as `NoticeView` was clipping to its bounds but the shadow needs to display outside the bounds. I also added a mask so that the shadow isn't drawn within the blur effect area, so it doesn't darken the background of the notice itself.
I tried to match the shadow as close as possible to Apple's shadows for notifications banners that drop down at the top of the screen.
**To test:**
* Publish a post and check the publish confirmation notice has a shadow and looks like the screenshot above.
=> Notices: Add shadow to improve visibility of notices

WordPressKit/WordPressKitTests/ReaderTopicServiceRemoteTest+Subscriptions.swift
=> Fix Unit Test within WordPressKit

Scripts/manage-version.sh
Updates manage-release.sh script with the new .plists layout and .xcconfig schema.
@diegoreymendez
=> Update manage-release script to the new plists config

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Fixes #9205
1. Revert to commit `9c49e1b`
2. Fresh install the app
Verify that the NoResults UI (Blog List) shows up correctly, and that there are no broken constraint errors.
@nheagy Sir, may i bug you with a fun review?.
=> Fix: Broken Constraint at Launch

WordPress/Classes/Models/ReaderSaveForLaterTopic.swift
This PR removes a deprecation warning.
Added people with knowledge of this code as reviewers for proper testing.
=> Removes a deprecation warning.

Podfile, Podfile.lock, WordPressAuthenticator/WordPressAuthenticator/Signin/LoginProloguePromoViewController.swift
Fixes #9102
This updates several of our pods, including the long-neglected `lottie`.
To test:
- ensure everything builds
- ensure everything still works
@aerych you got time for this one?
=> Update several pods

WordPress/Classes/ViewRelated/Plugins/PluginDirectoryCollectionViewCell.swift
One my latest PRs introduced a warning (#9346). This gets rid of it :)
=> Plugin Directory: fix a recently introduced warning.

WordPress/Classes/Utility/ZendeskUtils.swift
Ref #9020
This is just cleaning up some code and adding comments. No functional changes.
To test:
Just some sanity checks:
- Go to the Support view.
- Select 'WordPress Help Center' and verify it appears.
- Select 'Contact Us' and submit a ticket (I'll take care of it on the Zendesk side).
- Select 'My Tickets' and verify your ticket is there.
@etoledom - quite possibly the easiest PR you'll ever get from me! Would you mind? Thank you!!
=> Zendesk Mobile: code cleanup and comments

Podfile, Podfile.lock, WordPressAuthenticator/WordPressAuthenticator/Signin/LoginEmailViewController.swift
Merge fixes of 10.0.2 into develop
=> Merge 10.0.2 into develop

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Ref #9020
To test:
- Go to Me > Help & Support
- Verify you see the new Help & Support view.
=> Enable Zendesk

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift, WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift
Refs #8109
This removes the username changing feature flag.
To test:
- ensure everything still builds and the app settings screen still works
=> Remove username changing flag

WordPress/Classes/Utility/Media/ImageDownloader.swift, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Surgical PR: 
- **ImageDownloader** comes in
- **AFNetworking** comes out!
2. Add a new post. Insert [Local Images, Blog Images, Free Gallery Images]
3. Verify the images look good
4. Publish!
5. Open the Post. Edit
6. Verify that the images look good!
cc @SergioEstevao 
=> Nuking AFNetworking: AztecPostViewController!

WordPress/Classes/ViewRelated/Cells/PostFeaturedImageCell.h, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
=> Merges 10.1.1 into 10.2

WordPress/Classes/ViewRelated/Comments/CommentViewController.m
This fix is analog to #8804
Closes #8803
Same as #8804. No known repro steps, i'm afraid!
@koke would you be game for a quick review?
cc @kwonye doing groundskeeping too, i promise!!
=> CommentViewController: Bad URL Failsafe

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
This PR activates the Gif Support in reader detail feature for everyone!
Let's keep the flag around for some time just in case.
To test:
- Check that the project builds and run.
- Check that the reader detail loads and plays animated gifs.
=> FeatureFlag: Activating `gifSupportInReaderDetail` feature for everyone.

Scripts/manage-version.sh
This PR updates the manage-version script with:
1. Fix for #9453 
2. New commands for automatically bumping the release number starting from the current one  
To test:
a. use the script to update the version number to have a _hotfix_ digit other than 0.
b. verify that `VERSION_SHORT` in _config/Version.Internal.xcconfig_ and _config/Version.public.xcconfig_ is correct (has the hotfix digit set). 
c. verify that `app_version` in _DeliverFile_ is correct (has the hotfix digit set).
d. use the script to update the version number to have a _hotfix_ digit equal to 0.
e. verify that `VERSION_SHORT` in _config/Version.Internal.xcconfig_ and _config/Version.public.xcconfig_ is correct. 
f. verify that `app_version` in _DeliverFile_ is correct.
_**Important note:** the scripts push every new …
=> Version management script update

WordPress/Classes/Services/SiteCreationService.swift, WordPress/Classes/ViewRelated/NUX/SiteCreationCreateSiteViewController.swift, WordPress/Classes/ViewRelated/NUX/SiteCreationFields.swift
Fixes #8109 
The very last bit of cleanup for the new site creation flow! This chunk is your baby, @ScoutHarris, would you do the honour of reviewing it?
To test:
- ensure site creation still works
- ensure the code is good
=> Make SiteCreationParams.theme non-optional

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Aztec/Extensions/VideoAttachment+WordPress.swift, WordPress/Classes/ViewRelated/Aztec/Processors/VideoUploadProcessor.swift, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
Integrates the latest from Aztec.
More specifically: the new output node merging logic.
=> Updates to the latest from Aztec.

WordPress/Resources/AppStoreStrings.po
Merge Release/10.4 into develop
=> Merge Release/10.4 into develop

Scripts/fastlane/metadata/no/description.txt, Scripts/fastlane/metadata/no/keywords.txt, Scripts/fastlane/metadata/no/subtitle.txt
=> Merge 10.3.1 into develop

Scripts/fastlane/metadata/no/description.txt, Scripts/fastlane/metadata/no/keywords.txt, Scripts/fastlane/metadata/no/subtitle.txt, WordPress/Classes/Models/Notifications/NotificationSettings.swift, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+PushPrimer.swift, WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift, WordPress/Classes/ViewRelated/Reader/ReaderPostMenu.swift, WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift, WordPress/Classes/ViewRelated/Themes/ThemeBrowserCell.swift, WordPress/Classes/ViewRelated/Themes/ThemeBrowserHeaderView.swift, WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift, WordPress/Classes/ViewRelated/Views/NavigationTitleView.swift, WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
This PR is to keep our feature branch, `feature/extract-notifications-feature-branch` in sync with `develop`
To test:
- The project should build
- The tests should pass.
=> Merge develop into the Extract Notifications feature branch

WordPress/Classes/System/WordPressAppDelegate+Swift.swift, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Universal Links/Route.swift, WordPress/Classes/Utility/Universal Links/RouteMatcher.swift, WordPress/Classes/Utility/Universal Links/Routes+Me.swift, WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift, WordPress/Classes/ViewRelated/System/WPTabBarController.h, WordPress/Classes/ViewRelated/System/WPTabBarController.m, WordPress/Resources/AppStoreStrings.po, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/RouteMatcherTests.swift
To Test:
- The project builds
- The tests pass
=> Merge develop into feature branch for Extracting Notifications 

Podfile, Podfile.lock
Integrated the latest from `release/10.4` into `develop`.
=> Integrates the latest from release/10.4 into develop

Podfile.lock
=> Merge develop into Extract notifications feature branch

WordPress/Credentials/gencredentials.rb
This PR completes the update of the gencredentials.rb started in #9714.
To Test:
- Build the release version of the app and verify that the operation completes without errors.
=> Fixes credentials scripts

WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
This updates the screenshots taken by snapshot to the agreed set. This does not include faking notifications and stats data. Examples are shown below for `en-US`:
| File name       | iPhone X        | iPhone 8 Plus | iPad Pro (12.9-inch) |
| ------------- | ------------- | -------------- | --------------------|
| 1-PostEditor  | ![iphone x-1-posteditor](https://user-images.githubusercontent.com/1773641/42948459-339dd0ca-8b78-11e8-9534-1af8e0e76f84.png)  | ![iphone 8 plus-1-posteditor](https://user-images.githubusercontent.com/1773641/42948309-e2269844-8b77-11e8-8655-3bfafb6e61a4.png) | <img width="1366" alt="ipad pro 12 9-inch -1-posteditor" src="https://user-images.githubusercontent.com/1773641/42948137-8f8d672a-8b77-11e8-9858-064586b15c58.png">  |
| 2-Reader       | ![iphone …
=> Update screenshots taken by snapshot to agreed set

WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift
=> Merge 10.4.1 into 10.5

WordPress/Classes/System/WordPressAppDelegate+Swift.swift, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/AccountHelper.swift, WordPress/Classes/Utility/Universal Links/NavigationActionHelpers.swift, WordPress/Classes/Utility/Universal Links/Routes+MySites.swift, WordPress/Classes/Utility/Universal Links/Routes+Post.swift, WordPress/Classes/Utility/Universal Links/Routes+Stats.swift, WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift, WordPress/WordPress.xcodeproj/project.pbxproj
I accidentally forgot to merge https://github.com/wordpress-mobile/WordPress-iOS/pull/9819 into its target branch before I merged the target branch, so I've opened this PR which re-targets against `develop`.
Code is all the same, just targeting `develop` instead of the feature branch.
=> Universal Links: Improve failure cases (retargeting PR)

Gemfile.lock, Podfile, Podfile.lock
Updates Aztec to a new version that fixes an important bug with lists.
Fixes #9857.
- Make sure the editor works normally.
- Make sure the issue reported in #9857 is no longer reproducible.
=> Updates Aztec to 1.0.0-beta.24

MIGRATIONS.md, Podfile, Podfile.lock, WordPress/Classes/Models/PublicizeConnection.swift, WordPress/Classes/Models/PublicizeService.swift, WordPress/Classes/Services/SharingService.swift, WordPress/Classes/ViewRelated/Blog/SharingAccountViewController.swift, WordPress/Classes/ViewRelated/Blog/SharingConnectionsViewController.m, WordPress/Classes/ViewRelated/Blog/SharingDetailViewController.m, WordPress/Classes/ViewRelated/Blog/SharingViewController.m, WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion, WordPress/Classes/WordPress.xcdatamodeld/WordPress 77.xcdatamodel/contents, WordPress/WordPress.xcodeproj/project.pbxproj
=> Merge 10.5.1 into 10.6

WordPress/Resources/AppStoreStrings.po, WordPress/Resources/release_notes.txt
Merge new release notes from 10.7 into develop
=> Merge new release notes from 10.7 into develop

WordPress/Classes/Services/BlogService.m
This PR is simply pulling in the changes from #10017 into `release/10.7`.
Tagging @ctarda because you reviewed the original PR :)
=> BlogService: Don't double-filter blogs when searching by hostname (10.7)

README.md
Fixes: just minor formatting 
To test: there is no break in the code. Just formatting proposals
=> Minor formatting (proposals)

Podfile, Podfile.lock
Update Podfile to the released versions
=> Update Podfile to the released versions

README.md
This PR updates `README.md` to reflect the current versions of Xcode & Swift in use. It also corrects addresses a formatting error surrounding _WordPress for iOS_.
=> Updated README to reflect the in-use versions of Xcode & Swift

WordPress/Classes/Services/SiteManagementService.swift, WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
Refs #9447
With this PR completing the entire quick start checklist for a blog will grant an award!
Thanks to @danielebogo for doing the heavy lifting in #10284 😀 
To test:
- Complete an entire quick start checklist, then check for the award in notifications 😀
=> Quick Start: completion award

Podfile, Podfile.lock
Update dependencies to the released versions
=> Update dependencies to the released versions

WordPress/Classes/Extensions/NSURLCache+Helpers.swift, WordPress/Classes/Services/NotificationActionsService.swift
This PR removes some commented out code, and tidies up one small typo I found. This is undoubtedly not the _only_ place in the code base like this, but it's worth taking care of.
Checkout the branch and verify that existing tests pass. Perform a cursory "smoke test" of the app.
=> Removed some commented out code

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Fixes #10422.
- Verify that the branch compiles and existing tests pass.
- Reproduce the steps in the issue report, and observe the empty space is no longer visible.
=> Resolved visual defect after editing visible blog list

WordPress/Classes/Categories/UIApplication+Helpers.h, WordPress/Classes/Categories/UIApplication+Helpers.m, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressScreenshotGeneration.xcscheme, WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
To test: Run the screenshot suite!
=> Remove autocorrect bar from screenshots

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Refs #10304
This puts v1 of History/Revisions live!
To test:
- You could see if a release build has revisions, or you could look at the code and speculate if it works 😆
=> Revisions: turn Revisions on for everyone

WordPress/Classes/Utility/Automated Transfer/AutomatedTransferHelper.swift, WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController+LocalizedStrings.swift
=> Fix sucesfully

WordPress/Classes/ViewRelated/Me/AboutViewController.swift
Merge release 11.3.1 into 11.4
=> Merge release 11.3.1 into 11.4

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Fixes #10301 
To test:
On an iPad, in landscape, delete a site and make sure the app doesn't crash. 
=> Check if the indexPath is valid before selecting it

Podfile, Podfile.lock
This PR just changes the Aztec pod to use a version number instead of a commit number.
This PR doesn't change any functionality.
=> Integrates Aztec using the version number of the pod.

RELEASE-NOTES.txt
Small PR about the `RELEASE-NOTES.txt`.
File updated after #10584 being merged.
=> Update release notes

WordPress/Classes/Models/SiteSegment.swift, WordPress/Classes/Models/SiteVertical.swift, WordPress/Classes/Services/SiteSegmentsService.swift, WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreator.swift, WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreatorOutput.swift, WordPress/WordPressTest/SiteCreation/SiteAssemblyServiceTests.swift, WordPress/WordPressTest/SiteCreation/SiteCreatorTests.swift, WordPress/WordPressTest/SiteCreation/SiteSegmentTests.swift, WordPress/WordPressTest/Test Data/site-segment.json
Fixes #10670.
To test:
- Perform a cursory pass through the enhanced site creation flow.
=> Modified the segment & vertical identifier types to match services

Podfile, Podfile.lock, WordPress/Classes/System/WordPressAppDelegate+Swift.swift
Merges out-of-date dependencies in preparation for 11.7
=> Update dependencies for 11.7

Podfile, Podfile.lock
Update pods to released version for 11.8 code freeze.
=> Update pods to released version for 11.8 code freeze

Podfile, Podfile.lock
This applies all changes in Automattic/Automattic-Tracks-iOS#93 and completes the #11003 task.
=> Upgrade Automattic-Tracks to 0.3.2-beta.1

Podfile, Podfile.lock
Fixes the issue described here https://github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view/pull/5
=> Update react-native-keyboard-aware-scroll-view ref

Podfile, Podfile.lock
This PR updates the dependencies to released versions.
=> Update dependencies to released versions

Scripts/fastlane/Fastfile, Scripts/fastlane/appstoreres/metadata/source/screenshot_1.html, Scripts/fastlane/appstoreres/metadata/source/screenshot_2.html, Scripts/fastlane/appstoreres/metadata/source/screenshot_3.html, Scripts/fastlane/appstoreres/metadata/source/screenshot_4.html, Scripts/fastlane/appstoreres/metadata/source/screenshot_5.html, Scripts/fastlane/appstoreres/metadata/source/screenshot_6.html, WordPress/Resources/AppStoreStrings.po
Adds enhanced screenshot files, references, and keys for automated upload to GlotPress.
**To test:**
- Make a change in one of the enhanced screenshot text files
- Run `bundle exec fastlane update_appstore_strings`
- See the new change reflected in the `.po` file
=> Add enhanced screenshots

WordPress/Classes/Models/StatsRecord+CoreDataClass.swift, WordPress/Classes/Models/StatsRecord+CoreDataProperties.swift, WordPress/Classes/Utility/PushNotificationsManager.swift, WordPress/Classes/WordPress.xcdatamodeld/WordPress 87.xcdatamodel/contents, WordPress/WordPressTest/ClicksStatsRecordValueTests.swift, WordPress/WordPressTest/CountryStatsRecordValueTests.swift, WordPress/WordPressTest/ReferrerStatsRecordValueTests.swift, WordPress/WordPressTest/StatsRecordTests.swift, WordPress/WordPressTest/StatsTestCase.swift, WordPress/WordPressTest/TopViewedStatsTests.swift, WordPress/WordPressTest/TopViewedVideoStatsRecordValueTests.swift, WordPress/WordPressTest/VisitsSummaryStatsRecordValueTests.swift
I started doodling around on connecting `Core Data` to our `Store`s and quickly realized I forgot a _fairly important field when modeling the Core Data entities 🤦‍♂️ . This fixes it :)
To test:
Verify the tests still pass
=> Add `period` field to `StatsRecord`

.configure
Updates the build configuration to the latest version.
To test:
=> Update the project configure file to the latest

Podfile, Podfile.lock
Update to released Pods for 12.0
=> Update to released Pods for 12.0

WordPress/Classes/Models/StatsRecord+CoreDataClass.swift, WordPress/Classes/Models/TodayStatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/TodayStatsRecordValue+CoreDataProperties.swift, WordPress/Classes/WordPress.xcdatamodeld/WordPress 87.xcdatamodel/contents, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/TodayStatsTests.swift
Another one I somehow forgot before! 
Includes mapping from WPKit model and tests ;P
=> Add missing TodayStats entity

WordPress/Classes/System/WordPressAppDelegate+openURL.swift
Same as #11233, but targetting release/12.0.
=> Fix compiler warning

Scripts/fastlane/Deliverfile
Wow, those were some old docs in there - amazing to see how long you've been using fastlane :)
=> Remove old comments from Deliverfile

Podfile, Podfile.lock
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/671
**To Test**
Follow steps on gutenberg-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/742
=> [Gutenberg]Update heading placeholder size on heading level change

WordPress/Classes/Utility/Debouncer.swift
Merging the fixes from release/11.9.1 into release/12.0
=> Merge release/11.9.1 into release/12.0

WordPress/Classes/Stores/StatsPeriodStore.swift, WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
Fixes #11283 
To test:
- Go to Period > Published > View more.
- Verify all published posts are listed (instead of just the top 6 that was done with #11282).
=> [Stats Refresh] Period Published detail list: correct data with new API

Podfile, Podfile.lock
This PR updates the pods reference to the released versions (instead of the beta ones)
=> Update to released pods

Podfile, Podfile.lock, WordPress/Classes/Models/ClicksStatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/ClicksStatsRecordValue+CoreDataProperties.swift, WordPress/Classes/Models/CountryStatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/OtherAndTotalViewsCount+CoreDataClass.swift, WordPress/Classes/Models/OtherAndTotalViewsCount+CoreDataProperties.swift, WordPress/Classes/Models/ReferrerStatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/SearchResultsStatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/StatsRecord+CoreDataClass.swift, WordPress/Classes/Models/StatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/TagsCategoriesStatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/TopViewedAuthorStatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/TopViewedPostStatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/TopViewedPostStatsRecordValue+CoreDataProperties.swift, WordPress/Classes/Models/TopViewedVideoStatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/TopViewedVideoStatsRecordValue+CoreDataProperties.swift, WordPress/Classes/Models/VisitsSummaryStatsRecordValue+CoreDataClass.swift, WordPress/Classes/Models/VisitsSummaryStatsRecordValue+CoreDataProperties.swift, WordPress/Classes/WordPress.xcdatamodeld/WordPress 87.xcdatamodel/contents, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/ClicksStatsRecordValueTests.swift, WordPress/WordPressTest/CountryStatsRecordValueTests.swift, WordPress/WordPressTest/ReferrerStatsRecordValueTests.swift, WordPress/WordPressTest/StatsRecordTests.swift, WordPress/WordPressTest/StatsTestCase.swift, WordPress/WordPressTest/TopViewedStatsTests.swift, WordPress/WordPressTest/TopViewedVideoStatsRecordValueTests.swift, WordPress/WordPressTest/VisitsSummaryStatsRecordValueTests.swift
This should be the last "big" PR for Stats! 
Sorry for the large size — It's rather verbose code, but most of it is very same-y and boring and not very interesting or clever.
I have half-finished branch of making `StatsPeriodStore` making use of this — but having all this mapping code, switching the `Store` over to the new WPKit API _and_ making it use Core Data is WAY to big to be a single PR, so I'm breaking this up. The rest will come tomorrow :)
To test:
Nothing to really see here yet!
Make sure the tests pass — I'll add more tests specifically targeting this and you'd be able to see it in action with the subsequent PRs :)
=> [Stats Refresh] TimeInterval/Period mapping code

WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
This PR resolves a recently introduced warning.  It does not have an accompanying issue.
Just build the app, run the unit tests and make sure all is fine.
=> Site Creation: Fixes a warning.

RELEASE-NOTES.txt
Resolves #11355 
This PR updates our release notes for 12.2 to report the improvements we've made to the Site Creation process.
=> Site Creation: Updated the release notes.

Podfile, Podfile.lock
This PR simply update the _Podfile_ updating 2 pods:
• **WordPressKit** `~> 4.0.0-beta`
• **WordPressAuthenticator** `~> 1.4.0-beta`
=> Podfile Update

RELEASE-NOTES.txt, WordPress/Classes/ViewRelated/Site Creation/Wizard/WizardNavigation.swift
Proposes a fix for #11388. 
While we've been unable to reproduce this through manual testing, a few improvement opportunities were identified & implemented. Moreover, an additional logging statement was added to confirm potential recurrences.
To test:
- Navigate through the new Site Creation flow, confirm that it continues to work without regression.
cc: @diegoreymendez would you have capacity to review this change, please?
=> Simplified the wizard navigation index tracking in site creation flow

Podfile, Podfile.lock
I forgot to update the Podfile and release the WPKit before merging the previous PR :(
@ScoutHarris would you do me the honor of rubber-stamping this one :)?
=> point WPKit to a release, not a branch name

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Fixes #11467 - subtask - create feature flag
To test:
* Verify feature flag is off with test code.
=> Add domain credit feature flag (turned off)

WordPress/WordPressTest/AbstractPostTest.swift, WordPress/WordPressTest/NewsCardTests.swift, WordPress/WordPressTest/PostTests.swift, WordPress/WordPressTest/ReaderFollowedSitesStreamHeaderTests.swift, WordPress/WordPressTest/ReaderPostCardCellTests.swift, WordPress/WordPressTest/SearchMenuItemCreatorTests.swift
I set my device in Hebrew and noticed that 26 tests were failing. This PR is fixing these tests by localizing some of the strings.
To test:
1. run tests on develop. see 26 tests fail. 
2. checkout this branch.
3. run test see that they all pass
=> Fixing tests for localization.

Podfile, Podfile.lock
Fixes #11515 
A detailed description of the issue and the fix can be found in the [related Aztec PR.](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1178).
To test:
- Follow the steps described on #11515 and check that the issue is fixed.
- Follow the steps described on https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1178 .
- Smoke test other aspects of Aztec.
- Smoke test Gutenberg.
cc @jkmassel
=> Update Aztec ref to test fix #11515

WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
Fixes #11491.
To test:
- Checkout the branch, verify it builds, and that tests pass.
- Replicate the steps in the issue with VoiceOver, and verify that the accessible description is read. It should be specialized for each unique step.
@danielebogo or @nheagy, would one of you be willing to take a look at this?
=> Improved accessibility of close button in Quick Start checklist

WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift, WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
Fixes #11489.
To test:
- Checkout the branch, verify it builds, and that tests pass.
- Replicate the steps in the issue with VoiceOver, and verify that the accessible description is read.
@danielebogo or @etoledom , would one of you be willing to take a look at this?
=> Added accessibility label to add image in new user epilogue

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Fixes #11571 
This PR fix the problem with QuickStart and the first row selected. I used `BlogDetailsSectionCategory` enum recently introduced to easily update the stored indexPath with the new index. Because we have dynamic sections like QuickStart or Domain Credit, we need to update the stored indexPath even when the dataModel change.
• Add a new site
• When the QuickStart alert appears click _Yes, Help Me_ to activate it
• The selected default row should be _Stats_
=> [Quick Start] Wrong cell selected as soon QuickStart is activated

WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift, WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes 3 warnings in the project.
To test: simply build the app and make sure there are no warnings in the modified lines of code.
=> Fixes 3 warnings in the project.

WordPress/Classes/Utility/Logging/WPCrashLogging.swift, WordPress/Classes/Utility/Sentry/WPCrashLogging.swift
**To Test:**
Run the app in debug mode, and ensure you're logged in. 
If the app doesn't crash, everything is working.
If you want to get really fancy, you could run a release build and cause a crash, but that shouldn't be necessary 😄
=> Clean up Sentry logs + Fix user attribution + Improve Sentry Testability

WordPress/Resources/AppStoreStrings.po
Gonna merge this myself to fix the issue discussed in https://wordpress.slack.com/archives/C02RQC4LY/p1557767471012600, but adding @loremattei as an FYI
=> Fix 12.4 release notes

README.md
Condensed Steps are a shortened version of the build instruction steps in a numbered list.
=> Add Condensed Steps to Build Instructions

Podfile, Podfile.lock, RELEASE-NOTES.txt
Fixes #11682
To test:
- Open post using the editor Aztec
- Select and copy some of its content
- Try to paste in another app ( Notes for example)
- See that the content is properly pasted.
=> Update Aztec version to 1.6.1.1

README.md, SECURITY.md
Adds some details on how to report security issues.
=> Add responsible disclosure policy

WordPress/Classes/Utility/PingHubManager.swift
I added a precondition to make sure we're not trying to change state from different threads at once, then ensured the account changed and reachability callbacks were being dispatched on the main queue.
@jkmassel this seems like it should cover the cases I've seen in the stack traces, but I'm wondering if you saw anything else I might have missed.
Fixes #11399
To test:
I couldn't reproduce the original crash, so there are no good testing instructions. What I did test was enabling the `-debugPinghub` argument, and trying to go through all the state changes and see that PingHub did the right thing:
- Log in and out of the account
- Switch to foreground/background
- Toggle airplane mode on/off
=> Ensure PingHubManager state changes on main thread

WordPress/WordPress.xcodeproj/project.pbxproj
To test: Run `bundle exec pod install` in the project directory. There should be no warnings.
=> Fix merge issue

Podfile, Podfile.lock
**To test:**
- Verify that the new ref looks correct
- See that tests pass
=> Use the correct `wordpress-shared` reference

WordPress/Classes/Services/EditorSettingsService.swift
Fixes an issue where the bulk editor setting post request for all blog might not be set properly on the server.
This PR makes all the request run sequentially.
Let's also keep an eye on a possible backend solution: https://github.com/Automattic/wp-calypso/issues/34999
To test:
- Instal WP v12.9
- Enable Gutenberg on App Settings
- Migrate to v13.0 (this branch)
- Check in your user report card that all your blogs were set to gutenberg.
=> [Gutenberg] Use a queue to post editor settings sequentially

WordPress/Classes/Services/MediaCoordinator.swift
Fixes #12213. 
This is a backport of a fix from #12214 to 13.0 release train.
=> Backport #12214 to 13.0

WordPress/Classes/Services/MediaCoordinator.swift
Fixes #12213. 
This is a hotfix backporting a fix from #12214 to 12.9 release.
=> Hotfix: merge #12214 to 12.9

WordPress/Classes/Services/MediaCoordinator.swift
This is a backport of #12292 to release/13.0 branch!
=> Backport notices fix to 13.0

Podfile, Podfile.lock
=> Update pods for release

WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/WPAccount+AccountSettings.swift, WordPress/Classes/Services/BlogService.h, WordPress/Classes/Services/BlogService.m, WordPress/Classes/System/WordPressAppDelegate.swift, WordPress/Classes/Utility/AccountHelper.swift, WordPress/Classes/Utility/ZendeskUtils.swift
As we try to sort out why sometimes users get duplicate sites, we should add more detailed information to the logs so we can know exactly what's in core data.
Refs #7886 
----
Before:
```
2019-08-28 18:18:11:988 WordPress[58546:4634037] wp.com account: kokejb7 (ID: 54822278) (verified)
2019-08-28 18:18:11:988 WordPress[58546:4634037] All blogs on device:
2019-08-28 18:18:11:990 WordPress[58546:4634037] <Blog Name: Koke's .org Sandbox URL: https://sandbox.koke.me XML-RPC: https://sandbox.koke.me/xmlrpc.php jetpack: 🚀✅ Jetpack 7.5.3 connected as kokeme with site ID 137551970>
2019-08-28 18:18:11:990 WordPress[58546:4634037] <Blog Name: Koke's Test Blog #7 URL: https://kokejb7.wordpress.com XML-RPC: https://kokejb7.wordpress.com/xmlrpc.php wp.com account: kokejb7 blogId: 57360227 plan: Free …
```
=> Improve logging of accounts and blogs

WordPress/Classes/Services/CommentService.m
Refs: #11384 
This PR is an attempt at addressing the crash in #11384.  There is some background that gives context to these changes in the issue, but the tl;dr is ReaderComments were saved on a derived context, but not via the intended mechanism.  Its theorized this allowed for circumstances that result in the WPTableViewHandler crash. 
The PR does two things:
- Ensures a failure block is called from the main thread.
- Ensures that a derived context is properly saved.  Some code was slightly refactored to allow for this.
To test:
Open the reader and view comments for several posts. 
Ensure comments are correctly loaded. 
Try liking or replying to a comment. 
Ensure content updates and nothing goes 💥 .
@astralbodies since this deals with main and derived contexts I'd …
=> ReaderComments: Adjust comment service save behavior.

WordPress/Classes/Services/AccountService.m, WordPress/WordPressTest/AccountServiceTests.swift
This is a copy of https://github.com/wordpress-mobile/WordPress-iOS/pull/12412 that ports the fix into our forthcoming `13.2.xx` release.
=> Merge Duplicate Sites Fix into 13.2.xx Part 1

WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift, WordPress/WordPressUITests/Screens/BaseScreen.swift, WordPress/WordPressUITests/Screens/Login/LoginEpilogueScreen.swift, WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
**To test:**
- Ensure UI Tests pass
**Update release notes:**
=> Fix UI tests for iOS 13

WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift
=> Stop logging preview failure

Podfile, Podfile.lock
This PR updates the pods that are in beta version, to the latest release. 
=> Update beta pods to release version

RELEASE-NOTES.txt
I avoided adding too much detail. I think this explains it enough. But please let me know if:
- I missed something
- You have suggestions
- Only 1 reviewer is needed but anyone can review. 
- Please merge it if you approve of the change and are not requesting any changes.
=> Add release notes for Offline Posting

Podfile, Podfile.lock
This PR updates the `beta` pods to their final version.
To test:
Check CircleCI is green.
=> Update dependencies to released versions.

Podfile, Podfile.lock
Update Pods to the released versions
=> Update Pods to the released versions

WordPress/Classes/ViewRelated/Post/Scheduling/CalendarCollectionView.swift, WordPress/Classes/ViewRelated/Post/Scheduling/CalendarMonthView.swift, WordPress/Classes/ViewRelated/Post/Scheduling/ChosenValueRow.swift, WordPress/Classes/ViewRelated/Post/Scheduling/HalfScreenPresentationController.swift, WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift, WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController.swift
Addresses feedback on PR https://github.com/wordpress-mobile/WordPress-iOS/pull/12820.
This should address everything commented on by @danielebogo and @frosty
=> PR Feedback corrections

WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift, WordPress/Classes/System/WordPressAppDelegate.swift, WordPress/Classes/ViewRelated/Post/Scheduling/CalendarCollectionView.swift, WordPress/Classes/ViewRelated/Post/Scheduling/CalendarMonthView.swift, WordPress/Classes/ViewRelated/Post/Scheduling/ChosenValueRow.swift, WordPress/Classes/ViewRelated/Post/Scheduling/HalfScreenPresentationController.swift, WordPress/Classes/ViewRelated/Post/Scheduling/LightNavigationController.swift, WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift, WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj
This addresses the latest PR comments from @frosty and @danielebogo on PR https://github.com/wordpress-mobile/WordPress-iOS/pull/12820
=> Address PR comments

Podfile, Podfile.lock, RELEASE-NOTES.txt
To test:
- Smoke test the GB editor
- Check that tapping on links is working correctly
- Check that inserting new lines in multiline blocks ( quote, lists, image captions) works correctly
=> Update gutenberg to 1.16.1

Podfile, Podfile.lock, WordPress/Classes/Utility/ZendeskUtils.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #12977 
To test:
- Go to Me > Help & Support > Contact Us.
- Submit a request.
- In Zendesk, find your ticket.
- Verify these fields have information:
- WP Mobile App Version Number
- WP Mobile App Blog Info
- Free Space
- WP Mobile App Other Info
- System Status Report
- Current Site
- WP Mobile App Platform
- WP Mobile App Language
=> Zendesk: update to 4.0.0

WordPress/Resources/AppStoreStrings.po, WordPress/Resources/release_notes.txt
Merge Release/13.8 into develop
=> Merge Release/13.8 into develop

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Fixes #12872, Fixes #12870 with issues addressed in #13038. I apologize @shiki, I was having issues building and didn't realize deleting the remote branch would close the other pull request. The issues you brought up have been taken care of, though!
To test:
=> [VoiceOver] Add accessibility to Post List buttons

Podfile, Podfile.lock, WordPress/Classes/System/WordPressAppDelegate.swift, WordPress/WordPressDraftActionExtension/WordPressDraft-Lumberjack.m, WordPress/WordPressDraftActionExtension/WordPressDraftPrefix.pch, WordPress/WordPressShareExtension/WordPressShare-Lumberjack.m, WordPress/WordPressShareExtension/WordPressSharePrefix.pch
**To test:**
1. Enable the Address Sanitizer
2. Run the application in the Simulator.
3. It should no longer crash on startup.
=> Fix CocoaLumberjack memory layout issue

WordPress/Resources/release_notes.txt
=> Update AppStore release notes

RELEASE-NOTES.txt, WordPress/Classes/Stores/StatsPeriodStore.swift, WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Merge release 13.8.1 into 13.9
=> Merge release 13.8.1 into 13.9

WordPress/Classes/Extensions/WKWebView+SynchJSEvaluation.swift, WordPress/Classes/System/WordPressAppDelegate.swift, WordPress/Classes/Utility/WPUserAgent.h, WordPress/Classes/Utility/WPUserAgent.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/WPUserAgentTests.m
Fixes #13184 
Implements side by side testing of the User Agent
Run the unit tests and make sure they work properly.
Check the code and make sure the changes make sense.
=> Implements tests for getting the user agent in WKWebView.

WordPress/Classes/Utility/WPMediaEditor.swift, WordPress/MediaEditor/Enums/MediaEditorStyle.swift, WordPress/MediaEditor/MediaEditor.swift, WordPress/MediaEditor/MediaEditorHub.storyboard, WordPress/MediaEditor/MediaEditorHub.swift, WordPress/MediaEditor/MediaEditorThumbCell.swift, WordPress/WordPressTest/MediaEditor/MediaEditorHubTests.swift, WordPress/WordPressTest/MediaEditor/MediaEditorTests.swift
Fixes #13209
Refinements on the Media Editor design.
=> Portrait design

Podfile, Podfile.lock, WordPress/WordPressUITests/Screens/FancyAlertComponent.swift
**To test:**
- Ensure that UI tests pass in CI
**PR submission checklist:**
=> Update FancyAlertView accessibilityIDs

README.md
This is a quick update to the README.md to clarify some instructions, and incorporate some [feedback shared in Slack](https://wordpress.slack.com/archives/C02RQC4LY/p1578522445001300) by a recent contributor (h/t @kduncanwelke ).
It also updates the minimum Xcode version. 
To test:
Read the changes.  Check the grammar and spelling.  Confirm everything still makes sense.
@designsimply would you be game for a review? 
cc @jkmassel as you showed some interest in the Slack conversation.
=> Updates to the README.md based on contributor feedback.

.github/PULL_REQUEST_TEMPLATE.md
I am proposing that we incorporate accessibility checks within our pull request review process by amending the pull request template as seen in this PR. Enforcement of these accessibility processes and principles will further our commitment to creating products that are accessible end to end.
The process that would support this change is:
* The reviewer of the PR would verify that the feature was made accessible using the accessibility guidelines and testing tools. 
* If making a component accessible is difficult or not enough time is left in a sprint to allow it, then an issue should be created so that it can be tracked and included in future Accessibility projects. 
These are the benefits of this approach: 
* It’s likely that the person who is developing a feature has the most context …
=> Update PR Template For Accessibility

WordPress/Classes/Utility/WebKitViewController.swift, WordPress/Classes/Utility/WebViewControllerConfiguration.swift, WordPress/Classes/ViewRelated/Post/Preview/PreviewDeviceSelectionViewController.swift, WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift, WordPress/WordPressTest/ViewRelated/Post/Controllers/PreviewWebKitViewControllerTests.swift
#13197
[Voice Over Video](https://imgur.com/a/rQW9vIz)
To test:
- Use Voice Over on the web page preview screen
- Use Accessible text sizes and check the HUD displayed when tapping and holding navigation and toolbar items.
=> Post Preview: Accessibility label / font fixes

WordPress/Classes/Utility/CookieJar.swift, WordPress/Classes/Utility/WPUserAgent.m, WordPress/Classes/Utility/WPWebViewController.m
=> Remove UIWebView from comments and method names

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift, WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift, WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
The green build should be enough.
=> [Media Editing] Remove Feature Flag

WordPress/Classes/ViewRelated/Blog/SharingAuthorizationWebViewController.swift
Removes several comments that were supposed to be removed before merging https://github.com/wordpress-mobile/WordPress-iOS/pull/13389 but weren't. 🤦‍♂️
Closes https://github.com/wordpress-mobile/WordPress-iOS/projects/14
Apologies @leandroalonso !
Also tweaks a few method names a bit to make them more readable.
Just make sure the app builds and the tests succeed.
=> Removes several comments and improves some method names.

Podfile, Podfile.lock
This PR updates pods to their final, not beta version, in preparation for the upcoming code freeze.
To test:
- CI is green
=> Update pods for releases

Podfile, Podfile.lock, RELEASE-NOTES.txt
Fixes #
Updates Aztec to version 1.16.0
To test:
- Smoke test the Aztec and Guterberg editor
- Pay special attention to the lists blocks
- Test the case where we have ordered lists with large numbers
=> Update Aztec to version 1.16.0

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Fixes #13487 
Create a new post, tap "..." and then "Post Settings":
1. Check that `Tracked: post_settings_shown` appears in the console when Post Settings appear
2. Tap "Tags" and check that `Tracked: post_settings_add_tags_shown` appears in the console
1. Add a new tag and tap back, check that `Tracked: post_settings_tags_added` appears in the console
1. Tap "Tags" again and then "Back", check that nothing appears in the console
1. Clear all tags and tap back, check that no track appears in the console
=> Track adding tags in Post Settings

WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift, WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
Fixes #13592 
This is so https://github.com/wordpress-mobile/WordPress-iOS/pull/13597 that was approved can be merged to 14.4
=> Show loading indicator when searching domains for 14.4 release

WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
To test
1. Go to reader
2. Go to search 
3. See keyboard up and cursor in search bar 
=> Auto focus Reader search bar 

WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift, WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift, WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift, WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift, WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Fixes #13660
Make sure to enable the keyboard appearing on your simulator or use a real device.
2. Tap "Publish"
3. Tap "Tags" on the bottom sheet
4. Fill some tags, tap back
5. Check that the tags were applied and are appearing in the cell label
Ignore the navigation bar, it will be redesigned in a future task.
=> Add tags field

WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift, WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/Bottom Sheet/BottomSheetViewControllerTests.swift, WordPress/WordPressTest/PrepublishingNudgesViewControllerTests.swift
Fixes #13694
1. Create a Post
2. Tap Publish
3. Confirm by tapping "Publish Now"
4. Check that the post was successfully published
=> Add "Publish Now" button

RELEASE-NOTES.txt
This PR merges the `hotfix/14.4.1` branch into `release/14.5`. 
As discussed, the changes in the hotfix branch are not required in the release branch, so the only actual change is in the release notes file.
=> Merge hotfix/14.4.1 into release/14.5

WordPress/Classes/Models/AbstractPost+TitleForVisibility.swift, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/PostVisibilitySelectorViewController.swift, WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PasswordAlertController.swift, WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift, WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/UIPasswordAlertController.swift, WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #13695
2. Tap "Publish"
3. Select "Public" visibility
4. Tap Publish
5. Check that the post was published and it's public
2. Tap "Publish"
3. Select "Password Protected" visibility
4. Enter a password
5. Tap Publish
6. Check that the post was published and it's protected by a password
2. Tap "Publish"
3. Select "Private" visibility
4. Tap Publish
5. Check that the post was published and it's private
=> Add "Visibility" option

Podfile, Podfile.lock
Update dependencies for release
=> Update dependencies for release

WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift, WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift, WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
Fixes #13801 
1. Open the Nudges View
2. Go landscape
Also, open the Nudges view while in Landscape and alternate between Portrait/Landscape.
The landscape code comes from @bjtitus `BottomSheetPresentationController`, all credits to him. :)
=> Adapt the Bottom Sheet for Landscape

WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorClient.swift, WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorGIF.swift, WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorGIFCollection.swift, WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorMediaObject.swift, WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorReponseParser.swift, WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorResponse.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/MediaPicker/Tenor/TenorAPIResponseTests.swift, WordPress/WordPressTest/MediaPicker/Tenor/TenorReponseData.swift
This is a smaller PR split from #13830 as suggested by @frosty, This is a part of #13803
**Test**
This PR doesn't include any end-user feature for testing. It just needs code review.
=> Implement Tenor client api

WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift, WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.swift, WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.xib, WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift, WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Fixes #13802
To test:
1. Open the Nudges view in an iPad
2. Check if it behaves correctly
The design was approved by @mbshakti.
=> Adapt Nudges view for iPad

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift, WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift, WordPress/WordPressTest/ReaderDetailViewControllerTests.swift, WordPress/WordPressTest/ReaderPostCardCellTests.swift
Fixes #NA
To test:
- Check that the reblog feature works as expected
=> Remove post reblogging feature flag

.circleci/config.yml, Podfile, Podfile.lock
In preparation to 14.8 code freeze, this PR updates the beta pods to the release version.
=> Update pods to released version

Podfile, Podfile.lock, RELEASE-NOTES.txt
To test:
- Smoke test the Aztec editor
- Smoke test the Gutenberg editor
=> Update aztec version to 1.19.0

Podfile, Podfile.lock
To test:
- Create a new post using Gutenberg
- Make sure the app doesn't crash
=> Update GB version with new JS bundles

Gemfile, Gemfile.lock, Scripts/fastlane/Pluginfile
This PR updates `fastlane` and its plugins.
There are no critical changes listed in the changelogs, so this PR is aimed to just keep our tools up to date. 
=> Update fastlane and plugins

RELEASE-NOTES.txt, WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
REF: [IA Project](https://github.com/wordpress-mobile/WordPress-iOS/projects/15)
To test:
- Check that the release notes are updated with content related to FAB, Me and Reader
=> Add release notes for the new IA features (FAB, Me and Reader)

WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift, WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
Just check the code and the renames. :)
=> Rename post settings/nudges events to match Android

RELEASE-NOTES.txt, WordPress/Classes/Networking/MediaRequestAuthenticator.swift, WordPress/Classes/Utility/Media/ImageLoader.swift, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
=> Merge release 14.8.1 into 14.9

WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Merge release 14.8.2 into 14.9
=> Merge release 14.8.2 into 14.9

RELEASE-NOTES.txt
An update to the release notes for missing new feature in the block editor.
To test:
- Check if release notes are correct and contain the missing feature in the block editor
=> Update release notes with missing new feature in the block editor.

WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
Fixes #14147 
To test:
-  go to the Reader screen
- switch between tabs and/or filter sites or tags. Try to switch between sites with posts that have no featured image and posts that have one
- verify that the layout of the cells looks correct
=> Reader - Remove buttons animation

WordPress/Classes/Extensions/UITableViewCell+enableDisable.swift, WordPress/Classes/Extensions/WPTableViewCell+enableDisable.swift, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/PostVisibilitySelectorViewController.swift, WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #13966 
Please, test with the Prepublishing Nudges and the Post Settings.
1. Schedule a post
2. Change the visibility to private
3. Check that the post is not scheduled anymore and you can't schedule
4. Change the visibility to public
5. Check that you can schedule again
=> Do not allow scheduling a private post

Podfile, Podfile.lock
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2274
To test:
- Smoke test the Aztec and Gutenberg editors
- Check the scenario describe in the bug above
=> Update Aztec to version 1.19.2

RELEASE-NOTES.txt
Updating release notes for gutenberg 1.29.0
=> Update release notes for Gutenberg 1.29.0 changes

RELEASE-NOTES.txt, WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
Fixes #14072 
To test:
Check that the Published date under Stats->Insights is correct on sites configured across different timezones.
=> Update Stats->Insights Latest Post date calculations

RELEASE-NOTES.txt, WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Ref #13803 
This enables Tenor (Free GIF Library) feature.
To test:
- Go to Media > Add > Free GIF Library.
- Enter a search term.
- Verify search results are displayed.
=> Enable the Tenor feature flag.

MIGRATIONS.md
Fixes #NA
To test:
NA - No changes in functionalities
=> Update Migrations.md for WordPress 96

WordPress/Classes/Services/AuthenticationService.swift, WordPress/Classes/Utility/CookieJar.swift, WordPress/Classes/ViewRelated/Reader/ReaderRelativeTimeFormatter.swift, WordPress/WordPressTest/ReaderRelativeTimeFormatterTests.swift
This PR brings the changes from https://github.com/wordpress-mobile/WordPress-iOS/pull/14360 to the `release/15.1` branch.
Changes have been tested and approved via the mentioned PR.
To test (steps from https://github.com/wordpress-mobile/WordPress-iOS/pull/14360):
- Clean install the WordPress app.
- Login to a WPCom account.
- Create a new post on a blog that's not private Atomic.
- Write something and choose to preview (without publishing).
- Check that the preview works.
=> Fix webviews auth issues

Scripts/fastlane/appstoreres/metadata/source/description.txt
This PR adds a non-clickable link to the CCPA the App Store description.
=> Add CCPA link to the store description

WordPress/Classes/ViewRelated/Reader/DetailWebView/ReaderWebView.swift
Fixes Reader embeds for: Instagram, Twitter, Facebook, Tumblr, and Reddit.
1. Open this post in Reader: https://charlietest12345.blog/2020/07/02/embeds/
2. Check that all embeds work (Instagram, Twitter, Facebook, Tumblr and Reddit)
=> Fix Reader embeds

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
This PR implements changes from https://github.com/WordPress/gutenberg/pull/23956
To test:
- Run the project.
- Check that @-Mentions works as expected when it should be available.
- Check that Unsupported Block Editor works as expected when it should be available (i.e: Simple WPCom site).
=> [Gutenberg] Implement Capabilities changes from GutenbergDataSource

Podfile, Podfile.lock
WPAuth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/364
This PR addresses two issues with the analytics tracking in the basic Google authentication flow.
1. It tracks the start of the signup flow if the user is logging in with Google, and a matching WPCom account does not exist.
2. It tracks the success of the login flow when logging in through Google, when the WPcom account has a 2FA code set.
- Enable `unifiedGoogle`
- Make sure your Google account isn't linked with a WPcom account, and the email isn't used by an existing WPcom account.
1. Log in with Google.
2. Select your Google account and log in.
3. Complete the process.
You should see this sequence of tracking events.  The one I maked in bold is the one that is missing when you run the same steps in …
=> Fixes some issues with the basic Google Authentication flow tracking.

Podfile, Podfile.lock
Refs https://github.com/Automattic/Automattic-Tracks-iOS/pull/142
Updates to the latest version of tracks
To test:
Run the branch.
Visit the tracks dashboard. Look at live events for your user. Confirm that you see the updated device width and height properties.
@bjtitus could I trouble you for a review of this one? 
cc @aforcier
=> Updates tracks version.

Podfile, Podfile.lock
Ref. #14009 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/374
This PR navigates the user to the "magic link sent!" view in the Unified Signup flow. Ensure the UI matches the design. The "Open Mail" button is not yet implemented. 
**Notes:** 
1. The unified sign up flow will **crash on purpose** if the invalid email address is not edited in the Auth branch.
2. You may get a crash when going through the signup flow. You may have to delete derived data, clean the project, and `rm -rf pods` before raking and rebuilding. The file name changes are difficult to get to stick. (`UnifiedSignUp.storyboard` changed capitalization to `UnifiedSignup.storyboard`, and git seems to be hanging onto the old file name capitalization.)
**Design**
1. Check out the Auth PR / …
=> UL&S: SignupMagicLinkViewController: display the "magic link sent" UI
