wordpress-mobile/WordPress-iOS

WordPress/WordPressApi/gencredentials.rb
Removed the warning that was spit out by `gencredentials.rb` if it didn't know what to do with a key. Some people remove keys by renaming them or have extra keys for other things they are testing so it's annoying to see warnings appear all the time that aren't really needed.
=> Removed warning for unknown keys

WordPress/Classes/ViewRelated/Pages/PagesViewController.m
Fix https://github.com/wordpress-mobile/WordPress-iOS/issues/3017
/cc @aerych can you review this? It's a quick one..
=> Make page editor show in fullscreen.

WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.h, WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m
Fix for this https://github.com/wordpress-mobile/WordPress-iOS/issues/3040
/cc @sendhil or @bummytime
=> Fix compiler warning by using parent class of post and page.

WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m
Was getting this validation warning:
The source of it was this commit(https://github.com/wordpress-mobile/WordPress-iOS/commit/4e19cf7b470efa81216de4920cc5c435daead282#diff-e0107cd042ca5ace4c94361cfc5920edR126) which renamed a method but forgot to update all of the selectors that pointed to it.
=> Fixing validation warning

WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
We weren't tracking when photos were added to the editors in Mixpanel. This PR fixes that.
cc @bummytime @diegoreymendez @meremagee
=> Adding in tracking for when photos are added

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Ratings/AppRatingUtility.h, WordPress/Classes/Utility/Ratings/AppRatingUtility.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/AppRatingUtilityTests.m, WordPress/WordPressTest/Test Data/app-review-prompt-all-enabled.json, WordPress/WordPressTest/Test Data/app-review-prompt-global-disable.json, WordPress/WordPressTest/Test Data/app-review-prompt-notifications-disabled.json
Tweaking the App Review prompt to allow for more granularity. Also added ability for app review prompt to be disabled remotely on a feature by feature basis or for the entire app.
=> Tweaking App Review Prompt

WordPress/Classes/Categories/NSBundle+VersionNumberHelper.h, WordPress/Classes/Categories/NSBundle+VersionNumberHelper.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m, WordPress/Classes/ViewRelated/System/AboutViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
Updating the usage of the version number throughout the app since we now use a separate build number for CFBundleVersion.
Note - this is a result of a discussion from #3007.
Note - this is a re-do of https://github.com/wordpress-mobile/WordPress-iOS/pull/3039
=> Updating version number usage throughout app

WordPress/Classes/System/WordPressAppDelegate.m
This PR fixes this crash in the latest internal beta:
```
0   CoreFoundation                       0x000000018458a59c __exceptionPreprocess + 132
1   libobjc.A.dylib                      0x0000000194c880e4 objc_exception_throw + 56
2   CoreFoundation                       0x000000018458a45c +[NSException raise:format:arguments:] + 112
3   Foundation                           0x00000001854114f4 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 108
4   WordPress                            0x00000001001b75ec +[AppRatingUtility assertValidSection:] (AppRatingUtility.m:319)
5   WordPress                            0x00000001001b6838 +[AppRatingUtility incrementSignificantEventForSection:] (AppRatingUtility.m:178)
6   WordPress …
```
=> Fixing AppRatingUtility crash

WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist, WordPress/WordPress.xcodeproj/project.pbxproj
Although we cleaned up our usage of how we pull version numbers in https://github.com/wordpress-mobile/WordPress-iOS/pull/3063, some external service still rely on the `CFBundleVersion` which makes it confusing when using them. For example, Mixpanel uses `CFBundleVersion` which can make it hard to figure out what version is what. As such lets drop this auto incrementing stuff for now.
=> Removing build script to increment build number

WordPress/Classes/ViewRelated/Post/EditImageDetailsViewController.m
Closes https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/518 
cc @bummytime
=> Fixes typo in text field placeholder.

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.h, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/497).
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/509).
Improves the code we had for [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/466).
This was implemented using the minimum possible logic to turn the new editor on by default.  In my opinion we should consider in the next few versions cleaning up some of the code and removing the old visual editor - also removing some of the code that was introduced in this PR, since it won't be needed anymore.
How it works, please review the logic:
- **For users who didn't have the editor in earlier versions:** the new editor is enabled as default.  The onboarding tip is shown.
- **For users who had …
=> v1 of the code that enables the new editor for all users.

.travis.yml, Scripts/build.sh
The reason sometimes out unit tests where failing while running on Travis was because of the use of xctool instead of xcodebuid to build and run unit tests.
When using xctool locally to build and test started to got the same errors has Travis. After I converted the build script to use xcodebuild the test errors stop happening.
/cc @sendhil can you please review?
=> Use xcodebuild instead of xctool to build and run tests.

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Due to localization and rotation, the blog list page edit header height is manually calculated and updated on rotation. Fixes #3135.
Here are the updated screenshots:
https://cloudup.com/ckNd_ha2FEM
@aerych May I bother you with a review? I've tested both iPhone and iPad in both rotations (including the rotation animations), however I'd feel better if you can test it out as well.
=> Blog list page header manually calculated for localization and rotation

Podfile, Podfile.lock
There was a bug with the last Lookback.io where some assets weren't loaded properly - they issued a hotfix.
=> Updating Lookback.io

WordPress/Classes/Services/AccountService.h, WordPress/Classes/Services/AccountService.m, WordPress/Classes/ViewRelated/Me/MeHeaderView.m, WordPress/Classes/ViewRelated/Me/MeViewController.m
We trigger an update on the email and default blog when the Me page loads for the first time, updating the email will now trigger an update on the gravatar. This is especially important for the initial update the 4.8 version, since we are starting to store the email in this version. The gravatar is also changed to be round.
@aerych May I bother you with another review?
=> Refresh me page gravatar once the email for the account is updated

Podfile, Podfile.lock
The latest version tweaks the email placeholder text to be "Email address" instead of "Email placeholder".
=> Bumping appbotx version

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/WhatsNew/WPWhatsNew.h, WordPress/Classes/ViewRelated/WhatsNew/WPWhatsNew.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/510).
/cc @aerych or @SergioEstevao, since you guys are online.
=> The onboarding tip will keep showing until dismissed.

WordPress/Classes/Networking/PostServiceRemoteXMLRPC.m, WordPress/Classes/Networking/Remote Objects/RemotePost.h, WordPress/Classes/Services/PostService.m
Closes #3045 
Restores the check to see if a featured image was changed. If there is no change then the `wp_post_thumbnail` param is not included in the XML-RPC request.  This avoids an odd fault returned in cases where the param is included, but there was no change.
=> Do not pass wp_post_thumbnail if it has not changed.

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
Adding a super property `seen_legacy_editor` which indicates whether a user has seen the legacy editor or not.  The code runs a one time check that will execute for WPiOS 4.8 and the logic behind detecting if a user has seen the legacy editor is:
```
if a user has created an account
if a user has the new editor active
flag the user as having not seen the legacy editor since in this case the user has created their account after 4.6 when the editor was enabled for new users
else
flag the user as having seen the legacy editor as they created their account before 4.6
end if
else if the user has a session count of zero indicating this is the first time they've opened the app
flag the user as having never seen the legacy editor since the visual editor is enabled for all users starting in 4.8 …
```
=> Flagging if users have seen leagcy editor

WordPress/Classes/ViewRelated/WhatsNew/WPWhatsNew.h
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/3187).
=> Fixes a duplicate declaration warning.

WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.h, WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m
Fixes https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/526
This fix makes the ```WPBlogSelectorButton``` act as a back button when displaying a single site in the editor (e.g. we are editing a post). If there is more than one site the blog selector screen should appear as normal.
/cc @diegoreymendez would you mind reviewing?
=> Blog picker now acts as back button when a single site is displayed.

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
This should fix #3082.
The ```post.blog.isPrivate``` call was returning ```NO``` randomly when the user really was on a private site, thus causing the loading of private images to fail. This is most likely because the blog options dictionary is getting wiped out for some reason before isPrivate is called.
After discussions with @aerych, we decided the best course for now was to enable the PrivateSiteURLProtocol  for all .com blogs (and not .org blogs).
/cc @aerych for a quick review
=> Fix for private images

WordPress/Classes/System/WordPressAppDelegate.m
In iPad we are showing a `UIActionSheet` for the Sign-out button and it acts as a `presentedViewController` for the `WPTabBarController`. Since we check `presentedViewController` and dismiss it in the `AppDelegate` before the login screen appears, that UIActionSheet was preventing login page from showing up. This case is now ignored and login page should appear even if the action sheet is not dismissed yet. Fixes #3114.
This was an interesting bug. I am not absolutely sure if this is the best way to prevent it. @jleandroperez Can I bother you with a review? Let me know if you have a better idea than checking for the `UIAlertController`.
=> iPad logout issue resolved

WordPress/Classes/ViewRelated/WhatsNew/WPWhatsNew.m, WordPress/Resources/WhatsNew/WPWhatsNewView.xib
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/512).
@bummytime - I opened [a separate issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/548) for the bug you reported about showing the onboarding tip on top of the state restored editor.
/cc @bummytime @SergioEstevao
=> Fixes a problem with a constraint.

WordPress/Classes/ViewRelated/Blog/BlogDetailHeaderView.m
Fixes #3219.
@jleandroperez Can I bother you with a review for a one-liner fix?
=> Show blog url when blog name is empty

WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/560).
It seems there's some strange problem with the legacy restoration code, when the new editor is enabled.  In order to fix this issue in a secure manner I disabled the legacy editor restoration if the new editor should be used instead - the result is that the post will be saved as draft but the legacy editor window will not be restored.
/cc @SergioEstevao
=> Fixes a restoration edge-case.

WordPress/Classes/System/WordPressAppDelegate.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/3232).
The chosen fix is not the most elegant solution.  I added notes on how the whole code can be improved [in this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/3218).
/cc @bummytime
=> Added a temporary fix to prevent the Whats New dialog from showing multiple times.

WordPress/Classes/Utility/HelpshiftUtils.m
We use a remote variable in Mixpanel to update if the Helpshift is enabled or not and since it requires a network request, it takes some time to update. Previous version of the app was trying to update this flag prematurely, this PR adds a 5 second delay (should be enough in most cases) to the flag check. It also updates the unread notification count if Helpshift is enabled. Fixes #3146.
@sendhil May I bother you with a review?
=> Delay added to Helpshift enabled flag check

WordPress/Classes/ViewRelated/Me/MeHeaderView.m
Fixes a bug caused by using `containsString` in iOS7.
/cc @sendhil
=> Fixes me page header bug for containsString usage

WordPress/Classes/ViewRelated/WhatsNew/WPWhatsNew.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/548).
Also mitigates [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/569) considerably, since it becomes a minor issue rather than a blocker.
If the Whats Up popup is shown on top of something with first responder status, its forced to resign it.
/cc @bummytime
=> Fixes a problem with the Whats New popup.

WordPress/Classes/Services/MediaService.m, WordPress/Classes/Utility/WPAssetExporter.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
This fix a bug where selecting a image from a photostream not available on the device make the app crash if trying to do it in self-hosted blog (using XML-RPC).
It also updates the error messages according to this: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/567
cc @diegoreymendez, please review.
=> Selecting image from photostream problems

WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist, WordPress/de.lproj/InfoPlist.strings, WordPress/en-GB.lproj/InfoPlist.strings, WordPress/en.lproj/InfoPlist.strings, WordPress/fr.lproj/InfoPlist.strings, WordPress/id.lproj/InfoPlist.strings, WordPress/it.lproj/InfoPlist.strings, WordPress/nl.lproj/InfoPlist.strings, WordPress/pt-BR.lproj/InfoPlist.strings, WordPress/pt.lproj/InfoPlist.strings, WordPress/th.lproj/InfoPlist.strings
Fix for this https://github.com/wordpress-mobile/WordPress-iOS/issues/3042
and general access to location services in iOS8.
cc @jleandroperez , please review.
=> Location services permission issue on ios8

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
We weren't properly aliasing new users before so when a user would create an account we'd always lose that event in any funnel because it would be associated with the randomly generated id Mixpanel would assign them. 
=> Fixing bug where we weren't properly aliasing new users in Mixpanel

WordPress/Classes/Networking/BlogServiceRemoteREST.m, WordPress/Classes/Services/BlogService.m, WordPress/WordPressTest/BlogServiceTest.m
Fixes #3266 
Adds timezone and gmt_offset to REST API call and properly retrieves the value from the gnarly options dictionary.
=> Add timezone to blog sync and fix options retrieval so it works.

WordPress/Classes/ViewRelated/Me/MeViewController.m
We wanted to make it more obvious that when you sign-out, you're actually signing out from your main WordPress.com account. So, we (with Davide) have came up with this design: https://cloudup.com/cyju4iomQb2
I am a little concerned about the "link" phrase but don't really have a better suggestion. @aerych May I bother you with a review?
Closes #3265.
=> Me page sign-in/out label and section header changed

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Stats/StatsViewController.m
1. Show connection error message as was done before 0.2.0.
2. Push chromeless web view when a URL is loaded from stats UI instead of launching out to Safari.
3. Resolved iOS 7 loading problems with Storyboard and call made to NSCalendar that doesn't exist until iOS 8.
=> Show no connection error & push web view for stats

WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/531
This PR fixes a few minor logic flaws in ```AbstractPost.hasLocalChanges``` and also now calls ```hasLocalChanges ``` in ```cancelEditing``` because ```hasUnsavedChanges``` will always return YES on new, empty posts.
/cc @SergioEstevao for PR review please and thank you! :-)
=> User can close a new, empty post without a warning

WordPress/WordPressApi/gencredentials.rb
I added a few checks to `gencredentials.rb` file that will spit out warnings when archiving the app when it detects missing keys. I figure this way we can make sure we don't send out a version of the app that's missing a critical key.
=> Adding checks to `gencredentials.rb` for missing keys

WordPress/Classes/Categories/NSProcessInfo+Util.h, WordPress/Classes/Categories/NSProcessInfo+Util.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/WordPress.xcodeproj/project.pbxproj
This should end the random tests failures we see on Travis regarding AppRatingTests.
cc @sendhil
=> Only start App tracking if not running tests.

WordPress/Classes/Utility/WPTooltip.h, WordPress/Classes/Utility/WPTooltip.m, WordPress/Classes/ViewRelated/Pages/EditPageViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.h, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
Fixes https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/511
Created a new class: ```WPTooltip``` that encapsulates the tooltip display logic along with the look & feel. Page and post VC's now call ```displayToolTipInView:fromFrame:withText:``` with the correct text.
/cc @diegoreymendez
=> Tooltip popover fix for pages

WordPress/Classes/ViewRelated/Post/EditImageDetailsViewController.m
For iOS7, update the delegate in the completion block.
Closes #3327
=> Avoid crash on iOS 7.

WordPress/Classes/ViewRelated/WhatsNew/WPWhatsNewView.h, WordPress/Classes/ViewRelated/WhatsNew/WPWhatsNewView.m, WordPress/Resources/WhatsNew/WPWhatsNewView.xib
This PR aims at fixing an exception we've been getting on launch, before the AppDelegate is even initialized (stack trace pasted below).
The issue has been tracked down to WPWhatsNewView.nib. Apparently, UIKit performs an internal initialization as soon as you launch the app, and an exception is thrown (+ captured), due to a font that's not available in the *Resources* folder.
@bummytime may i bother you with a quick review Matt?.
=> WhatsNewView: Setting OpenSans font via code

WordPress/Classes/ViewRelated/Blog/EditSiteViewController.m
to prevent row height change when transitioning to a new view, addresses #3128
=> adding missing heightForRowAtIndexPath method

Scripts/fastlane/.gitignore, Scripts/fastlane/Deliverfile, Scripts/fastlane/Snapfile, Scripts/fastlane/SnapshotHelper.js, Scripts/fastlane/deliver/metadata.json, Scripts/fastlane/shoot_the_screens.js, Scripts/fastlane/wordpress_translation_retrieval.rb
Adding in scripts utilizing https://github.com/KrauseFx/deliver and https://github.com/KrauseFx/snapshot to help automate the process of generating screenshots and uploading them to iTunes connect. Let's hold off on merging this for now until we can verify this with 4.9. Right now 4.8 is still waiting to be approved so once it's approved and off to the app store we'll run this script with a new version to make sure everything works ok.
=> Adding scripts for screenshot generation/upload

WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTextTableViewCell.swift
Fixes #3292
/cc @astralbodies (Thanks in advance!)
=> NoteBlockText: Prevents default UITextView openURL behavior

WordPress/WordPress.xcodeproj/project.pbxproj
The file's functionality was moved over to *WPURLRequest*, my bad, i definitely moved things over, and missed nuking the old category reference.
@aerych thanks for spotting this one!
=> Nukes Dead Import

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/50 (and should not break the fix here: https://github.com/wordpress-mobile/WordPress-iOS/issues/3032)
@diegoreymendez would you mind reviewing?
=> Post status not updated if post is scheduled

WordPress/Classes/ViewRelated/Reader/CommentContentView.m, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Removes iOS8 transition method. This restores calls to depreciated orientation change methods (for now).
Sets constraint priority to high instead of required.
Closes #3378
=> Fixes an issue where comment cells heights were not updated during rotation

README.md
Need to do it when setting up the project otherwise you get build errors.
=> Add note about running `pod install` when building

WordPress/Classes/System/WordPressAppDelegate.m
Closes #3385 
Sets OpenSans as the default font for `UISegmentedControl` instances in the app.
=> Add appearance API settings for UISegmentedControl to have OpenSans font

WordPress/Classes/System/WordPressAppDelegate.h, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Analytics/WPAppAnalytics.h, WordPress/Classes/Utility/Analytics/WPAppAnalytics.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/WPAppAnalyticsTests.m
The app delegate was taking care of some app tracking tasks that did not belong to `WPAnalytics`.  Since they do not belong to the app delegate either, I created a new class to take care of it.
**Test 1:**
- Run the unit tests
**Test 2:**
- Set a breakpoint in `WPAppAnalytics - trackApplicationOpened`.
- Set a breakpoint in `WPAppAnalytics - trackApplicationClosed`.
- Run the app, and make sure both are triggered.
- `po analyticsProperties` in both to make sure the data is right.
/cc @jleandroperez 
PS: Travis seems to be still failing so you'll have to check this locally.
=> Modularize app tracking

WordPress/Classes/Services/BlogService.m
Avoids fetching revisions and other unwanted post types.
Closes #3428
=> Specify post type when syncing a wpcom blog.

WordPress/Classes/Models/Blog+Jetpack.m, WordPress/Classes/Services/SuggestionService.m, WordPress/Classes/System/WordPressAppDelegate.h, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerWPCom.m, WordPress/Classes/Utility/NotificationsManager.m, WordPress/Classes/Utility/WPWebViewController.m, WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m, WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderPostsViewController.m, WordPress/Classes/ViewRelated/Reader/WPWebAppViewController.m, WordPress/Classes/ViewRelated/Settings/NotificationSettingsViewController.m, WordPress/Classes/ViewRelated/Stats/StatsViewController.m, WordPress/Classes/ViewRelated/Stats/StatsWebViewController.m, WordPress/Classes/ViewRelated/System/WPTabBarController.m, WordPress/Classes/ViewRelated/System/WPTableViewController.m, WordPress/Classes/ViewRelated/Views/WPWebView.m, WordPress/WordPressApi/WordPressComApi.m
`WordPressAppDelegate` has a method called `sharedWordPressAppDelegate` that was too verbose.  I renamed the method to the also-standard variant `sharedInstance` to make the code more readable.
/cc @sendhil
=> Small change to make a method less-verbose.

WordPress/Classes/Networking/ReaderPostServiceRemote.m
Fixes an occasional crash caused when an attachment dictionary has a string for a width instead of a number.
=> Ensure width is an NSNumber

WordPress/Classes/ViewRelated/Reader/WPTableViewHandler.m
Identified via crash log.  I have no idea how we'd reproduce this practically, but the fix for the crash seems obvious enough.
Crash log: 
> Last Exception Backtrace:
0   CoreFoundation                       0x000000018252e530 __exceptionPreprocess + 132
1   libobjc.A.dylib                      0x00000001935040e4 objc_exception_throw + 56
2   CoreFoundation                       0x000000018247a5c8 -[NSArray subarrayWithRange:] + 664
3   WordPress                            0x00000001001e7b08 -[WPTableViewHandler indexPathForFirstObjectPrecedingPreservedVisibleIndexPath:] (WPTableViewHandler.m:696)
4   WordPress                            0x00000001001e759c -[WPTableViewHandler refreshTableViewPreservingOffset] (WPTableViewHandler.m:638)
5   WordPress …
=> Fix crash to to index being NSNotFound

WordPress/Classes/Utility/Analytics/WPAppAnalytics.h, WordPress/Classes/Utility/Analytics/WPAppAnalytics.m, WordPress/WordPressTest/WPAppAnalyticsTests.m
Cleans up `WPAppAnalytics` and its unit tests following @sendhil's notes [to a previous PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/3419/files).
/cc @sendhil
=> Small cleanup on the recently added WPAppAnalytics.

WordPress/WordPress.xcodeproj/project.pbxproj
Precompiles headers are making some fake-errors pop up when building WPiOS, that makes spotting real errors more difficult.  I'm disabling precompiled headers for now.
- Just make sure the build times are reasonable with this setting off.
/cc @sendhil, @astralbodies
=> Headers are no longer precompiled for WPiOS.

WordPress/Classes/Categories/UIDevice+Helpers.h, WordPress/Classes/Categories/UIDevice+Helpers.m, WordPress/Classes/Models/Blog+Jetpack.m, WordPress/Classes/System/WordPressAppDelegate.h, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerWPCom.m, WordPress/Classes/Utility/WPUserAgent.h, WordPress/Classes/Utility/WPUserAgent.m, WordPress/Classes/Utility/WPWebViewController.m, WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m, WordPress/Classes/ViewRelated/Reader/WPWebAppViewController.m, WordPress/Classes/ViewRelated/Views/WPWebView.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressApi/WordPressComApi.m, WordPress/WordPressTest/WPUserAgentTests.m
`WordPressAppDelegate` was dealing with some code to handle the user agent for the app.  Since this was outside of the scope of what the app delegate should be doing I created a module to take care of it.
A method from a `UIDevice` extension was also moved into this class as it was inside of it's domain.
**Test:**
- Run the unit tests.
Unfortunately, testing this is difficult, but I added unit tests that should ensure a certain level of assurance.  Please make sure the lines that were replaced were replaced correctly.
/cc @bummytime
=> New User-Agent module

Podfile, Podfile.lock
Closes #3458 
Adds a safety check for the class of responseObject to make sure its not assumed to be an NSDictionary. Added unit tests to ensure a nil response is acceptable.
=> Update to stats pod 0.2.5 which includes Jetpack stats crash fix

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Logging/WPLogger.h, WordPress/Classes/Utility/Logging/WPLogger.m, WordPress/WordPress.xcodeproj/project.pbxproj
Removes some logging code from the app delegate.
**Test 1:**
- Place a breakpoint in `configureLogging`.
- Launch the app and make sure the method is called.
**Test 2:**
- Place a breakpoint in `fileLogger`.
- Launch the app and make sure the file logger is created.
**Test 3:**
- Place a breakpoint in the last line of the app delegate's `application:didFinishLaunchingWithOptions:`.
- Launch the app.
- When the breakpoint is hit, type `po [self.logger getLogFilesContentWithMaxSize:5000]`
- Make sure the returned string makes sense by comparing it to the log in the console.
=> Removes some logging code from the app delegate.

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/WPCrashlytics.h, WordPress/Classes/Utility/WPCrashlytics.m, WordPress/WordPress.xcodeproj/project.pbxproj
Modularizes the app delegate's crashlytic code by creating a new class called WPCrashlytics.
The app delegate is still responsible for deciding whether crashlytics should be run or not (checks for debug or internal builds, checks for a crashlytics credential).
**Test 1:**
- Run the app in debug or internal mode, make sure `WPCrashlytics` is never instanced.
**Test 2:**
- Run the app in release mode, make sure `WPCrashlytics` is instanced
**Test 3:**
- Run the app in release mode, put a breakpoint in `WPCrashlytics`'s method `setCommonCrashlyticsParameters` and make sure it's called when the user account changes (logout, login).
**Test 4:**
- Run the app in release mode, make it crash by raising an exception.
- Place a breakpoint in `WPCrashlytics`'s method …
=> Modularizes the app delegate's crashlytic code

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
This PR adds extra debug information, to help us track a possible sync'ing glitch.
Steps to trigger this flow are as follows:
2. Log into your account, and accept the Push Notifications badge
3. While the app is in background (or closed) receive a push notification, and tap on it
If the affected notification takes over 10 seconds to be received, the Timeout event will get triggered. This can be forced by means of the Network Link Conditioner tool.
/cc @diegoreymendez  (thanks in advance!)
=> Updates Sync Timeout Metric

Podfile, Podfile.lock
2.5.2 has a fix that deals with a MITM attack(details <a href="http://blog.mindedsecurity.com/2015/03/ssl-mitm-attack-in-afnetworking-251-do.html">here</a>)
=> Bumping AFNetworking to 2.5.2

WordPress/Classes/Categories/UIImageView+Gravatar.h, WordPress/Classes/Categories/UIImageView+Gravatar.m, WordPress/Classes/ViewRelated/Me/MeHeaderView.m
Fixes #3109. This PR introduces a way to pass a gravatar rating parameter. Currently, if the gravatar doesn't have a "G" rating, the app will not show it, which in most cases what we would like to do. However, in pages such as the new "Me", it'd be a good idea to show the avatar no matter what it's rating is since that page will only be visible for the current user. So, I've added a way to pass the gravatar rating parameter if you want to, otherwise it'll fallback to G rating by default.
@aerych Can I bother you with a quick review?
Note: If you close the simulator before running the app, it will not use the cached version of the image, so it's easy to reproduce the issue in #3109.
=> Ability to filter gravatars with rating

WordPress/Classes/System/WordPressAppDelegate.m
Trying to clean up the code a bit: this PR re-organizes the app delegate's import directives.
I'll probably be easier to see the changes in the final header file.
**Test 1:**
- Clean and build in debug mode.
- Make sure there are no errors.
**Test 2:**
- Clean and build in release-internal mode.
- Make sure there are no errors.
**Test 3:**
- Clean and build in release mode.
- Make sure there are no errors.
=> Re-organizes the app delegate import directives.

WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m
1. Fresh install WPiOS.
2. Tap over the *Create Account* button
3. Tap over any of the TextFields
4. Tap over the 1Password field
5. The keyboard should get dismissed, and the Activity List should show up.
6. Tap over 1Password again.
The keyboard, which got dismissed in (5), shouldn't reappear after tapping 1Password in (6).
**Additionally:** once 1Password flow is ready, the Site URL should become the first responder. Reason to do so is: it's the field below the 1P button.
@diegoreymendez i'm sorry i missed this screen last time (#3440). Mind taking a quick review?
Fixes #3488 
Thank you!
=> Fixes Signup 1Password Glitch

WordPress/Classes/ViewRelated/Post/PostsViewController.m
Fixes #3467
Removes the flag set on the Posts/Pages VC that set the table view controller as an accessibility element. When in VoiceOver it makes the entire table a single element and not scrollable with a single finger left and right.
I left the accessibility label on it for the UI Automation tests that we may be using it for.
Video of broken VoiceOver: https://cloudup.com/cEB9_-6aGZ6
Video of fixed VoiceOver: https://cloudup.com/cCgpx7QjswR
cc: @sendhil @SergioEstevao
=> Fixes accessibility on the Posts/Pages table so that VO users can use it

WordPress/Classes/System/Constants.h, WordPress/Classes/System/Constants.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/WPLookbackPresenter.h, WordPress/Classes/Utility/WPLookbackPresenter.m, WordPress/Classes/ViewRelated/Settings/SettingsViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
Modularizes the lookback presenter code.
**Test 1:**
- Build in debug mode.
- Run the app.
- Make sure Lookback doesn't launch when shaking the device.
**Test 2:**
- Build in release-internal mode, or make sure LOOKBACK_ENABLED is defined and that the lookback pod is installed for the debug configuration.
- Run the app.
- Make sure Lookback is launched when shaking the device.
**Test 3:**
- Build in release-internal mode, or make sure LOOKBACK_ENABLED is defined and that the lookback pod is installed for the debug configuration.
- Remove the Lookback credential from the credentials .m file.
- Run the app.
- Make sure Lookback is not launched when shaking the device.
=> Modularizes the lookback presenter code.

WordPress/WordPressApi/WordPressComApi.m, WordPress/WordPressApi/WordPressComOAuthClient.m
We should be able to revert this after AFNetworking 2.5.3 or higher is
released.
=> Enables validatesDomainName on AFSecurityPolicy

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
While doing some iOS 7 iPad testing I noticed we had a constraint breaking somwhere.  I tracked it back to the one removed in this PR. Its actually an unneeded constraint since the other contraints for X centering and fixed width already ensure the correct layout. 
Tested in iOS 7 and iOS 8 iPad retina simulators
=> Removes unneeded constraint breaking on iOS7

WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m
As an easy win before the new Jetpack login screen is ready, pre-fill
the username in the existing view if we know it.
See #2847
=> Pre-fill username in JetpackSettingsViewController

Podfile, Podfile.lock
This updates CTAssetsPickerController to the latest version.
Has it can be seen from the [release notes](https://github.com/chiunam/CTAssetsPickerController/blob/master/RELEASE-NOTES.md) it's mainly bug fixes and extra localisations.
cc @sendhil can you please review.
=> Update CTAssetsPickerController pod version.

WordPress/Classes/ViewRelated/System/WPTabBarController.m
This PR adds "Notifications Unread" accessibility label in case there are unread notifications. Before the change it used to say "X items", which was not very descriptive. Also, we decided to keep "Notifications" part in the beginning so users can easily determine which tab they are on using Voice Over, in case they are switching tabs quickly.
=> Notifications tab accessibility label updated to reflect unread state

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Closes #3535 
Original PR #3536 (aimed at wrong branch)
Corrects some names of events sent to Tracks and also moved some items to properties that were part of the event name. Updated Tracks pod to fix some bugs in the client.
=> Update Tracks event names to follow guidelines

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fix #3537 
How to test:
* Open the app, create a new post and insert a video.
* Wait for the video to be uploaded 
* When the video is finished check in mix panel to see if the video event was reported: Editor - Added  Video via Local Library
cc @sendhil can you please review
=> Add video tracking events

WordPress/Classes/Extensions/NSAttributedString+Helpers.swift, WordPress/Classes/Extensions/NSIndexPath+Swift.swift, WordPress/Classes/Extensions/Notifications/NotificationBlock+Interface.swift, WordPress/Classes/Extensions/UIView+Helpers.swift, WordPress/Classes/Utility/Migrations/20-21/AccountToAccount20to21.swift, WordPress/Classes/Utility/Migrations/AccountToAccount22to23.swift, WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift, WordPress/Classes/ViewRelated/Notifications/RichTextView/RichTextView.swift, WordPress/Classes/ViewRelated/Notifications/Tools/NotificationMediaDownloader.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift, WordPress/Classes/ViewRelated/Reader/ReaderPostContentView.m, WordPress/Classes/ViewRelated/Reader/ReaderPostRichContentView.m, WordPress/Classes/ViewRelated/Views/CircularImageView.swift, WordPress/Classes/ViewRelated/Views/WPRichContentView.m, WordPress/Classes/ViewRelated/Views/WPRichTextEmbed.swift, WordPress/Classes/ViewRelated/Views/WPRichTextImage.swift, WordPress/WordPressTest/ContextManagerTests.swift, WordPress/WordPressTodayWidget/TodayViewController.swift
Merging work from https://github.com/wordpress-mobile/WordPress-iOS/pull/3554 and https://github.com/wordpress-mobile/WordPress-iOS/pull/3551. Thanks @nheagy and @alexcurylo for the hard work!
cc @astralbodies @jleandroperez
=> Upgrading to Swift 1.2

WordPress/Classes/Services/OnePasswordFacade.h, WordPress/Classes/Services/OnePasswordFacade.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewModel.h, WordPress/Classes/ViewRelated/NUX/LoginViewModel.m, WordPress/WordPressTest/LoginViewModelTests.m
1. Fresh install WPiOS (develop) on an iPad Device
2. Tap over the 1Password button
The app should not crash, and 1Password Popover should appear onscreen.
Fixes #3567
/cc @sendhil (Thanks in advance!)
=> Fixes 1Password Crash on iPad Devices

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Fixes #3569 
Prevents a crash when logging in with a self-hosted site. Used the wrong variable to determine if a user is ready to be aliased or not with Tracks.
=> Fixes crash when logging in with self-hosted site

WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Fix for https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/54
and
https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/310
cc @bummytime
=> Resize date picker cell at the proper time and assign the proper tag.

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/System/WPTabBarController.m
In #3203, a fix for #3130 was introduced that popped all the main
navigation controllers when the account was changed.
This was causing #3594, as signing into a wordpress.com account from the
Stats view would change the account, resetting the navigation.
This change does two things:
- Only pop controllers on sign out (account == nil)
- Only pop the sites navigation if it was showing a site that was
removed
Fixes #3594 
/cc @oguzkocer
=> Don't pop any site navigation on sign out

WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/NUX/WPWalkthroughTextField.h, WordPress/Classes/ViewRelated/NUX/WPWalkthroughTextField.m
This PR switches rightPadding property's data type to *UIOffset*, which is way more appropiate (thanks for the tip Koke!).
1. Fresh install WPiOS on a device that has 1Password
3. Verify if the 1Password button is properly aligned
4. Tap over the *Create Account* button
5. Same as (3), the 1P button should look fine.
/cc @koke (Thanks in advance Jorge!)
=> Updates WPWalkthroughTextField Padding data type

WordPress/Classes/Utility/Analytics/MixpanelProxy.h, WordPress/Classes/Utility/Analytics/MixpanelProxy.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.h, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/Utility/Analytics/WPAppAnalytics.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/MixpanelProxyTests.m, WordPress/WordPressTest/WPAnalyticsTrackerMixpanelTests.m
@meremagee noticed sometime back that some of the data coming into Mixpanel looked a little off when it came to super properties. In particular the `editor_enabled_new_version` wasn't being set about 70% of the time(yikes). After looking at `WPAnalyticsTrackerMixpanel` and the Mixpanel source I realized we were running into a race condition because of how we were storing super properties. 
The way we were storing super properties was basically:
1) Grab a copy of the super properties dictionary from Mixpanel.
2) Add in/modify the properties we care about
3) Tell Mixpanel to register the new dictionary of super properties.
The race condition occurred because of step 1 and step 3.  The race condition occurs for step 1 because if two methods call into the super property registration method on …
=> Fix some race conditions with Mixpanel tracking

Podfile.lock, WordPress/Classes/ViewRelated/System/WPTabBarController.m, WordPress/WordPress.xcodeproj/project.pbxproj
Alternative to [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/3614).
Pros:
- The visibility of the badge is now inherently tied to the visibility of the tab bar.
- Less code to make sure the badge is hidden / shown when needed.
=> The notification badge now hides with the tab bar.

WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/Networking/CommentServiceRemote.h, WordPress/Classes/Networking/CommentServiceRemoteREST.m, WordPress/Classes/Networking/CommentServiceRemoteXMLRPC.m, WordPress/Classes/Services/CommentService.h, WordPress/Classes/Services/CommentService.m, WordPress/Classes/ViewRelated/Comments/CommentsViewController.m, WordPress/Classes/ViewRelated/System/WPTableViewController.m
Closes #2925 
cc @aerych and @koke can you please review
I implemented this feature based on the behaviour implements on Posts. While doing this I struggle with some things:
* Do the blog properties isSyncingPosts, isSyncingPages, isSyncingComments, isSyncingMedia ever being accessed somewhere in the code? I searched but couldn't find a place where they are being changed.Was this something that was used before and didn't got deleted? Or something that was added but not used yet?
* The same for hasOlderPosts, hasOlderPages
The PR don't need this properties but I wanted to now if this is something that needs to be fixed/implemented.
=> Implement Comments infinite scroll

WordPress/Classes/Models/Blog+Jetpack.m, WordPress/Classes/ViewRelated/Stats/StatsWebViewController.m
Since we don't store wp.com passwords anymore, this makes
`blog.authToken` return the Jetpack account's token for Jetpack blogs.
Fixes #3508 
*Testing note:* make sure to set `WPJetpackRESTEnabled` to NO (normally enabled on Debug builds). Otherwise, Jetpack sites turn into wp.com sites and the original issue doesn't appear.
=> Fixes web stats for Jetpack sites

WordPress/Classes/Extensions/UIViewController+Helpers.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
3. Receive a new Notification
As a result, the new notification should be marked immediately as seen, and the badge should get reset.
As of now, the badge and "last seen" are both being reset in the viewWillAppear's method of NotificationsViewController.
There is a potential race condition between the Push Notification, and the actual Simperium Sync, in which the user first gets the Push Notification, opens the Notifications tab, and the Note arrives afterwards. This could cause the newly arrived note not to get marked as seen (and the badge could also remain intact).
In this PR we make sure that new notifications are marked as seen, as long as *NotificationsViewController* is onscreen.
Fixes #3559
@astralbodies may i bother you with a …
=> Marking new Notifications immediately as seen if the list is onscreen

Podfile
Fixes #3654 
Adds a post-install hook to set the device family for pods. This forces storyboards to be compiled for more than just iPhone preventing the crash in Stats.
cc: @koke
=> Sets device family to iPhone & iPad for resource compilation

WordPress/Classes/Services/PushAuthenticationService.swift, WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/Classes/Utility/NotificationsManager.m, WordPress/Classes/Utility/PushAuthenticationManager.swift, WordPress/Classes/Utility/UIAlertViewProxy.h, WordPress/Classes/Utility/UIAlertViewProxy.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/MockWordPressComApi.swift, WordPress/WordPressTest/PushAuthenticationManagerTests.swift, WordPress/WordPressTest/PushAuthenticationServiceRemoteTests.swift, WordPress/WordPressTest/PushAuthenticationServiceTests.swift, WordPress/WordPressTest/WordPressTest-Bridging-Header.h
This PR adds in unit tests to @jleandroperez's pending PR(https://github.com/wordpress-mobile/WordPress-iOS/pull/3626). I had to adjust some of the classes just a little bit to be able to properly test the classes added to the original pull request. The changes I made were:
* Pulled out the direct instantiation of `PushAuthenticationServiceRemote` in the `authorizeLogin` method so I could swap in a mock during testing.
* Dropped the singleton as singletons are a pain to test.
* Added a convenience initializer so the rest of the codebase wouldn't have to care about any internal dependencies.
* Pulled out the direct instantiation of `PushAuthenticationService` from `authorizeLogin`
* Created a `UIAlertViewProxy` class to control access to UIAlertView so we can more thoroughly test this …
=> Adding unit tests to #3615

WordPress/Classes/Categories/MFMailComposeViewController+StatusBarStyle.h, WordPress/Classes/Categories/MFMailComposeViewController+StatusBarStyle.m, WordPress/Classes/Categories/MFMessageComposeViewController+StatusBarStyle.h, WordPress/Classes/Categories/MFMessageComposeViewController+StatusBarStyle.m, WordPress/Classes/Categories/WPMediaPickerViewController+StatusBarStyle.h, WordPress/Classes/Categories/WPMediaPickerViewController+StatusBarStyle.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/Reader/WPImageViewController.m, WordPress/Info.plist, WordPress/WordPress.xcodeproj/project.pbxproj
This is a refactor of the status bar management throughout the app in order to use the iOS 7+ way.
Refs #2507, it solves the problem of the status bar reseted to the default black color in ```MFMailComposeViewController``` and ```MFMessageComposeViewController```.
Basically, I turned the ```UIViewControllerBasedStatusBarAppearance``` key in Info.plist to YES. I then update everywhere I could the status bar management rules (color, animation and hidden settings) using the following overridden methods:
```
- (BOOL)prefersStatusBarHidden;
- (UIStatusBarStyle)preferredStatusBarStyle;
- (UIStatusBarAnimation)preferredStatusBarUpdateAnimation;
```
The ```setNeedsStatusBarAppearanceUpdate``` method is used whenever the previous methods values change at runtime.
Regarding the mail and message …
=> Update status bar management to use iOS 7+ features

WordPress/Classes/ViewRelated/Me/MeViewController.m
Fixes #3636. This PR changes the login label for WordPress.com in Me page to "Connect to WordPress.com" so that it fits in iPhone 5 screens. This also matches the Android counterpart with this change.
iPhone 5: https://cloudup.com/cIyLAmUWXwd
Android: https://cloudup.com/chuP-oxsaf0
@aerych Can I bother you with a really quick review? Thanks in advance!
=> Change login label for WordPress.com to fit in iPhone 5 screen

WordPress/WordPressApi/gencredentials.rb
I recently upgraded to Ruby 2.2 and I get this warning when building
> File.exists? is a deprecated name, use File.exist? instead
According to [the docs](http://ruby-doc.org/core-1.8.6/File.html#method-c-exist-3F), `File.exist?` already existed in 1.8 and `File.exists?` was already obsolete, so this should be safe
=> Fixes warning when using Ruby 2.2

WordPress/Classes/Utility/WPURLRequest.m, WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/WPURLRequestTest.m
As a side effect of #3597, `blog.authToken` was not `nil` for Jetpack
sites. When there's an auth token, WPURLRequest will drop the password
from the request. Since the login was posted to the self hosted and not
WordPress.com, the authentication failed.
This sets the token only if the blog is a WordPress.com one, and adds a
safeguard to prevent tokens from being sent to non-wp.com URLs.
fixes #3637 
/cc @jleandroperez since I think you wrote WPURLRequest
/cc @sendhil since I mentioned it in private
=> Fix Jetpack preview authentication

WordPress/Classes/Utility/WPURLRequest.m, WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/WPURLRequestTest.m
Porting #3641 to 5.2
> As a side effect of #3597, blog.authToken was not nil for Jetpack
sites. When there's an auth token, WPURLRequest will drop the password
from the request. Since the login was posted to the self hosted and not
WordPress.com, the authentication failed.
> This sets the token only if the blog is a WordPress.com one, and adds a
safeguard to prevent tokens from being sent to non-wp.com URLs.
> fixes #3637
=> Fix Jetpack preview authentication (5.2)

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Closes #3688 
Fixes a crash when the anonymous ID might be blank. Added safety checks to prevent this but also am handling the creation of the anonymous aliasing events properly.
=> Properly handle lifecycle changes in WPAnalytics with Tracks

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Couldn't directly reproduce the crash. It's potentially triggered by a race condition in which the object was gone, and still, the UI wasn't refreshed.
Fixes #3682.
@diegoreymendez may i bother you with a quick review?
Thanks!
=> NotificationsViewController: Implements didSelectRow Failsafe

WordPress/Classes/ViewRelated/NUX/WPWalkthroughTextField.m
When switching between secure and readable mode, it's necessary to resign focus before applying the selected range again to prevent the caret to be at the wrong position
Fixes #2498
=> Update the cursor position when toggling secure mode

WordPress/Classes/Utility/WPWebViewController.m
On #2679, a hack was introduced to set the viewport width to the actual
web view width.
The problem is some sites set the viewport width to `device-width`,
which is a problem if the web view is in a modal window instead of full
screen.
This change only applies the hack if the web view's width is less than
the window's width
Also helps with #1652
=> Fixed web view rendering

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/Me/MeViewController.m
Since the iPad uses a popover to confirm the sign out, it seems it was
preventing the NUX from being presented.
After debugging, all the right things were being called and the app
delegate was presenting the welcome screen, yet nothing happened.
I added a `dispatch_async` to let the popover dismiss animation finish.
Fixes #3667
=> Fix iPad sign out

WordPress/Classes/Services/BlogSyncFacade.h, WordPress/Classes/Services/BlogSyncFacade.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewModel.h, WordPress/Classes/ViewRelated/NUX/LoginViewModel.m, WordPress/WordPressTest/LoginViewModelTests.m
If the added site has Jetpack, it's connected, we know the wp.com
username, and we have a matching account, setup Jetpack automatically.
Otherwise, delay Jetpack setup until the user tries to access stats
A first step towards #3628 
@sendhil I'm having trouble with those Specta tests. There are three of them failing, but since it doesn't integrate well with Xcode I can't really figure out what's failing and why
=> Skip jetpack login on setup

WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewModel.h, WordPress/Classes/ViewRelated/NUX/LoginViewModel.m, WordPress/WordPressTest/LoginViewModelTests.m
1. Fresh Install
2. Log into a WordPress.com with 2FA enabled
3. When the app requests the One Time Code, tap over the 'Send SMS' label
As a result, a SVProgressHUD instance should be briefly displayed, with the legend 'Sending SMS!'.
Fixes #3643
=> Send SMS Feedback

WordPress/Classes/Models/Blog+Jetpack.h, WordPress/Classes/Models/Blog+Jetpack.m, WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/JetpackState.h, WordPress/Classes/Models/JetpackState.m, WordPress/Classes/Services/BlogSyncFacade.m, WordPress/Classes/Utility/WPURLRequest.m, WordPress/Classes/ViewRelated/Blog/EditSiteViewController.m, WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m, WordPress/Classes/ViewRelated/Stats/StatsViewController.m, WordPress/Classes/ViewRelated/Stats/StatsWebViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/BlogJetpackTest.m
While I just wanted to bump the required version (#2287) and update the Jetpack screen to ask users to update old installs, I used the opportunity to refactor a bit.
- Most of `Blog+Jetpack` is moved to a new `JetpackState` object
- I plan to move the rest of `Blog+Jetpack` to either `Blog` or a new `JetpackService`, but that's for the next PR
- In 20728ca I fixed an issue where the "Install Jetpack" web view would show the wrong plugin status, because we were caching too aggresively
- Also, no more _Jetback_ :v: 
Fixes #2278
References #3627
=> Prompt to update Jetpack on connection

Podfile, Podfile.lock
Closes https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/654
This version of WPMediaPicker adds proper layout support for FullScreen Mode in the iPhone 6 Plus.
Needs Review: @diegoreymendez, @sendhil
=> Update WPMediaPicker to version 0.3.6

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Closes #3706 
Adds a push type to the WPAnalytics tracker so we have an idea of what type of note is involved. 
Needs Review: @jleandroperez @sendhil
=> Added push notification type to the WPAnalytics call

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
@diegoreymendez may i bother you with a very quick review?.
Found a missing *removeObserver* call!.
Thanks!
=> NotificationDetailsViewController: Adds missing removeObserver call

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
1. Fresh install WPiOS (on the device)
2. Launch the app, login and send it to background
3. Receive a Push Notification
As a result, the badge should **not** get reset. 
We've discovered that, during the **background fetch** OS call, Simperium's *Object Inserted* callback might get called, and thus, the badge would be reset.
In this PR we just make sure that the app is in active state before resetting the badge. Plus: there is a notification listener waiting for the **appDidBecomeActive** note.
Closes #3638
@astralbodies may i bother you (yet again) with a review?
=> Prevents resetting the badge while the app is not active

WordPress/WordPressTest/NSStringHelpersTest.m
The "elipsize" unit test was failing due to a logical error in it.  This PR fixes it.
**Hot to test:**
- First, make sure the logical changes in the code make sense.
- Then run the unit tests and make sure they're not failing.
**UPDATE:** we decided to remove this test.  See my comment below.
=> Removes a failing unit test.

WordPress/Classes/Services/PostService.m
While running the profiler with Instruments I noticed this method was taking some time.
Previously we filtered `blog.posts`, which means every post is fetched then filtered. Since #3577, Post will build the content preview on each awakeFromFetch, which was being called for every post, and not just the matching one.
Switching to a fetch request doesn't call awakeFromFetch
=> Faster implementation of findPostWithID

WordPress/Classes/Models/Notifications/Notification.h, WordPress/Classes/Models/Notifications/Notification.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
1. Receive a new Comment on any of your blogs
2. Disapprove the comment
3. Tap over *Like*.
As a result, the comment should get auto approved, right after tapping *Like*.
/cc @sendhil (Thanks in advance!)
Closes #3705
=> Notifications: Like should auto approve comments

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m
Updates the media picker to the latest version.
Changes on media picker here:
* https://github.com/wordpress-mobile/MediaPicker-iOS/releases/tag/0.4.0
* https://github.com/wordpress-mobile/MediaPicker-iOS/releases/tag/0.4.1
To test it try to add images and videos to a post using the picker. And also add a featured image to a post.
=> Update to MediaPicker version 0.4.1

WordPress/WordPress.xcodeproj/project.pbxproj
Fixes a build error due to a missing header file when a crashlytics api key is not defined.
=> Create InfoPlist.h even if key is not found.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
2. Receive a new Like Notification
3. Tap over the new notification
4. Remove the like added in (2)
As a result, the view should get dismissed, and the user should be left in NotificationsViewController.
Ref. Issue #3692
/cc @astralbodies (Thank you!)
=> NotificationDetails: Fallback to Root on Delete

WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/JetpackState.m, WordPress/Classes/Networking/Remote Objects/RemoteBlog.m, WordPress/Classes/Services/BlogService.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m
As part of #3627 this improves logging so we can support Jetpack sites better:
- It will log when a new site is added automatically via `syncBlogs`
- It will log when a Jetpack site is migrated to use REST
- Improves the blog list logged on launch
Some sample blogs and their logged description on launch
**Before**
>Name: Edge test site URL: http://edge.wpmt.co XML-RPC: http://edge.wpmt.co/xmlrpc.php isWpCom: NO blogId: 0 jetpackAccount: PRESENT
Name: Jetpack Test #2 URL: http://jp2.koke.co XML-RPC: http://jp2.koke.co/xmlrpc.php isWpCom: NO blogId: 0 jetpackAccount: NONE
Name: Jorge Bernal URL: http://jorgebernal.es XML-RPC: https://jorgebernales.wordpress.com/xmlrpc.php isWpCom: YES blogId: 17691640 jetpackAccount: NONE
Name: Jorge Bernal URL: http://jorgebernal.info XML-RPC: …
=> Improve logging for Jetpack REST migrations

WordPress/Classes/Networking/PostServiceRemoteREST.m
Fixes publish immediately for wpcom scheduled posts.
Closes #3732 
=> Assign current date for existing post if date is nil.

.clang-format
Clang Format is a tool that is part of the <a href="http://clang.llvm.org">Clang toolset</a> and it helps to automatically format Objective-C code. Out of the box, clang-format is a command-line tool that you can run directly on your source files. It doesn’t add/remove code from your source, instead focusing on adjusting the whitespace characters within your source to make code more consistent.
With a little bit of extra effort, you can make clang-format available from within Xcode. <a href="http://ClangFormat-Xcode">ClangFormat-Xcode</a> is an Xcode plugin developed by Travis Jeffery that makes Clang’s format tools available within Xcode.
Travis has made the plugin available via Alcatraz. Alternately if you don't want to install <a href="http://alcatraz.io">Alcatraz</a> and prefer to …
=> Add clang format file.

Podfile, Podfile.lock
Closes #3775 
Updates to the latest stats release. Included with this release:
* Removes Storyboard warning (cartwheel @koke)
* Improves user interface - aligned colors with rest of the app
* Added more bars to iPhone and iPad views
* New progress loading indicator
=> Update to latest stats 0.3.5

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
1. Launch WPiOS and open the Notifications Tab.
2. Receive a comment on a testing blog.
3. Tap over the Notification, once it arrives.
4. Tap over the Trash action.
As a result, the Details ViewController should get dismissed, and the affected Notification cell should not be tappable anymore.
Closes #3692
/cc @diegoreymendez (Thanks in advance Diego!).
=> Notifications: Disabling interaction on Nuked Notes

WordPress/WordPressTest/NotificationTests.m
As a side effect of #3699, Notifications Unit Tests broke.
@SergioEstevao may i bother you with a quick review?
Thank you!
-- 
=> Fixes Notifications Unit Tests

WordPress/Classes/ViewRelated/Me/MeViewController.m, WordPress/Classes/ViewRelated/Settings/SettingsViewController.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m, WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #3723. This PR adds the restoration to `WPTabBarController` and it now opens up with the last selected tab. I've also added restoration to `MeViewController`, `SettingsViewController` and `SupportViewController`. There are a lot of pages that currently doesn't support restoration, we probably should add them in the future.
I didn't know this before, so I am sharing here just in case it's not common knowledge: "Be aware that the system automatically deletes an app’s preserved state when the user force quits the app." http://stackoverflow.com/questions/12718341/ios-6-saving-restoring-app-state-feature
@sendhil Can I bother you with a review? Thanks!
=> Fixes restoration issues in tab bar

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Just a small bug fix.  Can't be really tested because the app wasn't breaking because of this - but it's nevertheless correct to call `super` here.
**How to test restoration is working fine:**
2. Open the editor and create a new post
3. Send app to background
4. Stop the app from xcode
5. Run the app again
Make sure the post editor is restored.
=> Adds a missing call to super.

WordPress/Classes/ViewRelated/Blog/EditSiteViewController.m
_Previously #3696. After #3451, it was easier to do this again than to solve conflicts_
You can set up Jetpack when you actually need it, from Stats and soon
from notifications.
Also, when Jetpack is already setup, settings would still show the same
login form as when it's not setup.
Related to #3628
=> Remove Jetpack settings from Edit Site

WordPress/Classes/Utility/PushAuthenticationManager.swift
1. Install WPiOS 5.3 on your phone
2. Log into WordPress.com, in your web browser, with an a8c account that has 2FA enabled
3. A Push Notification should arrive shortly
4. Wait ~20 minutes before tapping on it
An alertView should show up onscreen, indicating that the login request has expired. The button text should say **Accept**.
Props to @dmsnell for spotting this one.
Needs Review: @sendhil (thanks in advance Sendhil!)
=> Fixes Invalid PushAuthenticationManager Alert Button

WordPress/WordPress-Internal-Info.plist
I'm matching the `UIViewControllerBasedStatusBarAppearance` we already've got in `Info.plist`, so that a given UIViewController can tweak the statusBar appearance.
This affects only the Internal build. This can be tested by means of the new WebViewController:
2. Tap over the My Sites tab
3. Pick a random blog
4. Tap over `View Site`
As a result, a modal viewController should be onscreen, with the statusBar text set to black. In the latest internal beta, the text is set to white instead.
Needs Review: @diegoreymendez  (Tanks Diego!)
=> Fixes statusBar Appearance

WordPress/Classes/Utility/PushAuthenticationManager.swift
We recently received feedback on the Push Authentication mechanism. In order to match Calypso's style, let's update the Push Auth's alertView to `Verify Sign In`.
1. Log into WordPress.com, in your browser, using your a8c account
2. WPiOS should receive a push notification
3. Tap over the push notification
Expected: The app will launch, and the Push Authentication alertView should be onscreen.
The title should read `Verify Sign In`
Needs Review: @SergioEstevao  (Thanks in advance Sergio!)
=> Updates Push Auth AlertView's Title

WordPress/Classes/ViewRelated/Post/PostCardImageCell.xib, WordPress/Classes/ViewRelated/Post/PostCardTextCell.xib
Closes #3815 
Adjusts constraint priority so there is no warning about a broken constraint on some iPad and OS versions.  
Test by launching the iPad 2, iOS 8.1 simulator and navigating to the post list. You should not see any warnings about constraints when viewing the post list. 
=> Fixes breaking constraint on iPad 2, iOS 8.1

WordPress/Classes/ViewRelated/Pages/PageListSectionHeaderView.xib, WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib, WordPress/Classes/ViewRelated/Post/PostListFooterView.xib
Closes #3823 
To test:
Launch the iOS 8.1 iPad 2 simulator
View the post list
Ensure constraints do not break on the table footer view. 
View the page list
Ensure constraints do not break on the section header views.
Ensure the page cells do not break constraints. 
=> Adjusts iPad width constraint priority.

WordPress/Classes/Models/WPAccount.m, WordPress/WordPressApi/WordPressComApi.h, WordPress/WordPressApi/WordPressComApi.m
1. Install WPiOS on your device
2. Allow the app to receive Push Notifications
3. Log into your account
4. Tap over the Me tab, and hit the Disconnect row
As a result, the Push Notifications token should be removed from the backend, and the following legend should show up in the console:
```
2015-06-09 14:57:20:509 WordPress[10095:807] Successfully unregistered device ID [Device's ID]
```
Needs Review: @SergioEstevao + @diegoreymendez 
Any improvements / suggestions will be very welcome, thank you!
=> Prevents Unregister Token OP's cancellation

WordPress/WordPressApi/WordPressComApi.m
Sometimes the error code is a clearer indicator of what's wrong when debugging an issue, e.g. `json_syntax` vs `Invalid response from the Jetpack site`.
Let's include that in the log.
As a side effect, this might show in some user facing errors
I think that's probably OK as long as we show the friendly error message first
References #3627 
=> Include error code in error message

WordPress/Classes/Categories/UIImageView+Gravatar.h, WordPress/Classes/Categories/UIImageView+Gravatar.m, WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/Post.m, WordPress/Classes/Networking/AccountServiceRemoteREST.m, WordPress/Classes/Networking/Remote Objects/RemoteBlog.h, WordPress/Classes/Networking/Remote Objects/RemoteBlog.m, WordPress/Classes/Services/BlogService.m, WordPress/Classes/ViewRelated/Blog/BlogDetailHeaderView.m, WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m, WordPress/Classes/ViewRelated/NUX/AddUsersBlogCell.m, WordPress/Classes/ViewRelated/Reader/FollowedSitesViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderBrowseSiteViewController.m, WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion, WordPress/Classes/WordPress.xcdatamodeld/WordPress 32.xcdatamodel/contents, WordPress/WordPress.xcodeproj/project.pbxproj
Closes #3720. The issue we wanted to fix was the Jetpack site icons were not showing up in the app. Up until now, we used the host url to construct a gravatar.com url for the blavatar. However, we do not support this for Jetpack sites. In order to solve the issue, we need to start saving the icon url for the `Blog`. As discussed on Slack with @koke, we have opted to use the term "icon" instead of "blavatarUrl" since the url returned might not be a blavatar url. Also, we originally wanted to move the URL construction away from `UIImageView+Gravatar` since it's a UIKit category, but we need the size information, so it's probably best to keep it there.
Needs Review: @koke (Thank you!)
=> Support for Jetpack site icons

WordPress/Classes/Models/AbstractPost.m, WordPress/WordPressTest/CoreDataMigrationTests.m
Avoids needing to check for an attribute's existence in the model.
cc @astralbodies :)
=> Tweak the 19-31 revision migration test.

Podfile, Podfile.lock
Closes #3830 
Updated Tracks library to v0.0.5 which fixes missing `performBlockAndWait` wrappers around a few Core Data calls.
=> Update Tracks pod to 0.0.5

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTextTableViewCell.swift
1. Receive a Comment Notification that contains an image embed. This can be used to test the feature:
`<img src="https://i.cloudup.com/RiNQdiWYLe.gif">`
2. Launch WPiOS and open the Notifications tab
3. Open the new notification's details
4. Tap over the embedded image
Expected: the image should be displayed in a modal viewController.
Needs Review: @aerych (Thanks in advance Eric!)
Closes #2764
=> Notifications Comment Embeds: Fullscreen Support

WordPress/Classes/ViewRelated/Pages/PageListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewControllerSubclass.h, WordPress/Classes/ViewRelated/Post/PostListViewController.m
Closes #3832 
To test:
Go to the post list and search for any term that should have no results.
The no results view should indicate there are no posts (or drafts, scheduled posts, trashed posts) for the specific search term. 
Repeat for each filter. 
Repeat for the page list. 
=> Tailors no results message for searches.

WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
When Jetpack REST is enabled, we don't have the self hosted credentials, and the Jetpack site won't care for the OAuth2 token.
Let's fall back to a local preview until we have a better solution for authentication
See #3627 
=> Use local previews if we don't have credentials

WordPress/Classes/ViewRelated/Post/PostListViewController.m
Closes #3835 
To test:
Start with a multi-author blog
Start a new post.
Double tap the home button and force quit WordPress. 
Relaunch the app. 
Make sure the newly started local-only post appears under both "only me" and "everyone" author filters. 
@koke since you discovered this one would you mind taking a look?
=> Includes newly created posts under the only me filter.

WordPress/Classes/Networking/AccountServiceRemote.h, WordPress/Classes/Networking/AccountServiceRemoteREST.m, WordPress/Classes/Networking/BlogServiceRemote.h, WordPress/Classes/Networking/BlogServiceRemoteREST.m, WordPress/Classes/Networking/PostServiceRemote.h, WordPress/Classes/Networking/PostServiceRemoteREST.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/AccountServiceRemoteRESTTests.m, WordPress/WordPressTest/BlogServiceRemoteRESTTests.m, WordPress/WordPressTest/PostServiceRemoteRESTTests.m
Follow up to [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/3808).
This PR adds several tests for:
- AccountServiceRemoteREST.
- BlogServiceRemoteREST.
- PostServiceRemoteREST.
- Run the unit tests and make sure the newly added tests all succeed (at the time of this writing there are a few unrelated broken tests coming from `develop` which are outside of the scope of this PR).
=> More unit tests for our REST service classes.

WordPress/Classes/Utility/WPWebViewController.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
3. Find any achievement notification (ie. stats) and open it
4. Tap over the linked site
As a result, the site stats (web version) should be onscreen.
I've found, and patched, a logic error in the **WPWebViewController**'s `retryWithLogin` mechanism as well.
Closes #3755
Needs Review: @bummytime (Thanks in advance Matt!)
=> Initializing WebViewController with Credentials

WordPress/WordPressTest/PushAuthenticationManagerTests.swift
One of the Push Auth strings was recently updated, and i didn't notice i broke the unit test (Sorry!!)
=> Fixing PushAuthentication Unit Test

WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Notifications/Tools/NotificationMediaDownloader.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTextTableViewCell.swift
2. Receive a Comment Notification with embedded images
3. Tap over the Notifications tab
4. Open the new notification
5. Verify that the assets should show up shortly, once available
6. Rotate the device
7. Verify that the assets get properly resized to fit the new width
This can be tested with the following images:
```
We'll do an inline image here <img src="https://i.cloudup.com/RiNQdiWYLe.gif">.
Another one here:
Another here:
And last one: <img src="https://cldup.com/VSVBixYg33.png">
```
Needs Review: @aerych (thanks in advance Eric!)
Closes #2765
=> Notifications: Resizing Media Embeds on Rotation

WordPress/Classes/Utility/DisplayableImageHelper.m
Lowers the threshold size to match the web.
If no other image is found, chooses the first image without size information.
The assumption is this will be a feature worth image, and size info was omitted to allow it to naturally scale in the browser.
Closes #3853 
To test:
Try viewing the post list with posts that have images in the content, but no width defined on the image. Confirm the first image is now selected to show in the post card in the list. 
Its expected that some images will be up-scaled but this should happen infrequently, and a slightly grainy image is preferred to no image at all. 
=> Adjusts featured image selection logic.

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Previously we synced when the list loaded, which in practice meant when
the app launched. This meant that for most, it seemed as if new sites
didn't automatically appear in the app
Fixes #3873 
Needs Review: @oguzkocer
=> Sync blogs when list appears

WordPress/Classes/Services/CommentService.m, WordPress/Classes/Services/PostService.m, WordPress/Classes/ViewRelated/Comments/CommentsViewController.m, WordPress/Classes/ViewRelated/Pages/PageListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewControllerSubclass.h, WordPress/Classes/ViewRelated/Post/PostListViewController.m
@aerych i initially thought that `CommentService` should be the one updating the `lastCommentsSync` property.
However, after a brief check, i've found out that `AbstractPostListViewController` is the one that's actually updating `lastPostsSync`, so... thought it'd be a good idea to keep things consistent.
Mind taking a quick look?
Thank you!!
Closes #3867
=> CommentsViewController: Updating Blog's lastCommentsSync property

WordPress/Classes/ViewRelated/Post/PostListViewController.m
Closes #3864 
To Test:
Open the post list.
Tap the edit button at the bottom of a post card view in the list. 
Confirm the editor opens in edit mode. 
=> Open post in edit mode if edit is tapped.

WordPress/Classes/Utility/JetpackREST.m
This enables Jetpack REST by default for app store builds.
@beaulebens any concerns before we flip the switch?
@oguzkocer this is pretty straightforward, but I ask for a review just to be safe :)
Fixes #3627 
Needs Review: @beaulebens @oguzkocer
=> Enable Jetpack REST for everyone

WordPress/Classes/Services/PostService.m
Fixes an issue sorting pages.
Fixes #3886 
This is a rather hacky patch but takes advantage of an existing initialization feature. A better fix would probably be to set all of these properties as the default values in the model.   Let's follow up up with a PR doing that in the develop branch. 
To test:
- Open your page list. 
- If you have any pages already created today, move them into drafts or the trash. 
- Tap to create a new page. 
- Add a title and content and save. 
- The page should show up with the correct title under the "today" section and the UI should still be responsive. 
cc @koke, @sendhil 
=> Work around to correctly set the metaPublishImmediately flag.

Podfile, Podfile.lock, WordPress/WordPressTodayWidget/TodayViewController.swift
Closes #3881 
Updates to latest stats pod which includes Insights stats for a site. 
There will be another version bump of this pod before WPiOS 5.4 is released to include a few open bug fixes.
1. Load the app.
2. Visits stats for any site.
3. Notice a new tab labeled Insights.
4. Experience extreme joy.
=> Updated to latest stats pod

WordPress/Classes/Extensions/Notifications/NotificationBlock+Interface.swift
We spotted several Notification Styles that are not being used anymore. Comment blocks and Text blocks may not contain the following ranges:
- User
- Post
- Comment
I'm removing those references from the proper styles map, just to clean things up.
This is probably a leftover from the `Badges` style implementation, which *may* contain those ranges, but since it requires different alignment settings, we ended up adding another styles collection, down the road.
Props to @dmsnell for checking the backend side, and @aerych for spotting this!
Needs Review: @aerych (Thanks in advance!)
=> Nukes dead Notifications Styles

WordPress/Classes/ViewRelated/Blog/EditSiteViewController.m
Before:
After:
In #3719 we discussed better alternatives, but since @tonyr59h is going to update the settings screen soon I went for the simplest solution so at least it's not broken.
Since we don't have a way to get the username for Jetpack managed sites right now, let's just hide username for wp.com+Jetpack
Needs Review: @tonyr59h
=> Hide username in Jetpack site settings

WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m
Fixes https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/653
This PR adds a little more space between the navbar buttons (preview, options, etc) as well as fixes an overlap issue with the blog picker button on smaller devices.
How to test:
* Test the code on a wide variety of devices, make sure the editor navbar looks ok.
* Make sure the blog picker button does not overlap the preview button when in a new post AND editing an existing post (e.g. on a iPhone 4s)
/cc @diegoreymendez
=> Adjusted spacing on editor navbar

WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.m
Missed making the post card title bold with the reset of the font changes. 
Previously:
After:
=> Post card title font should be bold.

WordPress/Classes/ViewRelated/Post/PostCardImageCell.xib, WordPress/Classes/ViewRelated/Post/PostCardTextCell.xib
Closes #3921 
Attempts to fix an edge case bug where a post card on an iPad can appear too wide. Since the bug is very hard to reproduce the strategy here is to raise the width constraint priority to a high aount without making required.  This should enforce the correct width in unusually autolayout situations and avoid situations that could lead to a breaking constraint. 
@jleandroperez, could I trouble you to review this one as well? 
=> Increase ipad width constraint priority

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/WordPress.xcodeproj/project.pbxproj
Closes #3923 
1. Fixes refresh state weirdness with insights and regular stats.
2. More button now works properly when switching between days and insights.
3. Today stats (individual stats for views/visitors/etc) in Insights now switches to related view on graph in Days view.
4. Fixes a rare crash on /stats/visits mainly on iOS 7 and logs the data to Tracks for further analysis.
The individual pieces of the stats update have been tested in StatsDemo in the source project/pod. Simply load stats and make sure the screens work and there are no demons.
Needs Review: @sendhil, @jleandroperez
=> Bump stats to 0.4.1

WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m
Closes #3925
See the ticket above for more details about the bug.
I found that updates to the device library where getting propagate to the WP media library and making the screen get repainted. 
This is specially bad when you have iCloud Photos enabled, because iCloud can make changes to the device library and then these where getting in the app and making the screen refresh. 
How to test: 
* Open the app
* Go to a blog and create a post
* Select Insert a Media 
* Select the Media Library
* After the media library loads, exit the app
* Go to the Photos app and start changing things there, for example delete some photos you don't need
* Go back to the app, and check if you don't see the Media Library refresh
* After while switch to the Camera Roll and check if your changes happen.
Needs …
=> WP media library repaints while loading.

WordPress/Classes/ViewRelated/Blog/BlogDetailHeaderView.m
Sets a default background for blavatars on the blog details screen.
Before:
After:
Fixes #3738 
Needs Review: @oguzkocer
=> Set a background color for blavatars

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Addresses #3948 
Testing:
1. Go to the site picker
2. Tap on the search icon, but don't type anything in the search field
3. Make sure the virtual keyboard is up
4. Try scrolling to the bottom of the sites list
Expected result: the last items in the list should be visible.
=> TableView is now resized on keyboard change

WordPress/Classes/ViewRelated/System/Search/WPSearchControllerConfigurator.m
Closes #3893 
To test:
Open the post or page list
Tap to search
Ensure the keyboard return key has the label "Done" 
Needs to be tested on iOS 7.1 to ensure backward compat. 
=> Sets search keyboard return key to 'Done'.

WordPress/Classes/Utility/WPURLRequest.m, WordPress/Classes/Utility/WPWebViewController.m
2. Launch the app, and log into your account
3. Tap over the Notifications tab
4. Find a Stats-Y notification for a *private* site and open it
5. Tap over the site name
As a result, WebViewController is expected to be onscreen, and the blog should be visible. No extra authentication should be required.
Needs Review: @diegoreymendez  ||  @sendhil (Thanks in advance!)
=> Fixing web view authentication

WordPress/Classes/Models/WPAccount.m
Fixes #3950 
Recreated PR #3953 to point at release/5.3.1.
This isn't the final solution but it's a minimally-impacting change to make the OAuth2 token not get lost when the username is changed. AccountService will possibly change the username from an email address (for example) to a WordPress.com username after a sync occurs. This makes sure that if a username is changed that the token is moved along as well.
I tried to write this so we continue to use existing accessor methods for authToken and a minimal impact on the setter for username. I'm open to suggestions for improvements but I wanted to touch the least amount of code for this hot fix.
I haven't written a unit test for this - which I can do. The keychain unit tests are notoriously unreliable though. Simulator seems to work fine …
=> First stab at making the OAuth2 token less susceptible to breaking

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/WPAnalyticsTrackerAutomatticTracksTests.m
Closes #3959 
Adds the missing implementation for the app upgraded event to Tracks. Also fixes an event name mapping that doesn't pass validation. Created a unit test to scan all of the event enum to make sure the mappings are valid.
This isn't the best solution for doing all enum values as there isn't any way to count the enums. The unit test will have to be maintained or we add an enum in for the last placeholder.
cc: @daniloercoli 
Needs Review: @aerych, @sendhil
=> Adds missing event to Automattic Tracks tracker

Podfile, Podfile.lock
Closes #3957 
Update to the latest stats pod for the release/5.3.1 branch. 
Includes a small fix to remove restoration identifiers in the view controllers so they do not try to participate in state restoration. When coming out of the background the state can't be restored via default mechanisms as the storyboard SiteStats is not in the default bundle. Stats is not ready to participate in state restoration.
=> Update to stats 0.3.6 including the state restoration fix.

WordPress/Classes/Models/WPAccount.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/NotificationsManager.m, WordPress/Classes/Utility/WPAuthTokenIssueSolver.h, WordPress/Classes/Utility/WPAuthTokenIssueSolver.m, WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Me/MeViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.h, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
Takes care points 3, 4 and 5 from [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/3964) reported by @astralbodies.
This should NOT be merged until [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/3956) by @astralbodies is merged.  The reason is that this PR is a branch from that PR.
Please keep in mind this is a hotfix, so even though some code has been moved, as little as possible of the existing logic has been really modified.  This means there's some code duplication.
**Test 1:**
- Comment out method `setUsername:` in `WPAccount`
- Login with a mixed case WP.com username name or a WP.com email address
- Create post, quit app without hitting the save button
- Reopen the app, it should ask you to re-authenticate (if you disabled the method above)
- …
=> Auth token issues solver. [DO NOT MERGE]

WordPress/Classes/ViewRelated/Post/PostCardImageCell.xib
Fixes #3961 
The buttons for the image post card were not subclassing `PostMetaButton` as they should.  This patch adds the missing inheritance to `PostCardImageCell.xib`. 
To test:
Replace `PostCardTableViewCell configureMetaButtons` with [this snippet](https://gist.github.com/aerych/091fd1eaaa7e8469c8ac) to randomly populate the title values of the like and comment buttons and confirm the titles never overlap the image, and the titles are never truncated. 
@kwonye would you be game for a review?
Needs Review: @kwonye
=> Makes buttons extend PostMetaButton

WordPress/Classes/ViewRelated/Post/PostCardActionBar.m
Closes #3894 
To test:
- The most reliable way is probably to use the iPad simulator. 
- Hold down the option button to display the touch indicators. 
- Position them above the preview and stats buttons on a card, and then click your mouse. 
Set a break point in `PostCardActionBar handleButtonTap:` to ensure only a single tap is registered.
@diegoreymendez since you're familiar with this one would you be up for the review? 
=> Let post card action buttons have exclusive touch.

WordPress/Classes/ViewRelated/NUX/LoginViewModel.m
2. Enter the credentials for an account with 2FA enabled
3. Whenever requested, enter an invalid One Time Code
4. Tap over the background to dismiss the keyboard
5. Tap login again.
As a result, the app is expected to submit the credentials again, and request the Multifactor Code.
Fixes #3983
Needs Review: @sendhil || @diegoreymendez 
=> Login: Stuck with an invalid Multifactor Code

WordPress/Classes/Networking/ThemeServiceRemote.h, WordPress/Classes/Networking/ThemeServiceRemote.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/ThemeServiceRemoteTests.m
Adds the services we're going to use for themes in our app.  Also adds unit tests for those services.  I specifically separated this from a larger set of changes since it was becoming too large (1k+ changes).  I'll soon be adding a VC to test these services from within the app.
**Test:**
- Run the unit tests, make sure they don't fail.
**Additional testing:**
Since the services are not currently wired, they will be tested in the upcoming themes view controller.
**Additional Code Checks:**
- When reviewing the code take a momento to make sure the services URLs match the URLs available for the themes services [here](https://developer.wordpress.com/docs/api/console/).
/cc @jleandroperez, @aerych
=> Adds theme services.

WordPress/Classes/Services/PostService.m, WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion, WordPress/Classes/WordPress.xcdatamodeld/WordPress 35.xcdatamodel/contents, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/PageModelTest.m, WordPress/WordPressTest/PostModelTest.m
Adds tests
Closes #3888 
This is the same as #3891, but targeting the 5.5 release.  As it turns out revision `WordPress 34` was introduced in the 5.4 branch so this introduces `WordPress 35`.  So much for avoiding an extra revision.
From the original PR:
> This PR updates the default values for new post and pages. Status is defaulted to publish and metaPublishImmedately is defaulted to true. This let us remove some initialization for new drafts from the PostService and keeps defaults in the model.
Tests were added for checking default properties are correctly assigned and that changes to either the date_created_gmt and remoteStatus are properly reflected in the meta properties used for sorting. 
Needs Review @astralbodies @diegoreymendez
=> Updates default values on BasePost and AbstractPost models

WordPress/Classes/Services/AccountService.h, WordPress/Classes/Services/AccountService.m, WordPress/Classes/Services/BlogService.h, WordPress/Classes/Services/BlogService.m, WordPress/Classes/Services/CommentService.h, WordPress/Classes/Services/CommentService.m, WordPress/Classes/Services/JetpackService.h, WordPress/Classes/Services/JetpackService.m, WordPress/Classes/Services/LocalCoreDataService.h, WordPress/Classes/Services/LocalCoreDataService.m, WordPress/Classes/Services/MediaService.h, WordPress/Classes/Services/MediaService.m, WordPress/Classes/Services/PostCategoryService.h, WordPress/Classes/Services/PostCategoryService.m, WordPress/Classes/Services/PostService.h, WordPress/Classes/Services/PostService.m, WordPress/Classes/Services/PushAuthenticationService.swift, WordPress/Classes/Services/ReaderPostService.h, WordPress/Classes/Services/ReaderPostService.m, WordPress/Classes/Services/ReaderSiteService.h, WordPress/Classes/Services/ReaderSiteService.m, WordPress/Classes/Services/ReaderTopicService.h, WordPress/Classes/Services/ReaderTopicService.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/LocalCoreDataServiceTests.m
Turns LocalCoreDataService into a superclass, thus reducing code redundancy since all classes implementing the old protocol shared the initialization code and the `manageObjectContext` property.
**Test 1:**
- Run the unit tests
**Test 2:** (this is pretty broad, but I tried to make the change as atomic as possible to make the review easier)
- Launch the app and move around the different sections, thus triggering service calls.
- Make sure no service call fails because of this.
/cc @kwonye, @jleandroperez
=> Turns LocalCoreDataService into a superclass.

WordPress/Classes/ViewRelated/NUX/LoginViewController.m
2. Enter the credentials for a 2FA-Enabled account
3. Enter an invalid code
The keyboard should get dismissed, and an error should appear onscreen (Invalid OTP). However, the Username Field should remain disabled.
Fixes #3985 
Needs Review: @aerych (Thanks in advance Eric!)
=> LoginViewController: Prevents setting full alpha on disabled fields

WordPress/Classes/ViewRelated/Pages/PageListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewControllerSubclass.h, WordPress/Classes/ViewRelated/Post/PostListViewController.m
Fixes #3966 
All local-only `AbstractPosts` have a `postID` of `-1`.  This led to an inconsistent row count when trashing a local post when the app had more than one local post saved. 
Rather instead using the postID to reference a trashed post in an `NSPredicate`, we'll use the post object's `NSManagedObjectID` which should always be unique.
Steps to reproduce the error are included in the issue.
@bummytime since this is tangentially related to the editor would you mind taking a peek?
@astralbodies Would you mind vetting the Core Data voodoo at play?
Needs Review: @bummytime @astralbodies
=> Reference trashed post/page by NSManagedObjectID not postID

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/ViewRelated/Blog/BlogListViewControllerTests.m
Addresses #3975
Testing instructions:
On the site picker, click 'edit'. Search button should be disabled. Clicking 'done' will re-enable the search button.
=> Disable search button when in edit mode

WordPress/Classes/Networking/PostServiceRemoteREST.m
Refs #3973 
Applies the same work around for scheduled posts used for the XML-RPC API to the REST API.  This accounts for an API inconsistency where a 'future' status of a scheduled post is ignored. 
Ideally this is something we could address at the REST API level, however since we have the same treatment for XML-RPC I think its reasonable to have in-app patch while exploring an API fix.  Its at least consistent. 
=> Ensure scheduled posts are uploaded with a publish status via REST.

WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
This PR updates the Bold font, used all over in Notifications, to `Open Sans Semi Bold`.
This can be verified in both, the Notifications List, and the details view for any comment notification.
Closes #3974
Needs Review: @aerych (Thanks sir!)
=> Updates Notifications Bold Font

WordPress/Classes/ViewRelated/Settings/SupportViewController.m
Fixes #4008
1. Fresh install WPiOS on an iPad device
2. Tap over the top right icon (Help!)
As a result, the Support view should be onscreen. The dismiss button should be *on the right* side of the navBar.
Needs Review: @aerych (Thanks Eric!)
=> SupportViewController: Dismiss button goes on the left

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
This fixes two of the three problems listed in #3910 :
>  1. The user taps once on a post to bring up the editor, however when they want to return to the post list screen they need to tap twice. (once to exit edit mode and once to return to the post list screen from preview mode).
>
>  3. Even though we are editing an existing post, the navbar command in the upper right corner starts as "Post" and then changes to "Update" after the screen transitions (admittedly, this could be a separate issue in github).
Per the current 'develop' branch code, when the user taps on a post in the list of posts, it opens the post view controller in preview mode (not edit mode). However, when the user taps on an 'Edit' button at the bottom of a post in the list of posts, it opens the post view controller in …
=> Fix issues in opening of the post view controller directly in edit mode

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Fixes the predicate for hideable blogs so it doesn't falsely return all blogs when there's no default account
Fixes #3932 
=> Show edit button only if there are hideable blogs

Podfile, Podfile.lock
Fixes #4010 
Bump the stats pod to 0.4.2 which includes the changes from 0.3.6 which was aimed at release/5.3.1 to prevent crashes during state restoration.
Changes: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/commit/eebff1229141214ff75671fe22632bf317bde696
Needs Review: @sendhil, @diegoreymendez
=> Bump stats pod to 0.4.2 to include state restoration fix from 0.3.6

WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion, WordPress/Classes/WordPress.xcdatamodeld/WordPress 34.xcdatamodel/contents, WordPress/Classes/WordPress.xcdatamodeld/WordPress 35.xcdatamodel/contents, WordPress/WordPress.xcodeproj/project.pbxproj
As a side effect of [this commit](https://github.com/wordpress-mobile/WordPress-iOS/commit/7eeb07ccd831998aec461fd24a6fada144ab8c97), Beta Users that were already in DataModel Mark 34 are getting logged off.
I'm simply adding a new Data Model, and moving over the new fields to it.
Needs Review: @sendhil + @SergioEstevao
=> Fixing Core Data Migration Error

WordPress/Classes/Services/BlogService.m
@astralbodies i'm afraid that the previous NSObjectInaccessibleException has proven to be ineffective.
Just got the crash again in the simulator (screenshot below). The spot in which it crashed had the *Account* entity effectively load, but the *defaultBlog* was faulted.
This fix should fix it, for real, this time!.
=> BlogService: Prevents NSObjectInaccessibleException

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Moved view admin to the first group on blog details and renamed it to 'WP Admin' for consistency
Fixes #4023 
=> Move view admin

WordPress/Classes/Utility/WPError.m
Fixes #4028
Needs Review: @aerych  (Thanks Eric!)
=> WPError: Stripping HTML from the Message String

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Blog/EditSiteViewController.h, WordPress/Classes/ViewRelated/Blog/EditSiteViewController.m, WordPress/Classes/ViewRelated/Post/EditImageDetailsViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Changes code to reflect the new name of UITableViewTextFieldCell -> WPTextFieldTableViewCell
=> Update to latest version of WordPress Shared.

WordPress/Classes/Utility/PushAuthenticationManager.swift
Whenever a Push Authentication Notification is received, if the app is open after (5) minutes, it'll have expired.
In that scenario, we'll display an AlertView indicating what happened. Let's update the `Accept` button, so that it reads `OK`, since there's nothing to actually accept.
Thanks @dmsnell for the suggestion!
=> PushAuthenticationManager: Dismiss AlertView should say OK

WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
1. Receive a Comment Y notification, with a link in it
2. Launch WPiOS and open the Notification
3. Tap over the `Approve` button to disapprove the comment
As a result, the comment's view style is expected to change. However, the link should still be visible.
Fixes #4037
Needs Review: @aerych (thanks in advance Eric!).
=> Updates the style of links in Unapproved Comments

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
Although i've been unable to directly reproduce this crash, let's add a failsafe, so that we avoid a potencial invalid scenario.
In this PR, we're simply updating the sequence in which the destructive action is performed, so that we guarrantee that the Notification is still alive at the point in which the **onCompletionCallback** block is executed.
Needs Review: @diegoreymendez (Thanks!)
Fixes #4046
=> Notifications: Updates onDestructionCallback Order

WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/NUX/WPNUXBackButton.m, WordPress/Classes/ViewRelated/NUX/WPNUXSecondaryButton.m
1. Fresh Install WPiOS
2. Press the `Create Account` button
3. Tap over the top right button
Note that the `Close` button of the modal screen should be placed at the exact same position as the `Back` that shows up in the `Create Account` view.
2. Tap over `My Site` > `Add Site`
3. Notice the position of the cancel button in the sign in modal.
4. Tap the (?) button in the top right to open the support screen.
The Navigation Buttons are expected to be displayed at the exact same position, so that it looks consistent.
I'm afraid that the NavigationBar Metrics are different for iPad / iPhone. Please, verify this PR in both devices.
Needs Review: @aerych  (I believe these changes look / feel okay Eric, thanks in advance!)
Fixes #4013
=> Fixes Login Layout Inconsistency

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
I've found incorrect Push Authentication Mixpanel Events. For some reason, they're Nosara-Style.
Since Push Auth hasn't been enabled, yet, for everyone, it'd be great to get this fixed ASAP.
Needs Review: @astralbodies (Thanks Aaron!)
=> Fixing inconsistent Push Auth Mixpanel Events

WordPress/Classes/ViewRelated/Reader/ReaderPostDetailViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderPostsViewController.m
Closes #4038 
This PR: 
Moves "Opened Article" stat from post list to post detail. It will now track posts opened from notifications.
Updates to proper naming convention.
Adds property to track offline views.
Bumps a post's "page view" state via the tracking pixel when its viewed in the reader.
To test:
- Follow one of your test blogs and add a new post to the blog. 
- Open the reader and view the Blogs I Follow feed. 
- Find your newly created post in the list and tap to view it.  (Do this a few times if you want more page views.)
- Wait a couple of minutes til the server side process has run.
- Go to your stats page either in the app or on the web and confirm that your reader views are registering as page views for your test post. 
=> Updates analytics for reader detail view.

WordPress/WordPress.xcodeproj/project.pbxproj
Addresses #4056
We had the exact same Module Name in all of our targets. This was causing odd side effects, such as Swift Unit Tests not building (after running twice in a row).
Needs Review: @sendhil 
=> Prevents Module Names Collision

WordPress/Classes/ViewRelated/Reader/ReaderPostsViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderViewController.m
Fixes #4059 
In #3860 (d860c744b342b0a9544f8e37aed5ae54345f244d) the app was altered so that a WPAccount would only ever exist for WordPress.com blogs and there would no longer be one for a self-hosted blog. This broke the Reader for users who only had a self-hosted account in the app as no posts would sync due to checks added in #2023 to prevent unnecessary syncing while signed out. 
This PR removes the checks for the number of accounts that are gate-keeping the post sync. Since it should be very rare that the app is ever on the sign in screen, the checks probably weren't doing much for optimization anyway. 
To test, follow the steps below in each of the scenarios described to confirm posts are loading correctly:
- Switch to the reader tap. 
- Confirm Freshly Pressed is loaded
- Confirm …
=> Removes checks for WPAccount when syncing posts for the reader.

WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/Networking/AccountServiceRemoteREST.m, WordPress/Classes/Networking/Remote Objects/RemoteBlog.h, WordPress/Classes/Services/BlogService.m, WordPress/Classes/ViewRelated/Reader/ReaderPostDetailViewController.m
Closes #4062 
Viewing a post detail in the reader should not bump the page view if the current user is an admin on the post's site, (unless the site is private). 
In this PR I'm leveraging an existing (but unused) `isAdmin` attribute on the `Blog` model.
To Test: 
Prep:
Be signed into WordPress.com since this is a wpcom only feature. 
Visit the blog list in the My Sites tab. This syncs blog info and updates the isAdmin attribute which wasn't previously set.
Scenario 1:
View a post in the reader from a private site you admin.
You should see the page view reflected in your stats after a few minutes (processing time) 
Scenario 2:
View a post from the reader in a public site you admin. 
You should not see a page view reflected in your stats. 
You can also set breakpoints to confirm the proper …
=> Alters pageview tracking for site admins of viewed post.

WordPress/Classes/Networking/PushAuthenticationServiceRemote.swift, WordPress/Classes/Services/PushAuthenticationService.swift, WordPress/Classes/Utility/PushAuthenticationManager.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/PushAuthenticationManagerTests.swift, WordPress/WordPressTest/PushAuthenticationServiceRemoteTests.swift, WordPress/WordPressTest/PushAuthenticationServiceTests.swift
Please, make sure to review this **after** merging #4056.
- Removed Invalid Imports (Main Project files should not be associated to the testing target).
- Added required imports to Swift Unit Tests (`import WordPress`!).
- Updated the visibility of several properties required by the PushAuth Unit Tests.
Needs Review: @sendhil (Last PR of the week, i promise. Thanks!!)
[Swift Unit Testing Reference](http://www.andrewcbancroft.com/2014/12/29/getting-started-unit-testing-swift/)
=> Unit Testing Target: Cleanup

Podfile, Podfile.lock
Closes #4064 
Updating to WordPressCom-Stats-iOS 0.4.3 includes a fix for switching the layout on iPhone to a 2x2 grid. This lets text expand a bit more on the smaller screen so words aren't cut off in different languages.
=> Update to latest stats pod

WordPress/Classes/ViewRelated/Notifications/Views/NoteSeparatorsView.swift
I've noticed a glitch in iPad Mini 1st gen (SD screen!). Notifications separators are currently being displayed in a color that looks slightly dimmer than expected.
In this PR we're patching up `NoteSeparatorsView`, which is the class in charge of drawing the Notification Separators.
1. Receive a Comment-Y Notification
2. Open the Notifications tab and tap on it
As a result, the Notification Details should be onscreen, and there should be separators between the three cells onscreen. Try disapproving / approving the notification, and notice that the separators color is way too clear.
--
--
--
--
--
**Needs review:** @aerych mind taking a quick look?. 
I missed a `CGContextSetShouldAntialias(ctx, false)`, and, as a result, the separators were being drawn in a different color.
Thank you!
=> Fixes Notifications Separators

WordPress/Classes/Networking/Remote Objects/RemoteTheme.h, WordPress/Classes/Networking/Remote Objects/RemoteTheme.m, WordPress/Classes/Networking/ThemeServiceRemote.h, WordPress/Classes/Networking/ThemeServiceRemote.m, WordPress/WordPress.xcodeproj/project.pbxproj
Follow up to [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/3947).
Improves the services by renaming the result blocks.  Also adds the `RemoteTheme.h` object for a more standardized approach.
This is part of [a much larger incoming PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/4070) that will integrate these services into the app.
**To test:**
1. Run the unit tests.  For now this should suffice until the services are integrated.
=> Review of remote theme services

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m, WordPress/Classes/ViewRelated/Notifications/Views/NoteSeparatorsView.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.xib, WordPress/WordPress.xcodeproj/project.pbxproj
1. To ease things out, hack [this method](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m#L202), so that the ratings view is always rendered
3. Switch to the Notifications Tab
Few seconds afterwards, the Ratings View should be onscreen. Note that the Section Headers should be displayed correctly, and the top and bottom separator's width should match with the cell's width.
Needs Review: @astralbodies (Thanks Aaron!)
Closes #4097
=> Notifications: Fixing Table Section Separators

WordPress/Classes/System/WPGUIConstants.h, WordPress/Classes/System/WPGUIConstants.m, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m, WordPress/Classes/ViewRelated/Me/MeViewController.m, WordPress/Classes/ViewRelated/Settings/ActivityLogViewController.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m
We've noticed that row heights are inconsistent in several spots of the app. Standard UITableViewCell's should be 44pt in height, while the `Site Row` [ Icon + Title + Description ] should be 54pt.
Props to @drw158 for the metrics / feedback on this one.
-- 
1. Log into your account
2. Verify that the following sections look great:
2.A. `My Sites`: Blogs rows should be 54pt height (44pt for the rest)
2.B. `My Sites` > `Site Details`
2.C. `My Sites` > `Site Details` > `Settings`
2.D. `Me`
2.E. `Me` > `Help + Support`
2.F. `Me` > `Help + Support` > `Activity Logs`
Needs Review: @aerych mind taking a look at this one?
[Sample Screenshots (Broken vs Fixed) can be found here](https://cloudup.com/cD1K4xN2oZs)
=> Normalizes Row Heights

WordPress/Classes/Utility/WPWebViewController+Auth.swift, WordPress/Classes/ViewRelated/Comments/CommentViewController.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderBrowseSiteViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderPostDetailViewController.m, WordPress/Classes/ViewRelated/Stats/StatsWebViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
I've recently come across a problem in which opening a link to a private blog, from within the Reader Post Details VC, would result in a WebView Authentication request.
Sadly, simply toggling `PrivateSiteURLProtocol` doesn't do the trick: the **bearerToken** must be sent to the `wp-login.php` endpoint, so that UIWebView gets the required cookie. 
For this reason, i've opted for implementing a simple **WPWebViewController** extension, that will pre-initialize the `username` and `bearerToken` fields with the default WordPress.com account's values, so that we just don't duplicate the same snippet all over.
--
1. Fresh install
2. Log into your main WordPress.com account
3. Open a post that contains a link to a private blog, and tap on it
As a result, the WPWebViewController should be …
=> Preventing Unauthenticated WebViews

WordPress/Classes/Utility/WPWebViewController.m
Closes #4113 
To test:
You will need a notification, or a post, or comment in the reader that includes a link without a scheme. Something to the effect of `//aerychtest.wordpress.com`.  In the reader any p2 theme site mention (+blogname) should do. 
Set a break point in `setUrl:` to observe the value being passed and confirm its missing a scheme. 
Set a break point after the patch to confirm the default scheme was added. 
Set a break point inside the patch to confirm that URLs with a scheme already defined are not edited. 
Needs Review : @jleandroperez
=> Adds default http scheme if absent from url.

Podfile, Podfile.lock, WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/Classes/Utility/WPTableViewHandler.m, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Blog/SettingsMultiTextViewController.m, WordPress/Classes/ViewRelated/Blog/SettingsTextViewController.m, WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m, WordPress/Classes/ViewRelated/Me/MeViewController.m, WordPress/Classes/ViewRelated/Post/EditImageDetailsViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Settings/AboutViewController.swift, WordPress/Classes/ViewRelated/Settings/ActivityLogViewController.m, WordPress/Classes/ViewRelated/Settings/NotificationSettingsViewController.m, WordPress/Classes/ViewRelated/Settings/SettingsViewController.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m
The latest WordPress-Shared release replaces **WPTableViewSectionHeaderView** and **WPTableViewSectionFooterView** with **WPTableViewSectionHeaderFooterView**.
In this PR we're updating the 14 ObjC spots in which the two legacy components were wired, plus 1 Swift spot. Please, verify the UI of the following sections:
- `My Sites` > `Blog Details`
- `My Sites` > `Blog Details` > `Settings`
- `New Post` > `Settings`
- `New Post` > `Add an Image` > `Image Details`
- `Me`
- `Me` > `Help and Support`
- `Me` > `Help and Support` > `Activity Log`
- `Me` > `About`
- `Notifications` > `Manage`
Needs Review: @SergioEstevao (Thanks in advance!)
=> Updating Shared Pod

WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.xib
1. Hack [this spot](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m#L677) and replace it with something like: `cell.commentText = @"The Dangling Pointer"`
2. Receive a Comment-Y Notification
3. Run the app using an iPad Simulator
4. Open the Notifications tab, and select the new notification
Verify that the Blog Name doesn't get clipped.
@astralbodies your blog's name was breaking the Notifications interface. You may either rename your blog to something that doesn't have descending characters issues... or review this PR please!
Needs Review: @astralbodies (Thanks in advance Aaron!)
Closes #4102
=> Notifications: Fixing blogName clipping

WordPress/Classes/ViewRelated/Post/PostCardCell.h, WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m, WordPress/Classes/ViewRelated/Post/PostListViewController.m
Performance optimization
Avoids a deadlock when rapidly starting and cancelling requests that's triggered in `PrivateSiteURLProtocol`
Refs: #4090 
=> Don't load images when computing layout.

WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewModel.h, WordPress/Classes/ViewRelated/NUX/LoginViewModel.m, WordPress/WordPressTest/LoginViewModelTests.m
There's a potential security issue where a password can get exposed through the following steps:
1) Open Login Screen
2) Enter password
3) Toggle show password button
4) Exit to home screen
5) Using a tool like iExplore check the snapshots folder, in it will be a snapshot of the app with an exposed password.
To fix this vulnerability I just toggle the password field to hidden if the user should decide to background the app.
=> Hiding the password when the user goes into that background

WordPress/Classes/ViewRelated/Comments/CommentViewController.m, WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Although i've been unable to directly reproduce this issue, apparently, what's going on is:
- The user is about to spam a comment.
- In the meantime, the comment was already trashed/removed.
- The local CoreData entity for this comment has been already invalidated.
With this patch, we're simply making sure that **CommentViewController** gets dismissed whenever the comment is spammed / trashed.
--
1. Receive a comment
2. Open `My Sites` > `Blog` > `Comments`
3. Open the new comment
4. Try trashing / marking as spam
As a result, CommentViewController should get dismissed. Note that (prior to this patch) the comment details view was being left onscreen.
Needs Review: @diegoreymendez (Thanks in advance Diego!)
Fixes #4084
=> Fixing NSObjectInaccessibleException Crash

WordPress/Classes/Models/WPAccount.m
Removes unused code from `WPAccount`.
- Make sure no other references exist to the removed property.
- Make sure the unit tests run as usual.
- Make sure the app builds as usual.
/cc @aerych
=> Removes unused code from WPAccount.

WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
This addresses a minor positioning glitch in some post cards due to the wrong value for constraint constants being used. 
When awakeFromNib is called, constraint constants have the default values for any w, any h. The constant values for the correct size class are not applied until the view is first moved to its superview. When this happens, it will override any value that has been assigned in the interrum. Hence the glitch. 
This patch implements a work around to preserve constant values after they have been updated for the relevant size class, and to configure a cell after this occurs.
=> Corrects a minor UI glitch due to using the wrong values for constraint constants

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Fixes #3822 
The constraint in question is actually not needed. 
To test:
Visit the site detail screen in the iPad simulator and navigate between its different features (stats, comments, posts, pages). 
Confirm the header view maintains its correct layout and position, even during rotation.
=> Removes superfluous (and breaking) constraint.

Scripts/localize.py
This Pull Request patches the `localize` Python Script, so that Swift files are also picked up by the `genstrings` script.
We've got plenty of Swift strings that never got localized, because they were never picked up.
Needs Review: @sendhil (Thank you!)
=> Localization Script Swift support

Podfile, Podfile.lock
Closes #4134 
Bumps Tracks pod to 0.0.6 to include the following bug fixes:
* User-Agent set on connection to REST endpoint. String is now updated automatically to include the actual pod version in it.
* Calculate the timestamp of an event in a way that is consistent across 32-bit and 64-bit processors.
=> Bump to Tracks 0.0.6 pod

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m
Sort the site list and site picker so that the primary blog appears first.
I'm not too happy with the readability of the code but it seemed like the simplest option: since core data relationships have to have an inverse, `accountForDefaultBlog` will only be set for the default
account's default blog. It will be nil for all the other blogs.
Fixes #2599 
=> Make primary blog first

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
I've been unable to reproduce the original issue. However:
- Two extra `layoutIfNeeded` calls have been added (for both, *view* and *tableViewHeader*)
- Killed the `if`'s nested level
Closes #4083
Needs Review: @diegoreymendez (thanks in advance!)
=> NotificationsViewController: Misplaced Ratings Failsafe

WordPress/Classes/ViewRelated/System/Search/WPSearchControllerConfigurator.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/4144).
Go to the sites list, tap the search field
Expectations
The return button in the virtual keyboard should read "Search" for iOS versions lower than 7.1, and be titled "Done" for iOS versions equal or greater than 7.1.
PS: couldn't test this myself on < 7.1 as I don't have any device running on a version of iOS that old.
/cc @sendhil
=> Fixes an issue for iOS < 7.1.

WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m
Fix crash on media picker.
To test it just open the media picker on a new post, switch to WP media library and the switch back again to other library. 
=> Unregister data source observer on media library.

WordPress/Classes/Extensions/NSAttributedString+Helpers.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.xib
1. Receive a comment on a testing blog, with the following content:
`Logged in as dennis after linking to dmsnell on WordPress.com (and disabling the login renamer)`
3. Tap over `My Sites` > `Comments`
4. Open the new comment
As a result, the text *should not* get clipped. Please, verify this one on both, iPhone and iPad devices.
- The comment itself is rendered by `NoteBlockTextTableViewCell`, which is a shared component between `CommentViewController` and `NotificationDetailsViewController`.
- This bug caused by Size Classes not being applied for the layout cell.
- In order to fix this, we've both, applied a workaround for the glitch outlined above, and updated the Content Hugging priorities.
- Extra padding at the bottom of the comment has been added.
- In order to have …
=> CommentViewController: Fixing clipped text

WordPress/Classes/Services/ReaderPostService.m
Fixes #4163 
To test:
1. Be signed into a WordPress.com account
2. Switch to the reader. Open the topics menu and choose a new topic to kick off a sync.
3. Very quickly switch to the Me tab and log out of WPcom before the sync finishes. 
You can use a network link conditioner to gain a bit of time if syncs are happening too quickly. 
cc @sendhil (Turned out to be a rather simple fix.)
=> Resets a derived context before merging posts.

WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.m
Fixes a crash trashing a post from the My Sites post list.
To test: 
- Navigate to the post list. 
- Tap the more button on a post cell
- Tap the trash button. 
The cell should transition to an "undo" cell and the app should not crash. 
=> Implements missing delegate method.

WordPress/Classes/Utility/LocationService.m
Increases the time out duration so places that are very slow to resolve can have a better chance of not failing. 
Prompted by a user's request: https://ios.forums.wordpress.org/topic/set-location-post-error-again?replies=4
=> Doubles location timeout duration

WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m, WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m
Re-submitting https://github.com/wordpress-mobile/WordPress-iOS/pull/4158 against `release/5.5`.
cc @SergioEstevao
=> Improved checks for request of media based on identifiers.

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/Comments/CommentViewController.m, WordPress/Classes/ViewRelated/Comments/CommentsViewController.m, WordPress/Classes/ViewRelated/Stats/StatsViewController.m
In this PR we're adding a top padding to `CommentViewController `, on iPad devices. Towards the #4128 goal, we're also normalizing the topPadding -within the commentsView- to be iOS's default (35pt instead of 40pt)
--
1. Launch WPiOS and log into your account
2. Tap over `My Sites`
3. Open any site
4. Tap over Comments
Expected: iPhone devices should have no top padding, while iPads should get 35pt top
--
1. Launch WPiOS and log into your account
2. Tap over `My Sites`
3. Open any site
4. Tap over Comments and open any comment
Expected: iPhone devices should have no top padding, while iPads should get 35pt top
--
1. Launch WPiOS and log into your account
2. Tap over `My Sites`
Please, test all of the rows, since the handling code has been normalized / cleaned up.
Closes #4151
Needs …
=> Comment Details Top Padding

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist
Fixes #4161 
We had left the Facebook URL scheme in the application from an old-SSO method from 2013 or earlier. Since we don't have the Facebook SDK in the app any more and we aren't handling the URLs being opened, remove it from the PLIST.
I noticed there was a problem when tapping on some posts from the Facebook iOS app caused WPiOS to launch. Nothing would appear in the WPiOS app.
=> Removes Facebook URL Scheme

WordPress/Classes/Networking/BlogServiceRemoteREST.m
2. Tap over My Sites
3. Open any of your blogs
4. Tap over the `Settings` row
As a result, the app _should not_ crash.
Fixes #4187
Needs Review: @diegoreymendez  || @sendhil
=> BlogServiceRemoteREST: Fixing settings parsing crash

WordPress/Classes/Networking/WordPressComServiceRemote.h, WordPress/Classes/Networking/WordPressComServiceRemote.m, WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m
This PR improves `WordPressComServiceRemote` by:
- Documenting its methods.
- Naming the block types used.
- Adding a few missing assertions.
- The assertions added made me realize that even though we were treating `languageId` as a number, it was actually a string object.  I fixed the data type.
**To test:**
2. At the login screen tap on "Create account"
3. Fill the forms
4. Make sure the account and blog are created.
=> Code quality improvements to WordPressComServiceRemote

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
2. Tap over My Sites
3. Pick any of your sites and tap over `View Site`
As a result, the WebView should display your website, in a logged state. The visit shouldn't increase the Site Stats, and the user should get the admin bar.
Fixes #3461
Needs Review: @astralbodies (Thanks in advance Aaron!)
=> BlogDetailsViewController: View Site should always post credentials

WordPress/Classes/ViewRelated/Views/CircularImageView.swift
1. Launch WPiOS on an iPad Air Simulator
3. Open any 'Likes' / 'Follower' notification
As a result, the list of new Followers / Likers should be onscreen. Note that the corners should be rounded.
Closes #4186
=> Fix: Gravatar rounding wrong on iPad

Podfile, Podfile.lock
Closes #4196 
Two bug fixes included:
* Prevent segmented control from being oversized when a translation makes it too wide.
* Provide a slightly better UX on Insights when data can't be fetched.
=> Update to stats 0.4.6

WordPress/Classes/Models/Notifications/NotificationSettings.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift
2. Tap over the `Me` tab
3. Open the `Notification Settings` row
4. Open `Updates from WordPress.com`
As a result, each one of the rows should have a descriptive footer. Please, try updating any of those settings, closing the NCC, and opening it back, to verify it effectively gets stored.
Closes #4202
=> Notifications Control Center: WordPress.com Footers

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift, WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
2. Open `Me` > `Notification Settings`
3. Scroll all the way down, until you find a blog with a `nil` site icon
As a result, the app shouldn't crash.
Thanks for helping me out Diego!
=> NotificationSettingsViewController: Implements Nil Site Icon Failsafe

WordPress/Classes/ViewRelated/Settings/SupportViewController.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/4211).
1. Go to the "Me" tab
2. Go into "Help & support"
3. Tap on "WordPress Help Center"
4. Make sure that the VC opens normally and the app doesn't crash.
(the same steps can be performed in an older version to reproduce the crash)
/cc @SergioEstevao, @jleandroperez, @sendhil (tagging three so this bugfix goes out quickly as it crashes for our testers)
=> Fixed a service path that was missing the API version.

WordPress/WordPressApi/WordPressComApi.m
1. In `WordPressComApi.m` add the line marked by the comment:
```objective-c
- (void)assertApiVersion:(NSString *)URLString
{
URLString = @"bad/bad/api"; // Add this line
NSAssert([URLString rangeOfString:@"v1.1"].length > 0
|| [URLString rangeOfString:@"v1.2"].length > 0,
@"Unexpected API version in URL: %@", URLString);
}
```
2. Launch the app and make sure any service is called.  The assertion should fail and show the URL added above.
/cc @sendhil
=> Added the URL that's causing the failure in the api version check.

WordPress/Classes/Models/AbstractPost.h, WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/Models/Media.h, WordPress/Classes/Services/MediaService.m
Closes #4096 
This goes against my knowledge of CoreData, that says that relationships with inverse are automatic filled but after some tests it looks they don't :(. Maybe it's because of the relationship being multiple to multiple?
=> Add object to the other side of relationship.

WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
Fix bug when using filtering on the WordPress Media Library for just images or videos.
How to test:
Create a post
Go to Post->Settings
Add a feature image.
Chose the media library
Check if the images from the media library.
If tested on the current version on the store or internal you will always see an empty list :(
=> Fix media filtering on picker.

Podfile.lock, WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.xib
2. Open the Notifications Tab and reply to a comment
3. Enter a +3 lines reply
4. Attempt to scroll up
As a result, the user should be able to scroll over the ReplyTextView's text.
Closes #4223
Needs Review: @aerych (Thanks in advance!!)
=> Fix: ReplyTextView Not scrollable

WordPress/WordPressApi/WordPressComApi.m
Fixes the following crash in `release/5.6`.
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unexpected API version in URL: https://public-api.wordpress.com/rest/v1/read/a8c'
```
/cc @sendhil
=> Allow v1 REST api calls.

WordPress/Classes/Models/Blog.m, WordPress/Classes/Networking/AccountServiceRemoteREST.m, WordPress/Classes/Networking/CommentServiceRemoteREST.m, WordPress/Classes/Networking/CommentServiceRemoteXMLRPC.m, WordPress/Classes/Networking/MediaServiceRemoteREST.m, WordPress/Classes/Networking/MediaServiceRemoteXMLRPC.m, WordPress/Classes/Networking/PostCategoryServiceRemoteREST.m, WordPress/Classes/Networking/PostCategoryServiceRemoteXMLRPC.m, WordPress/Classes/Networking/PostServiceRemoteREST.m, WordPress/Classes/Networking/PostServiceRemoteXMLRPC.m, WordPress/Classes/Networking/ReaderPostServiceRemote.m, WordPress/Classes/Networking/ReaderTopicServiceRemote.m, WordPress/Classes/Services/PostService.m, WordPress/Classes/Utility/WPMapFilterReduce.h, WordPress/Classes/Utility/WPMapFilterReduce.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m, WordPress/WordPress_Prefix.pch
Replaces common map/filter patterns with the new methods from #4156 
I've tried to replace only very obvious cases, and I've left alone a few things that could match the map pattern, but performed some other side effects (e.g. Service classes that could create new core data objects inside the map block).
=> Adds usage of WPMapFilterReduce

WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/Models/Media.h, WordPress/Classes/Models/Media.m, WordPress/Classes/Services/MediaService.m, WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Cleans code around the media model and detection of a feature image.
The MediaTypeFeatured enum didn't make sense, because the same Media model object can be used in two different posts and be featured on one and not in the other. 
The proper checks need to be done using ```post.post_thumbnail```.
=> Media - Featured image cleanup

WordPress/Classes/Categories/NSURL+Util.m, WordPress/Classes/Utility/WPWebViewController.m
I've noticed that the `WPWebViewController` tool was appending, almost always, `wp-login.php`. Even to 3rd party URL's, such as github links, and self hosted blogs that didn't really require authentication.
Logic was patched, so that we only retry with credentials whenever we hit a `wp-login.php` url.
Plus, `NSURL`'s `isWordPressDotComUrl` helper has been patched to reuse `NSString`'s `isWordPressDotComUrl`. Reason for that is: the NSString implementation is (A) already unit tested, and (B) is more robust. Links such as `https://href.li/?https://lanteanartest.wordpress.com/` are no longer detected as `WordPress.com`, and thus, won't fail to load.
1. Launch WPiOS and open the reader
2. Find any post that contains links to a github // elsewhere
3. Attempt to load those links. They should …
=> WebViewController: Don't retryWithLogin when not needed

WordPress/Classes/Models/AbstractPost.h, WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/Models/Post.h, WordPress/Classes/Models/Post.m, WordPress/Classes/Models/PostCategory.h, WordPress/Classes/Models/ReaderPost.h, WordPress/Classes/Services/PostService.m
Fix the relationships that where using NSMutableSet with this recommendations:
See what they say here: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CoreData/Articles/cdAccessorMethods.html#//apple_ref/doc/uid/TP40002154-SW7
```
You declare attributes and relationships as you would properties for any other object, as illustrated in the
following example. When you declare a to-many relationship, the property type should be NSSet *. (The
value returned from the get accessor is not a KVO-compliant mutable proxy—for more details, see To-many relationships.)
```
=> Fix CoreData relationships using ns mutable set

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
2. Tap over `Me` and open the `Notification Settings`
As soon as any of the `Blog` rows show up, they should display an icon at the right side.
Props to @sendhil for pointing this one out!
Needs Review: @sendhil (Thanks sir!!)
=> NotificationSettingsViewController: Fixes invalid var mapping

Podfile, Podfile.lock
Fix crash for non retina iPads.
=> Update media picker version to 0.6.0

WordPress/Classes/Models/AbstractPost.m
Fix for a crash detected on fabric.
=> Check for mediaID that are nil before comparing.

WordPress/Classes/Models/Notifications/NotificationSettings.swift
1. Log into the app
2. Tap over `Me` > `Notification Settings`
The last row should say `Email from WordPress.com`.
Needs Review: @diegoreymendez (Thank you Diego!
Closes #4252
=> NotificationSettings: Updates wpcom Settings Description

WordPress/Classes/ViewRelated/Reader/CommentContentView.m
Fixes a crash in iOS 9 due to a type mix match defining two constraints. 
Exception:
>  *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:]: A constraint cannot be made between a leading/trailing attribute and a right/left attribute. Use leading/trailing for both or neither.'
To test: 
Confirm the crash by launching an iOS 9 simulator and viewing comments in the reader. 
Confirm the fix by repeating the steps and ensuring there is no crash.
=> Fixes a crash due to mismatch creating constraint.

WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist
1. Log into an account with a self hosted blog, that doesn't support HTTPS
2. Tap over `My Sites` and open your blog's details
3. Tap over `View Site`
As a result, the error pasted at the bottom would (normally) show up onscreen. In this PR we allow unencrypted `http` requests (iOS 9 security feature).
Needs Review: @sendhil 
```
UserInfo={NSErrorFailingURLStringKey=http://www.lantean.co/, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLKey=http://www.lantean.co/}}, NSErrorFailingURLStringKey=http://www.lantean.co/, NSErrorFailingURLKey=http://www.lantean.co/, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a …
```
=> iOS 9 Fix: Enabling Arbitrary Loads

WordPress/Classes/Networking/WordPressComServiceRemote.m
Fixes the new-user and new-site services that were causing issues in WPiOS 5.6.
1. Launch an HTTP-request intercepting app (such as Charles).  Configure it to work with WPiOS.
2. Launch WPiOS.
3. At the login screen create a new account.
4. Make sure the account and blog are created properly.
5. Review the HTTP request logs to make sure the endpoints `v1.1/users/new` and `v1.1/sites/new` were called.
**Not to testers:** don't rely on the account and site being created only, since there's a hack @ the server side to allow this to work even if the version isn't set in the request.  That's the reason why I mention above that we should make sure the request URL contains the proper version number in its path.
/cc @sendhil, @jleandroperez
=> Fixes the new-user and new-site services.

WordPress/Classes/Networking/ReaderSiteServiceRemote.m, WordPress/WordPressApi/WordPressComApi.m
Fixes an issue checking the existence of a site before following it.  The original call was just a HEAD request to the site to ensure it did not 404, but was accidentally included in the rest endpoint refactor.
To Test: 
Open the Reader's menu and try to follow `ma.tt`
Confirm you do not see a 404 error and are able to successfully follow the blog.
=> Fix 404 error following sites from menu.

WordPress/Classes/Utility/DisplayableImageHelper.m
Closes #4296 
Prevents WP core emoji images from being picked up as featured images by the reader. 
To test:
View a post in the reader that contains only wp core emoji images, like [this one](https://wordpress.com/read/post/feed/18/813616864).  The easiest way might be to LIKE the post, then check your LIKED feed.
Confirm that the emoji is not chosen as the featured image, both in the list and the detail.
@SergioEstevao would you be game for a quick review?
=> Ignore core emoji images.

WordPress/Classes/Networking/ReaderSiteServiceRemote.m, WordPress/WordPressApi/WordPressComApi.m
Rolls back cef0d7de8b8622295e197498e62135f184202a95 and replaces it with a generic check.
To test: 
Try to follow a site via the reader's menu such as:
ma.tt, or gizmodo.com
=> Use a generic request when testing if a site exists.

Podfile.lock, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift, WordPress/Classes/ViewRelated/Views/NavigationTitleView.swift
1. Log into your account
2. Tap over `Me` > `Notification Settings`
3. Tap over any of the settings rows (both, for any of your blogs, and `Comments on other sites`)
4. Tap over (any) of the available streams
As a result, the Setting Details view should display a two-lines Navigation titleView, outlining the name of the blog / stream.
Closes #4240
=> Notifications Stream Setting Details

Podfile, Podfile.lock
Closes #4317 
Updates Tracks client to 0.0.8 which includes:
* Xcode 7 support (which really doesn't affect the pod)
* Reduces the chattiness of the logging in the client
Lockfile got updated with UIDeviceIdentifier as well.
Needs Review: @sendhil, @aerych
=> Updated to Tracks 0.0.8

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
1. Receive a Stats notification
3. Open the Notifications tab, and open the new notification
4. Tap your site's name (last visible link).
As a result, the native Stats view should be onscreen.
Closes #4313
Needs Review: @koke  (Thanks in advance!)
=> Notifications: Fixes Stats bridge

WordPress/Classes/Categories/NSString+Helpers.m, WordPress/Classes/Utility/DisplayableImageHelper.m, WordPress/WordPressTest/NSStringHelpersTest.m
Closes #4298 
Adds a check for images that are core emoji. 
Converts matches to their emoji string equivalent. 
Adds unit tests.
To test: 
Confirm the emoji shown in #4298 is showing the correct size. 
Need Review: @koke
=> Reader: Replace images from core emoji with emoji strings.

Podfile.lock, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderViewController.m
Returns nil for fetchRequest when the topic is nil.
Delete orphaned poss when starting the reader.
Closes #4324 
Steps to test are included in the issue. 
=> Fixes a crash when posts are returned for a null topic.

WordPress/Classes/Extensions/Notifications/Notification+Interface.swift
During our Swift 2.0 migration, i've found this snippet, from ancient times. Notifications Section Identifiers used to have two attributes, joined by a `:` character.
This is no longer the case. In this PR we're cleaning up the code that used to process this.
2. Open the Notifications Tab
3. Make sure that the Section Titles look okay
Needs Review: @astralbodies (Thanks in advance!)
=> Notification+Interface: Cleaning up dead code

WordPress/WordPressTest/NSStringHelpersTest.m
Fixes an issue with one of the string helpers tests. 
I broke this one when updating the emoji helpers to inspect an image tag's `alt` attribute. Doh!
=> Removes mismatched alt attribute.

Podfile, Podfile.lock
Closes #4333 
Updates to the latest stats pod which includes the following updates:
* Adds latest post summary to Insights
* Persists the last selected tab in stats so the user comes back to the same section they left off with
* Fixes issues with sizing and layout on iOS 9 and iPad multitasking
Testing was done with StatsDemo on the stats project but a good once-over with rotations, iPad multitasking, iPhone 6 Plus and non-iPhone 6 Plus would be good. Getting some iOS 7 testing in would be beneficial too.
Needs Review: @sendhil, @jleandroperez
=> Updated to stats pod 0.4.8. EmailChecker got bumped too for some reason.

Podfile.lock, WordPress/Classes/ViewRelated/Post/PostCardCell.h, WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m, WordPress/Classes/ViewRelated/Post/PostListViewController.m, WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.m, WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
After noticing some jank scrolling in the post lists, I used the Time Profiler to take a look at performance. There was a bit of wasteful work being done when cells were configured.  This PR improves scrolling by avoiding unnecessary work when computing layout and redundant work to configure views already properly configured.
To test: 
Run this branch on a device and observe the scrolling performance compared to scrolling in the develop branch for the Reader post list, and the My Sites post list. 
Needs review : @astralbodies
=> Reader, Post List: Improves scrolling performance in reader and post lists

Podfile.lock, WordPress/Classes/ViewRelated/Post/PostCardImageCell.xib, WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m, WordPress/Classes/ViewRelated/Post/PostCardTextCell.xib, WordPress/Classes/ViewRelated/Post/PostListViewController.m, WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.m
Closes #4332 
Closes #4285 
Tweaks margins and spacing in the post cards, and fixes an issue where row height was incorrectly computed, resulting in some content being cropped. 
Pinging @mnt and @shaunandrews for a pixel sanity check. Shaun this is the PR we chatted about (much) earlier that updates the post cards to match the margins in the reader cards.  To get the right spacing between text field I'm taking the delta of the font-size (which seems to match the cap-height) and line-height for each element and then adding to make a multiple of eight.  It seemed like the right approach but some of the vertical spacing looked off so I've fudged it in a few places.  Maybe there is a more reliable way?
The iPad keeps the larger font sizes, line heights, and left/right margins which it had …
=> Post list cards layout tweaks

Podfile.lock, WordPress/Classes/Extensions/UIAlertController+Helpers.swift
Instead of loading the UIApplicationDelegate's *window*, we should be loading the *keyWindow*.
This will, potentially, save us few headaches, if apps ever get multiple windows. iOSX!
=> Updates UIAlertController Helper

README.md
Pointing to generic style guide that has links to both the Objective-C and Swift style guides
The Objective-C style guide was a page in the wiki while the Swift style guide was its own repo.
I created an Objective-C style guide repo to match the swift style guide, and redirected the `README.md` to point to the generic style guide page which has links now to both repos.
@sendhil this may affect Freshly Pressed(?)
=> Adding swift style guide

WordPress/Classes/ViewRelated/Stats/StatsWebViewController.m
Previous code was trying to authenticate to WordPress.com with the site
username, so the authentication would fail.
=> Fix authentication for web stats

Podfile, Podfile.lock
Closes #4372 
Adds fixed for better iOS 9 support including autolayout tweaks and proper resizing for multitasking.
Changes reviewed under PR: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/pull/329
=> Update to latest stats pod with iOS 9 fixes

WordPress/Classes/Services/CommentService.m
Fixes #4369 
To test:
- While on the Reader tab, view the comments for a post.  My approach was to Like a post on my test blog, switch to the Liked feed and view comments for that post. 
- Tap the "Reply" button on one of the comments, enter some text and submit the reply. 
Confirm that the reply shows up in the list as a child comment in the correct location.
Needs Review: @kurzee would you do the honors?
=> Comments: Ensure objectID of a newly created hierarchical comment is not a temp

WordPress/Classes/Services/BlogService.m
When I enabled Jetpack REST, I added a migration method so any self
hosted that were manualy added and then connected would show up as sites
from the WordPress.com account.
Since this only looked at the account's `jetpackBlogs`, it would only
work for sites that were already connected in the app.
The new method will search through all blogs that don't have a wp.com
account for a match.
Fixes #4370 
The issue could be reproduced by adding a self hosted site, then signing in with the associated wp.com account from the Me tab.
=> Fixes Jetpack site migration

Podfile, Podfile.lock, WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #4376 
Updated stats view controllers to use weak references inside of the remote callbacks to prevent a table view lifecycle issue. This was a rare-ish crash but I think can be attributed to a few different instances of animation updates in table views crashing the app.
Needs Review: @sendhil, @koke
=> Updated to stats pod 0.4.10 to prevent crash with early dismissal

WordPress/Classes/ViewRelated/NUX/LoginViewController.m
1. Fresh install WPiOS, on a device with 1Password installed
2. Tap over the `Add Self-Hosted Site` button
3. Press the 1Password button
As a result, you should get an AlertController onscreen, requesting for the site's URL.
Thanks Aaron!
=> LoginViewController: Nukes UIAlertView

Podfile.lock, WordPress/Classes/Networking/ReaderTopicServiceRemote.h, WordPress/Classes/Networking/ReaderTopicServiceRemote.m, WordPress/Classes/Services/ReaderTopicService.m
Closes #4404 
I wasn't able to reproduce the crash case.  I have a theory that the slug might just be missing from the data returned by the endpoints in some weird scenario but I can't account for that either.  
In lieu of an answer I'm adding a fallback to compose a slug if one is missing. 
@bummytime would you mind a review since you're familiar with this one? 
=> Reader: Prevent a crash when a slug is nil.

WordPress/Classes/Services/ReaderSiteService.m
Closes #4413 
The success block was not being called for some follow/unfollow methods.  
Derp.
=> Reader: Maybe we should...I dunno...actually call `success`

WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
refs #4355 - of the writing settings, enabling or disabling geo-tagging is up to the user whatever its role on the blog is. This change keeps the geotagging switch visible when the user is not admin.
Validation: 
- made sure the setting was persisted and consistent for each blog
- verified that enabling geo-tagging for one blog, doesn't enable it for all the blogs
- verified that location was sent when geo-tagging is active, and not sent when geo-tagging is not active
Note:
- when dealing with a self-hosted blog, the option will still show up (as it did before this change)
=> make geotagging setting available when not admin

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Resources-iPad/MainWindow-iPad.xib, WordPress/Resources/MainWindow.xib
Also refreshes the MainWindow xibs. Just viewed them in the editor and let Xcode do whatever magic it does. :p 
Closes #1162  (again)
Wasn't able to reproduce [the original issue](https://ios.trac.wordpress.org/changeset/3477) that those lines were supposed to fix. 
=> Removes code that sets window bounds from app delegate.

WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
Closes #4402 
The share link was being set as a String instead of an NSURL. This was causing our application share targets to not appear. 
To test: 
Go to the reader post list, tap the ( ... ) icon in one of the post cards and choose "Share" in the action sheet.  Confirm that WordPress, etc. are included as share options. 
@astralbodies The optional unboxing in this PR works but I think its a bit ugly.  I'd be game to go a different route but couldn't think of one I liked better. Suggestions welcome!
=> Reader: url should be an NSURL not a String.

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Closes #4419 
As a fix this PR is just a guess as don't see an execution path where `viewWillLayoutSubviews` can be called prior to `viewDidLoad` but I don't see another way to account for the crash.  Worst case the patch does nothing. :( 
=> Reader: Adds check for isViewLoaded

WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
Closes #4437 
To test: 
View Site Settings in the app and confirm the change to the privacy hint text. 
=> SiteSettings: Updates hint text.

WordPress/Classes/ViewRelated/Settings/SettingsViewController.m
Makes the slider speak a value in pixels instead of percentage, and hide that value from the label.
Before/After Video:
https://cloudup.com/cq9DfBfM9ZQ
=> Improve accessibility of media size settings

WordPress/Classes/System/WordPressAppDelegate.h, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderViewController.m
Adds a new check to see if the test suite is running. 
If the suite is running, skips syncing the Reader.  We could likely extend this to other "sync" tasks as well. 
Not %100 sure that `WordPressAppDelegate` is the best place for the check to live but I didn't see a better candidate and I'm reluctant to create a new category just for a single check. 
Needs review @jleandroperez
=> Skip syncing reader when test suite is running.

WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m
Addresses #4459 
Decided to go with option 1 (Disallow them to input a space in relevant fields) with the relevant fields being email, username, and site address as other apps follow this strategy.
=> Disallow spaces in every field except password

WordPress/Classes/ViewRelated/Me/MeViewController.m, WordPress/Classes/ViewRelated/Settings/SettingsViewController.m
Since the restoration method called init, it would restore as a plain table view and look all weird.
Needs Review: @oguzkocer
=> Fixed Settings controller restoration

WordPress/Info.plist
Fixes #4463 
Turns off the multitasking for WPiOS as it shouldn't be on yet until 5.8.
This is aimed for 5.7.1.
=> Turns off multitasking

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m
Resolves #4466
Fixes it for both the `BlogListViewController` and `PostListViewController`
Repro steps:
1. Open search in portrait
2. Rotate to landscape
3. Rotate back to portrait
Expected:
The search bar is correctly sized in both landscape and portrait mode
=> Rotation causes search bar to sized incorrectly

WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
1. Receive a Comment-Y notification
2. Open the Notifications tab
3. Tap over the *Notification Header*
4. As a result, Reader Comments should be onscreen.
Please, verify that: if you've got reply permissions on that blog, the `ReplyTextView` component should show up.
Closes #4312
cc @sendhil 
Thanks gentleman!
=> ReaderCommentsViewController: canComment property is now calculated

WordPress/Classes/Utility/WPUserAgent.m, WordPress/WordPressTest/WPUserAgentTests.m
Some web servers (e.g. Facebook video) misinterpret the current `User-Agent` string as if the app was a feature phone and was only able to parse WML content, e.g.:
wp-iphone/5.7 (iPhone OS 9.1, iPhone) Mobile
So, append "wp-iphone/<version>" to the UIWebView's default `User-Agent` string and use it instead:
Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B137 wp-iphone/5.7
Fixes #4295.
=> Use more detailed HTTP "User-Agent" header so web servers won't fallback to XHTML / WML

WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
Refs #4477 
The cause of the crash is unknown but it seems to be due to a problem getting a blog's subdomain.  Its potentially due to a specific post being returned from the REST API but feedback from an affected user indicates the crash happens as soon as the Reader tab is accessed. This leaves us unable to confirm which posts are being viewed.
This PR improves the way a url path is parsed for a subdomain.  It also should handle the rare situation where the passed string has a zero length -- potentially happening if a cached v1 REST endpoint is being queried. 
@jleandroperez may I call on your Swift expertise since this is a code change we probably can't vet by reproducing the crash.
=> Reader: Better handling of URL

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Refs #4419 
I started to go this route in #4469 but decided against adding a new bool and instead to just check for nil.  That approach worked fine but then we discovered a new edge case where the topic could be assigned after the view was loaded but before `viewDidLoad` was called.  (Seriously, wtf.)  
This PR adds a bool flag to check if the view has been setup in `viewDidLoad` before doing anything that would trigger the related crash cases. 
cc @jleandroperez as an FYI cos of the upcoming merge back to 5.8. 
=> Reader: Fix for #4419 take tre

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/747).
Applies a local change to fix this, and changes by @bummytime in the editor pod.
1. Launch app
2. Go to any blog with posts you can edit
3. Tap on a post with title and content to edit it
4. Editor should open up with title and description properly set
5. Go back to the post list
6. The post should show the proper title and description
=> Fixes a bug with the posts editor.

Podfile.lock, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Refs #4419
This is a re-do of #4496 (and friends) targeting the 5.8 branch instead of 5.7.1. 
If there is a "take the fifth" I believe I shall, and then promptly drink it whole. :P 
#4496 already had a :shipit: but pinging again for paranoia sake.
Needs Review : @sendhil
=> Reader: Fix for #4419 take the fourth

Podfile.lock, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController_Internal.h, WordPress/Classes/ViewRelated/Post/WPPostViewController.h, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Update all the code that use UIAlertView, UIActionSheet and UIPopover to be compatible iOS 9 code.
As a side effect this code also makes things work better on iPad on multitask mode and iPhone Plus on landscape mode.
In order to test it some scenarios that use these views need to be reviewed on regular iPhone, iPhone Plus and iPad
- Edit post and click on the X button to see the discard alert/actions
- Add images and/or video and click on them while the upload is happening
- Click on the blog selector
- While uploads are going click on the HTML switch or try to close the editor.
Needs Review: @jleandroperez, thanks in advance!
=> Remove deprecation alerts from post editors

WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m
This PR just cleans one missing ALAsset code that missed on the upgrade to Photos.
=> Remove last remain of ALAsset from legacy editor.

WordPress/Classes/Utility/WPThemeSettings.m
Enables support for theme-enabling URL with internal builds.
Test: wpinternal://themes?enabled=1 results in 'Themes Enabled' alert in the app.
=> Allow enabling theme browser with internal builds

WordPress/Resources-iPad/MainWindow-iPad.xib
Set build version of the nib file to the deployment version of the app. This removes a warning from the project.
=> Fix build version of MainWindow for iPad nib file

MIGRATIONS.md, WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion, WordPress/Classes/WordPress.xcdatamodeld/WordPress 41.xcdatamodel/contents, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/CoreDataMigrationTests.m
This PR recreates #4481, which was merged against Release 5.7.1.
We had to revert #4481 (Ref. #4497) because Beta 5.8 was already shipped, and merging 5.7.1 back into 5.8 would log off (ALL) of our beta testers.
1. Install WPiOS 5.8
2. Log into your account
3. Install, on top of it, this branch
4. Make sure you don't get logged out, and the `Notifications` are still accessible
1. Run `CoreDataMigrationTests.testMigrate40to41`
2. Make sure the unit test passes correctly
cc @astralbodies + @aerych (sorry guys, we had to revert the previous PR, and resubmit against 5.8)
Closes #4456
=> Notifications: 64 bit ID field

WordPress/Classes/ViewRelated/System/WPTabBarController.m
In this PR we implement **a violent hack** to address iPad Pro's Notification Icon misplacement.
I've opted in favor of this mechanism... because in one shot, we can solve the layout in all of the available devices (even in Multitasking), instead of adding more constraints per screen size.
Please, verify this in (as many devices as possible), and in Multitasking mode.
[You may hack this spot](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/System/WPTabBarController.m#L494) to simulate "Pending Unread Notifications".
Needs Review: @kwonye 
Thank you sir!
=> iPad Pro: Notification Icon Position

WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
Closes #4508 
To test:
Open the Reader, and switch to the Discover feed. 
Scroll through the list of posts.  Posts that show attribution should not show a like or comment buttons. Posts that are original content and do not show attribution *may* show like and comment buttons. 
=> Reader: Hides action buttons when showing attribution.

WordPress/Classes/Services/AccountService.h, WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
Adds nullability annotations to `AccountService` for better Swift integration.
Extracting this from #4510
=> Adds nullability to AccountService

WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
Closes #4512 
Some users may still be subscribed to FP.  We'll remove that tracking at a future date. For now we'll just start tracking Discover.
=> Reader: Adds analytics for Discover feed.

WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Info.plist, WordPress/Wordpress-Alpha-Info.plist
Fixes https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/724
This PR should prevent the editor's navbar blog picker from overflowing into the buttons on the right side of the screen (when WPiOS is in the compact size class). 
Run WPiOS on small + large devices (and also in multitasking modes)...try and get it to look like this:
/cc @sendhil would you mind looking at this?
=> Editor navbar fix for compact size class.

WordPress/Classes/Networking/BlogServiceRemoteREST.m
Closes #4517 
This is a stopgap for a crash when the value assigned to the parameters dictionary is nil.
A more robust treatment is commited in #4445 but targets the 5.9 release.
When merging back to develop this patch can be discarded in favor of #4445.
Needs Review @jleandroperez
=> Site Settings: Adds nil check when updating site settings.

MIGRATIONS.md, WordPress/Classes/Models/AccountSettings.swift, WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion, WordPress/Classes/WordPress.xcdatamodeld/WordPress 43.xcdatamodel/contents, WordPress/WordPress.xcodeproj/project.pbxproj
I'm adding just the data model in a separate PR so it's merged as soon as possible to avoid conflicts
I had to add `AccountSettings.swift` since the data model references the entity class
Refs #4499, #4510 
=> Data Model for My Profile/Account Settings

Podfile, Podfile.lock, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/BlogJetpackTest.m
Things that I've changed to get this to build:
- Update CocoaLumberjack to 2.2.0
- Updated our pods to the versions that support CocoaLumberjack 2.2.0
- Removed NSLogger-CocoaLumberjack-connector. Nothing was using it, and
the project is abandoned.
- Moved most of the dependencies to the WordPress target. This gets rid
of most of the duplication errors
Fixes #4371
=> Updates CocoaLumberjack to 2.2.0

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m, WordPress/WordPress.xcodeproj/project.pbxproj
This MediaPicker version update fixes the following bugs:
https://github.com/wordpress-mobile/MediaPicker-iOS/issues/85
https://github.com/wordpress-mobile/MediaPicker-iOS/issues/86
https://github.com/wordpress-mobile/MediaPicker-iOS/issues/73
https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/749 -> associated PR https://github.com/wordpress-mobile/MediaPicker-iOS/pull/91
and also improves the accessibility on the component:
https://github.com/wordpress-mobile/MediaPicker-iOS/pull/81
=> Media picker update version

WordPress/Classes/System/Constants.m, WordPress/Classes/ViewRelated/Settings/AboutViewController.swift
If we use the regular HTTP URL, the Twitter app will launch if
installed, and Safari will launch otherwise.
This way, the Twitter row is always available.
=> Don't use the custom Twitter URL

WordPress/Classes/Services/BlogSyncFacade.m, WordPress/Classes/Services/ReaderPostService.m, WordPress/Classes/Services/ReaderSiteService.m, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Pages/PageListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m, WordPress/Classes/ViewRelated/Post/PostListViewController.m, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderPostDetailViewController.m, WordPress/Classes/ViewRelated/Stats/StatsViewController.m, WordPress/Classes/ViewRelated/System/WPTabBarController.m
Changes in https://github.com/wordpress-mobile/WordPress-iOS/commit/0b7e2da6103874db4da49dda77f35321310db38a created multiple crash cases for when the `dotComID` method returns `nil`.
Testing for crash:
1. Open app
2. Hit Post button on TabBar (crash)
3. Dismiss TabBar (crash)
UPDATE:
Also additional crash issues of `nil` IDs in https://github.com/wordpress-mobile/WordPress-iOS/pull/4443
@alexcurylo please review the simple `nil` checks added here for protection against crashing.
@daniloercoli Please take a look at these changes and refactor for what should be tracked or passed when the `dotComID` returns `nil` instead.
=> Nil checks for preventing crash when using dotComIDs for Tracks.

WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
There where reported situations when doing media uploads to the server where the status bar saying "Media uploading..." was never dismissed when the media finished.
This was track down to the following scenarios:
Scenario 1:
- Start several media upload by selecting multiple images, 
- then canceled one of the uploads
- When the other uploads finished the status bar didn't get updated
Scenario 2:
- Select one media to upload
- Then add another media to upload while the first was still going
- When the media finished upload the status didn't get updated.
Scenario 3:
- Put yourself offline
- Start to upload 1 or two medias
- They should fail after a while but the status bar didn't updated.
This PR fixes this situation by removing some iOS 7 specific hacks and doing proper checks for …
=> Fix media upload tracking on editor

WordPress/Classes/Services/BlogService.h, WordPress/Classes/Services/BlogService.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/WordPressTest/WPAnalyticsTrackerMixpanelTests.m
The old code would only work for the pre-REST Jetpack sites connected to
the default account.
It now takes into account managed Jetpack sites, sites connected to a
different account, and sites that have Jetpack installed but not
configured in the app
Fixes #4480 
=> Fix Jetpack blog detection

WordPress/Classes/ViewRelated/System/WPTabBarController.m
In #4308 it was intended to start bumping the `WPAnalyticsStatReaderAccessed` stat whenever the Reader tab was accessed.  Prior to release/5.7 this stat was bumped whenever the post list was viewed for the first time, an imperfect approach that allowed for incorrect counts depending on user behavior.  The change introduced in #4308 incorrectly assumed that `showReaderTab` would be called in every case the reader tab would be accessed, however `showReaderTab` is not called when the user taps directly on a tab.  The change in this PR fixes the issue.
To test:
Scenario 1: Switching tabs
Set a break point on line 436.  
Launch the app and switch to the reader tab, to a different tab, then back to the reader. 
Confirm that the stat is bumped when tapping on the reader tab, but not other tabs. …
=> Reader: Fixes issue bumping the accessed state.

WordPress/Classes/Extensions/NSString+Helpers.swift, WordPress/Classes/Services/BlogService.m, WordPress/WordPressTest/NSStringHelpersTest.m
BlogSettings entity contains two Transformable fields: `Blacklist` + `Moderation`.
In this PR we update the parser: strings should get split using the `\n` character, instead of `space`.
Unit tests updated =)
Reference: #4397
=> BlogSettings: Updating Parser

Podfile, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/Utility/NotificationsManager.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Fix #4544 
- **PN Received on the device:** we can bump stats here – 100% accuracy, we have the noteID.
- **The user taped on a single entry in Notifications center:** we can bump stats here – 100% accuracy, we have the noteID.
Android Ref: https://github.com/wordpress-mobile/WordPress-Android/pull/3448
=> [Analytics] - Track push notifications 

WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
Refs #2076 
This PR fixes an issue where the site blavatar URL was being incorrectly composed. 
To Test:
- Load the post list without the patch and confirm that default avatars are only shown, even when the site *does* have a blavatar present at the top of the site detail. 
- Load the post list *with* this patch and confirm the post list correctly displays the blavatar in the cards. 
Needs review: @oguzkocer
=> PostList: Fixes issue loading blavatars/site icons.

WordPress/Classes/Extensions/PHAsset+Exporters.swift
`var` in pattern matching is being removed from Swift
https://github.com/apple/swift-evolution/blob/master/proposals/0003-remove-var-parameters-patterns.md
=> Fixes for Swift 2.2

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Addresses #4476
Using @aerych's suggestion: 
> Maybe don't show the search button when there is only a single blog.
=> If there is only one site (or less), then do not show the search button

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerWPCom.m, WordPress/Classes/Utility/WPUserAgent.h, WordPress/Classes/Utility/WPUserAgent.m, WordPress/Classes/Utility/WPWebViewController.m, WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderPostDetailViewController.m, WordPress/Classes/ViewRelated/Views/WPWebView.m, WordPress/WordPressApi/WordPressComApi.m, WordPress/WordPressTest/WPUserAgentTests.m
Here's my proposed WPUserAgent cleanup:
* A custom HTTP User-Agent header (the default UA with appended `wp-iphone/<version>` string) is set in app delegate and gets used in all UIWebViews indiscriminately.
* WPUserAgent stores cached versions of default and custom UAs in local variables and not in NSUserDefaults.
* Non-UIWebView code that wants to use the custom UA can call `wordPressUserAgent` to get the preferred client UA string.
* Added some more unit tests.
Fixes #4491.
=> Use custom User-Agent HTTP header in all UIWebViews

WordPress/Classes/ViewRelated/Themes/ThemeBrowserCell.swift, WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift, WordPress/Classes/ViewRelated/Themes/WPStyleGuide+Themes.swift
Closes #4564 
To help control Theme browser bandwidth, load screenshots at maximum displayed width on the current device in line with Android practice.
=> Control Theme browser bandwidth

Podfile, Podfile.lock
This fixes a warning in Xcode 7.2.
Thanks Aaron!
=> Updates Simperium to Mark 0.8.10

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Rather than force unwrap the `indexPathsForVisibleRows` optional, this pr uses a safer method.  This is an attempt at addressing a crash case with a somewhat unhelpful stack trace and description.
```
Thread : Crashed: Thread
0  WordPress                      0x10024bee8 ReaderStreamViewController.viewWillLayoutSubviews() -> () (ReaderStreamViewController.swift:182)
1  WordPress                      0x10024bf08 @objc ReaderStreamViewController.viewWillLayoutSubviews() -> () (ReaderStreamViewController.swift)
2  UIKit                          0x1895bb688 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 416
3  QuartzCore                     0x186fcab2c -[CALayer layoutSublayers] + 148
4  QuartzCore                     0x186fc5738 CA::Layer::layout_if_needed(CA::Transaction*) + 292
5 …
```
=> Reader: Safer optional unboxing for indexPathsForVisibleRows.

WordPress/Classes/Utility/FeatureFlag.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/FeatureFlagTest.swift
Instead of having a bunch of checks for `DEBUG` and `INTERNAL_BUILD` spread across the app, I suggest we keep them contained and actually check for enabled features.
This moves the checks from compile time to run time, so it might not be best for all scenarios:
- Constants that have different values for each build
- Static tables with row constants that depend on features, but we're moving those to ImmuTable progressively
- Code that we don't just want disabled but not linked (e.g. HockeySDK)
Despite all this, I think this approach is interesting so we can easily start using more feature flags. Ideally we'd start work on a new feature by flagging it and enabling only on Debug builds. This way, we can make smaller PRs and only release the feature when it's ready.
I've only added the …
=> Feature flags

WordPress/Classes/Models/AccountSettings.swift, WordPress/Classes/Models/ManagedAccountSettings+CoreDataProperties.swift, WordPress/Classes/Models/ManagedAccountSettings.swift
Use NSNumber for NSManagedObject attributes. The model type is Int64, and Int
seemed to work fine, I guess because I just tested on 64 bit simulators.
The iPad 2 crashed when visiting My Profile. Switching to NSNumber seems to fix
it.
Fixes #4604 
=> Fix crash on iPad 2

WordPress/Classes/ViewRelated/MeViewController.swift
I merged #4589 a bit too fast, and the section header title for the
WordPress.com account sign in/out looks out of place on the iPad.
While we find a global fix in #4591, I've skipped ImmuTableViewHandler and
implemented the data source and delegate methods on MeViewController, so I can
provide a WPTableViewSectionHeaderFooterView as the section header view.
=> Fixes section headers on Me

WordPress/Classes/ViewRelated/MeViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj
My Profile should only be visible on Debug/Internal builds, not on the App Store version.
I'm not too happy with repeating the whole ImmuTable tree for each check, but it seemed simpler and more readable than any of the alternatives, and should be gone in a few weeks when My Profile is finished.
=> Disable My Profile on App Store builds

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
In this PR we're splitting *NotificationDetailsViewController.viewDidLoad* method, just to keep things readable (long overdue minor touch).
Please, test opening few Notification Details, just for safety!.
=> Notification Details Refactor

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Fixes #4526 – Constraints on the site name header in BlogDetailsViewController are now updated whenever the trait collection changes, so that it's displayed correctly when multitasking (previously it only checked whether the device was an iPad or not).
To test: Please verify this in all multitasking configurations on iPad, and on iPhone when not multitasking to ensure nothing's broken – particularly the 6(s) Plus, as it uses regular size class in landscape.
=> Issues/4526: Fix BlogDetailsViewController site name position in multitasking

Podfile, Podfile.lock
Fixes #4624.
Details as to what was changed can be found in [this commit](https://github.com/wordpress-mobile/WordPress-Editor-iOS/commit/944a4228faa0e66b33268f2c883348604e497498).
Seems to be an obscure UIKit bug.
1. Launch the app on a real device.
2. Go to tab "Me"
3. Go into account settings
4. Make sure the visual editor is disabled.
5. Tap the "+" button in the middle of the toolbar to start writing a new post.
6. Give focus to the contents text field.
7. Tap on the add link toolbar item (on top of the keyboard).
8. Make sure the "insert link" view comes up and that the app doesn't crash.
=> Fixes obscure crash in the legacy editor.

WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m
Fixes #4475. I've disabled user interaction on the blog selector button in the navigation bar of the editor. 
1. Add a single self-hosted blog to the app. 
2. Tap the center tab button to open the editor. 
3. Attempt to tap the name of the blog at the top of the editor. You shouldn't be able to.
4. Also verify that with multiple blogs added, you _can_ tap the name of the blog to switch blog.
Needs review: @aerych - thank you!
=> Issue/4475: Disables blog selector button in editor when user only has a single site

Podfile.lock, WordPress/Classes/Services/AccountService.m, WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/InteractiveNotificationsHandler.swift, WordPress/Classes/Utility/NotificationsManager.h, WordPress/Classes/Utility/NotificationsManager.m, WordPress/Classes/Utility/PushNotificationsManager.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/InteractiveNotificationsHandlerTests.m, WordPress/WordPressTest/PushNotificationsManagerTests.m
In this PR we're moving over `Interactive Notifications` specific code over from *NotificationsManager* to *InteractiveNotificationsHandler* helper.
Plus: I've updated the documentation style of the new Notifications-Y handling classes.
Reference: #4069
1. Fresh install the app, and log into your WordPress.com account
2. Kill (or) close the app
3. Receive a comment in a blog that has comments auto-approval enabled
4. In the springboard, pull the notification to reveal its interactive actions
5. Tap over the *Reply* button
As a result, the app should launch, and the associated Notification should be onscreen (allowing the user to reply right there).
1. Fresh install the app, and log into your WordPress.com account
2. Kill (or) close the app
3. Receive a comment in a blog that has comments …
=> NotificationsManager: Revamp Mark II

WordPress/Classes/Services/OnePasswordFacade.h, WordPress/Classes/Services/OnePasswordFacade.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewModel.h, WordPress/Classes/ViewRelated/NUX/LoginViewModel.m, WordPress/WordPressTest/LoginViewModelTests.m
Implements #4634. The `OnePasswordFacade` now retrieves the current one-time password for the user's WordPress account, if available. The verification code field is _not_ displayed on the login screen unless there is an issue logging in – everything's just handled magically in the background for the user.
1. Ensure you have a WordPress.com account (with 2FA) set up in 1Password with username, password, and one-time password.
2. If you're already logged in to a wpcom account in the app, log out.
3. In Me, tap Connect to WordPress.com (or launch the app for the first time).
4. Tap the 1Password button. Choose 1Password from the popup.
5. Log into the 1Password extension and select your WP account.
6. Check that you're signed in correctly.
It's probably worth trying to catch your one-time …
=> Issue/4634: Retrieve 2FA code from 1Password if available

WordPress/WordPressTest/ContextManagerTests.swift, WordPress/WordPressTest/WordPressTest-Bridging-Header.h
We've found several unit tests breaking on different dev environments. After a brief debugging session, we've found out that the `TestContextManager`, for unknown reasons, might get retained more than expected.
When this happens, there may be side effects in other unit tests, that would impact the incorrect Core Data model.
In this PR we're forcing a `TestContextManager` cleanup, when needed. 
Thanks Eric!!
--
=> Fixing Unit Tests

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift
1. Launch WPiOS with Push Notifications disabled
2. Open `Me` tab
3. Open `Notification Settings`
4. Open any site and tap over `Push Notifications`
As a result, the user should be informed that Push Notifications are disabled, and a legend offering to `Go to iOS Settings` should show up.
Needs Review: @astralbodies  (Thanks!)
Closes #4627
=> Fix: Go to iPhone Settings should be iOS Settings 

WordPress/Classes/Utility/ImmuTable+WordPress.swift, WordPress/Classes/ViewRelated/MeViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj
In #4609 I implemented a quick workaround so we still used `WPTableViewSectionHeaderFooterView` in the refactored `MeViewController`.
This is a more generic solution until we can get rid of `WPTableViewSectionHeaderFooterView` completely (#4591).
=> Custom section header/footer for ImmuTable

Podfile, Podfile.lock
Closes #4631 
Updated stats to latest release which includes these fixes:
* Adds blog and post ID to stats analytics events
* Improve the graph on days/weeks/months/years to handle iPad multitasking better
* Fixes a glitch with date selection in graph going funky after viewing all or post details and coming back
* Re-enables tapping rows to see post details
Needs Review: @sendhil 
cc: @daniloercoli
=> Updating stats pod to 0.6.1

WordPress/Classes/ViewRelated/Blog/DiscussionSettingsViewController.swift
1. Launch WordPress
2. Open `My Sites` tab
3. Open any WordPress.com site
4. Tap over the `Settings` row
5. Tap over `Discussion` row
6. Tap over `Blacklist`
Try adding / editing a keyword. Note that the navigation title should read `New Blacklist Word` / `Edit Blacklist Word`.
Needs Review: @koke 
=> DiscussionSettingsViewController: Updates insertion and edition titles

WordPress/Classes/ViewRelated/Blog/DiscussionSettingsViewController.swift
2. Open `My Sites` tab
3. Open any WordPress.com site
4. Tap over the `Settings` row, and open the `Discussion` settings
5. Open the `Close Commenting` row
As a result, the table onscreen should have the following legend:
```
Automatically close comments on posts after a certain number of days.
```
Needs Review: @SergioEstevao (Thanks in advance Sergio!)
Props to @drw158 for reporting this!
=> DiscussionSettingsViewController: Updates setting footer text

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Fixes #4593 – Hides the filters in Notifications if we're displaying the "Connect to Jetpack" prompt, shows it otherwise.
1. Sign in with a self-hosted site that's not connected to Jetpack.
2. Visit Notifications and check that the filter bar is not visible.
3. Sign into a .com account and check that the filter bar is now visible.
4. Sign back out of .com (and sign back into a self-hosted non-Jetpack site) and check that the bar is hidden again.
Also verify that if you add a self-hosted site with Jetpack (but don't sign into .com) then the bar is hidden.
Thanks!
=> Hides the filters in Notifications if not connected to Jetpack.

WordPress/Classes/ViewRelated/Reader/CommentContentView.m, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m, WordPress/Classes/ViewRelated/Views/WPRichTextView.m
This is a short refactor to clean up some deprecated methods in the reader comments feature. 
To test on both iPhone and iPad:
- Launch the reader and view comments for a post with at least a half dozen comments. 
- Confirm that comments are correctly laid out. 
- Rotate the device and confirm that comments layout was updated for the new screen size. 
@SergioEstevao  Would you do the honors sir? 
=> Fixes some deprecation warnings in reader comments.

MIGRATIONS.md, WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/KeyringConnection.swift, WordPress/Classes/Models/PublicizeConnection.swift, WordPress/Classes/Models/PublicizeService.swift, WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion, WordPress/Classes/WordPress.xcdatamodeld/WordPress 44.xcdatamodel/contents, WordPress/WordPress.xcodeproj/project.pbxproj
Refs #4105 
The current [main branch for the sharing feature](https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/4105-sharing) has grown to be a bit unwieldy.  After some thought, some welcome feedback from @diegoreymendez and @jleandroperez, and @alexcurylo's blessing, I'm going to split this branch up into some smaller, more easily digestible PRs to merge into develop vs trying to wrangle a large feature branch.  The code is (mostly) already reviewed in #4407 and #4256, so these *should* be relatively straight forward reviews. 
This is the first PR and adds the data model for the Sharing feature.  Original commit was edac8b8. 
@jleandroperez Would you be game for the re-review? 
=> Sharing: Adds the data model. Adds model revision 44.

WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/Classes/ViewRelated/MeViewController.swift, WordPress/Classes/ViewRelated/NUX/LoginViewController.m
Fixes #3649. The login screen's layout was incorrect after rotating the device, viewing the support screen (which supports rotation) and dismissing it. See To Test for full details.
The login screen was also incorrectly rotating on iPhone when it shouldn't. I've made use of `RotationAwareNavigationViewController` to pass through the relevant rotation method. Login should now never rotate on iPhone!
### To Test
1. While signed out of the app and viewing the sign-in screen, rotate to landscape orientation. The Sign-in screen requires portrait orientation and should not rotate.
2. Tap the info (?) icon to view the support screen.
3. Rotate to Portrait orientation.
4. Dismiss the support screen. The sign-in screen's layout should not have changed.
Please also check the following:
- Check the …
=> Issue/3649: Broken login layout on rotation

WordPress/Classes/ViewRelated/NUX/LoginViewModel.m, WordPress/WordPressTest/LoginViewModelTests.m
Fixes #4287 
Waits to dismiss the login UI until all of the sync operations have completed. This fixes an issue with BlogListController firing off too early in the login process. The default blog hadn't been stored yet which made setting the Today Extension stats site up impossible.
**Testing:**
1. Fresh install
2. Log in with a WordPress.com account.
3. Verify Today Widget is configured.
Needs Review: @jleandroperez, @sendhil
=> Ensures blogs are synced to the device before dismissing the login UI

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Fixes #4647. On first launch, BlogListViewController's add search (+) button would be hidden, and never re-appear until you relaunched the app.
This was due to the updateSearchButton method nilling out rightBarButtonItems when it initially detected a blog count of zero (before the user has logged in). Despite the method being called on viewWillAppear:, it would never re-add the button on subsequent calls when more than one blog is present.
I think there was also another bug in this code – I'm presuming that the updateSearchButton method should've been hiding the search button, not the add site button. I've updated it to do so, and also to add the button back in if there are > 1 blogs.
=> Issue/4647: Add Site button now shows correctly on initial launch

WordPress/Classes/System/Constants.h, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
The forthcoming sharing feature will be enabled/disabled via a feature flag and accessible from the Blog Details screen.
This change makes it a bit easier (and saner) to present cells conditionally, and avoids some complicated `const` wrangling.
The approach is similar to what was done in ImmuTable and should be considered as a stopgap/stepping stone til `ImmuTable` is usable in ObjC classes, or when `BlogDetailsViewController` is refactored to Swift.
To test: 
Test each cell and confirm that the correct content is opened.  Do this for a wpcom and self-hosted site. Note that the People feature is currently crashing for self-hosted sites but is only available in dev builds. 
=> Blog Details: Quick refactor making it easier to change table content.

WordPress/Classes/ViewRelated/Pages/RestorePageTableViewCell.xib, WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.xib, WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.m
Fixes #4184. Increases horizontal padding inside Undo button for deleting posts and pages (`RestorePostTableViewCell` and `RestorePageTableViewCell`). I also noticed that with long localizations (e.g. Dutch) the button and the info text in the cell would overlap, so I've added some extra constraints to handle this.
Before:
After:
1. Launch the app in a language other than English (original issue was raised against Spanish).
2. Delete a page, and observe the spacing between the undo arrow and the label of the undo button.
3. Repeat for deleting a post.
Also verify with languages with long translations (Dutch is one that I used) to ensure that text does not overlap as per screenshots above.
=> Issue/4184: Increases Undo button padding

WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m
Fixes #4665 
Corrects a problem with layout being called at the wrong point in the view controller lifecycle. This fixes a glitch with the UI jumping upwards after a remote request has completed.
The ultimate solution is to replace the UI with something with autolayout and not all manual layout code. This would resolve #1914 as well.
**Testing:**
1. Start with a fresh app install.
2. Add self-hosted site that does not have Jetpack installed.
3. Attempt to view settings.
4. View (you should install Jetpack notice) should not jump after a couple seconds.
Also -
1. Start with a fresh app install.
2. Add self-hosted site that has Jetpack installed (and connected).
3. Attempt to view settings.
4. View (log into your Jetpack) should not jump after a couple seconds.
=> Move the awful layout code into the right lifecycle method

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
The only icon that needed to be replaced on the My Sites screen is the Add icon, which is currently using the system standard add icon. This swaps it out in favor of the Add gridicon.
=> Use our custom add icon for the addSitebutton.

WordPress/Classes/Utility/ImmuTable.swift, WordPress/Classes/ViewRelated/Cells/WPImmuTableCells.swift, WordPress/Classes/ViewRelated/MeViewController.swift, WordPress/WordPressTest/ImmuTableTest.swift
It just looks better and there's no point in having the `Type` suffix
=> Rename ImmuTableActionType to ImmuTableAction

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift
In this PR we'll update the style of the Notification Settings's NavBar Title.
@frosty may i bother you with a review?
Closes #4390
2. Open the `Me` tab, and tap over `Notification Settings`
3. Open any of your sites
4. Tap over any (all) of the available Notification Streams
Verify that the site title (in the actual stream settings view, also known as "the last one") displays the Site Title as the tableView header of the first section.
--
--
=> Notification Settings: Site Title is now a TableView Header

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Fixes #4595 – The sites list now listens out for `WPAccountDefaultWordPressComAccountChangedNotification` and ends editing if a notification comes in. I also moved some other notifications code to be grouped under the existing 'Notifications' `pragma mark`.
**To Test** 
1. Sign in to to a self-hosted site not connected to Jetpack.
2. Sign in to a wpcom account.
3. Go to the My Sites tab, and tap the Edit button at the top of the site list to display the site picker.
4. Switch to the Me tab and sign out of wpcom. This should leave just the self-hosted blog still in the app.
5. Switch back to the My Sites tab. The list should no longer be in edit mode (so the remaining site is visible). As there's only one site there now, the user will be automatically taken to its details.
6. Also try …
=> Issue/4595: End editing in site list when signing out of .com account

WordPress/Classes/Models/Blog.m, WordPress/Classes/Networking/BlogServiceRemoteREST.m, WordPress/Classes/System/WordPress-Bridging-Header.h
We were using the wrong import type in a few places, and it becomes a build
error in Xcode 7.3-beta
=> Fixed imports for Xcode 7.3

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Reproduced the same kind name/properties as "editor_photo_added"
s/editor_added_video_via_local_library/editor_added_video/
Match wpandroid: https://github.com/wordpress-mobile/WordPress-Android/blob/2e98b5a36c64caa7a42066d6c1dcecf7a0eb4937/libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java#L155-L162
=> Rename editor_video_added Tracks event and add a "via" property.

WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Closes #4650 
This is another one I haven't been able to reproduce.  However, the stack trace shows a nil value was assigned to an array in this method which pretty much identifies the problem. 
Its unclear under what circumstances the `NSIndexPath` returned from the results controller would be `nil` but adding a nil check should prevent the crash. 
=> Reader: Adds nil check before reloading row for updated attachments.

WordPress/Classes/Services/MediaService.m, WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
Closes #4663.
This is a replacement for #4681.  Props @koke for the suggestion
=> Media: Use jpg instead of jpeg for uploaded image extension

WordPress/Classes/ViewRelated/Blog/DiscussionSettingsViewController.swift
1. Make sure that "Comment author must fill out name and e-mail" is checked.
2. Open the site settings in the mobile app.
3. Open the site settings in calypso.
4. Go back one level in the mobile app, without changing anything.
5. Uncheck "Comment author must fill out name and e-mail" in Calypso and save the settings.
6. Open the site settings in the mobile app again.
As a result, "Comment author must fill (...)" should reflect the last Calypso-saved state.
Closes #4615
Needs Review: @aerych  
=> Refreshing Discussion Settings

WordPress/WordPress.xcodeproj/project.pbxproj
Previous PR added and then removed a CoreData model version 46. https://github.com/wordpress-mobile/WordPress-iOS/pull/4715
This PR removes a leftover reference in the project file to model 46.
Please review @alexcurylo
=> Removes reference to deleted CD model version 46.

WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift, WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.xib
In this PR we perform a minor cleanup over the CommentsTableViewCell height calculation code.
- Preferred Max Width is now automattic
- Layout subviews code is gone
- No need to implement `sizeThatFits`, since this cell already uses autolayout. We can use it's magic!
2. Open `My Sites` tab and access any of your blogs
3. Tap over `Comments`
As a result, the comment cells should show up onscreen, without any UI modifications (nor glitches!).
Closes #4159
=> Comments Cell Cleanup

WordPress/Classes/ViewRelated/Comments/CommentViewController.m
1. Launch WPiOS on an iPad Device
2. Open `My Sites` > `(Any) Site`
3. Tap over Comments
4. Tap over any comment
As a result, the Comment Details should be onscreen. Note that the Header's right chevron accessor shouldn't have any (Weird) padding.
Closes #4726
=> CommentViewController: Disabling readable width

WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift
2. Open `My Sites` > `(Any site)` > `Comments`
3. Tap over any comment
4. Toggle the Approval / Unapproval state
5. Hit back
As a result, the comment cell might end up rendering the Comment Details beyond the visible area ([Sample Video Here](https://cloudup.com/c4X1irKRDdt)).
In this PR we're forcing a layout pass, whenever the Cell's Details Text is updated.
Needs Review: @aerych (Last PR of the week, promise Eric!)
Thank you sir!
=> CommentsTableViewCell: Forcing layout on details refresh

WordPress/Classes/Networking/BlogServiceRemoteXMLRPC.m
Closes #4472 
Decodes entities in the title and tagline
Needs Review: @koke 
Before:
After:
=> My Sites: Decodes entities in title and tagline when syncing via XMLRPC

WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
While trying to reproduce #4594 I ran into a different crash because I was testing with a self hosted without Jetpack, and `restApi` was `nil`. 
I believe this also fixes #4594 since I can't reproduce that crash on any site.
=> Only show People on blogs that support REST

WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Closes #4711
Suppresses navigation bar 'Activate' button for inactive as well as active theme Customizer invocations.
To test: 
Bring up Theme browser. Select 'Try & Customize' for an inactive theme. Observe that the Customizer's 'Save & Activate' button is visible and the navigation bar 'Activate' button is not.
=> Suppress 'Activate' button in Theme preview

WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift, WordPress/Classes/ViewRelated/Reader/SubscribedTopicsViewController.m
Closes #4743 
The reader has only partial support for lists.  You can view them if you're already subscribed, but you can not yet create them, follow them, or unfollow them from the app.  This functionality is intended to be implemented as a part of #4094.  For now, and for consistency with the post list behavior, lets remove the unfollow option from the menu for lists. 
To test:
- Be subscribed to a list. If you're not already subscribed, you can create one via the option in the web reader's sidebar. 
- In the app, open the reader's menu. 
- Tap the edit button. 
- Confirm that the "unfollow" button does not appear for the lists you're following, only for the tags you're following. 
Needs review: @kurzee would you do the honors?
=> Reader: Lists should not be unfollowable from the menu.

WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/ViewRelated/Blog/SiteManagement/DeleteSiteViewController.swift, WordPress/Classes/ViewRelated/Blog/SiteManagement/StartOverViewController.swift, WordPress/Classes/ViewRelated/Blog/SiteManagement/TableViewHeaderDetailView.swift, WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
Adds the UI for our first pass at WordPress.com site management features as listed in #4570.
To Test:
- Check that Blog > Settings now has an 'Advanced' section with 'Start Over' and 'Delete Site' items for WordPress.com blogs that user has admin access to
- Check that section is not there for non-WordPress.com blogs or non-administered blogs
- Check that Start Over controller opens a Helpshift session if enabled, and goes to browser support otherwise (similar to behaviour of Me > Support)
- Check that Delete Site controller correctly displays blog's primary domain and requires exact match to enable deletion 
- Verify that a deleted site is in fact deleted
Please Review: @kurzee
=> Site Management UI

WordPress/Classes/Networking/Remote Objects/RemoteTaxonomyPaging.h, WordPress/Classes/Networking/Remote Objects/RemoteTaxonomyPaging.m, WordPress/Classes/Networking/TaxonomyServiceRemote.h, WordPress/Classes/Networking/TaxonomyServiceRemoteREST.m, WordPress/Classes/Networking/TaxonomyServiceRemoteXMLRPC.m, WordPress/Classes/Services/PostCategoryService.h, WordPress/Classes/Services/PostCategoryService.m, WordPress/Classes/Services/PostTagService.h, WordPress/Classes/Services/PostTagService.m, WordPress/WordPress.xcodeproj/project.pbxproj
This is required implementation for work on Menus management and also for the upcoming work on Categories and Tags management. There is more work to be done between categories and tags across the whole app, but will await a larger refactor with many more dependencies observed.
1. Refactors `TaxonomyServiceRemote` for paging and searching taxonomy results via REST and XML-RPC.
2. Refactors `PostTagService` for supporting search and paging via remotes.
3. This also resolves an issue seen in XML-RPC connections in which a category created via the app with a parent category was not setting the parent correctly according to the XML-RPC.
**Note on `PostCategoryService`**: I did not include the methods on `PostCategoryService` for supporting paging or search. Upon testing I noticed it will …
=> Taxonomy paging and search for Categories and Tags.

Podfile, Podfile.lock
Update media picker to version 0.8.0:
This version of the media picker fixes the following issues:
- remove all deprecated classes that used the AssetLibrary
- remove all user of alert view and popover controllers classes
- update the rotation to be platform independent with no more checks for iPad
=> Update media picker to version 0.8.1

MIGRATIONS.md, WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/Plan.swift, WordPress/Classes/Networking/AccountServiceRemoteREST.m, WordPress/Classes/Networking/Remote Objects/RemoteBlog.h, WordPress/Classes/Services/BlogService.m, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/WordPress.xcdatamodeld/WordPress 45.xcdatamodel/contents
Displays a blog's current Plan on its row in `BlogDetailViewController`.
**Note:** To display the detail value on the row, I had to change `BlogDetailViewController` to register the `Value1` cell type instead of the standard `WPTableViewCell`. This had the side effect of displaying the number of pending comments on the Comments row, which appears to have not been working since  219812a1 when it was changed _from_ `Value1`. I've disabled the line that adds the number of comments to the cell, and I'm opening another issue to flag it for review / removal.
* Select various blogs with different types of plan from the blog list and ensure you can see their correct plan in the blog detail screen. 
* Jetpack sites should currently display no value.
Part of #4744
=> Plans: Display user's current plan

WordPress/WordPress.xcodeproj/project.pbxproj
Cocoapods was complaining about `OTHER_SWIFT_FLAGS` being overriden, which we
did since #4608. Add `$(inherited)` to the setting so it picks up the
per-project setting (adds `-D COCOAPODS`).
=> Inherit swift flags

WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift, WordPress/Classes/ViewRelated/Themes/ThemeWebViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Closes #4679
Patches navigation to theme customization pages so that the close button is never visible to the user.
To test:
1. Open Sites > site > Themes browser
2. Tap 'Details' in the 'Current Theme' header
3. Scroll down to 'Customize' and tap.
4. Ensure that there is no 'X' in upper left as described in #4679.
5. Return to browser and tap 'Customize' for 'Current Theme' and 'Try & Customize' for non-current themes to ensure links with "hide_close" already set function as expected.
@kwonye: Please review functionality and conformance with Android behaviour.
=> Hide close in Theme Customizer

WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Closes #4639 
Resuming a search on web controller dismissal now adapts properly to changed bounds and size class of view whilst the browser was hidden.
To test: 
1. Open Sites > site > Themes browser
2. Activate Search and enter a search string.
3. Tap a result to display its preview.
4. Rotate device 90°.
5. Dismiss preview and ensure reveal smoothly animates back to a browser with grid cell size adapted to content width.
@kurzee: Could you check everything you reported in #4639 is fixed please?
=> Theme Search Layout

WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
Resolves the conversation and issues raised in https://github.com/wordpress-mobile/WordPress-iOS/issues/4756, https://github.com/wordpress-mobile/WordPress-iOS/pull/4757 and https://github.com/wordpress-mobile/WordPress-iOS/pull/4766.
After much thought and conversation with @aerych. The best approach moving forward allows for both admin and non-admin users of XML-RPC sites to toggle default post options under a new section in settings titled "This Device".
This PR also moves "Geotagging" under "This Device" for all users, XML-RPC and REST.
REST users only have default post options available if they are admins of the connected site and under the section "Writing". Non-admins will instead default to what the admin has selected for the site. (This is in parity with Calypso on the web)
REST …
=> Reorganizes post options in Settings.

WordPress/Classes/ViewRelated/Tools/SettingsPickerViewController.swift
1. Launch WPiOS and open `My Sites` tab
2. Open any WordPress.com site
3. Tap over the `Settings` row
4. Scroll all the way down, and tap over `Discussion`
5. Tap over `Close Commenting`
6. Rotate the device into landscape mode
7. Make sure the Days Picker is onscreen
8 .Select any of the picker's rows
As a result, once the user lifts the finger the screen should *not* flicker, and the row right above the picker should show the new selected value.
Closes #4695 
Needs Review: @SergioEstevao  
Thanks in advance Sergio!
P.s.: Props to @astralbodies for spotting the bug on this one. Thanks Aaron!
=> SettingsPickerViewController: Preventing flicker on selection

WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
Closes #4768
This is a bug fix for #4768. To fix the odd settings state I've borrowed the the BlogDetails vc the same approach it uses and added an observer to model changes. It feels a bit heavy handed but doesn't seem to have any negative visual side effects, and it is more reliable than listening for the default wpcom account change notification.
To test:
- Repeat the steps described in the issue and confirm the blog settings screen always shows options consistent with the type of blog being shown. 
=> Blog Settings: Updates sections when model changes.

Podfile, Podfile.lock, WordPress/Classes/System/WordPressAppDelegate.m
As per request, let's reduce the Simperium noise in WPiOS Logs, since the integration is already stable.
Needs Review: @SergioEstevao 
=> Disables Simperium verbose logs

WordPress/Classes/Utility/ImmuTableViewController.swift, WordPress/Classes/ViewRelated/AccountSettingsViewController.swift, WordPress/Classes/ViewRelated/Me/MyProfileViewController.swift, WordPress/Classes/ViewRelated/SettingsCommon.swift
The main goal is to remove `visible` from `ImmuTablePresenter`, since it
doesn't really belong there. Presenter is a thing that can "present" view
controllers: usually a UIViewController, but implemented as a protocol so it's
testable.
But then I realized, the Controller doesn't really need a reference to
Presenter, or the parent View Controller. The only thing that needs that is
ImmuTable (for the callbacks), and we can pass the presenter when requesting
the table view model (renamed). This is similar to the previous solution, but
avoids the chicken-and-egg problem when initiailizing. And because of this, it
removes 4 assertions/preconditions that are now guaranteed at compile time.
The `visible` observable is still exposed on ImmuTableViewController, but
the VC is the one pausing the …
=> Refactor ImmuTablePresenter/Controller/VC

WordPress/WordPressTest/WPAvatarSourceTest.m
`testGravatarCaches` was failing intermittently, and seemingly only when run in combination with other tests.
This could be due to multiple tests using the same shared instance of `WPAvatarSource`.
This PR changes the tests to create a new instance each time. 
I had more success recreating the issue by running with a clean simulator instance.
=> WPAvatarSourceTest: Don't use a shared WPAvatarSource

WordPress/Classes/Utility/Ratings/AppRatingUtility.h, WordPress/Classes/Utility/Ratings/AppRatingUtility.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Our App Ratings prompt is currently broken. I don't know what happened but I think recently Apple changed things and the link that we used to use to pull up the App Review page from within the app no longer works. This PR updates the link to work correctly.
**To Test**
1. Start with a clean version of WPiOS
2. Login
3. Go to the Notifications Page
4. Open 5 notifications
5. Once the prompt appears tap "I Like It" -> "Leave a Review". At this point the App Store review page should display.
Needs Review:@astralbodies
=> Fixing broken link to app store review

MIGRATIONS.md, WordPress/Classes/Models/BlogSettings.swift, WordPress/Classes/Networking/BlogServiceRemoteREST.m, WordPress/Classes/Networking/Remote Objects/RemoteBlogSettings.swift, WordPress/Classes/Services/BlogService.m, WordPress/Classes/WordPress.xcdatamodeld/WordPress 46.xcdatamodel/contents, WordPress/WordPressTest/BlogServiceRemoteRESTTests.m, WordPress/WordPressTest/Test Data/rest-site-settings.json
In this PR we'll add a new field, `languageID`, to the `BlogSettings` entity. Changes in the Service Layer + Persistance layer are included right here.
Please, verify that the Unit Tests pass, and check the Data Model 46 changes. I'm reusing Mark 46 since it's not been sent, yet, to our beta testers.
Reference: #3558
=> Site Settings: Language service layer

WordPress/Classes/Utility/ContextManager.h, WordPress/Classes/Utility/ContextManager.m, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Closes #4263 
Moves the child context creation out of `ReaderStreamViewController` and into a new method in `ContextManager`.
=> Reader: Extracts child context creation to ContextManager

WordPress/Classes/Services/BlogService.m, WordPress/Classes/Services/BlogSyncFacade.m, WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/WordPressTest/System/3DTouch/WP3DTouchShortcutCreatorTests.swift
3D Touch creator now checks for the availability of 3D Touch before attempting to make shortcuts. Also handles possible cases where there is no blog or the settings cannot be found.
=> Safety checks for 3D Touch shortcuts

WordPress/Classes/ViewRelated/Cells/WPImmuTableCells.swift, WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift
Before, VoiceOver would read all the features without saying if they were
included in the plan or not.
With this change, it will add either "Included", "Included in web version", or
"Not included" after reading the feature name. For features with a description
(support and storage), it will still read the name and description.
It adds some refactoring so the accessoryView and spoken text follow the same
logic.
Demo: https://www.youtube.com/watch?v=CjiDAyew4WE
Fixes #4800 
=> Improve accessibility of plan details.

WordPress/Classes/Models/WPAccount.h, WordPress/Classes/Models/WPAccount.m, WordPress/Classes/Services/ThemeService.h, WordPress/Classes/Services/ThemeService.m, WordPress/WordPressTest/ThemeServiceTests.m
Every account is now a WordPress.com account, so that method doesn't make sense
anymore.
=> Remove WPAccount isWPComAccount

Podfile, Podfile.lock
This introduces a bunch of deprecation warnings we'll need to address(https://developers.helpshift.com/ios/upgrade-4x/#api-changes) but as we have them currently suppressed we can defer dealing with it given this is a hot fix.
Note - in develop Helpshift doesn't appear by default and in order to get it to appear you'll have to modify this line - https://github.com/wordpress-mobile/WordPress-iOS/blob/1445e067b2f62984940f260a9f8dbfed81b73e83/WordPress/Classes/Utility/HelpshiftUtils.m#L74.
cc @kwonye
=> Updating Helpshift to 5.3.0.

WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift, WordPress/WordPressTest/PlanDetailViewControllerTest.swift
The main goal of this PR was to remove the UIKit dependency on the plan detail tests: instead of having to create a cell, configure it, and test it, we expose all the logic through accessors on `FeatureListItemRow` and test those.
While doing this, I had a couple test failures that I wasn't sure how to solve, because there were some states of `FeatureListItemRow` that just didn't make sense: what happens if a feature is not available and it has a description?
I think features with description are a special case, and now are being handled with a `TextRow`.
`FeatureListItemRow` is still initialized with a `PlanFeature` for convenience, but internally it stores `(title, webOnly, available)` so it's easier to reason about the possible combinations.
Fixes #4801 
=> Refactor Plan detail tests

WordPress/Classes/Extensions/Math.swift, WordPress/Classes/Extensions/PHAsset+Exporters.swift, WordPress/Classes/Services/MediaService.h, WordPress/Classes/Services/MediaService.m, WordPress/Classes/Services/MediaSettings.swift, WordPress/Classes/System/AppSettings.swift, WordPress/Classes/ViewRelated/Cells/WPImmuTableCells.swift, WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/Extensions/MathTest.swift, WordPress/WordPressTest/MediaSettingsTests.swift
Removes the max image size setting logic from `MediaService` and moves it to a new class.
I also cleaned it up a bit, and now we just deal with a single `Int` value instead of a `CGSize`.
Also modified the logic for "Original" resize: instead of having `0` or `CGSizeZero` as a mark for "Original", I use `Int.max` now. Then the code to check that is more generic and just checks if the desired target size is bigger than the image size, an uses the original size in that case.
Refs #4797 
cc @astralbodies 
=> Extract media settings to a separate class, add unit tests

WordPress/Classes/Networking/ReaderPostServiceRemote.m
Addresses an odd crash seen while composing a remote reader post.  Sample stack trace:
```
Fatal Exception: NSInvalidArgumentException
-[__NSCFBoolean stringForKey:]: unrecognized selector sent to instance 0x19fe800b0
Thread : Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x181c15900 __exceptionPreprocess
1  libobjc.A.dylib                0x181283f80 objc_exception_throw
2  CoreFoundation                 0x181c1c61c __methodDescriptionForSelector
3  CoreFoundation                 0x181c195b8 ___forwarding___
4  CoreFoundation                 0x181b1d68c _CF_forwarding_prep_0
5  WordPress                      0x100071aac -[ReaderPostServiceRemote crossPostMetaFromPostDictionary:] (ReaderPostServiceRemote.m:276)
6  WordPress                      0x1000716fc …
```
=> Reader: Ensure object is a dictionary before continuing.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m
In this PR we're nuking Comment Destructive Operation confirmation Alerts, since we're already offering the user to *Undo* such OP's.
Closes #48262
Aaron, may i bother you with a violent review?. Thanks in advance!
--
1. Receive a Comment Notification
2. Tap over `Notifications`, and open the new notification details
3. Spam the comment
As a result, the app shouldn't ask for Spam confirmation.
1. Receive a Comment Notification
2. Tap over `Notifications`, and open the new notification details
3. Spam the comment
As a result, the app shouldn't ask for Trash confirmation.
=> NotificationDetailsViewController: Nuking deletion / spam confirmation

WordPress/Classes/ViewRelated/Plans/PlanComparisonViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift, WordPress/Classes/ViewRelated/Plans/Plans.storyboard, WordPress/WordPress.xcodeproj/project.pbxproj
Implements #4799, adding a comparison view for plans.
- No state restoration – we'll revisit that after this has been merged.
- The current active plan isn't highlighted, as that requires quite a visual change from the current plan detail screens. Will raise a separate issue to track that.
=> Adds Plan Comparison view

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/751).
- Open a post, can be either a new one, or an existing one.
- Delete the title and content, make sure they're empty.
- Change the post's publication date or anything else in the post's settings screen.
- Exit the editor without saving.
- The editor should roll the changes back, and the post should be gone if it was a new one.
=> Posts without content can no longer be saved.

WordPress/Classes/ViewRelated/Blog/SiteManagement/DeleteSiteViewController.swift
Closes #4836
Updates the Delete Site confirmation alert to match latest Calypso wording.
To test: Check that Settings > Delete Site confirmation alert matches Calypso alert wording.
Could you take a quick look @kurzee please?
=> Update delete site confirmation to match latest Calypso prompt.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
In this PR we'll fix an overlap between the Notification Filters and the Empty State Label, whenever the App ratings utility is displayed.
@kurzee may i bother you with a review?
Thanks in advance Brent!
Fixes #4536
1. Hack [this helper](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/Ratings/AppRatingUtility.m#L281) so that it always returns YES.
2. Log into an account that has no notifications (DM me, got a bunch of testing accounts!)
3. Tap over the Notifications tab
Notice that the Empty State legend won't be overlapping with the filters anymore. After receiving a new notification, the filters should show up automatically.
=> Notifications: Fixing Empty State Overlap

WordPress/Classes/ViewRelated/Post/Categories/PostCategoriesViewController.m, WordPress/Classes/ViewRelated/Post/Categories/WPAddPostCategoryViewController.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/27).
1. Launch WPiOS.
2. Create a new blank post.
3. Go to Post Settings (gear icon in top-right corner) -> Categories.
4. Add a new category.
5. No need to input the name, just select a parent category.
6. In the parent category selection screen make sure that there's an option to select "No Category".
7. Also make sure that, after selecting a parent category, opening the parent-category-selection screen places the checkmark in the correct item.
/cc @jleandroperez for review.
=> Editor #27: setting parent category works much better now.

WordPress/Classes/Networking/PostServiceRemote.h, WordPress/Classes/Networking/PostServiceRemoteOptions.h, WordPress/Classes/Networking/PostServiceRemoteREST.m, WordPress/Classes/Networking/PostServiceRemoteXMLRPC.m, WordPress/Classes/Services/PostService.h, WordPress/Classes/Services/PostService.m, WordPress/Classes/Services/PostServiceOptions.h, WordPress/Classes/Services/PostServiceOptions.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewControllerSubclass.h, WordPress/Classes/ViewRelated/Post/PostListFilter.h, WordPress/Classes/ViewRelated/Post/PostListFilter.m, WordPress/Classes/ViewRelated/Post/PostListViewController.m, WordPress/Classes/ViewRelated/Post/Posts.storyboard, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/PostServiceRemoteRESTTests.m
Originally, the `PostService` implementation did a couple things in which it managed paging of posts itself. In some sense, this just about attempted to manage its own state by paging requests based on whatever oldest post happened to be in CoreData, and also with purging any posts that weren't a part of a sync or paging request.
The above was an issue while implementing a new endpoint within `PostService` for searching posts. Searching posts created an issue because resulting posts would break the assumed paging of `PostService` implementation.
The primary refactor of this PR is within `PostService` and separating the use of sync and paging parameters instead on users of `PostService` via a new object parameter class `PostServiceOptions`. 
The secondary refactor is within …
=> PostService and AbstractPostListViewController Refactor

WordPress/Classes/Utility/Sharing/WordPressActivity.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.h, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m, WordPress/Classes/ViewRelated/Post/PostListViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.h, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/769).
Basically when a post is created or edited in the new editor, and saved, the parent list makes sure that the post is visible by changing the filtering as necessary (ie: published, draft, pending, etc).
**Test 1:**
2. Open the list of posts for a blog
3. Set the filtering to "Published"
4. Create a new post
5. Set it to save as "Draft" in the optinons
6. Save the draft
7. The parent VC's filtering should be changed to "Drafts".
Variations of this test can be performed by changing the status.
**Test 2:**
2. Open the list of posts for a blog
3. Set the filtering to "Published"
4. Edit an existing post
5. Change it to "Draft" in the optinons
6. Save the draft
7. The …
=> Newly created posts can now switch the parent VC's filter to be shown.

WordPress/Classes/ViewRelated/AccountSettingsViewController.swift, WordPress/Classes/ViewRelated/Me/MyProfileViewController.swift, WordPress/Classes/ViewRelated/MeViewController.swift, WordPress/Classes/ViewRelated/SettingsCommon.swift
I've removed most of the shared logic in SettingsCommon and only left the
ImmuTable action helpers there. My Profile doesn't make sense without a
service, while Account Settings still can display the app settings witout one.
The table view model and error logic is still similar for both, but not the
same, so each controller implements its own variant.
I also now pass the service to the action helpers explicitly to avoid having to
deal with optionals: the rows with actions that require a service won't be
displayed if there's no service.
Fixes #4842 
Cc: @astralbodies 
=> Fix crash on Account Settings for self hosted

WordPress/WordPressTest/NotificationTests.m
In this PR we'll explicitly cleanup the ContextManager Override. The Override is, apparently, getting retained more than expected, which might have weird side effects.
P.s.: Same kind of bug / fix already applied to `ContextManagerTests`.
May i bother you with a quick review / test @koke?
Fixes #4848
=> NotificationTests: Explicitly cleaning up ContextManager Override

WordPress/Classes/Models/Notifications/Notification.h, WordPress/Classes/Models/Notifications/Notification.m, WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Internal.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+RowActions.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m, WordPress/Classes/ViewRelated/Notifications/Helpers/Notifications+Definitions.h, WordPress/WordPress.xcodeproj/project.pbxproj
In this PR we'll enhance the Notifications List, so that the user may swipe over any comment cell, and Approve / Unapprove / Trash any comments, right there.
The new set of UITableViewDelegate methods have been implemented in a Swift category. Main reason is: we'll gradually migrate the Notifications Stack over to Swift.
Note: I've noticed we've got code that looks alike in several spots (NotificationsViewController / NotificationDetailsViewController). Looks like a great candidate for `The Fourth Layer`, will dig into that!.
Closes #4825
--
1. Receive a Comment-Y Notification
2. Launch the app and open the Notifications tab
3. Swipe over the cell
4. Tap over Approve / Unapprove
Verify that the web properly reflects the new state.
1. …
=> Notifications: Swipe actions

WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
This PR makes the Set Featured Image show in a modal like the Set Location option.
This was discussed here: https://github.com/wordpress-mobile/WordPress-iOS/issues/4808
=> Make feature imaged selection a modal instead of a push.

WordPress/Classes/Utility/Sharing/WPActivityDefaults.m
If there are no visible blogs in the app, don't show the WordPress option in
the share sheet. Otherwise we'll crash.
Fixes #4856
=> Don't "Share to WordPress" with no blogs

WordPress/Classes/System/WordPressAppDelegate.m
The previous app delegate method was deprecated in iOS9:
`- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(nullable NSString *)sourceApplication annotation:(id)annotation`
Updating to the current method to use when URLs are thrown into the app:
`- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options`
Please review, @astralbodies
=> Updates a deprecated openURL method to the latest iOS9 method.

WordPress/Classes/ViewRelated/Settings/ActivityLogViewController.m
That was an easy one.
The tricky question: should I search and replace in the strings file, so we reuse the existing translations? I'd guess many of them won't have this issue.
Fixes #1640
=> Improve description of activity logs

WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
Hiding the button has a weird side effect where it would hide after pushing a
new view controller, and you'd be stuck.
Since the modal "Authenticating..." is shown while validating the credentials,
and you can't tap Back anyway, there's no need to hide the button.
Fixes #4885 
=> Don't hide the back buton when saving password

WordPress/Classes/Utility/FeatureFlag.swift, WordPress/Classes/ViewRelated/AccountSettingsViewController.swift, WordPress/Classes/ViewRelated/MeViewController.swift
Since we still don't have  a clear solution for #4888, let's disable My Profile and the new fields in Account Settings in 6.0, and keep working on a solution for 6.1.
The easiest way to test is to change `build(.Debug)` to `false` in `FeatureFlag`. My Profile should be gone from Me, and Account Settings should only show the media size and visual editor options.
cc @diegoreymendez @sendhil @rachelmcr 
=> Disable My Profile and new Account Settings for 6.0

.travis.yml
Travis has been erroring a lot lately with simulator timeouts. I've read that just upgrading to 7.2 might fix it, so let's try.
=> Switch to Xcode 7.2.1 for travis

WordPress/Classes/Networking/MediaServiceRemoteREST.m
Fix crash on Media parsing detected on Crashlytics.
https://fabric.io/automattic/ios/apps/org.wordpress/issues/56508180f5d3a7f76bc18d84/sessions/a998377dcb0945068d93a03719309a4f
=> Use safe expectations when parsing Media objects.

WordPress/Classes/Extensions/WPNoResultsView+Model.swift, WordPress/Classes/Models/Plan.swift, WordPress/Classes/Models/Product.swift, WordPress/Classes/Services/PlanService.swift, WordPress/Classes/Services/StoreFacade.swift, WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/PlanListViewControllerTest.swift, WordPress/WordPressTest/StoreFacadeTests.swift
Includes a mock store facade for quick testing of the UI.
Some notes:
- Available plans are still hardcoded, but it's designed so they can be loaded from the API in a future version.
- (Test) product identifiers are hardcoded.
- I'm not happy about how `ProductRequestDelegate` retains itself until the request completes but I couldn't think of a better solution.
- The UI for loading/error is pretty basic. I didn't wanted to clutter this PR with all the animation code, but it's ready for a future PR.
See #4746
=> Fetch product prices from StoreKit

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
How to test:
- Open the app and create a new post
- Disconnect the network connection
- Insert a image
- You should get a failed media upload
- Tap on the image and select the option Remove
- Check if the editor is not dismissed.
Needs Review @frosty
=> Fix Media Removal

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Fixes a stat that was not being properly bumped as tracks only supports lowercase properties. 
=> Reader: Makes analytics property key lower case.

WordPress/Classes/Utility/FeatureFlag.swift, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Refs #4907 
This pr removes the sharing feature flag, and enables the feature in non-debug builds. 
Needs review: @alexcurylo
=> Sharing: Removes sharing feature flag.

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m, WordPress/Classes/ViewRelated/NUX/LoginViewModel.h, WordPress/Classes/ViewRelated/NUX/LoginViewModel.m, WordPress/WordPress-Alpha.entitlements, WordPress/WordPress-Internal.entitlements, WordPress/WordPress.entitlements, WordPress/WordPress.xcodeproj/project.pbxproj
Adds support for iOS associated domains to pull in Safari saved passwords. Using the shared web credential functions, any saved passwords that were entered via the FQDN of wordpress.com will prompt for autofill on login within the app.
Any subdomains of wordpress.com, mapped domains, or self-hosted sites will not work as they cannot be an "associated domain" without inclusion in the app bundle.
Also including support for updating a Safari saved password if the user autofills an out-of-date password and inputs the correct updated password text upon successful login.
**Testing:**
1. On a device, enable saved passwords and names in Safari settings.
2. Log in at http://wordpress.com/wp-login.php
3. When prompted, save password.
4. Open app and log out if needed.
5. Upon viewing the log in …
=> Safari username/password autofill for login

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.m
Previously posts where filtered out according to an oldest post date. This is to prevent old posts from showing up in a posts list and breaking the ordered paging.
Updating the predicate for filtering posts by an oldest date _and_ including posts that do not have a date. Posts that may not have a date are posts created without a connection or a bad connection. These posts should display at the top of the list, even after refreshing the post list.
To test:
1. Open up the "Blog Posts" posts list view.
2. Turn off Wifi or disable internet connection.
3. Create a new post and post it.
4. Post should display at top of the posts list as a "local post".
5. Enable internet connection.
6. Refresh list, post should either stay at top of list as a "local post" or should automatically post, depending …
=> Issue: Local posts hidden if created without a connection

WordPress/Classes/ViewRelated/NUX/LoginViewController.m
Adding support for prompting Safari AutoFill credentials when a user on the LoginView backgrounds the app and returns to the app/LoginView.
This resolves a case in which a user may have saved a password into Safari while the app is backgrounded, or if the user hit the "Not Now" button and then returned to the app expecting the prompt.
To test:
1. Open the app, sign out if needed.
2. Hit the "Not Now" button on the prompt.
3. Background the app, return to the app.
4. Notice prompt for autofilling credentials.
=> Prompt for autofill credentials when returning to the app from background.

WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #4845 
Updates rendering of icon badge to match specification in #4845 and uses CAShapeLayer to eliminate cornerRadius antialiasing. Before and after rendering:
To test:
With unread notifications, verify badge appearance matches specification.
Note - To test on a device, Install the App Store version, then generate a notification by commenting on one of your blogs or the like, so that the available notifications badge will be picked up by the debug build. To test in the Simulator, set `count` in `updateNotificationBadgeVisibility()` to 1.
cc: @mattmiklic 
=> Update rendering of notification icon badge

WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
Fixes #4894
To test:
1. Log into your WP.com account
2. Tap over Notifications
3. Open a Comment-Y Notification
4. Enable iOS VoiceOver
5. Verify that `Like` / `Approve` buttons change their accessibility labels, as needed.
=> NoteBlockActionsTableViewCell: Dynamic accesibility labels

WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/Models/BasePost.h, WordPress/Classes/Models/BasePost.m, WordPress/Classes/Models/Post.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/393
To test:
2. Start writing a new post.
3. Disconnect from your wifi
4. Try to "Post" the post.
5. It should be saved locally.
6. Reconnect to the internet
7. Open the post
8. Tap the back button.
Expected behaviour: a "Save as Draft" option should be available.
Also: play with creating posts, closing them, saving, etc... and make sure the action sheet buttons are always correct.
=> Fixes an issue with how local changes were handled.

WordPress/Classes/Networking/BlogServiceRemoteXMLRPC.m
Fixes #4887
To test:
- Check out `release/5.8`. If you find a build error you might need to replace an AFNetworking header import with `@import AFNetworking;` in `WPWebView.m`
- Run the app, fresh install
- Add a self hosted blog
- Go to wp-admin on a browser and change your password
- Check out this fix's branch
- Run the app
- Go to site settings
- Change the site title
As a result, the app shouldn't break anymore.
=> BlogServiceRemoteXMLRPC: Adds nil failsafe(s)

WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.xib
Fixes #4937
Ideally, the noticon would read the type of notification, but I didn't see an easy way to do that, so I just disabled VoiceOver on the noticon label
To test:
1. Enable VoiceOver
2. Go to notifications
3. Tap on any notification
It should read the text as displayed, without any weird "extras" before
=> Disable accessibility on noticon label

WordPress/Classes/Utility/Sharing/WordPressActivity.m, WordPress/Classes/ViewRelated/Post/PostListViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.h, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/785
**Test 1:**
1. Go to the list of posts for any blog.
2. Set the filtering to "Published"
3. Create a new post but instead of saving, discard it.
4. The filtering should still be set to "Published".
**Test 2:**
1. Go to the list of posts for any blog.
2. Set the filtering to "Published"
3. Create a new post, and save it as draft.
4. The filtering should be changed to "Draft" and the new post should be on screen.
=> Cancelling editing no longer modifies the post list filtering.

WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
Continuing the work on #4926
Fixes #4894
To test:
1. Log into your WP.com account
2. Tap over Notifications
3. Open a Comment-Y Notification
4. Enable iOS VoiceOver
5. Verify that `Like` / `Approve` buttons change their accessibility labels, as needed.
Like button should say:
- When liked: _Liked, Button,... Unlikes the comment_
- When not liked: _Like, Button,... Likes the comment_
Approve button should say:
- When approved: _Approved, Button,... Disapproves the comment_
- Wehn not approved: _Approve, Button,... Approves the comment_
I chose "Disapproves" over "Unapproved" as VoiceOver was pronouncing that weird, and it's also a bit more accurate.
=> Improve accessibility of comment actions

WordPress/Classes/Models/Blog.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Fixes #https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/254
There was a bug that was making some people have to close and reopen the post settings screen, since if the post formats didn't load successfully due to a lack of an internet connection, they would not attempt a re-download.
**Test 1:**
1. Reset the simulator
3. Login
4. As soon as login completes, disconnect from the internet (shut down your Wifi)
5. Open a blog
6. Create a new post
7. Go to post settings (the gear icon in the top right)
Expected: the post format cell should read "Not available".  If you tap on it, an alert should come up saying there's no connection to the internet.
**Test 2:**
1. Follow all steps from test 1, up to step 7 (included).
2. Reconnect to internet, and make sure the …
=> Editor: Post formats are now synchronized when internet reconnects.

WordPress/Classes/Models/WPAccount+AccountSettings.swift
Fixes #4944
To test:
Easiest way to test this is by checking out `issue/2599-primary-site-order` branch, cherry-picking commit `acd8cd1` (the only commit in this PR) and...
2. Open `Me` > `Account Settings`
3. Update the Primary Site
4. Verify that the (new) Primary Site shows up on top of the `My Sites` list
=> WPAccount+AccountSettings: Updating defaultBlog Relationship

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Fixes #4956 (maybe)
This is a best guess as a patch for #4956 based on the offending line number. If nothing else its probably a better practice to use guard here than the previous explicit unwrapping of the optional. It shouldn't have ever been nil but I'm not sure how else to account for the crash.
=> Reader: Adds guard against nil and logs nil as an error.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Internal.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Fixes #4859
To test:
1. Receive a Comment-Y Notification
2. Launch WPiOS and open the Notifications tab
3. Open the Notification details
4. Tap over the `Trash` button
5. Within 4 seconds, tap *Undo*, open the Notification Details, and tap `Trash` again
Verify that the notification gets effectively nuked *4 seconds* after tapping the Trash button. This was caused by a *GCD* dispatch_after call, not being cancelled (because there is no mechanism to do so!).
=> Fixes Notifications Undelete Glitch

WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift
Fixes #4858
To test:
1. Launch WPiOS and log into (YOUR `ardwptest1` Test Account, Aaron)
2. Open the Notifications Tab
3. Verify that the Gravatars don't get mixed
Thanks in advance Aaron (+ thanks for lending me the buggy test account!!)
=> NoteTableViewCell: Fixing gravatar caching glitch

WordPress/Classes/ViewRelated/Reader/CommentContentView.m
Fixes #4878
This fixes an improper conditional so that the author button is correctly enabled or disabled depending on if the comment author has a valid author URL. This resolves the crash in #4878 which could be triggered if the button was enabled when the author URL was nil.
To test:
Repeat the steps described in #4878.
Set a breakpoint in the editied conditional and confirm that the button is being correctly enabled/disabled.
=> Reader: Fixes condtional so button is correctly enabled/disabled.

WordPress/Classes/Services/BlogService.m, WordPress/Classes/Services/TodayExtensionService.m, WordPress/Classes/ViewRelated/Stats/StatsViewController.m, WordPress/WordPress_Prefix.pch
This PR is a minor cleanup. `NCWidgetController` is available for iOS +8 devices, and since our deployment target has been +9 for a while, already... it's time to clean the house.
Thanks!
=> Nukes WIDGETS_EXIST Macro

WordPress/Classes/Services/AccountService.m, WordPress/Classes/Services/BlogService.m, WordPress/Classes/Services/JetpackService.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressShareExtension.xcscheme
1. From a fresh install, sign into a self hosted blog.
2. Open safari and confirm that the share extension prompts you to connect a wpcom acct.
3. Back in the app, navigate to the blog detail screen and tap Stats.
4. Sign into the wpcom account connected to Jetpack.
5. Return to the blog list and confirm any other wpcom blogs owned by the account appear in the list.
6. Return to Safari and try the share extension again.
7. The Today Extension should show the "Primary Blog" pre-selected
Fixes #4955
=> Fixing Extension Setup via Jetpack Login

WordPress/Classes/Services/ShareExtensionService.swift, WordPress/Classes/Services/TodayExtensionService.m, WordPress/Classes/System/Constants.h, WordPress/Classes/System/Constants.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/Stats/StatsViewController.m, WordPress/Tracks+ShareExtension.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressShareExtension/ShareViewController.swift, WordPress/WordPressShareExtension/Tracks.swift, WordPress/WordPressTodayWidget/TodayViewController.swift
In this PR we're implementing a small tool, meant for Extensions Usage, which hits the Tracks Backend.
This tool can be hooked to a background NSURLSessionConfiguration in background mode, which allows us to "complete tracker-OP's even after the extension has been killed"™.
Testing scenarios outlined below.
--
1. Fresh install the app, and **don't sign into your account**
2. Switch to Safari
3. Launch the WPiOS Share Extension
As a result, after a couple minutes, the event `wpios_share_extension_launched` should show up, with the payload `is_configured_dotcom = false`.
1. Fresh install the app, and sign into your account
2. Switch to Safari
3. Launch the WPiOS Share Extension
As a result, after a couple minutes, the event `wpios_share_extension_launched` should show up, with the payload …
=> Share Extension Metrics

WordPress/WordPressShareExtension/Tracks.swift
In this (brief) PR, we're adding few good NSURLSession practises:
- The same Background NSURLSession is being reused for all of the Tracks calls
- On deinit, as per [Apple's documentation, we're invalidating the session](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/NSURLSessionConcepts/NSURLSessionConcepts.html#//apple_ref/doc/uid/10000165i-CH2-SW42).
```
When your app no longer needs a session, invalidate it by calling either invalidateAndCancel (to cancel outstanding tasks) or finishTasksAndInvalidate (to allow outstanding tasks to finish before invalidating the object).
```
cc @SergioEstevao thanks for helping me out with this one!
=> Share Extension NSURLSession Invalidation

Podfile, Podfile.lock, WordPress/Classes/Services/AccountService.h, WordPress/Classes/Services/AccountService.m, WordPress/Classes/System/WordPressAppDelegate.m
In this PR we're exposing the Extension Initialization routine, so that it can be called from (anywhere else). This is meant to solve the "Extension doesn't get initialized after upgrading the app" glitch we've observed during our IPA tests.
=> Share extension initialization

WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift
While testing other things I noticed the sharing button label was not saving changes. The problem was due to faulty conditional.  This PR fixes the conditional so changes are properly saved.
To test: Navigate to the Sharing feature and manage sharing buttons.  Edit the text of the sharing label and confirm the change is A) reflected back on the management screen and B) propagated to the blog. 
Needs review: @kurzee would you mind a quick review sir?
=> Sharing: Fixes the check for a changed sharing button label.

WordPress/Classes/Models/Blog.m
Fixes #4992 
To test: 
Using a private wpcom blog, perform the following actions:
Connect to a publicize service. 
Disconnect from a publicize service. 
Add sharing buttons.
Add more buttons. 
Reorder buttons. 
Change sharing button settings. 
Confirm the changes are propagated to the private blog. 
Needs review: @jleandroperez would you do the honors sir?
=> Sharing: Allow sharing mgt for private blogs.

Scripts/build.sh
While trying to figure out some broken tests I wanted to run the same `xcodebuild` command as Travis, but `xcpretty` wasn't showing why everything was failing. It turned out it wasn't xcpretty's fault, but I think this additions are useful to debug the build script locally.
New functionality:
- Adds command line argument parsing to the script, `-h` to show usage
- `-c` will call `clean` before building. This isn't needed on Travis/CircleCI as we're building on "clean" VMs, but it's useful when running locally
- `-d` will show the exact command(s) that the script will run.
- `-l` will store the raw output of `xcodebuild` in a log file.
- `-v` will skip xcpretty and print the output of `xcodebuild` directly.
If you run it without arguments, the behavior shouldn't have changed since the …
=> Improvements to build script

WordPress/Classes/ViewRelated/Blog/SharingConnectionsViewController.m
Fixes #4990 
To test: 
Go to the Sharing feature and tap on a publicize service that has no connections.  Confirm the cell text reads "Connect"
Connect to the service. Confirm the text still reads "Connecting..." and shows a spinner when the publicize authentication modal dismisses. 
Return to the connections screen. Now that you have an existing connection, confirm the cell text reads "Connect Another Service"
=> Sharing: Changes text depending on state and number of connected accts.

WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m
Fixes #4831
To test: view or edit a post. The back button/blog selector is no longer truncated.
=> Corrected inset calculation for WPBlogSelectorButton

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Fixes #5019 
Ideally we'd show the NUX controller to add a new account, which was the direction I started down initially.  However, doing so would require a small refactor of that controller.  Since there is *already* a refactor planned as a follow up to the work currently being done on sign in I've opted to just hide the button when the user isn't signed in. 
To test:
Repeat the steps outlined in the issue. 
Confirm the add wpcom site option does not appear unless signed into wpcom. 
=> Hide add wpcom site option when not signed in.

WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m
Fixes #5026
To test:
View or edit a post that has been published to a site, so that the site selector isn't shown. The text part of the back button is now tappable.
Needs review: @aerych – as  this one is similar to the last
=> Back button text

WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift, WordPress/WordPressTest/System/3DTouch/WP3DTouchShortcutCreatorTests.swift
Improve 3D Touch shortcut creator testability. This test keep failing randomly when messing with the build scripts and CI, until I realized the `With3DTouchNotAvailable`. The previous tests passed on the iPhone 6 simulator, but failed on the iPhone 6S, since 3D touch was available there.
I've extracted what's needed from `UIApplication` to an `ApplicationShortcutsProvider` so we can mock it and pretend that 3D Touch is (un)available regardless of the device used in the simulator. 
To test:
- Run the test suite on iPhone 6/6S and make sure it passes on both.
=> 3D Touch tests refactor

WordPress/Classes/ViewRelated/NUX/LoginViewController.m
Fixes #5023
Now avoiding auto-filling login fields if the user has toggled to add a self-hosted site.
To test:
Follow same steps in #5023
=> Prevent AutoFill prompt when adding a self-hosted site.

WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
When a post has no comments, this message is currently displayed:
An extra "m" has snuck into "comments". This PR removes it :)
To test:
- In the post stream, tap the comment bubble on a post with no comments.
- Make sure "comments" is spelt correctly in the displayed message.
=> Fix typo in no comments message ("commment")

WordPress/Classes/Models/Blog.m, WordPress/WordPressApi/WordPressComApi.m
Fixes #4985
To test: Try to upload a image to a self-hosted site with jetpack installed that is returning a 403 error. User is a contributor for example.
=> Media upload crashed on upload error

WordPress/Classes/Services/PostCategoryService.h, WordPress/Classes/Services/PostCategoryService.m, WordPress/Classes/ViewRelated/Blog/CreateNewBlog/CreateNewBlogViewController.m, WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m
To test:
2. Create a new account
Make sure that the Widget + Share extension are properly initialized. No assertion should be triggered.
=> Fixing extension assertion

WordPress/WordPressApi/WordPressComOAuthClient.m
To test:
- Log in to WordPress.com
- Make sure there's no real `access_token` in the log
=> Don't log OAuth2 tokens

WordPress/Classes/Models/BasePost.h, WordPress/Classes/Models/BasePost.m, WordPress/Classes/Models/Comment.m, WordPress/Classes/Models/PostContentProvider.h, WordPress/Classes/Models/ReaderPost.m, WordPress/Classes/Models/ReaderPostContentProvider.h, WordPress/Classes/Models/WPCommentContentViewProvider.h, WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/Classes/ViewRelated/Pages/PageListViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
Small change to our codebase.  Renames `WPContentViewProvider` to `PostContentProvider`, since it's basically providing post-related information only.
The name `WPContentViewProvider` was not too clear and sounded too generic.
To test:
- Just make sure the app compiles and runs.
- Review the code changes.
Needs review: @aerych.
=> Renames WPContentViewProvider to PostContentProvider.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
Fixes #4986
1. Log into a WordPress.com account with few notifications (i can hand over a test account via DM!)
3. Ensure that at least one of the filters produces zero results, and tap on it
As a result, the Notification Filters should remain visible.
Thanks in advance James!
Props to @lancewillett for spotting this one + reporting it!
=> Fixes Notification Filters Logic

Podfile, Podfile.lock, WordPress/Classes/Categories/UIImage+Resize.m, WordPress/Classes/Utility/WPAvatarSource.m, WordPress/Classes/Utility/WPTableImageSource.m, WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift, WordPress/Classes/ViewRelated/Comments/WPStyleGuide+Comments.swift, WordPress/Classes/ViewRelated/Me/AboutViewController.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingStreamsViewController.swift, WordPress/WordPressTest/WPAvatarSourceTest.m
Fixes dependencies of outside pods:)
Check the comments section on the reader and the notifications section to see if all gravatar images are being displayed properly.
Needs review: @jleandroperez and @aerych I think the Reader and Notifications where the main users of these methods do you mind to have a look?
=> Remove MGImageUtilities pod from our project.

WordPress/Classes/ViewRelated/Plans/PlanComparisonViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift, WordPress/Classes/ViewRelated/Plans/Plans.storyboard, WordPress/Classes/ViewRelated/System/PagedViewController.swift, WordPress/Classes/ViewRelated/System/PagedViewController.xib, WordPress/WordPress.xcodeproj/project.pbxproj
Besides making PlanComparisonViewController use real plans and prices, this PR changes a few things:
- Refactored UI logic of the custom page controller to a generic PagedViewController. The view controllers to show are passed on initialization, although it could be modified to make it dynamic if that's necessary.
- Switched from storyboards to a single XIB for PagedViewController, so we can have `let` properties populated on initialization.
- Plan Comparison subclasses this new paged controller and just adds: close button, feature fetching, and transforming the plan information into view controllers.
Known issues:
- Tweaked the accessibility announce to use the VC's `accessibilityLabel` if present. I haven't been able to test this since VoiceOver is not announcing the layout change for …
=> Refactor Plan Comparison and use remote data

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/ViewRelated/NUX/LoginViewController.m
Ref https://github.com/wordpress-mobile/WordPress-Android/pull/3769 and https://github.com/wordpress-mobile/WordPressCom-Analytics-iOS/pull/56
=> Rename Safari auto fill events to something more generic

Podfile, Podfile.lock
The existing versions of Alamofire and Nimble were throwing a bunch of warnings on build. This updates them both to newer versions which include fixes for Xcode 7.3
=> Update Nimble/Alamofire to fix Xcode 7.3 warnings

WordPress/Classes/Extensions/String+Helpers.swift, WordPress/Classes/Models/Plan.swift, WordPress/Classes/Networking/PlansRemote.swift, WordPress/Classes/Services/PlanService.swift, WordPress/Classes/ViewRelated/Plans/PlanComparisonViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift
Gets rid of both the global `planFeatures` and `PlanFeatureGroup.groups`.
The previous `PlanFeatureGroup` is now `PlanFeatureGroupPlaceholder` as it only holds the slugs of the features.
When the features are fetched from the API, we call `PlanService.featureGroupsForPlan(_:features:)` to combine the known plan groups with the full feature data for that plan.
This also makes `PlansRemote` actually get all the plan data from the JSON. Surprisingly the existing version still got just the planID and mapped the rest from the hardcoded plans list.
Fixes #5068 
=> Refactor feature loading

WordPress/Classes/Extensions/NSString+Helpers.swift, WordPress/Classes/Extensions/UIViewController+Helpers.swift, WordPress/Classes/Networking/AccountSettingsRemote.swift, WordPress/Classes/Utility/ImmuTableViewController.swift, WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m, WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift, WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m, WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift, WordPress/Classes/ViewRelated/Me/SettingsCommon.swift, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/Classes/ViewRelated/Tools/SettingsListEditorViewController.swift, WordPress/Classes/ViewRelated/Tools/SettingsTextViewController.h, WordPress/Classes/ViewRelated/Tools/SettingsTextViewController.m, WordPress/WordPressTest/NSStringHelpersTest.m
In this PR we're adding the `Edit Account Email` feature. Please, note that for the sake of consistency, all of the Account editable fields now present a modal viewController on tap.
Reason for this is: validation must be performed before dismissal.
Please, note that the **Email change pending validation** will be handled via #5086.
Closes #4823
1. Log into a WordPress.com account
2. Open `Me` > `Account Settings` > `Email`
3. Enter an invalid email
4. Verify that an AlertController gets displayed
5. Enter a valid email
Verify that the change is effectively persisted. Please, test on both, iPad / iPhone devices.
1. Log into a WordPress.com account
2. Open `Me` > `Account Settings`
3. Open `Primary Site` and verify that it gets presented modally
4. Open `Web Address` and verify that it …
=> Account Settings: Email

WordPress/Classes/Services/MediaService.m, WordPress/Classes/Services/MediaSettings.swift, WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m, WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift
Fixes #4850
To test:
- Go to account settings and check if new option to strip GPS location is there
- Create a new post, add image with GPS information (make sure you the photos you use has location information)
- See if the options has the desired effect of keeping and removing GPS information by downloading the image from  the server and checking the properties on Preview.
=> Move strip gps information setting from blog settings to account settings.

Podfile, Podfile.lock, WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #5081 
Adds a temporary (hopefully) fix to the Today widget target to whack the Frameworks folder that CocoaPods creates inside of the Today Widget plugin in the app bundle. Also told the compiler that the extension doesn't contain Swift so that it doesn't try bundling the Swift libraries with the extension.
The other problem with the submission process is due to HelpShift's bundle having a key in it that has to be removed. See the original issue for how to fix this - they should be issuing an updated library to fix this in the near future. Updated 7-APR: Helpshift released 5.5.1 of their SDK which resolves this issue. Updated the branch with the Podfile update.
Note: I have submitted a build to Apple for TestFlight using this branch as well as turning off bitcode because of …
=> Prevent build from embedding Framework in Today Widget

WordPress/Classes/ViewRelated/Blog/SharingAuthorizationHelper.m
Fix a typo in a translator comment.
=> i18n: Typo in translator comment

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Me/MeViewController.swift
Closes #5113 
Adds missing Gravatar icons to the Me screen and applies the 10% lighten grey color to them.
To test:
* Look at the screenshot or launch the app in debug to see the updated screen
Needs review: @frosty, @rickybanister
=> Updates the styling of the Me screen

WordPress/Classes/Extensions/UIView+Helpers.swift, WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift, WordPress/Classes/ViewRelated/Plans/Plans.storyboard
#A couple of quick design amends for Plans:
* Plan detail header now scrolls with the tableview.
* Plan detail header shrinks if necessary – to test this, go to a site that currently has Premium and then view the Free plan.
* "per year" period labels for plans are now in `grey`, not `greyLighten20`.
* Some font size changes:
=> Plans design amends

MIGRATIONS.md, WordPress/Classes/Models/Menu.h, WordPress/Classes/Models/Menu.m, WordPress/Classes/Models/MenuItem.h, WordPress/Classes/Models/MenuItem.m, WordPress/Classes/Models/MenuLocation.h, WordPress/Classes/WordPress.xcdatamodeld/WordPress 48.xcdatamodel/contents
Adding changes to the Menus model objects since developing the UI in branch `feature/menus-views`.
- New string `const` for Menus.
- Includes new helper methods on `Menu` and `MenuItem`.
- Using `strong` instead of `retain` on CoreData generated attributes in code.
- Updating the CoreData model version 48 to refactor Menu ID attributes to instead be `NSNumber` integers rather than strings.
To test:
- No tests available for the model changes here, but tests are available for the upcoming `MenusService` PR utilizing this model.
Needs review: @diegoreymendez 🎉
=> Menus: model object additions and refactor

WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #5078 
To test:
1. Install.
2. Turn on VoiceOver or use the Accessibility Inspector.
3. Verify each of the five tabs have labels. Verify that visible labels are not present (against my better judgement). :smile: 
=> Sets a blank title which allows accessibilityTitle to work properly

WordPress/Classes/Utility/ImmuTableViewController.swift, WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift, WordPress/Classes/ViewRelated/Me/SettingsCommon.swift
Reverts the behavior introduced in f87900f7eccd6552b60a5fcaef665bead127d67c for #5087 and adds the more explicit `insideNavigationController` method to SettingsController.
This fixes an issue where presenting a plans list would try to wrap a navigation controller inside another navigation controller causing a crash.
To test:
- Go to Account Settings, make sure all the fields present the editor with a navigation controller.
- Go to a wp.com site > Plans, and tap on a plan. The plan comparison should open inside a navigation controller.
=> Don't wrap controllers in navigation from present

WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift
Changes to plural possessive from singular possessive. 
=> Sharing: Fix typo

WordPress/Classes/ViewRelated/Themes/ThemeBrowserHeaderView.swift
Fixes #5092 
To test:
1. At the present moment the text isn't localized so to make sure it works copy [this](https://cloudup.com/caRzGgIUq8M) Localizable.strings into the `Resources/es.lproj` directory
2. Open the app up and login with a .com account.
3. Open up the Themes page and verify that the "Current Theme", "Customize", "Support",  and "Details" labels are all localized(see screenshot below).
=> Themes Header:Fix buttons on the header to be localizable.

WordPress/Classes/Networking/MenusServiceRemote.h, WordPress/Classes/Networking/MenusServiceRemote.m, WordPress/Classes/Networking/Remote Objects/RemoteMenu.h, WordPress/Classes/Networking/Remote Objects/RemoteMenu.m, WordPress/Classes/Networking/Remote Objects/RemoteMenuItem.h, WordPress/Classes/Networking/Remote Objects/RemoteMenuItem.m, WordPress/Classes/Networking/Remote Objects/RemoteMenuLocation.h, WordPress/Classes/Networking/Remote Objects/RemoteMenuLocation.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/MenusServiceRemoteTests.m
Adds the Menus remote service and unit tests. The Menus API is only available over the REST API, so no XML-RPC remote is needed here.
- `RemoteMenu` is a site menu itself.
- `RemoteMenuLocation` is a location/area in which a menu can appear on a site/theme.
- `RemoteMenuItem` are the individual items/link for a menu.
To test:
- Run the tests under `MenusServiceRemoteTests` and check for all passing.
Needs review: @diegoreymendez would please review? 💃💃💃
=> Menus: remote menus service and tests

WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/Services/MenusService.h, WordPress/Classes/Services/MenusService.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/MenusServiceTests.m
Adds the Menus model service and unit tests. The Menus service wraps around `MenuServiceRemote` with the CoreData model for persistence and relationships.
- `Menu` is a site menu itself.
- `MenuLocation` is a location/area in which a menu can appear on a site/theme.
- `MenuItem` are the individual items/link for a menu.
Currently, every sync of Menus is intended to wipe the `menus` and `menuLocations` relationships on `Blog`, not trying and update existing objects.
**To test:**
Run the tests under MenusServiceTests and check for all passing.
Needs review: @diegoreymendez would you please review? 🙈
=> Menus: model service and tests

Podfile, Podfile.lock
Fixes #5076 and https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/627
To test: 
* Create a new post and try to upload a video, see if the thumbnail progress shows correctly.
* Add media to post and delete it while uploading by using the back button in the keyboard. Check if the progress bar on top is updated correctly. 
=> Update editor pod version to 1.3

WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift
Fixed sizing for Plan Detail table headers with wrapped text.
I've added an implementation of `tableView(_:heightForHeaderInSection:)` that uses the uppercased string from the header view itself.
To test: View the section headers in Plan Details Business on an iPhone 4S sized simulator. Check that the wrapped header has enough padding below it.
=> Plan Detail: Table headers that wrap are now sized correctly.

WordPress/Classes/ViewRelated/NUX/LoginViewModel.m
Fixes #5134 
To test: Try signing into a self-hosted site and append wp-login.php or /wp-admin to the end of the URL. Confirm that you are still able to login. 
=> Use the filtered baseSiteUrl not siteUrl when signing in.

WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift
After merging #5129, I was using the app and noticed that the plan detail header was collapsing the price or 'current plan' label. This PR moves the call to layout / resize the header (and only does so if the size has changed), which fixes the issue for me. 
Before:
After:
=> Plan Detail: Fixes sizing of the table's header view.

WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Closes #5075 
To test: 
- Set a break point in ReaderHelpers.bumpPageViewForPost().
- Load a topic in the reader and like a post from one of the cards in the list. 
- Confirm the breakpoint catches the like. 
- Unlike the post.  Confirm the unlike action does not bump the page view. 
=> Reader: Bumps page view when post is liked from the stream.

WordPress/Classes/Extensions/UIViewController+Helpers.swift, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Removes a duplicated symbol.  It's not failing currently in `develop` but it was causing trouble in [another PR I'm working on](https://github.com/wordpress-mobile/WordPress-iOS/pull/5156/files).
This is a temporary name change, as these methods should be unified (probably in the WPiOS Shared pod).  I've opened [an issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/5157) to track this task.
=> Removes a duplicated symbol.

WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #5168 
To test:
1. Perform an archive build for the Internal target.
2. Inspect the bundle to find HockeyApp and Lookback resources.
Needs review: @aerych or @kwonye
=> Adds the missing steps for CocoaPods to embed resources properly

WordPress/Classes/Models/Plan.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/PlanListViewControllerTest.swift, WordPress/WordPressTest/StoreTests.swift, WordPress/WordPressTest/Test Data/TestPlans.swift
Not sure if ready for merge, but I wanted some feedback:
`titleForPlan` worked with hardcoded plans, and there's no easy alternative. Right now the Site Details would just not show the active plan in the Plans row.
I was thinking of fixing that on a separate PR, since I'm not sure what's the best approach yet. I'm leaning towards getting a plan name along with the active plan ID.
In a way it seems wasteful to send an extra request for all plans just to show the site details. But then we might want to preload all the plan data in the app. I think this needs more thinking, and I really want to get rid of those hardcoded plans :)
Fixes #5069 
=> Remove hardcoded plans

WordPress/Classes/Services/Store.swift, WordPress/Classes/ViewRelated/Plans/PlanComparisonViewController.swift, WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/StoreCoordinatorTests.swift
Part of #5033, #5167 
Please review the unit tests as I think I covered all relevant cases. For manual testing:
- A Purchase button should only show for sites without an existing paid plan
-To test the `pending` state, you can tap purchase on the simulator, then cancel. When you come back to the plan details, it should show the animating button. This obviously needs to be improved, but it's been helpful to test this PR
=> Prevent purchase of plans in certain cases

WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTodayWidget/TodayViewController.swift, WordPress/WordPressTodayWidget/Tracks+TodayWidget.swift
Closes #3306 
To test:
1. Launch the today widget.
2. When unconfigured, tap configure. Verify event sent.
3. When configured, verify event sent when data is refreshed.
4. When configured, verify event sent when tapping data to launch containing app.
=> Using the Tracks client from Share, track Today Widget usage.

WordPress/Classes/Utility/ImmuTableViewController.swift
Previously, when the SettingsTextViewController is dismissed, the value changes.
The service applies the change locally and saves immediately, then queues a
change request. When Profile/Settings appears again it triggers a remote
refresh, which brings back the old value. When the change request completes, it
doesn't update the local value.
The downside of this fix is that the VC will keep getting updates even if not
visible but I can live with that for now and the alternatives are much more
complicated.
Fixes #4888
=> Prevent race condition when changing settings

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Cells/WPBlogTableViewCell.h, WordPress/Classes/ViewRelated/Cells/WPBlogTableViewCell.m
Fixes #5195. See that issue for full details, and how to test.
I've tweaked the code so that it can now use the correct index path for each cell, rather than relying on a view tag (eww!)
Thanks!
=> Fixes #5195 – Toggling site visibility crashed the app

WordPress/Classes/Networking/AccountServiceRemoteREST.m, WordPress/Classes/Networking/WordPressComServiceRemote.m, WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/Utility/Analytics/WPAppAnalytics.m, WordPress/Classes/Utility/HelpshiftUtils.m, WordPress/Classes/Utility/HockeyManager.m, WordPress/Credentials/ApiCredentials.h, WordPress/Credentials/ApiCredentials.m, WordPress/Credentials/gencredentials.rb, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressApi/WordPressComOAuthClient.m, WordPress/WordPressTest/WPAppAnalyticsTests.m
Before moving further with #5187 I'm moving the credentials code outside the WordPressApi directory, since it doesn't really belong there, but mostly because I don't want to put the credentials inside a framework.
Also renamed to ApiCredentials, since they don't just contain wp.com credentials
anymore.
=> Move API credentials outside WordPressApi

WordPress/Classes/Models/Media.m, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m
This PR adds support for video insertion on the legacy editor
To test:
- Disable the Visual editor in App Settings
- Using the text editor click to add a media object
- Select a video
- Check if insertion happens
Check on WP.com sites and self-hosted.
=> Add support for video in the legacy editor.

Podfile, Podfile.lock
Switching to using Gridicons from Cocoapods' spec repo instead of pointing directly at the podspec.
Thanks!
=> Gridicons pod now uses Cocoapods trunk.

WordPress/Classes/Utility/DisplayableImageHelper.m
Fixes #5205
To test:
View a feed where some of the posts contain a single .svg image, and where they contain a wpcom smiley. Make sure that none of the .svg images are picked up.
=> Reader: Filter out svg and wpcom smilies from featured images.

WordPress/Classes/Categories/UIImage+Alpha.h, WordPress/Classes/Categories/UIImage+Resize.h, WordPress/Classes/Categories/UIImage+RoundedCorner.h, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressShareExtension/UIImageView+Extensions.swift, WordPress/WordPressShareExtension/WordPressShare-Bridging-Header.h
Fixes #5192
1. Hack [this spot](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/WordPressShareExtension/SitePickerViewController.swift#L107) so that siteIconUrl gets initialized with the following url: `https://i1.wp.com/photos.happylinguist.com/wp-content/uploads/2013/12/cropped-conwycastle.jpg`.
2. Launch the share extension.
3. Verify that the Blavatars are properly sized down, when / if needed.
=> Share Extension: Jetpack Blavatars

WordPress/Classes/ViewRelated/NUX/SigninWPComSyncHandler.swift
Fixes #5229 
Blogs need to be synced before account info is updated. 
To test: Sign in via the new sign in flow.  Confirm that the default site is correctly displayed in the blogs list. 
cc @jleandroperez
=> Signin: Switches order that blogs are updated and acct info is synced..

Podfile.lock, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressShareExtension/NSExtensionContext+Extensions.swift, WordPress/WordPressShareExtension/ShareViewController.swift, WordPress/WordPressShareExtension/String+Extensions.swift, WordPress/WordPressTest/Extensions/StringExtensionsTests.swift
Fixes #5191
Testing steps described in the issue itself. Until we implement the JS Extension Add-on, fix consists on:
- Always append the URL, and make it visible
- Linkify the text, whenever the user hits Post
Few things have been prettified here and there.
Thanks in advance, YO!
=> Share Extension: No more Empty Text

WordPress/Classes/ViewRelated/Post/PostListFilter.h, WordPress/Classes/ViewRelated/Post/PostListFilter.m
Adds nullability information to `PostListFilter`.  Also adds additional type information for an array.
PS: this is a very atomic PR aimed at solving these issues as part of another [large upcoming PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/5237).
**To test:**
Simply build the code and run the unit tests to make sure nothing broke.
=> Adds nullability info to PostListFilter.

WordPress/Classes/ViewRelated/Post/PostListFilter.h
I missed a modification from a [previous PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/5238).  This change was and is still non-breaking so it can be handled separately.
This is also a part of an upcoming [large PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/5237).
Just build the code and run the unit tests.
Needs review: @kurzee (sorry for the double PR!)
=> Adds more specific type info in PostListFilter.

WordPress/WordPress.xcodeproj/project.pbxproj
@diegoreymendez Looks like your recent merges missed a deletion in the project file for `PageListViewController` and also a previous deletion of `NSDateStringFormattingTest` previously merged in https://github.com/wordpress-mobile/WordPress-iOS/commit/7531fb60cee7464ef67b34c99c4ee9584ae4bb7a.
Note: Xcode auto-cleaned these when I was adding files for a different PR.
=> Xcode auto cleanup of previously removed files.

WordPress/Classes/Networking/ReaderPostServiceRemote.m
In #5221 I neglected to correct the path for the v 1.2 endpoint.  The result was api calls to `/sites/siteID/posts/postID` were 404ing.  
This pr adds the missing path component. 
To test: 
Try opening a post detail from a comment notification, or from a Discover editor's pick.  Confirm that the post loads correctly. 
=> Reader: Adds missing endpoint path component.

WordPress/Classes/Utility/Languages.swift, WordPress/WordPressTest/LanguagesTests.swift
This fixes a couple issues:
- Apple uses `language-script` for Chinese languages, but we only do `language-region`. We already do a similar map on `update-translations.rb` to match the `.lproj` codes with GlotPress. I think this only affects the Chinese variants so far, so I added a couple exceptions, as properly parsing language tags was not a trivial task.
- While developing this, I realized that not only Apple did `language-script`, but it also appended the region. Before this PR, we'd search the full tag (`zh-Hans-ES`) and then the language (`zh`), and none of them matched the right language. Now we try the full tag and start dropping components from the end until we find a match (`zh-Hans-ES`, `zh-Hans`, `zh`, `en`)
Testing:
Try creating a new site with your device set to different …
=> Improve support for Chinese languages in Languages helper

WordPress/Classes/ViewRelated/Menus/Views/Menu+ViewDesign.h, WordPress/Classes/ViewRelated/Menus/Views/Menu+ViewDesign.m, WordPress/Classes/ViewRelated/Menus/Views/MenuItem+ViewDesign.h, WordPress/Classes/ViewRelated/Menus/Views/MenuItem+ViewDesign.m, WordPress/Classes/ViewRelated/Menus/Views/MenuItemCheckButtonView.h, WordPress/Classes/ViewRelated/Menus/Views/MenuItemCheckButtonView.m, WordPress/Classes/ViewRelated/Menus/Views/MenuItemSourceHeaderView.h, WordPress/Classes/ViewRelated/Menus/Views/MenuItemSourceHeaderView.m, WordPress/Classes/ViewRelated/Menus/Views/MenuItemSourceTextBar.h, WordPress/Classes/ViewRelated/Menus/Views/MenuItemSourceTextBar.m, WordPress/WordPress.xcodeproj/project.pbxproj
Adding accessory views used in Menus when editing sources.
Adding a few of the accessory views used when editing a MenuItem. Also adds generic categories used 
throughout Menus for design consts and helpers with `Menu+ViewDesign` and `MenuItem+ViewDesign`.
Note: this is primarily a code review as the users of these views will UI include testing within their context.
=> Menus: Accessory views for editing MenuItem sources

WordPress/Classes/Services/PostService.h
Title has it.  This is a minor change that's needed for an upcoming [larger PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/5237) that I'm breaking up to make the review easier.
**To test:**
Simply build the code.
Verify the methods that use this block to make sure the new type is correct.
=> Specifies the post type better when retrieveing posts.

WordPress/Classes/Utility/Languages.swift, WordPress/Classes/ViewRelated/Blog/CreateNewBlog/CreateNewBlogViewController.m, WordPress/Classes/ViewRelated/Blog/LanguageViewController.swift, WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m, WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m, WordPress/WordPressTest/LanguagesTests.swift
I found the naming around the Language helpers way too ambiguous. Specially if we're already handling the different representations of languages between iOS and WordPress, if we have a `Language` type, it should be way more generic.
In this PR:
- I renamed `Languages` to `WordPressComLanguageDatabase`, which is closer to reality. This class is about WordPress.com supported languages.
- I renamed `Language` to `WordPressComLanguage`, as it's not a generic "language" but a representation of one in WordPress.com terms.
- I removed `sharedInstance`. Having a shared instance means that the list of languages is always in memory wether you need it or not. As languages are accessed very rarely, I'd rather load the database on demand.
- I make LanguageTagVariants a top level type. Even if it's …
=> Languages naming refactor

WordPress/Classes/ViewRelated/Menus/Views/MenusHeaderView.h, WordPress/Classes/ViewRelated/Menus/Views/MenusHeaderView.m, WordPress/Classes/ViewRelated/Menus/Views/MenusSelectionDetailView.h, WordPress/Classes/ViewRelated/Menus/Views/MenusSelectionDetailView.m, WordPress/Classes/ViewRelated/Menus/Views/MenusSelectionItem.h, WordPress/Classes/ViewRelated/Menus/Views/MenusSelectionItem.m, WordPress/Classes/ViewRelated/Menus/Views/MenusSelectionItemView.h, WordPress/Classes/ViewRelated/Menus/Views/MenusSelectionItemView.m, WordPress/Classes/ViewRelated/Menus/Views/MenusSelectionView.h, WordPress/Classes/ViewRelated/Menus/Views/MenusSelectionView.m, WordPress/WordPress.xcodeproj/project.pbxproj
Adding a collection of views responsible for handling the selection and display of Menus and Menu Locations in the header of the primary Menus view.
- `MenusHeaderView` is the top-most view encapsulating the use of two `MenusSelectionViews` to represent selection options for `Menus` and `MenuLocations` (areas).
- `MenusSelectionView` is a view encapsulating the use of `MenusSelectionItems` as a list of options.
- `MenusSelectionDetailView` is the detail view encapsulating labels displaying a currently selected `MenusSelectionItem` and a count of available `MenusSelectionItems`.
- `MenusSelectionItem` is an abstract object used for representing a `Menu` or `MenuLocation`.
Note: This is primarily a code review as testing in proper context will occur within a smaller PR merging the view …
=> Menus: Menu and Menu Location Header Selection Views

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Fixes a crash in a recent migration to Swift.  No versions of the app were published with the crash.
Props to @SergioEstevao for finding this issue.
=> Fixes a bug in a recent migration to Swift.

WordPress/WordPressShareExtension/ShareViewController.swift
Fixes #5283 
To test:
1. Launch the share extension.
2. Verify window title is present.
=> Adds "WordPress" to the title of the share extension UI.

WordPress/Classes/Models/BasePost.h, WordPress/Classes/Models/BasePost.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostSharingController.swift, WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes a crash that was caused by posts with no status set.  If you create a draft post and crash the app you can easily cause this scenario to trigger.
This PR improves `BasePost` by adding nullability info, meaning any Swift code using this class will know which properties, parameters and return values are optionals and which are not - thus forcing our Swift code to unwrap any optionals we may be dealing with.
At some point it'd be interesting to migrate `BasePost` to Swift and make sure a post cannot exist without a status being set, but for the time being this fix should do.
**Test 1:**
1. Create a post, write some content.
2. Crash the editor.
3. Relaunch the app and interact with the draft.  Make sure the post list does not crash.
**Test 2:**
1. Create a post, and save it as draft. …
=> Adds nullability info to BasePost.

Scripts/build.sh
We're installing `xcpretty-travis-formatter` but not really using it in our build script
If you look at the [build](https://travis-ci.org/wordpress-mobile/WordPress-iOS/builds/128018694), the build step is collapsed. The test step isn't but it's also cut before it's finished, which is a different issue.
=> Actually use xcpretty-travis-formatter

Scripts/build.sh
I refactored the build script a bit so it doesn't use `eval`, as it seems like that was causing the Travis log to be truncated when the build finished.
=> Fix truncated travis log

MIGRATIONS.md, WordPress/Classes/Models/Person.swift, WordPress/Classes/Networking/PeopleRemote.swift, WordPress/Classes/WordPress.xcdatamodeld/WordPress 49.xcdatamodel/contents
In this PR we're adding the `linkedUserID` field (returned by WordPress.com for Jetpack users, linked to a WordPress.com user).
This is required to properly handle the "Self hosted + Jetpack" scenario, in Issue #5175.
I'm adding the extra field to the Data Model Mark 49, since it is still in Develop, and didn't make it's way thru 6.2
=> Person: Adds linkedUserID

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/People/PeopleViewController.swift
Fixes #5289
To test:
1. Log into a Dotcom account
2. Open `My Sites` > `Site` > People
3. Press the home button
4. Kill the app
5. Relaunch the app
As a result, the User's list should be onscreen. And of course, the app shouldn't crash.
Thanks in advance James!
=> Fixing Restoration Crash

WordPress/Classes/Networking/PlansFeaturesRemote.swift, WordPress/Classes/Networking/PlansRemote.swift, WordPress/Classes/Utility/Languages.swift, WordPress/Classes/ViewRelated/Blog/LanguageViewController.swift, WordPress/WordPressTest/LanguagesTests.swift
To test: visit plans with a non-English language/region, make sure the content is localized.
I've included a few changes to `Languages` here to avoid postponing this PR even more (previously on Languages: #5246, #5251, #5252)
=> Plans: load localized copy from the API

WordPress/Classes/ViewRelated/NUX/NUXSubmitButton.swift, WordPress/Classes/ViewRelated/NUX/SigninSelfHostedViewController.swift
Fixes #5269 
Adds support for LoginFacade's wpcom delegate method, and SigninWPComSyncHandler. 
To test: 
Switch to the self-hosted controller and try to login to a wpcom site. 
Also try with credentials that have 2fa enabled.  Ensure that the 2fa screen is presented and you can login correctly. 
=> Signin: Handle a wpcom credentials and site from self-hosted vc.

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Fixes the build errors we're getting in release builds.
This is a temporary fix to make sure we can keep building the app.  A better fix will be provided by [this issue I opened](https://github.com/wordpress-mobile/WordPress-iOS/issues/5319).
Test 1:
Build the app in both debug and release make sure it works as expected.
Test 2:
Run the app, go to the list of posts / pages for a blog... interact... make sure it doesn't break.
=> Fixes some compilation errors in release builds.

WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #5285 
To test: Repeat the steps described in the issue. Confirm that stopping the scroll 
Needs review: @diegoreymendez, would you be so kind?
=> Reader: Improve scrolling experience. Keeps bars hidden when tapping to stop scroll

WordPress/Classes/Models/AccountSettings.swift, WordPress/Classes/Models/ManagedAccountSettings.swift, WordPress/Classes/Networking/AccountSettingsRemote.swift, WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift
Fixes #5185
To test:
1. Log into a WordPress.com account
2. Tap over `Me` > `Account Settings`
3. Edit your email
As a result, the *Account Settings* interface should display, immediately, the new email, along with the top notice (indicating that there's a pending change).
May i bother you with a review sir?
=> Account Settings: Improving Update Email UX

WordPress/Classes/Networking/ServiceRemoteXMLRPC.m
=> Check the arguments instead of the ivars on ServiceRemoteXMLRPC init

WordPress/Classes/Utility/WPImmuTableRows.swift
Fixes #5260 
To test:
- Go to Me -> App Settings
- Tap on Max Image Upload Size
- Check that cell is not selected.
=> Make cell selection style None.

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
#5321 updated WordPressCom-Analytics-iOS to 0.1.11, but didn't handle all the new stat values.
I've cherry-picked the A/B test one from #5226, but I'm not sure of the values for the People related stats, so I left those to be implemented.
@jleandroperez I'm merging this right away to fix the broken tests in develop, but please take a look at those People stats when you have a minute and handle them properly
=> Fix missing analytics

WordPress/Classes/Networking/BlogServiceRemoteREST.m, WordPress/Classes/ViewRelated/Blog/CreateNewBlog/CreateNewBlogViewController.m, WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m
Fixes #5347
To test:
1. If you are logged in, disconnect from WordPress.com
2. Select Create Account
3. Enter valid details to create a new account and submit them
As a result the app should no longer crash. Both, the Widget and Share Extension should be properly wired.
=> Fixing Crash after SignUp

WordPress/Classes/Services/SignupService.swift, WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift, WordPress/Classes/ViewRelated/NUX/SigninKeyboardResponder.swift, WordPress/Classes/ViewRelated/NUX/SigninWPComViewController.swift, WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
(also semicolons) 
No trailing space shall escape our linter's wrath. 
=> Removes whitespace flagged by the linter.

WordPress/Classes/ViewRelated/Plans/PurchaseButton.swift
This PR fixes an issue where the purchase button doesn't animate correctly when entering / exiting the selected state. Before (green highlight just to help debugging):
After:
The PR simply changes the animation to tell the button's superview to layout if necessary (which in turn will layout the button), instead of just the button itself. Prior to this, I tried calling `invalidatesIntrinsicContentSize`, but that didn't do the trick. Asking the superview to layout feels a little dirty perhaps, but I've seen other situations in the past where it's been necessary too. I spent a while trying different ways to resolve this issue, and eventually figured that spending much extra looking for another solution wasn't worth it for such a relatively small issue. 
=> PlanDetail: Fixes a visual glitch when PurchaseButton animates.

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
Fixes #5259.
Events can be no-op for certain trackers.  This is allowed and perfectly fine.  I've removed the log message that was coming up since it's not really adding useful information, and looked a bit like a warning / error to the reader.
Run the app and make sure the "No instructions, do nothing" log message doesn't come up anymore.
=> Removed an unnecessary log message.

WordPress/Classes/ViewRelated/Menus/MenuItemAbstractView.h, WordPress/Classes/ViewRelated/Menus/MenuItemAbstractView.m, WordPress/Classes/ViewRelated/Menus/MenuItemInsertionView.h, WordPress/Classes/ViewRelated/Menus/MenuItemInsertionView.m, WordPress/Classes/ViewRelated/Menus/MenuItemView.h, WordPress/Classes/ViewRelated/Menus/MenuItemView.m, WordPress/Classes/ViewRelated/Menus/MenuItemsVisualOrderingView.h, WordPress/Classes/ViewRelated/Menus/MenuItemsVisualOrderingView.m, WordPress/WordPress.xcodeproj/project.pbxproj
Adding a collection of views responsible for handling the display, selection, ordering, and editing of MenuItems.
These views are managed by the `MenuItemsViewController` currently in the Menus staging branch `feature/menus-views`. In order to break down the review, this PR is primarily a code review as testing will occur with the upcoming PR for the `MenuItemsViewController` code itself.
For context build and run `feature/menus-views`.
@diegoreymendez can I kindly request a code review from you fine sir? 🕵
=> Menus: MenuItems views for ordering and editing

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift
I only track views to the plans list and plans comparison. We'll add more purchase stats when it's actually implemented.
I've pointed the analytics pod to a branch so we can review it before bumping the version. Before merging, we'd need to release a new analytics version
Changes to the analytics pod are here: https://github.com/wordpress-mobile/WordPressCom-Analytics-iOS/compare/plans
=> Add analytics for Plans views

WordPress/Classes/Models/WPAccount.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerWPCom.m, WordPress/Classes/Utility/WPUserAgent.h, WordPress/Classes/Utility/WPUserAgent.m, WordPress/Classes/Utility/WPWebViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift, WordPress/WordPressApi/WordPressComApi.m, WordPress/WordPressTest/WPUserAgentTests.m
Refactor WPUserAgent to use static methods that are thread safe and invoked once.
To test: 
- Run unit tests see if they are correct.
- Run the app on the simulator using a Charles or similar program and see if the user agent is correct.
Needs review: @koke, @astralbodies and @aerych mind to have a look?
=> Refactor WPUserAgent

WordPress/Classes/ViewRelated/Menus/MenuItemsViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemsViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
Continuing with the Menus merge by adding the `MenuItemsViewController` and its `UIStackView` goodness. (Menus has been broken up over several PRs to lessen the load for review.)
The `MenuItemsViewController` is embedded as a child view controller within the primary `MenusViewController`, which is un-merged and seen in the staging branch `feature/menus-views`.
`MenuItemsViewController` is responsible for encapsulating the ordering and hierarchy of `MenuItems` built as `MenuItemViews` within a `UIStackView`. Ordering is handled via monitored touch events that check for the ability of a `MenuItem` to order itself under/over another `MenuItem` based on the ordering and hierarchy rules for WordPress Menus.
The view controller itself can be tested and run on a device/simulator via the staging …
=> Menus: MenuItems view controller for ordering and hierarchy editing.

MIGRATIONS.md, WordPress/Classes/Models/ManagedPerson+CoreDataProperties.swift, WordPress/Classes/Models/ManagedPerson.swift, WordPress/Classes/WordPress.xcdatamodeld/WordPress 49.xcdatamodel/contents, WordPress/WordPressTest/CoreDataMigrationTests.m
Closes #5322
1. If your cocoapods setup has (RVM?) please install `release/6.2` on your device, normally
2. If not, you may hack it, as i did:
2.1. In develop, temporarily set the data model to Mark 48
2.2. Comment [this line](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/BlogService.m#L593) so it doesn't crash.
2.3. Run the app, and log into your account
3. Install this branch on top
As a result, the app should not get logged out.
Please, run `CoreDataMigrationTests.testMigrate48to49DoesntLoosePersonEntities` and verify it doesn't break.
cc @aerych
=> Updates Person data-types

WordPress/Classes/Models/AbstractPost.h, WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/ViewRelated/Post/ConfigurablePostView.h, WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m, WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.m
Fixes #5396.
**To test:**
1. Build the code, make sure it doesn't fail.
2. Run the unit tests, make sure they don't fail.
3. Run the app, go to the list of posts for a blog and interact with it: create, edit, view, view stats, trash, restore posts.
=> PostCardTableViewCell and RestorePostTableViewCell now use Post objects.

WordPress/Classes/Networking/PostServiceRemoteREST.m
Fixes #5407 - Looks like a completion block was leftover from the NSURLSession updates.
To test:
1. Repeat the steps in the issue #5407 
2. Ensure a crash does not occur in any update method.
=> Issue/5407 - Resolve crash when updating a post.

WordPress/Classes/Networking/PlansFeaturesRemote.swift, WordPress/Classes/Networking/PlansRemote.swift, WordPress/Classes/Services/PlanService.swift
Refs #5245 
To test:
- Login with a WP.com account
- Access the option blog->plans and check if plans show correctly
- Put the app offline
- Go to plans again and see if the cache works.
=> Migrate Plans Remote to WordPressComRestApi

WordPress/Classes/Networking/TaxonomyServiceRemoteREST.h, WordPress/Classes/Networking/TaxonomyServiceRemoteREST.m, WordPress/Classes/Services/PostCategoryService.m, WordPress/Classes/Services/PostTagService.m, WordPress/WordPressTest/TaxonomyServiceRemoteRESTTests.m
Refs #5245 
To test:
- Login in the app using a WP.com account
- Create a new Post or Edit one.
- Go to Post Settings and change category and tags
- Add new categories
- Go to blog settings and check if list of categories shows correctly
=> Migrate TaxonomyService to use WordPressComRestAPI class.

WordPress/Classes/Models/Page.h, WordPress/Classes/Models/Post.h, WordPress/Classes/ViewRelated/Post/PostSharingController.swift
Adds nullability information to `Page` and `Post`.
**To test:**
1. Make sure the app builds.
2. Make sure the tests build and run properly.
3. Go to the list of posts for a blog and interact with posts: search, filter, create, edit, view, view stats, trash, restore, delete.
4. Go to the list of pages for a blog and interact with posts: search, filter, create, edit, view, view stats, trash, restore, delete.
=> Added nullability info to Page and Post.

WordPress/Classes/Networking/PushAuthenticationServiceRemote.swift, WordPress/Classes/Services/PushAuthenticationService.swift, WordPress/WordPressTest/PushAuthenticationServiceRemoteTests.swift, WordPress/WordPressTest/PushAuthenticationServiceTests.swift
Refs #5245 
To test:
- Try to log in using a WP.com account on the web that triggers a push authentication
- Check if all goes well
=> Migrate PushAuthentication Remote to WordPressComRestApi

WordPress/Classes/Services/GravatarService.swift, WordPress/Classes/Utility/WPTableImageSource.m
Refs #5245 
To test:
- Login with WP.com account
- Test if uploading a gravar image works correctly on the Me section
- Check if images on tables like comments, show correctly.
=> Use oAuthToken directly from the mainAccount instead of the restAPI.

WordPress/Classes/Services/SuggestionService.m
Refs #5245 
To test: 
- Login to a Wp.com account
- Check if user suggestions are working on Reply To Comments.
=> Migrate SuggestionService to WordPressComRestAPI

WordPress/Classes/Networking/WordPressComServiceRemote.h, WordPress/Classes/Networking/WordPressComServiceRemote.m, WordPress/Classes/Services/SignupService.swift, WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/Classes/ViewRelated/Blog/CreateNewBlog/CreateNewBlogViewController.m, WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressApi/WordPressComRestApi.swift, WordPress/WordPressTest/Test Data/WordPressComRestApiFailThrottled.json, WordPress/WordPressTest/WordPressComServiceRemoteRestTests.swift
Refs #5245 
To test:
- Create a new wp.com account, by testing success scenarios and failure scenarios:
- Repeated email
- Invalid username
- Invalid email
- Insecure password
- Create a new wp.com site,  by testing success scenarios and failure scenarios:
- Used site name
- Site name is too short
=> Make WordPressComServiceRemote use WordPressComRestApi

WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
Refs #5082 
The priority of the width constraint was set to 900, which is certainly a factor in cards showing up full width.  This PR sets the priority to 1000 to enforce the 600px iPad width.  Hopefully it resolves the bug but leaving it open for now just in case. 
To test: 
View the branch on an iPad. 
Confirm there are no breaking constraints. 
Confirm that reader cards are the correct width on the iPad.  This is a tough one to verify with any certainty as the bug was never reproducible on demand.
Needs review: @frosty would you please?
=> Reader: Makes the iPad card width constraint priority 1000.

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/ViewRelated/People/PeopleViewController.swift, WordPress/Classes/ViewRelated/People/PersonViewController.swift
This PR just defines the Stats to-be-wired in the People Management feature.
cc @oguzkocer @hypest
=> People Management Stats

WordPress/Classes/ViewRelated/Settings/SupportViewController.m
Fixes #5041. See issue for full details.
To test: View the Support screen with Helpshift both enabled and disabled. When disabled, the Forums should be referenced, and when enabled, 'contact us' should be referenced.
=> Issue/5041 Displays different Support footer text if Helpshift is enabled.

WordPress/Classes/Models/Blog.h, WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/Post.h, WordPress/Classes/Models/Post.m, WordPress/Classes/Models/PostCategory.h, WordPress/Classes/Models/PostCategory.m, WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressTest/PostTests.swift
Adds unit tests for the Post CoreData entity.
The reason why I'm introducing these unit tests (aside from them being a good thing to have), is that I'm planning to use them to check that the [upcoming migration](https://github.com/wordpress-mobile/WordPress-iOS/pull/5453) of `Post` to Swift does not introduce any regressions.
- Complete unit testing all public interfaces of `Post`.
- Modified `categoriesText` to always return the same result given the same input (by ordering the categories alphabetically).  Otherwise it would be impossible to properly test it.
- Added a few entity name constants, to cleanup the code a bit.
Test 1:
- Run the unit tests and make sure they all succeed.
Test 2:
- Run the app.
- Edit a post with categories.
- Go to the post settings.
- Make sure the post …
=> Adds unit tests to the Post CoreData entity.

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Fixes #5080. Please see that issue for full details.
When search was activated, but no search query was entered, we were filtering to show all 'hideable' blogs (this basically means any blogs that belong to the default dotcom account). I've changed this to now simply show all sites. I've also tidied up the predicates we already had a little.
To test:
* Log into a WordPress.com account, and also add a non-dotcom, non-Jetpack site. 
* From the site picker, tap the search icon
* Verify that the site appears in the site list before you enter a search term.
* Verify that you can still see the site when you enter a matching search term, too.
Needs review: @jleandroperez (It looks like you touched this code last, so would you mind doing the honours? Thanks!)
=> Issue/5080 BlogListViewController now shows all sites when search is activated

WordPress/Classes/Networking/PushAuthenticationServiceRemote.swift, WordPress/Classes/Services/PushAuthenticationService.swift, WordPress/WordPressApi/WordPressComRestApi.swift, WordPress/WordPressTest/PushAuthenticationServiceRemoteTests.swift, WordPress/WordPressTest/PushAuthenticationServiceTests.swift
Refs #5245 
To test:
- Try to log in using a WP.com account on the web that triggers a push authentication
- Check if all goes well
Needs review: @jleandroperez, this PR is exactly the same code as before but targeting the 6.3 release branch.
=> Migrate push notification service to nsurlsession

WordPress/Classes/Networking/NotificationsServiceRemote.swift, WordPress/Classes/System/Constants.h, WordPress/Classes/System/Constants.m, WordPress/WordPressApi/WordPressComApi.h, WordPress/WordPressApi/WordPressComApi.m
Refs #5245 
To test:
- Check if push notifications are getting to the app when events happen in the backend: new comment, new post, etc...
=> Move Push Notification constant out of WordPressComApi class.

.travis.yml, Rakefile
This should fix the issues with Travis caches and the new build system. From what I found, we're installing gems to a custom path (`vendor/bundle`). We provide this path on `bundle install`, but not on every other `bundle exec` call. This is usually fine as the config is cached in `.bundle/config`, but that's not added to git and wasn't included in the cache.
This PR adds that config file to the cache, and will run `bundle install` again if it's missing.
=> Fix travis cache on 6.3

WordPress/Classes/ViewRelated/Tools/SettingsMultiTextViewController.m
1. Launch WPiOS and log into a dotcom account
2. Open `Me` > `My Profile`
3. Tap over `About Me`
Note that the TextView shouldn't shrink anymore, as soon as the view appears (which is the behavior we have in `develop`
Plus: To prevent UI weirdness in the caller, the callback block will now be executed on `viewWillDisappear`.
=> Prevents settings multi shrink

WordPress/Classes/Networking/MediaServiceRemoteREST.m, WordPress/WordPressApi/WordPressComRestApi.swift
Refs #5245 
Because of the REST Api updates media progress reporting and media error reporting where not working correctly. When a media upload failed the editor still thought the media upload was still in progress and needed to be canceled explicitly.
This PR needs to be **tested on a device,** because the simulator has a bug that doesn't report progress correctly on streamed file uploads.
To test:
- Login with WP.com account
- Create a new Post on the editor
- Add a image or video
- Check if progress is being reported correctly.
- Add another media
- In the middle of the upload cut the network connection
- Check if failure report is done correctly and the top progress bar is updated correctly.
=> Fix media upload progress reporting.

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m
Fixes #1802
To test:
Testing on the simulator is the easiest. To enable notifications in the simulator, you'll have to apply this patch: https://cloudup.com/c7zsRYsoQ88
(Restart simulator contents and settings every time before each step)
1. Open app and notice there is no notification pop up
2. Open app, click info button on the top right, and select "Contact Us". A Notification pop up should appear.
3. Open app, log in to a WordPress.com site and after successful log in, the notification pop up will show.
4. Open app, log in to a self-hosted site. Connect Jetpack and the notification pop up will show.
=> Don't show notification pop up immediately after first open

WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/WPPickerView.m
Fixes #5473 
To test:
- Open the app on a iPad
- Create or edit a post
- Go to Post Settings
- Edit the publish date of the post
- Check if the layout of the picker and toolbar are done correctly on multiple orientations and multitasking modes.
=> Fix layout of date picker for the iPad.

WordPress/Classes/ViewRelated/NUX/SigninErrorViewController.swift, WordPress/Classes/ViewRelated/NUX/WPWalkthroughOverlayView.m
Fixes #5421
I've updated both the old and new login flow errors so that they'll announce their titles (and that a layout change has taken place) if Voiceover is active. So, if you enter incorrect login details, the error overlay should appear and Voiceover should read and focus the "Sorry, we can't log you in" label. 
Additionally, I've told UIAccessibility to treat `WPWalkthroughOverlayView` as a modal view, so that you're no longer to tap through to elements underneath it.
To test:
Please see original issue for testing steps. Make sure you test each of the following scenarios for displaying the error:
* New and old login flows
* With the keyboard visible, select the Done button
* With the keyboard visible, select the Sign In button
* With the keyboard hidden, select the Sign In button …
=> Issue/5421 Login errors now announce their titles when VoiceOver is active

WordPress/Classes/ViewRelated/System/Search/WPSearchControllerConfigurator.h, WordPress/Classes/ViewRelated/System/Search/WPSearchControllerConfigurator.m
Fixes #5481 
To test:
- Start the app on an iPad device or simulator
- Go to Blog List and/or Post List
- Tap on the Search icon
- Activate the multi-task mode on the iPad
- Test on all multitask mode and  rotations to see if the search bar is kept inside the screen.
- Run the same tests on a iPhone simulator or device
=> Fix search controller layout on ipad compact mode

WordPress/Classes/Services/LoginFacade.m
Based on an increase in stats seen for the `WPAnalyticsStatLoginFailed` "**Failed Login**" stat, it appears there was a duplicate call leftover from a recent refactor in https://github.com/wordpress-mobile/WordPress-iOS/commit/5cf56bba58ab
Needs review: @SergioEstevao, can you take a quick peak? It looks like your changes in https://github.com/wordpress-mobile/WordPress-iOS/commit/5cf56bba58ab missed a deletion.
Thanks for spotting @maxme  🕵
=> Login: Removing duplicate WPAnalyticsStatLoginFailed stat

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Fixes #5223. 
To test:
* Tap a tag in the Reader to preview it. As the view controller is pushed on, you shouldn't see the title being truncated.
Before:
After:
=> Issue/5223: Fixes issue with ellipsis in title of tag previews in Reader

WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
Fixes #4683. I've changed tagline from using a `SettingsMultiTextViewController` to using a `SettingsTextViewController`.
To test: As per the original issue, edit a site's tagline and ensure that you can't press return to enter newlines.
=> Issue/4683 Site Settings tagline is now a single line field

WordPress/Classes/Models/Comment.h, WordPress/Classes/Models/Comment.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
Fixes #5015. I've replaced all instances of 'disapprove' with 'unapprove'.
Tagging you because it affects notifications :) Thanks!
=> Issue/5015: Replaces all instances of 'disapprove' with 'unapprove'.

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
Fixes #5434 
Removing the stat `WPAnalyticsStatMenusUpdatedMenuName` altogether as it can't be easily tracked accurately. Will reimplement if a desire to track this change emerges or Menus implementation changes to support it.
Test:
- Build the branch after a pod update, without errors.
Needs review: @jleandroperez can you take a quick peak?
=> Menus: Cleanup removed menus stat

WordPress/Classes/ViewRelated/Notifications/Tools/NotificationMediaDownloader.swift
Refs #5245
To test:
- Login with a WP.com account in the app
- Go to the Notifications Tab
- Tap on a notification
- Check if the images are downloaded properly.
=> Migrate code to use NSURLSession based object.

WordPress/Classes/Services/MediaService.m, WordPress/Classes/Utility/WPError.m, WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPressApi/WordPressComRestApi.swift, WordPress/WordPressTest/Test Data/WordPressComRestApiMultipleErrors.json, WordPress/WordPressTest/WordPressAPI/WordPressComRestApiTests.swift
Refs #5245 
Test 1:
- Login to WP.com account
- Go to blog list
- Go to server and invalidate password and token for that user
- Try to do a refresh and check if the correct error message/dialog shows up
Test 2:
- Login with WP.com account
- Reduce the maximum file size or disk quota for media for that user on the server to 1Mb
- Try to upload a media file and see if a proper error message shows up.
=> Update and fix error handling for new api class

WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift
Fixes #5487
To test:
View the sharing button management view controller on an iPad Pro and confirm that the rows are correctly laid out. 
=> Sharing: Fixes cell margins in sharing button mgt vc.

WordPress/Classes/Networking/DomainsServiceRemote.swift, WordPress/Classes/Services/DomainsService.swift, WordPress/WordPressTest/DomainsServiceTests.swift
Refs #5245 
To test:
- Login with a WP.com account.
- Test domain pages on Blog->Domains
- Run unit tests
=> Migrate Domain Services to WordPressComRestApi.

Podfile, Podfile.lock
Fixes #5500 
Updating the Lookback pod to `1.3.0` to try and resolve launch crashes seen by @rachelmcr.
Merging this into the 6.3 branch so the upcoming internal builds include this update for testing.
To test:
- Checkout and update the pods for this branch.
- Test build the WordPress Internal target to your device.
- Ensure no build errors or warnings occur.
- Run the Lookback app on your Mac.
- Ensure Lookback runs as expected.
=> Lookback: Update 6.3 Podfile to Lookback 1.3.0

WordPress/Classes/Networking/PeopleRemote.swift, WordPress/Classes/Services/PeopleService.swift, WordPress/Classes/ViewRelated/People/People.storyboard, WordPress/Classes/ViewRelated/People/PeopleViewController.swift
Closes #5502
1. Locally [hack this spot](https://github.com/wordpress-mobile/WordPress-iOS/pull/5508/files#diff-5e2d6556d819df0de802fec9c853008aR19), so that the pageSize is set to 1.
2. Open **My Sites** > **Site A** > **People**
3. Try scrolling all the way down. Switch to Followers, and please, verify it works as well.
Note: Please, make sure that **Site A** has more than 1 User / Follower.
Follower's API lacks a sorting order parameter. I'll file another issue to deal with that, once the API has been enhanced.
--
Sergio, may i bother you with a (hopefully fun) PR?
=> People Management: Infinite Scroll

WordPress/Classes/ViewRelated/Reader/Reader.storyboard, WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #5390 
To test: Check portrait oriented featured images in the reader detail.  The height of the images should be correctly constrained to respect the w/h ratio.
=> Reader: reconfigures featured image height constraint.

Podfile, Podfile.lock, WordPress/WordPress.xcodeproj/project.pbxproj
Integrated the latest editor version (1.7), fixing an important bug when pasting links.
While this fix allows links to be pasted, they're currently pasted as simple text.  I've created [a new issue](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/829) to implement this.
More information [here](https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/825).
To test:
Paste an URL copies from Safari.
=> Integrated Editor v1.6.2.

WordPress/Classes/ViewRelated/Blog/SharingAccountViewController.swift
Fixes #5543
To test:
1. Open the app
2. Go to a site's dashboard and select Sharing
3. Under Connections select a service to connect
4. Select Connect (or Connect Another Account if you already have a connection)
5. Log in to that sharing service and accept the connection to WordPress
6. On the next screen in the app, confirm that the navigation header and "Connecting" use the sharing service label (e.g. `Google+`) instead of serviceID (e.g. `google_plus`)
=> Sharing: Switch Publicize service from serviceID to label

WordPress/Classes/Services/MenusService.m
Quick rewrite of setting up the `MenuItemRemote` objects for pushing to the remote in the correct order. Previously this was written in a way that lost any ordering for items that were children of another item.
To test:
1. Open Menus for a .com site with admin rights.
2. Reorder items that are children of another item or create multiple children if needed. (For example, reorder items above as About, Contact, Home.)
3. Save the changes.
4. Check the site that the ordering is correctly updated for the menu.
Needs review: @jleandroperez would you mind reviewing fine sir? 🎩
=> Menus: Resolve ordering issue when updating Menu items.

WordPress/Classes/Utility/NoticeAnimator.swift
NoticeView's *Y Position* was being reset each time the view was laid out. In a specific scenario, this was causing a weird UI glitch (Detailed below).
1. Log into a dotcom account using **Device A**
2. Open **Me** > **Account Settings** > **Email**
3. Change your Email address
4.The Notice should show up on top
5 Hit back. You should see the **Me** screen
6. Using **Device B** (or just a web browser!) revert the email change
7. On **Device A** open again the **Account Settings** screen
As a result, the Notice should animate in / out, without any weird side effect.
=> NoticeAnimator: Preserving OriginY on Layout

WordPress/WordPressShareExtension/NSExtensionContext+Extensions.swift, WordPress/WordPressShareExtension/ShareViewController.swift, WordPress/WordPressShareExtension/String+Extensions.swift
- `ShareViewController` code has been split in different sections, by means of private extensions.
- `NSExtensionContext` Extension has been generalized, internally, and a new helper to extract images has been added.
- String-specific helper moved to its own extension
This PR doesn't add extra code, it's just a reorganization. This came as a spin off while working on #4910, and thought it'd be healthier to ship it on its own.
Please, verify that the extension works as expected (sanity check).
=> Share Extension: Minor Cleanup

WordPress/Classes/WordPress.xcdatamodeld/WordPress 50.xcdatamodel/contents
The Domains entity was omitted from the v 50 core data revision. Best guess is it was added to revision 49 after version 50 was created.  This PR restores the Domains entity to revision 50. 
=> Restores the Domains entity to the version 50 data model.

WordPress/Classes/ViewRelated/Pages/PageListViewController.swift, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Fixes #5557 
To test:
1. Open the app
2. Open a site's Page list
3. In the Page filter, select Scheduled
4. Make sure the page list is empty (publish, move to draft, or trash any scheduled pages so the list is empty)
5. Check to make sure the call to action button says "Edit Drafts" instead of "Start a Page"
6. Tap the "Edit Drafts" button
7. Make sure you end up on the Drafts page list
=> Fix button title for scheduled page list

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
We've had a couple of crashes where the cause was reported to be `UITableView internal bug: unable to generate a new section map with old section count: 1 and new section count: 0'`. The exact cause isn't known but it appears that the apps is trying to reload rows in a section that no longer exists.  Rather than reloading visible rows, we can just reload the UITableView to avoid the crash. 
Needs review: @sendhil 
Sample stack trace:
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UITableView internal bug: unable to generate a new section map with old section count: 1 and new section count: 0'
> Last Exception Backtrace:
0   CoreFoundation                       0x0000000182456db0 __exceptionPreprocess + 124
1   libobjc.A.dylib …
=> Post List: Reload tableview instead of visible rows.

WordPress/Classes/ViewRelated/Tools/SettingsMultiTextViewController.m
Closes #5526
To test:
2. Open `Me` > `My Profile` > `About`
3. Begin typing a long text.
Note: Please, use an iPhone 6 device (or simulator). This glitch was caused by the initial `View`'s width getting resized, and the textView not getting properly expanded.
=> SettingsMultiTextViewController: Correcting width when needed

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
This PR allows user to edit post settings while media uploads are being done. This will allow user to be more productive while the wait for media uploads to finish.
To test:
- Start or edit a post
- Add media to it
- Click on the settings icon,
- Edit settings
- Close settings screen
- See if image upload continues normally
- Do the same but spend enough time on settings to allow the upload to finish while on settings
- Go back to the editor and check if everything went ok.
=> Allow edit of post setting while images are being uploaded.

WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Closes #5522 
To test: Check that draft posts are sorted by date last modified, and show the correct date when compared with wp-admin and calypso.
Confirm that published, scheduled, and trashed posts continue to be sorted by date published. 
=> Posts: Sort drafts by last modified date.

WordPress/Classes/ViewRelated/Tools/SettingsMultiTextViewController.m
Backporting PR #5531 for Release 6.3
2. Open Me > My Profile > About
3. Begin typing a long text.
Note: Please, use an iPhone 6 device (or simulator). This glitch was caused by the initial View's width getting resized, and the textView not getting properly expanded.
=> SettingsMultiTextViewController: Correcting width when needed - Release 6.3 Backport

WordPress/Classes/ViewRelated/Pages/EditPageViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
This PR fixs the editing of pages that was crashing because of assert for Post type on WPPostViewController.
To test:
- Go to Blog->Pages
- Edit a page
- Save a page
- Check if no crash happens
Needs review: @diegoreymendez do you mind have a look on this?
=> Fix editing of pages

WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #5570. 
iOS 10 was seeing a crash on launch. Checking the console, I found:
```
Jan  1 01:02:34 Jamess-iPad WordPress(Foundation)[484] <Notice>: *** Assertion failure in -[WPTabBarController lastTabBarButtonFrame], /Users/sendhil/Projects/WordPress/WordPress-Release/WordPress/Classes/ViewRelated/System/WPTabBarController.m:644
```
I then added some extra debugging to `[WPTabBarController lastTabBarButtonFrame]` to see what was going on. On both iOS 9 and iOS 10, this method is called twice when the tab bar is laying out its views (via `viewDidLayoutSubviews`). 
On iOS 9, the frames of the tab bar's subviews are correct both times. 
On iOS 10, the frames have a zero origin the first time round. This means that the method can't find an appropriate frame for the notifications cell, …
=> Issue/5570 – Fixes iOS 10 crash on launch

WordPress/Classes/Services/MenusService.m, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemEditingViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemEditingViewController.m, WordPress/Classes/ViewRelated/Menus/MenusViewController.h, WordPress/Classes/ViewRelated/Menus/MenusViewController.m
This PR resolves and improves a couple of warnings from the static analyzer for Menus.
To test:
1. Select a .com site with admin rights.
2. Open Menus from the blog details.
3. Open the MenuItem editing view by selecting an item in the list of items.
4. Ensure the modal editing controller presents.
5. Run the static analyzer on the project and ensure no warnings present.
6. 🏁 
Needs review: @nheagy can I bother you with a review?
=> Menus: Resolving Static Analysis Warnings

MIGRATIONS.md, WordPress/Classes/Models/ManagedPerson+CoreDataProperties.swift, WordPress/Classes/Models/ManagedPerson.swift, WordPress/Classes/Models/Person.swift, WordPress/Classes/Services/PeopleService.swift, WordPress/Classes/ViewRelated/People/PeopleViewController.swift, WordPress/Classes/WordPress.xcdatamodeld/WordPress 50.xcdatamodel/contents
This PR doesn't really add new functionality. Several minor changes were introduced, as a requirement to implement the  `Site Viewers` feature.
- `Person` Core Data entity looses the `isFollower` attribute, and gains the `kind` attribute
- PeopleService / Person / PeopleViewController got updated accordingly.
Please, log into a WordPress.com and:
- Open `My Sites` > `Site`
- Verify that the People tab works as expected (view Users / Followers, send an invitation).
@aerych may i bother you with a (hopefully brief) PR?
Ref. #5585
=> People Management: Viewers Data Model

WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m, WordPress/WordPressApi/WordPressOrgXMLRPCApi.swift
Refs #5245 
To test:
- Add a self-hosted site to the app
- Go to Blog -> Settings
- Try to change the password to a invalid one.
- Check if error message shows up
- Go to the web and change the password for the site
- Now in the app try to update the password to the new one.
- Check if success message shows up.
=> Check self-hosted credentials using the WordPressOrgXMLRPCApi class.

WordPress/Classes/ViewRelated/Reader/Reader.storyboard
Fixes a regression I introduced in #5524 when I changed some constraints to not be relative to the margin. Its uncommon that we respect margins, and instead the norm is to set leading and trailing constraints to be relative to the containing view so I fixed something that *looked* wrong vs something that was wrong, and then missed the regression when testing. :(
This PR reverts the change. 
To test:  Launch the iPad simulator and confirm that content respects readable margins and is not full width.
Needs review: @kurzee would you please?
=> Reader: Fixes broken margins in the reader detail.

WordPress/Classes/System/WordPressAppDelegate.m
Refs #5245 
To test:
- Sign in the app with a WP.com account.
- Log out
- Sign in with another account.
=> Remove Single Sign On code.

Podfile, Podfile.lock, WordPress/Classes/Networking/MediaServiceRemoteREST.m, WordPress/Classes/Services/BlogService.m, WordPress/Classes/Services/MediaService.m, WordPress/Classes/Services/ReaderTopicService.m, WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Refs #5245 
Final step to remove WordPressApi pod from the app
To test:
- Compile the app and check if no warning related to WordPressApi show
- Test the app with a WP.com and  self-hosted site.
=> Remove WordPressApi pod.

WordPress/Classes/ViewRelated/Reader/WPImageViewController.m, WordPress/Classes/ViewRelated/System/FlingableViewHandler.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Adds a 'fling' to dismiss gesture to `WPImageViewController`, like Slack and Tweetbot. 
* View an image full screen anywhere that `WPImageViewController` is used. Images in the Reader are probably easiest.
* Check that you can still zoom and pan the image. 
* When you're zoomed out you should be able to drag the image. If you fling it hard enough, it'll fly offscreen and be dismissed.
* Check when the app is viewed at different sizes. I changed the velocity slightly at regular vs compact sizes, as it felt a little fast when viewed Regular.
* Let me know if you think it 'feels' right! Compare to Slack and Tweetbot perhaps.
=> Added a 'fling' gesture to WPImageViewController.

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostPreviewViewController.h, WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.h, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #5377
This PR makes the status bar visible again while editing a post. The gains of extra space or small compared to the ability of seeing the status bar information.
It also fixes the bug above when the status has special states like hotspot or in call connections.
To test:
- Start or Edit an existing post
- Check if the status is present
- Click on post settings and post preview and check if all works correctly.
- Check the same on pages
- Check the same using the legacy editor.
@bummytime do you want also to have look?
=> Stop hiding the status bar on post and page edit.

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Fixes #5082
Attempts to fix our misbehaving card layout by using an alternate cell type on the iPad when not in a window. When returning to a window the tableview is reloaded which switches cells to the correct card style. 
To test:
Repeat the steps outlined in #5082 to trigger the error.
Confirm that cells are rendered with the correct width.
Confirm that none of the alternate cells are shown. 
Needs review: @kurzee, Once more unto the breach! Cry havoc, etc. etc.
=> Reader: Dequeue alternate cells when not in a window to avoid layout gllitch

WordPress/Classes/Models/Person.swift
🚔 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚔
Fixes trailing whitespace violation in `Person.swift`.
=> Person: Trailing whitespace violation 🚔

.travis.yml, Gemfile.lock
Fixes `rake`-related build errors that have been appearing today on `develop` (and earlier on other branches)
To test: if the Travis build below is happy, then this should be a success.
Needs review: @astralbodies you know rake/gem/builder stuff right?
=> Adding rake install to travis config

WordPress/Classes/Utility/Logging/WPLogger.m
Not sure how it really broke - maybe Crashlytics changed slightly causing the log warnings to show up. This PR changes our initialization slightly to not add the custom Crashlytics logger to our CocoaLumberjack setup when its not an app store build.
**To test:**
1. Launch the app in the simulator or on a device.
2. Verify the console does not mention any errors about CLLog.
=> Does not add the Crashlytics logger for Debug & Internal builds

WordPress/Classes/ViewRelated/System/WPTabBarController.m
Closes #5629 
*To test:*
1. Launch in physical iPad with external keyboard or simulator with external keyboard turned on under Hardware > Keyboard menu.
2. Hold down the Command key to see the helper window of keyboard shortcuts.
3. Try each of the shortcuts (only works with real device because of simulator conflicts).
4. Make sure keyboard shortcuts don't affect things when a modal window is up (like a new post window).
Needs review: @frosty, @diegoreymendez
=> Adds external keyboard shortcuts for access to the tabs

WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/Reader/WPImageViewController.m
Whilst updating our use of modal view controllers, I found a couple of small issues around featured images, which I've fixed here.
* When previewing a featured image, the image was being overlapped by the navigation bar. I've disabled extended layout so this no longer happens.
* The featured image preview in post settings was pixellated. It now takes into account the screen scale so should be retina quality.
* Create a new post
* Open the Post Settings
* Tap Featured Image and add a new featured image.
* Wait for it to upload and the full thumbnail to be generated.
* Check that the thumbnail isn't pixellated.
* Tap the thumbnail to view the image.
* Check that the image fits correctly in the area below the navigation bar, and check that you can zoom and pan around it correctly.
* Check …
=> Featured image improvements

WordPress/Classes/ViewRelated/People/PeopleViewController.swift, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/Categories/PostCategoriesViewController.m, WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m, WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m, WordPress/Classes/ViewRelated/System/ForcePopoverPresentationPopoverControllerDelegate.swift, WordPress/Classes/ViewRelated/System/ForcePopoverPresenter.swift, WordPress/Classes/ViewRelated/Tools/SettingsSelectionViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
Refs #5599. 
This picks off some of the low-hanging fruit listed in the above issue around some more appropriate uses of modals and popovers on iPad.
Check the following:
* People and Posts filter dropdowns from the navigation bar are popovers on all devices (and no longer include a navigation bar – fixes #3748).
* Adding a category (either from Post Settings > Categories or from Site Settings > Default Category) should now present a form sheet modal on iPad (full screen on phone)
* Adding a featured image and a location to a post (in post settings) should now use form sheet modals on iPad.
=> Issue/5599 Modal and popover presentation updates

WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.h, WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Whilst looking through our uses of modals in the app, I realised that `promptForPassword()` in `AbstractPostListViewController` wasn't working correctly. 
I think it must've been written before `UIAlertController`, as it attempted to present an alert and them immediately afterwards present a view controller. Since view-controller based alerts, the alert is already being displayed and the view controller presentation fails.
I've updated the method to present the site settings VC once the alert has been dismissed.
To trigger the alert, I faked it by adding the following into the end of the `success` block of `syncHelper(_:syncContentWithUserInteraction:success:failure:)`:
```
let error = NSError(domain: WPXMLRPCFaultErrorDomain, code: strongSelf.dynamicType.HTTPErrorCodeForbidden, userInfo: …
```
=> Fixes Site Settings modal in AbstractPostListViewController

MIGRATIONS.md, WordPress/Classes/Models/ManagedPerson+CoreDataProperties.swift, WordPress/Classes/Services/PeopleService.swift, WordPress/Classes/ViewRelated/People/PeopleViewController.swift, WordPress/Classes/WordPress.xcdatamodeld/WordPress 50.xcdatamodel/contents
- Updating Data Model Mark 50 (yet again)
- Person gets a new creationDate attribute
- Followers are now sorted by this attribute
1. Pick a blog that has a *LOT* of followers (such as automattic.com), and make sure you're an admin
2. Log into your dotcom acocunt
3. Open `My Sites` > `Site` > `People`
4. Tap over the navbar title and select `Followers`
5. Begin scrolling down
Please, note that newly added Followers will always be appended to the list. (Before this patch, since the Sort was being applied over the name, scrolling downwards didn't always append new pages).
Eric, may i bother you with (yet another) review?
cc @oguzkocer / @hypest ("Easiest Hack Ever")
=> People Management: Followers Order

WordPress/Classes/Utility/WPTableViewHandler.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+RowActions.swift, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderSearchSuggestionsViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
This PR adds nullability specifiers to the WPTableViewHandler's delegate. I've hit few annoying issues while reimplementing the Notifications Stack in Swift... and this brings a bit of order back to the universe.
Please, run a smoke test over the Reader (Stream / Search Suggestions / Followed Sites), and Notifications (Swipe over any Comment-Y notification and verify that the actions do show up).
Eric, may i bother you with a violent review?
**Thank you!!!**
=> WPTableViewHandler nullability specifiers

WordPress/Classes/ViewRelated/Menus/MenusViewController.m
A `Menu` object was being strongly referenced during the processing of default `MenuItems` for a site. This `Menu` object should instead be weakly referenced as the user may leave the Menus view before this process finishes and the Menu object, while valid in memory, is no longer a valid CoreData object, causing a crash.
To test:
- I couldn't actually reproduce this, @jleandroperez can you retest as when you found it?
- Regardless, this should be fixed by casting a `weak` reference.
Needs review: @jleandroperez can you take a peak, whenever you have a chance? No rush, thanks for finding this one!
=> Menus: Fix memory retain issue for default menus

WordPress/Classes/Utility/FeatureFlag.swift, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Removes the Domains item from the blog detail menu. I'm leaving the rest of the code in for now as we may want to re-introduce it later.
=> BlogDetailsViewController: Removed Domains menu item.

WordPress/Classes/ViewRelated/Reader/CommentContentView.m, WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes #5650.  
To test:
Repeat the following tests with a list of comments of various size containing links, images, and/or other embedded content.   Note that it is expected to see some layout artifacts in the iOS simulator, but not on a device.
Scenario 1:  iPhone
Load a comment list. Scroll the list and confirm that comments are rendered correctly.
Change device orientation. Confirm that comments are correctly resized and render correctly.
Scenario 2: iPad
Load a comment list. Scroll the list and confirm that comments are rendered correctly.
Change device orientation. Confirm that comments are correctly resized and render correctly.
Scenario 3: iPad
Load a comment list. Scroll the list and confirm that comments are rendered correctly.
Lock the screen then unlock the screen. 
Confirm …
=> Reader: Fixes comment UI glitch after locking/unlocking screen

WordPress/Classes/Services/Store.swift
This PR should _actually_ remove the purchase buttons from Plans, like, for real this time.
Please ensure you test against sites that are already on both Free and Premium plans. I think we might have missed this last time because we may have only checked on Premium (which wouldn't show purchase buttons anyway).
=> Disables payments through StoreKit.

Podfile, Podfile.lock, WordPress/Classes/Models/Media.h, WordPress/Classes/Models/Media.m, WordPress/Classes/Services/MediaService.h, WordPress/Classes/Services/MediaService.m, WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
This PR updates the WPMediaPicker to version 0.10.0.
As a consequence the MediaLibrary data source needed to be update in order to report correct media count depending of the filter that are active on the Media Picker.
To test:
- Start a new post.
- Tap to add new media.
- Tap on the collection/group selector on the media picker
- Check if the count for media on the Media Library is updated correctly with the number element inside
- Cancel the picker
- Go to Post settings and tap on Featured Image
- Check if the picker here shows the correct count for the Media Library, it should ignore any videos on the library.
=> Update the WPMediaPicker to version 0.10.0

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
The new Search feature was never intended to support pull-to-refresh but somehow pull-to-refresh was left enabled when the feature merged.  This PR disables it.
To test:
Perform a search in the reader. 
Try to perform a pull to refresh action. 
The refresh control should not appear and a new sync should not occur.
Load any other topic in the reader.
Confirm that pull to refresh continues to function.
=> Reader: Disable refresh for search topics.

WordPress/Classes/ViewRelated/Reader/ReaderSearchSuggestionsViewController.swift
Fixes #5679 
To test: 
Prepare by searching for at least five different topics beginning with the same letter. 
For each platform, confirm that the clear button is always visible.
=> Reader: Show fewer suggestions for smaller heights.

WordPress/Classes/ViewRelated/Reader/ReaderBlockedSiteCell.xib, WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.xib, WordPress/Classes/ViewRelated/Reader/ReaderGapMarkerCell.xib, WordPress/Classes/ViewRelated/Reader/ReaderListStreamHeader.xib, WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib, WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.xib
Fixes #5660 
It looks like the culprit was a required constraint for our iPad width implemented in a few different xibs (cards and headers). This PR lowers the priority so we shouldn't see it breaking anymore.
To test:
Repeat the steps described in the issue and confirm that there are no longer warnings about breaking constraints. 
=> Reader: Fixes breaking constraints when multitasking on the iPad.

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
Update the media library data source to use a NSFetchedResultsController.
This allows improved changed notification and also allow to show media immediately instead of waiting for the server sync.
To test:
- Tap on add media
- Select the media library
- If it's the first access it should sync from the server and then show the results
- If not the first access it should show results immediately and eventually update from server results.
- On the media library you also need to test the adding a new image using the camera. 
=> Update Media Library Data Source

WordPress/Classes/ViewRelated/People/PeopleViewController.swift, WordPress/Classes/ViewRelated/People/PersonViewController.swift
Fixes #5691
To test:
2. Open a blog in which you're an admin (**My Sites** >> **Testing Site**)
3. Open the `People` section
Please, verify that the **Followers** + **Viewers** don't display **First Name** + **Last Name** anymore.
Note that **Viewers** is only available for private sites.
Needs review: @kurzee  
Thanks in advance Brent!!
=> People: Removes Followers + Viewers Fullname

WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m, WordPress/Classes/ViewRelated/Post/PostListViewController.swift, WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.h, WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.m
This PR fixes the loading of images on PostListViewController when the site is private
To test:
- Login with a private WP.com site
- Access that site
- Open the post list
- Check if the image load correctly.
=> Show images from private sites

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Extensions.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Internal.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
We're slowly rewriting the entire Notifications stack in Swift, and relying on Swift Extensions to just... port code over (instead of a full massive rewrite).
This time we're moving over the NoResults handling code.
Outlining below few testing scenarios, thanks!!
Reference #5613
1. Log into a dotcom account that has no notifications
Verify that the legend `No notifications yet` shows up onscreen, and the Filters segmented control isn't visible.
1. Log into a dotcom account that has no notifications
3. Receive a notification
Please, verify that the Empty Notifications legend is removed, and the Filters shows up.
1. Fresh install the app
2. Log into a dotcom account, with a non-empty notifications list
3. Open the …
=> Notifications + Swift Mk 4: NoResults View

WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift
Fixes #5726 
See original issue for description of issue. I've fixed the issue by deselecting the row when the modal is presented, as there's no simple way to tell when the modal is dismissed (`viewWill/DidAppear` doesn't get called) – we'd have to implement a delegate or somesuch which seems like overkill.
=> Issue/5726: Plan list cells not deselecting after modal dismiss

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m, WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Blog.swift, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #5677. I've added search to the blog selector modal in the editor, and updated the style of the tableview to match the recently-updated My Sites list.
To test:
* Open the editor, and open the blog selector.
* Please ensure you test the top and bottom tableview scroll indicator and content insets when showing / hiding the keyboard and activating / cancelling search on both iPhone and iPad, in different 
orientations and multitasking configurations.
=> Issue/5677 Add search to blog selector

WordPress/Classes/System/WordPressAppDelegate.m
Parallel to https://github.com/wordpress-mobile/WordPress-iOS/pull/5736 just targetting `release/6.3.1`
=> Disables state restoration after updates.

WordPress/Classes/Models/ReaderSiteTopic.swift
Fixes #5730 
To test:
Browse posts for a tag. 
Tap the header of one of the posts in the list to preview that site. 
Tap the following button in the site header to follow and unfollow the site. Confirm there are no crashes. 
In the new reader Menu, ap the Manage button next to Followed Sites.
Tap on one of the sites in the list to preview it. 
Unfollow and refollow the site. Confirm their are no crashes. 
Back on the Manage Sites list, follow a wpcom site and a remote feed via the search bar. 
Confirm they are followed correctly and there are no crashes. 
Swipe to delete the two sites you just added. 
Confirm they are removed correctly and there are no crashes. 
Needs review: @nheagy would you mind taking this one?
=> Reader: Check siteID to determine if topic is external.

WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
Fixes #5708 
To test: 
Open the reader search screen. 
Try to search for a space, or multiple spaces.  
Confirm a search is not performed when the search phrase is just spaces and there is no crash.
Needs review: @kurzee would you sir?
=> Reader: Confirm the search phrase is not empty

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.m, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m, WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard, WordPress/Classes/ViewRelated/Notifications/Tools/IntrinsicTableView.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockImageTableViewCell.swift, WordPress/WordPress.xcodeproj/project.pbxproj
This PR addresses technical debt in NotificationDetailsViewController. Specifically:
- UIStackView has been implemented, to easily handle scenarios in which ReplyTextView has to be attached.
- The new leading/trailing Anchor's API has been wired
- Since i was around... cleaned up old Storyboard Segues that weren't used, and shifted over to code for transitions that don't have, as a destination, a VC that lives within Notifications.storyboard.
- Implemented IntrinsicTableView, to simplify "Vertically Centered" layouts, such as the ones used by Badge Notifications
Ref. #5613
--
2. Open the Notifications List, and press over an automattcher notification
Please, verify that the Reader shows up onscreen
1. Open a "Mention in a comment notification"
2. Verify that …
=> NotificationDetails: StackViews

WordPress/Classes/Extensions/NSFetchedResultsController+Helpers.swift, WordPress/Classes/System/WordPress-Bridging-Header.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Extensions.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Internal.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.h, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m, WordPress/Classes/ViewRelated/System/WPTabBarController.m
This PR adds no new functionality. We'll gradually migrate all of the Notifications-Y code over to Swift.
Once it's ready, we'll address code improvements / technical debt.
Reference #5613
--
1. Receive a regular Notification (you may click like over any of your own posts)
2. Launch the app and open the Notifications tab
3. Press over the new notification row
As a result, the notification details should be onscreen.
1. Receive a matcher notification (mention on a post)
2. Launch the app and open the Notifications tab
3. Press over the Matcher notification
As a result, the reader should be onscreen.
1. Launch the app and open the Notifications screen
2. Receive a new notification
As a result, the badge should get immediately reset.
1. Receive a push notification while the app is in BG
2. …
=> Notifications + Swift Mk 5: Simperium

WordPress/Classes/ViewRelated/System/WPTabBarController.m
A tiny PR, but something that's been bugging me for a while. The tab bar images on iPad were displaying too high in the tab bar, whereas they should be centered vertically:
This PR adjusts the image insets slightly on iPad vs iPhone. I'm not sure why it's not 'one size fits all' here, as the tab bars and images are the same size on both platforms. It also seems to be platform specific and not size class specific – the positioning was also incorrect in a narrow multitasking split on iPad.
Fixed insets:
Please ensure you verify the spacing on both iPhone and iPad, as well as in multitasking. The icons should appear consistently spaced across all device types.
=> Adjusted tab bar image insets slightly on iPad

WordPress/WordPressShareExtension/ShareViewController.swift
Fixes #5690
To test:
1. Install Google Photos
2. Attempt to share a Photo
Please, verify that the local URL isn't appended to the Extension Text. Also, please, double check that Sharing from Safari didn't break.
Thanks in advance Aaron!!
=> Share Extension: Prevents appending local URL's

WordPress/Classes/Utility/WPImageURLHelper.swift, WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m, WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift, WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #5720 
To test:
- Login with WP.com
- Select a blog that is private
- Look at the post list
- Check if images are downloading correctly.
- Add the same site to the reader
- Check post from that site and see if images show correctly.
=> Resize images for private blogs.

WordPress/WordPressTest/FeatureFlagTest.swift
Fixes #5752. Feature flags have changed since the test was written – updated to reflect current state.
To test: check the tests build and pass.
=> Fixed invalid feature flag tests.

Podfile, Podfile.lock
Fixes #5710 
**To test:**
1. Update pods.
2. Verify compilation and that stats screens all load.
Functionality was validated in https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/pull/420
=> Update to stats pod 0.7.5 to include localization fix for date strings

WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #5749 
To test:
1. Launch the app.
2. See the labels.
3. Hear the labels with VoiceOver.
=> Brings back all our hopes and dreams by restoring the tab labels.

WordPress/WordPressShareExtension/NSExtensionContext+Extensions.swift, WordPress/WordPressShareExtension/ShareViewController.swift
This PR updates the `Post` button logic, so that it's disabled whenever there is actually no content.
--
1. Launch the Share Extension from Photos.app
2. Make sure the TextView's content is empty
3. Verify that the **Post** button is enabled
Please, try posting to both, dotcom and self-hosted (empty text with attachments). Verify that everything works as expected
1. Launch the Share Extension from Safari.app
2. Verify that the **Post** button is enabled
3. Nuke the TextView's contents
4. Verify that the **Post** button gets disabled
5. Add at least a character. Verify that the button gets enabled again.
Aaron, up for a quick review?
Thanks!!!
=> Share Extension: Empty Posts

Podfile, Podfile.lock
Re-Do of #5776
Bumps the Tracks pod to 0.1.1 which includes a fix for HTTP errors preventing events from getting cleared and not using the shared NSURLSession.
=> Bump Tracks pod to 0.1.1 to include networking fixes

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m
The name of the selector method changed.
To test:
Log out and the app shouldn't crash
Feel free to merge if this work for you @jleandroperez, and once this is merged, #5723 can be merged by you 👍
=> Using new method name for handling defaultAccount change (logging out)

WordPress/Classes/ViewRelated/NUX/SigninErrorViewController.swift
Fixes #5747 
This glitch feels like a framework bug but I can't say for sure.  When the SigninErrorViewController's presentationStyle is set to OverFullScreen, the presenting controller displays a back button arrow that lingers after the error vc is dismissed.  Strictly speaking we don't need to set the presentationStyle as the full screen is covered by default, so removing the custom init *mostly* fixes the glitch.  I say mostly because a keen eye might spot the back button arrow momentarily becoming visible as the error vc is presented.  However when the vc is dismissed the arrow is no longer there. 
To test: 
Be already signed into the app and try to add a new self-hosted site. You can just enter `a` for the username, password, and URL and you'll see the error screen. 
Dismiss the …
=> Signin: Fixes a UI glitch described in #5747

WordPress/Classes/ViewRelated/People/People.storyboard, WordPress/Classes/ViewRelated/People/PeopleCell.swift, WordPress/Classes/ViewRelated/People/PeopleViewController.swift, WordPress/Classes/ViewRelated/People/PersonViewController.swift
This removes the previously added toggle for forcing fixed width cells via `WPTableViewCell` and revises the layout to follow readable margins instead.
- Also drops the constant values used for trailing and leading (no longer needed)
- Also changed the name label font to use the system font instead of Merriweather.
To test:
1. Ensure the People management views follow readable margins on iPad.
2. Ensure the same People management views follow the expected margins on iPhone devices.
Note: In the future, this layout could probably use some `UIStackView` goodness.
Needs review: @frosty can you take a look? 🕶
=> Readability: Revised People Management layout.

WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift, WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.xib, WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Reworking the comments cell layout a bit to better follow readability margins for leading and trailing. Also drops the use of the custom separator to instead use the default separator which does extend to the far right.
Note: There's still a bit of wonky layout here with the dedicated `layoutView` and how the height for these cells is calculated by running a layout calculation... but we'll leave that for another day.
To test:
- Ensure the comments cells load as expected under Comments.
- Ensure the height calculations are correct and no lines are cut off.
- Ensure the margins follow the readable margins on iPad.
- Ensure the margins are as expected on iPhone.
Needs review: @jleandroperez can you take a peak? 😐🍔
=> Readability: Comments Cell

WordPress/Classes/Categories/NSString+Helpers.m
Fixes #5780 
To test: 
- In a browser, create a new post on wpcom add some content including an ascii smiley like ":)"  Publish the post. 
- Add a comment to the post containing some content and the same ascii. 
- Check the image URL and confirm that in both cases it is an .svg.
- Like the post. 
- Go to the reader and open the Liked feed. 
- Find the post in the feed and view its detail. 
- Confirm that the smiley emoji is correctly displayed in the detail, and also in the post card's summary if appropriate. 
- View the comments for the post. 
- Confirm that the smiley emoji is correctly displayed in the comment. 
Needs review: @bummytime would you be up for a quick review?
=> Reader: Adds filter for svg smiley images.

WordPress/WordPressTest/FeatureFlagTest.swift, WordPress/WordPressTest/ViewRelated/Blog/Style/WPStyleGuide+BlogTests.swift
Updates the tests configuration for the currently disabled feature flags and recent blog list cell changes. (tests were failing)
To test:
- Run all of the tests for WordPressTest, ensure all pass.
=> Tests: Update broken tests

WordPress/Classes/ViewRelated/Reader/CommentContentView.m, WordPress/Classes/ViewRelated/Views/WPRichTextView.m
Fixes #5796 
#5654 introduced a subtle bug where comment images could be loaded over and over in a never ending loop.  The normal flow should be:
1. The table view loads its data.
2. A comment cell is configured with a comment.
3. The comment cells comment view processes its content provider and assigns the comment content to its internal WPRichTextView
4. The WPRichTextView renders its text and begins loading any images.
5. Delegates are notified when any images have finished loading.
6. The tableview refreshes clears cached cell heights and reloads so the images are correctly rendered. 
When the tableView reloads steps 1 - 3 repeat, however since the same content is being assigned to the richtext view the process ends there.  Or rather that's what should happen. #5654 introduced code to …
=> Reader: Moves text 'reset' to WPRichTextView

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
To test:
1. Log into a dotcom account on an iPad Device
2. Make sure *NEVER* to open the Notifications tab (ensuring that the view doesn't load)
3. Switch to Safari
4. Open WPiOS side-by-side
Verify that the app doesn't crash right away.
Brent, may i bug you with a quick review?. Thanks for catching this one!!!
=> Fixing Notifications TableViewHandler Crash

WordPress/Classes/ViewRelated/Reader/Reader.storyboard, WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
Ref https://github.com/wordpress-mobile/WordPress-iOS/pull/5792#issuecomment-235706730
Resolving the header margin misalignment by adapting readable margins on iPad for the tableView and search bar up top. We'll leave the margins as is for iPhone layouts for now.
To test:
1. Open the `ReaderFollowedSitesViewController` on iPad.
2. Ensure the margins for the tableView, cells and header are following the expected readable margins.
3. Ensure the margins for the searchBar are following the expected readable margins.
4. Open on iPhone.
5. Ensure the margins are as originally expected for iPhone.
Needs review: @aerych can you take a look?
=> Reader Followed Sites: Readability for iPad layouts.

Podfile, Podfile.lock
Fixes #5806 
This fixes a long standing infrequent crash when stats loads and a NIB can't be found.
To test:
1. Update your local CocoaPods repo with `bundle exec pod repo update`.
2. Install latest Pods with `bundle exec pod install`.
3. Verify stats 0.7.7 is fetched and installed.
No need to verify the crash itself is fixed; verified in the PR from the pod repo.
cc: @sendhil
=> Update WordPressCom-Stats-iOS pod to 0.7.7.

WordPress/Classes/Networking/PlansRemote.swift
Fixes #5813. Removes manual sorting (by ID) of plans, and simply uses them in the order returned by the API.
The missing plan icon should be fixed on the server side soon.
To test: 
* Select a site
* View plans
* Check that the plans are ordered Free, Personal, Premium, Business.
=> PlansRemote: Removes sorting, so plans are returned in API order.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Just updating this comment as the crash was actually not unique to iPad multitasking and occurs even on iPhone, as long as that view controller was not initially loaded.
Ref https://github.com/wordpress-mobile/WordPress-iOS/pull/5810
=> Notifications: Updates a comment to reflect how the crash occurs.

WordPress/Classes/ViewRelated/System/PagedViewController.swift
The plan comparison view controller didn't update the page count of its page control correctly to match the number of plans it was displaying. With the addition of the Personal plan, we were showing 3 page indicators, but 4 pages.
To test:
* View Plans for a site and then tap into a specific plan to view the comparison screen. Ensure that the number of dots on the page control at the bottom of the screen matches the number of pages in the scrollview.
=> PlanComparisonViewController page count now updates correctly

Rakefile
Travis builds haven't been failing when tests fail (last example was addressed by #5797). This is fixed by having the build command return a non-zero exit code when tests fail.
To test:
1. You can find a commit with failing tests by checking out `4e2eaa624050fcbc1a7e5f292894105dae2903db`
2. Before applying this change: `rake test & echo $?`. You'll see that two tests fail, and exit code is 0. Travis would consider this to be passing.
3. After applying this change, run the same command and you'll see two tests fail but the exit code will be 1. On Travis, this will consider this failing.
__Update:__
You can also just check out these builds [with](https://travis-ci.org/wordpress-mobile/WordPress-iOS/builds/149222838) and [without](https://travis-ci.org/wordpress-mobile/WordPress-iOS/builds/14 …
=> Fix Travis builds not failing for tests

WordPress/Classes/Networking/RemoteBlogOptionsHelper.m, WordPress/Classes/Services/BlogService.m
Fixes #5732 
To test:
The easiest way to test this is to edit [RemoteBlogOptionsHelper mapOptionsFromResponse:] and comment out the `software_version` key. This will simulate the issue described in #5732 with a wpcom acct. 
- Start signed out of the app.
- Sign into the app with a wpcom acct, and view the blog details screen.
- Confirm you are not prompted about WordPress being too old.
- Confirm you do not experience other errors due to the software version being `0`.
=> Removes fallback min software version. Adds check for 0 version.

WordPress/Classes/ViewRelated/Menus/MenusViewController.m
Resolves https://github.com/wordpress-mobile/WordPress-iOS/pull/5834
Rebuilding the original PR as just the typo, and into our release branch for 6.4. (Chose not to cherry-pick since the original commit is in a fork)
Thanks to @pixolin
=> Menus: Typo fix courtesy of @pixolin

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Setting the `searchController` to not `active` when it already wasn’t active subsequently called `willDismissSearchController` on the delegate, producing unexpected search cancelling results.
This specifically caused an issue with the tableView's offset when leaving the view controller, where `willDismissSearchController` is called, `searchText` is set to `nil`, and the tableView's content and offset are updated.
To test:
1. Open Blog Posts.
2. Scroll down a bit, select a post.
3. Go back.
4. The tableView offset should be where it was originally.
5. The `willDismissSearchController` should not have been called.
To Test:
1. Open Blog Posts.
2. Search for posts.
3. Select a post.
4. Search should be cancelled, as expected.
To Test:
1. Repeat above, but for Themes.
Needs review: @frosty (no …
=> Posts/Themes: Preventing call to willDismissSearchController.

WordPress/Classes/System/WordPressAppDelegate.m, WordPress/Classes/Utility/FeatureFlag.swift, WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesStreamHeader.swift, WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderMenuViewModel.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderViewController.m, WordPress/Classes/ViewRelated/System/WPTabBarController.h, WordPress/Classes/ViewRelated/System/WPTabBarController.m, WordPress/WordPressTest/FeatureFlagTest.swift
Refs #4094 
This PR removes the new Reader menu's feature flag, enabling the new menu and navigation flow in the app for everyone. Also, as it was convenient, it includes some small fixes to #5799 and #5800, and a slight style tweak to an icon requested by @jancavan.
Needs review: @kurzee, would you be so kind sir?
=> Issues/4094 minor fixes, and removes feature flag

WordPress/WordPressShareExtension/Tracks.swift
Fixes #5837 
To test:
1. Add a logging statement to the `payloadWithEventName` method.
2. Load the share extension or Today extension.
3. Verify timestamps are 13 or more digits (roughly looking like 1470339213034) and no decimal point or numbers afterwards are included.
cc: @xyu
=> Forces the format of the timestamp to drop decimal places

WordPress/Classes/ViewRelated/Pages/PageListSectionHeaderView.m, WordPress/Classes/ViewRelated/Pages/PageListSectionHeaderView.xib, WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m, WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib, WordPress/Classes/ViewRelated/Pages/PageListViewController.swift, WordPress/Classes/ViewRelated/Pages/Pages.storyboard, WordPress/Classes/ViewRelated/Pages/RestorePageTableViewCell.m, WordPress/Classes/ViewRelated/Pages/RestorePageTableViewCell.xib, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/ConfigurablePostView.h, WordPress/Classes/ViewRelated/Post/PostCardActionBar.m, WordPress/Classes/ViewRelated/Post/PostCardImageCell.xib, WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m, WordPress/Classes/ViewRelated/Post/PostCardTextCell.xib, WordPress/Classes/ViewRelated/Post/PostListFooterView.xib, WordPress/Classes/ViewRelated/Post/PostListViewController.swift, WordPress/Classes/ViewRelated/Post/Posts.storyboard, WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.m, WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.xib, WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.m, WordPress/WordPress.xcodeproj/project.pbxproj
While I originally set out to adapt Posts and Pages away from fixed widths, it ultimately brought me to this glorious refactoring for autosizing cells and following iOS imposed margins.
- Cleans up the layout for Pages and Posts.
- Autosizes cells via `UITableViewAutomaticDimension`.
- Adopts readable margins for iPad and iPhone 6+ landscape (Reg Width and Any Height)
- Updates the Pages design just a _bit_.
For now we'll only follow readable margins on iPad and iPhone 6+ landscape. This conforms to the size classes of _Regular Width_ and _Any Height_. We'll leave default iPhone as is for now, as the margins there are technically hand-designed.
With the autosizing cells, I absolutely could not find a way to keep cells from _bouncing_ their heights after any reload animations. Even if the …
=> Posts & Pages: Autosizing and Readability

WordPress/Classes/ViewRelated/Blog/BlogDetailHeaderView.m, WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
This resolves an issue with the margins layout of `BlogDetailHeaderView`. Previously, the margins were not being followed correctly and were misaligned on iPhone.
Note: Also removed unused `const` `BlogDetailHeaderViewHorizontalMarginiPhone`.
To test:
- Open up the Blog Details for a site.
- On iPhone, ensure the icon in the header is aligned with the icons in the cells below.
- On iPad, ensure the icon in the header is aligned with the icons in the cells below.
Needs review: @diegoreymendez can you take a quick run-through? 🏃
=> Blog Details: Rewrites proper readable margins layout.

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Fixes a crash when unblocking a site that was just blocked.
Looks like this particular method `unblockSiteForPost` should have been updated similarly to how `blockSiteForPost` was updated to handle the indexPath guard.
I'm guessing something happens after `recentlyBlockedSitePostObjectIDs.removeObject(objectID)` causing a crash when trying to access that post. `¯\_(ツ)_/¯`
To test:
1. Open the Reader.
2. Block a site with the `...` button.
3. Unblock the site by tapping the blocked cell.
4. Don't crash, and the site should be unblocked.
Needs review: @aerych can you take a peak?
=> Reader: Prevent crash when unblocking site

WordPress/Classes/Models/BlogSettings+Discussion.swift, WordPress/Classes/Networking/AccountSettingsRemote.swift, WordPress/Classes/Services/AccountSettingsService.swift
I fixed a few of our uses of `as!` to prove out my thoughts while writing [a style guide proposal](https://github.com/wordpress-mobile/swift-style-guide/issues/7)
**To test:**
Functionality should not have changed. If account settings and comment sorting still work, then that would appear to be the case.
_For authoring the first accepted style guide proposal:_
=> Cleanup a few forced downcasts

WordPress/Classes/ViewRelated/Menus/MenuItemSourceResultsViewController.m
For whatever reason, the super call to `viewDidLayoutSubviews` was lost at some point for `MenuItemSourceResultsViewController`. I'm surprised no issues cropped up because of it, thus far.
To test:
1. Open Menus.
2. Tap on a Menu item to open the item editor.
3. Results list should layout as expected:
- Search bar in the header for Posts, Pages, Tags
- No search bar for Categories
- Text field, header label and checkbox for Links.
Needs review: @diegoreymendez can you take a look?
=> Menus: Adds missing super call for viewDidLayoutSubviews

WordPress/Classes/ViewRelated/Pages/PageListViewController.swift, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Fixes #5857
Fixes the full-width issue for Posts and Pages as previously solved for Reader cards in https://github.com/wordpress-mobile/WordPress-iOS/pull/5617 and discovered in https://github.com/wordpress-mobile/WordPress-iOS/issues/5082#issuecomment-228387047
To test:
- On iPad, delete the app, reinstall.
- Let the posts or pages for a site load.
- While it’s fetching, move to another tab.
- Let the sync finish.
- Go back to the posts or pages tab.
- Cells should follow correct margins.
Needs review: @aerych take a run-through? Thanks for finding this one!
=> Posts/Pages: Avoid windowless cells

Podfile, Podfile.lock
Closes [this PR](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/16).
The Aztec pod version is the only one published so far - it's not a good candidate for complete integration into WPiOS.  In fact there is nothing we can show in the app with this version.
The purpose of this PR is only to make sure the published pod works, and integrate an initial version of it into WPiOS, while not breaking anything else.
We'll be updating the version as soon as we publish a new one.
**To test:**
1. Just do the Pod dance.
2. Make sure the app builds.
Needs review: @kurzee .
=> Integrates the Aztec pod into WordPress-iOS.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
To test:
1. Open a Comment-Y notification. Please, note that it's contents should cover most of the screen.
2. Tap over the Reply field
3. Enter several new lines
Please, verify, that the Reply field grows, and that it doesn't remain in a single line.
Brent, may i bug you with a hopefully painful review?
=> ReplyTextView: Overlap Glitch

WordPress/Classes/Utility/HelpshiftUtils.m
There are reported issues of some users being unable to use Helpshift at login because they attempt to access it before we've gotten any data back from Mixpanel. This PR defaults to assuming Helpshift *is* enabled until we hear otherwise from Mixpanel.
=> Updated the way we enable/disable Helpshift to optimistically assume it's enabled rather than disabled

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
Assigns values to the magic links events. 
=> Signin: Populates the stubs for magic links analytic events.

WordPress/WordPressApi/WordPressComRestApi.swift
Progress reporting was being reset to 1 when updates failed. It was also being set to 1 when get or post request where successful
To test:
- Use the app and check if REST API requests are being done properly and returning well.
=> Fix progress reports when request fails.

WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Small fix for the Reader when on the detail view, if a user was scrolled down a bit and the nav bars hidden, tapping on the iOS status bar scrolled to top without revealing the nav bars.
To test:
1. Open Reader, tap on a detail post.
2. Scroll down on detail post, nav bar will hide.
3. Tap the status bar to scroll to top.
4. Navbars should become visible again.
Needs review: @aerych can you take a peak?
=> Reader: Set navBars visible after a scrollToTop.

WordPress/Classes/ViewRelated/Reader/ReaderGapMarkerCell.swift
Fixes #5916 
To test:
1. Create a gap, manually or not.
2. Verify gap cell's contentView is no longer white.
=> Issue/5916 Reader gap color

WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
Fixes #5908
To test:
Go to the reader menu.
Tap the Add a Tag option.
Type some spaces then tap the done button (or hit return).
Confirm that controller silently dismisses and a follow attempt is not made for the empty tag.
=> Reader: Trim tag and check length before following.

Podfile, Podfile.lock, WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Integrates the latest from Aztec.
Improves the look & feel to look more like our live editor.
Enables HTML mode and moves the "Done" button to the left of the navigation bar.
**Known issues:**
It seems Aztec is having problems with starting a post from zero.  Switching to HTML is broken, styling is broken too.
We'll need to apply some extra fixes in Aztec before we can get it working properly under WPiOS.
=> Aztec: integrate latest

WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyBezierView.swift, WordPress/Classes/ViewRelated/Notifications/Tools/NotificationMediaDownloader.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockImageTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTextTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockUserTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteUndoOverlayView.swift
- Nukes `@objc` statements, since those are not needed anymore
- Nuked `public` modifiers, since those are not required!
Ref #5613
Build the app and verify nothing breaks!
Nate, may i bug you with a (hopefully fun) review?
=> Notifications: Details Cells Cleanup

WordPress/Classes/Services/ReaderPostService.m
Closes #5917 
This restores some previously gap detection code, with an added condition to avoid applying it to search results (which are sorted by offset not date).
This partly resolves the behavior shown in #5917, however we're still seeing false positives in gap detection due to some current wonkiness in the API.
To test: 
Confirm the code was correctly restored and that the conditional properly excludes search results.
Needs review: @kurzee would you be so kind?
=> Reader: Restores previously removed gap detection, but avoids searches.

Podfile, Podfile.lock
Fixes #5944 
To test:
1. Be sure to update the CocoaPods repo with `bundle exec pod repo update`.
2. Run the app and make sure Helpshift operates as expected.
cc: @sendhil
=> Updating to Helpshift 5.7.1 to fix a problem with UI in support.

WordPress/Classes/ViewRelated/Post/PostCardActionBar.m
Fixes #5915 
To test:
1. Open Blog Posts on iPad.
2. Verify four action buttons are visible in Portrait and Landscape.
3. Transition to multitasking, verify only three action buttons are visible.
4. Transition from multitasking to full-screen, verify all four buttons are visible again.
To test:
1. Open Blog Posts on iPhone.
2. Verify three action buttons are visible in portrait orientation.
3. Verify four action buttons are visible in landscape orientation.
=> Posts: Better calculation for action bar buttons count.

Podfile, Podfile.lock, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #4071 
Whacks `WPAnalyticsStatStatsOpenedWebVersion` analytics event and adds `WPAnalyticsStatMeTabAccessed` & `WPAnalyticsStatMySitesTabAccessed` events.
To test:
1. Run the application.
2. Set a breakpoint in `TracksServiceRemote` in `sendBatchOfEvents:withSharedProperties:completionHandler:` (or dump the dictionaries out to NSLog).
2. Tap on Me Tab & My Sites tab.
3. Wait 10 seconds or less for your breakpoint to fire or log statement to verify those two events are being sent.
=> Adds Me & My Sites analytics

WordPress/Classes/ViewRelated/Menus/MenuItemEditingHeaderView.m, WordPress/Classes/ViewRelated/Menus/MenuItemEditingViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemSourceViewController.m
Fixes a couple issues with Menus on the iPad while sliding into multi-tasking. Removes the previous device identification of iPad and instead decides what to do based on the size class, _as it should_.
To test:
1. Open Menus on iPad.
2. Select a Menu Item to bring up the modal item editor.
3. The view should have a "full" layout with the item types on the left and the selectable values on the right.
3. Background the app.
4. Select another app, such as Safari.
5. Slide in WPiOS for multitasking.
6. The editing modal should now display a "compact" layout with only the selectable items visible and the header displaying the "< Type" back button.
7. Tapping the back button should slide in the item types.
8. Slide the multitasking toggle to bring the app to full-screen.
9. The layout should …
=> Menus: Layout issues on iPad multitasking

WordPress/Classes/Services/PostService.h, WordPress/Classes/Services/PostService.m, WordPress/Classes/ViewRelated/Menus/MenuItemAbstractPostsViewController.m, WordPress/Classes/ViewRelated/Pages/PageListViewController.swift, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostListFilterSettings.swift, WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Removes the `PostServiceType` enum and returns the `PostService` sync method to using strings. This is in anticipation of growing support for custom post types.
Uses a `typedef` for a cleaner API, and _especially_ as a step toward [Swift 3's stringly/strongly API](https://youtu.be/UU2fNq35xkM?t=31m43s) support.
Best test is probably to make sure the menus now sync the correct post type instead of everything. You'll know how to do this better than I, @kurzee.
Another test that's easy is to verify the right posts are being preloaded:
1. With the device on wifi select a site from the *My Sites* screen
2. The network activity indicator should show up in the status bar, indicating that posts and pages are being preloaded. Wait until it's gone so that preloading has completed.
3. Verify both …
=> Remove PostServiceType enum

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift
It's time to enable Autosizing Cells in the Notifications List.
Ref. #5613
2. Test the Notifications List on iPhone / iPad Devices
3. Try rotations as well!
Thought you might love this PR Aaron!!
=> Notifications List: Autosizing Cells

Podfile, Podfile.lock, WordPress/Classes/Networking/ReaderTopicServiceRemote.m, WordPress/Classes/Services/PostService.h, WordPress/Classes/Services/PostService.m, WordPress/Classes/Services/ReaderPostService.m, WordPress/Classes/ViewRelated/Menus/MenuItemEditingHeaderView.m, WordPress/Classes/ViewRelated/Menus/MenuItemEditingViewController.m, WordPress/Classes/ViewRelated/Menus/MenuItemSourceViewController.h, WordPress/Classes/ViewRelated/Menus/MenuItemSourceViewController.m, WordPress/Classes/ViewRelated/Pages/PageListViewController.swift, WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostCardActionBar.m, WordPress/Classes/ViewRelated/Post/PostListFilterSettings.swift, WordPress/Classes/ViewRelated/Post/PostListViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderGapMarkerCell.swift, WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift, WordPress/Info.plist, WordPress/WordPress-Internal-Info.plist, WordPress/WordPressApi/WordPressComRestApi.swift, WordPress/WordPressApi/WordPressOrgXMLRPCApi.swift, WordPress/WordPressShareExtension/Info-Internal.plist, WordPress/WordPressShareExtension/Info.plist, WordPress/WordPressTest/WordPressAPI/WordPressComRestApiTests.swift, WordPress/WordPressTodayWidget/Info-Internal.plist, WordPress/WordPressTodayWidget/Info.plist
Note, only conflict was Podfile.lock checksum, which is resolved by running `pod install` for the latest checksum between `develop` and `release/6.5`.
Needs review: @diegoreymendez I think this would be a case where we could just go ahead and auto-merge since there were no conflicts other than the Podfile.lock. Before I move forward with it, just wanted to give you a chance to take a look in an actual case of merging.
Note: Of course, eventually, if we were merging right after we merged something into the release branch, merging back would _only_ be our recent changes, so it would be less of a history of commits.
=> Merge latest from release/6.5 into develop

WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
Fixes #5952 
**To test:**
1. Launch the app using the simulator for iPad 2, under iOS 9.3.
2. Open a published post.
3. Preview the post.
4. Tap the share button.
5. Make sure sharing works.
Props to @lancewillett for finding this bug.
=> Fixes a crash when trying to share a previewed post.

WordPress/Classes/Networking/ReaderPostServiceRemote.m
Fixes #5917 (for realz)
To test: 
Confirm the issue in 5917 by scrolling a tag like "coffee" until you encounter the "load more" button incorrectly appearing in the list.  
Switch to this branch 
Sign out and back into the app to clear the reader's cached posts.
Repeat the original steps and confirm you can scroll past the point without encountering an errant "load more" button. 
Needs review: @jleandroperez could I trouble you for a quick review?
=> Reader: Check for tagged_on date.

WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #5964
To test:
View a post detail that has enough content to scroll and hide the bars. 
Confirm that the bars are restored when reaching the bottom of the post.
Confirm that the offset is correctly adjusted to continue showing the bottom of the post rather than the bottom bar covering up part of the content and necessitating another scroll. 
Needs review: @nheagy could I trouble you with this one?
=> Reader: Restore bars when scrolling to the bottom of a post detail.

WordPress/Classes/Models/ReaderPost.m
Reader posts were showing the "sort date" on cards and detail which makes no sense for search results.  This PR switches from using the sortDate to using dateCreated, which is really more proper. 
To test:
Test release/6.5 and perform a search to confirm the bug. Note that the dates shown are incorrect for the post's dateCreated. 
Test this branch and confirm that the dateCreated is now shown. 
Needs review: @sendhil could I trouble you for a quick review?
=> Reader: Display date created not sort date.

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Fixes #5913
1. Be signed into a wpcom account and be showing a section header in the Notifications screen.
2. Confirm the header is the correct width.
3. Switch to the Me tab and sign out of the app.
4. Sign back into the app with the same account.
5. Switch to the Notifications tab.
As a result, the Section Header should have the expected width.
Eric, may i bug you with a quick review?
=> Fixing Notifications Header

WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.xib
Opening a Notification Comment Details, develop, iOS 10, is currently displaying the following error in the console.
This appears to be caused by a constraint with priority set to 1000 (and breaks on iPhone devices, since the button is actually not displayed).
```
27 15:53:33.909398 WordPress[3908:1206234] [LayoutConstraints] Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want. 
Try this: 
(1) look at each constraint and try to figure out which you don't expect; 
(2) find the code that added the unwanted constraint or constraints and fix it. 
(
"<NSLayoutConstraint:0x174298a60 VerticallyStackedButton:0x102bac800'Reply'.width == 55   (active)>",
"<NSLayoutConstraint:0x174298d80 'UISV-hiding' …
```
=> NoteBlockActions: Fixes constraint error

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift, WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift, WordPress/Classes/ViewRelated/Notifications/Helpers/NotificationDeletion.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift, WordPress/Classes/ViewRelated/Notifications/Views/NoteUndoOverlayView.swift
Closes #4230 
Sergio, may i bug you with a review?
--
2. Open a comment-Y notification
3. Press the `Spam` button
Please, verify that:
- The undo legend displays `Comment has been marked as Spam`
- After a while the comment is effectively marked as spam.
- Verify that the Undo button avoids the spam action.
1. Log into a dotcom account and open a Comment-Y notification
2. Press the `Delete` button
Please, verify that:
- The Undo Legend displays `Comment has been deleted`.
- After a while the comment is effectively deleted.
- Test that the Undo button avoids the deletion action.
2. Locate a Comment-Y Notification and *Swipe* over the cell
3. Press the `Delete` button
Please, verify …
=> Notifications: Destructive Actions Legend

WordPress/Info.plist
Fixes #5982 
Quick little thing that'll add the today widget to the shortcuts items
To test:
3D touch the icon and the today widget will show up
=> Adding 3D Touch widget shortcut

WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
I noticed last night that gravatars in the reader we non-retina and so looked pixellated. I thought we'd fixed this before, but perhaps not.
I've updated `ReaderCommentsViewController` to take into account the screen scale when populating the comment gravatars.
Before:
After:
To test: view the comments for a post in the reader!
=> Reader comment gravatars are now retina quality

WordPress/Classes/Utility/WPWebViewController.m
Fixes #5788 
Attempting to load audio files directly in a UIWebView yields a web kit error, yet the audio continues to play.  The error isn't helpful to the user, so since the audio still plays let's not show the prompt.  
This PR checks for the error and returns vs showing an alert.  The error domain and code do not seem to be exposed via system consts (not that I could find anyway) so I've added some of our own.
To test: Follow the steps outlined in the issue and confirm an alert does not appear.
@nheagy would you be game to review this one?
=> Avoid showing error when playing audio files.

WordPress/Classes/ViewRelated/Reader/ReaderPostMenu.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Fixes #5620 
Now when using the "Visit Site" option, instead of loading the site URL, we'll load the post permalink. 
This PR also updates the text of the menu option from "Visit Site" to "Visit" for better consistency with the web, and removes some redundancy in menu item names.
To test:
Open the menu for a post in both the stream, and in the detail vcs.  Confirm the "Visit" option opens the post's permalink.
@kurzee would you care to take this one? 
=> Reader: Updates 'Visit Site' to show the post on the site.

WordPress/Classes/Models/Blog.m, WordPress/Classes/Models/WPAccount.h, WordPress/Classes/Utility/HelpshiftUtils.h, WordPress/Classes/Utility/HelpshiftUtils.m, WordPress/Classes/ViewRelated/Settings/SupportViewController.m
If there's a WordPress.com account, go through every blog and add a tag for
each plan.
I've also added the plan name and ID to the log.
Fixes #6060
=> Include plans as tags in Helpshift conversations

WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift
Fixes an issue created in 8ee180ee8c0b919f7911a67aaead4bf395476884 where labels now had a background color that would show when selecting a comment cell.
To test:
- Open Comments
- Select a cell, make sure the label's background is transparent.
=> Comments: Default transparency for label background colors.

WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/Networking/MediaServiceRemote.h, WordPress/Classes/Services/MediaService.h, WordPress/Classes/Services/MediaService.m, WordPress/Classes/Services/PostService.m, WordPress/Classes/ViewRelated/Post/PostListViewController.swift, WordPress/Classes/ViewRelated/Post/WPPostViewController.m
**Original issue:**
Sometimes when publishing a new post a duplicate post will appear in the post list. It was determined that the cause of this is the dismissal of the editor before the post has finished being published. The post list view controller initiated a refresh of posts before the post saves properly to Core Data and then a duplicate appears. If the posting was done within the timeout period of the list view controller (less than 5 minutes) then the issue wouldn't present itself.
Several improvements were made:
1. Added KVC life cycle calls to AbstractPost to prevent any possible issues with accessing `original` and `revision`.
2. Updated the filter on the post list to only show "original" posts. The filter was showing original and revision posts which can add to the confusion. …
=> Prevent duplicate posts in Post List

WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
This PR fixes an issue with the way certain reader analytics are being bumped and iOS state restoration.  
Previously, the reader stream and detail controllers would bump their analytics when their views were loaded. This was fine when the reader had only marginal support for state restoration.  Now that SI is fully supported, when the app is resumed and the reader is restored to its previous state *all* controller views in the navigation hierarchy are being loaded when state is restored, whether the reader tab is selected (and the reader visible) or not. 
This PR changes it so reader analytics are bumped in `viewDidAppear` and a flag is set so stats are only bumped once.  This approach allows for a stat to still be bumped when state is restored if that controller's view is actually seen …
=> Reader: Bumps analytics when views appear, not when loaded.

Podfile, Podfile.lock
Fixes #
To test:
- Tap on Add media
- Try to capture a new photo and/or video on the picker and see if no hang happens
- Try to open a empty camera roll and see if the capture photo/video header shows up.
=> Update WPMediaPicker pod to 0.10.2

WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift, WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
This is a quick follow up to #6116 to remove some forced unwrapping of optionals.  
I noticed a crash reported by hockeyapp that may or may not be related to the changes in #6116 -- the stack trace wasn't clear.  This pr is intended to address the issue (if it was an issue). Regardless its better practice to use a guard to unwrap required optionals.  I've also added additional checks ensuring a controller's view is loaded and assigned to a window (thus visible) before bumping stats.  Also, since both ReaderTopic and ReaderPost instances can be assigned *after* the view controller has appeared, depending on circumstance, we'll try to bump stats when the is configured, and when the view has appeared.
To test: Same instructions as in #6116  
Needs review: @kurzee, care for another quick …
=> Reader: For paranoia, adding extra checks before bumping stats.

WordPress/Classes/Services/PostService.m
This partially addresses an issue with not syncing a site's settings before editing a new post.
Previously when creating a new post, if a site's settings were not already synced, the post would simply be set with the "uncategorized" ID. This would then override whatever the user actually had set to the default category for their site, upon posting.
Now, we'll avoid setting a default category ID unless we actually have one for `blog.settings.defaultCategoryID`, allowing both self-hosted and .com sites to default to the correct default category on post once it hits the API.
1. Log out of the app.
2. Sign in to .com account.
3. Hit the new post button on the tab bar.
4. Post a new post.
5. Check the post on the site and that it used the correct default post category.
6. Change the default …
=> PostService: Avoid setting uncategorized by default, on new posts.

Rakefile
To avoid problems when building SwiftLint, and because it's so much faster,
let's install it using the `pkg` from the releases page if available.
To test:
- Make sure `SWIFTLINT_VERSION` in Rakefile is different from the installed version (or `rm -rf vendor`)
- Run `rake dependencies`, no need to change it to `master` anymore
- SwiftLint 0.12.0 should be installed from the pkg file
- Try `rake lint`
=> Install SwiftLint from binaries when available.

Rakefile
Currently, if SwiftLint release is not found on github a `.pkg` file is created with `{"error":"Not Found"}` content and failing to expand the `.pkg` file.
=> Fix SwiftLint installation if release not found on github

WordPress/Classes/Extensions/UITableView+Helpers.swift, WordPress/Classes/Networking/AccountServiceRemoteREST.m, WordPress/Classes/Networking/BlogServiceRemote.h, WordPress/Classes/Networking/BlogServiceRemoteREST.m, WordPress/Classes/Networking/Remote Objects/RemoteBlog.h, WordPress/Classes/Networking/Remote Objects/RemoteBlog.m, WordPress/Classes/Services/BlogService.m, WordPress/Classes/Utility/ContextManager.h, WordPress/Classes/ViewRelated/Blog/BlogListViewController.m, WordPress/Classes/ViewRelated/Blog/CreateNewBlog/CreateNewBlogViewController.h, WordPress/Classes/ViewRelated/Blog/CreateNewBlog/CreateNewBlogViewController.m, WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift, WordPress/WordPressTest/BlogServiceRemoteRESTTests.m
Fixes #1466 – when a new .com site is created, it now gets highlighted in the sites list.
- When the app is horizontally regular (so the split view is expanded), the blog is _selected_ and the user is taken to blog details.
- When horizontally compact (so the split view is collapsed), the blog is only _highlighted_ and the user remains on the blog list.
To test:
- On iPad (full screen, no multitasking), create a new site using the + button in the top right of the sites list. After the create site screen is dismissed, the new blog should be highlighted and then you'll be taken to its detail screen.
- On iPad (multitasking either 50/50 landscape or in portrait) or iPhone, create a new site using the + button in the top right of the sites list. The new site should be temporarily highlighted …
=> Issues/1466 – New sites are now selected / highlighted in the blog list after creation

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m, WordPress/Classes/ViewRelated/Stats/StatsViewController.h, WordPress/Classes/ViewRelated/Stats/StatsViewController.m
Fixes a warning for a "duplicate" category definition from the stats pod. Really, we just needed to import in .m files and not the .h files for Xcode 8.
To test:
- Build, make sure there's no warnings.
Needs review: @aerych can you take a gander?
=> Fix that unrelated warning that stares me to death when I try to compile a risky block of code

WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift
Fixes #6136 
To test:
Go to sharing->Manage and enable "Edit sharing buttons" or 'Edit "More" button'.  
Add a button.
Go back to Sharing
Go back to Manage.  With the fix the additional button is appropriately checked.  Without it is not.
Needs review: @rachelmcr
=> Saving sharing button settings when dismissing view controller

WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Fixes #6109 
To test:
- Open the app
- Select a blog with multiple authors
- Go to post list
- Tap on the segment control that allows to select my posts, and everyone
- Check if the list gets updated.
=> Refresh Post list after author filter is changed.

WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #6154
To test:
Testing this patch is sort of convoluted. It's fairly straightforward but you're welcome to add a localization string and see if it's working properly or not. 😄 
=> Properly wraps Reader tab label in NSLocalizedString.

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift, WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Breaks off from https://github.com/wordpress-mobile/WordPress-iOS/pull/6147 to partially fix #5992.
To test, on Blog Posts:
1. Select a post from "Published" and edit it to become a draft.
2. The filter selection should update to "Drafts" and drafts should be displayed.
##
3. Select a post from "Drafts" and edit to publish it.
4. The filter selection should update to "Published" and published posts should be displayed.
##
5. Select a post from "Scheduled" and edit it to become a draft.
6. The filter selection should update to "Drafts"  and drafts should be displayed.
##
7. Select a post from "Drafts" and edit it to become scheduled.
8. The filter selection should update to "Scheduled"  and scheduled posts should be displayed.
##
9. Select a post from "Scheduled" and edit it to post …
=> PostList: Improves filter update when switching post statuses.

WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
Fixes #6158. @hoverduck reported an issue (with reproduction steps) where the 'dimming' view could become misplaced when switching between multitasking sizes. This PR just ensures that the frame is correct when a splitview appears.
To test: Follow the reproduction steps in the original issue, and ensure it doesn't happen again!
=> Issue/6158 Splitview Dimming with Multitasking

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
We'll need to disable the posts and pages preloading for now until we can find better solutions for handling the issues in #6151. I can't come up with anything that's not too risky to fit into 6.7, and we really need to make sure users can access all of their posts on the lists in our next release.
Sorry @nheagy!!!
To test:
- Ensure no posts are preloading on a fresh install or log out/in.
=> Temporarily disable posts preloading

WordPress/Classes/ViewRelated/Me/GravatarPickerViewController.swift
Fixes #6017 
To test:
Navigate to the **Me** tab and tap the current avatar and the view should be different based on the images on the device:
| No selfies on the device | At least one selfie on the device |
|:----------:|:-------------------:|
| ![without selfies](https://cloud.githubusercontent.com/assets/1046917/19954056/7c02e972-a1af-11e6-8d1c-288c81d29837.PNG) | ![with selfies](https://cloud.githubusercontent.com/assets/1046917/19954057/7c065eea-a1af-11e6-8e61-1a6ff5904119.PNG) |
<hr>
And thanks for building this awesome app.
This is my first step contributing to this project, would love to 👂  your thoughts on this!
Thank you 😃
=> Me: Show selfies album by default when picking image for Gravatar

WordPress/Classes/ViewRelated/Post/PostListViewController.swift
We lost the original re-sync call when changing authors via: https://github.com/wordpress-mobile/WordPress-iOS/commit/dadde8f9e73354b3627ee5c8fd27c090cedebc4a#diff-56d3ee28947d056476717395cb71f4d7L584.
Adding it back now to address an issue where posts would not sync or page correctly when switching authors. This also helps alleviate some of the issues on https://github.com/wordpress-mobile/WordPress-iOS/issues/6151.
To test:
- Fresh install.
- Log in, Open "Blog Posts" for a site that has many posts and multiple authors.
- The `PostListViewController` will start on "Only Me", switch to "Everyone".
- The `PostListViewController` should reload and resync.
- Scroll to the bottom of the list, more posts should page in as expected.
=> Posts: sync when changing filter author

WordPress/Classes/ViewRelated/Blog/SiteManagement/StartOverViewController.swift
I missed the Start Over controller in #6061, and paid users who contacted us from there didn't have their conversations tagged accordingly
Cc: @rachelmcr 
=> Add Helpshift tags to Start Over conversations

WordPress/WordPress.xcodeproj/project.pbxproj, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/OCLint.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Alpha.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Internal.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressScreenshotGeneration.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressShareExtension.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressTodayWidget.xcscheme, WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressUITests.xcscheme
Fixes warnings from both Xcode 8.1 and cocoapods to update to recommended settings. Particularly by setting `$(inherited)` for `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES`.
To test:
- Close Xcode
- Nuke `Pods` dir
- Run `pod install`
- Open Xcode
- Make sure Xcode doesn't ask to update to recommended settings
- Make sure the project builds
- Make sure tests build/pass
Needs review: @astralbodies  can you take a peak?
cc @kwonye as this is a part 2 for https://github.com/wordpress-mobile/WordPress-iOS/pull/6096
=> Xcode 8.1/cocoapods recommended settings.

WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift
ReplyTextView appears to be slightly broken in iOS 10 (just noticed). Details below!
1. Launch WPiOS on an iOS 10 device (tested here on the SE / 6s)
2. Open a Comment-Y Notification
3. Type three lines of text (word + newline + word + newline + word)
4. As a result, the first word will end up offscreen.
5. Try to scroll upwards
6. Note that the ReplyTextView won't scroll
Please, verify that iOS 9 doesn't break. This might have been broken for months, i'm afraid!
Eric, may i bug you with a review
=> ReplyTextView: Fixing Scroll Position Glitch

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
On fast connections, the pull to refresh gesture's spinner might get dismissed nearly instantly. In this PR we're implementing a "Minimum Delay" mechanism, so that the manual refresh doesn't feel broken.
Closes #6177
1. Log into a WordPress.com account
2. Open the Notifications tab
3. Perform a Pull to Refresh gesture
Make sure that the minimum delay is ~1.5 seconds, before the spinner goes away. Optionally, toggle the Network Link Conditioner and verify everything works as expected.
Nate, may i bug you with a review?
=> NotificationsViewController: Minimum PTR delay

WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #6202. See the original issue for a brief summary.
To test:
* Open the editor to start a new post. Enter a title and ensure the keyboard is visible onscreen.
* Background the app.
* Quit the app in Xcode (so that state restoration is used).
* Relaunch the app. The 'unsaved changes' alert should be displayed, but the keyboard should not be visible.
Needs review: @nheagy Would you mind?
=> Fixes #6202: Dismiss keyboard when showing unsaved changes alert.

WordPress/Classes/System/WordPressAppDelegate.m
In fixing #1802, we removed code to register for push notifications on launch (#5476). However, if there's a problem registering after sign in, then we'd end up never attempting to register again. Apple's documentation also states that you should attempt to register on every launch of the app. 
Registering for push doesn't prompt the user, so it doesn't affect #1802. We'll still delay asking for _user_ notification permission until sign in.
Targeting 6.7 because we've had one user in testing who had issues at least partially caused by this omission.
**To test:** run the app, ensure you register successfully for push notifications. Of course, it won't do anything on first launch, until you've signed in. Ensure you're not asked for notifications permission until you sign in.
Needs review: …
=> Register for push notifications on launch

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Fixes #4328. I've added a variation on the no results view when all sites are hidden. The messaging should match Calypso's in the same situation.
To test:
* Hide all sites, exit Edit mode and check the message appears as expected.
* Check the message disappears when you re-show a site.
* Check the existing 'no sites' message still appears when you have no sites whatsoever.
=> Issue/4328 Show No Results message when all sites are hidden

WordPress/Classes/Networking/PostServiceRemoteREST.m
Fixes #6113 (mostly), https://github.com/wordpress-mobile/WordPress-iOS/issues/3973#issuecomment-245332447
This was previously an attempted fix on https://github.com/wordpress-mobile/WordPress-iOS/pull/6147, but we soon realized we weren't sure of any greater implications from the change.
After much thought, testing, and seeing new user reports of the same issues, I've decided it would be in our best interest to ship the fix as seen here. The side affects of the original bug are more consequential than the potential edge cases this fix may create. I would find myself afraid to use our editor if I experienced the issues users have reported based on the original bug.
That said, the only real edge case I can seem to find from this fix are that previously saved drafts which are later changed …
=> Posts: Remove API override of dateCreated when equal to dateModified

Podfile, Podfile.lock, WordPress/Classes/Models/AbstractPost.m, WordPress/Classes/Models/Blog+Capabilities.swift, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m, WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m, WordPress/Classes/ViewRelated/Post/PostEditorSaveAction.swift, WordPress/Classes/ViewRelated/Post/WPPostViewController.m, WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #6121. 
Adds Publish Now / Submit for Review / Save as Draft options to the options menu in the editor.
* If the post is new and the status is currently set to Publish, then the options menu will contain a "Save as Draft" option. This toggles the post status and updates the content of the local post.
* If the post's status is currently set to Draft and the user has permission to publish posts, the options 
menu will contain a "Publish Now" option.
* If the post's status is currently set to Draft and the user does not have permission to publish posts, the options menu will contain a "Submit for Review" option.
To test:
* Try the above scenarios out in the editor, and others besides to ensure it's not appearing when it shouldn't (and is appearing when it should)!
* Ensure that the …
=> PostViewController: Adds quick Publish / Draft item to options menu.

WordPress/Classes/ViewRelated/System/ForcePopoverPresenter.swift
On the iPhones Plus in landscape orientation, the post list filters popover was appearing as a form sheet modal instead of a popover.
This PR uses a different `UIAdaptivePresentationControllerDelegate` method in `ForcePopoverPresenter`, which fixes the problem.
Before:
After:
To test:
* Check that the Post List filters popover (Published / Drafts / etc) appears as a popover in all orientations on all devices (particularly iPhones Plus).
=> Fixes an issue where post list filters didn't appear as a popover on 7+

WordPress/Classes/ViewRelated/Post/WPPickerView.m
Fixes #846. On some devices, the publish date picker in post settings could end up with a zero width, making it invisible. This PR moves around some of the date picker view setup code so that it'll always get its width from the picker view.
To test:
* Edit a post, go to Options, and then attempt to set a date. You should always see the blue bar at the top of the picker, and be able to successfully select a date. I was always able to reproduce the original issue on the iPhone 5S simulator, so I'd test there and also ensure other devices look fine.
cc @rachelmcr
=> Issue/846: Publish date picker could end up with a zero width
