- WordPress/Classes/ViewRelated/Cells/PickerTableViewCell.swift
Fixes #6226
To test:
- Open the My Sites tab in the app
- Open a site's Settings
- Open the Discussion settings
- Open a setting with a picker, e.g. Paging
Bare in mind that I haven't fully digested the project, just wanted to take a look on what Automatticians do in iOS development 😉 
That's how it looks with the fix:
> Fixes number picker's height in Site Settings

- WordPress/Classes/ViewRelated/NUX/NUXAbstractViewController.swift
Fixes #6216
To test:
- Try to login in the app with invalid login details
- On the error screen tap on the Contact US option
- See if you ask something like "login" a screen shows up with possible solutions in the FAQ
- Do the same by tapping on the ? icon on the top right.
Note: if you used the app before, and used helpshift you may need to reset the Simulator in order to start a conversation from the beginning.
> Show search options on initial help shift talk.

- WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
Fixes #6057
2. Open `Me` > `App Settings`
3. Tap over the `Open Device Settings` row
Verify that the OS Settings for WPiOS show up onscreen. Tap the top left button to reopen wpios, and verify that the row gets properly de-highlighted.
Sir, may i bug you with a review?
> Linking Device Settings

- WordPress/Classes/Networking/WordPressComServiceRemote.m
We recently got a support request via Helpshift, regarding issues creating an account. After a brief check, we've noticed the minimum password length isn't being adviced anywhere.
In this PR we're just updating the `Invalid Password` message, to indicate that the minimum required length is 6 characters.
1. Fresh install the app
2. Attempt to create a new account, with a 1 character password
3. Verify that the Error message reads as follows:
```
Sorry, that password does not meet our security guidelines. Please choose a password with a minimum length of six characters, mixing uppercase letters, lowercase letters, numbers and symbols.
```
Nate, may i bug you with a quick review?
Thanks!!!
cc @mzorz @oguzkocer
> Updates Invalid Password Message

- WordPress/Classes/Models/Person.swift
- WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
This PR updates the list of available roles to invite people, whenever the target blog is set to Private.
Fixes #5676 
1. Open `My Sites` tab and pick up any of your testing blogs
2. Set its visibility to Private (`Settings` > `Privacy` > `Private`)
3. Open the People Management UI (`My Sites` > `Blog` > `People`)
4. Tap the plus sign in the top right to invite a new user.
Verify that (A) the preselected role is `Viewer`, and (B) if you attempt to change the role, `Follower` doesn't show up in the list.
Diego, may i bug you with a quick PR?
Thanks!
> Invite People: Private Sites

- WordPress/Classes/Models/ReaderCrossPostMeta.swift
- WordPress/Classes/Models/ReaderPost+ManagedObject.swift
- WordPress/Classes/Models/SourcePostAttribution+ManagedObject.swift
- WordPress/Classes/Utility/ReaderPostCacheProvider.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/ReaderPostCacheProviderTests.swift
- WordPress/WordPressTest/WordPressTest-Bridging-Header.h
Retales to #6240 
This class will be hooked in a later PR to the `ReaderPostService` class.
It's only responsibility is to retrieve a cached `ReaderPost` based on a `postID` and a `siteID`
Which is the information passed on `ReaderStreamViewController`
```swift
var controller: ReaderDetailViewController
if post.sourceAttributionStyle() == .Post &&
post.sourceAttribution.postID != nil &&
post.sourceAttribution.blogID != nil {
controller = ReaderDetailViewController.controllerWithPostID(post.sourceAttribution.postID!, siteID: post.sourceAttribution.blogID!)
} else if post.isCrossPost() {
controller = ReaderDetailViewController.controllerWithPostID(post.crossPostMeta.postID, siteID: post.crossPostMeta.siteID)
} else {
controller = ReaderDetailViewController.controllerWithPost(post)
}
``` …
> Adds class to fetch cached ReaderPost objects

- WordPress/Classes/Extensions/NSURL+Exporters.swift
- WordPress/Classes/Services/MediaService.h
- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #5560
To test:
- Go to the settings app and block the access to Photo Library for the WordPress app
- Start a new post or edit an old one
- Tap on add media
- Tap on the media capture on the top
- Check if the new media is added to the WordPress media library
- Tap on Done
- See if media is correctly added
- Go to App setting and change media related settings (maximum image size and geo-location) and check if all works correctly.
> Allow direct copy of image or video from capture to WP media library.

- WordPress/Classes/Utility/HelpshiftUtils.m
Fixes #6162 
To test:
- Remove the Helpshift credentials from the wpcom_credentials file
- Recreate the ApiCredentials.m file
- Build and run the app
- Go to Me->Help And Support -> WordPress Help Center
- Check if no crash happens and the app forum webpage opens
- Add the credentials back to the file, and regenerate the ApiCredentials file.
- Go to Me->Help And Support -> WordPress Help Center 
- Check if help shift starts.
> Disable helpshift if no valid API key is available.

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
This PR fixes an issue where a post with an empty string for content would cause a crash trying to retrieve the paragraph style from an attributed string.  Props @kurzee for the find.
To test:
Try viewing a post with an empty string for its content.   Confirm there is no crash.
> Fixes an issue where an empty string could cause a crash.

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Fixes an issue where subviews associated with text attachments were not correctly re-positioned after changing margin height.  This is most noticeable when multitasking on the iPad. Props @frosty for the find.  
To test:
View the post detail on the iPad Pro. 
Swipe to open the multitasking window and enter side by side mode. 
Drag the app separator to switch between 50/50 and 1/4 split screen. 
Confirm that images are correctly positioned after changing split screen size.
Needs review: @frosty would you do the honors?
> Reader: Fixes placement of attachment subviews after updating margins.

- WordPress/Classes/Services/AccountService.m
- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/Utility/InteractiveNotificationsManager.swift
- WordPress/Classes/ViewRelated/Tools/HelpshiftPresenter.swift
Adds inline comment reply to notifications.
Fixes #2036 
I've split the registration of categories and authorization in two. iOS 9 keeps the old behavior but iOS 10+ will always register notification categories on launch. Otherwise, changes to those categories would only be picked by iOS when we requested authorization (i.e. you had to sign out and back in).
I've reversed the order of actions on `CommentReplyWithLike`. Specially for iOS9, where the first item looks like the primary action (blue vs grey). I personally think we should encourage reply over like, but that's a design decision that's not really related to inline reply, so I could use a second opinion.
- Run the app. If testing on iOS 9, sign out and back in or do a fresh install so the system picks up the new notification …
> Add inline reply to comment notifications

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
We've received several reports about posts in the reader displaying correctly at first, but then the text vanishes when scrolling. Props @rachelmcr @roundhill and @ebinnion for the reports. 
The cause appears to be when the NSTextAttachment used to reserve space for a footer view has a height of zero. It only seems to happen on certain posts, but on those posts it happens consistently.  The posts are on private blogs so ping me for the URLs. 
To test:
Confirm the glitch in the release/6.8 branch on any of the affected posts.  
Switch to the branch in this PR and confirm that
Needs review: @jleandroperez would you mind taking a look at this one?
> Reader: Fixes an issue where text could vanish for some posts.

- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
After publishing a post, we should show a "Published!" status after the "Publishing..." HUD appears if the post was published successfully. If the publish fails, we should show an error stating that something went wrong.
It seems like these final statuses weren't being displayed because we were calling `dismiss` on the HUD just before we tried to show them. I've removed the calls to dismiss, and it seems to work as expected now:
To test:
* Publish a post and ensure you see the "Published!" status.
* Attempt to publish a post resulting in a failure (you could tweak `-[PostService uploadPost:success:failure]` to call failure instead of success) and ensure you see an error status.
Needs review: @astralbodies looks like you touched this code recently – would you mind?
> Editor: Fixes status HUD being dismissed too early after posting

- WordPress/Classes/ViewRelated/Reader/Reader.storyboard
I noticed a breaking constraint in the reader detail when the attribution footer was not being shown.  This PR changes that view's height constraint priority to 999 to avoid the breakage. 
To test:
View the detail and check in the console that the constraint does not break.
Needs review: @nheagy could I trouble you for this one?
> Reader: Fixes a breaking constraint on the reader detail.

- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #6255.
The new "quick publish" action (#6207) adds either a Save as Draft, Publish Now, or Submit for Review action to the `...` menu in the editor.
We were determining whether to show Publish Now or Submit for Draft based on the blog's `capabilities` – if it contains `publish_posts` then show Publish Now, otherwise Submit for Draft.
However, self-hosted blogs don't have `capabilities`, and we don't currently seem to have any way to determine user role / permissions. Because of this, we were always showing "Submit for Review". I've updated the logic to default to "Publish Now" if no capabilities are present.
To test:
* Start a new post for a self-hosted non-Jetpack site.
* Save the post as a draft (you can use the quick action in the `...` menu)
* Open the `...` menu and you should …
> Issue/6255 Show Publish Now action for self-hosted non-Jetpack sites

- WordPress/Classes/ViewRelated/People/PersonViewController.swift
Fixes #5670
1. Set up a site with two users: the site owner and a second account you are using in the app
2. Open the app (logged in to the second account)
3. Go to My Site > People
4. Select the site owner in the list of users
4. Try to change the user's role. 
5. Verify that an alert shows up, with the following text: `There was an error updating @[username]`
6. Verify that the Remove User row now reads `Remove @[username]` instead of `Remove User`
Sir, may i bug you with a quick review?. Thanks in advance!
Thanks @rachelmcr for spotting this one!!
> PersonViewController: Updates Interface Messages

- WordPress/Classes/ViewRelated/Post/Categories/WPAddPostCategoryViewController.m
Fixes #6266
1. Comment out [this snippet](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Networking/TaxonomyServiceRemoteXMLRPC.m#L33) (`TaxonomyServiceRemoteXMLRPC. createCategory`, `extraParameters` initialization) in order to force a "Create Category Remote Error"
2. Fresh install the app
3. Log into a self hosted blog
4. Launch the Post Editor
5. Tap over the top right actions button, and pick `Options`
6. Tap over the `Categories` row
7. Press the `+` button and try adding a new category
As a result, the app is expected not to crash anymore.
Sir, may i bug you with a crashfix check?
Thanks!!
> WPAddPostCategoryViewController: Thread Safety makes us Happy

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Fixes #6279 
To test:
Check that blockquotes are displayed in the Merriweather font and not Merriweather-Italic
Needs review: @jleandroperez would you mind taking this one?
> Switch to Merriweather instead of Merriweather-Italic for blockquotes.

- WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Fixes #6282 
For the fix I'm just increasing the lineSpacing.  I thought it might be better to set the lineHeightMultiplier to match the line height set in the detail (1.6875), but when I tried it the line spacing was significantly larger than desired.  Best I can tell this is due to a difference between how the detail computes its line height via css. 
Also, since the same font size is used on the iPad and iPhone I've made the spacing the same as well.
To test: 
Compare the line spacing in the cells and in the detail.  They should be nearly indistinguishable, with only a pixel or two difference at three lines of text.  
Needs review: @kurzee Could I trouble you again sir?
> Reader Cards: Adjusts line spacing.

- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes the transition between **Post** and **Scheduled** buttons to happen before the settings view dismisses, instead of after the animation has completed.
**Before:**
**After:**
To test:
1. Create or edit a post
2. Open the options, and change the post to be scheduled for a future date
3. Go back to the editor
4. Observe that the button has changed to 'Scheduled' without animation.
> Fix delayed transition in Post/Schedule button

- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Just like #6275 but now for the Drafts/Save button transition!
We like small, focused PRs, right?
To test:
- Make a new post, change it draft status, watch the top right button as it transitions back to the editor
- Also, try the new "Save as Draft" option in the `…` menu to make sure nothing is broken 😉
Jorge, mind looking over this one for me?
> Fix transition between Post and Save buttons in editor

- WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
I didn't remove Xcode's autogenerated header before merging. Oops.
_You found it, so you can review it_ ;)
> Fix improper header on EditPostViewController.swift

- WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
Fixes #6265 
I was never able to reproduce the crash.  The stack trace suggests that `isUserAdminOnSiteWithID` was being passed a `nil` value for `post.siteID` so I've opted to `guard` everything to ensure nothing is nil that shouldn't be.  I'm a little worried this is kicking the proverbial can down the road and we'll just end up seeing a new crash with the same root cause.  If we do perhaps the root cause will be more apparent.  Open to other ideas in the meantime.
To test:
Confirm that page views are still bumped when viewing a post.  You can confirm the session task is executed via a breakpoint. Or for a more practical test:  
- Create a new post with a test account. 
- With another test account, like that post.
- Note the page view from the first account.
- With the second account, …
> Guard all the things to prevent a crash case bridging objc.

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
I've noticed the no-results/loading view overlapping the loaded post content a couple of times now.  It only happens momentarily and is quick to correct itself so it can be tough to spot.  Best case to observe it is loading a post via a notification and hope it occurs while the view controller is transitioning. 
This pr sets the textView's opacity to 0 until the post content is loaded. This seems to prevent the overlap during the transition animation.  Opacity is set vs making the view hidden to avoid conflicts with updating constraints when the view is hidden.
To test:
Try to confirm the bug via the method stated above. Look sharp or you'll miss it.
Switch to this branch and try to reproduce the bug.  Confirm that the loading/no-results view does not overlap the text content.
Needs …
> Reader: Hide the details textView while loading the post.

- WordPress/Classes/Extensions/UIImageView+Gravatar.swift
- WordPress/Classes/Networking/GravatarServiceRemote.swift
- WordPress/Classes/Services/GravatarService.swift
- WordPress/Classes/Utility/WPAvatarSource.m
- WordPress/WordPressTest/GravatarServiceTests.swift
- WordPress/WordPressTest/WPAvatarSourceTest.m
Fixes #6270 
Gravatar URLs should be constructed with a hash based off of the e-mail address (or URL for Blavatar) with the following sanitization ([per Gravatar documentation](https://en.gravatar.com/site/implement/hash/)):
1. Trim leading and trailing whitespace from an email address
2. Force all characters to lower-case
3. md5 hash the final string
To test (based on @rachelmcr's steps):
1. While logged out of the WordPress app, select "Create a site".
2. Create a new account and site, using an email address with capital letters.
3. On the Me tab, add a new Gravatar.
4. Confirm the Gravatar is added and appears on the Me tab.
5. Swipe to close the app.
6. Reopen the app. Verify the Gravatar is still there.
> Sanitize Email for Gravatar Hash Creation

- WordPress/Classes/Models/Blog.m
Fixes #6928.
The Plans menu item in `BlogDetailsViewController` will now only appear if the user is an Admin of the blog.
To test:
* Add yourself to a site with a user level of Author or Contributor.
* Start the app, select the site, and check that the Plans menu item isn't visible.
> Issue/6928: Remove Plans menu item for non-Admin users

- WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
`WPSplitViewController`'s 'dimming view' didn't position itself correctly for right-to-left layouts:
This PR fixes the issue by adjusting the placement of the dimming view based on the current interface layout direction:
To test:
* On iPad...
* Set your scheme's application language to "Right to Left Pseudolanguage", build and run
* On My Sites, navigate back to the Blog List, and you should see the detail pane dimmed out. Ensure the dimming view stays in the right place when rotating the device.
> Add RTL support to WPSplitViewController dimming

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
In #6285 we removed the custom font for blockquotes but neglected to remove the custom font size used for Merriweather-Light.  This PR corrects that oversight. 
To test:
Confirm the incorrect font size by comparing a blockquote text to regular paragraph text.  Switch to this branch and confirm that blockquotes are displayed in the correct font size.
Needs review: @jleandroperez could I trouble you again?
> Rich Text: Removes different font-size for blockquote and italics.

- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Fixes #6297 
The crash in #6297 occurs when the reader stream kicks off its auto sync while the detail is being viewed, and then the post shown in the detail is cleaned up by the sync.  This patch avoids the crash by deferring the auto sync until the stream is the visible controller.
It would be nice if at some point we could A) completely decouple syncing from the controller and B) have a nice way of making sure "active" content is not deleted while its needed. Maybe a separate persistent store.  For now this patch will avoid the crash until we can build out a more robust solution.
To test:
Follow the steps outlined in the issue.  Confirm there is no crash
> Reader: Wait to autosync while stream is hidden.

- WordPress/Classes/Utility/WPAvatarSource.h
- WordPress/Classes/Utility/WPAvatarSource.m
- WordPress/WordPressTest/WPAvatarSourceTest.m
Fixes a warning when running tests, an undeclared selector for `purgeCaches`. The warning is justified as we're just forcing a call there, without protection.
This revises our use of a private method and exposes it explicitly for testing.
To test:
1. Run the tests for `WPAvatarSourceTest` and ensure no warnings pop up.
2. 🍰 
Needs review: @diegoreymendez can you take a peak?
> Cleanup WPAvatarSource private test method use.

- Podfile
- Podfile.lock
Fixes #6273 
To test:
Try to get the app to crash with rotations, backgrounding, etc. Reproducing this crash is really really hard. I'm fairly certain the fix does resolve the problem and this is really just a sanity check for the pod version bump.
> Update Stats pod to 0.8.1 to fix rotation crash in graph VC.

- Rakefile
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #486
Project can now build from a path containing spaces.
- Rename folder containing the repo to contain a space
- Build
> Fix broken builds when path contains spaces

- WordPress/Classes/Extensions/Data.swift
- WordPress/Classes/Utility/PushNotificationsManager.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
The existing code relied on the specific `NSData.description` implementation.
Since the Swift 3 migration switched to `Data`, the `description` method did
not contain the hexadecimal data but just a simple description (32 bytes).
> Fix token registration with Swift 3

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Fixes #6344
Fixes a glitch I introduced when converting the comments refresh to Swift 3.
To test:
Repeat the steps in the issue and confirm images load correctly.  
Also confirm that cells and images are correctly sized when first downloaded and displayed in a cell.
Needs review: @nheagy could I trouble you with this one?
> Rich Text: Fix delegate method signature.

- WordPress/Classes/Networking/PostServiceRemoteXMLRPC.m
Fixes #6307
When creating a new post using the `XMLRPC` api, the service will now immediately fetch the post to get its metadata, such as `permalink`.  This allows the post-post view to show a live preview. 
Hopefully there are no unwanted side-effects…
1. Create a new post on a self-hosted site
2. Tap "View Post" from the post-post screen
3. Enjoy a live preview of the post
_This was all your idea_
> Add wp.getPost call after creating new post with XMLRPC

- WordPress/Classes/ViewRelated/Me/MeViewController.swift
- WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
In #6352 @aerych says:
> State restoration appears recently broken in develop on the iPhone (Swift 3 merge maybe?)
And you were right, the Swift 3 migration did some weird things to VC restoration code. And just for fun I hit a [compiler bug](https://bugs.swift.org/browse/SR-3465) while trying to fix this
To test:
Make sure restoration works in
- Me
- Reader
- Plans
> Make UIViewController restoration work again

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #6288
The previous fix did not work for long posts with no featured image displayed on the iPad.  For these posts, the geometry of the text view was not yet finalized by the time the offset was set (its width was too narrow). When the view received its final geometry the offset was adjusted to compensate for the change in size. This patch ensures the view is properly laid out before setting the offset.
To test:
Confirm the glitch in an iPad simulator.  DM me for sample posts, or find one of your own.  A long text post with no featured image should do the trick. 
Switch to this branch and confirm the fix. The post should load scrolled to the top.
Needs review: @bummytime would you be game to review this one?
> Reader: Make sure view is properly laid out before setting content offset

- WordPress/Classes/ViewRelated/Stats/StatsViewController.m
Fixes #5946 
To test:
In the iPhone simulator, browse to the stats screen and background/restore the app.
Stop the debug session, then relaunch the app in the simulator. 
Confirm that the app launches and restores the stats screen.
> Stats: Fixes state restoration.

- WordPress/Classes/Categories/NSString+Helpers.m
- WordPress/WordPressTest/NSStringHelpersTests.m
The existing regular expressions were way too greedy.
To illustrate what was wrong, imagine you have the following HTML:
```
```
The regular expression will start matching at the beginning and see a `<img` that matches.
```
^..^
/<img/
```
Then, it will advance any number of characters (.*) until it finds the next part of the expression (`src=`).
```
^.........^
/<img.*?src=['\"]/
```
Then it advances again until it finds a `wp-includes/images...`.
```
^..................................................X
/<img.*?src=['\"].*?wp-includes/
```
Since that doesn't happen, it backtracks to that `<img` and keeps advancing to find another `src=`.
```
^.........................^
/<img.*?src=['\"]/
```
Then it advances again until it finds a `wp-includes/images...`.
``` …
```
> Improve performance of Emoji regular expressions.

- WordPress/Classes/ViewRelated/Views/WPHorizontalRuleAttachment.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #6278
To test:
Check a post containing horizontal rules. For example: https://wordpress.com/read/blogs/53424024/posts/20733
Ensure the horizontal rules are displayed.
Needs review: @kurzee would you mind?
> Rich Text: Adds support for horizontal rules.

- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Fixes #6000 
This was an interesting one, thanks to @aerych for the really nice find a while back! As seen in #6000, some times the API may return posts out of the order from which they were requested with, such as asc/dsc dates, when the created date offset differs between posts.
I've fixed this by not relying on the direct order returned from the API and instead calculating our `oldestPostDate` with a manual compute on the returned results.
**To test:**
1. Open a site with a large amount of posts.
2. Scroll to the bottom and page through a series of pages of posts.
3. Ensure the paging is loading the correct posts as expected, compared with the list on the web or wp-admin.
**To test the original offset issue:**
1. Open up wp-admin for a test site with a few pages.
2. Find the two oldest …
> Posts/Pages Lists: calculate correct oldestPostDate from synced posts.

- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
I found that `WPPostViewController.h` was including two headers twice each. That's silly.
To test: Make sure it still compiles. If it doesn't, I'll lose faith in humanity. 
> Removed two duplicate headers from WPPostViewController.h

- WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
This was interesting one. A crash would occur in Reader when backgrounding the app during NUX, but only if the app is freshly installed.
In this particular scenario the `ReaderSearchViewController` is initiated via `initialDetailViewControllerForSplitView` as the initial controller. This is because the `ReaderTopicService.topicForDiscover()` topic is unavailable on first launch, otherwise discover would be loaded as a `ReaderStreamViewController`.
Since `ReaderSearchViewController` is initialized at first launch, if the user backgrounds the app during NUX, or before they login, the `encodeRestorableState` method will be called which triggers the crash at `if let topic = streamController.readerTopic` by unwrapping `fileprivate var streamController: ReaderStreamViewController!`.
So the fix …
> Reader crash while backgrounding

- WordPress/Classes/ViewRelated/Menus/MenuItemEditing.storyboard
- WordPress/Classes/ViewRelated/Menus/Menus.storyboard
- WordPress/Classes/ViewRelated/Menus/MenusSelectionDetailView.m
- WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.m
Fixes #5683
Readability fixes for the labels in the header. This was a bit of tech debt, but also more troublesome with our new split-view on iPad and iPhone Pluses.
In the Menus header, refactored to use a `UIStackView` and allow for properly resizing/truncating the selection labels when it's super long. Also updated the storyboards for Xcode 8.2 and fixed the compression issue for the "USES" label.
To test:
1. Open Menus on an iPhone Plus simulator or device, for a test site that has at least one Menu set up on it.
2. Rotate to landscape, this will bring in the split-view and compress the layout.
3. Type in a new, long name for the Menu currently selected (may be the "Default Menu").
4. Check that the "USES" label doesn't compress in width when you reach the truncated limit.
5. Tap on …
> Menus: Readability fixes

- WordPress/Classes/Networking/PostServiceRemoteOptions.h
- WordPress/Classes/Networking/PostServiceRemoteXMLRPC.m
Fixes #6392, #6391
Way back in https://github.com/wordpress-mobile/WordPress-iOS/pull/4840 we added support for searching posts via the `PostService`, but at the time XML-RPC was not obviously supported as per the documentation: https://codex.wordpress.org/XML-RPC_WordPress_API/Posts
For whatever mysterious, glorious, hidden reason, the XML-RPC does apparently in-fact support searching/filtering `wp.getPosts` with an `"s"` param under filters. Thus, we now support it in app as well.
To test:
1. Uninstall the app to ensure no posts are cached.
2. Add a self hosted site with more than 40 posts, or lower the default sync count on https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/PostService.m#L23
3. Select the Blog Posts list.
4. Don't scroll down.
5. …
> Posts: Super secret hidden support for searching remote posts via XML-RPC

- WordPress/Classes/Services/PostService.m
Fixes #6372 
I broke-diddy-oke attaching media to posts after they've been published in d707022d57210192da39240abcae5722bbe976b6. This puts back the missing functionality when I batched stuff.
To test:
1. Create a new post.
2. Attach an image (new one).
3. Publish the post.
4. Verify media is attached in wp-admin.
> Fixes a bork to properly attach media to uploaded posts.

- Podfile
- Podfile.lock
Fixes crash on gravatar change on an iPhone 4s.
To test:
- On a iPhone 4s
- Go to Me section
- Tap on the gravatar image
- Check if the app doesn't crash.
- Check on another device to see if it's working ok.
> Update media picker version to 0.10.3

- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Fixes #6388 
Currently the anonymous ID sticks around as long as the app isn't evicted from memory and the user ID property in `TracksService` isn't wiped. Technically the anonymous ID would be replaced every time the app is backgrounded (not on purpose) but isn't wiped due to it being stored in the `TracksService` instance.
This PR makes the randomly-generated anonymous ID for users not logged into WordPress.com a little more sticky. The anonymous ID, after being generated, is stored in user defaults. When the user logs in as a .com user the appropriate alias event is sent to Tracks and the anonymous ID is wiped out. If the user logs out from a .com account and then logs back in to another the anonymous ID is created for a brief moment to prevent aliasing in Tracks.
To test:
1. Set a …
> Makes Tracks anonymous ID a bit more persistent

- WordPress/Classes/Services/ReaderPostService.h
- WordPress/Classes/Services/ReaderPostService.m
Fixes #6404 
The reason cells were inactive after following a site is because the managed object context was being reset.  When the context is reset, the post object referenced by the cells is dealloced, which in turn means the guard checks on the cells cause certain actions to fail silently.  Scrolling away and back retrieves a fresh instance of the post from the context which is why everything works again. 
The reset is intentional, and necessary for the correct operation of the reader list. However its intended that a table view using a results controller backed by a managed object context that is reset, should in turn reload its data.  Since we silently fetch new posts for the followed sites topic whenever a post is followed or unfollowed, the table view was never reloaded. 
The meat …
> Reader: Improves the silent followed posts refresh.

- WordPress/Classes/Networking/BlogServiceRemote.h
- WordPress/Classes/Networking/BlogServiceRemoteREST.h
- WordPress/Classes/Networking/BlogServiceRemoteREST.m
- WordPress/Classes/Networking/BlogServiceRemoteXMLRPC.h
- WordPress/Classes/Networking/BlogServiceRemoteXMLRPC.m
- WordPress/Classes/Networking/RemoteBlogOptionsHelper.h
- WordPress/Classes/Networking/RemoteBlogOptionsHelper.m
- WordPress/Classes/Services/BlogService.h
- WordPress/Classes/Services/BlogService.m
- WordPress/Classes/Services/SignupService.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Blog/CreateNewBlog/CreateNewBlogViewController.m
- WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m
- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
- WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m
- WordPress/WordPressTest/BlogServiceRemoteRESTTests.m
Fixes #6120 
This refactor largely started to address the issue seen in #6120. However while working through the issue and where a sync can occur, it was quickly apparent we have a decent size of tech debt surrounding the different methods of syncing a blog, syncing it's settings, or options or details. I've run into this area of confusion before but never within the right context to take a moment and refactor.
The bulk of this PR moves around code, renames methods and updates code documentation comments. The primary goal was to better separate the concerns and paths between the `BlogServiceRemoteREST` and the `BlogServiceRemoteXMLRPC` and which remote can handle which type of sync or update.
Particularly, methods were moved out of the top-level `BlogServiceRemote` protocol and more …
> BlogService: Refactor for syncing a blog, settings, and options

- WordPress/WordPressShareExtension/MediaView.swift
Fixes #5689 
To test:
Prep: Make sure you have a photo with a visually distinct aspect ratio (4:1 or the like) for easier testing.
Confirm the bug by using the share extension with the photo and observe the photo is squished in the thumbnail. 
Run this test branch and confirm that the photo preserves its aspect ratio while being cropped to the bounds of the media view.
> Share Extension: Prevent images from being squished.

- WordPress/Classes/Services/BlogSyncFacade.m
- WordPress/Classes/ViewRelated/Blog/CreateNewBlog/CreateNewBlogViewController.m
@frosty originally discovered this issue when adding a self-hosted site in https://github.com/wordpress-mobile/WordPress-iOS/pull/6407, in which the categories failed to sync after login.
The source of the issue was that after creating a blog, the context was being saved via an asynchronous block as `performBlock:` in `[[ContextManager sharedInstance] saveContext:context]` which did not call and obtain permanent objectIDs in time for the blog object to actually be used right after being created.
The fix is to instead perform a synchronous save via `[[ContextManager sharedInstance] saveContextAndWait:context]` which will obtain permanent objectIDs and save the context before moving forward with the blog object. Thus allowing the blog to be fetched and used correctly later.
I also went …
> Blogs: Synchronous context save when creating a blog managed object

- WordPress/Classes/Extensions/UINavigationController+Helpers.swift
- WordPress/Classes/System/WordPress-Bridging-Header.h
- WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #6215. Default behaviour for the tab bar should be that if the user taps the currently selected item, the current navigation controller should pop back up to the root. This functionality broke when adding in UISplitViewController, so this PR restores it. 
If the current view controller is already at the root, we instead scroll its content back up to the top of possible / applicable.
I also took the opportunity to tidy up / refactor a little bit of code in `WPTabBarController`.
To test:
* Check that for each of the tabs in the app, with the split view both collapsed and expanded, that both the primary and detail navigation controllers pop back to the root if you reselect the current tab.
> Issue/6215 Tapping on the current tab now pops to its root

- WordPress/Classes/Models/Blog.m
Fixes #6396 
We we want administrators, editors, and author user roles to be able to use publicize, so we can just check for the `publish_posts` [capability](https://codex.wordpress.org/Roles_and_Capabilities) and we should be good to go. 
To test:
Repeat the follow steps with an account that has an editor role, and and account that has an author role.
Sign into the app.
Confirm the blog details screen shows the Sharing option.
Confirm the sharing screen shows publicize options but not the sharing button management option.
Confirm that a user with an administrator role has access to both the publicize and button management feature. 
Confirm that a user with a contributor role does not have access to the Sharing feature under Blog Details.
Needs review: @kwonye would you mind taking a look …
> Sharing: Allow publicize for authors and editors.

- WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
- WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
In this (small!) PR we're addressing few of the new compiler warnings we're getting. Don't worry, we'll get to zero in #6425.
- Verify that the app builds correctly
- Verify that ReaderSearch works as expected (cc @aerych)
- Verify that WPSplitViewController works correctly as well (cc @frosty)
Needs review: Invoking my personal friends, @aerych, for **ReaderSearchViewController**, and @frosty for **WPSplitViewController**.
> Fixing Build Warnings

- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Reselecting the previously selected row when the row currently been selected shouldn’t show the selected state and the split view controller is horizontally compact.
Fixes #6176
To test:
1. Cells remain selected on split view mode
2. Cells don't remain selected in horizontally compact mode (no detail view visible)
Needs review: @
> My Sites: Stats cell highlighted on iPhone after opening site dashboard

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
This PR updates the navigationBar, so that the Switch **HTML <> Rich** toggle is moved to an Action Sheet button.
This matches the Hybrid Editor, and makes room for `Settings` // `Post` actions.
1. Launch the Aztec Editor
2. Verify that the top right corner has a three dots button
3. Press over the `ellipsis` button
4. Press the Switch action
5. Please, verify that everything works as expected. 
6. Press the Cancel action
7. Verify that the Editor gets closed
> Aztec: Navbar Actions

- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Fixes #6394 
To test:
Tap the View button on a post in the post list. 
Confirm the title of the preview controller is "View"
Tap to edit the post
Tap the menu button and choose the Preview option.
Confirm the title of the preview controller is "Preview"
Needs review: @diegoreymendez do you have time for a quick review?
> Posts: Set the title of the preview controller for consistency.

- Podfile.lock
- WordPress/Classes/Utility/PingHubManager.swift
- WordPress/Classes/Utility/PushNotificationsManager.swift
I've combined a bunch of small fixes into this one for the finishing details for PingHub:
- If the application is active, it now ignores push notifications, as we assume we'll get them through pinghub. #5894 might change this in the future though
- Updated Starscream. My [previous patch](https://github.com/daltoniam/Starscream/pull/294) introduced a new bug that meant the delegate/callback wasn't being called correctly on disconnect.
- This, combined with the delayed retry made the state machine confused when coming from the background, and there was a lot of reconnection, since `connect` would `disconnect` the socket if it was already connecting, changing the state again 🙄 I added a `guard` for sanity so we don't call `connect()` if we're connect(ing|ed).
- Besides (dis)connecting from …
> PingHub wrap up

- WordPress/Classes/Utility/Gravatar.swift
Fixes #6320 
Make sure we're downloading the right sizes for the Gravatars
As mentioned in #6320, I think large Gravatar requests is what was causing them to fail in the first place. I haven't tackled the issue of retrying to load gravatars if they failed, but it seems like it'd take a major refactor of how we load images. So, for now, I believe this will be good enough until we can devote some time to improve image loading.
To test:
Browse around the app all views that show gravatars, and ensure we're fetching the right size. What I did was to set a breakpoint in Gravatar.swift:
```Downloading avatar of size @size@: @gravatar.canonicalURL.lastPathComponent@```
> Force layout before requesting Gravatar size

- WordPress/Classes/ViewRelated/NUX/SigninSelfHostedViewController.swift
Fixes #6448 
When the user signs into a self-hosted site, we now mark it as the 'last used' site so that it'll get auto selected in the blog list view controller.
To test, follow the steps outlined in the original issue and ensure the new blog gets selected.
> Issue/6448: Fix auto selection of newly added self hosted sites

- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
Fixes #5489 
Similar to https://github.com/wordpress-mobile/WordPress-Android/pull/4181, this patch limits the username and site name fields to lowercase alphanumeric characters.
To test:
Repeat the steps outlined in the issue and confirm that capital characters typed are automatically lowercased and that punctuation is not accepted.
Needs review: @frosty could I trouble you with this one?
> Sign up: Username and site are a-z0-9 only.

- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Just as we don't show errors on sync unless it was user initiated, avoid
presenting an alert if infinite scroll was triggered.
The deeper issue is that the infinite scroll code is triggered from
willDisplayCell which doesn't only get called as you scroll, but also whenever
we update the table data (i.e. every core data save).
There is a lot of room for improvement there, but this will at least avoid
presenting the user with countless alerts when trying to write a post while
being offline.
Fixes #4993
To test:
- Launch the app while in Airplane Mode
- Go to a site's post list
- Add a new post 
- Write a title and some content
- No offline alerts should display while editing the post
> Don't show errors if load more fails on posts.

- WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
I've been experiencing a crash, in develop, after trying to launch 1Password (see screenshot below!).
(For some unknown reason!) the forced cast of the closure isn't working anymore // now it's breaking.
0. Make sure you've got 1Password Installed!
1. Fresh install the app
2. Press the 1Password button
Verify that nothing breaks!
> SigninHelpers: Fixing 1Password Crash

- WordPress/Classes/ViewRelated/NUX/Signin.storyboard
- WordPress/Classes/ViewRelated/NUX/SigninEmailViewController.swift
Instead of presenting shared credentials as soon as the view appears for `SigninEmailViewController`, or as soon as a user opens the app, now present the credentials when they tap on the username/email textfield.
When discussing this with @mattmiklic, the idea I had here was to get away from instantly presenting the credentials picker and instead allowing a user to soak up the actual first NUX view. This also allows a user to instead add a self-hosted site or choose the 1Password option, without having to dismiss the credentials picker each time (if they had some available).
I think this cleans the experience up a bit for our users to not be so surprised by the picker immediately every time the app is opened, without being logged in.
Any additional thoughts or concerns @mattmiklic?
To …
> NUX: Instead, present shared credentials when tapping the text field.

- WordPress/Resources/HTML/defaultPostTemplate.html
Fixes #6384 
To test:
Create or edit a post and add a few images.
Edit each image and set its alignemnt to left, center, right.  Optionally set the image size to thumbnail to help it fit on screen.
Back on the editor screen, tap the menu button and choose Preview from the options. 
Confirm that the images are shown the the correct alignment.
Needs review: @nheagy could I trouble you with this one?
> Editor Preview: Adds css classes for alignment.

- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
While there is some value on letting users know they're editing a post that has
local changes, the alert is very disruptive and causing some issues on
restoration.
Fixes #6367 
To test:
- Create a new post, type some title/content
- Switch to airplane mode and publish
- From the posts list, locate the failed post
- Open the post, no alert should show
> Remove Unsaved Changes alert

- WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
Fixes #4079 
When showing a post preview, the loading view can reappear for every request made by the webview to fetch content.  This PR limits the spinner to appearing for just the initial page load. 
Before:
https://cloudup.com/ipfjb-ASyqx
After:
https://cloudup.com/i8mlQrpM9Lg
To test:
Preview a post that has a lot of remote content.  Embedding some video links and images should do the trick.
Ensure that the spinner does not flicker. 
Needs review: @bummytime would you mind taking a peek at this one?
> Post Preview: Prevent spinner from flickering.

- WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
Titles for X-Posts were showing as Optional. This patch adds a default of `""` for nil titles so they show correctly.
> Fix "optional" X-Post titles

- WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift
As reported in #6480, the contact support button on the plan details screen didn't work. 
> Fix Contact Support on plan details

- WordPress/Classes/Models/Plan.swift
- WordPress/Classes/Networking/PlansFeaturesRemote.swift
- WordPress/Classes/Networking/PlansRemote.swift
- WordPress/Classes/ViewRelated/Plans/FeatureItemCell.swift
- WordPress/Classes/ViewRelated/Plans/FeatureItemRow.swift
- WordPress/Classes/ViewRelated/Plans/PlanListRow.swift
- WordPress/Classes/ViewRelated/Plans/PlanPostPurchaseViewController.swift
There may be a better solution here, but a plan feature with an empty icon URL string was causing the guard checks to throw out of the try attempting to decode the JSON. In this case it was the Google Analytics feature that had an empty icon string.
Since the Swift `URL(string:)` init method may return `nil`, I thought it might best to go ahead and account for any other empty icon strings, and declare the use of iconURLs as optional. This tweaks the code a bit to account for that.
To test:
1. Open up Plans, tap on a plan.
2. Make sure it loads, as do the other ones.
Needs review: @frosty can you take a look? I believe you're much more familiar with this code and wrote most of it? Let me know if there's something else entirely we should be doing here.
> Plans: allow for optional icon URL from plan features

- WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.xib
This PR tweaks the reader comment cell layout a bit to reduce the amount of indentation of the content.  Content is now left aligned with the avatar.  This helps nested content from getting too squished while maintaining a clear indication of how nested a comment is.  This also is consistent with comment layout in the Android reader.  (cc @nbradbury) 
Example:
To test:
Confirm the xib does not have any issues with frames, constraints, or unused views after the changes.
FInd a post with threaded comments and view it in the reader.  Confirm that threading is correct as described above.
cc @rachelmcr
> Reader: Tweaks indentation of reader comment content

- WordPress/Classes/Extensions/UINavigationController+SplitViewFullscreen.swift
Fixes #6494. 
This was caused by the first half of the Reader fullscreen transition happening when selecting a post in Notifications. Normally, the split view controller (acting as navigation controller delegate) completes the transition when the push finishes. I've tweaked the fullscreen push so it'll only trigger the transition if we're actually running in a split view controller.
To test: follow the steps in the original issue, ensure that the navigation items stay visible!
Thanks for spotting this!
> Issue/6494 Notifications: Fix disappearing navigation items

- WordPress/Classes/Utility/PingHubManager.swift
For some reason, I had this idea that `isReachable` could return the wrong value initially and that we had to wait for a reachability changed notification. Maybe that was the case in an older iOS version. So I initialized the state with `reachable = true`.
TIL that `isReachable` (through `SCNetworkReachabilityGetFlags`) is synchronous, so you can call it whenever you want.
Fixes #6487 
To test:
- Switch on airplane mode
- Look at the console and make sure PingHub doesn't try to connect
> Initialize PingHub with the actual reachability

- WordPress/Classes/ViewRelated/Post/PostEditorSaveAction.swift
Fixes a crash we've been seeing where the editor is recreated without a post. Obviously this doesn't fix the root cause, but should at least prevent the app from crashing.
The editor's post is implicitly unwrapped, but now we're explicitly unwrapping it.
> Fixes a crash in PostEditorSaveAction

- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
This fixes two issues I've noticed with Reader comments while working on Notifications readability.
1. The no results view would hang around after loading a `ReaderCommentsViewController` for the first time.
- This is fixed by async dispatching the `success` block after `syncHierarchicalCommentsForPost` is called. There is a point in which the no results view was checking the `resultsController` for a count before it was actually ready, after syncing.
2. The cells would some times jump or bump in size when reloading a `ReaderCommentsViewController` that already had cached data.
- This is fixed by using the familiar method of caching estimated heights for rows using `UITableViewAutomaticDimension`. This is kind of duplicate code in other multiple VCs, so I'm going to refactor later to …
> Reader Comments: reloading issues with jumping and no results label

- WordPress/Classes/ViewRelated/NUX/NUXAbstractViewController.swift
- WordPress/Classes/ViewRelated/NUX/Signin2FAViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninErrorViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninLinkRequestViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninSelfHostedViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninWPComSyncHandler.swift
- WordPress/Classes/ViewRelated/NUX/SigninWPComViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
Fixes #6510 
To test:
- intentionally encounter an error while signing up for WordPress.com (a single letter password works)
- on the error screen, tap "Contact Us"
- Enter some text
- Check the created Helpshift issue to ensure it has the proper tag of `origin:signup-screen`
> Add source tag arg to NUX error screens

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
This PR adds media downloading for the Aztec editor.
This use the AFNetworking Image download cache mechanism to manage the requests.
To test:
- Open a post that is already published and has images on it.
- Check if the images are dowloaded a displayed correctly.
- Check if while images are being downloaded a placeholder is show.
Check this on wp.com sites and wp.org sites and on private wp.com sites. 
> Add media downloading for image already existing in a post.

- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes a breaking constraint to do an invalid height value.
To test:
Confirm the bug by viewing a comment notification, then viewing that notification's list of comments. Note that the console logs a warning about the breaking constraint. 
Switch to this branch and repeat the steps above. Note that the warning is gone. 
> Reader: Fixes warning about breaking constraint.

- Podfile
- Podfile.lock
This PR updates the Aztec's Dependency, to the latest commit. The crash outlined in #6502 has been [fixed in this Aztec PR](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/pull/231).
Closes #6502
Please, give it a smoke test, and make sure everything looks fine.
> Updating Aztec Dependency

- WordPress/Classes/ViewRelated/Me/AboutViewController.swift
Fixes #6533 
To test:
- Go to Me > App Settings > About WordPress for iOS
- Verify that the copyright footer shows correctly
> Fix Optional string in copyright year

- WordPress/Classes/Models/Post.swift
- WordPress/WordPressTest/PostTests.swift
Fixes #6522
To test:
- Edit a Post
- Enter a simple Tag (remember how many characters it has)
- Save the Post
- Edit the Post, changing the Tag to something that has the same number of characters as before
- The Update button on the Post edition screen should be enabled
Needs review: @kurzee @diegoreymendez 
CC: @sendhil
> Fixes bug with changes detection for Post Tags

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Closes #6503
1. Log into a dotcom account with a single site
2. Enable Aztec
3. Open the Editor from the **New Post** action / **Edit Published Post** / **Edit Page**
Verify that the Site Picker doesn't display an arrow downwards. Plus, please, verify that pressing over the Blog's Title doesn't result in **any** action at all.
1. Log into a dotcom account with multiple sites
2. Enable Aztec
3. Open the Editor from the **New Post** action / **Edit Published Post** / **Edit Page**
Verify that the Site Picker **does** display an arrow downwards. 
Plus, please, verify that pressing over the Blog's Title doesn't trigger an assertion.
Pressing over the Blog's Title, should result in:
A. Blog Picker onscreen, if the post had no changes
B. AlertView indicating the 'Change Site' effects, and …
> Aztec: Disabling BlogPicker Button in Single Site Mode

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
In this PR we're nuking the call to `loadMerriweatherFontFamily`. Reason why we were getting that warning is:
- `loadMerriweatherFontFamily` actually calls `loadFontResourceNamed` for every single Merryweather font we've got
- Whenever you actually call any of the `merriweather*FontOfSize`, internally, if the font is not available, `loadFontResourceNamed` is executed
- The app is using Merryweather Regular elsewhere. Meaning that the font was already preloaded, way before Aztec gets launched.
In other words, the warning was being printed because Merryweather Regular Font was already loaded.
Fixes #6493
Please, just launch the Aztec editor, and verify that the warning is gone.
> Aztec: Fixing Font Load Warning

- WordPress/Classes/ViewRelated/Post/PostPostViewController.swift
Fixes #6544 
Sharing could cause post-post to make the app unresponsive. There may have been other undiscovered cases that caused this which will be fixed as well.
To test:
_On an iPhone:_
1. Create a new post and publish it, to get the post-post screen
2. Tap Share
3. Tap Message or Mail
4. Don't share, instead tap Cancel
The post-post should reappear, and be completely functional
Got time for this one?
> Fix post-post causing unresponsive app

- Gemfile.lock
- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/Services/WordPressXMLRPCAPIFacade.m
- WordPress/Classes/Utility/WPError.m
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
- WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
1. use https://github.com/rbenv/ruby-build to build and install ruby-2.4.0 $HOME/ruby/
2. export PATH=$HOME/ruby/bin:$PATH
3. gem install bundler
4. rake dependencies ...
5. apply the patch to some *.m as the the compilation run on case sensitive HFS file system.
Fixes # mainly step 5 which import <WPXMLRPC/WPXMLRPC.h> and "WordPress-Swift.h".  Also compile ruby-2.4.0 from source and installed locally to run rake dependencies
To test:  git clone the source to HFS case sensitive filesystem and compile the source
Needs review: @
> Fixes issues with building on a case-sensitive file system

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Make sure Merriweather-Italic is loaded before using it on reader comments
Fixes #6564
To test:
- Launch the reader and visit a post with a comment that has `<em>` text
- Make sure it's using Merriweather
> Fix italic font on reader comments

- WordPress/Classes/Services/ReaderPostService.m
Closes #6459 
Refs: #6546
This is an improved fix for the issue causing our infinite scroll stat to be spammed.  Here we assume that there is no more available content for a topic when the REST API returns fewer results than expected.  Tag topics are excluded as it is expected we'll receive fewer results than requested due to anti-tag spam measures.
To test:
Take the reader for a test drive.  Confirm that the load more feature continues to function as expected for the default lists, tags, and sites. 
Test a site stream known to previously trigger a load-more refresh loop (ping me for an example). Confirm that the loop no longer occurs.
Needs review: @kurzee, I think we finally got it squared away. :)
> Reader: Assume no more content when receiving less posts than requested.

- WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.xib
Fixes #6567 
The stackview for the header had its alignment set to fill which ended up cropping the label.  This PR changes that setting to `top` allowing the stackview to accommodate the full label height. 
To test:
View reader comments and confirm that the date label is no longer cropped
Needs review: @frosty would you do the honors?
> Reader Comments: Fixes stackview alignment setting so label isn't cropped

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
This PR allows to cancel ongoing media uploads on aztec and/or remove media objects
To test:
- Start a new Post using Aztec
- Insert media on the post
- While the media is uploading, long press on the media object.
- An action sheet should show with two options: Dismiss and Cancel Upload
- Tap on Cancel Upload and see if media gets remove and upload is cancelled
- Double check on server to see if no media showed up there
- Repeat but only press after upload finished
- Check if instead of Cancel Upload it shows Remove Media
- Tap on Remove Media and confirm that media is removed.
- Next insert media again and remove it using the backspace
- Check if media stop uploading and doesn't go to the server
> Aztec Media upload cancel

- WordPress/Classes/Services/ReaderTopicService.m
Fixes #6457 
To test:
Follow the steps outlined in the issue and confirm you can no unfollow the deleted blog.
Needs review: @jleandroperez would you do the honors?
cc @nbradbury
> Reader: Unfollow deleted site by URL.

- WordPress/Classes/ViewRelated/Menus/MenusViewController.m
Fixes #6483
This resolves the issue in #6483, nice find @hoverduck!
Since the newly created Menu object was never saved, it was never persisted beyond our context's undo manager for Menus. Thus, once discarding the changes and calling `undo` on the context's `undoManager`, we lost the need for saving the originally selected Menu since we ended up at the currently selected Menu, anyways.
To test:
1. Follow the steps in the original issue.
Bonus steps:
1. Open Menus.
2. Add a new Menu by selecting from the Menus drop down, hit "+ Add New Menu".
3. Save that menu, back out of Menus.
4. Go back to Menus, should now see your custom Menu in place.
5. Add a new menu, don't save it.
6. Re-select your previous menu.
7. Discard changes.
8. Save should be disabled.
Needs review: @aerych  can you …
> Menus: avoid selecting and enabling a save for the default menu

- WordPress/Classes/Extensions/String+Helpers.swift
- WordPress/Classes/ViewRelated/Post/PostPostViewController.swift
- WordPress/WordPressTest/Extensions/StringHelperTests.swift
Fixes #6435 
To test: Create a new post with title: And <em>here?</em>
The html tags are stripped in post post view
> Strip html from post title in post-post

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
- WordPress/WordPressTest/ViewControllers/MediaProgressCoordinatorTest.swift
This PR implements to retry failed upload of media.
To test:
- Create a new post using Aztec
- Turn on Airplane mode
- Add media to the post
- check if error message shows overlaying the image.
- Long press on the image
- Turn off Airplane mode
- On the action sheet choose retry upload
- see if upload finishes correctly.
> Allow to retry failed uploads.

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
This PR updates Aztec's Post Removal logic. Apologies about the misunderstanding, this bug is also present in the Hybrid Editor (and i was replicating precisely that!).
Fixes #6587
1. Launch WordPress iOS and enable **Aztec**
2. Open **My Sites** > **Any Site**
3. Open the Post List
4. Press the top right `+` button to create a post
5. Dismiss the editor
6. Verify that the draft gets effectively nuked
7. Try editing a post from the list
8. Dismiss Aztec
9. Verify that the post you've just edited does not get nuked from CoreData
Thanks Diego!!
> AztecPostViewController: Updates draft removal logic

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
In this PR we're bringing back the Force-Load Merryweather Fonts call. This is known to be triggering a warning, whenever a font was already preloaded.
We've nuked this call, not long ago, but definitely missed the crash!!
2. Toggle Italics
3. Verify that the app doesn't break
Needs review: @astralbodies / @diegoreymendez 
> Aztec: Force Load Merryweather Fonts

- WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
Fixes #6604
The post preview's Done button should now always appear when presented modally, which is how the post-post screen presents it.
To test:
1. Publish a new post
2. Tap "View Post" on post-post screen
3. Tap the share button
4. Tap Messages
5. Hit Cancel
6. Ensure that the preview can still be dismissed via the Done button
Needs review: @kurzee  
Brent, have time for this one?
> Fix preview done button

- Podfile
- Podfile.lock
<h3>Description:</h3>
Updates to Gridicons 0.4. (using the pod version rather than the tag)
<h3>To test:</h3>
Run `pod install`.
Run WordPress iOS tests.
> Updates to Gridicons 0.4.

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Notes in the "Unread" filter would disappear as soon as you read them, making
it a bit confusing.
This keeps a list of notes that were unread for as long as the Unread filter is
selected, unless you pull to refresh.
Fixes #4420 
To test:
- Launch notifications and switch to unread
- Make sure there are some unread notes
- Visit an unread note and go back to the list, it should still be there
- Switch to another filter, or pull to refresh, "Unread" should not have any read notes now
> Keep read unread notes a little longer.

- WordPress/WordPress.xcodeproj/project.pbxproj
To test:
* Build develop before this branch to compare times from clean & also single file change.
* Try running on a device as well.
Thanks!
> Reduced build times for debug builds by skipping dSYM creation

- .gitignore
This PR removes the duplicate .DS_Store in .gitignore.
> Remove duplicate .DS_Store in .gitignore

- WordPress/Classes/ViewRelated/Reader/Reader.storyboard
- WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Closes #6127 (tho not via a stackview)
Fixes an issue in the reader's detail where a long tag could overlap the like and comment buttons. (h/t/ @melchoyce)
This PR adds a missing constraint, adjusts content compression resistance values, and ensure that truncation occurs at the end of the button label.
Before:
After:
To test:
Test the branch with a very long tag.  Confirm the tag truncates rather than overlaps. 
Test the branch with a short tag.  Confirm that layout remains as expected.
Needs review: @bummytime could you take a peek at this one?
> Reader: Truncate long tags so they don't overlap action buttons.

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Fixes: https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/250
How to test:
- Open Safari and open a site
- Tap on share icon on Safary and select the option Copy
- Jump to the Aztec demo app
- tap on the link button in a area where a link doesn't exist
- check that the link URL is pre-filled with the link copied from Safari
> Copy paste link to link dialog if a link is available.

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #6288 (again :p )
I haven't traced this cause of this one back to a specific commit, but I'm guessing its related to reverting the full screen detail. 
The behavior we're seeing currently is the view, and subsequently the textView, do not have their final geometry until after `viewWillAppear:` has been called, and not until a subsequent call to `traitCollectionDidChange:`.  This differs from earlier behavior where the correct geometry was available immediately after the view was loaded. This is problematic for the textView as updating its contentInsets to match readable content margins affects its scroll offset,  hence the reemergence of the glitch.   This PR provides a temporary patch for this behavior until the full screen reader detail is restored.  
To test:
Like the example …
> Reader: Ensure the scroll offset is not affected when traits are updated

- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
> Fix encoding in TOS footer

- WordPress/Classes/Networking/WordPressComServiceRemote.h
- WordPress/Classes/Networking/WordPressComServiceRemote.m
- WordPress/Classes/Services/SignupService.swift
- WordPress/WordPressTest/WordPressComServiceRemoteRestTests.swift
Fixes #5244 
To test:
- Switch phone to a non-English language (or change language in scheme editor)
- Run the app and sign up for a new site/account
- Verify that both the account and site language are set to the device language
> Include locale when creating account

- WordPress/Classes/Extensions/UINavigationController+SplitViewFullscreen.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
- WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
Fixes #6478. Reopening #6557 against `develop`.
@kurzee, I think I've fixed up the couple of issues you were seeing: I've disabled the automatic cell deselection in the reader list when reduce motion is on (which should hopefully fix the flicker – I don't see any on my device), and I've fixed the broken cell selection when collapsed.
Make sure you test on a device, as the transition won't look right on some simulators, and check when the split view is both expanded and collapsed. Thanks!
> Respect "Reduce Motion" accessibility setting for fullscreen transition

- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
In this PR we're fixing a retain cycle: just marking a delegate as `weak`. 
Please, note that **AztecPostViewController** won't get deinitialized after dismissal, not even after applying this patch, since there's yet another Retain Cycle affecting Aztec's Format Bar (shipping a PR to get that one fixed right away).
Please, verify that the app builds correctly.
> Aztec: Fixing Retain Cycle

- WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
Closes #6596 
To test:
Be logged out of the app.  
Sign in to wpcom and confirm the reader defaults to the Followed Sites stream.
Be logged out of the app. 
Sign in to a self-hosted site and confirm that the default is still Discover.
Needs review: @nheagy could I trouble you with this one?
> Reader: Makes the followed sites stream the default.

- WordPress/Classes/ViewRelated/Post/PostSharingController.swift
- WordPress/WordPressTest/Posts/PostSharingControllerTests.swift
Fixes #6645 
To test:
- On a device, review a post in the post list
- Tap the share button
- Share to Messages
- Observe that tags aren't included in the Message
Hey Eric, trade ya?
> Remove tags from post sharing

- WordPress/Classes/Utility/PhotonImageURLHelper.h
- WordPress/Classes/Utility/WPImageURLHelper.swift
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
This PR fixes an issue where images where being fetched on Aztec using incorrect dimension causing crop of images.
To test:
- Create a post in Aztec
- Insert an image on it
- Check that after the upload is finished the image stays with the same aspect ratio and no crop is applied.
- Check on wp.com and .org sites.
> Correct the requested size of images.

- WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift
Dancing a bit on the insane side of things...
The test `testPixelSize` on `MediaLibraryPickerDataSourceTests` was crashing when you ran _all_ tests for our WordPressTests project. However, the test class itself would _not_ crash and would pass if you simply ran `MediaLibraryPickerDataSourceTests` by themselves, or even the individual test `testPixelSize` by itself.
So seemingly, you can fix this by simply renaming the test method from `testPixelSize` to anything else, such as `testMediaPixelSize` in this PR, for example. Why? I'm not sure. Swizzling issue? Maybe namespace collision with our other uses of `pixelSize`? Not clear to my eyes at the moment.
To test:
1. First run all tests on `develop` to see the original crash.
2. Switch to this branch `issue/media-broken-test-method` with the …
> Media tests: change name of method to fix test, for whatever reason.

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Fixes #6517 
This was a peculiar bug that I took a crack at after @frosty wanted a second set of eyes on it for his split-view implementation.
It wasn't super clear what was going on with the issue, but it did replicate every time. I guessed that after we nuke the notifications objects and save the context in `resetNotifications`, we need to go ahead and do a hard `reloadData` to wipe out the tableView, before subsequently pinging the `resultsController` afterwards during the account transitions.
Not 100% confident in this, but I am decently confident in it 😎 
To test:
1. Repeat the steps in the original issue, and also try with a different account when logging back in.
Needs review: @aerych can you take a spin since you found the original issue? Also, cc @jleandroperez for any obvious …
> Notifications: reload the tableView after nuking notifications

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
I still can't reproduce #6341 so I have no idea if this would fix it, but it seems like a possible fix.
Since the section identifier is based on a relative date and might change at midnight, this would ensure that we reload the results controller in that case, or when the time zone changes.
> Reload notifications on significant time changes

- MIGRATIONS.md
- WordPress/Classes/Models/Blog.h
- WordPress/Classes/Models/Blog.m
- WordPress/Classes/Models/Post+CoreDataProperties.swift
- WordPress/Classes/Models/Post.swift
- WordPress/Classes/Services/BlogService.m
- WordPress/Classes/Services/PostService.m
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController_Internal.h
- WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 56.xcdatamodel/contents
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/PostTests.swift
Fixes #2698 
To test:
1 - Configure at least one Publicize Connection for a Blog
2 - Create a new Post
3 - Navigate to the Post Settings
4 - Edit the Publicize Message
5 - Enable/Disable some connections for the Post
6 - Publish the Post and check that it's shared to the selected Publicize Connections with the correct message
When sharing is not supported or there are no Connections setup the Sharing section is completely hidden.
If the Post has been published the Sharing section and its items are disabled.
Needs review:  @jleandroperez @kurzee @koke 
CC: @sendhil 
How the API handles enabling/disabling Publicize Connections:
**_Fetching disabled connections_**
Disabled publicize connections are returned for every post in the metadata section:
```
...
"metadata": [ 
{
"id": "270",
"key": …
```
> Support publicize on posting

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Fixes #6656
0. Launch WPiOS on an iPad Device
1. Open Aztec and type some content
2. Press the top right `...` button to display the **More** action sheet
3. Verify that pressing the top left `x` button dismisses the popover
4. Press the top left `x` button to display the **Dismiss** action sheet
5. Verify that pressing the top right `...` button dismisses the popover
6. Add an image to the post
7. Double tap over the asset to trigger the Image Actions popover
8. Verify that pressing over the top left button (`x`) or top right (`...`) dismisses the popover
Thanks for helping me out @SergioEstevao!!!
Closes #6656
@astralbodies ain't this an (extra) evil PR? 6666!
> AztecPostViewController: Sheet Passthru Fix

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
Fixes #6662
As requested, making the spacing between the arrows a bit tighter, and changed the order of buttons (now it's ⬆️ ⬇️ )
Needs review: @jleandroperez @mattmiklic
> Adjust up/down buttons for notifications (7.0)

- WordPress/Classes/Extensions/UIView+Helpers.swift
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
- By default, the Title TextField will become the first responder
- Whenever Aztec is about to disappear, we'll store the previous First Responder
- On viewWillAppear, we'll restore the previous first responder
- Did some cleanup in `UIView+Helpers`!
Closes #6673
2. Verify that the Title TextField is the First Responder
3. Press the TextView
4. Open `More` (Top Right navBar button) > `Options`
5. Return to Aztec
6. Verify that the TextView becomes first responder, again.
> Aztec: First Responder Handling

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Changes the native editor's placeholder text to be darker, and to read "Title" like in Calypso.
Fixes #6693 
Fixes #6687 
To test:
1. Launch the native editor.
2. Make sure the placeholder text for the title field reads "Title".
3. Make sure the placeholder text color for the title field matches the hybrid editor's.
> Improves the title placeholder for the native editor.

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
This fixes the issue in which a button in `NoteBlockActionsTableViewCell` would break out of its `isHidden` layout when hidden in the stackView.
Since we're doing custom layout on `layoutSubviews` for these buttons with `VerticallyStackedButton`, we need to just go ahead and hide these buttons altogether when hidden, via `alpha`.
Note: I thought about not using alpha, but all alternatives point to a refactor of these buttons/action views. For another day.
To test:
1. On iPad, landscape, open a Notification comment.
2. Pull in a multitasking split that takes up the right third of the screen space.
3. Notice a reply action button is still available.
4. Rotate to portrait, but keep your eye on the reply button. It should disappear with ease and not stick around after the orientation change. …
> Notifications: fix for broken layout of action buttons

- WordPress/Classes/ViewRelated/Blog/SiteManagement/StartOverViewController.swift
- WordPress/Classes/ViewRelated/Blog/SiteManagement/TableViewHeaderDetailView.swift
This PR reworks our custom `TableViewHeaderDetailView` for readability and autosizing, which is currently only used in `StartOverViewController`.
Particularly, we really just wanted to get away from its use of custom margins and `WPTableViewFixedWidth`, and rely on readable margins instead. We also autosize it via automatic dimension.
To test:
1. Open up Site Settings on a .COM site.
2. Scroll down, open up the Start Over selection.
3. Check that the header view with labels is loaded correctly and aligned with the expected readable margins.
4. Check on iPad, iPhone and iPhone Plus.
Needs review: @frosty can you take a look? (no rush)
> Site Management > Start Over: readability and autosizing

- WordPress/Classes/Utility/PushNotificationsManager.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingStreamsViewController.swift
- WordPress/WordPressTest/PushNotificationsManagerTests.m
This PR addresses the pending Build Warnings we've got, related to Notifications.
**Please review / merge this one after #6684 gets approved!**
cc @koke 
1. Log into wpios
2. Open `Me` > `Notification Settings`
3. Pick any of your websites
4. Verify that the `Push Notifications` row doesn't say *off*
5. Switch to **Settings.app* and disable wpios's push notifications
6. Switch back to **WPiOS** and verify that the Push Notifications row displays an `Off` legend
7. Press over the Push Notifications Row
8. Verify that there's a single row onscreen, which allows the user to open the Settings.app entry
9. Enable WPiOS's Push Notifications
10. Switch back to WPiOS and verify that the Push Notification (Fine-Grainted) Settings are onscreen
> Fixing notifications ios10 warnings

- WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
Adds a much-needed question mark to the tag removal alert, to protect my sanity.
> ReaderMenu: Improves punctuation of the tag removal alert

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
Looks like had a bad change on the Notification split-view PR, which compiled fine previously but fails since the iOS 10 only requirement.
Either way, looks like we probably didn't have these same buttons, anyways, but failed gracefully.
Reworked to share how the buttons are set as `rightBarButtonItems`.
To test:
1. Build without error 😄 
2. Open Notifications on iPhone, select a notification.
3. Check that the up/down navigation arrows work.
4. Open on iPad, select a notification.
5. Check that the up/down arrows are not shown.
6. Pull in a multitasking split until the left pane collapses.
7. Check that the notification detail arrows are then available and work.
cc @frosty just in case something needs to be changed later
> Notifications: fix issue with a bad wrap for how we set nav buttons

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
This is a leftover Notifications readability change, which I didn't notice before.
I reworked our `maxMediaWidth` calculation to instead rely on the `readableContentGuide.layoutFrame` for an expected max width. This allows wide images to correctly size up for our expected readable width, vs the ole fixed width or view width it used before.
To test:
1. Add a wide image (like a desktop wallpaper) to a comment on a site. You can easily add an image by editing the comment in WP-Admin.
2. In the app, log into the account which would have the corresponding comment notification with the insert image.
3. Open the detail notification view of that comment notification.
4. Ensure the maxWidth is as expected for an image that's wide enough to fill.
5. Check on iPad, iPhone and iPhone Plus.
6. Also …
> Notifications: use readable width for maxMediaWidth in comments.

- WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
Fixes #6670.
Note that the reproduction steps are slightly incorrect in the original issue. See 'to test' below for replication steps.
I wanted to fix this in the Reader detail VC, as that's the one that hides the bar in the first place. But it turns out that its `navigationController` gets set to `nil` as soon as `popToRootViewController` is called. I also could've set it in the navigation controller delegate, but I didn't want to presume to update the bars for any and every navigation controller. 
So I've opted to just set it in the method that takes care of popping to the root when you tap on the currently-selected tab bar item.
To test:
1. Open a post in the Reader
2. Scroll down to cause the top bar to hide
3. **Tap the Reader tab bar item to pop back to the Reader menu**
4. …
> Split view: Ensure nav bar is visible when popping to root.

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Fixes a crash that occurs after the newly merged split-view implementation.
Basically, we just needed to `nil` the `selectedNotification` when we call `resetNotifications`. Otherwise the object is no longer valid when we try to use it, after being nuked.
To test:
1. Open Notifications, select a notification to view the detail.
2. Switch to Me tab.
3. Log out
4. Log back in.
5. Don't crash.
6. Everything loads as expected.
Needs review: @frosty another one for ya 😃
> Notifications Crash: when resetting notifications, nil the selectedNotification

- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
As reported by @rachelmcr:
> 1. I start a new post.I save the post as a draft (I generally do this with the quick action in the ellipsis menu).
> 2. I edit the post further.I save the draft again (either by tapping “Update” or by saving when I exit the editor).
> 3. The post disappears from the top of my list of posts. I thought it was gone, but it (and any other drafts where I do these steps) is showing up between drafts from May and August 2016, 8th in the list of drafts. On other blogs the same thing happens but the date/placement in the list isn’t consistent.
The changes in #6477 meant that we were now sorting drafts on local status, “publish immediately” first, then by date modified. Previously, we only sorted drafts on local status, then by date modified. So this effectively put all …
> Don't sort by publish immediately on drafts.

- Podfile
- Podfile.lock
Closes #6728
To test:
1. `pod repo update`.
2. `pod install`.
3. Run the app and verify stats loads properly.
> Update WordPressCom-Stats-iOS pod to 0.9.0

- WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m
Fixes: #6030
This should resolve the crashes we've been seeing from the media picker involving section counts not matching. I was able to reliable reproduce the crash through WPiOS (not the media picker project):
1. Select a site that has a lot of remote media (50+ images). It also helps to throttle your connection with network link conditioner or Charles Proxy to simulate slower speeds.
2. Create a new post.
3. Tap the add media button in the post content.
4. Allow access to your photos - make sure you have at least a handful number of images in your camera roll.
5. Tap the group button to switch to Media Library.
6. As soon as the collection view shows the placeholders and starts downloading images, switch back to camera roll (quickly!!).
7. Select any image from the camera roll and tap …
> Fixes a crash when switching between media groups and inserting an image

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Fixes #https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/295
To test:
- Using Aztec do
- Create new post
- Write some thing on it
- Tap on the X (close) button
- Check if you get the option to Save Draft.
> Fix logic error.

- WordPress/Classes/Extensions/NSManagedObject.swift
- WordPress/Classes/Models/AbstractPost.swift
- WordPress/Classes/Models/BasePost.h
- WordPress/Classes/Models/BasePost.m
- WordPress/Classes/Models/BasePost.swift
- WordPress/Classes/Models/Post.swift
- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditorSaveAction.swift
- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
- WordPress/Classes/ViewRelated/Post/PostListFilter.swift
- WordPress/Classes/ViewRelated/Post/PostListFilterSettings.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/PostTests.swift
I went through the 🐰 🕳 and converted `BasePost.status` into an enum instead of a string, so I didn't have to deal with ugly Obj-C constants in Swift.
Some odd things:
- Added a `NSManagedObject` extension to provide accessors for `RawRepresentable` properties.
- As the `status` accessor is now custom and an optional enum, it can't be `@objc` so you can't do `#keyPath(BasePost.status)`. I added `BasePost.statusKeyPath` as an ugly workaround.
- Added a couple `statusString` helpers. With the help of `@objc`, I didn't need to change any of the Objective-C code using status. I'd rather rewrite that in Swift over time, and remove those helpers when not needed.
- Added an extension on Sequences of PostStatus, so you can access `.strings` and convert them to an array of strings. I would have …
> Switch BasePost.status to a swift enum

- WordPress/Classes/Models/AbstractPost.swift
- WordPress/Classes/Models/Page.swift
- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListFilter.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/PostListFilterTests.swift
This is the longer version of #6723.
I've simplified the sorting logic, removing the sort descriptors by local status and "publish immediately", and leaving only date created/modified.
Sorting by "Publish Immediately" only made sense on drafts, and not really anymore since we sort them by date modified.
The "Local" sort descriptor was useful to ensure that posts with local changes were kept at the top. But revisiting this, there are two cases for local changes:
- Drafts: Any local draft is likely to be at the top anyway because it was the last modified
- Published: The only scenario where a published post can be "Local" is if the app crashed or was killed in the background while the editor was open. The ideal case is that we restore the editor when the app launches again, but that might …
> Refactor of posts/pages sorting

- WordPress/Classes/Networking/MediaServiceRemoteREST.m
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/MediaServiceRemoteRESTTests.swift
Fixes #6360 
Errors returned by the media endpoint have two dictionary keys - `media` and `errors`. In code the errors key was misspelled as `error`. The unit test also made this assumption.
https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/media/new/#apidoc-response
I can't figure out the best way to test this remotely because it's difficult to get the API side to return an error on media upload. Specifically the user who reported this has some Jetpack connectivity issues which is causing media upload to fail.
I did update the unit test with the right key and verified that the tests do cause the same crash when it's not the right key.
Needs review: @koke, @SergioEstevao
> Resolves crash upon upload of media when remote errors happen

- WordPress/Classes/Utility/WPError.m
This fixes a recurring crash we've had for a while now in which _something_ is amiss down the line when presenting alertcontrollers via `WPError`.
```
UIAlertController+Helpers.swift line 0
UIAlertController.presentFromRootViewController() -> ()
```
I've dug into this for quite some time and still can't nail exactly where this is occurring. Generally any time a `WPError.showAlertWithTitle ` call is made within an `NSOperationQueue`, things get crazy and `UIAlertController` winds up on a thread != the main thread.
That said, while a bit sloppy, wrapping our `showAlertWithTitle:message:withSupportButton:fromSource:okPressedBlock` block of code within an async dispatch to the main queue will prevent any crashes arising from `WPError` being called in questionable areas.
Ideally we would never …
> WPError: dispatch alert and presentation on main queue.

- WordPress/Classes/ViewRelated/Blog/BlogListViewController.h
- WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
- WordPress/Classes/ViewRelated/System/WPTabBarController.h
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #6736
This fixes the primary issue of the crash created in #6736, as seen in Fabric, by instead presenting the Create a Site flow via the My Sites tab.
To test:
1. Follow the steps in #6736
2. Instead, you should be presented with the alert controller to create or add a new site.
3. The tab should automatically switch for you, and no crashes.
4. Upon actually creating/adding a site, we won't follow through with the post button action and let the user decided what to do afterwards.
Needs review: @astralbodies this is the most ideal solution to fix this in the wild, but technically a more minimal fix would be to simply ignore taps on the post button instead of trying to do anything, if there aren't any sites. If we want to go that route with `7.0` instead, we totally can.
> Prevent crash by not presenting the editor without a site, allow user to create a site.

- WordPress/Classes/ViewRelated/Menus/MenuItemsViewController.m
Just for fun, I added taptic feedback to the menu reordering in Menus so that it behaves like a `UITableView`.
To test:
* Go to Details > Menus for a site
* Reorder items in a menu
* Check that you can feel taptic feedback when the selection begins or changes
> Menus: Added taptic feedback for reordering

- WordPress/Classes/Models/AbstractPost.m
Fix #6545: Make sure authorNameForDisplay and blogNameForDisplay getters returns plain text. Author and site names can include HTML entities, make sure these are decoded for display.
To test: Change your username to "AT&T" and load your site post list.
> Fix #6545: Make sure authorNameForDisplay and blogNameForDisplay getters returns plain text

- WordPress/Classes/Services/AccountService.m
- WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
As noted in #5480, the previous code had a couple issues:
- We were flagging the primary blog as the "last used" on every account sync (effectively, every time the user visited the Me Tab, contacted support, logged in, or connected to Jetpack).
- The post button in the tab bar would use the "last used" even if the user was on a specific site.
In this PR:
- We don't flag the primary blog as "last used", ever. Since we'd fall back to the primary if there was no "last used", it makes no sense to save it there.
- Tapping the post button will check first if the "My Sites" tab is selected, and if there is a site detail in the navigation stack (i.e. not on the sites list). In that case, it'll create a post in that blog, otherwise it'll default to the primary (or first) blog.
- Moved the blog …
> Use current site for new posts

- WordPress/Classes/Services/ReaderPostService.m
- WordPress/Classes/Services/ReaderTopicService.m
- WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
Fixes #6757, see the issue for details.
This PR changes when the Reader's clean up logic is performed.  Instead of cleaning up stale content at launch, it will not clean up stale content just before the app is terminated. 
To test:
The crash this attempts to fix is difficult to reproduce, so for testing, just confirm that content is being successfully cleaned up when the app is terminated. 
- Go to the reader.  Preview a couple of sites and tags so there will be content to clean up
- Double tap the home button (Or cmd+H for the simulator) and swipe to force close the app.
- Inspect the console output. Confirm that the previewed topic(s) were deleted.
> Reader: Changes when stale content is cleaned up.

- WordPress/Classes/ViewRelated/NUX/Signin.storyboard
- WordPress/Classes/ViewRelated/NUX/SigninErrorViewController.swift
- WordPress/WordPressUITests/LoginTests.swift
Fixes #4717
The generic "Sorry, we can't log you in" title has been removed from login error screens in favour of the description which contains information on the specific problem encountered.
To test:
1. Attempt to login to either a WordPress.com or self-hosted site
2. Enter the wrong password or username
3. Observe that the error no longer has the title text.
> Remove title from login error screens

- Podfile.lock
Looks like https://github.com/wordpress-mobile/WordPress-iOS/pull/6758/ didn't commit the updated Podfile.lock.
Merging this in without review 😅
> Updates podfile.lock from previous Aztec PR

- WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
Fixes #6773
Just needed to not instantiate with another `UINavigationController`.
To test:
1. Add the following block of code to `WordPressAppDelegate.didFinishLaunchingWithOptions:`.
2. Make sure the modal presents as expected, no crash.
```
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
[SigninHelpers showSigninForWPComFixingAuthToken];
});
```
> NUX: use the right controller for showSigninForWPComFixingAuthToken()

- WordPress/Classes/ViewRelated/NUX/SigninEmailViewController.swift
Fixes #6776
I'm _fairly_ sure we can fix this crash by using `weak self` versus `unowned` self. I'm also generally sure we should be using `weak` here anyways.
To test:
1. Log out.
2. Test Safari credentials, fills, no crashes.
3. On device, test 1Password, fills, no crashes.
Needs review: @aerych 🥇
> NUX: use weak self for fetching Safari/1Password credentials.

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift
Fixes #6779 
To test:
- Add a new post to a blog you're following in the reader. Add an empty blockquote to the end of the post.  Its important there are no trailing spaces, and that the editor does not remove the empty tag after publishing.
- Confirm the crash by viewing the post's detail in the reader.
- Switch to this branch.
- Again, view the detail of the post in the reader.  Confirm there is no crash.
> Rich Text: Check for out of bounds index.

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Closes #6682
2. Publish a dummy post (random content!)
3. Verify that the keyboard gets dismissed immediately once the post OP completes.
As a result, the keyboard dismiss animation should be half way (or fully complete) once the Post Post screen shows up.
Note that without this PR, the keyboard was fully visible whenever the Post Post interface became visible.
> AztecPostViewController: Dismissing the keyboard before dismissing Aztec

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Brings Aztec 0.5a5 to WPiOS 7.1 mostly matching #6787 which only made it into develop.
> Aztec 0.5a5 7.1

- WordPress/Classes/Utility/ContextManager.h
- WordPress/Classes/Utility/ContextManager.m
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Bringing these from https://github.com/wordpress-mobile/WordPress-iOS/pull/6768 to 7.1 so we can knock out our top crash.
> 7.1: Cherry-picked ContextManager crash fixes

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Fixes #6772 
This PR improves some optional handling which *should* resolve the crash reported in 6722. 
To test:
- Create a post on a blog you follow, where the post contains an iframe with an empty string for its `src` tag. For example: ```<iframe src="" width="300" height"200"></iframe>```
- Confirm the crash by viewing the post in the reader detail.
- Switch to this branch.
- View the post in the reader detail again and confirm there is no longer a crash. 
While this will prevent a crash, the exact markup involved remains unknown. Since the embed's HTML will be passed in its expected that we'll receive some reports of embedded content looking wrong in the reader.  We can use these reports to zero in on the exact circumstances and improve the fix once the exact mark up is known. 
Needs …
> RichText: Better handling for optionals relating to embeds.

- WordPress/WordPress.xcodeproj/project.pbxproj
Also removed a bunch of crap from other targets that shouldn't have ever been included like plists in the copy phases.
Fixes #6806 
To test:
1. Change your simulator to non-English language (French or Spanish for example).
2. Launch the app.
3. Exit out and make sure Today Widget & Share Extension are translated.
> Adds Localizable.strings to Share Extension build phase

- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
- WordPress/WordPressTest/PostEditorStateTests.swift
Fixes #6654 
1. Start a new post in Aztec.
2. Verify Save As Draft not available in the ellipsis menu.
3. Type something in the title or content fields.
4. Verify Save As Draft is now available in the ellipsis menu.
> Don't show the secondary publish actions when the post has no content.

- WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
Brings in crash fix for last iOS 9 release from https://github.com/wordpress-mobile/WordPress-iOS/pull/6774
Needs review: @frosty 🔆
> NUX: use the right controller for bad token modal.

- WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
We've implemented State Restoration in Aztec in #6582. In this PR we're shipping a minor fix that prevents a double instantiation of our editors, upon state restoration.
iOS itself takes care of reinstantiating all of the view controllers that carry a **restorationIdentifier** and **restorationClass**.
On the other hand, **EditPostViewController** always instantiates the active editor in it's **viewDidAppear** method. Meaning that upon state restoration, the Active Editor would get alloc'ated twice: once by the OS, and the second time, by ourselves.
In this PR we're addressing this dual instantiation.
Closes #6700
1. Make sure Aztec is **enabled**
2. Log into a dotcom account
3. Press the `+` button to add a new post
4. Send the app to BG
5. From Xcode, stop execution
6. Relaunch WPiOS
As …
> Aztec: Preventing Double Restoration

- WordPress/Classes/ViewRelated/NUX/SigninEmailViewController.swift
- WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.swift
Fixes #6797 
To test:
1. attempt to login to jetpack
2. use help button to contact support
3. verify the created Helpshift issue has the correct tag
1. launch fresh install of app
2. on very first screen, use `?` button to contact support
3. verify the created Helpshift issue has the correct tag
Needs review: @bummytime 
_I touched your new swift code. does it meet your standards?_
> Fix Helpshift tag problems

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
- WordPress/WordPressTest/PostEditorStateTests.swift
Fixes #6766
1. Enable Aztec!
2. Open any published post using
3. Tap the "Edit" link.
4. Verify that the top right button (**"Update"**) is disabled
5. Type any character int he post's title
6. Verify that the **Update** button gets enabled
7. Undo the edit performed in (4)
8. Verify that the **Update** button gets disabled
9. Edit the Post's Contents
10. Verify that the **Update** button gets enabled
11. Undo the edition, and verify that the **Update** button gets disabled again
May i bug you with yet anoooother review?
Thanks!!!
> Aztec: Context now tracks Content Changes

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Fixes #6765
1. Enable Aztec
2. Create a new Page
3. Use the Site Picker and switch the target to another site
4. Hit the publish button
Verify that, as a result, a new Page is uploaded (instead of a post). Note that the original issue mentioned that the button would read `Post`. That's not the case in the latest develop build.
However, upon post recreation, we weren't taking care of regenerating a **Page** draft, when needed.
Thanks!!
> Aztec: Recreating Posts or Pages as needed

- Podfile
- Podfile.lock
Reopened from https://github.com/wordpress-mobile/WordPress-iOS/pull/6813, on develop.
Fixes #wordpress-mobile/MediaPicker-iOS#128 (MediaPicker-iOS)
This brings in the updated pod to resolve the crash seen in the original issue.
For sanity's sake, test by:
1. Build and run on device.
2. Open Media collection picker, Camera Roll.
3. Take a photo, ensure it shows up.
4. Background app, delete the same photo in Photos.
5. Take another photo with Camera.
6. Open app again, ensure the deleted photo disappears and the newly added photo appears.
Needs review: @frosty 🛡
> Pod bump WPMediaPicker 0.11.3, crash fix.

- Podfile
- Podfile.lock
- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/ViewRelated/Me/GravatarPickerViewController.swift
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
- WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m
- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Updates the app to use MediaPicker 0.12
The media picker had a couple of high-level architecture changes in this release, which required a few changes to WPiOS. `WPMediaCollectionViewController` has now become `WPMediaPickerViewController`, and `WPMediaPickerViewController` has now become `WPNavigationMediaPickerViewController` (wrapping the collection view in a navigation controller.
**To test:**
Check that all of the editors show the media picker correctly, that it's styled correctly, and that you can select images.
> Update to media picker 0.12

- WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
This is a backport of Issue #6812, mapped to `release/7.1`.
iOS itself takes care of reinstantiating all of the view controllers that carry a **restorationIdentifier** and **restorationClass**.
On the other hand, **EditPostViewController** always instantiates the active editor in it's **viewDidAppear** method. Meaning that upon state restoration, the Active Editor would get alloc'ated twice: once by the OS, and the second time, by ourselves.
In this PR we're addressing this dual instantiation.
Closes #6700
1. Make sure Aztec is **enabled**
2. Log into a dotcom account
3. Press the `+` button to add a new post
4. Send the app to BG
5. From Xcode, stop execution
6. Relaunch WPiOS
As a result, Aztec should be back onscreen, and the **Dismiss Button** (top left) should display an `X`.
1. Make …
> EditPostViewController: Preventing Editor(s) Double Instantiation

- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
- WordPress/WordPressTest/PostEditorStateTests.swift
Fixes #6840 
Makes the context keep track of the current post status to prevent Publish Now from showing up when the button says "Update" but the post is published. 
To test:
1. Edit an existing published post. Verify action is Update.
2. Tap options. Verify Publish Now isn't present.
3. Edit an existing draft. Verify action is Update.
4. Tap options. Verify Publish Now is present.
5. Create a new post. Change post options to Draft.
6. Verify Publish Now is present.
> Don't show Publish Now on existing published posts

- WordPress/Classes/System/WordPress-Bridging-Header.h
- WordPress/Classes/Utility/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m
- WordPress/Classes/ViewRelated/Reader/WPImageViewController.h
- WordPress/Classes/ViewRelated/Reader/WPImageViewController.m
- WordPress/WordPress.xcodeproj/project.pbxproj
Related issues: #6817 and #4528
Here's our first PR towards adding Media Library functionality to WPiOS. The Media Library is currently feature flagged so it'll only show in debug mode.
**This PR adds:**
* A Media row to Blog Details.
* A grid view of media, using WPMediaPicker's collection view.
* A detail view of an individual piece of media, including some metadata. Metadata should match Calypso and Android.
* A zoomable preview of each image, accessible by tapping the image in the detail view.
**What's not in here yet:**
* No results view if the user doesn't have any media items
* Video preview
* Editing metadata
* Deleting items
* Searching and filtering
> Media Library #1: Grid and detail views

- WordPress/Classes/System/WordPress-Bridging-Header.h
- WordPress/Classes/Utility/WPURLRequest.h
- WordPress/Classes/ViewRelated/Post/FakePreviewBuilder.swift
- WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift
- WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
- WordPress/WordPress.xcodeproj/project.pbxproj
For #5693 I have to introduce quite a bit of logic to support multiple authentication mechanisms (nonce, cookie, no auth), and in the future also autosave drafts so we can show a real preview.
This first PR takes all the preview generation logic out of PostPreviewViewController, leaving it only to handle the UI.
I know there's plenty to improve in this code, but for this first pass I wanted to keep the exact same behavior, with just better separation of responsibilities (and Swift migration).
The one behavior change I did was to get rid of the custom loading indicator and use `SVProgressHUD` instead.
I'm having some trouble running the test suite, so I'm leaving unit tests for a future PR.
> Preview refactor

- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
Hopefully a simple one, this – adds the ability to share a media item's URL. 
To test:
* View a media item in the media library
* Tap the Share button in the navigation bar
* Check you get the URL out correctly. Make sure the URL works for self-hosted and .com.
> Media Library #2: Media URL sharing

- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Fixes #6852. It'll be nice to support other file types in the future, but for now let's limit things to images or video (I thought I'd done this already, but turns out I used the wrong filter type).
To test:
* Add a non-image or video file to your media library using Calypso
* Open the media library in the app, and check that you can't see the newly-added file.
> Issue/6852: Update Media Library filter to only show images and videos

- WordPress/Classes/ViewRelated/Post/PostListFilter.swift
Refs #6819 
See the issue for more details.  This is a hail-mary pass at fixing the issue, but I think its a likely fix.
To test:
Primarily we want to confirm that the post list continues to refresh properly after the change. 
Confirm a first time load, a subsequent refresh, and load more all function correctly.
Needs review: @kurzee, you're probably the most recently acquainted with the post filters. Would you care to review?
> Posts: Defaults the post filter's hasMore prop to false.

- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
Fixes #6562
A small PR to get us in better place for error messaging when a media upload fails. For the most part, we're just overriding the raw `NSURLError` domain messages with something that encourages the user to try again. For self-hosted though, we go ahead and pass on the raw value except for two previous cases. This way self-hosted can debug and REST can try again.
When we refactor for async uploading we'll have more opportunity to really inform users of what went wrong and where.
To test:
1. Generate the error messages by selecting a media to insert and have it fail.
2. You can easily test the `Media upload failed, internet connection appears to be offline.` by going into airplane mode.
3. The other cases are a bit more difficult and I couldn't find away to trigger them, instead …
> Media: slightly better errors for failed uploads

- WordPress/Classes/Networking/AccountServiceRemote.h
- WordPress/Classes/Networking/AccountServiceRemoteREST.m
- WordPress/Classes/Services/AccountService.h
- WordPress/Classes/Services/AccountService.m
- WordPress/Classes/ViewRelated/NUX/NUXAbstractViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
- WordPress/WordPressTest/SigninHelperTests.swift
Fixes #6600 
WordPress.com domains containing valid usernames will now work for logging in.
To test:
1. At the first username/email screen, enter a wp.com domain whose subdomain is a username
2. Hitting next should cause the wp.com login screen to appear with the username prefilled
And a possible failure case:
1. At the same screen, enter a wp.com domain whose subdomain isn't a username
2. Hitting next should cause an error screen to appear
You handled the Android side, figured that makes you the expert +wink
> Allow wp.com domains as username

- WordPress/Classes/Networking/TaxonomyServiceRemoteREST.m
- WordPress/WordPressTest/TaxonomyServiceRemoteRESTTests.m
Fixes #6861 
I'm not proud of this fix, but with a current user only being able to pull in half of their total categories at the moment, we probably ought to lean towards a quicker patch.
Since we currently only pull in the default `100` categories we can remedy this issue quickly, but with potential performance impact by requesting up to the full `1000`. However, we already receive the full set of categories on XML-RPC, so technically we're not doing anything too different for REST. Furthermore I suppose there's not too many cases of sites with more than 100 categories.
Also, looks like Android currently has the same problem glancing at: https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/networking/WordPressNetworking/src/main/java/org/wordpress/android/networking/Res …
> Categories: request max by default for REST

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #6565
2. Enter some random Text
3. Verify that the **Discard** action shows **below** the **Save Draft** action
Please, retry with the Hybrid editor as well. I've updated them both, for consistency's sake.
> Editor: Updates Discard Action Placement

- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Enabling/disabling publicize connections was being handled at the cell's UISwitch level, now it is handled when tapping on the publicize cells.
Fixes #6850 
To test: 
Create a new post in a blog with configured publicize connections.
Go to the post options and tap on the publicize cells to enable/disable them.
> Toggle publicize connection switch on cell tapping

- WordPress/Classes/Models/Blog.h
- WordPress/Classes/Models/Blog.m
- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR introduces editing to the media library.
To test:
* Open a media item from within the library.
* Tap the title, caption, or description fields to edit them.
* Once you've edited any of those fields and returned to the media item view controller, the navigation bar will show Cancel or Save.
* Cancel should revert the changes, Save should save them.
> Media Library #4: Editing

- WordPress/Classes/ViewRelated/Post/Categories/WPAddPostCategoryViewController.m
<h3>Description:</h3>
When adding a category to a post, tapping on the "DONE" button in the keyboard, now properly dismisses it.
Fixes #5904 .
<h3>Testing:</h3>
**Test 1:**
1. Go to the list of posts for a blog.
2. Select any post.
3. Tap in the top-right "..." button.
4. Select "Options".
5. Tap on "Category", and tap "+" in the top right corner to add a new category.
6. Start typing the category name, and press "DONE" in the virtual keyboard.
Make sure the keyboard is properly dismissed.
> When adding a category, the done button now dismisses the keyboard.

- WordPress/Classes/Utility/Logging/WPLogger.m
- WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme
Removes the CocoaLumberjack TTY logger to prevent duplicate log events from being seen and turns on OS activity. We've been missing out on important logging like autolayout constraints being broken.
To test:
1. Compile & run.
2. Ensure duplicate logging isn't showing up.
Needs review: @koke, @frosty
> Turn off the OS_ACTIVITY_MODE disabling so we see important stuff

- WordPress/Classes/ViewRelated/Tools/SettingsMultiTextViewController.m
- Nuked tableView.frame update. Not needed, since we use autolayout, and the tableView is the top level component
- Updated the adjustCell call to be asynchronous. Since there's a guard condition, after the first resize, the loop effectively stops.
Fixes #6877
1. Set Text Size to smallest in Settings > Display & Brightness > Text Size.
2. Launch the app.
3. Open the Me tab.
4. Tap My Profile > About Me.
Verify if the world is a happy place again. Or not.
Thanks!
> SettingsMultiTextViewController: Fixing recursive loop

- WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
Just a small tweak to add the error description to the list of properties tracked when tracking an error. 
To test: 
Add a breakpoint @ `[self track: withProperties:]`
Be signed out of the app.
Try to sign in to wpcom with invalid credentials.
Confirm that the properties dictionary contains the error description, and there are no errors.
Needs review: @elibud may I trouble you for a review?
> Analytics: Include error description in passed props.

- WordPress/Classes/Services/EditorSettings.swift
- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/Utility/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/EditorSettingsTests.swift
Closes #6647 
Provides a way to enable the Aztec editor in builds where it's not available by default (like the App Store/TestFlight builds). URL scheme is defined in the referenced issue.
1. Launch the app and verify Native Editor is visible in Me > App Settings.
2. Open `FeatureFlag.swift` and temporarily remove `.debug` from the `case .nativeEditor` if statement. This simulates the configuration for the App Store build.
3. Launch the app and verify Native Editor is not visible in Me > App Settings.
4. Open Safari and visit the URL `wpdebug://editor?available=1&enabled=1`. Allow Safari to launch WordPress.
5. Go back to App Settings and verify Native Editor is both visible and enabled.
6. Open Safari and visit the URL `wpdebug://editor?available=1&enabled=0`. Allow Safari to launch …
> Adds URL override for Aztec editor

- Podfile
- Podfile.lock
**Fixes:** #5212 #6789 
**To test:**
#5212 
Create a post without a title
Go to the Stats section -> Insights, and check that **(no title)** is displayed.
#6789 
Go to the Stats section -> Countries and enjoy beautiful non-wavy flags.
> Bump stats to version 0.9.1

- WordPress/Classes/System/WordPress-Bridging-Header.h
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
Fixes #6762 #6763 
To test:
- Edit a page using Aztec
- Go to Options
Only the Publish and Featured Image section should be there
> Aztec: show page settings for pages

- WordPress/Classes/Services/PeopleService.swift
- WordPress/Classes/ViewRelated/People/PersonViewController.swift
Fixes #5671 
This PR adds an alert after attempting to remove a site owner. In addition,  a `WPError.showNetworkingAlertWithError` will now display if there are any other issues when removing people.
**To test:**
1. Set up a site with two users: the site owner and a second account you are using in the app
2. Open the app (logged in to the second account)
3. Go to My Site > People
4. Select the site owner in the list of users
5. Select "Remove User"
6. In the confirmation dialog, select "Remove" to confirm that you want to remove the user.
The app will take you back to the list of users on the site, display the alert, and that user should still be in the list.
Needs review: @kurzee would you be so kind?
> Display error when deleting a site admin

- WordPress/Classes/Categories/UIImageView+Gravatar.m
Fixes #6844 
This takes care of the issue for the new site icon storage, but it still won't work for private sites (request is unauthenticated) or self hosted (it will wrongly interpret the URL as a host for blavatar, but that's fine because we need a resized icon anyway). I considered fixing those as well, but I think it's better to wait for the upcoming network improvements and rethink or image loading in general.
To test:
- In a web browser, add a site icon to a WordPress.com site (in the general settings or in the customizer).
- Open the My Sites tab in the app and check that the right site icon is shown
- Visit the site details and check that the right icon is there as well.
> Support wp.com site icons on the blog list

- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
On Site settings the _View Site_ and _Dashboard_ options are moved to a new section called _External_ at the bottom of the settings. 
_Dashboard_ access is hidden for WPCom users that created their account after September 7th, 2015
**Fixes** #6832 
Before        | Dashboard Disabled           | Dashboard Enabled
------------ | -------------|------------ |
**To test:**
With a WPCom account created before September 7th, 2015 check that View Site and Dashboard are at the bottom of the settings.
With a WPCom account created after September 7th, 2015 check that ONLY View Site is at the bottom of the settings.
With a non WPCom account check that View Site and Dashboard are at the bottom of the settings.
> Move View Site and Dashboard to External section

- WordPress/Classes/ViewRelated/Comments/CommentViewController.m
Fixes #6470 
To test:
1. Navigate to My Sites > Site > Comments > Comment
2. Tap the edit button next to Spam
3. The comment editor should appear
> Fix comment edit button

- WordPress/Classes/Models/Notifications/NotificationBlock.swift
- WordPress/Classes/Services/NotificationActionsService.swift
- WordPress/Classes/Services/NotificationSyncMediator.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
Several Notification Actions are not forcing, backend side, a Notification Document Regeneration. As a result of this, retrieving the remote `[NoteID, Hash]` collection will not correctly indicate us if the notification has been updated.
Bottom line is: performing actions, such as Liking a Comment, **do work**, but upon relaunch, the Notification does not reflect it's actual remote state.
As a workaround, we'll force a Notification Refresh whenever the user perform an action such as `[Like, Unlike, Follow, Unfollow, Update Comment, Reply Comment, Approve Comment, Unapprove Comment]`
Fixes #6744
1. Open a Comment-Y Notification
2. Try the following actions:
`[Like, Unlike, Follow, Unfollow, Update Comment, Reply Comment, Approve Comment, Unapprove Comment]`
3. Kill the app
4. Relaunch
5. …
> Forcing Notifications refresh

- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.h
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR adds search to the media library. The search will search the title, caption, and description fields of media items.
**Note:**
* There's a noticeable flickering when the collection view is refreshed as you type your search query. This is due to the way the media picker loads its images asynchronously, and will be fixed separately in the media picker.
* Search currently doesn't have a 'no results' state. I'll be adding no results separately for when a user has no items in their media library, so I'll address search at the same time.
**To test:**
* Try searching a media library!
* Try editing metadata for an item and check you can search for the new values
* Check the scroll insets play correctly with the keyboard
> Media Library #5: Search

- WordPress/Classes/Networking/ReaderPostServiceRemote.m
- WordPress/Classes/Utility/DisplayableImageHelper.m
- WordPress/WordPressTest/DisplayableImageHelperTest.m
- WordPress/WordPressTest/ReaderPostServiceRemoteTests.m
**Fixes** #6714 
**To test:**
1. Before checking out this branch:
Find a post on the web reader with an image that does not match what you see on the reader in the app. A good example is: https://wordpress.com/read/feeds/3039616/posts/1219371263
2. Checkout this branch
3. Force refetch the feed (log out and back in or uninstall so even old posts are refetched?)
4. Check that the images match on the post
**Example:**
On the left you can see the reader on the browser, and on the right on the simulator.
Before this change:
After this change:
That particular post has an image on the `featured_media` field and that's what caused the discrepancy.
> Only look for an image to feature on the post content

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift
**Fixes** #6894 
**To test:**
1. Turn on Voice Over or lunch the Accessibility Inspector
2. Navigate to a comment notification and check that all the elements on the screen have accessibility labels (back button, previous and next notification button, reply text field, reply button)
> Adds missing accessibility labels to reply to comments

- WordPress/Classes/ViewRelated/Blog/SharingConnectionsViewController.m
- WordPress/Classes/ViewRelated/Blog/SharingDetailViewController.h
- WordPress/Classes/ViewRelated/Blog/SharingDetailViewController.m
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
- WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.m
We already show if a connection is broken from post options. This lets the user fix the issue right there. I had to refactor things a little bit as the sharing detail expected the publicize services to be synced, so I removed that requirement. It's still not bulletproof as the sync can fail and there's no retry, but I'd leave that for the new network infrastructure.
I also had to fix this crazy hard to debug thing where the same authorization web view would work from the Sharing section but not when presented from the editor, because the editor enables PrivateSiteURLProtocol. I updated it so it forwards redirects to the client, but perhaps we should limit it to wordpress.com sites (i.e. exclude public-api).
Fixes #6837 
To test:
- Do a fresh install to ensure publicize services aren't …
> Reconnect publicize from editor

- WordPress/Classes/Utility/WPWebViewController.m
- WordPress/Info.plist
**Fixes** #6820 
**To test:**
1. Choose an article from the reader that has sharing enabled.
2. Click on Visit for that article.
3. Scroll down to the share options.
4. Select WhatsApp and check that the application opens with the correct pre-populated message.
5. Select Telegraph and check that the application opens with the correct pre-populated message.
> Allows sharing to WhatsApp and Telegraph from the reader

- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
Fixes an unsatisfiable constraint issue that was occurring with `MediaItemViewController`, by setting a priority on the aspect ratio constraint. I've also moved all the custom views within `ImageTableViewCell` into the `contentView`.
To test:
* Check the cell still looks and works as expected, and there are no constraint issues in the console.
> Fix Constraint Issue with Media Item View Controller

- WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift
Open any spot in which the ReplyTextView is wired, and verify that the inner textView does not flicker whenever you type a new character.
Since we changed the font over to **Noto**, few constants required adjustment!
> ReplyTextView: Fixing Flicker

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
2. Bring the keyboard up
3. Tap into the content field (doesn't happen in the title field).
4. Verify that the formatBar gets a "peek" animation, as soon as the keyboard is fully up
Ref. #6688
> Aztec: Peek Animation

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
This switches the responsibility for marking a note as read to the detail view
controller, since it'll be able to tell if it's visible or not.
Previously it was marked as read when the view was loaded, regardless of
visibility: split view would preload the first notification even on iPhone or
if the user was in different tab.
Fixes #6919 
To test:
- Make sure you have a new unread notification
- The new notification should stay unread
- When you visit the notification it should be marked as read
> Mark notifications read only when they're displayed

- WordPress/Classes/Services/NotificationActionsService.swift
1. Receive a Comment Notification
2. Try Spam / Delete OP's
3. Relaunch WPiOS
4. Verify the Nuked Comment Notification doesn't turn zombie!
> NotificationActionsService: Wiring force sync for Spam and Delete OP's

- WordPress/Classes/Models/Blog.m
- WordPress/Classes/Services/AccountService.h
- WordPress/Classes/Services/AccountService.m
- WordPress/Classes/ViewRelated/Blog/BlogListDataSource.swift
Instead of fetching the default account every time we check for visibility
support, we just need to check if the account's uuid matches the stored one.
We could optimize further, but I think the core data fetch was the big
bottleneck and I'm seeing a similar scrolling performance than the non-edit
list with this.
Fixes #6920 
> Improve scrolling performance for edit sites

- WordPress/Classes/ViewRelated/NUX/Signin.storyboard
- WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme
- WordPress/WordPressUITests/LoginTests.swift
- WordPress/WordPressUITests/XCTest+Extensions.swift
- WordPress/WordPressUITests/gencredentials.rb
Fixes the testCreateAccount test in the WordPressUITest target.  Needs two new fields added to the ~/.wp_test_credentials file:
```
nuxEmailPrefix=***
nuxEmailSuffix=***
```
These will be appended to either end of the randomly generated username to build a dynamic e-mail address for the new account.  This supports doing something like `username+RANDOM@gmail.com` or `RANDOM@youremailserver.com`
> Fix UI create account test

- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
It looks like our old friend #6757 (ReaderPostCardCell crash) is still around in our latest releases. Whilst we don't seem to have got to the bottom of the root cause yet, I'm hoping this PR might at least prevent the app from crashing. However, I haven't been able to recreate the crash itself so it's all a bit of guesswork – I'm just ensuring that the post hasn't been deleted, and treating the like and comment counts as optionals in case for some reason they don't exist.
@astralbodies This is our current top crasher – is it okay for this fix to be targetted at 7.3?
> Issue/6757 ReaderPostCardCell crash fix

- WordPress/Classes/ViewRelated/Comments/CommentViewController.m
In this PR we're removing the Comment Detail's Navbar Edit action, since it's duplicated. We can also trigger the Comment Edition screen by means of the `Edit` button, visible at the bottom of the comment.
1. Lauch WPiOS
2. Open `My Sites` > `Site` > `Comment`
3. Pick up any Site's comments
Verify that the navbar's Top Right **Edit** action is gone. We still should have the **Edit** Action visible at the bottom of the comment
Sir, may i bug you with a small PR?
Thanks!!!
P.s.: @drw158 thanks for reporting this one!
> CommentViewController: Nukes Duplicated Edit Action

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
Fixes #6948. 
One of our current top crashes for 7.2 is happening on `keyboardManager.stopListeningToKeyboardNotifications()` in `viewWillDisappear` of `NotificationDetailsViewController`. `keyboardManager` was an implicitly-unwrapped optional, so there is a possibility it could be nil (which I'm presuming is the cause of the crash).
I've switched `keyboardManager` to a real optional, and we'll fail silently if it doesn't exist at that point. There _might_ be a deeper issue going on here, but at least this should stop us crashing.
To test:
* Ensure the keyboard handling still works as expected.
* You could try nilling out the `keyboardManager` and ensure we don't crash.
> Notification Details: Fix potential crash on viewWillDisappear

- WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.swift
Fixes #6950 
This should fix a crash on the Jetpack login screen, which appears to be due to force unwrapping a blog's username and password. I've simply removed the force unwraps, as `displayWebView` can take optional usernames and passwords anyway.
To test:
* Slightly tricky testing this one, but you could try modifying the `password` getter in `Blog` to return nil, and check nothing crashes with this fix in place.
> Jetpack Login: Don't force unwrap username and password

- WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.h
- WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m
- WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift
Fixes #6956. We were getting a crash in Account Settings (see original issue) when editing the primary site. This PR just makes the optional handling around presenting and dismissing the blog selector a little more careful, by removing some force unwraps.
To test:
* Ensure you can still edit / change your primary blog correctly.
* Perhaps change the code to pass `nil` into the blog selector or to return `nil` from its success block and check that nothing breaks.
> AccountSettings: Allow nil selected blog ID

- WordPress/WordPress.xcodeproj/project.pbxproj
Looks like this was leftover from https://github.com/wordpress-mobile/WordPress-iOS/pull/6929, or snuck back in somewhere along the way. Running `pod install` produced this output:
```
[!] `<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `B587797B19B799D800E57C5A` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.
```
To test:
- Run `pod install`, but make sure there isn't any output complaining about that UUID
- Make sure the project builds
> Xcode: remove leftover NSIndexPath extension reference

- WordPress/Classes/Extensions/NSFetchedResultsController+Helpers.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Closes #6771
I've been unable to directly repro this bug. I'm reimplementing an old failsafe we had in that spot, that got removed after the Swift 3.0 migration.
Please, log into a dotcom account, and verify that pressing over any Notification would display it's details.
Thanks in advance Brent!!
> NotificationsViewController: didSelectRow Failsafe

- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR fixes some issues that cropped up whilst testing the no results PR (#6916). I've switched the search controller for a standard search bar, which behaves much better.
I'm not entirely happy with how the no results view animates along with the keyboard, but I think that could be much improved by converting the no results view to use auto layout.
To test:
* Ensure that all of the issues reported in #6916 are fixed, around rotation, multitasking and item deletion.
> Media search bar fixes

- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressShareExtension/Info-Alpha.plist
- WordPress/WordPressShareExtension/Info-Internal.plist
- WordPress/WordPressShareExtension/Info.plist
- WordPress/WordPressShareExtension/NSExtensionContext+Extensions.swift
- WordPress/WordPressShareExtension/ShareExtractor.swift
- WordPress/WordPressShareExtension/ShareViewController.swift
- WordPress/WordPressShareExtension/WordPressShare.js
Fixes #5224, also #5198 was partly a duplicate.
I've refactored the content extraction from `NSExtensionContext` so it's easier to add new supported types: I have another PR ready with a custom data type for posts shared from the reader that was [super simple](https://github.com/wordpress-mobile/WordPress-iOS/commit/54018768bb58605b7bc6d98f6bc263d5eb0c6faa#diff-5abc91b1e16e8a80744054d07c84b507) to add.
Having models of the extracted data will also help when we get to implement a custom UI and can differentiate, for instance, between a title and a quote.
During the refactor, I also learned that `UIViewController` has a `beginRequest` method, which is where you are supposed to start looking into the extensionContext content instead of `viewDidLoad`
To test:
- Run the app
- Switch to Safari …
> Share: extract selected text from Safari

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Previously we were animating the navigation bar display even if the VC was
disappearing without animation. This somehow led to UIKit presenting a note
detail modally instead of pushing it when opening a push notification.
Refs: #6976
To test:
- Log in with your a8c account, find a notification that mentions you on a post (not a comment)
- The notification opens a reader view for the post.
- Scroll down a bit until the navigation bar disappears
- Put the app in the background
- Generate a new comment notification
- Tap on the new notification
- The comment notification should appear with the navigation bar
> Respect animated when reader disappears

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
Fixes #6549 
Testing this PR could be a bit of a challenge. I ended up going through the existing editor VC and finding all of the methods that had events and added them into similar places in Aztec. You could perform checks on each event making its way into Tracks & Mixpanel.
Needs review: @bummytime, @nheagy
> Aztec: Adds all editor analytics tracking events to Aztec VC

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m
- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
I've added a handful of new analytics events for the new media library functionality (added to the analytics pod here: https://github.com/wordpress-mobile/WordPressCom-Analytics-iOS/pull/89). 
WPAnalyticsStatMediaLibraryDeletedItems
WPAnalyticsStatMediaLibraryEditedItemMetadata
WPAnalyticsStatMediaLibraryPreviewedItem
WPAnalyticsStatMediaLibrarySharedItemLink
To test:
* Ensure the tracks events are being logged as expected.
* Deleted items should be triggered if you delete a single media item, or if you delete multiple items from the grid view. It should include a property containing the number of items deleted.
* Previewed item should be triggered whether you just tap into an item or if you preview it with force touch.
* Edited item should be triggered if you edit and save an item's …
> Media Library: Add analytics events

- WordPress/Classes/Networking/AccountServiceRemoteREST.m
This PR passes the current WPComScheme of the app when requesting a magic link.  The link that is sent will be constructed with the specified scheme.  The link may then be used to open debug, internal, or alpha builds rather than just production builds.
To test: 
- Request a link via a debug build.
- Background the app.
- Copy the link in the email you receive.
- Paste it into the simulator.  Open Safari tap into the URL field and choose Paste & Go.
- Open the link with WordPress. 
- Confirm that you are logged in. 
> Magic Links: Pass scheme when requesting link.

- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
I noticed a retain cycle in the media library earlier, so this PR fixes that up. It's just a case of making a few blocks use a weak `self`.
To test:
* Open the app, navigate into the media library (from Blog Details VC), tap into a single media item, and then navigate back to Blog Details. Repeat this a couple of times. Finally, tap into another item in Blog Details, like Posts.
* In Xcode, view the Memory Graph:
* On `develop`, you should see `MediaLibraryPickerDataSource`, `MediaService` `MediaLibraryGroup`, and some `MediaItemViewController`s hanging around:
* On this branch, they should be all gone.
> Media Library: Fixes a retain cycle

- WordPress/Classes/Utility/FeatureFlag.swift
This PR enables the media library for internal builds, not just debug.
> Media Library: Enable for internal builds

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Fixes #6976 
Whilst I don't like a magical dispatch main fix, this _seems_ to fix our missing navigation issue.
To test:
- Log in with your a8c account, find a notification that mentions you on a post (not a comment)
- The notification opens a reader view for the post.
- Scroll down a bit until the navigation bar disappears
- Put the app in the background
- Generate a new comment notification
- Tap on the new notification
- The comment notification should appear with the navigation bar
> Fix an issue where notifications sometimes present with no navigation

- WordPress/Classes/Models/SharePost+UIActivityItemSource.swift
- WordPress/Classes/ViewRelated/Post/PostSharingController.swift
- WordPress/Shared/SharePost.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressShareExtension/ShareExtractor.swift
Improves sharing from reader by passing extra data about the post when sharing to WordPress.
For now, we're only using title/link since the share UI is very simple, but this opens the door to more advanced sharing.
For sharing to other apps, we still pass just the URL, but the new custom `UIActivityItemSource` will allow us to make tweaks for specific apps
Fixes #5198 
To test:
- Launch the app and find a Reader post
- Share to WordPress, it should have the post title and link
- Share to other apps, it should have the link. Apps like Facebook, Twitter, or Notes should show a link preview and not just plain text.
> Share from reader

- WordPress/WordPressUITests/XCTest+Extensions.swift
Fixes the testSelfHostedLoginWithoutJetPack test in the WordPressUITests target.
The updated test accounts for the change in the self-hosted Remove Site button (now located on the site details screen instead of the site settings).
Needs review: @hoverduck 
cc @catehstn
> Fix self-hosted login UI test to use new Remove Site button

- WordPress/Classes/ViewRelated/Blog/SiteManagement/DeleteSiteViewController.swift
genstrings was throwing a tantrum about that `\u{2022}` so I'm using the bullet
point character instead. There's no need for the RTL comment, as that would
flip properly when translated (not just with the RTL pseudolanguage).
@bummytime I'm merging this directly so I can generate the strings files, but I'd appreciate a post-merge review :)
> Fix bullet point in localized strings

- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.xib
- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.xib
Resolves constraint conflict warnings when loading the Notifications cells; auto layout not
liking the height constraint versus the bottom constraint, together. Simply setting the bottom constraint to priority to `999` fixes the constraint conflict, and is ideal.
To test:
1. Launch the app, check that no warnings appear.
2. Give the Notifications tab a few good scrolls, rotations, push/pop, make sure all of the cells layout as expected.
3. Reader seems to have it's own warnings going on, might need to pop to root on the Reader tab before testing to avoid those warnings.
4. Test again on iPad.
Needs review: @elibud can you give it a whirl?
> Notifications: cell bottom padding constraint @ 999.

- WordPress/Classes/ViewRelated/Cells/MediaItemImageTableViewCell.swift
- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
This PR adds state restoration to the media library. Both the main media library and the individual item view controller should be restored. We encode the blog for the media library, and the viewed media item for the item VC.
The PR looks a little bigger than you might expect just because I pulled the media image table view row and immutable row out into their own file to clean things up a little – but none of the content has changed in there.
To test:
* You know the dance. Open one of the media screens in the app, background the app, stop it in Xcode. Reopen and check the correct screen is restored.
> Media Library: State restoration

- WordPress/Classes/Networking/CommentServiceRemote.h
- WordPress/Classes/Networking/CommentServiceRemoteREST.m
- WordPress/Classes/Networking/CommentServiceRemoteXMLRPC.m
- WordPress/Classes/Services/CommentService.m
Fixes #4673 
To test:
- On a self hosted site non jetpack
- Add a comment to a post
- Check that the comment shows in the app and is waiting moderation
- Go back to the web as and admin and spam/delete the comment
- Go back to the app and without a refresh, tap on the comment and tap spam/delete
- See if the comment goes away.
> Add check for specific error code on xml rpc when status changed on the server.

- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
This PR fixes an issue find by @frosty where videos on the WordPress media library where being returned as images.
This was cause by a bug while fetching thumbnails for videos where the thumbnail was save to the location of the local video.
To test:
- Open the app
- Go to Setting -> App Settings  and clear the Media Cache
- Go to a blog where you have videos save on your media library
- Tap on add media
- Select the video and force touch/long press to preview it
- See if the video shows correctly.
Needs review: @frosty cc @kurzee
> Fix preview of video assets on WP library

- WordPress/Classes/Models/Blog.m
Fixes #7009 
OAuth support of a blog was detected only when the blog was hosted at WP.com and the current user was an admin of the blog, this PR removes the requisite that the current user is an admin.
To test:
On branch develop, as a non-admin user, preview a Post. You will get a local preview.
Checkout this branch and repeat the process, you should correctly see a remote on-site preview.
> Fix blog OAuth capability detection

- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/Utility/FeatureFlag.swift
- WordPress/Classes/ViewRelated/NUX/Login.storyboard
- WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
New login work can go behind this feature flag until ready for release. Adds a new `Login.storyboard` to hold the new UI. Currently the only difference is use of the initial view controller setting, and a "New Login" label:
To test:
1. Launch app after a fresh install (no existing accounts in app)
2. Ensure the first screen has the "New Login" label at top
> Add feature flag for new login project

- WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
**Fixes** #5906 
**To test:**
1. Go to Blog->Themes
2. Search for a theme
3. Activate it
4. Check that the search is not cleared
> Don’t clear the search when a theme is activated

- WordPress/Classes/Extensions/Media+Blog.swift
- WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.h
- WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m
- WordPress/Classes/ViewRelated/Post/EditImageDetailsViewController.h
- WordPress/Classes/ViewRelated/Post/EditImageDetailsViewController.m
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
This PR makes a couple of tweaks to make it easier to set featured images. Note that these changes are currently only for the hybrid editor. If it's all okay we can do another small PR for Aztec.
There are two main changes:
The Post Settings "Set Featured Image" button now shows the media picker defaulted to show the WP media library. This matches the behaviour on Android, and I know most of the time when I personally want to chose a featured image, I've already uploaded it. You can of course still switch back to the device library if necessary.
I had to add a new property to `WPAndDeviceMediaLibraryDataSource` to allow us to set the starting source. I also had to call `loadData` on the local photo library data source on `init` to ensure we have the groups available in the picker. I'm not …
> Featured Images convenience tweaks

- WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
**Fixes** #6468 
This PR replaces the UISearchController by a UISearchBar on the Blog List screen. 
This allows us to pin the search bar on top of the screen as it was requested, but it also plays nicely with the SplitVC.
Moreover using a search bar is consistent with how search is implemented both on Reader and on Media Library.
**To test:**
Go to My Sites and Search. 
Edit the list of available blogs.
Search again.
Play around.
Please test on IPad and landscape 7plus.
> Blog List Search Bar pinned to top

- WordPress/Classes/ViewRelated/NUX/SigninWPComSyncHandler.swift
This PR fixes an issue where the `dotcom_user` property was being set a string value of `1` rather than `true` on a successful login.  The same change is made to the `multifactor` property.
To test:
Add a breakpoint after the change.
Sign into wpcom.
Inspect the value of the properties dictionary and confirm that `dotcom_user` is set to `true`, and that multifactor is set to either `true` or `false` and not `1` or `0`. 
Bonus points for checking in our analytics dashboards.
> Signin: Fixes value of dotcom_user property.

- WordPress/Classes/ViewRelated/System/WPTabBarController.m
**Fixes** #6972 
I was able to reproduce the problem only by logging out and in with unread notifications. It's caused by two different issues:
1. The UITabBarItems recreation on top of the previously added Notification Badge
2. When `viewDidLayoutSubviews` is invoked after logging in the frames for the UITabBarButtons are not correct.
**To test:**
You can add this bit of code to `updateNotificationBadgeVisibility` so you always have a notification icon that comes and goes.
```
count = arc4random() % 2;
[self performSelector:@selector(updateNotificationBadgeVisibility)
withObject:nil
afterDelay:5];
```
I suggest doing this in develop, logging out and in and checking that the icon is misplaced. If you rotate the device it will go to the correct location, but behind the bell.
Then checkout …
> Fix incorrect placement of notification badge icon

- WordPress/Classes/System/WordPressAppDelegate.m
Fixes #7052 
To test:
1. Follow the steps in #6890 but replace `editor` with `aztec`.
This doesn't need to be an exhaustive test given the relatively small code change.
cc: @0nko
> Lets users unlock with aztec or editor parameter

- WordPress/WordPress-Internal-Info.plist
- WordPress/Wordpress-Alpha-Info.plist
**Fixes** #7060 
On https://github.com/wordpress-mobile/WordPress-iOS/pull/7047 the references to MainWindow.xib were removed from Info.plist 
On this PR they are removed from WordPress-Internal.plist and WordPress-Alpha.plist
**To test:**
Run the app for both schemes and see that it works.
Needs review: @jleandroperez @aerych
> Remov references to MainWindow.xib for Alpha and Internal

- WordPress/Classes/Utility/Analytics/WPAppAnalytics.h
- WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m
- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #7051 
This PR does a couple things.
First, it adds a convenience method to `WPAppAnalytics` to accept an `AbstractPost` parameter similar to the blog parameter method already available. I'm not a big fan of the naming but why rock the boat. This change will make it easy to include `post_id` in all of our analytics events when one is present. It then also subsequently adds `blog_id` because it makes good sense.
Second, it adds a new property `editor_source` to all editor-related events and indicates which editor is being used to send those events. This does feel ugly as well but then our analytics tracking code in general isn't the most pretty. When we remove the legacy and hybrid editors we can axe these properties.
To test:
1. Set a breakpoint or NSLog in `[TracksServiceRemote …
> Adds post ID & editor source to all editor-related events.

- WordPress/Classes/ViewRelated/Cells/MediaItemImageTableViewCell.swift
- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
- WordPress/Classes/ViewRelated/Views/PlayIconView.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
This PR adds playback of video assets to the media library. When you view details for a video, you'll see a play icon over the video thumbnail:
This is a custom view, which I've tried to match as close as I could to the system icon that's shown over videos in Safari. When you tap the video, we play it back through `AVPlayerViewController`.
To test:
* Try playing back video assets on different types of site (self-hosted, .com etc)
* Check that the video icon only shows on videos, not images
* Check that the icon is centered correctly and looks right
cc @SergioEstevao
> Media Library: Add support for video preview

- WordPress/Classes/Categories/SVProgressHUD+Dismiss.h
- WordPress/Classes/Categories/SVProgressHUD+Dismiss.m
- WordPress/Classes/System/WordPress-Bridging-Header.h
- WordPress/Classes/ViewRelated/Blog/RelatedPostsSettingsViewController.m
- WordPress/Classes/ViewRelated/Blog/SharingAuthorizationHelper.m
- WordPress/Classes/ViewRelated/Blog/SharingDetailViewController.m
- WordPress/Classes/ViewRelated/Blog/SharingViewController.m
- WordPress/Classes/ViewRelated/Blog/SiteManagement/DeleteSiteViewController.swift
- WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteSettingsViewController+SiteManagement.swift
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
- WordPress/Classes/ViewRelated/Comments/CommentViewController.m
- WordPress/Classes/ViewRelated/NUX/Signin2FAViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
- WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostMenu.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
- WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
**Fixes** #7058 
Adds a Category to `SVProgressHUD` to make them dismissible by tapping anywhere on the screen.
Note: we need `[SVProgressHUD setDefaultMaskType:SVProgressHUDMaskTypeClear]` to allow user interactions with the control.
**To test:**
Do an action that displays a HUD, for example replying to a comment (for a success one) or posting while offline (for a failure one). 
Once the message is displayed you can tap anywhere on the screen to dismiss it.
> HUD messages are now dismissible by tapping anywhere on the screen

- WordPress/WordPressShareExtension/ShareExtractor.swift
This PR updates the `ShareExtractor` order, so that whenever the ImageExtractor can handle a request, it'll be returned **before** the Text Extractor.
Fixes #5690
1. Open the Google Photos app
2. Select a photo and tap the sharing icon
3. Select WordPress as the sharing target
Verify that the actual picture gets shared (instead of the local URL)
> ShareExtension: Fixing Sharing from Google Photos

- WordPress/Classes/ViewRelated/NUX/Login2FAViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginLinkAuthViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginLinkRequestViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginSegueHandler.swift
- WordPress/Classes/ViewRelated/NUX/LoginSelfHostedViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginWPComViewController.swift
- WordPress/Classes/ViewRelated/NUX/NUXAbstractViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Small improvement to #7066
Based on: https://www.natashatherobot.com/protocol-oriented-segue-identifiers-swift/
To test, ensure the new login process is still working:
1. use a debug build to:
2. Login via both wp.com and self-hosted
3. Ensure all necessary screens appear, and that the epilogue screen appears at end
Got time for this one?
> Login: Segue identifiers become an enum

- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
**Fixes** #7048
**IMPORTANT: All the string files will have to be regenerated.**
**To test:**
Post while offline, check that the error message is correct (were instead of where)
> Fixed typo on recently released strings

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
This PR updates the Mark Notification as Read mechanism.
Fixes #7074
We'll mark Notifications as Read in two scenarios:
- The user explicitly selects a notification row
- We're on SplitView, the user opens Notifications, and the preselected row _was_ unread
1. On a iPhone device!
2. Log into a dotcom account with unread notifications
3. Try opening a Post Mention Notification
4. Verify that the Reader is onscreen
5. Hit back and verify the note is marked as read
6. Repeat 4 and 5 for a **Comment Mention**. The Note Details should be rendered instead
1. On a iPhone device!
2. Log into a dotcom account with unread notifications
3. Try opening a Comment Mention Notification
4. Verify that the Notification Details are Onscreen
5. Hit back and verify the note is marked as read
1. On an iPad …
> Notifications: Mark as Read

- WordPress/Classes/ViewRelated/Notifications/Tools/KeyboardDismissHelper.swift
Whenever the user interactively dismisses the ReplyTextView component, in some conditions, the Content Offset was getting reset.
As a result of this, you would see the ScrollView getting back to `offset.y = 0`, as soon as the dragging OP began moving the Reply component.
In this PR we're fixing this. Yay!
1. Open a Comment-Y Notification
2. Press over the ReplyTextView component
3. Drag downwards to dismiss the keyboard
Verify that the TableView's cells follow your finger. There should not be any "Reset to Zero" flicker anymore.
Elisa, may i bug you with a fun one?
🔥
> Notifications: Smoot Interactive Keyboard Dismissal

- WordPress/Classes/ViewRelated/NUX/EpilogueSegue.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #7088
To test:
- Use the new login process to login (on for debug builds)
- Ensure that the blog list navigation controller's transitions still work
- Also ensure that the tab bar can still show UIAlerts—such as when tapping "Log Out" from the Me tab
_You found it you have to review it_ 😝
> Fix Login's unwind segue breaking transitions

- WordPress/Classes/Networking/SharingServiceRemote.swift
Although i've been unable to reproduce this crash, i'm adding a couple `guard let` in the spot that, according to the crashlog, the app was crashing.
Closes #7102
Please, run a smoke test over Publicize, and make sure nothing breaks.
Eric, may i bug you with this one?
> SharingServiceRemote: Crash Failsafe

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
In this PR we're replacing an Implicitly Unwrapped Optional, main suspect of crash #7091, with an`if let` sequence.
Fixes #7091
I'm afraid there are no specific repro steps. Please, try forcing `Post.authorForDisplay`  and `dateForDisplay.dateForDisplay` to return nil values, and verify nothing sets on fire.
> ReaderDetailViewController: Replacing IUO with if let

- WordPress/Classes/Services/OnePasswordFacade.m
- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
In this PR we're addressing two 1P Signup bugs:
- Autogenerated password was being displayed in the Username field
- Autogenerated password max-length constant was invalid
Closes #6319
1. Make sure you've got 1Password installed
2. Fresh install WPiOS
3. Hit the signup button
4. Attempt to generate a password. Verify that the min/max length ranges from 7-50
5. Verify that the username / password are correctly displayed, in the right fields
Needs review: @nheagy May i bug you with this one?
> Signup: Fixing 1Password Integration

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Tools/KeyboardDismissHelper.swift
This PR fixes an unintended animation, in which the Notification Details navigation arrows would move around the navigation bar.
Sample video here: [CrazyArrows.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/962486/CrazyArrows.zip)
1. Open a Comment-Y Notification
2. Press over the Reply Text View component
3. Swipe downwards
Verify that the `Previous` / `Next` notifications arrow don't dance around the navbar anymore.
> Notifications: Arrows won't dance anymore

- MIGRATIONS.md
- WordPress/Classes/Models/MenuItem.h
- WordPress/Classes/Models/MenuItem.m
- WordPress/Classes/Networking/MenusServiceRemote.m
- WordPress/Classes/Networking/Remote Objects/RemoteMenuItem.h
- WordPress/Classes/Services/MenusService.m
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 59.xcdatamodel/contents
- WordPress/WordPressTest/MenusServiceTests.m
Fixes #7108 
This is a simple change that persists the `classes` field array for menu items coming in from the API, and upon subsequently saving a Menu.
To test:
1. Open up wp-admin on a .com or Jetpack site (self-hosted not supported for Menus)
2. Go to Appearance > Menus
3. In the top right, open up Screen Options, check the CSS Classes option if needed and reload the page.
4. Under Menus, check that you have a menu, or create one if needed.
5. Note which Menu is selected, it should be the "Primary Menu", select it if needed.
6. Open one of the menu items to view it's field options.
7. Type in a couple of custom classes under "CSS Classes (optional)".
- Ex: `special_class, extra_special_class` which auto-formats to `special_class extra_special_class` upon save.
8. Open up the app from …
> Menus: persist CSS classes for MenuItems

- WordPress/Classes/Networking/JetpackServiceRemote.m
Follow up to #7071. It turns out that the endpoint expects slashes in the path to be replaced with a double colon instead of simply escaping the character. Props to @maxme who noticed the incorrect response when testing the REST endpoint with his own blog. 
Needs review: @koke would you take a peek since you're already familiar with this?
> Use character replacement instead of string encoding.

- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
**Fixes** #7130 
**To test:**
We don't have steps to replicate, but you can trigger background refresh from XCode and see that it works fine.
Original PR for reference: https://github.com/wordpress-mobile/WordPress-iOS/pull/7049
> Attempt to fix crash by explicitly unwrapping

- WordPress/Classes/ViewRelated/Post/EditImageDetailsViewController.m
Fixes #7137
There was an issue with how we were calculating `shouldHighlightRowAtIndexPath` and checking the wrong values.
Separately, it looks like featured images are broken altogether here and cannot be enabled/selected. Also, when hitting the detail for a featured image in the post options results in an all white scrollview of sorts. @frosty any ideas there?
To test:
1. Run, open the visual editor.
2. Insert media either from the library or device.
3. Tap to open the `EditImageDetailsViewController`.
4. Try and select the Caption cell, make sure you can.
Needs review: @frosty can you take a spin of this one?
> Media: fix issue with caption cell not selecting.

- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Fixes #7142 
To test:
We don't have steps to replicate, but you can trigger background refresh from XCode and see that it works fine.
Original PR for reference: #7049
> Bug fix: only scroll to the top of the table on new data with content

- WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m
Fixes a separate issue seen in #7138
Declaring `url` property as `dynamic` since we're actually using the property from the super class, `WPImageViewController`. Nice fix as suggested by @frosty 🎩 
To test:
1. Open editor, options.
2. Add a featured image, select it to view the detail.
3. Ensure the image loads as expected within the scrollview.
Needs review: @frosty at your leisure!
> Post Options: fix issue with subclassed featured image VC.

- WordPress/Classes/ViewRelated/Post/EditImageDetailsViewController.m
- WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m
This brings in the three commits from https://github.com/wordpress-mobile/WordPress-iOS/pull/7138 and https://github.com/wordpress-mobile/WordPress-iOS/pull/7140 in which a user could not select the "Caption" cell to add/edit a caption, as well as preview a featured image.
These bugs were introduced sometime in `7.4` or `7.5`, if we could go ahead and bring them into `7.6` it would be great!
Needs review: @astralbodies your call on this one for `7.6`! These are minimal, recent bugs. You can follow the testing steps from both PRs if you'd like. I'll be on a ✈️ so feel free to merge if ready.
> 7.6: cherry-picks featured image/media caption fixes.

- WordPress/WordPressShareExtension/ShareExtractor.swift
- WordPress/WordPressShareExtension/ShareViewController.swift
Tweaked the share extractor so we can extract both image and text. I've also tweaked the URL extractor to only consider non-file URLs because otherwise sharing from Google Photos would show the link (#5690)
Fixes #7124 
To test:
1. Install the YouVersion app. If asked, enable Verse of the day.
2. Look for an image "Verse of the day".
3. Tap the share icon and select WordPress as a sharing target.
4. It should include both the image and a link
Original instructions in #7124, but you can skip creating the account and then just scroll until you find an image.
> Share: Extract both image and text if available

- WordPress/Classes/Utility/FeatureFlag.swift
- WordPress/Classes/Utility/InteractiveNotificationsManager.swift
- WordPress/Classes/Utility/KeychainTools.swift
- WordPress/Classes/Utility/PushNotificationsManager.swift
- WordPress/WordPressTest/EditorSettingsTests.swift
- WordPress/WordPressTest/FeatureFlagTest.swift
To make it clearer where our feature build configurations apply.
When setting up a feature flag, it's not entirely clear where a build configuration will apply, especially 'alpha' and 'internal'. By renaming them, hopefully setting up a new feature flag will be easier thus encouraging their use.
To test:
- make sure everything still builds
- make sure the BuddyBuild build still runs
> Rename feature flag build configurations to be easier to understand

- WordPress/Classes/Services/ShareExtensionService.swift
- WordPress/Classes/System/Constants.h
- WordPress/Classes/System/Constants.m
- WordPress/WordPressShareExtension/ShareViewController.swift
**Fixes** #7027 
**To test:**
_Test the new functionality:_
Do a share and select one site that is not your primary site.
Do another share and verify that the last used site is pre-selected.
_Test that nothing else broke:_
Uninstall the app.
Install it and log in.
Do a share and check that your primary site is selected.
> Preselect the last used site on Share Extension

- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/ViewRelated/NUX/Login.storyboard
- WordPress/Classes/ViewRelated/NUX/NUXAbstractViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
- WordPress/Classes/ViewRelated/NUX/SigninLinkMailViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninLinkRequestViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninWPComViewController.swift
Add the wpcom-only and self-hosted-only entry points to the new login flow.
To test:
1. Test the self-hosted login entry point
- login with a wpcom account
- use the `+` to add a new self-hosted site
2. Test the wpcom login entry point
- logout from wpcom with a self-hosted site already added
- from the Me tab, tap `Log In`
Needs review: @kurzee  
Want to look at some login stuff, or want me to find a different victim?
> Add entry points to new login flow

- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
I found a bug in the media picker data source, where it could end up with stale data and show duplicate media items.
* The data source was creating a media service on `init`, with a new background context. It would hang onto this and use it for every request to sync the library.
* If the user uploaded media through the app whilst a picker data source was alive (for example, in the Media Library section, behind the editor), the new media would be added on the main context and the background picker's context would _not_ be updated.
* When the background picker next performed a sync and attempt to merge changes from the server, it wouldn't see the new local media items, and recreate them.
* This would result in duplicate media items once the picker saved up to the main context.
To fix it, …
> Fix duplicates in Media Library

- WordPress/Classes/Services/MediaService.h
- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.h
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR adds upload functionality to the media library.
You can upload media either by tapping the new + button in the nav bar, or by tapping the Upload Media button in the no results view if you have no media.
During upload, we're currently showing blocking progress using the HUD. I think we can ditch this fairly soon, but I wanted to go for the simplest implementation first. You can tap on the HUD to cancel any pending uploads.
To test:
* Attempt to upload media!
* Try from an empty library and a library with existing content.
* Try cancelling uploads
* Try from dotcom and self hosted sites
* Try both photos and videos
* Note that progress reporting seems to be more granular on a device vs in the simulator
@SergioEstevao I also made a couple of tweaks to the media …
> Media Library: Add basic upload functionality

- .hound.yml
- WordPress/WordPress.xcodeproj/project.pbxproj
I've enabled [Hound](https://houndci.com/) on this repo so it'll take care of running SwiftLint on each PR.
I've removed the Lint Check build step, but you can still run SwiftLint locally with `rake lint` or with the pre-commit git hook from `rake git:instal_hooks`
> Use HoundCI for Swift linting

- WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
If there's a partial tag, finish it and add a comma, otherwise ignore the return.
See #7100 
To test:
- Create a new post, go to options, tags
- Pressing return on the keyboard should be ignored
- Type some text
- Pressing return should add a comma and start a new tag
- Any extra return should not add any other commas
> Improve handling of return in tag picker

- WordPress/Classes/Models/Blog+Capabilities.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR removes the upload buttons in the Media Library for users who don't have permission to upload files to a site. Both the + button in the navigation bar and the upload text / button in the 'no results' view should be hidden.
To test:
* For a site where you have permission to upload files (Author role or higher) and an empty media library, visit the Media Library section in the app and ensure that you can see the + / Upload buttons indicated above.
* For a site where you don't have permission to upload files (Contributor role or lower) and an empty media library, visit the Media Library section in the app and ensure that the + / Upload buttons indicated above are *not* present.
> Media Library: Hide upload buttons for users who don't have permission

- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
**Fixes** #3516 
This is a solution to the last stated problem on #3516:
> draft being published with the original creation date instead of the current date
As part of https://github.com/wordpress-mobile/WordPress-iOS/pull/7129 the places where the word "Publish" is used have been cleaned up. 
On this PR I am setting the date_created_gmt when "Publish Now" is tapped on the Editor or "Publish" is tapped on the post list. This is not a perfect solution, since a previously published post that was changed to a draft and then published will not retain its original publish date. However, that seems like a much more unusual case, and the publish date can be modified via the post options. 
Note: we still have to clean up/rethink our publishing logic, but this is a step closer to a consistent …
> Set date_created_gmt on publishing

- WordPress/Classes/Services/MediaLibrary.swift
Before I get ahead of myself, let's go ahead and do a code review of the initial `makeMediaWith` methods on the `MediaLibrary` that works with the new exporters.
This will very quickly change to what we discussed in Amsterdam of these methods becoming `addMediaWith` and carrying forward with the upload themselves. However, the base implementation seen here is what handles the complete export assets into uploaded Media objects so let's focus on that for a bit.
One new thing that we do here is actually enqueuing the export operations on a background thread, which helps prevent UI lockage for larger exports. These might have to be on a specific serial queue later.
To test:
1. Make sure it compiles after a Clean > Build.
2. Review the code 🔍 
Needs review: @frosty and @SergioEstevao as usual …
> MediaLibrary: make/addMedia methods and configuration.

- WordPress/Classes/Extensions/NSURL+Exporters.swift
- WordPress/Classes/Extensions/PHAsset+Exporters.swift
Fixes #7257 
To test:
- Record a video on the device with location info
- Make sure the option to Strip Geolocation is activated on : Me->App Settings-> Multimedia
- Add to the post the video recorded on the first step
- Publish the Post
- Go to the web, download the video from the Media Library
- Open the video in QuickTime Player
- Press CMD+I
- Check that no location information is present.
> Strip location from videos when option is selected.

- Podfile
- Podfile.lock
- WordPress/Classes/Networking/MediaServiceRemoteREST.m
- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR adds analytics to the media library and media service to track uploads, in line with Android's events. Added events:
```
WPAnalyticsStatMediaLibraryAddedPhoto
WPAnalyticsStatMediaLibraryAddedVideo
WPAnalyticsStatMediaServiceUploadStarted
WPAnalyticsStatMediaServiceUploadFailed
WPAnalyticsStatMediaServiceUploadSuccessful
WPAnalyticsStatMediaServiceUploadCanceled
```
I've currently set this to "do not merge", until the analytics branch I'm targeting is merged and released. I'll update the Podfile for this PR branch when that happens.
To test:
* Perform uploads to check each event – photo and video uploads (successful), cancel uploads in progress, and make uploads fail, ensure that events are being sent / arriving as expected.
> Media Library: Add upload analytics

- WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
This is a quick fix for #7254 in 7.7. I'd like to refactor this into something easier to follow, with unit tests, but I'll do that for develop later.
Only disallow typing a comma at the end of the string.
Only remove comma with space at the end of the string.
Fixes #7254 
To test:
- Type or add several tags.
- Move the cursor to one of the tags in the middle.
- Ensure you can delete tags, commas, and type new tags in the middle of the string.
> Improve tags replacement logic

- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift
We got reports of the Title + Details labels being displayed with a backgroundColor that does not match with the rest of the cell.
(My suspicion is) that, under unknown conditions, `backgroundColor.didSet` is not being called. In this PR we're implementing a simple safety measure, which involves explicitly setting the Label's Background Colors.
1. Launch WPiOS and log into a dotcom account
2. Switch over the Notifications Tab, and verify that the Cell Background (always) matches the Label's Background.
> NoteTableViewCell: BackgroundColor Failsafe

- WordPress/Classes/Models/AbstractPost.h
- WordPress/Classes/Services/PostService.m
- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListFilter.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
We have some reports of "lost posts" that aren't actually lost. What happens is when the app crashes/closes when editing a new (unsaved) post, it will appear to be gone on relaunch, but it'd actually be at the bottom of the published posts list. This is because the post had no date, so it's sorted that way. We can't set a date on drafts because then all kind of wrong things happen.
While this is not ideal, it's the best solution I could imagine without a major refactor of how we store and save posts in the app.
What this PR does:
- Put any post with `remoteStatus == .local` in the Drafts filter
- Populate `dateModified` as soon as a draft is created
- Switch to the Drafts filter when a new one is created. This way the list will show the right post list if the app closes/crashes.
- Switch …
> Improve handling of local drafts

- WordPress/Classes/Networking/MediaServiceRemoteREST.m
- WordPress/Classes/Networking/MediaServiceRemoteXMLRPC.m
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
- WordPress/WordPressApi/WordPressComRestApi.swift
- WordPress/WordPressApi/WordPressOrgXMLRPCApi.swift
This PR changes the way progress report is done in two ways:
- Now failed uploads report their progress has completed and don't go back to zero total Units and completed Units
- XML-RPC calls have an extra 1 unit in progress to account for processing time in server, so the call only report 100% progress when an answer is given from the server and not when the upload is done.
To test:
- Using the post editor, insert media and see if all progress report is done correctly
- Try scenarios where media fails to upload (go offline, exceed limits of files)
- Test on all site scenarios ( WP.com, self-hosted, self-hosted Jetpack)
- Test also on the media library of the site.
> Improve upload progress report

- WordPress/Classes/ViewRelated/Menus/MenuItemsViewController.m
Fixes #7269 
This prevents the UI issue seen in #7269 as well as the crash that can occur from navigating within that UI state. Simply fixed by closing out the "insertion" views that show up when a menu item is toggled for adding items around it, before presenting the detail view.
To test:
1. Repeat the steps in the original issue.
2. Now, the items should close once you select the item.
3. When returning from the selected item's detail view, there shouldn't be any more of the "insertion" views.
4. Tap on any remaining items, make sure they don't crash when selected.
Needs review: @elibud can you take a quick peak at this one? 🔍🐞🔎 
Note: there are some constraint issues going on Menus, for another day's efforts.
> Menus: prevent crash and bad UI state when editing items.

- WordPress/Classes/Utility/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
This PR removes the feature flag for the media library! The only thing it was used to control was whether the Media item showed in the Blog Detail list.
To test:
* Check the code looks okay and builds
* Perhaps try a release build and check the Media item shows?
> Remove Media Library feature flag

- WordPress/Classes/Categories/UIImageView+Gravatar.h
- WordPress/Classes/Categories/UIImageView+Gravatar.m
This stops relying on blavatar for self hosted sites and will use the blog.icon
passed through photon.
To avoid some problems with resizing, the site icon size is fixed at 40x40 for
download. We previously tried to calculate it based on the imageView size, but
for some reason it's 74x73.5 by the time the cell is being configured
Fixes #6802 
To test:
- Ensure site icons are visible for both wp.com and Jetpack sites
> Fix site icon for Jetpack sites

- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
- WordPress/WordPressApi/WordPressOrgXMLRPCApi.swift
A couple of tweaks to fix some issues with upload progress reporting in the media library. Mainly switching to use asset identifiers instead of media IDs (which were all 0, as they were new media).
To test:
* Upload items in the media library, ensure that progress reporting works as expected. 
* In particularly, check cases when items fail.
* Check on self-hosted as well as wpcom.
> Media Library: Upload progress tweaks

- WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift
It was bugging me that in Aztec, the scrollbar was inset from the edge of the view. I adjusted the insets so that it now sits against the edge. 
I'm totally unfamiliar with Aztec, so please let me know if I did this wrong (or it was intentional) or I broke something :)
To test:
* Write a post in Aztec that's long enough to enable scrolling.
* Check the scroll indicators appear correctly.
> Aztec: Adjust text container inset so scrollbar appears at edge of view

- WordPress/Classes/System/WordPressAppDelegate.m
Closes #7291
Not my most proud code but it's the least amount of change in the rest of the app.
Note: We'll remove this code most likely before the end of the code freeze or after 7.9.
To test:
1. Comment out the ifdef & endif to test for debug builds.
2. Launch the app with Aztec disabled.
3. Verify Aztec gets enabled.
4. Turn off Aztec.
5. Relaunch and verify Aztec is not re-enabled.
6. Change the main target version & build number.
7. Relaunch and verify Aztec is re-enabled.
> Quick hack to force Aztec on for every internal user upon initial launch

- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
`WPAnalyticsStatLoginEmailRetryViewed` was slated to be removed by overlooked when updating the analytics pod.  This pr adds the key back for now to silence a compiler warning and fix a busted test. 
> Adds back an errant analytics key. Will remove it in a future update.

- WordPress/Classes/Models/Blog.m
Fixes #7006 
This adds consistency, since currently comments for Jetpack sites can be liked from notifications. On this PR we add the functionality to like them from Site->Comments by updating how whether a blog supports or not Likes is determined.
To test:
1. Select a self-hosted site without Jetpack, navigate to Comments, select a comment, check that Like is not available.
2. Select a self-hosted site with Jetpack, navigate to Comments, select a comment, check that Like is available.
> Update blog support method for CommentLikes

- Podfile
- Podfile.lock
- WordPress/Classes/Services/Store.swift
The app now builds in Xcode 9, although tests crash due to a OCMock issue I'm still investigating.
It both builds and tests in Xcode 8, so I think it's enough for a first PR
I commented out conflicting code in Store, but we should probably remove all IAP code in another PR
See #7343 
To test:
(You might need to clean before build when switching Xcode versions)
- Build with Xcode 9
- Build and test with Xcode 8
> Make the app build in Xcode 9

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
I've been unable to repro this crash. The cause isn't exactly clear, but the spot definitely is. 
In this PR we're implementing **guard let**, along with a few safety changes, that should prevent crashig whenever any of the required properties isn't there.
Closes #7273
Please: Verify that the Reader's Details Comments Action gets properly set up.
Thanks in advance sir!! hope you're doing more than great Eric!!
> ReaderDetailViewController: Guard Let FTW!

- WordPress/Classes/Services/BlogService.m
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Blog/SiteIconPickerPresenter.swift
- WordPress/Classes/ViewRelated/Me/GravatarPickerViewController.swift
- WordPress/Classes/ViewRelated/Media/ImageCropViewController.swift
**Fixes** #7344 
**To test:**
1. Select one site
2. Tap on its icon
3. Select Change Icon
4. Select the Media Library
5. Chose a square item and do not resize it nor crop it
6. Once the item is set as the site icon, check on the Media Library that there is not a duplicate instance of it.
7. Do the same steps but modifying the media item, check that a new media item is created.
8. Do the same steps but choosing an image from your camera roll, check that a new media item is created.
> Avoid creating new media item when unnecessary

- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift
We've been after an issue that's affecting Notifications List for a while: the Label's background color is getting out of sync with the BG Color, in an unknown scenario.
This can probably be tracked back to #6009 (in which we began matching the Label's Background Colors with the Cell's BG color as an optimization). Since i've been unable to pinpoint the exact scenario that breaks, let's revert that optimization.
Closes #7337
Closes #7040
1. Launch WordPress iOS
2. Verify that Unread Notifications / Highlighted Notification cells look good
> Notifications Cell: Keeping Label's background Clear Color

- WordPress/Classes/ViewRelated/NUX/EpilogueSegue.swift
- WordPress/Classes/ViewRelated/NUX/Login.storyboard
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
This PR tweaks the way the login epilogue transitions into view and how it is dismissed from view. 
To test:
Log in via the new Login flow and observe the epilogue screen as it is presented and dismissed on both an iPhone and iPad.  Confirm the animation is smooth, there is no visual artifacts or jumps, and the previous login view controller is never visible when dismissing.
> Login: Smooths out the epilogue animation.

- WordPress/Classes/ViewRelated/System/WPTabBarController.h
Fixes warning due to method declaration left in header. (doh!)
To test:  Build the project and confirm the warning is removed.
> Login: Remove method definition in header.

- WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
In #7100 I disabled the autocorrection in the tags field, and I'm not sure it was a good idea.
From a support request, it seems users are expecting it:
> Is it possible to activate the keyboard word selector (the three words above the keyboard) in the tag interface for those of us who are spelling-challenged and fat finger typists?
> Enable autocorrection in tags field

- WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib
Fixes #7363
At some point it looks like the IBAction connection to the follow button's touchupinside event was unset.  This PR restores it.
To test:
Follow the steps in the issue and confirm that you can now toggle following status via the site header.
Needs review: @elibud could I trouble you for this review?
> Reader: Wire up missing outlet to site header follow btn.

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Fixes #6867 (mostly)
This PR attempts to fix the jump in the reader post detail when scrolling to the end of a long post. The separate navbar animation was causing a conflict so its been moved inside the animation block. 
There remains a noticeable stutter if, while at the bottom of the post you scroll up slightly, then scroll back down in such a way that the bars are set to hide, then show before the hide animation completes. The fix for this eludes me but I'm fine to circle back on that later since this PR addresses the larger issue.
To test:
- Confirm the bug by scrolling to the bottom of a long article in the post detail. Observe the animation stutter. 
- Switch to this branch and repeat.  Note that upon reaching the bottom of the post the bars animate smoothly back into view and the …
> Reader: Fix scroll bounce at end of post detail.

- WordPress/Classes/Categories/UIImageView+Gravatar.h
- WordPress/Classes/Categories/UIImageView+Gravatar.m
- WordPress/Classes/ViewRelated/Blog/BlogDetailHeaderView.m
- WordPress/Classes/ViewRelated/Blog/BlogListDataSource.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
- WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
- WordPress/Classes/ViewRelated/Post/PostPostViewController.swift
**Fixes** #7345 and improves on https://github.com/wordpress-mobile/WordPress-iOS/pull/7268
**To test:**
1. Change the icon of a private site.
2. Check that the icon looks good in: BlogList, BlogDetail, PostList, PostPost, Notification settings.
3. Remove the icon for the site, and do number 2 again.
4. Check that all that still works for Public sites. 
> Support for setting icon for private sites

- WordPress/Classes/ViewRelated/Blog/SharingDetailViewController.m
**Fixes** #6959 
**To test:**
Start on the develop branch: 
1. Connect a sharing service to one of your sites.
2. Break the connection
3. Try to repair it, once the WebView is opened, try to close it form the cross on the top left.
4. Enjoy the app hanging.
5. Check-out this branch and repeat.
6. See that it works, pat yourself in the back for such great testing abilities.
> Sharing: Broken publicize reconnection fixing can not be cancelled

- WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
- WordPress/Classes/ViewRelated/Post/PostEditorSaveAction.swift
- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
- WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m
Fix #7387: Replace the _Post_ button to _Publish_ and update translation comment
> Fix #7387: Replace the _Post_ button to _Publish_ and update translation comment

- WordPress/Classes/Extensions/WPStyleGuide+Aztec.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Updates the format bar colors in Aztec to match the style guide.
To test:
* Launch the Aztec editor
* Check the colors look right:
I know the tint color currently isn't correct in the header and list menus for selected items – this will require an Aztec library change.
Needs review: @jleandroperez  
> Update Aztec format bar colors

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Aztec/Extensions/FormattingIdentifier+WordPress.swift
This PR updates the icons in the format bar. The read more and HTML icons have been updated, and the bar will now reflect different heading levels as they're selected in the content.
To test:
* Open Aztec, and check the read more and HTML icons are new
* Try using heading levels H1 to H6 and check the header icon in the format bar gets updated.
> Aztec: Update format bar icons

- WordPress/Classes/ViewRelated/Aztec/Extensions/FormattingIdentifier+WordPress.swift
This PR reverts the 'read more' icon change in the Aztec toolbar. I updated it to the wrong icon, and I'll need to update Gridicons to pull in the new one.
> Aztec: Revert the latest 'read more' icon change in the format bar

- WordPress/Classes/Services/AccountService.m
Silence a compiler warning about an incorrect type being passed. 
> Pass the bool, not the string. Derp.

- WordPress/Classes/Extensions/NSAttributedString+StyledHTML.swift
- WordPress/Classes/ViewRelated/NUX/Login2FAViewController.swift
Fixes #7277
I was unable to reproduce this crash, despite many attempts, however this eliminates the `try!` that was causing the crash. Also removes two unnecessary lines in `Login2FAViewController.swift` that I found while working on this ;)
To test:
1. ensure that attributed text build with this method still appears correctly, such as:
- the underlined text on the 2FA verification screen
- text on the plans screens
- text on the delete site screen
_You touched this last, it seems, want to check out my hacking?_
> Fix crash in attributedStringWithHTML

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR fixes a crash on the Aztec editor, when tapping twice on the Headers Icon or Bullets icon make the app crash. This only happen on the iPad
To test:
- Start the app on the iPad
- Start the Aztec editor
- Tap on the Headers option in the toolbar
- Tap on the Headers options again
- Check the app doesn't crash
- Try the same but now press another icon on the toolbar
- Check that everything works.
> Fix crash on Aztec when pressing header icon twice.

- WordPressKit/WordPressKit/WordPressOrgXMLRPCApi.swift
Fixes #7398 
To test:
A practical test would be to modify an xmlrpc.php to return an HTML document and 403 error code (mimicing the situation that prompted this issue and PR), but confirming that the data to string conversion is properly performed would be sufficient I think. 
Needs review: @elibud, would you mind taking a peek at this one?
> Include string representation of data with error userInfo.

- WordPress/Classes/Services/LoginFacade.m
If we can't get the blog's version then pretend it's good so users aren't stuck
without being able to log in.
To test:
You need a self hosted site that doesn't include the version in the `wp.getOptions` response. You can do that with the following code:
```php
add_filter('xmlrpc_blog_options','no_version_in_xmlrpc');
function no_version_in_xmlrpc($options) {
unset($options['software_version']);
return $options;
}
```
Then try to log in to that site and verify that you can log in and it doesn't show an error about the version being too low
> Update version check on login

- WordPress/Classes/Extensions/WPStyleGuide+Aztec.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR adds a 'beta' tag to the top right of the Aztec editor. When we launch the beta, this button will be hooked up to show more info or release notes in a web view.
> Aztec: Add Beta tag to editor

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #7106 
When enter is pressed while the caret is in the title view, the caret will be moved to the content view.
If text containing newlines is pasted into the title view, the newlines will be removed before pasting.
**Test 1:**
* Open the editor.
* Place the caret in the title view and press enter.
* The caret should be moved to the first position of the rich text view.
PS: Combine the above steps with having content in the title and rich text view.
**Test 2:**
* Copy text containing several newlines.
* Pase the text in the title view.
* Make sure all newlines are removed.
> Newlines are no longer allowed in the title field.

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
In #7366 I fixed an issue with a glitchy bounce when scrolling to the bottom of the post detail.  The fix had a glitch that would keep the nav bar from reappearing if the user started scrolling back to the top before reaching the bottom of the post.  This PR fixes that glitch. 
To test:
- Scroll part of the way down a long post.  Confirm that bars properly hide.
- Scroll back up a bit.  Confirm that bars reappear.
- Test the original issue and confirm the fix is still in place. 
Needs review: @jleandroperez game for another peek at this one? 
cc @elibud
> Reader: Tweaks the bar animation so the navbar always reappears.

- WordPress/Classes/Networking/ReaderPostServiceRemote.m
Fixes an issue where html entities were not being escaped in the author's name.
To test:
Follow a blog like `https://taliwutblog.wordpress.com/` where the author's name has an ampersand.  Confirm the ampersand is shown and not its html entity. 
Needs review: @kurzee One more review for the road, sir?
> Reader: Escape html entities in the author's name.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes a broken build. Looks like a placeholder method declaration was kept along with the actual implementation.
To test:
* Check everything builds.
> Aztec: Remove duplicate method declaration due to merge

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This fix a crash on the Aztec editor, when tapping twice on the Headers Icon or Bullets icon make the app crash. This only happen on the iPad
To test:
- Start the app on the iPad
- Start the Aztec editor
- Tap on the Headers option in the toolbar
- Tap on the Headers options again
- Check the app doesn't crash
- Try the same but now press another icon on the toolbar
- Check that everything works.
> Make sure the options views is present and is no the same.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This add the keyboard shortcuts to the Aztec editor in the main app.
The PR is basically a copy over of this [PR in Aztec](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/566).
To test:
- Start the app on a iPad device
- Make sure you have the Aztec editor active
- Test the shortcuts
> Add keyboard shortcuts to Aztec editor.

- WordPress/Classes/Utility/ImmuTable.swift
- WordPress/Classes/Utility/WPImmuTableRows.swift
- WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
This PR updates the App Settings preferences toggle for Aztec.
Note: The button in the footer currently doesn't link anywhere.
To test:
* Launch the app, visit App Settings
* Check the correct current editor setting is reflected in the options
* Try changing between the different options and check the correct editor is presented
* Ensure the 'help' footer appears if you select the Beta option, and disappears if you toggle a different option.
* Check the changes to `ImmuTable` footer delegate methods didn't affect other VCs that use `ImmuTable`.
> Aztec: Update preferences toggle

- WordPressShared/WordPressShared/Core/Utility/WPFontManager.m
- WordPressShared/WordPressShared/Core/Views/WPStyleGuide+DynamicType.swift
This PR make sure that before a font is loaded from file is not already loaded.
This avoid some logging errors being printed that can be confusing to HE and us.
To test:
- Make sure in the logs you don't see `"Failed to load font: XXXX"`
> Only load fonts if they are not available yet.

- WordPress/Classes/Extensions/WPStyleGuide+Aztec.swift
- WordPress/Classes/ViewRelated/Aztec/Extensions/Header+WordPress.swift
- WordPress/Classes/ViewRelated/Aztec/Options/OptionsTableView.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
A few more tweaks to button and table colors for the format bar.
To test:
* Build and run Aztec, check the colors look correct:
* Any highlighted items in the format bar should now be WordPress blue
* The table view for headings and lists should now have a background colour of `lightGrey` on iPhone and white on iPad.
* The background of selected cells on the tables should now be `greyLighten30` on iPhone and `lightGrey` on iPad.
* The "Default" paragraph / heading style should now have no icon in the list.
> Aztec: Update format bar colors

- WordPress/Classes/ViewRelated/Aztec/Processors/VideoProcessor.swift
This PR fixes the following problem:
The poster parameter in the video shortcode always referred to a local file on my device, like this:
```
[video src="https://videos.files.wordpress.com/4wBIvbhH/img_9678-2.mov" poster="file:///var/mobile/Containers/Data/Application/1E4DD69E-2A51-4B4A-A6F1-8F35DFB3740A/Documents/Media/img_9678-2-thumbnail.jpeg"
```
To test:
- Make sure Aztec is active.
- On a self-hosted site create a new post
- Add a video to the post
- After the upload is done
- Switch to HTML mode
- Check that no poster image attribute is set on the image
- Switch back to visual and see if the preview image shows up.
> Don’t allow video shortcodes to point to local files.

- WordPress/Classes/ViewRelated/System/FancyAlerts+AztecAnnouncement.swift
This PR introduces two small tweaks to the Aztec announcement UI.
1. We now track an analytics event for 'editor toggled on' if the user taps the 'Try It' button
2. We show an alternative message if the user already had Aztec enabled.
To test:
* Check out `develop`, run the app and enable Aztec in App Settings.
* Build and run this version over the top.
* You should see the announcement UI shown above.
* Delete the app from the simulator and build and run again.
* After logging in, you should see the original two step announcement UI asking you to enable Aztec.
> Aztec announcement tweaks

- WordPress/Classes/Extensions/WPStyleGuide+Aztec.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
The divider color (top and bottom lines, and between the add media button item and the other items) in the format bar in Aztec wasn't quite right. This PR updates it to `greyLighten30`.
To test:
* Build and run, check the color is correct in Aztec.
> Aztec: Fix incorrect divider color in format bar

- WordPress/Classes/Utility/ImmuTable.swift
- WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
Fixes a bug where I accidentally broke ImmuTable footers.
To test:
* Build and run, check footers now look correct and wrap over multiple lines. Two examples:
* Me > App Settings (seen in screenshot above)
* Blog > Plans
> ImmuTable: Restores auto sizing footers

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Me/MeViewController.swift
- WordPress/Classes/ViewRelated/System/FancyAlerts+AztecAnnouncement.swift
- WordPress/Classes/ViewRelated/System/FancyAlerts.storyboard
- WordPress/Classes/ViewRelated/System/WPTabBarController.h
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
This PR enables the various links in the Aztec beta announcements UI.
**To test:**
Build and run, and check the following links work as expected:
* In the Aztec editor, the 'beta' tag should link to our placeholder blog post
* In the announcement UI, the 'beta' tag and what's new text should link to the placeholder blog post
* On the second announcement screen (after you tap Try It), the 'Me > App Settings' link should take you to the app settings screen.
> Aztec: Enable webview links for announcements UI

- Podfile
- Podfile.lock
Integrates Aztec Beta 7.
The only change is that it's now possible to indent lists using a hardware keyboard with Tab, and SHIFT + TAB.
> Integrates Beta 7 of Aztec.

- WordPress/Classes/Categories/Media+WPMediaAsset.m
- WordPress/Classes/Models/Media.m
- WordPress/Classes/Services/MediaService+Legacy.h
- WordPress/Classes/Services/MediaService+Legacy.m
- WordPress/Classes/Services/MediaService.h
- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/Utility/Media/MediaFileManager.swift
- WordPress/Classes/ViewRelated/Blog/SiteIconPickerPresenter.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/MediaTests.swift
This PR adds legacy support for the original `MediaService` implementation. This also adds support for existing `Media` objects that were not exported with the new file and URL specifications.
Why legacy support? Moving forward, I don't want to just merge in use of the new exporting code (and walk away). Instead, we'll support the original implementation now seen in this category and revert to it via a feature flag. While we bring in use of the new exporting code, we'll elevate it's use through the feature flag support, e.g. internal, testflight, release.
Eventually we can remove this category altogether, only using the new exporting code itself.
Changes:
- Excise the relevant code from `MediaService` and support it via `MediaService+Legacy`.
- Update methods just a bit.
- Support …
> Media: Legacy support for MediaService implementation.

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/System/FancyAlerts+AztecAnnouncement.swift
This PR adds the new analytics events to the buttons in the new Aztec announcement alert. It also hooks up an analytics call to the 'beta' button in the top of the Aztec editor view controller.
To test:
* Check the analytics calls look right.
* If you like, open `TracksServiceRemote.m` (in WP analytics) and edit `sendBatchOfEvents:` to dump events out with `NSLog`. Check they appear in your log after you tap each button (there may be a few seconds delay before each batch of events are logged).
> Aztec announcement: Add analytics

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/Utility/WPWebViewController.h
- WordPress/Classes/Utility/WPWebViewController.m
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
- WordPress/Classes/ViewRelated/System/FancyAlerts+AztecAnnouncement.swift
This PR hooks up the button in the Aztec footer in App Settings:
It'll display the same web view as the other beta / what's new links for Aztec. I've centralised the code that displays that web view so we're not repeating it everywhere.
I've also updated that code so that the web view displays a "bug" link in the top right of the webview, which will launch Helpshift if available.
To test:
* Check the footer link in App Settings loads the web view
* Check the bug link in the web view works correctly
* Ensure I haven't broken the other web view links
> Aztec: Helpshift and App Settings footer

- WordPressComStatsiOS/WordPressComStatsiOS/Services/WPStatsService.m
- WordPressComStatsiOS/WordPressComStatsiOS/UI/InsightsPostingActivityCollectionViewController.m
- WordPressComStatsiOS/WordPressComStatsiOS/UI/InsightsTableViewController.m
- WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m
- WordPressKit/WordPressKit/WPStatsServiceRemote.m
Fixes #7417 
To test:
1. Run static analyzer.
2. Verify no warnings appear for WordPressKit or WordPressComStatsiOS
3. Run unit tests and verify they pass (technically Buddybuild will do this).
> Fixes several static analyzer warnings in WordPressKit & Stats Framework

- WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
In cases where loading of a post preview encounters an `NSURLErrorCancelled` error the spinner can remain visible.  This PR tweaks the error handing to aways dismiss the spinner first.
Needs review: @koke, would you mind looking at this one?
> Post Preview: Hide spinner before returning after error.

- WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
Avoids premature normalization of text by checking markedTextRange. If that's
non-nil it means we're in "multistage input" and the text displayed is only
temporary.
To test:
- Switch to Chinese (Traditional) keyboard
- Enter tag picker
- Start typing and confirm it doesn't duplicate symbols.
> Fix tag picker with Chinese keyboard.

- WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
Refs #7272 
Shows the site address controller instead of the self-hosted username/password controller when adding a new self-hosted site. Shows the correct nav bar style.
To test: 
Be signed into the app.
From the My Sites controller, tap to add a new self-hosted site. 
Confirm the site address controller is presented (you should be prompted for your URL)
Confirm the navbar has the correct style. 
Confirm you can successfully add the self-hosted site.
Needs review: @elibud would you mind taking a peek at this one?
> Login: Instantiate the correct login controller with the correct navcontroller

- WordPress/Classes/System/WordPressAppDelegate.m
Fixes #3120 
The flicker at launch is due to login being launched twice, once by the app delegate (as expected) and once by the `BlogListViewController` when its `viewWillAppear` method is invoked. From what I can tell `viewWillAppear` is invoked due to how we've composed the split view and tabbarcontroller but I might be missing/misunderstanding something here.  In any event, this PR resolve the issue by adding a check for the new prologue view controller when determining if the login flow is visible. 
To test:
Sign out of the app completely.
Launch the app. 
Watch carefully and confirm there is no flicker.
> Login: Add check for prologue vc.

- WordPress/Classes/ViewRelated/Me/SupportViewController.h
- WordPress/Classes/ViewRelated/Me/SupportViewController.m
- WordPress/Classes/ViewRelated/System/FancyAlerts+AztecAnnouncement.swift
Fixes #7517 
This PR changes Helpshift instances created from the Aztec what's new UI to use the `origin:aztec-feedback` Helpshift tag instead of `origin:in-app-feedback`, so we can more easily differentiate Aztec specific issues.
To test:
* Go into Me > App Settings, enable Aztec (if it's not already) and tap the 'i' button in the footer of the editors section.
* Tap the bug icon in the top right of the what's new webview
* Post a bug to Helpshift, view it in Helpshift and check that it has the correct tag.
> Helpshift: Use `aztec-feedback` source for Aztec issues

- WordPress/Classes/ViewRelated/System/FancyAlerts.storyboard
Fixes #7513 
Fancy alert titles were truncating if they were too long and didn't fit. This PR updates the view structure slightly to allow wrapping to 2 lines. I had to use a slight hack...
The stack view containing the title label and the beta badge was previously using `centered` distribution (first baseline would result in the badge being too low down in comparison to the label). However, when I enabled multiple lines on the label, that meant the badge would be centered against the entire label rather than just the first line. This looked a little weird.
To get around this, I've done the following:
* Removed the title stack view. The title label now sits directly in the main content stack view.
* The beta button now sits in the main content container and uses manual constraints instead …
> Issue/7513: Allow alert title to wrap to 2 lines

- WordPress/Classes/ViewRelated/NUX/Login2FAViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginLinkMailViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginLinkRequestViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginSelfHostedViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginWPComViewController.swift
Refs #7272 
This patch allows a button's title text to wrap rather than show an ellipsis in the event the button's text is too long to show on a single line. 
To test:
For a robust test, change the button titles to something rather long then run the app and ensure the text wraps. 
Needs review: @jleandroperez Could I trouble you for a review since you spotted this issue in an earlier iteration?
> Login: For paranioa, make sure buttons won't show an ellipsis.

- WordPress/Classes/ViewRelated/NUX/Login.storyboard
- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginViewController.swift
- WordPress/Classes/ViewRelated/NUX/NUXAbstractViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninEditingState.swift
Refs #7272
Safari saved passwords are functional again. Properly logs in, and handles errors with grace.
To test:
- login via safari saved passwords
- the same, with an incorrect passwords
- with and without requiring 2fa
> Login: restore ability to use safari saved password

- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
**Fixes** #7534 
**To test:**
Go to reader and visit one article, check that the font is bigger. 
Then you can change the accessibility values and check that that view adjust accordingly (go back and in again into the article).
**SETTINGS**
**BEFORE:**
**AFTER:**
> Update font style and line height on reader

- WordPress/Classes/ViewRelated/NUX/SigninKeyboardResponder.swift
Refs #7272 
To test:
Use the simulator setting for an external keyboard.
Put focus on a text field. 
Ensure the view adjusts for the height of the keyboard bar.
Toggle the soft keyboard.  Ensure the height continues to adjust for the full keyboard size.
Needs review: @elibud could I trouble you with this one? 
cc @nheagy 
Example:
> Login: Adjust height for external keyboard.

- WordPress/Classes/ViewRelated/Blog/SiteManagement/DeleteSiteViewController.swift
- WordPress/Classes/ViewRelated/Blog/SiteManagement/TableViewHeaderDetailView.swift
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableView.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.swift
- WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift
- WordPress/Classes/ViewRelated/Plans/PlanListRow.swift
Fixes #7449 
This fixes a couple instances of using uppercased() without passing in the current locale. Some languages have different rules for what's considered uppercasing based upon the character set. I also eliminated the default string from being in uppercase to simplify translations (prevents a duplicate string).
To test:
1. Build and run.
2. Make sure values are uppercased in each of the view controllers. Testing uppercase logic might be hard so just making sure default behavior isn't changed is good.
> Uppercase strings with the locale to take into account language rules

- WordPress/Classes/ViewRelated/NUX/Login.storyboard
Refs: #7272 
- Fixes readable content margins on the login epilogue screen for the iPad.
- Sets bottom buttons to the sub head font on the two magic link screens
- Corrects the font color and button class/settings on the Login storyboard's version of the SignupViewController.
To test:
Check the screens in the login flow and confirm the changes. 
Screen shots:
> Login: Some layout changes.

- WordPress/Classes/ViewRelated/System/FancyAlerts.storyboard
Fixes #7548
The title now fill the space properly
To test:
- ensure that the fancy alert titles look correct: site address, aztec beta
> Fix heading width in fancy alert when no beta button is shown

- WordPress/Classes/ViewRelated/NUX/WPWalkthroughTextField.m
This morning's change to the secure toggle icon in #7554 accidentally made the button super small. This fixes that while still having the image aligned.
To test:
- ensure the secure password button (the eye) has the right amount of padding to the right edge.
> Fix secure password toggle button to be bigger

- WordPress/Classes/Utility/FeatureFlag.swift
Fixes #7272
Who do we want to see the new login process?
To test:
- build a release build that wouldn't otherwise see the new login process
> Turn on the new login experience for everyone

- WordPress/Classes/ViewRelated/System/FancyAlertViewController.swift
- WordPress/Classes/ViewRelated/System/FancyAlerts.storyboard
Fix #7548
This should fix the issues we were seeing with the title of the fancy alert view. I'm not 100% sure of the reasoning, but I was able to get the wrapping working correctly by selectively deactivating the trailing constraint for the title accessory button – I'm guessing it was causing the button to still take up space despite being hidden.
To test:
* Check the site address alert, and the aztec announcements. If you need to get the aztec announcement to return, the easiest way is to change `aztecAnnouncementWasDisplayed` in `FancyAlertViewController+AztecAnnouncement` to always return `false`.
> Fancy Alerts: Fix title wrap issue

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #7576 
To test:
- Create or open text using Aztec
- Insert link to post
- Check if underline and medium blue styles are applied.
> Make links have underlines and use mediumBlue color.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Refs #7560 
To test:
- Set the simulator to use pseudo RTL language (Edit Scheme option in Xcode)
- On the simulator add a keyboard with an RTL langauage (arabic for example)
- Create a new post using Aztec and see if placeholder are show correctly
One small note regarding the cursor initial position, it looks that inside an UITextView the caret is only positioned on the right if you are using an RTL language so to see the cursor on the correct position the keyboard must be arabic
> Improve RTL of placeholders.

- MIGRATIONS.md
- WordPress/Classes/Models/Blog.h
- WordPress/Classes/Models/Blog.m
- WordPress/Classes/Services/BlogService.m
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListFilterSettings.swift
- WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 62.xcdatamodel/contents
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPressKit/WordPressKit/BlogServiceRemote.h
- WordPressKit/WordPressKit/BlogServiceRemoteREST.m
- WordPressKit/WordPressKit/BlogServiceRemoteXMLRPC.m
- WordPressKit/WordPressKit/RemoteUser.h
- WordPressKit/WordPressKitTests/BlogServiceRemoteRESTTests.m
To check if a blog has multiple authors, we were already fetching a list of
users. Besides counting them, we can match the existing known username to
figure out the user ID, so we can use that for the "Only me" filter.
Previously, this was problematic for Jetpack sites, as the known user ID was a
wordpress.com user ID, which didn't match the site's user ID that the API was
using.
Also, this enables filtering for non-Jetpack/XML-RPC self hosted sites, since
there's no reason not to :)
Fixes #6149 
To test:
Ensure the existing author filter feature also works for Jetpack and non-Jetpack self hosted sites.
Needs review: @elibud @aerych
> Support author filter for Jetpack and self hosted

- Podfile
- Podfile.lock
This PR integrates Aztec 1.beta 8.1 to the Release 8.1 of the main app.
> Update branch to Aztec beta 8.1

- WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.swift
The account service already sets the default account if there's not one already. We don't want to force it.
Fixes #7590
To test:
- Sign in to wp.com account A, confirm it's set as the default in "Me", and all the blogs are synced in "My Sites"
- Add a self hosted site connected to account B
- Go to stats and enter the password for B
- Confirm the "Me" tab still shows the account A, and all the blogs for A are still in "My Sites".
> Don't set default account on Jetpack login

- WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessor.swift
- WordPress/WordPressTest/Aztec/CalypsoProcessorTests.swift
We needed to implement a pre-processor that converts `\n` characters into `<br>` (Ref. #7446).
Problem is: doing so within UL / OL has a bad bad side effect of adding extra bullets to lists.
In this PR we're escaping UL / OL's, and adding a few Unit Tests.
Fixes #7598
1. Run the Unit Tests and verify the world is a happy green place
2. Add a post to your site that looks like:
```
Unordered List
<ul>
<li>First Item</li>
<li>Second Item</li>
<li>Third Item</li>
<li>Fourth Item</li>
</ul>
Ordered List
<ol>
<li>First Item</li>
<li>Second Item</li>
<li>Third Item</li>
<li>Fourth Item</li>
</ol>
```
3. Edit the post in Aztec and verify it doesn't look... odd?
Thanks in advance sir!!
> Aztec: Avoiding \n >> BR conversions within Lists

- WordPress/Classes/ViewRelated/NUX/EpilogueSegue.swift
This patch replaces the custom epilogue animation with a simpler left to right transition that also clears the navigation controller's history. A happy side effect is it resolves the issue @frosty reported in #7583 
@nheagy @mattmiklic and I discussed dropping the custom animation so I'm keen to kill two birds with one PR (as it were) as long as everyone's happy with the transition.
Fixes #7583 
To test: 
- Login to the app.
- Observe that the epilogue controller transitions from left to right like a regular view controller being pushed onto the stack. 
- Confirm there is no visual jump in the view similar to #7583 
Needs review: @nheagy @mattmiklic, what say you gentlemen? 
cc @frosty
> Login: Replace the custom epilogue animation

- WordPress/Classes/Services/BlogService.m
- WordPress/WordPressTest/BlogJetpackTest.m
- WordPress/WordPressTest/Test Data/get-user-blogs_has-blog.json
The previous code was too strict and would only do an exact match on the
XML-RPC endpoint.
This one will use the stored wp.com blog ID when available, and will fall back
to the XML-RPC endpoint, doing a case insensitive match of both HTTP and HTTPS
variants.
This is also closer to the algorithm in the Android app.
Fixes #5911 
To test:
See steps in #5911 and #7339.
> Improve algorithm to migrate Jetpack sites

- WordPress/Classes/ViewRelated/NUX/LoginSelfHostedViewController.swift
This PR restores a behavior that was accidentally clobbered while implementing the new login flow (mea culpa).  When adding a new self-hosted blog to the app, that blog should (once again) become the selected blog under the My Sites tab. 
To test:
- Confirm the bug in the release/8.1 branch by adding a new self-hosted site while logged into wpcom. When the epilogue dismisses you most likely will not be looking at the blog you just entered unless it is the first one in the list.
- Switch to this branch.
- Be logged into wpcom. 
- Add a self-hosted site to the app. 
- When the login epilogue dismisses, confirm you are view the detail screen for the newly added blog.
Needs review:
> Login: Restore updating selected blog when adding new blog to app.

- WordPress/Classes/Extensions/WPStyleGuide+Aztec.swift
Fixes https://github.com/wordpress-mobile/AztecEditor-iOS/issues/663
This PR fixes the above issue by darkening the color used for the active highlight in the format bar.
To test:
* Open Aztec
* Use the buttons on the format bar
* Check the highlight of the button matches the new color
> Aztec: Darkens format bar active color

- WordPress/Classes/Extensions/UICollectionViewCell+Tint.swift
- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #7639 
Well, that was a funky bug. I'm still not sure of what was happening under the hood, but a recent change to our `-[WordPressAppDelegate customizeAppearance]` method caused the buttons in instances of `WPWebViewController` to lose their tint color. This meant that people couldn't work out how to exit web views.
It seems like it was something to do with using `tintColor` with `UIAppearance`, even though it's not a `UI_APPEARANCE_SELECTOR` property. To get around this, I added a custom method to `UICollectionViewCell` which _can_ be used with `UIAppearance`.
**To test:**
* Build and run, and log in
* Open blog details for a site, scroll down and select View Site.
* In the web view, you should see the X and share buttons in the navigation bar.
* Close the web view
* Open Aztec, …
> Issue/7639: Restore web view navigation bar buttons

- WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift
- WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
Hopefully this PR goes some way to fix #7279. There are two key changes:
1. The delegate of `PostPreviewGenerator` is now `weak`. Previously, this was causing a retain cycle, resulting in `PostPreviewViewController`s and generators staying in memory.
2. PostPreviewViewController is now dismissed in the event of a memory warning. There doesn't seem to be much we can do in this situation, and you'd hope it wouldn't occur that often. But in an attempt to prevent the app crashing, let's just dismiss instead.
To test:
* Build and run the app.
* From the Posts list, open and close post previews multiple times.
* With the post preview closed, open the Debug Memory Graph. You shouldn't see any instances of `PostPreviewViewController` or `PostPreviewGenerator` in memory.
* Also, in the simulator, …
> Post Preview: Fix retain cycle and dismiss on memory warning

- WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift
This PR cherry-picks the retain cycle fix for post preview from #7646. See the original PR for testing details.
> 8.2: Cherry-pick PostPreviewGenerator retain cycle fix

- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
This PR restores bumping the `createAccountInititated` stat which was previously being bumped in the old `SignupEmailViewController`, but was overlooked in the new login flow.
To test:
- Set a break point where the stat is bumped. 
- Launch the app, log out completely if needed, and tap the option to create an account. 
- Confirm the stat is bumped.
Needs review: @
> Signup: Restores bumping the create-account-initiated stat.

- WordPress/Classes/ViewRelated/Me/MeViewController.swift
This PR fixes an issue that prevented a user signed in with only a self-hosted blog from accessing the account creation option.  This is a stop-gap that will be reevaluated as part of the Auth project focus.
To test:
- Start from a logged out state and add a self-hosted site to the app.
- On the Me tab, tap to login. 
- In the action sheet that appears, confirm that both options properly function and you are taken to either the Login email vc, or the sign up vc as appropriate. 
- Confirm that the actionsheet is correctly displayed as a popover on the iPad. 
Needs review: @jleandroperez could I trouble you with this one?
> Login: Implements a stop-gap fix for account creation access.

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR integrates Aztec Bleeding Edge Release into WPiOS 8.2.
Run a smoke test on the Aztec Editor. We're temporarily disabling the HTML prettifier (to be addressed in WPiOS 8.3).
> Aztec 1.0.0 Beta Mark 9.2

- WordPress/Classes/Utility/WPContentSyncHelper.swift
- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes #3002 
To test:
1. Follow https://cupofjo.com
2. On the followed sites list, select A Cup of Jo
3. Navigate to the post list
4. Tap on the comments button for one of the posts
5. Verify that a message explaning that the comments could not be fetched is displayed
(this site has some JP configuration issues right now and that is why we can not fetch the comments)
> Reader Comments: Display error when they fail to load

- Podfile
- Podfile.lock
- WordPress/Classes/Extensions/String+Ranges.swift
- WordPress/Classes/Extensions/String+RegEx.swift
- WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorIn.swift
- WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorOut.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/Aztec/CalypsoProcessorInTests.swift
Fixes #7671 by migrating `autop` and `removep` to Swift, and processing the post content with it.
- Adds support methods to make the migration more straightforward.
- Migrates `autop` and `removep` to Swift.
- The reference code can be found [here](https://github.com/WordPress/WordPress/blob/4e4df0e/wp-admin/js/editor.js#L309) and [here](https://github.com/WordPress/WordPress/blob/4e4df0e/wp-admin/js/editor.js#L172).
We've left comments for each line of code we migrated.  Make sure all lines have been properly migrated.
These comments will be removed once the PR is approved, but were left in there to make the review process easier.
**Test 1:**
Run the unit tests.  Make sure they all pass.
**Test 2:**
Create a post in Calypso with some content in more than 1 paragraph.  You can also use …
> Implement wpautop and wpremovep in Swift.

- Podfile
- Podfile.lock
Fixes #7679 
To test:
Test that the swipe actions: Mark as Read, Unapprove/Approve and Trash work correctly on notifications. Please test on IPhone and IPad, both orientations.
> Updates MGSwipeTableCell pod to the latest version

- WordPressKit/WordPressKit/ReaderSiteServiceRemote.m
- WordPressKit/WordPressKitTests/ReaderSiteServiceRemoteTests.swift
**Fixes:** #6924 
**To test:**
Follow a site and verify that the source is correctly recorded via `read/following/mine/new` and `sites/SITE_ID/follows/new`
Also please verify that unfollowing works because I made a simple change there too.
> Add source param when following sites

- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
**Fixes** #7686 
As part of https://github.com/wordpress-mobile/WordPress-iOS/pull/7672 I missed updating `ReaderCommentsViewController` to add the extra parameter and that's causing comments to hang on 8.3
**To test:**
1. Verify that you can replicate the hanging on release/8.3
2. Check out this branch and verify that comments load properly on reader
> Add missing param to sync methods for ReaderCommentsViewController

- WordPress/Classes/ViewRelated/NUX/LoginProloguePageViewController.swift
Fixes #7556 
To test: 
- View the login prologue screen. 
- Tap the page control.
- Confirm forward and reverse navigation depending on which side of the control is tapped.
Needs review: @astralbodies would you mind?
> Login: Make the prologue page control tappable.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #7698
2. Press the List (OR) H button
3. Press the Bold button
As a result, the *regular* soft keyboard should show up onscreen. Please: test this one on iPad + iPhone.
> AztecPostViewController: Fixing Options Dismissal

- Podfile
- Podfile.lock
Updates the editor pod to the latest version: `1.9.4`
**To Test:** Build and run the app. Using the visual (hybrid) editor, verify everything is working as expected.
Needs review: @elibud Thanks!!
> Update the editor pod to 1.9.4

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
I've (unsuccessfully) tried to reproduce the original crash in WPiOS 8.0 / 8.1 / 8.2 / 8.3 with the following steps:
1. Upload multiple assets
2. Ensure the mediaProgressView is onscreen
3. Send the app to BG
4. Stop Xcode
5. Relaunch WPiOS (trigger State Restoration)
If you set a BP in step (4), in AztecPostViewController's *updateViewConstraints* method, you'll get a trace that looks very similar to the one in the crashlog (Except, right, for the exception).
In this (super minor) PR, we're just adding a failsafe that would effectively prevent the exception condition.
Fixes #7607
Perform the steps detailed in the issue's description and ensure nothing breaks!
> AztecPostViewController: Crash Failsafe

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
In this PR we're adding a cast failsafe. I've been unable to directly trigger the initial crash. Suspicion is: the *error* is set to nil, which triggers a downcast crash.
Fixes #7606
Please run a smoke test, and make sure nothing (too obvious!) breaks!!
> AztecPostViewController: Cast failsafe

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Aztec/Extensions/VideoAttachment+WordPress.swift
- WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorIn.swift
- WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorOut.swift
- WordPress/Classes/ViewRelated/Aztec/Processors/VideoShortcodeProcessor.swift
- WordPress/Classes/ViewRelated/Aztec/Processors/WordPressProcessors.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/Aztec/CalypsoProcessorInTests.swift
- WordPress/WordPressTest/Aztec/VideoProcessorTests.swift
This PR:
- Integrates Aztec changes from https://github.com/wordpress-mobile/AztecEditor-iOS/pull/705.
- Adds a processor for `[caption]` shortcodes moving [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/7715) forward.  Still needs improvements in format coloring and alignment.
- Removes some old comments from the code.
- Fixes an issue that was converting certain `[wpvideo]` captions without a URL into `[video]` captions.
Test that shortcodes still work fine.
Try with `[video]`, `[wpvideo]` and `[caption]`.
To avoid de-synchornization issues between Aztec's `develop` branch and WPiOS's `develop` branch, this will be merged simultaneously with the PR mentioned above.
> Integrates Processor changes in Aztec.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Minor cleanup PR: moving Strings to constants!
1. Edit a new Post, and type something, so that it's not empty
2. Press the top left `x` button
3. Verify that `Save`/ `Updated` / `Discard` / `Keep Editing`  work as expected
> AztecPostViewController: Unsaved Changes Cleanup

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
In this minor PR we're doing a small cleanup of the LinkEdition Alert(s).
**Note:** This PR should be reviewed after #7725 is merged!
2. Verify that Inserting / Updating / Removing a link works as expected
3. Verify that New Links are pre-populated with the Pasteboard's Contents
1. Copy some (random) text.
2. Press the Link button. 
3. Verify that the text copied in (1) shows up pre-populated
> AztecPostViewController: Link Alert Cleanup

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecAttachmentViewController.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
In this PR we're fixing a regression we had in the Undo Mechanism, that affected, precisely, Image edits.
Fixes #7729
1. Open a post for editing.
2. Insert an image.
3. Tap the image, tap again for options, select "Details."
4. Make changes to the web display settings for the image and tap "Done."
5. Shake the device to see undo options and revert the last change
As a result, the Image Edits should be undone.
> Aztec: Fixing Undo for Image Updates

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
- WordPress/Classes/ViewRelated/System/FancyAlerts+AztecAnnouncement.swift
Fixes #7734
1. Perform a fresh install
2. Log into your dotcom account
3. Verify that the Aztec popup looks as expected
4. Switch to App Settings. Verify that the Aztec option looks as expected
5. Launch Aztec. Verify that the `Beta` button now reads `Feedback`.
> Removing Aztec Beta References

- WordPress/Classes/Utility/FeatureFlag.swift
This PR opens up the new media picker for all internal testers.
We'll merge after https://github.com/wordpress-mobile/WordPress-iOS/pull/7727 is merged.
> New media picker: open up feature flag for internal testers

- Podfile
- Podfile.lock
Integratez Aztec v1.0.0-beta.11.
Test as much as you need to make sure the integration didn't break anything.
Key features for testing:
- Undo support (particularly in images)
- Style editing
/cc @elibud - Can we wait to branch 8.4 until this is in?
> Updates Aztec to 1.0.0-beta.11

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
Fixes #7441
1. Launch WPiOS and enable Aztec
2. Edit a **Draft**
3. Verify that pressing the **Update** button won't dismiss the editor.
> AztecPostViewController: No longer dismissing upon draft update

- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
Fixes #7743
To test:
1. Login with just a self-hosted site (be logged out of WordPress.com entirely)
2. On the Me tab tap "Log In" then "Create a WordPress site"
3. Signup screen should appear (without any crashes 😜)
> Fix crash during signup

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #6974
2. Type `Helo` in the title field
Verify that the (incorrectly spelt) word gets underlined in red.
Thanks!
> AztecPostViewController: Enabling spell check on the title field

- WordPress/Classes/ViewRelated/Aztec/Extensions/Header+WordPress.swift
- WordPress/Classes/ViewRelated/Aztec/Extensions/TextList+WordPress.swift
- WordPress/Classes/ViewRelated/Aztec/Options/OptionsTableView.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
In this PR we're adding accesibility identifiers over the Heading + List options.
Closes #7005
1. Enable voice over in your device
2. Launch Aztec
3. Press the `Heading` button
4. Verify that all of the options have their accesibility details set
5. Press the `List` button
6. Verify that all of the options have their accesibility details set
> Aztec: Accesibility Identifiers

- WordPress/Classes/ViewRelated/Tools/HelpshiftPresenter.swift
**Fixes** #7770 
It looks like at some point we missed an update on the API and ticket deflection has not been working for a while. This fix brings it back.
**To test:**
Me -> Help & Support -> Contact Us
Type something that would have a suggested answer, like "Delete post"
Send
You should be presented with suggested FAQ articles.
I'm targeting 8.4 since it's an extremely simple fix and it may help with ticket volume.
> Update Helpshift settings for showSearchOnNewConversation

- WordPress/Classes/Services/WordPressXMLRPCAPIFacade.h
- WordPress/Classes/Services/WordPressXMLRPCAPIFacade.m
Fixes #7779 
To test:
- Add a self-hosted site with the following url: [REDACTED]
- Insert any user and password combination
- Check that app doesn't crash.
> Check if response to request is a proper dictionary before returning.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #7756
This PR updates the inline picker height logic that was introduced as part of #7723. A couple of changes were made:
1. The `currentKeyboardFrame`'s  coord system is converted from the window's thus providing more accurate values.
2. A computed var (`isExternalKeyboardConnected`) was added to determine if an external keyboard is currently connected.
3. The inline picker's height calculation now varies depending on if the external keyboard is present or not.
To test:
On the Sim and/or device, build and run the app.  Try a few of the following scenarios:
* (iPad with an external keyboard) Edit a post and bring up the inline picker — make sure the picker's height is appropriate. Try again, but disconnect the keyboard while the picker is visible.
* (iPad with soft keyboard) Edit a …
> New Media Picker: Updated the media picker keyboard sizing logic

- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.xib
**Fixes** #7451
Changed the `titleLabel` frame so it doesn't have margins to the top and bottom of the superview, since those were causing the label to be cut off.
**To test:**
In order for the problem to happen the Accessibility->Larger Text settings should look as follows:
1. First check that you can see the issue in develop
2. Check out this branch and check that is not a problem
3. Test with other text sizes and make sure it's ok
> Update notifications label frame

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
**Fixes** #7741 
**To test:**
Go to a notification before or after an unread one. 
Navigate with the arrows to the unread note. 
Go back to the list, check that the notification is marked as read.
> Mark note as read when navigating with arrows

- WordPress/Classes/ViewRelated/Post/PostPostViewController.swift
Fixes #6436
To test:
- Publish a post
- The post-post screen appears with animated buttons
- tap edit, then close the editor
- The buttons should _not_ animate
> Stop Post-post button reanimation

- WordPress/Classes/Services/BlogJetpackSettingsService.swift
- WordPress/Classes/ViewRelated/Blog/JetpackSecuritySettingsViewController.swift
- WordPressKit/WordPressKit/BlogJetpackSettingsServiceRemote.swift
- WordPressKit/WordPressKit/RemoteBlogJetpackSettings.swift
**Fixes** #7783 
**To test:**
Same as https://github.com/wordpress-mobile/WordPress-iOS/pull/7724 please check that all these work:
> Stop updating Jetpack settings one by one

- WordPress/Classes/Models/Blog.h
- WordPress/Classes/Models/Blog.m
- WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
- WordPress/Classes/ViewRelated/People/PersonViewController.swift
We were storing the order, but then fetching the blog's roles unordered. This
adds a `sortedRoles` accessor so they appear in the right order.
Also moved the Follower role to the end of the list when inviting a user.
Fixes #7682 
To test:
Ensure correct order of roles when editing a user and inviting a new user.
> Respect order of roles

- WordPress/Classes/Utility/WPWebViewController.m
**Fixes** #6020 
The simplest fix, lets only share the URL when sharing from the `WPWebViewController` 
**To test:**
Go to a Reader Stream and click on Visit. Then tap on the share Icon, copy, and paste it somewhere. Verify that the title is not included. 
> Only share URL on WPWebViewController sharing

- .hound.yml
This PR will stop Hound from considering our ruby scripts.
This is hard to test (you'd have to push a fork of this branch with a change to a ruby script). Instead, perhaps just consider [the documentation](https://houndci.com/configuration#ruby)
Thanks again, Jorge!
> Stop Hound for considering ruby files

- Scripts/fastlane/download_metadata.swift
- WordPress/Classes/Utility/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
We are disabling Jetpack themes until we fix https://github.com/wordpress-mobile/WordPress-iOS/issues/7758 and finish https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/webviewcontroller-refactor
**To test:**
Check that theme browsing is still enabled on development builds but not on prod builds for Jetpack sites. Check that .com sites always have access to themes.
> Disable Jetpack themes on AppStore builds

- WordPress/Classes/ViewRelated/NUX/Login.storyboard
Fixes #7815 
This PR fixes the gap at the top of the login prologue screen on iPhone X. To do this, we now pin the top of the container view in the Login Prologue View Controller to the top of its superview, instead of to the top layout guide.
To test:
* Ensure the login prologue view controller displays correctly on both the iPhone X and other models of iPhone / iPad.
> Login prologue: Fixes top constraint for iPhone X

- WordPress/Classes/Services/BlogJetpackSettingsService.swift
- WordPress/Classes/Utility/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Blog/JetpackConnectionViewController.swift
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPressKit/WordPressKit/BlogJetpackSettingsServiceRemote.swift
**Fixes** #7473
This is a development only implementation for Jetpack disconnect. The feature as will be rolled out to users will have very a different UI, with strong confirmation dialogs, in line with Calypso.
I'm implementing this now so we can test the remote call and also have an easy way to disconnect while we work on the rest of the Jetpack experience.
Please note that this is feature flagged and will only be available for development builds.
**To test:**
1. Select a Jetpack site
2. Settings
3. Manage Connection
4. Disconnect from WordPress.com
5. Verify on the web that Jetpack was disconnected
cc: @mattmiklic
> Jetpack disconnect - development only implementation

- WordPress/Classes/Services/LoginFacade.m
- WordPress/Classes/ViewRelated/NUX/LoginSiteAddressViewController.swift
While doing a bit of analytics research I noticed stats for xmlrpc discovery failures had plummeted. I suspect this is less due to the success of the new login flow and more to where the stat was being bumped.  This PR adds adds tracking for discovery failures to the site address vc as well as bumping regular failures via the "guess" failure callback in LoginFacade for consistency. 
Needs review: @nheagy could you take a quick peek?
> Login: Improve xmlrpc discovery failure tracking.

- WordPress/Classes/Utility/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR removes the feature flag for the new inline media picker.
To test:
* Check the code
* Build and run the app, check that the inline media picker is present in Aztec
> Media: Remove new inline media picker feature flag

- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
Fixes #7817.
The Reader stream on iPhone X shows white insets on the left and right when in landscape. I fixed this by simply applying the same background colour as the content view to the cell itself.
To test:
* Ensure the reader stream background looks correct on the iPhone X and other devices (including iPad).
> Issue/7817: Reader insets on iPhone X

- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes #7845. See original issue for screenshot.
On iOS 11, we were seeing large grey headers and footers in the reader comments section. This screen uses `WPTableViewHandler`, and it seems that the default header / footer height of `UITableViewAutomaticDimension` was producing ~30pt tall headers and footers. I've overridden this in the comments view controller itself to keep them at 0 height.
To test:
* View the comments for a post in the Reader, and ensure that the headers and footers no longer show.
> ReaderComments: Override default header and footer height

- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockUserTableViewCell.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockUserTableViewCell.xib
Fixes #7844 
In iOS 11, the Follow button in notifications can become misplaced when hidden. I couldn't work out exactly why it was being misplaced, as it seems to not be in the view hierarchy at this point. To fix it, we now explicitly remove the button from the view hierarchy entirely, and re-add it if necessary.
To test:
* See original issue for testing steps. Ensure the follow button isn't visible when it shouldn't be there.
> Issue/7844 Fix misplaced follow button

- WordPress/Classes/ViewRelated/Tools/SettingsTextViewController.m
Fixes #7846 
In iOS 11, table cells default to being auto sizing. This was resulting in the text cell in `SettingsTextViewController` collapsing to fit its content exactly. We'd prefer the cell to be the default cell height (44pt), so we'll disable auto sizing for it.
To test:
* Navigate to Me > My Profile > First Name, and ensure the cell is the correct height.
> Issue/7846: SettingsTextViewController cell height

- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
Fixes #7816. See the original issue for details of the problems we were having with the New Post button in iOS 11.
I've updated the logic so that we now show a different style in a couple of different situations, where the tab bar shows button icons and labels side-by-side instead of vertically stacked:
* Landscape on iPhone
* Portrait on iPad when the app is fullscreen
* Landscape on iPad if the app fills greater than 50% of the screen
It feels a bit of a hack detecting these specific cases, but I can't see any other way to determine how the bar is currently displaying. Here's how things look now:
To test:
* On each type of device, test the tab bar in both orientations, and in different multitasking splits:
cc @mattmiklic does this look ok to you?
> Issue/7816 Update New Post tab bar button for iOS 11

- WordPress/Classes/ViewRelated/Blog/JetpackConnectionViewController.swift
- WordPress/Classes/ViewRelated/Blog/JetpackSecuritySettingsViewController.swift
- WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
- WordPressShared/WordPressShared/Core/Views/WPStyleGuide.m
**Fixes** #7851 
And it also updates the AztecEditor footer to remove the info icon as agreed with @mattmiklic and to use WordPress blue in the link text.
**To test:**
Go to Jetpack Settings and check that the Learn More text is the correct color and that taping navigatest to the WebViewController.
Repeat for the Aztec editor feedback link on app settings.
> Consistently use WordPress blue for links on table footers

- Podfile.lock
- WordPress/Credentials/gencredentials.rb
Fixes #7675 
Update the podfile.lock to reflect the new google libs pods being used for login.
To test:
- Make sure the app compiles correctly.
FYI: @nheagy
> Update podfile.lock for google new libs.

- WordPress/Classes/Services/CommentService.m
- WordPressKit/WordPressKit/ReaderPostServiceRemote.m
- WordPressShared/WordPressShared/Core/Utility/RichContentFormatter.swift
In this PR we're swapping `UIApplication.shared.keyWindow` usage for `UIScreen.main`:
- We're **not** updating the threading scheme.
- Instead, we're switching over an API that doesn't piss off the Main Thread Sanitizer.
- We'll iterate... if the console warning gets back!
Closes #7861
1. Launch the app in Xcode 9
2. Open the Reader and sync
3. Verify that no warning shows up in the console
> RichContentFormatter: Sanitizer Fix

- WordPress/Classes/Services/AccountService.m
- WordPress/Classes/Services/NotificationSettingsService.swift
- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/Utility/InteractiveNotificationsManager.swift
- WordPress/Classes/Utility/PushNotificationsManager.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingStreamsViewController.swift
- WordPress/Classes/ViewRelated/Tools/HelpshiftPresenter.swift
In this PR we're doing a bit of pending cleanup:
- Swift enums should go in lowercase
- Replaced fileprivate methods with private extensions
- Renamed **sharedInstance** > **shared** properties
Ref #6755
**No logic** was modified in this PR. In order to test this one, please, verify that the unit tests run correctly.
> InteractiveNotificationsManager: Swift Cleanup

- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
- WordPress/Classes/ViewRelated/Views/VerticallyStackedButton.m
In this PR we're:
- Updating VerticallyStackedButton so that the titleLabel never overflows the container frame.
- Enforcing a fixed size for the Notification Comment's Actions.
I'm opting towards a fixed point size, since that's exactly what happens with the TabBar: each action has an icon, so it really does not make any sense to break the UI. Each action is recognizable always.
Fixes #7696 
1. Enable Dynamic Typing a select a bigger font
3. Open a Comment-Y Notification
4. Verify that Approving / Disapproving a comment doesn't cause the text to move
5. Verify that the font size remains fixed.
Elisa, may i bug you with this one?
> Comment Actions: Fixed Font Size

- WordPress/Classes/Utility/PushAuthenticationManager.swift
- WordPress/Classes/Utility/PushNotificationsManager.swift
- WordPress/WordPressTest/PushAuthenticationManagerTests.swift
As part of a Notifications refactor (merging a couple helpers!), we're updating few things around. Starting off with PushAuthenticationManager:
- Switched **if** statements over to guard
- Corrected method visibility
- Nuked NSObject inheritance
- Minor touches here and there
Ref #6755
No logic has been updated in this PR (other than if getting replaced by guard). In order to test, please, verify that the unit tests don't break.
Sir, may i bug you with yet another review?
Thanks!!
> PushAuthentication: Swift Update(s)

- WordPress/WordPress.xcodeproj/project.pbxproj
I've noticed the **WordPressShareExtension** folder turns red in the project's tree. 
When we implemented the Share Extension, it was initially called `WordPressShare`. Apparently we've got a leftover from that rename.
In this PR we're fixing the Share Extension's path, so that the project is happy again.
1. Build the project and verify nothing breaks
2. Make sure the unit tests pass
> Fixing Share Extension Path

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
As discussed [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/7765#discussion_r136657517), `unowned self` is no longer required in lazy properties.
In this PR we're just performing a minor cleanup.
Ref #7765
Please verify that the unit tests pass.
> AztecPostViewController: Removes unowned modifier

- WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift
While testing the app on Xcode 9 I noticed that we a crashes when trying to register the 3D Touch services. 
This PR changes the code to make sure the notifications that trigger the registration of 3DTouch are executed the main thread to avoid crashes.
To test:
- Launch the app for the first time on a device with 3DTouch
- Check that no crash happens when trying to register the 3DTouch events.
Needs review: @elibud  should I cherry pick this to the 8.5 release too?
> Make sure that handling of notification is done on the main thread.

- WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Alpha.xcscheme
- WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme
- WordPress/WordPressTest/PushNotificationsManagerTests.m
This PR stops the execution of Helpshift while running tests circumventing the background crash cause by Helpshift accessing an UIApplication property while on a background thread.
To test:
- Run the Unit tests
- Make sure all tests pass and no crash happens.
> Comment UnitTest that enable Helpshift while running tests.

- WordPress/Classes/Services/AccountService+SocialService.swift
- WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
**Fixes** #7803 
**To test:**
1. Activate a theme on develop and check that you see a warning on the console when the event is sent to Tracks.
2. Check out this branch and check that the warning is gone.
> Track event failing for theme activation

- WordPress/Classes/Utility/PushNotificationsManager.swift
- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
Fixes #7873.
A couple of folks who are new to the project and don't have the Helpshift API key in their credential files have seen a crash when the app attempts to register a device token with Helpshift. Not sure if this is a regression, but this PR puts a quick check in place before making the call to `registerDeviceToken`.
To test:
* Ensure the device token is registered correctly when it should be, and the app doesn't crash when there's no Helpshift key present.
Needs review: @astralbodies it looks like you touched this most recently – would you mind?
> Push Notification Manager: registration crash

- WordPress/Classes/ViewRelated/Aztec/Renderers/SpecialTagAttachmentRenderer.swift
- WordPress/Classes/ViewRelated/Aztec/Renderers/WordPressAttachmentRenderer.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- circle.yml
In this PR we're:
- Disabling smartDashes: iOS 11 UITextView feature that converts `--` into a single, longer dash, and miserably breaks our HTML editor.
- Renamed MoreAttachmentRenderer > WordPressAttachmentRenderer
- Added support to render the `nextpage` comment, the same way we render the `more` comment
[Related Aztec PR Here!](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/743)
Fixes #7894
1. Launch the empty editor
2. Verify that inserting the `more` attachment works as expected
3. Switch to HTML mode
4. Type ``
5. Switch to visual mode and verify everything looks as expected
> Aztec: Nextpage support

- WordPress/Classes/Services/PostService.h
- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListFilterSettings.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
As mentioned in #7905, there was a remaining warning in `PostListFilterSettings`.
Objective-C was exporting `PostServiceType` as `NSString`, but the specific values were correctly bridged as `String`.
Adding `NS_TYPED_ENUM` makes it a normal Swift enum, and solves all the bridging issues.
cc: @elibud 
> Make PostServiceType a proper enum in Swift

- WordPress/Classes/ViewRelated/NUX/LoginViewController.swift
Props @nheagy for noticing the glitch.  The problem was the Help button was no longer responding to taps.   Some debugging showed that its parent view had 0,0 geometry so taps weren't being registered. If `clipToBounds` was set on the `customView` then the button would simply vanish.
Not too sure what could have changed, something in a private API or the internals of how UIButtonBarItems are laid out.   In any event, this PR fixes the problem by setting constraints to pin the sides of the button to the customView so it has proper geometry.
To test: 
- Launch the app.  
- Enter the Login flow and confirm you can tap on the help button. 
- Confirm the Help button's layout is correct.
cc @elibud
> Login: Fixes an issue making the help button untappable.

- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
Make sure that an existing Google sign-in is disconnected so the user is always prompted to enter their Google credentials vs silently logging in with an already authenticated Google account.
Refs #7675 
To test:
Login via Google.
Log out of the app and then log back in via Google. 
Confirm that you are prompted for your Google credentials rather than silently authenticated to Google via an already signed in account. 
> Login: Disconnect from Google so the user is always prompted.

- WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorIn.swift
- WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorOut.swift
Fixes #7920 
Makes sure newlines are not added or removed from WP posts, other than by the user editing the post.
**Test 1:**
1. Open any existing post.
2. Switch to HTML mode and back.
3. Make sure newlines stay consistent.
**Test 2:**
2. Make some changes.  Add many empty lines.
3. Save it.
4. Open it again and make sure newlines stay consistent.
> Stops removing empty paragraphs.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR prevents an undesired vertical scrolling glitch, when switching to a custom Input View (ie. Header Level picker).
Fixes #7923 
cc @diegoreymendez 
2. Type enough text to cause vertical scrolling
3. Place the cursor at the bottom of the document
4. Press `H` / `List`'s format bar buttons
Verify that the vertical offset doesn't flicker at all.
> AztecPostViewController: Preventing vertical offset glitch

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This is a backport of #7925 for WPiOS Mark 8.5.1.
Fixes #7923 
cc @diegoreymendez @elibud 
2. Type enough text to cause vertical scrolling
3. Place the cursor at the bottom of the document
4. Press `H` / `List`'s format bar buttons
Verify that the vertical offset doesn't flicker at all.
> Aztec: Vertical Offset Glitch

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #7935 
To test:
- Check ticket description above for steps how to reproduce.
> Fix Media picker dismiss when no permission is available.

- WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorIn.swift
- WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorOut.swift
Reverts wordpress-mobile/WordPress-iOS#7928 since it introduced other problems we need to resolve.
I'm removing the milestones from these PRs in order to avoid any confusion as to anything having changed (nothing was changed and they cancel out).
> Revert "Stops removing empty paragraphs."

- Podfile
- Podfile.lock
Things to test:
- Our iOS 11 fixes (make sure the toolbar highlights appropriately and styles aren't lost).
- Make sure the layout looks right in both iPhone and iPad.
Known issues:
Moving the caret with the keyboard arrows to the last position in the document doesn't properly maintain the typing attributes.  This is [known](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/760).
> Integrates the latest from Aztec 1.0.0 Beta 12 into WP.

- Podfile
- Podfile.lock
Updates Aztec to v1.0.0-beta.12.
The changes were already tested in https://github.com/wordpress-mobile/WordPress-iOS/pull/7946.  This PR only versions those changes.
Make sure `pod install` works fine.  Make sure the unit tests work fine.
> Updates to Aztec v1.0.0-beta.12.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
Fixes #7878 
This PR fixes the issues with long names of blogs by setting the `ContentHuggingPriority` on components of the navigation bar on iOS11. This keeps the structure and layout of the navigation bar the same has before and avoid the use of the title view.
To test:  
- Open the editor on a blog with a long name
- Check that the navigation bar shows correctly and the blog name it's cropped correctly if needed.
- Test on different devices (iPhone SE, iPhone 8+, iPad) and multitasking modes.
- Test on iOS10 and iOS11
Thanks to @frosty for the nudge to the right direction.
> Issue/7878 fix editor bars with long titles 8.5.2

- WordPress/Classes/Utility/InteractiveNotificationsManager.swift
- WordPress/Classes/Utility/PushNotificationsManager.swift
In this PR we're neutralizing the **Push Notifications** guard we've got, preventing the registration from taking place, when running on the sim.
1. Preform a fresh install on the Simulator. Verify it doesn't crash miserably.
2. Verify that the unit tests pass correctly.
> Neutralizing Simulator Check

- WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Fixes #7940 
The same as #7847, we were seeing large grey section headers and footers in the CommentsViewController. It seems as though iOS 11 handles automatic headers and footers differently from iOS 10. To fix it, we're simply explicitly setting the header and footer heights to zero, instead of the `UITableViewAutomaticDimension` that `WPTableViewHandler` uses.
To test:
* Open Site Details > Comments, and ensure there are no headers and footers.
Needs review: @jleandroperez would you mind?
> Issue/7940: Set explicit header / footer heights in CommentsViewController

- WordPressKit/WordPressKit/WPStatsServiceRemote.m
- WordPressKit/WordPressKitTests/WPStatsServiceRemoteTests.m
Sets the max parameter to 3000 like calypso
Fixes #7976 
To test:
Find a blog with over 1,000 posts in the past year, and ensure you can reproduce the bug in #7976.
Make sure the bug is fixed in this branch.
> Ensure all posting activity loads

- WordPressKit/WordPressKit/WordPressComRestApi.swift
Fixes #7982 
This PR allows the use of background upload sessions for media uploads.
At the moment by default all request done on the WP.com Rest API are using a normal session. This PR allows the configuration of the API object to use background uploads.
To test:
- Check if the code works correctly for the current upload in the app.
- If needed switch the default to use background uploads and see if code works correctly with the new configuration.
Note: By default I didn't activate background uploads for all uploads because this is not what we want at the moment and can have implications the way the app reacts when no network is available.
When we have async fully implemented we can make background uploads the default value.
> Backround session api

- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Fixes #7922 
On iOS 11, a section of the top row of media items in the collection view was cut off, due to the iOS 11 search bar being taller than the (previously hardcoded) 44pt.
This PR fixes that by using the search bar's intrinsic content size, and also respects the safe area insets on iPhone X.
To test:
* Open the media library on iOS 10 and 11 and check the top of the scroll area looks correct.
* Check that the search bar displays correctly in both portrait and landscape on iPhone X (and isn't broken on other devices).
* Check that the search bar shows / hides correctly if you go from an empty media library to one that contains media items (and vice versa)
> MediaLibrary: Fix search bar size / content inset on iOS 11

- WordPress/Classes/Models/Media.h
- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
Hopefully fixes #7991.
I can't see anything else obvious that could cause the original crash, except that we use the media's `creationDate` when populating the metadata rows. `creationDate` is optional in the `Media` model, but the property in the `Media` class wasn't nullable.
To test:
* Ensure you can view the Media Item View Controller correctly (Site > Media > choose an item).
* Check that the Uploaded field still shows a date.
> Media: Make creationDate nullable to match optional type in model

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Since we were providing an actual URL for the **ImageAttachment**, an entire chain of requests were being triggered, that resulted in AFNetworking being queried for the `placeholder://` URL.
This had the side effect of: placeholder image getting displayed, during the whole `Upload Media` OP.
We've patched [Aztec Here](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/772) so that **nil** URL's are allowed (and thus, we can safely neutralize the `placeholder://` workaround, which effectively fixes issue #7973.
I'm submitting this PR right away so everything is in place, we'll be updating the Aztec dependency ASAP.
Fixes #7973
2. Add some new media
3. Verify that the actual asset immediately replaces the placeholder, while the Upload OP is going on
4. Verify that …
> Aztec: Drag + Drop Placeholder Fix

- WordPress/Classes/ViewRelated/NUX/LoginViewController.swift
Refs #7675 
Adding a comment to clarify why we're not informing a user of a failure connecting a social account.
cc @theck13
> Login: Clarifies why error is not handled.

- WordPressKit/WordPressKit/WPStatsServiceRemote.m
**Fixes** #7994 
**To test:**
We can't really test it unless we manipulate the incoming data, but is a pretty straight forward fix and the crash pointed exactly to it.
> Fixes a crash on WPStatsServiceRemote

- Podfile
- Podfile.lock
This PR updates the WordPress-Editor pod to version 1.9.7.
This updates addresses the following issues:
- Problems with the icons on the format toolbar being resized or going missing.
- Substitution of quotes and dashes for special quotes and special dashes. Ticket here: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/904
- It also prepare the editors for the iPhoneX
To test:
- Activate the hybrid editor
- Check if format toolbar works in the different orientations, devices, and iOS (10 and 11)
- Test the same using the old legacy editor.
> Update hybrid editor to 1.9.7

- WordPress/Classes/Services/LoginFacade.h
- WordPress/Classes/Services/LoginFacade.m
- WordPress/Classes/ViewRelated/NUX/Login2FAViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginFields.swift
- WordPressKit/WordPressKit/SocialLogin2FANonceInfo.swift
- WordPressKit/WordPressKit/WordPressComOAuthClient.swift
Refs #7675
This covers the scenario in which the user's account is already associated with Google, and their WordPress.com account requires 2FA.
To test:
- Setup a wpcom account to be associated with Google, and require 2FA
- Attempt to login to the app using Google
- When prompted for a 2FA token cover these scenarios:
- using app/generator token
- using SMS token
- using backup token
- using an incorrect of the above, then the real one
- using an incorrect of another sort, then a real one of a different kind (sms first, backup second, etc)
> Login: Add 2FA support for social login

- WordPress/Classes/Extensions/Media+Blog.swift
- WordPress/Classes/Models/Media.m
- WordPress/Classes/Services/MediaExportService.swift
- WordPress/Classes/Services/MediaService+Legacy.m
- WordPress/Classes/Services/MediaService.m
Fixes #8009 
So this PR restore the attachment of media to the posts on the new media code.
It also fix a status of the media object when the they are created.
To test:
- Open the app
- Insert a media object to the post
- Publish the post
- Go to the web and using the old WP-Admin check in the media library if your new media object is attached to the post.
> Make sure the media is attached to post.

- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
refs #7675
To test:
- Tap Log in with Google button
- Tap Cancel in the upper left
- _App should not crash_
*Note*: this was branched from #8010 and will include its changes until merged.
> Login: fix crash when dismissing Google view

- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
Refs #7675
Small change so that we keep the Google email address of failed login attempts to prefill on subsequent login or signup screens.
To test:
- Use the Google button to login to a Google account with no associated WordPress.com account.
- On the error screen, pick an option and ensure that the Google email address is correctly prefilled
- Repeat for the other two options
> Login: retain email address after failed Google login attempts

- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
- WordPressKit/WordPressKit/WordPressComOAuthClient.swift
Refs #7675
- Fixes next button spinning behaviour on email screen when using Google
- Improves error shown when Google login succeeds but then fails on wpcom
To test:
- Descriptions here: https://github.com/wordpress-mobile/WordPress-iOS/issues/7675#issuecomment-338247427
- Also, the error parsing for 400, 409, 403 responses has been refactored. Test it still works!
> Login: Several small UX fixes for Google login

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Fixes #7675
To test:
- ensure Google login shows up for a non-debug build
_Let's do this_
> Turn on Google login for all builds

- WordPress/Classes/Services/EditorSettings.swift
- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
- WordPress/Classes/ViewRelated/Post/WPLegacyEditPostViewController.m
- WordPress/Classes/ViewRelated/Post/WPPostViewController.m
- WordPress/Classes/ViewRelated/System/FancyAlerts+AztecAnnouncement.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/EditorSettingsTests.swift
Fixes #8032 
This PR:
- Enables [Aztec by default](https://github.com/wordpress-mobile/WordPress-iOS/compare/issue/8032-enable-aztec-for-all-users?expand=1#diff-da0fecd820d59f1edb25a061a232a23bR41) for the first launch of all versions moving forward.
- Simplifies the interface of `EditorSettings`.  External classes [now need to do less](https://github.com/wordpress-mobile/WordPress-iOS/compare/issue/8032-enable-aztec-for-all-users?expand=1#diff-fda23a7cb324124c3e6c17b7ac196d73R314).
- Editors [can no longer be turned OFF](https://github.com/wordpress-mobile/WordPress-iOS/compare/issue/8032-enable-aztec-for-all-users?expand=1#diff-da0fecd820d59f1edb25a061a232a23bL52).  This was "dangerous" and had no logical meaning.  Now you can only [turn one …
> Enable Aztec for all users by default.

- WordPress/Classes/ViewRelated/Plugins/PluginListViewController.swift
- WordPressKit/WordPressKit.xcodeproj/project.pbxproj
- WordPressKit/WordPressKit/PluginServiceRemote.swift
- WordPressKit/WordPressKit/PluginState.swift
- WordPressKit/WordPressKit/SitePluginCapabilities.swift
- WordPressKit/WordPressKitTests/Mock Data/site-plugins-success.json
- WordPressKit/WordPressKitTests/PluginServiceRemoteTests.swift
Switches the plugin remote to the 1.2 version of the endpoints.
This will only work for now on a site running Jetpack beta, but the changes will be included in the 5.5 release (Nov 7), which should be enough time since we'll release 8.8 two weeks later.
> Implement version 1.2 of the plugins endpoint

- WordPress/Classes/ViewRelated/NUX/Login2FAViewController.swift
- WordPressKit/WordPressKit/SocialLogin2FANonceInfo.swift
Fixes #8037
To test:
- Ensure you can still enter valid 2FA codes 😉
- Make sure to test normal wpcom accounts as well as Google-based login
- Test entering invalid codes: letters, codes longer than 8, etc
- The submit button should only be active for valid-looking 2FA codes
> Login: improve validation during 2fa entry

- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Tracks+ShareExtension.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift
- WordPress/WordPressShareExtension/ShareViewController.swift
- WordPressShared/WordPressShared/Core/Analytics/WPAnalytics.h
Fixes #8046 
This PR attempts to add analytics for error capture in the share extension. Unfortunately there still is a chance the error tracking call in `ShareViewController.swift` will not be fired. However by also adding a similar call to `ShareExtensionSessionManager.swift` we can attempt to track when something goes catastrophically wrong with the background URLSession when creating a new post. 
To test:
Try using the share extension and make sure everything still works as expected. Note: simply turning off the network will not cause the queued background upload task to fail.
Needs review: @SergioEstevao would you mind?
> Add error analytics to share extension

- WordPressKit/WordPressKit/CommentServiceRemoteREST.m
**Fixes** #7389 
**To test:**
1 - Like a comment on one of your Jetpack sites
2 - Fetch that comment via Reader and via Blog->Comments
3 - Check that the like is present
> Support for comment likes on Jetpack sites

- WordPressKit/WordPressKit/TaxonomyServiceRemoteXMLRPC.m
Fixes #8053 
To test:
Make sure tags show up in the tag picker for .org sites
> Fix tag loading for WordPress.org sites

- WordPress/Classes/Services/MediaImportService.swift
- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/Services/MediaThumbnailService.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
- WordPress/WordPress.xcodeproj/project.pbxproj
This PR renames the MediaExportService to be MediaImportService and also renames the export methods to be import method.
The rational for this change is that we are no exporting media but importing media from different source (PHAsset, URL, image) to our Media object.
It also moves the creation of the Media object to be done before the importing is done. This way it will be easier in the future to track progress of the import process.
To test:
- Open app
- Create new media by using the Media Library or creating a new post
- Check that data is created correctly.
> Refactor MediaExportService to MediaImportService

- WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m
Fixes #8052 
To test:
- Open a self-hosted site not jetpack
- Open Media Library
- tap on a image
- Check if navigation is working correctly.
> Fix alt field on .org sites.

- WordPressKit/WordPressKit.xcodeproj/project.pbxproj
- WordPressKit/WordPressKit/ActivityServiceRemote.swift
- WordPressKit/WordPressKit/RemoteActivity.swift
- WordPressKit/WordPressKit/ServiceRemoteWordPressComREST.m
- WordPressKit/WordPressKitTests/ActivityServiceRemoteTests.swift
- WordPressKit/WordPressKitTests/Mock Data/activity-log-auth-failure.json
- WordPressKit/WordPressKitTests/Mock Data/activity-log-bad-json-failure.json
- WordPressKit/WordPressKitTests/Mock Data/activity-log-success-1.json
- WordPressKit/WordPressKitTests/Mock Data/activity-log-success-2.json
- WordPressKit/WordPressKitTests/Mock Data/activity-log-success-3.json
**First step in** #7832
Remote implementation of the activity log feed endpoint.
**To test:**
Execute the tests, see that all is green.
For a site that supports the Activity Log you can add the following code to invoke the remote fetch:
```
let activityServiceRemote = ActivityServiceRemote(wordPressComRestApi: blog.wordPressComRestApi())
activityServiceRemote?.getActivityForSite((blog.dotComID?.intValue)!, count: 20, success: { (activities, hasMore) in
print(activities.count, hasMore)
}, failure: { (error) in
print("Error \(error)")
})
```
>  Activity Log Remote Feed initial implementation and tests

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #8068 
This PR adds logic to remove the overlay image on a media attachment when another is selected. In addition, the overlay reset logic was refactored into its own method to make things more DRY.
* Open a post with multiple media attachments and select an image. Now select another image. Verify the overlay text + image are removed from the previously selected image.
* Open a test post with and select an image. Tap the image again and then select dismiss from the action sheet. Verify the overlay image + text is removed.
* Open a test post, turn off the network connectivity, and attempt to upload media. After it fails, turn the network connectivity back on and then tap the image and select "Retry" on the action sheet. Verify the overlay image + text is removed.
_Note: Merging this …
> Aztec media overlay icon fix

- WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
Refs #7991.
It looks like our previous fix didn't resolve the issue. It's tricky because the crash report wasn't telling us exactly where the crash was. I found the same crash in Xcode's crashes, loaded it into the project, and it highlighted this line in `MediaMetadataPresenter`. This PR is just a small tweak to remove a force unwrap, which is all I can see potentially crashing there.
To test:
* Ensure you can still view details for media items in the Media section of the app.
cc @catehstn
> Issue/7991 Media Item View Controller crash

- WordPress/Classes/Extensions/NSAttributedString+StyledHTML.swift
- WordPress/Classes/Extensions/Notifications/NotificationBlock+Interface.swift
- WordPress/Classes/Extensions/String+RegEx.swift
- WordPress/Classes/Models/Post.swift
- WordPress/Classes/Models/ThemeIdHelper.swift
- WordPress/Classes/Utility/EmailTypoChecker.swift
- WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorOut.swift
- WordPress/Classes/ViewRelated/Aztec/Renderers/CommentAttachmentRenderer.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPress/Classes/ViewRelated/NUX/FancyAlertViewController+LoginError.swift
- WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
- WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift
- WordPress/WordPressScreenshotGeneration/SnapshotHelper.swift
- WordPress/WordPressShareExtension/SitePickerViewController.swift
- WordPress/WordPressShareExtension/String+Extensions.swift
- WordPress/WordPressUITests/XCTest+Extensions.swift
- WordPressKit/WordPressKit/WordPressComOAuthClient.swift
- WordPressKit/WordPressKit/WordPressOrgXMLRPCValidator.swift
- WordPressShared/WordPressShared/Core/Utility/RichContentFormatter.swift
- WordPressShared/WordPressSharedTests/LanguagesTests.swift
**Fixes** #8084 
**To test:**
- Clean + Build, check that we only have our usual 3 warnings (Update to Swift 4, Pods project settings, incompatible Objective-C category)
- Check that `EmailTypoChecker.swift` is working as expected (correcting emails for known domains on signups)
- Check that the rest of the app works fine
> Fix XCode 9.1 warnings

- WordPress/Classes/Models/Notifications/NotificationRange.swift
This PR patches the NotificationRange entity, so that whenever a plain link is present within a comment's body, it can be actioned upon.
Fixes #6056
1. Receive a Comment Notification with a link in it's body
2. Open the Notifications tab and expand it's details
3. Press over the link
As a result, a WebView should be onscreen.
Sir, may i bug you with a small fix?
cc @dmsnell because you've asked about the incoming comment-warning!!
> Notifications: Links in Comments are now actionable

- WordPress/Classes/ViewRelated/NUX/Login2FAViewController.swift
Fixes #8087
To test:
- begin login with an account that requires 2FA in simulator
- when entering 2FA code type it in, then hit enter on laptop
- no validation error should appear
> Login: Fix enter key causing validation problems in 2fa VC

- WordPress/Classes/Services/MediaUploadCoordinator.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #7597 
This PR adds a skeleton implementation of a MediaUploadCoordinator. It supports creating and uploading media via a single method, and observing begin / end events for a single Media object or for all Media objects. We'll build on top of this as we go, adding additional functionality and tweaking the implementation.
To test:
* You can check out a branch that makes use of this in the Media Library: `feature/upload-coordinator-in-media-library`. You should be able to use it to add media to the media library, and see a message logged out when the media item is created and finishes uploading.
> Add basic MediaUploadCoordinator

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR fixes an annoying UX bug, in which the Body + Title are rendered with a gap in between (temporarily!).
Fixes #8043
1. Enable Aztec
2. Edit a document that has Vertical Scroll
3. Press the body to display the keyboard
4. Swipe all the way down
5. Release your finger!
Verify that the Document's body doesn't loose "Vertical Sync" with the title. Sample video of the actual bug [available here.](https://cloudup.com/c02u4ci4Pqg).
> Aztec: Title + Body Constraints Out of Sync

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Fixes #8095.
This PR adds a feature flagged, local development only option to the Media Library when adding media, which uses the new in-development UploadCoordinator to perform uploads.
At the time of creating this PR, there's no UI indicating uploads in progress, but they do log out to the console.
To test:
* Build and run, and attempt to use the new upload option in the Media library. Check that the feature flag is for local development only.
> Async: Allow manual testing of UploadCoordinator in Media Library

- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.xib
In this PR we're patching up the Notification's Comments UI, so that the Gravatar size is always enforced.
Fixes #7436
1. Hack [this spot](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift#L646) and replace it with the following snippet:
```
cell.site = "A long long long long long site title made up in a galaxy far far far away"
```
Verify that Comment Notifications look as expected:
- The Gravatar should not get squashed, but the Site Title should get clipped
- Verify that the Name / URL look good
- Try rotations / multiple screen sizes
Thanks in advance James!!
> Notifications: Fixing Squashed Gravatars in Comments

- WordPress/WordPressTest/DomainsServiceTests.swift
We found some issues with automated tests that were failing in BuddyBuild due to timeouts.
This PR increases the timeout to avoid these random failures.
**To test:**
1. Run the unit tests and make sure the domain tests are not failing.
2. Make sure BuddyBuild's build also succeeds.
> Increase timeout for domain tests.

- WordPress/Classes/Models/Blog.m
Fixes #8114 
To test:
- Make sure the Themes section is visible for both WordPress.com and Jetpack sites
> Re-enable themes on WordPress.com sites

- WordPress/Classes/Services/MediaSyncCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
- WordPress/WordPress.xcodeproj/project.pbxproj
Fixes #8018 
To test:
- Open a blog that has a large media library (Meetomatic is a good example)
- Go to the media library
- Close
- Open the site icon media picker
- Close
- Create a new post, tap to add media and select the media library
- It should take a while to sync but no duplicates should show in the media library while the updates are going.
> Avoid media duplicates on Media Library

- .github/PULL_REQUEST_TEMPLATE.md
> We no longer need this because Github now support reviewers.

- WordPress/Classes/ViewRelated/Reader/WPImageViewController.m
This PR auto-hides the home indicator in `WPImageViewController` on iPhone X.
Before – the home indicator is always present at the bottom of the image view controller:
After – the home indicator hides a few seconds after the image view controller appears:
To test:
* Build and run the app on an iPhone X or in the simulator, and navigate to a site's Media Library.
* Tap on an image, then tap on the larger preview to view it full screen.
* Check that the home indicator at the bottom is hidden.
> WPImageViewController: Auto hide home indicator on iPhone X

- WordPress/Classes/Services/AccountService.m
- WordPress/Classes/Utility/CookieJar.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/CookieJarTests.swift
- WordPress/WordPressTest/MockCookieJar.swift
- WordPress/WordPressTest/WebViewAuthenticatorTests.swift
While working on #8120, I noticed the AccountService was clearing cookies from NSHTTPCookieStorage on sign out, but hadn't been updated to clear WebKit cookies.
This extends CookieJar so it's easier to remove cookies from both stores, and adds a debugging helper to clear all WordPress.com cookies.
Also added unit tests for CookieJar.
To test:
- Make sure unit tests pass
- Sign out and make sure no WordPress.com cookies are retained
To help with this, you can pause the execution and run this from LLDB:
```
(lldb) expr -l swift -- import Foundation
expr -l swift -- import WebKit
expr -l swift -O -- HTTPCookieStorage.shared.cookies
expr -l swift -- WKWebsiteDataStore.default().httpCookieStore.getAllCookies({ print($0) })
continue
▿ Optional<Array<NSHTTPCookie>>
- some : 0 elements
Process …
```
> Remove cookies from WebKit on sign out

- WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift
- WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
Re-targeting #8120 for 8.8
With the migration to WebViewAuthenticator and WebKit, we use a special
redirect system for WordPress.com, that needs some additional handling of the
authentication response.
In an oversight, this code wasn't added to PostPreviewViewController, which
uses its own UIWebView instead of subclassing the existing Web View Controllers.
Fixes #8117 
To test:
- Test from a fresh install to ensure there are no previous cookies
- Preview a post on a private site (or a draft)
- The preview should load the post correctly and authenticated
> Fix authenticated WordPress.com previews

- WordPress/Classes/System/WordPressAppDelegate.h
- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/Utility/ContextManager.m
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
A small PR that attempts to cleanup the calls to `[WPAnalytics track:WPAnalyticsStatLogout]`to be more accurate:
* The `ContextManager` [#](https://github.com/wordpress-mobile/WordPress-iOS/blob/6.2/WordPress/Classes/Utility/ContextManager.m#L223) 
-  I removed the call from here which, I realize, is debatable. My rationale is if there is a complete failure to spin up the `persistentStoreCoordinator`, the user is not actively "logging out". Perhaps another stat could be tracked here instead, but for now I removed it.
* The `BlogListViewController` [#](https://github.com/wordpress-mobile/WordPress-iOS/blob/6.2/WordPress/Classes/ViewRelated/Blog/BlogListViewController.m#L233)
- In this case, we were tracking the logout in `maybeShowNUX` which is called both from `dataChanged` and …
> Cleans up WPAnalyticsStatLogout tracking

- WordPress/Classes/Utility/WebKitViewController.swift
Fixes #8155 
To test:
Go to Site > View Site and make sure the web view looks good on an iPhone X
> Make WebKitViewController toolbar respect safe areas

- WordPressShared/CocoaLumberjack.swift
- WordPressShared/WordPressShared.xcodeproj/project.pbxproj
- WordPressShared/WordPressShared/Core/Utility/NSMutableData+Helpers.swift
- WordPressShared/WordPressShared/Core/Utility/RichContentFormatter.swift
- WordPressShared/WordPressShared/Core/Utility/WPImageURLHelper.swift
- WordPressShared/WordPressShared/Core/Views/WPStyleGuide+DynamicType.swift
- WordPressShared/WordPressShared/Languages.swift
- WordPressShared/WordPressShared/NSDate+Helpers.swift
- WordPressShared/WordPressShared/UIAlertController+Helpers.swift
Okay. Let's do this!. In this PR we're adding Swift 4.0 support to both, WordPressShared and WordPressSharedTests Targets.
1. Run the Unit Tests. Verify they stay green!
2. Click over the WordPressShared target 
3. Toggle the Language Picker to Swift 4
4. Verify that WPiOS still builds correctly
> WordPressShared: Swift 4.0 Support

- WordPressKit/WordPressKit.xcodeproj/project.pbxproj
- WordPressKit/WordPressKit/AccountSettingsRemote.swift
- WordPressKit/WordPressKit/ActivityServiceRemote.swift
- WordPressKit/WordPressKit/BlogJetpackSettingsServiceRemote.swift
- WordPressKit/WordPressKit/KeyringConnection.swift
- WordPressKit/WordPressKit/KeyringConnectionExternalUser.swift
- WordPressKit/WordPressKit/NotificationSettingsServiceRemote.swift
- WordPressKit/WordPressKit/NotificationSyncServiceRemote.swift
- WordPressKit/WordPressKit/PeopleServiceRemote.swift
- WordPressKit/WordPressKit/PluginServiceRemote.swift
- WordPressKit/WordPressKit/PushAuthenticationServiceRemote.swift
- WordPressKit/WordPressKit/RemoteBlogSettings.swift
- WordPressKit/WordPressKit/RemotePublicizeConnection.swift
- WordPressKit/WordPressKit/RemotePublicizeService.swift
- WordPressKit/WordPressKit/RemoteReaderCrossPostMeta.swift
- WordPressKit/WordPressKit/RemoteSharingButton.swift
- WordPressKit/WordPressKit/SharingServiceRemote.swift
- WordPressKit/WordPressKit/SiteManagementServiceRemote.swift
- WordPressKit/WordPressKit/SocialLogin2FANonceInfo.swift
- WordPressKit/WordPressKit/WordPressComOAuthClient.swift
- WordPressKit/WordPressKit/WordPressComRestApi.swift
- WordPressKit/WordPressKit/WordPressOrgXMLRPCApi.swift
- WordPressKit/WordPressKit/WordPressOrgXMLRPCValidator.swift
- WordPressKit/WordPressKit/WordPressRSDParser.swift
- WordPressKit/WordPressKitTests/AccountSettingsRemoteTests.swift
- WordPressKit/WordPressKitTests/JSONLoader.swift
- WordPressKit/WordPressKitTests/MockWordPressComRestApi.swift
- WordPressKit/WordPressKitTests/PeopleServiceRemoteTests.swift
- WordPressKit/WordPressKitTests/PluginServiceRemoteTests.swift
This PR is a follow up to #8159 (and should be reviewed after the former is merged). We'll introduce a few changes that make the WordPressKit Target Swift 4.0 friendly.
1. Verify that the app builds as usual
2. Toggle WordPressShared an WordPressKit to Swift 4.0
3. Verify that the app builds!
4. Verify that the WordPressKit Unit Tests are green
> WordPressKit: Swift 4.0 Support

- WordPress/Classes/Utility/WebViewAuthenticator.swift
Ensure the redirect URL is properly encoded, so the original URL is retrieved
when the redirect is intercepted
Fixes #8149 
To test:
Find a reader post with a link to Twitter and verify it works
> Fixes web authenticator problem with some URLs

- WordPress/HelpshiftCustomConfig.plist
**Fixes** #8153 
As part of iOS 11 changes, the background color of the search field in our FAQ section became dark blue, making it impossible to read what was being typed. Due to iOS 11 changes and the fact that this ViewController is presented entirely by Helpshift we can not fully control how it looks, so currently we are just setting the background color to white to improve readibility. Not a good looking solution but the best we can do without a Helpshift update (we have contacted them regarding this issue).
Before|After
-|-
**To test:**
1. Me->WordPress Help Center, check that the background of the Search field is light gray.
2. Test that other Helpshift functionalities (like Contact Us) work and look as expected.
> Change background color to white on FAQ search

- WordPress/WordPressShareExtension/ShareExtractor.swift
- WordPress/WordPressShareExtension/ShareViewController.swift
Fixes #8166 
This PR provides a fix for sharing web pages from Safari. See the bug for more details. In addition, a small change to `ShareExtractor` was made so the post's content body is properly filled when sharing a web page (including highlighted text). Previously it was left blank because the [completion handler](https://github.com/wordpress-mobile/WordPress-iOS/blob/13026fb5972644e6d8f9962ceea77ae155d2e4fb/WordPress/WordPressShareExtension/ShareExtractor.swift#L55) was never called.
1. Initiate sharing a web page to WPiOS in Safari. In the share UI, verify the post Title and Body are pre-filled and Safari doesn't hang when the post button is tapped. Check the destination site to make sure the post saved correctly.
2.  Initiate sharing a photo to WPiOS from Photos.  In the share UI, …
> Fix for issues sharing web pages from Safari

- Podfile
- Podfile.lock
Fixes a crash due to low memory, caused by repeated calls to `NSAttributedString().string`.
**To test:**
2. Type in the content: 0123456789
3. Select All, Copy
4. Paste 9 times.
5. You'll have 100 characters now.  Select All, Copy.
6. Paste 9 times.
7. You'll have 1000 characters now.
8. Repeat the process 2 more times in order to have 100k (100000) characters.
9. Switch to HTML mode.
Switching to HTML mode was causing a crash previously.  You can validate this by following the same steps in `release/8.8` or `develop`.
> Integrates Aztec 1.0.0-beta.14.1

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
**Fixes** #7662 
I have checked with the Reader team and we are ready to flip the switch on this one.
**To test:**
Check that comments are enabled for Jetpack sites on Reader for a production build.
> Remove feature flag for Jetpack comments on Reader

- WordPress/Classes/Services/LoginFacade.h
- WordPress/Classes/Services/LoginFacade.m
- WordPress/Classes/Services/WordPressComOAuthClientFacade.h
- WordPress/Classes/Services/WordPressComOAuthClientFacade.m
- WordPress/Classes/ViewRelated/NUX/Login2FAViewController.swift
- WordPressKit/WordPressKit/SocialLogin2FANonceInfo.swift
- WordPressKit/WordPressKit/WordPressComOAuthClient.swift
Fixes #8065
This turns on the button on the 2FA screen for requesting a new code via SMS.
To test:
- First, login with a Google-enabled wpcom account that requires 2FA
- You can only request a new 2FA code once a minute.
- You'll get a SMS code sent immediately. Wait over a minute and request a new code, it should appear.
- And if you mash the button, no new codes will be sent. However, each time you hit the button a request is made and the error creates a new nonce. So make sure you can hit the button a few times within a minute, and that it still works after a minute passes!
> Social Login: request a new SMS code for 2FA

- Scripts/prs.sh
Adds a new and more generic version of the `prs.sh` script, that doesn't require auth tokens inside the script.
IMPORTANT: after merging this PR we need to decide where to start writing the documentation for the scripts we have.  The instructions below can be used as a starting point for that documentation.
Before testing this script you have to make sure your local git configuration is properly set up.
**Make sure you have a `~/.ssh/config` file**
Do: `ls ~/.ssh/config`
If the file exists, jump to the GitHub entry configuration below.
If the file does not exist, follow the steps below to create it.
1. Create the file using your preferred text editor.
2. Run: `chown 600 ~/.ssh/config`
**Configure a GitHub entry in `~/.ssh/config`**
Here's an example of what it should look like:
```
Host …
```
> New prs.sh script

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Media/MediaCellProgressView.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR adds progress updates to cells in the media library when content is being uploaded asynchronously:
We show indeterminate spinners whilst the media items are being processed locally, then discrete progress during the upload, then indeterminate again once we hit 99% progress and the item is being processed on the remote end.
To test:
* Try uploading items using the async feature in the media library, and check the cells display correctly
* Try scrolling up and down the collectionview during an upload
* Try backing out of the media library and coming back in during an upload
* Check that normal uploads still work as expected
> Media Library: Show uploading progress in cells

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR fixes an issue where the Insert Link dialog in Aztec was detecting plain text clipboard items as URLs, and auto-filling them. 
To test:
* Copy some text that is not a URL to your clipboard. For example: "Pickle Rick".
* In Aztec, tap the insert link button. The URL should not be auto-filled (if you test on `develop`, it will be).
* Now copy some text that is a URL. For example: "https://stabby.today".
* In Aztec, tap the insert link button. The URL should now be auto-filled.
> Aztec: Improve automatic link detection

- WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Fixes #8219 
Copy of https://github.com/wordpress-mobile/WordPress-iOS/pull/8220 targetting `release/8.9`. 
I made a mistake on https://github.com/wordpress-mobile/WordPress-iOS/pull/8220 and merged into `develop` instead of `release/8.9`
> Configure comments sync helper for Jetpack sites

- Scripts/BuildPhases/AddVersionToIcons.sh
We should have the correct attribution in the icon generation script. This PR fixes that.
**To test:**
Check that the script still works correctly when generating the internal build.
> Add attribution to internal icon generation script

- WordPress/Classes/Models/Domain.swift
- WordPress/Classes/Models/ManagedAccountSettings.swift
- WordPress/Classes/Models/Post.swift
- WordPress/Classes/Services/AccountSettingsService.swift
- WordPress/Classes/Services/DomainsService.swift
- WordPress/Classes/Utility/CoreDataHelper.swift
- WordPress/Classes/ViewRelated/Domains/DomainsListViewController.swift
- WordPress/WordPressTest/CoreDataHelperTests.swift
- WordPress/WordPressTest/DomainsServiceTests.swift
- WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift
- WordPress/WordPressTest/NotificationSyncMediatorTests.swift
- WordPress/WordPressTest/PostTests.swift
Building WPiOS produces the following warning:
```
ld: warning: Some object files have incompatible Objective-C category definitions. Some category metadata may be lost. All files containing Objective-C categories should be built using the same compiler.
```
This is, reportedly, caused by `static var`properties, [declared in Class Extensions](https://stackoverflow.com/questions/39665979/xcode-8-objective-c-category-warning).
Pinpointing the exact source of this warning took **a lifetime**. I've tracked it down to **CoreDataHelper**'s `static var entityName`.
In this PR we're converting this mechanism into an actual method, which neutralizes the warning.
Verify that WordPress iOS builds correctly, without the ObjC Category Warning.
Needs Review: @koke 
> Fixing category warning

- WordPress/Classes/ViewRelated/NUX/SiteCreation.storyboard
Adding 'siteTypeTableCell' reuseIdentifier to Site Type table prototype cell.
Fixes #8216 
To test: Open project. Build. The warning should no longer appear.
Needs Review: @nheagy
> Fixing SiteCreation.storyboard build warning.

- MIGRATIONS.md
- WordPress/Classes/Models/PostTag.h
- WordPress/Classes/Models/PostTag.m
- WordPress/Classes/Services/PostTagService.h
- WordPress/Classes/Services/PostTagService.m
- WordPress/Classes/System/WordPress-Bridging-Header.h
- WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
- WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 68.xcdatamodel/contents
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPressKit/WordPressKit/RemotePostTag.h
- WordPressKit/WordPressKit/TaxonomyServiceRemoteREST.m
First PR for #8232 
Scope: 
- Update `PostTag` model object, to add a `tagDescription` optional property.
This PR only includes a new version of the coredata model, and a new property in the `PostTag` object.
My intention is to break down the implementation in several PRs, to keep their scope focused enough, and make reviews easier.
> The journey of a thousand miles begins with one step
Pinging @aerych
> Update PostTag model object

- WordPress/Classes/Utility/InteractiveNotificationsManager.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #7341 
Makes the distinction between HTML and Visual Mode clearer by:
- Changing the HTML editing mode font to Menlo.
- Highlighting the HTML button in the toolbar while in HTML mode.
fyi @jeremeylduvall, @iamthomasbishop 
Just launch the editor, and switch back and forth between visual and HTML mode.
Check that the above description matches what you see.
> Make html visual distinction clearer

- WordPressFlux/WordPressFlux.xcodeproj/project.pbxproj
Fixes error building WordPress-Internal, since it was looking for `WordPressFlux.framework` in the wrong build directory
> Adds Release-Internal/Release-Alpha configurations to Flux

- WordPress/WordPressShareExtension/ShareViewController.swift
- WordPressKit/WordPressKit/MediaServiceRemoteREST.h
- WordPressKit/WordPressKit/MediaServiceRemoteREST.m
- WordPressKit/WordPressKit/PostServiceRemoteREST.h
- WordPressKit/WordPressKit/PostServiceRemoteREST.m
- WordPressKit/WordPressKit/WordPressComRestApi.swift
- WordPressKit/WordPressKitTests/MediaServiceRemoteRESTTests.swift
This PR is the 2nd of a series that addresses uploading multiple media files (#8179) via the app extensions.  This PR:
* Adds 2 new methods to `MediaServiceRemoteREST` that will eventually be leveraged in #8179. For now, a few unit tests were added.
* Updates the returned `RequestEnqueuedBlock` from `WordPressComRestApi.swift` to include the background session's task ID. This task ID is _required_ in future PRs (used in working with NSURLSession + app extensions when crossing process boundaries)
* Contains a minor function call update in `ShareViewController.swift`
* Made `remoteMediaFromJSONDictionary` and `remoteMediaFromJSONArray` class methods.
* Includes some new/updated unit tests
Fixes #8264
Ref: #8263
* Verify that sharing media still works as expected (still only a max of 1 pic …
> Update WordPressKit to handle background uploads of multiple media items

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #8271 
Aztec was crashing when navigating back from the media library. In addition to the steps outlined in the original issue, it's also possible to trigger this by showing the fullscreen picker and then tapping Cancel. The crash arises from Aztec attempting to enable the HTML button in the toolbar, which doesn't exist while inserting media.
To test:
* See the original issue for replication steps.
* Also show the WordPress Media Library, then cancel it.
> Aztec: Fixes a crash when navigating back from the media library

- WordPress/Classes/System/WordPressAppDelegate.m
Fixes #8283 
Removes a log statement that is causing a crash when background NSURLSession resumes WPiOS when initiated from the share extension. See the issue for more details ☝️ 
This PR is for 9.0, `develop` already has this change.
> Remove log statement from handleEventsForBackgroundURLSession

- WordPress/Classes/Utility/Analytics/WPAppAnalytics+Media.swift
Fixes #8280 which affects older, 32bit devices.
This PR widens the `MediaProperties.bytes` value in `WPAppAnalytics+Media.swift` to an int64 which should (hopefully) prevent the overflow problem we are seeing in the issue ☝️. 
**To test:**
Open Aztec and upload some media so the media analytics fires. Make sure everything works as expected. If possible, test on an older device too.
@SergioEstevao would you mind taking a peek?
/cc @diegoreymendez @elibud
> Widened MediaProperties.bytes to Int64 in WPAppAnalytics+Media.swift

- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
**Fixes** #8297 
**To test:**
On Reader:
1. Find a post for a Jetpack site on reader (an example on the original issue).
2. Navigate to the post detail.
3. Check that the comment icon is present at the footer.
CC: @diegoreymendez targeting 9.0 on this one since it's a new Jetpack feature that should work on all fronts.
> Display comments on Reader Detail for Jetpack sites

- WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
Fixes #8098
Current builds will enter an unescapable login flow when restored from backup, which clears out the auth token from the keychain. This will allow those accounts to be reauthenticated.
To recreate the conditions of the bug, the wpcom auth token has to be deleted without deleting the whole app. I suggest putting this snippet in `application:willFinishLaunchingWithOptions:`. It has to go before `[WordPressAppDelegate fixKeychainAccess]`.
```swift
AccountService *accountService = [[AccountService alloc] initWithManagedObjectContext:[[ContextManager sharedInstance] mainContext]];
WPAccount *defaultAccount = [accountService defaultWordPressComAccount];
NSError *error = nil;
[SFHFKeychainUtils deleteItemForUsername:defaultAccount.username andServiceName:@"public-api.wordpress.com" …
```
> Allow wpcom accounts to be reauthenticated when restored from backup

- WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
For background see p4qSXL-2xV-p2
In certain scenarios we were sending the entire http response from a failed xmlrpc request to tracks as part of login error tracking.   This pr checks for the offending content and truncates it to preserve context, but avoid sending unhelpful info to tracks.
To test:
For a practical test you could edit a self-hosted test blog's xmlrpc.php file so it yields an error.  Set break points to inspect the diff then attempt to login to a self-hosted site. 
@astralbodies would you kindly?
> Tracks: Sanitize error messages sent to tracks.

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Fixes #8307 
To test:
- Open a blog media library
- Tap on + to add an object
- While the upload is ongoing tap on the media
- Select the option Cancel Upload
> Add methods for cancel uploads.

- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Fixes #8316 
To test:
- Open the Media Library of a blog
- Tap on Edit
- Select some media
- Tap on the trash icon
- Check that the selection indicator are removed.
> Media Library: fix selection on exiting edit mode

- WordPress/Classes/Models/Blog.m
- WordPressKit/WordPressKit/RemoteBlogOptionsHelper.m
Show plugins section only for sites  with Jetpack 5.6 or newer
See #8318 
To test:
> Require Jetpack 5.6 for plugin management

- WordPress/Classes/Services/PostTagService.h
- WordPress/Classes/Services/PostTagService.m
- WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift
- WordPressKit/WordPressKit/ServiceRemoteWordPressXMLRPC.h
- WordPressKit/WordPressKit/ServiceRemoteWordPressXMLRPC.m
- WordPressKit/WordPressKit/TaxonomyServiceRemote.h
- WordPressKit/WordPressKit/TaxonomyServiceRemoteREST.m
- WordPressKit/WordPressKit/TaxonomyServiceRemoteXMLRPC.m
Implements part of #8232 
Another early PR to check the general direction I've taken. 😊 
This one contains updates to the `PostTagService` and the Rest and XMLRPC taxonomies.
Saving and deleting seem to work fine, updating tags is a bit broken though. I am still looking into it, but in the meantime, more work for you, @aerych ! 😛
> Save, delete and update tags locally and remotely

- WordPress/Classes/Models/Blog.m
- WordPress/Classes/Models/JetpackState.h
- WordPress/Classes/Stores/PluginStore.swift
- WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift
- WordPressKit/WordPressKit/PluginServiceRemote.swift
- WordPressKit/WordPressKit/PluginState.swift
- WordPressKit/WordPressKit/RemoteBlogOptionsHelper.m
We don't allow some plugins to be removed or managed for automated transfer sites
See #8318 
To test:
> Keep track of automanaged plugins.

- WordPress/Classes/Stores/NoticeStore.swift
- WordPress/Classes/Stores/PluginStore.swift
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
As discussed, I removing the feature flag on notices since this is shipping in 9.1
See #8318 
To test:
- Go to plugins on a Jetpack site that has an update available
- Make sure the update will fail, changed permissions on the plugins folder so it wasn't writable, you can also take down the server, or add a mu-plugin that just calls `die()` 😬 
- The app should show a notice (alert) when the update fails.
> Show a notice if a plugin update fails

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
In this PR I'm increasing the number of fetched activities to 1000 and enabling the activity log on internal builds.
**To test:**
Go to a site with activity log and check that the feed is long ;)
> Activity Log: enable on internal builds

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
Fixes #8036 
Removes the social login feature flag.
To test:
- Make sure Google login still works
- And everything still builds.
Needs Review: @ScoutHarris 
Stephenie, got time to peak at this?
> Remove social login feature flag

- WordPress/Classes/Utility/WebKitViewController.swift
Fixes #8349 
This PR fixes a crash when attempting to share from the new WebKitViewController on iPad.
**To test:**
* Run the app on iPad / iPad Simulator
* In the blog details view controller, tap View Site at the bottom
* In the web view, tap the share icon, and check the activity view controller appears
* Prior to this PR, the app would crash when clicking the icon
> Issue/8349 WebKitViewController iPad Sharing Crash

- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
Fixes #8313 
To test: 
View the LoginEmailViewController and confirm that `Log into ..` is corrected to read `Log in to`. 
@ScoutHarris could I trouble you for a quick review? 🙏
> Login: Fixes a typo.

- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Fixes #8343 
To test:
- Open a media library of a blog
- Add new media using the async option
- Check if thumbnail of media shows when upload starts.
> When thumbnail is available make overlay transparent.

- WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
- WordPressKit/WordPressKit/Activity.swift
- WordPressKit/WordPressKitTests/Mock Data/activity-log-bad-json-failure.json
- WordPressKit/WordPressKitTests/Mock Data/activity-log-success-1.json
- WordPressKit/WordPressKitTests/Mock Data/activity-log-success-2.json
- WordPressKit/WordPressKitTests/Mock Data/activity-log-success-3.json
**Another step for** #7832 
Two changes go into this PR:
1. The field `summary` was moved to `content`.
2. We are removing our client side calculations for `isDiscarded` since they are now happening server side. We are keeping the code though since it might be useful when we (if we) implement review previews.
**To test:**
Fetch the Activity Log in a site with discarded events, check that they are displaying appropriately.
Note: This one is waiting on a server side change to be merged, I'll ping you @koke when it's ready.
> Activity Log: feed data update

- WordPress/Classes/Models/BlogSettings+DateAndTimeFormat.swift
- WordPress/Classes/ViewRelated/Blog/DateAndTimeFormatSettingsViewController.swift
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController+Swift.swift
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.h
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
- WordPress/Classes/ViewRelated/Tools/SettingsSelectionViewController.h
- WordPress/Classes/ViewRelated/Tools/SettingsSelectionViewController.m
- WordPress/WordPress.xcodeproj/project.pbxproj
**Another part of** #7831 
**To test:**
On a .com and Jetpack site try editing the following settings:
- Date Format
- Time Format
- Start of the Week
- Posts per page
To verify that everything is OK you will have to use the API or wp-admin because Calypso is too aggressive about caching and doesn't consider other apps modifying the site settings.
> Site settings: Missing writing settings

- WordPress/Vendor/ALIterativeMigrator.m
So, no idea why this is apparently _only_ happening on the X.
The bug is pretty obvious in retrospective — the code was iterating over a list of potential places where the `.momd` file might be, but _it never checked if it already found one_. 
This in turn meant, that the order of items in the array returned from `pathsForResourcesOfType:_inDirectory` mattered. For some reason, on iPhone X the `Extensions.momd` was after `WordPress.momd`, so the actual, correct result got overriden with `nil`, which lead to 💥.
Why the order was apparently different on the X then any other device still remains a mystery.
> Fix issue with crashes on startup on iPhone X.

- WordPress/Classes/Services/MediaService.h
- WordPress/Classes/Services/MediaUploadCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Fixes issue where the app would sometimes crash when the error passed to the `failure` block would be `nil`, despite being marked as `_Nonnull` in the header.
> MediaService: mark errors in callbacks to methods dealing with uploading media as nullable

- WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
Removes some old code that was causing trouble in App Settings.
2. Go to App Settings
3. Make sure the description label for "Usage Statistics" cannot be tapped.
Pinging @elibud for review since you're aware of the issue.
> Removes some old code that was causing trouble in App Settings.

- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController+Swift.swift
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.h
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
**Fixes** #7831 
This setting is available only for public WordPress.com sites. The irony that we are doing it in the Jetpack project does not escape me.
**To test:**
Site Settings -> Traffic, turn on and off, check that is saved. 
Tap on the footer, check that it takes you to the support page for AMP.
cc: @nbradbury in case it helps on Android
Thanks in advance
> Site settings: AMP

- WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
- WordPressKit/WordPressKit/Activity.swift
- WordPressKit/WordPressKitTests/Mock Data/activity-log-bad-json-failure.json
- WordPressKit/WordPressKitTests/Mock Data/activity-log-success-1.json
- WordPressKit/WordPressKitTests/Mock Data/activity-log-success-2.json
- WordPressKit/WordPressKitTests/Mock Data/activity-log-success-3.json
**Another update for** #7832 
Recently the activity format changed to have two fields, a summary and a text. In this PR we a re updating the mobile version of the Activity Log to display the summary bolded and the activity text next to it.
**To test:**
On a site with the Activity Log enabled check that the feed looks good.
cc: @mattmiklic
> Add summary field to activities

- WordPress/Classes/ViewRelated/NUX/LoginLinkRequestViewController.swift
- WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift
- WordPress/WordPressTest/SigninHelperTests.swift
Fixes #8389 
This PR tweaks the way magic link logins are handled when the user is trying to log in to Jetpack.
Changes made include:
- Updates the information saved to UserDefaults so a Jetpack login is properly identified when launching the app via a magic link.
- Updates the default WordPress account check to allow a Jetpack connection.
This should resolve the issue where a user can be left on the "open email" screen after using a magic link.
**Note**: You can test magic links in the simulator by opening the magic link email in your desktop browser, copying the link (don't click on it) and then pasting the link in Safari in the simulator. 
To test:
**Scenario 1**:
Confirm magic links still function as expected. 
**Scenario 2**:
Be signed into a wpcom account. 
Add a self-hosted blog …
> Login: Tweaks magic link handling for jetpack logins.

- WordPress/Classes/ViewRelated/NUX/SigninKeyboardResponder.swift
Fixes #8335
Login buttons now have appropriate padding on iPhone X:
To test:
- Ensure that the login button is in the right place on iOS 11 and 10 devices, on iPhone X, regular iPhone, and iPad
Got time for one more before you go?
> Fix bottom padding in login on iPhone X

- WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
Fixes #8304 
To test:
Go to Blog Posts in the app and select a post with links, tap "View", long-press a link, tap "Open"
Behavior:
External links should open in the external browser. Internal links (to the same blog) should open in the app.
Note: 
The previous behavior on "UIWebViewNavigationTypeLinkClicked" was to simply return "NO" without taking any action. Clearly someone put it the code for a reason, but I can't figure it out. I didn't find any way to make a call to the class where the new behavior is inappropriate, but I'm new to this codebase. So, if you are aware of cases where the old path has to be followed, please let me know so that I can add the proper checks.
> Fix the missing links opening in preview

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Implements #8397.
This PR adds a "Write Post" action to the notice that is displayed when media finishes uploading asynchronously to the media library.
Tapping the Write Post button will display the editor for the blog you just uploaded media to.
**To test:**
* Select a blog and upload some media items using the async upload option in the media library
* Tap the Write Post button on the notice that's displayed, and ensure the editor is presented for the correct blog.
* Close the editor and upload media to a different blog. Ensure the notice shows the correct count for the media items you just uploaded, and that the Write Post button shows the editor for the new blog.
> Async Media: Add Write Post action to success notice

- WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Although i couldn't directly reproduce this issue, in this PR we're adding a failsafe that should prevent any `BlogDetailsViewController` instance from being pushed, twice, in the blogList's navigation controller.
Needs Review: @nheagy 
Nate, maaaay i bug you with a hopefully simple PR?. I'm aware it's a band aid fix, but should be better than the actual crash. I could not find any flow to trigger the actual crash.
Closes #7284
1. Verify that pushing any blog's details works correctly (from the blog list)
2. Trigger the 3d Touch menu from the springboard. Verify that `Stats` works a expected.
> BlogListViewController: Crash Failsafe

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTextTableViewCell.swift
In this PR we're fixing a bug that caused `Stats are Booming` notification link, to redirect to a Website, instead of opening the native Stats.
Needs Review: @frosty 
Sir, may i bug you with a review?. Thanks in advance!!
Fixes #7070
1. Receive a Stats are Booming notification (DM me! i've got a testing account ready!)
2. Open it's details
3. Perform a long press / regular press over any of the links
Verify that the native Stats UI shows up.
> Notifications: Fixing Event Handling

- WordPress/Classes/Extensions/String+RegEx.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/Aztec/CalypsoProcessorOutTests.swift
In this PR we're fixing a NSRange conversion, source of a data loss bug.
Fixes #8399
2. Open Aztec and paste the sample HTML snippet attached below
3. Publish the post
4. Verify that the post shows up correctly
5. Edit the post in Aztec: Perform no changes, but hit the **update** button
6. Refresh the post in your browser
Verify that the post is in pristine condition, and no single character has been lost.
cc @bummytime 
--
```
Test &amp; Test 😊<strong>Test &amp; Test</strong>&lt;
1 tablespoon olive oil&lt;	 	 
lb. sweet Italian sausage, removed from casings&lt;	 	 
medium carrots, peeled, sliced into thin half-moons&lt;	 	 
stalks celery, trimmed, thinly sliced&lt;	 	 
medium yellow onion, diced small&lt;	 	 
cloves garlic, minced&lt;	 	 
/4 …
```
> Aztec: Data Loss

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Although i've been unable to directly reproduce this crash, i've noted the following snippet in the crashlog:
```
6  WordPress                      0x1003f10c0 @objc NoteBlockActionsTableViewCell.replyWasPressed(AnyObject) -> () + 4299002048
```
**replyWasPressed** is expected to **only** be used in iPad Devices. On iPhone devices, the method should never run. Yet, we've got 86% of crashlogs on iPhone devices.
While testing this one, i've manated to trigger a scenario in which multiple DetailsViewController's get pushed ([sample video here](https://cloudup.com/cXaSLF9mqka)).
I'm suspecting the crashlogs are (somehow) picking invalid symbols // corrupt. In this PR we're preventing the "multiple details push", which may trigger a wide variety of issues.
We'll revisit if the crash shows up …
> NotificationsViewController: Prevents pushing multiple DetailsView

- WordPress/WordPressTest/PostListFilterTests.swift
Hi there! I'm working on a [SwiftLint](https://github.com/realm/SwiftLint) rule which enforces specific matchers over `XCTAssertEqual` and `XCTAssertNotEqual`. For instance,  `XCTAssertEqual(true, foo)` throws a violations and suggests `XCTAssertTrue` instead.
SwiftLint's build system runs against popular open source software - which includes this one - and some violations were detected.
This pull request is just a suggestion. Feel free to reject it if it's relevant for the project.
> Uses specific XCTest matchers over XCTAssertEqual

- WordPress/Classes/ViewRelated/Aztec/Media/MediaProgressCoordinator.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
- WordPress/WordPressTest/MediaProgressCoordinatorTests.swift
- WordPressKit/WordPressKit/WordPressComRestApi.swift
- WordPressKit/WordPressKit/WordPressOrgXMLRPCApi.swift
Implements #8402.
This PR adds a notice which will be displayed when async uploads fail in the media library.
If all current uploads fail to complete, a notice like this will be displayed:
If any of the uploads are successful, that number will also be included:
I had to make some changes to the way failures are handled within `MediaProgressCoordinator` and `WordPressComRestApi` / XMLRPC to get this working, so it's important we test that this hasn't broken anything else. I added / changed some unit tests to verify this behaviour too.
I had to make these changes because I was seeing a problem where sometimes when uploads failed  a success message would be shown, or if only some uploads failed the wrong failure count would be shown. The issue seems to be with the previous behaviour:
* …
> Media Library Async: Show notice for failed uploads

- WordPress/Classes/ViewRelated/Aztec/Media/MediaProgressCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
Refs #8409 
This PR adds the Retry action to failed media uploads.
**To test:**
* You have to be quite quick to test this! If you struggle, you can increase the `dismissDelay` in `NoticePresenter.Animations`.
* Start some media uploading in the media library and cause it to fail – for example, switch to airplane mode.
* As soon as the media's failed, turn off airplane mode and dismiss control center
* You should still see the 'failed to upload' notice at the bottom of the WP app – it should have a Retry button
* Tap Retry, and you should see the media attempt to upload again
> Media async: Add retry action to failure notice

- WordPressKit/WordPressKit/PluginDirectoryServiceRemote.swift
Fixes #8421 
To test:
- Make sure your phone/simulator is in Spanish
- Go to a site's plugins
- Make sure the icons are loading
> Fix date parsing for plugin directory entries

- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
**Fixes** #8419 
**To test:**
Check that the 'Pages' section title is updated to 'Site Pages' and that that section and the 'Blog Posts' section works correctly.
Also, 'Site Pages' should be the first item under 'Publish'
> Rename pages section to site pages and move it up

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
**Fixes** #8418 
**To test:**
For a .com site go to Site Settings and check that the plan icons is now the Jetpack logo.
> Update plans icon to Jetpack logo

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR updates image capture and "Other Apps" document selection to use the new async upload methods.
Note that the code will get a bit neater once we remove the feature flag.
**To test:**
* On a device, try the "Take Photo or Video" and "Other Apps" upload options.
* Check that they upload in an async manner, with no HUD
> Media Library: Add async support for capture and document picker

- Podfile
- Podfile.lock
Updates the media picker to version 0.26
There wasn't any API changes on this version it's mainly bug fixes inside the pod, so the changes are very small, check [here](https://github.com/wordpress-mobile/MediaPicker-iOS/milestone/51?closed=1) to see what they were.
To test:
- Run the app and just see if the main uses of the picker are correct: Media Library, Post Editor, Site Icon Picker, Gravatar Picker.
> Update pod file to use MediaPicker 0.26

- WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
This PR fixes a string that was being formatted in a way that was problematic for translators.
**To test:**
On a Jetpack site:
1. Go to Site Settings -> Activity
2. Tap on an activity that has a blue ribbon on the left
3. Check that the string looks good
cc: @akirk
> Fix incorrectly formatted string

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR removes the feature flag for iCloud Files / other apps import in the media library and Aztec. Note that this feature is only available in iOS 11.
**To test:**
* Go to a site's Media Library, tap the + button and check that:
* On iOS 11 there is an 'Other Apps' option, and you can use it to import a file to the app.
* On iOS 10, there's just a Photo Library and (if you're testing on a device) a "Take Photo or Video" option.
* Open the editor, tap the + button on the left of the formatting toolbar and check that:
* On iOS 11 there is a '...' option, and you can use it to import a file to the app.
* On iOS 10, there's just a Photo Library, Media Library, and (if you're testing on a device) a Camera option.
> Remove file import / iCloud Files feature flag

- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/Services/MediaThumbnailService.swift
- WordPress/Classes/Utility/Media/MediaImageExporter.swift
- WordPress/Classes/Utility/Media/MediaThumbnailExporter.swift
Fixes 
This PR tries to address issues with thumbnail generation where sometimes thumbnails are not being create at all.
To test:
- Open the app
- Open the media library of a site ( preferably one that wasn't sync before)
- Check if thumbnail are generated correctly
- Try the same by adding new media to the media library.
> Fix media thumbnail generation

- WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift
If the plugin is not active, don't say it will deactivate on removal
Fixes #8424 
To test:
- Try to remove a plugin
- If it's active, the alert should say it will deactivate
- If it's inactive, the alert should not say it will deactivate
> Improve alert when removing a plugin.

- WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Fixes #8441 , #8452
To test:
- Have an account with only one site.
- Verify the siteCreation Feature Flag is enabled (should be by default).
- Go to 'Switch Site'.
- Verify the site isn't auto-selected and the app doesn't crash.
> Fix test for whether we should auto-select single site.

- Podfile
- Podfile.lock
- WordPress/WordPressTest/Posts/PostAttachmentTests.swift
Integrates Aztec 1.0.0-beta.17 into WPiOS.
Also fixes some unit tests which were broken with the update.
This is high priority since we need it to release WPiOS 9.2 as soon as possible.
General testing.  Make sure nothing important is broken.
> Integrates the latest from Aztec into WPiOS.

- Scripts/fastlane/Snapfile
Fixes #
a misalignment of locale identifiers between various scripts that caused some missing when uploading metadata/screenshots.
> Locale identifiers for fastlane screenshoter updated

- WordPress/Classes/Extensions/Array.swift
- WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
- WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
- WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
- WordPress/WordPressTest/Extensions/ArrayTests.swift
- WordPressKit/WordPressKit/Activity.swift
- WordPressShared/WordPressShared/NSDate+Helpers.swift
Another step on https://github.com/wordpress-mobile/WordPress-iOS/issues/7832
- Updated Activity icon on the blog settings screen.
- Grouped activities by date on the feed.
- Filtered out discarded activities.
**To test:**
On a site with AL enabled check that what  you see on mobile matches the web minus the discarded activities, which will not be displayed on mobile for now as per the last designs from @mattmiklic.
The grouping code on `ActivityListViewModel` is not meant to be permanent since we will have to face the paging + persistence issue eventually.
> Activity Log: Step 1 for design v1

- WordPressKit/WordPressKit/TaxonomyServiceRemoteREST.m
- WordPressKit/WordPressKitTests/TaxonomyServiceRemoteRESTTests.m
**Fixes** #8477 
Bug fix: fetch 1000 tags per site, the API default value was 100.
**To test:**
In a site with more than one hundred tags, go to Settings->Tags and check that they are all present.
Targeting `9.2` as this is a bug on a non-release feature.
cc:  @diegoreymendez
> Tags: Increase number of items fetched

- WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift
Fixes #8475 and #8470 
**To test:**
1. Check that you can create a new tag with a name that's not currently being used.
2. Check that you can edit a tag to a name that's not currently being used.
3. Check that you can't create a new tag with a name that's currently being used.
4. Check that you can't edit a new tag to a name that's currently being used.
cc: @diegoreymendez
> No tags with duplicate names

- .hound.yml
As described in the title – PRs currently have Hound as a required step, but it never fails them even if there are violations. This PR enables a setting so that violations will fail the PR check.
> Set Hound to fail PRs due to violations

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Small code refactor to move media action sheet strings to a static struct like the others in the class.
To test:
- Just check if the messages are correctly moved.
> Move media related action strings to static struct.

- WordPress/Classes/ViewRelated/Blog/SiteManagement/SettingsTitleSubtitleController.swift
Fixes #8474. This PR adjusts the `lineFragmentPadding` of the textview in the Tags settings screen so that the text aligns with the textfield used for the title. I also took the opportunity to refactor a few function / variable names to better fit our style.
**To test:**
* Navigate to a site > Settings > Tags
* Ensure that the text lines up between the two text fields. Try typing multiple lines of text and ensure that the scrollview doesn't overlap the text.
> Issue/8474 Fix Tags textview leading inset

- WordPress/Classes/Utility/Media/MediaVideoExporter.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR refactor a bit of code that was being used in Aztec to generate thumbnails.
Because the same code already exists on an MediaVideoExporter I refactored it to use that exporter.
To test:
- Add a self-hosted site that doesn't use Jetpack
- Create a post
- Insert a video to it
- Switch to HTML and back to visual
- See that thumbnail is generated correctly.
> Refactor video thumbnail generation

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #8507
This PR adds an option to do retry all of failed media uploads on Aztec.
To test:
- Turn On airplane mode
- Add multiple media objects to the post
- See them all fail
- Turn Off Airplane mode
- Tap on one media
- Check that Retry All Failed Media option shows off
- Tap on it
- Check if media is uploaded correctly.
> Add option to Retry All failed uploads.

- WordPress/Classes/Utility/InteractiveNotificationsManager.swift
- WordPress/Classes/ViewRelated/Media/MediaNoticeNavigationCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
In #8469, we displayed media async successful upload notices as local system notifications if they occur when the app is in the background. In this PR we do the same for failure notices.
**To test:**
* In the Media Library, start some media uploading
* Before the media completes, exit to the home screen and cause the uploads to fail (I used Airplane Mode)
* You should see a system notification confirming that the uploads failed.
* If you tap the notification, you'll be taken back to the media library in the app (you could also test this by navigating away from the media library in the app before leaving to the home screen)
* If you pull down on the notification, you should reveal a Retry action. Tapping this should take you back to the media library and attempt to retry the uploads. The …
> Media Async: Display failure notices as notifications when the app is in the background

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR refactors the location and code layout of the display video methods and improves the error handling when videos are not retrievable.
To test:
- Create a new post.
- Add a new video to it.
- Wait for upload to finish
- Now turn off the internet (airplane mode)
- Tap on the video and select the option Play
- See if an alert shows up
- Turn Internet on again
- Tap again to play video
- see if video plays correctly.
> Refactor display video methods

- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/Utility/Analytics/WPAppAnalytics+Media.swift
- WordPress/Classes/ViewRelated/Aztec/Media/MediaProgressCoordinator.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaNoticeNavigationCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
- WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
- WordPressShared/WordPressShared/Core/Analytics/WPAnalytics.h
Fixes #8520. This PR updates the behaviour to show the editor when the user taps the Write Post button in successful media upload notices. Now, when the editor is presented, the post will be pre-populated with the uploaded media items.
**To test:**
* In the media library, start some media items uploading
* When the upload completes, tap the **Write Post** button on the Notice
* Check that the editor is displayed with the new media items ready populated
* Also test the same but exit to the home screen once we've started items uploading, and using the Write Post action from the system notification that's displayed.
> Media notices: Pre-insert uploaded media into new editor post

- WordPress/Classes/ViewRelated/Blog/SiteManagement/SettingsTitleSubtitleController.swift
**Fixes** #8471 
Automatically make the Name TextField the first responder, and move on to the Description TextView when Done is tapped. When Done is tapped on the Description field the VC should be dismissed and the changes saved.
**To test:**
Go to Settings -> Tags, select an existing tag and create a new one, for both cases check that:
1. The Name field should be the first responder.
2. Tapping done should move you to the Description field.
3. Tapping done again should dismiss the VC and take you to the tag list.
4. Changes should be saved.
> Tag creation and edition improvements

- WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
Title has it. Fixes #8513 
To test:
1. Log into WPiOS with and account that follows lots of sites.
2. Open up Reader-> Followed Sites -> Manage
3. Scroll around and verify site icons are not reused on incorrect sites (a slower connection may help).
4. Profit.
@elibud Could you do a quick review for this?
> Small site icon fix for managing followed sites

- Podfile
- Podfile.lock
This PR updates Aztec to beta 18.
The main change in beta 18 is a change on the TextViewAttachmentDelegate for the deleteAttachment callback.
This was already integrated on the main app but referring to a version of the pod using a commit SHA reference. This update the reference to use an official Aztec reference.
To test:
- Make sure the project compiles and passes unit tests correctly.
> Update Aztec to beta 18.

- WordPressKit/WordPressKit/AccountServiceRemoteREST.m
Fixes #8515
This PR updates the version of the endpoint that is being used for `me/sites` to version 1.2.
The only difference I detected using a diff tools is that the new endpoint is not offering the following entry `site.plans.free_trial`
To test:
- Start the app from scratch
- Check that the sites are sync correct
- Go around inside some sites and check if any information is missing
- Site plan and Site Settings are good places to check.
> Update version of endpoint being used on me/sites

- WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
Title has it.
Fixes #8540 
**To test:**
1. Launch the share extension (with text/photos/web)
2. Verify the soft keyboard appears and the cursor is positioned at the end of the post.
3. Press the next button, verify the keyboard is dismissed.
4. Press the back button, verify the keyboard appears again.
Also, try the same thing on an iPad with the hardware keyboard attached/not attached.
@SergioEstevao would you mind taking a peek at this?
/cc @folletto
> Makes the soft keyboard active when launching share extension

- WordPress/Classes/Services/MediaCoordinator.swift
Fixes #8549 
This PR changes the context where insertions are done to avoid scenarios where the app get's deadlocked waiting for a secondary thread to get active to execute the work.
To test:
- Check ticket for steps on how to reproduce.
> Use main context for insertion.

- WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
This PR changes the alert text displayed to a user when they don't have an oauth token set when the share extension launches:
Note that this PR is merely a stopgap. In a subsequent PR, we need to get smarter about what the user needs to do in order to share something to WordPress. e.g:
>    I'm not logged in at all.
>    I'm logged in to a WordPress.com account with no sites.
>    I'm logged in to a self-hosted site that doesn't use Jetpack.
Addresses part of #8552 for WPiOS 9.3
To test:
1. Launch WPiOS and log out.
2. Open Safari and attempt to share a webpage. 
3. Verify the alert text matches the image above ☝️ 
@elibud Could you give this a quick 👀 ?
> Cleaned up login alert for share extension

- WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.swift
- WordPress/Classes/ViewRelated/Stats/StatsViewController.m
This ensure the Stats screen will refresh the blog's Jetpack status every time it loads, or the connection flow is dismissed (successfully or not)
Fixes #5154
To test:
- Go to the stats screen after having installed/connected/disconnected/removed Jetpack from the web. It should always refresh and show the right prompt.
- If you cancel the connection flow it should also refresh.
> Refresh Jetpack status when loading stats

- WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.swift
This was authenticating with the blog prior to loading a link on
apps.wordpress.com, and it wasn't redirecting properly, showing the
blog's wp-admin instead.
To test:
- Go to Stats on a self hosted site without Jetpack
- Ensure the more information link loads the FAQ
> Don't pre-auth Jetpack FAQ link

- WordPress/Classes/ViewRelated/Jetpack/JetpackConnectionWebViewController.swift
After a round of testing, it was reported that the flow was redirecting
to the plugin installation page right after selecting "Connect to
WordPress.com".
The problem was the current step switch was too specific, and it was
only clearing the site redirect if visiting an admin page other than
the expected ones (this was a workaround because poopy.life takes you
to wp-admin instead of the passed redirect_to URL).
This change will check if the detected step is any admin page and
prioritize using the redirect if there is a pending one.
To test:
1. Create a jurassic.ninja test site without Jetpack: https://jurassic.ninja/create?nojetpack
2. Add a new user to the site with my own email address
3. Log in to the test site in the app with that new user account
4. Try to set up Jetpack in the app
> Fix connection flow redirect handling.

- Podfile
- Podfile.lock
Updates Aztec to beta 18.1
To test:
- Just check project compiles and build correctly
> Update aztec to beta 18.1

- WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.swift
There was indeed a line break after the "Congrats!". This PR removes it.
> Tweak line breaks on Jetpack login prompt

- MIGRATIONS.md
- WordPress/Classes/Models/Blog.h
- WordPress/Classes/Models/Blog.m
- WordPress/Classes/Models/BlogSettings.swift
- WordPress/Classes/Services/BlogJetpackSettingsService.swift
- WordPress/Classes/ViewRelated/Blog/JetpackSpeedUpSiteSettingsViewController.swift
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController+Swift.swift
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
- WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 71.xcdatamodel/contents
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPressKit/WordPressKit.xcodeproj/project.pbxproj
- WordPressKit/WordPressKit/BlogJetpackSettingsServiceRemote.swift
- WordPressKit/WordPressKit/RemoteBlogJetpackModulesSettings.swift
**Fixes** #8568 
This PR adds two new Site Settings under the section Speed up your site: 
- Lazy Load Images 
- Serve Images from our servers
**To test:**
1. Test that the new section under writing is only present for Jetpack sites.
2. Test that updating the settings in the app is reflected in `/sites/SITE_ID/jetpack/modules` `v 1.1`
cc: @planarvoid
> Jetpack Settings: Speed up your site

- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/Utility/Media/MediaAssetExporter.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPressKit/WordPressKit/MediaServiceRemoteREST.m
- WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m
Fixes #8592 
This PR adds a fix to the `MediaAssetExporter` class to allow export of assets stored in the iCloud. The fix consists in allowing the PHImageManager to do an asynchronous request when media is not stored locally, otherwise the request for image fails. 
It also adds failsafe code to the MediaService and remote objects to prevent crashes when trying to upload Media that doesn't have a local file assigned. To finish it of it also adds options on the UI to remove/delete Media when that scenario is detected.
To test:
- Insert a media object that is on iCloud or in a shared stream and is not cached on the device (media that is not open or never opened full screen on that device)
- Check that insert works
- Try the same on the media library.
> Allow insert media from iCloud and add failsafes when import fails.

- WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
Fixes #8590. This PR switches the notice view model for async uploads to use the successful item count instead of the progress completed unit count. The successful items array provided by the progress coordinator has any cancelled items removed from it, which means we don't incorrectly show cancelled items as part of the successful item count.
**To test:**
* In the media library, begin one item uploading and then cancel it. No notice should be displayed.
* In the media library, begin multiple items uploading and cancel one of them. After the others have successfully uploaded, the notice displayed should show the count of successful uploads, not counting the one you cancelled.
* In the media library, begin multiple items uploading and cancel one of them. Switch on airplane mode so that all …
> Media async notices: Use successful upload count to account for cancelled items

- WordPress/Classes/ViewRelated/NUX/LoginSiteAddressViewController.swift
**Fixes** #8597 
**To test:**
Follow the steps on the issue and check that the displayed message is correct.
@jklausa another small one for you that has to be merged on Monday, thank you :)
> Fix typo in not a WordPress site message

- WordPress/Classes/ViewRelated/Activity/WPStyleGuide+Activity.swift
**Fixes:** 
A new icon is being used for the backup activity and we were missing a mapping for it. 
**To test:**
Run the app, go to the Activity Log and check that backups have an icon.
> Add missing icon mapping

- WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift
To test:
Go to plugin details and make sure version number still displays correctly.
> PluginViewModel: use a string format that friendlier to translations.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #8593 
This PR fixes the duplication of images when copying and pasting. The problem was cause because when an image was detected we where inserting back an attachment instead of updating the already existing attachment.
To test:
- Copy/paste to the post an image from another application (Safari or Notes)
- Check if the image is added and uploaded to the blog and no duplication show up
> 8593 Fix Duplication of image when copy/pasting

- WordPress/Classes/Extensions/UIControl+Helpers.swift
- WordPress/Classes/ViewRelated/NUX/Login.storyboard
- WordPress/Classes/ViewRelated/NUX/Login2FAViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginSelfHostedViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginSiteAddressViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginWPComViewController.swift
- WordPress/Classes/ViewRelated/NUX/Signup.storyboard
- WordPress/Classes/ViewRelated/NUX/SignupEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
- WordPress/Classes/ViewRelated/NUX/SiteCreationDomainSearchTableViewCell.swift
- WordPress/Classes/ViewRelated/NUX/SiteCreationSiteDetailsViewController.swift
- WordPress/Classes/ViewRelated/NUX/WPStyleGuide+Login.swift
- WordPress/Classes/ViewRelated/NUX/WPWalkthroughTextField.h
- WordPress/Classes/ViewRelated/NUX/WPWalkthroughTextField.m
- Fixes for RTL layout in the Login section.
- Refactor of the `WPWalkthroughTextField` class to work well with RTL layout.
**NOTE:**
- There is a breaking change for the `WPWalkthroughTextField` class: The new `contentInsets` take the place of the old `textInsets` property.
- The `textInsets` property is now the inset around just the text area. In most cases, should be fine to leave the default value ( `.zero` )
- The new `leadingViewWidth` helps to give extra space between the left image and the text. The default value should work fine unless we start using bigger (or longer) images. This also helps to perfectly align the left images and text of many textfields when they are stacked vertically.
- The rest should continue working like it did before.
- There are new extra options for …
> Fixes for RTL layout in the Login section.

- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/Utility/InteractiveNotificationsManager.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressShareExtension/AppExtensionsService.swift
- WordPress/WordPressShareExtension/ExtensionNotificationManager.swift
- WordPress/WordPressShareExtension/ShareExtensionAbstractViewController.swift
- WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift
- WordPress/WordPressShareExtension/ShareModularViewController.swift
- WordPress/WordPressShareExtension/ShareNoticeConstants.swift
- WordPress/WordPressShareExtension/ShareNoticeNavigationCoordinator.swift
- WordPress/WordPressShareExtension/ShareNoticeViewModel.swift
- WordPress/WordPressShareExtension/SharedCoreDataStack.swift
- WordPressShared/WordPressShared/Core/Analytics/WPAnalytics.h
This PR adds notification support to the share extension. Because of the non-deterministic nature of _either_ WPiOS _or_ the extension getting the "did complete" callback, I needed to fire off notifs from 2 different places:
* `ExtensionNotificationManager.swift` (via share extension)
* `ShareExtensionSessionManager.swift` (via WPiOS)
Two things to note here: 
1. The retry action is not implemented in this PR and will be part of the retry work itself.
2. IF the share extension's callback handles the post response...in-app notifs will not work. Perhaps @frosty could offer up some guidance here with his recent work on all this. :-)
Fixes #8146 
**Test 1:**
1. Open the Photos app and share 1 or 2 images.
2. Don't launch WPiOS.
3. You should see a iOS notification after a few seconds.
4. Tap …
> Share Ext: Added notification support to the share extension

- WordPress/Classes/Utility/Media/MediaImageExporter.swift
- WordPress/WordPressTest/MediaImageExporterTests.swift
Fixes #8613 
This PR, changes the place were we remove the orientation info to only be done when we are resizing the images and use the `kCGImageSourceCreateThumbnailWithTransform` option. ]
When we just copying the full size image we should keep the original orientation info.
To test:
- Check the ticket above for step on how to reproduce
> Fix orientation of images when copy pasted to a post

- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
We need a way to measure how many of the total users use the right-to-left version of the app.
This PR implement this by add a property to Tracks named `is_rtl_language` (the same name used on Android). 
**To test:**
- Open the app and check Tracks event for your user. Any event should display the `is_rtl_language`property with the corresponding value (0 if it's a ltr language).
- Change your device language to Arabic and repeat the previous test. it should show 1 for the `is_rtl_language` language.
> Adding is_rtl_language to Tracks

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR re-introduces tracking of uploads in the media library. We inadvertently removed it when switching over to async uploads. 
Now that the user can leave the media library during uploads, the `MediaCoordinator` seems to be the best place to track successful uploads, instead of the media library VC itself (which may not be around when the uploads complete). I've updated the coordinator to allow us to pass in the origin of the uploads (i.e. where the user was when uploading – media library or editor), so that we can report the correct event later.
**To test:**
* Stick a breakpoint in `TracksService.m`, around line 156 (`[self.remote sendBatchOfEvents:jsonEvents`). 
* Perform some uploads in the media library, and log out the `jsonEvents` when the breakpoint is hit – you should see …
> Media Library / Coordinator: Track photo + video uploads w/ origin

- WordPress/Classes/ViewRelated/NUX/FancyAlertViewController+LoginError.swift
- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
In this small PR we're replacing all of the **WPWebViewController** usage with **SFSafariViewController**. We're doing so because:
- In these points, there is no need for wpcom authentication
- This will definitely help us split the Login Flow into it's own framework
Needs Review: @frosty  
1. Disable the [socialSignup feature here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift#L17)
2. Fresh install > **Create a WordPress Site**
3. Tap over the **Terms of Service** label at the bottom.
Verify that SFSafariViewController shows up onscreen!
1. Make [this method public](https://github.com/wordpress-mobile/WordPress-iOS/compare/issue/decoupling-auth-flow-from-wpios-mark-3?expand=1#diff-3db241debe86 …
> Decoupling Authentication Flow: Mark III

- WordPress/Classes/ViewRelated/NUX/NUXViewController.swift
Fixes #8642 
This PR adds back the implementation of `presentationController(forPresented presented: UIViewController, presenting: UIViewController?, source: UIViewController) -> UIPresentationController?` which allows `FancyAlertViewController`s in the NUX to have a dimmed background view.
**To test:**
* Start a fresh install of the app, or log out.
* Tap Log In
* Tap "Log in to your site by entering your site address instead"
* Tap "Need help finding your site address?"
* Ensure that the background behind the alert is dimmed, providing contrast against the alert.
> Issue/8642 NUX Fancy Alert Dimming

- WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.xib
[LoginButton was renamed over to NUXButton](https://github.com/wordpress-mobile/WordPress-iOS/commit/bb7cd2284567ee6753f76b46aca7d681d788e865) ~18 days ago, but we've missed two NIB references to `LoginButton`.
Needs Review: @elibud 
Fixes #8652
Thanks in advance Eli!!
1. Fresh Install
2. Log into a self hosted site, that's connected to wpcom via Jetpack. **Do NOT log into dotcom, go via the self hosted sequence!**
3. Open the Notifications Tab
Verify that the `Log In` button looks as expected.
Repeat the same steps as above, but with a self hosted that's **not** connected to Jetpack.
> JetpackLoginViewController: LoginButton > NUXButton

- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Fixes #8627 
This PR updates the logic in the media library to only update the view state (no results view, search bar, navigation items) if the asset count changes (by adding or removing items).
**To test:**
* View the media library for a site that has lots of media.
* Enter Edit mode, and scroll down.
* Ensure that the trash icon doesn't flicker (see original issue) as thumbnails load in.
* Also try adding media to an empty library and check that the no results view is removed, the search bar is added, and the Edit button appears.
* Try removing all media from a library and check that the no results view is added, the search bar is removed, and the Edit button is removed.
> Issue/8627: Fix trash icon flicker in media library

- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Ref #8110 
To test:
- Go to create a site. 
- Verify it shows the new site creation flow.
> Permanently enabling new Site Creation flow.

- WordPress/WordPressShareExtension/ShareExtensionAbstractViewController.swift
- WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
- WordPress/WordPressShareExtension/ShareModularViewController.swift
Fixes #8648 
This PR moves the `verifyAuthCredentials()` function from `ShareExtensionEditorViewController` to `ShareExtensionAbstractViewController` so both the editor _and_ modules VC call it after being launched. The net effect here is that when a logged out user attempts to save a draft, she will see this error and be prompted to log into WPiOS.
**To test:**
With a user logged into WPiOS:
Now log out of WPiOS completely:
@elibud This should be a quick PR...would you mind taking a peek? 😸
> Draft ext: Verify the user is logged in when launched

- WordPress/Classes/ViewRelated/Jetpack/JetpackConnectionWebViewController.swift
**Fixes** #8657 
**To test:**
~If the backend has not been updated yet test that connecting a Jetpack site works properly, if the backend has been updated fake the URL by replacing `https://wordpress.com/log-in` with `https://wordpress.com/log-in/jetpack` ;)~
The backend has been updated to go back to `https://wordpress.com/log-in` so in order to test this you will have to replace `https://wordpress.com/log-in` by `https://wordpress.com/log-in/jetpack` in `func isDotComLogin(url: URL) -> Bool`
> Add support for https://wordpress.com/log-in/jetpack URL

- WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
Fixes #8669.
I didn't manage to get it to reproduce "naturally", but I have a hunch what has to happen.
1) A post you're viewing must have comments disabled.
2) For some reason, the `ReaderPost.commentCount` property must be `nil`.
First one is easy enough to force to happen, I couldn't think of a way to make 2) happen naturally, so I just put 
```
- (NSNumber *)commentCount {
return nil;
}
``` 
in `ReaderPost.m`.
To test: 
Reproduce the steps above, see that it crashed before and doesn't crash after applying this patch.
> ReaderPostCell: fix crash with disabled comments.

- WordPress/Classes/ViewRelated/NUX/LoginPrologueSignupMethodViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginPrologueViewController.swift
- WordPress/Classes/ViewRelated/NUX/NUXButtonView.storyboard
- WordPress/Classes/ViewRelated/NUX/NUXButtonViewController.swift
In some cases the NUXButtons at the bottom of the screen were white when they should be blue. This fixes that.
To test:
- Check out the site creation flow for blue buttons
> Fix: NUX Buttons that are always white

- WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Fixes #8662 
This PR implements self-sizing cells in the Blogs list section
- Run the app in the Simulator
- Open the 'Accessibility Inspector'
- Choose 'Simulator' as the inspector target.
- Go to WPiOS and visit `My Sites` section
- Change font size in the Accessibility Inspector
> BlogListViewController: Implemented self-sizing cells

- WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
Fixes #8666 
This PR implements self-sizing cells in `ReaderFollowedSitesViewController`
To test:
- Run the app in the Simulator
- Open the 'Accessibility Inspector'
- Choose 'Simulator' as the inspector target.
- Visit `ReaderFollowedSitesViewController ` in the app.
- Change font size in the Accessibility Inspector
> ReaderFollowedSitesViewController:  Implemented self-sizing cells

- WordPress/Classes/ViewRelated/Me/ActivityLogViewController.m
- WordPress/Classes/ViewRelated/Me/SupportViewController.m
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
This PR implement self-sizing cells in the following controllers:
- ActivityLogViewController
- SupportViewController
- NotificationSettingsViewController
Fixes #8673 
To test:
- Run the app in the Simulator
- Open the 'Accessibility Inspector'
- Choose 'Simulator' as the inspector target.
- Visit the mentioned sections in the app.
- Change font size in the Accessibility Inspector
> Implemented self-sizing cells in some 'Me' sub-sections

- WordPress/Classes/ViewRelated/NUX/NUXLinkMailViewController.swift
**Fixes** #8681 
This PR adds detection for AppleMail and Gmail, so when the `Open Mail` button is tapped it will only attempt to open either of those apps if it is configured on the device.
**To test:**
There's three different scenarios to test:
1. Apple Mail configured -> Apple Mail should be opened
2. Gmail configured (Apple mail not on the device) -> Gmail should be opened
3. None installed -> An alert should be display requesting the user to check their email
cc: @nheagy
> Add Gmail detection to OpenMail

- WordPress/WordPressDraftActionExtension/MainDraftActionViewController.swift
- WordPress/WordPressShareExtension/ExtensionPresentationController.swift
- WordPress/WordPressShareExtension/ShareModularViewController.swift
Fixes #8646
This PR improves the transitions of the draft extension on iPad. I've made two main changes:
* On iPad, the action extension modular view controller isn't inset within the presenting view controller, so you never see the white background. This particularly fixes the issue in regular size classes, where you could see the white border around the share extension, and gives it a little more space.
* On iPad, I've disabled the transitions when presenting / dismissing the modular VC within the presenting container, so that it just gets shown / dismissed with it, like a regular modal.
**Before:**
**After:**
**To test:**
* Try presenting and dismissing the draft extension in a variety of split sizes on iPad and see if the transition / presentation looks better than before
* Check that …
> Draft extension: Improve show / hide transitions on iPad

- WordPress/Classes/ViewRelated/Me/MeViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginPrologueViewController.swift
- WordPress/Classes/ViewRelated/NUX/NUXButtonView.storyboard
- WordPress/Classes/ViewRelated/NUX/NUXButtonViewController.swift
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticator.swift
**Fixes** #8694 
**To test:**
Do a clean stall of the app and test that:
1. The login/signup initial screen doesn't show the cancel button.
2. After adding a self-hosted site to the app, go to the Me tab and tap on LogIn, there should be a Cancel button available and it should dismiss the flow.
3. That I didn't break anything else.
> Show new flow from Me tab with ability to cancel it

- WordPress/Classes/ViewRelated/Post/PostCardImageCell.xib
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
- WordPress/Classes/ViewRelated/Post/PostCardTextCell.xib
- WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.h
- WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.m
- WordPress/WordPress.xcodeproj/project.pbxproj
This PR extracts the logic for the status label in post list cells into a view model, which will make it easier to add uploading statuses for async. I've also updated the icons and colours for the statuses, to match our latest designs:
Here are how these look in the cells:
Some of the states aren't in there yet as they're currently not supported. They'll be added as we add async support later.
I've also taken this opportunity to add a progress view to the bottom of the cell, which will be used when uploading posts / media, but it's currently hidden by default. 
**To test:**
* Check I've converted the logic correctly!
* If you want, you can either create posts of these different types (create a local post with no internet connection, schedule a post, mark a post as pending, trash a post), …
> Update Post Cell Statuses + Add Progress View

- WordPress/Classes/Services/BlogService.m
The algorithm was calculating a list of blog IDs to be removed, but then it was trying to match those with the xmlrpc URL 🤦
Fixes #8605 
To test:
1. Connect any Jetpack site (e.g. created with jurassic.ninja)
2. Disconnect that site
3. Check your sites list, make sure the site is gone
> Fix mergeBlogs to match deleted blogs

- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupEmailViewController.swift
**Ref:** #8109 
**To test:**
- Logout of app if necessary.
- Select 'Log In'.
- Select 'Log in with Google'.
- Select an email account that is _not_ associated with a WordPress.com account.
- On the 'Connected but...' screen, select 'Sign up'.
- Verify it goes to the new signup with email flow, with the email address populated.
cc: @nheagy
> Signup: social login fail ‘Sign up’ option now goes to new flow

- WordPress/Classes/Extensions/Notifications/NotificationBlock+Interface.swift
- WordPress/Classes/Models/Notifications/Notification.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteTableHeaderView.xib
Adopted dynamic types and self-sizing cells in the notifications table.
Fixes #8700 
This fixes just the tableView cells and section header.
The table header view ("what do you think about WordPress?") is not addressed. It's a beast of its own.
The changes necessary where mostly to clear the style cache when the user changes the system font size and change the font/attributes constants to computed properties, so they get new values after the font change.
**Design:**
I chose to use `.subheadline` font for the cells text since it was the most similar to the used before. It's still 1 point bigger for iPhone and 1 point smaller for iPad.
For the same reason I chose `.caption1` for the section header.
**Review**
@iamthomasbishop Would you mind to take a look at the final result?
@jleandroperez …
> NotificationsViewController: self-sizing cells

- WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m
This PR fixes the position of the blog selector button image when restoring the app state from the editor
Fixes #8707 
This could be a UIKit bug (not sure). 
Fixed by changing when the `semanticContentAttribute` is set to flip the layout (and move the button image to the right)
To test:
- Build and run the app in Xcode
- Open the editor
- Exit to the home screen
- Stop the app in Xcode
- Re-run the app
- Blog picker button arrow should be at the right side of the button.
> Fix WPBlogSelectorButton image position

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Implements #8682.
This PR adds multiple progress coordinators to the MediaCoordinator, to separately track uploads for posts vs items uploaded through the media library. This will allow us to handle their completion separately in the future.
**To test:**
* First, ensure that uploads through both the media library and Aztec function as you'd expect, and progress is reported correctly.
* On `develop`, upload some media items in the editor on an iPhone device. When the uploads complete, you'll feel Taptic feedback as a notice is posted to report success. If you exit the editor quickly, you'll see the 'media uploaded' notice still at the bottom of the screen.
* Re-test that same scenario on this branch, and you'll get no feedback and see that no notice is posted in this situation any more as …
> Issue/8682 Separate post vs media library progress in MediaCoordinator

- WordPress/Classes/Stores/PluginStore.swift
- WordPressKit/WordPressKit/PluginServiceRemote.swift
This was delightfully simple to implement, thanks to the Store architecture.
To test:
1. Pick any plugin that's not installed yet 
2. Try to install it
3. Verify that that it'll get automatically enabled and the auto-updates will be enabled too.
> PluginStore: try to enable auto-update and the plugin itself after installation

- Podfile
- Podfile.lock
This PR updates the MediaPicker to 0.27. We were already pointing to the latest commit, but I've now pushed it as a formal release.
> Update Media Picker to 0.27

- WordPress/Classes/Services/LoginFacade.h
- WordPress/Classes/Services/LoginFacade.m
Accidentally stumbled upon a dead method, not being used _anywhere_. Please:
1. Verify WPiOS builds
2. Verify the unit tests stay green
Needs Review: @bummytime 
Sir, may i bug you with a superquick PR?
> LoginFacade: Nuking dead login method

- WordPress/Classes/ViewRelated/NUX/Login.storyboard
- WordPress/Classes/ViewRelated/People/People.storyboard
- WordPress/Classes/ViewRelated/People/PeopleCell.swift
- WordPress/Classes/ViewRelated/People/PeopleRoleBadgeLabel.swift
- WordPress/Classes/ViewRelated/People/PeopleViewController.swift
Fixes part of #7236 (Blog -> People [Dynamic type implemented but cells doesn't resize])
This PR implements self-sizing-cells in `PeopleViewController` and dynamic type in `PeopleRoleBadgeLabel`.
**Design**:
The `usernameLabel` label (@etoledom) now uses the preferred font `.caption2`, since it had the same default size than the one used before.
**To test**:
Run the app in the Simulator
- Open the 'Accessibility Inspector'
- Choose 'Simulator' as the inspector target.
- Visit the mentioned sections in the app.
- Change font size in the Accessibility Inspector
> Fix/7236 Implement self-sizing cells in PeopleViewController

- WordPress/Classes/ViewRelated/NUX/Signup.storyboard
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Fixes #8751
The headers now cover the content that scrolls below them, as in the login epilogue.
To test:
- Sign up for a new account with the new flow
- scroll the content far to the top and ensure the table view header can still be read
> Fix transparent signup epilogue table header

- WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
Fixes #8749 
Not just the display name but also the password field were lost when coming back to the `SignupEpilogueTableViewController` from other controllers.
This PR fixes both issues.
To test:
1. Select the Signup button.
2. Select "Sign up with email."
3. Enter a new email address and tap "Next."
4. Open the mail app and tap the button in the magic link email.
5. On the New Account screen, change your Display Name.
6. Write a password
7. Tap on Username to open the Change Username screen.
8. Tap "Back" (you don't have to make any username changes).
Result: Both Display Name and password should be the same you just wrote, and not go back to the default.
> Fix loss of custom display name and password in SignupEpilogueTableViewController

- WordPress/Classes/ViewRelated/Activity/ActivityListSectionHeaderView.xib
- WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
- WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.xib
**Another step in** #7832 
**To test:**
Check that the activity log feed looks as specified by MT on the v2 design. 
Before | After
-|-
> Activity log: feed design v2

- WordPress/Classes/ViewRelated/NUX/Signup.storyboard
- WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Fixes #8750 
This PR fixes the issue by changing the table view style to `Grouped`. In this way, the section headers and footers won't be sticky.
This was the simplest and fastest solution. If we want to stay being sticky, there are others solutions for that too!
To test:
1. Select the Signup button.
2. Select "Sign up with email."
3. Enter a new email address and tap "Next."
4. Open the mail app and tap the button in the magic link email.
5. On the New Account screen, tap in the Password field to give it focus.
Result: The footer text stays bellow the Password field.
> SignupEpilogueTableViewController password footer overlap

- WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift
Fixes #8777 
This PR fixes a crash when searching for a new Username with a short text, assuming that we don't want to ever hide the search field cell.
cc @elibud
> Username search crash

- WordPress/Classes/ViewRelated/Jetpack/JetpackConnectionWebViewController.swift
The previous code was unnecessarily decoding the parameter, which meant
it would break when the blog title had some escaped characters.
To test:
- Make sure your site title has some punctuation in it (e.g. `Koke's .org Sandbox`)
- Go through the connection flow
- You should not see any error pages
> Fix redirect extraction in connection flow

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/Utility/Analytics/WPAppAnalytics+Media.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPressShared/WordPressShared/Core/Analytics/WPAnalytics.h
Fixes #8714.
This PR moves tracking events for adding photos and videos into `MediaCoordinator`. Previously, Aztec did its own tracking of these events. It also moves the "editorAddedPhoto" / "mediaLibraryAddedPhoto" etc events to be posted just before the upload takes place – previously, we were waiting for a successful result. This is in line with Android, and I think makes sense as we still post a MediaService success / failure event depending on the result.
We needed to pass some extra information forward to the coordinator to track editor events properly (previously we were just passing the 'origin' – media library or editor). I've added a smaller wrapper to handle this, called `MediaAnalyticsInfo`.
**To test:**
* Open up the Tracks live view for your test user, run through each of …
> Issue/8714 Consolidate Media tracking

- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryAccessoryItem.swift
Calypso hides active/inactive status of `automanaged` plug-ins, since their states are somewhat of a implementation detail. We weren't respecting it. Now we are:
@mattmiklic I improvised on the icon to use here (the globe), let me know if you'd prefer something else.
Fixes #8772 (and I'm pretty sure also #8755).
To test:
1. Go to plugin directory
2. Make sure that the `automanaged` plugins (Akismet, JPOP, VP...) now display "Auto-managed" in their status label.
> Plugin Directory: add "auto-managed" status for sites

- WordPress/Classes/Utility/InfoPListTranslator.m
- WordPress/Info.plist
- WordPress/WordPress-Internal-Info.plist
- WordPress/Wordpress-Alpha-Info.plist
As I understood it, we should not be needing this since we have
NSPhotoLibraryUsageDescription already, but we're getting a number of
crashes for privacy violations with this as the reason:
Termination Reason: TCC, This app has crashed because it attempted to
access privacy-sensitive data without a usage description. The app's
Info.plist must contain an NSPhotoLibraryAddUsageDescription key with a
string value explaining to the user how the app uses this data.
Fixes #8795
> Add NSPhotoLibraryAddUsageDescription to Info.plist

- WordPress/Classes/ViewRelated/NUX/Signup.storyboard
- WordPress/Classes/ViewRelated/NUX/SignupEmailViewController.swift
**Fixes** #8748 
**To test:**
Test both from a fresh install and from the Me tab:
1. Try to sign up with an already registered email.
2. Check that you are redirected to the login flow and the email field is pre-filled.
3. Check that you can login with password, magic link and google.
4. Check that canceling the flow works as expected.
@nheagy @ScoutHarris I'm not sure if this is how you would've implemented this one, feel free to commit to this branch with any changes/improvements as you see fit.
> Redirect to login on signup when email is already registered

- WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m
Fixes #8791 
This PR implements a different approach to change the arrow image to the trailing position in the `WPBlogSelectorButton` class.
This approach seems to work better, solving both #8791 and #8707 without the need of workarounds.
**To test for #8791:**
1. Start a new post
2. Look at site selector
2. Open post options
3. Close post options
4. Look at site selector (The arrow must stay in the same trailing position)
**To test for #8707 (avoid regression):**
1. Build and run the app in Xcode
2. Open the editor
3. Exit to the home screen
4. Stop the app in Xcode
5. Re-run the app  (The arrow must stay in the same trailing position)
> Blog selector button arrow

- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
**Fixes** #8352 #8212 and the looping inconsistent part of #8352
This PR adds two things:
- A feed refresh after the site has been followed/unfollowed from the header.
- A header refresh after the site has been followed/unfollowed from any cell on the feed.
**To test:**
1. First check that you can replicate the issues mentioned above in `develop`
2. Then check that you can't on this branch ;)
Note that the updates won't be instant as we are making a network request not faking the update.
@mindgraffiti I think this is a nice PR to get some more Swift exposure.
> Sync reader feed and header after site follow/unfollow

- WordPress/Classes/Utility/WebKitViewController.swift
The previous implementation was adding observers on viewDidLoad, which
meant there were some odd cases where the controller could be
deallocated before the view was loaded, leading to a crash.
Since removeObserver is called on deinit, we are calling addObserver
from init
Fixes #8801 
To test:
- Present a web vc (view site, view reader article,...)
- Notice that the title and progress update as the web page loads.
> Fix crash on WebKitViewController

- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Use an `.alert` style when presenting the retry options on a failed media upload.
Ideally, we'd want to present the popover from the tapped cell, but let's deal with the crash first.
Fixes #8807 
To test:
1. Go to the media library on an iPad
2. Start uploading a picture, then go offline (I turned off wifi while using the simulator)
3. Tap on the thumbnail for the uploading image.
4. The app should show an alert with all the options and not crash
> Fix media retry options on iPad

- MIGRATIONS.md
- WordPress/Classes/Models/Blog+Quota.swift
- WordPress/Classes/Models/Blog.h
- WordPress/Classes/Models/Blog.m
- WordPress/Classes/Services/BlogService.m
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
- WordPress/Classes/ViewRelated/Cells/MediaQuotaCell.swift
- WordPress/Classes/ViewRelated/Cells/MediaQuotaCell.xib
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
- WordPress/Classes/WordPress.xcdatamodeld/WordPress 73.xcdatamodel/contents
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPressKit/WordPressKit/RemoteBlog.h
- WordPressKit/WordPressKit/RemoteBlog.m
Fixes #8814 
This PR adds the following:
- Add the the disk quota values to the CoreData blog entity model
- Updates the quota values by reading them from the WP REST API
- Display the Quota in the Media Library when tapping on the Add media button
- Display the Quota in the Site Settings on the new section Media
Designs where provided by @SylvesterWilmott
To test:
- Open the site settings of a WP.com site add see if Disk Quota is displayed
- Check if on a self-hosted site the quota is not displayed
- Open the media library for the same site
- Tap on +
- Check if the Disk Quota is displayed on the Action Sheet title
- Check if that info is not displayed on a self-hosted site
> Display disk quota info for sites

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #8546 
When WPiOS is backgrounded, we are simply dismissing the input view (`OptionsTableViewController`) to prevent it from being orphaned.
To test: Follow the instructions to repro listed in the issue:
> 1. Create a new post
> 2.  Write some content
> 3. Tap heading, then list, then heading
> 4. Put the app in the background
@koke would you mind checking this out?
> Crasher fix for UIViewControllerHierarchyInconsistency when using OptionsTableViewController as an input view

- WordPress/Classes/ViewRelated/Post/PostCardActionBar.m
**Fixes** #8211 
**To test:**
Check that the More button looks good on RTL and LTR languages 🤦‍♀️ 
| Left to Right  | Right to Left |
-|-
> Fix More button image insets on post list

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Improves the publishing experience by adding a confirmation alert.
Also renames the cancel button within "More".  It's now named "Keep Editing".
Includes some minor code cleanup.
Fixes #6397 
- **Publish confirmation alert**:
- **More button alert**:
**Test 1:**
- Create a new post.
- Write a title and some content.
- Tap publish and make sure there's a confirmation alert as described.
**Test 2:**
- Create a new post.
- Tap X
- When the alert comes up, pick "Save as Draft".
- Make sure the publish confirmation alert does not come up.
**Test 3:**
- Create a new post.
- Tap on "..."
- Make sure the default action is now named "Keep Editing".
> Publish confirmation and other post alert changes.

- WordPress/Classes/Services/SignupService.swift
- WordPress/Classes/ViewRelated/NUX/LoginEpilogueUserInfo.swift
- WordPress/Classes/ViewRelated/NUX/NUXViewController.swift
- WordPress/Classes/ViewRelated/NUX/Signup.storyboard
- WordPress/Classes/ViewRelated/NUX/SignupGoogleViewController.swift
**Fixes** #8775 
In this PR we are adding a check for the `created_account` value when doing a Google SignUp. If it's not a new account the user is logged in and the flow dismissed.
**To test:**
Both from a fresh install and from the Me tab perform the following actions and check that everything behaves as expected.
1. Sign up with a new Google account.
2. Sign up with an existing Google account.
3. Log in with a Google account.
> Dismiss Google sign up flow according to user status

- WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
Fixes #8752 
To test:
1. Create a new WordPress.com account
2. Open the magic link that gets sent
3. Rotate the screen when you're shown a possible username/password
@elibud we may want to just disable rotation as well (no other login screen allows rotation)
But this fix works for now.
> Fixes auto rotate cell configuration

- WordPress/Classes/Extensions/URL+Helpers.swift
- WordPress/Classes/Models/Blog+Quota.swift
- WordPress/Classes/Services/MediaService.h
- WordPress/Classes/Services/MediaService.m
- WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPressKit/WordPressKit/RemoteBlogOptionsHelper.m
Fixes #5077
This PR uses the disk quota information and max file upload size information to check for possible upload errors even before the uploads are started.
To test:
- Try to add a new large media object (big video)to an on site that is reaching the limits of it's disk quota
- Check if upload fails even before up the upload start
- Check if an appropriate error message shows up
- Try start an media upload on site that has a limited max file upload size (self-hosted site with Jetpack)
- Check if upload fails even before up the upload start
- Check if an appropriate error message shows up
> Check available size before uploads

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Tools/NotificationReplyStore.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPress/WordPressTest/NotificationReplyStoreTests.swift
This PR implements a Notification Reply cache, which preserved any entered text for 7 days.
Closes #6003
1. Verify the (new) unit tests are green
2. Launch WPiOS and log into your account
3. Open any Comment-Y Notification
4. Press over the ReplyTextView component
5. Enter some random text
6. Hit back
7. Kill the app, and relaunch
8. Reopen the same notofication opened in (3)
Verify that the Reply Text is pre-populated with the text you've written in (5).
Needs Review: @SergioEstevao 
Sir, may i bug you with a fun review?
> Remembering Notifications Reply Text

- WordPress/Classes/ViewRelated/Me/SupportViewController.h
- WordPress/Classes/ViewRelated/Me/SupportViewController.m
- WordPress/Classes/ViewRelated/NUX/NUXLinkMailViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupGoogleViewController.swift
Ref #8314
To test: Nothing really. This just add two signup SupportSourceTags. If you feel spunky, you could log out the soureTag in `NUXViewControllerBase.displaySupportViewController` to ensure the tag is correct for the Epilogue and waiting for google page (you have to click fast on this one).
> Adding SupportSourceTag for Signup Epilogue and Signup Google pages.

- WordPressKit/WordPressKit/ReaderPostServiceRemote.m
**Fixes** #8393 
This PR adds another level of scanning for featured images on the reader feed to match Calypso's behavior.
**To test:**
Follow `b19y.blog` and check that the post `Lap dog #goldendoodle` from December 23rd has an image in the feed.
Also check that Reader images look reasonable by comparing it to develop or the web.
> Scan featured media for a suitable image on reader

- WordPress/Classes/ViewRelated/NUX/LoginPrologueSignupMethodViewController.swift
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticator.swift
Fixes  #8833
Signup epilogue can no longer rotate. Also found that the signup method selection screen (Email vs. Google) was rotatable, too.
This has likely been a problem with the magic link flow since 2016 😉
To test:
- signup to a new account
- ensure the Email vs Gmail screen can't rotate
- ensure the epilogue screen can't rotate
> Fix two rotatable Signup screens 

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Modifies the editor to have readable margins (as defined by Apple).
- Launch the editor in both iPhone and ipad.
- Create a new post.  Check the margins for the placeholders.
- Type in some content.  Check the margins for the inserted content.
- Rotate the device.
> Readable margins in editor

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Removes a residual line of code that was showing a warning.
Just build and make sure the warning is gone.
> Removes a residual line of code.

- WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib
Fixes #8855 
To test:
Before | After
-|-
> Fix padding for site description

- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
Fixes #8753 
So the original issue was caused because the feedback was triggered in the details view controller, in methods that were only called after the button animations were completed. I've moved the feedback generation forward, so that it happens before the animations.
**To test:**
* From a comment notification, try liking a comment and approving a comment. Check the Taptic feedback happens as soon as you tap the button.
> Notifications: Move comment + approve feedback generation pre-animation

- WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift
- WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.xib
1. Launch WPiOS and log into a dotcom account
2. Open the Notifications tab
3. Open any Notification that allows for Text Entry at the bottom
4. Type some random text in the reply component
Verify that the ReplyTextView doesn't get resized every single time you hit a button.
Closes #8847
Needs Review: @frosty 
Sir, you game for a review?. (Thanks!!!)
> Fixing Shaky ReplyTextView

- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Adds a confirmation alert when publishing from the post list.
Allows the user to go ahead and publish the post, or cancel the operation (default action).
Publish confirmation alert for iPhone:
Publish confirmation alert for iPad:
- Create a new draft post
- Go to the list of posts, pick the "Drafts" filter
- Tap on the publish button for the post you created
- Make sure the alert works as described
> Adds a confirmation alert when publishing from the post list.

- WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupUsernameViewController.swift
Fixes #8866 
To test:
- Create an account.
- On the epilogue, select the username to bring up the username changer.
- Select a username other than the default.
- Return to the epilogue. The username is now the one selected.
- Select the username again.
- Verify:
- The username in the top description is the one just selected (not the default one).
- The selected username is first in the suggestion list and has a checkmark.
- Press 'Continue' on the epilogue.
- Verify the account's username is what you selected.
> Signup Epilogue: Fix username changer issues

- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticator.swift
Fixes #8865 
The username screen now has a blue navbar ✅
To test:
- signup for a new account
- change the username
- ensure the navbar is blue
> Make sure the navbar is blue for username changing screen

- WordPress/Classes/Services/SignupService.swift
This PR brings back one Stat that vanished during `9.4`
**To test:**
1. Check that both email and social sign up fire the `.createdAccount` stat
> Add missing .createdAccount stat

- WordPress/Classes/ViewRelated/NUX/LoginSiteAddressViewController.swift
- WordPressKit/WordPressKit/WordPressOrgXMLRPCApi.swift
- WordPressKit/WordPressKit/WordPressOrgXMLRPCValidator.swift
This PR adds error messages for when access to the xmlrpc endpoit is forbidden or blocked
To test:
- Try to add a self-hosted sites using these addresses:
- `do.wpmt.co/405` (for the blocked error)
- `do.wpmt.co/ddos` (for the forbidden error)
- Any other working self-hosted WP address or non-WP address to be sure nothing is broken
> Extra XMLRPC validator error messages

- WordPress/Classes/System/WordPress-Bridging-Header.h
- WordPress/Classes/ViewRelated/Comments/CommentsViewController+Network.h
- WordPress/Classes/ViewRelated/Comments/CommentsViewController+NetworkAware.swift
- WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/People/PeopleViewController.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
- WordPress/Classes/ViewRelated/System/NetworkAware.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Implements part of #5759 
This PR assumes the rest of PRs open against #5759 will be approved eventually. It takes where the last one ends, and attempts to remove all the boilerplate introduced to present alerts and user facing messages when the network is down.
This is the first step to refresh content when the connection comes back up (which will be implemented in a follow-up PR)
To test:
1. Enter flight mode
2. Navigate the app (Sites,Sites > Pages, Sites > Blog Posts, Sites > Comments, Sites > People, Reader, Notifications)
The diff in this PR, as it is, contains only the effort to remove the aforementioned boilerplate.
Changing the base branch to iOS-5759-better-offline would allow a review of the full implementation of the feature (which has been already reviewed and approved, …
> Better offline messages: Extract boilerplate, and preparation for refreshing content when the connection is back up

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Prevent accidental post deletion by adding a confirmation alert.
Fixes #8798 
The alert was changed from the one proposed in #8798 because post deletion is NOT permanent unless you're deleting a post from the trash.
- Go to the list of published posts for a site
- Tap the trash icon to delete a post
- Make sure a confirmation alert comes up.
- Try the same with deleted posts, make sure the alert mentions the deletion would be permanent.
> Prevent accidental post deletion.

- Podfile
- Podfile.lock
- WordPress/Classes/System/WordPressAppDelegate+Swift.swift
- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/Utility/Logging/WPLogger.h
- WordPress/Classes/Utility/Logging/WPLogger.m
- WordPress/Classes/ViewRelated/Me/SupportViewController.m
Fixes #8876 
This resolves a few things.
1. Bumps CocoaLumberjack to the latest version.
2. Sets logging level on each module's `ddLogLevel` when the app's level is set.
3. Properly persists the "Extra Debug" bool by synchronizing to user defaults.
4. Changes the log level immediately when the "Extra Debug" switch is changed.
To test follow the procedures outlined in the reported issue.
@jleandroperez can you check this over?
> Sets logging level in every module to prevent loss of detail in logs

- WordPress/Classes/Services/SignupService.swift
- WordPressKit/WordPressKit/WordPressComServiceRemote.h
- WordPressKit/WordPressKit/WordPressComServiceRemote.m
Ref #8109 
To test:
Verify you can create a wp account using a Google account.
> Send user’s locale as an endpoint param when creating a Google account.

- WordPress/Classes/Extensions/Notifications/NotificationName+Names.swift
- WordPress/Classes/System/WordPressAppDelegate+Swift.swift
- WordPress/Classes/ViewRelated/Comments/CommentsViewController+Network.h
- WordPress/Classes/ViewRelated/Comments/CommentsViewController+NetworkAware.swift
- WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
- WordPress/Classes/ViewRelated/People/PeopleViewController.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
- WordPress/Classes/ViewRelated/System/NetworkAware.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Implements part of #5759
This is the final PR in the implementation of #5759.
- Changes in Reachability status not also post a Foundation.Notification
- That notification is observed in a protocol extension.
- So that view controller that want to be aware of changes in the network availability only need to implement `NetworkStatusDelegate`
To test:
1. Enter flight mode.
2. Navigate to Reader, Post List, Notifications, People
3. Exit flight mode. Wait for the network connection to be re-established. The content should reload
> Reload content when the network connection is back up

- WordPress/Classes/ViewRelated/Aztec/Helpers/AztecVerificationPromptHelper.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
This PR modifies the ellipsis menu in the editor:
- Adds an editor-mode-toggle button.
- Removes the red coloring from the "Save as Draft" / "Publish Button" (since that's for destructive actions).
- Renames "Options" to "Post Settings".
This PR also re-titles the post's "Options" view controller as "Post Settings".
Example of it in action in iPhone:
Just repeat the steps shown in the GIFs above.
Make sure to test in both iPhone and iPad.
Run the unit tests.
> Adds a mode toggle option to the ellipsis menu.

- WordPress/Classes/ViewRelated/NUX/SignupEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupGoogleViewController.swift
Fixes # n/a
To test: Nothing really. This just adds the `account_create_initiated` track in the new Signup flow.
> Adding `createAccountInitiated` track in for new Signup flow.

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditor.swift
This PR allows the editor to selectively control whether or not the PostPost screen is displayed. For async posting (currently feature flagged for local dev only), we now disable the PostPost flow. It'll be displayed if the user interacts with a Notice that'll be displayed on successful posting.
This PR also moves the debug option for Async Posting to the top of the action sheet, just so it's more out of the way.
**To test:**
* Publish a post normally, and check that the PostPost screen is still displayed
* Publish a post using the async debug option, and ensure that the PostPost screen is _not_ displayed
> Async Posting: Don't show PostPost when performing an async publish

- WordPress/Classes/Services/SignupService.swift
- WordPress/Classes/ViewRelated/NUX/NUXLinkAuthViewController.swift
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationTracker.swift
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticator+Events.swift
The `account_created` was missing from the email signup flow (was only working for Google).
To test:
- create a new account via email (not Google)
- ensure the `account_created` is being send (either via tracks or breakpoint)
> Add account_created event to magic link signup flow

- WordPress/WordPressShareExtension/ShareModularViewController.swift
Title has it. This PR moves the `trackExtensionPosted()` call to immediately after the Publish/Save button is tapped (before the network calls).
Fixes #8917 
@diegoreymendez would you mind taking a quick look?
/cc @kwonye
> Extensions: Fix for tracks event not making it to the server after upload

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Sometimes posts where being published when saving them as drafts.  This PR fixes that.
Fixes #8920 
These steps publish the post in `release/9.6` but should save as Draft normally in this PR:
1. Open the editor.
2. Enter a title and content.
3. Tap the "X" to exit the editor.
4. Select "Save Draft."
Result: The post-publish screen appears and the post is published.
> Fixes a problem with 'Save as Draft' sometimes publishing.

- WordPress/Classes/ViewRelated/Post/AuthorFilterButton.swift
- WordPress/Classes/ViewRelated/Post/AuthorFilterViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/Classes/ViewRelated/System/FilterBar.swift
This PR improves the voiceover support for the new pages / posts list filter bar and author filter button. Previously, Voiceover didn't even recognise the author filter button, so it couldn't be selected. I've added some more helpful descriptions for it, and posted a notification once the user changes the option.
@ctarda As you recently worked on Voiceover improvements, would you mind taking a look at this? If you have any suggestions for how to make it better, please let me know! Thanks!
**To test:**
* With Voiceover enabled, try scrolling through and using the items at the top of the Posts screen. Ensure that items can be interacted with, and make sense using Voiceover.
> Improve Voiceover accessibility for FilterTabBar + Author Filter Button

- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostPostViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Partial implementation of #8713
This PR implements notices for the successful path of async posting. Currently these will be triggered when a post is successfully uploaded using the PostCoordinator. There are different messages shown for posts vs pages and for drafts vs published vs scheduled vs pending review statuses.
**Actions**
* If a post / page is in a state other than 'draft', a **View** action button will be displayed on the notice. Tapping View should show the PostPost view, allowing the post to be shared / edited / viewed.
* If a post / page is in 'draft' state, a **Publish** action button will be displayed on the notice. Tapping Publish should publish the post using the post coordinator.
**To test:**
* Using the new async upload debug option, try the following:
* Publish a post …
> Async Posting: Show Notice on successful posting

- WordPress/Classes/Extensions/WPStyleGuide+Search.swift
- WordPress/Classes/System/WordPressAppDelegate.m
- WordPress/Classes/ViewRelated/Reader/WPStyleGuide+ReaderComments.swift
- WordPressShared/WordPressShared/Core/Views/WPStyleGuide+DynamicType.swift
Looking at Apple/system apps, the navigation bar title won't change its font size when the user selects a different content size category.
The same happens with the search bar text and cancel button
Currently, both elements will adopt the system font size when the view is loaded, but it won't resize when the user changes it. This can create awkward situations like this:
This PR fixes this problem by giving to this elements a fixed font that won't change its size according to content size category, but will assume the size of the default category.
**To reproduce the issue:**
- Open the app
- Change the system font size
- Navigation bar title and search bar text will remain with the previous
- Change tab to reset the font size of those elements
**This PR:**
Following the previous steps, the …
> Fixed font (not changing size) for nav bar title and search bar

- WordPress/Classes/ViewRelated/NUX/SiteCreationDomainsTableViewController.swift
Fixes #n/a
To test:
- Start Site Creation process.
- Enter a Site Title that returns no domain suggestions. (Or hack the code by altering the success block of `service.getDomainSuggestions` in `SiteCreationDomainsTableViewController`.)
- Verify the Search field appears.
- Enter a Site Title that does return domain suggestions. 
- Verify the Search field appears.
> Domain suggestions - always show searchField.

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
Partial implementation of #8713. This PR follows on from #8921, by adding notices for failure cases when either media or posts fail to upload.
Note that the messages differ slightly from the designs, as the circumstances under which uploads can fail are I think a little different to what we first thought. There are two cases in which these failures might be displayed:
1. Media for a post fails to upload. In this case, we haven't yet tried to upload the post, so we can just display a normal media failure notice (except we mention that the post has failed). The retry button on the notice will retry the uploads, which will still be observed by the `PostCoordinator`. If the media uploads then complete, the post coordinator will upload the post as normal.
2. If the media has uploaded, but the …
> Async Posting: Show notices for failed uploads

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
This PR implements check for post status before reopening a pending to upload post.
It introduces checks to see if a Post is pending media upload and if a post being uploaded at the moment.
To test:
- Create a new Post
- Add some media to it
- Exit the editor by selecting the Async Publish option
- Before it uploads the media
- go back inside the post
- insert more media
- Tap Async Publish again.
> Post upload cancel when editing again

- WordPress/Classes/Models/WPAccount+AccountSettings.swift
- WordPress/Classes/Models/WPAccount.h
- WordPress/Classes/Models/WPAccount.m
- WordPress/Classes/System/WordPressAppDelegate+Swift.swift
- WordPress/Classes/ViewRelated/Aztec/Helpers/AztecVerificationPromptHelper.swift
I refactored the emailVerified a bit to use an enum. @jklausa I'm a bit confused by the logic in `AztecVerificationPromptHelper`, does this make sense?
Fixes #8837
> Fix account verification crash when email is missing

- WordPress/Classes/Utility/InteractiveNotificationsManager.swift
- WordPress/Classes/ViewRelated/Post/PostNoticeNavigationCoordinator.swift
- WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
The last part of #8713! This PR follows on from #8935, by showing system notifications for async posting notices that are posted while the app is in the background. I've also extracted some of the navigation logic from the `PostNoticeViewModel` into a new navigation coordinator.
**To test:**
* Start an async post uploading and leave the app. Test the following cases:
* The post uploads successfully. You should see a success notification, which will have a View action (you'll need to interact with the notification to show the action). Tap View to be taken into the app and shown PostPost.
* The post fails to upload. You should see the failure notification with a Retry action. The Retry button should retry the upload in the background.
* Try async saving a draft post, and check you see the …
> Async posting: Add system notifications for upload success / failure

- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryAccessoryItem.swift
This addresses design comment by @mattmiklic left in #8780, which I missed before, but caught when catching up on notifications after my AFK. 
(tl;dr remove the icon for the "automanaged" state and change the text color)
Here's how it looks like now:
To test:
1. Go to plugin directory
2. Verify that the "automanaged" label doesn't have an icon and is in the correct color (grey).
> PluginDirectory: change how "Auto-managed" label is displayed.

- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Pages/Pages.storyboard
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/Classes/ViewRelated/Post/Posts.storyboard
Fixes #8937. The new post status filter bar wasn't showing up at all on iOS 10 due to some difference in the top margin of the superview. I'd prefer a cleaner solution, but after spending a while trying things out I couldn't currently come up with anything better and this needs to be fixed for 9.7. 
There's still a slight issue on iOS 10 when the keyboard appears – the tableview is scrolled ever so slightly too far up. But it's almost not noticeable, and it's still better than no filter bar appearing at all!
**To test:**
* Build and run the app, and check that the filter bar is visible in both the Posts and Pages VCs on both iOS 10 and 11.
* Check that the search bar animates to the top of the screen (and back again when cancelled) as expected.
@jleandroperez Can I trouble you with a …
> Issue/8937 Make post status filter bar visible on iOS 10

- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryViewController.swift
"Fixes" #8741. I tried actually making everything be reasonably fast so this doesn't ever happen, but I couldn't find any easy wins here — and I didn't want to spend too much time on this, so here it goes.
To test:
1. Go to plugin directory.
2. Tap on a item really fast
3. Verify that only one VC is pushed onto the stack
> Don't allow multiple items being pushed in PluginDirectory.

- WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift
Fixes #8746 — there was an issue where a paragraph immediately after a bulleted list had no space between the list and the text. This fixes it.
Quick before: 
and after shots:
To test:
1. Open plugin directory
2. Go to a plugin that has bullet list in description, like Akismet
3. Verify there's a space below the bulleted list.
> Fix list layouting issue in Plugin Details

- WordPress/Classes/ViewRelated/NUX/SiteCreationCategoryTableViewController.swift
Fixes #8947 
To test:
- Change device language to something other than English.
- Start the create site process.
- Verify on the Theme Selection page (Step 2 of 4) the nav bar Back button is translated.
@elibud - would you have a minute to look at this? Thanks!
> Localizing ‘Back’ button text for Theme Selection page.

- WordPress/Classes/Utility/Throttle.swift
- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryViewController.swift
- WordPress/Classes/ViewRelated/Plugins/PluginDirectoryViewModel.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPressKit/WordPressKit/PluginServiceRemote.swift
This is a collection of small fixes and touchups for PD, I felt all of them were small enough to warrant rolling them up in a collective PR, instead of 3 tiny ones.
The biggest change should be fairly invisible, except in bad scenarios — sometimes on slower devices (or simulator when your Mac is under a lot of load) the initial screen of Plugin Directory would freeze for a second or two. This was caused because every `PluginDirectoryEntry` that would get downloaded would trigger a full reload — and on a reasonable internet connection, it would mean we'd call `tableView.reloadData` like 20+ times right after each other. We're now throttling those calls, to avoid the freeze.
There should also no longer be a weird gray gap at the bottom of the Plugin Directory. 
Also — fixes #8789, adding …
> Plugin Directory — small fixes.

- WordPress/Classes/ViewRelated/Post/PostCardImageCell.xib
- WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
- WordPress/Classes/ViewRelated/Post/PostCardTextCell.xib
Fixes #8963 
To test:
- Create a new account in the app.
- Create a new site for your new account.
- Go to My Sites > Blog Posts.
- Verify there is no longer a gap at the top of the post.
To note, the header is hidden when the post is **_not_** `isMultiAuthor`.
@frosty - would you mind please kind sir? (Sorry for the dupe, I messed up the first one.). Also, this is going in `9.7`, so I kept the changes minimal. Please keep that in mind when reviewing. 😄
> Fix the layout when the post header view is hidden.

- WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupUsernameViewController.swift
Fixes #8962
To test:
- Follow the repro steps on #8962 
- Verify the original username is used when re-selected.
@elibud - when you have a moment to review, I'd appreciate it!
> Use original username when reselected.

- WordPress/Classes/Models/AbstractPost+Searchable.swift
- WordPress/Classes/Models/ReaderPost+Searchable.swift
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
- WordPress/Classes/Utility/Spotlight/SearchManager.swift
- WordPress/Classes/Utility/Spotlight/SearchableItem.swift
- WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
- WordPress/Classes/ViewRelated/System/WPTabBarController.m
- WordPress/WordPress.xcodeproj/project.pbxproj
- WordPressShared/WordPressShared/Core/Analytics/WPAnalytics.h
This PR builds on top of the work done in  #8781 by indexing and posts opened in the reader. Unlike post/page indexing we only index posts if the user drills into a specific post (vs. scrolling through a topic tableview). In addition, the reader post `CSSearchableItem` is set to expire after 7 days.
(Note that featured image thumbnails are out of scope for this PR)
Fixes #8785 
Fixes #8786 
**To test:**
_You will want to test this PR on a device because the sim is not reliable when working with spotlight._
Should be straight-forward to test:
1. Open Me -> App Settings and clear the spotlight index
2. Browse around in reader and drill into a few articles. 
3. Search in spotlight for various keywords verifying articles show up
4. Tap on search results and make sure appropriate article …
> Reader post spotlight indexing

- WordPress/Classes/ViewRelated/NUX/Login2FAViewController.swift
We should be slightly more permissive for the formatting of 2FA codes by allowing white space.
This updates our support to match https://github.com/Automattic/wp-calypso/pull/23176
To test:
- ensure normal 2FA codes still work
- ensure typing in a 2FA code with or without a space (such as `123 456`) works
- ensure pasting codes with/without white space works
- ensure that really wrong codes still don't work eg `12as56`; `password`; `😂`
Also tagging @diegoreymendez for release management.
> Allow 2FA codes to have spaces

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR fixes an issue where media progress fails to be reported to Aztec after a post has been saved. The issue seems to be due to a revision being created on save, which means the observers were pointing to an old Post object. This PR updates the MediaCoordinator to always use the post's `original` post when creating or fetching a progress coordinator.
**To test:**
* Open the editor, enter a title / text
* From the `...` menu choose Save as Draft
* Add some images to the post, and check the actual images appear in the post (not placeholders) and that their progress is reported
> MediaCoordinator: Use original posts when observing / reporting progress

- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
This PR pulls the changes from #8986 into `develop`.
**To test:**
* Check all the right changes have been pulled over.
* Same as the original PR:
* Open the editor, enter a title / text
* From the ... menu choose Save as Draft
* Add some images to the post, and check the actual images appear in the post (not placeholders) and that their progress is reported
> MediaCoordinator: Use original posts when observing / reporting progress (develop)

- WordPressComStatsiOS/WordPressComStatsiOS/UI/StatsTableViewController.m
This PR is a proposal to fix the issue #8825. I couldn't reproduce the crash, but I'm pretty sure about what started it:
Updating the `SiteStats.storyboard` to Xcode 8 format.
That change introduced a crash when loading the `StatsTableViewController` that was fixed [in this commit](https://github.com/wordpress-mobile/WordPress-iOS/pull/8576/commits/536225b367da95842a36d76078029727bbc399a5)
That crash is easy to reproduce since that animation is always called at `WPStatsViewController:viewDidLoad`.
All these other crashes are of the same kind:
`attempt to delete section X, but there are only 0 sections before the update`, the difference is that those are called after an API call (and that makes all this weird).
I noticed that all those crashes (reported by users) happen after the user open …
> Adding check to animate table section just if the section exists

- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
This PR updates post cells to show 100% progress while the final part of the upload process (uploading the post itself) is happening. Previously it was showing 0%.
**To test:**
* Upload a post with images, using async
* After the images complete, check the cell progress bar continues to show 100%
> Async Posting: Show 100% progress while a post is uploading

- WordPress/Classes/Utility/ImmuTable.swift
- WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
Part of #7832.
Adds ability to swipe-to-rewind.
To test:
1. Go to activity log
2. Swipe left on a cell that's "rewindable" — i..e has the rewind icon on the right.
3. Verify that it triggers the rewind dialog.
4. Swipe left on a different cell.
5. Verify that it doesn't do anything.
> Activity Log: add swipe action to "Rewind" cells.

- WordPressKit/WordPressKit/AccountServiceRemoteREST.m
Ref #8109
To test:
- Change device language to something other than English.
- Create a new WP account.
- Verify the Reader shows in the correct language.
@elibud , @nheagy - could one of you look at this please?
> Adding device locale to signup email request.

- WordPress/Classes/ViewRelated/Post/Categories/PostCategoriesViewController.m
Fixes #7232, #5905
To test:
On an iPad:
- Go to Site Settings > Default Category.
- Add a new Category. Save.
- Verify the new Category appears in the list.
- Edit a blog post.
- Go to Post Settings > Categories.
- Add a new Category. Save.
- Verify the new Category appears in the list.
@frosty , @koke  - if either of you have a moment for a review I'd appreciate it!
> Reload table after category added.

- WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.swift
- WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.xib
Fixes #8948 
To test:
- Sign into self-hosted site with and without a Jetpack site.
- Verify the setup/login view does not scroll.
- Verify the view renders correctly in portrait and landscape (this was unrelated to the scrolling, but it was overflowing in landscape.)
> Jetpack setup/login: Removed ScrollView, corrected layout for orientations.

- WordPress/Classes/ViewRelated/NUX/SiteCreationCategoryTableViewController.swift
- WordPress/Classes/ViewRelated/NUX/SiteCreationSiteDetailsViewController.swift
- WordPress/Classes/ViewRelated/NUX/SiteCreationThemeSelectionHeaderView.swift
Fixes # n/a (brought up by @elibud on https://github.com/wordpress-mobile/WordPress-iOS/pull/8952)
To test:
Verify in the Site Creation process the step labels for steps 1 - 3 are still uppercase (e.g. STEP 1 OF 4).
> Site Creation: Using `localizedUppercase` for all step labels.

- WordPress/Classes/ViewRelated/Me/MeViewController.swift
This PR prevents the creation of the old `UIAlertController` to show login/signup options when the feature flag `socialSignup` is `true`.
Fixes #9007
To test:
- Follow the steps in the gif.
> Avoid to create an alert controller when presenting LoginPrologueViewController

- README.md
Updates the README noting that authenticating via Google is not supported in dev builds.
> Specify Google Auth is not supported in dev builds

- WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
- WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.xib
Activity Log had some layout issues when displayed on iOS 10. I've changed how the `ActivityTableViewCell` is constrained and added the missing `estimatedRowHeight` needed to make trigger AutoLayout pass for UITableView under iOS 10.
To test:
1. Open Activity Log under iOS 10.
2. Verify that it lays out correctly.
3. Open Activity Log under iOS 11.
4. Verify that it also still lays out correctly.
> ActivityLog: fix layouting issues with iOS 10.

- WordPress/Classes/Utility/Media/MediaExternalExporter.swift
- WordPress/Classes/ViewRelated/Aztec/Stock Photos/AztecMediaPickingCoordinator.swift
- WordPress/Classes/ViewRelated/Aztec/Stock Photos/AztecMoreCoordinatorDelegate.swift
- WordPress/Classes/ViewRelated/Aztec/Stock Photos/MediaPickingContext.swift
- WordPress/Classes/ViewRelated/Aztec/Stock Photos/MediaPickingOptionsDelegate.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Media/CameraCaptureCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryPicker.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryStrings.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
- WordPress/WordPress.xcodeproj/project.pbxproj
Implements part of  #8954
In this PR: 
- Add support for Stock Photos to the Media Library, according to the following flow:
I continued piggybacking on the work we had already done on the media picker. I renamed a bunch of the abstractions that we already had created while developing this feature. Turns out some naming was a bit too specific to Aztec. I am terrible at naming things, good thing there are code reviews.
To test:
1. Select a blog > Media
2. Tap the `+` button
3. Taking a Photo or Video should work
4. Importing from the Photo Library should work
5. Importing from Stock Photos should work (although we have not completely finished the implementation of that side of the UI)
6. Importing from Other apps should also work.
> Implement Stock Photos from Media Library + button

- WordPress/Classes/Models/Blog.m
Activity Log is rolling out to WPCom now. Let's show the menu item in the app for those sites too.
(Note: the entierety of AL is still only enabled for devs/internal builds, so this doesn't affect external users.)
To test:
1. Open the app
2. Select Hogwarts P2 from the site switcher
3. Verify that the "Activity" menu item is there
> Activity Log: enable for sites hosted on WPCom

- WordPress/Classes/ViewRelated/Jetpack/JetpackConnectionWebViewController.swift
- WordPress/Classes/ViewRelated/NUX/Login.storyboard
- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/NUXViewController.swift
- WordPress/Classes/ViewRelated/NUX/Signup.storyboard
Fixes #8949 
With this second PR (first #9012) the login screen will offer the ability to sign up to a new account during the Jetpack setup flow. 
To test:
- ensure that the jetpack setup flow now allows for signing up to a new wpcom account
Review note:
This is a relatively simple change: the button opens the sign up flow. at the end, the notification for successful jetpack login fires and the process completes. Are their any implications I've missed?
cc: @elibud for your reference
> Jetpack signup: show signup flow

- WordPress/Classes/Models/AbstractPost.h
- WordPress/Classes/Models/AbstractPost.m
- WordPress/Classes/Services/MediaCoordinator.swift
- WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
- WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
- WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
- WordPress/Classes/ViewRelated/Post/PostListViewController.swift
- WordPress/Resources/AppImages.xcassets/icon-post-actionbar-more.imageset/Contents.json
Implements #8977. 
This PR implements the updated requirements for #8977:
* Currently uploading pages will be shown in the pages list
* Failed page uploads in the pages list will have red text / `...` icon
* Failed page uploads will have a Retry option in their `...` menu
**To test:**
**Publishing a Page**
* Go to Site Pages, and tap the + in the navigation bar to start creating a page
* Add some text and a few images
* Before the images finish uploading, tap `...` in the editor and choose **Async Publish (Debug)**
* If you see an alert, tap **Publish Now**
* Ensure that you see the new page appear in the pages list under the Published filter
**Saving a Page Draft**
* Perform the same steps, but before you add images to the post go to Post Settings and toggle the status to Published and …
> Issue/8977 Pages List: Show uploading and failed pages

- WordPress/Classes/ViewRelated/NUX/LoginSiteAddressViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupGoogleViewController.swift
- WordPress/Classes/ViewRelated/NUX/SignupViewController.swift
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationTracker.swift
- WordPress/Classes/ViewRelated/NUX/WordPressAuthenticator+Events.swift
In this PR we're simply mapping the new **Signup WPAnalytics** calls via the **WordPressAuthenticator**'s event delegate.
This way, it's up to the Host App to actually track the events (the login library won't have access to **WPAppAnalytics** // **WPAnalytics**.
Please verify the app builds correctly, and the unit tests look green!.
@ScoutHarris may i bug you with a relatively quick review?
> Decoupling Authentication Flow: Mark XIV

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes part of #8954 
This PR prevents losing the first responder in the text view when the Stock Photos picker is dismissed.
I also removed `stopListeningToNotifications()` from `func showMore(from: FormatBarItem)`, since seems to not affect the crash that we saw previously when dismissing the action sheet.
**To test:**
- Pick and add images to the editor from the Stock Photos library.
- After dismissing the picker, the focus should stay in the text view.
- Test presenting and dismissing the action sheet and the picker many times to be sure that the crash is still not present.
> Added second check to rememberFirstResponder()

- WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosDataSource.swift
- WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosPicker.swift
Fixes parts of #8954 
This PR implement the following improvements:
- Open Stock Photos with the keyboard present.
- Dismiss the keyboard when selecting/deselecting images.
- Clear last search when dismissing the picker.
- Better keyboard animation when dismissing the picker.
- Clear search when cancel search button is pressed.
To test:
- Start a new post.
- Add photos using Stock Photos.
- Test the previews improvements.
> Stock photos UX fixes

- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
- WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
- WordPress/WordPressTest/PostEditorStateTests.swift
Fixes an issue that was causing the main action button of the editor to mismatch the post status.
The reason we were having problems is that the logic that turns future posts into scheduled posts inside `PostEditorState` had no mechanism to update the actual post status.  This resulted in the post still showing as draft in the post settings window, if the date was changed before the status was.
This PR also removes some of the code to simplify the state management of the main editor publish action.
Setting a post's status to "Pending review" set the post as draft in my case.  I'm not sure what the rationale behind that option is, but it may need to be restricted to a few specific use-cases.
Test creating a post, saving as draft, publishing, scheduling, etc.
Test in a blog where you don't …
> Simplifies and fixes post state logic.

- WordPress/Classes/ViewRelated/NUX/SiteCreationThemeSelectionCell.swift
- WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockImageTableViewCell.swift
- WordPress/Classes/ViewRelated/Themes/ThemeBrowserCell.swift
- WordPressUI/WordPressUI/Extensions/UIImageView+Networking.swift
I've found few issues in the *UIImageView+Networking* extension (which is now part of WordPressUI, and hits NSURLSession, directly):
- ObjectiveC's Object Association was broken / malfunctioning. You've got to pass the pointer!
- Added a failsafe: upon completion we make sure the image we're about to set is the one we should (`response?.url == self?.downloadURL`)
- Updated the 'onSuccess' behavior. Now, by default, we'll always set the image, and hit the callback.
@diegoreymendez Maaaay i bug you with this one?
(Thanks in advance!!!)
1. Verify the Gravatars in the Notifications List show up correctly
2. Verify your Site's Blavatars (My Sites Tab) show up fine!
3. Verify that your gravatar shows up as expected (Me Tab), and that you look as pretty as ever
> UIImageView+Networking: Few Bugfixes!

- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Fixes #9025 , as suggested, by:
1. AbstractPostListViewController should only display an alert if it's topmost
2. It should only attempt to display an alert if the refresh was user initiated. We should pass a parameter to the refresh method to indicate whether the refresh was caused by the user (pull to refresh) – only in that situation should we display the alert.
To test:
Navigate to the Post list
1. Start composing a post.
2. Turn on airplane mode. There should be one and only one alert.
It should be possible to compose a post and save it as draft (locally)
First discussion here: #9038
> Post and Pages List: Do not present network alert when composing posts / pages

- WordPress/Classes/Extensions/UIImage+Assets.swift
- WordPress/Classes/Extensions/UIImageView+Gravatar.swift
- WordPress/Classes/System/Constants.h
- WordPress/Classes/System/Constants.m
- WordPressUI/WordPressUI/Extensions/UIImageView+Networking.swift
In this PR we're replacing AFNetworking usage (in our UIImageView+Gravatar extension) with the new UIImageView+Networking.
This is a multi-staged approach to move UIImageView+Gravatar over to WordPressUI (required by the upcoming WordPressAuthentication.framework).
**Plus** we're updating UIImageView+Networking's callback sequence:
- **Before**: the placeholder would be set, and if the URL was the same, nothing else would have happened.
- **Now**: we only check if the URL differs before firing a new Networking request. This effectively prevents a UI glitch we've seen around!
1. Open the Notifications List. 
Try scrolling upwards / downwards. Verify nothing odd happens, and the gravatar(s) load correctly.
1. Press `Me`
2. Upload a new Gravatar
3. Try scrolling the gravatar offscreen (so …
> Gravatar: Wiring our new Image Downloader

- WordPress/Classes/Services/PostCoordinator.swift
- WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
- WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
- WordPress/Classes/ViewRelated/Post/PostListFilter.swift
Fixes #8976.
This PR removes the feature flag for async posting, and switches over most of the UI uploading actions to use the new asynchronous methods:
* Tapping Publish or Schedule on a draft in the Posts / Pages list.
* Starting a new post, adding some content, then tapping Publish in the navigation bar.
* Starting a new post, adding some content, then tapping the X and choosing Save Draft.
* Publishing an existing draft using the Publish Now quick action in the `...` menu.
These will all post asynchronously whether or not the post has media uploading or not. If there is media, the post will be uploaded once media completes.
Here's a couple of gifs of these in action:
There are a few cases where we're currently still using synchronous posting, due to complexities with revisions. I'd …
> Issue/8978 Async Feature Flag Removal

- WordPress/Classes/Categories/NSAttributedString+Util.h
- WordPress/Classes/Categories/NSAttributedString+Util.m
- WordPressUI/WordPressUI.xcodeproj/project.pbxproj
- WordPressUI/WordPressUI/Extensions/NSMutableAttributedString+Helpers.swift
In this (super small PR) we're moving a NSAttributedString method over to WordPressUI.
RE: WordPressAuthenticator.
Please: Verify the app builds correctly. Minor change!
@frosty can i bug you with a really quick PR?
> New NSAttributedString Swift Extension

- Podfile
- Podfile.lock
- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
Fixes #7447
To test:
- Set a breakpoint in TracksServiceRemote to log when Tracks is sending events
- Do some stuff in the app
- Go to Me > App Settings and disable "Send Statistics"
- Put the app in the background
- Ensure no Tracks events are sent after the setting is disabled
> Ensure tracks doesn't send events if user opts out

- WordPress/Classes/Stores/PluginStore.swift
- WordPress/Classes/ViewRelated/NUX/SiteCreationCreateSiteViewController.swift
- WordPress/WordPressShareExtension/ShareModularViewController.swift
Fixes #8831
Two questions for validators;
1. There were many incorrect instances of 'succesfully' throughout in comments and a variable name, I left them unchanged but can go through and correct them all. They can be seen here;
https://github.com/wordpress-mobile/WordPress-iOS/search?p=1&q=Succesfully&type=Code&utf8=%E2%9C%93
2. There were many three dots cases instead of ellipsis', I only went to change these as I found in translating most of the new strings were using the ellipsis character. For consistentcy what's preferred? I can go back through and revert or go and replace all cases of the three dots with ellipsis.
For instance they're strewn throughout these files;
https://github.com/garrett-eclipse/WordPress-iOS/blob/issue/8831-strings/WordPress/Classes/ViewRelated/NUX/SiteCreationC …
> Fixed Strings

- WordPress.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
- WordPress/Classes/ViewRelated/Post/PostEditorState.swift
Fixes a high-priority bug that was causing private posts to be published as public.
See [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/8989).
The other [post status changes](https://github.com/wordpress-mobile/WordPress-iOS/pull/9057) are not necessary in 9.7 because it fixes issues only present in 9.8.
1. Create a new post.
2. Set it's visibility to private.
3. Publish it.
4. Check the post is private.
5. Edit the post and make it public.
6. Publish and check the status again.
7. Play with the visibility.
NOTE: this PR is intentionally very specific, since it's going to be included in 9.7.1 for direct release to the App store.
> Fixes private publishing.

- WordPress/Classes/ViewRelated/NUX/Login2FAViewController.swift
I've been finding a proper solution to this... but ended up with a compromise one.
**SVProgressHUD**'s category, implemented in ObjectiveC, brings the method `showDismissibleSuccess` to the table. This is used in the whole app, quite extensively. However: the Authentication flow only calls that method in a single spot.
I've analyzed the following alternatives:
- Moving the category over to WordPressUI. Disregarded, because that means a third party dependency to a framework that was meant to be... pristine?
- Moving the category over to WordPressShared. Felt... definitely wrong.
- Duplicating the code (keeping a copy of `SVProgressHUD+Dismiss.{h, m}` in the Authenticator) doesn't feel good either.
Ultimately, i figured we can simply alter the way the HUD is used. `SMS Sent` is meant to be …
> Decoupling Authentication Flow: Mark XXIV

- WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
This is a small change for developers to make it easier to keep track of our analytics events.
During the development of login and social signup several analytics events were missed or modified in annoying ways. Also, during the development of new features, analytics is often an after thought. This is a simple change to try and help developers both think about analytics earlier, and to make it easier to see how events are currently working.
To test:
- Build and the run the app in Xcode (if you can build it elsewhere, congrats, but I didn't consider that possibility)
- Open the developer console/output window
- Look for blue dots calling attention to analytics events
Asking for a few reviews to find out if this would be considered useful.
> Add tracks events to Xcode console

- WordPressKit/WordPressKit/ReaderSiteServiceRemote.m
> API: Follow request - pass the "source" in the POST url not in the POST body

- Podfile
- Podfile.lock
- WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosPicker.swift
- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
This PR implements the update of the MediaPicker-iOS library. This update includes:
- Image Carousel to preview many assets.
- Bottom action bar with a `preview` and an `add` action.
An example video [here](https://www.dropbox.com/s/kf0vo7lj6yrchit/stock_photos.mov?dl=0)
Fixes part of #8954 
**To test:**
1. From the editor:
- Tap the + button over the keyboard.
- Tap the … button.
- Open the `Free Photo Library`.
- Search for kittens (or pizza).
- Play selecting, deselecting, previewing, showing and dismissing the keyboard, etc...
2. Repeat the test from the Media Library:
- From the Media Library, tap the top right `+` button.
- Choose `Free Photo Library`.
- Repeat previous tests.
> Stock Photos: Implementing MediaPicker updates

- WordPressKit/WordPressKitTests/ReaderSiteServiceRemoteTests.swift
This PR fixes a unit test that started failing as a result of changes made in https://github.com/wordpress-mobile/WordPress-iOS/pull/9022. My fault, as I forgot to run unit tests before merging.
The call to follow a site by ID in the Reader originally passed the `source` of the follow as a parameter of the `POST` (where it was being added to the request's JSON body). The PR switched this up to add the `source` to the request's query string. The unit test wasn't expecting this change, so I've updated it to look for the source in the correct place.
There are two force unwraps in there, but neither of those things should ever be nil, and we want the test to fail if they are.
**To test:**
* Build and run tests, ensure they pass.
> Fix a failing test for following sites by ID in the Reader

- WordPress/Classes/ViewRelated/NUX/Login.storyboard
- WordPress/Classes/ViewRelated/NUX/LoginPrologueViewController.swift
This is code cleanup to remove two buttons from the Login prologue that were covered up and not being used anymore. The only noticeable result beyond the code is that the shadow above the button's container is lighter, since before there were actually _two_ shadows on top of one another:
*Code note*:
One of the buttons was the origin for a storyboard segue, which had to be recreated.
To test:
- Logout of all accounts, or use a fresh install, so that the login prologue appears
- Ensure that both login and signup flows still work (that they've started should be enough, no need to test every case)
> Remove unused buttons from login prologue

- Podfile
- Podfile.lock
Ref #9020 
**To test:**
- Do a pod install, build and run the project.
- To verify Zendesk components:
- NOTE: Right now, the new Support view is only accessible if you are logged in with a WP or social account. And only via the navigation bar > Help. (Tip: I usually do Create Site > Help)
- Sign in with a WP/social account.
- Go to the Support page.
- Verify 'WordPress Help Center' shows the FAQ.
- Verify 'Contact Us' displays the new ticket view. 
- Verify 'My Tickets' shows the ticket list view.
**Help Center view:**
**Contact Us view:**
**My Tickets view:**
@etoledom , @jleandroperez - can I bother one of you for a quick review please? Thank you!!
> Update Zendesk pod to 1.11.2.1.

- WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosPlaceholder.swift
- WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosStrings.swift
- WordPressShared/WordPressShared/Core/Views/WPNoResultsView.h
- WordPressShared/WordPressShared/Core/Views/WPNoResultsView.m
Fixes part of #8954 
This PR adds support for attributed text in `WPNoResultsView`'s message label.
Using that, now the Stock Photos `WPNoResultsView` has a tappable link to the Pexel website.
To add tappable links to `UILabel` or even to `UITextField` is fairly complicated, so I decided to replace the `UILabel` with a `UITextView` that already manages opening links by default. In this way the implementation became much simpler.
@bummytime  could you help us to review this?
**To test:**
1. Open Stock Photos (Blog -> Media -> + up right corner -> Free Photo Library).
2. In the `Photos provided by Pexel` message, the `Pexel` word should me highlighted as a link.
3. By tapping the link, it should open the Pexel website.
4. Please inspect the NoResultViews across the app to be sure they are …
> Stock Photos: Add Pexel link to NoResultsView

- WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Fixes #9128. This PR modifies the `UIDocumentPickerViewController` instance presented by the Media Library to accommodate selection of multiple document types.
To test: On an iOS 11 device, complete the following sequence:
- Select a Site.
- Navigate to `Publish/Media : Upload Media : Other Apps`
- Observe that the _Browse_ tab presented in the view controller includes a _Select_ bar button item.
- Validate that multiple selections are added to the Media Library.
Alternatively, review the attached screen shots.
> Media Library: Enable multiple selection for document picker

- WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Fixes #9130. This PR modifies the `UIDocumentPickerViewController` instance presented by Aztec to accommodate selection of multiple document types. A similar change was applied to the [Media Library](https://github.com/wordpress-mobile/WordPress-iOS/pull/9147).
To test: On an iOS 11 device (or Simulator), complete the following sequence:
- Select a Site.
- Navigate to `Publish/Site Pages : Start A Page : + (Add Content) : ... (Present the Document Picker)`
- Observe that the _Browse_ tab presented in the view controller includes a _Select_ bar button item.
- Validate that multiple selections are added to the Media Library.
Alternatively, review the attached screen shot.
> Aztec: Enable multiple selection for document picker

- WordPress/Classes/ViewRelated/NUX/Login.storyboard
- WordPress/Classes/ViewRelated/NUX/LoginEmailViewController.swift
- WordPress/Classes/ViewRelated/NUX/LoginPrologueViewController.swift
- WordPress/Classes/ViewRelated/NUX/NUXViewController.swift
Refs #8883 
In this PR Google can be used to create a new WordPress.com account when setting up Jetpack on a self-hosted site. This is the final part of finishing #8883, bringing the Jetpack flow up to parity with our regular login & signup flow.
To test:
- You'll need a self-hosted site that isn't yet setup with Jetpack.
- You also need a Google account that doesn't yet have a wpcom account.
- Then you login to the self-hosted site in the app
- Then go to Stats and initiate the Jetpack setup process
- When able, use Google to setup a new account
- That was fun. Let's never do it again 😜 
Hey @jleandroperez and @elibud can one of you review in time for 9.9? MUCH THANKS ❤️
> Add Google signup to jetpack signup

- WordPress/Classes/ViewRelated/System/FancyAlertViewController+Async.swift
This PR updates the URL launched from the "How does it work?" link in the async promo displayed in Aztec. It also updates the promo logic so that the promo alert itself isn't dismissed when the safari view controller is displayed.
**To test:**
* Either test with a fresh install, or modify the `if` statement at the end of `publishPost(action:dismissWhenDone:analyticsStat:)` in `AztecPostViewController` so that `promoBlock()` is always called (You can just replace `if !UserDefaults.standard.asyncPromoWasDisplayed {` with `if true {`).
* Verify that the "How does it work?" link takes you to en.blog.
* Verify that after closing the web view controller that the promo alert is still visible.
> Update Async Promo link for release
