wordpress-mobile/WordPress-iOS

WordPress/Classes/Utility/Scheduler.swift
WordPress/Classes/Utility/Throttle.swift
WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosDataSource.swift

Implements part of #8954 
Fixes a bug when deleting a preexisting search term, character by character, until all characters were removed. After a second, a new search request containing the last character removed will be performed. It will be easy to understand with one example.
0. Launch Stock Photos
1. Search for "car" (without quotes)
2. Wait until the search results are populated
3. Delete characters one by one.
4. After deleting the "c", the "no results" placeholder will be presented
5. Wait for a second
6. A new search will be triggered, and some results will be presented (corresponding to the letter c)
To test:
Follow the instructions in the bug description.
After step 4, wait for a couple of seconds. No new searches should be triggered, and the "no results view" should not be …

Stock photos: Cancel previous throttled jobs when the search string is empty

---

WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
WordPress/Classes/ViewRelated/Tools/TimeZoneSelectorViewController.swift

I'm somewhat conflicted if this is the "right" way to fix this — I don't think adding the four lines of code in every view controller ever is exactly a scalable solution. I'm somewhat afraid of rewriting `WPNoResultsView` to use AutoLayout though, especially if there's `NoResultsViewController` coming soon (?). 
I'm leaning towards fixing this where it pops up, and then maybe it would make for a nice HackWeek project to migrate away from `WPNoResultsView`? Totally up for discussion, curious to hear your thoughts!
Fixes #9144.
To test:
1. Open the app on an iPad (or simulator thereof)
2. Cut off your network connection
3. Wait for the empty/error state to appear.
4. Rotate the device to/from landscape
5. Rotate the device back to previous orientation
6. Verify that the content is properly …

ActivityList, TimeZoneSelector: Fix issue where the WPNoResultsView ould be misaligned after rotation.

---

WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift

While reviewing #9161, I noticed that changes to `showDocumentPicker` in `MediaLibraryViewController` didn't seem to be having any effect. It looks as though `showDocumentPicker` was moved to `MediaLibraryMediaPickingCoordinator` as part of the recent stock photos changes, but the original method wasn't removed from `MediaLibraryViewController`. 
The camera capture presentation and processing methods were also still present, so I've removed those too.
This also meant that the stock photos merge removed functionality added in #9147 (multiple selection in the document picker). I've re-added this to `MediaLibraryMediaPickingCoordinator`.
**To test:**
* Check the app builds and runs.
* In the media library, choose + and Other Apps. Ensure you can see the Select button in the navigation bar, …

Media Library: Remove redundant code and reinstate multiple document selection

---

WordPress/Classes/Models/Blog+Files.swift
WordPress/Classes/Services/MediaImportService.swift
WordPress/Classes/Services/MediaService.m
WordPress/Classes/Services/MediaThumbnailService.swift
WordPress/Classes/Utility/Media/MediaThumbnailExporter.swift
WordPress/Classes/Utility/Media/MediaURLExporter.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #9129, which requests support for adding additional document types to the _Media Library_ via `UIDocumentPickerViewController`. It accomplishes this with the following changes:
- Leverages an existing property on `Blog` called `allowedFileTypes` to identify the file types associated with the blog's plan.
- Extends `Blog` to translate those file types into corresponding [Uniform Type Identifiers](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_intro/understand_utis_intro.html#//apple_ref/doc/uid/TP40001319-CH201-SW1).
- Enforces `allowedFileTypes` injected into `MediaURLExporter`.
- Defines a new case for `URLExportExpectation`, and propagates support for that.
To test:
- *Manually* attempt to add various files …

Media Library : Allow document types to be selected in the doc picker

---

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/Utility/Spotlight/SearchManager.swift

This simple PR adds some missing analytics to the new spotlight user activity indexing.
ref: #9148 
**To test:**
0. Make sure WPiOS builds and runs.
1. Navigate around the app a little bit (open the main tabs, open app settings, open notification settings)
2. Dismiss the WPiOS and open spotlight search on iOS. Search for things like "WordPress" or "Settings"
3. Verify you are seeing log statments like this in the console:
* `🔵 Tracked: spotlight_search_opened_app, properties: {
via = "org.wordpress.mysites";}`
* `🔵 Tracked: spotlight_search_opened_app, properties: {via = "org.wordpress.notifications";}`
* `🔵 Tracked: spotlight_search_opened_app, properties: {via = "org.wordpress.me.notificationsettings";}`
@diegoreymendez could you take a quick peek at this for me?

Add spotlight user activity analytics

---

WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosPicker.swift

Fixes #9168 
This PR adds styling to the Stock Photos search bar.
To test from Media Library:
- Go to your favorite blog's Media Library.
- Press the `+` button at the top right.
- Choose `Free Photo Library`.
- Check that the search bar color is the same than the other ones in the app.
Test from editor:
- Open the editor.
- Press the `+` button in the style bar.
- Press the `...` button.
- Choose `Free Photo Library`.
- Check that the search bar color is the same than the other ones in the app.
cc: @diegoreymendez

Stock Photos: Adding WPStyle to search bar

---

WordPress/Classes/System/WordPressAppDelegate.m
WordPress/Classes/ViewRelated/Media/MediaLibraryStrings.swift

Fixes #9186 
- Media library's "Add asset picker": Rename "Device library" option.
- The actions/links on the Free Photo Library action bar should be set in `wordPressBlue`.
To test:
- First point:
- Go to the Media Library.
- Press the `+` button at the top right corner.
- The second option should say: "Choose from My Device".
- Second point:
- From that same picker, choose `Free Photo Library`.
- Search for `car`.
- Select items.
- Check that the color of the buttons in the bottom bar are `wordPressBlue` (like in the screenshot).

Stock Photos design review

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m

Fixes #9178 
The reloading issue was solved internally in the [MediaPicker project](https://github.com/wordpress-mobile/MediaPicker-iOS/pull/290).
This PR adapts the project to the changes made in the Media Picker project to solve the reloading issue. Basically, reloading the Media Library manually after the search phrase has changed.
(The loading indicator is coming soon)
*To test:*
- `pod install`
- Test searching in:
- Blog's Media Library
- Free Photo Library (from `+` butting in the media library)
- Editor: WordPress Media (from `W` in the style bar)
- Editor: Free Photo Library (from `...` button in the style bar)
- Any other media picker with search bar you could think of

Stock Photos: Avoid reload images when typing in search bar

---

WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosDataSource.swift
WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosPicker.swift
WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosPlaceholder.swift

Fixes #9176 
This PR adds a loading indicator to the Stock Photos search query.
This loading indicator was added in the background, so it won't be visible when there are images showing.
To test:
1. Go to My Sites > Blog Posts > +.
2. In the body of the post, go to Add Media > {ellipsis menu} > Free Photo Library.
3. Enter a search term.

Stock Photos: Add loading indicator

---

WordPressUI/WordPressUI/FancyAlert/FancyButton.swift

This fixes some slight clipping for `FancyButton`s, which appear in our fancy alerts (such as site address info screen and [async announcement](https://github.com/wordpress-mobile/WordPress-iOS/pull/8999)).
To test:
- open a fancy alert
- for example, Log In > Log in by entering your site address. > Need help finding…
- ensure the bottom of the buttons aren't cut off

Fix clipping in FancyButton

---

WordPress/Classes/ViewRelated/Aztec/Extensions/URL+LinkNormalization.swift
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/URL+LinkNormalizationTests.swift

Fixes #9197 
This PR makes sure that a link inserted using Aztec follows one of the following conditions:
- Has a scheme (http, https or other)
- Or it's absolute path like: `/example.com`
This mimics the behaviour of the web editor when inserting links.
To test:
- Insert a link using the following format: `www.wordpress.com`
- Switch to HTML mode
- See if the html has the link has: `http://www.wordpress.com`
- Got back to visual mode
- Insert a new link but now write the full URL like: `https://www.wordpress.com`
- Switch to HTML mode add see if the https is preserved

Make sure links inserted on Aztec have a scheme.

---

MIGRATIONS.md
WordPress/Classes/Services/PostService.m
WordPress/Classes/WordPress.xcdatamodeld/WordPress 74.xcdatamodel/contents

Fixes #9182 
I was unable to recreate the original crash, but I could create the Core Data errors. @aerych discovered that the `featuredOnPosts` relationship from `Media` was referencing `Post` objects instead of `AbstractPost`, which could've been causing an issue. I've fixed that in this PR, but it didn't remove the Core Data errors for me. 
The errors seemed to be appearing during the creation / merging of all of the remote pages when they're first loaded, so I looked through the code in `PostService` to see there were any obvious differences between Posts and Pages.
I noticed that in `createPostForBlog`, we call
```
[[ContextManager sharedInstance] obtainPermanentIDForObject:post];
```
after creating the post, before returning. This was added some time ago by @astralbodies, to …

Issue/9182 Fix Page List crash

---

WordPress/Classes/Utility/ZendeskUtils.swift
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift

Fixes #9213 
**NOTES:**
- Your local `.wpcom_app_credentials` must be up-to-date as it contains Zendesk credentials. If you have not, refer to the Field Guide for instructions.
- `SupportSourceTag.inAppFeedback` is not passed on to Zendesk. This will be addressed with a future task that implements SourceTag support.
**To test:**
- Since displaying the App Feedback view is dependent on many conditions, it probably won't just appear. My suggested hack - in `NotificationsViewController:showRatingViewIfApplicable` comment out the first `guard` that checks `shouldPromptForAppReview`. The App Feedback view will _always_ show, but at least you'll see it!
- Go to the Notifications tab.
- Select 'Could Be Better'.
- Select 'Send Feedback'.
- Verify the Zendesk ticket view is displayed.
**Zendesk …

Zendesk Mobile: show Zendesk new ticket from App Ratings > Send Feedback.

---

WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessor.swift
WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorIn.swift
WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorOut.swift
WordPress/Classes/ViewRelated/Aztec/Renderers/CommentAttachmentRenderer.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/Aztec/CalypsoProcessorInTests.swift
WordPress/WordPressTest/Aztec/CalypsoProcessorOutTests.swift

Disables paragraph tag stripping for Gutenberg posts, and hides Gutenberg comment blocks in visual mode (again, because the comment blocks changed it seems).
This won't solve all compatibility issues, but will at least resolve some of them.

Disables paragraph tag stripping for Gutenberg posts.

---

README.md

*Fixes* an issue identified during discussion of #9129.
*To test:* Read documentation and confirm that Markdown renders as expected.

Corrected description of default SwiftLint behavior in project README

---

Podfile
Podfile.lock

@etoledom and @ctarda this PR updates the MediaPicker pod to version 0.28.
This version should have all the contributions that you made to the MediaPicker project included.
Do you mind to give it a look to see if all is ok?
To test:
- Media Library (Scroll around and insert Media)
- Select Media on Post, Site Icon Picker, Featured Image and user Gravatar

Update to media picker 0.28

---

WordPress/Classes/ViewRelated/NUX/SiteCreation.storyboard

I was testing out the site creation flow quite a lot today, and noticed that the Site Title and Site Tagline fields don't do any auto capitalization. This PR makes the following changes:
* The Site Title field will now auto capitalize the first word of each sentence
* The Site Tagline field will now auto capitalize the first word of each sentence
@ScoutHarris Does this makes sense? I wasn't sure if it was the way it was for a specific reason, so please let me know if that's the case!
**To test:**
* Start to create a new site, and on step 3 of 4 check that the capitalization works as described above.

Site Creation: Auto capitalize site title and tagline fields

---

WordPress/Classes/Models/Blog+Quota.swift

Fixes #9237 
This PR add a simple test for the max upload size variable set for the site, if it's set to zero we are assuming some kind of server/api issue and allowing the upload to go forward.
To test:
- There are have been some users sites reporting this, but I wasn't able to reproduce it on my own servers, so the only thing is to see if the uploads are working normally for the regular sites.

If the maxUpload size is zero assume that uploads can go forward.

---

WordPress/Classes/ViewRelated/Post/PostCardImageCell.xib
WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m

Fixes #9244 
This PR is a small improvement in the `PostCardTableViewCell`, removing an unnecessary `UIImageView`.
Now, the same `postCardImageView` property is used to show both still images and animated images.
To test:
- Be sure to have a few blog posts, with gifs and images as `featuredImage`.
- Open the Posts list, scroll around and check that the featured images display properly.

Remove extra image view from PostCardTableViewCell

---

WordPressKit/WordPressKit/JetpackServiceRemote.m

A new site-info endpoint has been added that receives the URL as a query
parameter rather than parts of the path (D11731-code)
This simplifies the API call and is less error-prone.
What was in the path, with `/` -> `::` (slug-style) encoding:
`https://public-api.wordpress.com/rest/v1.1/connect/site-info/https/example.com::site::path`
Is now a query param (no need to think about encoding):
`https://public-api.wordpress.com/rest/v1.1/connect/site-info?url=https%3A//example.com/site/path`
Aligns with https://github.com/Automattic/wp-calypso/pull/24034
The API logic and response are unchanged.
cc: @seear
1. Add a new self-hosted site from the app
1. Enter a URL with a non-WordPress site and verify you're not allowed to continue
1. Enter a WordPress.org site and verify you are allowed to …

API: Update connect/site-info API call

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

This PR ports the changes made on this Aztec PR https://github.com/wordpress-mobile/AztecEditor-iOS/pull/940 to the main app.
This fixes a lot of constraints warning and some scrolling issues we where seeing.
To test:
- Open the Aztec editor with a big post
- Scroll up and down on it and see if everything is work ok.
- Check on phones and tablets on the multiple multitasks mode.

Fix Aztec editor constraints and scrolling issues

---

WordPress/Classes/Extensions/AbstractPost+PostInformation.swift
WordPress/Classes/Extensions/URL+Helpers.swift
WordPress/Classes/Utility/Media/ImageLoader.swift
WordPress/Classes/Utility/Media/MediaLoader.swift
WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #9250 
This PR introduce a new class `MediaLoader`. The intent is to facilitate loading images across the app. Specially those images that could be animated (gifs).
This PR also implements this `MediaLoader` in the `PostCardTableViewCell`, so it can be tested in action in the Posts list.
To test:
- Be sure to have plenty of images/gifs in your blog posts's feature images.
- Open the Blog list and check that all featured images are loading properly.
- Test in a WPcom sites, a self-hosted site and public/private posts.

Image loader

---

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+JetpackPrompt.swift
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift

Fixes #9235
This fixes the issue of the jetpack connection prompt staying on screen even after Jetpack has been connected.
To test:
- login to a self-hosted site
- flip to the notifications tab
- then flip to my sites > stats
- from stats, login to jetpack
- once done, flip back to the notifications tab
- ensure the jetpack prompt is gone
cc: @elibud you touched this code most recently, but I assume you can't do a review anymore… here's a ping FWIW

Hide Jetpack prompt once connected

---

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift

Fixes #9025 
Composing a new post was blocked by the network alert when:
1. Navigate to Me tab
2. Navigate to any of the sections in the Me tab (i.e. Account Settings) (this is the key step)
3. Enter flight mode
4. Start composing a post.
To test:
Attempt to compose a post when flight mode is on. Launch the editor from:
1. Me > My Profile
2. Reader > Followed sites
3. My Site > Blog posts

Fix alerts blocking composing posts when offline

---

WordPressAuthenticator/WordPressAuthenticator/Signin/LoginSiteAddressViewController.swift

Fixes #9263 
This PR reorders the conditionals to restore the prompt previously shown to Jetpack users.
To test:
- You'll need a self-hosted site with Jetpack installed and connected to wpcom. 
- Break the site so it is unreachable to XML-RPC queries.  An easy way is to introduce a syntax error in the site's `xmlrpc.php` file.
- Attempt to log in to the self-hosted blog. 
- Confirm you see the following prompt:
@etoledom or @nheagy could I trouble one of you for a review?

Restores the help nudge for Jetpack users.

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

While editing a post, the caret should be moved when the title has first-responder status and the user press tabs.
Fixes #9273.
The issue description matches the testing steps.

Editor: pressing tab while the caret is in the title moves the caret to the content.

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

This PR disables the `Save for later` feature flag, due to a crash on lunch that is happening when trying to initialize the `NSPersistentStoreCoordinator`. 
(Crashing on file: `ReaderSaveForLaterTopic.swift:17`)
Tested on iOS10.

Save for later: Disabling feature flag.

---

WordPress/Classes/System/WordPressAppDelegate.m

Fixing a bad 9.9 merge!. This PR removes a duplicated WordPressAuthenticator initialization.
1. Clean
2. Fresh install > Launch
Verify nothing breaks violently!
@ScoutHarris may i bug you with a quick check?
Thanks!!

WordPressAppDelegate: Nukes duplicate auth initialization

---

WordPress/Classes/ViewRelated/Tools/SettingsTextViewController.m

Fixes #9302 
Crash was occurring when `SettingsTextViewController`'s  `initWithText:placeholder:hint:` was called from `ReaderMenuViewController.showAddTag()` with a nil text param. This PR adds a simple check in `initWithText:placeholder:hint:` that will replace any nil text params with an empty text string.
1. Open the reader main menu
2. press "Add tag"
3. Verify it doesn't crash
4. Add a tag string and save
5. From the main menu, press "Add tag" again
6. Verify it doesn't crash 😄 
@etoledom Since you were able to repro this crasher, would you mind taking a very quick look at this?
/cc @loremattei

Crasher fix for adding a tag in reader

---

WordPress/Classes/ViewRelated/Post/PostPost.storyboard

This PR fixes the `NUXSubmitButton` Namespace (now that fellow lives in `WordPressAuthenticator`).
**Note:** we should seriously figure out if `NUX*` is worthy of WordPressUI.
1. Fresh Install
2. Log into a dotcom site
3. Post something
4. Press `View` when you get the notice (after a successful post)
- Verify that all of the buttons look cute!
- Verify there's no warning in the console
P.S.: Xcode did change few (unrelated) nib things. Submitting the whole thing... last time i got picky, i ended up breaking everything!!
@frosty THANKS in advance!!!!

Fixing PostPost submit buttons

---

WordPress/Classes/Utility/InteractiveNotificationsManager.swift
WordPress/Classes/Utility/ZendeskUtils.swift

Fixes #9310
**NOTES:** 
- This must be done on a real device as PNs don't work in simulators.
- To view mobile tickets in Zendesk, use the filter noted in this [comment](https://wp.me/p9xubY-6U-p2/#comment-247). 
**To test:**
The alert will only appear if: (this is dictated by ZD PN handling, not the app)
- The app is open.
- A Zendesk view is being displayed (Help Center, Contact Us, or My Tickets).
---
- Go to Support > Contact Us and submit a ticket.
- Select one of the Support options to display a Zendesk view. Leave the app open.
- Go to Zendesk, reply to your ticket.
- Verify an alert is displayed as shown below.
- 'Open' will display the ticket that was updated.
- 'Dismiss' will simply dismiss the alert.
ZD alert:
---
- Do not have a Zendesk view open. Leave the app open.
- Go to …

Zendesk Mobile: show Zendesk notification alert when push notification received.

---

WordPress/Classes/ViewRelated/Cells/PostFeaturedImageCell.h
WordPress/Classes/ViewRelated/Cells/PostFeaturedImageCell.m
WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m

Fixes #9257 
This PR adds gifs animation support in the Post Settings screen.
To test:
- Go to the posts list and select a random post (or start editing a new one)
- Press `...` button at the top right.
- Select `Post Settings`.
- Set / change the featured image to an animated gif.
- Check that uploading images works properly.
- Test saving the changes/publishing/saving as draft/Discarding changes.

Add animated images support in post settings.

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/Post/PostEditorState.swift

Fixes #9224 
To test:
1. Create new post
2. Change its publish options to scheduling
3. Tap on “Schedule” button or attempt to exit
4. Alert action sheet will now display text and title for "schedule" or "publish" according to the `postEditorStatContext`

Fix for confusing publish button and title when scheduling post

---

Podfile
Podfile.lock

Fixes #8794 
This PR updates the Media Picker to version 1.0. that should fix the crashed reported on the issue above.
To test:
- Open the app
- Open the media library of blog, see if loading goes well
- Create a post and add new media to it
- Bonus point to use media that you think it's stored on iCloud storage.

Issue/update media picker to 1.0

---

MIGRATIONS.md
WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
WordPress/Classes/WordPress.xcdatamodeld/WordPress 76.xcdatamodel/contents
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/CoreDataMigrationTests.m

Fixes #9295.
A crash that was previously reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/9182 and fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/9209 [resurfaced](https://github.com/wordpress-mobile/WordPress-iOS/issues/9295) due to (seemingly) a bad merge between two data model updates, which knocked out a fix to the Media entity.
We recently added a relationship to Media for featured images: `featuredOnPost`. The relationship originally referenced `Post` instead of `AbstractPost`, which meant that it couldn't handle Pages, and so caused a crash. 
As a result of the data model merge, we've seen a few instances in local testing where the app has been unable to migrate to the latest model. This PR fixes the relationship, and also adds a test to ensure …

Fixes the Media `featuredOnPosts` relationship

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Blog/SiteIconPickerPresenter.swift

Closes #9300.
This is for tracking parity with Android version.
To test:
Go to site details, observe the console output to verify that the proper items are being printed and perform following steps:
* Tap on the site icon
* Select an image from gallery
* Crop it
* Verify that it uploaded correctly
* Repeat above while offline, verifying that the "upload failed" event is tracked
* Remove a site icon

Tracking for editing Site Icon

---

WordPress/Classes/ViewRelated/Plugins/PluginDirectoryCollectionViewCell.swift
WordPress/Classes/ViewRelated/Plugins/PluginListCell.swift
WordPress/Classes/ViewRelated/Plugins/PluginListRow.swift

Fixes #9345.
To test:
* Go to Plugin Directory (using a JP or AT site (ping me for invite if you don't have one handy))
* Tap on "See All" on the "New" section.
* Wait a second for images to load
* Scroll up and down a bit
* Verify that the cells have the same images as before you scrolled up and down

Plugins: fix cell reuse issue

---

WordPress/Classes/Utility/Ratings/AppRatingsUtility.swift
WordPress/WordPressTest/AppRatingUtilityTests.swift

We want to experiment if frequency of how often we bug people for reviews on the App Store has influence over the ratings themselves. (p2: p5uIfZ-8p6-p2). 
Let's start with changing it to twice/y from up to 3 times/year.

AppRatingsUtility: Change how often we prompt users for reviews.

---

WordPress/Classes/Utility/Analytics/WPAppAnalytics.m

Fixes #9342. 
This PR fixes an issue caused by the recent tracks opt out setting. The way that was implemented resulted in `WPAppAnalytics` calling `registerTrackers` and `beginSession` being called multiple times.
This this PR I've made a few tweaks to prevent that happening:
* In `setUserHasOptedOut`, we now only update the value or start / stop sessions if the value has changed from the existing value we have stored.
* In `initializeOptOutTracking`, we now only set the opt out value itself, and don't start sessions.
* On startup, the sessions should now only be started by `initializeAppTracking`.
**To test:**
* With a fresh install of the app, click "Log In" and check you only see the related analytics event show up in the console once..
* Log into the app and ensure as a logged in …

Issue/9342 Fix multiplied analytics trackers

---

WordPress/Classes/ViewRelated/Cells/PostFeaturedImageCell.h
WordPress/Classes/ViewRelated/Cells/PostFeaturedImageCell.m
WordPress/Classes/ViewRelated/Media/CachedAnimatedImageView.swift
WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.h
WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m
WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m

Fixes #9258 
This PR adds support for animated gifs on the post setting featured image preview, using the additions on `WPImageViewController ` from #9322 .
To test:
1. Open a post with a gif as featured image
2. Press the `...` button at the top right corner.
3. Select `Post Settings`.
4. Scroll down to see the featured image.
5. Tap on the featured image.
6. You should see the animated gif in the preview.
- Test also removing the featured image from the preview.
- Adding static images and gifs.
- Test publishing/discarding changes.
@bummytime can I bother you with a review please? :)

Animated gifs support on post setting featured image preview

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/Utility/Analytics/WPAppAnalytics.m

Fixes #9343.
Note: this relies on https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/131. The hash in `Podfile` now points to the commit in a branch. I'll update _this_ PR with hash pointing to develop once the PR in -iOS-Shared gets merged.
To test:
There are two stages to this. First one is making sure we're not accidentally wiping events on backgrounding:
1. Locate the Tracks database file. My preferred way is stopping the app in debugger, doing `po NSHomeDirectory()` and then `cd`-ing to that path. Tracks database will then be in `Documents/Tracks.sqlite`)
2. Open the database file (either by doing `sqlite3 Documents/Tracks.sqlite` or using your preferred SQLite GUI)
3. Make sure that the app is offline and you haven't opted out of tracking.
4. Perform some activity in the …

WPAppAnalytics: ensure events don't get wiped on app background.

---

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m

Fixes #3898.
Adds pull-to-refresh to list of blogs:
To test:
1. Go to the list of blogs in the app
2. Go to [WP.com on the web](https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs&show=visible) and perform some action that'd be visible in this list, like hiding a blog/making it visible.
3. Pull-to-refresh in the app
4. Verify that the change from the web is reflected in the app

Blog list: add pull-to-refresh.

---

WordPress/Classes/Utility/Media/MediaAssetExporter.swift

Fixes #9329 
This PR fixes an issue where the media upload progress never finishes when exporting a gif file.
It took me a while to figure out to what was the problem until I noticed a difference in the `mediaGlobalProgress` object when exporting static images and gifs.
This is how the `mediaGlobalProgress` object looks like in every progress update:
**Static images**
```
<NSProgress: 0x1c4133240> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 0 of 1  
<NSProgress: 0x1c4128ca0> : Parent: 0x1c4133240 / Fraction completed: 1.0000 / Completed: 25 of 100  
<NSProgress: 0x1c0127800> : Parent: 0x1c4128ca0 / Fraction completed: 1.0000 / Completed: 2592808 of 2592809  
<NSProgress: 0x1c4133240> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 1 of 1  
```
**Gifs** (It always got …

Gif export progress fix

---

Gemfile
Gemfile.lock

We updated `develop` to use Cocoapods to 1.5.2 in #9369. This PR updates the `Gemfile` and `Gemfile.lock` to also use 1.5.2 so `rake` and `bundler` are on the same page.
**Note: You probably want to try the following on a fresh git clone of the WPiOS repo!**
**Clear the decks:**
(If you are using a fresh git clone of the WPiOS repo you can ignore this part)
1. In terminal, `cd` into the WordPress-iOS repo dir
2. Either run `rake clobber` **OR** manually do the following:
* Delete (or temporarily `mv`) the `vendor` dir
* Delete (or temporarily `mv`) the `.bundle` file
* Delete (or temporarily `mv`) the `Pods` dir
**Install stuff and test:**
1. Run `bundle install`
2. Run `rake dependencies`
3. Run `pod install`
4. Run `rake xcode` and then build and run WPiOS.
5. Make sure all the unit …

Updates Gemfile to use cocoapods v1.5.2

---

WordPressAuthenticator/WordPressAuthenticator/NUX/NUXViewControllerBase.swift

Ref #9338 
To test:
Designed position:
Implemented position:
@SylvesterWilmott - can you take a look please? Thanks!

Zendesk Mobile: adjust position of notification alert on navigation bar

---

Podfile
Podfile.lock

This PR updates WordPressUI to Mark 1.0.1.
CC @nheagy || @ScoutHarris 
Thanks in advance (and sorry about breaking this!!!)
Thanks for helping me out @frosty !!!
2. Press `Login`
3. Press `Login by entering your Site's Address`
4. Press `Need Help finding (...)`
Verify nothing blows up.

Updating WordPressUI Reference

---

WordPress/Classes/System/Constants.h
WordPress/Classes/System/Constants.m
WordPress/Classes/Utility/WPImmuTableRows.swift
WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
WordPress/Classes/ViewRelated/Me/PrivacySettingsViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Replaces the analytics opt-out with a dedicated privacy page with more
information and links to the privacy and cookies policies.
@frosty besides a review, I need a bit of help with the UI. According to @folletto's design, the icons should be top-aligned, and the read more links should be left-aligned with the other texts. I'm not sure how to do either, and you might have some ideas 🙏 
Fixes #9359 
To test:
- Go to App Settings > Privacy Settings
- Verify that it matches the design in #9359 
- Make sure the toggle works

New Privacy Settings section

---

WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.xib

Fixes #9382 
This change reorders the buttons in comments action bar to make them in-sync with the order on Calypso.
To test:
- Open "My Sites" tab and move to "Comments" section.
- Open any existing comment. The order of items should be similar to what is shown in Calypso.

Reorder comments action bar items similar to Calypso

---

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m

Fixes #9397.
To test:
Verify that Xcode doesn't complain about UIKit methods being called from non-main threads.

BlogListViewController: fix issues with calling UIKit methods on non-main thread.

---

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift

Refs #9185
This adds a button to the push notification settings if the user ignored the prime for push alert after login.
To test:
- with a fresh install login to a wpcom account
- when the push notification primer appears, tap "Not now"
- go to Me > Notification Settings > Comments on Other Sites > Push Notifications
- ensure that the new button appears
- repeat for the other two scenarios: tapping "Allow notifications" on the alert after login, and then both allowing and denying push notifications

Prime for Push in Settings

---

WordPress/Classes/Services/AccountService.m
WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+PushPrimer.swift

Refs #9185
This enables prime for push features for app store and internal builds.
To test:
- ensure prime for push features still work
- ensure the old, abrupt alert for notifications doesn't appear after login

Enable Prime for Push for everyone

---

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m

When logging out and back in, we were seeing an issue where the system would try and reload a cell in the blog list, even though the data no longer contained any items. This created a crash because we tried to fetch data for an index path that didn't exist.
This was triggered by the call to `layoutIfNeeded` when adding the no results view in `BlogListViewController`. In this PR, we've added a call to refresh the table's data before that happens.
Original stack trace:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Index out of range
...
* frame #8: 0x000000010cd51031 WordPress`BlogListDataSource.blog(indexPath=2 indices, self=0x0000600000322f80) at BlogListDataSource.swift:147
frame #9: 0x000000010cd54611 …
```

BlogList: Fixes a data source issue when switching account

---

WordPress/Classes/Services/ReaderPostService.m

Compose predicates that need to filter out posts not saved for later using a compound predicate
Implements #9409 
To test:
- Delete posts from site with id should work as it used to.

Save for later: Clear up predicates in ReaderPostService

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/Classes/ViewRelated/Reader/Reader.storyboard
WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
WordPress/WordPressTest/ReaderPostCardCellTests.swift

Fixes #9425. This PR updates the Save for Later button in the Reader detail view:
* Adds a title, which is different depending on whether the post is already saved or not
* Updates the icon and tint colors for the various selection states
**To test:**
* Navigate to the detail view for a post in the Reader
* Check that the appearance for the Save button in the bottom right match the illustration above

Reader Detail: Update Save for Later button title / style

---

WordPressAuthenticator/WordPressAuthenticator/Signin/LoginEmailViewController.swift

Fixes #9436
This fixes the crash discovered in 10.0 that affects Google login/signup errors.
To test:
- instructions in #9436

Add bundle to UIStoryboard call

---

Scripts/localize.py

Removes the explicit reference to WordPressKit from `localize.py`since it's now a pod. 
@jleandroperez this one is so tiny...

Removes WordPressKit from the localization script

---

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSiteSubscriptionViewController.swift

Fixes #9441 
To test: Verify strings are properly localized. 
@jleandroperez would you please? :)

Localizes strings vs loalizing a parameter.

---

Podfile
Podfile.lock

This PR fixes an issue where an auto completion of text was being done using smaller or larger text than the original. For example replacing the word Love for the emoji ❤️ .
To test:
Create a new post
Type the word Cheers
Select the word
Activate the emoji keyboard (tap on the globe symbol)
see if on the autocompletion shows an emoji
tap on the autocompletion with the emoji
see if it not crashes.
cc: @loremattei

Updated Aztec to beta 18.2

---

Podfile
Podfile.lock
WordPressAuthenticator/WordPressAuthenticator/Signin/LoginEmailViewController.swift

This PR merges the fixes in 10.0.2 into the release/10.1.
Due to the fact that Aztec editor in 10.1 is newer that the one in 10.0, the branches were not directly mergeable.
What's in this PR:
- merged release/10.0 into release/10.1 -> took Nate's fix, kept 10.1 version of Aztec
- updated Aztec version to Beta-19 (which should be the Aztec in 10.1 + emoji fix).
Please, check it with a lot of care :-) 
cc/ @diegoreymendez @elibud @SergioEstevao

Merge 10.0 into 10.1

---

WordPress/Classes/Utility/ZendeskUtils.swift

Fixes #9446 
Per [this](https://wp.me/p9xubY-cC-p2) discussion, the Zendesk UI colors have been set to:
- primaryTextColor - #2E4453 (Gray Dark)
- secondaryTextColor - #2E4453 (Gray Dark)
- primaryBackgroundColor - #FFFFFF
- secondaryBackgroundColor - #F3F6F8 (Gray Light)
- emptyBackgroundColor - #E9EFF3 (Gray Lighten 30)
- metaTextColor - #668EAA (Gray Darken 10)
- separatorColor - #C8D7E1 (Gray Lighten 20)
- inputFieldTextColor - #2E4453 (Gray Dark)
- inputFieldBackgroundColor - #F3F6F8 (Gray Light)
To test:
- Access the Help Center, Contact Us, and My Tickets.
- Verify the colors are as stated.
**Help Center:**
**New Ticket:**
**Ticket List:**
**Individual Ticket View:**

Zendesk Mobile: customize UI colors

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
WordPress/Classes/ViewRelated/Reader/ReaderSaveForLater+Analytics.swift
WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterAction.swift
WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #9349. 
This PR adds analytics tracking for the Reader Save for Later feature. It's intended to match as closely as possible the Android [events](https://github.com/wordpress-mobile/WordPress-Android/issues/7716) and [tracking](https://github.com/wordpress-mobile/WordPress-Android/pull/7776)
**Notes:** 
* This currently points to a branch of `WordPress-Shared-iOS` with the new events: `add/reader-save-for-later-analytics`. I'll make a new release of the pod before merging this.
There were one or two cases from the Android PR that we can't / don't track here:
*   `READER_POST_SAVED_FROM_SAVED_POST_LIST` – This will be possible once we add a way to undo unsaving a post on the Saved Posts list.
* `READER_SAVED_LIST_VIEWED_FROM_POST_DETAILS_NOTICE` we currently don't trigger the notice …

Reader Save for Later: Adds analytics

---

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift

Fixes #9305 
To test:
1. Load notifications.
2. Turn on Airplane mode.
3. Navigate to one notification detail.
4. Navigate back to the list. There should not be any alerts
5. Pull the notification list down to refresh. There should be an alert (only when there is no network connection)

Notifications: Present network alert only after a manual refresh

---

Podfile
Podfile.lock

Fixes #9296 
At the moment the podfile referece is to a commit but if all it's ok will release a new version of the pod and update to a proper version.
To test:
- Open the app
- Open notifications tab
- Scroll up and down
- Check that all gravatars/icons are correct and assigned to the proper cell.

Update WordPressUI version.

---

WordPressUI/WordPressUI/FancyAlert/FancyAlertView.swift

Fixes #9443.
When FancyAlertView was converted from a UIViewController, the outlet for `titleAccessoryButtonTrailingConstraint` was made weak when it was [previously strong](https://github.com/wordpress-mobile/WordPress-iOS/commit/e243a7ae092cce26a39dd2a5b1be6d5c9a971ea0#diff-b61bca2cc9ab4f4c7b28db5b4d9f022bL112). This meant that when we deactivate the constraint it was getting deallocated. If we then try to apply a new configuration to the fancy alert, we get a crash when we try to configure the now deallocated constraint.
**To test:**
* Update `needsEmailVerification` in `WPAccount` to `return true`
* Log in and open the editor, and add some text
* Tap Publish, then tap Resend on the alert that appears
* Without this patch, the app will crash. With the app, the fancy alert should …

FancyAlertView: Make constraint strong to match previous view controller

---

WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift

Fixes #9454 
This change sets SaveForLater button as visible when it is configured for reuse.
To test:
- Open Reader tab, tap on Discover cell
Case 1:
- Scroll through posts having SaveForLater button and scroll back. The button should still be visible
Case 2:
- Tap on SaveForLater button in any post. The button should still remain visible.

Setting isHidden to false when configuring SaveForLater button.

---

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m

This fixes a warning and also a failing test
To test:
Run the tests in `WordPressTest`

Add missing cases to WPAnalyticsTrackerAutomatticTracks. 

---

WordPress/Classes/ViewRelated/Notifications/Tools/NotificationMediaDownloader.swift

To test:
Make sure the project builds without warnings.
Check that a notification with media downloads as expected.

Update AFNetworking deprecated method

---

README.md

As discussed here https://github.com/wordpress-mobile/WordPress-iOS/pull/9181#issuecomment-385940664, this PR tweaks the SwiftLint section of our README to include a mention of the SwiftLint git hook.
**To test:**
* Read the text, check it's okay!

README: Add mention of SwiftLint git hook

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m

Fixes #n/a
This sets `WordPressShared` to the latest pod version instead of a branch.
To test:
- Pod install.
- Build successfully.

Setting WordPressShared to the latest pod version. 

---

Podfile
Podfile.lock

Fixes #9470 
To test: 
Switch to this branch.
Run `pod install` to update pods.
View a gutenberg post in the reader and confirm it has the correct paragraph spacing.
Needs Review: @frosty would you mind?

Use latest shared pod to fix paragraph spacing for gutenberg posts.

---

WordPress/Classes/Utility/ZendeskUtils.swift

Fixes #9486 
This changes the user information used for Support tickets. Now, when a user access Contact Us or My Tickets for the first time, they are prompted for an email and name.
- If they are logged in, the fields are pre-filled with information from their account or selected site.
- If they are not logged in (i.e. login or signup), the fields will be empty.
Once the user enters their information, it is saved to User Defaults and used for all Support requests going forward, until the app is deleted/reinstalled.
To test:
---
**Tickets:**
- Start with a fresh install (to clear any previous UD information).
- Log in with any account type (WP, self-hosted, etc)
- Go to Support.
- Select Contact Us.
- Verify the alert appears.
- Verify the fields are pre-filled with account information.
- …

Zendesk Mobile: prompt user for Support email and name

---

WordPress/Classes/Utility/ZendeskUtils.swift
WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift

Fixes #9492
When a user first contacts Support they are prompted for an email address and name. That information is used for all future Support requests.
This adds an option on the 'Help & Support' page to allow the user to change the email address used for contacting Support.
NOTE: When you change the Support email address, you will no longer have access to tickets created with the prior email address.
To test:
---
- Start with a fresh install (to clear any previous UD information).
- Log in.
- Go to Help & Support.
- Verify 'Contact Email' is 'not set'.
- Select 'Contact Email'.
- Verify your account email is pre-populated.
- Select 'OK' (you can change the email address if you like).
- Verify 'Contact Email' now shows your email address.
- Select 'Contact Us' or 'My Tickets'.
- Verify …

Zendesk Mobile: allow users to change their Support email

---

Podfile
Podfile.lock
WordPress/Classes/Categories/Media+WPMediaAsset.m
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/Blog/SiteIconPickerPresenter.swift
WordPress/Classes/ViewRelated/Me/GravatarPickerViewController.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryPicker.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m

Fixes #9353 
This PR implements the [changes in the MediaPicker project](https://github.com/wordpress-mobile/MediaPicker-iOS/pull/295) to show a small GIF badge at the top right of the media picker cell.
To test:
Check that the gif badge shows on:

Add GIF badge to media picker

---

WordPress/Classes/Services/ReaderPostService.m
WordPress/Classes/Services/ReaderTopicService.m
WordPress/Classes/ViewRelated/Reader/ReaderCellConfiguration.swift
WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift

Fixes #9488.
Posts that have been saved for later were being deleted whenever their associated topics were deleted. A simple way to trigger this is using search:
* Search for a topic
* Save a post from the results
* Navigate out of the search section of the Reader – this deletes any search topics that were created while searching
* Go to Saved Posts
* Your saved post won't be there, because the topic has been deleted.
To fix this, I've adopted the same approach that we were using to avoid deleting 'in use' posts – if we attempt to delete a topic, we first check for any savedForLater posts that belong to that topic, and `nil` out their topic relationship.
I've also made a tweak to `createOrReplaceFromRemotePost`, so that we can find existing posts with no topic and merge them with remote …

Save for Later: Prevent saved posts being deleted with their topics

---

WordPress/Classes/Models/Blog.m
WordPressAuthenticator/WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
WordPressAuthenticator/WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
WordPressAuthenticator/WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorTests.swift

Fixes #9251
This PR will allow users with IDN (international/non-ascii) domains to login to the app once again.
To test:
- login to a site with an IDN domain or subdomain
- ensure it works

Fix IDN domain login

---

WordPress/Classes/Services/ReaderPostService.h
WordPress/Classes/Services/ReaderPostService.m
WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift

Ideally we’d like to save a user’s saved Reader posts if they log out of the app and then back in with the same account - but we’ll need to work out the right way to detect whether the account has changed. 
At the moment, we never wipe the list of saved posts, no matter who logs in. Until we have a proper solution, we should clear the list of saved posts on log out to prevent users potentially seeing which posts a different user had saved. This PR implements that functionality.
**To test:**
* Log in and save some posts
* Log out and log back in
* Ensure the list of saved posts is empty. Prior to this PR, you’d still see your saved posts.

Reader: Clear saved posts on account change

---

WordPress/Classes/ViewRelated/Me/MeViewController.swift

Fixes #n/a
When the Zendesk views are displayed, `MeViewController` was _always_ used to display them, resulting in: 
`Presenting view controllers on detached view controllers is discouraged <WordPress.MeViewController: 0x7fd4a254cec0>.`
The Zendesk views should only be displayed from the `MeViewController` if the device is an iPad, so they are shown modally.
This adds an iPad check so the Zendesk views are displayed from the correct view controller.
To test:
- Run the app on an iPhone.
- Verify the Support views show correctly (Help Center, Contact Us, My Tickets) - i.e. from the navigation controller.
- Run the app on an iPad
- Verify the Support views show correctly (Help Center, Contact Us, My Tickets) - i.e. modally from `MeViewController`.
- Verify the log message `Presenting view …

Display Zendesk views from correct view controller

---

Podfile
Podfile.lock

Integrates initial Gutenberg compatibility fixes from Aztec.
We fix several issues with Gutenberg compatibility such as:
- Paragraph nodes swallowing comments.
- Gutenberg block delimiters being shown in the editor.
- Gutenberg block delimiters being removable individually in visual mode.
We also added support for the `<cite>` element.
Self-closing Gutenberg blocks are [not supported yet](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/968).
Blockquotes are [splitting up when they should not](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/970).
Load a Gutenberg post and see that our support is compatible with what's described in [this PR](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/962).

Integrates initial Gutenberg compatibility fixes from Aztec.

---

WordPress/Classes/Services/ReaderPostService.m
WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.h
WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.m
WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterRemovedPosts.swift
WordPress/Classes/ViewRelated/Reader/ReaderSavedPostCellActions.swift
WordPress/Classes/ViewRelated/Reader/ReaderSavedPostUndoCell.swift
WordPress/Classes/ViewRelated/Reader/ReaderSavedPostUndoCell.xib
WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Implements #9474 
An early PR to validate the general direction.
Implement removal animation and undo by not actually removing the flag marking `ReaderPost`s a saved for later, but by tracking the post that have been selected for removal, and presenting a cell containing their "collapsed state" (title, and undo button) in their place.
Caveats: 
- The design of the collapsed cell is not final. I run out of time and I wanted to validate the rest of the implementation as soon as possible.
To test:
1. Mark a few posts as saved for later
2. Navigate to Saved Posts
3. Tap the "Save for Later" button (bookmark icon) in a few posts. The posts should collapse.
4. Tap Undo. The post should be visible again
5. Navigate away from Saved Posts. Posts that were "removed" should not be visible anymore …

Save for later: Add 'remove from saved posts' animation

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Fixes #9268. This PR enables the feature flag for Save for Later for all build configurations.
Later, once we've shipped successfully, we can remove the feature flag entirely.
**To test:**
* Smoke test the save for later features – save a post, view all posts, unsave a post

Save for Later: Enable feature flag for all

---

WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib

Fixes #9510. This PR makes a few tweaks to the header views in Reader streams and cards:
* Title and subtitle are now vertically centered against the blavatar (moved up slightly)
* The Follow button is now centered vertically
**To test:**
* View a stream in the Reader. For example, view Discover, and then tap the header of a single card to see the view shown in the screenshot above.
* Check the alignment looks correct.

Reader: Improve item alignment in reader headers

---

WordPress/Classes/Utility/ZendeskUtils.swift

Ref #9492 
This updates the message on the Support email prompt to match Android (https://github.com/wordpress-mobile/WordPress-Android/pull/7829#issuecomment-394301233).
To test:
- Go to Me > Help & Support.
- Select Contact Email.
- Verify the message text is "Please enter your email address.".

Zendesk Mobile: Support email prompt - update text.

---

WordPress/Classes/Services/ShareExtensionService.swift
WordPress/Classes/System/Constants.h
WordPress/Classes/System/Constants.m
WordPress/Classes/System/WordPressAppDelegate+Swift.swift
WordPress/WordPressShareExtension/AppExtensionsService.swift

Fixes #8645 
This PR fixes the site list order in the draft/share extension based on recently used sites in WPiOS. The order of the list should be as follows:
1. Primary site (always displayed even if hidden in WPiOS)
2. Last 3 recently used sites (Can be 0-3 sites)
3. Remaining visible sites in alpha order (excluding sites from 1 and 2 ☝️ )
While testing this, you will probably want to log into WPiOS using a few test accounts (e.g. account with many sites, a single site, a few sites, etc). Basic procedure:
1. With a fresh install of WPiOS, log into the main app.
2. Open Safari and share a page using the app extension
3. On the site list screen, verify the primary site is at the top (pre-selected) and the remaining sites are below it in alphabetical order.
4. Cancel out of the share ext …

Extensions: fixed site list ordering

---

WordPress/Classes/ViewRelated/Comments/CommentViewController.m
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift
WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTextTableViewCell.swift

This PR is actually VERY tiny, but since i was in the neighborhood, i seriously needed to modernize few things:
- Documented several properties
- **NoteBlockCommentTableViewCell** changes:
- *titleLabel* is now clickable
- *refreshDetails* got an improved logic
Ref. #9480
1. Log into WordPress.com
2. Open the Notifications tab
3. Open any Comment-Y notification
4. Verify that the Clickable Area (outlined in the image below) opens the source URL
@nheagy You game for a superquick review?
cc @elibud "Pingback Mark I"

Notifications: Extending Comment's "Source" Clickable Area

---

WordPress/Classes/Utility/WPError.h
WordPress/Classes/Utility/WPError.m

Fixes #9347 
On the 'Unable to Sync' alert, don't show the 'Need Help' button if the internet is unreachable.
To test:
- Start app.
- On the 'Unable to Sync' alert, verify the 'Need Help' button does not appear.

Don’t show ‘Need help’ button on 'Unable to Sync' alert if internet not accessible.

---

WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift

Fixes #9532 
- The new implementation for Gif support was relaying on the html attributes for `height` and `width` to show the final image size.
- For some reason that I couldn't find, some images doesn't have those attributes in their html code, so that information was not available.
- When this happened, the fallback height size was 50pts, and the image got cropped to that size by Photon.
To solve this, there where two changes:
- If the `height` and `width` html attributes are not found, we will search for the `data-orig-size` attribute that seems to be present more often, and get the size from there.
- If the previous still fails, the new fallback value is the screen height, so the image doesn't get cropped by Photon. When the image is available, the `intrinsicContentSize` will give …

Fix issue where images could get cropped on the reader detail

---

WordPress/Classes/ViewRelated/Blog/SiteManagement/DeleteSiteViewController.swift

Fixes #9217 
To test:
- Create a WordPress.com site with a very long site address (or increase the device text size).
- Go to site details > Settings > Delete Site > Delete Site.
- Verify there is no hyphen in the URL.
- Verify the message is `To confirm, please re-enter your site's address before deleting.`.
- Verify the delete button text is `Permanently Delete Site`.

Update delete site alert

---

Podfile
Podfile.lock

Simple PR to update the WordPressUI pod to the last version `1.0.4`.
To test:
- `pod install --repo-update`
- Check that the project builds and run correctly.
cc: @loremattei

Update WordPressUI to 1.0.4

---

WordPress/Classes/Utility/HockeyManager.m

This is related to #9538 and configures the HockeyApp SDK to daily check for updates and to show an update notification to the user when a new build is available.
If the update is not set as mandatory on the server side, the user can choose to update or to ignore the notification. Ignored updates will be re-notified the next day.
**To test**:
The relevant part of the HockeyApp SDK is documented [here](https://hockeyapp.net/help/sdk/ios/5.1.2/Classes/BITUpdateManager.html#/c:objc(cs)BITUpdateManager(im)checkForUpdate). 
Some hacking is required to actually test:
1. _Hack_: change the App internal version to something older than the latest build on HockeyApp (in the _Version.internal.xcconfig_ file);
2. _Hack_: disable the Mandatory Update flag on the server side;
3. Run the app and check …

Sets up hockeyapp daily notifications

---

WordPress/Classes/Models/Notifications/Notification.swift
WordPress/Classes/Models/Notifications/NotificationBlock.swift
WordPress/Classes/Models/Notifications/NotificationBlockGroup.swift
WordPress/Classes/Models/Notifications/NotificationRange.swift

This PR introduces locally generated NotificationBlocks. We should probably hold merging this until we hear back from the Android team (this workaround may not be possible there).
Closes #9479
@frosty would you be game for a (sad, sad, oh very sad) review? (THANKS!!!)
cc @planarvoidoid @elibud 
The actual UX looks slightly different from the one suggested in the mockups. However: this looks 100% exactly the same as the `You replied to this comment` footer, already present in Comment Notifications. @folletto do you think this is acceptable?
Pasting below screenshots for both, this PR and the `You've replied to(...)` UI, already present!.
(Sorry about bugging you sir, introducing a right hand side icon involves a bit of a much bigger change!!).
1. Receive a Pingback Notification
2. Open …

Notifications: Pingbacks Read Source footer

---

WordPress/WordPressDraftActionExtension/Info-Alpha.plist
WordPress/WordPressDraftActionExtension/Info-Internal.plist
WordPress/WordPressDraftActionExtension/Info.plist
WordPress/WordPressShareExtension/Info-Alpha.plist
WordPress/WordPressShareExtension/Info-Internal.plist
WordPress/WordPressShareExtension/Info.plist

We have officially outgrown using the basic extension activation rules in the share/draft extensions because of the need to support more UTIs (like `public.jpeg` in the case of #5642).
So we are "upgrading" to now use the more complex (and not very documented) [predicate syntax 
](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW8). The 3 config `plist` files for each extension now contain 3 groupings of rules all joined by `or` clauses:
```
...
ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.image"
|| ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.png"
|| ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.jpeg"
|| ANY …
```

App extensions now use NSExtensionActivationRule predicates

---

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m

Fixes #9536 
This adds missing checks to verify the `NoResultsViewController` has been instantiated before using it.
Suggestion: it's easier to see this issue if you log into a WP account, then add a self-hosted site. That way, when you remove the self-hosted site, the login screen doesn't appear immediately. And this issue became blatantly obvious.
**To test:**
**Account with no sites:**
- Add a self hosted site.
- Go to My Sites > swipe left > Remove site.
- Verify the No Results View displays correctly.
---
**With all sites hidden:**
- Add a self hosted site.
- Go to My Sites > swipe left > Remove site.
- Verify the No Results View displays correctly.

Check for NoResultsViewController before using it.

---

Gemfile.lock

Afer the changes in #9535, I'm getting a different Gemfile.lock every time I run `rake dependencies`. I'm pushing this and hoping it still works for everyone else. If another environment tries to revert it, we'll investigate further.

Update Gemfile.lock after running rake dependencies

---

WordPress/Classes/Services/AccountService.m
WordPressAuthenticator/WordPressAuthenticator/NUX/NUXLinkAuthViewController.swift
WordPressAuthenticator/WordPressAuthenticator/Signin/LoginViewController.swift

Fixes #9518 
This PR makes sure that analytics meta data is refreshed during account creation via email, and bumps account_created stat after we have the proper account info and meta data is refreshed.
You can confirm the bug by setting a break point in `TracksEventService` ln 61 and inspect the values of `username` and `userID` for when the `account_created` event is dispatched.  Then create a new account.  You should see the username is empty and the userID is a UUID.   With this patch you should see the username as either a wpcom username or an email address, and the userID empty.
To test:
Set a break point as described above.
Sign up for a new account via email.
Confirm the correct values are present.
@ScoutHarris could I trouble you with this one?

Ensures account_created events are not sent as an anon user.

---

WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressShareExtension/AppExtensionsService.swift
WordPress/WordPressShareExtension/RemoteBlog+Capabilities.swift
WordPress/WordPressShareExtension/ShareModularViewController.swift

#Fixes #8621. Is dependent upon [WordPressKit-iOS PR #13](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/13)
cc: @ctarda in case you're interested :)
When a user (whose role is set to `Contributor` on a site) shares media via either share extension (main share activity extension or `Save as Draft`), the background upload silently fails and the post sans media is uploaded anyway. Instead, when a `Contributor` attempts to share some media by using the extension, there should be an alert that appears to tell the user they can't take that action.
1. Ensure you have the WordPress Share activity and the `Save as Draft` options turned on. If you're not sure if you have it, check out **How to turn on `Save as Draft`** at the bottom.
2. On your test website that you'll be sharing to, …

Uploading media via the Share extension silently fails for Contributors

---

WordPress/Classes/Utility/CookieJar.swift
WordPress/Classes/Utility/WPWebViewController.m
WordPress/Classes/Utility/WebKitViewController.swift

Fixes #9396 
This PR fixes the UIBarButtonItem tint color on the `WebKitViewController` when `UIAccessibilityBoldText` is enabled.
**Notes**:
- The issue is a iOS 11 bug where the `UIBarButtonItem.appearance().tintColor` conflict with the tint color of the item instance. This was fixed by re-setting the bar tint color to override the appearance setting.
- Tool bar button items also had this problem, but the color was changing to a darker one.
- There was a thread error in this class. This also was addressed.
- I took the opportunity for a small refactor to organize the code and remove a couple of (harmless) optionals and `!`s.
@koke could you please take a look? :)
To test:
- Go to the system Settings app > General > Accessibility > Bold Text and turn it on. 
- Reopen the WordPress app, …

WebKitViewController nav bar buttons color for accessibility bold text

---

WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift

Fixes #9546 
This PR avoids the deletion of the `Follow` label from the follow button.
@nozomimimi , I noticed that the reason why it wasn't present, is because the label is removed when the card width is less than 480 points, leaving more space for the post title.
For wider screens like the iPhones on landscape or iPads, the label is always present.
This is the difference in the thinest of the screens for iOS (iPhone 5/5S):
If this is OK, let's go for it!
To test:
- Go to the reader.
- Go to a stream that displays the Follow button (i.e. Discover)
- Check that the `Follow` label is present for both `Follow` and `Following` states.

Avoid removing label from follow icon on the reader

---

WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift

Fixes #9551 
This is a simple PR that present the Discover section of the reader as a Site stream, so the `ReaderStreamViewController` shows the header.
I knew this should be simple, but it took me a while to figure out how to do it.
I was[ inspired by Android](https://github.com/wordpress-mobile/WordPress-Android/blob/a25e974142fe0bbf4e9617e996bd49684d2da7e0/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java#L362), where they detect that it's the `Discover` and fetch the site info by ID.
To test:
- Go to the Reader menu.
- Select (to) `Discover`.
- Check that the site header is there.
cc @nozomimimi

Present "Discover" as a site stream

---

WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift

This PR fixes a warning introduced in PR #9526, along with a missing DispatchGroup call:
@ctarda `dispatchGroup.enter()` must be called, always, before the `leave()` instruction. Otherwise, it's analog to closing a door that was never open.
[More here](https://developer.apple.com/documentation/dispatch/dispatchgroup/1452872-leave).
1. Verify the warning is gone
2. Repeat the testing steps detailed in #9526, and verify everything is okay
---
@ctarda please, before merging new code, make **extra sure** no new warnings show up neither in the top or left hand side. Thanks in advance!

Fixing Warning

---

WordPress/Classes/Extensions/Notifications/NotificationBlock+Interface.swift

Fixes #9513, #9514
This removes several kinds of superfluous whitespace that appears in notifications for comments that include mentions or links. It adds a single pass before parsing that replaces these whitespaces with hairline spaces, which are virtually invisible but maintain the length of the source string.
To test:
- have me send you an example problem notification
- ensure that it no longer has the problem whitespace

Remove extra whitespace in the comments of notifications

---

Dangerfile

Closes #9383 
This PR adds a warning to PRs that modify an existing Core Data model instead of creating a new version when inside of a release branch.
I created two test branches and a test PR to run Danger against for this PR. 
To test:
1. Check out this branch.
2. Run `rake dependencies` to ensure Danger is installed.
3. Run `bundle exec danger pr https://github.com/wordpress-mobile/WordPress-iOS/pull/9556`. You should only see a warning about a missing milestone.
4. In Xcode, modify any model version (76, the latest, is good).
5. Run step 3 again. You should see a warning about editing a model in a release branch.
6. Revert your model changes. Added a new model version based off of 76.
7. Run step 3 again. You shouldn't see any warning about the model being modified in a release …

Adds basic Core Data model checks when changing things in a release branch

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift

Ref #9020 
This removes Helpshift related code from NUX View Controllers.
**NOTE**: this is currently pointed at my branch `remove_helpshift_code_nux_view_controllers` on WordPressAuthenticator-iOS for testing purposes. I'll change it back once the pod has been updated.
Associated Authenticator PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/4
To test:
- In the Site Creation flow, verify the notification indicator appears on the nav bar > Help button.
- Hack to show the indicator: in `ZendeskUtils`, return `true` from `showSupportNotificationIndicator`.

Remove Helpshift code from NUX View Controllers

---

WordPress/Classes/Models/AbstractPost.swift
WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
WordPress/Classes/ViewRelated/Post/PostListViewController.swift

This adds a `has_gutenberg_blocks` property to many events related to editing a post, including but not limited to `post_list_button_pressed`, `editor_draft_saved`, `editor_post_scheduled`, `editor_post_published`, `editor_post_updated`, `editor_quick_post_published`, and `editor_quick_draft_saved`.
Fixes #9580 
To test:
Watch Xcode's console for tracks events, you should see the `has_gutenberg_blocks` property with the right value when:
- Opening a post in the editor
- Closing the editor dismissing changes
- Updating a draft
- Publishing a draft

Track whether a post includes Gutenberg blocks

---

Podfile
Podfile.lock

Updates the gifu pod to 3.1.0.
To test: build, ensure animated GIFs still work

Update gifu pod to 3.1.0

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/Utility/InteractiveNotificationsManager.swift

This adds missing analytics events for when the system push notification alert is interacted with. This allows us to better track the results of our push notification primers.
To test:
- use a fresh install. login.
- when the noficication primer appears, allow
- allow or deny push notifications when the system alert appears
- ensure that the correct event appears in the Xcode console
Psst @ScoutHarris @jleandroperez can one of you review this in time for monday's cutoff of 10.3? ❤️

Add new analytics events for OS notification alert

---

Gemfile
Gemfile.lock

In #9592 the cocoapods version got bumped to 1.5.3 in the Podfile.lock file, but the dependency wasn't updated in the Gemfile. As a result, when you ran `rake dependencies` it would change the Podfile.lock back to 1.5.2, leaving you with a dirty checkout.
To test, make sure running `rake dependencies` doesn't change the `Podfile.lock` file.

Update cocoapods to 1.5.3

---

WordPress/Classes/ViewRelated/Aztec/Stock Photos/AztecMediaPickingCoordinator.swift
WordPress/Classes/ViewRelated/Aztec/Stock Photos/MediaPickingOptionsDelegate.swift
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecNavigationController.swift
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj

This PR fixes an ugly  crash in the Posts Editor
Fixes #8995
@etoledom sir, would you be game for a super fun review?
2. Press the `+` button
3. Press the `...` button (navbar top right)
4. Press `Keep Editing`
5. Press the `...` navbar button, again
6. Verify the app doesn't crash!
1. Open Aztec editor.
2. Add an image to the editor.
3. Press the + button on the input accessory view to show the media picker at the bottom.
4. Tap on the image added to the editor to show the image options.
5. Tap on Dismiss.
6. Repeat 4 and 5. Verify the app doesn't crash
1. Open Aztec editor.
2. Tap on the body to activate the accessory input bar.
3. Press + button to open the media picker.
4. Press the ... button on the input accessory bar to show the options of Free …

AztecPostViewController: Preventing UIViewControllerHierarchyInconsistency

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecAttachmentViewController.swift
WordPress/WordPressTest/Posts/PostAttachmentTests.swift

Integrates some additional Aztec / Gutenberg compatibility fixes.
Since these were tested already, we should be good to go.  These are the issues included in this PR.
- https://github.com/wordpress-mobile/AztecEditor-iOS/issues/886
- https://github.com/wordpress-mobile/AztecEditor-iOS/issues/578
Also: `<pre>` multi-line elements are now merged properly.
Fyi @loremattei

Integrates the latest from Aztec.

---

WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift

Fixes #5858 
To test:
- Follow steps on #5858 
- Verify action button title is 'OK'.

Roles: change button text on alert

---

WordPress/WordPressDraftActionExtension/Info-Alpha.plist
WordPress/WordPressDraftActionExtension/Info-Internal.plist
WordPress/WordPressDraftActionExtension/Info.plist
WordPress/WordPressShareExtension/Info-Alpha.plist
WordPress/WordPressShareExtension/Info-Internal.plist
WordPress/WordPressShareExtension/Info.plist

With the updates to the extension activation rules in activation in #9543, we inadvertently added the WPiOS extensions to the login share sheet. The PR fixes that by adding an exclusionary `SUBQUERY` which filters out the 1Password UTIs.
Fixes #9574 
0. Make sure you are logged out of the app
1.  Attempt to login using 1Password
2. Verify the WPiOS extensions do not appear in the login share sheet
Verify the WPiOS app extensions still appear in the share sheet when sharing other things.
@mindgraffiti would you mind taking a look at this? 😄

Extensions: Exclude WPiOS extensions from login share sheet

---

WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift

Fixes what seems to be a bug/oversight in the implementation of #9526 
My brain hurts a little bit every time I need to reason about multithreading, but it seems to me like we should perform all the work associated to a work item within the actual work item (sandwiched in between `enter` and `leave`.
The thing is, I could reproduce the issue described by @alisterscott in the original PR before making the change, I can not reproduce it again after.
The best way to reproduce the bug, for me, was to assign a few tags to the post when uploading images. That seemed to make the association fail pretty often.
To test:
1. Upload an image or two using the share extension
2. Check that the images are associated to the post created when uploading.

When associating posts and images uploaded via share extension, set the postID within the work item

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Media/ImageLoader.swift

This PR updates the WPMediaPicker to version 1.1
To test:
- Open the following sections on the app and see if everything is working ok
- Media Library
- New Post and try to add media to it
- Gravatar picker
- Site icon picker

Update media picker to 1.1

---

WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift

Ref #6504 
Per https://github.com/wordpress-mobile/WordPress-iOS/pull/9544#issuecomment-398621187, the masterbar was still showing when viewing a Page or a Post. This hides the masterbar on Post previews.
As noted on #6504 , the admin bar will still show for self-hosted (non-JP) sites.
To test:

Hide WP masterbar in post previews.

---

WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift

Fixes #9485 
From the discussion on #9485 , the following labels have been updated:
- The clear cache button label is now `Clear Device Media Cache`.
- The `Media` section now has a footer: `Free up storage space on this device by deleting temporary media files. This will not affect the media on your site.`
To test:
Go to Me > App Settings.
Verify the changes in the Media section:

Update 'clear media cache' labelling

---

WordPress/Classes/Services/PostService.h
WordPress/Classes/Services/PostService.m
WordPress/Classes/ViewRelated/Me/MeViewController.swift

This PR implements an improved Logout Text:
- Whenever there are local changes, not persisted in the backend, the Logout Confirmation will read `You have changes to %d posts that haven’t been uploaded to your site. Logging out now will delete those changes. Log out anyway?`
- Whenever there are no local changes, the text will just say `Log out of WordPress?`
This one goes to our friend @sendhil, who filed the issue 3 years + nearly 5 months ago. If you ever get this ping, **WE MISS YOU AROUND!!!**
Closes #3164 
@ScoutHarris may i bug you with a hopefully fun review?. Thanks in advance!!
2. Press the `+` button
3. Type anything! (Title or Body)
4. Dismiss the editor
5. Wait a few seconds, so that the post is sync'ed with our backend
6. Press `Me` > `Logout`
Verify that …

Logout: Let's be friendly!

---

WordPress/Classes/Utility/Logging/CocoaLumberjack.swift
WordPress/Classes/Utility/Logging/CustomLogFormatter.swift
WordPress/Classes/Utility/Logging/WPLogger.m
WordPress/WordPress.xcodeproj/project.pbxproj

Ref #9625 
When the logs are sent to Zendesk, the timestamps were translated to the device language.
In app, the logs would look like:
```
٢٠١٨/٠٦/٢٢ ١٦:٤١:٠٠:٠٧٠  Crash count: 0
٢٠١٨/٠٦/٢٢ ١٦:٤١:٠٠:٠٧٠  Debug mode:  Debug
٢٠١٨/٠٦/٢٢ ١٦:٤١:٠٠:٠٧٠  Extra debug: NO
```
This change sets the log timestamp locale to English so the HEs can read them.
**To test:**
**NOTE**: It is not necessary to actually create a Zendesk ticket. In `ZendeskUtils:getLogFile`, you can log out `logText` to see what is being sent to Zendesk.
- Start with a fresh install (it's easier to see the new logs that way).
- Change your device language to something vastly different than English (for example, Spanish didn't make a difference. Try something like Arabic).
- Go to Me > Help & Support > Contact Us.
- Verify the …

Setting log timestamp locale to English.

---

WordPress/Classes/Utility/ZendeskUtils.swift

Ref #9625 
When the Free Space is sent to Zendesk, it was translated to the device language.
This change sends the Free Space in English.
**To test:**
**NOTE**: It is not necessary to actually create a Zendesk ticket. In `ZendeskUtils:getDeviceFreeSpace`, you can log out the `return` value to see what is being sent to Zendesk.
`print("Free Space: \(formattedCapacity) \(sizeAbbreviation)")`
- Change your device language to something vastly different than English (for example, Spanish didn't make a difference. Try something like Arabic).
- Go to Me > Help & Support > Contact Us.
- Verify the logged Free Space is in English, and is the correct value and format. Ex:
`Free Space: 1.68 TB`

Send Free Space to Zendesk in English.

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

Updates the app to Aztec version 21
This version brings the following fixes:
- Better support for video elements without a poster image defined ( Gutenberg video blocks)
- Improved merging of blocks, solves some issues around pre/blockquote/caption/figure
To test:
- Test the editor with handling of blockquotes, pre and figure
- Test the editor with insertion of videos in Calypso mode (.com and .org) and Gutenberg mode.

Update Aztec to beta 21.

---

Podfile
Podfile.lock

This PR updates the Gridicons pod to the new version 0.16
To test:
- run `pod install` (`--repo-update` might be necessary)
- Check that the project builds and run properly.

Update Gridicons to 0.16

---

WordPress/Classes/Stores/ActivityStore.swift
WordPress/Classes/Stores/StoreContainer.swift
WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Wowee, was that long in the making. I did end up rewriting most of it few times in the meantime because `~turns out~` I made few bad assumptions along the way, but hey. Who doesn't?!
This is part 1 of... at least three, I think. I wanted to break my changes into smaller chunks, so it's easier to review in separation — so this is just the Flux part of it. The new UI part for showing restore status and improved View Model is the next part :)
To test:
1. Go to Activity Log
2. Make sure things still display properly!
3. Try rewinding a site that's semi-disposable, verify that works
4. Throw your hands up in the air like you don't care
Note: there might be some UI weirdness happening around displaying the HUD with status: this shouldn't be considered a blocker, next PR is changing how we deal …

[Activity Log] Implement the Flux ActivityStore.

---

WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib

Fixes a warning in Xcode.
To test:
- build the project and make sure the above warning doesn't appear.

Fix warning in xib

---

WordPress/Classes/Extensions/Array.swift
WordPress/Classes/Models/Blog.m
WordPress/Classes/Stores/ActivityStore.swift
WordPress/Classes/ViewRelated/Activity/ActivityDateFormatting.swift
WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
WordPress/Classes/ViewRelated/Activity/RewindStatusRow.swift
WordPress/Classes/ViewRelated/Activity/RewindStatusTableViewCell.xib
WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift
WordPress/Classes/ViewRelated/Plugins/PluginDirectoryViewModel.swift
WordPress/Classes/ViewRelated/Plugins/PluginListViewModel.swift
WordPress/WordPress.xcodeproj/project.pbxproj

This:
* updates how the AL displays status of a restore currently in progress 
* gets rid of HUD in AL in favor of Notices
* makes sure that we display date/time in site's timezone, not UTC
To test:
* TZ stuff:
*  Make sure that your website is set to a different timezone than UTC
* Go to AL
* Go to any event details
* Verify that the date/time displayed is correct (you can use Calypso to compare if you're not keen on doing TZ math in your head :P)
* Restore status stuff
* Go to AL
* Start a restore
* Verify the notices posted at the bottom of the screen make sense
* Verify that there's a new section at the top of the AL during the restore process
* Verify that the new section displays progress at least somewhat in sync with Calypso (we poll the network much less often than Web does to …

Activity Log: UI updates

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m

This removes the feature flag for Activity Log, shipping it to everyone (as long as their blog is compatible).
(imagine that says "Activity Log", instead of "Bees")
You get Activity Log, you get Activity Log, and YOU!!! get Activity Log!
To test:
Look at the code :)
But if you wanted to test for realsies, I'm actually not sure. Build the app in release configuration and verify that Activity Log is there?

[ActivityLog] Remove the Activity feature flag.

---

WordPress/Classes/Models/Notifications/NotificationSettings.swift
WordPress/Classes/System/WordPressAppDelegate.m
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+PushPrimer.swift
WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
WordPress/Classes/ViewRelated/Reader/ReaderPostMenu.swift
WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
WordPress/Classes/ViewRelated/Themes/ThemeBrowserCell.swift
WordPress/Classes/ViewRelated/Themes/ThemeBrowserHeaderView.swift
WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
WordPress/Classes/ViewRelated/Views/NavigationTitleView.swift
WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift

I've been using Xcode 10 for the past few days and I'm super pleasantly surprised how stable and fast it is.
However, WPiOS throws up few new warnings when building it in Xcode 10. 
This PR fixes it!
To test:
* Build WPiOS in Xcode 10
* Verify that there are no warnings
* Build WPiOS in Xcode 9
* Verify that it still compiles and also doesn't show any warnings.

Fix Xcode 10 warnings.

---

Podfile
Podfile.lock

Fixes #9692
To test:
1. Open the login screen
2. Login and then login by site address
3. Select the need help for finding the site address button
4. Check that the fancy alert pops up and the image is there.

Fix a bundle issue with WPAuth

---

WordPress/Classes/System/WordPressAppDelegate+Swift.swift
WordPress/Classes/System/WordPressAppDelegate.m
WordPress/Classes/Utility/Universal Links/Route.swift
WordPress/Classes/Utility/Universal Links/RouteMatcher.swift
WordPress/Classes/Utility/Universal Links/Routes+Me.swift
WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
WordPress/Classes/ViewRelated/System/WPTabBarController.h
WordPress/Classes/ViewRelated/System/WPTabBarController.m
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/RouteMatcherTests.swift

Implements #9669. This PR adds some basic 'routing' infrastructure to handle universal links, and support for links into the Me section of the app.
3 Me links are supported:
* `/me` -> the root of the Me tab
* `/me/notifications` -> Notification Settings within Me
* `/me/account` -> Account Settings in Me
Tapping one of these links in Safari should direct the user to the appropriate place in the app.
**To test:**
* I'll send you some separate instructions via Slack!

Universal Links: Add basic routing and support for Me section

---

WordPress/Resources/AppStoreStrings.po

Minor translation fix making string en_US base, will become favourite in en_GB, en_CA, en_AU, etc.

Localized favourite to en_US

---

WordPress/Classes/Utility/Universal Links/Routes+Me.swift
WordPress/Classes/Utility/Universal Links/Routes+Notifications.swift
WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
WordPress/Classes/ViewRelated/System/WPTabBarController.h
WordPress/Classes/ViewRelated/System/WPTabBarController.m
WordPress/WordPress.xcodeproj/project.pbxproj

Implements #9668.
This PR follows on from #9702, and adds a universal links route for Notifications:
* `/notifications`
**To test:**
* Same as the previous PR, add an applinks: entry to the Associated Domains capability for the test domain I provided.
* In Safari on your device, open the test page I created and try the Notifications link. Check that the notifications section of the app launches.
Thanks so much for taking a look at these PRs, @etoledom!

Issue/9668 Universal Links: Handle Notifications link

---

WordPress/Classes/ViewRelated/Blog/BlogListViewController.h
WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
WordPress/Classes/ViewRelated/System/WPTabBarController.m

Refs #8807
Our new WordPress.com signup process allows users to use the app without having any blogs. Sadly when on iPad these users can crash the app just by tapping the Write button in the tab bar. This PR fixes that, by presenting the options to create or add a blog, just as on iPhone.
To test:
- on iPad, login with a wpcom user that has no blogs
- tap the Write button
- ensure the app does not crash

Fix crash on iPads for wpcom accounts without any blogs

---

Podfile
Podfile.lock

Fixes #9692 by updating WPAuthenticator to the latest, updated version.
We already tested the fix itself in 10.3 and we're opening a new different PR against this version (instead of merging) because the two releases had different WPAuthenticator versions.
@jleandroperez would you mind a quick review? (btw: as per you suggestion, I checked that the right code is imported in the project).

Updates to the latest WPAuth

---

WordPress/Classes/Services/BlogService.h
WordPress/Classes/Services/BlogService.m
WordPress/Classes/System/WordPressAppDelegate+Swift.swift
WordPress/Classes/System/WordPressAppDelegate.m
WordPress/Classes/Utility/Universal Links/Route.swift
WordPress/Classes/Utility/Universal Links/Routes+Me.swift
WordPress/Classes/Utility/Universal Links/Routes+Post.swift
WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
WordPress/Classes/ViewRelated/System/WPTabBarController.h
WordPress/Classes/ViewRelated/System/WPTabBarController.m
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/RouteMatcherTests.swift

Implements #9673.
This PR follows on from #9694, and adds two new routes for New Posts.
* `/post`
* `/post/:domain`
**To test:**
* Same as the previous PR, add an `applinks:` entry to the Associated Domains capability for the test domain I provided.
* Open the test page I created on your device, and try both of the links in the New Posts section.
* The first should open the editor with your primary or last used site.
* The second has a text field where you can enter a domain (e.g. `myawesomeblog.wordpress.com`). Then tap the link. If the domain matches a site in the app, it'll open the editor for that site. Otherwise it'll default to primary or last used.

Issue/9673 Universal Links: Handle new post links

---

WordPress/Classes/ViewRelated/Views/WPAnimatedBox.m

Fixes #9304
With this PR the loading animation for posts will loop for long loading times.
To test:
- break your internet or otherwise make post loading fail
- go to notifications and tap on a post notification
- watch the loading animation until you've had your fill

Make WPAnimatedBox animation loop

---

Podfile
Podfile.lock

Fixes an issue that was causing paragraphs to merge when they shouldn't have.
This does the same as https://github.com/wordpress-mobile/WordPress-iOS/pull/9715 but for WPiOS 10.4, integrating a proper 1.0.0-beta.23 Aztec release.
Fixes #9706 for WPiOS 10.4.
- Create a new post.
- Type several paragraphs of text as shown in the GIF above.
- Switch to HTML mode and back and make sure that paragraphs are not incorrectly merged together.

Updates Aztec to 1.0.0-beta.23.

---

README.md

The minimum Swift/Xcode versions specified in our README were outdated and misleading. Not anymore :)
To test:
I mean...

Update minimal Swift/Xcode version in docs.

---

Podfile
Podfile.lock
WordPress/Classes/Models/Notifications/Actions/ApproveComment.swift
WordPress/Classes/Models/Notifications/Actions/EditComment.swift
WordPress/Classes/Models/Notifications/Actions/Follow.swift
WordPress/Classes/Models/Notifications/Actions/LikeComment.swift
WordPress/Classes/Models/Notifications/Actions/LikePost.swift
WordPress/Classes/Models/Notifications/Actions/MarkAsSpam.swift
WordPress/Classes/Models/Notifications/Actions/NotificationAction.swift
WordPress/Classes/Models/Notifications/Actions/NotificationActionParser.swift
WordPress/Classes/Models/Notifications/Actions/ReplyToComment.swift
WordPress/Classes/Models/Notifications/Actions/TrashComment.swift
WordPress/Classes/Models/Notifications/Notification.swift
WordPress/Classes/Models/Notifications/NotificationBlock.swift
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
WordPress/Classes/ViewRelated/Notifications/FormattableContent/FormattableCommentContent.swift

This is the best way I can think of to move the Notification Actions down to `WordPressKit` while making the UI / BL concerns remain as concerns for clients of `WordPressKit`.
The `pod` file is pointing to a branch in `WordPressKit` and not to a specific commit hash. If / when this PR gets ready to merge, I would update that to make it point to a specific commit / tag
To test:
- Run `pod install`
- Notification Actions should still work

Extract notifications: Move Actions to WordPressKit

---

Podfile
Podfile.lock
WordPress/Classes/Utility/FormattableContent/DefaultFormattableContentAction.swift
WordPress/Classes/Utility/FormattableContent/FormattableContent.swift
WordPress/Classes/Utility/FormattableContent/FormattableContentAction.swift
WordPress/Classes/Utility/FormattableContent/FormattableContentActionCommand.swift
WordPress/Classes/Utility/FormattableContent/FormattableContentFactory.swift
WordPress/Classes/Utility/FormattableContent/FormattableContentFormatter.swift
WordPress/Classes/Utility/FormattableContent/FormattableContentGroup.swift
WordPress/Classes/Utility/FormattableContent/FormattableContentParent.swift
WordPress/Classes/Utility/FormattableContent/FormattableContentRange.swift
WordPress/Classes/Utility/FormattableContent/FormattableContentStyles.swift
WordPress/Classes/Utility/FormattableContent/FormattableMediaContent.swift
WordPress/Classes/Utility/FormattableContent/FormattableTextContent.swift
WordPress/Classes/ViewRelated/Activity/ActivityListRow.swift
WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
WordPress/Classes/ViewRelated/Activity/FormattableContent/ActivityActionsParser.swift
WordPress/Classes/ViewRelated/Activity/FormattableContent/ActivityContentGroup.swift
WordPress/Classes/ViewRelated/Activity/FormattableContent/FormattableActivity.swift
WordPress/Classes/ViewRelated/Notifications/FormattableContent/NotificationContentRangeFactory.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #9731 
This PR moves all `FormattableContent` code the main WP app.
As expected, Notifications didn't notice the change and it continues to work as before.
For Activity log, it was necessary a small change. There's a new wrapper class `FormattableActivity` that parse the activity `content` property as a `FormattableContentGroup`.
To test:
- Build and run.
- Check that all notifications continue to display as they should.
- Check that Activity Log formats its content as it should (the proper formatting will be applied later on)

Importing FormatableContent objects from WordPressKit

---

WordPress/Classes/ViewRelated/Views/WPAnimatedBox.m

I just realised that we had a retain cycle in WPAnimatedBox – not sure if it might've been caused by the changes in #9710, because the completion block references self, and the animation repeats indefinitely.
**To test:**
* Build and run the app
* Tap into Blog Posts and back out, and then navigate into another screen like Comments
* Repeat this multiple times
* Use the memory graph in Xcode to check for instances of WPAnimatedBox. On develop, you should see multiple instances hanging around, but not on this branch:

Fixed a retain cycle in WPAnimatedBox

---

WordPress/Classes/Utility/FormattableContent/FormattableContentFactory.swift
WordPress/Classes/Utility/FormattableContent/FormattableContentRange.swift
WordPress/Classes/ViewRelated/Activity/Activity.storyboard
WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
WordPress/Classes/ViewRelated/Activity/FormattableContent/ActivityContentStyles.swift
WordPress/Classes/ViewRelated/Activity/FormattableContent/FormattableActivity.swift
WordPress/Classes/ViewRelated/Activity/WPStyleGuide+Activity.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #9740 
This PR implements `FormattableContent` to format the content string on `Activity Log Detail`.
**Note:**
- Links will open on Safari.
- Not all links will open.
- There are kinds of Ranges yet to be implemented (`plugin`, `theme`).
All these points will be addressed on separated PRs.
And also if the design need to change, let's do it on a separated PR
To test:
- Open Activity Log.
- Check that the following kind of ranges are formatted correctly:
- Italic (Found on events like: `Default post category changes from <i>some</i> to <i>another</I>`
- Link (On the pingback example, the first link is a `link` type. It has a url without specifying type)
- Post (The names of posts formatted as a `italic` link)
- Comment (`Commented by someone on somewhere...`, the first `Commented` is …

Implement FormattableContent on Activity Log Detail

---

WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
WordPress/Classes/ViewRelated/System/WPTabBarController.h
WordPress/Classes/ViewRelated/System/WPTabBarController.m
WordPress/WordPress.xcodeproj/project.pbxproj

Implements #9667. This PR follows on from #9728, and adds a universal links route for Stats:
* `/stats` -> Shows stats for last used or primary blog
* `/stats/:domain` -> Shows stats for specified blog
* `/stats/day/:domain` -> Day view for blog
* `/stats/week/:domain` -> Week view for blog
* `/stats/month/:domain` -> Month view for blog
* `/stats/year/:domain` -> Year view for blog
* `/stats/insights/:domain` -> Insights view for blog
* `/stats/day/:category/:domain` -> Day view for blog (we ignore the category, as it's all on one page anyway)
* `/stats/annualstats/:domain` -> Year view for blog
* `/stats/activity/:domain` -> Activity log
**To test:**
* Same as the previous PRs, add an applinks: entry to the Associated Domains capability for the test domain I provided.
* In Safari on …

Issue/9667 Universal Links: Stats

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift

In this PR we're dropping a callback parameter which is not currently used by the WordPressAuthenticator. No new feature is being introduced.
1. Verify the branch builds correctly
2. Perform a fresh install, and verify the Login flow works as expected.
**NOTE:** Once this PR is approved, we'll swap to a formal WordPressAuthenticator release in the podfile.
cc @bummytime @mindgraffiti 
(Thanks in advance!!!)

WordPressAuthenticator: Wiring the latest Delegate's API

---

WordPress/Classes/Stores/ActivityStore.swift
WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift

Fairly simple one! Adds PTR in Activity views.
To test:
Go to Activity Log
Perform some activity that would get logged in AL via web (install a plugin, add a post, etc)
Make sure it shows up in Calypso (can take few moments)
Pull-to-refresh in the iOS app 
Verify that the new item shows in the app

Add pull-to-refresh to Activity Log.

---

WordPress/Classes/Utility/Universal Links/RouteMatcher.swift
WordPress/Classes/Utility/Universal Links/Routes+Banners.swift
WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/RouteMatcherTests.swift

Implements #9752. This is the last main universal links PR, and adds support for the URLs we'll use to handle links from app banners.
The app banners will all link to `apps.wordpress.com/get`, and use a URL fragment to link to a specific part of the app. In this PR, I'm stripping out the URL fragment, and passing it to the URL router to handle it as we would any other route. This allows us to point the banners to anywhere that we currently support with universal links.
**To test:**
Testing is a little simplified now, as we've [updated](https://github.com/wordpress-mobile/WordPress-iOS/issues/9753) the `apple-app-site-association` file on WordPress.com. 
* Add an `applinks:wordpress.com` entry to the main target's capabilities.
* Visit the usual test page in Safari on your device, try each …

Universal Links: Add app banner routes

---

WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
WordPress/Classes/ViewRelated/NUX/SiteCreationDomainsTableViewController.swift
WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift
WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift
WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift

Ref #9504 
This adds `NoResultsViewController:controller` and `NoResultsViewController:controllerWith` class methods to get a controller instance. View controllers that show the `NoResultsViewController` now call one of these methods to get an instance.
To test:
---
Activity List:
- Go to site details > Activity.
- Verify the No Results View appears.
---
Blog List:
- Hide all sites.
- Verify the No Results View appears.
---
Site Creation > Domain suggestions:
- Start the Site Creation process.
- NOTE: The '+' nav bar button is not working (an existing problem on `develop` that is being addressed). You can use an account that has no sites, and use the 'Add new site' button.
- On the domain selection page (step 4), enter a domain that returns no suggestions …

No Results View: refactor creating a controller instance

---

Podfile
Podfile.lock

This PR enables the One Time Code verification UI for iOS 12 Autofill.
Fixes #9737
@frosty mind taking a quick peek at this one?
2. Log into an account 2FA protected
3. When you reach the `Verification Code` screen, send an SMS to yourself with the following text: `WordPress.com verification code: 1234567`
4. Verify iOS offers you the autofill option (in the QuickType area)
**Notes**:
1. We'll switch to a formal Pod release once this is approved (before actually merging this PR)
2. We need to patch the actual WPCOM SMS Text. Otherwise... iOS 12 won't detect the OTP

iOS 12: One Time Code Autofill

---

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift

Fixes #9768
This PR adds a `formatter .resetCache` call on `NotificationDetailsViewController` when the interface needs to be refreshed.
This makes all the attributed strings to be rebuild with the new data.
**To test:**
Navigation:
- Open a notification that is shown on the `NotificationDetailsViewController`.
- Navigate with the top right arrows to the previous or next notification.
- Check that the screen shows the correct information.
Edition:
- Open a comment notification.
- Edit and save.
- Check that the screen shows the change made.

Refresh data on Notification Detail.

---

WordPress/Classes/Utility/Universal Links/Routes+MySites.swift
WordPress/Classes/Utility/Universal Links/Routes+Reader.swift
WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
WordPress/Classes/ViewRelated/System/WPTabBarController.m
WordPress/WordPress.xcodeproj/project.pbxproj

This PR adds a number of universal links we missed out the first time around, as identified in https://github.com/wordpress-mobile/WordPress-iOS/issues/9753#issuecomment-404896050.
* Reader feeds: `/read/feeds/:feed_id`
* Reader feeds: `/read/blogs/:blog_id`
* Site > Posts: `/posts/:domain`
* Site > Pages: `/pages/:domain`
* Site > Media: `/media/:domain`
* Site > Comments: `/comments/:domain`
* Site > Sharing: `/sharing/:domain`
* Site > People `/people/team/:domain`
* Site > Plugins `/plugins/:domain`
* Site > Manage Plugins `/plugins/manage/domain`
It also tweaks the existing Stats routes so that they can handle a site ID instead of a domain name in the path.
**To test:**
* This one will need to use the original testing instructions, as these routes haven't yet been added to the …

Add missing universal links

---

Scripts/manage-version.sh

This PR updates the `manage-version.sh` script with two changes that are preparatory to the next PRs which will add higher level tooling:
- both the internal and the external version are output when `get-version` is invoked, in order to allow the other tooling to be aware of them both.
- the call to `github-helper.rb` is removed and moved to the Ruby caller in order to have better and easier error management.
1. enter `Script` folder;
2. call `./manage-version.sh get-version`;
3. check that both internal and itc versions are printed out.

Updates version management script to display both version strings

---

Podfile
Podfile.lock

Fixes #9766. This PR previews the WordPressAuthenticator-iOS API changes. The changes allow WooCommerce iOS to assign a different color to the subheadline button. This PR ensures that WPiOS is not negatively impacted and that the subheadline button color remains unchanged.
Smoke test:
Run this branch and navigate through the login flow. Confirm the subheadline buttons haven't changed in appearance.
subheadline buttons:
- Log in with Google
- Log in by entering your site address
- Enter your password instead
- Forgot password
- Lost your password
- Send another code
- Need help finding your site address

Point to the latest version of WordPressAuthenticator 

---

WordPress/Classes/Utility/WPCrashlytics.h
WordPress/Classes/Utility/WPCrashlytics.m
WordPress/Classes/ViewRelated/Me/PrivacySettingsViewController.swift

This PR configures Crashlytics to respect the "Collect information" setting on the privacy screen:
If OFF, Crashlytics will not report crashes. If ON, Crashalytics will report crashes. Code-wise, this PR essentially mimics the opt-out logic found in `WPAppAnalytics` and applies it to `WPCrashlytics`. 
A couple of things to note:
1. In the [Fabric documentation](https://docs.fabric.io/apple/crashlytics/advanced-setup.html#enable-opt-in-reporting), it mentions users will need to "completely quit the app in order for the change to take effect". Instead displaying a message like that to our users, I opted call the completion handler in `crashlyticsDidDetectReportForLastExecution` with a `NO` param which causes the current report to be trashed and never sent over the wire.  
_(Note that the …

Disable Crashlytics if user opts-out of tracking

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift

This PR removes the `gifSupportInReaderDetail` feature flag, and all the related conditional code with the old paths of execution.
**note**:
I noticed that after removing this code, the class `WPTableImageSource` is not being used anywhere else in the project, and seems to be safe to be deleted.
I'm not sure if it's better to leave it if it's needed in the future, or if there's already a new class that replaces it.
If we decide to delete it, I can do it on a next PR.
cc @nheagy 
To test:
- Go to the Reader.
- Open a post with gifs. (You can go to search posts and search for `gif`).
- Check that gifs and static images display correctly.

Remove `gifSupportInReaderDetail` feature flag and related conditional code.

---

WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
WordPress/Classes/ViewRelated/NUX/SiteCreationDomainsTableViewController.swift
WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift
WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift
WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift

Ref #9504 
This adds a `NoResultsViewController:removeFromView` method to remove the NRV from the parent view. View controllers that show the NoResultsViewController now call this method instead of doing it within each VC.
To test:
Since all the VCs use the same logic, we'll just sanity check some of the cases.
---
Activity List:
- Go to site details > Activity.
- Verify the 'Loading Activities' view is removed when the Activities are loaded.
---
Theme Browser:
- Go to Site > Themes > Search.
- Enter a search term that returns no results.
- Verify the 'No Themes Found' view is displayed.
- Enter a valid keyword.
- Verify the 'No Themes Found' view is removed.
---
Blog List:
- Hide all sites.
- Verify the 'You have x hidden WordPress sites' view appears.
- Unhide a site.
- Verify the 'You …

No Results View: refactor hiding view

---

WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift
WordPress/WordPressShareExtension/ShareModularViewController.swift

This PR attempts to address the large amount of Tracks errors in the app extensions. See #9789 for more details. Things done:
1. In the `ShareExtensionSessionManager` we are only logging invalidated sessions that are _not_ tracks-specific.
2. `ShareModularViewController` is logging the `wpios_share_extension_posted` or `wpios_draft_extension_posted` events prior to actually firing the background NSURLSession which saves the media/post. We are doing this first because @astralbodies and I have a hunch the tracks network call is getting invalidated when fired in the save completion handler.
Fixes #9789 
_Test both the draft and share extensions sharing an image and also just text._
1. Build and run on a device (no sim) and disconnect XCode
2. Share text/image
3. Verify the media/text is …

App extensions: fix for tracks errors

---

WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift

Fixes #9810 
Build and run the app. Verify the footer text in plans is empty.

Updates plan table footer text

---

WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift

This PR removes the title label from the backBarButtonItem on the `SignupUsernameViewController`:
Fixes #9809 
1. Sign up for a new WP account using email or Google
2. In the epilogue VC, tap the username field to change it
3. On the `SignupUsernameViewController` screen, verify the back nav button has no title.
@nheagy would you mind taking a quick peek at this?

SignupUsernameViewController: Removes "Back" label from back nav button

---

WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
WordPress/WordPressScreenshotGeneration/XCTest+Extensions.swift
WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphBackgroundView.m

This should help the reliability issues discussed in https://github.com/wordpress-mobile/WordPress-iOS/issues/9720.
To test: `fastlane snapshot` should still pass and take the correct screenshots but now should be less prone to flakiness and random failures.

 Reduce reliance on sleep in screenshot tests by using waits where possible

---

WordPress/Classes/Utility/Universal Links/Routes+Banners.swift
WordPress/Classes/Utility/Universal Links/Routes+Stats.swift

This PR makes a small change to the way URL fragments are parsed for app banner universal links.
**Previously:**
* App banner universal links were of the form: `https://apps.wordpress.com/get#stats/day/discover.wordpress.com`
* The fragment consisted of a WordPress.com URL, with the leading slash stripped
**Now:**
* These links are of the form: `https://apps.wordpress.com/get#%2Fstats%2Fday%2Fdiscover.wordpress.com`
* The leading slash is kept as part of the fragment
* The fragment is URL encoded
**To test:**
* Add an `applinks` entitlement for `apps.wordpress.com`, and build to your device.
* Visit https://calypso.live/?branch=update/app-banner-ios-urls on your device, and check that the banners launch you into the app correctly. As a reminder, there are banners in the Stats, Reader, …

App Banner Universal Links: Small tweak to fragment parsing

---

WordPress/Classes/System/WordPressAppDelegate+Swift.swift
WordPress/Classes/System/WordPressAppDelegate.m
WordPress/Classes/Utility/AccountHelper.swift
WordPress/Classes/Utility/Universal Links/NavigationActionHelpers.swift
WordPress/Classes/Utility/Universal Links/Routes+MySites.swift
WordPress/Classes/Utility/Universal Links/Routes+Post.swift
WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
WordPress/WordPress.xcodeproj/project.pbxproj

This PR improves handling of some failure cases for universal links:
* Universal links won't be triggered at all if the user isn't logged into the app, to avoid unnecessary navigation behind the login screen.
* My Sites and Stats routes will now just display the root of the My Sites section and an error notice if the specified site can't be found in the app – for example, if the user is logged into Safari with a different account.
We're almost there, @etoledom! Sorry for all these PRs! I think this might be the last one! 🎉 
* Add an `applink` entry for WordPress.com. Build and run to your device.
**Logged out**
* Ensure you're logged out of the app.
* Open a WordPress.com page in mobile safari that triggers universal links – for example, Notifications.
* Scroll the page down slightly to …

Universal Links: Improve failure cases

---

WordPress/WordPress.entitlements

Fixes #9798. This PR shouldn't be merged until #9797 is merged.
This PR enables universal links in the app by adding `applinks` Associated Domain capabilities for `wordpress.com` and `apps.wordpress.com`.
**To test:**
* To test WordPress.com universal links, build this branch to a device and visit WordPress.com in mobile Safari.
* If you visit any of the paths specified in https://wordpress.com/apple-app-site-association and scroll the page down, you should see an 'open in app' banner at the top of the page.
* You can also try tapping one of the links below, which should launch the app:
* https://wordpress.com/stats
* https://wordpress.com/discover
* https://wordpress.com/notifications
* https://wordpress.com/post
* To test apps.wordpress.com links, build to your device and then visit …

Enable Universal Links

---

WordPress/WordPress.entitlements

It seems to be one of those days... my original PR, #9802 targetted a different branch, which I accidentally merged before I pulled this one in.
This PR is identical to #9802, just targeting `develop`.
Really sorry, @etoledom, would you mind just double checking this one?

Enable universal links for wordpress.com and apps.wordpress.com (retarget PR)

---

WordPress/Classes/Utility/ZendeskUtils.swift

Fixes n/a
Per HE request, this limits the Name field in the Support user information prompt to 50 characters.
To test:
- Start with a fresh install to clear your Support information.
- Go to Me > Help & Support.
- Select Contact Us or My Tickets.
- Verify you cannot enter more than 50 characters in the `Name` field.

Zendesk: limit Name field to 50 characters

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.swift
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.xib
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistView.swift
WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Refs #9447 
This PR adds the Quick Start checklist with all seven items.
Note that the tours don't work, there is no associated data storage to track progress, and that currently all sites will see the menu in developer builds. These will be addressed in future PRs.
To test:
- build the app
- view a blog's details, tap Quick Start

Quick Start: add checklist

---

WordPress/Classes/Models/Notifications/Notification.swift
WordPress/Classes/ViewRelated/Activity/FormattableContent/ActivityContentRouter.swift
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationContentRouter.swift
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
WordPress/Classes/ViewRelated/Notifications/FormattableContent/Groups/BodyContentGroup.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/FormattableContentGroupTests.swift
WordPress/WordPressTest/MockContentCoordinator.swift
WordPress/WordPressTest/NotificationContentRouterTests.swift
WordPress/WordPressTest/NotificationTests.swift
WordPress/WordPressTest/NotificationUtility.swift

Fixes #9847 
This PR implements routing on `NotificationDetailsViewController` using the new FormattableContent system.
The `coordinator` instance on `NotificationDetailsViewController` can be removed when the feature flag is eliminated.
A few tests were implemented to check a small bug encountered. I plan to add extra test in a future PR.
To test:
- Go to the Notification list.
- Check that each kind of content routes to the corresponding section.
- Change the `extractNotifications` feature flag to `false`.
- Check that the old code still run at it should.

Notification detail routing using FormattableContentGroups

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/Utility/Universal Links/Routes+Banners.swift
WordPress/Classes/Utility/Universal Links/Routes+MySites.swift
WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift

Implements #9799.
This PR adds analytics events for universal links:
* `WPAnalyticsStatDeepLinked`
* Matches the WPAndroid event used to track when a deep link is handled by the app. Triggered when a universal link is matched to a 'route' within the app.
* `WPAnalyticsStatDeepLinkFailed`
* Used to track if a deep link is triggered for a specific site, but that site cannot be found within the app (this may occur if a user is logged into Safari with a different account to the app).
This PR relies on a [branch](https://github.com/wordpress-mobile/WordPress-iOS-Shared/tree/add/universal-links-stats) of WordPressShared, which should be merged before this PR is merged.
**To test**
* Build and run this PR to a device.
* Load this page in Safari, and tap the following links:
* …

Universal Links: Add analytics

---

WordPress/Classes/Utility/ContentCoordinator.swift
WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
WordPress/Classes/ViewRelated/Activity/FormattableContent/ActivityContentRouter.swift
WordPress/Classes/ViewRelated/Activity/FormattableContent/Ranges/ActivityPluginRange.swift
WordPress/Classes/ViewRelated/Plugins/PluginViewController.swift
WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift
WordPress/WordPressTest/ActivityLogRangesTest.swift
WordPress/WordPressTest/MockContentCoordinator.swift
WordPressFlux/WordPressFlux/Sources/QueryStore.swift

Fixes #9836 
As part of #9748, this PR adds a route to an specific plugin from an activity log event:
**Note**:
The challenge was to adapt `PluginViewController` to be presented from other than the Plugins section, since it was prepared to accept a preloaded data fetched in the plugin list.
Now the `PluginViewController` can be loaded with just a plugin `slug` and it will fetch and display that plugin.
Since now it is loading without having any pre-fetched data, it was necessary to add a `loading` state, and since loadings can fail, also an `error` state.
Those new states are handled visually by `NoResultViewController` in the same way that it's handled in the activity log list.
The possible errors look like this:
**To test:**
1. Generate a plugin related event (activating, deactivating, …

Activity log plugin event navigates to plugin view.

---

Dangerfile
buddybuild_postbuild.sh

This PR adds a new Danger rule to fail PRs that are tagged with the 'DO NOT MERGE' label.
**To test**
* Check that this PR fails while it has the DO NOT MERGE label applied.

Danger: Add a rule for PRs tagged 'DO NOT MERGE'

---

Podfile
Podfile.lock

Bumps the pod version that include fixes to Activity Log.

Update WordPressKit-iOS to 1.2

---

WordPress/Classes/ViewRelated/Notifications/FormattableContent/NotificationTextContent.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/FormattableContentGroupTests.swift
WordPress/WordPressTest/FormattableUserContentTests.swift
WordPress/WordPressTest/NotificationBlockTests.swift
WordPress/WordPressTest/NotificationTests.swift
WordPress/WordPressTest/NotificationTextContentTests.swift
WordPress/WordPressTest/NotificationUtility.swift
WordPress/WordPressTest/Test Data/notifications-replied-comment.json
WordPress/WordPressTest/Test Data/notifications-text-content.json
WordPress/WordPressTest/Test Data/notifications-unapproved-comment.json
WordPress/WordPressTest/Test Data/notifications-user-content.json

Part of #9758
This PR adds some Unit Tests to the Notification implementation of `FormattableContent`.
Many of the tests are copies of tests made for the old `NotificationBlocks`, but using the new content groups.
To test:
- Build and run the tests.
- All tests should pass.

More tests to FormattableContent

---

WordPress/Classes/Utility/FormattableContent/FormattableContentStyles.swift
WordPress/Classes/Utility/FormattableContent/FormattableRangesFactory.swift
WordPress/Classes/Utility/FormattableContent/FormattableTextContent.swift
WordPress/Classes/ViewRelated/Activity/FormattableContent/Factory/ActivityRangesFactory.swift
WordPress/Classes/ViewRelated/Notifications/FormattableContent/NotificationTextContent.swift
WordPress/Classes/ViewRelated/Notifications/FormattableContent/Ranges/NotificationContentRangeFactory.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes part of #9758 
This PR is a small organization of code and documentation:
- Moving `FormattableRangesFactory` to its own file.
- Moving `rangesFrom()` function from `FormattableTextContent` to `NotificationTextContent`.
- Adding documentation to `FormattableContentStyles`
To test:
- Build and run.
- Check that Notifications works as it should.
@ctarda this is the last one! Sorry for the late PR.
I just couldn't leave this details there. 😅

Formattable content code organization

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift

Screenshots automation was broken since the order of cells in the blog details table changed. This is an update to use accessibility identifiers so that we are not dependent on order.
To test: `fastlane snapshot` now runs successfully.

Fix screenshots: Use explicit accessibilityIdentifier for stats row

---

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift

This is a potential fix for #9745. I was unable to recreate the original issue, but my best guess would be that we were attempting to configure the results status view in ReaderStreamViewController before the view was loaded (meaning the outlets would be `nil`).
**To test:**
* Check the code
* Ensure that the reader stream view controller still displays correctly, and the status view is still updated correctly.

ReaderStreamViewController: Check view is loaded before configuring status view

---

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift

This PR is simply cherry-picking #9900's fix into `release/10.6`.

ReaderStreamViewController: Check view is loaded before configuring status view (release/10.6)

---

WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift

This makes two small changes to improve reliability:
- Wait time for image loading has been increased.
- Log out now works for all locales. This was previously unreliable because button order varies.
Another step towards fixing https://github.com/wordpress-mobile/WordPress-iOS/issues/9720
To test:
- `fastlane snapshot` will still work.
- More time is now allowed for images to load

Improve screenshot reliability

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Adds a feature flag for the News Card feature, so that we can dark-reply changes to the UI

Add a feature flag for the News Card

---

WordPress/WordPress-Alpha.entitlements
WordPress/WordPress-Internal.entitlements

It turns out that universal links weren't working for internal builds, as I'd missed updating the entitlements files for them.
This PR should fix that by adding the missing `applinks` entries to the internal entitlements file. I added them to alpha while I was at it too.
**To test**
* Check that the `com.apple.developer.associated-domains` section in the Alpha and Internal entitlements files match that section in `WordPress.entitlements`
* Build and run an internal build onto a device. On that device, tap this link: https://apps.wordpress.com/get. It should launch the app!

Fix universal links entitlements for internal builds

---

WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift

If someone new to the project wants to work on screenshots, they can run the `WordPressScreenshotGeneration` test or use `fastlane snapshot`. However, if they haven’t set their WordPress.com username and password, it’ll fail with an unhelpful error:
>WordPressScreenshotGeneration.testGenerateScreenshots() failed: failed - Failed to find "Continue" Button after 30.0 seconds.
This is because by default the username and password are set to empty strings, which are technically valid code. 
After this commit, if someone takes the same steps, it’ll instead tell them:
>WordPressScreenshotGeneration.swift:50:32: Editor placeholder in source file
This points them to the exact place they need to make a change in order to continue, which should hopefully ease the onboarding process. As a bonus, in …

Improve screenshot onboarding

---

WordPress/Classes/ViewRelated/Me/GravatarPickerViewController.swift

Fixes #9902 
In the Gravatar Picker, replace `WPNoResultsView` with `NoResultsViewController`.
The No Results view is displayed when the user has no media.
The idea here is to replace `MediaNoResultsView` with `NoResultsViewController+MediaLibrary` (which was introduced in #9897). `MediaNoResultsView` will be removed once all relevant ViewControllers are updated.
**To test:**
---
**No Media - device with camera:**
- On an actual device, go to Me and tap on the user icon.
- The initial view is Selfies. If you don't have any, you'll see the following view. 
- If you do have Selfies, tap Albums and pick one that has no media.
---
**No Media - device with no camera (or simulator):**
- Follow the same steps as above.

Gravatar Picker: replace No Results view

---

WordPress/Classes/Models/Notifications/Notification.swift
WordPress/Classes/ViewRelated/Notifications/FormattableContent/FormattableCommentContent.swift
WordPress/Classes/ViewRelated/Notifications/FormattableContent/FormattableUserContent.swift
WordPress/Classes/ViewRelated/Notifications/FormattableContent/NotificationContentFactory.swift
WordPress/Classes/ViewRelated/Notifications/FormattableContent/NotificationTextContent.swift
WordPress/WordPressTest/FormattableCommentContentTests.swift
WordPress/WordPressTest/FormattableUserContentTests.swift
WordPress/WordPressTest/NotificationTextContentTests.swift

Fixes #9935, which paves the way for `FormattableContent` to be used with rich notifications. The changes are broken down into granular commits:
1. I noticed an issue with naming of a field within `Notification`; I took the liberty to make `cachedHeaderAndBodyContentGroup` plural to underscore that its an `Array`.
1. Defined a new interface - `NotificationIdentifiable` - that `Notification` implements. It consists of one parameter. The implications of this were propagated throughout the existing code.
1. Extended `RemoteNotification` to conform to this new interface. It will be manipulated further in #9936.
- Given that this is a basic refactoring, checkout branch and verify that it builds and tests continue to pass. 
- Manual testing should reveal no regressions regarding the formatting …

Extract interface from FormattableContent for use with both Notification & RemoteNotification

---

WordPress/Classes/ViewRelated/Aztec/Stock Photos/NoResultsViewController+StockPhotosPicker.swift
WordPress/Classes/ViewRelated/Aztec/Stock Photos/StockPhotosStrings.swift
WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
WordPress/Classes/ViewRelated/Media/NoResultsViewController+MediaLibrary.swift
WordPress/Classes/ViewRelated/Views/NoResults.storyboard

Ref #9504 
When making accommodations for putting the media search string in the title field, it broke the NoResultsView for no sites and all sites hidden.
This change puts the search string in the subtitle field (which actually looks better anyway) and restores the correct UI layout for no sites and all sites hidden.
NOTE: if you notice broken constraints messages, I know. 😄 I'm working on it!
To test:
---
**All sites hidden**
- Hide all sites on account.
---
**No sites**
- Log into an account with no sites.
---
**Media Library search**
- On a site with media, go to Media Library.
- Enter an invalid search string.
---
**Stock Photos search**
- Go to Media Library, click the + on the nav bar, and select 'Free Photo …

Fix No Results View issues

---

WordPress/Classes/ViewRelated/Views/NoResults.storyboard

Ref #9504
This fixes some constraint warnings when displaying the `NoResultsViewController` from the MediaPicker pod.
To test:
- Run the app.
- Go to Media Library.
- Verify no constraint message appear in the log.
- From the Media Library, tap + on the nav bar, and select 'Free Photo Library'.
- Verify no constraint message appear in the log.

Fix No Results View constraints

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

Fixes #9940 
In the Post Editor media selection, replace `WPNoResultsView` with `NoResultsViewController`.
- The user has no WordPress media.
- Media is being fetched.
- No results from searching the WordPress media library.
To note, there are associated `MediaPicker` changes (https://github.com/wordpress-mobile/MediaPicker-iOS/pull/304). I will update this `podfile` when that has been merged.
**To test:**
---
**No Media:**
- Select a site with no WordPress media.
- Edit/create a post.
- Tap on the WordPress media button.
---
**Fetching:**
- On a slow network, edit/create a post.
- To note, you may have to select another site, or do a fresh install, since media is cached.
- Tap on the WordPress media button.
- Verify the view …

Post Editor: replace No Results view

---

WordPress/Classes/ViewRelated/Media/NoResultsViewController+MediaLibrary.swift
WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m

Fixes #9945 
For Post Settings > Set Featured Image, replace `WPNoResultsView` with `NoResultsViewController`.
- The user has no media.
- Media is being fetched.
- No results from searching the WordPress media library.
**To test:**
---
**No Media:**
- On a site with no WordPress media, edit/create a post.
- Go to Post Settings > Set Featured Image.
- Select the 'WordPress Media' album.
---
**Fetching:**
- On a slow network, edit/create a post.
- Go to Post Settings > Set Featured Image.
- While the message `counting media items` is still displayed on an album, select it.
---
**No Results:**
- On a site with WordPress media, edit/create a post.
- Go to Post Settings > Set Featured Image.
- Select the …

Post Settings > Set Featured Image: replace No Results view

---

WordPress/Classes/ViewRelated/Ratings/AppFeedbackPromptView.swift
WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift

The simplest fix was to just click the "Not Now" button. Because the button labels may change (and with RTL support, the order may as well), it was necessary to add accessibility identifiers to the buttons. 
Fixes #9868
To test:
- Screenshots should no longer have the notification banner in them
- Adding the accessibility identifier to the buttons in `AppFeedbackPromptView` shouldn't have any side effects that'll affect app stability.

iOS Screenshots: Remove notification banner

---

WordPress/Classes/ViewRelated/People/PeopleViewController.swift

Fixes #9953 
In Site Settings > People, replace `WPNoResultsView` with `NoResultsViewController`.
- There are no Users.
- There are no Followers.
- There is no internet connection.
To test:
---
**No Users/Followers:**
- On a site with no Users/Followers, go to Site > People.
- Select `Users`/`Followers` from the nav bar dropdown.
---
**No Connection:**
- Go to Site > People.

Site People: replace No Results view

---

WordPress/Classes/ViewRelated/Comments/CommentsViewController.m

Fixes #9951 
In Site Settings > Comments, replace `WPNoResultsView` with `NoResultsViewController`.
- There are no site comments.
- There is no internet connection.
To test:
---
**No Comments:**
- On a site with no comments, go to Site > Comments.
---
**No Connection:**
- Go to Site > Comments.

Site Comments: replace No Results view

---

WordPress/Classes/ViewRelated/Tools/TimeZoneSelectorViewController.swift

Fixes #9955 
In Site Settings > Time Zone selector, replace `WPNoResultsView` with `NoResultsViewController`.
The No Results view is displayed in these cases:
- Loading time zones
- No connection
- Loading error
To test:
---
**Loading Time Zones:**
- On a slow network, go to Site > Settings > Time Zone.
---
**No Connection:**
- Go to Site > Settings > Time Zone.
---
**Loading Error:**
- This may require some hacking to show the error view. My suggestion:
- In `TimeZoneSelectorViewController:noResultsViewModel`, always return the "Oops" view for the `error` case.
- Disable internet connection (assuming you used the above hack).
- Go to Site > Settings > Time Zone.

Time Zone selector: replace No Results view

---

WordPress/Classes/ViewRelated/Blog/SiteIconPickerPresenter.swift

Fixes #9938 
In the Site Icon Picker, replace `WPNoResultsView` with `NoResultsViewController`.
- The user has no media.
- Media is being fetched.
- No results from searching the WordPress media library.
**To test:**
---
**No Media:**
- On a site with no WordPress media, click on the site icon.
- Select 'Change Site Icon'.
- Select the 'WordPress Media' album.
---
**Fetching:**
- On a slow network, click on the site icon.
- To note, you may have to select another site, or do a fresh install, since media is cached.
- Select 'Change Site Icon'.
- While the message `counting media items` is still displayed on an album, select it.
---
**No Results:**
- On a site with WordPress media, click on the site icon.
- …

Site Icon Picker: replace No Results view

---

WordPress/Classes/Utility/ZendeskUtils.swift

Fixes #9883 
Adds new fields to Zendesk tickets identifying the platform the ticket originated from and the language currently in use.
To test:
Create a new Zendesk issue.
Confirm in the Zendesk tool that the new fields show up and are populated with the correct data. 
cc @charliescheer, I sent a test ticket. Could you take a peek and confirm that its what's expected?

Zendesk: Adds new fields to tickets.

---

WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift

We got a few crash reports of AL crashing on launch. This fixes it! 
Turns out, setting a `tableFooterView` on a `UITableView` kicks off a bunch of internal methods that end up asking `delegate` for things like number of items in the first section. Turns out, when you don't _have_ a first section, this can blow up in ImmuTable ;) 
Moving the `refreshModel()` call sets up the `ImmuTable.viewModel` properly earlier in the lifecycle, so we don't run into this issue.
p2 ref: p4a5px-2fc-p2

[Activity Log] Fix a crash that would happen when opening AL on slower devices.

---

WordPress/Classes/ViewRelated/Menus/MenusViewController.m

Fixes #9960  
In Site > Menus, replace `WPNoResultsView` with `NoResultsViewController`.
- There are no Menus.
- Loading Menus.
- Loading error.
To test:
---
**No Menus:**
- I actually couldn't get no menus on my sites, so a hack may be required. Suggestion:
- In `MenusViewController:didSyncBlog`, comment out the first `if` that checks the `count`, and let it just show the NoMenus view.
- Go to Site > Menus.
---
**Loading Menus:**
- On a slow network, go to Site > Menus.
---
**Loading Error:**
- Disconnect internet.
- Go to Site > Menus.

Site Menus: replace No Results view

---

Podfile
Podfile.lock

This PR maps to a WordPressAuthenticator branch, which includes a bugfix for an Autofill iOS 12 crash.
1. Install this branch in a iOS 12 **BETA 6** device (built with Xcode 10!)
2. Log into a Dotcom account, 2FA protected (with SMS Auth)
3. Whenever the SMS comes thru, press over the autofill option that shows up above the keyboard
Verify the app doesn't crash
cc @frosty or @jklausa  Gentlemen, if any of you two has an iOS 12 device, can you please take a look at this one?.
Before merging this one  (once approved) i'll update the Podfile mapping to an actual Pod release.

iOS 12 Beta 6: Fixing Autofill Violent Crash

---

WordPress/Credentials/ApiCredentials.h
WordPress/Credentials/gencredentials.rb

Implements #9995.
This PR adds Giphy to the credentials process for our upcoming Giphy integration.
**To test:**
* I'll send you the latest credentials file on Slack. Replace the existing one.
* Add a line into `runStartupSequenceWithLaunchOptions:` in the app delegate, to log out the new key:
```
NSLog(@"GIPHY: %@", [ApiCredentials giphyAppId]);
```
* Build and run and check you see the key in the console!

Add Giphy to the credentials process

---

WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
WordPress/WordPressNotificationServiceExtension/Sources/Tracks/Tracks+ServiceExtension.swift

Fixes #9977, which calls for the addition of a few basic analytics events to track rich notifications events.
These events are as follows:
- Launch
- Successful notification delivery
- Failure to retrieve the payload for a specified notification
- Discarded notification; the initial iteration will only support Comment notifications. Others will be ignored by the service extension and will continue to be delivered as before. _While the event is defined here, it will be integrated via #9971.
To test:
- Verify that the branch builds & existing tests pass.
- While debugging the service extension, manually push a payload with a valid `note_id` value. Instructions for this can be found here: #9924 
- In the _Tracks Live View_, validate that events of type …

Rich Notifications : Integrated Tracks events for notification service extension

---

WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift

Fixes #10010 
In Reader > Post details, replace `WPNoResultsView` with `NoResultsViewController`.
The No Results view displayed when:
- loading the post
- error loading the post
To test:
- Not _every_ post will attempt to load, as some posts are pre-loaded and passed into the VC. It may take trying a couple of different posts. I found that most of the 'Discover' posts will do it, i.e. the ones with a header like:
---
**Loading post:**
- On a slow network, go to Reader > Followed Sites > select a Post.
---
**Loading error:**
- This will probably require some hacking. Suggestion:
- In `ReaderDetailViewController:setupWithPostID`, in the `service.fetchPost` `success` block, comment out what's there and replace it with this method call from the `failure` block:
``` …
```

Reader Post Detail: replace No Results view

---

WordPress/Classes/Services/BlogService.m

Fixes #10016.
When navigating to the app via a universal link for a blog with a custom domain, the universal link router often couldn't find the right site. 
This seems to be because sites with custom domains may use their `*.wordpress.com` URL in their XMLRPC property (which is used by the `Blog.hostname` method). In `BlogService.blogByHostname` we were likely finding the correct site by searching by URL, but then filtering out the site we wanted by re-filtering the list based on hostname. I'm pretty certain the `url` property should contain the correct hostname for the site (the same that'll be used in Safari) so I don't think the extra filtering is necessary.
**To test:**
**Note:** Universal links only work on a device, not in the simulator.
* Visit a WordPress.com-hosted site with a …

BlogService: Don't double-filter blogs when searching by hostname

---

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift

Ref #9992 
This is to fix the issue @frosty discovered [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/9957#pullrequestreview-147650246) . The problem was the header was being refreshed after the NoResultsView was displayed, causing the header to show on top of the NRV. The fix checks to see if the header already exists. If so, persist the `isHidden` state.
To test:
- You may wish to enable the `newsCard` FeatureFlag as this caused the issue to be quite obvious.
- On a slow network, go to Reader > Followed Sites, or Reader > Discover.
- Verify the 'Fetching Posts' view is full screen (i.e. the header does not show).

Fix Reader stream No Results view to display correctly with News Card

---

WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m

Fixes #10012 
In Reader > Post > Comments, replace `WPNoResultsView` with `NoResultsViewController`.
The No Results view displayed when:
- there are no post comments
- loading post comments
- error loading post comments
To test:
---
**No Post Comments:**
- Go to Reader > Followed Sites > Manage.
- Select a site that has a post with no comments.
- Press the comment icon on the post with no comments.
---
**Loading Post Comments:**
- On a slow network, in the Reader, press the comment icon on a post with comments.
---
**Loading Error:**
- This may require some hacking. Suggestion:
- In `ReaderCommentsViewController:syncContentEnded`, comment out all it's contents and call `[self syncContentFailed:syncHelper];`.
- In the Reader, press the comment …

Reader Post Comments: replace No Results view

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Activate refactor of notifications for all builds. 
This PR is an intermediate step before actually removing all the old code.
@jklausa If you don't mind a quick review 😊 
Pinging @etoledom for tracking purposes

Activate refactor of notifications for all builds

---

WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
WordPress/Classes/ViewRelated/System/WPTabBarController.m

Fixes #10014.
Previously, some universal links that opened the Reader on iPad would open in the wrong pane – showing post detail or a stream in the left pane of the split view:
This PR slightly adjusts the logic of `ReaderCoordinator` to ensure that the correct pane is selected to display content.
**To test:**
* Build and run to a **device**
* Tap each of the following links, and ensure that the view is correct in the app:
* https://wordpress.com/read/blogs/146091842/posts/548006 – should open a post in a full width view
* https://wordpress.com/read/blogs/146091842 - should open the 9to5mac feed in the right pane, with the Reader menu visible in the left pane

ReaderCoordinator: Ensure that VCs are opened in correct split view pane

---

WordPress/Classes/Models/Blog.m

Fixes and issue reported by @rachelmcr on p5T066-FX-p2 where the auto-update toggle was being hidden for plugins on all Jetpack sites, not just Atomic sites.  The culprit was an improperly cast boolean which was always evaluating to true.
To test:
Check Plugins on a Jetpack site and confirm that the auto update toggle is available. 
Check Plugins on an Atomic (AT) site and confirm that the auto update toggle is *not* available.
@jleandroperez its been ages sir.  Could I trouble you with this one?

Fix the check for isAutomatedTransfer and properly cast the returned option value

---

WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift

Fixes #10008 
In Reader > manage followed sites, replace `WPNoResultsView` with `NoResultsViewController`.
The No Results view displayed when:
- there are no followed sites
- fetching sites
To test:
---
**No followed sites:**
- On a site that has not followed sites, go to Reader > Followed Sites > Manage Sites.
--- 
**Fetching sites:**
- On a slow network, go to Reader > Followed Sites > Manage Sites.

Reader Manage Sites: replace No Results view

---

WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
WordPress/Classes/ViewRelated/Plugins/CollectionViewContainerRow.swift
WordPress/Classes/ViewRelated/Plugins/PluginDirectoryViewController.swift
WordPress/Classes/ViewRelated/Plugins/PluginDirectoryViewModel.swift
WordPress/Classes/ViewRelated/System/Notices/NoticeView.swift
WordPress/Classes/ViewRelated/Views/NoResults.storyboard

Fixes #10020 
- Error loading plugins.
- Fetching plugins.
Due to lack of space (as in the original implementation), the NRV image does not show. However, I did add the loading animation since, while loading, there is enough room for that.
NOTE: The constraint warnings are pre-existing and unrelated to the NRV.
To test:
---
**Error loading plugins:**
- This might require a hack to show. Suggestion:
- In `BlogDetailsViewController:configurationSectionViewModel` comment out this if check: `if ([self.blog supports:BlogFeaturePluginManagement])`.
- On a site that does not support plugins, go to Site > Plugins.
---
**Loading plugins:**
- On a slow network, go to Site > Plugins.

Plugin Directory: replace No Results view

---

WordPress/Classes/ViewRelated/NUX/SiteCreationEpilogueViewController.swift

Currently after creating a new site, tapping the "Write first post" button would drop the user at the list of sites, instead of showing details for the newly created site. This PR fixes that.
To test:
- create a new site
- tap "Write first post" when complete
- dismiss the editor
- ensure the new site is show instead of the list of sites

Show newly created site after its creation

---

WordPress/Classes/ViewRelated/Reader/NewsCard.xib

Fixes the readable margins for the news card.
I am not sure what the problem was, but a combination of activating `Preserve Superview margins`, `Follow readable guides` and `safe area relative margins` in the root view, plus removing and redoing the previous constraints seem to fix it.
Caveat: this is still not ready for a design review. The stack view containing the labels does not expand vertically to use all the available space, but for my mental sanity, I need to move on to something else. One thing a time, I guess...

Newscard readable margins

---

WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
WordPress/Classes/ViewRelated/Plugins/PluginDirectoryViewModel.swift
WordPress/Classes/ViewRelated/Plugins/PluginListViewController.swift
WordPress/Classes/ViewRelated/Plugins/PluginListViewModel.swift
WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderSiteSearchViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift

Fixes #10026 
In the Plugin List, replace `WPNoResultsView` with `NoResultsViewController`.
- Loading plugins.
- No results from plugin search.
- Error loading plugins.
- No connection.
To test:
---
**Loading plugins:**
- On a slow network, go to Site > Plugins > Manage.
---
**Search no results:**
- Go to Site > Plugins > Search.
- Enter an invalid search term.
---
**Loading error:**
- This might require a hack to show. Suggestion:
- In `BlogDetailsViewController:configurationSectionViewModel` comment out this if check: `if ([self.blog supports:BlogFeaturePluginManagement])`.
- On a site that does not support plugins, go to Site > Plugins > Manage.
---
**No connection:**
- Disable …

Plugin List: replace No Results view

---

WordPress/Classes/ViewRelated/NUX/SiteCreationSitePreviewViewController.swift

A new site displayed in the web view in the site creation flow shows a very prominent "Get Started" call to action at the top of the page:
Until we have a way to switch this off directly, why don't we just hide it using JavaScript?
**To test:**
* Create a new site in the app
* After the 'congratulations' screen, check that the preview webview doesn't show the Get Started bar at the top.
* If you like, maybe check with a couple of different site themes.

Site creation: Hide Get Started bar in webview

---

WordPress/WordPress.xcodeproj/project.pbxproj

Fixes the following issue as reported by `rake`:
```
2018-08-28 07:43:22.518 xcodebuild[69931:30554392] warning:  The file reference for "MediaCoordinator.swift" is a member of multiple groups ("Services" and "Services"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
2018-08-28 07:43:22.519 xcodebuild[69931:30554392] warning:  The file reference for "NewsService.swift" is a member of multiple groups ("Services" and "Services"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want …
```

De-duplicate file references

---

WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m

Fixes #10062 
To test:
- Go to Reader > Followed Sites > Manage.
- Select a site that has a post with no comments.
- On the post with no comments, press the comment icon.
- Show and hide the keyboard.
- Verify the No Results view adjusts accordingly, and the 'Reply to post...' bar is not obscured.
Keyboard:
No keyboard:

Reader Comments: Refresh No Results view when the keyboard shows and hides.

---

WordPress/Classes/ViewRelated/Me/ActivityLogDetailViewController.m
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes the first portion of #9780, which simplifies how a user shares logs via the Support interface. I also took the liberty to alphabetize the existing contents of this folder.
- Verify that the existing branch builds & tests pass.
- Run the branch and confirm that you see something similar to the screenshots below. One callout, depending on what's enabled in `...`, you may see more options.
_Before_
_After_:

Explicitly exclude superfluous activity types when a user shares logs

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/Utility/Automated Transfer/AutomatedTransferHelper.swift
WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift

Adds analytics to Automated Transfer.
Events are copied from Android app, for parity.
Testing steps are as per #10039, just with added caveat of "also watch out for console to make sure correct stuff gets tracked."
Would be grateful if you could tackle this one as well, @nheagy  :)

Automated Transfer analytics.

---

WordPress/Classes/System/WordPressAppDelegate+Swift.swift
WordPress/Classes/Utility/Universal Links/Route.swift
WordPress/Classes/Utility/Universal Links/RouteMatcher.swift
WordPress/Classes/Utility/Universal Links/Routes+Banners.swift
WordPress/Classes/Utility/Universal Links/Routes+MySites.swift
WordPress/Classes/Utility/Universal Links/Routes+Reader.swift
WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
WordPress/WordPressTest/RouteMatcherTests.swift

In the current implementation of universal links, if we fail to locate a site to navigate to, or if the user is logged out, we current either fail silently or display a "Site not found" notice.
This PR changes that so that we now bounce the user back to Safari in the event that we can't navigate them to the correct content.
* Build and run to a *device*.
**Logged out**
* Log out of the app and ensure you're logged in in Safari.
* Trigger a universal link from one of your sites in Safari – for example from the Posts or Stats pages. Scroll the page down a little to see the 'OPEN' banner at the top, and tap open. You should be taken to the app, and then back to Safari.
**Different account**
* Log back into the app, using a different account than you're logged into Safari with.
* Attempt the …

Universal Links: Bounce back to Safari if navigation fails

---

WordPress/Classes/Utility/Universal Links/Route.swift
WordPress/Classes/Utility/Universal Links/Routes+Banners.swift
WordPress/Classes/Utility/Universal Links/Routes+Me.swift
WordPress/Classes/Utility/Universal Links/Routes+MySites.swift
WordPress/Classes/Utility/Universal Links/Routes+Notifications.swift
WordPress/Classes/Utility/Universal Links/Routes+Post.swift
WordPress/Classes/Utility/Universal Links/Routes+Reader.swift
WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
WordPress/WordPressTest/RouteMatcherTests.swift

Fixes #5149.
This PR adds support for the Reader to present Reader post and feed links in native views (`ReaderDetailViewController` and `ReaderStreamViewController`) instead of web views. To do so, I'm reusing the Reader routing code from our universal links implementation, but I've added an optional `source` view controller parameter. If the navigation is happening _within_ the app, we provide a source view controller, and the navigation can be tweaked accordingly. Both post details and streams should simply be pushed onto the Reader navigation stack.
This PR actually also enables support for other Reader links too, such as `https://wordpress.com/read/search`, which will take the user to the Search section of the Reader. Practically, I figure these kind of links will very rarely ever …

Reader: In-app deep linking for Reader posts and feeds

---

WordPress/Classes/Utility/ContentCoordinator.swift
WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift

This PR continues from #10075. It extends the in-app deep linking for Reader posts and streams to also work for links within Notifications.
**To test**
* Add a comment to a post that will show up in your notifications. You could paste in the following text, which includes a link for each of the things we want to test:
```
Feed: https://wordpress.com/read/feeds/20787116
Feed post: https://wordpress.com/read/feeds/20787116/posts/1972532749
Blog: https://wordpress.com/read/blogs/53424024
Blog post: https://wordpress.com/read/blogs/53424024/posts/34894
```
* Build and run the app, and navigate to that notification
* Tap each of the links in the notification, and check that the appropriate Reader view is pushed.

Notifications: In-app deep linking for Reader posts and feeds

---

WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift

Fixes #9564 
This issue was a bit tricky. It was described as "Lines overlapping each other".
After a quick check, I notice that also an image was missing.
This specific issue (with this posts in particular) is related to three components: **HR**, **IMG**, **Paragraph**
```html
....
<p>
<em>David Llewellyn Dodds, Guest Editor
</em>
</p>
<hr>
<a href="http://apilgriminnarnia.com/?attachment_id=7546">
</a>
It may feel, for the inhabitants of the British Isles, that recent years have been particularly unsettled. The referendum…
```
None of those components are surrounded by `<p>` tags, but all the other components are.
I'm not sure if that is a bug by itself or how was that possible.
A fast test injecting surrounding `<p>` tags to the `img` and `paragraph` solved the issue, so it's clear …

Fix formatting issue on Reader post

---

Podfile
Podfile.lock
WordPress/Classes/Extensions/URL+Helpers.swift
WordPress/Classes/Services/ReaderPostService.h
WordPress/Classes/Services/ReaderPostService.m
WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift

This PR enables the Reader to load blog posts at WordPress.com subdomains in native Reader detail views, instead of web views. 
This works for blog posts hosted at sites with WordPress.com subdomains. In the event we can't load the post, we'll show a no results view, with a button to try and display the post in a web view.
To implement this, I added a new method to `ReaderPostServiceRemote` in `WordPressKit`, which you can find here: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/32
**To test:**
* Create a post in a site you follow with a link to another wp.com post. Also add a fake link to a post or site that doesn't exist. See the gif above for an example of this.
* View the post in the Reader and tap each link in turn, checking that they are loaded (or not) in a Reader …

Reader: Display wpcom blog links in Reader detail views

---

WordPress/Classes/ViewRelated/NUX/SiteCreationEpilogueViewController.swift

#10032 introduced a bug where the push notification primer would dismiss the editor when using the `Write first post` button on a newly created site. The fix is more complicated and will have to wait until after `10.8`, so for now this PR reverts the change.
To test:
- with a fresh install immediately create a new site (try to avoid seeing any push primers)
- at the end of the site creation process, tap "Write first post"
- ensure the editor appears

Fix editor being dismissed after site creation

---

WordPress/Classes/Utility/Media/ImageLoader.swift
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/Media/Giphy/GiphyMedia.swift
WordPress/Classes/ViewRelated/Media/Giphy/GiphyPicker.swift
WordPress/Classes/ViewRelated/Media/Giphy/GiphyService.swift
WordPress/Classes/ViewRelated/Media/MediaPreviewHelper.swift
WordPress/Classes/ViewRelated/Reader/WPImageViewController.h
WordPress/Classes/ViewRelated/Reader/WPImageViewController.m

Implements #10087. This PR adds support for previewing Giphy GIFs after performing a search. Our implementation currently _does not_ support actually importing the GIFs – so the 'add' button when you have some selected won't work.
**To test:**
* Navigate to Media > Tap + >Choose Giphy
* Perform a search, and when the results have loaded:
* Test previewing a single item from the results
* Test previewing a single item by 3d touching
* Test previewing multiple items and swiping between them in the carousel
@bummytime would you be able to review this one, as you worked on gif support? Let me know if you're stacked with other stuff and I can assign someone else instead!

Giphy: Add animated detail preview of gifs

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

This enables AT for all builds configurations. Should be just a formality :)
I've left the feature flag in deliberately, in case something _does_ blow up (hopefully not!) and we need to roll it back. I'll also be working in this area next (letting users claim their free domain), so if nothing blows up I'll clean it up then.
To test:
uhhh. Look at the code and see what it does? 
Bonus scout points for actually building the site in release configuration and making sure it shows up ;)

Enable AT for all build configurations.

---

WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift

Fixes #10094; in this case, a comment including an image is interpreted as having infinite width, resulting in a crash. The issue description includes additional context, including the offending P2 post & Fabric link.
To test:
- Checkout branch & validate that existing tests pass.
- From the _Notifications_ tab within the app, tap or click on the Notification below (I will explicitly mention each reviewer). Note that this crashes prior to the change (e.g., in `develop`). It should not crash on this branch.

Crash Fix : Guard against infinite width on images in Comments

---

WordPress/WordPressNotificationContentExtension/Sources/Views/NotificationContentView.swift

Fixes #10110, which requested some minor adjustments to the sizing & spacing of the gravatar, noticon & subject label in the _Long Look_ notification.
- Verify that the branch builds and existing tests pass.
- Fabricate and send a push notification for testing on-device. The payload for such a notification should include: `mutable-content`,  `note_id`, `category` & `type`. Please contact me if you need assistance with that.
- Confirm that the Long Look rendered matches below.
The appearance may differ slightly based on the user's Dynamic Type settings, but this is what is rendered on an iPhone X with default settings.

Adjusted gravatar-subject alignment and noticon sizing & spacing

---

WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
WordPress/Classes/ViewRelated/Blog/SharingAccountViewController.swift
WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift
WordPress/Classes/ViewRelated/Media/NoResultsViewController+MediaLibrary.swift
WordPress/Classes/ViewRelated/Menus/MenusViewController.m
WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
WordPress/Classes/ViewRelated/Post/PostListViewController.swift
WordPress/Classes/ViewRelated/Tools/TimeZoneSelectorViewController.swift

Ref #9504
In a [previous PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10011), I added the class method `NoResultsViewController:loadingAccessoryView` so each VC wouldn't have to create a `WPAnimatedBox`. This PR updates relevant VCs to use this method.
NOTE: I noticed the loading view on Site Tags is vertically off-center. I'll fix that in a separate PR.
To test:
On a slow network, access each of these loading views. Verify the animated box still appears.

Use No Results View loadingAccessoryView

---

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
WordPress/Classes/ViewRelated/Post/Posts.storyboard

Fixes parts of #9779
This PR replaces the old segmented control on top of the Notifications sections with the new `FilterTabBar` component used on Posts and Pages.
To test:
- Navigate to the Notifications section.
- Check that the filters work properly.
I had a small issue with restoration, where the selected tab was scrolled full to the left, please test that too:
- Run the app from Xcode.
- Select the Likes tab.
- Send the app to the background pressing the device's home button.
- Re-run the app from Xcode.
- Check that the same tab is still selected and the tab bar looks fine.

Update notifications segmented control

---

WordPress/Classes/Utility/iAds/SearchAdsAttribution.swift

This PR updates when SearchAds attribution data is sent to Tracks. Currently, we send attribution data even if the user did not tap on a SearchAd. Now with this update, we will only send Tracks the data if the user actually taps on a SearchAd (determined be inspecting the `iad_attribution` param — see the issue for more details 👇 ).
Fixes #10133
**To test:**
* Make sure the app builds and runs
* Inspect my logic thoroughly 😄 
_Testing beyond this may be a little difficult because of the new filtering put in place on the `wpios_searchads_attribution_detail_received` event._ 
@etoledom Would you mind taking a quick peek at this! Thank you!!!!
/cc @loremattei

Update SearchAdsAttribution logic

---

WordPress/Classes/Utility/HockeyManager.m

This PR solves https://github.com/wordpress-mobile/WordPress-iOS/issues/9942 by adding the "Install" button to the HockeyApp Update dialog. 
The updated dialog now have Install, View details and Ignore options. 
The relevant part of the HockeyApp SDK is documented [here](https://hockeyapp.net/help/sdk/ios/5.1.2/Classes/BITUpdateManager.html#/c:objc(cs)BITUpdateManager(py)showDirectInstallOption).
In order to test:
1. change the App internal version in the _xcconfig_ file  to something older (so that the update manager will show the dialog);
2. build and run the `Release-Internal` configuration ;
3. open the app and verify that all the three options are offered in the dialog.
@koke can I ask you to tackle this small review?

Add direct download button to HockeyApp dialog

---

Podfile
Podfile.lock

Fixes #10135 .
Before merging, a new 1.0.0-beta.25 version of Aztec will be released and integrated.
Please test this PR by editing Gutenberg posts in WP.com and seeing if what you type is maintained.

Updates to a newer version of Aztec for testing.

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift

Fixes #10137.
After some investigation, it turns out that gravatar changes introduced since 1.0.7 were causing a crash on launch. I narrowed down the issue to here, where we override `UIImageView`'s `removeFromSuperview()` method: https://github.com/wordpress-mobile/WordPressUI-iOS/blob/develop/WordPressUI/Extensions/UIImageView%2BGravatar.swift#L82
I guess this has two issues – 1) it doesn't call the `super` implementation, but also 2) because it's an extension and not a subclass it also knocks out whatever `UIImageView`'s implementation of that method is.
We'll have to find an alternative solution to unregistering from notifications – I guess potentially swizzling out that method and ensuring we also call the original could work. cc @nheagy.
For now, I'm reverting this change, to fix …

Fix Login Crash: Revert WordPressUI to 1.0.7

---

Podfile
Podfile.lock

This PR updates WordPressKit to the latest release 1.4.0.
There's no change in the pod itself from the latest beta 3 (just pushing to an official release before WPiOS code freeze).
To Test:
- update the pods;
- check that Podfile.lock doesn't change
- verify that the build has no error.

Update WordPressKit to 1.4.0

---

Podfile
Podfile.lock

Integrates Aztec v1.0.1 into WPiOS.
This release fixes [an issue which was causing edits to Gutenberg posts to be lost](https://github.com/wordpress-mobile/WordPress-iOS/issues/10135).
Make sure that editing a Gutenberg post, and adding text to it, works.

Updates Aztec to 1.0.1.

---

WordPress/WordPressNotificationContentExtension/Info-Alpha.plist
WordPress/WordPressNotificationContentExtension/Info-Internal.plist
WordPress/WordPressNotificationContentExtension/Info.plist
WordPress/WordPressNotificationServiceExtension/Info-Alpha.plist
WordPress/WordPressNotificationServiceExtension/Info-Internal.plist
WordPress/WordPressNotificationServiceExtension/Info.plist

This PR updates the plists files of WordPressNotificationContentExtension and WordPressNotificationServiceExtension to make them use the VERSION_SHORT and VERSION_LONG variables to get the bundle version strings.
Build the project from scratch and verify that no error is raised.

Update the new extensions plists to get the common bundle versions

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/System/FancyAlertViewController+Async.swift

Fixes #10068. This PR introduces slightly different strings for the Aztec 'async publishing' promo screen when scheduling posts and when working with pages.
**To test:**
* Update the `UserDefaults.standard.asyncPromoWasDisplayed` check at the end of `publishPost:action:dismissWhenDone:analyticsStat:` in `AztecPostViewController` so that the promo is always shown – this'll make testing easier!
**Publishing a post**
* Start a new post. Tap Publish, and check the promo reads correctly. It should reference publishing a post.
**Scheduling a post**
* Start a new post. In Post Settings, change the date to the future. Tap Schedule, and check the promo reads correctly. It should reference scheduling a post.
**Publishing a page**
* Start a new **page**. Tap Publish, and check the …

Aztec Async Promo: Update strings for scheduling and for pages

---

WordPress/Classes/ViewRelated/System/WPTabBarController.h
WordPress/Classes/ViewRelated/System/WPTabBarController.m

Fixes a warning that my last PR introduced.
Hound and I had a fight, hound died, I assumed that meant I won.
Hound's ghost got the last laugh.
To test:
- build
- find no warnings about `WPTabBarController.h`

Remove unused method declaration from WPTabBarController.h

---

WordPress/Classes/ViewRelated/System/FilterBar.swift

Based on discussion by Ministry of Magic i changed some UI Appearance aspects fo the FilterBar.
These are the changes:
On Filterbar `fitting` mode:
- Bottom divider 0.5 pt
- Selection Indicator width as the whole button width
- No horizontal padding
- Text with bold trait
@SylvesterWilmott

FilterBar style

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

**The Bug:**
At the moment, given a Post/Page, if a user select `Pending review` as status from the settings, the Post/Page status is forced to be `draft`.
**Fix:**
The problem was within `AztecPostViewController`, line `1218`. If the context action is `save` or `saveAsDraft` then the post status is `draft`.
Talking also with @diegoreymendez , the solution is:
- `save` should not change the status
- `save as draft` is an explicit action, so it's fine it sets the state to draft
**To test:**
- Change the Post/Page status to `Pending review`
P.S.
I'm not sure if the `save` action forced the status as draft for some reason. If so let me know so I can add some logici within the if statement.

Post status as draft even if Pending review was selected

---

Podfile
Podfile.lock

This updates fixes the issue related to copy/paste of URLs to the editor
To test:
- Open the app
- Create or edit a post
- Copy an URL from Safari
- Paste on the post
- Check that the link shows correctly
- Write some text
- Select the text
- Paste the URL
- Check that the link is applied to the selected text.

Update Aztec to 1.0.2

---

WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift

Fixes #10156 
NOTE: There is an existing issue where there is extra space between the search bar and collection view (#9730). This plays havok with the view layout a bit. So, while this view is displayed properly initially, it will become misplaced if you rotate and/or toggle the keyboard.
"this view is displayed properly initially" means when the search bar is tapped, the keyboard automatically shows. Then when a search is performed, the 'No themes matching your search' view is where it's supposed to be.
To test:
- Go to site > Themes > search.
- Enter an invalid search term.

Theme search: update no results view

---

WordPress/Classes/ViewRelated/Reader/NewsCard.swift
WordPress/Classes/ViewRelated/Reader/NewsCard.xib

Fixes #10183 
Clears an auto layout warning:
> warning: Attribute Unavailable: Leading or Trailing horizontal alignment before iOS 11.0
The fix: changing the Read More button's constraints from this:
to this:
To test:
- Checkout the branch and build. There should not be any auto layout warnings
cc @elibud

Fix auto layout warning in News Card

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
WordPress/Classes/ViewRelated/Blog/SiteIconPickerPresenter.swift
WordPress/Classes/ViewRelated/Media/Giphy/GiphyPicker.swift
WordPress/Classes/ViewRelated/Media/Giphy/GiphyStrings.swift
WordPress/Classes/ViewRelated/Media/Giphy/NoResultsGiphyConfiguration.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
WordPress/Classes/ViewRelated/Media/NoResultsViewController+MediaLibrary.swift
WordPress/Classes/ViewRelated/Media/Stock Photos/NoResultsStockPhotosConfiguration.swift
WordPress/Classes/ViewRelated/Media/Stock Photos/StockPhotosPicker.swift
WordPress/Classes/ViewRelated/Media/Stock Photos/StockPhotosStrings.swift
WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m

Fixes #10178 
In all places one can search for Media, this updates the search no results view to only show the message.
NOTE: 
This has a corresponding `WPMediaPicker` PR - https://github.com/wordpress-mobile/MediaPicker-iOS/pull/309.
This `podfile` version will be updated when that is merged.
To test:
All of these searches should result in the same view. That is, a `No media matching your search` message static at the top of the view. Example:
Searches:

Media searches: update no results view

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift

Fixes #10182
On views where the empty view contains an action button, this removes the '+' button from the navigation bar.
To test:
All these views should behave the same way.
- If there is no content, or content is removed, the nav bar add button does not appear. The empty view action button handles that.
- When there is content, or content is added, the nav bar add button appears.
---
**Site Tags and Media Library:**
- Add/remove content. 
- Verify the nav bar add button shows accordingly.
---
**Site Pages and Blog Posts:**
- Add/remove content. 
- Select the different filters across the top.
- Verify the nav bar add button shows accordingly.

Remove navigation bar button when empty view has an action button

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
WordPress/Classes/ViewRelated/NUX/SiteCreationEpilogueViewController.swift
WordPress/Classes/ViewRelated/System/FancyAlertViewController+QuickStart.swift

Refs #9447
This adds the third "never" option to the quick start alert.
To test:
- create a new `wpcom` site
- after you're done, the alert should appear, ensure it has all three buttons
- tap "never"
- create another site
- ensure that the alert does _not_ appear, as it is now dismissed forever.

Quick Start: Add never button to alert

---

WordPress.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
WordPress/Classes/ViewRelated/Notifications/Tools/KeyboardDismissHelper.swift
WordPress/Classes/ViewRelated/Plugins/PluginViewController.swift
WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift
WordPress/Classes/ViewRelated/Themes/ThemeBrowserHeaderView.swift
WordPress/Classes/ViewRelated/Views/WPRichText/NSAttributedString+WPRichText.swift
WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift
WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme
WordPress/WordPressTest/MediaAssetExporterTests.swift
WordPress/WordPressTest/NotificationSyncMediatorTests.swift
WordPress/WordPressTest/StockPhotosDataSourceTests.swift
WordPress/WordPressTodayWidget/TodayViewController.swift

Contributes to the resolution of #10149.
Specifically, this PR addresses the following:
1. Resolves several outstanding Hound warnings noted in the [current PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10175)
1. Reverts the Workspace back to using the Legacy build system
1. Explicitly re-enables a missing test from the `WordPress` scheme : `NotificationSyncMediatorTests/testMultipleSyncCallsWontInsertDuplicateNotes()`
1. Comments out two failing tests encountered by BuddyBuild.
To test:
- Checkout the branch and verify that enabled tests pass
- Observe that CI builds pass once again

Xcode 10 / Swift 4.2 transition assistance

---

.hound.yml
.swiftlint.yml
Dangerfile
Gemfile
Gemfile.lock
WordPress/Classes/System/WordPressAppDelegate+Swift.swift
WordPress/Classes/Utility/Debouncer.swift
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

This PR continues work started [previously](https://github.com/wordpress-mobile/WordPress-iOS/pull/10072). It integrates [`danger-swiftlint`](https://github.com/ashfurrow/danger-swiftlint) with our existing `Dangerfile`, paving the way for the retirement of Hound.
I made a few changes to `.swiftlint.yml`; namely, I removed some superfluous comments and I modified the lists of `included` & `excluded` project directories. Without this change, BuddyBuild was reporting the following error:
```
No lintable files found at path '/private/tmp/sandbox/workspace/WordPress/<path_to_Swift_file>'
```
At the moment, some fabricated Hound violations were added to the PR. These should be addressed prior to merging the change.
Finally, Danger SwiftLint offers both a default and an "inline" mode for …

Try adding Swiftlint to Danger again

---

Gemfile
Gemfile.lock

Github flagged a vulnerability in the version of rubyzip showing up in our Gemfile.lock. Its a dependency of Fastlane and it looks like we have some discretion of which version it will accept so let's increment to what Github recomments and see if it fixes the issue.

Specify rubyzip version to address vulnerability

---

.hound.yml
.swiftlint.yml

After conversing with staff at Hound, they noted that our previous `.hound.yml` (intact since January) differs from what they expect. Apparently they have updated their [documentation](https://intercom.help/hound/configuration/swiftlint) today (and behavior, presumably) to use a different key (i.e., `swiftlint` instead of `swift`).
The new file closely resembles the [previous one](https://github.com/wordpress-mobile/WordPress-iOS/blob/release/10.9/.hound.yml).
In addition to this change, I have also restored the GitHub webhook.
We can continue to evaluate `danger-swiftlint`, with inline comments as our ideal end state.
- https://intercom.help/hound/configuration/rubocop
- https://intercom.help/hound/configuration/swiftlint

Corrected Hound configuration

---

Podfile
Podfile.lock

Zendesk has released a [new framework version](https://github.com/zendesk/zendesk_sdk_ios/releases/tag/2.2.0) with explicit support for Xcode 10. This PR updates the `Podfile` to account for this.
The branch should build and existing tests should pass.

Update Podfile to reference an official Zendesk release

---

WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift

When we call `post` in ReaderFollowedSitesViewController off of the main thread, it causes a crash over in https://github.com/wordpress-mobile/WordPress-iOS/blob/4ac54edd8c4db2978a0122f97e137c755e627d4a/WordPressFlux/WordPressFlux/Sources/Dispatcher.swift#L61 due to an unmet assertion.
To test:
**Before** 
In the current version of the app, navigate to Reader > Manage and in the "Enter the URL..." box, type a completely garbage URL that won't resolve.
The app will attempt to add that site to the reader, then will crash.
**After**
The app will show a warning message, typically saying "A server with the specific hostname could not be found".
**Next Steps**
The error message from `error.localizedDescription` can be pretty verbose, and it's cut off when the bottom prompt shows up.

Fix crash caused by posting a notice off the main thread

---

WordPress/WordPressUITests/gencredentials.rb

If a user has a configuration file that looks like:
`key=` (no space following the `=`)
the script crashes, as there’s no second element.
This fixes that issue.
One side-effect: blank lines aren’t preserved when generating the output .swift file.
**To test:** 
Try adding a key in your ~/.wp_com_test_credentials (or similar file) that looks like:
`foo=` (no space after the equals sign).
That'll cause a crash.
Run it with this patch, and it'll just add the key with an empty value.

Fix a crash when generating credentials

---

WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift

To test:
**Before:**
In Reader > Followed Sites > Manage, when a user types a URL into the search bar to add it to the list, it doesn't use the URL keyboard, which is a minor annoyance.
**After**
Now the user gets a nice URL keyboard instead.

Use the URL keyboard when adding a followed site

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift

The following events were added:
notifications_replied_to - When a user replies to a notification comment
reader_article_comment_liked - when a user likes article comment
reader_article_comment_unliked - when a user unlikes article comment  (taps like button while it's selected)
reader_article_comments_opened - when the article comments are opened
reader_article_detail_liked - when the user opens an article and tap like
reader_article_detail_unliked - when a user opens an article and tap unlike (tap like button again while it's selected)
Fixes #10154 
To test:
*Notifications replied to*
1. Go to notifications tab
2. tap on a notification
3. write a reply
4. tap reply
*Reader Article Liked*
1. Go to Reader tab
2. Choose an article with comments
3. Tap the comments icon
4. Tap the Like icon …

Added missing tracking events

---

WordPress/Classes/ViewRelated/Reader/Reader.storyboard
WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderTableConfiguration.swift

Fixes #9997 (and #9745 )
Related: #9900
This PR attempts to solve a crash on the `ReaderStreamViewController` that could happen when attempting to `displayResultsStatus`. This `resultsStatusView` is a `NoResultsViewController` instance that is used to show the state of the controller (loading, no data, error, etc...).
Please note that this PR tries to merge to `release/11.0`
- The `ReaderStreamViewController` is a parent controller of a plane `UITableViewController`, that was being loaded from storyboard. This means that this outlet will be `nil` from the controller's init, until the `prepare(for segue:sender:)` method is called (there is where the reference is captured).
- This reference to the `tableViewController` was declared as `implicitly unwrapped`. ⚠️
- The …

Proposal to fix crash on ReaderStreamViewController

---

WordPress/Classes/ViewRelated/Pages/PageListTableViewHandler.swift
WordPress/Classes/ViewRelated/Pages/PageListViewController.swift

This PR fix a bug when you try to move a page to Draft from the Publish filter: the list doesn't reload.
**To test:**
- From the pages list -> filter Published -> Set a page as Draft. You should see the table updated correctly.
@loremattei can we include this fix into 11.0?

Fix problem when a page is saved as Draft

---

WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib
WordPress/Classes/ViewRelated/Pages/PageListViewController.swift

This PR fix a problem with the cell indentation, replacing the leading constraint with frame.
**To test:**
- If a pages list (Published filter) has child pages, then it shouldn't loose indentation switching section or doing some other action.

Use frame instead of constraint

---

WordPress/Classes/ViewRelated/Notifications/FormattableContent/Notifiable.swift
WordPress/WordPressNotificationContentExtension/Info-Alpha.plist
WordPress/WordPressNotificationContentExtension/Info-Internal.plist
WordPress/WordPressNotificationContentExtension/Info.plist
WordPress/WordPressNotificationServiceExtension/Sources/FormattableContent/RemoteNotificationStyles.swift
WordPress/WordPressNotificationServiceExtension/Sources/FormattableContent/RichNotificationContentFormatter.swift
WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift

Fixes #10101, which allows _Mentions_ to join _Comments_ in the class of rich notifications we support. 
This PR consists of the following changes:
1. Tidies up some code formatting for consistency, particular with regard to multiline control statements. Team convention was point out to me [elsewhere](https://github.com/wordpress-mobile/WordPress-iOS/pull/10066).
1. Modifies the formattable content styling to account for more notification types.
1. Exposes `automattcher` as a category identifier so that _Mention_ notifications can be presented in the Long Look.
First, confirm that the branch builds & existing test pass. Next, validate the successful receipt & rendering of _Mention_ notifications.
Push notifications tend to require manual testing. This can be exercised by triggering …

Added rich notification support for Mentions

---

WordPress/Classes/ViewRelated/Pages/PageListTableViewHandler.swift
WordPress/Classes/ViewRelated/Pages/PageListViewController.swift

This PR fix #10254 
@rachelmcr found a bug related to the *Set Parent* action: *on that screen, the pages list for setting a parent page includes pages from other sites I own.*
**To test:**
- Try to set a parent page
- You should see only published pages for that specific blog

Fix pages list including blog predicate

---

WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift

This PR fix a problem related to the Undo action after a page has been moved to the trash:
*Problem:*
Given a Page, if a user decide to move it to Trash, then decide to Undo, the tableview doesn't reload.
**To test:**
1. Move a page to Trash
2. Press on Undo
3. The tableview should reload and you should see the Page cell again

Fix Undo action 

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

Fixes #10176  
To test:
• New Post *	
-      Create a new post
-      Type something in title
-      Type something in text view.
-      Tap on the 3 dots menu in the top right corner.
-      See the title of the action sheet shows the number of words and characters .
• Editing post *
-      open an existing post
-      Tap on the 3 dots menu in the top right corner
-      See the title of the action sheet shows the number of words and characters .
-      Continue editing.
-      Tap on the 3 dots menu in the top right corner.
-      See the title of the action sheet shows the updated number of words and characters.

Added Action sheet title that shows word and character count

---

WordPress/Classes/ViewRelated/Views/NoResults.storyboard

Fixes #10249 
To test:
----
- NOTE: I could only get the bug to trigger after running the app, hiding all sites, then relaunching the app. Please try those steps when testing. 
- On an account with all sites hidden, go to My Sites.
- Verify the text is not truncated, and wraps properly.
---
- Go to Notifications.
- Select any tab with no notifications.
- Verify the text is not truncated, and wraps properly.

Empty States: fix truncated text.

---

WordPress/Classes/Utility/InteractiveNotificationsManager.swift

Addresses #6256, which observes that analytics are not captured when a user interacts with a push notification via custom actions.
To test:
- Whether through manual push notification delivery or a fabricated payload, at least three push notifications must be initiated to validate that each of the three events noted in the issue..
- To ensure that the appropriate action can be exercised, the `category` for the APNS payload must match [one of the following values](https://github.com/wordpress-mobile/WordPress-iOS/blob/593a6719ea2cc7df7f0541cd63b8003e3845fdb8/WordPress/Classes/Utility/InteractiveNotificationsManager.swift#L259-L262).
- Once each action has been initiated, visit _Tracks Live View_ and confirm that each of the following three events can be found: …

Capture analytics for push notification actions

---

WordPress/Classes/Stores/NoticeStore.swift
WordPress/Classes/System/WordPress-Bridging-Header.h
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
WordPress/Classes/ViewRelated/Blog/QuickStartNavigationWatcher.swift
WordPress/Classes/ViewRelated/Blog/QuickStartSpotlightView.swift
WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
WordPress/Classes/ViewRelated/Blog/SharingViewController.m
WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
WordPress/Classes/ViewRelated/System/WPTabBarController+QuickStart.swift
WordPress/Classes/ViewRelated/System/WPTabBarController.h
WordPress/Classes/ViewRelated/System/WPTabBarController.m
WordPress/Classes/ViewRelated/Themes/ThemeBrowserHeaderView.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Refs #9447
This adds the three final tours for Quick Start.
To test:
- Setup a site with Quick Start enabled (either create a new site or get my snippet)
- go through the three new tours
- the followers tour should be resilient to leaving the reader tab in different states _before_ starting the tour. check it out!
- test on ipad, too
Do you mind doing this since you're already familiar with it, @etoledom?

Quick Start: add the last three tours

---

WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
WordPress/Classes/ViewRelated/Notifications/Tools/KeyboardDismissHelper.swift
WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift

Fixes #10207 #10260 
To test:
---
Reader > Post > Comments > no comments (#10207)
- On a site that has followed sites, go to Reader > Followed Sites > Manage.
- Select a site that has a post with no comments.
- Press the comment icon on the post with no comments.
With the keyboard visible (tap in the reply field):
---
Reader > Manage > no followed sites (#10260)
- On a site that has not followed sites, go to Reader > Manage Sites.
With the keyboard visible (tap in the URL field):
- Note: there is still spacing issues in iPhone landscape. Sylvester is looking into the padding, so I'll save this for another day.

Reader empty states: adjust empty view for keyboard

---

README.md
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/buddybuild_prebuild.sh

This PR changes the expected path for the credential files. The new path let the build system to pick the files from the dedicated repository.
To Test:
1. Verify that the `ApiCredentials.m` into the `Derived Sources` folder contains the correct data after a build;
2. In theory, the previous point should be enough, but  verify that the app can access the relevant services (WP, Google Login, Crashlytics, Hockey, Zendesk) or at least a few of them won't hurt :-) 
@aerych can I bother you with this review?

Move credential files to the dedicated repository

---

WordPress/Classes/Utility/Analytics/WPAppAnalytics.h
WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
WordPress/Classes/Utility/InteractiveNotificationsManager.swift

Resolves a new facet of #6256. After [the last PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10280), a request was made via `p4qSXL-2RE-p2` to ensure that `blogid` was included in the event properties.
The [Android PR](https://github.com/wordpress-mobile/WordPress-Android/pull/8454) took the liberty to explicitly include the following attributes: `blog_id`, `is_jetpack`, `post_id`, comment_id`. 
_This_ PR explicitly sets both the blog ID & comment ID, as that information is readily available in the APNS payload. Unfortunately, however, `post_id` is not. In my testing, `is_jetpack` is included in the Tracks data implicitly.
- Checkout the branch and verify that existing tests pass.
- Follow the same testing steps as in the [prior …

Capture more analytics info for push notification actions

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
WordPress/Classes/ViewRelated/NUX/SiteCreationEpilogueViewController.swift
WordPress/Classes/ViewRelated/System/FancyAlertViewController+QuickStart.swift

Refs #9447
This adds the analytics events for Quick Start.
Run through various quick start tasks and check that the events are being logged. I can provide a references to the events that android is using.
Thanks @aerych!
This is targetting the previous QS branch until that one is merged 👍

Quick Start: add analytics events

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Fixes #9447
This PR turns on Quick Start for everyone.
To test:
- I dunno, make a non-developer build and ensure quick start appears?

Turn on Quick Start for everyone

---

Podfile
Podfile.lock
WordPress/WordPress.xcodeproj/project.pbxproj

This PR updates the Aztec reference to the last commit on `develop`.
To test:
- Overal functionality of Aztec Editor.
- Pasting from Notes App.
- Pasting from Google Docs

Updating Aztec reference to pre-release hash (for release v1.1)

---

WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift

This PR restricts swallowed taps to just those that will be used by the NoticeView itself.
Fixes #10298
To test:
- ensure that "View Site" is now tappable on iPad (see #10298 for an example)
- ensure that notices are still tappable:
- Quick Start "suggestion" notices
- Async post notices
- ensure that the above still work on iPhone

Quick Start: Fix notice view container from swallowing all taps

---

Scripts/fastlane/helpers/ios_git_helper.rb

This is a small change to our localization automation to only add `.strings` files to git. It eliminates the risk of committing unrelated changes.

Only add .strings files to git when updating translations

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/FeatureFlagTests.swift

Fixes #10312.
- New `FeatureFlagTests` should also pass.
Additionally, exercise the following _manual_ steps:
1. Launch the app in `Debug` build configuration.
1. Ensure that the user has signed in to WordPress.
1. From the _My Sites_ tab, tap the **+** in the right bar button item and select "Create WordPress.com site".
1. Visually confirm that the existing Site Creation flow remains intact.
To validate that the feature flag is recognized, consider setting a breakpoint [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/1925c6372518bc6617192d470eb25f698421b930/WordPress/Classes/ViewRelated/Blog/BlogListViewController.m#L902), and observing that the `if` block is entered.

Introduced feature flag for enhanced site creation

---

Scripts/fastlane/actions/ios_finalize_prechecks.rb
Scripts/fastlane/actions/ios_update_metadata_source.rb

Some Fastlane lanes (such as `finalize_release`) don't check for a clean git status. This can lead to accidental commits.
This PR adds the `ensure_git_status_clean` check to the two actions that were missing it.
To test:
These lanes still work as expected:
- `bundle exec fastlane finalize_release`
- `bundle exec fastlane update_appstore_strings`

Fastlane: Added check for clean git status to remaining lanes

---

MIGRATIONS.md
WordPress/Classes/Models/AbstractPost.h
WordPress/Classes/Models/AbstractPost.m
WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
WordPress/Classes/WordPress.xcdatamodeld/WordPress 82.xcdatamodel/contents
WordPress/WordPress.xcodeproj/project.pbxproj

This PR introduces:
- `WordPressKit 1.4.3-beta.2` with the new *revisions* property mapped for `RemotePost`.
- New *CoreData* model version *82*
- New *revisions* property for `AbstractPost` entity.
- `AbstractPost` model has a new *revisions* property.
- New entity `Revision`:  it will contain the data of a *post* revision, like title, content, date etc...
- New entity `RevisionDiff`: it will contain the data for a *revision diff*, like the amount of additions or deletions and the revision id it refers to.
- New entities `RevisionDiffAbstractValue`, `RevisionDiffContentValue`, `RevisionDiffTitleValue`: these will contain the type of change and the operation type.
**To test:**
- Run the app over any branch with CoreData model version 81
- CoreData migration should work with no problem
- …

History / Revision: new CoreData model version

---

WordPress/WordPress.xcodeproj/project.pbxproj

This changes the location of `Derived Sources` to outside the repo and into `BUILT_PRODUCTS_DIR` which is within derived data.
The build phase will also delete `WordPress/Derived Sources` so there is no chance of accidental commits. I have intentionally not removed the `.gitignore` entry for the same reason.
We should be careful about this change since it is in a sensitive area.
To test:
I have tested this in as many ways as I can think but it would be good to verify across multiple machines. I will test the following before merging:
- All build configurations (Debug, Release etc.)
- Different derived data locations (e.g. Relative to project, unique etc.)

Place 'Derived Sources' relative to BUILT_PRODUCTS_DIR

---

WordPress/Classes/Services/PostService.m

Refs #10304
This small PR map the *revisions* array from the *RemotePost* to the local *AbstractPost* within the local service. If the post doesn't have a revisions history, then it will be nil.
**To test:**
No action has been added here, so at the moment you can test if the blog list page works as before.
Select a blog, then select *Blog Posts*, and see if the list works correctly.

History / Revisions: Assign the revisions array to the local post

---

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift

Fixes #10356
This PR removes the code setting the reader stream's refresh control to a zero frame. I'm not too sure why we were doing this. There doesn't appear to be any visual consequence of removing this. @etoledom I wonder if you'd noticed anything?
To test:
Confirm the issue by attempting to pull to refresh. (The latest beta is affected.)
Apply this branch and repeat the test. Confirm that pull to refresh functions as expected.
Look sharp at the reader stream for any visual artifacts from this change.
@etoledom could I trouble you for a review?

Reader: don't set refresh control to zero frame

---

WordPress/Classes/ViewRelated/Plans/PlanComparisonViewController.swift

Fixes #10331 
This PR fixes the crash reported in #10331 by not unwrapping the optional when its nil.  Not sure how this one slipped past us -- I'd have sworn we also tested the detail pages when patching the original issue. 
To test:
Apply the patch and test the plans feature, list + detail screens, with multiple blogs on different plans.  At least one of the blogs should be on a plan other than the four default plans passed by the `v1.2/sites/site/plans` endpoint.  Ping me and I'll invite you to a test blog if you like.
@stevebaranski could I trouble you with this one?

Plans: Don't unwrap optional during assignment.

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

Fixes #10306 
The problem was the `No media matching your search` view was trying to display after a search was previously performed.
This adds a check to ensure `searchQuery` has a value before displaying the no results view.
To test:
- Edit a post.
- Press `+`, and select the WP Media Library. 
- Enter an invalid search term (to get the `No media matching your search` message).
- `Cancel` the search via the _nav bar_.
- Go back to the WP Media Library and insert an image.
- Go back to the WP Media Library again. (This is when the crash was occurring.)
- Verify it doesn't crash.
- Insert images to your ❤️ s delight.

Post Editor media search: Check for search query before showing no results view

---

WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
WordPress/Classes/ViewRelated/Views/WPRichText/WPTextAttachmentManager.swift

Fixes #6040 (partially) and #3027 (possibly)
When laying out attachment views, the layoutAttachmentViewForAttachment method would be called for each attachment. The resulted in nice, clean code, but it called layoutManager.ensureLayout for every layout attachment, which forces synchronous re-layout for each attachment. When there are many images in a post, this would take several seconds of main thread work to do the layout.
Batching the layout work for attachments and only calling ensureLayout once removes a lot of layout work for the device. This should resolve the "slow to load" and "crashing on old devices" issues in many cases. However, it doesn't resolve the memory issues.
To test:
Add mcraeblog.com to reader.
Choose the post called "Silo Art".
Before
The tile would be outlined, …

Fix slow reader loading with many images

---

WordPress/Classes/ViewRelated/Stats/LatestPostSummaryCell.swift
WordPress/Classes/ViewRelated/Stats/LatestPostSummaryCell.xib
WordPress/Classes/ViewRelated/Stats/SiteStatsDashboard.storyboard
WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/StatsViewController.m
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #10366 
This adds a `SiteStatsInsightsTableViewController` that displays the initial `Latest Post Summary` view (`LatestPostSummaryCell` class and xib).
- It shows the initial view as designed in Zeplin.
- Displays a temporary label where the chart will eventually be.
- The progress view is updated as the data is loading.
- Refresh control to reload the data.
NOTES:
- There are follow-up tasks to complete this feature. Please let me know if something's missing and there isn't an issue to cover it.
- https://github.com/wordpress-mobile/WordPress-iOS/issues/10372 - alternate views
- https://github.com/wordpress-mobile/WordPress-iOS/issues/10373 - tappable text areas
- https://github.com/wordpress-mobile/WordPress-iOS/issues/10374 - dynamic rows
- …

Stats Refresh: add initial Insights 'Latest Post Summary' view

---

WordPress/Classes/ViewRelated/Stats/SiteStatsDashboard.storyboard
WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsInsightsTableViewController.swift

Refs: #10379  #10380 
Since we'll be adding loading views with the referenced issues, the loading progress indicator is no longer needed. Tis nixed!
To test:
- Go to Stats > Insights.
- Verify the progress indicator no longer appears under the filter bar.

Stats Refresh: Remove loading progress indicator.

---

WordPress/Credentials/ApiCredentials.h
WordPress/Credentials/ApiCredentials.m
WordPress/Credentials/gencredentials.rb

Some items in `ApiCredentials` are no longer used so can be removed:
- `pocketConsumerKey`
- `googlePlusClientId`
Additionally, the `hockeyappAppId` is only used in a few build configurations we have a preprocessor definition `HOCKEYAPP_ENABLED` for this. This changes uses that in `ApiCredentials.m` also.
To test:
- Build the app. `ApiCredentials.m` should be generated successfully without `pocketConsumerKey`/`googlePlusClientId` and with the `#ifdef` for `hockeyappAppId`.

Removed unused credentials from ApiCredentials

---

Podfile
Podfile.lock

Updating WordPress internal pods to the final versions.

Update pods to final versions for 11.2 code freeze

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Fixes #10092 
To test: Make sure the giphy option shows up in the more options section for media

Turning on giphy for everyone

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

Fixes #10389 .
Since this have been working from 2017, and now after the Xcode update it started crashing, we could assume that there's a bug introduced on this new Xcode version.
The crash happens at `swift_objc_classCopyFixupHandler`. It seems to be a private API and I couldn't find anything about it, or crashes related to it. (Even though it says it comes from `libswiftCore.dylib` 🤔 )
Searching about Xcode 10.1 KVO related issues didn't help either.
Xcode 10.1 [release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_1_release_notes/) didn't show relevant information.
Bottom line, I couldn't find information that could help.
Since this seems to be related to `swift_objc` interoperability, one of my first tests was to see if it crashes when there's no swift …

Workaround proposal to fix crash building with Xcode 10.1

---

WordPress/SwiftPlayground.playground/contents.xcplayground
WordPress/SwiftPlayground.playground/section-1.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Navigating to `SwiftPlayground` in the project evinces the following Xcode error.
Removing this file eliminates the error, and it does not contain any WordPress-specific content.

Removed unused Swift playground from the project

---

WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift

Our deployment target is set to iOS 10, so this PR removes `available` checks against iOS 10. Only one was found within our app. 
Verify that the branch builds and tests pass.

Removed obsolete available check

---

WordPress/Classes/Services/AccountService.m
WordPress/Classes/Services/ShareExtensionService.swift
WordPress/Classes/Services/TodayExtensionService.m
WordPress/Classes/System/WordPressAppDelegate+Swift.swift
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
WordPress/Classes/Utility/Migrations/10-11/BlogToAccount.m
WordPress/Classes/Utility/Migrations/20-21/AccountToAccount20to21.swift
WordPress/Classes/Utility/Migrations/AccountToAccount22to23.swift
WordPress/Classes/Utility/PushNotificationsManager.swift
WordPress/Classes/Utility/ZendeskUtils.swift
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift

Our deployment target is set to iOS 10, so this PR removes `available` checks against iOS 10. Only one was found within our app. 
The `synchronize` method in `NSUserDefaults.h` was updated in iOS 10 with the following:
```
/*!
-synchronize is deprecated and will be marked with the NS_DEPRECATED macro in a future release.
-synchronize blocks the calling thread until all in-progress set operations have completed. This is no longer necessary. Replacements for previous uses of -synchronize depend on what the intent of calling synchronize was. If you synchronized...
- ...before reading in order to fetch updated values: remove the synchronize call
- ...after writing in order to notify another program to read: the other program can use KVO to observe the default without …
```

Removed superfluous calls to synchronize via UserDefaults

---

WordPress/Classes/ViewRelated/Views/NoResults.storyboard

This resolves a warning observed in the console that reads as follows:
```
Failed to set (isPrimary) user defined inspected property on (UIButton): [<UIButton 0x7fa0bb4fa760> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key isPrimary.
```
The culprit appears to be this:
Perhaps it was copied from another storyboard or XIB that used either a [`NUXButton`](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/develop/WordPressAuthenticator/NUX/NUXButton.swift#L53) or [`FancyButton`](https://github.com/wordpress-mobile/WordPressUI-iOS/blob/9607c540faf8368d0c1658963b96f8c8552830b6/WordPressUI/FancyAlert/FancyButton.swift#L104)?
1. From **`develop`**, launch the app and search for the console warning noted above.
1. Checkout …

Address isPrimary console warning

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
WordPress/Classes/ViewRelated/System/WPTabBarController+QuickStart.swift
WordPress/Classes/ViewRelated/System/WPTabBarController.m

Fixes #10398
If the user goes somewhere outside the given tour, it automatically ends.
To test:
- start a tour
- ignore it, go somewhere else in the app
- ensure the notice is dismissed

Quick Start: cancel tours when user navigates away

---

Rakefile
Scripts/fastlane/actions/ios_build_preflight.rb

`IosBuildPreflightAction` which is triggered from several lanes currently calls `rake clobber` and `rake dependencies`. This causes crashes if `fastlane` was invoked with `bundle exec` because Fastlane is trying to replace its own binary.
I have made some small changes to it:
- Instead of clobbering gems, the action checks if they are up to date and errors out if not.
- Pods are cleared and reinstalled, but not gems.
The downside of this is that we are not as confident that gems are 100% fresh. However, not running with `bundle exec` is worse because it just uses whatever gems happen to be installed systemwide.
To test:
- Run `bundle exec fastlane run ios_build_preflight` to verify the action works correctly.

Allow Fastlane lanes to be run with 'bundle exec'

---

WordPress/Classes/ViewRelated/People/People.storyboard
WordPress/Classes/ViewRelated/People/PeopleViewController.swift

Fixes #9779, which called for the `FilterTabBar` to be integrated in new places, including the _People_ view.
1. Checkout the branch and verify that existing tests pass.
1. Navigate to _My Sites : Site : People_ and confirm that the appropriate filter tab bar is presented. It might be worthwhile to review in the Simulator to confirm that no constraint warnings are presented. (Note that _Viewers_ should only be visible on private sites.)
1. Verify that the results update when you select different choices, and that the _No Results_ view is appropriately centered when presented.
_Before_
_After_

Transitioned People view to use the Filter bar

---

MIGRATIONS.md
WordPress/Classes/Models/Blog+BlogAuthors.swift
WordPress/Classes/Models/BlogAuthor.swift
WordPress/Classes/Services/BlogService+BlogAuthors.swift
WordPress/Classes/Services/BlogService.m
WordPress/Classes/Services/PostService+Revisions.swift
WordPress/Classes/Utility/CoreDataHelper.swift
WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
WordPress/Classes/WordPress.xcdatamodeld/WordPress 84.xcdatamodel/contents
WordPress/Classes/WordPress.xcdatamodeld/WordPress 85.xcdatamodel/contents
WordPress/WordPress.xcodeproj/project.pbxproj

Refs. #10304 
This PR adds a new *CoreData model version*: **85**
The Revision Cell needs to display the Author avatar and the username.
Following the [Android approach](https://github.com/wordpress-mobile/WordPress-Android/pull/8465) I saw the app already uses that `/sites/$site/users` endpoint when a *Blog* is synced.
Speaking with @aerych the best solution was to add a new _Entity_ to store the authors within that response block. This will allow us to sync only the _Revisions_ and have all the authors informations we need before display the Revisions list.
The new entity is called `BlogAuthor`.
The `Blog` entity has a new property _authors_.
**To test:**
- Install this PR over a pre installed version which contains the previous data model version to test the migration
- Select …

History / Revisions: CoreData model version 85 and Blog authors

---

Scripts/fastlane/actions/ios_build_preflight.rb

This removes the risk that `~/.mobile-secrets` is out of date if using a git repo to track changes in it. If its not a git repo, this does nothing.
@loremattei This is a proposal. If you would prefer the pull to be manual, I'm open to not making this change.
To test:
- `bundle exec fastlane run ios_build_preflight` should now update `~/.mobile-secrets`.

Fastlane: ensure secrets are up to date in build preflight

---

Podfile.lock
WordPress/RN/Gutenberg/GutenbergController.swift
WordPress/RN/Gutenberg/GutenbergMediaPickerHelper.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/EditorSettingsTests.swift

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/192
This has child PRs so we need to merge them first:
https://github.com/wordpress-mobile/gutenberg-mobile/pull/229 (merged)
https://github.com/WordPress/gutenberg/pull/11635 (merged)
https://github.com/WordPress/gutenberg/pull/11660 (merged)
To test:
- Clone the WordPress-iOs project, checkout branch try/gutenberg-mediapicker.
- git submodule init --update (clone this project as submodule of WPiOS)
- cd Gutenberg -> This project (and not gutenberg-web)
- All the normal steps to make gutenberg-mobile work. (yarn install... yarn start etc...)
- Go to the WPiOS root folder and pod install.
- Build and run the project on XCode.
Test 1:
- Open a post, add an image block
- Tap Media library and select an image
- Verify that the …

Handle gutenberg request "open media picker"

---

Podfile
Podfile.lock
Podspecs/React.podspec.json
Podspecs/yoga.podspec.json
WordPress/WordPress.xcodeproj/project.pbxproj

This PR implement the changes from https://github.com/wordpress-mobile/gutenberg-mobile/pull/231
We also add the default ReactNative script to build a release app.
This works automagically bundling the Gutenberg app in WPiOS when building for Release, so Metro is not needed. 
(cc @hypest )
**To test CocoaPods:**
- Checkout this branch.
- Clean build folder/derived data/Pods folder.
- Run `pod install`.
- ☝️should succeed.
- Run metro (`cd Gutenberg && yarn install && yarn start`)
- Run the iOS App.
- Check that Gutenberg load from the Metro server. (With the green top loading bar)
- Check that `cmd + R` and `cmd + D` work as expected.
**Test Release build:**
- Be sure that Metro is **not** running.
- Edit the WordPress scheme in Xcode:
- In the `Run` section -> Build Configuration: …

Gutenberg build for production.

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

What it says in the title.
To test:
Look at the code, verify that it looks correct
To test if you‘re an overachiever:
Build a „Release“ build of the app
Have a Biz site with a free domain credit (and no custom domain associated)
Go to Plugins on that site
Verify that the popup prompting you to set a custom domain shows up

Change the feature flag of custom domains to relase it to everyone.

---

Gemfile
Gemfile.lock

The CocoaPods plugin I introduced the other day has so far been working smoothly 😅 
However, @jklausa brought a case to my attention where CocoaPods could fail with a different error so the plugin didn't know that specs should be updated. This is a BuddyBuild log showing the error: https://dashboard.buddybuild.com/public/apps/57a120bbe0f5520100e11c19/build/5bee1e28a51a800001f4e852#logs.
Note how it fails with `CocoaPods could not find compatible versions for pod "WordPressKit"` rather than the error we usually see (something like `CocoaPods could not find compatible versions for pod "WordPressKit"`).
I have added support for this type of error in `0.0.3` of `cocoapods-repo-update`. Here's the diff in the plugin: https://github.com/wordpress-mobile/cocoapods-repo-update/compare/0.0.2...0.0. …

Bump cocoapods-repo-update to 0.0.3

---

WordPress/Classes/Services/EditorSettings.swift
WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme

Only show Gutenberg as the editor if the -gutenberg argument is passed on launch.
To do this, you can edit the WordPress scheme, go to the Arguments tab in Run, and check the `-gutenberg` box or not.
It's not the ideal workflow, but this will do until we have https://github.com/wordpress-mobile/gutenberg-mobile/issues/222 in place

Enable Gutenberg depending on feature flag

---

WordPress/Classes/ViewRelated/Post/Revisions/RevisionsTableViewController.swift

**To test:**
Let's just make sure that the updated strings look ok in context. I assume they will though, because they'd need to grow / shrink for other languages.

Update revisions error messaging to remove variables

---

WordPress/Classes/ViewRelated/Post/Revisions/RevisionsTableViewController.swift
WordPress/Classes/ViewRelated/Post/Revisions/Views/Footer/RevisionsTableViewFooter.swift

Fixes #10517 
This PR fixes the date formatter used by the revisions list footer.
**To test:**
- Open a Revisions list and check the date formatter style. It shouldn't contain the time but only a short date as style.

History / Revisions: Fix footer date formatter

---

WordPress/Classes/ViewRelated/Post/Revisions/Views/Cell/RevisionsTableViewCell.swift

Refs. #10304 
This PR fix a RevisionCell behaviour. I added a default value to the imageview. Because the gravatar image is assigned only if there is a valid URL, I added a default value in order to avoid wrong data displayed when a cell is reused.
**To test:**
- Open a revisions list and check if the image placeholder is displayed when there's no author
Issue found by @rachelmcr

Set a default value to the image view

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewModel/RegisterDomainDetailsViewModel.swift
WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainSuggestions/RegisterDomainSuggestionsViewController.swift
WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift

Adds basic analytics for Custom Domains.
`-Shared` counterpart PR is: https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/168
To test:
Look at the code, and like, trust me that it works ;P
Optionally, just go trough the whole flow and verify that appropriate events are printed to the console.

Add analytics event for Custom Domains.

---

WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
WordPress/Classes/ViewRelated/Stats/Insights/LatestPostSummaryCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/LatestPostSummaryCell.xib
WordPress/Classes/ViewRelated/Stats/Insights/SimpleTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/SimpleTotalsCell.xib
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.xib
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Fixes #10498 
This actually encompasses these changes:
1) Updates the card header to the new design.
2) Removes the full border on the cards, and now has only a top and bottom.
3) Updates margins for the Latest Post Summary text.
4) Fixes an issue where All Time Stats rows were being duplicated on pull to refresh.
The new card header should match this Zeplin design zpl://screen?pid=5a86dd8dfaff0fa0290982db&sid=5bf2a8d9e6b0427eb9a22108 (Full Stats Refresh > Heading Bar Changes).
To test:
---
On a site with Latest Post Summary data, Go to Stats > Insights. Verify the view is:
---
On a site with _no_ Latest Post Summary data, Go to Stats > Insights. Verify the view is:
---
On a site with _no_ All Time Stats data, Go to Stats > Insights. Verify the view is:

[Stats Refresh] Update card header

---

.swiftlint.yml

Following up on https://github.com/wordpress-mobile/WordPress-iOS/pull/10511, I'm thinking we should have an automated way to prevent this sort of change from being committed in the future.
**To test:**
Add the following to a file in the project:
```swift
let year = 2018
NSLocalizedString("© \(year) Automattic, Inc.", comment: "About View's Footer Text")
```
Run `swiftlint` in the project root (if you don't have it, `brew swiftlint`). You should see 1 violation. Remove it, and now you should see zero!

Don’t allow string interpolation in localizations

---

WordPress/Classes/ViewRelated/Blog/SiteIconPickerPresenter.swift
WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m

Fixes #10546 
To test:
- Edit a post or a page.
- Go to Post Settings > Set Featured Image > WordPress Media.
- Enter an invalid search term.
- **`Cancel`** on the search bar _**(this is important)**_.
- Return to Post Settings.
- Select Set Featured Image > WordPress Media again. Verify it does not crash.
NOTE:
Although I couldn't get `SiteIconPickerPresenter` to crash, I added the same check there too just to be safe.

Post featured image search: Check for a search string before displaying no results view.

---

WordPress/Classes/Utility/InteractiveNotificationsManager.swift
WordPress/Classes/Utility/PushNotificationsManager.swift
WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
WordPress/WordPressNotificationServiceExtension/Sources/Tracks/Tracks+ServiceExtension.swift

Fixes #10543, which calls for the addition of new analytics events to the notification service extension. 
It also addresses a lingering issue from #6256, where event parity was achieved, but the funnel was still not behaving as expected. Namely, in the case of a quick action, the initial analytics event was not being called.
Checkout the branch and confirm that existing tests pass. The new events are associated with error cases, so this may be difficult to validate via manual testing.

Improve analytics captured in support of rich notifications

---

WordPress/Classes/Services/EditorSettings.swift
WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme

Instead of the command line `-gutenberg` flag, this adds a setting on Debug an Internal builds to enable Gutenberg
Fixes #10554 
To test:
- Create a new post, Aztec should show
- Go to Me > App Settings, and toggle the Gutenberg switch
- Create a new post, Gutenberg should show
- Make sure the toggle and Gutenberg only show up in Debug/Internal builds (I haven't had time to test this myself yet)

Replace the gutenberg flag with a setting

---

WordPress/Classes/ViewRelated/Views/NoResults.storyboard

Fixes #n/a
This changes the left and right margins on the empty state view (aka No Results view) from 38 to 30. The max width is still 360.
To test:
Go to an empty state view. Verify the view is a bit wider. Can you see it? I bet @SylvesterWilmott can. 😉 
(@SylvesterWilmott let me know if you need more example screenshots.)

Empty state: Update margins on view

---

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m

Fixes #10528 
Reopens #10435 
This fixes the logout crash. However this undoes the fix in #10435. I now believe that headers/footers cannot be modified inside `performBatchUpdates` blocks (nor `performUpdates`).
To test:
- follow the instructions from #10528 with and without this fix
- ensure the crashes have stopped
@stevebaranski if you have time to review, great. if not, @jtreanor do you have time?

Fix crash by removing performBatchUpdates

---

WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.xib

Fixes #10501 
Well this was easier than expected. Turns out I'd used the wrong values to display. The string versions of the values are pre-formatted with commas. So I've simply replaced the number values with the string values. 🎉 !
Also, as a minor bonus, I disabled the selection on the cell header. So now if you select it, it won't turn an ugly brown color.
To test:
- On a site with a bunch of posts, views, visitors, and/or best views ever, go to Stats > Insights.
- Tip: the Automattic Field Guide has some high number.
- Verify the numbers have commas:

[Stats Refresh] All Time Stats: format large numbers

---

WordPress/Classes/Utility/Analytics/WPAppAnalytics.m

This PR addresses an issue with the `applicationOpenedTime` property being reset with a new date due to `UIApplicationDidBecomeActiveNotification` notifications received while multitasking or viewing a system overlay.
For more background see p9OQAC-90-p2.
To test:
- Use an iPad to test all uses cases.
- Set breakpoints in `trackApplicationOpened` and `trackApplicationClosed`.
Scenario 1:
Launch the app and confirm that `trackApplicationOpened` is called and the date is correctly set.
Background the app and confirm that `trackApplicationClosed` is called and the date is unset.
Scenario 2: 
With the app in the foreground, swipe down from the top left or right corners to view Mission Control or Notification Center.  Note that `UIApplicationDidEnterBackgroundNotification` is not dispatched …

Analytics: Fixes an issue with applicationOpenedTime being reset.

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
WordPress/Classes/ViewRelated/Post/PostEditor.swift

Following problems are solved:
1. Currently even if we change the title and tap close button it doesn't display the "You have unsaved changes" prompt
2. Sometimes(I can't reproduce this on my business site but it happens on free site) if you have Image blocks in your post and you tap close button without changing anything the "You have unsaved changes" prompt is displayed unnecessarily. Root cause of this is as follows: gutenberg side passes _style=""_ attribute to the parent app in the image block but this attribute is discarded on the back end service during saving the block, so the gutenberg version and the database version of the post actually never syncs and it appears to be always like there's a change. To avoid this unnecessary prompt we are using the changed flag that is sent us …

Improve gutenberg editor change detection

---

WordPress/Classes/ViewRelated/System/Notices/NoticeView.swift

The issue can be seen here:
And here it is after the fix:
And to verify that the other notices haven't been negatively affected:
To test:
- Make a new post
- Ensure the notice of its successful publishing looks correct
@jklausa since you noticed this can you review this fix? THANKS

Center notice view titles when there is no message

---

WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

This fixes an issue where the toolbar wouldn't be immediately visible when creating a new post. This sets the focus on the title bar after the editor has appeared, so the gutenberg view gets laid out correctly.
To test:
- Create a new Gutenberg post
- The focus should be in the title field
- The toolbar should be visible

Show Gutenberg title after it appears

---

Podfile
Podfile.lock

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/10569
To test:
Remove what's underneath pods folder and run "rake dependencies"
Stop metro if it is running
Then make sure gutenberg editor is running ok

Update Gutenberg version as 0.2.0

---

Podfile
Podfile.lock

This change bumps up gutenberg version to v0.2.2
To test:
- Verify that below placeholder is visible and when you tap on it you can edit the post

Bump up gutenberg version to v0.2.2

---

WordPress/Classes/Models/SiteVertical.swift
WordPress/Classes/Services/SiteVerticalsService.swift
WordPress/WordPressTest/SiteVerticalTests.swift
WordPress/WordPressTest/Test Data/site-vertical.json

Fixes #10581 
Add an extra property to the `SiteVertical` model object, called `isNew` as mentioned here: p9wMUP-dz-p2
To test:
- Check out the branch
- Build the project
- Run the tests. In particular, `SiteVerticalTests` should all pass

[Site creation] Add an isNew property to SiteVertical

---

WordPress/Classes/ViewRelated/Me/AboutViewController.swift

Fixes http://crashes.to/s/9fd5185922a
**To test:**
_Before_: Go to Me > App Settings > About WordPress for iOS. App will crash.
_After_: It will not.

Fix a crash caused by improper int format handling

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+MoreActions.swift
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

Fixes part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/182
This change adds History option to the Gutenberg editor. The behavior is same as Aztec, when an older revision is selected  among the old revision list the editor content is updated with that revision. After that we need to tap Update button if we want to publish the new content, we can still discard the content by tapping Close button and then choosing "Discard".
We'll need to merge the dependent PR first https://github.com/wordpress-mobile/gutenberg-mobile/pull/313
**To test:**
Test 1 - Update content on Visual mode
Tap (...) on right top corner, Select "History" and select one of the previous revisions
Verify that visual editor content updated with the given html
Switch to HTML mode and verify contents match …

Add History option for Gutenberg editor

---

.github/PULL_REQUEST_TEMPLATE.md
Scripts/fastlane/helpers/ios_git_helper.rb

As discussed, it would be great to start adding release notes throughout the development cycle. I had initially implemented a complex version of this that parsed a `ReleaseNotes.md` file, but I think this simpler approach is better start.
The change is this:
- A file, `RELEASE-NOTES.txt`, is in the root of the repo. ~It should be emptied on `develop` after every code freeze (when the release branch is made). This will be uploaded to the AppStore with fastlane when it is time to release.~ **Updated:** Changes should be added to it through the cycle. It will be cleared and copied to `WordPress/Resources/release_notes.txt` on code freeze so it can be uploaded to the AppStore.
- I have also added a reminder to the Pull Request template (see below) to help us remember to add release notes when …

Add RELEASE-NOTES.txt file to encourage adding release notes iteratively

---

README.md

Point to `~/.mobile-secrets/iOS/WPiOS/wpcom_app_credentials` instead of `~/.wpcom_app_credentials`.
See: https://github.com/wordpress-mobile/WordPress-iOS/issues/10624#issuecomment-445554047

Update the README with correct credential filename

---

Podfile
Podfile.lock

This change updates the version of Gutenberg editor as v0.2.3.
**To test:**
- Remove pods folder
- run `rake dependendcies`
- Make sure metro is NOT running in the background
- Run WordPress iOS app
- Check some lately added features like History option, Switch between HTML/Visual, Switch between Aztec/Gutenberg, try posting.
We don't have user facing changes yet.

Update gutenberg-mobile dependency with tag v0.2.3

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift

Fixes #10407 
To test:
- Go to Me > App Settings > Privacy section.
- Verify `Remove Location from Media` is at the bottom of the section.
- Verify the footer text is:
`Removes location metadata from photos before uploading them to your site.`

Privacy: Add explanation to Remove Location from Media feature

---

.circleci/config.yml

The danger CircleCI workflow is currently running `rake dependencies` which unnecessarily installs all pods. This is causing it to fail since its not set up properly for this. In this I have updated it to only install the gems and swiftlint.
To test:
- The danger CircleCI check on this PR should be green

CircleCI: Fix danger dependencies

---

.gitignore
Scripts/BuildPhases/CopyScreenshotCredentials.sh
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressScreenshotGeneration/ScreenshotCredentials-Template.swift
WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift

Add support for using a credential store for screenshot secrets.
**To Test**
Check out the branch, and try running the screenshot generation target. It'll transparently duplicate the template, and will give a build warning, because there's no credentials specified.
Then, delete the newly-created `WordPress/WordPressScreenshotGeneration/ScreenshotCredentials.swift` file, then create a file at `~/.mobile-secrets/iOS/WPiOS/ScreenshotCredentials.swift` based on the template.  Populate it with real values, then run the screenshot generation target again.

Use the ~/.mobile-secrets credentials for screenshots

---

.configure

A small fix to make `configure_validate` less noisy during builds. Relies on https://github.com/wordpress-mobile/release-toolkit/pull/12

Indicate the secrets directory this project uses

---

WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift

Fixes #10589
This fixes the positioning of the approve animation so that it is always aligned with the approve button.
To test:
- Approve a comment
- Ensure the animation is correct now, vs. the GIF in #10589 
- This is a minor bug fix, I wouldn't expect it to be mentioned in the release notes.

Change position of comment approve aniamtion

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift

Fixes #10639 
This PR removes feeds from the followed sites list in setting.
In the _NotificationSettingsViewController_ I filtered the followed sites removing the feeds. I also fixed a bug on displaying the right number of rows if the array count is less than the threshold.
**To test:**
- Go to the _Reader_ > _Followed Sites_ > _Manage_
- Enter **nytimes.com** in the textfield and press _Done_ and wait till the notice appears saying the site has been added.
- Go to _Me_ > _Notifications Settings_. _The New York Times_ site shouldn't appear on the Followed sites list.
ccing @theck13

Remove feed from followed sites list in setting

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

Fixes the issue of media library buttons not taking an action.
**To test:**
- Open a post with Aztec editor and see if the media buttons are working

Fix media library buttons not being effective

---

Podfile
Podfile.lock

Title has it.
This PR is particularly important because Aztec version 1.3.x introduced an odd regression that could break Gutenberg blocks (due to an iOS bug it seems).  Fortunately this will never see the light of day because it was integrated into WPiOS in 11.4 and this PR targets the same version.
The fix is part of a larger PR that can be found [here](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1101).
This version includes the fixes listed here: https://github.com/wordpress-mobile/AztecEditor-iOS/milestone/58?closed=1
Unfortunately, since there are many fixes, I'd suggest to see the issues listed above for additional testing instructions.
Keep in mind all of them have already been tested within Aztec's Example App.
Make sure to:
- Clean and reinstall the dependencies …

Integrates Aztec 1.3.2 into WPiOS

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

This PR implements the changes made in https://github.com/wordpress-mobile/gutenberg-mobile/pull/373 .
Using the new delegate method, we show the keyboard when we start a new post.
To test:
- Clean build folder.
- `pod install`
- Start a new post using Gutenberg. (no metro running)
- Check that the keyboard appears with the toolbar.
- Run metro (from master or from the [related PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/373))
- Start a new post using Gutenberg.
- Check that the keyboard appears with the toolbar.
cc @koke

Show keyboard when a new post is loaded

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift

Refs. #10304 
This PR adds the last Analytics event for History/Revisions: _revisions_load_undone_.
**To test:**
- Select a Revision from the revisions list.
- Load the selected Revision
- When the Notice View appears click the _Undo_ button
- You should see the event `revisions_load_undone` tracked

History/Revisions: Add last analytics event

---

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
WordPress/Classes/ViewRelated/Site Creation/Wizard/WizardNavigation.swift

Fixes #10657. I also noted that the new site creation flow could be initiated without a WPCOM account, so I remedied that.
_There are no changes impacting release notes._
- Checkout the branch and verify that test pass. 
- Launch the "Enhanced Site Creation" flow on iPhone and verify that content remains in Portrait orientation. 
- Repeat the preceding step on iPad and verify that rotation still works.

Disable iPhone Landscape support in Enhanced Site Creation flow

---

WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift
WordPress/Classes/ViewRelated/System/Notices/UntouchableWindow.swift

Fixes #10667
To test:
- Follow the rotation description/videos in #10667 
- Fixes a bug that users haven't been exposed to yet, no notes needed.

Fix new Notice presentation causing rotation errors

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

This solves the `updateHtml` warning when loading Gutenberg controller by checking `gutenberg.isLoaded` before sending html to JS side.
This PR needs a new version of `gutenberg-mobile` before merging.
The changes needed in that new version are here: 
https://github.com/wordpress-mobile/gutenberg-mobile/pull/385
To test:
- `pod install`.
- Open a post with Gutenberg.
- Check that there are no warnings. (or none related to `updateHtml` message.
- Test that loading older revisions works (History option in the more `...` menu)

[Gutenberg]: Check `gutenberg.isLoaded` before sending html to JS side.

---

WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift
WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyContentView.swift
WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyStep.swift
WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreator.swift
WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreatorOutput.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/SiteCreation/SiteAssemblyServiceTests.swift
WordPress/WordPressTest/SiteCreation/SiteCreatorTests.swift

Fixes #10328, which calls for the transformation of information collected from user input during the enhanced site creation flow into values suitable for submission to the server. 
I took the opportunity to shore up some of the preliminary inline documentation for the final site assembly step, and created unit tests that articulate our expectations for this behavior.
Noteworthy:
- We have agreed to change the segment & vertical identifiers from `String` to `Int64` (the Android implementation is using `Long`) as part of #10670. I documented applicable references here, but did not implement that change as part of this PR.
- While the _Site Info_ screen can be skipped, the values of the title & tagline attributes are `String` & `String?`, respectively. I implemented this to account for that …

Transform values from SiteCreator to SiteCreatorOutput

---

WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/375
This PR updates postEditorStateContext when `GutenbergViewController` gets html data from the Gutenberg module.
This helps the state context to make better desitions on wether show the secondary publish button or not.
To test:
- Create an empty post.
- Add title and some content.
- Press `...` (more) button.
- Select `Save to draft).
- Press `...` (more) button again.
- Check that the `Publish Now` button is there.
- Check that `Publish Now` works as it should.

[Gutenberg]: Show "Publish now" button on drafts.

---

WordPress/Classes/ViewRelated/Gutenberg/GutenbergContainerView.swift
WordPress/Classes/ViewRelated/Gutenberg/GutenbergContainerView.xib
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj

This PR makes the Gutenberg title respect to safe area, the issue is visible on iPhone X landscape mode.
**Before:**
**After:**
**To test:**
Test 1 - iPhone X - landscape
- Open WPiOS app with one of the iPhone X generation device or simulator, open a gutenberg post
- Switch device orientation to landscape
- Make sure title respects the safe areas leaving enough space from left/right
Test 2 - non iPhone X
- Open WPiOS app with one of iPhone 6/7/8/SE device or simulator, open a gutenberg post
- Switch device orientation to landscape
- There shouldn't be any spaces this time on left/right of the title
Test 3 - Portrait mode
- Switch to Portrait mode and check the title
- There shouldn't be any spaces this time on left/right of the title
Test 4 - Basic title update
- Update a post's title
- …

Make gutenberg editor title respect to safe area

---

Podfile
Podfile.lock

Aztec v1.3.3 fixes a crashing bug reported [here](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1111) that affects WPiOS.
To test, make sure the pod installation works fine.
There's an automated test in the library that ensures the change does fix the issue, but feel free to validate against the posts that were causing issues (can't make this info public unfortunately).

Updates Aztec to v1.3.3

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m

There was a weird edge case when trying to install plugins on site, it goes roughly like this:
* User has opened an app quite some time ago
* They have upgraded to a Business plan in the meantime
* The app wasn't reloaded in a while
* They try to go to "Plugins" section in the app 
* There is no "Plugins" section displayed, because the app doesn't know about that the site was upgraded to business plan.
This sorta fixes it! It now refreshed the site metadata on `viewWillAppear` of `BlogDetailsViewController`, so when a user comes back from some other screen, we'll refresh the active plan and be able to show the section.
To test:
* Open the blog detail views in an app, of a site that doesn't have a Biz plan active
* Add a Biz plan to the site (using SA, or ping me ;P)
* Go to any screen …

Preload metadata of blogs on `viewWillAppear:` in `BlogDetailsViewController`.

---

WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController+LocalizedStrings.swift
WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewModel/RegisterDomainDetailsViewModel+RowList.swift

This fixes an error message that is not properly translatable to many languages introduced in #10384.
The variable contents for `Please enter a valid %@` can be `First Name`, `Country`, `Phone number`. This only works in English because there is practically no gender for nouns. This is not true for example French or German. The above needs to be translated depending on the variable in German to `Bitte gib eine gültige %@ ein`, `Bitte gib ein gültiges %@ ein` or `Bitte gib einen gültigen %@ ein`.
Since the number of error message generated by the above string is quite small, we just need to write them all out.
I cannot compile WordPress iOS on my machine, so I just modified the Swift code to my best knowledge. Happy to get followup commits that fix any syntax error.

Make the domain valiation error message properly translatable

---

Podfile
Podfile.lock

I've been testing this through #10701 and releasing several builds for others to test, but doing a newer PR with cleaner history
To test:
- Run and make sure Gutenberg loads
- A good hint that it has the latest version is to look for the border at the side of focused blocks

Update Gutenberg to 0.3

---

Rakefile

Currently, if you run `rake dependencies` after making changes to the `Podfile`, nothing happens. This is because `bundle exec pod check` only checks if `Podfile.lock` and `Pods/Manifest.lock` match.
This PR updates `rake dependencies` to also check if the checksum in `Podfile.lock` matches the `Podfile` (Thanks @koke for the idea!).
The downside is that `rake dependencies` isn't as fast if you have no changes. I think its a trade off worth making.
I'll open a PR for https://github.com/square/cocoapods-check to see if they will accept a change so we don't need to do this.
To test:
- Make any change to `Podfile`
- Run `rake dependencies`

rake dependencies: Check if Podfile matches Podfile.lock

---

WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
WordPress/Classes/ViewRelated/Post/PostEditor+BlogPicker.swift

Used to update HTML content before switching to another blog.
This PR solves an issue where the content was lost after switching to another Blog using the blog picker.
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/442
Now:
To test:
- Open the Gutenberg post editor with a new post (mid button in the bottom tab bar.
- Write some content.
- Switch to another blog using the blog picker (as shown in the GIF)
- Check that all the content is still there.
- Save/Publish the post.
- Check that the post is saved in the corresponding blog.

Gutenberg: Adding new request HTML reason `switchBlog`

---

Podfile
Podfile.lock
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/395
To test:
run `rake dependencies`
and then test with steps in the [child PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/448) replacing example app with WPiOS app.
podfile will be updated after [child PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/448) is merged.

Gutenberg - Fix unwanted bottom inset when keyboard is open

---

WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/443
This PR fixes an issue where the MediaLibrar wasn't updated to the new blog, after switching blog with the blog picker.
Testing this, you might notice an issue that after changing the blog, the post content is deleted. This is solved here: #10724 
Now:
To test:
1. Open the Gutenberg editor.
2. Add an empty Image block.
3. Open the media library from that block.
4. Check that the images correspond to your current blog.
5. Switch to another blog using the blog switch button. (As shown in the GIF).
6. Repeat 2, 3 and 4.

Gutenberg: refresh `mediaPickerHelper` after post has changed.

---

WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/Utility/Analytics/WPAppAnalytics+Media.swift
WordPress/Classes/ViewRelated/Media/Giphy/GiphyDataLoader.swift
WordPress/Classes/ViewRelated/Media/Giphy/GiphyPicker.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift

Implements #10091.
We previously added some Giphy analytics events to our analytics tracker, but never actually used them. This PR completes that work.
**To test**
* Complete the following actions and check in the Xcode console that the relevant events are triggered:
* In the Media Library, tap + and choose Giphy
* Perform a search in the Giphy picker
* Choose an item from the search results and upload it
* In the Editor, chose `...` in the formatting toolbar, and select Giphy
* Perform a search, select a result, and insert it into the post

Track Giphy analytics events

---

.gitignore
Scripts/fastlane/ScreenshotFastfile
Scripts/fastlane/Snapfile

This makes a number of small improvements to the current screenshot automation:
- Introduce a `screenshots` lane that only builds the app once (currently it is built for every device/locale combination).
- Skip searching for the fastlane snapshot helper. This always fails because fastlane assumes it is being run from the project root. We could fix this by moving `fastlane/` to the root of the repo, but thats a big change.
- Make paths in `Snapfile` more reliable. They didn't always resolve correctly.
- ~~Update `SnapshotHelper.swift`~~ Hound didn't like the whitespace in this. Leaving it out since there were no other changes.
This all means that we should now run screenshots with `bundle exec fastlane screenshots`. Since it no longer spends minutes building the app for each test, it now …

Improve screenshot performance and reliability

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift

Fixes #10758.
Please see the original issue for full details / reproduction steps. This PR fixes the issue by ensuring the notifications router is updated whenever the view controller's notification changes. Previously, the router wasn't getting updated so it was still navigating to detail for the original notification.
**To test**
* Follow the steps in the original issue. Essentially:
* Go to Notifications and navigate to a comment notification
* Use the arrows to navigate to another notification
* Tap the header, and ensure you're taken to the right detail screen
@etoledom Would you mind reviewing this one, as you wrote the router originally?

Notification Details: Refresh router on Note change

---

WordPress/Classes/ViewRelated/Cells/WPProgressTableViewCell.m

Fixes #10728.
To test:
- Juxtapose this change with the removal in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10413/)

Resolved crash by restoring progress KVO observer

---

WordPress/Classes/Extensions/Math.swift
WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
WordPress/Classes/ViewRelated/Themes/WPStyleGuide+Themes.swift

Fixes #10354 (maybe)
Searching around for the crash on Fabric:
"Fatal Exception: NSInternalInconsistencyException negative sizes are not supported in the flow layout"
brought up a few similar crashes that were due to invalid values returned in the  collection view delegate method: sizeForItemAtIndex.
To test:
I was able to reproduce the crash by returning a hard coded negative value for one of these functions, but was not able to reproduce otherwise.

Attempted fix crash: "NSInternalInconsistencyException negative sizes are not supported in the flow layout"

---

WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
WordPress/Classes/ViewRelated/System/FilterBar.swift

Fixes #10703 
To test:
---
- Go to Stats > Insights.
- On the Comments and Followers cards, verify the selected tab colors are:
- Text color is dark grey
- Indicator color is light grey.
---
- Verify other instances of `FilterTabBar` colors have not changed, i.e. the selected tab's text and indicator colors should match. (ex: Stats, Notifications, Site Pages)

[Stats Refresh] Tabbed cards - update filter bar colors

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift

Fixes #10247 
Before and after (notice the Edit button)
To test:
- Checkout the branch
- Either build and run on a localised device or edit the WordPress scheme select Run configuration and in Options change the Application Language from System Language to any other language
- Navigate to Notifications > select a comment
@frosty do you mind taking a look? It is literally a one liner

Localize title of the button to edit comments

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Post/PostPostViewController.swift

Fixes #10444 
Before > After
To test:
- Checkout the branch
- Either build and run on a localised device or edit the WordPress scheme select Run configuration and in Options change the Application Language from System Language to any other language
- Compose and publish a post. In the Notice presented after the Post is published, tap "View". Notice the Done button in the view presented

Localise Done button in view presented after publishing a new post

---

WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
WordPress/Classes/ViewRelated/Cells/SwitchTableViewCell.swift
WordPress/Classes/ViewRelated/Cells/WPReusableTableViewCells.swift

Fixes #9816
This PR also fixed other similar issues where the labels get trimmed with text in other languages or with a bigger font.
There is still an issue with the right detail label on tables, that they are left without space by the left text label. I believe that issue deserves its own PR, I tried some possible simple solutions but non of those worked.
To test:
- Change your device/simulator to Spanish (or other language with longer words)
- Increase the text size to make the issues more evident. (iOS Settings -> Display -> Text Size)
- Visit the sections shown in the added image.
- Check that the cropped text issue is resolved.
- Turn ON accessibility text sizes and increase it (iOS Settings -> General -> Accessibility -> Larger Text
- Visit again the same screens and check that they …

Fix cropped localized text

---

README.md

The README currently incorrectly suggests running `pod install` to install dependencies. This updates it to clarify that pods are installed by `rake dependencies`.
To test:
- Check the README 😄 

Update README to remove 'pod install'

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift

Fixes #9708
To test:
- Login with an account that has no sites.
- Verify the 'My Sites' section is not displayed.
- Login with an account that has sites.
- Verify the 'My Sites' section is displayed.
---
---

Login Epilogue: Don’t show empty ‘My Sites’ section

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/NUX/SiteCreation.storyboard
WordPress/Classes/ViewRelated/NUX/SiteCreationCategoryTableViewCell.xib

Fixes #10646 
To test:
Either on a small device or with increased text size:
- Go to 'Create Wordpress.com site'
- On the first step, verify the 'Start with a xxx' label wraps.
NOTE: I noticed this page does not scroll. As Site Creation is being revamped, I'll assume that'll be addressed with the new project, or will just become irrelevant. (cc @ctarda @stevebaranski )

Site Creation > type selection: wrap 'Start with' label

---

WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift

Fixes #10770.
This PR hopefully fixes the high CPU usage that I noted in #10770. It adjusts the usage of `WPAnimatedBox` in `NoResultsViewController` to explicitly stop the animation when removing the animated box from the no results view.
**To test**
* Navigate to the Menus screen for a size. On `develop`, I see 100% CPU even when the screen has loaded. On this branch, I see normal CPU usage.

NoResults: Stop WPAnimatedBox animation when removing from superview

---

WordPress/Classes/ViewRelated/Me/MeHeaderView.m
WordPress/Classes/ViewRelated/Me/MeViewController.swift

This PR makes `MeHeaderView` height flexible, adjusting to different font sizes.
Before, even though the font size was adjusting, the header height was constant. This was problematic for larger font sizes, specially with `Larger accessibility text sizes` active.
To test:
- Activate `Larger accessibility text sizes`.
- iOS settings -> General -> Accessibility -> Larger Text -> Turn the switch ON -> Increase de slider to more than half.
- Go to the WPiOS app.
- Go to the `Me` tab section.
- Check that the table header is correctly displayed, as shown in the screenshot.

Make `Me` header view height adjust to text size

---

WordPress/Classes/ViewRelated/Cells/MediaSizeSliderCell.swift
WordPress/Classes/ViewRelated/Cells/MediaSizeSliderCell.xib
WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift

A continuation from #10757 
This PR makes `MediaSizeSliderCell`'s height to be calculated automatically, and resize according to text size.
It was necessary to update the xib file (it was quite old) to change some constraints configuration. Most of the changes visible in that file were automatically generated.
@ctarda - May I bother you again with a review? 😁
To test:
- Change your device/simulator to Spanish (or other language with longer words)
- Increase the text size to make the issues more evident. (iOS Settings -> Display -> Text Size)
- Go to Me -> App Settings -> Scroll down to `MEDIA`.
- Check that the cropped text issue is resolved as shown in the screenshots.

Fix MediaSizeSliderCell text cropped

---

RELEASE-NOTES.txt
WordPress/Classes/Extensions/URL+Helpers.swift
WordPress/Classes/ViewRelated/Me/AboutViewController.swift

Fixes #9824 
Load the TOS in the system locale. 
@etoledom May I trouble you with a review? 😊 
As discussed on slack, the solution to localise the TOS seems to be loading the specific language as subdomain:  p1547015680116700-slack-C02ECE3ML
To test:
- Check out the branch
- Run the app on a device (or simulator) with the system set to a language other than English.
- Navigate to Me > App Settings > About WordPress for iOS > tap Terms of Service

Present localised TOS

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockImageTableViewCell.swift

Fixes #9778. The `NotificationDetailsViewController` is reused when a user navigates via the arrows. For images, a cell of type `NoteBlockImageTableViewCell` presents images.
This PR implements a `prepareForReuse()` method. It's worth noting that in addition to `nil`-ing out the image view, we also nil out the `imageURL` to prevent early exit from the `downloadImage(_:)` method.
- While logged in, select the _Notifications_ tab and navigate between notifications with images. Ideally, you will no longer see "stale" images (i.e., images from old notifications) during said transition.

Prevented stale images from appearing in notifications

---

WordPress/Classes/ViewRelated/Comments/CommentViewController.m
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m

Fixes #9299.
This adds an excerpt of the comment to the error message that show up when there's an error posting a comment. The excerpt is capped at 140 chars, which was chosen arbitrarily, but should be enough to give people context on which comment failed to post.
To test:
1. Try replying to comment with a long post, under conditions that would cause it to fail (i.e. no network) (to test the flow in Notifications, it's easiest to add `completion(false); return` to `NotificationActionService.swift:61`

Add a better message error when replying to comment fails.

---

WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib

This PR updates the reader site header to layout it properly when the user chooses a bigger system font size. This is particularly noticeable when `Larger Accessibility Sizes` is active.
Sadly, most of the changes were in a `xib` file :( 
As a secondary improvement, now the `description label` will automatically update it's font size when the user changes the system font size.
**To test:**
- Activate `Larger accessibility text sizes`.
- iOS settings -> General -> Accessibility -> Larger Text -> Turn the switch ON -> Increase de slider to more than half.
- Go to the WPiOS app.
- Go to `Reader` -> `Discover`
- Check that the table header is correctly displayed, as shown in the screenshot.
**Font size change:**
- Sitting on the `Discover` screen, go to the iOS settings again and change the …

Update reader site header to display bigger text sizes.

---

RELEASE-NOTES.txt
WordPress/Classes/Services/PeopleService.swift
WordPress/Classes/ViewRelated/People/PeopleViewController.swift

Fixes #5675 
This fixes the issue of deleted users appearing in the People lists.
The issue was People were being added/updated in Core Data but never removed. This change removes all People from Core Data when the view is initially shown, and on pull to refresh. Core Data is repopulated as the People lists are loaded.
To test:
- Via the website (https://wordpress.com/people/team), invite a user.
- As that user, accept the invitation.
- In the app, verify the user appears in Site > People.
- Via the website, remove that user.
- In the app, refresh the People list.
- Verify the user no longer appears.

Site People: remove deleted users

---

Podfile
Podfile.lock
WordPress/Classes/Categories/Media+WPMediaAsset.m
WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m
WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/10228
We start showing a different error message in case of a parental control.
Media Picker changes are in [this PR](https://github.com/wordpress-mobile/MediaPicker-iOS/pull/313).
**To test**
1. Enable parental controls in your device, follow below steps to do this:
- for iOS 12 go to Settings > Screen Time > Turn on Screen Time
- If screen time is already turned on then turn it off and again turn it on because we need to select "This is my child's iPhone" option 
- Skip Downtime and App limits configuration by selecting "Not Now"
- Tap "Continue" on Content & Privacy
- Set a parent passcode, better make this different than the touch id passcode, this is the passcode to change the parental controls.
- Choose Content & Privacy …

Update WPMediaPicker to include parental control updates

---

RELEASE-NOTES.txt
WordPress/Classes/Utility/Media/ImageLoader.swift

Fixes #10211 
To test:
I'm actually not sure what steps trigger the crash. But, from the crash logs, it appears to be caused by a strong reference. So I've added a weak self reference in `callErrorHandler`. 🤞 this fixes it!

ImageLoader: Fix crashing when attempting to handle error

---

.circleci/config.yml
Dangerfile
Gemfile
Gemfile.lock

A few months back Hound was having issues running `swiftlint` so we added rules for it to Danger with `danger-swiftlint`. Since everything has been stable again for some time, this PR removes the duplicated work from Danger.
A nice extra benefit of this is that we can run Danger on a linux image in CircleCI. This frees up our macOS queue for iOS builds.
To test:
- See that Hound is working correctly. You can see a filing PR here: https://github.com/wordpress-mobile/WordPress-iOS/pull/10788
- Both Hound and Danger pass for this PR.

Don't run swiftlint on danger

---

WordPress/Classes/ViewRelated/Cells/MediaSizeSliderCell.xib
WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib

This PR silence some warnings related to dynamic types in a couple of xib files.
The warning says that system fonts does not support dynamic types, so I opted for changing it for the corresponding dynamic type font style of the same point size.
Ref: https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/
This effectively silence the warning keeping the automatic font sizing and font style intact.
To test:
- Clean project and build folder.
- Build the project.
- Check that there are no warnings related to xib files.
- Check that the modified elements display correctly:
- Reader site header: (more info) https://github.com/wordpress-mobile/WordPress-iOS/pull/10780
- Media settings slider: (more info) …

Silence xib warnings

---

WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.m

This PR removes unnecessary height constraints added to `ReaderPostHeaderView`, making it able grow together with the text size. In the same way, this PR makes changes to the `ReaderPostHeaderView` class to handle dynamic type changes.
**To test:**
- Activate `Larger accessibility text sizes`.
- iOS settings -> General -> Accessibility -> Larger Text -> Turn the switch ON -> Increase de slider to more than half.
- Go to the WPiOS app.
- Go to `Reader` -> `Followed Sites`
- Look for a post with comments and press the comments button to open them.
- Check that the header is correctly displayed, as shown in the screenshot.
**Font size change:**
- Sitting on the `Post comments` screen, go to the iOS settings again and change the system text size.
- Go back to WPiOS.
- Check that the post …

Reader - Comments header view dynamic text type.

---

WordPress/Classes/ViewRelated/Post/PostPostViewController.swift

I just noticed that the tracks event `post_epilogue_displayed` was getting sent every time we displayed the editor (because it's the PostPost screen that presents the editor). I've moved the event from `viewDidAppear` to when the post is revealed.
I think I got it right, but @nheagy could you check for me as you know this screen the best?
**To test:**
* Filter the Xcode console to search for `post_epilogue_displayed`
* Open the editor. You shouldn't see the even posted
* Publish a post, and then tap the View button in the successfully published notice that appears
* Check the event is posted

Move post epilogue tracking to after post post screen is revealed

---

WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsCell.swift

Fixes #10659 
As mentioned during the review of PR #10644 , the disclosure indicators in the Segment cell should be the default.
Before and after:
To test:
- Checkout the branch. Make sure it builds and the tests pass.
- Navigate to Enhanced Site Creation. Notice the disclosure indicators in the segments cell.
- There are no changes worth being mentioned in the release notes
cc @SylvesterWilmott

[Site creation]. Remove custom disclosure indicator from segments cell

---

WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsStep.swift
WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift

Fixes #10801, which observed that selecting a segment in the first step of the flow, then navigating back and selecting a different step didn't properly update.
This PR modifies the `VerticalsWizardContent` initializer to accept the outer reference type rather than an inner value type. This change is consistent with the signature of both `WebAddressWizardContent` & `SiteAssemblyWizardContent`.
To test:
- Review the code change and make sure everything looks good.
- Replicate the steps noted in the defect, selecting **Blogger** (the first segment) the first time and **Professional** the second time.
- Verify that the prompt on the second step (_Verticals_) properly updates. That is to say, the title text should now read: _What …

Resolved verticals selection issue when navigating through site creation

---

WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift

Fixes #10688.
To test:
- Review the code changes and make sure everything looks good.
- Navigate to Step 2 of the enhanced site creation flow (_Verticals_) on both iPhone & iPad. Confirm that the title header remains visible when the text field has been selected.
- Due to the behavior of the software keyboard on the iOS Simulator, this is most reliably validated on-device.
- This does not yet address the reappearance of the text field when returning to this screen (#10791); nor does it correct the conditions when the headers should be hidden/revealed (#10812). Furthermore, this change is focused on _Verticals_. Once the preceding changes are complete, a more generalized solution will be ported to the Domains …

Modified text headers to remain visible on iPad

---

WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift

Fixes both #10791 & #10812.
This branch builds off work for both #10815 & #10816. It required extracting the existing table offset animations, changing the stimulus that triggered those animations, and properly accounting for reentrant behavior (i.e., navigating forward & back multiple times). Moreover, these changes are limited to iPhone.
To test:
- Review the code changes and make sure everything looks good.
- On **iPhone**, start the Site Creation flow and search/select a few different verticals. Try deleting text manually and clearing the text field with the clear button and observe behavior. Select a vertical & come back (header is initially visible). Navigate even further back, select a different segment: search text should …

 Modified Verticals header to properly reset appearance

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift
WordPress/WordPress.xcodeproj/project.pbxproj

If a user previews a draft we automatically save it and show the site's preview instead of the fake preview.
Fixes #9286 
BEFORE:
AFTER:
To test:
1. Go to your site -> Blog Posts.
2. Go to Drafts.
3. Edit a draft post.
4. Tap on the 3 dots icon at the top right.
4. Tap Preview

Automatically save drafts before preview

---

README.md

Replaces the BuddyBuild status badge in the README with CircleCI ahead of the upcoming switchover.
To test:
- [View the file](https://github.com/wordpress-mobile/WordPress-iOS/blob/9678259edb7bfb23740c3183a94e1ae83cd3cec5/README.md). It works!

Replace BuddyBuild status badge with CircleCI

---

README.md
WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #9286 
To test:
See the CI passes
This is a PR to revert the project file to fix Ci failure to find a file:
error: Build input file cannot be found: '/Users/distiller/project/WordPress/WordPressDraftActionExtension/zh-Hant.lproj/InfoPlist.strings'

reverting project file

---

Dangerfile

This PR prevents Danger from checking that the Gutenberg pod is referenced by commit hash, as a temporary solution while we figure out the release process for the Gutenberg related stuff.

Danger: no check for commit hashes for Gutenberg

---

WordPress/Classes/Services/PlanService.swift

REST requests from the Plans service were being made without authentication.  This PR updates the PlansService to make authenticated requests.  This fixes an issue where the Plans endpoint might omit certain plans for unauthenticated requests.
To test:
Confirm the bug by viewing the plans list with an account that has a site subscribed to the blogger plan.
Switch to this branch and view plans again. Confirm that the blogger plan now appears.
@rachelmcr would you mind testing this one since you have a test blog with the blogger plan?
@jklausa could I trouble you for the code review?

Plans: Make the plans service send authenticated requests.

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift

Fixes #10834
To test: Try with gifs, comments, and non-animated, fixed-size images. Also, watch the CPU usage – it should peak quickly when loading in a new image or when loading the initial post. This is important because the original PR addressed a crash caused by excessive CPU usage.

Fix a layout issue when we don’t have image size

---

Dangerfile

This PR excludes `RNTAztecView` from the check against references to commit hashes in the Podfile.
To test:
Verify that no warning is raised by Danger in this PR.

Exclude RNTAztecView from the check against commit hash references 

---

.circleci/config.yml

I noticed that CircleCI runs to completion even if `Podfile` and `Podfile.lock` don't match. This is a simple change to enforce.
In the near future we can move these config steps to somewhere they can be shared across all repos (probably using [Orbs](https://circleci.com/orbs/)).
To test:
- See that [this](https://circleci.com/gh/wordpress-mobile/WordPress-iOS/4086) build which did not have matching Podfile/Podfile.lock files failed.
- CI is green for this PR.

CircleCI: Check that Podfile and Podfile.lock match

---

WordPress/Classes/Stores/StatsInsightsStore.swift
WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/Stores/StoreContainer.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsDashboard.storyboard
WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #n/a
This adds an initial view for Stats Period views (Days, Weeks, Months, Years).
- New `SiteStatsPeriodTableViewController`
- New `SiteStatsPeriodViewModel`
- New `StatsPeriodStore`
- A stub `Posts and Pages` card is displayed with fake data just to show something. It will be complete with a future task.
To test:
Go to Stats > Days, Weeks, Months, or Years.
- Since the data is fake, selecting period filters doesn't do anything yet. But there is a temporary log message indicating the change:
```
Stats Period selected: Optional(WordPress.PeriodDisplayed.weeks)
Stats Period selected: Optional(WordPress.PeriodDisplayed.months)
Stats Period selected: Optional(WordPress.PeriodDisplayed.years)
```

[Stats Refresh] Add initial Stats Period view

---

Scripts/fastlane/actions/ios_update_metadata_source.rb

This PR fixes a small issue with the ios_update_metadata_source fastlane action where the action fails if there is no change in the source files.
The lane fails because it tries to run a `git commit` when there's nothing to commit.
To test:
1. Run `bundle exec fastlane update_appstore_strings version:11.6` and verify that no file changes and that the lane runs without errors.

Fix ios_update_metadata_source action 

---

.circleci/config.yml

CircleCI has a useful feature called [CircleCI Orbs](https://circleci.com/orbs/) which allows sharing parts of the config across many projects. Since most of the config in WordPress iOS is generic and we will want to use it in other projects, I have created a new repo to contain Orbs for our projects: https://github.com/wordpress-mobile/circleci-orbs.
This allows us to remove most of the config from this project and re-use it in others.
Here are the two Orbs I created, listed on CircleCI:
- https://circleci.com/orbs/registry/orb/wordpress-mobile/ios
- https://circleci.com/orbs/registry/orb/wordpress-mobile/danger
Right now they contain exactly what was in `.circleci/config.yml` before this change but we can iterate and improve them over time.
To test:
- CircleCI is green on this pr ✅ …

CircleCI: Use re-usable config with CircleCI orbs

---

Podfile
Podfile.lock

This PR updates the Podfile to load the RNAztecView from the `gutenberg-mobile` repo.
To test:
- Run `rake dependencies`
- Build and run the project. (might need to clean build folder or build with legacy build system)
- Check that it build without errors.
- Open the Gutenberg editor and check that it displays without errors.

Gutenberg: Fetching RNAztecView from gutenberg-mobile

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Extensions/UITableViewCell+Stats.swift
WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
WordPress/Classes/ViewRelated/Stats/Insights/Annual Site Stats/AnnualSiteStatsCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/SimpleTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsNoDataRow.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #10875 
This adds the Period Posts and Pages card.
- Displays top 6 results.
- If there are more than 6, `View more` is added.
- Each row contains:
- Icon
- Data bar
- Disclosure icon
- Selecting different filters (DWMY) updates the data.
- If there is no data, `No data for this period` is displayed.
NOTES:
- `View more` will show a temporary alert.
- Selecting a row will show a temporary alert.
- Since the backend does not distinguish between Posts or Pages, for now every row will use the Post icon. (cc @SylvesterWilmott ) (related issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/10886)
- @jklausa  - I added a `SiteStatsPeriodDelegate`. I thought I was going to need it for this card, but I was  mistaken. However, I will need it for other cards, so went ahead and left …

[Stats Refresh] Add Period > Posts and Pages card

---

WordPress/Classes/ViewRelated/Site Creation/Shared/TableViewOffsetCoordinator.swift
WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #10821 & #10822 
To test:
- Review the changed code for correctness.
- Exercise the _Enhanced Site Creation_ flow on devices with limited screen real estate and confirm that you can now scroll to view & select all content on both the _Verticals_ & _Domains_ screens. It may be helpful to refer to prior PRs for : [Domains](https://github.com/wordpress-mobile/WordPress-iOS/pull/10786) & [Verticals](https://github.com/wordpress-mobile/WordPress-iOS/pull/10784).
- Confirm that no regressions are observed with regard to error states.
The following static screenshots show that it is now possible to scroll the visible table view content from beneath the keyboard. The original behaviors regarding header …

Corrected keyboard offset behavior on both Verticals & Domains screens in Site Creation

---

Podfile
Podfile.lock

Bump Gutenberg ref to release 0.3.4
To test:
- `rake dependencies`.
- Build and run the project.
- Open an instance of Gutenberg. (Without metro running)
- Check that it behaves correctly.
- Try one or a couple of late fixes.
- An easy one to test: The keyboard hide button should be docked at the right: https://github.com/wordpress-mobile/gutenberg-mobile/pull/480
- Another easy to test: https://github.com/wordpress-mobile/gutenberg-mobile/pull/481

Bump Gutenberg ref to release 0.3.4

---

Scripts/manage-version.sh

This PR changes the `manage-release.sh` script so that the `whats-new` key in the `AppStoreStrings.po` file is not updated during the code freeze.
This has to be done in order to prevent bad uploads to GlotPress when we merge a `release` branch back into `develop` while still waiting for the final release notes.
The key is then update by the `update_appstore_strings` lane.

Prevent the code freeze lane to update the release notes key

---

.circleci/config.yml

This is a small change (along with an update in https://github.com/wordpress-mobile/circleci-orbs) that allows modifying the cache key so that it can be changed if the cache should be reset.
To test:
- Checks should be green on this PR.

CircleCI: Allow resetting of CocoaPods cache

---

.circleci/config.yml

This uses the changes from https://github.com/wordpress-mobile/circleci-orbs/pull/3 to be stricter about how CocoaPods caching works.
To test:
- CircleCI is green.

CircleCI: Update Orb version for strict CocoaPods caching

---

WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift
WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyContentView.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift

Fixes #10927.
To test:
- Revert the commit `edacf39` (i.e., reverting this commit revert will temporarily restore the workaround for #10919, allowing site creation to proceed to completion).
- Place a breakpoint on line 138 of `AssembledSiteView.loadSiteIfNeeded()`
- Proceed through the enhanced site creation flow, following the steps in the issue report.
- Observe that this method only loads the web view once.

Prevent loadSite from being called twice

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift
WordPress/WordPressTest/ViewRelated/Views/WPRichText/WPRichTextFormatterTests.swift

Fixes a bug caused by viewing this post in Reader: https://marco.org/2019/01/28/overcast-instant-search. The presence of the `<img>` tag in the `<video>` tag causes a crash.
**To test:**
1. Comment out the change in WPRichTextFormatter.swift. 
2. Run the new test
3. See that it crashes
4. Put the change back
5. Run the new test
6. See that it doesn't crash anymore.
**Update release notes:**
**Future Work**
This PR fixes the crash, but doesn't properly resolve the issue – `<img>` tags within a `<video>` tag are used for fallback in case the users browser can't play any of the sources. Right now, this won't crash, but it won't properly display the video either – the `<img>` tag will replace the video.
If this PR looks ok, will open a new one / file an issue about it.

Fix a reader crash caused by images in video tags

---

WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.xib

Refs. #10860 
This PR fixes a bug related to the QS Checklist view and its new header. Basically when a user rotates this view in Landscape, then it wasn't possible to rotate it back in portrait.
This also fixes a thread problem on the iPad.
**To test:**
- Put return true in shouldShowQuickStartCheacklist()
- From the Blog detail page select one of the 2 Quick Start row and open the Checklist
- Rotate the device from Landscape to Portrait. It should rotate and normally update the view to its size

Quick Start V2: Bug on Checklist rotation

---

WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift

Fixes #10939. 
The `EXC_BREAKPOINT` in the stack trace suggests an issue with an implicitly unwrapped optional. Under manual testing, I noted that notification method fires successfully, and calls `reloadViewModel`. In turn, that method appears to call `tableHandler` which is an IUO. If this is, in fact, the reason for the crash, that would imply that `SupportTableViewController` is responding to a notification before the table is initialized in `viewDidLoad`.
I'm suggesting we transition to an optional type here. An alternative approach might be to add the observers after `setupTable` is called. I'd welcome your thoughts.
To test:
- Navigate to the _Me_ tab, select _Help & Support_, and confirm there are no regressions when …

Mitigated crash due to apparent use of an IUO in support VC

---

WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift

Fixes #10937.
The stack trace indicates that the crash occurs in`ReaderSiteStreamHeader.formattedFollowerCountForTopic(_:)`, which influences the appearance highlight in the screenshots.
As noted in [Apple's Technical Note TN2151 : Understanding and Analyzing Application Crash Reports](https://developer.apple.com/library/archive/technotes/tn2151/_index.html), `EXC_BREAKPOINT` is a tell-tale sign that (**emphasis** added):
> Swift code will terminate with this exception type if an unexpected condition is encountered at runtime such as: **a non-optional type with a nil value**; a failed forced type conversion.
On line 105, we see that `count` is an implicitly unwrapped optional. While the circumstances that lead to either `ReaderSiteTopic` or `count` being `nil` aren't well-known at this …

Resolved a crash in Reader Site Stream header follow count

---

WordPress/Classes/ViewRelated/Site Creation/Shared/TableViewOffsetCoordinator.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressTableViewProvider.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.xib

Fixes #10922 
iPhone X:
iPhone SE: 
iPad Pro 11:
To test:
- Checkout the branch, run the tests
- Launch the Enhanced Site Creation flow, navigate to the Domains step, and select a domain. The Create Site button should then be visible, and wizard should not progress until the "Create Site" button is tapped.

[Site Creation] Add "Create Site" button to Domain screen

---

Podfile
Podfile.lock
WordPress/Classes/Services/MediaService.m
WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

Fixes #https://github.com/wordpress-mobile/gutenberg-mobile/issues/206
This PR implements the possibility of canceling and retry media uploads.
To test:
- Start a new post using GB
- Add an image block
- Tap on the image while the upload is happening
- Tap Cancel, and see if the image block is reset
- Add another image
- Turn off the internet while the upload is going.
- Check if the error status shows
- Turn on the internet again
- Tap on the image
- Check if an error message shows in the action sheet
- Tap on Retry
- See if upload resumes and works to the end.

GB: implement media cancel and retry

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/SelectPostViewController.swift

This PR addresses `UISearchController` issues when selecting an existing page/post to link to within the editor:
Previously, the `UISearchController` would hang around after the VC it belonged to was dismissed (`SelectPostViewController`). This caused a number of visual glitches and potentially the crasher reported in #10858.
The fix here was to simply add `searchController.dismiss(animated: false, completion: nil)` in `viewWillDisappear`. Additionally in this PR, I gave `SelectPostViewController` some organizational ❤️.
Fixes #10858 
1. Start a new post.
2. Tap the link button to add a link to the post.
3. Choose "link to existing content."
4. Search for a post/page to link to.
5. Dismiss the keyboard (you can do this by pressing the blue "Search" button on the keyboard)
6. Select a …

Editor: Fixes UISearchController issues in SelectPostViewController

---

Podfile
Podfile.lock
WordPress/Classes/Models/WPAccount+RestApi.swift
WordPress/Classes/Services/SiteSegmentsService.swift
WordPress/Classes/Services/SiteVerticalsPromptService.swift
WordPress/Classes/Services/SiteVerticalsService.swift
WordPress/Classes/Stores/ActivityStore.swift
WordPress/Classes/Stores/TimeZoneStore.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes [#78](https://github.com/wordpress-mobile/WordPressKit-iOS/issues/78), which exposes the ability to inject different locale keys into `WordPressComRestApi`.
The code can be reviewed as-is; I have only affixed the `DO NOT MERGE` label to reflect the fact that it is dependent on the review, approval, merge, & versioning of [this PR](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/87) in `WordPressKit`.
**Note:** A [separate issue](
https://github.com/wordpress-mobile/WordPressKit-iOS/issues/86) has been created in `WordPressKit` to transition the existing service methods to leverage this implicit locale-handling behavior.
To test:
- Checkout the branch, confirm that it builds & that existing tests pass.
- Review the changes here, which are limited to implicit locale handling …

Integrated locale handling changes in WordPressKit

---

WordPress/Classes/ViewRelated/Blog/BlogDetailHeaderView.m
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
WordPress/Classes/ViewRelated/Pages/PageListViewController.swift

Refs #10860 
To test:
- Put `return true` in `shouldShowQuickStartChecklist()`
- Ensure the new tours work correctly:
1. Site Icon
2. Plans
3. Stats
4. New Page
4. Renamed sharing tour

Quick Start v2: Add new tours

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/ViewRelated/Blog/BlogListViewController+SiteCreation.swift
WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift
WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
WordPress/Classes/ViewRelated/Site Creation/Shared/ErrorStates/ErrorStateViewController.swift
WordPress/Classes/ViewRelated/Site Creation/SiteInfo/SiteInformationWizardContent.swift
WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsWizardContent.swift
WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift

Fixes #10335 
To test:
Make sure every event is hit in the correct area when going through the site creation flow.
https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/179 must be merged (and released) before this is merged!

Add analytics tracking for Enhanced Site Creation

---

Podfile
Podfile.lock
WordPress/Classes/Services/PostCoordinator.swift
WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergImgUploadProcessor.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/Gutenberg/GutenbergImgUploadProcessorTests.swift

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/206
This PR adds the possibility to async publish Post on GB while images are uploading. 
To test:
- Start a new post using GB
- Add an image from the device to it
- While the upload is going on press Publish
- See the upload finish and the post published on the post list
- Go back to the post and see if all content is ok
- Do the same as above but this simulate an error while the upload is going on (go offline)
- Open the post
- And see if the image is on error state.

GB finish uploads out of editor

---

WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift
WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift

Fixes #10962 
This PR does away with the old logic that would show a NoResultsView if Plans failed to sync.  This will allow Plans to be available to offline viewing as long as there is cached data. 
Of note:
- Plans are synced as a part of the blog sync process. We should *always* have plans data available given the blog is fully synced during login.  However, on the off chance no Plans data is present we continue to show the NoResultsView explaining there was a problem syncing plans.
To test:
Apply this patch and attempt to view the Plans feature after disabling your internet connectivity. 
Confirm that cached plans load as expected.
@frosty could I trouble you for a review?

Plans: Always show syned plans

---

WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift

Fixes #10942 
@stevebaranski should be a quick one! Thanks in advance 🙇 
To test:
Go to the Verticals screen on Enhanced Site Creation and verify the search field text isn't bolded. Also verify the text changes properly with different Larger text settings.

Updating Text style of SearchTextField 

---

WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift

Fixes #10943 
To test:
Go to the Domains selection screen and verify the following:
1. The placeholder text is in the right place
2. When typing in the search field, the text starts at the right place
3. When selecting a domain, the text in the search field stays in the right place

Fixing jumping around of text in Domains search field

---

WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityDay.swift
WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityMonth.swift
WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextEmbed.swift

Fixes #n/a
This addresses an oversight @frosty noticed on a previous PR where I failed to make the delegates weak. 
To test:
Nothing should visibly/functionally change. Just give Insights and Period stats some sanity checks to ensure all works as expected.

[Stats Refresh] Update delegates to be weak

---

WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextEmbed.swift

Fixes #10930 
The video reported in #10930 was appearing much larger than it should. The cause seems to be that the markup for the `video` tag omitted a `width` attribute.  Width was defined via inline styling but we remove style information when consuming the feed.  
This PR adds a style rule to the `WPRichTextEmbed` markup to force videos to 100% of the view port width.  This seems to be the lightest touch to get the correct width. Other options were to add more string parsing to either WPRichTextFormatter (which wasn't the best fit) or RichContentFormatter but I'm loath to add even more string parsing to the Reader. 
Props to @aut0poietic for the hint to try specifying size in terms of `vw` instead of `%`. Setting to `100%` seemed to be interpreted as pixels 😱, but `100vw` matches the …

Reader: Force video tags to 100% the width of the viewport

---

WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift

Updates the suggestion logic for v2. Now only suggests a tour after completing a tour manually. No automatic suggestions.
Refs #10860
To test:
- put `return true` in `shouldShowQuickStartChecklist()`
- You'll want to review what the new logic should be, to make sure I understood it correctly:
- No more automatic suggestions.
- Once the user has completed a tour, suggest the next one
No release notes needed, yet.

Quick Start v2: Update suggestion logic

---

WordPress/Classes/Models/PublicizeConnection.swift

See p9dueE-vy-p2 for additional context. 
LinkedIn is soon making changes to their sharing API that will invalidate existing connections. Users will have to reauth and the publicize API is updating to return a new status code for the affected connections. 
This PR updates the `isBroken` check to return true for any status that does not equal "OK". This seems like some nice future proofing as affected connections will be flagged as needing to be either reconnected or disconnected.
Any custom messaging specific to the upcoming LinkedIn event will be addressed in a subsequent PR.
To test:
On an blog that has configured one or more publicize connections:
- View the Sharing screen and confirm that good connections are not flagged as needing attention (i.e. no orange exclamation mark for their …

Sharing: Treat any non-ok status as broken.

---

WordPress/Classes/ViewRelated/NUX/EpilogueSectionHeaderFooter.xib

This PR fixes the console warning:
`[TableView] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please set a custom UIView with your desired background color to the backgroundView property instead.`
that appears when the login epilogue becomes visible.  
Fixes #10959 
0. Build and run the app, log out if needed
1. Log into the app
2. When the login epilogue VC displays, verify the warning above ☝️ does not appear in the console.
----
@aerych would you mind giving this a quick 👀 ?

Fixed bg color warning in EpilogueSectionHeaderFooter

---

Podfile
Podfile.lock

Bump Gutenberg ref to release 0.3.5
To test:
- `rake dependencies`.
- Build and run the project.
- Open an instance of Gutenberg. (Without metro running)
- Check that it behaves correctly.
- Try one or a couple of late fixes.
- An easy one to test: https://github.com/wordpress-mobile/gutenberg-mobile/pull/544
- Another easy to test: https://github.com/wordpress-mobile/gutenberg-mobile/pull/525
Also try some basic functionality on blocks.

Bump Gutenberg ref to release 0.3.5

---

WordPress/Classes/Extensions/WKWebView+Preview.swift
WordPress/Classes/ViewRelated/NUX/SiteCreationSitePreviewViewController.swift
WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #10984.
This PR introduces fixes an issue where some items on a preview web view could still be interacted with. I've also extracted code which hides the WordPress.com 'get started' banner into a helper so it can be used from the site creation v2 preview.
Unfortunately there is still a dimming overlay that appears if you tap and hold on the web preview, and I'm unable to find a way to remove it. It appears to be part of the `WKWebView` itself – a `_UIHighlightView`.
**To test:**
* Navigate to Enhanced Site Creation and create a site
* At the end of the flow, scroll down through the site preview and attempt to tap in the search field. You shouldn't be able to.
cc @kwonye because I moved your code
- Nothing user facing as this is a new feature.

[Site Creation] Prevents interaction in preview webpage via CSS

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m

Refs. #10860 
This PR set _Stats_ as initial view controller on iPad split view.
Moreover the quick start section rows don't set a `restorableSelectedIndexPath` anymore and their `showsSelectionState` value is always _false_.
**To Test**:
- Put `return true` in `shouldShowQuickStartChecklist()`
- Run the app on iPad: _Stats_ should be the first section selected
- Select one of the Quick Start row, present the checklist and then dismiss it. The previous section selected shouldn't change.
- Run the app on iPhone to check that everything works as before

Quick Start V2: Stats as initial view controller  

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.xib
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/ViewMoreRow.xib

Fixes #10946 
To test:
---
- On a site with some posts, go to Stats > Period > Authors.
- Note when switching between the Period filters, the expanded rows will reset.
---
- Select an Author row.
- Max 10 child rows will be displayed, showing the Author's posts.
- There is no action for selecting a child row.

[Stats Refresh] Add Period > Authors card

---

WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.swift
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.xib
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.swift
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.xib
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistManager.swift
WordPress/Classes/ViewRelated/Blog/QuickStartListTitleCell.swift
WordPress/Classes/ViewRelated/Blog/QuickStartListTitleCell.xib
WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextEmbed.swift

Refs. #10860 
This PR adds some UI fix:
- Remove disclosure indicator on iPhone
- Fix separator inset width
- iPhone: separators are edge to edge based on the safe area layout guide
- iPad: separators are following the readable layout guide
- iPad: the list has a section header and the first todo row has a top separator
- The icon imageview is aligned correctly
**iPhone portrait**
**iPhone landscape**
**iPad**
**To Test:**
* Put `return true` in `shouldShowQuickStartChecklist()`
* Open the blog detail on iPhone to check the QS section rows
* Open the checklist to check the separator insets (on both iPhone and iPad)

Quick Start V2: UI fix

---

WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsCell.swift

Fixes an issue with localization reported by our trusty polyglots in the [dot org mobile slack](https://wordpress.slack.com/archives/C02RQC4LY/p1549966157003600).  Rather than concatenate strings in a set order, we'll use a placeholder so the translations can be composed in the correct order.
To test:
- Confirm the accessibility label is composed correctly.
- Bonus, test with voice over enabled
@ctarda could I trouble you for the review?

SiteCreation: Use a formatted string and placeholder vs concatenation.

---

WordPress/Classes/ViewRelated/Pages/PageListSectionHeaderView.h
WordPress/Classes/ViewRelated/Pages/PageListSectionHeaderView.m
WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
WordPress/Classes/ViewRelated/Post/Revisions/RevisionsTableViewController.swift

Fixes a typo of `setTite:` which should be `setTitle:`
To test:
- Ensure the app still builds and runs

Replace occurrences of `setTite` with `setTitle:`

---

WordPress/Classes/Utility/ZendeskUtils.swift

Adds a mobile_gutenberg_is_default tag to conversations if Gutenberg is the
default editor for new posts.
See https://github.com/wordpress-mobile/gutenberg-mobile/issues/564
To test:
* Go to app settings and enable Gutenberg
* Contact support
* Go to Zendesk and verify that the conversation has the `mobile_gutenberg_is_default` tag
* Repeat with Gutenberg disabled and verify that the tag is not there
cc @hypest

Add tag to Zendesk when Gutenberg is the default editor

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+InformativeDialog.swift
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/GutenbergInformativeDialogTests.swift

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/10869
Also Android side issue has some additional info about the buttons, it turns out we just need a simple OK button for now. https://github.com/wordpress-mobile/WordPress-Android/issues/9034 
Also the text "Switch to Gutenberg" is updated as "Switch to Block Editor"
**To test**
Test 1 - Verify we don't see the dialog on Classic editor
- Reinstall the app
- Turn on the Gutenberg switch
- Create a post with Classic editor on the Web and close the editor
- Open the post on mobile
- Verify that you do NOT see the informative dialog
Test 2 - Verify we see the dialog on Gutenberg editor(and only once)
- Turn on the Gutenberg switch
- Open a post on mobile that you had created with Gutenberg editor
- Verify that you DO see the …

Add Gutenberg informative dialog

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

Adds an empty implementation for the new bridge method introduced in https://github.com/wordpress-mobile/gutenberg-mobile/pull/587
Part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/556
I'll add the actual tracking code in a future PR
To test:
* Set a breakpoint on the new `gutenbergDidMount` method
* Open a Gutenberg post
* Verify the new method gets called and the parameter reflects correctly if the post has unsupported blocks.

Add new gutenbergDidMount method to delegate

---

MIGRATIONS.md
WordPress/Classes/Models/FollowersStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/FollowersStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/Models/StatsRecord+CoreDataClass.swift
WordPress/Classes/WordPress.xcdatamodeld/WordPress 87.xcdatamodel/contents
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/FollowersStatsRecordValueTests.swift
WordPress/WordPressTest/LastPostStatsRecordValueTests.swift
WordPress/WordPressTest/StatsRecordTests.swift
WordPress/WordPressTest/StatsTestCase.swift
WordPress/WordPressTest/StatsTestsHelpers.swift

Follow-up to #11000.
There's gonna be a whole bunch of those coming in over the past few days — I'll try to keep to one entity/PR for ease of review. 
For now, this is targeting the branch that #11000 is based off of — after that'll get merged, I'll change the base to `feature/stats-core-data-finished`.
To test:
* Verify that the app builds
* Verify that the tests pass.

Add `FollowersStatsRecordValue` entity to Core Data

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/Utility/Editor/GutenbergSettings.swift

Adds the Gutenberg setting tracking described on https://github.com/wordpress-mobile/gutenberg-mobile/issues/556:
* App setting to enable Gutenberg: `gutenberg_setting_enabled` when switched on, `gutenberg_setting_disabled` when switched off.
* Add a `gutenberg_enabled` property to the user properties that are sent with every event.
To test:
The best way to test the events is to look at the logs, but it gets too noisy with React Native. You can edit the Xcode scheme, and in Run > Arguments enable the `OS_ACTIVITY_MODE=disable` environment variable. You can also search for `🔵` in the log but that would filter out the event properties 😞
You can't see the userProperties in the logs, so you can add a breakpoint and inspect `self.tracksService.userProperties`
Also, it's a good idea to do a …

Gutenberg settings tracking

---

WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift

👋🙉🙊😢
Fixes the iOS part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/567
To test:
1. Go to App Settings
2. Notice the lack of emoji and tension around the copy
3. 😭 
cc @hypest @iamthomasbishop

Update copy for Gutenberg toggle

---

WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift

Follow-up to #11044
To test:
* Go to app settings
* The Gutenberg setting explanation has a period at the end

Period at the end of Gutenberg setting footer

---

WordPress/Classes/ViewRelated/Blog/QuickStartChecklistManager.swift

Refs. #10860 
This pr fixes a problem @frosty found on the Quick start checklist. The swipe to left gesture to skip a tour is enabled for the completed section as well. This is wrong.
**To test:**
• Open a quick start checklist
• Skip a tour
• Expand the completed list and try to swipe to skip. It shouldn't appear any skip button.

Quick Start V2: Fix swipe to skip

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Fixes iOS part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/566
To test:
What I tried was editing the scheme to build the `Release` configuration. The Gutenberg setting in app settings wasn't available in develop but it is on this PR

Enable Gutenberg for all builds

---

WordPress/Classes/System/WordPressAppDelegate.m
WordPress/Classes/Utility/PushNotificationsManager.swift
WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
WordPress/Classes/ViewRelated/Me/MeViewController.swift
WordPress/Classes/ViewRelated/System/FancyAlertViewController+QuickStart.swift
WordPress/WordPressTest/PushNotificationsManagerTests.m

Refs. #10860 
This PR adds the local notification (as reminder for the next available tour) when a tour is completed.
• Reminder for the next uncompleted task is scheduled to go off in 48 hours after completing a task.
• Completing a task cancels current reminder and schedules a new one.
• Clicking on the notification will open the app even if it was closed and navigate to MySite tab.
• A reminder will not be scheduled when you complete Edit Post task before starting QS.
• A reminder will be canceled on logout.
• A reminder will be canceled on new site creation.
• A reminder will be canceled when you switch active site.
**To Test**:
• create a new site (otherwise the 'create a site' item won't appear) **OR** open a site that previously started (or completed) quick start
• Complete or skip …

Quick Start V2: Local notifications for the next available tour

---

Gemfile
Gemfile.lock
Rakefile

There have been a few cases recently where `rake dependencies` didn't trigger a `pod install` when it should have. This is because `cocoapods-check` sometimes think there are no pods to install when this is not the case (particularly when dealing with commit hashes).
This is a small change to just check if `Podfile.lock` matches `Pods/Manifest.lock` to decide if pods should be installed.
To test:
- If you removed `Pods/Manifest.lock` `rake dependencies` should install pods.
- Running `rake dependencies` again should do nothing.

Rakefile: Don't use 'cocoapods-check' to check if pods should be installed

---

.circleci/config.yml

This updates the iOS Orb from 0.0.12 to 0.0.20 for lots of incremental improvements.
Here are some of the relevant changes this includes:
- iOS: Disable indexing while building: https://github.com/wordpress-mobile/circleci-orbs/pull/12
- Preboot simulator to improve xcodebuild stability: https://github.com/wordpress-mobile/circleci-orbs/pull/5
These have combined to give a modest improvement in build times (it seems to be around 30 seconds faster).
This is a draft until https://github.com/wordpress-mobile/circleci-orbs/pull/12 is reviewed and merged.
To test:
- CircleCI checks are green

CircleCI: Update Orb for improved build performance

---

WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift

Fixes #11051 
Refs. #10860 
This fixes a bug with the notice appearing every time the checklist is dismissed after a tour is completed.
To fix this i set the `recentlyTouredBlog` to nil when the tour is skipped. @nheagy I saw that atm this property is used only for this purpose. If not I'd like to use another approach storing the state.
**To test:**
- Complete a task or create a new site and then enable the quick start feature
- Present and dismiss the checklist. It should trigger the notice once as soon the notice disappear.

Quick Start V2: Prompt for next step appearing when exiting checklist VC

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistManager.swift
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift

Refs. #10860 
This PR fix a bug introduced changing the checklist presentation style. After the checklist is dismissed the notice doesn't appear correctly. It appears over the tab bar.
To fix it the selected tour starts after the checklist is definitely dismissed.
**To Test:**
• Open a qs checklist and select a tour
• The notice won't be displayed over the tab bar anymore

Quick Start V2: Fix notice bug

---

WordPress/Classes/Models/SearchResultsStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/SearchResultsStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/Models/StatsRecord+CoreDataClass.swift
WordPress/Classes/WordPress.xcdatamodeld/WordPress 87.xcdatamodel/contents
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/SearchResultsStatsRecordValueTests.swift

Follow-up to #11000, another one in line with #11010, #11011 (all those PR have binary numbers!), #11016, #11017, #11038 and #11038.
There's gonna be a whole bunch of those coming in over the past few days — I'll try to keep to one entity/PR for ease of review.
To test:
* Verify that the app builds
* Verify that the tests pass.

Add `SearchResultsStatsRecordValue` entity to Core Data

---

WordPress/Classes/Models/StatsRecord+CoreDataClass.swift
WordPress/Classes/Models/TopViewedAuthorStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/TopViewedAuthorStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/Models/TopViewedPostStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/TopViewedPostStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/WordPress.xcdatamodeld/WordPress 87.xcdatamodel/contents
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/TopViewedStatsTests.swift

Follow-up to #11000, another one in line with #11010, #11011 (all those PR have binary numbers!), #11016, #11017, #11038, #11038 and #11047.
There's gonna be a whole bunch of those coming in over the past few days — I'll try to keep to one entity/PR for ease of review.
To test:
* Verify that the app builds
* Verify that the tests pass.

Add `TopViewedAuthorStatsRecordValue` and `TopViewedPostStatsRecordValue` entities to Core Data

---

WordPress/Classes/Models/Blog+QuickStart.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsSectionHeaderView.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsSectionHeaderView.xib
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Blog/QuickStartListTitleCell.swift
WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Refs #10860
This adds the ellipsis menu that allows quick start to be removed.
To test:
- Don't force quick start to appear. You'll have to actually have QS enabled—putting a `QuickStartTourGuide.find()?.setup(for: blog)` somewhere makes this a big easier 😆
- Ensure that you can use the ellipsis menu to remove the QS cells

Quick Start v2: Add Ellipsis Menu

---

WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m

This PR fixes the `Argument is not a literal string.` error that `getstrings` raises when one of the  arguments of `NSLocalizedString`  is dynamic.

Update a localised string to have literal content

---

WordPress/Classes/Utility/Debouncer.swift
WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/DebouncerTests.swift

This PR improves the `Debouncer` class in three ways:
1. It no longer waits to trigger if it's being released.  This ensures that if the owner of the `Debouncer` is being released, it will be able to trigger the last call before it's actually released.
2. [The callback is no longer optional](https://github.com/wordpress-mobile/WordPress-iOS/pull/11015/files#diff-d025383eb1161f651ad2ec8c7b154b2cR6), as the debouncer would make no sense without a callback.
3. [Adds automated tests](https://github.com/wordpress-mobile/WordPress-iOS/pull/11015/files#diff-87b0abffcbd8e06248ecc2d337dff76fR4) covering both the regular scenario, and the scenario in which we want the `Debouncer` to be released immediately.
To test the original issue, check out `develop` and change this line: …

Debouncer improvements

---

MIGRATIONS.md
WordPress/Classes/Models/ClicksStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/ClicksStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/Models/CountryStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/CountryStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/Models/ReferrerStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/ReferrerStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/Models/StatsRecord+CoreDataClass.swift
WordPress/Classes/Models/TopViewedVideoStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/TopViewedVideoStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/Models/VisitsSummaryStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/VisitsSummaryStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/WordPress.xcdatamodeld/WordPress 87.xcdatamodel/contents
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/ClicksStatsRecordValueTests.swift
WordPress/WordPressTest/CountryStatsRecordValueTests.swift
WordPress/WordPressTest/ReferrerStatsRecordValueTests.swift
WordPress/WordPressTest/StatsRecordTests.swift
WordPress/WordPressTest/TopViewedVideoStatsRecordValueTests.swift
WordPress/WordPressTest/VisitsSummaryStatsRecordValueTests.swift

Follow-up to #11000, another one in line with #11010, #11011 (all those PR have binary numbers!), #11016, #11017, #11038, #11038, #11047 and #11048.
This should be the last one for now! :) 
It's a bigger one, since I rolled up five new entities into one PR, but if I had to manually resolve conflicts five more times I think I would lose some marbles.
Hopefully it's still palatable — a fair amount of the +703/-94 is the auto-generated Core Data interfaces, so the actual changes to look over shouldn't be too bad :)
To test:
* Verify that the app builds
* Verify that the tests pass.

Stats Refresh: rest of Core Data models

---

Podfile
Podfile.lock

This PR updates the GB-mobile reference in order to get updated bridge code to support latest events in GB-mobile.
To test:
- Launch the GB editor and see if no red screen shows up.

Update gb-mobile reference.

---

WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #n/a (problem mentioned in https://github.com/wordpress-mobile/WordPress-iOS/pull/11079 description)
Previously, because tracking expanded rows was done only by Insights or Periods, it allowed for duplicate entries. This changes the tracking to be done by what `StatSection` the expanded row is in.
To test:
This fix is applicable to all expandable rows, but it is easily testable by these specific stat rows:
- On the en.blog site, go to Stats > Period.
- Expand _either_ Referrers _or_ Clicks `en.support.wordpress.com`
- Scroll down so that neither card is visible.
- Scroll back up, and verify only the one you expanded is still expanded.

[Stats Refresh] Remove duplicates from expanded row tracking

---

WordPress/WordPressTest/DebouncerTests.swift

A test was failing due to a timer set to trigger after 0.5 ms triggering after 0.61 ms.  This is normal as timer's based on `Timer` aren't 100% precise, but the error the test was allowing was 20%, which applied to 0.5ms gives us a maximum of 0.6ms allowed (short of 0.61ms).
I just changed the error value to allow for a 25% error.
Just make sure the tests succeed.

Allows for a wider error range in a failing test.

---

WordPress/WordPressTest/DebouncerTests.swift

Follow up to: https://github.com/wordpress-mobile/WordPress-iOS/pull/11089
Further raises the allowed error margin to 50%.
Kudos to @ScoutHarris for spotting this one.

Increases the error marging in a test.

---

Podfile.lock
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes:
To test:
Run pod install (bundle exec) and see that there's no warning.

Fix UUID warning on pod install

---

WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

This PR implements focus title on new posts. Following from https://github.com/wordpress-mobile/gutenberg-mobile/pull/633.
To test:
- Please refer to the `gutenberg-mobile` [side PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/633).

Gutenberg: Focus title on new posts.

---

WordPress/Classes/Models/Blog+Analytics.swift

Follow up for #11040
When doing the Android implementation in https://github.com/wordpress-mobile/WordPress-Android/pull/9293 we discovered there's a lint check there that tells you to use `wpcom` and not `dotcom`, so we switched to that
To test:
- Create a new post on a WordPress.com blog
- Debug and inspect the editor session events, and verify that the `blog_type` property has `wpcom` and not `dotcom` in it
cc @mzorz 

Rename blog type from dotcom to wpcom

---

WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift

Fixes #n/a
While working on the Stats detail list view, I realized it needed access to the strings for the stat cards (i.e. card title and column titles). However, these strings were private and in different view models. So I took advantage of the `StatSection` enum, and moved all the strings out of the view models and into `StatSection`. And since it was a considerable refactor, it gets its very own PR.
Now, these strings can be accessed just by knowing the `StatSection`. As an added bonus, this refactor allowed several duplicate strings to be removed. 🎉 
To test:
Visibly, nothing should change. Just verify all the cards have the correct card titles and column titles (where applicable), i.e. these three labels:

[Stats Refresh] Make stat section labels accessible

---

WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

This PR makes sure we are saving a revision every time we get new HTML from the GB-JS
To test:
- Start writing to it
- Open the Post Settings or Switch to Aztec
- Kill the app
- Open the app again
- See if changes are saved.

Gutenberg auto-save improvements

---

WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextEmbed.swift

Refs: #11078
This is a partial fix for the issues outlined in #11078. The complete fix is going to be more involved and not something I'd be comfortable landing in a release branch this close to submitting to the app store.
By setting the height to auto, we force the tag to preserve its aspect ratio. With this change, a video tag that has a width and height defined via attributes will be correctly sized even tho we override the width to match the viewport.
This change also removes some extra white space around the top and left of the video by setting margins and padding to zero.
Notice the cropping on the bottom video. This appears to be because its internal document height is matching the height of the video tag's height attribute.
Notice the video is correctly centered.
To test:
View a …

Reader: Set video tag height to auto, remove padding and margins.

---

WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

Implements autosave of posts in Gutenberg using a timer with a 5s interval.
To test:
- Write some test
- Wait at least 5s
- Stop the app or force quit.
- Restart the app
- See if the post content is kept/saved.

Auto save post in Gutenberg.

---

Scripts/fastlane/Fastfile

As discussed this removes the step to set branch protection on every release branch.
Since Github now supports patterns for branch protection rules we no longer need to set it on individual branches through the API.
I have set up a protection rule for `release/*` so release branches are automatically protected.
Related to https://github.com/wordpress-mobile/release-toolkit/pull/24.
I don't think there is any need to update the release-toolkit since the only change is that this action is removed.
To test:
- See that we no longer call `setbranchprotection `.

Code freeze: Don't add branch protection to individual release branches

---

Podfile
Podfile.lock

This PR updates Gutenberg to 1.0.1.
To test:
- Open an instance of Gutenberg.
- Check that everything looks fine.

Update gutenberg to version 1.0.1

---

Gemfile.lock
Scripts/fastlane/Pluginfile

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/11123 (cc @jkmassel )
The issue is fixed because the `git` gem is now an explicit dependency of the release toolkit (https://github.com/wordpress-mobile/release-toolkit/pull/29).
To test:
- The following commands run without error (you can choose `cancel` when asked for which lane to run):
```
rake dependencies
cd Scripts
bundle exec fastlane
```

Update release toolkit to 0.1.8

---

RELEASE-NOTES.txt
WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Refs #10860
This makes Quick Start v2 live for everyone.
Depends on #11132 being merged.
To test:
- Make sure QS v2 is on for everyone 😉
```
* Quick Start v2: After creating a new site with WordPress.com there are more tutorials available, now including tips to improve growth.
* Quick Start will also be suggested less often, but when it's more likely to be helpful.
```

Quick Start v2: Turn it on!

---

WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift

While testing https://github.com/wordpress-mobile/WordPress-iOS/pull/11132, I noticed that Quick Start hasn't been added to the Enhanced Site Creation flow, which is [now the only way of creating sites](https://github.com/wordpress-mobile/WordPress-iOS/pull/11133). This PR is my attempt at adding Quick Start there, but let me know if I've done it wrong.
**To test:**
* Create a site using the new site creation flow
* Ensure you see Quick Start after dismissing the preview at the end of the flow.

Added Quick Start to Enhanced Site Creation flow

---

Podfile
Podfile.lock

Helps address a [WordPressKit issue](https://github.com/wordpress-mobile/WordPressKit-iOS/issues/109) related to nil parameters and locale handling. 
I've marked this as a Draft PR, pending the approval, merge & release of the supporting [WordPressKit PR](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/111).
To test:
- Smoke test the app, confirm that nothing looks out of sorts.

Absorbed defect-resolving changes to WordPressKit

---

WordPress/Classes/Models/AllTimeStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/AllTimeStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/Models/AnnualAndMostPopularTimeStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/LastPostStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/StatsRecord+CoreDataClass.swift
WordPress/Classes/Models/StatsRecordValue+CoreDataClass.swift
WordPress/Classes/WordPress.xcdatamodeld/WordPress 87.xcdatamodel/contents
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/AllTimeStatsRecordValueTests.swift
WordPress/WordPressTest/AnnualAndMostPopularTimeStatsRecordValueTests.swift
WordPress/WordPressTest/LastPostStatsRecordValueTests.swift
WordPress/WordPressTest/StatsTestCase.swift

This is first part of addressing #11153.
The basic shape/idea of it is sorta analogous to how `StatsServiceRemoteV2` works: one centralized, generic function where a lot of "magic" takes place, with a bunch of boring/mundane data marshalling between formats in appropriate subclasses.
In this case, most of the work is being done in Core Data `StatsRecordValue` subclasses implementing conformance to `StatsRecordValueConvertible` protocol for their respective `WordPressKit` counterparts.
My plan for tackling the entirety of Peristence work in Stats is roughly:
1. Handle mapping Insights data from WPKit format into Core Data entities (#11153) 
2. Make the `StatsInsightsStore` able to use the persisted data and persist new one to disk
3. Optional, TBD if I'll end up going this route: 
Ideally …

Stats: mapping Insights into Core Data models, part 1

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m

This makes the `WPAnalyticsStatQuickStartRemoveDialogButtonTapped` into two events with properties set in the definition instead of when used.
@stevebaranski got a moment to check this out?

Cleanup QS v2 events

---

WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift

Fixes #11149
After skipping a tour in one of the quick start checklists, there will no longer be a suggestion.
To test:
- Skip a QS checklist (let me know if you need advice how to get this list)
- Ensure that when the list is dismissed a suggestion doesn't appear
- Also ensure that only the skipping event fires, and that no analytics for completion.

Stop marking skipped tours as complete

---

Scripts/fastlane/Fastfile
WordPress/Resources/AppStoreStrings.po

This PR reverts https://github.com/wordpress-mobile/WordPress-iOS/pull/11110. 
As I mentioned in that PR, putting html into the strings seems to break GlotPress. 
I checked that the file can't be loaded because of a parsing error. Removing the strings with the html tags fixes it. 

Fix errors in metadata

---

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
WordPress/Classes/ViewRelated/People/PeopleViewController.swift
WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
WordPress/Classes/ViewRelated/Post/PostListFilter.swift
WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
WordPress/Classes/ViewRelated/System/FilterBar.swift

While working on UI Test Automation, I needed to add support for accessibility identifiers on a couple of different filters (Posts List and Stats). This allows the XCUITest runner to properly tap buttons on-screen, regardless of their position or translated labels.
Because the work was being done in a couple of places, and I suspect we'll do be doing more soon, I  added a protocol for individual tab items that'll ensure the required fields that are always available.
I considered stopping here, as the protocol for the updated `FilterTabBar` _can_ live side-by-side with the `[String]` methods, but it seemed messy to leave two implementations in place across the codebase, especially as there are only five instances of `FilterTabBar` being used.
I went through and conformed all of the data …

Add accessibility identifier support for filters

---

Podfile
Podfile.lock

Fixes: not a specific issue, just weakified self usages where needed https://github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view/commit/f2acb44d71a169fa021f92166b336cbedd9b4d49
**To test:**
Just some smoke test would be enough.
The test in this issue can be used https://github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view/pull/5

Bump up react-native-keyboard-aware-scroll-view version

---

WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m

Fixes #10767 
This was a trivial fix. Just swapped the placement of the buttons. Functionality unchanged.
To test:
- Navigate to Post Settings by clicking on the ellipses at the top right
- Select 'Set Location'
- Notice that the 'Done' bar button is now on the right, and the 'Remove' bar button is on the left.
- Nothing to update

Swap position of 'Done' and 'Remove' buttons (PostGeolocationViewController)

---

WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
WordPress/Classes/ViewRelated/Pages/ParentPageSettingsViewController.swift

Fixes #11186 
This PR introduces the dynamic font size to the PPP Page cell and the set parent cell.
It also fixes a bug where the _Noto bold_ font wasn't load correctly in the PPP Page cell.
_Before_
_After_
**To test:**
- Open the page list, you should see the title label using the _Noto bold_ as font.

Properly Placed Pages: using dynamic font size

---

WordPress/WordPress.xcodeproj/project.pbxproj

I noticed that the "Generate API credentials" does not have the config file as an input. This means that when it is updated, Xcode won't know it needs to re-generate it.
This is what I added:
To test:
- Change a value in `~/.mobile-secrets/iOS/WPiOS/wpcom_app_credentials`
- Re-build and see that `Derived Sources/Api Credentials.m` has been updated.

Add as input file for credentials build phase

---

WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m

This is part of #11187 
Because I didn't push the change before, this Pr fix the menu icon used by the page list cell, replacing the local image with the image generated by _Gridicon_.

PPP: Fix gridicon icon

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift

Fixes #11150.
| ![11150pr_before](https://user-images.githubusercontent.com/221062/53895927-e7c5b580-3fe7-11e9-9ef1-896a06ad467c.png) | ![11150pr_after](https://user-images.githubusercontent.com/221062/53895926-e7c5b580-3fe7-11e9-9410-44cbd0cd6602.png) |
To test:
- Checkout the branch, confirm that it builds, and that existing tests pass.
- Execute the site creation flow, and attempt to interact with the status bar post-creation. Observe that it does not become first responder.

Disabled text field in assembled site view

---

Gemfile.lock
Scripts/fastlane/Fastfile
Scripts/fastlane/Pluginfile

Reverts wordpress-mobile/WordPress-iOS#11117 and updates release toolkit to 0.1.9 (so the action is available).

Revert "Code freeze: Don't add branch protection to individual release branches"

---

Podfile
Podfile.lock

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/673
This PR updates the gutenberg ref to add a fix on dictation.
The original issue was that, after dictation finishes, the inserted (dictated) string would disappear, leaving the block empty again.
More info:
https://github.com/wordpress-mobile/gutenberg-mobile/pull/700
To test:
- Run `rake dependencies`.
- Clean build folder.
- Run the app **without** metro running.
- Test the dictation feature on an empty paragraph block.
- Check that it behaves as expected.

Gutenberg: Fix dictation issue

---

WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift
WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.xib
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.xib
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
WordPress/Classes/ViewRelated/System/FilterBar.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #11192 
This adds the Period Overview card. The data is fake for now, but the functionality can still be seen. Also, there is a temporary view for the chart area.
To test:
- Go to Stats > Period. 
- The hero value and label matches the tab selected.
- Selecting different tabs will update the hero value and label, and the difference value.
- The hero value is abbreviated after 99,999.
- The difference value and difference percent are abbreviated after 9,999.
- If the difference is negative, the text is red. If positive, green.

[Stats Refresh] Add Period > Overview card

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m

This is an attempt to resolve the issue of Quick Start's customization checklist appearing at app launch.
I have been unable to recreate this issue, so I've attempted to make the code that decides to show the customize checklist more specific, such that it hopefully won't trigger in error.
To test:
- Ensure that creating a site can cause the quick start checklist to appear _as intended_.
- If you can reliably get the customize checklist to appear in error before this change, please try after it! 🤞

Make handleDataModelChange more resilient

---

Podfile
Podfile.lock

This PR updates the gutenberg ref for testing v1.0.2
Changes:
- Hot fix on iOS writing flow. 
https://github.com/wordpress-mobile/gutenberg-mobile/pull/694
To test:
- Run `rake dependencies`.
- Clean build folder.
- Run the app and open a Gutenberg instance.
- Check that https://github.com/wordpress-mobile/gutenberg-mobile/issues/603 and https://github.com/wordpress-mobile/gutenberg-mobile/issues/693 are solved.
- Smoke test around to see if everything seems right.
**Note:** The only change from 1.0.1 is that hot fix, nothing else we have been working on the last week has been included.
cc @loremattei , @koke , @hypest

Gutenberg v1.0.2

---

WordPress/Classes/Extensions/UIImageView+SiteIcon.swift
WordPress/Classes/Extensions/URL+Helpers.swift
WordPress/Classes/Utility/Media/ImageLoader.swift
WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.h
WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.m

This PR adds an extra check where we try to add the security token to request. 
This is mainly done when we try to fetch images from sites that are private.
To test:
- Open a private site and create a post.
- Add images from the media library to the post.
- Check if you can see the images.
- For extra check
- Add an image to the post from another non WP.com site
- Check that the request for that image doesn't get the token ( use litle snitch or Charles Proxy) to check it.

Check if URLs were token is being added are on WP.com

---

Podfile
Podfile.lock

This PR updates Aztec to 1.4.4. It also updates Gutenberg with the changes needed to handle the changes on Aztec.
Starting with commit hashes before the formal Aztec release.

Updating aztec and gutenberg refs to test Aztec v1.4.4

---

Podfile
Podfile.lock

This PR updates the Gutenberg ref to the version 1.1.0. Starting with the hash for testing.
Release PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/726
To test:
- Run `rake dependencies`.
- Build the project.
- Open a Gutenberg instance.
- Smoke test to see if everything is fine.
- Check that recent fix is present (i.e. dictation should work properly).

Update Gutenberg ref for release v1.1.0

---

WordPress/Classes/ViewRelated/Stats/Charts/Charts+AxisFormatters.swift
WordPress/Classes/ViewRelated/Stats/Charts/Charts+Styling.swift
WordPress/Classes/ViewRelated/Stats/Charts/Charts+Support.swift
WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
WordPress/Classes/ViewRelated/Stats/Charts/Stubs/PeriodDataStub.swift
WordPress/Classes/ViewRelated/Stats/Charts/Stubs/PostSummaryDataStub.swift
WordPress/Classes/ViewRelated/Stats/Charts/Stubs/Stub+Shared.swift
WordPress/Classes/ViewRelated/Stats/Charts/Stubs/period_data.json
WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.xib
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #11063, which calls for the introduction of chart styling for period data, with an emphasis on the overlay of Visitors / Views data. 
To test:
- For a site, navigate to Stats, and select a given period (i.e., Days, Weeks, Months, Years). 
- Please note that at the moment, the chart is the same regardless of period or dimension (Views, Visitors, Likes, Comments).
_iPad - Portrait_
_iPad - Landscape_
_iPhone SE_

Preliminary implementation of Period Chart

---

WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.xib
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift

Ref #11189 
This adds a chart card to the Post Stats view. The chart card is the same as the Period Overview card, with the Filter Bar hidden. For now, it is displaying fake data.
To test:
- Go to Post Stats. From either:
- Insights > Latest Post Summary > View more.
- Period > Posts and Pages > row selection.
- Verify the chart appears.

[Stats Refresh] Post Stats: add chart card

---

WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Fixes #11190.
To test:
- Navigate to the Post Stats screen, and inspect the rendered Chart. It should look the same as #11173; or like the chart on the Insights screen, but with tappable bars.
- Navigate to a period screen, and confirm that it still looks like #11210.

 Modified OverviewCell to support injected data & styling

---

WordPress/Classes/Services/MediaThumbnailCoordinator.swift
WordPress/Classes/Utility/Media/ImageLoader.swift
WordPress/Classes/ViewRelated/Media/CachedAnimatedImageView.swift
WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m

Fixes #11188 
This PR fixes a problem with the Page and its featured image. At the moment, if a Page featured image is set up from outside (using the website or another device), is not possible to see that image when a blog is synchronised. This because if the featured image is not present in the local data model a new model is created marked as _stub_ containing only the media id.
Also the `ImageLoader` used to load the featured image returns if a _Media_ doesn't contain a valid URL.
**To test:**
- Select a blog using another device
- Open the pages list and set a featured image
- Select the same blog on your device and open the pages list
- You should all the featured images

PPP: Featured image not displayed

---

WordPress/Classes/Stores/StatsInsightsStore.swift
WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Fixes #11232 
On the Insights Tags and Categories card, selecting `View more` will now show a full list of Tags and Categories.
- When a row is selected, a web view is displayed for that tag/category (same behavior as the Insights card).
- Expanding rows are supported, and behave the same as on the Insights card.
**NOTE:** Currently, there is no API call to get the full list of Tags and Categories. So for now, this displays the data fetched from the "top" Tags and Categories API call used for the Insights card. (cc @jklausa issue #11238 )
To test:
---
- On a site with more than 6 tags/categories, go to Insights > Tags and Categories > View more.
- Hogwarts and en.blog usually have some.

[Stats Refresh] Insights Tags and Categories: add detail list view

---

Podfile
Podfile.lock
WordPress/Classes/Models/WPAccount.m
WordPress/Classes/Services/NotificationSettingsService.swift
WordPress/Classes/System/WordPressAppDelegate+Swift.swift
WordPress/Classes/System/WordPressAppDelegate.m
WordPress/Classes/Utility/PingHubManager.swift
WordPress/Classes/Utility/WPAuthTokenIssueSolver.m
WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift

Currently, when the oAuth2 token is revoked, the app doesn't notice unless you refresh the posts list.
This PR will add a handler to, whenever we receive an `invalid_token` response from WordPress.com, present the login screen and remove that token from the keychain
To test:
1. Log in to the app
2. Go to https://wordpress.com/me/security/connected-applications and disconnect WordPress for iOS
3. Navigate somewhere in the app, any network request should trigger the login screen
If you kill and relaunch the app, you should also get a prompt to log in

Improve re-authentication prompts

---

RELEASE-NOTES.txt
WordPress/Classes/Services/AccountSettingsService.swift
WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #11214
This PR adds the error message to the notification when account settings fail to update and display an error message if one is provided by the server.
To test:
- Open the app
- Make sure you are logged in with a WP account
- Open Me->Account Settings
- Try to change your email to an email already being used.
- Check that an error notification is displayed like above

Display error message provided by the server when setting change fails.

---

Podfile
Podfile.lock
WordPress/Classes/Models/WPAccount.m
WordPress/Classes/Services/NotificationSettingsService.swift
WordPress/Classes/System/WordPressAppDelegate+Swift.swift
WordPress/Classes/System/WordPressAppDelegate.m
WordPress/Classes/Utility/PingHubManager.swift
WordPress/Classes/Utility/WPAuthTokenIssueSolver.m
WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift

This brings the invalid token fix up release 12.0 the same work that was done here for 11.9 https://github.com/wordpress-mobile/WordPress-iOS/pull/11245
To test:
- Check the original PR above to see the steps needed.

Fix invalid token on release 12.0

---

WordPress/Classes/Models/AllTimeStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/AnnualAndMostPopularTimeStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/LastPostStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/PublicizeConnectionStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/StatsRecord+CoreDataClass.swift
WordPress/Classes/Models/StatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/StreakInsightStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/StreakInsightStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/Models/StreakStatsRecordValue+CoreDataProperties.swift
WordPress/Classes/Models/TagsCategoriesStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/TodayStatsRecordValue+CoreDataClass.swift
WordPress/Classes/WordPress.xcdatamodeld/WordPress 87.xcdatamodel/contents
WordPress/WordPressTest/PublicizeConectionStatsRecordValueTests.swift
WordPress/WordPressTest/StreakStatsRecordValueTests.swift
WordPress/WordPressTest/TagsCategoriesStatsRecordValueTests.swift

I was hoping to have entirety of this work wrapped by today, but it's been hard getting into the groove after AFK, so here we are :)
This adds more support for mapping more of Stats Insights into Core Data entities, namely:
* Streak
* Publicize
* Tags/Categories
This leaves us with:
* Dotcom/Email followers
* Most commented posts / top comment author
to wrap up Insights persistence and then then move on to the TimeInterval-related data.

[Stats Refresh] Add Core Data mapping code for Publicize, Streak and Tags/Categories

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift

Fixes #11248 
On the Period Posts and Pages card, selecting `View more` will now show a full list of Posts and Pages. The rows should look and behave like they do on the Period Posts and Pages card:
- Each row as a percent data bar.
- When a row is selected, Post Stats is displayed.
**NOTE:** Depending on the number of pages/posts, it could take several seconds for the view to load (en.blog is a good example). While you're staring at a blank screen, please keep in mind there is an outstanding issue to show a loading view (#11166).
To test:
- On a site with more than 6 posts/pages, go to Period > Posts and Pages > View more.
- Verify selecting a row displays the Post Stats view.

[Stats Refresh] Period Posts and Pages: add detail list view

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Fixes #11252 
On the Period Search Terms card, selecting `View more` will now show a full list of Search Terms. The rows should look like they do on the Period Search Terms card. There is no row selection action.
**NOTE:** Depending on the number of search terms, it could take several seconds for the view to load (en.blog is a good example). There is an outstanding issue to show a loading view (#11166).
To test:
- On a site with more than 6 search terms, go to Period > Search Terms > View more.

[Stats Refresh] Period Search Terms: add detail list view

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift

Fixes #11254 
On the Period Videos card, selecting `View more` will now show a full list of Videos. The rows should look like they do on the Period Videos card, and row selection is the same, i.e. media details is displayed.
**NOTE:** Depending on the number of videos, it could take several seconds for the view to load. There is an outstanding issue to show a loading view (#11166).
To test:
- On a site with more than 6 videos, go to Period > Videos > View more.
- Verify selecting a row displays the media details.

[Stats Refresh] Period Videos: add detail list view

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift

Fixes #11262 
On the Period Clicks card, selecting `View more` will now show a full list of Clicks. The rows should look like they do on the Period Clicks card, and row selection is the same:
- If a row has child rows, the row will expand.
- If a row has no child rows, a web view is displayed for the URL.
**Bonus:** this also fixes the row expansion from stat card to details and back to stat card to be consistent with Android. Android retains the expanded state on the card independently from the details view. In other words, if a row is expanded in the card, it is not expanded on the details, but is still expanded when the details is closed. (This last step is the difference - previously, expanded rows were being reset on the card.)
**NOTE:** Depending on the number of clicks, it could …

[Stats Refresh] Period Clicks: add detail list view

---

WordPress/Classes/ViewRelated/Stats/Charts/Charts+Styling.swift
WordPress/Classes/ViewRelated/Stats/Charts/Charts+Support.swift
WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift

Fixes #11230.
To test:
- For a site, navigate to Stats, and select a given period (i.e., Days, Weeks, Months, Years). The image should look like those below.
- Please note that at the moment, the chart is the same regardless of period or dimension (Views, Visitors, Likes, Comments).

Improved the appearance of the Period chart with highlights & overlaid bars

---

Scripts/fastlane/Deliverfile

Cherry picking the commit from https://github.com/wordpress-mobile/WordPress-iOS/pull/11259 to apply it to `develop`.

Remove old comments from Deliverfile

---

WordPress/Classes/Utility/Debouncer.swift

*** At the time of writing this fix we were not able to reproduce this issue.
We assume that the fireDate is somehow in the past for a valid timer and so it never gets invalidated in digit.
As a result, the callback has an unowned self that is pointing to a deallocated object.
Since the callback is already handling weak references, we're removing the capture of self and instead capturing only the callback.
Fixes #11257 
To test:
Could not reproduce. 
Seems like this issue happens after editing a post and then discarding. 

An attempt to fix crash in Debouncer callback.

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Fixes #11267  
On the Period Authors card, selecting `View more` will now show a full list of Authors. The rows should look like they do on the Period Authors card, and row selection is the same:
- If a row has child rows, the row will expand.
- If a row has no child rows, there is no row selection action.
**NOTE:** Depending on the number of authors, it could take several seconds for the view to load. There is an outstanding issue to show a loading view (#11166).
To test:
---
- On a site with more than 6 authors, go to Period > Authors > View more.
---
- Verify selecting an expandable row shows child rows.

[Stats Refresh] Period Authors: add detail list view

---

WordPress/Classes/Extensions/UIAlertController+Helpers.swift

setting up the popoverPresentationController source view to fix the crash.
Fixes #11184 
To test:
1. Go to reader/ notifications 
2. Choose a post with comments. 
3. Long press the time stamp label. 
4. See the "Copy link to comments" pop over. 

Fixed crash on long press time stamp on iPad.

---

Rakefile

Hound uses SwiftLint 0.27.0 so this makes our Rakefile use that version. It also simplifies the logic for downloading SwiftLint to use the portable zip file rather than attempting to extract the `.pkg`.
Woo PR is here: https://github.com/woocommerce/woocommerce-ios/pull/771
Test:
- `rake lint` should work correctly.

Update SwiftLint to 0.27.0

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Fixes #11276   
On the Period Referrers card, selecting `View more` will now show a full list of Referrers. The rows should look like they do on the Period Referrers card, and row selection is the same:
- If a row has child rows, the row will expand.
- If a row has no child rows, a web view is displayed.
**NOTE:** Depending on the number of referrers, it could take several seconds for the view to load. There is an outstanding issue to show a loading view (#11166).
To test:
---
- On a site with more than 6 referrers, go to Period > Referrers > View more.
---
- Verify selecting an expandable row shows child rows.
---
- Verify selecting a non-expandable row shows a web view.

[Stats Refresh] Period Referrers: add detail list view

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Fixes #11278    
On the Period Countries card, selecting `View more` will now show a full list of Countries. The rows should look like they do on the Period Countries card. There is no row selection action.
**NOTE:** Depending on the number of countries, it could take several seconds for the view to load. There is an outstanding issue to show a loading view (#11166).
To test:
- On a site with more than 6 countries, go to Period > Countries > View more.

[Stats Refresh] Period Countries: add detail list view

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Fixes #11280     
On the Period Published card, selecting `View more` will now show a full list of Published. The rows should look like they do on the Period Published card. Selecting a row will open a web view.
**NOTES:** 
- Currently, there is no API call to get the full list of Published. So for now, this displays the data fetched from the "top" Published API call used for the Period card. (cc @jklausa issue #11283 )
- Depending on the number of Published, it could take several seconds for the view to load. There is an outstanding issue to show a loading view (#11166).
To test:
- On a site with more than 6 Published, go to Period > Published > View more.
- Verify selecting a row displays a web view.

[Stats Refresh] Period Published: add detail list view

---

WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
WordPress/Classes/ViewRelated/Stats/Charts/StatsChartLegendView.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #11266 and in doing so, updates the legend to more closely respect the specification in Zeplin.
To test:
- For a site, navigate to Stats, and select a given period (i.e., Days, Weeks, Months, Years). The image should look like the exhibits below.
- Please note that at the moment, the chart is the same regardless of period or dimension (Views, Visitors, Likes, Comments).
_iPhone SE (Portrait)_
_iPhone SE (Landscape)_

Transitioned to use custom chart legend

---

RELEASE-NOTES.txt
WordPress/WordPressShareExtension/ShareExtractor.swift

Fixes #11222
Fixes #11270 
This fixes text import from other applications by treating text from shared files differently than from text shared directly (which will still be blockquoted). It also fixes the issue of shared text (both kinds) being treated like HTML, opening the possibility of nefarious HTML making it into the user's site.
To test:
- Share text from bear using the export UI. See GIF. (cc: @trix180)
- Share text from Ulysses using text UI
- In both cases, ensure that the text appears in the body of the post without block quote
- Also trying sharing from other text editors you may have. Some may only share the text directly, not a file, and the blockquote will still appear
- Also, try sharing HTML source in another editor. Now that HTML should appear with escaped HTML entities. …

Share Extension: Improve text import from other apps

---

Scripts/fastlane/Fastfile

This PR fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/11169 by adding the upload of the symbols to Fabric.
It will probably make sense to remove the upload of the symbols to HockeyApp in the future, as they have little usage there. Let's tackle it as a part of the upcoming migration.
To test:
1. Update the internal version of the app.
2. run `bundle exec fastlane build_and_upload_internal` (you need to remove some checks or to commit the previous changes in order to make this work).
3. Verify that the previous command finishes without errors.
4. Verity that the symbols have been uploaded.
5. Delete the app from Hockey and the dSYM from Fabric.
I tested it while building the latest beta.

Update Fastlane to upload dSYMs to Fabric for the internal version

---

WordPress/Classes/Stores/NoticeStore.swift
WordPress/Classes/System/WordPressAppDelegate.h
WordPress/Classes/System/WordPressAppDelegate.m
WordPress/Classes/Utility/Queue.swift
WordPress/Classes/Utility/ReachabilityUtils+OnlineActions.swift
WordPress/Classes/Utility/WPError+Swift.swift
WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/Classes/Stores/NoticeStoreTests.swift
WordPress/WordPressTest/QueueTests.swift
WordPressFlux/WordPressFlux/Sources/Store.swift

Closes #11175.
This changes the `Notice` dismissal architecture to more closely follow Flux. 
To show a `Notice`, we would do this:
```swift
ActionDispatcher.dispatch(NoticeAction.post(notice))
```
The process flow looks like this:
To dismiss the `Notice`, we currently need the `NoticePresenter`:
```swift
let noticePresenter = findNoticePresenterFromAppDelegate()
noticePresenter?.dismissCurrentNotice()
```
And the flow looks like this:
As you can see, it doesn't follow the same flow when we show a `Notice`. 
This PR changes this so that to dismiss a `Notice`, we would only need the `ActionDispatcher`:
```swift
ActionDispatcher.dispatch(NoticeAction.dismiss)
```
And the flow looks the same as when showing a `Notice`:
Testing for regression is recommended. Here are some places we use …

Dismiss Notices using ActionDispatcher

---

RELEASE-NOTES.txt
WordPress/Classes/Services/DomainsService.swift

Fixes #10530.
During a domains search, if any of the domain's subdomains exactly matches the user's query, filter it to the top of the list.
**To test:**
* Build and run, log in, and tap + on the site list view.
* Tap Create a new Wordpress.com Site
* Chose a type of site and enter a category
* Enter a title that might produce an exact available domain match – perhaps include some numbers. Tap Next.
* On the domains search screen, the initial results should populate. Hopefully there should be an exact match for your search, and it should be at the top of the list.
* Enter a new domain search query, again something that matches an available domain. Check that the exact match shows at the top of the list.
* Check that existing tests pass.

Domains Search: Filter an exact match to the top of the list

---

WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.xib
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift

Fixes #11284
This updates Insights Latest Post Summary to match the new design:
- Move “views” to top and use full number
- Move “likes” and “comments” to bottom as table rows
- The Views number now abbreviates after 99,999.
To test:
---
- On a site that has a post with views/comments/likes, go to Insights > Latest Post Summary.
- Verify the view is now:
---
- On a site that has a post with no views/comments/likes, go to Insights > Latest Post Summary.
- Verify the view is still: (the point being there should be no change here)
---
- On a site with a more than 99,999 views, go to Insights > Latest Post Summary.
- Verify the number is abbreviated.
- Note: to test this, in `LatestPostSummaryCell:configure`, you can modify the value used in this line:
`viewsDataLabel.text = …

[Stats Refresh] Insights Latest Post Summary: update design

---

WordPress/Classes/Models/AllTimeStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/AnnualAndMostPopularTimeStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/LastPostStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/StatsRecord+CoreDataClass.swift
WordPress/Classes/Models/StatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/StreakInsightStatsRecordValue+CoreDataClass.swift
WordPress/Classes/Models/TodayStatsRecordValue+CoreDataClass.swift
WordPress/WordPressTest/AllTimeStatsRecordValueTests.swift
WordPress/WordPressTest/AnnualAndMostPopularTimeStatsRecordValueTests.swift
WordPress/WordPressTest/FollowersStatsRecordValueTests.swift
WordPress/WordPressTest/LastPostStatsRecordValueTests.swift
WordPress/WordPressTest/PublicizeConectionStatsRecordValueTests.swift
WordPress/WordPressTest/StatsRecordTests.swift
WordPress/WordPressTest/StatsTestCase.swift
WordPress/WordPressTest/StreakStatsRecordValueTests.swift
WordPress/WordPressTest/TagsCategoriesStatsRecordValueTests.swift
WordPress/WordPressTest/TodayStatsTests.swift

This fixes a temporary workaround that was in place in #11295 and fixes the uniquing logic for Core Data validation for Stats objects — bringing back the commented-out tests from the previous PR.
To test:
Verify that the tests pass.

Bring back uniquing of StatsRecordValues

---

Podfile
Podfile.lock

Fixes #11302 
This PR address the issue that post categories weren't being saved.
The work on the main app just updates the reference to a new version of WordPressKit that provides the fix. You can see the related PR here: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/126
Note: After the review I will update the WordPressKit hash to use a proper version. 
To test:
1. Start a new post and enter a title and text.
2. Open Post Settings.
3. Open Categories.
4. Select a category other than the default.
5. Go back to Post Settings and confirm you see your selected category.
6. Go back to the editor and save or publish the post.
7. Reopen the post and view the Post Settings.
8. Check that correct category is set.

Fix post categories not saved bug

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift

Fixes #11292 
This restores the button functionality in Reader Followed Sites and My Likes. It also restores hiding/showing the No Results image when the device is rotated.
To test:
---
- On a site that is not following any sites, go to Reader > Followed Sites. 
- Tap the `Manage Sites` button. 
- Verify the Manage view is displayed.
---
- On a site with no liked posts, go to Reader > My Likes. 
- Tap the `Go to Following` button. 
- Verify the Followed Sites view is displayed.
---
- On an iPhone, with a No Results view displayed, rotate the device. 
- Verify the image hides in landscape and shows in portrait.

Reader: restore empty state button functionality

---

WordPress/Classes/Utility/ReachabilityUtils+OnlineActions.swift
WordPress/Classes/Utility/ReachabilityUtils.m
WordPress/Classes/ViewRelated/Comments/CommentsViewController+NetworkAware.swift
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
WordPress/Classes/ViewRelated/Post/PostListViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
WordPress/Classes/ViewRelated/System/NetworkAware.swift

Closes #11034. 
This changes the Notices applied in #11171 to use messages that are specific to where they are shown.  The areas affected are:
- Reader
- Site → Comments
- Site → Blog Posts 
- Site → Pages 
- Notifications (pull-to-refresh only)
|  ![2019-03-20 09 33 06](https://user-images.githubusercontent.com/198826/54697680-96431d80-4af3-11e9-933e-0657debdd3d9.png)      |  ![2019-03-20 09 25 19](https://user-images.githubusercontent.com/198826/54697703-a1964900-4af3-11e9-890c-24c148693625.png)    |
|  ![2019-03-20 09 32 49](https://user-images.githubusercontent.com/198826/54698432-ef5f8100-4af4-11e9-88b9-021c1a352ad1.png)      |   ![2019-03-20 09 43 53](https://user-images.githubusercontent.com/198826/54698458-f5556200-4af4-11e9-9a38-afad826a4f98.p …

Use page-specific Offline Notice messages

---

Podfile
Podfile.lock
RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
WordPress/Classes/ViewRelated/Post/PostEditor.swift

Fixes #11246 
This PR implements the necessary calls to allow Gutenberg to start a post with images pre-inserted or with the media picker started.
To test:
Scenario 1:
- Make sure you have the Gutenberg editor activated
- Open the Media Library of a site
- Add one or more media items using the + button
- When the uploads are finished and a notification informs you of that, press on the option "Write Post".
- Check that Gutenberg editor opens and the image are pre-inserted on the post.
Scenario 2:
- Go to the home screen on a device with force touch
- Force touch on the WordPress app icon
- Select the option New Photo Post
- Check that the Gutenberg editor is open and a media picker is presented.
- After the media is selected check if the media is added to the post and uploaded correctly. …

Start draft with image

---

Podfile
Podfile.lock

This PR updates mobile Gutenberg to v.1.1.1.
To test:
run "rake dependencies"
Stop metro if it is running
If WPiOS app still tries to pick JS files from metro remove the app from simulator/device and reinstall
Make sure gutenberg editor is running ok.
Quickly check out one of the new PRs delivered to Gutenberg Mobile repo, make sure it works as described in the PR.

Update to Gutenberg 1.1.1

---

Podfile
Podfile.lock

Merging Gutenberg 1.1.1 to master caused CocoaPods to break since the Podfile here pointed at master.
This cherry picks the change that fixed this on `develop` (https://github.com/wordpress-mobile/WordPress-iOS/commit/cbed6c40bed0e1bfc3f1de918cfb81d008512ea4).

Cherry pick Podfile update to fix CocoaPods failing.

---

WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift

Fixes #11310.
This fixes a bug in Site → Pages and Site → Posts where when there is no content and no internet connection, both the Notice and Empty View are shown at the same time.
|  ![2019-03-20 11 40 57 2019-03-20 11_53_45](https://user-images.githubusercontent.com/198826/54786194-dc7ca780-4bed-11e9-8921-a1dc02e4edb5.gif) |  ![2019-03-20 11 44 04 2019-03-20 11_51_44](https://user-images.githubusercontent.com/198826/54786203-e1415b80-4bed-11e9-8232-ec678cedf410.gif) |
Before starting, make sure that you have not loaded anything in Site → Pages and Site → Posts. You can use an empty site or delete the app from the device.
1. Turn off the internet connection on the device.
2. Navigate to Site → Pages and Site → Posts.
You should not see the Notice …

Fix Notice and Empty View shown at the same time in Site → Pages/Posts

---

WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift

This fixes the bug where Notices animate on top of the tab bar. Also included is a fix for the Notice's y-position when the device is rotated. I had to fix this one because with the first fix, the Notice gets cut off from the screen and the bug becomes more obvious. 
| ![2019-03-21 16 04 43 2019-03-21 16_28_16](https://user-images.githubusercontent.com/198826/54789001-ba3b5780-4bf6-11e9-85be-7effec6599b8.gif) |![2019-03-21 16 03 41 2019-03-21 16_27_06](https://user-images.githubusercontent.com/198826/54789014-c3c4bf80-4bf6-11e9-9f37-2ac275de5d00.gif) |
This fix was done by adding a mask (`MaskView`) on the main `view`:
The blue background is where the Notice will only be visible. 
The rotation bug is shown below. Notice that in _Before_, after …

Fix Notice animating over the tab bar

---

WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressTableViewProvider.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift

Fixes #11331 
Fixes #11332 
The "Suggestions" title label is now only shown for the implicit suggestions (the suggestions we provide before the user types anything).
The implicit suggestions are now shown again if the domain text field is emptied.
1. Enter the site creation flow for a WP.com site.
2. In step 3, make sure that initially you can see the "Suggestions" title, and a list of implicit suggestions (based off the site's title).
3. Type something and make sure "Suggestions" goes away.
4. Clean the field and make sure the initial state is shown again.

Site Creation: Improves the Domain Suggestion UI/UX

---

Podfile
Podfile.lock

Update WordPressKit to 3.2.0

---

WordPress/Classes/ViewRelated/Stats/Charts/Charts+AxisFormatters.swift
WordPress/Classes/ViewRelated/Stats/Charts/Charts+Styling.swift
WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
WordPress/Classes/ViewRelated/Stats/Charts/Stubs/PeriodDataStub.swift
WordPress/Classes/ViewRelated/Stats/Charts/Stubs/period_data.json
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Fixes #11064.
To test:
- For a site, navigate to Stats, and select a given period. Then select a period dimension (Views, Visitors, Likes, Comments.
- Please note that at the moment, the chart is the same regardless of period (i.e., Days, Weeks, Months, Years).
- Please also note that the fabricated numbers do not match the magnitude of the values in the stubbed JSON data.

Add support for updating chart in response to period dimension selection

---

WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift

Fixes #11325. 
The bug seems to consistently happen when you launch the app, show a `Notice`, and then rotate the device.
| Starting Orientation | After Rotating |
|      <img width="1455" alt="develop-before-rotate" src="https://user-images.githubusercontent.com/198826/54955986-83c24d00-4f14-11e9-9f43-967e0d746db9.png"> | <img width="1087" alt="develop-after-rotate" src="https://user-images.githubusercontent.com/198826/54955985-83c24d00-4f14-11e9-8021-cec34f7825a1.png"> |
Based on my tests, the `UntouchableViewController.view` never gets automatically resized when the device is rotated. The first orientation that the app is launched in will determine the size of the `view`.
This only happens on iPad devices. For iPhone, the `view` seems to be rotated correctly. 
Based …

Fix Notices showing anywhere but the bottom on iPad devices

---

Podfile
Podfile.lock

This PR updates gutenberg to `v1.1.2`.
The change implemented can be seen here:
https://github.com/wordpress-mobile/gutenberg-mobile/pull/790
To test:
- Run `rake dependencies`.
- Run the project.
- Add a breakpoint on: `func gutenbergDidMount(hasUnsupportedBlocks: Bool)`.
- Open a post on gutenberg that does NOT have unsupported blocks.
- Check that `hasUnsupportedBlocks == false`.
- Open a post on gutenberg that has unsupported blocks.
- Check that `hasUnsupportedBlocks == true`.
cc @loremattei

Update gutenberg to v1.1.2

---

WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.xib
WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift

Fixes #n/a
This makes the date bar on the Period view actually functional.
- Back button goes back by one period.
- Forward button goes forward by one period.
- Forward button is disabled if the next period is beyond the current date's period.
- Back button is disabled if the next period is beyond the number of periods shown on the Overview chart, which is 13. (i.e. you get 13 Days, 13 Weeks, etc.)
- The data in the Period cards is updated according to the newly selected date. (except for the Overview card since that's still bogus data)
**Note**: if you change the dates quickly, you'll probably notice a slew of `Stats Period Overview refresh triggered while one was in progress` log messages. I've created #11353 to address this.
To test:
- Go to Stats > Period.
- Change the date back and …

[Stats Refresh] Add functionality to date bar

---

WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.swift
WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.xib
WordPress/Classes/ViewRelated/Site Creation/SiteInfo/SiteInformationWizardContent.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.xib

Fixes #11333 
This also changes the layout of `InlineEditableNameValueCellDelegate` so that we no longer need to configure the insets.
1. In the posts list press + and add a new WP.com site.
2. Select the type of site you want.
3. Make sure that the separator shown in step 2 is aligned with the cell titles.
1. Go to source file `PluginViewModel.swift`, line 186
2. Replace that line with `if true {`
3. Go to source file `Blog.m` method `supportsPluginManagement`
4. Make sure the method exits immediately with `return true;`
5. Launch the app and go to the mobile dashboard for any site
6. Tap on "Plugins"
7. Try to install any plugin
8. When the alert comes up telling you that you need a custom domain, tap on "Register Domain".
9. Make sure all cells look right.

Site Creation: Fixes separator alignment in the basic information step.

---

WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.xib

Fixes #11335 
This PR resolves an issue that was causing text to be laid out behind the selected cell's checkmark icon, in the domains suggestion screen in our Site Creation flow.
1. Go to the list of sites.
2. Tap the + icon and create a new wp.com site.
3. In the domain suggestion step, type a really long text.
4. Select one of the suggestions and make sure text is no longer laid out behind the checkmark icon.

Site Creation: Domain suggestions are no longer laid out behind the checkmark.

---

Podfile
Podfile.lock
WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

This switches StatsPeriodStore to the new `StatsServiceRemoteV2` based API, also updating the appropriate ViewModels.
I found two more changes (grr.....) I'll need to make to the data model when working on this — 
* `Videos` endpoint doesn't return a media `ID`, just a URL
* we need to move the country-flag icons from WPStatsiOS module to WPiOS. This was outside of scope for this PR so I decided to leave it broken for now.
To test:
* Go to Stats
* Look at Period-type data
* Verify everything still works! (modulo the two broken things above)

[Stats Refresh] StatsPeriodStore: make use of the new API

---

WordPress/Classes/Stores/StatsInsightsStore.swift
WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/Stores/StoreContainer.swift
WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Alright, last of the major ones!
This teaches `StatsPeriodStore` about Core Data objects. I snuck in few other fixes in here too — some fixes for memory leaks  and a fix for persistence of Insights.
To test:
Pre-requisite: Comment out lines 114-120 in `StatsViewController.m` to disable current offline-mode handling.
1. Launch the app.
1. Tap around Stats, jump across different tabs etc
1. Background the app
1. Kill the app
1. Kill your network connection
1. Open the app again
1. Verify that data for Stats shows up!

TimeInterval persistence

---

Podfile
Podfile.lock

Fixes #
To test:
- Create a post on the web using gutenberg
- Add a shortcode block to it.
- Use the following has the content of the block: `[video src="https://videos.files.wordpress.com/kUJmAcSf/bbb_sunflower_1080p_30fps_normal.mp4" ]`
- Add another shortcode block and use this content: `[wpvideo kUJmAcSf ]`
- Save the post
- Open the post on the mobile device, using Aztec.
- Check that the videos are presented.

Fix video Shortcodes on Aztec.

---

WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift

Fixes #11370 
The right inset of `SearchTextField` was zero.  This PR fixes that inset to add some spacing.
1. Go to the list of sites.
2. Tap + and create a WP.com site.
3. In step 3 of the Site Creation flow, type a really long text.
4. Select one of the suggestions below, so that the input field is no longer first responder.
Make sure the right margin of the input field is not sticking to the right border of the screen, and has a 16pt margin.

Fixes the right inset in SearchTextField when not in edit mode.

---

WordPress/Info.plist

Fixes #8231
I simply turned off the status bar upon launch to prevent the logo from being squished. No amount of autolayout constraints fixed this for some reason. Common solution online is to disable the status bar on launch which it should be anyway.
To test:
Put a breakpoint in the App Delegate in didFinishLaunching and double check the simulator doesn't show the squished logo.
Make sure all the screens in the app don't look janky with the status bar turned off on launch. So far everything looks okay.

Turns off the status bar on launch to prevent W logo squish

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

Fixes the build error resulting from the merge of PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/746
Applies patch shared in: https://github.com/wordpress-mobile/gutenberg-mobile/pull/746#issuecomment-478389589
To test:
- run metro on gutenberg-mobile/develop
- run `rake dependencies`
- clean build folder
- run the app
Follow steps on: https://github.com/wordpress-mobile/gutenberg-mobile/pull/746

[Gutenberg]Integrate logging

---

WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift

Fixes #11391. 
This was caused by the changes in #11319. It does not happen on WPiOS 12.0.
It looks like after the camera is dismissed, the mask (`MaskView`) can be interacted with. As @SergioEstevao found, it is also put in front of the `NoticeView`. I did not expect this because the mask shouldn't be part of the view hierarchy.
Aside from the mask preventing interaction with the `NoticeView`, it also prevents users from interacting with the view _behind_ it. This means that when Notices are shown, users cannot scroll around the Media Library or press any button. 
I opted to disable the user interaction for the `MaskView` when it is initialized. In retrospect, I wonder if I could have used a `CALayer` when I worked on #11319. 
Copied from #11391: 
1. Using a real device
2. Go to the …

Fix Notices not being actionable after taking a photo

---

WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.xib

Fixes #11369 
The current behavior is the default behavior of iOS. The cell's `contentView` will always be resized when the checkmark is shown. 
This PR adds custom width calculation for the label's trailing constraint so that it will add or subtract the width of the checkmark when the checkmark is hidden or shown. 
| |  |
| ![image](https://user-images.githubusercontent.com/198826/55357295-e7ef8e80-5489-11e9-8ff8-8897445d3d57.gif) |  ![2019-04-01 14-32-02 2019-04-01 14_32_59](https://user-images.githubusercontent.com/198826/55357827-3baea780-548b-11e9-9281-76601eb75d8b.gif)  |
My problem with this solution is the hardcoded `39` value for the checkmark width. This was manually taken from Xcode's UI debugger. I could not find a way to preemptively acquire this value …

Site Creation: Always add a space for the checkmark when selecting domains

---

WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.swift
WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.xib

Fixes #11356 
Copied from #11356: 
1. Go to the list of sites.
2. Tap + and create a new WP.com site.
3. As you move forward in the process of creating a new site, try tapping in the title of cells that have an editable field.

Site Creation: Make label taps focus their corresponding text fields

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift

Here we go again.
After long discussions I've decided to tackle this in steps. This is the first step and it includes drafts only. It also uses an existing end point for uploading the post with API version 1.2.
If the post is a draft we are uploading it before the preview so it shows the remote version of the preview. 
This PR DOES NOT include a solution for a published post which currently shows the remote version on no changes and the local version when there are local changes.
A following PR will cover a published post.
Fixes #9286 
To test:
1. Create a new draft or edit an existing one
2. Preview the draft
3. See the remote preview

Uploading draft and displaying remote preview

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/730
Relate GB-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/810
To test:
- Create a new post using GB-mobile
- Open the Photos app
- Select one or more images
- Tap on the copy button
- Go back to the post
- Select a text block, and tap paste
- See that the images are inserted in the post has image blocks
- Check that the upload happens correctly.

Implement copy paste of image in GB mobile

---

Podfile
Podfile.lock
RELEASE-NOTES.txt

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/208
Related GB-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/704
To test:
- Create a new post using GB
- Add a list block to it
- See if it shows correctly
- Add list items
- Change type of list (ordered, unordered)
- Split list items in the middle
- Split block by inserting two empty list items 

Updates GB version to support list blocks

---

WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.xib

Fixes #11396.
After some tests, I found that this started happening in 4e6049a. That is a legitimate fix for the checkbox hovering over the labels. However it seems to be causing some issues on the self-sizing `AddressCell`. The issue only happens on the first table reload. This reverts the change on that.
To fix the checkbox hovering over the labels, I reverted the change in 6c84f94 and opted to increase the trailing constraint constant of the title label to accommodate the checkbox. This now works because the trailing constraint is tied to the Safe Area instead of the cell's Content View.
|![2019-04-04 06 24 53 2019-04-04 06_32_47](https://user-images.githubusercontent.com/198826/55555908-8b67bb80-56a3-11e9-9d2d-8cda699466e3.gif) |  ![2019-04-04 06 …

SiteCreation: Fix AddressCell height on first load

---

Podfile
Podfile.lock

This PR updates the gutenberg-mobile reference to point to the latest release, v1.2.0. There are no other WordPress iOS changes.
The reference is currently pointing to the `release/1.2` branch on https://github.com/wordpress-mobile/gutenberg-mobile. Relevant PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/833.
When that gets merged to gutenberg-mobile master, I'll update the ref here to point to the v1.2.0 tag on gutenberg-mobile master.
To test:

Point to latest gutenberg-mobile release v1.2.0

---

Podfile
Podfile.lock
WordPress/WordPress.xcodeproj/project.pbxproj

Updating WordPressKit, WordPressAuthenticator, WordPressShared and Automattic-Tracks-iOS to release versions.

Update pods to release versions

---

WordPress/Classes/ViewRelated/Plugins/PluginListViewController.swift

Fixes #11386
To test:
I couldn't make the crash reproduce, so this is a best-effort guess for a fix/workaround. Hopefully we'll see less crashers for this after this is released!

Add defensive check for crash in plugins

---

WordPress/Classes/ViewRelated/Jetpack/Install/Data/JetpackRemoteInstallViewModel.swift
WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.xib

Refs. #10277 
This PR remove the warnings used to mark some functions and vars used to manually test #11405 .
The warning had this message: `This is for manual testing purpose only. Remove after this PR is merged.`
**To test:**
- Build the app to check if all the 4 warnings have been deleted.

[Jetpack Remote Install] Remove warnings and unnecessary code

---

Podfile.lock
WordPress/Classes/Utility/ReachabilityUtils+OnlineActions.swift
WordPress/Classes/Utility/WPWebViewController.m
WordPress/Classes/Utility/WebKitViewController.swift

This is only for os 11.0 as we are showing WebKitViewController for os > 11.0 but for lesser versions we show WPWebViewController that doesn't seem to be able to adopt the new notice (as it is a struct WPWebViewController is obj-c)
Fixes #11313 
To test:
1. Be offline
2. Go to "View Site"
3. See snack bar (if os > 11.0)
* Unfortunately my device has updated to 12.2 and I am currently unable to test this on the device (still no support for xcode 10.2) so this is only tested in simulator  

Update WebKitViewController to show notice When offline instead of showing alert

---

Podfile
Podfile.lock
WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/11444
It relies on the changes in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/78. ~~That should be merged and released before this PR.~~
To test:
1. Open the app logged out.
2. Start the email signup flow.
3. Enter a new email address and confirm the signup via the magic link.
4. On the signup epilogue screen, tap the username field to try to change your username.
5. It doesn't crash.

Fix loading WordPressAuthenticator xibs

---

WordPress/Classes/Utility/ContextManager.m

Adding this in hopes of getting more useful tracebacks to fix #10729 — as suggested by @astralbodies.
Can I trouble you for a quick review @astralbodies?

Add more verbose logging to Core Data crashes

---

Scripts/fastlane/Deliverfile

**To Test:**
If you already have an Fastlane environment configuration file, just run `bundle exec fastlane deliver--skip_binary_upload --skip_screenshots`. 
If you have `FASTLANE_USER` / `DELIVER_USER` and `FASTLANE_ITC_TEAM_ID` defined in there, the first prompt you should receive is to verify the HTML file. That's how you'll know it's working.

Use global env variables in fastlane deliver

---

WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift
WordPress/Classes/ViewRelated/System/WPTabBarController.m
WordPress/WordPress.xcodeproj/project.pbxproj

Closes #11395 
After some investigation, I found that the `my_site_tab_accessed` event is counted:
1. On app start (`WPTabBarController.init`)
2. On `WPTabBarController.decodeRestorableStateWithCoder`
3. When the user selects the _My Sites_ tab
4. On first launch of the app (user is not logged in)
5. After log out and moving the app to the background and then foreground again. 
The first and second causes the event to be counted *twice*.
Related: paCBwp-54-p2.
This adds a more elaborate mechanism for tracking the event. Most of them are encapsulated in the new file, `WPTabBarController+Swift.swift`. The event is now counted on these scenarios only:
- Logged in: The app has been placed in the foreground
- Logged in: The app was just launched and we restored the previously selected tab
- …

Fix my_site_tab_accessed tracking

---

WordPress/Classes/Stores/StatsInsightsStore.swift
WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift

Fixes #11359.
After banging my head against this for a better part of three days, and writing 200+ lines of code to do this in a clever way, in a fit of frustration I decided to try the dumbest possible thing... and it worked. I swear to god, trying to be too clever will be the end of me...
Both `Insight`/`Period` `Store`s now no longer run network operations when you ask them for the most generic datasets: `PeriodQuery.periods(date:_, period:  _)` in case of `PeriodStore` and `InsightQuery.insights` in case of `InsightQuery`. 
Now, asking for those only fetches data from the Core Data store and in order to trigger the network requests for these you need to manually dispatch  a `PeriodAction.refreshPeriodOverviewData(date: _, period: _)` or `InsightAction.refreshInsights()`, respectively. …

[Stats] Don't fetch insights/period data by default, only on manual refreshes

---

WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift

Fixes #11309 
To test:
1. Be offline
2. switch to site that has custom themes
3. make sure the labels  are not being displayed if the "no results view is presented"

Hiding header if there are no item in that section.

---

Podfile.lock
WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift

Fixes #11312 
Before:
After:
To test:
1. Be offline
2. Go to sharing
3. Go to manage
4. Don't change anything
5. Go back
6. See that the alert is not displayed
1. Be online
2. Go to sharing
3. Go to manage 
4. Make changes 
5. Make sure they are saved

Only showing "can't save changes" alert if changes were actually made.

---

Podfile
Podfile.lock
WordPress/Classes/Stores/StatsInsightsStore.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Fixes #11238 and #11182
This updates the StatsInsightStore to use the new API endpoints for fetching data for detail views of Followers/Tags and Categories/Comments.
To test:
* Build this branch
* Go to Stats
* Go to detail view for Followers for a highly-followed site
* Verify that more than 10 datapoints appears 
* Go back
* Go to detail view for Tags And Categories
* Verify that up to 100 datapoints appear

Make Stats Followers/Tags and Categories detail views use the new API.

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Blog/SharingViewController.m

Fixes #11311 
[this PR should be merged before](https://github.com/wordpress-mobile/WordPress-iOS/issues/11312)
To test:
1. Be offline
2. go to sharing 
3. see snack bar.

Sharing screen to show snack bar instead of alert when offline

---

WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift

Fixes #11474
This fixes a bug where the "Last Post Insight" would grow every time it's displayed on screen. 
To test:
Go to Stats Insights
Scroll around a bit making the "Last Post Insight" repeatedly appear on/off screen
Verify that the number of the rows stays constant

[Stats Refresh] Fix a reuse bug in Last Post Insight

---

WordPress/Classes/ViewRelated/Stats/Charts/Charts+Support.swift
WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
WordPress/Classes/ViewRelated/Stats/Charts/StatsChartLegendView.swift
WordPress/Classes/ViewRelated/Stats/Charts/Stubs/PeriodDataStub.swift
WordPress/Classes/ViewRelated/Stats/Charts/Stubs/PostSummaryDataStub.swift

Fixes #11065.
To test:
- Whether manually with VoiceOver, or via the Xcode Accessibility Inspector, select the bar chart in each of the following: Insights / Latest Post, Insights / Selected Post, Period (DWMY) / Views | Visitors | Likes | Comments.
- "Drill down" further on the chart and confirm that each bar is read out with the date (x-axis), followed by the value backing the bar (e.g., visitor count).

Improved accessibility of bar chart views in Stats

---

RELEASE-NOTES.txt
WordPress/Classes/Stores/ActivityStore.swift

Fixes #9818
I'm clearing up some old issues that were assigned to me, and this is a quick fix :)
This fixes a problem where Activity Log would have incorrectly translated labels coming from backend.
| old | new |
| --- | ---- |
| ![Simulator Screen Shot - iPhone Xs Max - 2019-04-17 at 01 10 10](https://user-images.githubusercontent.com/1594081/56249843-92cc9300-60ad-11e9-915d-530499dda391.png) | ![Simulator Screen Shot - iPhone Xs Max - 2019-04-17 at 01 08 21](https://user-images.githubusercontent.com/1594081/56249849-99f3a100-60ad-11e9-9832-1d9a31050d84.png)|
To test:
Change your device/simulator language to something non-english
Go to Activity Log
Verify that the text is localized properly

Send proper locale key to Activity remotes

---

WordPress/Classes/ViewRelated/Post/PostListViewController.swift

"Fixes" (not really though) #11425
This is the smallest possible thing to do in #11425, while I'm still investigating/working on actually making sure the post will get deleted offline.
For now we just swap the modal pop-up about internet being offline, for the new Notice.
To test:
Go to Post list
Go offline
Try to delete a post
Verify that you see a neat new Notice, and not a modal letting you know about the device being offline

Remove blocking interaction when trying to delete a post when offline

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift

Fixes #11205 
This uses real summary data for the Period Overview card. To note, the chart still uses stub data.
**NOTE**: As noted on https://github.com/wordpress-mobile/WordPress-iOS/pull/11342#issuecomment-477330842, fetching summary data can take a _really_ long time, especially with longer Periods. Patience is a virtue.
To test:
- Go to Stats > Period.
- Verify the numbers populate real data.
- Verify the data updates when different periods are selected (D, W, M, Y).
- Verify the data updates when different dates are selected via the date bar.

[Stats Refresh] Period Overview card: populate with real data

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift

Fixes #11353 
When a user performs any of these actions, the currently running queries will be cancelled and new queries run.
- Select another period.
- Select another date.
- Pull to refresh.
(Basically, any action that triggers `SiteStatsPeriodTableViewController.refreshData`.)
To test:
- Go to Stats > Period.
- Perform any of the above actions in quick succession.
- If any queries were still running, you'll see messages like this in the console:
`Error fetching posts: Optional("cancelled")`

[Stats Refresh] Period stats: restart queries when period or date changes

---

WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.xib
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Fixes #11344 
When on Post Stats, tapping the post title will now open a web view for that post.
To test:
- Access Post Stats via:
- Insights > Latest Post Summary > View more
- Period > Posts and Pages > row selection
- Period > Posts and Pages > View more > row selection
- Verify tapping in the post title area opens a web view for that post.

[Stats Refresh] Post Stats: show web view when post title tapped

---

Podfile
Podfile.lock

This PR updates the gutenberg-mobile reference to point to the latest release, v1.3.0. It also updates Aztec to 1.6.0.
The reference is currently pointing to the `release/1.3.0` branch on https://github.com/wordpress-mobile/gutenberg-mobile. Relevant PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/895.
When that gets merged to gutenberg-mobile master, I'll update the ref here to point to the v1.3.0 tag on gutenberg-mobile master.
To test:

Point to latest gutenberg-mobile release v1.3.0

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift

Fixes #11509 - Part 1
To test:
- Go to Reader on a clean install and check that the News Card is displayed.
- Go to Reader, and then to a specific feed and check that the header is properly configured.
- In general check that Reader headers look good.

Remove newsCard FeatureFlag

---

WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift

Fixes #11242 
To test:
First replicate the issue following the instructions in the original ticket.
Then checkout this branch, and check the following scenarios:
Reset UserDefaults and check that when you first publish a post you get the AsyncPromo alert:
@rachelmcr do the testing steps sound good?

Only display confirmation alert for unpublished posts

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift

Fixes #11509 - Part 7
To test:
- On a self-hosted site, trigger a Jetpack install and check that everything works as expected.

Remove jetpackRemoteInstallation FeatureFlag

---

WordPress/Classes/Utility/ZendeskUtils.swift

Fixes #11477 
This updates the Zendesk API methods that were deprecated in v2.3. Visibly, there should be no changes, so these tests are just to make sure the new methods work as expected.
To test:
---
- Build the app. 
- Verify there are no Zendesk deprecation warnings.
---
The updated methods center around showing/hiding the `Contact Us` option from these views:
1. WordPress Help Center > right nav bar button.
2. Help Center search > no results > link on no results view.
3. Help Center > select an Article > right nav bar button.
If your `Contact Email` is set, you _will_ see these options. If your `Contact Email` is not set, you _will not_ see these options.
So, to test:
- Go to Me > Help & Support.
- With Contact Email set, go to the 3 views and verify the Contact options appear.
- …

Zendesk: update API methods

---

WordPress/Classes/Utility/InteractiveNotificationsManager.swift

Fix #11293 
The Analytics call is dispatched to the main thread avoiding the app being stuck while the dialog is dismissed.
• Fully uninstall the app (just delete it out of the simulator).
• Reinstall the app and log in.
• When prompted to allow notifications, choose to allow them.
• The App should work normally and the Fancy Alert should be dismissed quickly.

[FIX] Application stuck after Notifications dialog block is called

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift

Fixes #11509 - Part 2
To test:
Check that you can add images from Giphy in:

Remove giphy FeatureFlag

---

WordPress/Classes/ViewRelated/Ratings/AppFeedbackPromptView.swift

Fixes #11510 
Removing centering of the label, as NSLayoutConstraint does, to resolve this issue.
To test:
1. Run the app on develop and see the issue in the log
2. checkout this branch and run the app. See that the issue doesn't appear in log 
I tested this in English and Hebrew with big and small fonts.

Fixing layout issue in AppFeedbackPromptView

---

WordPress/Classes/ViewRelated/Jetpack/Install/View/State/JetpackRemoteInstallState.swift

Fixes #11525 
This PR fixes the copy on the JRI success screen 
• Add a self-hosted site with no Jetpack installed
• Open Stats from your site dashboard
• Click on Install Jetpack
• Complete all the steps to install Jetpack

[Jetpack Remote Install] New copy for Jetpack installation success

---

WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyContentView.swift
WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleHeader.swift
WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift
WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsCell.swift
WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsWizardContent.swift

Fixes #11480 by applying the following changes:
- Removed the `accessibilityTraits` designation that was preventing navigation of the screen in question.
- Tidied up a few other accessibility considerations elsewhere in the site creation flow.
- Improved the accessibility of the _Add_ button that initiates this flow. Previously it only read "Button". Now it leverages the system description, which is (a) accessible; and (b) properly localized.
To test:
1. From _My Sites_ (i.e., `BlogListViewController`), enable VoiceOver and initiate the Site Creation flow by selecting _Add_ : _Create WordPress.com site_.
1. Observe that _Create Site_ presented subsequently (i.e., `SiteSegmentsWizardContent`) can now be navigated successfully.
1. All other screens in the flow are (and were) still navigable …

Improved accessibility experience with the site creation flow

---

WordPress/Classes/ViewRelated/System/WPTabBarController.m

[Warning] Splitview controller is expected to have a view controller at index 0 before it's used!
Fixed by setting the primary view controller before setting up the width and other parameters.
To test:
1. Run the app on develop see the warning in the logs. 
2. Checkout this branch and run the app. See that the warning is gone.

Fixing SplitViewController warning:

---

WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard

Fixing the below mentioned layout issues by setting the leading and trailing constraints priorities to 999 so there would be no ambiguity:
To test:
1. Run the app on develop.
2. put a break point on NotificationsViewController line 113 (setupFilterBar())
3. notice that once you over step that line there are 4 layout issues (search for  "Unable to simultaneously satisfy constraints")
4. checkout this branch
5. repeat steps 2-3 
6. see that there are no layout issues. 
Layout issues in log
```2019-04-23 18:51:14.557428-0700 WordPress[56492:2956353] [LayoutConstraints] Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want.
Try this:
(1) look at each constraint and try to figure out which you don't expect;
(2) find …
```

Fix layout issues:

---

WordPress/Classes/Services/SiteAssembly.swift
WordPress/WordPressTest/SiteCreation/SiteAssemblyServiceTests.swift

Hi @stevebaranski! I'm hoping to get your feedback on this. 
The two `testSiteAssemblyService_StatusPostRequest_*` are being reported as the slowest tests in CI. I found that there's a deliberate delay in `MockSiteAssemblyService.createSite()` when it is executed. Is there a reason for this long delay? I checked #10609 but couldn't find any discussion around that. Do you think what I proposed here, 50 ms, is good enough for the test? 
Run `SiteAssemblyServiceTests` and check that it still passes.

Improve SiteAssemblyServiceTests execution time

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift

Fixes #11387 
According to the Fabric logs, this crash seems to happen when searching the Free Photo Library. 
```
51 | 1556091505912 | 🔵 Tracked: stock_media_accessed
52 | 1556091512547 | 🔵 Tracked: stock_media_searched
53 | 1556091514021 | 🔵 Tracked: stock_media_searched
54 | 1556091515163 | 🔵 Tracked: stock_media_searched
55 | 1556091515401 | 🔵 Tracked: stock_media_searched
56 | 1556091520549 | 🔵 Tracked: stock_media_searched
57 | 1556091525780 | 🔵 Tracked: stock_media_searched
```
I was not able to reproduce the crash, but this sort of crash typically happens when the NRV isn't actually visible so it fails when setting the constraints according to the `view`. So I added a check to ensure the NRV is visible before setting the constraints. 🤞 this fixes it.
To test:
- Access the Free …

Check NRV visibility before modifying constraints

---

WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift

Fixes #n/a
When accessing Insights, if the raw `mostPopularWeekday` was 0, subtracting 1 from it would go 💥  when used as the index for `standaloneWeekdaySymbols`. This adds a check for that, and sets the index accordingly.
To test:
- On a site where the most popular day is the start of the week, go to Stats > Insights.
- Verify it doesn't crash.

[Stats Refresh] Insights: fix getting most popular day

---

WordPress/WordPressShareExtension/ShareExtractor.swift

Fixes #11352 
This PR improves our Markdown import by turning the first line of an MD file into the title of the created post, if that first line is formatted as a heading. 
This substantially improves the experience of sharing items from Bear, which is launching in 12.3 so I have targeted that branch instead of `develop`.
To test:
- Build to device
- In Bear or Ulysses, create a new note with a headline as the first line (this is default in Bear)
- Share that note as either MD file or a TextBundle, open in WP
- Ensure that the first line of the file has become the post's title

Share Extension: use first line of Markdown as title

---

RELEASE-NOTES.txt
WordPress/Classes/Services/NotificationSyncMediator.swift
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift

This PR adds the ability to mark notifications as unread. Swipe left-to-right on a read notification to mark unread.
**To test:**
* Build and run and go to your Notifications
* Swipe left-to-right on a read notification and check it becomes unread
* Ensure you can still swipe on unread notifications to mark them read
* Open the same WPCom account in a browser and check the state is reflected there. Note that you may need to reload the page to see your changes on the app take effect.

Notifications: Mark as unread

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsSectionHeaderView.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m

Fixes #11383 
This PR fix a crash we have when an iPad user wants to remove the QuickStart section.
The UIAlertController was presented as _ UIAlertControllerStyleActionSheet_ without any popover property set.
**iPad**
• Add a new site and enable QuickStart
• Click on the `•••` ellipsis button to display the alert and remove the QuickStart Action
**iPhone**
Replicate the same steps on an iPhone to check everything works correctly as before. 

[Fix] UIAlertController popover properties

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
WordPress/Classes/ViewRelated/Post/PostEditor.swift

**Fixes** #8916 
**To test:**
1. Go to the posts list
2. Display the drafts list
3. Open the editor to create a new Post
4. Save it as a Draft from the top right three dots menu
5. Close the editor from the cross on the top left and to go back to the Draft list
6. The newly created post should be there
Also test: publishing a new post from the draft list, from the published list, scheduling posts, etc. Basically we need to run through all the publishing scenarios to make sure nothing is broken.
Notes:
There were two issues at play here:
- The `shouldRemovePostOnDismiss` property was being calculated during the ViewController initialization, which was incorrect because the post status could change later on.
- When closing the editor from the top left cross, and assumption that there were …

Draft missing from post list

---

WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift

Yesterday I was trying to view a post in the reader and the app was being shut down and spring board restarted on my iPhone X.  Investigating, I discovered the images in the post were quite large, over 10,000x8,000 pixels which was this being scaled up to over 30,000x25,000 (x3 for the iPhone X retina display).  Memory pressure from trying to process the image was apparently yielding an OOM error.
To resolve the issue, this patch limits the maximum size for an image shown in the reader. 
To test:
Use this post to test: paKIRI-1c-p2
- Confirm the bug on a device by viewing the post in the reader.  Liking the post then viewing your My Likes feed is an easy way.  You can also check the post in the simulator.  The app probably won't crash but the post will not scroll smoothly while the images …

Reader: Enforce max image size to prevent OOM errors due to gigantic images

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.swift
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.xib
WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift

Fixes #11492. 
The biggest change here was the addition of a new field on `QuickStartTour`. With that, I took the liberty to create hints in accordance with [our guidelines](https://github.com/wordpress-mobile/WordPress-iOS/wiki/VoiceOver-guideline), and set them appropriately.
To test:
- Checkout the branch, verify it builds, and that tests pass.
- Replicate the steps in the issue with VoiceOver, and verify that the desired accessibility behavior is observed.

Improved accessibility of the steps in a Quick Start tour

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift

Fixes #5884
In Account Settings > Primary Site, if the site has no name, the site URL will now be displayed.
To test:
---
- Remove the primary site Title. (site > Settings > Site Title)
- Go to Account Settings > Primary Site.
- Verify the URL is displayed.
---
- Give the primary site a Title.
- Go to Account Settings > Primary Site.
- Verify the Title is displayed.
---

Account Settings Primary Site: show URL if site has no name

---

WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.swift
WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.xib

Fixes #11493. 
The `QuickStartChecklistHeader` is somewhat dynamic, so I devoted a bit of attention to updating the `accessibilityLabel` & `accessibilityHint` in conjunction with the view state.
_NB: It's probably best to review this in conjunction with #11578, as the same screen (and release notes entry) are impacted._
To test:
- Checkout the branch, verify it builds, and that tests pass.
- Replicate the steps in the issue with VoiceOver, and verify that the desired accessibility behavior is observed.

Improved accessibility of Quick Start checklist header

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift

Ref #11189
This adds the 'Months and Years' card to the Post Stats view. 
- It shows total views for the last 6 years. 
- If there are more than 6 years, `View more` will be added.
- NOTE: `View more` doesn't do anything just yet. Coming soon.
- Expanding a year shows the total views for each month in the year.
To test:
- Tip: en.blog > Home Page has views for several years.
- Access Post Stats via:
- Insights > Latest Post Summary > View more
- Period > Posts and Pages > row selection
- Period > Posts and Pages > View more > row selection
- Verify 'Months and Years' appears, and each year expands to show all months in the year.

[Stats Refresh] Post Stats: add Months and Years

---

WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.xib

Fixes #11490, via the following changes:
- Applied "extract method" refactoring* to the existing configuration of cell accessory view & text content type.
- Although there is a low likelihood of cell reuse on this table, implemented `prepareForReuse()` to reset existing cell configuration to "known, good" state.
- Disabled `isAccessibilityElement` of the cell's label, as its value is now read implicitly.
- Set `accessibilityTraits` of `username` cell configuration to reflect that it's a button. This is consistent with other parts of the app (e.g., `MyProfileViewController`) where the value is _not_ edited inline.
- Modified the cell's `accessibilityLabel` to read back contents of the label & the current text field value, as applicable (i.e., for `displayName` & `username` types, but _not_ …

Improvements to signup epilogue accessibility

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift

Ref #11189
This adds the 'Avg Views Per Day' card to the Post Stats view. 
- It shows average views for the last 6 years. 
- If there are more than 6 years, `View more` will be added.
- NOTE: `View more` doesn't do anything just yet. Coming soon.
- Expanding a year shows the average views for each month in the year.
To test:
- Tip: en.blog > Home Page has views for several years.
- Access Post Stats via:
- Insights > Latest Post Summary > View more
- Period > Posts and Pages > row selection
- Period > Posts and Pages > View more > row selection
- Verify 'Avg Views Per Day' appears, and each year expands to show all months in the year.

[Stats Refresh] Post Stats: add Avg Views Per Day

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Blog/DomainCredit/DomainCreditEligibilityChecker.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/DomainCredit/DomainCreditEligibilityTests.swift

Refs. #11467 - subtask - determine whether domain credit can be redeemed
Code changes:
- Updated `domainCredit` feature flag to be on under local development.
- Created helper `DomainCreditEligibilityChecker` to check whether a site is eligible for domain credit, given feature flag is on. A site is eligible if:
- Site is not self-hosted
- Site has `*.wordpress.com` domain
- Site has domain credit (with a paid WP.com plan and not redeemed yet)
- On site dashboard, used `DomainCreditEligibilityChecker` helper method to check for domain credit eligibility and showed domain credit section if eligible.
To test:
- Prerequisites: try having at least one site of the following:
- Self-hosted site
- Site created by others
- Site that already has a custom domain (not `*.wordpress.com`)
- WP.com …

Check domain credit eligibility

---

WordPress/Classes/System/WordPressAppDelegate+Swift.swift

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/11595
To test:
Open login screen, enter your mail address, tap next
Choose enter your password instead
Enter your password and tap next
Application shouldn't crash

Fix crash on login with password

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.xib
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.xib
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Ref #11189
This adds the date selector to the Post Stats view.
- When the date is changed, the Views count, difference, and percentage update on the Overview card.
- Back button goes back by one day.
- Forward button goes forward by one day.
Behavior inherited from the date selector (i.e. this is not new, just reiterating the behavior):
- Forward button is disabled if the next day is beyond the current day.
- Back button is disabled if the next day is beyond the number of days shown on the Overview chart, which is 13.
To test:
- Access Post Stats via:
- Insights > Latest Post Summary > View more
- Period > Posts and Pages > row selection
- Period > Posts and Pages > View more > row selection
- Change the date back and forward.
- Verify it performs as expected, and the overview data …

[Stats Refresh] Post Stats: add date selector

---

WordPress/Classes/ViewRelated/Stats/Charts/Charts+Support.swift
WordPress/Classes/ViewRelated/Stats/Charts/PostChart.swift
WordPress/Classes/ViewRelated/Stats/Charts/Stubs/PostSummaryDataStub.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #11068.
To test:
- View stats for a selected post (1 of 3 ways).
- Observe the chart. There should be no aesthetic differences from #11173, but the chart should now be populated with live data (see below image).

 Transitioned selected post chart to leverage actual data

---

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift

Fixes #7287
1. View a comment notification
2. Background the app (it will save state)
3. Kill the app and relaunch it
4. It should return to showing the same detail view for the same comment
5. Tap "Trash"
6. _Crash_
1. Repeat the steps above and ensure the app no longer crashes
2. Ensure that the Trash and Spam buttons now work in this situation
@aerych you ok with this one? If not I'll find someone else 😀

Fix crash in NotificationDetailsViewController after state restoration

---

Podfile
Podfile.lock

Fixes #11530 
To test:
- Check Loading a revision of a post:
- Open a post with revision history available
- Tap on ... -> History
- Select a revision
- Tap on load on the top right
- Check that revision loads
- Check share of post in Stats work
- Go to site with low activity
- Go to stats
- Select post with no view activity
- Tap on the option to share a post
- Check that it works

Update WordPressKit to point to hot fix WordPressKit 4.0.1

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsSectionFooterView.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/WordPress.xcodeproj/project.pbxproj

Refs. #11467 - subtask - [design polish] Add extra 20pt spacing after footer if the next section has title
* Created `BlogDetailsSectionFooterView` that contains a title label and a spacer view (20px height) in a vertical stack view. Configuration method updates the title text, and whether the spacer view is shown.
* In `BlogDetailsViewController`, replaced default footer title setup with `BlogDetailsSectionFooterView`, and set to show extra spacing when the next section has no-empty title.
To test:
- Turn on Domain Credit UI by returning true in `DomainCreditEligibilityChecker.canRedeemDomainCredit`
- Go to a site
- Turn `QuickStart` on (if not already on, can return true in `BlogDetailsViewController`'s `shouldShowQuickStartChecklist`)
- There should be comfortable spacing (more than …

Update blog details footer section with optional extra spacing between sections

---

.configure
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressUITests/Flows/LoginFlow.swift
WordPress/WordPressUITests/Tests/EditorAztecTests.swift
WordPress/WordPressUITests/Tests/EditorTests.swift
WordPress/WordPressUITests/Tests/MainNavigationTests.swift
WordPress/WordPressUITests/WPUITestCredentials-Template.swift

Fixes #11599 
The UI tests now use the site address login (with username/password) for all tests except LoginTests, which explicitly test different login flows.
To test:
* Pull the latest mobile secrets. (Your `WPUITestCredentials.swift` file will need to include `testWPcomUsername` with the WordPress.com test account's username.)
* Start the simulator with the device set to English.
* Run the tests under `EditorAztecTests`, `EditorTests`, and `MainNavigationTests` in the WordPressUITests target and confirm that they log in successfully using the site address login option.
Note that the test under `EditorTests` may fail after login but there's a fix for that in https://github.com/wordpress-mobile/WordPress-iOS/pull/11315.

Testing: Use site address login for UI tests

---

WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift

Fixes #11546
This rounds the Annual Site Stats averages and displays them as whole numbers.
To test:
- Go to Stats > Insights > Annual Site Stats.
- Verify the Averages no longer have decimal values.

[Stats Refresh] Insights Annual Site Stats: round averages

---

WordPress/Classes/ViewRelated/Me/MeHeaderView.m
WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.xib

Fix layout issues in NoteBlockCommentTableViewCell:
[LayoutConstraints] Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want. 
Try this: 
(1) look at each constraint and try to figure out which you don't expect; 
(2) find the code that added the unwanted constraint or constraints and fix it. 
(
"<NSLayoutConstraint:0x6000018c79d0 WordPress.CircularImageView:0x7fdf7ecac590.height == 32   (active)>",
"<NSLayoutConstraint:0x600001890b40 WordPress.CircularImageView:0x7fdf7ecac590.top == UITableViewCellContentView:0x7fdf7ecac3a0.topMargin   (active)>",
"<NSLayoutConstraint:0x600001890cd0 V:[WordPress.CircularImageView:0x7fdf7ecac590]-(5)-[WordPress.RichTextView:0x7fdf7ecad1e0]   (active)>", …

Fix layout warning in NoteBlockCommentTableViewCell and MeHeaderView.

---

WordPress/Classes/ViewRelated/Stats/StatsViewController.m

Fixes #11126
This enables the existing Today widget for the new Stats.
To test:
---
- Go to Stats. 
- Verify `Today` appears on the navigation bar on the main view (i.e. for Insights and Periods).
---
This verifies the existing Today widget functionality.
- Select `Today`, then `Use this site`.
- Go to the device's notification center.
- You may need to add the WordPress widget via Edit > Add Widgets.
- Verify the Stats widget appears and is using the selected site.

[Stats Refresh] Enable Today widget

---

WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift

Ref #11189
This brings back the Recent Weeks column headers (`Period` and `Views`), which I broke with https://github.com/wordpress-mobile/WordPress-iOS/pull/11593. Woops.
To test:
- Go to Post Stats > Recent Weeks.
- Verify it has column headers once again.

[Stats Refresh] Post Stats: revive Recent Weeks headers

---

WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift

Ref #11189
This abbreviates the Recent Weeks values in Post Stats starting at 10,000.
To test:
- Go to Stats > Period > Posts and Pages.
- Select one with a lot of views.
- Tip: en.blog Home Page is a good one.
- Verify the numbers are abbreviated.
- NOTE: I don't have a site where a _day_ has high enough views to abbreviate, but it uses the same logic.
Before:
After:

[Stats Refresh] Post Stats: abbreviate Recent Weeks values.

---

WordPress/Classes/ViewRelated/Stats/Charts/Charts+AxisFormatters.swift

Fixes #11143.
While working on #11069, I decided to address this first. That issue calls for improvements to formatting of the **vertical** axis, I also resolved an issue with the **horizontal** axis. Namely, single-digit days were preceded with a "0". This is visible in the screenshots for both #11605 & #11616.
To test:
- View stats for the three primary chart types. Verify the horizontal & vertical axes follow the rules noted in the issue.

Chart axis formatting improvements

---

Podfile
Podfile.lock

This PR updates the gutenberg-mobile reference to point to the latest release, v1.4.0. 
The reference is currently pointing to the release/1.4.0 branch on https://github.com/wordpress-mobile/gutenberg-mobile. Relevant PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/951.
When that gets merged to gutenberg-mobile master, I'll update the ref here to point to the v1.4.0 tag on gutenberg-mobile master.
To test:

Update mobile block editor to the latest

---

WordPress/WordPressShareExtension/ShareExtractor.swift

Fixes #11626 
This allows HEIC images in TextBundles to be uploaded as JPGs.
To test:
- Put a HEIC image in a note in Bear
- Share as a TextBundle to the WordPress app
- Publish
- Ensure the post appears with the image
@SergioEstevao do you have time to review this for 12.3? Let me know if not, thanks! 👍

Convert HEIC images to JPG in share extension

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Fixes #n/a
This enables Stats Refresh for internal testers.
To test:
Go to Stats. Verify the new Stats appears.

[Stats Refresh] Enable internal testing

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.swift

Fixes #11618
This addresses the problems noted in #11618 regarding the Post Title displayed in the title card, namely:
- The Post Title is now dark grey
- The font is NotoSerif-Bold
- The spacing between the `Showing stats for` label and the Post Title is now consistent regardless of the post title length.
The problems stemmed from [this](https://github.com/wordpress-mobile/WordPress-iOS/pull/11499) change, where I got...creative, and made the Post Title look like that on Latest Post Summary since it's now clickable.
The fix was simply to remove the `postTitleLabel.attributedText`, thus allowing the original formatting to shine through.
To test:
- Go to Post Stats, and verify the three points noted above.

[Stats Refresh] Post Stats: fix Post Title display issues

---

WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift

Refs. #11592
This is a quick PR which removes 2 warnings in `NotificationDetailsViewController`.
• Build the PR and check the warnings `Value 'onDeletionRequestCallback' was defined but never used;...` won't be displayed.
• To test everything is the same you can follow the same step as before described [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/11592)

[Develop] Fix warnings

---

WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift

Refs #11401 
While re-testing a different issue I noticed that text in the reader detail and reader comments was editable.  It looks like we missed that storyboards and xibs had flagged the WPRichContentView as not editable when refactoring.  This is a quick patch to disable editing again. 
To test:
Confirm the bug by running `develop` and tapping into a reader comment or detail and typing some text. 
Run this patch and repeat the test.  Confirm you do not see a cursor and can not edit text. 
@diegoreymendez could you take a quick peek at this one?

Reader: Disable text editing in reader views.

---

WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift

This PR fix a problem @diegoreymendez reported me on Slack.
The loading view we display with the `NoResultsViewController` is not removed properly.
I reverted the `removeFromView()` method without using the UIViewController helper.
• Open the reader and fetch the posts.
• Or open the posts of a followed site from the reader
• Or go to reader, back out to the screen with streams and tags. Add a new tag. Tap that tag.

Revert removeView method

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift

Fixes #11620.
I found that in `NoticePresenter`, we do watch for keyboard notifications and move the **existing** Notice up when it's shown. However, we don't check if there is a keyboard already present when showing a new Notice. This adds that check.
| ![notice-before gifcask 2019-05-03 13_26_47](https://user-images.githubusercontent.com/198826/57160823-26d57480-6da7-11e9-9308-1231747f5b26.gif)|  ![notice-after](https://user-images.githubusercontent.com/198826/57160827-29d06500-6da7-11e9-93e0-049a269e4ba0.gif) |
This can be tested in, but not limited to, these scenarios: 
1. Navigate to Site → Blog Posts
2. Tap on the search box to trigger the keyboard
3. Go offline. 
The offline Notice should be shown (eventually) on top of the keyboard. If not, …

Fix Notices sometimes shown behind the keyboard

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Fixes #n/a
We've decided Stats Refresh is not yet worthy of internal testing. Disabling that FeatureFlag.
To test:
Run the app. Verify new Stats still shows for development.

[Stats Refresh] Disable internal testing

---

RELEASE-NOTES.txt
WordPress/Classes/Utility/WPError+Swift.swift
WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift

Fixes #11432 
Expected: When unable to load tags the bottom label will show "Couldn't load tags."
To test:
1. Be offline 
2. Go to post from the post list
3. Go to post settings
4. Go to tags
5. see that the label shows  "Couldn't load tags."
BEFORE:
AFTER:

Removing "Tap to retry"

---

WordPress/Classes/System/WordPressAppDelegate+Swift.swift
WordPress/Classes/Utility/BuildInformation/BuildConfiguration.swift
WordPress/Classes/Utility/Sentry/WPCrashLogging.swift

- Simplifies calling crash logging
- Fixes Sentry environment tag
- Simplifies the release name
- Adds the locale as a Sentry tag
- Fixes `logged_in` and `connected_to_dotcom` variables to be correct
**To Test:**
See `2d0c52b8f4f642e5a3e75d53cd163d44-sentry` and note the fixed tags.

Improve Sentry tags

---

WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift

Refs. #11643 
This PR fix the animation issue found in the `ReaderStreamViewController`. 
• Go to reader
• Back out to the screen with streams and tags 
• Add a new tag
• Tap that tag
• You should see the loading animation

[NRV] Loading view is not animated in the reader stream

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+DomainCredit.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController.swift
WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewModel/RegisterDomainDetailsServiceProxy.swift
WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewModel/RegisterDomainDetailsViewModel.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/RegisterDomainDetailsServiceProxyMock.swift
WordPress/WordPressTest/RegisterDomainDetailsViewModelLoadingStateTests.swift
WordPress/WordPressTest/RegisterDomainDetailsViewModelTests.swift

Refs. #11467 - subtask - Integrate the whole domain registration flow
Code changes:
* Integrated domain registration flow from domain credit redemption entry point.
* In `RegisterDomainDetailsViewController`, moved domain registration success callback from before view controller dismissal to dismissal's completion block. This change was made so that after domain registration UI is dismissed, new UI can be presented (otherwise presenting view controller is not visible in view hierarchy when success block is called).
To test:
- Prerequisites: have a site/blog with paid WordPress.com plan (e.g. Blogger plan) and its domain credit still available
- Go to a site dashboard where the site meets conditions in prerequisites, domain credit section should be shown
- Tap on "Register Domain" row
- …

Integrate domain registration flow to domain credit redemption

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.xib
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Ref #11360
This is the first step in fixing #11360. Which is - instead of adding all the data to one `UIStackView`, use `UITableViewCell`s instead. This change fixes Period > Posts and Pages in that manner.
Previously, all the data was stuffed into the stack view on the `TopTotalsCell` card. Which didn't work out so well with a lot of data. 
Now it only uses the `TopTotalsCell` card to show the "header" via the new `DetailSubtitlesHeaderRow`. The stack view is left empty. Instead, a `UITableViewCell` is added to the table for each data row via the new `DetailDataRow`. 
There should be no visual or functional changes, but showing the details view is _a lot_ faster. To note, there is still no loading view, so there may still be a blank view for a couple seconds for longer periods.
Side …

[Stats Refresh] Period Posts and Pages: fix displaying details view

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.xib
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Ref #11360
This changes Period > Search Terms to use `UITableViewCell`s instead of one `UIStackView`.
Previously, all the data was stuffed into the stack view on the `TopTotalsCell` card. Now it only uses the `TopTotalsCell` card to show the "header" via `DetailSubtitlesHeaderRow`. The stack view is left empty. Instead, a `UITableViewCell` is added to the table for each data row via `q`. 
There should be no visual or functional changes, but showing the details view is _a lot_ faster. To note, there is still no loading view, so there may still be a blank view for a couple seconds for longer periods.
To test:
- Go to Stats > Period > Search Terms on a very active site (en.blog Years was particularly painful).
- Verify …

[Stats Refresh] Period Search Terms: fix displaying details view

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Ref #11360
This changes Period > Published to use `UITableViewCell`s instead of one `UIStackView`.
Previously, all the data was stuffed into the stack view on the `TopTotalsCell` card. Now it no longer uses the `TopTotalsCell`. Instead, a `UITableViewCell` is added to the table for each data row via `DetailDataRow`. 
There should be no visual or functional changes, but showing the details view is _a lot_ faster. To note, there is still no loading view, so there may still be a blank view for a couple seconds for longer periods.
To test:
- Go to Stats > Period > Published on a very active site.
- Verify selecting a row opens a web view.

[Stats Refresh] Period Published: fix displaying details view

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Ref #11360
This changes Period > Videos to use `UITableViewCell`s instead of one `UIStackView`.
Previously, all the data was stuffed into the stack view on the `TopTotalsCell` card. Now it only uses the `TopTotalsCell` card to show the header via `DetailSubtitlesHeaderRow`. The stack view is left empty. Instead, a `UITableViewCell` is added to the table for each data row via `DetailDataRow`. 
There should be no visual or functional changes, but showing the details view is a lot faster. To note, there is still no loading view, so there may still be a blank view for a couple seconds for longer periods.
To test:
- Go to Stats > Period > Videos on a very active site.
- Verify selecting a row displays the media.
Update release …

[Stats Refresh] Period Videos: fix displaying details view

---

WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
WordPress/Classes/ViewRelated/Post/PostEditor.swift
WordPress/Classes/ViewRelated/Post/PostEditorState.swift

For the sake of consistency like we do upon failure to upload when the user choose to update after closing the editor.
Fixes #11421
To test:
1. update published post
2. be offline
3. tap "Update" from the top right in the navigation
4. See notice message on failure to upload 
**Before**
**After**
* Also updated strongSelf to self in this PR to fit  > Swift 4.0 
** Will update Release notes before merging 

Updating upload post method failure UI to show notice instead of a HUD

---

Podfile
Podfile.lock
WordPress/Classes/Models/WPAccount+RestApi.swift
WordPress/Classes/Models/WPAccount.m
WordPress/Classes/Services/AccountService.m
WordPress/Classes/Services/CommentService.m
WordPress/Classes/Services/PlanService.swift
WordPress/Classes/Services/ReaderPostService.m
WordPress/Classes/Services/ReaderSiteSearchService.swift
WordPress/Classes/Services/ReaderTopicService+Subscriptions.swift
WordPress/Classes/Services/ReaderTopicService.m
WordPress/Classes/Services/SiteAddressService.swift
WordPress/Classes/Services/SiteAssemblyService.swift
WordPress/Classes/Services/ThemeService.m
WordPress/Classes/Stores/ActivityStore.swift
WordPress/Classes/Stores/PluginStore.swift
WordPress/Classes/Stores/StatsInsightsStore.swift
WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/System/WordPressAppDelegate.swift
WordPress/Classes/Utility/Automated Transfer/AutomatedTransferHelper.swift
WordPress/Classes/Utility/Environment/Environment.swift
WordPress/Classes/Utility/Networking/WordPressComRestApi+Defaults.swift
WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/ViewModel/RegisterDomainDetailsServiceProxy.swift
WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme

Currently, `https://public-api.wordpress.com` and similar urls are hardcoded everywhere that we use WordPressKit and WordPressAuthenticator. This makes it very difficult to mock out network requests for testing purposes without resorting to swizzling or similar hacks. Recent changes to those pods (see the PRs below) allow the URLs to be passed in while defaulting to the correct value.
Here is what I have done:
- Added `wordPressComApiBase` to `Environment`. It defaults to `public-api.wordpress.com` but can be overridden.
- In an extension, I have defined `WordPressComRestApi.defaultApi()` which can be used everywhere that we want an API instance. It uses the value from `Environment.current.wordPressComApiBase`.
- Added support for a `-wpcom-api-base-url` launch argument that overrides the …

Allow WordPress.com API URLs to be overridden with a launch argument

---

RELEASE-NOTES.txt
WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Refs. #11467 
Turned on domain credit feature flag!
To test:
- Prerequisite: have a site/blog with any paid WP.com plan (e.g. Blogger plan), with domain credit still available
- Go to "My Sites"
- Tap on the site in prerequisite
- Should see "Register Domain" row on the top of the site page below site name and URL. For all the other sites not with conditions in prerequisite, should not see this UI

Turn on domain credit feature flag

---

WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Ref #11360
This changes Period > Countries to use `UITableViewCell`s instead of one `UIStackView`.
Previously, all the data was stuffed into the stack view on the `CountriesCell` card. Now it only uses the `CountriesCell` card to show the header via the new `DetailSubtitlesCountriesHeaderRow`. The stack view is left empty. Instead, a `UITableViewCell` is added to the table for each data row via `DetailDataRow`. 
There should be no visual or functional changes, but showing the details view is a lot faster. To note, there is still no loading view, so there may still be a blank view for a couple seconds for longer periods.
To test:
- Go to Stats > Period > Countries on a very active site.
- Verify selecting a row does …

[Stats Refresh] Period Countries: fix displaying details view

---

WordPress/Classes/ViewRelated/Stats/Extensions/UITableViewCell+Stats.swift
WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Ref #11360
This changes the Insights tabbed cards, Comments and Followers, to use `UITableViewCell`s instead of one `UIStackView`.
Previously, all the data was stuffed into the stack view on the `TabbedTotalsCell` card. Now it only uses the `TabbedTotalsCell` card to show the header via the new `DetailSubtitlesTabbedHeaderRow`. The stack view is left empty. Instead, a `UITableViewCell` is added to the table for each data row via `DetailDataRow`. 
There should be no visual or functional changes, but showing the details view is a lot faster. To note, there is still no loading view, so there may still be a blank view for a couple seconds for longer periods.
To test:
---
- Go to Stats > Insights > Comments on a very active site.
- Verify the data appears relatively …

[Stats Refresh] Insights tabbed cards: fix displaying details view

---

WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.xib

Fixes #n/a
This hides the stub map view on the Countries views.
To test:
---
- Go to Stats > Period > Countries.
- Verify the map view no longer appears.
---
- Verify the map view no longer appears.
---

[Stats Refresh] Hide stub Countries map view

---

WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift

Addresses part of #11671. This is the first of 2-3 PRs that fulfill this issue. The first issue ensures that the most recent value is highlighted in the chart by default.
To test:
- Navigate to Stats for a given site and confirm that the chart now reflects live data, and the last bar is selected by default. Please note that this applies only to Post Stats & Period charts (i.e., not the Insights chart on Latest Post Summary).
- Rinse & repeat for a couple of different periods, dimensions, device types & orientations, confirming no regressions in behavior or appearance.
- As noted in #11672, the chart still contains 10 bars, and does not interact with the date bar. This will be addressed in a forthcoming PR.
- I …

Modified Stats charts to highlight the most recent day when applicable

---

WordPress/Classes/ViewRelated/Views/WPRichText/WPTextAttachmentManager.swift

Fixes #10745 
This has been a very stubborn bug.  Starting the other day we began the same crash reported in #10745, #11145, and #11692 [showing up in Sentry](https://sentry.io/organizations/a8c/issues/1024577016/?referrer=github_integration).  Previous patches improved things yet something is still triggering the crash.  
This time around, when I was able to reproduce the crash I noticed via the stack trace and some debugging that `WPTextAttachmentManager layoutAttachmentViews` was calling ` layoutManager.ensureLayout(for: textView.textContainer)` ([here](https://github.com/wordpress-mobile/WordPress-iOS/blob/12.4.0.2/WordPress/Classes/ViewRelated/Views/WPRichText/WPTextAttachmentManager.swift#L82)) even when there were no attachments. Two things about this: 
1) its wasted work when …

Reader: Guard against ensuring layout when there are no attachments.

---

WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Addresses another portion of #11671. Namely, it updates the period header view in response to taps on individual chart bars.
To test:
- Navigate to Stats for a given site, and review the Post Stats & Period Charts presented. 
- Observe that tapping a different bar shifts the applicable period as expected.
- Rinse & repeat for a couple of different periods, dimensions, device types & orientations, confirming no regressions in behavior or appearance.
- _Caveat_ : the period chart still contains 10 bars, as noted in `p1557859877030800-slack-nde-stats-refresh`.

Modified Stats charts to update the period in response to bar selection

---

WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift

As [requested](https://github.com/wordpress-mobile/WordPress-iOS/pull/11672#issuecomment-492601849) by @SylvesterWilmott, this PR sets the number of vertical axis label count to be 5 instead of 6.
To test:
- Review a few charts and confirm that you now see 5 labels on the vertical axis instead of 6.

Modified vertical axis to include just five labels

---

WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift

Fixes an issue where the Post Stats chart presented stale data. 
As discussed via Slack, this issue is most apparent when navigating from _Posts and Pages_ to _Post Stats_ for a given post. Currently the data on the subsequent screen does update unless a pull-to-refresh gesture is performed. The chart, however, was _not_ refreshed in response to pull-to-refresh.
Now the chart updates via pull-to-refresh along with the other screen content.
To test:
- Replicate the scenario above, and confirm that it updates as expected.

Resolved a defect where in limited cases a chart would not refresh with new data

---

Podfile
Podfile.lock

https://github.com/wordpress-mobile/WordPress-iOS/pull/11559 introduced an issue with Aztec loading its image resources (such as the play icon). I fix the Aztec issue in https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1187 and this bumped the version to use the fix here.
To test:
- Open a post with a video.
- See that the video has a play button with the correct icon.

Update Aztec to fix static bundle loading issues

---

WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.xib
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Ref #11360
This changes Insights > Tags and Categories to use `UITableViewCell`s instead of one `UIStackView`.
Previously, all the data was stuffed into the stack view on the `TopTotalsCell` card. Now it only uses the `TopTotalsCell` card to show the header via `DetailSubtitlesHeaderRow`. The stack view is left empty. Instead, a `UITableViewCell` is added to the table for each data row via the new `DetailExpandableDataRow`. 
There should be no visual or functional changes, but showing the details view is faster. To note, there is still no loading view, so there may still be a blank view for a couple seconds for longer periods.
Known Issues:
- When a row is expanded/collapsed, _all_ the rows' arrows update. I don't _think_ this is new as I've seen it before, but it's pretty obvious now. …

[Stats Refresh] Insights Tags & Categories: fix displaying details view

---

WordPress/Classes/Stores/StatsInsightsStore.swift

Fixes #11695
Using a limit of 0 on the followers API returns the default 20 results, and not _all_ results as one would expect. This API also returns a maximum of 100, regardless of the requested number. So this sets the `limit` on the API request to get all 100 results.
To test:
- Go to Stats > Insights > Followers > View more.
- Tip: en.blog has lots of both follower types.
- Verify there are now 100 results displayed for both WordPress.com and Email. (Or, at least verify there's more than 20.)

[Stats Refresh] Insights Followers details: get max results from API

---

WordPress/Classes/Stores/StatsPeriodStore.swift

Refs. #10380
This PR just has a small revert to the previous method to check if there's cached data. This because the new block used to bind the loading view and its implementation don't require any change to that method.
• From My Sites select a site and open its dashboard
• Select Stats to open the Stats section.
• Select one of the tab period tab _Days, Weeks, Months, Years_.
• You should see the loading view
• The loading view should disappear as soon the data is loaded
• The loading view should appear only if there's no data cached
• You can also test it tapping on the stats bar or changing the period date

[Stats Refresh] Revert cache method

---

Podfile
Podfile.lock

This PR updates the gutenberg-mobile reference to point to the latest release, v1.5.0. 
The reference is currently pointing to the release/1.5.0 branch on https://github.com/wordpress-mobile/gutenberg-mobile. Relevant PR: wordpress-mobile/gutenberg-mobile#988.
To test:

Update Gutenberg to the 1.5.0 release branch

---

WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartConfiguration.swift
WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
WordPress/WordPress.xcodeproj/project.pbxproj

Fixes #11671.
To test:
- Navigate to Stats for a given site, and review the Post Stats & Period Charts presented. 
- Observe that navigating with the Period bar updates the chart, as well as the highlighted bar when applicable.
- Rinse & repeat for a couple of different periods, dimensions, device types & orientations, confirming no regressions in behavior or appearance.
_Period Chart (iPhone) :_
_Post Stats Chart (iPhone) :_
_Post Stats Chart (iPad)  :_

Completed transition to coordinate period bar and chart interaction

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Fixes #11708 
This PR fixed the problem we had about displaying the correct Posts Stats data. Post Stats initially shows stats for the Latest Post Summary post. Only after refreshing the view does it show the correct data.
The _Period Store_ with more than one _Period Query_ of the same type **_postStats(postID: Int_)** executes only the first active query of that type when _func queriesChanged()_ is called.
Use Dictionaries over single values. This allows to store _StatsPostDetails_ keyed by post id (fix a possible override action) and set the fetching status per post id (fix the problem of skipping multiple period queries of the same type).
• Go to Stats > Insights -> Latest Post Summary (accessed via Insights > LPS > View more)
• Go to Stats > Period > Posts and Pages > select a post …

[Stats Refresh] Posts Stats - Display correct data 

---

Podfile
Podfile.lock

Update the gutenberg version after the 1.5.1 hotifx: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1002
The only change is https://github.com/WordPress/gutenberg/pull/15734/commits/7631bb187d43a84aea904f19fc346cb87bee7a21 which should not affect iOS

Update gutenberg to 1.5.1

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Ref #11360
This changes Period > Clicks to use `UITableViewCell`s instead of one `UIStackView`.
Previously, all the data was stuffed into the stack view on the `TopTotalsCell` card. Now it only uses the `TopTotalsCell` card to show the header via `DetailSubtitlesHeaderRow`. The stack view is left empty. Instead, a `UITableViewCell` is added to the table for each data row via `DetailExpandableDataRow`. 
There should be no visual or functional changes, but showing the details view is faster. To note, there is still no loading view, so there may still be a blank view for a couple seconds for longer periods.
To test:
---
- Go to Stats > Period > Clicks on a very active site.
- Tip: en.blog is a good one. …

[Stats Refresh] Period Clicks: fix displaying details view

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Ref #11360
This changes Period > Authors to use `UITableViewCell`s instead of one `UIStackView`.
Previously, all the data was stuffed into the stack view on the `TopTotalsCell` card. Now it only uses the `TopTotalsCell` card to show the header via `DetailSubtitlesHeaderRow`. The stack view is left empty. Instead, a `UITableViewCell` is added to the table for each data row via:
- `DetailExpandableRow` - for parent rows
- `DetailExpandableChildRow` - for child rows
There should be no visual or functional changes, but showing the details view is faster. To note, there is still no loading view, so there may still be a blank view for a couple seconds for longer periods.
To test:
---
- Go to Stats > Period > Authors on a very active site.
- Verify the …

[Stats Refresh] Period Authors: fix displaying details view

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Ref #11360
This changes Post Stats  _Months and Years_ and _Avg Views Per Day_ to use `UITableViewCell`s instead of one `UIStackView`.
Previously, all the data was stuffed into the stack view on the `TopTotalsCell` card. Now it only uses the `TopTotalsCell` card to show the header via `DetailSubtitlesHeaderRow`. The stack view is left empty. Instead, a `UITableViewCell` is added to the table for each data row via:
- `DetailExpandableRow` - for parent rows
- `DetailExpandableChildRow` - for child rows
There should be no visual or functional changes, but showing the details view is faster. To note, there is still no loading view, so there may still be a blank view for a couple seconds for longer periods.
To test:
---
- For a site older than 6 years, Go to Stats > …

[Stats Refresh] Post Stats: fix displaying details view

---

Podfile.lock
WordPress/Classes/Services/JetpackService.swift
WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift

This is a follow up to https://github.com/wordpress-mobile/WordPress-iOS/pull/11655 with a few fixes:
- Updates WPAuthenticator to get the changes from https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/96.
- Fix a typo where the wrong URL was passed through to WPAuthenticator.
- Use `WordPressComRestApi.defaultApi()` in one place I missed.
To test:
- Run through login and smoke test the app.

Fix some WordPress.com API injection issues

---

WordPress/Classes/ViewRelated/Post/PostEditorState.swift

This PR changes the stat sent when the Publish Now button is used on the editor. Instead of using the  `editorQuickPublishedPos`t event we now consolidate all publish actions on the editor with `editorPublishedPost`.
To test:
- Start the open
- Add some content
- Save the post has draft
- Exit editor
- Open the post again
- Tap on publish now
- Check if event sent is `editorPublishedPost`. I checked this by putting a breakpoint on `PostEditor+Publish.swift` on the `publishPost` method

Use editor published post event, instead of quick published post.

---

WordPress/Classes/Stores/StatsInsightsStore.swift
WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Fixes #11166 
Refs. #10840
This PR adds the loading view on any detail view controller, `SiteStatsDetailTableViewController` and `PostStatsTableViewController ` accessed by tapping on _View More_ from the Insights and Periods overviews.
• From My Sites select a site and open its dashboard
• Select Stats to open the Stats section.
• Select one of the tab _Insights_, _Days_, _Weeks_, _Months_, _Years_.
• Scrolling the selected tab overview tap on any _View More_ to open the detail
• You should see the loading view

[Stats Refresh] Stats Detail lists / Post Stats loading view

---

WordPress/Classes/ViewRelated/Site Creation/Shared/TableViewOffsetCoordinator.swift
WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift
WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift

This PR addresses the issue reported in #11702 that makes it impossible for the search field in the Domain Selection screen to resign first responder.  It also unifies the search logic a bit.
Fixes #11702 
There are more issues when going back and re-opening this screen that can cause the layout to look a bit broken.  From my research those issues are not related to the changes in this PR, and I'm planning to address them incrementally after this fix.
1. ...Go through the site creation flow
2. Go to step 3 of 3, and tap on the search field.
4. Go back one step
5. Press "Next"
Make sure the search field doesn't have first responder, and make sure the title and subtitle aren't hidden.

Site Creation: first responder can now be resigned in the Domain Selection screen.

---

WordPress/Classes/Services/PostService.m

When a post fails to save, it status was set to `AbstractPostRemoteStatusFailed` which should have
made `post.hasNeverAttemptedToUpload` return true hence return false in `shouldRemovePostOnDismiss` in `discardChanges()`.
https://github.com/wordpress-mobile/WordPress-iOS/blob/d05cb734d50c253e0bf67fc8415dbc90f7089eff/WordPress/Classes/ViewRelated/Post/PostEditor%2BPublish.swift#L239
The problem was that the remoteStatus property was not really being saved. In order to save those changes we are merging the revisions back into the base post.
Fixes #11435
To test:
**upload failed post with no changes**
1.Be offline
2.Create a new draft
3.Save draft (either through options menu or by exiting the editor and choosing "save draft")
4.rerun xcode
5.See the post with "failed upload" status
6.tap on …

Fix discard draft loosing all changes

---

WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
WordPress/Classes/ViewRelated/Post/PostEditor.swift

The error message we're showing depends on the action. Previously we were sending the primary action hence the label was wrong.
We are now passing the action to uploadFailureNotice
Fixes #11732 
To test:
1. Be offline
2. Start new post
3. Go to the option menu and choose "Save As Draft"
4. See the notice message says "Error Occurred while saving"
Before:
After:

Fixing error message when saving draft while offline

---

WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift

Ref #11360, #11080
This changes Period > Referrers to use `UITableViewCell`s instead of one `UIStackView`.
Previously, all the data was stuffed into the stack view on the `TopTotalsCell` card. Now it only uses the `TopTotalsCell` card to show the header via `DetailSubtitlesHeaderRow`. The stack view is left empty. Instead, a `UITableViewCell` is added to the table for each data row via:
- `DetailExpandableRow` - for parent rows
- `DetailExpandableChildRow` - for child rows
And, because Referrers `Search Engines` rows can be expanded twice, "grandchild" rows are now supported.
This also addresses two other issues:
From #11080 - When no icon is available then show `gridicons-globe`.
From https://github.com/wordpress-mobile/WordPress-iOS/pull/11674#issuecomment-491386360 - fix …

[Stats Refresh] Period Referrers: fix displaying details view

---

WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift

Fixes #11744
To test:
- On a slow network, go to either Period _Referrers_ or Insights _Publicize_.
- These are the only two that are downloaded and aren't user icons.
- Until the icon is loaded, verify a grey box is shown.
- Once the icon is loaded, verify the icon appears.

[Stats Refresh] placeholder while loading icon

---

WordPress/Classes/ViewRelated/Stats/Extensions/UITableViewCell+Stats.swift

Fixes #11746
When I first added support for details views, in `addRows` I added a check for `limitRowsDisplayed` before adding a `StatsNoDataRow` (since details doesn't limit rows). Clearly I didn't realize I broke `SimpleTotalsCell`s, which don't limit rows either. However, since details rows are added differently now, I've simply removed that check.
To test:
- On a site with very little/no data, go to Insights.
- Verify the following stats show `No data yet` instead of just being blank when there is no data.
- Today's Stats
- All Time Stats
- Most Popular Time
- Total Followers
- Publicize

[Stats Refresh] empty "simple" stat cards now show `No data yet` label

---

RELEASE-NOTES.txt
WordPress/WordPressShareExtension/AppExtensionsService.swift
WordPress/WordPressShareExtension/ShareExtractor.swift
WordPress/WordPressShareExtension/SharedCoreDataStack.swift

Fixes #9118 
Replaces #11581
This fixes the problems with the share extension creating posts with broken images.
- Share two images to the share extension, and publish
- Ensure both images are visible in the post
- Share a TextBundle that includes one or two images (from Bear, likely)
- Ensure the images work there, too
My first attempt to solve this, #11581, changed `AppExtensionsService.swift` to solve the possibility that the server had altered the name of the file, returning a filename that wouldn't match to our local file. However, I had failed to notice that `SharedCoreDataStack.swift` has the same issues, and also lacked the accounting for case changes that `AppExtensionsService` already had.
The app extension uploads images in a background session. It returns in one of two places: …

Fix broken images in posts created by the share extensions

---

WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift

When tapping an overlay and dismissing the action sheet by touching the screen out of the image a gesture recognizer is fired which in turn
calls the deselect method from the editor so the attachment gets removed.
I added the method to reprocess the media attachment upon dismissal so in case there is still an error, the attachment will show.
Fixes #11428 
To test:
1. Create new post while offline
2. Select media to upload
3. Tap the media to activate the action sheet
4. Tap outside of the action sheet
5. Return or add characters to the editing space
6. Scroll up and down in the view -- see that the overlay is still displayed 
**Before**
**After**

Keeping image overlay on Action sheet dismissal

---

WordPress/Classes/ViewRelated/Stats/Insights/SimpleTotalsCell.xib
WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.xib
WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.xib
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift

Fixes #n/a
This adds some missing separator lines. Specifically:
- Insights _Comments_ and _Followers_ cards - top line on card
- Insights _Publicize_ card - bottom line on card
- Detail views for all non-expandable stats - bottom line on last row
- Insights _Countries_ card - bottom line on card
- Period _Published_ details - top line on first row
cc @SylvesterWilmott - so you know which ones I fixed.
To test:
- Go to the Stats listed above. Verify the lines appear as expected.

[Stats Refresh] Add missing separator lines

---

WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift

Fixes #11755
This reinstates the correct period displayed on the date bar. It broke with [this change](https://github.com/wordpress-mobile/WordPress-iOS/commit/f11a8e4c5f664efb34b23d32c0dab0e66dd5f2e0#diff-11eff2d79209874b44eb956bedeb5ecf), which I believe was just a copy/paste error. I've checked out the charts, and they look fine. But please give them a look to be sure.
To test:
- Go to Stats.
- Select Day, Week, Month, Year.
- Verify the period displayed on the date bar once again reflects the period selected.

[Stats Refresh] Fix period displayed on date bar

---

Podfile
Podfile.lock
WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/ViewMoreRow.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift

Fixes #11730.
To test:
- Checkout the branch and confirm that existing tests pass, including those in `WPAnalyticsTrackerAutomatticTracksTests`.
- Review the code changes, and confirm that everything looks square.
- As a user, launch the app on-device or in the Simulator, logged in with _Collect Information_ toggle enabled in _Me : App Settings : Privacy Settings_.
- Step through the Stats functionality, taking note that these events are logged* as expected.
It's probably easiest to validate events in one of the following two ways:
1. The event and properties are logged to the console [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m#L72-L76).
1. You can search for the events in post via _Tracks …

Implement Stats Refresh analytics events

---

Podfile
Podfile.lock
WordPress/Classes/Stores/StatsPeriodStore.swift

This is the WPiOS counterpoint to https://github.com/wordpress-mobile/WordPressKit-iOS/pull/159 — which was brought up in Slack a while ago.
It also should speed up the performance of fetching Summaries a bit, but a more comprehensive solution is coming soon.

Change the fetching of summary data to fetch data for 14 periods at once

---

WordPress/Classes/Stores/StatsInsightsStore.swift

Fixes #11763
So, the `limit` parameter bit us again. An unspecified limit defaults to 10. `limit: 0` doesn't return all. `StatsPostingStreakInsight.queryProperties` uses 5000, so I set the `limit` to 5000. And voila, we have a year's worth of data once again.
To test:
- Go to Stats > Insights > Posting Activity for an active site.
- Tip: Hogwarts is a good one.
- Select `View more`. 
- The Insights card and details view use the same data, so verifying details should do it.
- Compare the data with Calypso (https://wordpress.com/stats/insights/<site_url>).
Calypso for Hogwarts:
Insights card:
Details:

[Stats Refresh] correct Posting Activity data

---

WordPress/Classes/Stores/StatsInsightsStore.swift

Fixes #11747
For Insights _Posting Activity_, always show the months grids, even if there is no data.
To test:
- On a site with no Posting Activity, go to Insights _Posting Activity_.
- Verify the 3 months appear.
- Verify all months appear.

[Stats Refresh] always display Posting Activity months

---

WordPress/Classes/Utility/ContentCoordinator.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+Stats.swift
WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
WordPress/Classes/ViewRelated/Post/PostListViewController.swift
WordPress/Classes/ViewRelated/Stats/Helpers/SiteStatsInformation.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTodayWidget/TodayViewController.swift
WordPressComStatsiOS/WordPressComStatsiOS/Services/WPStatsService.h
WordPressComStatsiOS/WordPressComStatsiOS/Services/WPStatsService.m
WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsViewController.m
WordPressComStatsiOS/WordPressComStatsiOSTests/WPStatsServiceTests.m

This extends the changes made in https://github.com/wordpress-mobile/WordPress-iOS/pull/11655 to `WPStatsService`. Once this change is made it will be possible to point the stats service at a different URL. We'll use this for mocking purposes.
To test:
- Smoke test stats to make sure things look as they should.

Use Environment.current.wordPressComApiBase when initializing WPStatsService

---

WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift

This PR addresses two issues:
1. It addresses a regression introduced via #11757, where the period bar was not visible on the Period screens. Regrettably, the implementation of the `UIScrollViewDelegate` to capture the "scroll to bottom" analytics event was hijacking `UITableViewDelegate` (which now conforms to `UIScrollViewDelegate`). Restoring the tracked event will be tackled in a subsequent PR.
1. Now that #11758 has been merged, this PR removes the workaround introduced via #11719 to allow the period bar and chart navigation to remain in sync for a longer horizon (i.e., 14 periods).
To test:
- Navigate to Stats for a given site, and review the Period Charts presented. 
- Observe that navigating with the Period bar updates the …

Restored period bar visibility and set to use default period count

---

WordPress/Classes/Utility/ImmuTable.swift
WordPress/Classes/ViewRelated/Stats/Helpers/BottomScrollAnalyticsTracker.swift
WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/ImmuTableTest.swift

Fixes an issue identified in #11769. Namely, the bottom-scroll event analytics tracking was temporarily removed. This PR is based off of that PR branch, and contains three net new commits that restore analytics logging.
To test:
- Check out the branch, confirm that it builds & existing tests pass.
- Review the code changes, and confirm that everything looks okay.
- As a user, launch the app on-device or in the Simulator, logged in with _Collect Information_ toggle enabled in _Me : App Settings : Privacy Settings_.
- Select a site and navigate to _Stats_.
- On both _Insights_ & a _Period_ screen (e.g., Days, Weeks, Months, Years), scroll to the bottom and observe the console.
- You should see a Tracks event logged : `stats_scrolled_to_bottom`.

 Restored bottom-scroll analytics tracking for Stats screens

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m

Fixes #11772 
This PR fixes a problem with the iPad and the first section/row selected. Because _Quick Start_ and _Domain Credit_ are dynamic sections, we should never keep selected these rows.
This test requires a site with a plan purchased
- Open the _My Sites_ section and select a site with the _Register Domain_ prompt.
- Force-close the app (completely close it, don’t just background it).
- Open the app again and now the _Register Domain_ cell is not selected.
- Tap on _Register Domain_ to to open it
Do the same test with a site with _Quick Start_ enabled

[Domain Credit] Fix "Register Domain" cell wrongly pre-selected

---

WordPress/Classes/ViewRelated/Blog/DomainCredit/DomainCreditEligibilityChecker.swift

Fixes #11797
This PR enables the domain credit section for all the sites with a domain credit. The problem was in the `func canRedeemDomainCredit(blog: Blog) -> Bool` where we constrained the feature only for `wordpress.com` domains.
Hey @jklausa would you mind having a look?
As @designsimply suggested:
• On the web, setup a new site using a free .blog domain such as `thetimeywimeykindof.family.blog`.
• On the web, add a Blogger Plan for that site.
• From the app, go to My Sites and look for the _Register Domain_ option.

[Domain Credit] Remove wp.com constrain

---

WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift

Fixes #11792 
To test:
- Go to Insights Most Popular Time.
- Verify the icons color is now grey (matching other gridicons color)

[Stats Refresh] Insights Most Popular Time: change icon color to grey

---

WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.xib

Fixes #11793 
To test:
- Go to Insights _All Time Stats_.
- Verify _Best Views Ever_ subtitle (i.e. the date) is 15pt.

[Stats Refresh] Insights All Time Stats: correct Best Views Ever subtitle font size

---

WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityViewController.swift

Fixes #11796 
To test:
NOTE: The problem didn't happen on every device, but I was able to repro it on the iPhone Xs simulator.
- Go to Insights _Posting Activity_ and select `View more`.
- Rotate the device to landscape and back.
- Verify the months layout properly.

[Stats Refresh] Insights Posting Activity detail: correct layout on rotation

---

WordPress/Classes/ViewRelated/Themes/ThemeBrowserCell.swift

Fixes #11721
To test:
- Run the app on an iPad.
- Go to Themes.
- Tap the `...` button on a theme.
- Verify the menu appears aligned with the button tapped.
- Verify it works in both landscape and portrait.

Theme options picker: align with button

---

WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.xib
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.xib

Fixes #11798
The problem stemmed from toggling two top constraints on the row stack view depending on if the subtitles are shown or not. This wasn't working very well when the cells were reused. Now there is only one top constraint, and is modified per subtitle visibility.
To test:
---
- On a site with no data, go to Stats.
- On Insights and Periods, verify when `No data...` is displayed there is no longer extra space above the label. Example:
---
- Switch to a site with data, and go to Stats.
- For that stats that previously showed `No data...` verify the subtitles are shown correctly. Example:

[Stats Refresh] remove extra space when 'No data' shown

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m

Fixes #11819 
This fixes a crash I introduced in _12.4_. It happened when the `restorableSelectedIndexPath` decoded by `- (void)decodeRestorableStateWithCoder:(NSCoder *)coder` is out of bounds with the `tableSections`.
To fix that I check in the section index is out of bound or not.
I wasn't able to reproduce it, so I forced it setting different values to the `restorableSelectedIndexPath` property when `- (void)decodeRestorableStateWithCoder:(NSCoder *)coder` is called.
Like this:
```
- (void)decodeRestorableStateWithCoder:(NSCoder *)coder
{
//    NSIndexPath *indexPath = [coder decodeObjectForKey:WPBlogDetailsSelectedIndexPathKey];
//    if (indexPath) {
self.restorableSelectedIndexPath = [NSIndexPath indexPathForRow:0 inSection:999999];
//    }
[super …
```

[Crash] NSRangeException in BlogDetailsViewController

---

RELEASE-NOTES.txt
WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift

Fixes #11716 (original issue #5884)
This changes the Account Settings > Primary Site to display the domain (instead of the web address) if the site has no title. I checked Calpyso to ensure I got the right one this time, and it does appear to show the domain.
cc @designsimply 
To test:
---
- Go to Account Settings > Primary Site.
- Select a site with no title, or remove the primary site title via Site Settings > Site Title.
- Verify the domain is displayed.
---
- Go to Account Settings > Primary Site.
- Select a site with a title, or set the primary site title via Site Settings > Site Title.
- Verify the title is displayed.
---

Account Settings Primary Site: show domain if site has no title

---

RELEASE-NOTES.txt
WordPress/WordPressDraftActionExtension/Info-Alpha.plist
WordPress/WordPressDraftActionExtension/Info-Internal.plist
WordPress/WordPressDraftActionExtension/Info.plist
WordPress/WordPressShareExtension/Info-Alpha.plist
WordPress/WordPressShareExtension/Info-Internal.plist
WordPress/WordPressShareExtension/Info.plist

Refs #9335
Improvements in #11626 and #11740 should now allow a large number of images to be shared without any memory issues or broken image URLs. I made an [example post](https://natesnotesandnovels.wordpress.com/2019/05/20/lots-oimages/) with fifteen images.
To test:
- Build, and share more than three images with the share extension(s)
- Publish
- Ensure the post has all the images

Share Extension: Remove the restriction on number of images shared

---

Podfile
Podfile.lock
RELEASE-NOTES.txt

This PR updates the gutenberg-mobile reference to point to the latest release, v1.6.0.
The reference is currently pointing to the release/1.6.0 branch on https://github.com/wordpress-mobile/gutenberg-mobile. Relevant PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1036.
To test:

Update Gutenberg to 1.6.0

---

WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.xib
WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift

Fixes #11800 
In order for the child row to appear indented, the icon image view is actually shown, just with no image. The side effect of this was the child row height was affected by the image view height.
To avoid this, if there is no image, the image height is now set to 1. The width is still the parent image width.
To note, this only fixes the overview card. I've created #11824 to fix the detail view.
To test:
- Go to Stats > Period > Authors.
- Expand an Author.
- Verify the child row height is 44.

[Stats Refresh] Period Authors: fix expanded row height

---

WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift

Fixes #11815 
This PR fixes in part #11815 (part has been fixed in #11805). Browsing back from a Stats Detail Screen changes the data in the current Stats overview. This is caused by the a receipt being deallocated, which triggers the query update function emitting the change trough all the observers. Having a shared instance of the stats stores makes the overview updated even if is not necessary.
I decided then to remove the view model listeners when is not necessary, and add those again when it's required. This avoids the overview being reloaded when it's not necessary.
• Select a Site with a big bunch of data, to have the _View More_ row in Insights and Periods
• Select Stats and test this behaviour with Insights and any Period
• Tap on a _View More_ row to display a Stats detail
• …

[Stats Refresh] Avoid reload stats overview when browsing back from a stats detail

---

RELEASE-NOTES.txt
WordPress/Classes/Extensions/UIAlertController+Helpers.swift
WordPress/Classes/Extensions/UIViewController+Notice.swift
WordPress/Classes/ViewRelated/Comments/CommentViewController.m
WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m

This PR only updates the experience of messaging the failure in uploading an edit to a comment or a reply to a comment and does not deal with the reported failure to upload the comment completely.
Instead of showing an alert with confusing options to try again (which didn't do anything) or to cancel (which dismissed the alert)
We are showing a snack bar to fit the behavior of this type of failure in other parts of the app. w
Hopefully the failed upload of the comment/reply can be automatically triggered in the future with the upcoming addition of the upload manager
Fixes #11307 
To test:
1. Turn on Network Link Conditioner with 100% loss
2. Go to comments
3. reply to a comment
* See the snack bar with a message saying "There has been an unexpected error while sending your reply"
Before: …

Updated reply and edit comment messaging experience

---

WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift

Fixes #n/a
This enables Stats Refresh for everyone.
To note, I won't merge this until we're 100% sure we're ready. But at least we'll have it ready to go.
To test:
Go to Stats. Verify the new Stats appears.

[Stats Refresh] Enable Stats Refresh for all.

---

WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
WordPress/Classes/ViewRelated/Menus/MenuItemEditingViewController.m

Fixes a couple of warnings about calling deprecated API : `automaticallyAdjustsScrollViewInsets`. 
In `MenuItemEditingViewController.m` the call is simply removed as it doesn't appear its needed.
In `MediaLibraryViewController.swift` the call is replaced with the recommended substitute.
To test:
Note how the UI looks, paying particular attention to the scroll views, on the following two screens:
- My Sites > Site > Menus > Select a Menu > Tap to Edit one of the menu's items. 
- My Sites > Site > Media
Check on an iPad and on an iPhone.  Bonus for also checking on the XS Max.
Apply the patch and check the screens again.  There should be no noticeable difference.
Note that there is some preexisting unrelated UI wonkiness with Menus. :(  I'll open issues for these when I get time.
Update …

Fixes warnings regarding deprecated api.

---

WordPress/Classes/Services/MediaCoordinator.swift
WordPress/Classes/System/WordPress-Bridging-Header.h
WordPress/Classes/Utility/CoreDataHelper.swift
WordPress/Classes/Utility/WPException.h
WordPress/Classes/Utility/WPException.m
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/CoreDataHelperTests.swift

Fixes #11609 
This PR changes the MediaCoordinator to use a safeManagedObjectID function to retrieval media objects referenced in HTML.
This avoid that malformed CoreData URI crashing Aztec when opening posts.
To test:
- Create a new post using Aztec
- Switch to HTML mode
- Copy/Paste the HTML referred in #11609 
- Switch to visual mode
- Make sure the app doesn't crash.

Use safeManagedObjectID to retrieval media objects referenced in HTML.

---

WordPress/Classes/Stores/StatsPeriodStore.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift

Ref #11841
Since Overview Likes takes longer to load than the other summary data, showing 0 while loading is misleading. This change shows dashes for Likes until the fetching is complete.
To test:
- On a very active site, go to Stats > Period.
- On the overview chart, verify the Likes value is dashes until the actual Likes value is fetched.
- If the query times out (which it frequently does for longer periods), the dashes will remain as an indicator Likes was not obtained.

[Stats Refresh] Period Overview chart: show dashes for Likes value

---

WordPress/Classes/Services/MediaCoordinator.swift
WordPress/Classes/Services/MediaService.h
WordPress/Classes/Services/MediaService.m
WordPress/Classes/Services/PostCoordinator.swift
WordPress/Classes/Services/PostService.h
WordPress/Classes/Services/PostService.m
WordPress/Classes/Uploads/UploadsManager.swift

Fixes #11785 
Fixes #11784 
Implements the Uploader protocol in both coordinator, and wires it so that it's triggered when the App is opened, when it comes to foreground, and when `Reachability` detects there's a connection.
Reachability isn't working very well, but from my investigation this is not related to my PR.  Reachability is simply failing to call the closures it should call.
I'll need to [investigate this separately](https://github.com/wordpress-mobile/WordPress-iOS/issues/11840#issuecomment-498194915), as it goes beyond the scope of this specific PR.
1. Create a post with media while offline.
2. Put the app in the background.
3. Go back online.
4. Bring the app back to foreground.
5. Make sure the post is uploaded.
1. Create a post with media while …

Implements Uploader protocol in MediaCoordinator and PostCoordinator.

---

WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift

Fixes #11853
To test:
- On a site with a lot of Videos, go to Stats > Period > Videos.
- Tip: en.blog is a good one.
- Select a video.
- Verify the media details view appears.
- Select a video.
- Verify the media details view appears.

[Stats Refresh] Period Videos: fix video selection

---

WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m

Fixes #n/a
Previously, if the device was on WiFi, `BlogDetailsViewController` would pre-load the old Insights. This change disables that for Stats Refresh to avoid an unnecessary (and expensive) network call. I'll open a separate issue to replace that behavior.
To test:
- Launch the app.
- Verify `BlogDetails: preloading stats.` does _not_ appear in the logs.

[Stats Refresh] disable preloading Stats

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift

Fixes #11869 
To test:
- Go to Stats > Insights > Followers > View more.
- To note, the issue didn't happen for every site, but I was able to repro it 100% of the time on mobile.blog.
- Verify the total matches that on the Insights card.

[Stats Refresh] Follower detail count: show correct value

---

WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift

Fixes #11688 
Changes the Quick Start notices to have a white highlight
To test:
- Start a Quick Start tour (let me know if you need help with this)
- Ensure the notices use white as a highlight color

Change quick start highlight color to white

---

WordPress/Classes/Utility/ContentCoordinator.swift

Fixes #11870 
To test:
- Follow repro steps on #11870.
- Verify the new stats Followers is displayed. This should look exactly like Insights > Followers > View more.
- Note: I've created issue #11869 (Follower details sometimes shows 0 total) as that is unrelated to this change.

[Stats Refresh] Show new Follower stats from Follower notification.

---

Podfile
Podfile.lock
RELEASE-NOTES.txt

This PR makes video/quote/more blocks available for public usage.
gutenberg-mobile PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/1094
To test:
`rake dependencies`
make sure metro is off
open a post and verify that you can add video/quote/more blocks

[Gutenberg]Make video/quote/more blocks public

---

WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift

Ref #11713
Due to the issue described in #11713 , this disables the `View more` option for Insights _Comments_.
To test:
- On a site with a lot of Comments, go to Stats > Insights > Comments.
- en.blog is a good one.
- Verify 6 rows are displayed for _Authors_ and _Posts and Pages_.
- Verify `View more` is _not_ displayed.
cc @SylvesterWilmott 

[Stats Refresh] Insights Comments: don't show 'view more' option

---

WordPress/Classes/ViewRelated/Stats/Charts/Charts+AxisFormatters.swift
WordPress/Classes/ViewRelated/Stats/Charts/Charts+LargeValueFormatter.swift
WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift

Fixes #11859. This PR updates the y axis formatting of the stats charts to better match Android's behaviour. Main changes:
* Updating the logic of the `LargeValueFormatter` to match Android's implementation. On Android this is bundled with the library, but on iOS there's a Swift version with the library's demo app which has different behaviour. We'll now only show a decimal point for values between 1000 and 100,000.
* Rounding the y axis values to produce a nicer set of rounded values on the Y axis. e.g. if the highest value is 96, we would previously have had axis lines at 24, 48, 72, 96. Now they'll be 25, 50, 75, 100. Again, this matches Android.
* Charts with no data now have a default y axis of 0, 1, 2, 3, 4. Previously we were showing 0, 0.2, 0.5, 0.8, 1.0.
**To test:**
* Build and …

[Stats Refresh] Update Y axis chart formatting to match Android's behaviour

---

Podfile
Podfile.lock
WordPress/WordPress.xcodeproj/project.pbxproj
WordPress/WordPressTest/WordPressUIBundleTests.swift

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/11848
This fixes the image loading crash by updating WordPressUI (see https://github.com/wordpress-mobile/WordPressUI-iOS/pull/37) and adding regression tests to ensure it can't happen again.
To test:
- See that the tests pass.
- A smoke test works as expected without crashing.

Bundle patch

---

WordPress/Classes/ViewRelated/Stats/Charts/Charts+AxisFormatters.swift
WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift

Fixes #11880. This PR updates the x axis label formatting to match android. The new formats are as follows:
Latest Post: MMM d, yyyy
Day: MMM d, yyyy
Week: MMM d – MMM d
Month: MMM, yyyy
Year: yyyy
These should now match Android:
Note that while the formatting matches, the actual date ranges seem to be slightly different on Android, but I think this is an unrelated issue that we should check into.
**To test:**
* Verify that dates are formatted as expected!

[Stats Refresh] Improve x-axis label formatting

---

Podfile
Podfile.lock

This PR is a Gutenberg version bump to pair with WPAndroid https://github.com/wordpress-mobile/WordPress-Android/pull/10027
Gutenberg-mobile side PR:  https://github.com/wordpress-mobile/gutenberg-mobile/pull/1098
To test:
cc @loremattei

Update gutenberg to v1.6.1

---

WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift

Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/11882#issuecomment-500704850
The problem is that sometimes the date bar is created _after_ the overview chart. This resulted in the chart delegate being `nil` because the delegate was the date bar.
This changes the chart delegate to be `PostStatsTableViewController`. Which then inform the date bar when a chart bar has been selected.
To test:
- Access Post Stats via both:
- Insights > Latest Post Summary > View more.
- Period > Post and Pages > row selection.
- Verify selecting a chart bar updates the data.

[Stats Refresh] change Post Stats chart delegate
